### ISSUE TITLE
service.ranking can be removed from com.ibm.ws.persistence defaultInstances.xml

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/open-liberty#10006]
Presently there is a warning message that is suppressed when activating the com.ibm.ws.persistence bundle.  It is complaining about the service.ranking attribute in defautlInstances.xml being the wrong type.  It expects Integer and it is String.  The reason for this is that the metatype.xml doesn't declare the internal attribute of service.ranking at all so it doesn't get configured with an Integer type.  This is what is done for other metatypes that use the service.ranking attribute.  I don't think there is any use of service.ranking for the dataStore config so I believe it can be removed from defaultInstances.xml.  The other option is to add the internal attribute to the metatype.xml file.  I talked with Joe Grassel and he suggested he would go with the former option of removing the attribute from defaultInstances.xml, but will leave that to him to finalize on.

**Comment by jgrassel** [comment]
Merged #10009
