### ISSUE TITLE
GA BLOG: #9457 Support OpenShift OAuth server for Authentication and Authorization

### ISSUE THREAD

**Issue by brutif** [OpenLiberty/open-liberty#10047]
a. Which Liberty feature does it relate to?

   i. Human-readable name (eg WebSockets feature)

```
SocialLogin-1.0
```

   ii. Feature name (eg websockets-1.0)

```
SocialLogin-1.0
```

   iii. Is this a new feature or is it an update to an existing feature for this release?

```
Pre-existing feature, new configuration elements and capabilities
```

b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc

```
Application Developers and appserver administrators
```

c. Write a sentence or few that introduces it to someone new to the general technology/concept.

``` 
The SocialLogin-1.0 feature allows applications to be secured by using popular social media OAuth and OpenIDConnect providers, and supports configuration for additional  providers.
```

d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)

  The Liberty SocialLogin-1.0 feature can now be configured to use Open Shift's built in OAuth server and OAuth Proxy sidecar as authentication providers.

  The first is a standard OAuth Authorization Code flow, where a web browser accessing an app running in Liberty will be redirected to the OpenShift OAuth server to authenticate.

  The second is accepting an inbound token from the OpenShift OAuth Proxy sidecar or obtained from an Openshift API call. This approach requires less cluster-specific configuration.

  Most users of this will run Liberty in a pod, however in the Authorization Code flow, Liberty can run outside the OpenShift cluster.

  In either mode, an optional JWT can be created for propagation to downstream services.

e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.

Using OpenShift as a provider differs slightly from other OAuth providers, it requires a service account token to obtain information about the OAuth tokens.
Once the client Id, secret, and token have been obtained from OpenShift, Liberty can be configured as shown below.

Server configuration to use OpenShift OAuth server:
```
<server description="social">

  <!-- Enable features -->
  <featureManager>
    <feature>appSecurity-3.0</feature>
    <feature>socialLogin-1.0</feature>
  </featureManager>

<logging traceSpecification="com.ibm.ws.security.*=all=enabled" maxFiles="8" maxFileSize="200"/>

<httpEndpoint  id="defaultHttpEndpoint" host="*" httpPort="8941" httpsPort="8946" > <tcpOptions soReuseAddr="true" /> </httpEndpoint>


  <!-- specify your clientId, clientSecret and userApiToken as liberty variables or environment variables -->
  <oauth2Login id="openshiftLogin" 
    scope="user:full" 
    clientId="${myclientId}" 
    clientSecret="${myclientSecret}"
    authorizationEndpoint="https://oauth-openshift.apps.papains.os.fyre.ibm.com/oauth/authorize" 
    tokenEndpoint="https://oauth-openshift.apps.papains.os.fyre.ibm.com/oauth/token"
    userNameAttribute="username" 
    groupNameAttribute="groups" 
    userApiToken="${serviceAccountToken}" 
    userApiType="kube" 
    userApi="https://api.papains.os.fyre.ibm.com:6443/apis/authentication.k8s.io/v1/tokenreviews"> 
  </oauth2Login>

  <keyStore id="defaultKeyStore" password="keyspass" />
   
  <!-- more application config would go here -->

</server>

```

In the sidecar scenario, the configuration changes to accept an inbound token from the sidecar.
Server configuration to use OAuth proxy sidecar:
```
  <!-- specify your userApiToken as a liberty variable or environment variable -->
  <!-- note that no clientId or clientSecret are needed --> 
  <oauth2Login id="openshiftLogin" 
    scope="user:full" 
    userNameAttribute="username" 
    groupNameAttribute="groups" 
    userApiToken="${serviceAccountToken}" 
    userApiType="kube" 
    accessTokenHeaderName="X-Forwarded-Access-Token"  
    accessTokenRequired="true" 
    userApi="https://kubernetes.default.svc/apis/authentication.k8s.io/v1/tokenreviews"> 
  </oauth2Login>

```
Use of https communication requires that the server either have a key signed by a well-known certificate authority, which Liberty can trust automatically, or that the server's public key be added to the Liberty trust store.  OpenShift does not come with CA-signed keys by default,  so the OpenShift OAuth server's public key will need to be added.  The easiest way to do this is to specify an environment variable in server.env that identifies the file containing the public key in PEM format.  Liberty will read the file and add the key to its trust store. 

```
# server.env

# OAuth sidecar scenario: causes the Kubernetes default certificate that is pre-installed in pods to be added to Liberty trust store.
cert_defaultKeyStore=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt

# OAuth server scenario: causes the public keys from /tmp/trustedcert.pem (obtained separately) to be added to Liberty trust store.
cert_defaultKeyStore=/tmp/trustedcert.pem

```

f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

Setup instructions used during development are available [here](https://github.com/brutif/using-openliberty-with-openshift).

g. Attach any images to this work item as .png files.

```
NONE
```

**Comment by tomjenningss** [comment]
Hi @brutif, at the end with the example of `#server.env`, please can you explain what this is showing as I'm not totally understanding it. Thanks

**Comment by brutif** [comment]
@tomjenningss updated the blog, does it make better sense now?

**Comment by tomjenningss** [comment]
@brutif It does, thank you for your help.

**Comment by tomjenningss** [comment]
Thank you
