### ISSUE TITLE
Feature test summary for LG-225: Provide ability to omit specified fields from JSON logging output 

### ISSUE THREAD

**Issue by ellen-lau** [OpenLiberty/open-liberty#10134]
1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.

For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature.

If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below. This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths. There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here. Error/outlying scenarios are not really covered. There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios. There is a risk when the feature is used outside the golden paths however we are confident on the golden path. Note: This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios. While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature. The testing covers all golden path cases as well as all the error/outlying scenarios that make sense. We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer. Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above. We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5. We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc. Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by ellen-lau** [comment]
1. 

Extra test cases are added onto JSONFieldsTest because this feature is an extension of the JSON Mapping Fields feature. The test cases that were added are:

testMessageFieldNamesOmitEnv()
- Tests that the server.env configuration to remove the `message` field is fulfilled
	- Sets up Liberty Server with `WLP_LOGGING_JSON_FIELD_MAPPINGS=message:` in server.env
	- Checks messages.log to see if `message` field exists

testMessageFieldNamesOmitBootstrap() 
- Tests that the bootstrap.properties configuration to remove the `message` field is fulfilled
	- Sets up Liberty Server with `com.ibm.ws.logging.json.field.mappings=message:` in bootstrap.properties
	- Checks messages.log to see if `message` field exists

testMessageFieldNamesOmitXML()
- Tests that the server.xml configuration to remove the `message` field is fulfilled
	- Sets up Liberty Server with` jsonFieldMappings=message:` in server.xml
	- Checks messages.log to see if `message` field exists	
	- Sets up Liberty Server with `jsonFieldMappings=ibm_datetime:` in server.xml
	- Checks messages.log to see if `ibm_datetime` field exists

jsonFieldsOmitWrongEventType()
- Tests that the server.xml configuration to remove an invalid event type is fulfilled
	- Sets up Liberty Server with `jsonFieldMappings=wrongtype:message:` in server.xml
	- Checks messages.log to see if `TRAS3010W` error is thrown	

jsonFieldsOmitWrongFieldName()
- Tests that the server.xml configuration to remove an invalid field name is fulfilled
	- Sets up Liberty Server with `jsonFieldMappings=message:wrongfield:` in server.xml
	- Checks messages.log to see if `TRAS3009W` error is thrown

testRenameAndOmit()
- Tests renaming and omission of the same field name
	- Sets up Liberty Server to rename `message` field to `log2`
	- Checks messages.log to see `log2` field exists
	- Sets up Liberty Server to omit `message` field (neither `message` field nor renamed `log2` field should exist)
	- Checks messages.log to see if `message` field exists
	- Sets up Liberty Server to rename `message` field to `log2`
	- Checks messages.log to see if `log2` field exists

omitMultipleFields()
- Tests omission of multiple fields and adding a field back in
	- Sets up Liberty Server with `jsonFieldMappings=message:, ibm_datetime` in server.xml
	- Checks messages.log to see `message` field exists
	- Sets up Liberty Server with `jsonFieldMappings=message:` in server.xml
	- Checks messages.log to see` ibm_datetime` field is added back

2.

4

**Comment by ellen-lau** [comment]
@sabolo for your review please. Thanks!

**Comment by dave-waddling** [comment]
Hi @ellen-lau,

Thanks for completing the Feature Test Summary. The WAD for this feature covers both LG-60 and LG-255 so forgive me if I ask anything covered by LG-60 here. 

Your testing for the omitting of fields from JSON logging output is sufficient, though I'd just like to confirm whether the existing testing for malformed jsonFieldMappings values accounts for the new ability to omit fields?

The testing is passing green in the latest SOE.

I'm almost ready to approve this feature, but before I do please can you:-
- Confirm that the existing syntax testing discussed above is sufficient.
- Add the FAT Complete and WAD Approved tags to the parent epic.

Thanks in advance!

**Comment by ellen-lau** [comment]
Hi @dave-waddling,

Yes, the existing testing for malformed jsonFieldMappings accounts for the new ability to omit fields. I have added the FAT Complete tag to the parent epic, and the Design Approved (I assume this is the same as the WAD Approved tag - I could not find a WAD Approved tag to add) is already existing.

Thanks!

**Comment by dave-waddling** [comment]
Hi @ellen-lau ,

The WAD Approved tag appears to have been replaced or renamed, I expect you're right with Design Approved but I'll check with Kevin and update the tag on the epic myself if we've erred :)

Also thanks for confirming that no additional testing is needed, I'm happy to approve at this time and will add the tag to the parent epic.
