### ISSUE TITLE
server help stop missing options

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#10157]
**Describe the bug**
If you run server help stop it doesn't mention the --force option which will cause the server to stop without the quiesce phase. The option is in docs here: https://openliberty.io/docs/ref/command/#server-stop.html

**Steps to Reproduce**
Run:

```
 server help stop
```

**Expected behavior**

```
Usage: bin/server stop serverName [options] [JVM options]

	Stop the running instance of the named server.

Options:

	--force
﻿﻿﻿﻿	    Skips the quiesce stage before the server is shut down. Normal server 
﻿﻿﻿﻿	    stop includes a quiesce stage before the server is shut down. The quiesce 
﻿﻿﻿﻿	    stage, a period of 30 seconds, allows services to perform pre-shutdown 
﻿﻿﻿﻿	    work; for example, inbound listeners are stopped but existing requests are 
﻿﻿﻿﻿	    allowed to complete. The --force option has no effect if server stop was 
﻿﻿﻿﻿	    already invoked. If you use the --force option, you might see unexpected 
﻿﻿﻿﻿	    exceptions in the messages.log file that occur after the server stop 
﻿﻿﻿﻿	    command was received by the server.
```
**Diagnostic information:**
 - OpenLiberty Version: [e.g. 19.0.0.12]
 - Java Version: 
```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Mac OS X amd64-64-Bit Compressed References 20190806_306 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - fa49279450 based on jdk-11.0.4+11)
```
 - server.xml configuration  N/A
 
**Additional context**
Current output is as follows:

```


Usage: bin/server stop serverName [options] [JVM options]

	Stop the running instance of the named server.

Options:
```

**Comment by hlhoots** [comment]
Hi @NottyCode  --

Referencing the doc link above the server help stop command references --force and --clean.  It currently does not display the --clean option in addition to the --force option.  Should that be added  in addition ?

**Comment by hlhoots** [comment]
Ignore my question above - see those updates were just made via issue 908 in the docs repo.
