### ISSUE TITLE
Support non-Liberty app server default JNDI configs

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#10179]
**Describe the solution you'd like**
It is common for older applications written to run on other application servers to provide non-portable configuration for accessing the in server JNDI. While the following code should work:

```
Context ctx = new InitialContext();
```

older code commonly configures the InitialContextFactory either through `jndi.properties` or via a Hashtable passed into InitialContext creation. 

Currently these apps will fail when loaded in Liberty because the InitialContextFactory class cannot be loaded. This epic proposes detecting these scenarios at runtime and rerouting to the built in JNDI provider.

**Describe alternatives you've considered**
Update application code, or application binary to remove the legacy code.

**Comment by malincoln** [comment]
Per @joe-chacko this should be reviewed by @NottyCode and @gcharters.

**Comment by malincoln** [comment]
Agreement to close.
