### ISSUE TITLE
Serviceabilty: log messages hiding

### ISSUE THREAD

**Issue by 2ppisaHcl** [OpenLiberty/open-liberty#10229]
Hi, 
is there a way to configure liberty server for having the messages hidden in messages.log
without be "moved" in trace.log?
A configuration like this
<logging hideMessage="XXXXX, YYYYY" messageFileName="messages.log"/>

doesn't log XXXXX and YYYYY in messages.log but creates a trace.log containing them even though
no traces has been enabled.

Thanks.

**Comment by donbourne** [comment]
There's no direct way of doing that.

If you're up for using JSON logging (at least for your console output) and you don't want any trace at all you could do this in your bootstrap.properties:

```
com.ibm.ws.logging.trace.file.name=stdout
com.ibm.ws.logging.console.source=message
com.ibm.ws.logging.console.format=json
```

That would 1 - direct your trace to stdout, 2 - by not having `trace` in the list of sources would ignore trace, 3 - has to be in json format to pay attention to the list of sources.
