### ISSUE TITLE
Default logging format not being set when using an invalid console/message logging format

### ISSUE THREAD

**Issue by lamkavan** [OpenLiberty/open-liberty#10238]
The default logging format is not automatically set when using an invalid console/message logging format. This issue occurs when setting the console/message log formats using the bootstrap.properties file or server.env file (environment variables).

For example, if we set the messages.log logging format using the server.env file (environment variables) like so...
`WLP_LOGGING_MESSAGE_FORMAT=Blah`
Then the messages.log file will not be created and of course no log messages.

Also, if we set the console.log logging format using the server.env file (environment variables) like so...
`WLP_LOGGING_CONSOLE_FORMAT=Blah`
Then the console.log file will be created, but nothing is actually logged other than the "Server has started" message.

The same behavior occurs when using the bootstrap.properties file.

Information about logging in general and the different logging fields can be found here https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_logging.html

**Comment by ellen-lau** [comment]
This issue also occurs during server startup with an invalid server.xml console/message format.
