### ISSUE TITLE
CDI does not inject @RequestScoped beans when accessing the server using computer name instead of localhost

### ISSUE THREAD

**Issue by Eng-Fouad** [OpenLiberty/open-liberty#10256]
I have a simple JAX-RS resource with ContainerRequestFilter that is called before accessing the resource. Inside the ContainerRequestFilter I am injecting a bean which is annotated with @RequestScoped. The bean value is `null` if I tried to call JAX-RS using the computer name (i.e. `http://fouad-pc:9080/test/foo`). However, it works fine if I use `localhost` or `127.0.0.1`.

**Diagnostic information:**
 - OpenLiberty Version: 19.0.0.12
 - Java Version: JDK13.0.1

**Comment by andymc12** [comment]
@Eng-Fouad do you have a sample app that we could use to reproduce this problem?  Thanks

**Comment by Eng-Fouad** [comment]
I couldn't reproduce the same issue again.
