### ISSUE TITLE
Remove traces  from http compression FAT

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#10267]
Currently the `com.ibm.ws.transport.http.compression_fat`  contains multiple trace entries in the  `bootstrap.properties `:
```
HttpTransport=all:\
HttpDispatcher=all:\
HTTPChannel=all:\
TCPChannel=all:\
GenericBNF=all
```

We should be able to remove these once we get good executions across all the platforms that are tested and we don't have any test failures

Also ensure that warning messages are not just in the trace.log

**Comment by sercheo87** [comment]
PR is available in [PR-10286](https://github.com/OpenLiberty/open-liberty/pull/10286)
