### ISSUE TITLE
Clean up com.ibm.websphere.javaee.servlet.4.0 component

### ISSUE THREAD

**Issue by mmulholl** [OpenLiberty/open-liberty#103]
Remove jars and depandancy on IBM JDK in the bnd.bnd file.

**Comment by kundel** [comment]
open-liberty/dev(integration) $ git diff com.ibm.websphere.javaee.servlet.4.0/bnd.bnd
diff --git a/dev/com.ibm.websphere.javaee.servlet.4.0/bnd.bnd b/dev/com.ibm.websphere.javaee.servlet.4.0/bnd.bnd
index 4c2a38e4..3aeaf08f 100644
--- a/dev/com.ibm.websphere.javaee.servlet.4.0/bnd.bnd
+++ b/dev/com.ibm.websphere.javaee.servlet.4.0/bnd.bnd
@@ -20,10 +20,9 @@ instrument.disabled: true
 publish.wlp.jar.suffix: dev/api/spec
 
 -buildpath: \
-       com.ibm.ws.internal.prereq.java:java.ibmjgssprovider;strategy=exact;version=1.8.0,\
     lib/com.ibm.ws.javaee.servlet.4.0.jar;version=file,\
     lib/com.ibm.ws.javax.servlet.resources_4.0.jar;version=file,\
     com.ibm.websphere.org.osgi.core;version=latest,\
        com.ibm.websphere.org.osgi.service.component;version=latest,\
        com.ibm.wsspi.org.osgi.service.component.annotations;version=latest
-    
\ No newline at end of file
+
