### ISSUE TITLE
acmeCA-2.0: Add local Boulder server for ACME feature testing

### ISSUE THREAD

**Issue by kristip17** [OpenLiberty/open-liberty#10315]
We added a Pebble server for FAT testing, but we will want to additional testing with a test Boulder server. We can set it up on a VM. Long term plans could possibly turn it into a Consul server.

https://github.com/letsencrypt/boulder

For #9017

**Comment by ryanesch** [comment]
#11374

**Comment by jvanhill** [comment]
@ryanesch - Can this be closed?
