### ISSUE TITLE
Feature Test Summary for OpenShift service account support

### ISSUE THREAD

**Issue by ayoho** [OpenLiberty/open-liberty#10361]
### Testing Performed

- The new FAT project will be: **com.ibm.ws.security.social_fat.okdServiceLogin**
- Tests will be run in automation using a test applicaton that replaces the OpenShift user validation api
- All tests can be run using this test application or against a real OpenShift server (To run the tests against a real OpenShift server, simply uncomment test class in FATSuite.java, update the bootstrap.properties file variables as appropriate and add the OpenShift cert to the test servers trust store)

Testing includes cases for good/bad/blank/empty/omitted values for each config attribute.  Tests will validate that we receive the correct behavior and access or error as appropriate.  Testing also includes group and user role information that will match and not match values found in the subject created from the service account token.  We will ensure that we only allow access to the protected app when the user/group is in the specified role.

### Automated Test Cases:
`OKDServiceLogin_BasicTests_badUserValidationApi_fullConfig_Stub 
OKDServiceLogin_BasicTests_blankRealmName_fullConfig_Stub 
OKDServiceLogin_BasicTests_blankUserValidationApi_fullConfig_Stub 
OKDServiceLogin_BasicTests_emptyUserValidationApi_fullConfig_Stub 
OKDServiceLogin_BasicTests_omitUserValidationApi_fullConfig_Stub 
OKDServiceLogin_BasicTests_realmNameWithSpaces_fullConfig_Stub 
OKDServiceLogin_BasicTests_reuseServiceAccountTokenWithinCacheLifetime_fullConfig_Stub 
OKDServiceLogin_BasicTests_roleMap_badGroupMember_dueToRealmMisMatch_fullConfig_Stub 
OKDServiceLogin_BasicTests_roleMap_badGroupMember_fullConfig_Stub 
OKDServiceLogin_BasicTests_roleMap_badUser_dueToRealmMismatch_fullConfig_Stub 
OKDServiceLogin_BasicTests_roleMap_badUser_fullConfig_Stub 
OKDServiceLogin_BasicTests_roleMap_goodGroupMember_fullConfig_Stub 
OKDServiceLogin_BasicTests_roleMap_goodGroupMember_specifyRealm_fullConfig_Stub 
OKDServiceLogin_BasicTests_roleMap_goodUser_fullConfig_Stub 
OKDServiceLogin_BasicTests_roleMap_goodUser_specifyRealm_fullConfig_Stub 
OKDServiceLogin_BasicTests_shortCacheLifetime_fullConfig_Stub 
OKDServiceLogin_BasicTests_specifyRealmName_fullConfig_Stub 
OKDServiceLogin_GenericTests_badServiceAccountToken_fullConfig_Stub 
OKDServiceLogin_GenericTests_badServiceAccountToken_minimumConfig_Stub 
OKDServiceLogin_GenericTests_blankServiceAccountToken_fullConfig_Stub 
OKDServiceLogin_GenericTests_blankServiceAccountToken_minimumConfig_Stub 
OKDServiceLogin_GenericTests_emptyServiceAccountToken_fullConfig_Stub 
OKDServiceLogin_GenericTests_emptyServiceAccountToken_minimumConfig_Stub 
OKDServiceLogin_GenericTests_goodServiceAccountToken_fullConfig_Stub 
OKDServiceLogin_GenericTests_goodServiceAccountToken_minimumConfig_Stub 
OKDServiceLogin_GenericTests_omitServiceAccountToken_fullConfig_Stub 
OKDServiceLogin_GenericTests_omitServiceAccountToken_minimumConfig_Stub 
OKDServiceLogin_SSLTests_badSSLRef_Stub 
OKDServiceLogin_SSLTests_goodSSLRef_Stub 
OKDServiceLogin_SSLTests_missingSSLRef_Stub 
OKDServiceLogin_SSLTests_omitSSLRef_globalSSLCfgIsNotSufficient_Stub 
`
### Manual Tests
[OKDServiceAccountTokenManualTesting.pdf](https://github.com/OpenLiberty/open-liberty/files/4220804/OKDServiceAccountTokenManualTesting.pdf)

Our confindence in the testing delivered is a **4**
While we would like to always test with a real OpenShift server, resources at the present time do not allow that.

**Comment by dave-waddling** [comment]
Hi @c00crane,

Thanks for completing the Feature Test Summary; all looks good to me in that regard. As a slight aside we're currently working on adding OCP into the EBC so it may be possible to update your testing above to work with an actual OCP in the not-too-distant future.

There are a couple of outstanding issues which require addressing before I can grant a FAT Focal Approval:
-  The UFO needs to be approved (currently the parent epic lacks the Design Approved label and I can see that @ayoho has added the Design Approval Request label so I'm sure that's being driven).
- Defect 272108 also needs to be fixed as it's hitting all of our Windows platforms in the SOE and the regular non-SOE Windows build.

**Comment by dave-waddling** [comment]
Hi,

I can see that the design has now been approved and the defect mentioned above is fixed so I'll add the FAT Focal Approval to the epic now.
