### ISSUE TITLE
LG-263: MicroProfile Health v2.2 - Spec/API/TCK

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#10375]

**Comment by pgunapal** [comment]
- Released MicroProfile Health 2.2 Spec/API/TCK: 
https://github.com/eclipse/microprofile-health/releases/tag/2.2

- Maven Central MicroProfile Health 2.2 API:
https://repo1.maven.org/maven2/org/eclipse/microprofile/health/microprofile-health-api/2.2/

- Maven Central MicroProfile Health 2.2 TCK:
https://repo1.maven.org/maven2/org/eclipse/microprofile/health/microprofile-health-tck/2.2/
