### ISSUE TITLE
Feature Test Summary for Fault Tolerance 2.1

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#10370]
This is the Feature Test Summary for #9341 

**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

Here are the 4 main changes in Fault Tolerance 2.1 and the test plan to go with them:
1. Activate request context during `@Asynchronous` method invocation #10172:
    - Tested request context is activated during asynchronous execution. Tested for methods returning a `CompletionStage` and for methods returning a `Future` (TCK: [#497](https://github.com/eclipse/microprofile-fault-tolerance/pull/497)).
    - Tested implementation does not set request context when `@Asynchronous` is not used (FAT: #10172).
    - Tested request context is activated and deactivated for each `@Retry` attempt (UT: #10172).
    - Tested request context is still activated and deactivated if method execution is interrupted (e.g. due to `@Timeout` or user calling `Future.cancel()`) (UT: #10634).<br/><br/>
2. Implemented `applyOn()` and `skipOn()` for `Fallback` #9977:
    - Tested that `applyOn()` and `skipOn()` handle exception subclasses correctly for a range of different scenarios (TCK: [#417](https://github.com/eclipse/microprofile-fault-tolerance/pull/473)), testing that:
        - `skipOn()` takes precedence over `applyOn()`.
        - Multiple different exceptions can be set and caught for both.
        - The `Fallback` method is being called correctly.
    - Tested that the correct default values are set for both (UT: #9977).<br/><br/>
3. Implemented `skipOn()` for `CircuitBreaker` #9723:
    - Tested that `failOn()` and `skipOn()` handle exception subclasses correctly for a range of different scenarios (TCK: [#466](https://github.com/eclipse/microprofile-fault-tolerance/pull/466)), testing that:
        - `skipOn()` takes precedence over `failOn()`.
        - Multiple different exceptions can be set and caught for both.
        - The `CircuitBreaker` state is being set correctly.
    - Tested that the correct default values are set for both (UT: #9723).<br/><br/>
4. Added integration between MP Fault Tolerance 2.0 and MP Metrics-2.2 #9728:
    - Configured existing FAT tests to also run with the server configured to use mpMetrics-2.2 (FAT: #9728).

Existing functionality which is unchanged from Fault Tolerance 2.0 will be covered by:
- Running existing FAT tests against the new feature using a RepeatTests rule.
- Running the FT 2.1 TCK (which includes coverage of the 2.0 functionality, as well as the parts which are newly added).

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Confidence level = 4**

**Comment by ayoho** [comment]
@tevans78 Testing looks like it's thorough and does well enough to cover most cases that would be encountered with this new functionality. I'll go ahead and approve this feature.
