### ISSUE TITLE
GA BLOG: APSFOUND-1 Liberty Annotation Caching

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#10380]

**Comment by tbitonti** [comment]
See: https://github.com/OpenLiberty/open-liberty/issues/9647 for the Beta Blog QA.

The Blog text can be the following, which is adapted from:
https://openliberty.io/blog/2019/11/08/diagnose-slow-requests-easily-190011.html#LAC

----

**Faster application startups with Liberty annotation caching**

In this release, application startup times have been made faster by adding cache capabilities ("annotation caching") to core class and annotation scanning function.

Depending on application characteristics, startup times are reduced by 10% to more than 50%.  Applications with many jar files, or which use CDI or JAX-RS function, see the best improvements:

![20001-annotationcaching-graph](https://user-images.githubusercontent.com/31104478/72174255-3fbb0e80-33a7-11ea-9412-3192ebf390ad.png)

Notes:

In the prior release, annotation caching was conditionally available.  Starting in release 20.0.0.1, annotation caching is enabled by default.

Annotation cache data is visible as a new, nested directory of server workarea named "anno". Cache data uses a binary format and is not human readable. Cache data is relocatable: Movement of a server image to a new location does not require that annotation cache data be regenerated. Cache of application class data is cleared when performing a clean server start (starting the server with the --clean option). In normal operations, the clearing of cache data is not necessary, since the cache automatically regenerates cache data for changed application classes. However, the cache function has no way to tell when cache data is obsolete. If the same server is used with many different applications, annotation cache data will accumulate on disk, and a clean start should be performed occasionally to remove stale cache data.

In pipeline deployment environments, for example, Docker, for annotation caching to be effective, the server image must be "warmed" before packaging the deployment image, and application class cache data must be included in the deployment image. Warming the server means performing a single start of the server. This will cause cache data to be generated and available when packaging the server image. A failure to generate the cache data or to include the cache data in the deployment image will result in longer startup times, since a typical startup uses a fresh copy of the deployment image, which will not have any cached data.

----

**Comment by tbitonti** [comment]
Faster application startups with Liberty annotation caching

In this release, application startup times have been made faster by adding cache capabilities ("annotation caching") to core class and annotation scanning function.

Annotation caching is performed automatically, including the regeneration of cache data for changed application classes.  Cache data is stored in the server workarea, and may be cleared by performing a clean server start (starting the server with the --clean option).

Depending on application characteristics, startup times are reduced by 10% to more than 50%. Applications with many jar files, or which use CDI or JAX-RS function, see the best improvements.

("Startup time" measures the time taken to obtain an "Application Started" message after issuing a "server start" command.  The chart, below, graphs the ratio of the the startup time with annotation caching to the startup time without annotation caching.)

https://user-images.githubusercontent.com/31104478/72174255-3fbb0e80-33a7-11ea-9412-3192ebf390ad.png

Notes:

In the prior release, annotation caching was conditionally available. Starting in release 20.0.0.1, annotation caching is enabled by default.

For optimal performance in container environments, the container image must be "warmed".  Warming a container image means starting and stopping the liberty server during the container build.  Applications must be present when the server is started.  Warming the container image by starting and stopping the server causes annotation cache data to be generated, stored in the container image as a subset of the server image, and available to subsequent starts.

When the container environment is Docker, the script "configure.sh" may be used to start and stop the server during the container build.

**Comment by tomjenningss** [comment]
Thank you
