### ISSUE TITLE
Issues raised by non-members should be labelled for member attention

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#104]
Because we have a high volume of issues opened/owned by OpenLiberty members, it would be easy to miss issues that are raised by non-members who have no power to properly label their issue for attention.  Ideally, OpenLiberty members should be able to query for issues raised by non-members so the members can process the issues in a timely manner.

Suggestion:  When a user who is not a member of the OpenLiberty organization raises an issue, Rosie ought to tag the issue with a label such as `[Needs member attention]` so that members can easily query for these issues.  Also, members should be able to remove the tag once the issue has received some initial level of member attention (i.e. don't have rosie re-add the tag if removed)

**Comment by cbridgha** [comment]
I like the idea of a label, but we should also @mention the OpenLiberty/Reviewer team as well for immediate attention.  Doing both should cover us well.

**Comment by aguibert** [comment]
I'd rather we don't put additional burden on the Reviewer group, since anyone in the OpenLiberty team should be able to watch for and respond to issues opened by non-members.

**Comment by cbridgha** [comment]
Ok I agree @aguibert - we just need to make sure that one person keeps an eye on it  :)
