### ISSUE TITLE
FAT Approval Test Summary for Persistent EJB Timer Failover

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#10472]
**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature.

If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

##### Failover1ServerTest
This test bucket attempts to simulate failover of tasks. For this oversimplified scenario, we don't actually have multiple servers, just multiple persistent executor instances on a single server.  We can simulate an instance going down by removing it from the configuration.

testMultipleInstancesCompeteToRunManyLateTasks - Have 3 instances available that could take over for running several late tasks.
testMultipleInstancesCompeteToRunOneLateTask - Have 3 instances available that could take over for running a single late task. Exactly one of the instances should take over and run it.
testScheduleOnOneServerRunOnAnother - Schedule a task on an instance that cannot run tasks. Verify that another instance takes over and runs it. In this test, the missedTaskThreshold is configured on the instance that cannot run tasks.
testScheduleOnOneServerRunOnAnotherThenBackToOriginal - Schedule a task on an instance that cannot run tasks. Verify that another instance takes over and runs it. Then prevent that instance from running tasks. Enable the ability to run tasks on the first instance and verify it fails over back to the original.
testScheduleThenRunOnDifferentServer - Schedule a task using an instance that cannot run tasks. It will go ahead and schedule the task without any claim to run it, allowing another instance to take over. In this test, the missedTaskThreshold is not configured on the instance that cannot run tasks.

##### SwitchFromSingleInstanceToFailOverTest
 This test bucket covers scenarios where the user starts out with fail over disabled and switches to enable fail over. There are a variety of ways they might do this, which are described in more detail in the comments for each individual test.

testEnableFailOverWhileServerIsRunning - Schedules tasks on an instance where fail over is not enabled. Enables fail over while the server is still running. Then verifies that the previous, as well as new, tasks run.
testEnableFailOverWhileServerIsStopped - Schedules tasks on an instance where fail over is not enabled. Stops the server and enables fail over. Starts up the server and verifies that the previous, as well as new, tasks run.
testNewFailOverEnabledInstance - Schedules tasks on an instance where fail over is not enabled. Stop the server and create a new instance with fail over enabled. Verify that the previous, as well as new, tasks run. Stop the server and remove the old instance. Verify that the previous, as well as new, tasks run. This is not a recommended way of enabling fail over, because it leaves instances with and without fail over running at the same time. But it is being tested here in case anyone tries it.
testNewFailOverEnabledInstanceWhileServerIsRunning - Schedules tasks on an instance where fail over is not enabled. While the server is running, create a new instance with fail over enabled. Verify that the previous, as well as new, tasks run. Then remove the old instance. Verify that the previous, as well as new, tasks run. This is not a recommended way of enabling fail over, because it leaves instances with and without fail over running at the same time. But it is being tested here in case anyone tries it.
testRemoveFailOverEnablementWhileServerIsRunning - Schedules tasks on an instance where fail over is enabled. While the server is still running, disables fail over on the same instance. New tasks can be scheduled on the instance and should run there, but those that were submitted previously will not be recognized unless some operations are performed to manually transfer them. Users should not do this. This test is only written to experiment with what would happen and explore how to cope with it.
testRemoveFailOverEnablementWhileServerIsStopped - Schedules tasks on an instance where fail over is enabled. Stops the server and disables fail over on the same instance. Starts up the server. New tasks can be scheduled on the instance and should run there, but those that were submitted previously will not be recognized unless some MBean operations are performed. Users should not do this. This test is only written to experiment with what would happen and explore how to cope with it.
testReplaceWithNewFailOverEnabledInstanceWhileServerIsRunning - Schedules tasks on an instance where fail over is not enabled. While the server is running, removes the original instance, creating a new one with fail over enabled. Then verifies that the previous, as well as new, tasks run.
testReplaceWithNewFailOverEnabledInstanceWhileServerIsStopped - Schedules tasks on an instance where fail over is not enabled. Stops the server and removes the original instance, creating a new one with fail over enabled. Starts up the server and verifies that the previous, as well as new, tasks run.

#### com.ibm.ws.concurrent.persistent_fat_failovertimers
This test bucket covers scenarios where EJB persistent timers are shared across multiple servers, by pointing at the same database.  When the instance that has been running the timer goes down, it should fail over to another server and continue running there.

testProgrammaticTimerFailsOverWhenTimerFailsOnOneServer - On one of the servers, programmatically start a persistent timer which runs in the same global transaction as the database operations performed by the EJB Timer Service/persistent executor. Force the timer to start failing on that server (but keep the application and the server up) and verify that the timer starts running on the same application on a different server.
testProgrammaticTimerFailsOverWhenTimerRollsBackOnOneServer - On one of the servers, programmatically start a persistent timer which runs in the same global transaction as the database operations performed by the EJB Timer Server/persistent executor. Force the timer to start rolling back on that server (but keep the application and the server up) and verify that the timer starts running on the same application on a different server.
testProgrammaticTimerWithTxSuspendedFailsOverWhenAppStops - On one of the servers, programmatically start a persistent timer which runs outside of a global transaction. Stop the application on that server (but not the server itself) and verify that the timer starts running on the same application on a different server.
testSingletonTimerFailsOverWhenAppStops - Determine which server an automatic persistent timer, which is a Singleton EJB, is running on. Stop the application on that server (but not the server itself) and verify that the timer starts running on the same application on a different server.
testLongRunningTimerLooksLikeAMissedTimer - Schedule a long-running timer, which exceeds the missedTaskThreshold by a significant amount. Verify that timer is allowed to complete on the same server (subject only to the transaction timeout), and otherwise does not cause a failover due to its slowness. This is not a recommended way of running. In general, a user should increase their missedTaskThreshold to accommodate the length of their longest timers. However, if it does happen, this test helps to demonstrate that Liberty deals with it gracefully, apart from the extra locking that is incurred by attempting an unnecessary failover.
testTimerFailsOverWhenServerStops - Determine which server an automatic persistent timer is running on. Stop that server and verify that the timer starts running on a different server.

#### com.ibm.ws.concurrent.persistent_fat_demo_timers
This test suite starts an application that has automatic EJB persistent timers and manually scheduled EJB persistent timers that will perform some sort of in-memory data manipulation. This is to simulate the situation where customers use timers to do something like unit conversions, data processing, etc.  These timers will run as frequently as every other second. That sort of frequency is the maximum we would ever expect a customer to run a timer that is doing in memory-work.  This bucket was constructed with the guidance of the EJB team to attempt to simulate real usage by customers.

testRepeatingAutomaticPersistentTimerMemory - Verify that an automatic persistent timer is running multiple times. This timer runs every other second.
testRepeatingAutomaticPersistentTimerDatabase - Verify that an automatic persistent timer is running multiple times. This timer runs every 30 seconds.
testRepeatingAutomaticPersistentTimerIO - Verify that an automatic persistent timer is running multiple times. This timer runs every minute.

##### AutonomicalPolling1ServerTest
This test bucket attempts simulate multiple servers polling for tasks. For this oversimplified scenario, we don't actually have multiple servers, just multiple persistent executor instances on a single server. We can simulate instances going up and down by updating the persistent executor configuration.

testAdd10Remove1PersistentExecs - Add 10 persistent executors, then remove 1, and verify the polling interval is set correctly.
testAdd10Remove9PersistentExecs - Add 10 persistent executors, then remove 9, and verify the polling interval is set correctly.
testAdd10RemoveAllImmediatelyAdd10PersistentExecs - Add 10 persistent executors, remove them all, immediately add 10 persistent executors back, and verify the polling interval is set correctly.
testAdd10RemoveAllWaitAdd10PersistentExecs - Add 10 persistent executors, remove them all, wait long enough to miss more than one poll interval, add 10 persistent executors back, and verify the polling interval is set correctly.
testAdd10Remove5PersistentExecs - Add 10 persistent executors, then disable 5 of them, and verify the polling interval is set correctly.
testAdd3Add4PersistentExecs - Add 3 persistent executors, remove 2, and then add 4 more. Verify the polling intervals for all the persistent executors are correct.
testAddPersistentExecs - Add persistent executors and verify the polling interval is set correctly.
testPollIntervalStable - Have 3 persistent executors available for running tasks. Verify the persistent executors are all taking regular turns.

#### com.ibm.ws.concurrent.persistent_fat
These are the core tests for persistent executor, consisting of 51 existing test cases.
Added a PersistentExecutorWithFailoverEnabledTest bucket, which runs the existing tests with fail over enabled, and also includes the following new tests:

testBlockAfterCancelByIdFE - Cancel a task given its Task ID and block for a while without committing to determine if this interferes with other operations.
testBlockAfterCancelByNameFE - Cancel a task based on a name pattern and block for a while without committing to determine if this interferes with other operations.
testBlockAfterFindByIdFE - Find tasks based on their Task ID and block for a while without committing to determine if this interferes with other operations.
testBlockAfterFindByNameFE - Find a task based on a name pattern and block for a while without committing to determine if this interferes with other operations.
testBlockAfterRemoveByIdFE - Remove a task based on its unique task ID and block for a while without committing to determine if this interferes with other operations.
testBlockAfterRemoveByNameFE - Remove a task based on a name pattern and block for a while without committing to determine if this interferes with other operations.
testBlockAfterScheduleFE - Schedule a task and block for a while without committing to determine if this interferes with other operations.
testBlockRunningTaskFE  - Block the execution of a task after it starts running. Simulate another instance attempting to run the task.
testBlockRunningTaskThatCancelsSelfFE - Block the execution of a task after it starts running and cancels itself.
testBlockRunningTaskThatRemovesSelfFE - Block the execution of a task after it starts running and removes itself.
testCancelRunningTaskFE - Cancel a task while it is running. The task entry does not autopurge.
testRemoveRunningTaskAutoPurgeFE - Removes a task (which autopurges on successful completion) while it is running. This test relies on being in the failover-enabled mode where task execution does not lock the task entry, which allows the remove operation to succeed while the task is running.
testRemoveRunningTaskFE - Attempt to remove a task while it is running.

#### com.ibm.ws.concurrent.persistent_fat_compat
PersistentExecutorCompatibilityWithFailoverEnabledTest added to run 21 existing tests (for compatibility of persisted timer data across Liberty server versions) with fail over enabled

##### PersistentExecutorErrorPathsTest
Added the following to existing test bucket:
testIntrospectorWithFailOverDisabled - Verify that pending/active task ids, plus other helpful information, appears in the server dump output.

##### PersistentExecutorErrorPathsTestWithFailoverAndPollingEnabled
New test class that runs 19 existing tests with failover and polling explicitly configured. Also adds these new test methods:
testIntrospectorWithFailOverEnabled - Verify that pending/active task ids, plus other helpful information, appears in the server dump output.
testMissedTaskThresholdBelowMinimum - attempt to use a persistent executor where the missedTaskThreshold value is less than the minimum allowed. Expect IllegalArgumentException with a translatable message.
testMissedTaskThresholdExceedsMaximum - attempt to use a persistent executor where the missedTaskThreshold value exceeds the maximum allowed. Expect IllegalArgumentException with a translatable message.
testPollIntervalBelowMinimum - attempt to use a persistent executor where the pollInterval value is less than the minimum allowed. Expect IllegalArgumentException with a translatable message.
testPollIntervalExceedsMaximum - attempt to use a persistent executor where the pollInterval value exceeds the maximum allowed. Expect IllegalArgumentException with a translatable message.
testRetryIntervalAndMissedTaskThresholdBothEnabled - testRetryIntervalAndMissedTaskThresholdBothEnabled - attempt to use a persistent executor where the retryInterval and the missedTaskThreshold are both configured. Expect IllegalArgumentException with a translatable message.

#### com.ibm.ws.concurrent.persistent_fat_execdisabled
This existing bucket runs with task execution disabled
PersistentExecutorExecutionDisabledTestWithFailoverEnabled is added to run the 14 existing tests when failover is also enabled.

#### com.ibm.ws.concurrent.persistent_fat_loadtest
This existing bucket runs a small load test in FULL mode.
LoadTestWithFailoverEnabled is added to run the load test with failover enabled.

#### com.ibm.ws.concurrent.persistent_fat_locking
This existing bucket runs tests that aim to surface locking issues in the code.
PXLockTestWithFailoverEnabled is added to run the 10 locking tests with failover enabled.

#### com.ibm.ws.concurrent.persistent_fat_multiple
MultiplePersistentExecutorsWithFailoverEnabledTest adds the following tests:

testConnectionSharing - Have a task share the same connection as the persistent executor transaction.
testFailoverBetweenTwoInstancesFE - Schedule a task from one persistentExecutor instance. Remove the instance, and verify that it continues running on a second instance. Restore the first instance and remove the second. Verify the task continues running.
testFailoverWithFourInstancesFE - Schedule 5 tasks from two persistentExecutor instances. Remove both instances, and verify that all of the tasks continue running on third and fourth instances.
testTaskVisibleToBothExecutorInstancesFE - Verify that one instance can schedule a task, and another instance can query and remove it.

#### com.ibm.ws.concurrent.persistent_fat_oneexec
OneExecutorRunsAllWithFailoverEnabledTest adds the following tests:
testEJBSingletonDeadlockPreventionFE - Simulate a scenario where we need to prevent deadlocks with EJB singletons
testEJBTimersFindAndRemoveFE - Test interfaces for find and remove that we provide to EJB container for EJB persistent timers.
testFailOverIsEnabled - Verify that the interface to EJB Timer Service indicates that fail over is enabled.
testRunTasksOnDifferentExecutorFE - Schedule tasks from two persistentExecutor instances with execution disabled. Verify the tasks run on a third instance, which has task execution enabled. Remove the third instance. Schedule another task. Add an instance with execution enabled, and verify that all tasks run.

#### com.ibm.ws.concurrent.persistent_fat_timers
This is an existing bucket that includes various types of persistent EJB Timers.
The test class PersistentExecutorTimersWithFailoverEnabledTest is added to this bucket in order to run the same tests with fail over enabled.

#### com.ibm.ws.ejbcontainer.timer.persistent_fat
This is an existing bucket that includes various types of persistent EJB timers from an EJB container perspective. Tests added to this bucket specifically cover changes to the EJB Container that allow
missed timer expirations to be skipped/caught up either when a server is down or is failing over to a new server. Basically, this provides a way to avoid running the timer 50 or 100 or more times
immediately when it fails over... and instead perform one catchup and then continue on the configured schedule.

In general, new test variations will create a repeating persistent timer, then examine the behavior of when and how many times the timer runs after scheduled expirations are missed, either due to a simulated server slowdown (i.e. sleep) or server stop and re-start (failover).

The existing test class PersistentTimerCoreTest was updated to cover scenarios where the timer is delayed for other reasons (not failing over):

- testMissedTimerActionDefaultNoFailover - default action without failover is ALL, the existing behavior before failover existed; no catch up
- testMissedTimerActionDefaultWithFailover - default action with failover is now ONCE, to perform one catch up, then resume
- testMissedTimerActionAllNoFailover - verify that ALL (old behavior) may be configured without failover
- testMissedTimerActionAllWithFailover - verify that ALL may be configured with failover, overriding the default with failover.
- testMissedTimerActionOnceNoFailover - verify the ONCE (new behavior) may be configured without failover
- testMissedTimerActionOnceWithFailover - verify the ONCE (new behavior) may be configured with failover
- testMissedTimerActionMixedCaseNoFailover - verify the configuration allows mixed case for the config value
- testMissedTimerActionBadValueNoFailover - verify the correct warning and behavior when an invalid value is specified.

The new test class PersistentTimerRestartTest was added to cover scenarios where the server is stopped, and restarted to simulate failover:

- testMissedTimerActionDefaultNoFailoverRestart - verify default ALL when no failover
- testMissedTimerActionDefaultWithFailoverRestart - verify default ONCE when failover enabled
- testMissedTimerActionAllWithFailoverRestart - verify override failover default to ALL
- testMissedTimerActionOnceNoFailoverRestart - verify override non-failover defatult to ONCE.

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

5

**Comment by ayoho** [comment]
Extent of testing looks good to me; I'm happy to approve this feature.
