### ISSUE TITLE
JMXConnectorServerFactory.newJMXConnectorServer creates "Illegal reflective access by com.ibm.ws.jndi.internal.WASURLObjectFactoryFinder" running on Java 11

### ISSUE THREAD

**Issue by c-koell** [OpenLiberty/open-liberty#10488]
**Describe the bug**
We use JMXConnectorServerFactory.newJMXConnectorServer in our Applivcation. If we use Java 11 we see following Warning.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.ibm.ws.jndi.internal.WASURLObjectFactoryFinder (file:/C:/Development/Liberty_NewApp/newweb/target/liberty/wlp/lib/com.ibm.ws.jndi_1.0.35.jar) to constructor com.sun.jndi.url.rmi.rmiURLContextFactory()
WARNING: Please consider reporting this to the maintainers of com.ibm.ws.jndi.internal.WASURLObjectFactoryFinder
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Steps to Reproduce**
If you try to create a JMXConnectorServer you will see the message above.

**Expected behavior**
No warning is displayed if you run the application on Liberty with Java 8

**Diagnostic information:**
 - OpenLiberty Version: 19.0.0.12
 - Java Version: Eclipse OpenJ9 VM, Version 11.0.6+10

**Comment by aguibert** [comment]
hi @c-koell, thanks for reporting this issue. Looks like we are missing an `--add-opens` for this code path

**Comment by aguibert** [comment]
@c-koell can you share more code on how you are creating the JMX connector server? I tried to reproduce the issue with this code but did not get the warning you are reporting:

```java
JMXServiceURL jmxUrl = new JMXServiceURL("service:jmx:rmi://localhost");
JMXConnectorServerFactory.newJMXConnectorServer(jmxUrl, Collections.emptyMap(), MBeanServerFactory.createMBeanServer());
```

I believe that adding a `jvm.options` file in your `${server.config.dir}` with the following contents will work around the issue:
```
# Make sure these are on 2 separate lines in jvm.options
--add-opens
jdk.naming.rmi/com.sun.jndi.url.rmi=ALL-UNNAMED
```

If that JVM option fixes the issue for you, let me know and I will deliver the fix

**Comment by c-koell** [comment]
I get the warning with following code

```javascript
LocateRegistry.createRegistry(2088);
JMXServiceURL jmxUrl = new JMXServiceURL("service:jmx:rmi:///jndi/rmi://localhost:2088/TST");
JMXConnectorServer newJMXConnectorServer = JMXConnectorServerFactory.newJMXConnectorServer(jmxUrl, Collections.emptyMap(), ManagementFactory.getPlatformMBeanServer());
newJMXConnectorServer.start();
```
The Method .start() creates the warning ... 

With the entries in the jvm.options file i see no warnings anymore !

thanks & greets
claus
