### ISSUE TITLE
mpJwt header checking

### ISSUE THREAD

**Issue by dshimo** [OpenLiberty/open-liberty#10516]
**Is your feature request related to a problem? Please describe.**
When a spec requires tokens to be passed in a specific manner, i.e. `Authorization: Token <jwt>` instead of `Authorization: Bearer <jwt>` , a ContextRequestFilter must be used instead of the mpJwt feature.

**Describe the solution you'd like**
Variable or ability to change what mpJwt searches for

**Describe alternatives you've considered**

**Additional context**
https://github.com/OpenLiberty/open-liberty/pull/10498

**Comment by yeekangc** [comment]
@chunlongliang-ibm @brutif

**Comment by yeekangc** [comment]
@chunlongliang-ibm @brutif, is this a feature and a spec change?  Or, it can be fixed in Liberty first?

**Comment by brutif** [comment]
chatting with CL we can begin by  adding an internal metatype property "authorizationHeaderPrefix" with default value of "Bearer " that they could change to "Token " or any other value we come across in the wild.
