### ISSUE TITLE
Webcontainer Bundle Deactivation causes IO Exceptions for the Cached Plugin-cfg File

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#10552]
There is a timing issue where the generateXML is running, pauses momentarily, and the webcontainer bundle is stopped and uninstalled (due to the servlet feature removal). Once the thread resumes, exceptions are generated when it tries to create file output stream (Path to the file is broken) or copy the file (Missing File).

**Comment by wraschke** [comment]
#link 264939

**Comment by volosied** [comment]
PR #10969  and PR #10613
