### ISSUE TITLE
Memory leak in feature install code com.ibm.ws.install

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/open-liberty#10562]
**Describe the bug**
After using the install map feature to update an instance of Liberty certain objects are loaded and not released for garbage collection. The result is that the jar file used cannot be deleted on Windows 10. 

This issue involves the use of com.ibm.ws.install.map_1.0.36.jar and com.ibm.ws.install_1.0.36.jar to work with a Liberty installation. 
**Steps to Reproduce**
The attached program demonstrates the bug. In this use case, the Liberty install directory used by the program is used strictly for the install jar and the Liberty install directory is deleted after use. If the sample had actually tried to change an instance of Liberty it would have been an instance of Liberty in yet another location. 

1. Log on to a Windows 10 computer
1. Install Liberty in the location required by the program or update the program to provide a valid path to the Liberty wlp directory. 
1. Compile and run the program and wait for it to print "Press Enter to quit." Do not quit.
1. With the program still running try to delete the files *wlp/lib/com.ibm.ws.install.map_1.0.36.jar* and *wlp/lib/com.ibm.ws.install_1.0.36.jar.* You will find that you can delete the former but not the latter. This is because all the objects using classes from the former are cleaned up but there are still references to objects using classes in the latter jar. 
Error message:
```
C:\Users\ibmadmin\devmode-test>del build\wlp\lib\com.ibm.ws.install_1.0.36.jar
C:\Users\ibmadmin\devmode-test\build\wlp\lib\com.ibm.ws.install_1.0.36.jar
The process cannot access the file because it is being used by another process.
```
**Expected behavior**
After the code in com.ibm.ws.install.map_1.0.36.jar is finished executing we should be able to delete the entire wlp directory but references to jars prevent wlp from being deleted when running on Windows. Unix based operating systems do not have this limitation. 

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.1 [e.g. 19.0.0.8]
 - Java Version: [i.e. full output of `java -version`]
All versions including:
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20200116_435 (JIT enabled, AOT enabled)
OpenJ9   - 6968c18d7
OMR      - 7a1b0239a
JCL      - 104cab2452 based on jdk-11.0.6+10)
 - server.xml configuration (WITHOUT sensitive information like passwords)
N/A
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`
N/A
**Additional context**

[LoadInstallMap.java.zip](https://github.com/OpenLiberty/open-liberty/files/4105282/LoadInstallMap.java.zip)

**Comment by yeekangc** [comment]
@alvinso, is someone looking at this?

FYI, @ericglau.

**Comment by alvinso** [comment]
@herman-kailey could you take a look?  Thanks.

**Comment by yeekangc** [comment]
Thank you, @herman-kailey @alvinso .

@turkeylurkey @ericglau, let us work with Herman and Alvin to get to the bottom of this.

**Comment by turkeylurkey** [comment]
I hope to experiment with some code modifications but first I need to build open liberty.

**Comment by turkeylurkey** [comment]
This is a problem in the Liberty code but we are working around it in the Liberty Maven plugin, ci.common. 
The problem is that URLConnection uses a cache which holds a reference to the jar file even after you call close(). Also, URLClassLoader does not provide a method to control this. 
Our approach was to use a method to disable caching:
`java.net.URLConnection.setDefaultUseCaches("jar", false);`
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/URLConnection.html#setDefaultUseCaches(java.lang.String,boolean)
Note since Java 9.
The real fix would be to rewrite the com.ibm.ws.install code to use a file based class loader instead of the URL loader. I believe we only use files and not web resources anyway.
