### ISSUE TITLE
Liberty OpenID Connect client throws "error":"invalid_request" after successful authentication with OIDC Provider

### ISSUE THREAD

**Issue by milanshergill** [OpenLiberty/open-liberty#10605]
**Describe the bug**
Our application is deployed on Liberty Server and it uses Liberty's OpenID Connect client feature to perform the OIDC flow for user authentication. We use Dex (https://github.com/dexidp/dex) as our OIDC provider.

After successful user authentication Liberty client throws "error":"invalid_request" during the final re-direct of the web request. This happens every time a user tries to authenticate itself.

Refreshing the browser successfully reloads the application without any further need of authentication.

**Steps to Reproduce**
Steps to reproduce the bug

**Expected behavior**
Liberty client should be able to successfully re-direct to the webpage after user authentication.

**Diagnostic information:**
 - OpenLiberty Version: 19.0.0.9
 - Java Version: Java 8
messages.log, server.xml and details of web request flow has been provided to the appropriate personnel. 

**Additional context**
N/A

**Comment by brutif** [comment]
@brutif has logs and ffdc and milanshergill can get trace if needed.  I suspect the OP code is expiring.

**Comment by brutif** [comment]
The authcode duration appear to be set in dex/server/handlers.go:633, to 30 minutes.  From messages.log, during code exchange, dex returns `{"error":"invalid_request","error_description":"Invalid or expired code parameter."}`
this is in dex/server/handlers.go:775
It looks like it can come from either the code being expired or the client id not matching up.  One could add a print statement to handlers.go to see which.   I can't see anything in messages.log that would show the client side having any problems passing the code to dex.

**Comment by brutif** [comment]
@milanshergill I'm suspecting that dex backend storage is messed up somehow and it's forgetting the auth code.  Is there another client besides Liberty you can test against your installation of dex? 
If you can send me this trace,  we can check the code coming and going from the rp side:
```<logging  traceSpecification=“*=info:com.ibm.ws.security.openidconnect.*=all:”
        traceFileName=“trace.log” maxFileSize=“20” maxFiles=“10" />```

**Comment by milanshergill** [comment]
@brutif Thank you for looking into this problem. I have sent you the trace logs via email. We do have other components within the product that uses Dex for authentication. I will see if i can find some other client apart from Liberty to perform the OIDC flow with Dex and see if it throws similar error.

**Comment by milanshergill** [comment]
@brutif Other issue that i wanted to highlight was that if the auth code is not found in dex's memory or if its forgetting it then refreshing the browser shouldn't fix the problem - right? I mean currently after the error is throw I can just refresh the browser and this time it would successfully load the application without re-authentication.

**Comment by brutif** [comment]
@milanshergill it's hard to say for sure what's happening with dex.  I'm speculating, but one possibility is if it's using "eventually consistent" storage, and that storage is slow,  the code can't be read out of storage for awhile after it's initally written, and waiting for a second attempt gives it time to achieve consistency.  Just a guess.

**Comment by brutif** [comment]
@milanshergill I reviewed the trace and can see the code we get from and send back to dex are the same (wturzajn2dinwaan3sxhsv3s6), so I'm not sure why dex is unhappy.  We run the openid foundation rp compliance tests daily so I'm strongly suspecting this is something with dex at this point.

**Comment by brutif** [comment]
@milanshergill I'm going to close because I think we're still thinking it's on the dex side, and you found a workaround.  Please reopen and/or let me know if I've misunderstood.

**Comment by milanshergill** [comment]
@brutif Thank you for spending time to look into this issue. Yes, we found a work around so we can go ahead and close this for now. Thanks!
