### ISSUE TITLE
Wrong encoding for special characters (Swedish language)

### ISSUE THREAD

**Issue by Pooriafd** [OpenLiberty/open-liberty#10604]
**Describe the bug**
In the latest release (20.0.0.1), our application started to handle Swedish characters in wrong way

**Steps to Reproduce**
Print something in swedish like äppel or översätt, and it will be question marks instead of right characters

**Expected behavior**
to be written correctly in responses

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.1
 - Java Version:  11.0.6+10-LTS 

**Additional context**
The problem got fixed by setting LANG=en_US.UTF-8 in linux, however we still have the same problem in windows which seems not to solve the problem by LANG env variable

**Comment by chooty** [comment]
This seems to happen as a result of the change in JsonBProvider in commit 548bcf2b where getBytes is called without a charset specified.

**Comment by andymc12** [comment]
I'm taking a look - it seems like we should be setting the charset based on the `Accept-Charset` header instead of just assuming the default charset.

**Comment by chooty** [comment]
According to [RFC8259](https://tools.ietf.org/html/rfc8259#page-9),
`JSON text exchanged between systems that are not part of a closed ecosystem MUST be encoded using UTF-8`

So to me it sounds like always using UTF-8 could be ok, or at least the default if no charset is specified.

**Comment by c-koell** [comment]
We are facing the same problems after upgrading. German umlauts are not readable

**Comment by andymc12** [comment]
I've just integrated a change that uses UTF-8 as the default, but allows users to override the default charset for the JSON-B entity provider by setting `com.ibm.ws.jaxrs.jsonbprovider.defaultCharset=<differentCharset>`.  The change will also attempt to respect the `Accept-Charset` HTTP header from the client.
