### ISSUE TITLE
JakartaEE: PackageRename: Transform servlet-5 required jars

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#10637]
Transform the minimally required servlet-5 liberty bundle jars.

Public Feature -- https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.websphere.appserver.features/visibility/public/servlet-5.0/com.ibm.websphere.appserver.servlet-5.0.feature

Private Feature (API Bundle) -- https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.jakarta.servlet-5.0.feature

Outstanding Questions/Issues -- 
How to set the ServletVersion value in Servlet Factories.  Currently, servletVersion would report incorrectly for servlet 5.0. Only one factory bundle is loaded at a time and that sets the servletversion in the webcontainer.

com.ibm.ws.webcontainer.servlet.4.0.factories/bnd.bnd -- Service-Component . 

We may need to create update the transformer tool to update the manifest for these new attributes. 

__________________

**Comment by tbitonti** [comment]
subset of issue #10538

**Comment by volosied** [comment]
In the minfied liberty servlet-4.0 image, I found the follow jars that use javax.servlet:

- com.ibm.ws.org.apache.commons.fileupload_1.0.36.jar
- com.ibm.ws.session_1.0.36.jar
- com.ibm.ws.webcontainer.cors_1.0.36.jar
- com.ibm.ws.webcontainer.servlet.3.1_1.0.36.jar
- com.ibm.ws.webcontainer.servlet.4.0.factories_1.0.36.jar
- com.ibm.ws.webcontainer.servlet.4.0_1.0.36.jar
- com.ibm.ws.webcontainer_1.1.36.jar
- com.ibm.ws.webserver.plugin.runtime_1.0.36.jar
