### ISSUE TITLE
SESN0008E error when using infinispan with server failover

### ISSUE THREAD

**Issue by nstewart0206** [OpenLiberty/open-liberty#10696]
**Describe the bug**
After configuring infinispan, server failover for sessions does not work as expected.  Instead multiple SESN0008E errors occur and the sessions do not successfully switch to a new server.
```
[1/31/20 15:32:44:332 GMT-06:00] 000007c9 com.ibm.ws.logging.internal.impl.Incid
entImpl                I FFDC1015I: An FFDC Incident has been created: "com.ibm.websphere.servlet.session.UnauthorizedSessionRequestException: SESN0008E: A user
 authenticated as anonymous has attempted to access a session owned by user:LdapRegistry/cn=user1,o=ibm,c=us. com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters 1105" at ffdc_20.01.31_15.32.43.0.log
[1/31/20 15:32:44:332 GMT-06:00] 000007c9 com.ibm.ws.webcontainer.webapp
                       E SRVE0315E: An exception occurred: java.lang.Throwable: com.ibm.websphere.servlet.session.UnauthorizedSessionRequestException: SESN0008E: A user authenticated as anonymous has attempted to access a session owned by user:LdapRegistry/cn=user1,o=ibm,c=us.
        at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5079)
        at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(Dynam
icVirtualHost.java:314)
        at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:
1007)
        at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualH
ost.java:279)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWr
apper.run(HttpDispatcherLink.java:1134)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHa
ndlerAndExecute(HttpDispatcherLink.java:415)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(
HttpDispatcherLink.java:374)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscri
mination(HttpInboundLink.java:548)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewReq
uest(HttpInboundLink.java:482)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processReque
st(HttpInboundLink.java:347)
        at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete
(HttpICLReadCallback.java:70)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQ
ueueManager.java:503)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueMa
nager.java:573)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueMa
nager.java:954)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueM
anager.java:1043)
        at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run
(ExecutorServiceImpl.java:239)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:635)
        at java.lang.Thread.run(Thread.java:812)
Caused by: com.ibm.websphere.servlet.session.UnauthorizedSessionRequestException: SESN0008E: A user authenticated as anonymous has attempted to access a session
 owned by user:LdapRegistry/cn=user1,o=ibm,c=us.
        at com.ibm.ws.webcontainer.session.impl.HttpSessionContextImpl.checkSecu
rity(HttpSessionContextImpl.java:775)
        at com.ibm.ws.webcontainer.session.impl.HttpSessionContextImpl.isValid(H
ttpSessionContextImpl.java:250)
        at com.ibm.ws.webcontainer.srt.SRTRequestContext.getSession(SRTRequestCo
ntext.java:93)
        at com.ibm.ws.webcontainer.srt.SRTServletRequest.getSession(SRTServletRe
quest.java:2230)
        at org.jboss.weld.servlet.SessionHolder.requestInitialized(SessionHolder
.java:47)
        at org.jboss.weld.servlet.HttpContextLifecycle.requestInitialized(HttpCo
ntextLifecycle.java:234)
        at org.jboss.weld.servlet.WeldInitialListener.requestInitialized(WeldIni
tialListener.java:152)
        at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletRequestCreated(Web
App.java:2769)
...
```

**Steps to Reproduce**
1. Create a Liberty Collective with four members
1. Install an application that uses sesssions with login/logout to a cluster
1. Get Infinispan 10 jars (or later)
    1. Use maven to get the jars
    1. pom.xml file to use:
       ```
        <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"> 
        <modelVersion>4.0.0</modelVersion>
        <groupId>io.openliberty</groupId>
        <artifactId>openliberty-infinispan</artifactId>
        <version>1.0</version>
        <!-- https://mvnrepository.com/artifact/org.infinispan/infinispan-jcache -->
        <dependencies>
        <dependency>
        <groupId>org.infinispan</groupId>
        <artifactId>infinispan-jcache</artifactId>
        <version>10.0.0.Final</version>
        </dependency>
        </dependencies>
        </project>
        ```
    1. Run the mvn command to get the dependencies: mvn dependency:copy-dependencies -DoutputDirectory=/opt/ibm/wlp/usr/shared/resources/infinispan
1. Install IHS, Plugins, and WCT on the controller machine
    1. Create a plugin-cfg.xml file for the cluster and put it on the IHS machine.
    1. If using SSL, add certificates for the liberty servers to the plugin-key.kdb file
1. Add the sessionCache-1.0, mpMetrics-2.0, and mpReactiveStreams-1.0 features to each liberty server
1. Add the infinispan information to the server.xml file for each liberty server.
    1. If the liberty servers are in the same subnet, then add the infinispan information below to the server.xml. Example:
       ```
        <httpSessionCache enableBetaSupportForInfinispan="true" libraryRef="InfinispanLib"/>
        <library id="InfinispanLib">
            <fileset dir="${shared.resource.dir}/infinispan" includes="*.jar"/>
        </ library>
        ```
    1. If the liberty servers are not in the same subnet, then more configuration is needed.
        1. add a JVM option of -Djava.net.preferIPv4Stack=true to the jvm.options file for each server
        1. add the following infinispan information to the server.xml
           ```
           <httpSessionCache enableBetaSupportForInfinispan="true" uri="file:///${shared.resource.dir}/infinispan/infinispan.xml" libraryRef="InfinispanLib"/>
           <library id="InfinispanLib">
               <fileset dir="${shared.resource.dir}/infinispan" includes="*.jar"/>
           </library>
           ```
        1. add the following infinispan.xml file to the ${shared.resources.dir}/infinispan directory where libertyhost1, libertyhost2, libertyhost3, and libertyhost4 are the fully qualified host names (or IPs) of your 4 liberty servers
           ```
           <infinispan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:infinispan:config:10.0 http://www.infinispan.org/schemas/infinispan-config-10.0.xsd urn:org:jgroups http://www.jgroups.org/schema/jgroups-4.0.xsd" xmlns="urn:infinispan:config:10.0" xmlns:ispn="urn:infinispan:config:10.0">
              <jgroups>
                 <stack name="tcpping" extends="tcp">
                    <MPING ispn:stack.combine="REMOVE" xmlns="urn:org:jgroups"/>
                    <TCPPING initial_hosts="libertyhost1[7800],libertyhost2[7800],libertyhost3[7800],libertyhost4[7800]"
                         port_range="3"
                         ispn:stack.combine="INSERT_AFTER"
                         ispn:stack.position="TCP"
                         ergonomics="false"/>
                 </stack>
             </jgroups>
             <cache-container>
                 <transport stack="tcpping"/>
                 <replicated-cache-configuration name="com.ibm.ws.session.*"/>
             </cache-container>
           </infinispan>
           ```
1. After starting each liberty server, check that the following message exists: ```SESN8502I: The session manager found a persistent storage location; it will use session persistence mode=JCACHE```. One liberty server should also have messages like the following:
    ```
    [1/29/20 22:05:27:243 EST] 0000016b org.jgroups.protocols.pbcast.ClientGmsImpl                   I libertyhost1-6819: no members discovered after 2003 ms: creating cluster as first member
    [1/29/20 22:05:27:254 EST] 0000016b org.infinispan.CLUSTER                                       I ISPN000094: Received new cluster view for channel ISPN: [libertyhost1-6819|0] (1) [libertyhost1-6819]
    ```
    The other servers should be joining that infinispan cluster and not creating their own and the message should look similar to this: ```[1/29/20 22:05:27:254 EST] 0000016b org.infinispan.CLUSTER I ISPN000094: Received new cluster view for channel ISPN: [libertyhost1-6819|1] (2) [libertyhost1-6819,libertyhost2-7729]```.
1. Start load against the application using appropriate stress engine for the application.
    1. Load should be pointed to IHS and not individual liberty servers
1. Stop one liberty server

**Expected behavior**
Session failover occurs successfully using the infinispan cache

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.1
 - Java Version: 
```
-bash-4.2# java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 8.0.5.26 - pap6480sr5fp26-20181115_03(SR5 FP26))
IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20181106_401576 (JIT enabled, AOT enabled)
OpenJ9   - fde1d6f
OMR      - d8c3617
IBM      - 5c4a9f0)
JCL - 20181022_01 based on Oracle jdk8u191-b26
```
 - I gathered trace (com.ibm.ws.session.*=all) and can send the logs and configuration via email if needed.

**Comment by nstewart0206** [comment]
#8835

**Comment by emilytee** [comment]
Suggestion to try the following:
LTPA token limitations
An SESN0008E exception occurs when an LTPA token expires before the user session expires.
An LTPA token is associated with the current user session. If the session expires before an LTPA token expires, a new session is created automatically. However, when an LTPA token expires before a user session expires, the following exception occurs:
com.ibm.websphere.servlet.session.UnauthorizedSessionRequestException: SESN0008E: A user authenticated as anonymous has attempted to access a session owned by {user name}
To resolve this limitation, you must force the user session to expire when the LTPA token expires.
On WebSphere Application Server Liberty, set the httpSession attribute invalidateOnUnauthorizedSessionRequestException to true in the server.xml file.
On WebSphere Application Server, add the session management custom property InvalidateOnUnauthorizedSessionRequestException with the value true to fix the issue.

**Comment by nstewart0206** [comment]
I was able to get around this by following the information in this article: https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_sec_cluster.html.  I did not try the invalidateOnUnauthorizedSessionRequestException since copying the ltpa.keys from one cluster member to the rest of the cluster members solved my problem.
