### ISSUE TITLE
AsyncResponseImpl.initContinuation() throws NPE when Continuation is null

### ISSUE THREAD

**Issue by WhiteCat22** [OpenLiberty/open-liberty#10712]
Jaxrs-2.0 and Jaxrs-2.1

`AsyncResponseImpl.initContinuation()` should check if the Continuation from 
```cont = provider.getContinuation();```
is null and throw an exception.

This occurs when a user's application has an async resource method and a ServletFilter registered that does not support async requests. Every ServletFilter in the chain must support Async otherwise `HTTPServletRequest.isAsyncSupported()` will return `false` and we won't set up a Continuation, resulting in an NPE.

**Comment by bmhm** [comment]
Hi @WhiteCat22 

I think this is a duplicate of this RFE: https://www.ibm.com/developerworks/rfe/execute?use_case=viewRfe&CR_ID=120020

Thanks for looking into it!

**Comment by WhiteCat22** [comment]
contributing to CXF
https://issues.apache.org/jira/browse/CXF-8235
