### ISSUE TITLE
Context-root attribute for server.xml web-ext element ignored

### ISSUE THREAD

**Issue by dlandis** [OpenLiberty/open-liberty#10732]
### Overview

I'm experiencing exactly the same problem as described here: https://github.com/OpenLiberty/open-liberty/issues/696

> In Liberty it is possible to define binding attributes via server.xml. According to our documentation, if we have an enterprise application (.ear) named "earApp" which contains a web archive (.war) named "warModule", we should be able to re-map the default context root of the warModule to a different context root using the following server.xml config

### My Code

server.xml
```
<enterpriseApplication id="my-apps" location="my-apps.ear" name="my-apps">
    <web-ext moduleName="myapp" context-root="newcontextroot" />
...
    <application-bnd>
       <security-role name="MyApplicationUsers">
                <special-subject type="ALL_AUTHENTICATED_USERS"></special-subject>
            </security-role>
     </application-bnd>
</enterpriseApplication>
<webContainer deferServletLoad="false"/>
<applicationManager autoExpand="true"/>
...
```

application.xml
```
<application>
...
	<module id="WebModule_1240515816637">
		<web>
			<web-uri>myapp.war</web-uri>
		</web>
	</module>
...
</application>
```

### Result

The context root is still `myapp` despite using the `web-ext` element in server.xml. It should be `newcontextroot`.

### Versions Tested
 - `WebSphere Application Server 19.0.0.3 (1.0.26.cl190320190321-1636) on IBM J9 VM, version 8.0.5.41 - pxa6480sr5fp41-20190919_01(SR5 FP41) (en_US)`
 - `WebSphere Application Server 19.0.0.12 (1.0.35.cl191220191120-0300) on IBM J9 VM, version 8.0.5.26 - pxa6480sr5fp26-20181115_03(SR5 FP26) (en_US)`

### Other Details
This issue might relate to these issues:
 - https://github.com/OpenLiberty/open-liberty/issues/696
 - https://github.com/OpenLiberty/open-liberty/issues/1553
 - https://github.com/OpenLiberty/open-liberty/issues/6590

**Comment by brenthdaniel** [comment]
Thanks for the report.. It turns out that the previous fix from Erik only addressed one piece of the problem, and we neglected to ever put in the other part.

**Comment by dlandis** [comment]
Thanks for the update @brenthdaniel  ! Much appreciated. I could help verify the new fix if needed.

**Comment by dlandis** [comment]
Hi @brenthdaniel - I see the PR was merged already; do you know what the first version is that will have this change? Thanks

**Comment by brenthdaniel** [comment]
@dlandis I think it was too late for 20.0.0.2, so it should be in 20.0.0.3.
