### ISSUE TITLE
Investigate the interaction between JAX-RS and CDI in JaxRsFactoryImplicitBeanCDICustomizer to explore possible improvements.

### ISSUE THREAD

**Issue by jkoehler22** [OpenLiberty/open-liberty#10742]

**Comment by jkoehler22** [comment]
Other issues:
https://github.com/OpenLiberty/open-liberty/issues/10725
https://github.com/OpenLiberty/open-liberty/issues/10633

**Comment by andymc12** [comment]
will look at the other two issues directly - closing this one
