### ISSUE TITLE
jax-rs get with "return String" generates response header content-type: application/octet-stream

### ISSUE THREAD

**Issue by gorlok** [OpenLiberty/open-liberty#10759]
### JAX-RS GET method with "return String" generates a response header with "content-type: application/octet-stream" instead of "content-type: text/plain"

- Steps to reproduce:

Using https://start.microprofile.io/ to create a sample application. Choose Microprofile Version 3.2, Java SE 11, and MicroProfile runtime: Open Liberty. Choose any (or all) examples, like Config or Metrics.

Use CURL to test some GET method that returns a String. For instance:
`curl -i -X GET "http://localhost:9080/data/hello" -H  "accept: */*"`
or
`curl -i "http://localhost:9080/data/resilience" -H  "accept: */*"`
or any other endpoint that "return String".

The response Content-Type is **application/octet-stream** instead of **text/plain**.

If you visit Open UI (Swagger) on your browser at http://localhost:9080/openapi/ui/#/default/sayHello, and you try any such endpoint, on response body you will get a weird "Download file" instead of body text been showed.

- OpenLiberty version: 

(Open Liberty 20.0.0.1/wlp-1.0.36.cl200120200108-0300) on OpenJDK 64-Bit Server VM, version 11.0.2+9 (en_US)

- java -version

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.2+9, mixed mode)

**Comment by andymc12** [comment]
Hi @gorlok When I used the starter, it did not add any `@Produces` annotations (I selected the Metrics and Config features, so maybe a different feature does add it), but that annotation determines what the response's content type is.  Is your resource method (or class) annotated with `@Produces(MediaType.TEXT_PLAIN)` ?  If not, please give that a try. 

By default, if no media type is specified in the `@Produces` annotation, then the default is `application/octet-stream`.  Hope this helps!

**Comment by gorlok** [comment]
Why is application/octet-stream by default? That's not consistent or logic to me. For instance, other methods that returns long, at the same example, the content-type is text/plain by default. Why it's not applitacion/octet-stream too? I would spected text/plain and I think it's more useful.

For example:
`curl -i -X GET "http://localhost:9080/data/metric/increment" -H  "accept: */*"`
returns Content-Type: text/plain by default. Why "return String" not?

That default is part of JAX-RS spec, MicroProfile spec, or OpenLiberty implementation?

**Comment by andymc12** [comment]
That is a good question.  The JAX-RS spec defines the default, and it was added shortly after JAX-RS version 1.0 (from the change history):
```
D.10 Changes Since 1.0 Release
...
    * Section 4.2.1: Default to application/octet-stream if a request does not contain a content-type header.
```

That was before I was involved with JAX-RS, so I can't give a good answer for why that content type was chosen. 

As for why longs or other primitives use text/plain, that is defined in section 4.2.2:
```
java.lang.Boolean, java.lang.Character, java.lang.Number Only for text/plain. Corresponding primitive types supported via boxing/unboxing conversion.
```

HTH

**Comment by gorlok** [comment]
Then it's not a problem with OpenLiberty. It's part of JAX-RS specs.

It sounds perfect for most types, but what sounds unexpected to me, it's that strings use application/octet-stream by default, instead than text/plain, like other primitives.

But it's a question for JAX-RS then.

Just a note:
I just tested with other runtimes. PayaraMicro retuns text/plain:

`
curl -i http://localhost:8080/data/hello
HTTP/1.1 200 OK
Server: Payara Micro #badassfish
Content-Type: text/plain
Content-Length: 11
X-Frame-Options: SAMEORIGIN
`

And ThorntailV2, returns octecstream like OpenLiberty:
`
curl -i http://localhost:8080/data/hello
HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: application/octet-stream
Content-Length: 11
Date: Thu, 06 Feb 2020 18:13:42 GMT
`
Maybe OpenLiberty and Thorntail uses the same implementation of JAX-RS and Payara uses another one?

**Comment by andymc12** [comment]
All three of us use different implementations. :-) OpenLiberty uses Apache CXF; Thorntail uses RestEasy, and Payara uses Jersey.  

But yes, it is a JAX-RS question.  You can raise the issue [here](https://github.com/eclipse-ee4j/jaxrs-api/issues) (and reference this issue to keep context).  The JAX-RS community may not be able to change this behavior in the next release (3.0) since the release is intended to include the `javax.*` to `jakarta.*` package rename, but it could be changed in a future release.

**Comment by gorlok** [comment]
Thanks for everything. You helped me shed some light on the matter. I will bring this there later. I close this.

**Comment by gorlok** [comment]
I will follow this on https://github.com/eclipse-ee4j/jaxrs-api/issues/844
Thanks.
