### ISSUE TITLE
BETA BLOG 20.0.0.2 mpMetrics-2.3

### ISSUE THREAD

**Issue by Channyboy** [OpenLiberty/open-liberty#10769]
a) Which Liberty feature does it relate to?

i) Human-readable name
`MicroProfile Metrics 2.3`

ii) Feature name
`mpMetrics-2.3`

iii)Is this a new feature or is it an update to an existing feature for this release?
This is a new feature to support MicroProfile Metrics 2.3 specification.

 iv) Provide the fully qualified name of all public features ( as '*.esa' filenames) that are delivered as part of this work 
`com.ibm.websphere.appserver.mpMetrics-2.3.esa`

b) Who is the target audience?
Application developers and administrators.

c) What does this feature provide in general? Write a sentence or two that introduces it to someone new to the concept.

MicroProfile Metrics 2.3 enables developers to instrument metrics in their (microservice) applications for easy monitoring by their operations team.

d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)

MicroProfile Metrics 2.3 introduces a new metric type called a Simple Timer (annotated with @SimplyTimed) and runtime provided metrics that track REST resource method usage and is backed by the new Simple Timer metric.

The new Simple Timer metric is a light-weight alternative to the existing Timer metric. The Simple Timer metric only tracks total timing duration and counts the amount of times it was invoked. The Timer metric on the other hand is a performance heavy metric that continually calculates duration statistics and throughput statistics resulting in 14 values.

The new REST stat metrics are gathered from REST resource method usage (i.e GET, POST, PUT, DELETE, OPTIONS, PATCH, HEAD). Total time duration and total count of invocation is tracked ( by use of the Simple Timer metric). This functionality is properly enabled when used in combination with the `jaxrsMonitor-1.0` feature. ALL REST stat metric will use the `REST.request` metric name and will be tagged/labeled with their fully qualified class name and method signature.

e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.
Include the following in the server.xml:
```
<feature>mpMetrics-2.3</feature>
```

The following is an example of how to use the new SimpleTimer metric:
***Programmatically***
```
@Inject
MetricRegistry metricRegistry;

//create metric
Metadata metadata= Metadata.builder().withName("sampleSimpleTimer").build();
SimpleTimer simpleTimer = metricRegistry.simpleTimer(metadata);

//retrieve simple timer context (will start timing)
SimpleTimer.Context simpleTimerContext = simpleTimer.time()

doLogic();
//stops the simple timer from timing
simpleTimerContext.close();
```

***Annotations***
```
@SimplyTimed(name=“sampleSimpleTimer”)
public void doSomething() {
    doLogic();
}
```

**Resulting OpenMetrics output:**
```
# TYPE application_sampleSimpleTimer_total counter 
application_sampleSimpleTimer_total 12
# TYPE application_sampleSimpleTimer_elapsedTime_seconds gauge 
application_sampleSimpleTimer_elapsedTime_seconds 12.3200000
```
--------------------------------------------------------------------------------------------------
REST stat metrics will be enabled with the `mpMetrics-2.3` feature and the `jaxrsMonitor-1.0` feature. e.g
```
<feature>mpMetrics-2.3</feature>
<feature>jaxrsMonitor-1.0</feature>
```

Given the following REST resource:
```
package org.eclipse.microprofile.metrics.demo;

@ApplicationScoped
public class RestDemo {

  @POST
  public void postMethod(String... s, Object o){
      ...
  }
}
```

Regarding REST stat metrics. The OpenMetrics formatted REST metrics would be:
```
# TYPE base_REST_request_total counter
base_REST_request_total{class="org.eclipse.microprofile.metrics.demo.RestDemo",method="postMethod_java.lang.String[]_java.lang.Object"} 1
# TYPE base_REST_request_elapsedTime_seconds gauge
base_REST_request_elapsedTime_seconds{class="org.eclipse.microprofile.metrics.demo.RestDemo",method="postMethod_java.lang.String[]_java.lang.Object"} 1.000
```

f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

The Changes section under:
https://github.com/eclipse/microprofile-metrics/releases/tag/2.3.0

g. Attach any images to this work item as .png files
N/A

**Comment by jim-krueger** [comment]
This jaxrsMonitor-1.0 feature has been moved to GA under PR https://github.com/OpenLiberty/open-liberty/pull/11219

This changes jaxrsMonitor-1.0 from a stand-alone public feature in the Beta to an auto-feature under the monitor-1.0 feature in 20.0.0.4 GA

**Comment by donbourne** [comment]
@Channyboy I think this one is done (https://openliberty.io/blog/2020/02/14/preview-microprofile-3-3-20002.html#metrics)
