### ISSUE TITLE
BETA BLOG 20002 mpHealth-2.2

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/open-liberty#10761]
- Development progress update

  - a. Which Liberty feature does it relate to?
    - i. Human-readable name (eg WebSockets feature)
      - `MicroProfile Health Check 2.2`
    - ii. Feature name (eg websockets-1.0)
      - `mpHealth-2.2`
    - iii. Is this a new feature or is it an update to an existing feature for this release?
      - `This is a new feature to support MicroProfile Health Check 2.2 specification.`
    - iv. Provide the fully qualified name of all public features ( as '*.esa' filenames) that are delivered as part of this work
       (eg: com.ibm.websphere.appserver.transportSecurity-1.0.esa)
      - `com.ibm.websphere.appserver.mpHealth-2.2.esa`

       For example new or changed .esa files for public features in dev/com.ibm.websphere.appserver.features/build/libs/repo/

  - b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc
    - `Application developers and administrators`
  - c. Write a sentence or two that introduces it to someone new to the general technology/concept.
     - `MicroProfile Health Check 2.2 enables you to provide your own health check procedures to be invoked by Liberty, to verify the health of your microservice.`
  - d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)

In mpHealth-2.2 feature for OpenLiberty, all the supported Qualifiers (Liveness and Readiness) now have Annotation Literals added in the specification to ease programmatic lookup and support for inline instantiation of the qualifiers, which was not supported in the previous versions. 

Also, for better integration with 3rd party frameworks, like MicroProfile Rest Client, the `HealthCheckResponse` class declaration was changed from an abstract class to a concrete class with constructors allowing for direct instantiation on the consuming end.

  - e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.

    - Include the following in the server.xml:
`<feature>mpHealth-2.2</feature>`

---
Applications are expected to provide health check procedures, by implementing the HealthCheck interface with the @Liveness or @Readiness annotations, which will be used by Liberty to verify the Liveness or Readiness of the application, respectively. Add the logic of your health check in the call() method, and return the HealthCheckResponse object, by constructing using the simple up()/down() methods from the API. To view the status of each health check, access the either the `http://<hostname>:<port>/health/live` or `http://<hostname>:<port>/health/ready` endpoints.

```
**Liveness Check**
@Liveness
@ApplicationScoped
public class AppLiveCheck implements HealthCheck {
...
    @Override
     public HealthCheckResponse call() {
       ...
       HealthCheckResponse.up("myCheck");
       ...
     }
}
```
---

  - f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.
* [MicroProfile Health Check 2.2 Release Page](https://github.com/eclipse/microprofile-health/releases/tag/2.2-RC2)
* [Release Notes](
https://github.com/eclipse/microprofile-health/blob/master/spec/src/main/asciidoc/release_notes.asciidoc)
  - g. Attach any images to this work item as .png files.

**Comment by donbourne** [comment]
@pgunapal I think this one is done - https://openliberty.io/blog/2020/02/14/preview-microprofile-3-3-20002.html
