### ISSUE TITLE
MP Config 1.4: Feature Test Summary

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#10760]
**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature.

If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

### MP Config 1.4 has double test coverage in many cases, provided by having both TCK and custom FAT tests.
A full list of changes delivered in the 1.4 release can be found at MicroProfile Config 1.4 Milestone. https://github.com/eclipse/microprofile-config/milestone/7?closed=1
API/SPI Changes
    Prevent incorrect caching of ConfigProviderResolver (https://github.com/eclipse/microprofile-config/issues/265)
    ConfigProviderResolver classloading issues (https://github.com/eclipse/microprofile-config/issues/450) (https://github.com/eclipse/microprofile-config/issues/390)
    Converter extends Serializable (https://github.com/eclipse/microprofile-config/issues/473)

Spec Changes
    Change the priority of implicit converters (https://github.com/eclipse/microprofile-config/issues/383)
    Clarify if @ConfigProperty injected values are bean passivating enabled (https://github.com/eclipse/microprofile-config/issues/404)
    Add built-in converters for byte, short and char (https://github.com/eclipse/microprofile-config/issues/386)

All of the API and spec changes include TCKs to test them...
- `com.ibm.ws.microprofile.config.1.4_fat_tck` runs the MP Config 1.4 TCK (FULL mode). Initially delivered in https://github.com/OpenLiberty/open-liberty/pull/9939

In addition we have some selcted extra FAT tests of our own...
- `com.ibm.ws.microprofile.config.1.4_fat` contains tests for new functions or requirements that have been added in version 1.4. Initially delivered in https://github.com/OpenLiberty/open-liberty/pull/6618.
-- `CharacterInjectionTest` tests that a `char` or `Character` can be injected automatically (LITE mode).
-- `BadObserverTest` tests that if a @ConfigProperty is Injected into a CDI Observer then the application will not start if the property can not be resolved. (FULL mode)
-- `OptionalObserverTest` tests that if an Optional @ConfigProperty is Injected into a CDI Observer then the application will still start even if the property can not be resolved.  (FULL mode)
- `com.ibm.ws.microprofile.config.1.3_fat`, `com.ibm.ws.microprofile.config.1.2_fat` and `com.ibm.ws.microprofile.config.1.1_fat` contain the tests that were added for previous verisons
-- In LITE mode these will now run against MP Config 1.4 to confirm backward compatibility.
-- In FULL mode these will be repeated to run against all previous versions of MP Config to which the tests apply.

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Confidence level = 4**

**Comment by ayoho** [comment]
@tevans78 You mention that you added a `com.ibm.ws.microprofile.config.1.4_fat` bucket with a handful of tests, one of which being for injection of `char`s and `Character`s. Is there a particular reason why you chose those values to add tests for but not `short` and `byte`? The TCK associated with the new feature appears to be pretty extensive, so I'm inclined to approve this feature. I was just curious why those particular types were chosen to have specific tests for them.

**Comment by tevans78** [comment]
@ayoho The Open Liberty impl supported short and byte from day 1 ... was actually in the unreleased mpConfig-1.0! So we didn't need to make any changes to pass those new TCK tests for short and byte ... only char.

**Comment by ayoho** [comment]
LGTM. I'll go ahead and approve the feature.
