### ISSUE TITLE
Channel Framework Http Endpoint SameSite Configuration

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#10789]

**Comment by mrsaldana** [comment]
With the upcoming stable version of Chrome 80, Chrome will treat cookies as SameSite=Lax by default if no SameSite attribute is specified. 
More information can be found here:
https://www.chromestatus.com/feature/5088147346030592

This story aims to provide a way to enhance the server's support for SameSite by providing a new httpEndpoint configuration child element called <samesite/>. 

It provided three optional attributes, lax, strict, and none. These are described as follows: 

1. lax : List of cookie names or patterns for which the SameSite attribute is set to a value of Lax, if not already defined. A single wildcard (*) character is supported as a stand-alone value, or following cookie name prefixes. Any cookie name or pattern that is defined by this list must be unique and not present in the 'none' nor 'strict' configurations.

2. none : List of cookie names or patterns for which the SameSite attribute is set to a value of None, if not already defined. A single wildcard (*) character is supported as a stand-alone value, or following cookie name prefixes. Any cookie name or pattern that is defined by this list must be unique and not present in the 'lax' nor 'strict' configurations. Each cookie that is modified to contain a SameSite value of None as a result of this configuration is also set to Secure.
 
3. strict :  List of cookie names or patterns for which the SameSite attribute is set to a value of Strict, if not already defined. A single wildcard (*) character is supported as a stand-alone value, or following cookie name prefixes. Any cookie name or pattern that is defined by this list must be unique and not present in the 'lax' nor 'none' configurations. 

_Note: The transport will only use these list to add the SameSite attribute that matches a Set-Cookie header or Cookie object when this header or cookie does not already contain a SameSite attribute. The transport will not overwrite SameSite values set on the application layer._ 

The following is an example of a configuration that will:

-  set all chocolate* cookies as Samesite=Strict (for instance, chocolate and chocolatechip would match)

- set all sugar cookies as SameSite=None

- set any other cookie as SameSite=Lax

```
<httpEndpoint id="defaultHttpEndpoint" httpPort="9080" httpsPort="9443">
      <samesite strict="chocolate*" none="sugar" lax="*"/>
</httpEndpoint>
```

With this configuration, if the transport receives header such as:
"Set-Cookie: chocolatechip=gooey", "Set-Cookie: sugar=free", and "Set-Cookie: oatmeal=chewie" 

The <samesite/> configuration will take effect and the headers would be written out:
 "Set-Cookie: chocolatechip=gooey; **SameSite=Strict**", "Set-Cookie: sugar=free; **Secure; SameSite=None**", and "Set-Cookie: oatmeal=chewie; **SameSite=Strict**"  

Note: Any cookie that is modified by the 'none' SameSite configuration that is not already Secure, will be set to Secure.

**Comment by mrsaldana** [comment]
With the upcoming stable version of Chrome 80, Chrome will treat cookies as SameSite=Lax by default if no SameSite attribute is specified. 
More information can be found here:
https://www.chromestatus.com/feature/5088147346030592

This story aims to provide a way to enhance the server's support for SameSite by providing a new httpEndpoint configuration child element called `<samesite/>`. 

It provides three optional attributes: `lax, strict, and none`. These are described as follows: 

1. lax : List of cookie names or patterns for which the SameSite attribute is set to a value of Lax, if not already defined. A single wildcard (*) character is supported as a stand-alone value, or following cookie name prefixes. Any cookie name or pattern that is defined by this list must be unique and not present in the 'none' nor 'strict' configurations.

2. none : List of cookie names or patterns for which the SameSite attribute is set to a value of None, if not already defined. A single wildcard (*) character is supported as a stand-alone value, or following cookie name prefixes. Any cookie name or pattern that is defined by this list must be unique and not present in the 'lax' nor 'strict' configurations. Each cookie that is modified to contain a SameSite value of None as a result of this configuration is also set to Secure.
 
3. strict :  List of cookie names or patterns for which the SameSite attribute is set to a value of Strict, if not already defined. A single wildcard (*) character is supported as a stand-alone value, or following cookie name prefixes. Any cookie name or pattern that is defined by this list must be unique and not present in the 'lax' nor 'none' configurations. 

_Note: The transport will only use these list to add the SameSite attribute that matches a Set-Cookie header or Cookie object when this header or cookie does not already specify a SameSite attribute. The transport will not overwrite SameSite values set by the application layer. The transport will first verify if an explicit match of the cookie name can be found in these lists. If no match if found, the patterns are verified from most specific to most generic. A pattern is considered more specific if it is a subset of another pattern. The single '*' character is thus considered the most generic, and last to be evaluated._ 

The following is an example of a configuration that will:

-  set all chocolate* cookies as Samesite=Strict (for instance, chocolate and chocolatechip would match)

- set all sugar cookies as SameSite=None

- set any other cookie as SameSite=Lax

```
<httpEndpoint id="defaultHttpEndpoint" httpPort="9080" httpsPort="9443">
      <samesite strict="chocolate*" none="sugar" lax="*"/>
</httpEndpoint>
```

With this configuration, if the transport receives header such as:
"Set-Cookie: chocolatechip=gooey", "Set-Cookie: sugar=free", and "Set-Cookie: oatmeal=chewie" 

then the `<samesite/>` configuration will take effect and the headers would be written out as:
 "Set-Cookie: chocolatechip=gooey; **SameSite=Strict**", "Set-Cookie: sugar=free; **Secure; SameSite=None**", and "Set-Cookie: oatmeal=chewie; **SameSite=Lax**"  

_Note: Any cookie that is modified by the 'none' SameSite configuration that is not already Secure, will be set to Secure._

_Avoid Trouble: If the Transport receives a Set-Cookie header with an unrecognized attribute, for backwards compatibility it will treat the unrecognized attribute as the beginning of a new cookie. The new cookie will be transmitted in its own Set-Cookie header with all the attributes that follow it._

**Comment by pnicolucci** [comment]
All work is completed for this Story so I'm going to close it!
