### ISSUE TITLE
Blog Post content for MP Config 1.4

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#10794]
The mpConfig-1.4 feature provides an implementation of the Eclipse MicroProfile Config 1.4 API. The full list of changes to the API since 1.3 can be found here;
https://github.com/eclipse/microprofile-config/milestone/7?closed=1

The two biggest changes to the API are in the built-in and implicit converters.

Built-in converters for byte/Byte, short/Short and char/Character have been added. The Open Liberty implementation actually already supported byte/Byte and short/Short.

If we have the following properties available in a ConfigSource...
```
byte1=128
short1=5
char1=\u00F6
```
...then you can inject those properties into your application, either as primitives or as their boxed equivalents;
```
@Dependent
public class MyBean {

    @Inject
    @ConfigProperty(name = "byte1")
    private Byte property1;

    @Inject
    @ConfigProperty(name = "byte1")
    private byte property2;
    
    @Inject
    @ConfigProperty(name = "short1")
    private Short property3;

    @Inject
    @ConfigProperty(name = "short1")
    private short property4;
    
    @Inject
    @ConfigProperty(name = "char1")
    private Character property5;

    @Inject
    @ConfigProperty(name = "char1")
    private char property6;
}
```

The implicit converter order has been slightly changed. Previously the order was:
1.  `of(String)`
2. `valueOf(String)`
3. `constructor(String)`
4. `parse(CharSequence)`

In version 1.4, the last two have been swapped:
1. `of(String)`
2. `valueOf(String)`
3. `parse(CharSequence)`
4. `constructor(String)`

The reason for this change is that static `parse(CharSequence)` methods typically have some built-in caching of their results and are therefore faster in some cases. Also in many cases throughout the JDK, the String constructors have been deprecated.

In the following example, the MyType class has two possible implicit converter methods available; a String constructor and a static `parse(CharSequence)` method;
```
public class MyType {

    private static final ConcurrentMap<CharSequence, MyType> cache = new ConcurrentHashMap<>();
    private String value;

    private MyType(CharSequence raw, boolean cached) {
        if (cached) {
            this.value = "Cached: " + raw;
        } else {
            this.value = "Constructor: " + raw;
        }
    }

    public MyType(String raw) {
        this(raw, false);
    }

    public static MyType parse(CharSequence raw) {
        MyType cached = cache.get(raw);
        if (cached == null) {
            cached = new MyType(raw, true);
            MyType previous = cache.putIfAbsent(raw, cached);
            if (previous != null) {
                cached = previous;
            }
        }
        return cached;
    }

    @Override
    public String toString() {
        return value;
    }
}
```
In MP Config 1.3, the String constructor would have been used to do the implicit conversion. In version 1.4, the `parse(CharSequence)` method will be used instead. Notice that the `parse` method uses a simple cache. If the same raw String (String extends CharSequence) is converted twice then the same instance of MyType will be returned. This would not be possible with a String constructor.

We have also made a noteable internal change to the Open Liberty implementation. In versions prior to 1.4, our implementation included a background update thread which frequently scanned through the available ConfigSources and cached the results. This made calls to the Config API very fast. However, since the size and complexity of user provided ConfigSources is unknown, this was a potentially expensive thing to be doing in the background.

The background update thread has been replaced with an expiry process. What this means is that the first request for a property may be a little slower as it may need to go through all the available ConfigSources to find a value. Once found, this value is then cached and a timer started to expire the cache. If a second request is made for that property before the cache expires then the cached value is used and will return quickly. In order to maintain the same dynamic characteristics of the previous versions, the expiry time is set to only 500ms. This value may be increased by setting the `microprofile.config.refresh.rate` system property. 500ms is the minimum expiry time allowed but if the property is set to 0 or less then caching is disabled.

**Comment by tevans78** [comment]
This needs some code snippets added before it can be used for the GA blog post.

**Comment by Emily-Jiang** [comment]
Looks good!

**Comment by Joseph-Cass** [comment]
LGTM!

SPAG:
Also in many cases -> Also, in many cases
noteable -> notable

**Comment by yasmin-aumeeruddy** [comment]
Thanks
