### ISSUE TITLE
FAT Approval Test Summary

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#10800]
**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature.

If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by utle** [comment]
We are waiting for all of the core security code in the master and we will deliver another FAT PR hopefully this week. After deliver another FAT PR.  The core security FAT is ok with 4)

**Comment by pnicolucci** [comment]
`<httpSession cookieSameSite="lax|strict|none|disabled"/>` tests:

1) testSameSiteSessionCookie_Disabed() : Test the following configuration:
`<httpSession cookieSameSite="Disabled"/>
Ensure that the Set-Cookie header for the Session Cookies does not contain a SameSite attribute

2) testSameSiteSessionCookie_InvalidValue(): Test the following configuration:
`<httpSession cookieSameSite="InvalidValue"/>`
Ensure the logs contain the following:
`CWWKG0032W: Unexpected value specified for property [cookieSameSite], value = [InvalidValue]. Expected value(s) are: [Lax][Strict][None][Disabled]. Default value in use: * [Disabled].`
Ensure no SameSite attribute was found for the Session Cookie.

3) testSameSiteSessionCookie_Lax(): The the following configuration:
`<httpSession cookieSameSite="Lax"/>`
Ensure that the SameSite=Lax attribute was found for the Session Cookie.

4) testSameSiteSessionCookie_MixedCaseValue(): Test the following configuration:
`<httpSession cookieSameSite="Lax"/>`
Ensure that SameSite=Lax attribute was found for the Session Cookie.

5) testSameSiteSessionCookie_None_Not_Secure(): Test the following configuration:
`<httpSession cookieSameSiite="None"/>`
Ensure that the SameSite=None attribute was found for the Session Cookie as well as ensure that
the Secure attribute was added automatically even though it was not specified in the httpSession configuration.

6) testSameSiteSessionCookie_None_Secure(): Test the following configuration:
`<httpSession cookieSameSiite="None" cookieSecure="true"/>`
Ensure that the SameSite=None attribute was found for the Session Cookie as well as ensure that the Secure attribute was also set since it was explicitly configured in the httpSession configuration.

7) testSameSiteSessionCookie_NothingSpecified(): Do not set any `<httpSession/>` configuration and ensure that no SameSite attribute was found for the Session Cookie.

8) testSameSiteSessionCookie_Strict(): Test the following configuration:
`<httpSession cookieSameSite="Strict"/>`
Esure that the SameSite=Strict attribute was found for the Session Cookie.

9) testSameSiteSessionCookie_UniqueName(): Test the following configuration:
`<httpSession cookieName="uniqueSessionIdCookieName" cookieSameSite="Lax"/>`
Ensure that the Session Cookie named "uniqueSessionIdCookieName~ contains the
SameSite=Lax attribute. This tests the non default cookie name which is "JSESSIONID".

**Comment by ayoho** [comment]
# SSO Testing Strategy

Determining the features and flows that could be affected by the SameSite behavior is non-trivial, so work is still ongoing to identify what all we want to test and how far it makes sense to go.

We're working on identifying the situations in which cookies are required to successfully complete SSO flows. That includes JWT-SSO, OAuth, OIDC, SAML, and social login.

#### Considerations

- Does any particular `sameSiteCookie` setting change existing behavior for golden path flows?
- Multiple features require or allow URLs to be configured in server.xml
    - Many of the URLs could be non-HTTPS
    - If those endpoints are expected to carry cookies that we need, the `sameSiteCookie` setting could cause interactions with those endpoints or overall flows to break

### Automated test changes

- `com.ibm.ws.security.openidconnect.client_fat.jaxrs`
    - `OidcJaxRSSameSiteTests`
        - Runs through an OIDC golden path flow with various server configurations
        - Three servers involved in the flow (RP, OP, and an RS)
        - Tests were added for all combinations of `<webAppSecurity sameSiteCookie="<value>"` in all three of the servers
            - sameSiteCookie: Disabled, None, Lax, Strict
            - Total of 64 tests
        - Ensures the golden path OIDC flow works

### Manual tests

We're not planning on relying on any manual tests, but I did want to document any that we happened to have done so far.

#### Social login

1. `sameSiteCookie=“None”` + HTTP redirect URL
    - RP: `sameSiteCookie=“None”`, `redirectToRPHostAndPort=“http://localhost:8941”`
    - OP: `sameSiteCookie=“None”`
    - Get 401 when completing the authentication flow because the `WASReqUrlSocial` cookie isn’t sent

1. `sameSiteCookie=“None”` + HTTP redirect URL + Reconfig in the middle of the flow
    - RP: `sameSiteCookie=“None”`, `redirectToRPHostAndPort=“http://localhost:8941”`
    - OP: `sameSiteCookie=“None”`
    - Try to hit the protected resource
    - When the form login page is presented, reconfigure RP to `sameSiteCookie=“Lax/Strict/Disabled”`
    - Continue logging in
    - Get 401 when completing the authentication flow because the `WASReqUrlSocial` cookie isn’t sent

**Comment by Zech-Hein** [comment]
# Core Security Tests

We are adding automated tests to: 
- `com.ibm.ws.webcontainer.security_fat`
  - `ConfigurableOptionsTest`

The changes are currently in the delivery pipeline.  
  
server.xml configuration: `<webAppSecurity sameSiteCookie="Lax|Strict|None|Disabled"/>` 

**Tests:**
1. testConfigOptionsFL_sameSiteCookieStrict() : Test the following configuration:
`<webAppSecurity sameSiteCookie="Strict"/>`
  ensure that the SameSite=Strict attribute is found in the Set-Cookie header for the SSO Cookie.
2. testConfigOptionsFL_sameSiteCookieDisabled() : Test the following configuration:
  `<webAppSecurity sameSiteCookie="Disabled"/>`
  ensure that the SameSite attribute is not found in the Set-Cookie header for the SSO Cookie.
3. testConfigOptionsFL_sameSiteCookieBadValue() : Test the following configuration:
  `<webAppSecurity sameSiteCookie="BadValue"/>`
  ensure that the SameSite attribute is not found in the Set-Cookie header for the SSO Cookie.
4. testConfigOptionsFL_sameSiteCookieNoneSetsSecure() : Test the following configuration:
  `<webAppSecurity sameSiteCookie="None"/>`
  ensure that the SameSite=None attribute is found in the Set-Cookie header for the SSO Cookie.
  Also ensure the Secure attribute is found in the Cookie.

**Comment by dave-waddling** [comment]
Hi all,

Thanks for updating the Feature Test Summary - all looks good and the testing described (so far) seems sufficient.

I understand that there is an amount of testing still to be delivered and this feature needs to be shipped in 20.0.0.3 so my expectation is that this won't get a FAT Focal Approval so that the feature remains open until the testing has been delivered.

I've assessed the testing which has been delivered at this time which I'll break down by bucket:
- com.ibm.ws.webcontainer.servlet.4.0_fat (@pnicolucci) is passing well for the most part but I've opened defect 272784 for what seems to be a sporadic failure.
- com.ibm.ws.security.openidconnect.client_fat.jaxrs (@ayoho) I can't find a PR containing any changes to this bucket so will assume it's yet to be delivered.
- com.ibm.ws.webcontainer.security_fat (@Zech-Hein) sounds like the changes are in progress.

I'll keep an eye on this issue for updates over the coming days to try and keep an eye on quality as the rest of the testing is delivered.

**Comment by pnicolucci** [comment]
@dave-waddling all of the tests have been delivered now by the  Security team. We are ready for your review. Please let us know if you have any questions.

**Comment by pnicolucci** [comment]
According to @utle  comment security should be good with :

**Comment by Zech-Hein** [comment]
No objection, I am in agreement

**Comment by dave-waddling** [comment]
Hi all,

Many thanks for the updates. Everything is now looking good, the testing is all passing cleanly and definitely seems sufficient. 

However, part of the FAT Focal Approval process includes ensuring that the functional area for the feature has no defects overdue for triage. For this feature I believe that this should actually apply to two functional areas: Security and Web Comps. Please can you let me know when these defects have been triaged and I will add the approval at that time.

**Comment by dave-waddling** [comment]
Hi all,

Thanks for focusing on the defect triage; the backlogs are looking much better! I'll add the FAT Focal Approval to the parent epic now.
