### ISSUE TITLE
Add ability to set a Cookie Attributes in ltp and jwt Cookies

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#10808]
- Proposed: <webAppSecurity ssoCookieSameSite=Lax"/>

- Ensure the metaType uses an Enum. `Lax,None,Strict,Disabled` 

- Determine default value or if we just don't set SameSite by default like we do today.

- WebContainer to provide a way for the SameSite attribute value to be passed to them from where the addCookie call is made on the Response object in #10820

- Ensure that if SameSite=None is specified Secure is also set on these Cookies. I don't think you have any existing metaType to allow this  specification so we should set the Cookie secure when SameSite None is configured. If you do have a configuration for `Secure` let me know and we can discuss further.

- Ensure jwt / ltpa covered here.

**Comment by chunlongliang-ibm** [comment]
1. add sameSiteCookie attribute to <webAppSecurity ...>.
2. The sameSiteCookie has four values, Lax,None,Strict,Disabled, similar to https://github.com/OpenLiberty/open-liberty/pull/10829

        <AD id="sameSiteCookie"
            name="%same.site.cookie"
            description="%same.site.cookie.desc"
            required="false" type="String" default="Disabled" ibm:beta="true">
            <Option label="%same.site.cookie.disabled" value="Disabled"/>
            <Option label="%same.site.cookie.lax" value="Lax"/>
            <Option label="%same.site.cookie.none" value="None"/>
            <Option label="%same.site.cookie.strict" value="Strict"/>
        </AD>

# The word SameSite should not be translated
same.site.cookie=Include SameSite attribute in web security cookies
same.site.cookie.desc=Specifies the SameSite attribute value to use for web security cookies.
same.site.cookie.disabled=Do not set a SameSite attribute value on the web security cookies
same.site.cookie.lax=Set the session cookie SameSite attribute value to Lax
same.site.cookie.none=Set the session cookie SameSite attribute value to None same.site.cookie.strict=Set the session cookie SameSite attribute value to Strict

**Comment by chunlongliang-ibm** [comment]
@utle , as discussed, please update the metadata first, and get metadata checked in by this Friday

**Comment by chunlongliang-ibm** [comment]
1. we will get metaType update first.
2. Subsequent runtime code change:
Based on the value of sameSiteCookie, set the reqState to proper value prior to creating cookie, as shown in this sample code

   WebContainerRequestState reqState = WebContainerRequestState.getInstance(true);
   reqState.setAttribute("SameSite", ssAttValue);
   response.addCookie(cookie);

**Comment by utle** [comment]
Update security code with new metatype: https://github.com/OpenLiberty/open-liberty/issues/10855

**Comment by pnicolucci** [comment]
@ayoho , I removed the epic label here as the "feature/epic" is actually #10086 , I've labeled each of the issues for the components such as this one a `story` and we should add dependent issues for each story as dependencies here. Let me know if you have any questions.

**Comment by utle** [comment]
Core security DEV and FAT are done

**Comment by ayoho** [comment]
Security SSO dev and FATs are also now done.

**Comment by pnicolucci** [comment]
@utle @ayoho @Zech-Hein any objection to closing this issue? Looks like we're completed now including tests.

**Comment by Zech-Hein** [comment]
No objection from me :+1:
