### ISSUE TITLE
BETA BLOG 20.0.0.2 jaxrsMonitor-1.0

### ISSUE THREAD

**Issue by jim-krueger** [OpenLiberty/open-liberty#10839]
a) Which Liberty feature does it relate to?

i) Human-readable name
Metrics for JAX-RS

ii) Feature name
jaxrsMonitor-1.0

iii)Is this a new feature or is it an update to an existing feature for this release?
This is a new feature to support MXBean and MpMetrics statistics for RESTful resource methods.

iv) Provide the fully qualified name of all public features ( as '*.esa' filenames) that are delivered as part of this work
com.ibm.websphere.appserver.jaxrsMonitor-1.0.esa

b) Who is the target audience?
Application developers and administrators.

c) What does this feature provide in general? Write a sentence or two that introduces it to someone new to the concept.

As a RESTful service developer or administrator, I want to track service metrics so that I can 
better understand the usage patterns and performance of my services.

d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)

JaxRSMonitor-1.0 introduces the capability to collect statistics related to the execution of an application's RESTful resource methods (specifically the number of invocations and the cumulative execution time.  This data is useful for design, debug, and monitoring purposes.
These metrics can be accessed via the jaxrsMonitor-1.0 feature in combination with the mpMetrics-2.3 feature (see https://github.com/OpenLiberty/open-liberty/issues/10769 for details).  This information is also accessible via JMX (JConsole, etc.).

e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.
Include the following in the server.xml:

For JMX/PMI access:
<feature>jaxrsMonitor-1.0</feature>

For mpMetrics access:   See https://github.com/OpenLiberty/open-liberty/issues/10769 

The JMX/PMI data collected is per-method and is aggregated to the class and web module level.  For example, suppose a server has two web modules, each with identically named classes containing two resource methods, the results for the REST_Stats in jconsole will look like the following:
![image](https://user-images.githubusercontent.com/31767744/74287160-ebc97f80-4cee-11ea-862a-f388468f6a7d.png)

f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

https://github.com/OpenLiberty/open-liberty/issues/8620
https://github.com/OpenLiberty/open-liberty/pull/9202
https://github.com/OpenLiberty/open-liberty/pull/10450

g. Attach any images to this work item as .png files

**Comment by jim-krueger** [comment]
This feature has been moved to GA under PR https://github.com/OpenLiberty/open-liberty/pull/11219

This changes jaxrsMonitor-1.0 from a stand-alone public feature in the Beta to an auto-feature under the monitor-1.0 feature in 20.0.0.4 GA

**Comment by jim-krueger** [comment]
Not sure if I should close this.   Leaving open for now.

**Comment by lauracowen** [comment]
Is the information above still relevant? There's more info above than we published in the beta: https://openliberty.io/blog/2020/02/14/preview-microprofile-3-3-20002.html#fault

If the GA is targeted at 20.0.0.4 and there needs to be info about it (changes to monitor feature?) in that release blog post, can you tag this and make sure it appears in the GA query listed here: https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/Wde4b45b770c2_47cd_9d6d_7061f359add9/page/Blog%20and%20Beta%20Content

If nothing it needed, can you comment then close. Thanks

**Comment by jim-krueger** [comment]
@lauracowen last week I created https://github.com/OpenLiberty/open-liberty/issues/11244 for the GA.   I've added the Blog label to it now so it shows up on your list.   I will close this beta blog issue now.
