### ISSUE TITLE
Incorrect test logic is performing a null assertion on a boolean condition

### ISSUE THREAD

**Issue by peterbroadbent** [OpenLiberty/open-liberty#10844]
There are instances in the test code where the following e.g. assertion is made:

```
assertNotNull( result != null );
```
This will always be true, as a `boolean `condition will never be `null`.

**Comment by peterbroadbent** [comment]
PR: https://github.com/OpenLiberty/open-liberty/pull/10842

**Comment by wtlucy** [comment]
The incorrect assertions have been fixed in `jsf.2.3_fat` and `jsfContainer.2.3_fat`.
