### ISSUE TITLE
JakartaEE: Milestone 2.0: Automate transform

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#10939]
Automate transformation of of initial servlet function in prototype environment:

1) Invoke transformer as gradle task
2) TransformCopy web container bundle jars
3) Add WebProfile9 features
4) Add JakartaEE9 API jars
5) Demonstrate running servlet test application

**Comment by volosied** [comment]
Closing as this milestone was reached earlier this year.
