### ISSUE TITLE
GA BLOG: #10022 Support OpenShift service account credentials for authentication

### ISSUE THREAD

**Issue by ayoho** [OpenLiberty/open-liberty#10952]
a. **Which Liberty feature does it relate to?**

i. **Human-readable name (eg WebSockets feature)**

  `socialLogin-1.0`

ii. **Feature name (eg websockets-1.0)**

  `socialLogin-1.0`

iii. **Is this a new feature or is it an update to an existing feature for this release?**

  Update to an existing feature: new configuration element to support new capabilities.

b. **Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc**

  Application Developers and appserver administrators

c. **Write a sentence or few that introduces it to someone new to the general technology/concept.**

  The `socialLogin-1.0` feature allows applications to be secured by using popular social media OAuth and OpenIDConnect providers, and supports configuration for additional providers.

d. **What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)**

  The `socialLogin-1.0` feature can now be configured to use OpenShift service accounts to authenticate and authorize protected resource requests. This allows server administrators to secure, for example, monitoring and metrics endpoints that might produce sensitive information but require repeated access by an automated process or non-human entity. The new behavior allows service accounts to authenticate themselves by providing in the request a service account token that was created within the OpenShift cluster.

e. **Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.**

  A new `<okdServiceLogin>` configuration element is now provided to support this behavior. The `socialLogin-1.0` feature must be enabled to gain access to this new element.

  The minimum configuration requires only that an `<okdServiceLogin>` element be specified:

  ```XML
  <server>

  <!-- Enable features -->
  <featureManager>
    <feature>appSecurity-3.0</feature>
    <feature>socialLogin-1.0</feature>
  </featureManager>

  <okdServiceLogin />

  </server>
  ```
  
  The minimum configuration assumes that the Liberty server is packaged and deployed within an OpenShift cluster. By default, the `<okdServiceLogin>` element will be used to authenticate all protected resource requests that the Liberty server receives.

  Incoming requests to protected resources must include a service account token. The token must be specified as a bearer token in the `Authorization` header of the request. The Liberty server will use the service account token to query information about the associated service account from the OpenShift cluster. The OpenShift project that the service account is in will be used as the group for the service account when making authorization decisions. Similarly, the name of the service account will be used as the user name.

  If the Liberty server is not deployed within an OpenShift cluster, the `userValidationApi` attribute should be configured and set to the value for the appropriate User API endpoint in the OpenShift cluster:

  ```XML
  <okdServiceLogin userValidationApi="https://cluster.domain.example.com/apis/user.openshift.io/v1/users/~" />
  ```

  Multiple `<okdServiceLogin>` elements can be configured as long as each element has a unique `id` attribute specified. In those cases, authentication filters should also be configured to ensure the appropriate endpoints are protected by a unique `<okdServiceLogin>` instance.

f. **Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.**

More information about OpenShift service accounts can be found in the OpenShift documentation for [Understanding and creating service accounts](https://docs.openshift.com/container-platform/4.3/authentication/understanding-and-creating-service-accounts.html).

g. **Attach any images to this work item as .png files.**

N/A

**Comment by yasmin-aumeeruddy** [comment]
Thanks
