### ISSUE TITLE
NPE in wlp 20.0.0.2 createSSLCertificate and IBM Java 8.0.6.5

### ISSUE THREAD

**Issue by tcherel** [OpenLiberty/open-liberty#10957]
createSSLCertificate command fails with the following message (but no stack trace):
`Error: java.lang.NullPointerException`

Adding `-Xdump:java+system:events=throw,filter=java/lang/NullPointerException` to the JVM_ARGS is producing two separate javacore files included below.
Second one seems more interesting and showing the following:

```
4XESTACKTRACE                at java/lang/ProcessBuilder.start(ProcessBuilder.java:1023)
4XESTACKTRACE                at java/lang/Runtime.exec(Runtime.java:631)
4XESTACKTRACE                at java/lang/Runtime.exec(Runtime.java:496)
4XESTACKTRACE                at com/ibm/ws/crypto/certificateutil/keytool/KeytoolCommand.executeCommand(KeytoolCommand.java:131)
4XESTACKTRACE                at com/ibm/ws/crypto/certificateutil/keytool/KeytoolSSLCertificateCreator.createDefaultSSLCertificate(KeytoolSSLCertificateCreator.java:49)
4XESTACKTRACE                at com/ibm/ws/security/utility/tasks/CreateSSLCertificateTask.handleTask(CreateSSLCertificateTask.java:191)
4XESTACKTRACE                at com/ibm/ws/security/utility/SecurityUtility.runProgram(SecurityUtility.java:131)
4XESTACKTRACE                at com/ibm/ws/security/utility/SecurityUtility.main(SecurityUtility.java:167)
```

**Steps to Reproduce**
- Fresh wlp 20.0.0.2 install (kernel version)
- export KEYSTORE_PASSWORD=$(openssl rand -hex 32)
- ./wlp/bin/server create
- ./wlp/bin/installUtility install --acceptLicense defaultServer
- ./wlp/bin/securityUtility createSSLCertificate --password=$KEYSTORE_PASSWORD --server=defaultServer

**Diagnostic information:**
 - OpenLiberty Version: [e.g. 20.0.0.2]
 - Java Version:
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 8.0.6.5 - pxa6480sr6fp5-20200111_02(SR6 FP5))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200108_436782 (JIT enabled, AOT enabled)
OpenJ9   - 7d1059c
OMR      - d059105
IBM      - c8aee39)
JCL - 20200110_01 based on Oracle jdk8u241-b07
 - server.xml 
default one when creating a server

**Additional context**
It works fine with IBM Java 8.0.6.0.

[javacore.20200219.172613.1347.0002.txt](https://github.com/OpenLiberty/open-liberty/files/4226413/javacore.20200219.172613.1347.0002.txt)
[javacore.20200219.172613.1347.0004.txt](https://github.com/OpenLiberty/open-liberty/files/4226414/javacore.20200219.172613.1347.0004.txt)

**Comment by tcherel** [comment]
We need to adopt 20.0.0.2 fairly quickly due to some of recent security vulnerabilities that it is fixing.
So if there is some sort of worakround that we can use, I am interested.
I guess running they keytool command directly is one option but I am not exactly sure what command (which keytool options) will be executed by createSSLCertificate and it does anything else under the cover.

**Comment by tcherel** [comment]
Adding the `--extInfo="SAN=dns:localhost"` option to the createSSLCertificate command is making it work.
Seems to be a viable workaround.

**Comment by jvanhill** [comment]
@acdemyers - Has this issue been addressed by the mentioned PR?

**Comment by acdemyers** [comment]
@jvanhill Yes it has
