### ISSUE TITLE
FAT Approval Test Summary for JAAS login modules loaded from resource adapters/applications

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#10963]
**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature.

If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

Created login modules and added new tests across various buckets in order to cover a broad range of scenarios for placement of login modules within resource adapters and applications.

#### com.ibm.ws.jca_fat

This test bucket creates a standalone resource adapter, which, in addition to the normal resource adapter classes, has a JAR that is packaged within the resource adapter, and another JAR that is packaged inside of the first JAR.  We have added login modules to both of those JARs - the one within the other JAR, and that JAR within the resource adapter, then added two login module configurations, one with the name of the login module class from the first JAR and one with the name of the login module class from the second JAR, both with a classProviderRef to the resource adapter.  Then, added the following tests:

testLoginModuleInJarInRar - testLoginModuleInJarInRar - Look up a JMS connection factory using a resource reference that specifies to use a login module that is packaged within a JAR within a standalone RAR. Check the JMS provider name (to which the fake resource adapter appends the user name) to confirm that the login module is used.

testLoginModuleInJarInJarInRar - Look up a JMS connection factory using a resource reference that specifies to use a login module that is packaged within a JAR within another JAR within a standalone RAR. Check the JMS provider name (to which the fake resource adapter appends the user name) to confirm that the login module is used.

#### com.ibm.ws.jca_fat_derbyra

Added a login module to an existing resource adapter in the same location as other the implementation classes of the resource adapters connection factories and so forth.  Configure a login module with classProviderRef set to the resource adapter.

testCustomLoginModuleInRARCF - verify that the user name of the meta associated with a connection from a connection factory that is configured to use the login module matches the user name that is assigned by the login module.

#### com.ibm.ws.jca_fat_enterpriseApp

Wrote a new resource adapter that we embed within the existing enterpriseApplication from the test, alongside the other embedded resource adapter, to which we add a different new login module.  This covers the possibility that when configuring a classProviderRef to be the id of an application, the desired login module could be within any one of the embedded resource adapters.

testConnectionFactoryUsesLoginModule - Verify that a connection factory that is obtained from the loginModRA resource adapter has the user name that is assigned by its login module.

testDataSourceUsingLoginModule - Verify that the user computed by the login module is used by the JCA data source when the resource reference indicates to use the login module.

#### com.ibm.ws.jdbc_fat_loadfromapp

Added 2 EJB modules to one of the test applications, each with a login module of its own.
Added login module to the web module of the application.
Also added a top level JAR to the application containing a login module.

testLoginModuleFromEJBInWebApp - verify that a login module that is packaged within the web application can be used by an EJB within the web application to authenticate to a data source when its resource reference specifies to use that login module.

testLoginModuleFromEJBModule1 - verify that a login module that is packaged within an EJB module is used to authenticate to a data source when its resource reference specifies to use that login module.

testLoginModuleFromEJBModule2 - verify that a login module that is packaged within an EJB module is used to authenticate to a data source when its resource reference specifies to use that login module.  Similar to the previous test, but verifies that the login module from EJB module 2 is used instead of the one from EJB module 1.

testLoginModuleFromOtherAppNotFoundInWebApp - verify that a login module that is packaged within a separate enterprise application that does not match the classProviderRef CANNOT be used to authenticate to a data source when its resource reference specifies to use that login module.

testLoginModuleFromTopLevelJarInApp - verify that a login module that is packaged within a JAR at the top level is used to authenticate to a data source when its resource reference specifies to use that login module. Attempt this from the web module and both EJB modules.

testLoginModuleFromOtherApp - verify that a login module that is packaged within another application can be used to authenticate a data source that is defined in the current web application, where its resource reference specifies to use that login module.

testLoginModuleFromWebApp - verify that a login module that is packaged within the web application can be used to authenticate to a data source when its resource reference specifies to use that login module.

testLoginModuleFromWebAppNotFoundInOtherApp - verify that a login module that is packaged within a separate web application that does not match the classProviderRef CANNOT be used to authenticate to a data source when its resource reference specifies to use that login module.

testLoginModuleFromWebModuleInEAR - verify that a login module that is packaged within a web module within an enterprise application can be used to authenticate to a data source when its resource reference specifies to use that login module.

testWebInboundLoginModuleFromWebApp - log in with the default login module for web inbound traffic, for which the location of the login module class is configured via classProviderRef.

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by dave-waddling** [comment]
Hi @njr-11,

Thanks for completing the Feature Test Summary. Having reviewed all is looking good and the testing is passing cleanly in the latest SOE; I'll add the FAT Focal Approval to the parent epic now.
