### ISSUE TITLE
in openidConnectServer-1.0, discovery endpoints for app-password, app-token rest endpoints are wrong.

### ISSUE THREAD

**Issue by brutif** [OpenLiberty/open-liberty#10994]
A user reported:

I noticed that the endpoint URLs for /app-passwords and /app-tokens in the /.well-known/openid-configuration response is wrong:
 
   "app_passwords_endpoint":"https://localhost:9643/oidc/endpoint/jazzop/app_passwords",
  "app_tokens_endpoint":"https://localhost:9643/oidc/endpoint/jazzop/app_tokens",
 
Underscores are used instead of hyphens.

We need to check and update so they match the endpoints if they are incorrect.

**Comment by ezhou365** [comment]
closed with #11521
