### ISSUE TITLE
`value` and `defaultValue` in `variable` statements are not evaluated in `include` statements

### ISSUE THREAD

**Issue by maxveit** [OpenLiberty/open-liberty#10992]
**Describe the bug**
`value` and `defaultValue` in `variable` statements are not evaluated in `include` statements.

**Steps to Reproduce**
Use the following `server.xml`:
```
<server description="Test server">
    <featureManager>
        <feature>microProfile-3.2</feature>
    </featureManager>
    <variable name="TEST_VAR" value="test-include"/>
    <include optional="false" location="includes/${TEST_VAR}.xml"/>
    <webApplication id="test" name="test" location="test.war" contextRoot="test"/>
</server>
```
You will find a log statement saying:
```
[INFO] [ERROR   ] CWWKG0090E: The includes/${TEST_VAR}.xml configuration resource does not exist or cannot be read. 
```

**Expected behavior**
I would expect that the variable is evaluated and set to the value in the variable statement, such that the include is loaded from:
`includes/test-include.xml`
The same behavior applies for the `defaultValue` statement.
The expected behavior is described here: https://openliberty.io/docs/ref/config/serverConfiguration.html in the chapter "Variable substitution".

**Diagnostic information:**
 - OpenLiberty Version: Open Liberty 20.0.0.2/wlp-1.0.37.cl200220200204-1746
 - Java Version: 
```
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)
```
 - server.xml configuration: see above

**Additional context**
The behavior I am trying to implement is, that I have two configurations available, where one is included by default and the other one only if the variable is set from the outside. So for my use-case the "defaultValue" issue is most relevant.

**Comment by brutif** [comment]
I'll chime in with another case too:  if a variable has no defined value, the defaultvalue attribute will not be substituted.
```xml
    <variable name="myvar"  value="coffee" />
    <variable name="defineme" defaultvalue="${myvar}" />

[ERROR   ] CWWKG0092E: A value attribute or defaultValue attribute 
must be specified for the variable on line 18 of resource file:
/Users/bruce/tmp/liberty/20001_gmc/wlp/usr/servers/vbug/server.xml
```
