### ISSUE TITLE
Allow mapping of mpConfig property names

### ISSUE THREAD

**Issue by matthewpwilson** [OpenLiberty/open-liberty#11026]
**Is your feature request related to a problem? Please describe.**
A number of Microprofile features mandate a specific naming convention for mpConfig properties e.g. mpReactiveMessaging prefixes all properties with mp.message, and URLs mpRestClient are of the form <className>/mp-rest/url.   However, deployment environments often provide configuration parameters in specific environment variables. For example, Appsody service binding sets environment variables of the form <namespace>_<service-name>.   So it's not possible to inject configuration from the deployment environment e.g. REST endpoint URIs into the mandated mpConfig properties. 

**Describe the solution you'd like**
Allow a mapping of an mpConfig property to another property of an arbitrary name. 
For example 
```
com.example.MyClass/mp-rest/url=${NAMESPACE_REMOTE_SERVICE}
```
would set the property `com.example.MyClass/mp-rest/url` from the property `NAMESPACE_REMOTE_SERVICE`.  
This allows me to set the property based on an arbitrary environment variable provided in the deployment environment. 

**Describe alternatives you've considered**

**Additional context**

**Comment by tevans78** [comment]
MP Config 1.3 allows environment variables to be defined using `_` rather than other chars...
```
The ConfigSource for the environment variables searches three environment variables for a given property name (e.g. com.ACME.size):
    Exact match (i.e. com.ACME.size)
    Replace each character that is neither alphanumeric nor _ with _ (i.e. com_ACME_size)
    Replace each character that is neither alphanumeric nor _ with _; then convert the name to upper case (i.e. COM_ACME_SIZE)
```
So you could set an environment variable to be
`com_example_MyClass_mp_rest_url=$NAMESPACE_REMOTE_SERVICE`

and that would be found when the application searched for `com.example.MyClass/mp-rest/url`

**Comment by tevans78** [comment]
More generally, what you are asking for is this...
https://github.com/eclipse/microprofile-config/issues/118
