### ISSUE TITLE
ignoreApplicationAuthMethod not working in mpJwt when HttpAutenticationMechanism is active

### ISSUE THREAD

**Issue by eweitlaner** [OpenLiberty/open-liberty#11058]
**Describe the bug**
The injected JsonWebToken is always null if a HttpAutenticationMechanism is active. The Rest-Call does not use the JWT Header. If the HttpAutenticationMechanism is deactivated everything works fine. The MP-JWT Attribute ignoreApplicationAuthMethod seems to be ignored.

**Steps to Reproduce**
- Configure mpJwt, and make a REST Call with a valid JWT Authorization Token (works).
Use HttpAuthenticationMechanism, implement the validateRequest Method and make the same REST Call, the injected JwtWebToken is null ..

**Expected behavior**
The JsonWebToken should be available with <mpJwt id="myMPJWT" .... ignoreApplicationAuthMethod="true">

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.2
 - Java Version:
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Windows 10 amd64-64-Bit Compressed References 20200122_442 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)

 - server.xml 
```XML
<?xml version="1.0" encoding="UTF-8"?>
<server>
	<featureManager>
		<feature>webProfile-8.0</feature>
		<feature>mpJwt-1.1</feature>
	</featureManager>
	<httpEndpoint host="*" httpPort="${server.httpPort}" httpsPort="${server.httpsPort}" id="defaultHttpEndpoint" remoteIpRef="defaultRemoteIp" />
	<include location="${liberty.server.file}"/>
	<include location="${db.datasources.file}" />
	
	<mpJwt id="myMPJWT" jwksUri="${dvt.jwksUri}"
		issuer="https://anmeldung.tirol.gv.at" ignoreApplicationAuthMethod="true">
	</mpJwt>

	<ssl id="defaultSSLConfig" keyStoreRef="defaultKeyStore" trustStoreRef="defaultTrustStore" trustDefaultCerts="true"/>
</server>
```

**Comment by ayoho** [comment]
@arkarkala Would you guys be able to create a test case for this scenario? It could be that this is related to behavior in the JSR-375 implementation and that this would be an issue whether you had MP-JWT, a TAI, or whatever else configured down the line. It might be good to have a test case for this that we could add MP-JWT into to see how this would work.

**Comment by arkarkala** [comment]
Per JSR375, if an HTTPAuthenticationMechanism is configured in the app (i.e annotated) it should be called first. We need to discuss this scenario more and update this issue.

**Comment by ayoho** [comment]
@eweitlaner It sounds like this is actually working as designed. Just as Ajay said, if the application has an `HttpAuthenticationMechanism` configured, that mechanism will be called before MP JWT (or really any other feature) comes into play at all. The JSR-375 code takes over handling the request and isn't going to pass it on to the MP JWT logic. That's why you're not seeing the `ignoreApplicationAuthMethod` MP JWT configuration attribute make any difference.

If that's not satisfactory, would you be able to provide a little bit more detail about your application's configuration and more information about what you're trying to do?

**Comment by eweitlaner** [comment]
Hello. Thank you for your attention to this issue.

Our Usecase: 
We implement a web application with a shibboleth identity provider and a self implemented HttpAuthenticationMechanism which works great on OpenLiberty. This application should now provide a small REST Interface (on a special URL) which uses backend functionallity and should be authorized with a JsonWebToken. Unfortunately even if the HttpAuthenticationMechanism sends AuthenticationStatus.NOT_DONE for the REST Url, there is no further processing and no JsonWebToken can be used. The ignoreApplicationAuthMethod in the mpJwt config sounds like this should be possible?

Today I implemented a workaround which consumes the JWT Authorization Header in the HttpAuthenticationMechanism and notifies the container.  Works, but in our view the mpJwt feature parallel to the HttpAuthenticationMechanism would be great.

**Comment by c-koell** [comment]
Hi .. i am a coworker of @eweitlaner. I have attached a very simple project that should illustrate our usecase.

The TestWebAuthenticationMechanism  should handle a "normal" login into the web application.
It checks if a specific header value is present and returns a valid AuthenticationStatus.
On the other hand there is the SampleRestEndpoint which will be called from a other resource with a valid jwtToken.
If a request (with a valid jwtToken) comes to the SampleRestEndpoint, the TestWebAuthenticationMechanism does not find the specific header value and returns AuthenticationStatus.NOT_DONE (httpMessageContext.doNothing()).

The jwtToken will not be validated and therefore it is not valid injected in the SampleRestEndpoint.
We thought this is a valid scenario and therefore we configured in the server.xml 
<mpJwt id="myMpJwt" ignoreApplicationAuthMethod="true"...>

So at the moment if the TestWebAuthenticationMechanism returns AuthenticationStatus.NOT_DONE the jwtToken will not be validated.

You will find the Classes and the server.xml in the attached zip file.
[testweb.zip](https://github.com/OpenLiberty/open-liberty/files/4265787/testweb.zip)

As @eweitlaner mentioned we have implemented a workaround but we think it is not really satisfying.

**Comment by c-koell** [comment]
Any Update Here ?

**Comment by arkarkala** [comment]
Thanks for the details. It helps.
However, as mentioned earlier, when the custom HttpAuthMechanism (HAM) is configured in the application it is called to authenticate the user and other auth methods are not trigged. When the AuthenticationStatus.NOT_DONE is returned by the HAM, it is assumed the authentication was successful (as per spec) and no additional authentication happens. The ignoreApplicationAuthMethod has no impact when HAM is used.
wrt to your workaround, are you creating the Principal (containing the jwtToken) and passing it to the notifyContainer method? If so, are you making sure that the jwtToken is validated before the notifyContainer is called by using jwtConsumer as in 
JwtToken jwtToken = jwtConsumer.createJwt("Base64_encoded_JWT_token>"); ?

**Comment by c-koell** [comment]
So does this mean that if a HAM is used mpJWt can not be used ? If so you should change the documentation about ignoreApplicationAuthMethod. At the moment it says "Ignore the configured authentication method in the application"

To our workaround, we have configured a jwtConsumer.
`<jwtConsumer id="myMPJWT" issuer="https://anmeldung.tirol.gv.at" jwkEnabled="true" jwkEndpointUrl="${dvt.jwksUri}"></jwtConsumer>` 
and in the HAm we have implemented following

```
if (request.getHeader(HttpHeaders.AUTHORIZATION)) != null && request.getHeader(HttpHeaders.AUTHORIZATION).startsWith("Bearer ")) {
  JwtConsumer jwtConsumer = JwtConsumer.create("myMPJWT");
  JwtToken jwtToken = jwtConsumer.createJwt("<Base64_encoded_JWT_token>");
  CustomJwtTokenPrincipal principal = new CustomJwtTokenPrincipal(jwtToken);
  Set<String> groups = new HashSet<>((List<String>) jwtToken.getClaims().get("groups"));
  return httpMessageContext.notifyContainerAboutLogin(principal, groups );
}
```

So is the workaround the official way in such a scenario ? As mentioned before a declarative way would be your preferred scenario ...

**Comment by ayoho** [comment]
As far as I'm aware, no, MP JWT cannot be used in conjunction with a HAM. We can look at updating the description for the `ignoreApplicationAuthMethod` configuration attribute.

As far as your workaround goes, that _looks_ like it'd be about the right way to go about validating the JWT within your HAM. That is, getting the JWT from the Authorization header, verifying it, and using it to create a Principal is basically what the MP JWT feature would have done.

**Comment by c-koell** [comment]
Just for clarification, what Authentication Method will be ignored with ignoreApplicationAuthMethod ?

**Comment by ayoho** [comment]
Sorry about the delay in response. Any authentication methods that are configured in the application’s deployment descriptor will be ignored by the MP JWT feature when `ignoreApplicationAuthMethod="true"`. This does not apply, however, to any `HttpAuthenticationMechanism` that might be programmatically included in the application. If there is an `HttpAuthenticationMechanism` present in the application, it will supersede the MP JWT feature in accordance with the JSR-375 specification.

**Comment by c-koell** [comment]
Thank you for the information ! I think we can close this issue

greets
