### ISSUE TITLE
Better loose application XML syntax?

### ISSUE THREAD

**Issue by hrstoyanov** [OpenLiberty/open-liberty#1108]
The [Loose Application](https://www.ibm.com/support/knowledgecenter/en/SS7K4U_liberty/com.ibm.websphere.wlp.zseries.doc/ae/rwlp_loose_applications.html) idea is a very clever one and allows to cut down the redeploy time during development a lot. However, I think it the allow XML syntax need to be extended to allow for exclusions:

```
<dir targetInArchive="/META-INF"  
        sourceOnDisk="${example.dir}/applicationData/myApplication" >
       <exclude name="**/*Test*"/>
</dir>
```

The [Ant FileSet](https://ant.apache.org/manual/Types/fileset.html) provides a good design that you may borrow from.

To illustrate the issue, here are the "tricks" I have to do when constructing my WAR in order to deal with some bad dependencies in my Gradle:

```
//Only add jar files to the war that we know we will need at runtime!
war {
    duplicatesStrategy 'exclude'
    classpath configurations.warLib
    classpath = classpath.filter { file ->
        (!file.name.startsWith('javaee-api')
                && !file.name.startsWith('javax')
                && !file.name.startsWith('junit')
                && !file.name.startsWith('hamcrest')
                && !file.name.startsWith('gwt-slf4j')
                && !file.name.startsWith('dom4j')
                && !file.name.startsWith('guava-gwt')
                && !file.name.startsWith('jgroups')
                && !file.name.startsWith('j2objc')
                && !file.name.startsWith('error_prone')

                //Exclude Errai client side jars
                && !file.name.startsWith('errai-cdi-client')
                //&& !file.name.startsWith('errai-jaxrs-client')
                && !file.name.startsWith('errai-navigation')
                //&& !file.name.startsWith('errai-codegen')
                && !file.name.startsWith('errai-ui')
                && !file.name.startsWith('errai-data-binding')
        )
    }
    rootSpec.exclude('**/com/recres/web/gwt/client/')
}
```

I am not even sure how to translate this to loose app without exclusions? 

Also see [Issue #167](https://github.com/WASdev/ci.gradle/issues/167) in the [Gradle plug-in](https://github.com/WASdev/ci.gradle) project.

Thanks

**Comment by aguibert** [comment]
Hi @hrstoyanov, interesting idea, although I think this issue would be more properly solved in the build tool layer.  To address the 2 use cases you brought up:

1. Excluding test classes (i.e. `**/*Test.class`)
Normally application classes are compiled into one dir (e.g. bin/) and test classes are compiled into a separate dir (e.g. bin_test/), so having this separation of app vs. test output folders would resolve this use case.

2. Including/excluding various maven dependencies from the app
I don't know what your `warLib` configuration looks like, but I'm guessing all of your dependencies are `compile` type?  If you want to include a maven dependency at compile time only, and not package the dependency into the war, you can use the `provided` dependency type.<br>
Specifically, see this bit from the gradle docs:  https://docs.gradle.org/current/userguide/war_plugin.html
```javascript
configurations {
   moreLibs
}

dependencies {
    ///// these get packed into the war /////
    compile module(":compile:1.0") {
        dependency ":compile-transitive-1.0@jar"
        dependency ":providedCompile-transitive:1.0@jar"
    }
    ///// These do not /////
    providedCompile "javax.servlet:servlet-api:2.5"
    providedCompile module(":providedCompile:1.0") {
        dependency ":providedCompile-transitive:1.0@jar"
    }
    runtime ":runtime:1.0"
    providedRuntime ":providedRuntime:1.0@jar"
    testCompile "junit:junit:4.12"
    moreLibs ":otherLib:1.0"
}

war {
     ...
    classpath configurations.moreLibs // adds a configuration to the WEB-INF/lib dir.
}
```

**Comment by hrstoyanov** [comment]
@aguibert Thanks for the response!
Sorry for the somewhat confusing post, and let me clarify why I think we need exclusions. As I mentioned you can exclude certain .class files in WEB-INF/classes with the WAR plugin in Gradle:
```
war {
     ...
    rootSpec.exclude('**/com/recres/web/gwt/client/')
}
```

I need the above as I am using GWT/Erraiweb  client framework. It "transpiles"  Java->JavaScript, after which all client .class code is not needed in the produced WAR bundle (which now includes the generated JS instead).

How do you do that with the loose application XML format and prevent OL from even looking at these client .class files?


As far as your example with ```compile``` and ```providedCompile``` configurations, very strange things happen if an artifact A.jar is in both configurations - its transitive dependencies (A.jar->B.jar) are removed, which is perhaps not what you expected (or documented by Gradle). Therefore, I used the flexibility of the WAR plugin to directly decide what gets bundled and goes in WAR-INF/lib.

**Comment by aguibert** [comment]
Hmm, I've never heard of "transpiling" Java -> JS before, but it seems like the proper thing to do would be to delete the unused .class files directly after the gradle `compile` step (e.g. `compile.doLast`)

> How do you do that with the loose application XML format and prevent OL from even looking at these client .class files?
You can indirectly achieve an exclude by using fine-grained includes, for example:
```xml
<dir targetInArchive="/WEB-INF/classes/com/foo/my/package"  
        sourceOnDisk="/path/to/build/classes/com/foo/my/package" >
</dir>
```
However, there is not currently a way to exclude files via loose xml config.

As for the maven dependencies, I know that "provided" dependencies would prevent the war plugin from packaging the libs in the war.  I'm not sure why strange things happen when you try to move deps into "provided" scope, but perhaps that is something the maven folks can help out with.

**Comment by hrstoyanov** [comment]
Thanks , I was thinking about the same workaround.

If you need for info on "transpilers", just google GWT and JSweet
