### ISSUE TITLE
Support Java EE 8 XML schemas

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#1109]
The official set of EE8 schemas can be found here: 
http://www.oracle.com/webfolder/technetwork/jsc/xml/ns/javaee/index.html#8

We need to update places such as `com.ibm.ws.javaee.ddmodel.app.ApplicationAdapter` to tolerate version 8 schema.

Additionally, we should test each schema in the javaee.8.0_fat (or in the respective feature FATs)

**Comment by tbitonti** [comment]
Working notes:

[schemas.txt](https://github.com/OpenLiberty/open-liberty/files/1834755/schemas.txt)

**Comment by tbitonti** [comment]
This issue completed the parser code, and added javaee8 feature definitions.  Additional work for reviewing and completing the feature definitions is removed from this issue and moved to the new issue #3141 "EE8 feature definition completion".

**Comment by tbitonti** [comment]
Delivered: pull request #2843
