### ISSUE TITLE
Make MicroProfile Reactive Messaging work with AWS SNS

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#11115]
This is related to #10813 . This connector is to enable working with AWS SNS. This will lead to consume
https://github.com/smallrye/smallrye-reactive-messaging/tree/master/smallrye-reactive-messaging-aws-sns

**Comment by abutch3r** [comment]
Smallrye have deprecated AWS SNS connector, as such we should require an explicit requirement to do a connector for it, as such closing this issue
