### ISSUE TITLE
Enable MP RM to work with Vert.x Event Bus

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#11120]
This is related to #10813. This connector is to enable working with Vert.x event bus. This will lead to consume
https://github.com/smallrye/smallrye-reactive-messaging/tree/master/smallrye-reactive-messaging-vertx-eventbus

**Comment by hutchig** [comment]
Does this cover clustered (inter-process/machine) bus too?

**Comment by abutch3r** [comment]
Smallrye have deprecated their Vert.x Event bus. Given both how heavy this is related to Vert.x core and its threading model and the fact that Smallrye/Quarkus decided this was not something they themselves would support. This is not something we should at this time think about considering
