### ISSUE TITLE
GA BLOG: Allow the SameSite attribute to be set on a Cooki

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#11145]
------
GA

This information will be published in the blog post and used in Alasdair's webcast to announce what’s new in this release.

If the exact information you want to give is already in a previous blog post:
a. Provide a link to the post(s), specify exactly which sections are relevant, and any updates required or to make it more interesting.
b. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.
 

---

If not previously published in a blog post, please answer the following questions:

a. Which Liberty feature does it relate to?

   i. Human-readable name (eg WebSockets feature)

> Adding the SameSite cookie attribute.

   ii. Feature name (eg websockets-1.0)

> N/A

   iii. Is this a new feature or is it an update to an existing feature for this release?

> This is a new feature.

b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc

> application developers, application server administrators

c. Write a sentence or two that introduces it to someone new to the general technology/concept.

> The Servlet [javax.servlet.http.Cookie](https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/Cookie.html) API does not offer the ability to set the SameSite attribute on a Cookie. If the SameSite attribute is needed, the options for setting it are currently limited to using the [HttpServletResponse.addHeader](https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpServletResponse.html#addHeader-java.lang.String-java.lang.String-) and [HttpServletResponse.setHeader](https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpServletResponse.html#setHeader-java.lang.String-java.lang.String-) and constructing the Set-Cookie header.

The SameSite attribute is used by Browsers to determine if a particular cookie should be sent with a request. There are three values for the SameSite attribute: Lax, Strict, None.

- SameSite=Strict: The cookie will only be sent along with same-site requests. The cookie is only sent by the browser if the site for the cookie matches the site in the address bar for example.

- SameSite=Lax: The cookie will be sent with same-site requests and with cross-site top-level navigations. Clicking a link for example.

- SameSite=None: The cookie will be sent with same-site and cross-site requests. The cookie is sent by the browser for third party contexts, embedded content for example.

d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)

> Open Liberty now offers the ability to set the SameSite attribute on the Session cookie, the LTPA, and JWT cookies as well as application-defined cookies. The SameSite attribute can be added by adding one or more server.xml configuration options.

e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.
1) Set the Session Cookie SameSite attribute using the following server.xml configuration:
`    <httpSession cookieSameSite="Disabled|Strict|Lax|None"/>`
The default value is "Disabled". This means no SameSite attribute will be added.
2) Set the LTPA/JWT Cookie SameSite attribute using  the following server.xml configuration:
`    <webAppSecurity sameSiteCookie="Disabled|Strict|Lax|None"/>`
The default value is "Disabled". This means no SameSite attribute will be added.
3) Set the SameSite attribute on Cookies via the following server.xml configuration:
```
    <httpEndpoint id="defaultHttpEndpoint"
                  httpPort="9080"
                  httpsPort="9443" >
        <samesite lax="cookieOne" strict="cookieTwo" none="cookieThree"/>
    </httpEndpoint>
```
 The `<httpEndpoint/>` SameSite configuration allows the use of wildcards in the following ways:

1. A standalone wildcard (`*`). All cookies would have the `SameSite=Lax` attribute. This includes the Session and LTPA/JWT cookies unless the `<httpSession/>` and/or `<webAppSecurity/>` configuration has also been set.
```
    <httpEndpoint id="defaultHttpEndpoint"
                  httpPort="9080"
                  httpsPort="9443" >
        <samesite lax="*" />
    </httpEndpoint>
```

2. At the end of one or more cookie names. The below snipped would map the following cookie name to SameSite attributes: 

- cookieOne -> SameSite=Lax
- cookieTwo -> SameSite=Strict
- cookieThree -> SameSite=None

```
    <httpEndpoint id="defaultHttpEndpoint"
                  httpPort="9080"
                  httpsPort="9443" >
        <samesite lax="cookie*" strict="cookieTwo" none="cookieThree"/>
    </httpEndpoint>
```

 The `<httpSession/>` and `<webAppSecurity/>` configuration takes precedence over the `<httpEndpont/>`configuration. 

When a cookie matches the SameSite=None configuration then the Secure attribute will be automatically added to the cookie.

The `<httpEndpoint/>` configuration can apply to any Set-Cookie header.

f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.
Technical details regarding the SameSite attribute can be found in the following RFC: [Cookies: HTTP State Management Mechanism](https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-03#section-4.1.2.7)

g. Attach any images to this work item as .png files.

**Comment by tomjenningss** [comment]
Hi @pnicolucci  what is `Browers`? I assume you mean 'Browsers'?
"The SameSite attribute is used by Browers to determine if a particular cookie should be sent with a request."

**Comment by pnicolucci** [comment]
@tomjenningss  yes you are correct, I made the correction. Thanks for catching that!

**Comment by pnicolucci** [comment]
@tomjenningss I did update a bit of it to be consistent the use of quotes:


- SameSite=Strict: The cookie will only be sent along with same-site requests. The cookie is only sent by the browser if the site for the cookie matches the site in the address bar for example.

- SameSite=Lax: The cookie will be sent with same-site requests and with cross-site top-level navigations. Clicking a link for example.

- SameSite=None: The cookie will be sent with same-site and cross-site requests. The cookie is sent by the browser for third party contexts, embedded content for example.

**Comment by tomjenningss** [comment]
Thank you @pnicolucci I am just updating it now, then the blog should be ready to review

**Comment by pnicolucci** [comment]
@tomjennings, is there a place for me to review the final product? I think  that we should probably change `browsers` to `web browsers`. What do you think?

**Comment by tomjenningss** [comment]
Yes there is @pnicolucci. Link to the document is: https://github.com/OpenLiberty/blogs/blob/0c1d3a6b6b9dc59a5d368e88c286b9e0b941f9e9/drafts/20003.adoc

**Comment by pnicolucci** [comment]
@tomjennings, thanks, can you make one minor update? I'm also writing a standalone blog and would like some of it to match this: https://github.com/OpenLiberty/blogs/pull/293

**Comment by tomjennings** [comment]
sorry all, I'm @tomjennings but you meant to write to @tomjenningss, note
the added second s.
