### ISSUE TITLE
FAT Approval Test Summary

### ISSUE THREAD

**Issue by brenthdaniel** [OpenLiberty/open-liberty#11144]
**1) Testing will focus on various scenarios involving the `startAfter` attribute. Multiple scenarios can be covered by individual tests, but all of these should be exercized:
* A simple two application scenario where one app starts after another
* A more complex scenario with multiple applications using startAfter
* Mixed scenarios where some applications use startAfter and others do not
* Test updating of an application that has a startAfter dependency
* Test updating of an application that is a dependency of another application
* Test updating an application involved in a chain of dependencies
* Test restarting of applications in response to a feature change
* Error scenario: Ensure we get an error when a startAfter chain has cycles
* Error scenario: Ensure we get an error when an application has an invalid startAfter attribute

The tests will be stored in the com.ibm.ws.app.manager_fat bucket, but other existing buckets could also be updated to increase coverage. All testing will be automated. 

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

**Comment by ayoho** [comment]
Coverage looks good to me, and all tests appear to be running well across all supported platforms.
