### ISSUE TITLE
CWWKS5068E error is misleading

### ISSUE THREAD

**Issue by barbj** [OpenLiberty/open-liberty#11208]
**Describe the bug**
This message is being emitted when the NameID element is not in the SAML asertion and there is no user identifier configured:

CWWKS5068E: The SAML assertion does not contain a [user name] attribute.  A [user name] attribute is required.

This is confusing.  The customer is looking for a "user name" element in the SAML token, where there isn't, nor should there be.  I'm assuming that "user name" here should be NameID and it is an element, not an attribute.

I'm assuming that this message really means that you can't pull a user name from the token and that the XXX element is missing (in this case, NameID).

**Steps to Reproduce**
Send a SAMLResponse that does not contain a NameID

**Expected behavior**
Perhaps a message stating the element that was missing.
xxxxxxxx: The SAML assertion does not contain a [NameID] element.  A [NameID] element is required.

**Diagnostic information:**
 - OpenLiberty Version: [e.g. 19.0.0.12]
 - Java Version: [i.e. full output of `java -version`]
 Java(TM) SE Runtime Environment (8.0.6.5 - pxa6480sr6fp5-20200111_02(SR6 FP5) Small Footprint)
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**

**Comment by ezhou365** [comment]
connected with #11320

**Comment by ezhou365** [comment]
completed
