### ISSUE TITLE
Ability to add CDI extensions from a user feature

### ISSUE THREAD

**Issue by ind1go** [OpenLiberty/open-liberty#11212]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to add CDI beans from a user feature in a product extension, that an application can then inject.

`com.ibm.ws.cdi.extension.WebSphereCDIExtension` is used to register such CDI extensions within Liberty but it's not currently SPI available to a user extension so I can't make use of it.

**Describe the solution you'd like**

Could `com.ibm.ws.cdi.extension.WebSphereCDIExtension` be exposed as SPI?

**Describe alternatives you've considered**
Don't know!

**Comment by Emily-Jiang** [comment]
@benjamin-confino can you take a look? It should be an internal SPI, which is available to stack products.

**Comment by benjamin-confino** [comment]
This was done a long time ago.
