### ISSUE TITLE
Create CIS benchmark for Open Liberty

### ISSUE THREAD

**Issue by jtmulvey** [OpenLiberty/open-liberty#11227]
Open Liberty best practices for hardening security in configuration should be codified in a Center for Internet Security (CIS) benchmark (https://www.cisecurity.org/cis-benchmarks/).  This will provide the ability to generate Open Vulnerability Assessment (OVAL) file (https://oval.mitre.org/) that can then be used with things like OpenSCAP to scan/verify Open Liberty configurations. Many large financial institutions and government IT policies now mandate that there be a CIS benchmark available for all middleware/platform software.

**Comment by arkarkala** [comment]
Liberty CIS 1.0 has been delivered - https://workbench.cisecurity.org/benchmarks/7724
