### ISSUE TITLE
EclipseLink: Deliver Bug #548814

### ISSUE THREAD

**Issue by c-koell** [OpenLiberty/open-liberty#11228]
**Describe the bug**
We are using Oracle 19c and facing following bug. https://bugs.eclipse.org/bugs/show_bug.cgi?id=548814

**Steps to Reproduce**
Use Oracle 19c

**Expected behavior**
Update JPA to fix EclipseLink bug [548814](https://bugs.eclipse.org/bugs/show_bug.cgi?id=548814)

**Comment by jgrassel** [comment]
Merged changes into Eclipselink repo https://github.com/eclipse-ee4j/eclipselink/pull/543 (2.6_WAS) and https://github.com/eclipse-ee4j/eclipselink/pull/724 (2.7)

**Comment by c-koell** [comment]
Is that fix in the next 2020.4 Release ?

**Comment by c-koell** [comment]
Can someone tell me in which version the fix will be included ?

**Comment by dazey3** [comment]
@c-koell No, this was not included in fixpack 20.0.0.4. It is planned for inclusion in 20.0.0.5

**Comment by c-koell** [comment]
Was not included ?
The 20.0.0.4 isn't releasd yet ?

**Comment by dazey3** [comment]
> The 20.0.0.4 isn't released yet ?

@c-koell Our internal development cutoffs are different from the official release dates. 20.0.0.4 may not be release yet, but development is complete and this issue will not be included in that release.
