### ISSUE TITLE
GA BLOG 20.0.0.4 jaxrsMonitor-1.0

### ISSUE THREAD

**Issue by jim-krueger** [OpenLiberty/open-liberty#11244]
a) Which Liberty feature does it relate to? 
monitor-1.0

i) Human-readable name
Metrics for JAX-RS

ii) Feature name
jaxrsMonitor-1.0 (auto-feature under monitor-1.0)

iii)Is this a new feature or is it an update to an existing feature for this release?
This is a new auto-feature to support MXBean and MpMetrics statistics for RESTful resource methods.

iv) Provide the fully qualified name of all public features ( as '*.esa' filenames) that are delivered as part of this work
com.ibm.websphere.appserver.jaxrsMonitor-1.0.feature (auto-feature)

b) Who is the target audience?
Application developers and administrators.

c) What does this feature provide in general? Write a sentence or two that introduces it to someone new to the concept.

As a RESTful service developer or administrator, I want to track service metrics so that I can
better understand the usage patterns and performance of my services.

d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)

The jaxrsMonitor-1.0 auto-feature is enabled whenever the jaxrs-2.0 (or jaxrs-2.1) features are specified within the server.xml along with the monitor-1.0 feature.
This auto-feature introduces the capability to collect statistics related to the execution of an application's RESTful resource methods (specifically the number of invocations and the cumulative execution time. This data is useful for design, debug, and monitoring purposes.
RESTful metrics can be accessed via the monitor-1.0 feature in combination with the mpMetrics-2.3 feature (see #10769 for details). This information is also accessible via JMX (JConsole, etc.).

e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.
Include the following in the server.xml:

For JMX/PMI access:
`<feature>jaxrs-2.0</feature> (or jaxrs-2.1)`
`<feature>monitor-1.0</feature>`

For mpMetrics access: See #10769

The JMX/PMI data collected is per-method and is aggregated to the class and web module level. For example, suppose a server has two web modules, each with identically named classes containing two resource methods, the results for the REST_Stats in jconsole will look like the following:
![image](https://user-images.githubusercontent.com/31767744/76341705-6922e880-62cb-11ea-9816-bdbf6ff295a8.png)

f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

#8620
#9202
#10450
#11219

g. Attach any images to this work item as .png files

**Comment by yasmin-aumeeruddy** [comment]
Thanks
