### ISSUE TITLE
Unexpected user registry requirement when login with jwtsso cookie

### ISSUE THREAD

**Issue by chunlongliang-ibm** [OpenLiberty/open-liberty#11262]
Configure both openidConnectClient-1.0 and jwtSso-1.0 without user registry. First time login works fine. However, while cookie is still valid, if server is restarted, user is forced to relogin again while the correct behavior is user should be able to be authenticated with existing cookie.

Looking at trace, we can see jwtsso code correctly asserts com.ibm.wsspi.security.cred.uniqueId for login module, seems login module did not propagate the attribute properly, and forces user registry lookup. 

I can provide trace, or standalone test case to recreate the problem. Whoever works on this defect can contact me. I also want to test potential fix.

**Comment by chunlongliang-ibm** [comment]
got a patch from Ut Le, and problem fixed

**Comment by chunlongliang-ibm** [comment]
@utle problem resolved with the patch. The jwtsso cookie survives server restarting

**Comment by utle** [comment]
https://github.com/OpenLiberty/open-liberty/pull/11297
