### ISSUE TITLE
JakartaEE: JSP 3.0 Feature Support

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#11275]
This issue covers the feature file changes required for liberty to run jsp-3.0.

**Comment by volosied** [comment]
Completed, but now I am enabling the jsp 2.3 fat to run with the jsp-3.0 feature.

**Comment by pnicolucci** [comment]
I'm going to close this issue in favor of using https://github.com/OpenLiberty/open-liberty/issues/11717 to track the remaining work.
