### ISSUE TITLE
JPA FAT: Add test case that tests JPA using the javaee8 feature 

### ISSUE THREAD

**Issue by jgrassel** [OpenLiberty/open-liberty#1127]
The JPA FATs test declaring the jpa-2.2 feature, should have a test case that uses the javaee8 convenience feature.

**Comment by aguibert** [comment]
@jgrassel this issue can probably be closed -- we already test JPA with the `javaee-8.0` and `webProfile-8.0` feature in the com.ibm.ws.javaee.8.0_fat bucket

**Comment by tkburroughs** [comment]
Per Andy's update; closing out.
