### ISSUE TITLE
mvn is still not in the system path of the FAT test machines

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#1130]
I was testing the solution to #343 which requires 'mvn' to be on the FAT child build path and get: 

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_7XGDMNToEeeEtKxTXP6tcw&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider

java.io.IOException: 2017-11-29-16:29:53:762 Cannot run program "mvn" (in directory "publish/tckRunner"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1059)
	at org.eclipse.microprofile.config.tck.ConfigTckPackageTest.runCmd(ConfigTckPackageTest.java:88)
	at org.eclipse.microprofile.config.tck.ConfigTckPackageTest.testCustomConfigSourceProvider(ConfigTckPackageTest.java:58)
	at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:175)
	at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:316)
	at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:152)

This FAT test works locally on cd dev && 
./gradlew com.ibm.ws.microprofile.config_fat_tck:clean  && ./gradlew com.ibm.ws.microprofile.config_fat_tck:buildandrun

but if I change my launch string to be with the addition of CHEESE on top: 
        mvnCliRoot = new String[] { "mvnCHEESE", "clean", "test", "-Dwlp=" + wlp, "-Dtck_server=" + server.getServerName(),
                                    "-Dtck_port=" + server.getPort(PortType.WC_defaulthost) };

I get the same message:
./results/junit.html/org/eclipse/microprofile/config/tck/0_FATSuite.html:<code>java.io.IOException: 2017-11-30-10:20:44:295 Cannot run program "mvnCHEESE" (in directory "publish/tckRuunner"): error=2, No such file or directory<br>    at java.lang.ProcessBuilder.start(PProcessBuilder.java:1048)<br>        at com.ibm.ws.microprofile.tck.Utils.runCmd(Utils.java:60)<br>  at org.eclipse.microprofile.config.tck.ConfigTckPackageTest.testTck(ConfigTckPackageTest.java:55)<br>     at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:175)<br>
./results/output.txt:java.io.IOException: Cannot run program "mvnCHEESE" (in directory "publish/tckRunner"): error=2, No such file or directory

So I conclude that 'mvn' is still not on the path of the FAT machines as is needed to fix 343.

I have chatted to Kevin Smith and Chris Webster about this and Chris reckons he can
see that the problem is in the $PATH of the FAT machine environment having a non substituted ${}
(miss-spelt of missing) environment variable for the mvn directory.

**Comment by mhldr** [comment]
This should be resolved by CL1130 where the machines are set up. The location was defined inside a task that was antcalled, when we returned from that task the location was forgotten (as antcall is designed to do) before we'd persisted that location in our path.

**Comment by hutchig** [comment]
Testing in personal build... then I will close.

**Comment by hutchig** [comment]
Needs to be able to access Artifactory repo too....Cog Test are looking at it.

**Comment by hutchig** [comment]
Fixed now.
