### ISSUE TITLE
openidconnect client requires https for discovery even when httpsRequired="false" is set.

### ISSUE THREAD

**Issue by brutif** [OpenLiberty/open-liberty#11307]
An internal user reports that discovery cannot be made to work over http.  It might be a typo in the attribute, or a bug.

**Comment by ayoho** [comment]
The internal customer requesting this was able to work around this by specifying the necessary endpoints (authorization, token, jwk) in the OIDC client config. It's generally recommended to use HTTPS for pretty much everything, so the HTTPS check for discovery will remain in place for now. I'm going to go ahead and close this issue.
