### ISSUE TITLE
FAT Approval Test Summary for LG-254: Console.log should have a date/time timestamp

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/open-liberty#11324]
**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature.

If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

New FAT tests were added in the com.ibm.ws.logging_fat project, under the ConsoleFormatTest test suite, which tests for the following test scenarios:

1. testDynamicSimpleFormat - This test dynamically changes the consoleFormat from dev to simple and vice-versa, and verifies if new messages are in the new correct format.

2. testInvalidConsoleFormat - This test sets the "consoleFormat" attribute to an invalid value and verifies if the appropriate warning message is displayed and checks that the default format is applied.

3. testDeprecatedBasicConsoleFormat - This test sets the "consoleFormat" attribute to the deprecated basic console format and verifies if the appropriate warning message is displayed and checks that the default format is applied.

4. testSimpleFormatSetInBootstrapProperties - This test sets the "consoleFormat" attribute to simple in the bootstrap.properties and verifies the correct format in the console.log file.

5. testInvalidConsoleFormatSetInBootstrapProperties - This test sets the "consoleFormat" attribute to an invalid format in the bootstrap.properties and starts the server and verifies the correct default dev format in the console.log file.

6. testSimpleConsoleFormatWithIsoDateFormat - This test sets both simple console format and isoDateFormat=true and verifies if the message is formatted correctly.

7. testSimpleConsoleFormatWithSysOutSysErrMsgs - This test sets consoleFormat=simple and verifies if SystemOut and SystemErr messages are formatted correctly.

8. testSimpleConsoleFormatWithException - This test sets consoleFormat=simple and generates an exception and verifies if the exception is not trimmed/suppressed are formatted correctly.

9. testSimpleFormatSetInEnv - This test sets the "consoleFormat" attribute to simple as Environment Variables via the server.env file and verifies the correct format in the console.log file.

In addition to the above test scenarios, existing FAT test in com.ibm.ws.logging.json_fat and com.ibm.ws.security.audit_fat.config that tests the messageFormat/consoleFormat default names, were updated as well, to comply with the new default format names.

Manual testing of the above test cases were also done, to ensure an extra level of verification.

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

4
The current automated testing that we have, adequately tests a broad spectrum of scenarios offered by this feature from the updated FAT project.

**Comment by ayoho** [comment]
@pgunapal I suppose it's not strictly limited or related to this feature, but are there any tests for the behavior when a console format value is specified in both bootstrap.properties and the server.xml? Which setting is supposed to take precedence?

**Comment by pgunapal** [comment]
@ayoho Currently, we only have tests that tests for scenarios that tests when it is configured in the bootstrap.properties, they are dynamically updated in the server.xml, after the server has started (Check test cases in com.ibm.ws.logging.json_fat.JsonConfigTest). I don't believe we have test cases that tests the specified logging configuration attributes (message/console formats) in both bootstrap.properties and server.xml, before server start up.

I believe in that particular case, the server will output logs in the format that is specified in the bootstrap.properties file during initial server start up phase, and once the server.xml file gets read, it will switch the format to the one configured in the server.xml for the rest of the server lifecycle.

Do you want me to add the test case, as part of this feature? or should I create a follow-on item to address it later on, as there are multiple server configuration logging configuration attributes, that may have to be tested for this scenario?

**Comment by ayoho** [comment]
@pgunapal I think I'd like to see a follow-on item opened for that particular case. I believe the testing that you have is sufficient for this feature and I can see the tests are running well, so I'm happy to approve the feature as it is now. But I think the bootstrap.properties + server.xml test case is an interesting one and could warrant its own test, so adding it at some point down the line might be nice.

**Comment by ayoho** [comment]
I've gone ahead and added the `focalApproval:fat` label to the feature epic.

**Comment by pgunapal** [comment]
Thanks! Created a follow-on item (https://github.com/OpenLiberty/open-liberty/issues/11358) to address it.
