### ISSUE TITLE
JakartaEE: PackageRename: Connectors spec (previously JCA) implementation

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#11330]
User story:
"As a developer, I want to use Jakarta EE Connector spec API from Jakarta EE 9 in my application so that it is ready to take advantage of enhancements in Jakarta EE 10 when that eventually becomes available."
"As an administrator, I want applications to continue to run with JCA 1.7 (and 1.6) so that I don't need to migrate apps to Jakarta EE."

**Comment by KyleAure** [comment]
Added FAT approval test summary to #12969 
Closing this issue as GA of feature will be done under #9876
