### ISSUE TITLE
Update documentation for MP Config 1.4

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#11333]
This page in the knowledge center has some information about how our MP Config implementation caches values which is no longer valid for MP Config 1.4 and needs updating.

https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/cwlp_microprofile_overview.html

This information needs to be updated to cover the new behaviour.

**Comment by tevans78** [comment]
The docs issue is https://github.ibm.com/was-liberty/liberty-docs/issues/1816

**Comment by Azquelt** [comment]
The external documentation has now been updated.
