### ISSUE TITLE
Defining config_ordinal in server.xml has no effect on config properties

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/open-liberty#11357]
**Describe the bug**
I am using the mpconfig-1.3 feature, which allows you to add configuration variable values to the Liberty server's server.xml file as a \<variable> or \<appProperty>\< property> element.  I tried to change the config_ordinal of the variable elements by including a config_ordinal \<variable> element in my server.xml. 

`<variable name="config_ordinal" value="120"/>`

This had no effect.  It did not advance the precedence of the \<variable> element setting above that of the \<appProperty>\< property> element or that of a value set in another configuration file like bootstrap.properties that had a config_ordinal of 700 set.

**Steps to Reproduce**
1. Set a config variable in your bootstrap.properties file.  Also set a value for the same property as a \<variable> element and as an \<appProperties>\<property> element in your server.xml file.
2. Start your application and you will see that the value for the \<appProperties>\<property> element is used because it has the highest config ordinal value (600).
3. Set `config_ordinal=700` in bootstrap.properties.
4. Restart your application and you will see that the config variable is getting its value from bootstrap.properties since it now has the highest config_ordinal.
5. Add a config_ordinal setting to the server.xml file as a \<variable> element with a value of 800.
6. Restart your application and the config variable still equals that set in the bootstrap.properties file.  It does not appear that the setting a config_ordinal value for the \<variable> element in server.xml had any effect.

**Expected behavior**
I expect that if I set a \<variable> element for `config_ordinal` in the Liberty server.xml file, that mpconfig would elevate the precedence of this config source above that of \<appProperties>\<property> settings or other settings in other config sources for a variable.

Referencing: https://github.com/OpenLiberty/open-liberty/issues/2683

**Additional context**
I am updating the mp-config-intro guide for the additional features added for mpconfig-1.3.
I am using the sample application associated with the mp-config-intro guide to test:
https://openliberty.io/guides/microprofile-config-intro.html

**Comment by mbroz2** [comment]
Fixed by https://github.com/OpenLiberty/open-liberty/issues/14377
