### ISSUE TITLE
Metrics are exposed in the format that is not compliant with Prometheus spec

### ISSUE THREAD

**Issue by emyes** [OpenLiberty/open-liberty#11364]
Getting below exception while parsing the metrics that is available in path **/metrics** . I'm using prometheus-to-cloudwatch agent to scrap the metrics from my open liberty based microprofile application and to push cloudwatch.   During this process i'm getting below exceptions 

 **second TYPE line for metric name "base_gc_total", or TYPE reported after samples.** .  It looks like issue is due to duplication of the metric names which is mentioned below

base_gc_total
base_gc_time_seconds

Attached the complete metrics that is available in /metric path of the application
[CompleteAvailableMetrics.txt](https://github.com/OpenLiberty/open-liberty/files/4349039/CompleteAvailableMetrics.txt)

**Comment by Channyboy** [comment]
HI @emyes thanks for point that out!

There _should_ be two metrics with the same name (as your JVM is tracking two garbage collectors)
e.g.
`base_gc_total{name="G1**Young**Generation"} 0.254`
`base_gc_total{name="G1**Old**Generation"} 0`

But there **_shouldn't_** be two `TYPE` lines.

**Comment by emyes** [comment]
Agreed @Channyboy .  Is something that needs to be fixed ?  
 Do we have any workaround for that ?

**Comment by emyes** [comment]
Hi All,
 Good day.

 Getting similar kind of exception while processing vendor metrics as well.  
Resource path= /metrics/vendor
 
Exception logs :
 reading text format failed: text format parsing error in line 19: second TYPE line for metric name "vendor_session_invalidated_total", or TYPE reported after samples

Attached complete available metrics under /metrics/vendor path. 

[VendorLibertyMetrics.txt](https://github.com/OpenLiberty/open-liberty/files/4367884/VendorLibertyMetrics.txt)

**Comment by Channyboy** [comment]
Hi @emyes  

Yes this will  need to be fixed.

May I ask are you using a driver that you built your own or have downloaded off the https://openliberty.io/ site?

And unfortunately there isn't a  configurable work-around.

**Comment by emyes** [comment]
Hi @Channyboy , 

 Thanks for the response. I'm not understanding your question. Could you please tell me what do you mean by driver here ?

**Comment by Channyboy** [comment]
@emyes  Hi sorry, i meant to ask if you built Open Liberty from the repository/code or you downloaded it.

**Comment by emyes** [comment]
Hi @Channyboy , Downloaded it from OpenLiberty.  20.0.0.1 liberty version.

**Comment by Channyboy** [comment]
@emyes  
The PR is waiting to be merged.

**IF using for production:**
The fix would be included in 20.0.0.5

**IF using for testing/experimenting:**
- There would be daily drivers/builds available and i will update with a link when available.

**Comment by emyes** [comment]
@Channyboy  Thanks for the update.  Appreciated !

**Comment by emyes** [comment]
@Channyboy  : Could you please share the link where i can download the latest driver to test this changes, If it is available ?

**Comment by emyes** [comment]
@Channyboy :  Could you please advise when 20.0.0.5 version will be released ?
