### ISSUE TITLE
JakartaEE: Enable EE9 RepeatTests in WebContainer Servlet 4 FAT

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#11370]
Enablement of JakartaEE versions of the servlet.4 FAT tests.

Current Status: 
4/20 -- All tests enabled for EE9 except for _testSameSiteConfig_Lax_WebAppSecurity_Strict_

**Comment by volosied** [comment]
All servlet 4 fat tests, except for WCSameSiteCookieAttributeTests, have been enabled to run with EE9 Features. 

There is an issue with the tests, which is being fixed in this PR -- https://github.com/OpenLiberty/open-liberty/pull/11710/files

**Comment by volosied** [comment]
PR #11710 was merged -- closing issue
