### ISSUE TITLE
Liberty API that is written in terms of Java EE interfaces

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#11390]
User story:
"As a Liberty user, I want IBM API that relies on Java EE interfaces to continue working when I transform my Java EE app into a Jakarta EE app."

It needs to be determined what the expectations are for the JavaEE/Jakarta transformation tool around IBM API that includes Java EE classes?

For example, a security feature has this API package,
```
IBM-API-Package: com.ibm.wsspi.security.auth.callback; type=“ibm-api”, \
```

A couple of the classes in this package declare interface methods that use JCA spec types as parameters and results types.  For example:
```
/com.ibm.ws.security.jaas.common/src/com/ibm/wsspi/security/auth/callback/WSManagedConnectionFactoryCallback.java
```

and here is some of the content of the class,
```
import javax.resource.spi.ManagedConnectionFactory;
import javax.security.auth.callback.Callback;
...
    public void setManagedConnectionFactory(ManagedConnectionFactory managedConnectionFactory) {
    …
    public ManagedConnectionFactory getManagedConnectionFacotry() {
    …
```

Here’s the public JavaDoc for the above,
https://www.ibm.com/support/knowledgecenter/SS7K4U_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.security_1.2-javadoc/com/ibm/wsspi/security/auth/callback/WSManagedConnectionFactoryCallback.html

Will Liberty have 2 versions of the same IBM API interface, one in terms of Jakarta interfaces and the other in terms of Java EE interfaces?  Or does a new IBM API interface need to be created?

It’s difficult to see how we can externalize two conflicting variants of the same interface for a single Liberty release in a way that will make any sense to users.  But if we don’t convert these sort of interfaces, then I could see hardship for customers trying to use the transformation tool on their applications, unless the transformation tool is given built-in awareness of the equivalent Jakarta-based Liberty API.  If we did create a new Jakarta-based Liberty API in these cases, would it be in the same package?  How would we name it that will make any sense to users?  If we put it in a different package, would we move all of the other classes within that API package as well even if some of them don't have dependencies on Java EE?

**Comment by jhanders34** [comment]
This work is being done with #11497
