### ISSUE TITLE
GA BLOG: Support yum/apt-get installs for Liberty

### ISSUE THREAD

**Issue by bensonlatibm** [OpenLiberty/open-liberty#11392]
This information will be published in the blog post and used in Alasdair's webcast to announce what’s new in this release.

If the exact information you want give is already in a previous blog post:
a. Provide a link to the post(s), specify exactly which sections are relevant, and any updates required or to make it more interesting.
b. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.
 

---

If not previously published in a blog post, please answer the following questions:

a. Which Liberty feature does it relate to?

   i. Human-readable name (eg WebSockets feature)
   Support yum/apt-get installs for Liberty
   ii. Feature name (eg websockets-1.0)
   CONT-2: Support yum/apt-get installs for Liberty

   iii. Is this a new feature or is it an update to an existing feature for this release?
   new feature

b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc
appserver administrators
c. Write a sentence or two that introduces it to someone new to the general technology/concept.
Open Liberty is now available as a native linux .deb or .rpm package.  
 
d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)
You can now use native OS tools (yum/apt) to manage your open liberty installations.
 
e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.
See details in comments below
 
f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.
n/a
g. Attach any images to this work item as .png files.

**Comment by bensonlatibm** [comment]
To access openliberty rpms/debs, you'll have to configure your machine to use the openliberty repository.

https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/os-native-packages/deb
https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/os-native-packages/rpm

On Ubuntu systems:

    Append line deb https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/os-native-packages/deb/ /"to file /etc/apt/sources.list
    Add the repositories' public key with command “wget -O http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/os-native-packages/public.key | sudo apt-key add –”
    run command "sudo apt-get update"
    The latest version of Open Liberty can then be installed from the repository by running:
    sudo apt-get install openliberty

On Red Hat Systems:

    Create the following file named "/etc/yum.repos.d/openliberty.repo":
[olrepo]
name=olrepo
baseurl=http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/os-native-packages/rpm/
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/os-native-packages/public.key

Then run the following command after - “yum update” or “yum repolist”
The latest Open Liberty can then be installed by:
sudo yum install openliberty

**Comment by bensonlatibm** [comment]
Linux Service created during rpm/deb install. 

The openliberty.rpm/openliberty.deb will install create an empty defaultServer and configure it to run as a service.
Openliberty services will run as user openliberty.
The server is located in /var/lib/openliberty/usr/servers/defaultServer
Logs will be stored in /var/log/openliberty/defaultServer
PID for server is in /var/run/openliberty/defaultServer.pid

You can use the following standard linux service commands:

systemctl status openliberty@defaultServer.service

systemctl start openliberty@defaultServer.service

systemctl restart openliberty@defaultServer.service

systemctl stop openliberty@defaultServer.service

**Comment by yasmin-aumeeruddy** [comment]
Thanks
