### ISSUE TITLE
Add libraryRef element to mpOpenTracing feature

### ISSUE THREAD

**Issue by ggam** [OpenLiberty/open-liberty#11407]
**Is your feature request related to a problem? Please describe.**
The recommended way to use the Jaeger client for MP OpenTracing (https://openliberty.io/blog/2019/12/06/microprofile-32-health-metrics-190012.html#jmo) pollutes the application classpath with library dependencies, including SLF4J and GSON, which can easily collide with the application ones.

I don't want to share those dependencies with the application.

**Describe the solution you'd like**
Add the `libraryRef` configuration element to the mpOpenTracing feature, so the application doesn't need to see those classes.

**Describe alternatives you've considered**
For Zipkin, the documentation uses a custom feature: https://openliberty.io/guides/microprofile-opentracing.html#enabling-distributed-tracing

Creating  a new feature for this is too much overhead for users IMO, although is the path I'll follow for the moment.

**Comment by fmhwong** [comment]
People who used the Zipkin user feature told us that they don't like to download a separate user feature for tracer backend implementation.  In the Jaeger support, it is integrated inside `mpOpenTracing-1.3`.  Users can add the Jaeger dependencies in the application's pom.xml or use a shared library.  It is easier to use especially in container environment but you're right on the application can see these additional libraries.

**Comment by ggam** [comment]
I've been looking at this a bit more. The difference between Zipkin and Jaeger here is that Liberty provides the `JaegerTracerFactory` for Jaeger, while the user has to implement it on their own for Zipkin. But the overhead of the OSGi bundle that is recomended for Zipkin isn't really needed, as the same can be obtained with a library referenced by a bell: `<bell libraryRef="zipkinLib" />`.

So, with this in mind, I think the best possible design is:

* Make `JaegerTracerFactory` implement `com.ibm.ws.opentracing.tracer.OpentracingTracerFactory`. That way it can be obtained via ServiceLoader. The Jaeger libraries could be bundled on the WAR, or they could be discovered via BELL. Only when Jaeger classes are present, the factory is used.
* Optionally, for consistency, Liberty should also move the custom `ZipkinTracerFactory` to the core, so users only need to add the JARs in whatever form they prefer.

If someone wants more specific behavior, they'd need to implement `com.ibm.ws.opentracing.tracer.OpentracingTracerFactory` on their own and set higher priority for their service implementation.

**Comment by ggam** [comment]
@fmhwong if my understanding is correct, the changes aren't big and I could have a look at it myself and try to provide a PR. Would that contribution be welcomed or do you prefer to implement it based on your own roadmap? Where should I send the CLA?

**Comment by fmhwong** [comment]
@ggam You can find the contribution information at https://github.com/OpenLiberty/open-liberty/blob/integration/CONTRIBUTING.md.

**Comment by ggam** [comment]
@fmhwong I looked there and it contains the CLA but sadly it doesn't explain where should I send it... I'll ask on the OL mailing list.

**Comment by donbourne** [comment]
Closing this one out as I don't think it has progressed in quite a while.
