### ISSUE TITLE
JavaBatch: jobexcutionendtime of current execution is sometimes wrong inside afterJob() of joblistener

### ISSUE THREAD

**Issue by albertwang-ibm** [OpenLiberty/open-liberty#11413]
**Describe the bug**
We created a  joblistener for a partitionized job, Inside afterJob() of the joblistener,  using .getEndTime() for current jobexcution some times return null (which is reasonable, because joblistener runs as part of the job for now), but some times return a timestamp much earlier than when the job is finished. e.g, in some of our job executions, they took hours to finish, but the end time we got here is just few minutes after the job was submitted.

[3/22/20 9:27:52:232 GMT] com.ibm.fhir.bulkimport.ImportJobListener SystemcurrentTimeMillis:1584869272232.   **<--- System.currenttimemillis()**
[3/22/20 9:27:52:280 GMT] com.ibm.fhir.bulkimport.ImportJobListener jobContext.getExecutionId(): 148
[3/22/20 9:27:52:280 GMT] com.ibm.fhir.bulkimport.ImportJobListener **jobExecution.getEndTime().getTime()**: 1584844188644 jobExecution.getStartTime().getTime():1584843981170

**Steps to Reproduce**
Note: this doesn't always happen, it happens sometimes for our long running jobs.
(1) Create joblistener for partitionized job.
     (not sure if the same issue execute for non-partitionized job or not)
(2) Inside afterJob(), use .getEndTime() for current jobexcution.

**Expected behavior**
getEndTime for current execution should always return null, because at this time point, the job is not finished yet because the jobStatus is always "Started" inside afterJob().

**Diagnostic information:**
 - OpenLiberty Version: [e.g. 19.0.0.4]

**Additional context**
None

**Comment by scottkurz** [comment]
I wonder how the job got an end time set while it was executing?   I wonder if the status also went to FAILED?   

In any case, we'd probably need to see some trace or logs:  `com.ibm.jbatch.*=all:com.ibm.ws.jbatch.*=all`
