### ISSUE TITLE
About sprint boot support

### ISSUE THREAD

**Issue by dlwangwj** [OpenLiberty/open-liberty#11411]
Hi,
I see this following link only supports springboot 1.*
https://openliberty.io/blog/2017/11/29/liberty-spring-boot.html
which link support springboot 2.* ?
please kind of suggests. Thanks

**Comment by anjumfatima90** [comment]
Hi, 
We do not support Open Liberty Spring Boot Starter (open-liberty as an embedded server in spring boot application) any more. But we support deploying Spring Boot applications on Open Liberty. The link below provides more information https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_dep_springboot.html

`springBoot-1.5` feature is used to deploy spring boot applications with versions 1.5.* and `springBoot-2.0` feature is used deploy spring boot applications with versions 2.*.*

We also a maven and gradle plugin which helps you deploy your application on open-liberty. Open Liberty guide https://openliberty.io/guides/spring-boot.html#running-the-application-on-open-liberty can help you with this.

Thanks.
