### ISSUE TITLE
EJB Custom Bindings: AmbiguousEJBReferenceException

### ISSUE THREAD

**Issue by brideck** [OpenLiberty/open-liberty#11441]
- Create and bind AmbiguousEJBReferenceException if the same custom name is specified more than once
- Update tests in binding FAT

**Comment by olendvcook** [comment]
com.ibm.ws.ejbcontainer.bindings.noInterface.bnd.web.NoInterfaceBindingAbstractServlet.testNoInterfaceDefaultBindings() is one relevant test after the remote default binding stuff goes in

**Comment by tkburroughs** [comment]
Merged; in Master; Closing
