### ISSUE TITLE
JakartaEE 9: JPA 3.0 Support

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#11449]
Support Jakarta EE 9 : Jakarta Persistence (JPA) 3.0

FAT Summary : #12969

**Comment by samwatibm** [comment]
For release:20009-beta just the JPA 3.0 API was enabled, not JPA container/eclipselink 3.0

**Comment by tkburroughs** [comment]
FAT Complete : https://github.com/OpenLiberty/open-liberty/issues/12969
