### ISSUE TITLE
Can config update without app restart be made possible for connectionManager used by JCA/JMS?

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#11502]
User story:
"As a user of JCA or JMS connection factories, I would like to increase the connection pool size without triggering an application restart in order to avoid extra interruptions in service."

This might not be possible.  OSGi would need to be made to suppress sending the modified signal that causes the deactivate/activate of the connection factory when it sees that the connection manager which it uses has handled a modification.

Adding modified to JCA/JMS connection factories is architecturally impossible and not an option as determined from prior investigations.

https://github.com/OpenLiberty/open-liberty/pull/11483 includes a disabled test case that could be turned on if it were possible to make this work.

**Comment by malincoln** [comment]
Per @njr-11 this is still valid.

**Comment by cbridgha** [comment]
After evaluating the relative priorities and constraints this item is not likely to complete in next 2 years, we are going to close for now - we can revisit if needed.
