### ISSUE TITLE
GA BLOG: mpFaultTolerance-2.1 for 20.0.0.4

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#11505]
Refer to the beta release post:  #10792

**Comment by Azquelt** [comment]
Write the section for FT 2.1 for the 20.0.0.4 release blog post.

**Comment by Joseph-Cass** [comment]
## MicroProfile Fault Tolerance 2.1

* New Feature
* Short name: `mpFaultTolerance-2.1`
* Feature file: `com.ibm.websphere.appserver.mpFaultTolerance-2.1.esa`
* Target audience: application developers and administrators

MicroProfile Fault Tolerance allows developers to easily apply strategies for mitigating failure to their code. It provides annotations which developers can add to methods to use [bulkhead][bulkhead-link], [circuit breaker][cb-link], [retry][retry-link], [timeout][timeout-link] and [fallback][fallback-link] strategies. In addition, it provides an annotation which causes a method to be run [asynchronously][async-link].

MicroProfile Fault Tolerance 2.1 is a minor release which includes the following changes:
*  Adds new parameters `applyOn` and `skipOn` to `@Fallback` and adds `skipOn` to `@CircuitBreaker` to give the user more control over which exceptions should trigger these strategies, for example:

```
@Fallback(applyOn=IOException.class, skipOn=FileNotFoundException.class, fallbackMethod="fallbackForService")
public String readTheFile() { 
    ...
}
```

*  Ensures that the CDI request context is active during the execution of methods annotated with `@Asynchronous`

In addition, this Fault Tolerance release also adds more detail into the Javadoc and makes some minor clarifications to the specification.

### Additional resources

* Get an introduction to MicroProfile Fault Tolerance with the Open Liberty guides
  * [Failing fast and recovering from errors][guide-retry-timeout]
  * [Preventing repeated failed calls to microservices][guide-cb-fallback]
* Reference the [Javadoc][javadoc]
* Reference the full [specification][spec], including the [2.1 release notes][release-notes]
* Report any issues [on Github][ol-repo]

[bulkhead-link]: https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.1/apidocs/org/eclipse/microprofile/faulttolerance/Bulkhead.html
[cb-link]: https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.1/apidocs/org/eclipse/microprofile/faulttolerance/CircuitBreaker.html
[retry-link]: https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.1/apidocs/org/eclipse/microprofile/faulttolerance/Retry.html
[timeout-link]: https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.1/apidocs/org/eclipse/microprofile/faulttolerance/Timeout.html
[fallback-link]: https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.1/apidocs/org/eclipse/microprofile/faulttolerance/Fallback.html
[async-link]: https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.1/apidocs/org/eclipse/microprofile/faulttolerance/Asynchronous.html
[javadoc]: https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.1/apidocs/
[spec]: https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.1/microprofile-fault-tolerance-spec.html
[release-notes]: https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.1/microprofile-fault-tolerance-spec.html#release_notes_21
[guide-retry-timeout]: https://openliberty.io/guides/retry-timeout.html
[guide-cb-fallback]: https://openliberty.io/guides/circuit-breaker.html
[ol-repo]: https://github.com/OpenLiberty/open-liberty/

**Comment by yasmin-aumeeruddy** [comment]
Thanks
