### ISSUE TITLE
Test Failure: org.eclipse.microprofile.metrics.test.MpMetricTest.org.eclipse.microprofile.metrics.test.MpMetricTest

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#11537]
RTC 273436

This seems to fail on JDK14 Hotspot JDKs only.

```
org.eclipse.microprofile.metrics.test.MpMetricTest:java.lang.NoClassDefFoundError: Could not initialize class io.restassured.RestAssured
at org.eclipse.microprofile.metrics.test.MpMetricTest.setup(MpMetricTest.java:132)
```

**Comment by lamkavan** [comment]
PR to fix the issue is here https://github.com/eclipse/microprofile-metrics/pull/565
The tck fails due to an error with not being able to find the rest-assured test dependency from Maven. This only occurs on JDK 14 Hotspot. The PR upgrades the version of rest-assured being used from 4.0.0 to 4.3.0.

**Comment by lamkavan** [comment]
PR to fix issue is here https://github.com/OpenLiberty/open-liberty/pull/11941
