### ISSUE TITLE
Update the integration point on ConfigProviderResolver.setInstance

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#11549]
We have been put the debat on hold regarding removing setInstance on ConfigProviderResolver. A few people challenged to remove it. In preparing of moving away from calling setInstance, we need to use ThreadContextClassLoader to load the impl class. After chatting with @bjhargrave , we can achieve that by doing the following:

1. update our config impl to be the fragment of config api
2. In the fragment, import the impl class package
3. In the fragment, add service loader required file, eg. services/org.eclipse.microprofile.config.spi

**Comment by Azquelt** [comment]
I'm not sure the stuff with the fragment is necessary.

I think we can do this by exporting the implementation package with `thread-context=true` in the bnd file to make the implementation class available on the TCCL and then implementing a ResourceProvider service to add the service loader required file.

It looks like the same thing is done in `com.ibm.ws.microprofile.opentracing.rest.client.1.3` to make a RestClientFilter service loadable.

**Comment by Emily-Jiang** [comment]
I rememeber Rest Client did this but I could not find the record. It seems to be simplier with what @Azquelt said.

**Comment by tevans78** [comment]
We proved that a bundle fragment can work instead of using setInstance - https://github.com/OpenLiberty/open-liberty/pull/11615

**Comment by tevans78** [comment]
Closing this for now. Don't need to do it until the MP Community changes the spec to remove setInstance

**Comment by tevans78** [comment]
The MicroProfile issue is https://github.com/eclipse/microprofile-config/issues/364
