### ISSUE TITLE
SAML SP should use 401 instead of 403 when redirects user to IdP

### ISSUE THREAD

**Issue by chunlongliang-ibm** [OpenLiberty/open-liberty#11595]
AdminCenter secured by SAML might receive a browser exception before redirecting to IDP.

The following line code should be changed to use 401 or 302 instead of 403
TAIResult.create(HttpServletResponse.SC_FORBIDDEN); 
in dev/com.ibm.ws.security.saml.sso/src/com/ibm/ws/security/saml/sso20/sp/Solicited.java

**Comment by brutif** [comment]
closing as 11745 has merged
