### ISSUE TITLE
Try out the new config bundle to see whether it can be activated

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#11598]
https://github.com/eclipse/microprofile-config/pull/381 introduces the java contract in OSGi. However, this PR should make config bundle to start ok as it provides the required capability. We need to pull this PR and build the bundle and give it a go to see whether it can be started. All tests can still pass.

**Comment by Azquelt** [comment]
Steps required:
1. Extract PR branch and build locally
2. Upload the built snapshot to artifactory
3. Update oss_dependencies to include the new snapshot
4. Update the 1.4 API project
  a) use the new snapshot
  b) change `bnd.bnd` to include everything from the snapshot's manifest and use a `bnd.overrides` file.
    - See `com.ibm.ws.org.jboss.weld3` for an example of a project which does this

**Comment by Joseph-Cass** [comment]
I am testing this here: https://github.com/Joseph-Cass/open-liberty/commit/f2158b126dcc744073b2529d6b3e3b111cc94a92

**Comment by tevans78** [comment]
Joe tested this locally and it worked. Closing.
