### ISSUE TITLE
JakartaEE: WebTier Component Support -- Servlet, Websocket, EL, JSTL, JSP, JSF, Channel, & Transport.

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#11609]
This issue is to keep track of the package rename for the following features and any dependencies required for these tasks. 

servlet-4.0 -> servlet-5.0 --- #11819 
websocket.1.1 -> websocket.2.0 --- #11610 
jsf-2.3 - > jsf- 3.0 --- #11611

JSP Epic  - #11717  
EL Epic - #11720 
FacesContainer Epic - ##12234

Channel/Transport -- #11721

In addition, we will enable the corresponding fat buckets. 

com.ibm.ws.webcontainer.servlet.4.0_fat   --- #11370 
com.ibm.ws.jsp.2.3_fat --- #11371
com.ibm.ws.jsf.2.3_fat --- #11612

**Comment by pnicolucci** [comment]
All sub epics are completed. I'm going to close this top-level epic.
