### ISSUE TITLE
acmeCA:2.0: Handle updating the cert when the URI is changed

### ISSUE THREAD

**Issue by kristip17** [OpenLiberty/open-liberty#11601]
We need to handle updating the certificate when the URI is changed.
Paths:
Config update during runtime
Config changed after restart
Revoke/renew requested.

Per discussion, we will need to store the directoryURI in a file in the workarea so we can crosscheck when we restart the server (make sure our certificate is valid for the directoryURI configured). For example, if the customer switches from the test Acme server to the production acme server, we want to get a new certificate. If this change happens during runtime, we can check it on the config update. If this happens when the server is down, we still want to do a new certificate.

We discussed sorting an audit style sort of file

```
Date            Serial           DirectoryURI                AccountURI
------------------------------------------------------------------------------------------------------
20200413120000  6c47dac8316c06dc https://localhost:32815/dir https://localhost:32815/my-account/1 
20200413120500  8abae415ada26a66 https://localhost:32815/dir https://localhost:32815/my-account/1 
```

If a customer runs a --clean, the workarea file will be missing and we'll request a new certificate.

For #9017

**Comment by ryanesch** [comment]
PR https://github.com/OpenLiberty/open-liberty/pull/12119
