### ISSUE TITLE
JakartaEE:  WebSocket 2.0 Support [EPIC]

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#11610]
Top issue for enabling function WebSocket in open-liberty.

Instructions are found in the box note:
https://ibm.box.com/s/4xynu2j1byk2o8qk98rvcbcfl4npgfaq

**Comment by malincoln** [comment]
@volosied  pls add the FAT summary here:  https://github.com/OpenLiberty/open-liberty/issues/12969

**Comment by pnicolucci** [comment]
Delivery completed, closing!
