### ISSUE TITLE
SSL HANDSHAKE FAILURE

### ISSUE THREAD

**Issue by HanithaKrishnaraj** [OpenLiberty/open-liberty#11613]
CWPKI0823E: SSL HANDSHAKE FAILURE:  A signer with SubjectDN [CN=*.azure.net] was sent from the host [<hostname>:443].  The signer might need to be added to local trust store [/opt/ol/wlp/output/defaultServer/resources/security/key.p12], located in SSL configuration alias [defaultSSLConfig].  The extended error message from the SSL handshake exception is: [PKIXCertPathBuilderImpl could not build a valid CertPath.].

what should i do?

**Comment by ayoho** [comment]
That message is emitted if you have not imported the SSL certificate of the remote server (in this case, a certificate for *.azure.net) with which the Liberty server is attempting to communicate. As the message suggests, the fix is to add the signer certificate to the Liberty server's trust store. You can see the documentation in our Knowledge Center to walk you through how to do that: https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_add_trust_cert.html

**Comment by brutif** [comment]
on 20.001 and higher there's an even easier way to do this for certificates issue by well-known CA's (like Azure's). 
```
<keyStore id="defaultKeyStore" password="keyspass" />
<ssl id="defaultSSLConfig" keyStoreRef="defaultKeyStore" trustDefaultCerts="true"/>
```
trustDefaultCerts should allow most well-known CA's to be trusted automatically.

**Comment by HanithaKrishnaraj** [comment]
Thanks for the reply.

I have tried giving the below line in server.xml to skip the SSL Handshake error, but still facing same issue.
<ssl id="defaultSSLConfig"  trustDefaultCerts="true"/>

**Comment by ayoho** [comment]
What version of Open Liberty are you using?

**Comment by brutif** [comment]
not all well known certs are in the list liberty uses (the list  comes from the jvm, so if your jvm is very old, so is the list of certs).  Sometimes they do have to be added manually per the documentation link above.

**Comment by HanithaKrishnaraj** [comment]
We are using

**Comment by ayoho** [comment]
The MicroProfile feature doesn't have any bearing on this situation, and I'm a little confused by your last statement. I don't know what version of Open Liberty you're using. If you're using Open Liberty 20.0.0.1 or newer, the `trustDefaultCerts` attribute that Bruce suggested should have worked. In any case, I would recommend using the `keytool` command as outlined in that Knowledge Center link.

**Comment by ayoho** [comment]
Hello @HanithaKrishnaraj. This issue was recently brought to my attention again, and I am going to close it due to lack of activity. You may re-open this issue or create a new issue if you continue to have problems.
