### ISSUE TITLE
JakartaEE: Enable EE9 RepeatTests in JSF 2.2/2.3 FAT

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#11612]
Enable JSF FATs to run against the JakartaEE transformed JSF feature.

**Comment by pnicolucci** [comment]
JSF 2.2 FAT : https://github.com/OpenLiberty/open-liberty/issues/14069

JSF 2.3 FAT:

**Comment by pnicolucci** [comment]
This can be closed given we've already delivered these changes in other issues / pull requests.
