### ISSUE TITLE
UnsupportedDataTypeException while sending a mail within a self created Thread

### ISSUE THREAD

**Issue by c-koell** [OpenLiberty/open-liberty#11640]
**Describe the bug**
In our application there is a code part that tries to send a mail within a "self created" Thread.
(ScheduledExecutorService  is used)
Example:
```
ScheduledExecutorService scheduledPool = Executors.newScheduledThreadPool(4);
scheduledPool.schedule(new Runnable() {
  public void run() {
    Properties properties=new Properties();  
    //fill all the information like host name etc.  
    Session session=Session.getDefaultInstance(properties,null);  
    MimeMessage message=new MimeMessage(session);
    ....
    Transport.send(message);
  }
}, 1, TimeUnit.SECONDS);
```
On WebSphere 9.0.5.x works this code fine.

We see following Stacktrace:
```
javax.mail.MessagingException: IOException while sending message
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1365) ~[?:?]
Caused by: javax.activation.UnsupportedDataTypeException: no object DCH for MIME type text/plain; charset=us-ascii
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:885) ~[com.ibm.websphere.javaee.activation.1.1_1.0.37.jar:?]
	at javax.activation.DataHandler.writeTo(DataHandler.java:316) ~[com.ibm.websphere.javaee.activation.1.1_1.0.37.jar:?]
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1694) ~[com.ibm.ws.com.sun.mail.javax.mail.1.6_1.6.37.jar:1.6.2]
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1913) ~[com.ibm.ws.com.sun.mail.javax.mail.1.6_1.6.37.jar:1.6.2]
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1315) ~[?:?]
	... 10 more

```

We have tried to set the ContextClassloader on the new Thread like described on
https://stackoverflow.com/questions/21856211/javax-activation-unsupporteddatatypeexception-no-object-dch-for-mime-type-multi
```
Thread.currentThread().setContextClassLoader(callingClass.getClassLoader() );
```
Unfortunately this has changed nothing ...

**Steps to Reproduce**
Try the example above ...

**Expected behavior**
If possible it would be fine if Mails could be send within a ScheduledExecutorService Task.

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.3
 - Java Version: Eclipse OpenJ9 VM, Version 11.0.6+10
 - server.xml configuration 
   <feature>webProfile-8.0</feature>
   <feature>javaMail-1.6</feature>

**Comment by c-koell** [comment]
If i try with a ManagedExecutorService there are no errors.
It's really hard to change that code to use a ManagedExecutorService so it would be great if it also works with a ScheduledExecutorService.

**Comment by njr-11** [comment]
You can update it to use a ManagedScheduledExecutorService as follows,
```
ScheduledExecutorService scheduledPool = InitialContext.doLookup("java:comp/DefaultManagedScheduledExecutorService");
```

**Comment by c-koell** [comment]
If you use a third-party-library you are unable to change the code. So it would be great if it works with a ScheduledExecutorService.

**Comment by c-koell** [comment]
Any news here ?
