### ISSUE TITLE
github social login code calling deprecated api

### ISSUE THREAD

**Issue by meiaus** [OpenLiberty/open-liberty#11668]
Recently I was running tests on RH-SSO related to login different social media and below email was received.
Checked with @brutif for his advice on the action to take.
Bruce suggested as commented in his response to my email:
```
 
I'd open an open-liberty issue "github social login code calling deprecated api", attach or inline the email content.  tag it with the "sso" tag. We might need to update the code to keep it working with GH.
 
LinkedIn removed a deprecated api we didn't know about and broke us for about a month last year.  We didn't get any tickets on it so I think linkedin sso isn't very popular.
 
-- Bruce
```

----- Forwarded Message -----
From: GitHub <noreply@github.com>
To: Mei-hsiang Chang <ykkmhc@sbcglobal.net>
Sent: Monday, March 30, 2020, 11:13:54 PM CDT
Subject: [GitHub API] Deprecation notice for authentication via URL query parameters

Hi @meiaus,

On March 31st, 2020 at 04:13 (UTC) your application (my2LoginApp) used an access token (with the User-Agent Apache-HttpClient/4.5.10 (Java/11.0.6)) as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/user

Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder on a monthly basis.

Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.

Thanks,
The GitHub Team

**Comment by ezhou365** [comment]
fixed with #12125
