### ISSUE TITLE
JakartaEE: PackageRename Channel Framework & Transport

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#11721]
More discovery will be needed to determine which, if any, packages need to be updated.

For example,

com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/h2internal/H2ConnectionSettings.java
151:                Class<?> DatatypeConverter = Class.forName("javax.xml.bind.DatatypeConverter");

javax.xml.bind is updated to jakarta.xml.bind

**Comment by pnicolucci** [comment]
Looks like many of these references were removed in: https://github.com/OpenLiberty/open-liberty/pull/12839

**Comment by isaacrivriv** [comment]
After some invstigation, no javax resources were found. The projects for channel framework and tranport checked are

- com.ibm.ws.channelfw (TCP)
- com.ibm.ws.transport.http (HTTP)
- com.ibm.ws.channel.ssl (SSL)
- com.ibm.ws.wsoc (Web Sockets)


Out of all the projects, only com.ibm.ws.wsoc was transformed to jakarta with all the javax references accordingly updated. After looking in the decompiled classes of the jar, no javaee javax references were found. We did find some javase javax references of the type javax.net.ssl and javax.management which shouldn't be updated. This should be good to close.
