### ISSUE TITLE
mpHealth - readiness check reports UP when application fails to start

### ISSUE THREAD

**Issue by matthewpwilson** [OpenLiberty/open-liberty#11722]
**Describe the bug**
My application fails to start up, but the /health/ready endpoint still replies with UP.

**Steps to Reproduce**
1. Configure server with mpHealth 2.0
2. Define a readiness check in my applicaiton.
3. Start the server under conditions where the application will fail to start. In my case, the application should connect to Kafka with mpReactiveMessaging, but Kafka is not available. 
4. GET /health/ready and receive the response UP. 

**Expected behavior**
The readiness check should report DOWN as my application is not available.  This partitcularly important in Kubernetes, because my application appears ready and therefore will get traffic routed to it, but it's actually dead. 

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.3
 - Java Version: OpenJDK Runtime Environment (1.8.0_242-b08)
 - server.xml configuration:
```
<server description="Sample Liberty server">

  <featureManager>
    <feature>jaxrs-2.1</feature>
    <feature>jsonb-1.0</feature>
    <feature>mpHealth-2.0</feature>
    <feature>mpRestClient-1.3</feature>
    <feature>mpReactiveMessaging-1.0</feature>
  </featureManager>

  <httpEndpoint httpPort="9080" id="defaultHttpEndpoint" host="*" />

  <webApplication location="coffeeshop-ui.war" contextRoot="/">
  </webApplication>

</server>
```

 - [messages.log](https://github.com/OpenLiberty/open-liberty/files/4458174/startup-fail.log)
- App is available on DockerHub: matthewpwilson/coffeeshop-ui:lib-20-03

**Comment by matthewpwilson** [comment]
Trace with HEALTH=all and accompanying messages.log
[trace.log](https://github.com/OpenLiberty/open-liberty/files/4482401/trace.log)
[messages.log](https://github.com/OpenLiberty/open-liberty/files/4482404/messages.log)

**Comment by emyes** [comment]
Hi All,

 Please note that issue exist in Open liberty version 20.0.0.2 as well.

**Comment by kabicin** [comment]
@matthewpwilson I was able to reproduce this on my end, and got the same error.

Our AppTracker class is skipping states when it follows the lifecycle of your app due to the mpReactiveMessaging exception. Based on our implementation, this skipped state ignores that the app ever existed, when the health check is performed, which is problematic.

This issue is in constant discussion, working on a fix as the solution isn't cut and dried, and should definitely be addressed at the least in the mpHealth-3.0 release.

**Comment by matthewpwilson** [comment]
What's the timescale for mpHealth-3.0? Why does it need to wait for this release? It effectively means the readiness and liveness checks don't do their job at all when the app fails to start...

**Comment by kabicin** [comment]
mpHealth-3.0 is going to introduce changes to its design, and a reason for some of those modifications keep the bug you've raised in mind. Definitely agree that there is a problem in mpHealth-2.0 at this point, and I've finished a working implementation and but need to automate tests for scenarios like the one you've encountered. Apologize for the confusion above, but yes we will have a fix soon!

**Comment by matthewpwilson** [comment]
Sounds good, thanks for the clarification.
