### ISSUE TITLE
Unable to create logger error in server startWinService when WLP_OUTPUT_DIR set in server.env

### ISSUE THREAD

**Issue by hlhoots** [OpenLiberty/open-liberty#11746]
**Describe the bug**
The user sets the WLP_OUTPUT_DIR in ${wlp.install.dir}/etc/server.env and registers a liberty server to run as a Windows service. When the server is started with the "server startWinService <servername>" command they get the following error:

The specified path can not be found.
Unable to create logger at ''

**Steps to Reproduce**
1. Specify the WLP_OUTPUT_DIR in ${wlp.install.dir}/etc/server.env file as some location, ex WLP_OUTPUT_DIR=C:\temp\output\
2. Create the server: server create myServer
3. Register the server:  server registerWinService myServer
4. Start the server:  server startWinService myServer

**Expected behavior**
The server should start as a service without the error mentioned above.

**Diagnostic information:**
All versions of Open Liberty

**Additional context**

**Comment by waldi5001** [comment]
Have you try a path without a \

Try c:/temp/output or /temp/output or c:\\temp\\output
