### ISSUE TITLE
Enabling javaee-8.0 gives SSL config errors out of the box

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#1175]
If someone is just getting started with Java EE 8 and OpenLiberty they typically do the following steps:
```
bin/server create myServer
# edit myServer's server.xml to enable the javaee-8.0 feature
bin/server run myServer
```

On server stratup, they will be met with the following errors:
> [ERROR   ] CWWKS9582E: The [defaultSSLConfig] sslRef attributes required by the orb element with the defaultOrb id have not been resolved within 10 seconds. As a result, the applications will not start. Ensure that you have included a keyStore element and that Secure Sockets Layer (SSL) is configured correctly. If the sslRef is defaultSSLConfig, then add a keyStore element with the id defaultKeyStore and a password.
> [ERROR   ] CWWKS9660E: The orb element with the defaultOrb id attribute requires a user registry but no user registry became available within 10 seconds.   As a result, no application will start. Ensure that you have configured an appropriate user registry in the server.xml file.

About 30 seconds after these errors pop out, a helpful AUDIT message comes along with some sample configuration that will likely resolve the errors:
> [AUDIT   ] CWPKI0817A: The default SSL configuration expects a <keyStore> element with an id value of defaultKeyStore, and a password. The defaultKeyStore <keyStore> element is missing, or the password is not specified. Either define the missing element: <keyStore id="defaultKeyStore" password="yourpassword" />, or change the default SSL configuration to use an existing keystore. See the following example: <ssl id="defaultSSLConfig" keyStoreRef="newKeyStore" />.

**Proposed solutions:**
1. Use JRE truststore
1. Add `<keyStore id="defaultKeyStore" password="CHANGEIT" />` to the default server template (would also require adding `ssl-1.0` to server template)
1. Add commented out config to the server template:
    ```xml
    <!-- if you enable ssl-1.0 (or anything that includes it, such as javaee-8.0 or webProfile-8.0) you must configure a <keystore> element -->
    <!-- <keyStore id="defaultKeyStore" password="CHANGEIT" /> -->
    ```
1. Have the `server create` command generate a random strong keystore password.  For example, have `<keyStore id="defaultKeyStore" password="${keystore.generated.password}" />` in the default config template and generate a random value for `keystore.generated.password` in the bootstrap.properties file.

**Comment by NottyCode** [comment]
We don't use default passwords in Liberty, so that rules out doing option 2. It isn't secure.

**Comment by aguibert** [comment]
Added option 4 for generating a random keystore password during `server create` command

**Comment by NottyCode** [comment]
Looking into whether option 4 is ok. Possibility of allowing an env var to set the keystore password for 12-factor/docker environments. Need to review with security experts.

**Comment by NottyCode** [comment]
+1

**Comment by utle** [comment]
+1 ... --no-password - maybe change to --no-random-password-gen?

**Comment by jtmulvey** [comment]
+1

**Comment by acdemyers** [comment]
+1

**Comment by Emily-Jiang** [comment]
>>Use the keystore.password environment variable, if set by the processes running server start
By the way, keystore.password is not a valid env variable name.

**Comment by aguibert** [comment]
good point Emily, we can change it to `keystore_password` instead

**Comment by NottyCode** [comment]
I updated the proposed solution to use _ over period
