### ISSUE TITLE
JAX-RS Default ExceptionMapper

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#11774]
In JAX-RS 3.1, there will be a new mandatory default ExceptionMapper<Throwable> - this ExceptionMapper will capture all otherwise "unmapped" exceptions and create a default Response - and will follow the same response flow as JAX-RS requests that return non-exception or mapped-exception responses - flowing through ContainerResponseFilters, MessageBodyWriters, WriterInterceptors, etc.

Currently, Open Liberty's MicroProfile Open Tracing implementation registers it's own default ExceptionMapper<Throwable> so that it can record the unmapped exception and ensure that the response is traced.  In the future MicroProfile Metrics would like to do something similar so that it can differentiate between metrics collected for successful requests and metrics collected for exception path requests.

After discussion with @jim-krueger, @Channyboy, @donbourne, and @fmhwong, we think that the best approach for this would be to create a new project (to be maintained by the JAX-RS team) that would implement and register the default ExceptionMapper<Throwable>.  This new project would _only_ be enabled by auto-feature when `jaxrs-2.1` (or 3.0)  and `mpOpenTracing-*` are enabled.  This ensures that we do not register the default ExceptionMapper in the existing JAX-RS 2.1 feature - which would break zero-migration.  The default ExceptionMapper would also be pluggable so as to allow MP OpenTracing and eventually MP Metrics to detect when an otherwise-unmapped exception has occurred in the JAX-RS processing flow. 

When we begin implementing JAX-RS 3.1, then the `jaxrs-3.1` feature will include the new default ExceptionMapper project and it will not need for the auto-feature.

The default exception mapper's plug point should look something like this:
```
public interface DefaultExceptionMapperCallback {
    /**
     * A callback method fired when the default exception mapper is invoked,
     * indicating that a request resulted in an unmapped exception. The JAX-RS
     * runtime will invoke this method for all registered listeners, passing in the
     * unmapped exception and the mapped status code. The returned map is
     * a map of headers to be added to the resulting Response. Null or an empty
     * map indicates no new headers should be added.
    Map<String,Object> onDefaultMappedException(Throwable t, int statusCode, ResourceInfo resourceInfo);
}
```

We should have a DS service that registers the default ExceptionMapper, and passes it a list of callbacks - like:

```
public class DefaultExceptionMapper implements ExceptionMapper<Throwable> {

    @Context
    private ResourceInfo resourceInfo;

    private final List<DefaultExceptionMapperCallback> callbacks = new LinkedList<>();

    DefaultExceptionMapper(Collection<DefaultExceptionMapperCallback> callbacks) {
        this.callbacks.addAll(callbacks);
    }

    @Override
    public Response toResponse(Throwable t) {
        Response response;
        if (t instanceof WebApplicationException && ((WebApplicationException)t).getResponse() != null) {
            response = ((WebApplicationException)t).getResponse(); 
        } else {
            response = Response.serverError().build();
        }

       Map<String, Object> callbackHeaders = new HashMap<>();
        for (DefaultExceptionMapperCallback callback : callbacks) {
            callbackHeader.putAll(callback.onDefaultMappedException(t, response.getStatusCode(), resourceInfo));
        }

        if (!callbackHeaders.isEmpty()) {
            ResponseBuildler builder = Response.fromResponse(response);
            for (Map.Entry<String, Object> entry : callbackHeaders.entrySet()) {
                builder = builder.header(entry.getKey(), entry.getValue());
            }
            response = builder.build();
        }

        return response;
    }
}
```

The DefaultExceptionMapper class would be initialized and register with a DS service like this:
```
@Component(immediate = true, property = { "service.vendor=IBM" }, configurationPolicy = ConfigurationPolicy.IGNORE, service = {JaxRsProviderRegister.class})
public class JaxRsDefaultExceptionMapperProviderRegister implements JaxRsProviderRegister {

    private List<DefaultExceptionMapperCallback> callbacks = new LinkedList<>();
    @Override
    public void installProvider(boolean clientSide, List<Object> providers, Set<String> features) {
        if (!clientSide) {
            providers.add(new DefaultExceptionMapper(callbacks));
        }
    }

    @Reference(cardinality = ReferenceCardinality.MULTIPLE, policy = ReferencePolicy.DYNAMIC, policyOption = ReferencePolicyOption.GREEDY)
    public void addCallback(DefaultExceptionMapperCallback callback) {
        callbacks.add(callback);
    }

    public void removeCallback(DefaultExceptionMapperCallback callback) {
        callbacks.remove(callback);
    }
```

Then the MP OT code could be changed to something like this:
```
@Component
public class MPOTDefaultExceptionMapperCallback implement DefaultExceptionMapperCallback {

    @Override
    public Map<String,Object> onDefaultMappedException(Throwable t, int status code) {
        Tr.warning(tc, "OPENTRACING_UNHANDLED_JAXRS_EXCEPTION", t);
        return Collection.singletonMap(EXCEPTION_KEY, t);
    }
}
```

**Comment by Channyboy** [comment]
Will a `ResourceInfo`  be included in the callback?
Metrics will need to resolve the the fully qualified class name and method signature.

**Comment by jim-krueger** [comment]
Yes,  there will be a ResourceInfo parameter in the onDefaultMappedException() method.

**Comment by fmhwong** [comment]
Are we planning to make the auto feature to work with mpOT 1.0, 1.1, 1.2 and 1.3?  1.0-1.2 uses JAX-RS 2.0 and tolerate 2.1.  mpOT 1.3 uses JAX-RS 2.1.

**Comment by andymc12** [comment]
This is resolved for both EE8 and EE9. We may need to enhance it for EE10 (JAX-RS 3.1), but that will be part of that epic issue.
