### ISSUE TITLE
Remove the session affinity dependency in SAML web sso login 

### ISSUE THREAD

**Issue by chunlongliang-ibm** [OpenLiberty/open-liberty#11796]
Liberty SAML web browser SSO relies on session to preserve request state, and restore request after login is completed. In cluster environment, if session affinity is not guaranteed, sso login could fail. For example, if an unauthenticated request is initially routed to pod 1, Liberty store the request state in pod 1's memory before redirecting user to SAML IdP.  After user is authenticated with SAML IdP, if SAML IdP redirects user back to pod 2 instead of pod 1, the authentication could not be completed because pod 2 can not find the initial request state.

The initial request state is cached with HttpRequestInfo. The proposal is to recreate HttpRequestInfo if HttpRequestInfo is not in cache. 
1.  Create a serializable object, sign (could be a salted hash by including default keystore password)
2. add the object as cookie, and cookie name need include or match relaystate (so it can be looped back after authenticated by IdP)
3. If HttpRequestInfo can not be retrieved from cache, use the cookie to recreate HttpRequestInfo. Prior to deserialize the cookie, we need verify the signature/hash to prevent serialization attack.

Whoever works on this issue, please talk to me

**Comment by arunavemulapalli** [comment]
saml websso login code is updated to remove the session dependency
The changes are tested using sp solicited and unsolicited flows. liberty sp server is restarted in the middle of the saml request/response exchange with the IdP. The sequence is 
1. sp sends saml request to IdP
2. restart the sp
3.user logs in at the IdP
4. sp receives saml response from IdP
5. sp recreates the initial request successfully without the session and consumes the saml response and redirects to application
Idp initiated flow is also tested to make sure that there are no regressions.
