### ISSUE TITLE
Moving in session.db

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/open-liberty#118]
Need to move \dev\com.ibm.ws.session.db from internal repo to open-liberty.

Need to move nl props to proper location
Need to fix copyrights

bnd and gradle files already there, but need to check if changes with .classpath and build.xml

**Comment by hlhoots** [comment]
Holding on this change until we've had some more discussion on the topic.

**Comment by hlhoots** [comment]
Changes made.
