### ISSUE TITLE
JakartaEE: Import Jakarta JSTL API

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#11836]
Currently updated in com.ibm.websphere.jakartaee.jstl.2.0

https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.websphere.jakarta.jstl.2.0

Source: https://repo1.maven.org/maven2/jakarta/servlet/jsp/jstl/jakarta.servlet.jsp.jstl-api/2.0.0-RC1/

Enabled in JSP-3.0 -- https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.websphere.appserver.features/visibility/public/jsp-3.0/com.ibm.websphere.appserver.jsp-3.0.feature

**Comment by pnicolucci** [comment]
This work has already been completed and the initial API is available here: https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.jakarta.jstl.2.0
