### ISSUE TITLE
JakartaEE: Jakarta XML Binding API Support 

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#11859]

**Comment by atosak** [comment]
Blocked by [](https://github.com/OpenLiberty/open-liberty/issues/11856)

**Comment by neuwerk** [comment]
JAX-B 3.0 is the Jakarta XML Binding feature. It allows a user to marshal and un-marshal XML to Java Objects. There were no new feature updates to JAX-B 3.0 over JAX-B 2.3 aside from the changes to use the new Jakarta API

**Comment by lauracowen** [comment]
Thanks @neuwerk

**Comment by malincoln** [comment]
@andymc12  pls add FAT summary to overall epic here:  https://github.com/OpenLiberty/open-liberty/issues/12969

**Comment by ayoho** [comment]
I've removed the FAT approval for this epic until https://github.com/OpenLiberty/open-liberty/pull/18975 is merged and successfully tested.

**Comment by malincoln** [comment]
@ayoho can this be fat approved now that 18975 is merged?

**Comment by ayoho** [comment]
@malincoln No, not until that PR has successfully made it through an SOE run. That PR didn't get delivered in time for this past weekend's SOE, so we'll have to wait until next Monday to check the test results.

**Comment by malincoln** [comment]
that's right.  Sorry, mixing it up with XML-WS.  Thanks
