### ISSUE TITLE
JakartaEE: Jakarta Activation Support

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#11856]

**Comment by malincoln** [comment]
@uberskigeek  pls add FAT summary to overall epic here:  https://github.com/OpenLiberty/open-liberty/issues/12969

**Comment by neuwerk** [comment]
There should be no FAT requirement for this activation-2.0, as it's an internal feature used as a dependency for the xmlWS-3.0 and mail-2.0 features. The testing of those features provide coverage for the dependency on activation-2.0.

**Comment by malincoln** [comment]
Discussed with @neuwerk and this is ready to close now.
