### ISSUE TITLE
JakartaEE: Jakarta JWS API Support 

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#11852]

**Comment by neuwerk** [comment]
JWS 3.0 (11852) is Jakarata API for Java Web Services. While it is a distinct from the JAX-WS 3.0 API, the JWS 3.0 API is not usable from a user perspective without the jaxws-3.0 implementation.

**Comment by lauracowen** [comment]
Thanks @neuwerk

**Comment by malincoln** [comment]
@neuwerk  pls add FAT summary to overall epic here:  https://github.com/OpenLiberty/open-liberty/issues/12969

**Comment by malincoln** [comment]
Per discussion with @neuwerk this is now ready to close.
