### ISSUE TITLE
JakartaEE: Jakarta Mail Support 

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#11860]

**Comment by atosak** [comment]
Blocked by https://github.com/OpenLiberty/open-liberty/issues/11856

**Comment by malincoln** [comment]
@uberskigeek  pls add FAT summary to overall epic here:  https://github.com/OpenLiberty/open-liberty/issues/12969

**Comment by malincoln** [comment]
Per discussion with @neuwerk this is now ready to close.
