### ISSUE TITLE
ZCEE: JWT feature doesn't support to configure claim nbf in element jwtBuilder

### ISSUE THREAD

**Issue by ghost** [OpenLiberty/open-liberty#11868]
Original Description:

Currently we can configure jwtBuilder with jwt feature in liberty server.xml to generate JWT Token , such as the follwing:
```XML
<jwtBuilder   id="myJWTBuilder" audiences="myApp1" expiresInSeconds="30m" issuer="z/OS Connect EE" jti="true" scope="scope1" signatureAlgorithm="RS256" />
```
this element has some attributes used to configure claims in JWT payload.  But **nbf** as a JWT public claim, it can not be configured in jwtBuilder.
There are customers that have the requirements to configure nbf in  server.xml with jwtBuilder, can liberty support it? thanks.

Problem: The jwtBuilder configuration element does not allow configuring the "not before" claim. The "nbf" claim of the JWT is needed to identify the time before which the JWT must not be accepted. 

Solution: The jwtBuilder element is being enhanced with a new "nbfOffset" attribute used to compute the value for the "nbf" claim to add to the JWT token. The "nbf" claim will be set to the the time the token was issued at plus the value of the "nbfOffset" attribute. An example of the configuration is as follows,

```XML
  <jwtBuilder nbfOffset="1800s" />
```

Therefore, if the JWT was issued "now", then the "nbf" claim will have a value of "now" + 1800 seconds. This particular JWT token can only be used after the 1800s from "now" have elapsed.

The type of the nbfOffset attribute is type="String" and ibm:type="duration(s)".

**Comment by ayoho** [comment]
This is an enhancement to Security SSO functionality, but we were hoping the z/OS team might be able to implement this functionality and provide appropriate tests.

**Comment by NottyCode** [comment]
@teddyjtorres I don't think elapsedNBF makes sense in this context. If I understand the design here the value of nbf is added to the time the JWT is issued, but common usage of elapsed would imply that this time period has passed. For example if I talk about 30 minutes elapsing I would think that it would mean 30 minutes has passed, but in this case no time has passed. I think what you are looking at is an offset from current time, so perhaps nbfOffset would make more sense. Also the design doesn't detail what the type of the attribute is. I'm assuming this would be a duration?

**Comment by mmerali96** [comment]
Fat test summary:  #14910

**Comment by mmerali96** [comment]
FAT Test Summary: #14910
