### ISSUE TITLE
Missing FunctionMapper

### ISSUE THREAD

**Issue by fcorneli** [OpenLiberty/open-liberty#11882]
Doing within a JSF component the following:
```
FacesContext facesContext = FacesContext.getCurrentInstance();
ELContext elContext = facesContext.getELContext();
FunctionMapper functionMapper = elContext.getFunctionMapper();
```
yields `null` for `functionMapper`. This should not happen.

Open Liberty version 20.0.0.4

**Comment by volosied** [comment]
Hello Frank,

Thank you for this bring this our attention. This one is easily reproducible, and I agree that this behavior does appear to be incorrect.  I made some investigated this today, but wasn't able to address it. However, I will continue looking into this issue. 

Thanks!

**Comment by volosied** [comment]
I've identified a fix and provided it to the MyFaces Community for review: https://issues.apache.org/jira/browse/MYFACES-4333.
