### ISSUE TITLE
JakartaEE: Jakarta RestConnector Support 

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#11885]
RestConnector includes RestHandler so is blocked by #11886 

The following APIs are enabled by RestConnector:
```
IBM-API-Package: com.ibm.websphere.jmx.connector.rest; type="ibm-api", \
 com.ibm.ws.jmx.connector.client.rest; type="ibm-api", \
 com.ibm.websphere.filetransfer; type="ibm-api"
```

These packages need to be evaluated for transformation.  If they use Jakarta types in their API signatures then we will need 2.0 versions of the packages.

**Comment by malincoln** [comment]
@sebratton @anjumfatima90 pls add the FAT summary here:  https://github.com/OpenLiberty/open-liberty/issues/12969

**Comment by dazavala** [comment]
Closing as fat-complete.  This issue may reopen due to FAT summary review or new milestones.
