### ISSUE TITLE
JakartaEE: Jakarta JDBC Support 

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#11884]

**Comment by malincoln** [comment]
@dazavala  pls add the FAT summary here:  https://github.com/OpenLiberty/open-liberty/issues/12969

**Comment by njr-11** [comment]
@malincoln I have already added the test information for JDBC to the Feature Test Summary under the section for #11771 , which is the story that I used to implement the JDBC support for Jakarta EE.  This #11884 that you found appears to be a duplicate story that Atosa created.  I'll just get rid of it as a duplicate.
