### ISSUE TITLE
JakartaEE: Jakarta RestHandler Support 

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#11886]
This feature enables the following SPI:

```
IBM-SPI-Package: com.ibm.wsspi.rest.handler; type="ibm-spi", \
 com.ibm.wsspi.rest.handler.helper; type="ibm-spi"
```

These packages need to be analyzed to see if jakarta types are part of their API signatures.  If so then 2.0 versions of these packages will be needed when transformed.

The restHandler includes these additional security related features that will need to be done as part of the work to enable RestHandler support:

```
 com.ibm.websphere.appserver.ssl-1.0, \
 com.ibm.websphere.appserver.adminSecurity-1.0, \
 com.ibm.wsspi.appserver.webBundleSecurity-1.0, \
```

The ssl feature should be agnostic to the version of EE and should "just work" without modification.

The adminSecurity and webBundleSecurity depend on work being done in PR #12291

**Comment by malincoln** [comment]
@sebratton @anjumfatima90  pls add the FAT summary here:  https://github.com/OpenLiberty/open-liberty/issues/12969

**Comment by dazavala** [comment]
Closing as fat-complete. This issue may reopen due to FAT summary review or new milestones.
