### ISSUE TITLE
@Path with regular expressions is not resolved as expected

### ISSUE THREAD

**Issue by rsoika** [OpenLiberty/open-liberty#11893]
Migrating my application from wildfly to openliberty I encountered a strange behavior concerning the resolving of jax-rs @Path param containing regular expressions. 

My rest api method looks like this:

```java
@GET
@Path("/{uniqueid : ([0-9a-f]{8}-.*|[0-9a-f]{11}-.*)}/file/{file}")
public Response getWorkItemFile(@PathParam("uniqueid") String uniqueid, 
		  @PathParam("file") @Encoded String file,
		  @Context UriInfo uriInfo) {

   logger.info("URI="+ servletRequest.getRequestURI());
   logger.info("uniqueid="+uniqueid);
   logger.info("file="+file);
  ...
}
```

When I call this method for example with the URL

`http://localhost:9080/api/4953011e-82d8-4fbf-8474-e70341ded06e/file/2-phone3.jpg`

I see the following console output:

```
app_1  | [INFO    ] URI=/api/snapshot/4953011e-82d8-4fbf-8474-e70341ded06e/file/2-phone3.jpg
app_1  | [INFO    ] uniqueid=4953011e-82d8-4fbf-8474-e70341ded06e
app_1  | [INFO    ] file=4953011e-82d8-4fbf-8474-e70341ded06e
```

So it seems that the regular expression in my path param is not resolved correctly.  
We tested it in wildfly and payara without problems.

**Comment by jim-krueger** [comment]
Thanks @rsoika , I've reproduced locally and will take a look.

**Comment by jim-krueger** [comment]
I've identified the problem.   
@Path("/{uniqueid : ([0-9a-f]{8}-.*|[0-9a-f]{11}-.*)}/file/{file}")
Your regex "([0-9a-f]{8}-.*|[0-9a-f]{11}-.*) is nested in parens.   Currently Liberty JAXRS will add an additional set of parens to this, which will cause this regex to be interpreted as having multiple groups, and that causes the value to be duplicated and incorrectly assigned to the file parameter.

**Comment by jim-krueger** [comment]
I've also written a CXF Jira to resolve this there:  https://issues.apache.org/jira/browse/CXF-8278
