### ISSUE TITLE
Duplicate workarea contents

### ISSUE THREAD

**Issue by gjdeval** [OpenLiberty/open-liberty#11897]
When an app packaged in a war is started in Liberty with autoExpand="false" (the default), some of the application archive contents are expanded into the workarea of the Liberty server, so that on subsequent starts the contents can be accessed without repeating the work of unzipping the archive. 
The general model is that if the app war is not changed, on the next server start the server should use the existing contents of the workarea to start the app, and should not unzip the (unchanged) war again. But for some apps/configs, on the second start the app is again unzipped into the workarea, at a different location than the original app expansion. 
This duplicate expansion of the app doubles the app's disk footprint in the workarea, and also has the side effect of doubling the number of URLs mapped into the J9 shared class cache (SCC). Also the extra work of unzipping the app into the workarea and mapping the new set of URLs into the SCC slows down the app startup.
Usually after the second start, for third start and beyond the server uses one of the existing workarea expansions of the app. But on at least one occasion, I have seen four separate copies of the app contents in the workarea and 4X the URLs in the SCC.
Looking in the workarea, the extra copy of the app archive contents is created under a separate path in the "data/cache" directory, inside a directory with a different app.manager_N sequence number.

$ du -hcs usr/servers/cics-single-app/workarea/org.eclipse.osgi/61/data/cache/*
14M     usr/servers/cics-single-app/workarea/org.eclipse.osgi/61/data/cache/com.ibm.ws.app.manager_0
14M     usr/servers/cics-single-app/workarea/org.eclipse.osgi/61/data/cache/com.ibm.ws.app.manager_18
27M     total

OpenLiberty version: 
- Open Liberty 20.0.0.3 (wlp-1.0.38.cl200320200305-1433)
-  Open Liberty 20.0.0.4 (wlp-1.0.39.cl200420200401-1714)
Java version: pxa6480sr6fp7-20200312_01

**Comment by jhanders34** [comment]
This is tied to Liberty case TS003610591

**Comment by brenthdaniel** [comment]
There are a few different ways this can happen, but all of them are tied to the configuration PID for an application changing in between server starts. 
1) For applications in dropins, there will generally be a different PID on every restart because we are deleting the old configuration and creating a new one. 
2) For configured applications, the PID will not change unless we reprocess configuration (which will only happen when server configuration or the app manager bundle has changed.) 
3) If you remove an application while the server is started it will probably have a new PID when it's added back. The old workarea cache will not be cleaned up. 

The solution here is to:
1) Delete the workarea cache for a PID when the app is deleted. This prevents scenarios (1) and (3)
2) When the app manager is shutting down, it will delete all workarea caches corresponding to PIDs that it doesn't know about. 

This does still leave a case where there will be a stale cache entry for an application after restart (assuming configuration has been updated) but it will be deleted when the server is stopped. We are doing this at shutdown rather than startup to avoid increasing startup time.

**Comment by gjdeval** [comment]
The duplication of workarea contents is happening in OL-20004-GA with configs where the app is not in dropins and there is no change (from the user perspective at least) in the config. 
Here's an example: I just start the server, stop the server, observe the size of the work area to be ~X MB; then start the server and stop the server again, the workarea is now ~2X MB; start the server and stop the server again, the workarea is now ~3X MB.
The server.xml points to the app in a fixed location on the system:

    <webApplication id="meetings" location="/gjd/sufp/apps/cdi-fat/fat-cdi-meetings.war" name="meetings">

I start by clearing the workarea and the Java SCC:
```
# rm -rf usr/servers/cdi-fat/workarea/*
# rm -f usr/servers/.classCache/C290M4F1A64P_liberty-root_G41L00
```
 Then start the server - stop the server - check the workarea size (63M).
```
# ./bin/server start cdi-fat
Starting server cdi-fat.
Server cdi-fat started with process ID 28670.
# ./bin/server stop cdi-fat
Stopping server cdi-fat.
Server cdi-fat stopped.
# du -hcs usr/servers/cdi-fat/*
0       usr/servers/cdi-fat/apps
0       usr/servers/cdi-fat/dropins
24K     usr/servers/cdi-fat/logs
4.0K    usr/servers/cdi-fat/server.env
4.0K    usr/servers/cdi-fat/server.xml
63M     usr/servers/cdi-fat/workarea
63M     total
```
Start and stop the server again - check the workarea size - 113M - so about 50 MB growth
```
# ./bin/server start cdi-fat
Starting server cdi-fat.
Server cdi-fat started with process ID 29277.
# ./bin/server stop cdi-fat
Stopping server cdi-fat.
Server cdi-fat stopped.
# du -hcs usr/servers/cdi-fat/*
0       usr/servers/cdi-fat/apps
0       usr/servers/cdi-fat/dropins
24K     usr/servers/cdi-fat/logs
4.0K    usr/servers/cdi-fat/server.env
4.0K    usr/servers/cdi-fat/server.xml
113M    usr/servers/cdi-fat/workarea
113M    total
```
And start-stop the server again - workarea is now 163M - 50 MB more growth
```
# ./bin/server start cdi-fat
Starting server cdi-fat.
Server cdi-fat started with process ID 29832.
# ./bin/server stop cdi-fat
Stopping server cdi-fat.
Server cdi-fat stopped.
# du -hcs usr/servers/cdi-fat/*
0       usr/servers/cdi-fat/apps
0       usr/servers/cdi-fat/dropins
24K     usr/servers/cdi-fat/logs
4.0K    usr/servers/cdi-fat/server.env
4.0K    usr/servers/cdi-fat/server.xml
163M    usr/servers/cdi-fat/workarea
163M    total
#   
```
And looking in the workarea to see where the growth occurs, we find 3 app.manager instances
```# du -hcs usr/servers/cdi-fat/workarea/org.eclipse.osgi/75/data/cache/*
50M     usr/servers/cdi-fat/workarea/org.eclipse.osgi/75/data/cache/com.ibm.ws.app.manager_23
50M     usr/servers/cdi-fat/workarea/org.eclipse.osgi/75/data/cache/com.ibm.ws.app.manager_24
50M     usr/servers/cdi-fat/workarea/org.eclipse.osgi/75/data/cache/com.ibm.ws.app.manager_25
150M    total
```
So there is nothing stale, nothing changed in the config, didn't touch the app archive or anything else ... ran the commands above in the sequence shown. 
Something must be incorrectly marking the configuration as changed during/after startup.

**Comment by brenthdaniel** [comment]
I'm not worried about the case where the configuration hasn't changed in the context of this defect given that the changes will clear out the workarea regardless, but it seems worthy of another issue to figure out why your configuration is being updated in the absence of any changes. Trace for `com.ibm.ws.config.*=all` should show why it is being updated.

**Comment by gjdeval** [comment]
OK well I opened this issue for the case where the config has not changed but the app artifacts are duplicated in the workarea ... :-)  but if you want to use this issue for another problem, and create a new issue for the 'no config change' issue, that's fine.
Here's the trace for a series of three starts of the cdi-fat app, following the sequence laid out in my last comment - clear the workarea, start/stop the app three times, observe that the workarea grows by 50m on the 2nd and 3rd starts.
[issue-11897-work-area-duplication-trace.zip](https://github.com/OpenLiberty/open-liberty/files/4622518/issue-11897-work-area-duplication-trace.zip)
At the end of this test sequence, the file system shows three copies of the app.manager storage in the workarea.
```
# du -hcs `find usr/servers/cdi-fat/workarea -name "com.ibm.ws.app.manager_*"`
50M     usr/servers/cdi-fat/workarea/org.eclipse.osgi/74/data/cache/com.ibm.ws.app.manager_26
50M     usr/servers/cdi-fat/workarea/org.eclipse.osgi/74/data/cache/com.ibm.ws.app.manager_23
50M     usr/servers/cdi-fat/workarea/org.eclipse.osgi/74/data/cache/com.ibm.ws.app.manager_27
20K     usr/servers/cdi-fat/workarea/org.eclipse.osgi/74/data/cacheAdapt/com.ibm.ws.app.manager_26
20K     usr/servers/cdi-fat/workarea/org.eclipse.osgi/74/data/cacheAdapt/com.ibm.ws.app.manager_23
20K     usr/servers/cdi-fat/workarea/org.eclipse.osgi/74/data/cacheAdapt/com.ibm.ws.app.manager_27
20K     usr/servers/cdi-fat/workarea/org.eclipse.osgi/74/data/cacheOverlay/com.ibm.ws.app.manager_26
20K     usr/servers/cdi-fat/workarea/org.eclipse.osgi/74/data/cacheOverlay/com.ibm.ws.app.manager_23
20K     usr/servers/cdi-fat/workarea/org.eclipse.osgi/74/data/cacheOverlay/com.ibm.ws.app.manager_27
150M    total
```
Let me know if any other trace would be useful.

**Comment by brenthdaniel** [comment]
To be clear, the separate problem to be addressed is the fact that there's a performance issue with not using cached config when the config hasn't changed. This issue (which was merged a week ago) deals with any stale app caches in the workarea regardless of their origin.

**Comment by gjdeval** [comment]
Ah OK, gotcha - I misunderstood "worthy of another issue" to mean 'another issue besides this one'. :-)

**Comment by gjdeval** [comment]
Here's trace with the trace spec configured in bootstrap.properties 
[issue-11897-work-area-duplication-trace-2.zip](https://github.com/OpenLiberty/open-liberty/files/4624569/issue-11897-work-area-duplication-trace-2.zip)

**Comment by brenthdaniel** [comment]
I opened #12212 for the cached config problem
