### ISSUE TITLE
loose ear application.xml has wrong targetInArchive value for web module

### ISSUE THREAD

**Issue by waldi5001** [OpenLiberty/open-liberty#11934]
**Describe the bug**
if you are assembling an EAR artifact with web modules, the generated loose [ear-target-in-archive-ear.ear.xml](https://github.com/waldi5001/ear-target-in-archive/blob/master/logs/ear-target-in-archive-ear.ear.xml) doesn't take notice of a eventually modules outputFileNameMapping of the maven-ear-plugin. Please show my small sample application for details: [ear-target-in-archive](https://github.com/waldi5001/ear-target-in-archive)

[completeMessage.log](https://github.com/waldi5001/ear-target-in-archive/blob/master/logs/messages.log)
```
0000003b bm.ws.app.manager.ear.internal.EARDeployedAppInfoFactoryImpl I CWWKZ0134I: The ear-target-in-archive-ear application is using the loose application definition at the /home/fk/Documents/ear-target-in-archive/ear-target-in-archive-ear/target/liberty/wlp/usr/servers/defaultServer/dropins/ear-target-in-archive-ear.ear.xml location.
0000003b com.ibm.ws.app.manager.ear.internal.EARDeployedAppInfo       E CWWKZ0117E: Application ear-target-in-archive-ear failed to locate module ear-target-in-archive-web.war of type web
0000003b om.ibm.ws.app.manager.ear.internal.EARApplicationHandlerImpl E CWWKZ0124E: Application ear-target-in-archive-ear does not contain any modules.
0000003b com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0012I: The application ear-target-in-archive-ear was not started.
```
**Steps to Reproduce**
git clone git@github.com:waldi5001/ear-target-in-archive.git
mvn clean install
cd ear-target-in-archive-ear
mvn liberty:dev
view target/liberty/wlp/usr/servers/defaultServer/dropins/ear-target-in-archive-ear.ear.xml

**Expected behavior**
The loose application.xml targetInArchive attribute has the value from the maven-ear-plugin/outputFileNameMapping or from the generated EAR application.xml.

**Diagnostic information:**
 - OpenLiberty Version: [20.0.0.4]
 - [`java -version`](https://github.com/waldi5001/ear-target-in-archive/blob/master/logs/java.version)
 - server.xml not needed
 - [messages.log](https://github.com/waldi5001/ear-target-in-archive/blob/master/logs/messages.log)
- please have a look on my maven-ear-plugin configuration: [pom.xml](https://github.com/waldi5001/ear-target-in-archive/blob/295176e005d67da772672901432237a628c94318/ear-target-in-archive-ear/pom.xml#L33)

**Additional context**
I'm not sure whats the correct source to fill the targetInArchive attribute, but I think the ear application.xml is a good approach.

Is there a way to provide its own loose application.xml? Maybe in src/main/liberty/config? Alle my tests failed. If you can provide your own, this bug is not so annoying and if you run in a complexer szenario, it can be realy helpfull to provide your own, and not the generated. In the [doku](https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/rwlp_loose_applications.html) there is no hint

**Comment by tbitonti** [comment]
The README steps generated a loose application configuration file:.

`

----

<?xml version="1.0" encoding="UTF-8"?>
<archive>


    <file sourceOnDisk="C:\dev\repos-pub\ear-target-in-archive\ear-target-in-archive-ear\target\application.xml"
          targetInArchive="/META-INF/application.xml"/>


    <file sourceOnDisk="C:\Users\ThomasBitonti\.m2\repository\de\fk\wlp\ear-target-in-archive-web\1.0-SNAPSHOT\ear-target-in-archive-web-1.0-SNAPSHOT.war"
          targetInArchive="/ear-target-in-archive-web-1.0-SNAPSHOT.war"/>


    <file sourceOnDisk="C:\dev\repos-pub\ear-target-in-archive\ear-target-in-archive-ear\target\tmp\META-INF\MANIFEST.MF"
          targetInArchive="/META-INF/MANIFEST.MF"/>

</archive>
`

**Comment by tbitonti** [comment]
The first and second sourceOnDisk locations match the build environment.  The third sourceOnDisk location does not map to a file:

Loose application file:
  "c:\dev\repos-pub\ear-target-in-archive\ear-target-in-archive-ear\target\liberty\wlp\usr\servers\defaultServer\dropins\ear-target-in-archive-ear.ear.xml"

First Actual:
  "C:\dev\repos-pub\ear-target-in-archive\ear-target-in-archive-ear\target\application.xml"

Second actual:
  "c:\Users\ThomasBitonti\.m2\repository\de\fk\wlp\ear-target-in-archive-web\1.0-SNAPSHOT\ear-target-in-archive-web-1.0-SNAPSHOT.war"

**Comment by tbitonti** [comment]
This looks to be an tooling issue, relating to the generation fo the loose application file.

**Comment by yeekangc** [comment]
Issue moved to [OpenLiberty/ci.maven #781](https://github.com/OpenLiberty/ci.maven/issues/781) via [**ZenHub**](https://www.zenhub.com/)

**Comment by dbnex14** [comment]
I am seeing the same issue
