### ISSUE TITLE
Cannot receive multipart/form-data file

### ISSUE THREAD

**Issue by Mixermachine** [OpenLiberty/open-liberty#11942]
OpenLiberty Version: 20.0.0.4

Hy open-liberty Team,

I'm currently trying to receive a file via a post request along with some other parameters.
My current methodHeader looks like this. I can read the Strings with no problem, but not the InputStream.
```
@POST
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    public Response ingest(
            @FormParam("method") String method,
            @FormParam("methodOptions") String options,
            @FormParam("compressionFormat") String compressionFormat,
            @FormParam("file") InputStream uploadedInputStream
            )
```

I also tried to use the IMultipartBody Interface which is suggested in some other issues and forums but IntelliJ can't resolve the dependency. Do I need some additional Maven dependency?

Best regards

Aaron

**Comment by andymc12** [comment]
Hi @Mixermachine - thanks for opening the issue. It took me a bit of searching, but I came up with the correct Maven address:

```
<dependency>
    <groupId>com.ibm.websphere.appserver.api</groupId>
    <artifactId>com.ibm.websphere.appserver.api.jaxrs20</artifactId>
    <version>1.0.39</version>
    <scope>provided</scope>
</dependency>
```

This will allow you to use the `com.ibm.websphere.jaxrs20.multipart.IMultipartBody` APIs in your app.

A future version of Jakarta RESTful Web Services (formerly JAX-RS) intends to add spec-defined APIs for handling multipart data - that should simplify things considerably.

Thanks again,
Andy

**Comment by Mixermachine** [comment]
Hi @andymc12 
Thanks a lot :)
That's what I needed.

Little follow up:
If somebody else also hits the error message:
"cannot access javax.activation.DataHandler"

when using attachment.getDataHandler(), add
```
<dependency>
        <groupId>javax.activation</groupId>
        <artifactId>activation</artifactId>
        <version>1.1.1</version>
</dependency>
```

To your pom.xml
Ref: https://stackoverflow.com/a/56142821/11652396

**Comment by andymc12** [comment]
@Mixermachine Thanks for the followup.  Yes, Java Activation was removed from Java 11.  If you are using Java 8, then you shouldn't need that dependency.  The Jakarta EE community is taking over the maintenance of Java Activation, and so this dependency might be preferred for recency (though I think either should work fine):
```
<dependency>
    <groupId>jakarta.activation</groupId>
    <artifactId>jakarta.activation-api</artifactId>
    <version>1.2.2</version>
</dependency>

```

Thanks again!

**Comment by Mixermachine** [comment]
@andymc12 that's a good info 👍.
I have updated my pom.

I always try to update my software to the newest version.
This way I stay fresh and see new stuff.
Currently I'm using Java 13.

**Comment by inad9300** [comment]
@andymc12 Even the latest version of [com.ibm.websphere.appserver.api.jaxrs20](https://mvnrepository.com/artifact/com.ibm.websphere.appserver.api/com.ibm.websphere.appserver.api.jaxrs20) (1.1.68) has references to javax objects, e.g. the `IAttachment` interface declares `javax.activation.DataHandler getDataHandler()`. As such, when trying to access the attachment's contents in a Jakarta context (I'm using the "jakartaee-9.1" feature), I get `No such instance method: 'getDataHandler'`, similar to what @Mixermachine reported back then. What would be the up-to-date, Jakarta alternative? In other words, how do we handle file uploads in 2022?

**Comment by inad9300** [comment]
Oh, my goodness, I found it! https://github.com/OpenLiberty/docs/issues/5259 showed awareness that the documentation page I was following was missing information, and in fact it is already published at https://openliberty.io/docs/22.0.0.9/send-receive-multipart-jaxrs.html! All the requirements are mentioned there (in particular the `io.openliberty.jaxrs30` Maven dependency).
