### ISSUE TITLE
JakartaEE: PackageRename: Persistence Service for EJB Timers and Batch

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#11951]
User Story:
"As a user of Liberty, I want to use Enterprise Jakarta Beans Persistent Timers and Jakarta Batch with the same set of databases that are available for Java EE so that I can migrate my application to Jakarta."

This capability is provided by the JPA persistence service, which needs to work with Jakarta as well as Java EE.

Feature file for persistence service appears to be:
/com.ibm.websphere.appserver.features/visibility/private/com.ibm.ws.persistence-1.0.feature

FAT Summary : #12969

**Comment by tkburroughs** [comment]
All work complete; FAT Summary : #12969
