### ISSUE TITLE
JakartaEE: UFO Question about "combining" EE8 and Jakarta EE 9 implementations

### ISSUE THREAD

**Issue by kwsutter** [OpenLiberty/open-liberty#12005]
From the [UFO](https://ibm.box.com/s/444d16e53je9r6942f99tltkhgama2hi) review for Epic Feature #9876 :

- Process footprint is increasing because some components are implementing both versions (EE 8 and 9) which brings in the EE 8 APIs into an EE 9 runtime (and vice-versa). TODO: Will take this offline.

It was discussed that Concurrency was exploring this possibility.  Since this approach would potentially increase the footprint of both the EE 8 and Jakarta EE 9 runtimes, we need to determine if this approach is acceptable as a general practice, or only on an exception basis, or not at all.

**Comment by kwsutter** [comment]
Interesting comment that came up later in the UFO review concerning RAR files...

- What if somebody like MQ creates a provider RAR that contains both EE 8 (javax) and EE 9 (jakarta) - do we still transform?  Andy G/Glenn M: That’s a really bad idea - we shouldn’t allow them to.

So, should this same answer apply to our own implementations?

**Comment by njr-11** [comment]
Code is no longer using this approach and has not been for a while.
