### ISSUE TITLE
Lock contention in a JAX-RS client handling JSON contents

### ISSUE THREAD

**Issue by inatatsu** [OpenLiberty/open-liberty#12017]
The following one liner to invoke a web service by using a JAX-RS client such as:
```
return ClientBuilder.build()
                    .target(<uri>)
                    .request("application/json")
                    .buildGet()
                    .invoke()
                    .readEntity(<entity>.class);
```
encounters lock contention to acquire a JAR file:
```
2LKMONINUSE      sys_mon_t:0x000003FF984B8108 infl_mon_t: 0x000003FF984B8188:
3LKMONOBJECT       java/util/jar/JarFile@0x000000010073C358: owner "Default Executor-thread-40401" (J9VMThread:0x0000000000A5B300), entry count 1
3LKWAITERQ            Waiting to enter:
3LKWAITER                "Default Executor-thread-40344" (J9VMThread:0x0000000001D01100)
3LKWAITER                "Default Executor-thread-40350" (J9VMThread:0x000000000186FF00)
3LKWAITER                "Default Executor-thread-40371" (J9VMThread:0x0000000001C9A300)
3LKWAITER                "Default Executor-thread-40387" (J9VMThread:0x0000000001C22100)
3LKWAITER                "Default Executor-thread-40388" (J9VMThread:0x0000000001D54600)
```
The direct reason is that a new JAX-RS client internally creates a new `Jsonb` object, which kicks the service loader mechanism and eventually locks a JAR file of the system classloader:
```
3XMTHREADBLOCK     Blocked on: java/util/jar/JarFile@0x000000010073C358 Owned by: "Default Executor-thread-40401" (J9V
MThread:0x0000000000A5B300, java/lang/Thread:0x000000010290E7A0)
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=65536 (0x10000)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/util/zip/ZipFile.getEntry(Bytecode PC:10(Compiled Code))
4XESTACKTRACE                at java/util/zip/ZipFile$1.getEntry(Bytecode PC:3(Compiled Code))
4XESTACKTRACE                at java/util/jar/JarFile.getEntry0(Bytecode PC:17(Compiled Code))
4XESTACKTRACE                at java/util/jar/JarFile.getEntry(Bytecode PC:2(Compiled Code))
4XESTACKTRACE                at java/util/jar/JarFile.getJarEntry(Bytecode PC:2(Compiled Code))
4XESTACKTRACE                at jdk/internal/loader/URLClassPath$JarLoader.getResource(Bytecode PC:22(Compiled Code))
4XESTACKTRACE                at jdk/internal/loader/URLClassPath$JarLoader.findResource(Bytecode PC:3(Compiled Code))
4XESTACKTRACE                at jdk/internal/loader/URLClassPath$1.next(Bytecode PC:42(Compiled Code))
4XESTACKTRACE                at jdk/internal/loader/URLClassPath$1.hasMoreElements(Bytecode PC:1(Compiled Code))
4XESTACKTRACE                at jdk/internal/loader/BuiltinClassLoader$3.hasNext(Bytecode PC:45(Compiled Code))
4XESTACKTRACE                at jdk/internal/loader/BuiltinClassLoader$3.hasMoreElements(Bytecode PC:1(Compiled Code))
4XESTACKTRACE                at java/lang/ClassLoader.getResources(Bytecode PC:46(Compiled Code))
4XESTACKTRACE                at java/lang/ClassLoader.getSystemResources(Bytecode PC:4(Compiled Code))
4XESTACKTRACE                at com/ibm/ws/classloading/internal/GatewayClassLoader.getResources(GatewayClassLoader.java:144(Compiled Code))
4XESTACKTRACE                at com/ibm/ws/classloading/internal/UnifiedClassLoader$3.run(UnifiedClassLoader.java:231(Compiled Code))
4XESTACKTRACE                at com/ibm/ws/classloading/internal/UnifiedClassLoader$3.run(UnifiedClassLoader.java:228(Compiled Code))
4XESTACKTRACE                at java/security/AccessController.doPrivileged(Bytecode PC:3(Compiled Code))
4XESTACKTRACE                at com/ibm/ws/classloading/internal/UnifiedClassLoader.getResources(UnifiedClassLoader.java:228(Compiled Code))
4XESTACKTRACE                at java/util/ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(Bytecode PC:106(Compiled Code))
4XESTACKTRACE                at java/util/ServiceLoader$LazyClassPathLookupIterator.hasNextService(Bytecode PC:15(Compiled Code))
4XESTACKTRACE                at java/util/ServiceLoader$LazyClassPathLookupIterator.hasNext(Bytecode PC:11(Compiled Code))
4XESTACKTRACE                at java/util/ServiceLoader$2.hasNext(Bytecode PC:18(Compiled Code))
4XESTACKTRACE                at java/util/ServiceLoader$3.hasNext(Bytecode PC:34(Compiled Code))
4XESTACKTRACE                at javax/json/spi/JsonProvider.provider(JsonProvider.java:92(Compiled Code))
4XESTACKTRACE                at org/eclipse/yasson/internal/JsonBinding$$Lambda$202/0000000000000000.get(Bytecode PC:0(Compiled Code))
4XESTACKTRACE                at java/util/Optional.orElseGet(Bytecode PC:17(Compiled Code))
4XESTACKTRACE                at org/eclipse/yasson/internal/JsonBinding.<init>(JsonBinding.java:49(Compiled Code))
4XESTACKTRACE                at org/eclipse/yasson/internal/JsonBindingBuilder.build(JsonBindingBuilder.java:63(Compiled Code))
4XESTACKTRACE                at com/ibm/ws/jaxrs21/providers/json/JsonBProvider.apply(JsonBProvider.java:210(Compiled Code))
4XESTACKTRACE                at com/ibm/ws/jaxrs21/providers/json/JsonBProvider.apply(JsonBProvider.java:45(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/atomic/AtomicReference.updateAndGet(Bytecode PC:19(Compiled Code))
4XESTACKTRACE                at com/ibm/ws/jaxrs21/providers/json/JsonBProvider.getJsonb(JsonBProvider.java:196(Compiled Code))
4XESTACKTRACE                at com/ibm/ws/jaxrs21/providers/json/JsonBProvider.readFrom(JsonBProvider.java:125(Compiled Code))
4XESTACKTRACE                at org/apache/cxf/jaxrs/utils/JAXRSUtils$2.run(JAXRSUtils.java:1435(Compiled Code))
4XESTACKTRACE                at java/security/AccessController.doPrivileged(Bytecode PC:3(Compiled Code))
4XESTACKTRACE                at org/apache/cxf/jaxrs/utils/JAXRSUtils.readFromMessageBodyReader(JAXRSUtils.java:1432(Compiled Code))
4XESTACKTRACE                at org/apache/cxf/jaxrs/impl/ResponseImpl.doReadEntity(ResponseImpl.java:445(Compiled Code))
4XESTACKTRACE                at org/apache/cxf/jaxrs/impl/ResponseImpl.readEntity(ResponseImpl.java:380(Compiled Code))
4XESTACKTRACE                at org/apache/cxf/jaxrs/impl/ResponseImpl.readEntity(ResponseImpl.java:369(Compiled Code))
```
The root cause is that the one liner does not reuse the `Client` object, which is mentioned in [the package summary](https://javaee.github.io/javaee-spec/javadocs/javax/ws/rs/client/package-summary.html):
> The main entry point to the API is a ClientBuilder that is used to bootstrap Client instances - configurable, heavy-weight objects that manage the underlying communication infrastructure and serve as the root objects for accessing any Web resource.

and in [the specification](https://javaee.github.io/javaee-spec/javadocs/javax/ws/rs/client/Client.html):
> Clients are heavy-weight objects that manage the client-side communication infrastructure. Initialization as well as disposal of a Client instance may be a rather expensive operation.

But I feel it is not easy to imagine the lock contention from "heavy-weight objects". For ease of use and debug, I think either:

1. the implementation of the `Client` should reuse the `Jsonb` object as recommended in [the specification](https://javaee.github.io/javaee-spec/javadocs/javax/json/bind/Jsonb.html), or
> For optimal use, JsonbBuilder and Jsonb instances should be reused - for a typical use-case, only one Jsonb instance is required by an application.

2. the lock contention should be explicitly warned somewhere.

**Comment by WhiteCat22** [comment]
Hi, thanks for opening this issue.

As I'm sure you already know we recommend reusing the client as much as possible, you're going to get much better performance. However, I agree that locked jars are a problem.

We reuse the same code for our client and server. This involves creating new provider on initialization. Your problem won't ever happen on the server side because we are only getting JsonB once per application. 

Currently I'm not sure how much work it would take to implement caching of JsonB for clients in the same application.

Our architect is out today, but I'l talk with him next week and see if it is feasible.

**Comment by inatatsu** [comment]
@WhiteCat22 Thank you very much for your immediate response. Has the reusing JsonB become available from a specific version? The stack trace above was sampled from a web application deployed on [WebSphere Liberty Java EE 8 Java 11](https://hub.docker.com/layers/websphere-liberty/library/websphere-liberty/19.0.0.9-javaee8-java11/images/sha256-2b28eb32f4339298d1fa6a43a9f2a00461e921165c6a02319304ba6bc8849d95?context=explore). The client code executes the snippet above at every execution of the transaction.

**Comment by WhiteCat22** [comment]
Hi @inatatsu, sorry I didn't see you had responded. We did some investigating this week and found an old change made by a previous team to create a new bus for each client. 

>Has the reusing JsonB become available from a specific version?
Unfortunately no. We are going to attempt to revert this change and see how performance and regression is impacted. I'll update this issue as we progress.

**Comment by inatatsu** [comment]
@WhiteCat22 Is there any progress? Is the corresponding old change available as a git commit?

**Comment by WhiteCat22** [comment]
Hi @inatatsu,

We have not been able to investigate this yet. I suggest reusing your client for the time being.

**Comment by inatatsu** [comment]
@WhiteCat22 I see. Thanks.
