### ISSUE TITLE
Set ServletVersion for the servlet-5.0 feature

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#12021]
Outstanding Questions/Issues --
How to set the ServletVersion value in Servlet Factories. Currently, servletVersion would report incorrectly for servlet 5.0. Only one factory bundle is loaded at a time and that sets the servletversion in the webcontainer.

com.ibm.ws.webcontainer.servlet.4.0.factories/bnd.bnd -- Service-Component .

We may need to create update the transformer tool to update the manifest for these new attributes?

**Comment by volosied** [comment]
I believe the OSGI-INF/com.ibm.ws.webcontainer.v40.dd.xml contain the version: 

  <property name="version" type="Integer" value="40"/>

Follow up question: 

Any additional changes required for the following files (located within the web-container jar): 
OSGI-INF/com.ibm.ws.webcontainer.v40.httpProtocolBehavior.xml
OSGI-INF/com.ibm.ws.webcontainer.v40.httpTransportBehavior.xml
OSGI-INF/com.ibm.ws.webcontainer40.async.factory.AsyncContextFactory40Impl.xml
OSGI-INF/com.ibm.ws.webcontainer40.osgi.container.config.factory.WebAppConfiguratorFactory
OSGI-INF/com.ibm.ws.webcontainer40.osgi.response.factory.IRequestResponseFactory40Impl.xml
OSGI-INF/com.ibm.ws.webcontainer40.osgi.srt.factory.SRTConnectionContextPool40Impl.xml
OSGI-INF/com.ibm.ws.webcontainer40.osgi.webapp.factory.WebAppFactory40Impl.xml
OSGI-INF/com.ibm.ws.webcontainer40.servlet.factory.CacheServletWrapperFactory40Impl.xml
OSGI-INF/com.ibm.ws.webcontainer40.session.impl.factory.SessionContextRegistryImplFactory4
OSGI-INF/com.ibm.wsspi.webcontainer40.util.factory.URIMatcherFactory40Impl.xml
