### ISSUE TITLE
Investigate changing default value of stopAppStartUponListenerException for the servlet-5.0 feature

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#12020]
Investigate changing default value of `stopAppStartUponListenerException` for the servlet-5.0 feature

**Comment by pmd1nh** [comment]
Testing the default true to see if it break any tests.

https://github.com/OpenLiberty/open-liberty/pull/13016

**Comment by pmd1nh** [comment]
https://github.com/OpenLiberty/open-liberty/pull/13399

**Comment by pmd1nh** [comment]
https://github.com/OpenLiberty/open-liberty/pull/13430
