### ISSUE TITLE
Jakarta EE 9 : Optimize com.ibm.ws.anno for jakarta

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#12028]
Although there is a new `com.ibm.websphere.appserver.anno-2.0` feature to expose the `jakarta.annotation` API, there does not appear to be any reason to transform the `com.ibm.ws.anno` project.  Both features use the same underlying bundle, just expose different APIs.

However, it does appear that `com.ibm.ws.anno` does need some changes and or optimizations to properly support both `javax` and `jakarta` packages.  The following need to be addressed:

 - [ ] Unit Tests - currently use javax.annotation.Resource; should these support both?
 - [ ] ClassInfo in SPI provides a public constant `EJB_EXCEPTION_CLASS_NAME = "javax.ejb.EJBException";`; what is this for?  Is a `jakarta` version needed?
 - [ ] PackageInfo in SPI provides public constants like `JAVAX_CLASS_PREFIX = "javax.";`; are `jakarta` versions needed?
 - [ ] Any other "cache" improvements needed for `jakarta` classes?

**Comment by tbitonti** [comment]
Hi; the main issue is the third case, "JAVAX_CLASS_PREFIX", which ties into a split of the cache of class information.  A class store maintains a cache of recently visited classes.  That cache is (today) partitioned into a "java" part, a "javax" part, and an "everything else" part.  The "java" and "javax" parts are retained longer than the "everything else" part.  The update will be to add a fourth "jakarta" part.
