### ISSUE TITLE
GA BLOG LG-254: Console.log should have a date/time timestamp

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/open-liberty#12038]
**a) Which Liberty feature does it relate to?**
i) Human-readable name
`Open Liberty Logging`
ii) Feature name
`logging` is part of the Liberty kernel.
iii) Is this a new feature or is it an update to an existing feature for this release?
This is an update to the existing logging configuration
iv) Provide the qualified name of all changed feature deliveries to this release?
N/A

**b) Who is the target audience?**
Any developers, administrators and liberty users viewing the logs from the console view (standard-out)/console.log file.

**c) What does this feature provide in general? Write a sentence or two that introduces it to someone new to the concept.**
In Liberty, users have the option to format their server logs that appear in the console.log file in different formats, such as JSON and dev (default) formats, in their server logging configuration, using the consoleFormat logging attribute. The dev format will show messages in a basic format, where there are not timestamp or any other relevant information. It will only show the message with its log level and the message itself.

**consoleFormat=dev (default)**
`[AUDIT ] CWWKE0001I: The server server1 has been launched.`

**d) What is new/changed in this release?**
This feature introduces a new option called `simple` for the consoleFormat logging server configuration attribute. This new option will configure Liberty to output logs in the same simple (default) format as the message.log file, with date/time stamps and other relevant information, to the console.log file or to the console (Standard-out).

**consoleFormat=simple**
`[25/11/19 10:02:30:080 EST] 00000001 com.ibm.ws.kernel.launch.internal.FrameworkManager A CWWKE0001I: The server server1 has been launched.`

**e) Why should they get excited about this new thing (2-3 sentences)? Explain how this new feature literally makes their life easier? Why should they care? What was the problem before and how does this solve it for them?**
Currently, when viewing the console.log file or the console view, only the message and its corresponding log level is shown. Users can not clearly view the date/time stamp of each message or any other relevant information, regarding the message. They would have to defer to the messages.log file, to find the appropriate information. By setting the consoleFormat=simple in their server configuration, they can now view all the relevant information and the timestamp for a particular message from the console.log file or console view. It will be helpful to analyze when an event occurred in the applications/server, where JSON logging format is not feasible.

f. Explain how to make it work.
To configure the Liberty logs to output logs in the new simple console format, you just have to set the following logging server configuation, in the bootstrap.properties, server.xml, or in the server.env (environment variables).

**bootstrap.properties**
`com.ibm.ws.logging.console.format=simple`

**server.xml**
`<logging consoleFormat="simple"/>`

**server.env**
`WLP_LOGGING_CONSOLE_FORMAT=simple`

g) Provide links to any docs in the externally available Knowledge Center. If you don't know the URL, ask your ID person to predict it.

- https://openliberty.io/docs/ref/general/#logging.html
- https://openliberty.io/docs/ref/config/#logging.html

h) If relevant, provide links to external articles etc about this technology.
N/A
i) Is this feature part of Open Liberty or is it WebSphere Liberty-only?
This feature is part of Open Liberty.

j) Attach any images to this work item as .png files.
N/A

**Comment by tomjenningss** [comment]
Hi @pgunapal is there supposed to be a space in "[AUDIT ]"?

"_[AUDIT ] CWWKE0001I: The server server1"_

**Comment by pgunapal** [comment]
HI @tomjenningss , yes there is a space in the Log Level in console log default format messages.
"[AUDIT   ]"
