### ISSUE TITLE
GA BLOG 9013 JAAS Custom Login Module in Resource Adapter or Application

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#12048]
a. Which Liberty feature does it relate to?

   i. Human-readable name (eg WebSockets feature)
_JAAS Custom Login Modules_
   ii. Feature name (eg websockets-1.0)
_appSecurity-2.0_
   iii. Is this a new feature or is it an update to an existing feature for this release?
_update_
   iv. Provide the fully qualified name of all public features ( as '*.esa' filenames) that are delivered as part of this work
_com.ibm.websphere.appserver.appSecurity-2.0.esa_
_com.ibm.websphere.appserver.jca-1.7.esa_
       For example new or changed .esa files for public features in dev/com.ibm.websphere.appserver.features/build/libs/repo/

b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc
_appserver administrators_
c. Write a sentence or two that introduces it to someone new to the general technology/concept.
_This feature enables you to use JAAS Custom Login Modules that are embedded within a resource adapter or application._

d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)
_Prior to this feature, it was necessary to package (or repackage) JAAS Custom Login Modules into a separate shared library in order to configure Liberty to use them. It is now possible for JAAS Custom Login Modules to remain packaged within a resource adapter. Alternatively, even if you are not using a resource adapter at all, it is now possible to package JAAS Custom Login Modules within your application._
 
e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.

_Enable the AppSecurity and JCA features and configure a resource adapter. Use the  `classProviderRef` attribute on the `jaasLoginModule` element to reference the `id` of the resource adapter,_

```
<server>
  <featureManager>
    <feature>appSecurity-2.0</feature>
    <feature>jca-1.7</feature>
    ... other features
  </featureManager>

  <resourceAdapter id="eciResourceAdapter" location="${shared.resource.dir}/cicseci.rar"/>

  <!-- classProviderRef indicates that the login module class is found in the resource adapter -->
  <jaasLoginModule id="identityProp" controlFlag="REQUIRED"
      className="com.ibm.ctg.security.idprop.LoginModule"
      classProviderRef="eciResourceAdapter">
    <options propIdentity="Caller"/>
  </jaasLoginModule>

  <jaasLoginContextEntry id="CTGEntry" loginModuleRef="identityProp" name="CTGEntry"/>

  <connectionFactory id="cf1" jndiName="eis/cf1" jaasLoginContextEntryRef="CTGEntry">
    <properties.eciResourceAdapter ConnectionUrl="tcp://localhost" portNumber="2006" serverName="MYSERVER"/>
  </connectionFactory>

  ...
</server>
```

The same approach can be used for JAAS Custom Login Modules that are packaged within an application. Set the `classProviderRef` to point to the `id` of the `application`, `webApplication`, or `enterpriseApplication` element that contains the login module class.  When packaging JAAS Custom Login Modules within an application, in the login module within one of the following places:

- within a top level JAR of the enterprise application
- within a resource adapter module of the enterprise application
- within the web module of the enterprise application
- within an EJB module of the enterprise application
- within a web application

It should be noted that JAAS Custom Login Modules require the use of a resource reference with container managed authentication.

f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.
https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_sec_jaas.html

g. Attach any images to this work item as .png files.

**Comment by jakub-pomykala** [comment]
Closing. Issue live [here](https://openliberty.io/blog/2020/05/07/EJB-persistent-timers-20005.html#CLM)
