### ISSUE TITLE
Tests for CDI extension SPI

### ISSUE THREAD

**Issue by benjamin-confino** [OpenLiberty/open-liberty#12052]
**Testing Performed**

We will create a new user feature and test in the project `com.ibm.ws.cdi.extension_fat`

The user feature will make us of all the methods provided by the new CDI SPI to register different beans: It will register one bean via `getBeanClasses()` and it will register one CDI extension `getExtensions()`. The extension will in turn register a bean. The test will also include a CDI interceptor registered via `getBeanClasses()`.

We also create an application that runs on a server with the user feature enabled. It will verify it can inject the both the beans provided by the user feature and that when it does so the interceptor will be triggered correctly. This application will also attempt to inject a class from the user feature that has a CDI bean defining annotation but has not been registered via either of the SPI's methods. The test will pass if it is unable to inject this unregistered bean. 

This test will be fully automated as part of Liberty's FAT tests and run on all platforms as well as with both CDI 1.2 and 2.0

**Manual Testing Performed**

We collaborated with the CICS team to verify that this SPI works for allowing the injection of CICSContext into applications.

**Confidence**

3

**Comment by dave-waddling** [comment]
Hi @benjamin-confino,

Thanks for completing the Feature Test Summary (and for our conversations on Slack).

Everything looks good after the review, and the final test case made it into the SOE where it passed cleanly. I'll add the FAT Focal Approval to the parent epic now.
