### ISSUE TITLE
Removing startAfter dependency cycle does not start the apps

### ISSUE THREAD

**Issue by gjdeval** [OpenLiberty/open-liberty#12139]
Working in 20006 dev build (wlp-1.0.41.cl200620200508-0300) I deliberately created an app dependency cycle using the startAfter attribute in the webApplication element, like:

* app-A startAfter  app-B
* app-B startAfter  app-C
* app-C startAfter  app-D
* app-D startAfter  app-A

When the server was started, the app manager correctly detected and reported the dependency cycle as blocking startup for the involved apps, like:
```
CWWKZ0066E: The following applications cannot start because the value of their startAfter attributes result in a cycle: meetings2 meetings3 meetings4 meetings5 meetings6 meetings7 meetings8 meetings
```
With the server still running, I then edited the server.xml to break the dependency cycle by removing the startAfter attributed in one of the webApplication elements. 

The server recognized the config change and processed it, like:
```
CWWKG0016I: Starting server configuration update.
CWWKG0017I: The server configuration was successfully updated in 0.035 seconds.
```
But the app manager apparently did not reprocess the non-started apps, to discover that the startAfter cycle no longer existed, so the apps were not started.

**Comment by brenthdaniel** [comment]
The strange thing here is that we have a test that explicitly tests this case. This function can work as expected when app updates happen in a certain order, but I'm really surprised we haven't seen a failure for this test yet. 

Anyway, the referenced PR will fix the issue and also will prevent the server from waiting for apps involved in a cycle before reporting that it has started.
