### ISSUE TITLE
Job status is changed to failed even though the job is still running

### ISSUE THREAD

**Issue by albertwang-ibm** [OpenLiberty/open-liberty#12182]
**Describe the bug**
We created long running javabatch job (with checkpoint of writing every 20 records) to import records to our database, and we used REST API to check the job status every few seconds, and found that the job status was sometime changed from "started" to "failed" even thought the job was still running, and the job status was changed from "failed" to "finished" later after the job was really finished.

**Steps to Reproduce**
Configure IBM Cloud DB2 as job repo.
Start 2 job execution nodes.
Submit the job request to node one.
Check the job status on node two.
we expect the job status is "started" when the job is running, but sometime, it's changed to "failed" unexpectedly. 
This is almost always reproducible when both liberty nodes are just started.  

**Expected behavior**
The job status should never be marked as "failed" when the job is still running normally.

**Diagnostic information:**
 - OpenLiberty Version: [e.g. 20.0.0.3]
 - Java Version: 
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
Eclipse OpenJ9 VM (build openj9-0.20.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200416_608 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - cfa47e66cd5 based on jdk8u252-b09)
 - server.xml configuration (WITHOUT sensitive information like passwords)
```
<server description="fhir-server">
    <dataSource id="fhirbatchDS" jndiName="jdbc/fhirbatchDB">
        <jdbcDriver libraryRef="fhirSharedLib"/>
        <properties.db2.jcc 
        apiKey="${env.BATCH_DB_APIKEY}"
        currentSchema="JBATCH" 
        databaseName="BLUDB" 
        driverType="4"
        pluginName="IBMIAMauth" 
        portNumber="50001"
        securityMechanism="15" 
        serverName="${env.BATCH_DB_HOSTNAME}"
        sslConnection="true" />
    </dataSource>

</server>
```
 - If it would be useful, upload the messages.log file
    No meaningful info can be found in messages.log
**Additional context**
None

**Comment by scottkurz** [comment]
The fact that this happens shortly after server start makes me wonder if the lazy initialization of the job repository DB is somehow failing the app. 

I wonder how you are submitting jobs to one node or the other?  Via REST API ?  (You're not using the JMS dispatcher function are you?)

In any case, this sounds like a problem that would typically require a support case, collecting and analyzing logs, etc.

On your own, the batch job logs might be useful to give you some clue.   These would be found in the server output dir, typically _usr/servers/MyServer_  at path: **usr/servers/MyServer/logs/joblogs/...**

The output dir also has an  _ffdc_ directory of logs though these are intended for IBM support.

**Comment by albertwang-ibm** [comment]
we enabled the finest trace for javabatch as attached.
Inside the log, you can find that there is "failed" batch status just as what we saw in our tests, but then job was finished successfully later.  

[job.log](https://github.com/OpenLiberty/open-liberty/files/4630689/job.log)

**Comment by albertwang-ibm** [comment]
@scottkurz thanks for your information! and I have paste the job.log as suggested.
we do the tests using a kube cluster, and we use the REST API for both submitting and checking status of the import job. so the job submitting request and the following status check request could be routed to different pod of the kube cluster.

**Comment by albertwang-ibm** [comment]
After set defaultHostName in server.xml to meta.name of the kube pod, now the jobs run correctly now. thanks @scottkurz and Chris for helping identifying the root cause.
<variable name="defaultHostName" value="${env.MY_POD_NAME}" />
