### ISSUE TITLE
Cached configuration not used in some circumstances

### ISSUE THREAD

**Issue by brenthdaniel** [OpenLiberty/open-liberty#12212]
In some situations, configuration is reloaded despite the fact that none of the configuration has changed. For this to happen, specific configuration types have to be used and the system must have specific environment variables defined. 

In particular, the one case that I'm aware of is when a configuration includes `security-role` and the platform is something like OS X where the `USER` environment variable is defined.  Looking through the metatype, I don't think there are likely to be any other cases where this will happen, but it is theoretically possible.

**Comment by gjdeval** [comment]
Just to clarify - the platform underlying #11897 is Linux on Intel, not OS X

**Comment by brenthdaniel** [comment]
Yes, I used OS X as an example because it's always set there. There are some linux/other unix shells that don't set it.
