### ISSUE TITLE
Path of jvm.options file in shared directory should not depend on ${WLP_INSTALL_DIR}

### ISSUE THREAD

**Issue by Eng-Fouad** [OpenLiberty/open-liberty#12215]
According to the [documentation](https://openliberty.io/docs/ref/config/), `jvm.options` is read first from `${wlp.user.dir}/shared/jvm.options`. However, It is actually read from `${WLP_INSTALL_DIR}/usr/shared/jvm.options`:

https://github.com/OpenLiberty/open-liberty/blob/bf9b94dde3344d4ea11df0fddc595dd99a394e42/dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server#L657

https://github.com/OpenLiberty/open-liberty/blob/bf9b94dde3344d4ea11df0fddc595dd99a394e42/dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat#L571

The problem is that when we use custom `${wlp.user.dir}`, the `server` script does not read `jvm.options` from the shared directory.

**Comment by scottkurz** [comment]
Thanks for opening @Eng-Fouad.     I confirmed that, when setting the WLP_USER_DIR env var, on 20.0.0.5 the jvm.options is not read from `$WLP_USER_DIR/shared` as documented.    So it does look like a bug.

**Comment by Eng-Fouad** [comment]
@scottkurz This should be a simple fix, and I've already created PR for that.

**Comment by jimblye** [comment]
@NottyCode we have a WAS Liberty customer also asking for this change.  I asked @hlhoots, who suggested this could either be fixed in the docs or the code.    Do you have an opinion?

See [pull request ](https://github.com/OpenLiberty/open-liberty/pull/12438) for proposed code change.  Thanks.

**Comment by hlhoots** [comment]
duping this to #12606
