### ISSUE TITLE
OL Beta: Create docker images

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#12223]
Docker images should be created for the "ALL" and "Jakarta EE 9" profiles. They should be based on linux/amd64 and include Java 11 Open J9.

The Open Liberty profile on docker hub should be updated to include beta tags
https://hub.docker.com/_/open-liberty

- beta-full
- beta-jakartaee9
- 20.0.0.8-beta-full-java11-openj9
- 20.0.0.8-beta-jakartaee9-java11-openj9

Note that I am not sure about use of the term `full` in those tags, it could be omitted? That image should contain all GA and beta features ... I'm not sure if `full` is the right term?

**Comment by arthurdm** [comment]
hi @tevans78 - we have moved away from using specific profiles in our Docker Images.  Our focus is now on having either `kernel` + featureUtility or `full` for convenience.

**Comment by tevans78** [comment]
@arthurdm Just a full beta image would be fine... in which case we can just call it the `beta`;

- beta
- 21.0.0.1-beta-java11-openj9

**Comment by arthurdm** [comment]
thanks @tevans78 

Since the betas are just for the latest release, we could do something like:
`beta` (Ubuntu + AdoptOpenJDK 8 OpenJ9)
`beta-java11` (Ubuntu + AdoptOpenJDK 11 OpenJ9)

@leochr - let me know if that fits your thoughts as well.

**Comment by leochr** [comment]
@arthurdm sounds good. I'll add the support for those tags. Thanks.

**Comment by leochr** [comment]
@tevans78 The beta tags (`java` and `java-11`) are available in Docker hub: https://hub.docker.com/_/open-liberty/
