### ISSUE TITLE
JakartaEE: Enable FacesContainer-3.0 Feature in Open Liberty [EPIC]

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#12234]
Top Tier Issue for Faces Container 

We currently have a `jsfContainer` feature for JSF 2.2 and JSF 2.3.

We'll need one for JSF 3.0.

**Comment by pnicolucci** [comment]
https://github.com/OpenLiberty/open-liberty/issues/14233 this was delivered in the 200012 timeframe (21001-beta) so retagging.

**Comment by malincoln** [comment]
@pnicolucci  pls add FAT summary to overall epic here:  https://github.com/OpenLiberty/open-liberty/issues/12969

**Comment by volosied** [comment]
Fat approved. No other changes planned. 

Closing Issue.
