### ISSUE TITLE
Investigate any servlet auto features that need to be updated for Jakarta EE9

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#12259]
Investigate any servlet auto features that need to be updated for Jakarta EE9

**Comment by isaacrivriv** [comment]
For now this it the list of auto features that may have to be updated

- [ ] com.ibm.websphere.appserver.autoRequestTimingServlet-1.0 contains all previous servlet versions up to 3.0
- [ ] com.ibm.websphere.appserver.cdi2.0-servlet4.0 could require another feature for servlet 5.0 and cdi 3.0 but I think its already covered by io.openliberty.cdi3.0-servlet5.0 auto feature
- [ ] com.ibm.websphere.appserver.jaxwsweb-2.2 and 2.3 could require update when jaxws gets delivered for jakarta
- [ ] com.ibm.websphere.appserver.managedBeansWar-1.0 could required updated but I think its already covered by io.openliberty.managedBeansWar-2.0
- [ ] com.ibm.websphere.appserver.sessionMonitor-1.0 contains all previous servlet versions up to 3.0
- [ ] All springboot server features
> - [ ] com.ibm.websphere.appserver.springBoot15ServerSupport-1.0
> - [ ] com.ibm.websphere.appserver.springBoot20ServerSupport-1.0
> - [ ] com.ibm.websphere.appserver.springBootServerSupport-1.0
- [ ] com.ibm.websphere.appserver.webAppSecurity-1.0 could require update for servlet 5.0 but I think is covered by io.openliberty.webAppSecurity-2.0
- [ ] com.ibm.websphere.appserver.webcontainerMonitor-1.0 could require update for servlet 5.0
- [ ] com.ibm.websphere.appserver.webJ2eeManagement-1.0 could require update for servlet 5.0
- [ ] io.openliberty.app.manager.wab could require update for I think is already covered by io.openliberty.app.manager.wab.jakarta

**Comment by isaacrivriv** [comment]
All the auto features have been investigated and updated accordingly
