### ISSUE TITLE
Investigate any Jakarta updates in JSF auto features

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#12262]
Looking at the current state of our features it doesn't look as though there are any remaining items here:
```

io.openliberty.cdi3.0-faces3.0.feature
io.openliberty.faces3.0-beanValidation3.0.feature
```

The above `faces-3.0` auto features mimic the existing `jsf-2.3` auto features:

```
com.ibm.websphere.appserver.cdi2.0-jsf2.3.feature
com.ibm.websphere.appserver.jsf.beanValidation-2.3.feature
```

**Comment by pnicolucci** [comment]
These is `com.ibm.websphere.appserver.jsf2.3-jsfApiStub2.3.feature` in liberty which we might need to add an additional feature for the third party faces-3.0

**Comment by isaacrivriv** [comment]
The jsf stub features were added for OSGi apps and there is no support for for OSGi apps with Jakarta EE8+ so no updated needed on these auto features. All the auto features are covered so this should be good to close.
