### ISSUE TITLE
Spring Boot 2.x features

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#12279]
Spring Boot support in Liberty currently includes two features: springBoot-1.5 and springBoot-2.0

These names are confusing because they imply a very specific version of Spring Boot.  But the two Spring Boot features are able to work with other versions.  For example, springBoot-2.0 works with Spring Boot 2.0, 2.1 and 2.2 and we assume it will also work with Spring Boot 2.3 but it is not clear to customers if this is the case.  We need to consider adding additional public features that make it clear that we support newer versions of Spring Boot 2.x

**Comment by tjwatson** [comment]
At a minimum we need to ensure the documentation is clear that the springBoot-2.0 feature is used to enable applications using Spring Boot 2.x.  Right now at least some documentation indicates that it enables 2.0.x Spring Boot applications to work.

**Comment by atosak** [comment]
Closing per Alasdair and Tom's confirmation.
