### ISSUE TITLE
Investigate any websocket auto features that need updates for Jakarta EE9

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#12277]
There is at least one auto feature for CDI and websockets.

This auto feature enables the following bundle `com.ibm.ws.wsoc.cdi.weld`

We should also move the CDI tests for websockets over to open liberty.

**Comment by isaacrivriv** [comment]
Waiting on the delivery of wasJmsServer/Client jakarta features to test cdi integration with wsoc
