### ISSUE TITLE
Pull in the latest API JARs for Jakarta Server Pages 3.0

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#12271]
Pull in the latest Jakarta Server Pages 3.0 JARS from Eclipse

**Comment by volosied** [comment]
JSTL: https://repo1.maven.org/maven2/jakarta/servlet/jsp/jstl/jakarta.servlet.jsp.jstl-api/

-Latest release is  still 2.0.0-RC1

JSP: https://repo1.maven.org/maven2/jakarta/servlet/jsp/jakarta.servlet.jsp-api/

- Latest release is 3.0.0-RC2

**Comment by pnicolucci** [comment]
https://github.com/OpenLiberty/open-liberty/pull/14938
