### ISSUE TITLE
webBundle feature support for jakarta 9

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#12281]
The protected feature com.ibm.wsspi.appserver.webBundle-1.0 needs support Jarkarta EE 9 Servlet 5.0

**Comment by sebratton** [comment]
Completed with PR #12247

**Comment by malincoln** [comment]
@sebratton  pls add the FAT summary here:  https://github.com/OpenLiberty/open-liberty/issues/12969

**Comment by sebratton** [comment]
Closing issue after reviewing FAT coverage with squad and updating the FAT Approval Test Summary.
