### ISSUE TITLE
NullPointerException observed when upgrading from jax-rs 1.1 to jax-rs 2.0 on an application that also uses Context & Dependency Injection (CDI)

### ISSUE THREAD

**Issue by Tonmcl** [OpenLiberty/open-liberty#1228]
Specifically, when injecting an object using CDI annotations, into an instance of javax.ws.rs.ext.MessageBodyWriter, and arranging for that object to be called from the MessageBodyWriter.isWriteable method, the injected object is null on the first call to that method, resulting in a NullPointerException. This typically happens on the first call to the writer's isWriteable method during a jax-rs request-response, and subsequent calls work ok.

It appears that the first usage is to a writer instance that is created without CDI involvement, and then the system swaps out this instance for another writer instance that has the injected object, and all is then well (the infrastructure creating and managing these instances).

I've tried using WLP 17.0.0.2 and 17.0.0.3 and also tried an older 8.5.5.6 install, with the same results.

**Comment by andymc12** [comment]
@Tonmcl can you verify that @WhiteCat22 's fix in #1397 resolved the NPE?  If so, can you please close this issue?

Thanks, Andy

**Comment by Tonmcl** [comment]
tested in openliberty-all-17.0.0.4-20180113-0741.zip - looks good
