### ISSUE TITLE
Fix com.ibm.websphere.javaee.jsp.tld.2.2 location 

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#12298]
Currently, _com.ibm.websphere.javaee.jsp.tld.2.2_ resides in the dev/api/spec/ location, but it is  an _implementation_, not an API. 

**API:** 
- com.ibm.websphere.javaee.jstl.1.2
- com.ibm.websphere.jakartaee.jstl.2.0 (jakarta) 

**IMPL:** 
- com.ibm.websphere.javaee.jsp.tld.2.2
- com.ibm.websphere.javaee.jsp.tld.2.2.jakarta

See Features Files:

JSP -2.2
https://github.com/OpenLiberty/open-liberty/blob/master/dev/com.ibm.websphere.appserver.features/visibility/public/jsp-2.2/com.ibm.websphere.appserver.jsp-2.2.feature

 JSP-2.3
https://github.com/OpenLiberty/open-liberty/blob/master/dev/com.ibm.websphere.appserver.features/visibility/public/jsp-2.3/com.ibm.websphere.appserver.jsp-2.3.feature

 JSP-3.0
https://github.com/OpenLiberty/open-liberty/blob/master/dev/com.ibm.websphere.appserver.features/visibility/public/jsp-3.0/com.ibm.websphere.appserver.jsp-3.0.feature

**Comment by pnicolucci** [comment]
One other thing to look at here if we have not already figured it out is how do the tools use:

`com.ibm.websphere.javaee.jsp.tld.2.2` we add this / the jakarta counter part depending on the feature as a jar to the JSP features.
