### ISSUE TITLE
Allowing users to define more of the Open Liberty as a Windows service parameters for prunsrv.exe

### ISSUE THREAD

**Issue by hlhoots** [OpenLiberty/open-liberty#12329]
The initial implementation of running an Open Liberty server as a Windows service (https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_setup_new_server_winserv.html) utilizes the prunsrv.exe command from Apache Commons Daemon.  The prunsrv.exe command line properties needed to register/start/stop/unregister the Open Liberty server were hard coded in the server.bat file and have worked well since its creation.

We're seeing more instances where a user needs to add an additional command line parameter that is not specified as a fixed value in the server.bat file.  Thus resulting in the question of how do we expose other prunsrv.exe command line parameters that the user can configure. 

A list of these parameters (~ 40) are listed here under the 'Command line parameters' section: https://commons.apache.org/proper/commons-daemon/procrun.html

Proposed solutions:
1.  Change the server command to take these as arguments and parse out the values and apply. 
2.  Create a prunsrv.options file, and have the server.bat script read any properties from there and apply them when the server.bat script runs the Open Liberty as a service commands.

**Comment by hlhoots** [comment]
Another case for adding this function is to allow the user to specify the --LogLevel=Debug to gather troubleshooting data.  We currently dont set this parameter and it defaults to --LogLevel=Info.

**Comment by NottyCode** [comment]
Need to look at the options for prunsrv to see which ones make sense given the options we already set, for example setting JVM startup options likely doesn't make sense given the server batch script is used to launch the server. Currently the following options are set on prunsrv:
  
    "!WLP_INSTALL_DIR!\bin\tools\win\prunsrv.exe"  //IS//%SERVER_NAME% 
    --Startup=manual 
    --DisplayName="%SERVER_NAME%" 
    --Description="Open Liberty" 
    ++DependsOn=Tcpip 
    --LogPath="%WLP_INSTALL_DIR%\usr\servers\%SERVER_NAME%\logs" 
    --StdOutput=auto 
    --StdError=auto 
    --StartMode=exe 
    --StartPath="%WLP_INSTALL_DIR%" 
    --StartImage="%WLP_INSTALL_DIR%\bin\server.bat" 
    ++StartParams=start#%SERVER_NAME% 
    --StopMode=exe 
    --StopPath="%WLP_INSTALL_DIR%" 
    --StopImage="%WLP_INSTALL_DIR%\bin\server.bat" 
    ++StopParams=stop#%SERVER_NAME%

**Comment by hlhoots** [comment]
These are the other potential parameters that are valid for a user to set on prunsrv:

--User : User account used for running executable. It is used only for StartMode Java or exe and enables running applications as a service under an account without the LogonAsService privilege.

--Password : Password for user account set by --User parameter

--ServiceUser : Specifies the name of the account under which the service should run. Use an account name in the form DomainName\UserName. The service process will be logged on as this user. if the account belongs to the built-in domain, you can specify .\UserName Note that the Service Control Manager does not accept localised forms of the standard names so to use them you need to specify NT Authority\LocalService, NT Authority\NetworkService or LocalSystem as appropriate.

--ServicePassword : Password for user account set by --ServiceUser parameter

--StopTimeout : Defines the timeout in seconds that procrun waits for service to exit gracefully.

--LogPrefix : Defines the service log filename prefix. The log file is created in the LogPath directory with .YEAR-MONTH-DAY.log suffix

--LogLevel : Defines the logging level and can be either Error, Info, Warn or Debug. (Case insensitive).

--PidFile : Defines the file name for storing the running process id. Actual file is created in the LogPath directory

Of these, --ServiceUser needs to be set to resolve a bug when we upgraded to prunsrv 1.2.0; the default user was changed from LocalSystem to LocalService.

Additionally, one of the most useful for L3 support would be the --LogLevel being set to Debug.

**Comment by hlhoots** [comment]
Discussed with the group on 6/9/2020.  

The general thought was that users probably didnt need most of the 8 parameters above.  The two that do seem necessary are --ServiceUser and --LogLevel.

Suggestion was just to hard code --ServiceUser=LocalSystem to resolve the bug encountered from the update from 1.x to 1.2.0 where Apache Commons Daemon changed the service user default.

Also hard code --LogLevel=Info, and the user could just edit server.bat to change it to Debug if needed for troubleshooting.  The rationale was that users would feel more comfortable changing Info to Debug vs having to add the whole parameter.

In general users do tend to edit server.bat on their own, so perhaps architecting a generic solution as originally proposed is overkill, and we should just let users add parameters themselves as needed.

**Comment by hlhoots** [comment]
After further discussion, the resolution is as follows:
1. We will hard code --ServiceUser=LocalSystem to resolve the bug encountered from the update from 1.x to 1.2.0 where Apache Commons Daemon changed the service user default. This fixes #12312
2. We will make no changes to enable Debug for prunsrv.  If support needs to enable, it can be done manually by cd \wlp\bin\tools\win and executing prunsrv //US//<server_name_inserted_here> --LogLevel=Debug

**Comment by hlhoots** [comment]
Implemented #1 in PR #13051
