### ISSUE TITLE
server package minify complains of illegal reflective access

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/open-liberty#12397]
**Describe the bug**

Server package minify outputs the following warnings

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.ibm.ws.kernel.service.location.internal.Activator (file:/Users/charters/Downloads/wlp/lib/com.ibm.ws.kernel.service_1.3.40.jar) to field javax.naming.spi.NamingManager.initctx_factory_builder
WARNING: Please consider reporting this to the maintainers of com.ibm.ws.kernel.service.location.internal.Activator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Steps to Reproduce**
Download and unzip Liberty (e.g. 20.0.0.5)
Create a server 'bin/server create'
Package the server 'bin/server package --include=minify

**Expected behavior**
I don't expect to see the warnings

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.5
 - Java Version: java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Mac OS X amd64-64-Bit Compressed References 20200122_450 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)

 - the default server xml from 'bin/sever create' will do.

**Additional context**

**Comment by hlhoots** [comment]
There were some script changes made when we moved to Java 9 such that some additional java options (wlp\lib\platform\java\java9.options) are applied to removed these warnings.  These changes were not applied to the server package (with --include=minify - which starts the server to build the smaller image) command.

**Comment by hlhoots** [comment]
Should now be resolved.
