### ISSUE TITLE
BETA BLOG 20600: Jakarta Servlet 5.0, Jakarta Server Pages 3.0 and Jakarta Expression Language 4.0

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#12394]
Beta blog post for: https://github.com/OpenLiberty/open-liberty/issues/11819, https://github.com/OpenLiberty/open-liberty/issues/11717 and https://github.com/OpenLiberty/open-liberty/issues/11720. These are sub epics of the overall Jakarta EE9 epic here:  https://github.com/OpenLiberty/open-liberty/issues/9876
Development progress update

a. Which Liberty feature does it relate to?

   i. Human-readable name (eg WebSockets feature)
`Jakarta Servlet 5.0`, `Jakarta Expression Language 4.0`, `Jakarta Server Pages 3.0`

   ii. Feature name (eg websockets-1.0)
`servlet-5.0`, `el-4.0`, `jsp-3.0`

   iii. Is this a new feature or is it an update to an existing feature for this release?
`These are new features for Jakarta EE9.`

   iv. Provide the fully qualified name of all public features ( as '*.esa' filenames) that are delivered as part of this work

       (eg: com.ibm.websphere.appserver.transportSecurity-1.0.esa)

       For example new or changed .esa files for public features in dev/com.ibm.websphere.appserver.features/build/libs/repo/

`com.ibm.websphere.appserver.servlet-5.0.esa`
`com.ibm.websphere.appserver.el-4.0.esa`
`com.ibm.websphere.appserver.jsp-3.0.esa`

b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc

`application developers`

c. Write a sentence or two that introduces it to someone new to the general technology/concept.

`These features are a subset of the Jakarta EE9 features. The largest change in these features is they have all been updated to use and reference the new jakarta namespace. Previously the APIs used a javax namespace, but as part of Jakarta EE9, the packages were updated from javax to jakarta.` 

d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)

`Application developers can start working with the new jakarta namespaces as part of Jakarta EE9. The functionality of the features will be the same as the previously released Jakarta EE8 features but with updated packages and references to the new jakarta namespace.`
 
e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.

One or more of the following features can be included in your server.xml:

```
    <featureManager>
        <feature>jsp-3.0</feature>
        <feature>servlet-5.0</feature>
        <feature>el-4.0</feature>
    </featureManager>
```

`The jsp-3.0 feature includes the servlet-5.0 and el-4.0 features so the minimum set of features to enable to get all three features enabled is jsp-3.0`
 
f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

g. Attach any images to this work item as .png files.
------

**Comment by pmd1nh** [comment]
section e. perhaps include some information about implicit including of dependent features. (i.e <feature>jsp-3.0</feature> will automatically pull in <feature>servlet-5.0</feature> ...)

**Comment by pnicolucci** [comment]
@pmd1nh  I added the following: The jsp-3.0 feature includes the servlet-5.0 and el-4.0 features so the minimum set of features to enable to get all three features enabled is jsp-3.0

**Comment by lauracowen** [comment]
thanks @pnicolucci

**Comment by lauracowen** [comment]
thanks @pn
