### ISSUE TITLE
GA BLOG: Support provisioning features from maven repository

### ISSUE THREAD

**Issue by herman-kailey** [OpenLiberty/open-liberty#12415]
a. Which Liberty feature does it relate to?

   i. Human-readable name (eg WebSockets feature)
      featureUtility command line tool
   ii. Feature name (eg websockets-1.0)
      featureUtility
   iii. Is this a new feature or is it an update to an existing feature for this release?
       New Feature
b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc
    Operation teams and container developers
c. Write a sentence or two that introduces it to someone new to the general technology/concept.
    Users are now able to install desired features to their Open Liberty runtimes from maven repositories using a command line tool.
d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)
    Previously users did not have a convenient tool to install features onto their Open Liberty runtimes, but now a user will be able to install features onto their Open Liberty runtimes from Maven Central or an on-prem Maven repository (Artifactory or Nexus) using a convenient command line tool.

e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.
 
Use the _wlp_/bin/featureUtility command to find, get information about, and install assets that are in a Maven repository.
Usage examples

Display help information for the installFeature action:

`featureUtility help installFeature
`

Install the MicroProfile Health 2.2 feature from Maven Central:

`featureUtility installFeature mpHealth-2.2`

or:

`featureUtility installFeature io.openliberty.features:mpHealth-2.2`

Install server features for the myserver server:

`featureUtility installServerFeatures myserver`

Install the MicroProfile Health 2.2 feature without caching the feature to the local Maven repository:

`featureUtility installFeature mpHealth-2.2 --noCache`

Install server features for the myserver server without caching the features to the local Maven repository:

`featureUtility installServerFeatures myserver --noCache`

Install the Admin Center feature from Maven Central:

`featureUtility installFeature adminCenter-1.0 --acceptLicense`

Install features for the myserver server with debug enabled:

`featureUtility installServerFeatures defaultServer --verbose`

View a template of your featureUtility.properties file:

`featureUtility viewSettings`

Search for the MicroProfile Health 2.2 feature from Maven Central and all configured Maven repositories:

`featureUtility find mpHealth-2.2`

Search for all available features from Maven Central and all configured Maven repositories:

`featureUtility find`

f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.
n/a
g. Attach any images to this work item as .png files.

**Comment by jakub-pomykala** [comment]
Closing. Issue live [here](https://openliberty.io/blog/2020/06/05/graphql-open-liberty-20006.html#MVN)
