### ISSUE TITLE
Jakarta Transformer Build Integration:  Support additional BND directives

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/open-liberty#12445]
Per the linked pull request, new BND directives were added as follows:

```
Override the transformed bundle name:
  'jakartaFinalJarName'

Supply local properties files; these must be placed in a project 'rules' folder:
  'jakartaLocalSelections'
  'jakartaLocalRenames'
  'jakartaLocalVersions'
  'jakartaLocalBundles'
  'jakartaLocalDirect'
  'jakartaLocalTextMaster'

Add specific bundle update data:
  'jakartaInitialBundleId'
  'jakartaFinalBundleId'
  'jakartaFinalBundleVersion'
  'jakartaFinalBundleShortName'
  'jakartaFinalBundleDescription'
```

See task 'jakartaeeTransform' in 'https://github.com/OpenLiberty/open-liberty/blob/integration/dev/wlp-gradle/subprojects/tasks.gradle' for implementation details.

---

The existing BND directive to activate the jakarta transformer is a simple true/false flag.

We have had a request to override the default transformed jar name 
  - existing is <bundle-name>.jakarta.jar

New directives:
`jakartaee.transform.jar.name=<new jar name>`

MANIFEST - directives...
```
JakartaEE-Bundle-Name: ...
JakartaEE-Bundle-Symbolic-Name: ...
JakartaEE-Bundle-Version: ...
JakartaEE-Bundle-Description: ...

```
These properties would then be passed via command line arguments to the transformer.

**Comment by tbitonti** [comment]
Linked transformer issue: https://github.com/OpenLiberty/open-liberty/issues/12446

**Comment by tbitonti** [comment]
The ability to choose an output name that is different than the current jakarta name can be handled entirely through the build scripts: The transformer uses an explicit "output file name" parameter, and the build scripts are free to specify whatever particular output name is appropriate.

The other BND directives will require either more extensive build scripting (to dynamically generate rules files for the transformer), or will require new command line options to the transformer tool.  My sense is that adding new options is the better way to provide the new function.
