### ISSUE TITLE
Batch: Fixes for remote partition job logs

### ISSUE THREAD

**Issue by cgianfra** [OpenLiberty/open-liberty#12450]
Logs from Batch job partitions that are run on remote endpoints are not accessible via the REST interface as other job logs are. We need a set of fixes that will ensure these logs can be accessed using the same interface as locally-run jobs.

**Comment by scottkurz** [comment]
From the PR, it looks like this covers both:
- GET
- DELETE (purge) 
Might help later to clarify.

**Comment by cgianfra** [comment]
Summary of changes:

When doing REST job log operations, we have JobInstanceLog and JobExecutionLog to represent the files we're working with. I've added RemotePartitionLog. so the relationship is one JobInstanceLog has one or more JobExecutionLogs, which have zero or more RemotePartitionLogs.

Creating those RemotePartitionLog objects is where we fetch the remote partition rest URL and job log path that we've been storing in the new table. Previously, at a job execution level, we only had the concept of "is this local? yes/no". now in JobExecutionLog there's an enum:

    /**
     * EXECUTION_LOCAL: The job execution ran on this server
     * PARTITION_LOCAL: The job execution did not run on this server, but at least one remote partition did
     * NOT_LOCAL: Neither the execution nor any remote partitions ran on this server
     */
    public enum LogLocalState {
        NOT_LOCAL, EXECUTION_LOCAL, PARTITION_LOCAL
    }

So we can tell if the current server has nothing, has the execution, or has one or more of the partitions

This is used in the REST classes JobInstances/JobExecutions to figure out how to access everything. if we're NOT_LOCAL, we need to pass the request to the execution owner similar to how we do it today. if we're EXECUTION_LOCAL but there are remote partitions, we need to make requests to the partition owners to get their logs.

I used a REST parameter localOnly to facilitate this. The idea is that this is to mark our own internal requests so we don't end up recursing on ourselves.

So an example flow would be something like:

- You request a job execution log from the dispatcher.
- The dispatcher considers the logs NOT_LOCAL because nothing ran there. he finds the owner of the execution, and either forwards or redirects the request, as we do today.
- The execution endpoint gets the request, and tags it EXECUTION_LOCAL, but finds that there are remote partitions.
- We go through the remote partition REST URLs to find all the endpoints we need to hit. for each of them, we send a new REST request, but we add the localOnly flag.
- Each of the endpoints gets a request with the localOnly flag set. they find that they're PARTITION_LOCAL, so they use the job log root dir info from the remote partition db entry to find the logs, and return them in either text or zip form.
- Back at the execution owner, we compile the results to send back. for text this is just concatenating each result into one big file, then adding the logs from the non-partitioned part of the execution. for zip we have to do a little work to copy the ZipEntry objects into a new zip along with the local execution logs, but it works out pretty cleanly. in either case, the result mimics what you'd see if the partitions ran local to the execution owner.
