### ISSUE TITLE
TCPChannel: Add a shutdown logic check to avoid autofvt intermittent

### ISSUE THREAD

**Issue by billw1024** [OpenLiberty/open-liberty#12479]

**Comment by pnicolucci** [comment]
@billw1024  should this one be marked as a `release bug` ?

**Comment by billw1024** [comment]
@pnicolucci no, not to me.  It happened on one build in autoFVT, so extremely intermittent at best, and I can not tell exactly what the circumstances were.  I think this is due to a lot of stop/start of the server during autoFVT, but could have been something else going on with this one run, like some unique network issue at that time, etc.....  I think it would be something that would be more confusing to a customer to see published somewhere, than not.   I wouldn't fix it, except that this is our process for build breaks, and the fix seems quite safe.
