### ISSUE TITLE
Improve performance of OIDC RP with access token cache

### ISSUE THREAD

**Issue by jensengelke** [OpenLiberty/open-liberty#12496]
**Is your feature request related to a problem? Please describe.**
We observed significant performance impact when consuming REST APIs using _opaque_ OAuth access_tokens (which need to be introspected). 
We have one use case with 25% lower throughput while simulating browser users.
A different report about a programmatic REST client was way worse like 100s vs. 30 invocations per second.

**Describe the solution you'd like**
Cache introspect responses with configurable timeout similar to https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.liberty.autogen.nd.doc/ae/rwlp_config_okdServiceLogin.html 
This allows us to balance between when we notice revocation vs. performance.

**Describe alternatives you've considered**
We might be able to use JWT instead of opaque tokens, however, in our LDAP users can be be in many groups, letting JWT grow to like 10kB - signficantly increasing network bandwidth.

**Additional context**
We have been falling back to cookie based authentication for browser use cases in some scenarios, but this has different issues, like CSRF and uncommon pattern for non-browser clients.

**Comment by chnke** [comment]
Here are the complete results (200 invocations of the REST API using cURL):
1. Basic Auth: 6s
2. JWT + HS256: 14s
3. Opaque + HS256: 42s
4. Opaque + RS256: 44s
5. Opaque + RS256, using ID-TOKEN: 14s

I can share the configuration files, if needed.
So opaque token with RS256 is roughly 7 times slower than BA, 3 times slower than JWT. (edited) 

For the cases 4 and 5, it is observed visually that the requests look to become slower and slower. This may require further investigation.

Improvements:
- We could use ID-TOKEN to workaround the case of opaque+RS256, but the JWT local validation can be optimized.
- Opaque token remote introspection could be cached.

**Comment by ayoho** [comment]
Implementing this may also be able to deliver the performance improvement sought by https://github.com/OpenLiberty/open-liberty/issues/14971.

**Comment by teddyjtorres** [comment]
Added label for prioritization. No design appears to be needed at the moment.

**Comment by samwatibm** [comment]
BPM is escalating this as a resolution to case TS004489270

**Comment by ayoho** [comment]
We'll probably be taking another look at this in 1Q, so I'm going to move this back to our Backlog.

**Comment by teddyjtorres** [comment]
An access token cache is being added as part of https://github.com/OpenLiberty/open-liberty/issues/14646 in 21.0.0.9 beta. You can try it out by adding the openidConnectClient's accessTokenCacheEnabled and accessTokenCacheTimeout attributes. For the moment, setting tokenReuse="true" is also required. This will change in an upcoming update for opaque tokens.

Please feel free to try this out and let us know your experience.

**Comment by ayoho** [comment]
Actually delivered under https://github.com/OpenLiberty/open-liberty/pull/17632
