### ISSUE TITLE
Update OpenID Connect client API to retrieve raw id_token

### ISSUE THREAD

**Issue by chunlongliang-ibm** [OpenLiberty/open-liberty#12504]
The openidConnectClient-1.0 feature has API com.ibm.websphere.security.openidconnect.token.IdToken, which has getter to retrieve claims. However there is no way to get the original raw id_token. This request is to add a method to retrieve the raw id_token

**Comment by chunlongliang-ibm** [comment]
see https://github.com/OpenLiberty/open-liberty/issues/10091

**Comment by chunlongliang-ibm** [comment]
Here is the sample code:

    public String getRawIdToken() throws WSSecurityException {
        Subject subj = WSSubject.getRunAsSubject();
        Set<Object> privCredentials = subj.getPrivateCredentials();
        for (Object credentialObj : privCredentials) {
            if (credentialObj instanceof Map) {
                Object value = ((Map<?, ?>) credentialObj).get("id_token");
                if (value != null)
                    return (String) value;
            }
        }
        
        return null;
    }

**Comment by ayoho** [comment]
https://github.com/OpenLiberty/open-liberty/pull/13126 is the PR that Julien opened for the product code change. The next step is to develop FATs to ensure the new API works before we deliver it.
