### ISSUE TITLE
disableLtpaCookie for spnego and TAI authentication, and disableJwtCookie for jwtSSO authentication Feature Test Summary

### ISSUE THREAD

**Issue by Zech-Hein** [OpenLiberty/open-liberty#12512]
**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature.

If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by Zech-Hein** [comment]
We added automated FAT test cases to the following existing FATs:
1. `com.ibm.ws.security.spnego_fat` [CL 20906](https://github.ibm.com/was-liberty/WS-CD-Open/pull/20906)
2. `com.ibm.ws.security.authentication.tai_fat` [CL 21109](https://github.ibm.com/was-liberty/WS-CD-Open/pull/21109)
3. `com.ibm.ws.security.jwtsso_fat` #12494 

## com.ibm.ws.security.spnego_fat Automated Test Cases:
1. `testDisableLTPACookie_true()` Tests setting the disableLtpaCookie="true" in the spengo server config. Expects the LtpaCookie to NOT be returned in the response for spnego authentication.  
2. `testDisableLTPACookie_false()` Tests setting the disableLtpaCookie="false" in the spengo server config. Expects the LtpaCookie to be returned in the response for spnego authentication.

## com.ibm.ws.security.authentication.tai_fat Automated Test Cases:
### Shared Library Tests
1. `testTAI_disableLtpaCookie_true()` tests shared library TAI with disableLtpaCookie="true" in TAI config element. Expects Ltpa Cookie to NOT be return in response for TAI authentication.
2. `testTAI_disableLtpaCookie_false()` tests shared library TAI with disableLtpaCookie="false" in TAI config element. Expects Ltpa Cookie to NOT be return in response for TAI authentication.
3. `testTAI_disableLtpaCookie_false_sharedLib_true()` tests custom library interceptor config should be ignored and TAI config element used for disableLtpaCookie property

### User Feature Tests
4. `testTAI_disableLtpaCookie_true_feature_false()` test user feature with disableLtpaCookie set to "true" in TAI config and  "false" in interceptor, expects user feature interceptor to override TAI config and Ltpa Cookie should be found in the response.
5. `testTAI_disableLtpaCookie_false_feature_true()` test user feature with disableLtpaCookie set to "false" in TAI config and  "true" in interceptor, expects user feature interceptor to override TAI config and Ltpa Cookie should NOT be found in the response.

### Combined Shared Library and user Feature Automated Test
6. `testTAI_feature_and_lib_disableLtpaCookie_false()` test a configuration with userFeature TAI and a sharedLibrary TAI where userFeature interceptor sets disableLtpaCookie to "true" and server.xml config sets to "false". Authentication is performed by the sharedLibrary TAI in this case and we expect the ltpaCookie to be found in the response.

## com.ibm.ws.security.jwtsso_fat Automated Test Cases:
1. `test_disableJwtCookie_true_includeLtpaCookie_true()` 
    Expects the Ltpa cookie to be found in the response, and the Jwt cookie to not be found.
2. `test_disableJwtCookie_true_includeLtpaCookie_true_differentJwtCookieName()` 
   Expects the same as the 1st testcase but also changes the Jwt CookieName set in the config and verifies it is not found in the response.
3. `test_disableJwtCookie_true_includeLtpaCookie_true_useLtpaIfJwtAbsent_false()`
   Expects the Ltpa cookie to be found in the response, and the Jwt cookie to not be found. We also expect to not successfully reach the protected resource.
4. `test_disableJwtCookie_true_includeLtpaCookie_false()`
   Expects neither Jwt nor Ltpa cookie is in the response, and the client remains on the login page.
5. `test_disableJwtCookie_false_includeLtpaCookie_true()`
   Expects the Jwt and Ltpa cookies to both be found in the reponse.
6. `test_disableJwtCookie_false_includeLtpaCookie_false()`
   Expects the Jwt cookie to be found in the reponse but not the Ltpa cookie.
7. `test_disableJwtCookie_false_includeBadLtpaCookie()`
   Expects the Jwt cookie and bad Ltpa cookie to be found in the reponse, and reach the protected resource to verify the Jwt cookie was used for authentication and the Ltpa was not.

### Config Scenarios for test cases above
```
1. <jwtSso disableJwtCookie="true"  includeLtpaCookie="true" useLtpaIfJwtAbsent="true" setCookieSecureFlag="false"/>
2. <jwtSso disableJwtCookie="true"  includeLtpaCookie="true" useLtpaIfJwtAbsent="true" cookieName="AdamsJwtCookie" setCookieSecureFlag="false"/>
3. <jwtSso disableJwtCookie="true"  includeLtpaCookie="true" useLtpaIfJwtAbsent="false" setCookieSecureFlag="false"/>
4. <jwtSso disableJwtCookie="true"  includeLtpaCookie="false" setCookieSecureFlag="false"/>
5. <jwtSso disableJwtCookie="false" includeLtpaCookie="true" useLtpaIfJwtAbsent="true" setCookieSecureFlag="false"/>
6. <jwtSso disableJwtCookie="false" includeLtpaCookie="false" setCookieSecureFlag="false"/>
7. <jwtSso disableJwtCookie="false" includeLtpaCookie="false" setCookieSecureFlag="false"/>
```

**Comment by Zech-Hein** [comment]
**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios. While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

**Comment by dave-waddling** [comment]
Hi,

Thanks for completing the Feature Test Summary. From a review standpoint all is looking good, however `com.ibm.ws.security.authentication.tai.fat.FATTest.testTAI_disableLtpaCookie_false` failed in the last two SOEs and defect 275383 has been opened for it. 

In both cases it only failed on a single platform, Windows 2012R2 OpenJDK 11 (Hotspot), so I am not overly concerned but would prefer it to be triaged before granting a FAT Focal Approval.

**Comment by Zech-Hein** [comment]
I updated 275383, we delivered a fix yesterday that should fix the failure from that defect in [CL PR 21334](https://github.ibm.com/was-liberty/WS-CD-Open/pull/21334)

**Comment by dave-waddling** [comment]
Hi Zech,

Many thanks, given that it was a very infrequent test bug, and that the Security FA's defect backlog are now in a healthier state I'll add the FAT Focal Approval to the parent epic now.
