### ISSUE TITLE
Can't install adminCenter-1.0 via featureUtility on 20.0.0.6

### ISSUE THREAD

**Issue by ggam** [OpenLiberty/open-liberty#12519]
**Describe the bug**
I tried to install adminCenter following instructions from the 20.0.0.6 release blog post (https://openliberty.io/blog/2020/06/05/graphql-open-liberty-20006.html#MVN) but it doesn't work. It complains about `com.ibm.websphere.appserver.features:wlp-base-license:20.0.0.6` artifact, which seems to be missing on Maven Central: https://search.maven.org/search?q=g:com.ibm.websphere.appserver.features%20AND%20a:wlp-base-license

Example result:
```
[guillermo@localhost bin]$ ./featureUtility installFeature adminCenter-1.0
Inicializando...
Resolviendo características remotas. Este proceso puede tardar varios minutos en completarse.
CWWKF1406E: No se puede descomprimir el paquete de licencia con la coordenada Maven com.ibm.websphere.appserver.features:wlp-base-license:20.0.0.6 del repositorio en la vía de acceso de archivo /home/guillermo/.m2/repository.
```

I cant install features that don't require license acceptance.

**Steps to Reproduce**
`./featureUtility installFeature adminCenter-1.0 --acceptLicense

**Expected behavior**
adminCenter feature should be installed

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.6
 - Java Version: 14

**Comment by TayyabDev** [comment]
Issue is now fixed. The missing artifacts were pushed to maven central recently so it should work now

![image](https://user-images.githubusercontent.com/19651696/84176219-10d8bf80-aa4f-11ea-9df2-fa1da4d021a1.png)

**Comment by ggam** [comment]
Great, thanks!
