### ISSUE TITLE
OpenAPI explorer UI not producing correct sample value for field

### ISSUE THREAD

**Issue by nadiramra** [OpenLiberty/open-liberty#12581]
When using openapi-3.1, there is a resource method that is defined as follows:

```java
  @javax.ws.rs.POST
  @javax.ws.rs.Consumes({"application/xml", "application/json"})
  @javax.ws.rs.Produces({"application/xml", "application/json"})

public Response tsdate( @javax.ws.rs.core.Context HttpServletRequest req, TSDateFields bufferin)
```

where the class TSDateFields is defined as:

```java
@javax.xml.bind.annotation.XmlRootElement(name ="TSDateFields")
@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
@javax.xml.bind.annotation.XmlType(propOrder={"date_", "timestamp_"})

public class TSDateFields
{
    @javax.xml.bind.annotation.XmlElement(name="date_")
    @javax.xml.bind.annotation.XmlSchemaType(name="date")
    private String date_ = null;

    @javax.xml.bind.annotation.XmlElement(name="timestamp_")
    @javax.xml.bind.annotation.XmlSchemaType(name="dateTime")
    private String timestamp_ = null;

    public TSDateFields() {   super();  }

    public void setdate_(String value)  {  this.date_ = value;  }
    public String getdate_()  {    return date_;   }
    public void settimestamp_(String value)   { this.timestamp_ = value; }

    public String gettimestamp_() {return timestamp_; }
}
```

The  OpenAPI  explorer would produce  the following sample values  for XML:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<TSDateFields>
	<date_>string</date_>
	<timestamp_>string</timestamp_>
</TSDateFields>
```

and for JSON it would produce the following:

```json
{
  "getdate_": "string",
  "gettimestamp_": "string"
}
```

The values are not taking into consideration the schema type of the field in order to produce a logical sample value.  

When using apiDiscovery-1.0 feature, it produces the following  for XML:
```xml
<?xml version="1.0"?>
<TSDateFields>
  <date_>1970-01-01</date_>
  <timestamp_>1970-01-01T00:00:00.001Z</timestamp_>
</TSDateFields>
```

And for JSON it produces the following:
```
{
  "date_": "2020-06-11",
  "timestamp_": "2020-06-11T17:14:30.105Z"
}
```

Currently running IBM Liberty 20.0.0.5 with JRE 8.

**Comment by Azquelt** [comment]
The `openapi-3.1` feature is based on MicroProfile Open Api, which is slightly different from the older `openapi-3.0` and `apiDiscovery-1.0` features.

To get the desired behaviour in this case, you need to add [`@Schema(format = "date")`][schema-jd] or [`@Schema(format = "date-time")`][schema-jd] to the field. The formats which can be used here are the ones listed in the [OpenAPI v3 spec][formats].

Also, if your properties use a more specific type than `String`, e.g. `java.time.Instant` or `java.time.LocalTime`, `mpOpenApi-2.0` should add the correct format automatically.

[formats]: https://swagger.io/specification/#data-types
[schema-jd]: https://download.eclipse.org/microprofile/microprofile-open-api-2.0/apidocs/org/eclipse/microprofile/openapi/annotations/media/Schema.html#format--
