### ISSUE TITLE
server.bat script does not read path of jvm.options correctly as documented

### ISSUE THREAD

**Issue by Eng-Fouad** [OpenLiberty/open-liberty#12606]
According to the [documentation](https://openliberty.io/docs/ref/config/), `jvm.options` is read first from `${wlp.user.dir}/shared/jvm.options`. However, It is currently read from `${WLP_INSTALL_DIR}/usr/shared/jvm.options`:

https://github.com/OpenLiberty/open-liberty/blob/bf9b94dde3344d4ea11df0fddc595dd99a394e42/dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server#L657

https://github.com/OpenLiberty/open-liberty/blob/bf9b94dde3344d4ea11df0fddc595dd99a394e42/dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server.bat#L571

The problem is that when we use custom `${wlp.user.dir}`, the `server` script does not read `jvm.options` from the shared directory.

**Comment by Eng-Fouad** [comment]
Hi @scottkurz, any updates regarding this issue?

**Comment by hlhoots** [comment]
Should be fixed now.  Closing.
