### ISSUE TITLE
Document the allowQueryParamWithNoEqual property

### ISSUE THREAD

**Issue by Thihup** [OpenLiberty/open-liberty#12604]
**Is your feature request related to a problem? Please describe.**
I was trying enable the property "com.ibm.ws.webcontainer.AllowQueryParamWithNoEqual" documented [here](https://www.ibm.com/support/knowledgecenter/da/SS7K4U_9.0.5/com.ibm.websphere.zseries.doc/ae/rweb_custom_props.html#d1648698e1756), without success. However, when I tried
```xml
<webContainer allowQueryParamWithNoEqual="true"/>
```
It worked, but this property is not in the docs.

**Describe the solution you'd like**
Add this property to https://openliberty.io/docs/ref/config/webContainer.html

**Describe alternatives you've considered**
I don't know if this is a deprecated feature. The alternative would be to change my code.

**Comment by Thihup** [comment]
Any updates?

**Comment by pnicolucci** [comment]
Sorry for the delay, I'll start taking a look at this soon!

**Comment by wtlucy** [comment]
@Thihup this property is not going to be deprecated, so I'll start the process for getting this prop added to the OpenLiberty docs in #15233.  There are a handful of other OpenLiberty WebContainer properties which aren't documented either - I've opened an issue to work through those at #15232

**Comment by wtlucy** [comment]
I've merged #15233, so this `AllowQueryParamWithNoEqual` will be documented for the `21.0.0.1` release.

**Comment by Thihup** [comment]
Thanks a lot!
