### ISSUE TITLE
Investigate jakarta.servlet.jsp.resources for JSP-3.0

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#12637]
These xsd files are pull in from the following IBM dependency. 
```
<dependency>
    <groupId>com.ibm.ws.javax.j2ee</groupId>
    <artifactId>servlet.jsp.resources</artifactId>
    <version>2.3</version>
</dependency>
```

The following files are contained in the jar: 

<img width="396" alt="image" src="https://user-images.githubusercontent.com/5934310/84813608-341ae600-afde-11ea-8d68-2ce681e57c59.png">

A custom 3.0 servlet.jsp.resources jar may also need to be created. 

These dtd/xsd files are used in the following place: 
https://github.com/OpenLiberty/open-liberty/blob/552601852736baa8a85521616aeb9bcddf037a55/dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/taglib/TldParser.java#L62-L84

**Comment by pnicolucci** [comment]
@volosied  see  thread here regarding this: https://www.eclipse.org/lists/jsp-dev/msg00093.html we may want to revisit what we bundle as we might have overlap with the servlet api jar

**Comment by volosied** [comment]
https://github.com/apache/tomcat/tree/master/java/jakarta/servlet/resources

Looks like some of these 3.0 xsd & dtd files are available.

I'll look to see if they are included in the releases so we can pull them into the ibm jars directly without any transformations

**Comment by pnicolucci** [comment]
In addition we have some overlays in the servlet 5.0 api jar. We need to see if these are in the jakarta servlet 5.0 api jar and if so are they the same? If some are missing we need to see why and where we might have gotten them from historically. Did the servlet 4.0 api jar contain them?

**Comment by volosied** [comment]
From my investigation, I don't see any use of various xsd files within the TldParser.

The only two used were TAGLIB_DTD_PUBLIC_ID_11 and TAGLIB_DTD_PUBLIC_ID_12. 

Those two taglibs were used for 

- /webcontainer/com/ibm/ws/jsp/jsx/tags/jsxFunction.tld
- /webcontainer/com/ibm/ws/jsp/tsx/tag/tsx.tld

Additionally I ran a personal build where only the TAGLIB_DTD_PUBLIC_ID_11 and TAGLIB_DTD_PUBLIC_ID_12 paths were resolved.  No failure or  errors occurred.

**Comment by volosied** [comment]
Will re-look at this next to see if there are any actionable items.

**Comment by volosied** [comment]
With #15938 now merged, this can now be closed.
