### ISSUE TITLE
Review default of deferServletRequestListenerDestroyOnError for Servlet 5

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#12633]
See https://github.com/OpenLiberty/open-liberty/issues/9929#issuecomment-644736561

**Comment by pmd1nh** [comment]
https://github.com/OpenLiberty/open-liberty/pull/13430

**Comment by volosied** [comment]
Thank you for working on this, @pmd1nh!

**Comment by pnicolucci** [comment]
This is going to be done standalone outside of #13430 as we need to determine how best to test this.

**Comment by volosied** [comment]
@pnicolucci  I can test this functionality using the app provided in the original issue (made by the outside contributor)

**Comment by volosied** [comment]
I tried to create a minimal, reproducible example using the app provided. 
Unfortunately, it's didn't work as intended. 

servlet 4.0 

- setting deferServletRequestListenerDestroyOnError to true prompted the error page instead of just displaying the exception in the page.

servlet 5.0
- jakarta.servlet.ServletException displayed on the page regardless of whether deferServletRequestListenerDestroyOnError was true or false. 

[deferServletRequestListenerDestroyOnError-testing.zip](https://github.com/OpenLiberty/open-liberty/files/5549530/deferServletRequestListenerDestroyOnError-testing.zip)
