### ISSUE TITLE
How should HTTP/2 be enabled/disabled/configured/defaulted.

### ISSUE THREAD

**Issue by billw1024** [OpenLiberty/open-liberty#1264]
HTTP/2 needs to be configured for default out of the box settings, and then how to override those settings. I think the simpliest way to do that, following how other servers appear to be configured is to have HTTP/2 off by default, and then have it as a configuration parameter on the http endpoints. Here is what other servers do, and what I am proposing:

1.Undertow/JBOSS/Wildfly HTTP2 configuration
 Add a HTTPS connector
 /subsystem=undertow/server=default-server/https-listener=https:add(socket-binding=https, security-realm=https, enable-http2=true)

2.NGINX:
 Add the http2 parameter to all listen directives.
 server {
 listen 443 ssl http2 default_server;
 ssl_certificate server.crt;
 ssl_certificate_key server.key;
 ...
 }

3 Apache:
 add to your server configuration is: Protocols h2 http/1.1
 <VirtualHost ...>
 ServerName test.example.org
 Protocols h2 http/1.1

4.WebSphere Liberty
H2 Secure:
```xml
<httpEndpoint
             httpPort="9080"
             httpsPort="9043"
             id="defaultHttpEndpoint">
       <sslOptions  alpnProtocols="h2" />
<httpEndpoint>
```

H2 Unsecure:
```xml
<httpEndpoint
              httpPort="9080"
              httpsPort="9043"
              id="defaultHttpEndpoint">
          <httpOptions http2="enabled" />
<httpEndpoint/>
```

**Comment by tevans78** [comment]
@billw1024 the title of this issue isn't very clear?!

**Comment by NottyCode** [comment]
It has been decided that servlet 4 must support http2 out of the box. There is no need to support disabling http2 support for servlet 4. For servlet 3.x we need a way to turn http2 on. The alpnProtocol on sslOptions is reasonable for support over https, but the httpOptions http2 might imply both configuration was required, or that setting http2=enabled would be sufficient for turning it on for https (which isn't proposed). More discussion is going on here.

**Comment by billw1024** [comment]
so the for the unsecure option, our best idea so far is that  the option parameter be called "unsecureUpgradeProtocol",  and that it can have a value of "h2c" or "http2".  where both values mean the same thing.   the reason for two values is that "h2c" is the actual header value that is specified in the spec for unsecure http2 upgrade,  and "http2" is the more understandable way.  But I'm fine with choosing one or the other or both.  so this: 

<httpOptions unsecureUpgradeProtocol="h2c" />
or
<httpOptions unsecureUpgradeProtocol="http2" />

or both are allowed and do the same thing.

**Comment by billw1024** [comment]
The design of this was modified slightly from the above, but the same spirit of the solution was kept.
