### ISSUE TITLE
Feature-Request: Add old javaee6 feature (JPA 2.0)

### ISSUE THREAD

**Issue by JuergenSu** [OpenLiberty/open-liberty#12649]
**Is your feature request related to a problem? Please describe.**
We are currently trying to port older applications to a cloud platform based open source software and therfor investing in porting javaee6 applications to openliberty as a first step in modernizing this applications. We succeded in upgrading all the javaee6 components to the corresponding javaee7 versions, but failed with jPA the introduced behaviour change from JPA 2.0 aka openJPA to JPA 2.1 aka eclipselink causes a lot of work to be done or even the whole application to be rewritten. for this migration path it would be good to support JPA2.0 (openJPA) as well..

**Describe the solution you'd like**
the usage of <feature>JPA-2.0</feature> should be possible

**Describe alternatives you've considered**
there is no really alternative, it simply creates a huge first step on the jurney to the cloud for legacy applications, which sometimes means the first step "rehost" is impossible and we have to immediately go to the last Step "refactor".

Whats your opinion in supporting JPA2.0 in openLiberty ?

**Comment by jgrassel** [comment]
Hello, @JuergenSu.  JPA 2.0 is an old technology which has been stabilized.  It (the `jpa-2.0` feature) is available in the commercial version of Liberty, but it will not be migrated to Open Liberty.
