### ISSUE TITLE
GA BLOG 20.0.0.8 HTTP access log fields in JSON logs

### ISSUE THREAD

**Issue by jennifer-c** [OpenLiberty/open-liberty#12685]
**a) Which Liberty feature does it relate to?**
i) Human-readable name
`JSON Logging`
ii) Feature name
`logging` is part of the Liberty kernel.
iii) Is this a new feature or is it an update to an existing feature for this release?
This is an update to the existing logging configuration
iv) Provide the qualified name of all changed feature deliveries to this release?
N/A

**b) Who is the target audience?**
Any developers, administrators and liberty users using logging in JSON format.

**c) What does this feature provide in general? Write a sentence or two that introduces it to someone new to the concept.**
In Liberty, users have the option to format their server logs in basic or JSON format. When logs are in JSON format, users have to specify the sources (message, trace, accessLog, ffdc, audit) they want to send to messages.log or console.log/standard-out.

**d) What is new/changed in this release?**
This feature adds an option for users to include fields from the `accessLogging logFormat` attribute in their JSON logs. Previously, only select fields would be printed in JSON logs. Users are now able to include other NCSA access log fields in their JSON logs.

**e) Why should they get excited about this new thing (2-3 sentences)? Explain how this new feature literally makes their life easier? Why should they care? What was the problem before and how does this solve it for them?**
Users are now able to define which JSON access log fields they want from their accessLogging logFormat property, which can then be sent to a log analysis tool, such as the ELK (Elasticsearch, Logstash, Kibana) stack. With this new feature, users can receive more informative logs that suit their needs. For example, the user is able to specify that they want the user ID and request time fields in their JSON access logs -- then, they can filter by user ID in Kibana and track performance on a user-by-user basis.

**f. Explain how to make it work.**
When logs are in JSON format, you can use the new `jsonAccessLogFields` logging attribute to specify whether you want your access logs to have the default set of fields or a custom set of fields based on the HTTP accessLogging logFormat attribute. In order to receive access logs, the property `accessLogging` or `httpAccessLogging` must be set. For example, in your server.xml, set the following attributes:
```
    <httpEndpoint id="defaultHttpEndpoint" httpPort="9080" httpsPort="9443" host="*">
        <accessLogging logFormat='%R{W} %u %{my_cookie}C %s'/>
    </httpEndpoint>

    <logging messageFormat="json" messageSource="message,accessLog" jsonAccessLogFields="logFormat"/>
```
Now, in the `messages.log` file, your access logs will contain the four fields specified in the `accessLogging logFormat` attribute (elapsed time, user ID, cookie, and response code).
```
{
  "type": "liberty_accesslog",
  "host": "192.168.1.15",
  "ibm_userDir": "/Users/jennifer.zhen.chengibm.com/libertyGit/open-liberty/dev/build.image/wlp/usr/",
  "ibm_serverName": "defaultServer",
  "ibm_cookie_my_cookie": "example_cookie",
  "ibm_responseCode": 200,
  "ibm_datetime": "2020-06-18T09:30:47.693-0400",
  "ibm_sequence": "1592487047653_0000000000001"
}
```

This new functionality is also available for the `logstashCollector-1.0` feature by adding the following to your server.xml:
```
    <featureManager>
        <feature>logstashCollector-1.0</feature>
    </featureManager>

    <logstashCollector 
        jsonAccessLogFields="logFormat">
    </logstashCollector>
```

g) Provide links to any docs in the externally available Knowledge Center. If you don't know the URL, ask your ID person to predict it.
https://openliberty.io/docs/ref/config/#logging.html
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_logging.html

h) If relevant, provide links to external articles etc about this technology.
N/A
i) Is this feature part of Open Liberty or is it WebSphere Liberty-only?
This feature is part of Open Liberty.

j) Attach any images to this work item as .png files.
N/A

**Comment by jennifer-c** [comment]
@donbourne @Yushan-Lin Please review. Feel free to make any grammatical edits directly to the main body of the issue.

**Comment by donbourne** [comment]
Looks good!

**Comment by Yushan-Lin** [comment]
https://openliberty.io/blog/2020/07/30/json-logging-open-liberty-20008.html
