### ISSUE TITLE
GA BLOG 20.0.0.8: Allow JSON written to System.out to pass without wrapping

### ISSUE THREAD

**Issue by Yushan-Lin** [OpenLiberty/open-liberty#12688]
**a) Which Liberty feature does it relate to?**
i) Human-readable name
`JSON Logging`
ii) Feature name
logging is part of the Liberty kernel.
iii) Is this a new feature or is it an update to an existing feature for this release?
This is an update to the existing logging configuration
iv) Provide the qualified name of all changed feature deliveries to this release?
N/A

**b) Who is the target audience?**
Any developers, administrators and liberty users using logging in JSON format.

**c) What does this feature provide in general? Write a sentence or two that introduces it to someone new to the concept.**
In Liberty, users have the option to format their server logs in basic or JSON format. When logs are in JSON format, users have to specify the sources (message, trace, accessLog, ffdc, audit) they want to send to messages.log or console.log/standard-out.

**d) What is new/changed in this release?**
This feature adds a new option for users to write pre-formatted JSON application logs directly to System.out/System.err. Previously, when Liberty is running with JSON logging enabled, Liberty embeds anything written to System.out/System.err into the message field of a `liberty_message `event. Now, users can write JSON directly to System.out/err without wrapping in the `liberty_message` event.

**e) Why should they get excited about this new thing (2-3 sentences)? Explain how this new feature literally makes their life easier? Why should they care? What was the problem before and how does this solve it for them?**
Users can now write their JSON application logs directly to System.out/System.err, which can then be sent to a log analysis tool, such as the ELK (Elasticsearch, Logstash, Kibana) stack. Previously, when JSON logging is enabled, pre-formatted JSON application logs would look like this:
```
{
     "type":"liberty_message",
     "host":"192.168.0.119",
     "ibm_userDir":"\/Users\/yushan.lin@ibm.com\/Documents\/archived-guide-log4j\/finish\/target\/liberty\/wlp\/usr\/",
     "ibm_serverName":"log4j.sampleServer",
     "message":"{\n   \"timeMillis\" : 1587666082123,\n  
             \"thread\" : \"Default Executor-thread-8\",\n  
             \"level\" : \"WARN\",\n  
              \"loggerName\" : \"application.servlet.LibertyServlet\",\n  
              \"message\" : \"hello liberty servlet warning message!\",\n  
              \"endOfBatch\" : false,\n  
              \"loggerFqcn\" : \"org.apache.logging.log4j.spi.AbstractLogger\",\n  
              \"threadId\" : 53,\n  
              \"threadPriority\" : 5\n}\r",
     "ibm_threadId":"00000035",
     "ibm_datetime":"2020-04-23T14:21:22.124-0400",
     "module":"SystemOut",
     "loglevel":"SystemOut",
     "ibm_methodName":"",
     "ibm_className":"", 
     "ibm_sequence":"1587666082124_000000000001B",
     "ext_thread":"Default Executor-thread-8”
}
```
Now users can output their logs so that pre-formatted JSON logs are not wrapped in `liberty_message` events. Visualization tools such as Kibana can be used to analyze certain fields in your JSON logs. Users can analyze both their custom-formatted JSON application logs and Liberty JSON logs in the same visualization.

**f. Explain how to make it work.**
Users can enable this functionality at any time by setting `appsWriteJson="true"` in the logging element of the server.xml , or can have it set from the moment the server starts by setting in bootstrap.properties:
`com.ibm.ws.logging.apps.write.json=true`

**f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.**
https://openliberty.io/docs/ref/config/#logging.html
**g. Attach any images to this work item as .png files.**
N/A

**Comment by donbourne** [comment]
```
"Users can analyze both their JSON application logs and Liberty JSON logs in the same visualization."
- seems out of context.  you may need a sentence or two to introduce the idea of visualizations

" the new appsWriteJson attribute to true in the server.xml. "
->
" the new appsWriteJson attribute to true in the logging element of the server.xml. "


"To enable the functionality, add the following to bootstrap.properties:"
- need to make this flow better from previous paragraph about server.xml.  eg. you could say that people can enable this at any time by setting the thing in server.xml , or can have it set from moment the server starts by setting in in bootstrap.properties.

```

**Comment by donbourne** [comment]
maybe change...
```
Users can analyze both their JSON application logs
```
to
```
Users can analyze both their custom-formatted JSON application logs
```
(to avoid confusion with logs people have always sent to JUL and output into Liberty's JSON logs)

**Comment by donbourne** [comment]
updates look good!

**Comment by Yushan-Lin** [comment]
https://openliberty.io/blog/2020/07/30/json-logging-open-liberty-20008.html
