### ISSUE TITLE
Re-balance the FaultTolerance FAT buckets

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#12683]
We would like FAT buckets to execute in 5 minutes or less in LITE mode. For example, on average;

com.ibm.ws.microprofile.faulttolerance.cdi_fat	        00:24:45
com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck	00:17:26
com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck	00:15:49
com.ibm.ws.microprofile.faulttolerance.1.1_fat_tck	00:13:33
com.ibm.ws.microprofile.faulttolerance_fat_tck	00:07:01

These buckets should be rebalanced to run more tests in FULL mode or to split them across multiple buckets.

**Comment by Azquelt** [comment]
This work is done. For the FAT tests it was less of a rebalance and more of a refactoring to speed up executions.

FAT tests: ~25 minutes -> 3 minutes
2.1 TCK: ~17 minutes -> 9 minutes (other TCK projects saw comparable runtime reductions)
