### ISSUE TITLE
uniqueSecurityName is null when the realm contains a parenthesis. 

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/open-liberty#12681]
**Describe the bug**
There's logic issue when realm security name is being split. 

If there is a stack trace, please include the FULL stack trace (without any `[internal classes]` lines in it). To find the full stack trace, you may need to check in `$WLP_OUTPUT_DIR/messages.log`

**Steps to Reproduce**
Steps to reproduce the bug

**Expected behavior**

**Diagnostic information:**
 - OpenLiberty Version: [e.g. 19.0.0.8]
 - Java Version: [i.e. full output of `java -version`]
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**

**Comment by utle** [comment]
Fixed by https://github.com/OpenLiberty/open-liberty/pull/12755

**Comment by una-tapa** [comment]
Thanks, Ut!
