### ISSUE TITLE
BETA BLOG 20007: grpc-1.0 and grpcClient-1.0

### ISSUE THREAD

**Issue by wtlucy** [OpenLiberty/open-liberty#12696]
Development progress update

a. Which Liberty feature does it relate to?

   i. Human-readable name (eg WebSockets feature): 

> gRPC and gRPC Client

   ii. Feature name (eg websockets-1.0): 

> grpc-1.0 and grpcClient-1.0

   iii. Is this a new feature or is it an update to an existing feature for this release? 

> new feature

   iv. Provide the fully qualified name of all public features ( as '*.esa' filenames) that are delivered as part of this work

> io.openliberty.grpc-1.0.esa
> io.openliberty.grpcClient-1.0.esa

b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc: 

> Application Developers

c. Write a sentence or two that introduces it to someone new to the general technology/concept.

> gRPC is a “high-performance, open source universal RPC framework”.  gRPC support on Liberty allows developers to both provide and consume gRPC services from their web applications.  
 
d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?) 

> With the introduction of gRPC support in OpenLiberty, developers can take advantage of the benefits of gRPC more easily than before.  Those benefits include great performance, simple service definitions via Protocol Buffers, cross-platform and language support, and wide industry adoption.  
 
e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.

> Two new features are available: `grpc-1.0`, which enables gRPC services, and `grpcClient-1.0`, which enables the use of a gRPC client for outbound calls.

> Example of the most simplistic server.xml snippet that enables both new features:

```
    <featureManager>
        <feature>grpc-1.0</feature>
        <feature>grpcClient-1.0</feature>
    </featureManager>

```

> The `grpc-1.0` feature works by scanning web apps for gRPC service implementations - that is, implementors of `io.grpc.BindableService`.  The webapp must include the protocol buffer compiler generated code for the services it intends to provide, and additionally the service class must provide a no-argument constructor.   The webapp does not need to include any core gRPC libraries; those are provided by the Liberty runtime.  Once a gRPC service is scanned and started, it becomes accessible to remote gRPC clients on the configured HTTP ports.

> The `grpcClient-1.0` feature provides applications with access to a Netty gRPC client, as well as the related libraries.  A webapp must provide a client implementation and stubs, and can make outbound calls with a `io.grpc.ManagedChannel` without needing to provide the supporting client libraries.

> As an example, a basic helloworld service can be defined via `grpc-1.0` with:

```
package com.ibm.ws.grpc;

import com.ibm.ws.grpc.beans.GreetingBean;

import io.grpc.examples.helloworld.GreeterGrpc;
import io.grpc.examples.helloworld.HelloReply;
import io.grpc.examples.helloworld.HelloRequest;
import io.grpc.stub.StreamObserver;

public class HelloWorldService extends GreeterGrpc.GreeterImplBase {

    public HelloWorldService(){}

    @Override
    public void sayHello(HelloRequest req, StreamObserver<HelloReply> responseObserver) {
        HelloReply reply = HelloReply.newBuilder().setMessage("Hello " + req.getName()).build();
        responseObserver.onNext(reply);
        responseObserver.onCompleted();
    }
}
```
> For this example, the application must provide the [helloworld service definition](https://github.com/grpc/grpc-java/blob/master/examples/src/main/proto/helloworld.proto) along with the protobuf compiler output.  No additional libraries need to be provided with the application, and once it's started the helloworld Greeter service will be accessible on the server's HTTP endpoints.

> For a client example, a basic Servlet using gRPC can be defined via `grpcClient-1.0` with:

```
package com.ibm.ws.grpc;

import io.grpc.examples.helloworld.GreeterGrpc;
import io.grpc.examples.helloworld.HelloReply;
import io.grpc.examples.helloworld.HelloRequest;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
...

@WebServlet(name = "grpcClient", urlPatterns = { "/grpcClient" }, loadOnStartup = 1)
public class GrpcClientServlet extends HttpServlet {

    ManagedChannel channel;
    private GreeterGrpc.GreeterBlockingStub greetingService;

    private void startService(String address, int port) {
        channel = ManagedChannelBuilder.forAddress(address , port).usePlaintext().build();
        greetingService = GreeterGrpc.newBlockingStub(channel);
    }

    private void stopService() {
        channel.shutdownNow();
    }

    @Override
    protected void doGet(HttpServletRequest reqest, HttpServletResponse response) 
            throws ServletException, IOException {

        // set user, address, port params
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) 
            throws ServletException, IOException {

        // grab user, address, port params
        startService(address, port);
        HelloRequest person = HelloRequest.newBuilder().setName(user).build();
        HelloReply greeting = greetingService.sayHello(person);

        // send the greeting in a response
        stopService();
    }	
}
}
```
> As with the service example, the application must provide the [helloworld service definition](https://github.com/grpc/grpc-java/blob/master/examples/src/main/proto/helloworld.proto) along with the protocol buffer compiler output.  All required gRPC client libraries are provided by `grpcClient-1.0`.
 
f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

> gRPC project page: https://grpc.io/
> gRPC Java basics: https://www.grpc.io/docs/languages/java/basics/
> gRPC Java repo: https://github.com/grpc/grpc-java

> The gRPC functionality was designed using the following Open Liberty Epic: https://github.com/OpenLiberty/open-liberty/issues/8637.  The design is outlined within the Epic for more detailed reading.

g. Attach any images to this work item as .png files.

**Comment by tomjenningss** [comment]
Hi @wtlucy please can you explain what “protof” or “protobuf” are? 
The Github page linked to is `helloworld.proto` but I can't seem to get an idea of what they are. 
Thanks

**Comment by wtlucy** [comment]
Hi @tomjenningss - `protof` is a typo, by `protobuf` I'm just abbreviating `protocol buffers`.  I'll update the text here for clarity.

**Comment by wtlucy** [comment]
This ended up getting published at https://openliberty.io/blog/2020/07/02/disable-default-cookies-20007.html#grpc
