### ISSUE TITLE
Only client and server scripts in bin are executable

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#127]
The Open Liberty zip doesn't set the execute bit for any of the scripts in the zip distribution.

**Comment by jgwest** [comment]
Confirmed, for instance 'openliberty-2017.9.0.0-201709201552.zip' is missing execute bit on, under /bin/:
```
binaryLog
ddlGen
pluginUtility
productInfo
securityUtility
serverSchemaGen
jaxb/xjc
jaxb/schemagen
jaxrs/wadl2java
jaxws/wsgen
jaxws/wsimport
```

**Comment by cbridgha** [comment]
Chris - can you take a look at fixing these up the same way you did for the gradle file?

**Comment by crpotter** [comment]
The issue ended up being that we weren't explicitly setting file permissions when we did the copy into the wlp/bin/ folder. There are fixes covered under Issues 199/201.
