### ISSUE TITLE
JAX-RS @Context injection into ContextResolver<Jsonb> failing with NPE

### ISSUE THREAD

**Issue by rslemos** [OpenLiberty/open-liberty#12715]
Some ways of injecting a `SecurityContext` into a `ContextResolver` instance results in an unusable reference (one that throws NPE for whichever method you call).

I could only reproduce this error in a scenario where the `SecurityContext` is used in the return path of a resource invocation (such as json-b or jackson transformations).

## Steps to reproduce

Here I'll delineate the steps to reproduce using json-b's feature `PropertyVisibilityStrategy`. The idea is to vet each json property based on `SecurityContext` (I'll post only the relevant sections).

### 0. Base case (incomplete, i.e., don't expect it to run)
```
<server>
  <featureManager>
    <feature>jaxrs-2.1</feature>
    <feature>jsonb-1.0</feature>
  </featureManager>
</server>
```

```
@ApplicationPath("/myapp")
public class MyApplication extends Application {
}
```

```
@Provider
public class MyContextResolver implements ContextResolver<Jsonb> {
  // somehow this securityContext must be injected
  private SecurityContext securityContext;

  public Jsonb getContext(Class<?> type) {
    JsonbConfig config = new JsonbConfig()
      .withPropertyVisibilityStrategy(new PropertyVisibilityStrategy() {
        public boolean isVisible(Field field) {
          return useSecurityContextToVetProperty();
        }

        public boolean isVisible(Method method) {
          return useSecurityContextToVetProperty();
        }

        private boolean useSecurityContextToVetProperty() {
          return true;
        }
      })
    ;

    return JsonbBuilder.newBuilder().withConfig(config).build();
  }
}
```

```
@Path("/myresource")
@Produces(MediaType.APPLICATION_JSON)
public class MyResource {

  @GET
  public MyData getMyData() {
    return new MyData();
  }

  public static class MyData {
    public int myField = 42;
  }
}
```

There are a couple of ways to inject the `SecurityContext`. I'll show two options, one that works and one that doesn't.

### 1. Directly injecting field `securityContext` (FAILURE)
```
public class MyContextResolver implements ContextResolver<Jsonb> {
  @Context
  private SecurityContext securityContext;
  ...
  public Jsonb getContext(Class<?> type) {
    ...
      new PropertyVisibilityStrategy() {
        ...
        private boolean useSecurityContextToVetProperty() {
          securityContext.isUserInRole("admin");
          return true;
        }
    ...
}
```

Though `securityContext` gets injected, its reference is unusable. Trying to use it throws NPE:
```
    [INFO] [err] java.lang.NullPointerException
    [INFO] [err]    at org.apache.cxf.jaxrs.impl.tl.ThreadLocalSecurityContext.isUserInRole(ThreadLocalSecurityContext.java:42)
    [INFO] [err]    at my.MyContextResolver$1.useSecurityContextToVetProperty(MyContextResolver.java:38)
    [INFO] [err]    at my.MyContextResolver$1.isVisible(MyContextResolver.java:27)
    [INFO] [err]    at org.eclipse.yasson.internal.model.PropertyValuePropagation.lambda$isFieldVisible$0(PropertyValuePropagation.java:121)
    [INFO] [err]    at org.eclipse.yasson.internal.model.PropertyValuePropagation.isVisible(PropertyValuePropagation.java:167)
    [INFO] [err]    at [internal classes]
    [INFO] [err]    at org.eclipse.yasson.internal.ClassParser.lambda$parseProperties$0(ClassParser.java:71)
    [INFO] [err]    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    [INFO] [err]    at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1628)
    [INFO] [err]    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
    [INFO] [err]    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
    [INFO] [err]    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    [INFO] [err]    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    [INFO] [err]    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
    [INFO] [err]    at org.eclipse.yasson.internal.ClassParser.parseProperties(ClassParser.java:72)
    [INFO] [err]    at org.eclipse.yasson.internal.MappingContext.lambda$createParseClassModelFunction$1(MappingContext.java:97)
    [INFO] [err]    at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
    [INFO] [err]    at org.eclipse.yasson.internal.MappingContext.getOrCreateClassModel(MappingContext.java:81)
    [INFO] [err]    at [internal classes]
    [INFO] [err]    at java.security.AccessController.doPrivileged(Native Method)
    [INFO] [err]    at org.apache.cxf.jaxrs.utils.JAXRSUtils.writeMessageBody(JAXRSUtils.java:1494)
    [INFO] [err]    at [internal classes]
    [INFO] [err]    at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
    [INFO] [err]    at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:96)
    [INFO] [err]    at [internal classes]
    [INFO] [err]    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    [INFO] [err]    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    [INFO] [err]    at java.lang.Thread.run(Thread.java:748)
```

(get the same error when injecting through constructor or setter)

### 2. Indirectly injecting via `Application` (SUCCESS)

```
public class MyApplication extends Application {
  @Context
  private SecurityContext securityContext;

  public Map<String, Object> getProperties() {
    return Collections.singletonMap("securityContext", securityContext);
  }
}
```

```
public class MyContextResolver implements ContextResolver<Jsonb> {
  @Context
  private Application application;
  ...
  public Jsonb getContext(Class<?> type) {
    ...
      new PropertyVisibilityStrategy() {
        ...
        private boolean useSecurityContextToVetProperty() {
          ((SecurityContext)application.getProperties().get("securityContext")).isUserInRole("admin");
          return true;
        }
    ...
}
```

Then it works. The `SecurityContext` (from application's properties) is also a `org.apache.cxf.jaxrs.impl.tl.ThreadLocalSecurityContext`. But this one works (its `isUserInRole` returns false).

## Expected behavior
Unless the spec forbids injection of `SecurityContext` inside `ContextResolver`, the reference should be usable (at least when serving a request).

If such usage is in fact forbidden by the spec, then indirectly injecting it through `Application` may invoke UB.

## Diagnostic information
 - OpenLiberty Version: 20.0.0.6
 - Java Version: 
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

**Comment by rslemos** [comment]
I've coded a more full report, injecting `SecurityContext` through many paths:

```
public class MyApplication extends Application {
  private SecurityContext securityContext1;
  @Context
  private SecurityContext securityContext2;
  private SecurityContext securityContext3 = null;

  // Resource classes with singleton scope can only have ServletConfig or ServletContext instances injected through their constructors
  // public MyApplication(@Context SecurityContext securityContext) {
  //   securityContext3 = securityContext;
  // }

  @Context
  public void setSecurityContext(SecurityContext securityContext) {
    securityContext1 = securityContext;
  }

  @Override
  public Map<String, Object> getProperties() {
    Map<String, Object> properties = new HashMap<>();
    properties.put("securityContext1", securityContext1);
    properties.put("securityContext2", securityContext2);
    // though I could put NULL into this HashMap, later on
    // it will be replicated into another Map, that abhors NULLs
    // (maybe another bug, if NULLs are not strictly forbidden by the specs)
    // properties.put("securityContext3", securityContext3);
    return properties;
  }
}
```

```
public class MyContextResolver implements ContextResolver<Jsonb> {
  private Application application1;
  @Context
  private Application application2;
  private Application application3 = null;

  private SecurityContext securityContext1;
  @Context
  private SecurityContext securityContext2;
  private SecurityContext securityContext3 = null;

  private SecurityContext securityContext1FromApplication1;
  @Context
  private SecurityContext securityContext2FromApplication1;
  private SecurityContext securityContext3FromApplication1 = null;

  private SecurityContext securityContext1FromApplication3;
  @Context
  private SecurityContext securityContext2FromApplication3;
  private SecurityContext securityContext3FromApplication3 = null;

  public MyContextResolver(@Context Application application, @Context SecurityContext securityContext) {
    securityContext3 = securityContext;
    // for late grabbing
    application3 = application;
    // early grabbing
    securityContext1FromApplication3 = (SecurityContext)application3.getProperties().get("securityContext1");
    securityContext2FromApplication3 = (SecurityContext)application3.getProperties().get("securityContext2");
    securityContext3FromApplication3 = (SecurityContext)application3.getProperties().get("securityContext3");
  }

  @Context
  public void setApplication(Application application) {
    // for late grabbing
    application1 = application;
    // early grabbing
    securityContext1FromApplication1 = (SecurityContext)application1.getProperties().get("securityContext1");
    securityContext2FromApplication1 = (SecurityContext)application1.getProperties().get("securityContext2");
    securityContext3FromApplication1 = (SecurityContext)application1.getProperties().get("securityContext3");
  }

  @Context
  public void setSecurityContext(SecurityContext securityContext) {
    securityContext1 = securityContext;
  }

  public Jsonb getContext(Class<?> type) {
    ...
      new PropertyVisibilityStrategy() {
        ...
        private boolean useSecurityContextToVetProperty() {
          System.out.println("=== REPORT ===");

          // known FAILURES (from bugreport's first alternative)
          report("securityContext1", securityContext1);
          report("securityContext2", securityContext2);
          report("securityContext3", securityContext3);

          // known SUCCESSES (from bugreport's second alternative)
          // 2 securityContexts for 3 applications
          // (with late grabbing; grabs reference only on point of usage)
          report("application1.securityContext1", (SecurityContext)application1.getProperties().get("securityContext1"));
          report("application1.securityContext2", (SecurityContext)application1.getProperties().get("securityContext2"));
          report("application2.securityContext1", (SecurityContext)application2.getProperties().get("securityContext1"));
          report("application2.securityContext2", (SecurityContext)application2.getProperties().get("securityContext2"));
          report("application3.securityContext1", (SecurityContext)application3.getProperties().get("securityContext1"));
          report("application3.securityContext2", (SecurityContext)application3.getProperties().get("securityContext2"));

          // SUCCESSES
          // securityContext from applications
          // (with early grabbing; grabs reference right when application gets injected)
          report("securityContext1FromApplication1", securityContext1FromApplication1);
          report("securityContext1FromApplication3", securityContext1FromApplication3);
          report("securityContext2FromApplication3", securityContext2FromApplication3);

          // FAILURE
          // securityContext from application
          // (with early grabbing; grabs reference right when application gets injected)
          report("securityContext2FromApplication1", securityContext2FromApplication1);

          // expected failures, because applications' securityContext3 never gets injected
          report("application1.securityContext3", (SecurityContext)application1.getProperties().get("securityContext3"));
          report("application2.securityContext3", (SecurityContext)application2.getProperties().get("securityContext3"));
          report("application3.securityContext3", (SecurityContext)application3.getProperties().get("securityContext3"));
          report("securityContext3FromApplication1", securityContext3FromApplication1);
          report("securityContext3FromApplication3", securityContext3FromApplication3);

          System.out.println("=== END OF REPORT ===");
          return true;
        }

        private void report(String description, SecurityContext securityContext) {
          StringBuilder output = new StringBuilder();

          output.append(description).append("\t");
          output.append(String.valueOf(securityContext)).append("\t");
          try {
            System.out.println("Using securityContext: " + securityContext);
            System.out.println("isUserInRole(admin): " + securityContext.isUserInRole("admin"));
            return true;
            securityContext.isUserInRole("admin");
            output.append("SUCCESS");
          } catch (RuntimeException e) {
            e.printStackTrace();
            throw e;
            output.append("FAILURE: ").append(e.getClass().getSimpleName()).append(" at ").append(e.getStackTrace()[0]);
          }
          System.out.println(output.toString());
        }
      })
    ;
    ...
  }
}
```

## Results
| scenario | securityContext | outcome |
| --- | --- | --- |
| securityContext1 | org.apache.cxf.jaxrs.impl.tl.ThreadLocalSecurityContext@20a860 | FAILURE: NullPointerException at org.apache.cxf.jaxrs.impl.tl.ThreadLocalSecurityContext.isUserInRole(ThreadLocalSecurityContext.java:42) |
| securityContext2 | org.apache.cxf.jaxrs.impl.tl.ThreadLocalSecurityContext@ce4df8d | FAILURE: NullPointerException at org.apache.cxf.jaxrs.impl.tl.ThreadLocalSecurityContext.isUserInRole(ThreadLocalSecurityContext.java:42) |
| securityContext3 | org.apache.cxf.jaxrs.impl.tl.ThreadLocalSecurityContext@230b22f6 | FAILURE: NullPointerException at org.apache.cxf.jaxrs.impl.tl.ThreadLocalSecurityContext.isUserInRole(ThreadLocalSecurityContext.java:42) |
| application1.securityContext1 | org.apache.cxf.jaxrs.impl.tl.ThreadLocalSecurityContext@20bd1037 | SUCCESS |
| application1.securityContext2 | org.apache.cxf.jaxrs.impl.tl.ThreadLocalSecurityContext@255bcfe8 | SUCCESS |
| application2.securityContext1 | org.apache.cxf.jaxrs.impl.tl.ThreadLocalSecurityContext@20bd1037 | SUCCESS |
| application2.securityContext2 | org.apache.cxf.jaxrs.impl.tl.ThreadLocalSecurityContext@255bcfe8 | SUCCESS |
| application3.securityContext1 | org.apache.cxf.jaxrs.impl.tl.ThreadLocalSecurityContext@20bd1037 | SUCCESS |
| application3.securityContext2 | org.apache.cxf.jaxrs.impl.tl.ThreadLocalSecurityContext@255bcfe8 | SUCCESS |
| securityContext1FromApplication1 | org.apache.cxf.jaxrs.impl.tl.ThreadLocalSecurityContext@20bd1037 | SUCCESS |
| securityContext1FromApplication3 | org.apache.cxf.jaxrs.impl.tl.ThreadLocalSecurityContext@20bd1037 | SUCCESS |
| securityContext2FromApplication3 | org.apache.cxf.jaxrs.impl.tl.ThreadLocalSecurityContext@255bcfe8 | SUCCESS |
| securityContext2FromApplication1 | org.apache.cxf.jaxrs.impl.tl.ThreadLocalSecurityContext@f696479 | FAILURE: NullPointerException at org.apache.cxf.jaxrs.impl.tl.ThreadLocalSecurityContext.isUserInRole(ThreadLocalSecurityContext.java:42) |
| application1.securityContext3 | null | FAILURE: NullPointerException at my.MyContextResolver$1.report(MyContextResolver.java:121) |
| application2.securityContext3 | null | FAILURE: NullPointerException at my.MyContextResolver$1.report(MyContextResolver.java:121) |
| application3.securityContext3 | null | FAILURE: NullPointerException at my.MyContextResolver$1.report(MyContextResolver.java:121) |
| securityContext3FromApplication1 | null | FAILURE: NullPointerException at my.MyContextResolver$1.report(MyContextResolver.java:121) |
| securityContext3FromApplication3 | null | FAILURE: NullPointerException at my.MyContextResolver$1.report(MyContextResolver.java:121) |

**Comment by andymc12** [comment]
Thanks for the thorough testing!  Here is my reproducer app that shows the failure where the NPE comes from `org.apache.cxf.jaxrs.impl.tl.ThreadLocalSecurityContext`:
https://github.com/andymc12/secureJson

**Comment by rslemos** [comment]
And here is mine: https://github.com/rslemos/open-liberty-12715

**Comment by rslemos** [comment]
Should I report it to Apache CXF?

**Comment by andymc12** [comment]
Open Liberty effectively forks CXF, so not every issue that you find in Liberty will also be in the base CXF product.  I would only open an issue with CXF if you have verified that the problem exists with only CXF (outside of Open Liberty).  If we find that the bug is in CXF code, we'll submit a patch back to the CXF community so that it will be fixed in both places.  Thanks!

**Comment by andymc12** [comment]
So, this error is definitely specific to Open Liberty - the bug is in our JsonBProvider class, which does not inject context values into the ContextResolver instances that it uses. This would impact any context-injected value, not just `SecurityContext`, so if you don't mind, I may change the title of this issue to make it more "findable" by other users (who might see the same problem but with a different context type).  I also chose to test my fix using `@Context HttpHeaders` since that required less changes to an existing test case (no need to add-in authorization checks etc.).  

Thanks again for reporting this and the detail provided!

**Comment by rslemos** [comment]
So you're saying me it's specific to Json-b?
Shouldn't we test also for Jackson, that is, ContextResolver<ObjectMapper>?

**Comment by rslemos** [comment]
Updated my [project](https://github.com/rslemos/open-liberty-12715) to test Jackson. All injections are working fine.

Jackson [finds its `ContextResolver<ObjectMapper>`](https://github.com/FasterXML/jackson-jaxrs-providers/blob/a42a0790c2be7dc2e7c0b32c8ec0e0a0e2c9f027/json/src/main/java/com/fasterxml/jackson/jaxrs/json/JacksonJsonProvider.java#L198) by means of [`Providers.getContextResolver(...)`](https://jax-rs.github.io/apidocs/2.0.1/javax/ws/rs/ext/Providers.html#getContextResolver(java.lang.Class,%20javax.ws.rs.core.MediaType)). Isn't it simpler?

**Comment by andymc12** [comment]
The bug was in Liberty's JSON-B / JAX-RS Provider - it doesn't use the `Providers` implementation to get the ContextResolver(s) - instead it uses internal CXF injection methods.  This is mainly to avoid using context injection in a runtime class (which has different classloading implications).

**Comment by bmhm** [comment]
Today, using 20.0.0.3 through 20.0.0.6, I stumbled over this.
I thought this was already implemented: 
 * Issue https://github.com/OpenLiberty/open-liberty/issues/5903
 * Merged PR https://github.com/OpenLiberty/open-liberty/pull/6485
 * Performance commit https://github.com/OpenLiberty/open-liberty/pull/7025/files

So, isn't this technically a regression?
