### ISSUE TITLE
Unable to Override JAX-RS SecurityContext in ContainerRequestFilter

### ISSUE THREAD

**Issue by abrievanaardt** [OpenLiberty/open-liberty#12724]
### Bug description
Overriding the default SecurityContext in a JAX-RS authorisation filter using `ContainerRequestFilter.setSecurityContext()`does not affect the SecurityContext used by OpenLiberty during authorisation. It seems that the internal Apache CXF `SecurityContext` is used regardless, so there's no way to override behaviour on e.g. the `SecurityContext.isUserInRole()` method which is especially useful for custom behaviour for JSR 250 security annotations.

### Steps to reproduce

1. Define a `ContainerRequestFilter` registered on a phase such that it runs before OpenLiberty's authorisation filters. Replace the current `SecurityContext` with any other that exhibits your expected behaviour, e.g.:

```java
@Provider
@Priority(AUTHORIZATION)
public class RBACRequestFilter implements ContainerRequestFilter {

    @Override
    public void filter(ContainerRequestContext requestContext) {

        SecurityContext myCustomSecurityContextWrapper =
                new MyCustomSecurityContextWrapper(requestContext.getSecurityContext());

        requestContext.setSecurityContext(myCustomSecurityContextWrapper);
    }
}
```
2. Use any of the JSR 250 security annotations on a JAX-RS resource, e.g. `@RolesAllowed`. 
3. When debugging, notice that none of the methods on the new `SecurityContext` is invoked.

### Expected behaviour
I expect that OpenLiberty should make use of the overridden `SecurityContext` when determining whether a call to a JAX-RS resource is authorised.

### Diagnostic information:
 - OpenLiberty Version: 20.0.0.5
 - Java Version:
OpenJDK version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)

### Additional context
It seems this exact issue was reported for Quarkus as well and has since been resolved, see [here](https://github.com/quarkusio/quarkus/issues/6105). I've also done some digging which can hopefully point someone in the right direction: Looking at the `LibertySimpleAuthorizingInterceptor` class it retrieves an instance of `org.apache.cxf.security.SecurityContext` by invoking `message.get(SecurityContext.class)`. However, in `ContainerRequestContextImpl`, `setSecurityContext()` has the following implementation:

```java
@Override
public void setSecurityContext(SecurityContext sc) {
    checkContext();
    m.put(SecurityContext.class, sc);
    if (sc instanceof org.apache.cxf.security.SecurityContext) {
        m.put(org.apache.cxf.security.SecurityContext.class,
              (org.apache.cxf.security.SecurityContext) sc);
    }
}
```
The backing map in `Message` holds the two contexts against their individual canonical names. The JAX-RS `SecurityContext` parameter above is added with a call to `put`, but a different `SecurityContext` type is retrieved in the built-in authorisation filter.

**Comment by asodja** [comment]
Does it work with `@PreMatch`? 

Example from Quarkus Unit tests: https://github.com/gsmet/quarkus/commit/7cacfe0d1f216c3d95631ece48abed43742c877d#diff-a3773f2638e291c8d417bdb4ac4c2d6e

**Comment by abrievanaardt** [comment]
I've tried adding `@PreMatching` on the filter. I've also tried `@Priority`s of 100 above and below `AUTHORIZATION`. But, all to no avail.

**Comment by WhiteCat22** [comment]
Looks like my changes were successfully merged and this issue is fixed.

I modified our AuthorizingInterceptor in both jaxrs-2.0 and jaxrs-2.1 to check if there was an ```javax.ws.rs.core.SecurityContext`` and process it if it exists, then default back to our old behavior of processing the ```org.apache.cxf.security.SecurityContext``` if one has not been supplied.

I then set the priority of our filter, which is the entry point for our Interceptor, to ```Priorities.AUTHORIZATION + 1``` to ensure that any user provided filter with Priority ```Priorities.AUTHORIZATION``` get's ran first.

I also created the CustomSecurityContextTest to test these changes.
