### ISSUE TITLE
RestEasy JAXRS Integration:  Migration tool entries / Documentation differences

### ISSUE THREAD

**Issue by jim-krueger** [OpenLiberty/open-liberty#12742]
The purpose of the is issue is to document/resolve potential Migration tool and Documentation issues related to the JAXRS RestEasy Integration.

**Comment by jim-krueger** [comment]
1.  Currently RestEasy does not support the IBMRestServlet used in JAXRS 2.0 and 2.1.

**Comment by andymc12** [comment]
In 2.0/2.1, users could specify the SSL configuration property ("com.ibm.ws.jaxrs.client.ssl.config") and proxy configuration properties ("com.ibm.ws.jaxrs.client.proxy.*") on the `ClientBuilder`, the `Client`, and the `WebTarget`. In 3.0, the user is only allowed to specify the SSL configuration property on the `ClientBuilder`. See #13476 for more details.

**Comment by WhiteCat22** [comment]
The Restful WS 3.0 spec made the change so that users are now required to perform CDI injection themselves when using the Applicaiton.getSingletons() method:
https://github.com/eclipse-ee4j/jaxrs-api/pull/836/files

This differs from Jaxrs-2.0 and 2.1 where the user could simply new up an instance of their singleton class and we'd get a 2nd instance from CDI under the covers in order to inject into the singleton classes.

Going forward, getSingletons() is deprecated completely in Restful WS 3.1

**Comment by jkoehler22** [comment]
In 2.1, users were not required to specify `<async-supported>true</async-supported>` in their web.xml if using server-side async. In 3.0, users are required to specify `<async-supported>true</async-supported>` in their web.xml if using server-side async.

**Comment by jkoehler22** [comment]
~~In 2.1, CXF preserves = or lack thereof, for the query param in the request.  In 3.0, RestEasy does not preserves = or lack thereof for the query param in the request.~~

Andy has a potential fix in https://github.com/OpenLiberty/open-liberty/pull/16518
The web container is also pursuing a more global fix in: https://github.com/OpenLiberty/open-liberty/pull/16531

**Comment by jkoehler22** [comment]
~~In 2.1, users that used the default of  media type of` "*/*"`, the `ClientRequestContext` `StringHeaders`  was automatically updated to include `"*/*"`.  In 3.0, users that used the default of  media type of `"*/*",` the `ClientRequestContext` `StringHeaders ` is not updated to include `"*/*"`.~~

Andy fixed:  [16290](https://github.com/OpenLiberty/open-liberty/pull/16290)

**Comment by jkoehler22** [comment]
A Client property with a null value is maintained as part of the Client's internal configuration state in JAXRS-2.0 and is removed from the Client's internal configuration state in 3.0.

**Comment by jkoehler22** [comment]
In 2.1, users that use `Response.readEntity() `will see an `IllegalStateException` when the entity is empty.  In 3.0, users that use `Response.readEntity()` will see an empty string when the entity is empty.

**Comment by jkoehler22** [comment]
In 3.0, `JSON4JObjectProvider` is not supported.

**Comment by andymc12** [comment]
There is ambiguity in the javadocs for `HttpHeaders.getRequestHeader(String headerName)` when the specified headerName does not exist.  The [javadocs](https://jakarta.ee/specifications/restful-ws/3.0/apidocs/jakarta/ws/rs/core/httpheaders#getRequestHeader(java.lang.String)) say:

>Get the values of a HTTP request header. The returned List is read-only. This is a shortcut for getRequestHeaders().get(name).
...
Returns:
a read-only list of header values.
 

There is a conflict there because the shortcut code, `getRequestHeaders().get(name)` would return null if the header name (map's key) does not exist in the map. This is what CXF (jaxrs 2.0 and 2.1) does - it returns null.

But the description and "returns:" section both says that this method must return a read-only list - it says nothing about returning null, so RESTEasy returns `Collections.emptyList()`.  

I am intending to address this conflict in the spec with JAX-RS API issue https://github.com/eclipse-ee4j/jaxrs-api/issues/944

**Comment by jkoehler22** [comment]
In 3.0, `ClientBuilder` properties of `com.ibm.ws.jaxrs.client.receive.timeout` and `com.ibm.ws.jaxrs.client.connection.timeout` are not supported.  Users can use `ClientBuilder` `connectTimeout` and `readTimeout`.

**Comment by jkoehler22** [comment]
~~In 3.0, `ClientBuilder` property of `com.ibm.ws.jaxrs.client.ltpa.handler` is not supported. Users can use (when we figure out how to handle LTPA with RestEasy add to this comment)~~

These are supported - see #17160 for more details.

**Comment by jkoehler22** [comment]
~~In 2.0/2.1, users could specify either a  `Invocation.Builder` `get(x.class)` or  `Response` `get().readEntity(x.class)` to return the class type. In 3.0, only `Response` `get().readEntity(x.class)` can be used to return the class type.~~

This test case (which is repeated in 2.0, 2.1, and 3.0) shows that `Invocation.Builder#get(String.class)` works.

**Comment by andymc12** [comment]
JAX-RS parameters are not allowed to be injected into a resource class's constructor. With resources now being CDI beans, only CDI injection may occur in resource class constructors. 

The following examples would need to be re-written:
```
@Path("myPath")
public class MyResource {

    private String q1;

    public MyResource(@QueryParam("q1") String q1) {
        this.q1 = q1;
    }

    @GET
    public Response get() {
        doSomethingWith(q1);
        // ...
    }
}
```

Instead, this should be written like:
```
@Path("myPath")
public class MyResource {

    @GET
    public Response get(@QueryParam("q1") String q1) {
        doSomethingWith(q1);
        // ...
    }
}
```

**Comment by andymc12** [comment]
Subresource locator methods must not share the same path as a regular subresource method.  For example, the following code would work with CXF (jaxrs-2.0 / jaxrs-2.1), but will result in an error in RESTEasy (restfulWS-3.0):
```
@Path("/root")
public class MyRootResource {
    /*
     * Subresource locator method.
     */
    @Path("subresource")
    public MyObject postSub() {
        return new MyObject();
    }

    public static class MyObject {

        @POST
        public String hello() {
            return "MyObject.hello()";
        }
    }

    /*
     * Subresource method.
     */
    @GET
    @Path("subresource")
    public String getSub() {
        return "MyRootResource.getSub()";
    }
}
```

In EE9 this will result in an error message like:
```
[6/16/21, 13:48:03:249 CDT] 00000050 org.jboss.resteasy.resteasy_jaxrs.i18n                       W RESTEASY002195: The following sub-resource methods and sub-resource locators have the same path, [/root/subresource].  The paths should be unique.  [com.ibm.ws.jaxrs.fat.resourcealgorithm.MyRootResource.getSub, com.ibm.ws.jaxrs.fat.resourcealgorithm.MyRootResource.postSub]
```

**Comment by WhiteCat22** [comment]
We have decided that users are required to annotate their `Application` subclasses with the `@ApplicationPath()` annotation if they want CDI injection into those classes for the `restfulWS-3.0` feature.

See https://github.com/OpenLiberty/open-liberty/pull/17488#issuecomment-866438245
 for more information.

**Comment by andymc12** [comment]
In an effort to position Open Liberty for JAX-RS 3.1, the JAX-RS 3.0 implementation will always use CDI - and it will treat `@ApplicationPath`, `@Path`, and `@Provider` as bean-defining annotations.  By default, JAX-RS resources annotated with `@Path` will be request-scoped while providers and app sub-classes (annotated with `@Provider` and `@ApplicationPath`, respectively) will be application-scoped.

**Comment by andymc12** [comment]
* inclusion of EJBs in the `getClasses` method - in JAX-RS 2.X (CXF), users could specify the local interface of the EJB bean. In JAX-RS 3.0 (RESTEasy), users must specify the bean class itself. See https://github.com/OpenLiberty/open-liberty/issues/18210#issuecomment-902116281 for more details.

**Comment by jim-krueger** [comment]
In 2.0 and 2.1 CXF accepts the use of wildcards in the ApplicationPath annotation:  `@ApplicationPath(value="/rest1/*")`
RESTEasy does not allow this and the specification appears to back them up:

> If the Application subclass is annotated with @ApplicationPath, implementations are REQUIRED to use the value of this annotation appended with ”/*” to define a mapping for the added server.

This means that `@ApplicationPath("/somePath")` is the equivalent of a web.xml servlet mapping of /somePath/*

**Comment by andymc12** [comment]
Documented in 21.0.0.12 in STE and OL Docs
