### ISSUE TITLE
Custom JDBC Driver configuration not working with Openliberty

### ISSUE THREAD

**Issue by emyes** [OpenLiberty/open-liberty#12775]
Hello everyone, 

  **Note: This could be invalid.** Just need suggestion in implementing TracingDriver exposed by below open source project.

https://github.com/opentracing-contrib/java-jdbc

I'm trying to create an datasource using TracingDataSource  exposed by above project. I'm getting below error

FFDC1015I: An FFDC Incident has been created: "java.lang.NoClassDefFoundError: io/opentracing/Tracer com.ibm.ws.jdbc.DataSourceService 591" at ffdc_20.06.24_14.04.24.0.log*
[2020/06/24, 14:04:24:638 CAT] 00000046 com.ibm.ws.logging.internal.impl.IncidentImpl I FFDC1015I: An FFDC Incident has been created: "java.lang.NoClassDefFoundError: io/opentracing/Tracer com.ibm.wsspi.injectionengine.InjectionBinding.getInjectionObject 408" at ffdc_20.06.24_14.04.24.1.log
[2020/06/24, 14:04:25:498 CAT] 00000046 com.ibm.ws.logging.internal.impl.IncidentImpl I FFDC10

Any one tried to make use of above api to trace db calls in OL

**Comment by fmhwong** [comment]
java-jdbc has the following compile dependencies:

```
io.opentracing:opentracing-api:jar:0.33.0:compile
io.opentracing:opentracing-noop:jar:0.33.0:compile
```

The jar created by `mvn install` doesn't include the dependencies.  You can try to create a jar with the dependencies included.

**Comment by emyes** [comment]
Hi @fmhwong , 

   Thanks for the response. 
  My app is having above mentioned opentracing dependencies.   I'm trying to configure java-jdbc as mentioned in the below page

https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_dep_configuring_ds.html

<dataSource id="DefaultDataSource" jndiName="jdbc/sample" type="javax.sql.DataSource">
    <jdbcDriver libraryRef="SampleJDBCLib" 
                javax.sql.XADataSource="io.opentracing.contrib.jdbc.TracingDataSource"/>
    <properties databaseName="SAMPLEDB" hostName="localhost" port="12345"/>
</dataSource>

<library id="SampleJDBCLib">
    <file name="C:/Drivers/SampleJDBC/opentracing-jdbc.jar"/>
</library>

NoClassDefFoundError appearing in server logs. I'm trying to inject the datasource inside my  CDI bean.

**Comment by fmhwong** [comment]
Can you share your server configuration files?  `server.xml`, `server.env`, etc

**Comment by emyes** [comment]
[server.txt](https://github.com/OpenLiberty/open-liberty/files/4832634/server.txt)

**Comment by fmhwong** [comment]
I see some incompatibilities.

`MicroProfile-3.2` includes `mpOpenTracing-1.3`.  `mpOpenTracing-1.3` provides OpenTracing API version 0.31.  The java-jdbc project depends on OpenTracing API 0.33 and OpenTracing Noop 0.33.  There are breaking changes between 0.31 and 033.  You may need to use an older version of java-jdbc that depends on OpenTracing API 0.31.

**Comment by emyes** [comment]
Thank you @fmhwong . Appreciated.  Java-jdbc doesn't have TracingDataSource file with version that supports Open Tracing 0.31.  It seems now i can't use it directly. I will close this ticket.  Thanks for your time.

**Comment by HasseNasse** [comment]
Has this been resolved? We're still getting similar errors.

**Comment by fmhwong** [comment]
Open Liberty has released 2 more versions of MicroProfile OpenTracing.
- `mpOpenTracing-2.0` which is compatible with OpenTracing API version 0.33 and Jakarta EE 8.  
- `mpOpenTracing-3.0` which is also compatible with OpenTracing API version 0.33 and Jakarta EE 9.
