### ISSUE TITLE
Feature Test Summary for LG-286

### ISSUE THREAD

**Issue by Yushan-Lin** [OpenLiberty/open-liberty#12784]
**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

The FAT tests the functionality of the `appsWriteJson` logging attribute - this currently passes 100%, which was added under the `com.ibm.ws.logging.json_fat` project.

The FAT test the following:
`testAppsWriteJson `- Tests server.xml update of appsWriteJson to ensure application JSON logs are written directly to System.out/System.err when `appsWriteJson="true"`. Application logs that are tested includes empty JSON string and JSON written to System.out and System.err.

`testEnableAppsWriteJsonInProperties` - Tests setting the attribute `com.ibm.ws.logging.apps.write.json` to true in the bootstrap.properties.

`testEnableAppsWriteJsonEnv` - Tests setting the attribute `WLP_LOGGING_APPS_WRITE_JSON` to true in the server.env.

`testAppsWriteJsonPrecedence `- Tests the precedence order of the attribute by setting `WLP_LOGGING_APPS_WRITE_JSON` to true in the server.env, setting `com.ibm.ws.logging.apps.write.json` to false to ensure that the functionality is not enabled. In the server.xml, `appsWriteJson` is set to true to enable the functionality again.

Manual testing was also done as an extra level of verification of function already tested by `com.ibm.ws.logging.json_fat`.

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

4

**Comment by ayoho** [comment]
Testing coverage looks fine to me. Closing this and approving the feature.
