### ISSUE TITLE
Need to limit how many times an OIDC refresh token can be used to get new tokens

### ISSUE THREAD

**Issue by yannizhang2019** [OpenLiberty/open-liberty#12790]
Expected behavior: Need to limit how many times an OIDC refresh token can be used to get new tokens
Current behavior: you can have unlimited requests to get the tokens. This can cause potentially large number of tokens accumulated.

**Diagnostic information:**
os linux
version 19.0.0.3
java.runtime = Java(TM) SE Runtime Environment (8.0.5.40 - pxa6480sr5fp40-20190807_01(SR5 FP40))

**Additional context**

**Comment by chunlongliang-ibm** [comment]
In Liberty OIDC authorization flow, we limit how many tokens a client can be issued for a user, but we do not put token limit on refresh token which results unlimited access_tokens for a given refresh_token
