### ISSUE TITLE
Feature Test Summary for LG-265

### ISSUE THREAD

**Issue by jennifer-c** [OpenLiberty/open-liberty#12803]
**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature.

If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

The FAT tests the functionality of the `jsonAccessLogFields` attribute in the logging element. The tests are added under the com.ibm.ws.logging_fat project in a new test suite `CustomAccessLogFieldTests`.

The FAT tests the following:
| Test | Behaviour being tested |
|---|---|
| testAccessLogFieldNamesEnv | Tests setting the attribute `WLP_LOGGING_JSON_ACCESS_LOG_FIELDS` to `logFormat` in the server.env.  |
| testAccessLogFieldNameBootstrap | Tests setting the attribute `com.ibm.ws.logging.json.access.log.fields` to `logFormat` in the bootstrap.properties. | 
| testAccessLogFieldNameXml | Tests setting the attribute `jsonAccessLogFields` to `logFormat` in the server.xml. | 
| testAccessLogFaultyConfig | Tests that `CWWKG0032W` is printed if the property is not set properly. |
| testRenameAccessLogField | Tests that access log field names can be renamed. |
| testOmitAccessLogField | Tests that access log field names can be omitted. |
| testAllFieldsArePrinted | Tests that all possible fields are printed correctly in the JSON log. |
| testNullValuesDontPrintInJSON | Tests that null values do not print in the JSON log (instead, the field does not show up.) Anything that shows up as a `-` in the http_access.log will not print to JSON logs. |
| testDefaultWillNotPrintNewFields | Tests that setting the attribute `jsonAccessLogFields` to `default` in the server.xml will not print any new fields and behave the same as before. |
| testFieldsInAccessLogAreSameInJSON | Tests that the fields in the http_access.log have the same values in messages.log. |
| testChangeJsonAccessLogFieldsConfigValue | Tests that the `jsonAccessLogFields` attribute can be changed on-the-fly in the server.xml. |
| testDisableAccessLog | Tests that removing the `accessLogging` property while the server is running removes the JSON access logs too. |
| testEnableAccessLog | Tests that adding the `accessLogging` property while the server is running enables the JSON access logs too.  |
| testInvalidTokens | Tests that an invalid `logFormat` token will throw an FFDC but not interrupt printing the keys that are valid to the JSON log. |
| testDuplicateTokensInLogFormat | Tests that duplicate tokens in the `logFormat` will only print once in the JSON log. |
| testDefaultIsSameAsOriginal | Tests that the setting `jsonAccessLogFields="default"` will exhibit the same behaviour as setting `logFormat='%h %H %A %B %m %p %q %{R}W %s %U %{User-Agent}i'` (default fields before this new feature) with `jsonAccessLogFields="logFormat"`. |
| testMultipleHttpEndpoints | Tests that only one `SetterFormatter` is created per configuration. Each endpoint has its own independent `SetterFormatter` to have multiple `logFormat` configurations. |

Manual testing was also done as an extra level of verification of function already tested by com.ibm.ws.logging_fat.

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

**Comment by ayoho** [comment]
The testing coverage looks great, the bucket appears to be running well, and I'm not seeing any unaddressed defects in this area. I'll go ahead and close this out and give FAT approval for the feature.
