### ISSUE TITLE
Delay application startup until configured mechanisms are in place

### ISSUE THREAD

**Issue by chackoj** [OpenLiberty/open-liberty#12815]
While addressing #11151 it became evident that there was no way to delay application startup _generically_ for services on which applications might depend.

This problem has historically been dealt with by outputting log messages when services were available and explicitly waiting for all the relevant log messages within any test that used those services. This approach is flawed because it allows applications to be available before they can work correctly. 

It may be reasonable to tell an administrator to start a server and wait for the appropriate log messages, but it is quite unreasonable to expect automated admin tasks to wait for a set of log messages that are not easily discoverable and subject to change with changes to server configuration.

We propose a generic mechanism that would allow a configured feature to declare and eventually supply a number of DS components of type `ApplicationPrereq`. Each application handler would wait for the number of declared instances of `ApplicationPrereq` to become available before starting up.

This would be achieved using the `….cardinality.minimum` service property [defined in the OSGi spec](https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.component.html#service.component-minimum.cardinality.property) along with OpenLiberty's reference counting metatype extensions.

**Comment by chackoj** [comment]
@brenthdaniel notes that while the described approach is both viable and an improvement to the status quo, it leaves a timing window in which application handlers might be started before config processing has progressed far enough to discover all the declared `ApplicationPrereq` services.

In this case, once the relevant config is discovered, the application handlers would be destroyed and re-created. This is undesirable but still eventually correct. Ideally, we should find a solution that does not have such a window, but perhaps this proposal is only a step on the journey towards that ideal.

Here is a description of the timing window problem as I understand it:

- The WAR application handler is started because no `ApplicationPrereqs` are known to have been declared yet.
- Configuration for the messaging feature and its bundles is processed, and an `ApplicationPrereq` is discovered.
- The WAR application handler configuration is re-processed, and its `ApplicationPrereq` service reference now has a minimum cardinality of 1.
- The WAR application handler is stopped because it does not meet the service requirements.
- A new WAR application handler is started with the declared service reference.

This timing window is minimal, and I do not think it would progress to the application being started up before the handler is stopped and replaced.

@brenthdaniel: please correct me if I have misunderstood/misrepresented anything

**Comment by tjwatson** [comment]
I do not understand the timing window.  All application handlers are installed by the feature manager as bundles contained in features it is installing.  The feature manager signals to the config impl that all the bundles have been installed and resolved that are needed as part of a feature update operation.  At this point my understanding is that config should discover all the default configurations available in all the currently installed bundles.  This happens before feature manager activates any of the newly installed bundles.  Config should have done all it needs to do synchronously before any of the feature bundles containing application handlers are activated and their components start getting handled by SCR.

**Comment by chackoj** [comment]
After a live meeting, we have the following recommended modifications to the proposal:
- Do *NOT* make any new interfaces part of the Liberty SPI (at least until we have tried the mechanism and reviewed it as SPI)
- Move the ApplicationStartBarrier dependency into the app manager to avoid duplication of this dependency across every app handler
- For any DS components that become application prereqs, consider removing them from default test configuration and adding them explicitly to only those tests that need them. This may help avoid introducing unnecessary delays and potential timeout failures.
