### ISSUE TITLE
Ensure Correct XML namespaces are used in JSP-3.0

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#12856]
JSP files references to namespaces as so: _xmlns:c="http://java.sun.com/jsp/jstl/core"_
These will need to be updated to align with the new Jakarta namespaces, if any changes are made.  It doesn't appear anything has changed yet. 

However, there have been changes to the JSP resources & JSTL Tag Libraries.

We will need to use the correct JSP resources (#12637)  and Taglibs ( #15317). Issues are for reference, but similar changes will need to be made.

**Comment by pnicolucci** [comment]
@volosied  is there any remaining work for this issue?

**Comment by volosied** [comment]
I think just #15938.

It's where we need an export to stay in a bundle even though no files exist within that package.  I"ll follow up with you on slack.

**Comment by isaacrivriv** [comment]
Going through the Jakarta Pages spec Im not seeing any updates to the namespace used in JSP files so I believe this one can be closed and can be followed up in #12637

**Comment by pnicolucci** [comment]
`https://github.com/eclipse-ee4j/jstl-api/issues/144` is an issue where the namespace will be updated for Jakarta EE10 for Jakarta Tags but nothing was done there for Jakarta EE9
