### ISSUE TITLE
Update TAI javadoc regarding initialization

### ISSUE THREAD

**Issue by e-phan** [OpenLiberty/open-liberty#12864]
**Describe the bug**
The TrustAssociationInterceptor (TAI) javadoc in the [Liberty IBM knowledge center](https://www.ibm.com/support/knowledgecenter/en/SSD28V_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.security_1.3-javadoc/com/ibm/wsspi/security/tai/TrustAssociationInterceptor.html) is misleading. It suggests that the initialization status is checked when a TAI is invoked, and that the properties *com.ibm.websphere.security.trustassociation.initStatus* and *com.ibm.websphere.security.trustassociation.ignoreInitStatus* can be used.

>  The return status is now checked before using the trust association interceptor implementation. A return of 0 is considered SUCCESS and anything else a FAILURE. If your previous implementation of the TAI returns a different error status you can either change your implementation to match the expectations or do one of the following:
> 
>    1. Add the property com.ibm.websphere.security.trustassociation.initStatus in the Trust Association Interceptor custom properties and set it to the value that indicates SUCCESS in your implementation. All other values imply failure. In case of failure, the corresponding TAI implementation will not be used.
> OR
>    2. Add the property com.ibm.websphere.security.trustassociation.ignoreInitStatus in the Trust Association Interceptor custom properties and set it to true to indicate to WebSphere to ignore the status of this method. In this case WebSphere will not check the return status from this method just like in the earlier versions.
> 

But this is not how Liberty behaves. When a TAI is configured, it is invoked (at least for the _isTargetInterceptor_ method) regardless of the initialization status. The javadoc needs to be updated accordingly and maybe needs to state that the initialization status is not checked.

**Steps to Reproduce**
N/A

**Expected behavior**
N/A

**Diagnostic information:**
 - Liberty for z/OS 20.0.0.3
 - Java Version: 1.8.0_241
 - Java Runtime: Java(TM) SE Runtime Environment (8.0.6.7 - pmz6480sr6fp7-20200312_01(SR6 FP7))

**Additional context**
N/A

**Comment by utle** [comment]
Fixed by https://github.com/OpenLiberty/open-liberty/pull/12847
