### ISSUE TITLE
Create MD5 (Checksums) for release file.

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/open-liberty#12873]
Similar to what we do for our Maven releases, generated checksum files, and publish to DHE release directories.

We can replicated how the Maven files are generated, and reuse these for DHE publish steps.

**Comment by mbroz2** [comment]
Looks like for maven we provide both MD5 and SHA-11; since those two are no longer considered secure, we should also consider adding something from SHA-2 family, like SHA-256
