### ISSUE TITLE
Classloader's apiTypeVisibility attribute is not overriden by the xml under configDropins

### ISSUE THREAD

**Issue by mkoinuma** [OpenLiberty/open-liberty#12905]
**Describe the bug**

My server.xml has something like the following for my enterprise app:
```
    <enterpriseApplication id="op-apps" location="op-apps.ear" name="op-apps">
        <classloader commonLibraryRef="jaas-proxy" privateLibraryRef="ext-lib" />
        ...
    </enterpriseApplication>
```
and it is working fine.

The above is provided as part of an IBM product and when our customers or BPs are asking for a configuration modification, we advise them to drop a separate xml to `<server>/configDropins/override/` folder.

However when the following xml is added to `<server>/configDropins/override/` folder, the api visibility is not overriden and it results in NoClassDefFoundError for the customer's custom code, which requires the third-party API visibility:
```
    <enterpriseApplication id="op-apps" location="op-apps.ear" name="op-apps">
        <classloader apiTypeVisibility="+third-party" commonLibraryRef="jaas-proxy" privateLibraryRef="ext-lib" />
        ...
    </enterpriseApplication>
```

If I update the server xml at the base `<server>` folder with the `apiTypeVisibility` attribute, it is functional and we no longer see the NoClassDefFoundError. 
However it is supported to override the server configuration via the xml under configDropins right?

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.3
 - Java Version: 
```
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 8.0.6.5 - pxa6480sr6fp5-20200111_02(SR6 FP5))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200108_436782 (JIT enabled, AOT enabled)
OpenJ9   - 7d1059c
OMR      - d059105
IBM      - c8aee39)
JCL - 20200110_01 based on Oracle jdk8u241-b07
```
 - server.xml configuration (WITHOUT sensitive information like passwords): see above

**Comment by brenthdaniel** [comment]
Hi, 

 This is a bit of a historical oddity with the way the `classloader` element is defined that we should be able to fix. In the meantime, you can work around this by specifying a matching `id` attribute on both `classloader` elements.

**Comment by mkoinuma** [comment]
Thank you for the workaround suggestion @brenthdaniel . We'll give it a try.

**Comment by mkoinuma** [comment]
The suggested workaround worked for us. Thank you.
