### ISSUE TITLE
JAAS - All authenticated users does not work without WSCredential

### ISSUE THREAD

**Issue by Thihup** [OpenLiberty/open-liberty#12953]
I'm migrating a legacy application that uses JAAS Login Modules to authenticate.
The objective is to allow all authenticated users to be authenticated, and get the login object through _HttpServletRequest.getUserPrincipal_. Currently, it is added a custom public credential to the subject. 

I'm not able to complete the authorization successfully because in BuiltinAuthorizationService class, in method isAuthorized, it calls the method _isSubjectValid_ and only if it is OK it calls the _isAllAuthenticatedGranted_.

However, isSubjectValid requires to have a WSCredential, it does not allow a custom one, thus making the whole process to fail.

server.xml:
```xml
   <application-bnd>
      <security-role name="*">
         <special-subject type="ALL_AUTHENTICATED_USERS" />
      </security-role>
   </application-bnd>
   <jaasLoginModule id="Login" classProviderRef="Login" className="some.package.LoginModule" controlFlag="SUFFICIENT" />
   <jaasLoginContextEntry id="system.WEB_INBOUND" name="system.WEB_INBOUND" loginModuleRef="Login"/>
```
web.xml:
```xml
    <security-constraint>
        <web-resource-collection>
            <web-resource-name>All resources</web-resource-name>
            <url-pattern>/*</url-pattern>
        </web-resource-collection>
        <auth-constraint>
            <role-name>*</role-name>
        </auth-constraint>
    </security-constraint>
    <security-role>  
        <role-name>*</role-name>  
    </security-role>
```

LoginModule:
```java
    private SomeClassPrincipal login;
    @Override
    public boolean commit() {
        subject.getPrincipals().add(login);
        subject.getPublicCredentials().add(login);
        return true;
    }
```

**Comment by arkarkala** [comment]
The builtin authorization does require WSCredential. 

If you have to use a custom login module to authenticate and use built in authorization, you need to follow the instructions here (Develop a sample custom login module using hashtable login.) https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_dev_custom_jaas.html 
and configure it as shown here 
https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_sec_jaas.html

You can authenticate the user in your custom login module  and fill in the required shared state info and we will create the WSCredential - you can create your own credentials too.

You can also implement your own authorization (using JACC) if you have any custom authorization requirement.

**Comment by Thihup** [comment]
Alright. Using the hashmap both the authentication and authorization works, however, the HttpServletRequest.getUserPrincipal returns a WSPrincipal, without any way to get information from the subject. The only available thing is the getName method. 
I would like to get the Principal that I've created in the LoginModule. Is there a way to do this?

**Comment by utle** [comment]
You can use public API com.ibm.websphere.security.auth.WSSubject to get the subject information. The  com.ibm.websphere.security.cred.WSCredential may useful for you.

**Comment by arkarkala** [comment]
You can get the subject as Ut mentioned and get your Principal from that. 

Or you can configure the appSecurity-3.0 feature  and try the following and see - javax.security.enterprise.SecurityContext.getPrincipalsByType(Class<T> pType)

More info: https://javaee.github.io/security-api/apidocs/javax/security/enterprise/SecurityContext.html

**Comment by Thihup** [comment]
Thank you all!

Both alternatives worked pretty well. I was unsure of how to get the SecurityContext, but I could by using the CDI:

```java
CDI.current().select(javax.security.enterprise.SecurityContext.class).get()
```

**Comment by arkarkala** [comment]
You can inject SecurityContext in your code. CDI will make it available for you. @Inject SecurityContext securityContext;
