### ISSUE TITLE
Rename JPA 2.2 Container + CDI 2.0 Autofeature and remove version numbers

### ISSUE THREAD

**Issue by jgrassel** [OpenLiberty/open-liberty#1296]
I see that the project "com.ibm.websphere.appserver.jpaContainer2.1-cdi1.2" was updated to support both jpa 2.1/2.2 + cdi 1.2/2.0, with the following:

IBM-Provision-Capability: \
  osgi.identity; filter:="(&(type=osgi.subsystem.feature)(|(osgi.identity=com.ibm.websphere.appserver.cdi-1.2)(osgi.identity=com.ibm.websphere.appserver.cdi-2.0)))", \
  osgi.identity; filter:="(&(type=osgi.subsystem.feature)(|(osgi.identity=com.ibm.websphere.appserver.jpaContainer-2.1)(osgi.identity=com.ibm.websphere.appserver.jpaContainer-2.2)))"

While this works, the name of the project obfuscates the fact that the feature services both JPA 2.1 + CDI 1.2 and JPA 2.2 + CDI 2.0.  Thus we should rename the project to eliminate that confusion.

**Update:** It was suggested to split it into its own auto-feature, which I agree, so repurposing this issue for that endeavor.

**Comment by tevans78** [comment]
@jgrassel my preference would be for a second auto-feature

**Comment by jgrassel** [comment]
@tevans78 Yeah, I agree with that.
