### ISSUE TITLE
Issues using authentication type as "ActiveDirectoryMSI" to connect with Azure SQL database using OpenLiberty

### ISSUE THREAD

**Issue by sadafshaikh18** [OpenLiberty/open-liberty#12995]
Expected behavior: To connect with Azure SQL database using managed service identity with Open Liberty

Actual behavior: ActiveDirectoryMSI is unspecified authentication type

OpenLiberty Version: Open Liberty 20.0.0.6
Java Version: java version "1.8.0_251"
   Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
   Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

server.xml configuration: 
[Server and Persistence xml.txt](https://github.com/OpenLiberty/open-liberty/files/4914392/Server.and.Persistence.xml.txt)

OpenLiberty startup logs:
Launching defaultServer (Open Liberty 20.0.0.6/wlp-1.0.41.cl200620200528-0414) on Eclipse OpenJ9 VM, version 1.8.0_252-b09 (en_US)
[AUDIT ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/install_apps_configuration_1491924271.xml
[AUDIT ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/open-default-port.xml
[AUDIT ] CWWKG0028A: Processing included configuration resource: /opt/ol/wlp/usr/servers/defaultServer/persistance.xml
[AUDIT ] CWWKG0028A: Processing included configuration resource: /opt/ol/wlp/usr/servers/defaultServer/jndiRegistry.xml
[INFO ] CWWKE0002I: The kernel started after 5.29 seconds
[INFO ] CWWKF0007I: Feature update started.
**[WARNING ] CWWKG0032W: Unexpected value specified for property [authentication], value = [ActiveDirectoryMSI]. Expected value(s) are: [ActiveDirectoryIntegrated][ActiveDirectoryPassword][SqlPassword][NotSpecified].**

Application logs: [StacTrace.txt](https://github.com/OpenLiberty/open-liberty/files/4914358/StacTrace.txt)

Raised an issue for microsoft mssql-jdbc to check the possible root cause (https://github.com/microsoft/mssql-jdbc/issues/1377) but it seems OpenLiberty library doesn't support ActiveDirectoryMSI as authentication type.

**Comment by aguibert** [comment]
hi @sadafshaikh18, Liberty doesn't do anything special with the `authentication` value and we just pass it along to the SQL Server driver. I think we can simply add the option since it looks like it was added in a newer version of the driver:
https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver15

As a temporary workaround, you  should be able to make this work by using a generic `<properties>` element in your datasource like this:
```xml
        <!-- using <properties> instead of <properties.microsoft.sqlserver> -->
	<properties
		databaseName="<<DB_Name>>" serverName="<<ServerName>>"
		portNumber="<<PortNumber>>" encrypt="true" trustServerCertificate="false"
		hostNameInCertificate="<<CertificateDetails>>" loginTimeout="30"
		authentication="ActiveDirectoryMSI"
		msiClientId="<<MSIClientID>>"
		/>
```

**Comment by sadafshaikh18** [comment]
Hi @aguibert,
Thank you for giving detailed insight on the reported issue.
Indeed workaround suggested by you to update <properties> instead of <properties.microsoft.sqlserver> worked for us.

**Comment by aguibert** [comment]
great, this option will be added in the next release of OpenLiberty (version `20.0.0.8`) so when you upgrade to that version you can swap back to `<properties.microsoft.sqlserver>`

**Comment by suxlv2** [comment]
Hi. Really not sure, if this is the right place to post, but looks like 23.0.0.12 doesn't support another authentication type, as we do receive the following in the log:

[WARNING ] CWWKG0032W: Unexpected value specified for property [authentication], value = [ActiveDirectoryServicePrincipal]. Expected value(s) are: [ActiveDirectoryDefault][ActiveDirectoryMSI][ActiveDirectoryIntegrated][ActiveDirectoryPassword][SqlPassword][NotSpecified]. 

While using mssql-jdbc driver v12.4.2 and the following code in my server.xml

`<properties.microsoft.sqlserver serverName="myServerName"
                                        databaseName="myDbName"
                                        portNumber="1433"
                                        integratedSecurity="false"
                                        authentication="ActiveDirectoryServicePrincipal"
                                        user="myClientId"
                                        password="myClientSecret"
                                        encrypt="true"
        />`

**Comment by bwa** [comment]
@aguibert I'm also a customer lacking support for ActiveDirectoryServicePrincipal so this is very needed for my company to actually finish migration to Azure
