### ISSUE TITLE
Grafana better support for kubernetes workloads

### ISSUE THREAD

**Issue by NissesSenap** [OpenLiberty/open-liberty#13010]
**Describe the bug**
The Grafana created by the open-liberty project is hard to use when running kubernetes/openshift workloads due to instance scanning.

**Steps to Reproduce**
Kind of long... you will need a kubernetes cluster and do a bunch of other things.
So instead I will share the issue and what I would like to have

When importing the open-liberty grafana dashboard created in: https://github.com/OpenLiberty/open-liberty/issues/10168
I'm unable to scrape my open-liberty endpoints that is running on k8s.

The reason for this seems to be that the instance that prometheus finds when you run on kubernetes is a bit hard to write.
I get the following output as instance: "10.169.2.84:9080",job="jafti",namespace="jafti",pod="jafti-f6d775684-kggv6",prometheus="openshift-user-workload-monitoring/user-workload"

![instance_default](https://user-images.githubusercontent.com/14774899/87410117-2dc05f80-c5c6-11ea-9df4-ab04577e6a88.PNG)

As you can see the default quary with the instance that grafana gets from prometheus dosen't find anything.

**Expected behavior**
Instead I would expect the instance regexp to just get me the instance name that I have defined in 
My env variable to tag MP_METRICS_TAGS:

  - name: MY_POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: MP_METRICS_TAGS
    value: instance=$(MY_POD_NAME):9080

In the picture bellow I'm using the instance variabel in grafana and hardcoding it to the ip in this case.
![instance_hardcoded](https://user-images.githubusercontent.com/14774899/87409928-f18cff00-c5c5-11ea-8c6c-6084eb15a686.PNG)

Or just use the podname but I assume that the rest of the community don't use kubernetes so you don't want to do that :)
Here you can see me pointing on the podname
![pod_hardcoded](https://user-images.githubusercontent.com/14774899/87410430-960f4100-c5c6-11ea-9de2-d587bd821833.PNG)

**Diagnostic information:**
This dosen't have anything to do with open-liberty it self.

- grafana dashboard revision 2: https://grafana.com/grafana/dashboards/11706/revisions
- Grafana v6.4.3 

**Additional context**

For someone who knows Grafana I think the rewrite of the regexp defined in https://grafana.com/grafana/dashboards/11706 is rather simple to meet both the needs of the current way of working and making the kubernetes a bit easier.

**Comment by donbourne** [comment]
@NissesSenap , we actually have Kubernetes versions of that dashboard as well.  We package them with our Open Liberty Operator at https://github.com/OpenLiberty/open-liberty-operator/tree/master/deploy/dashboards/metrics .  

The Kubernetes version of the dashboard provides filtering by pod, which I think would make your life easier.

**Comment by NissesSenap** [comment]
Ohh and using the grafana operator as well. I will give it a try tomorrow. Thanks @donbourne

**Comment by NissesSenap** [comment]
Tried it and sadly it dosen't work.
My current guess it that it's due to it adds the prometheus server where he the data comes from which dosen't match due to that I'm grabbing my data through Thanos so it the name of the prometheus in the query dosen't match with the prometheus datasourceName.

My datasourceName=Promethus which is Thanos in OCP 4.3 and above if you are using that as a middle layer.
And the real proemtheus that performs the query is called:  openshift-user-wokrload-monitroing/user-workload.
And that is what gets forwarded to grafana.

So in the current query you ask for pod="my-pod-name", prometheus="my none matching prometheus name"

<img width="902" alt="query_open-orig" src="https://user-images.githubusercontent.com/14774899/87666679-57fe5280-c769-11ea-8d8e-cde0728525d7.PNG">

So just as before when I hardcode the pod-name then it works as it should.
<img width="931" alt="query_working" src="https://user-images.githubusercontent.com/14774899/87666768-80864c80-c769-11ea-8f69-c4da89ceff7f.PNG">

As I wrote earlier I'm not good with how grafana functions and queries work and I'm not even able to find where the point to add the pod="my-pod-name", prometheus="my none matching prometheus name" is done.

If anyone can point me in the correct direction that would be great.

**Comment by NissesSenap** [comment]
Btw @donbourne do you want me to close this issue and create one in the open-liberty-operator repo instead?

I don't understand how I managed to miss these grafana deployment files but I guess I was to focused on everything surrounding the operator and just googled for open-liberty grafana dashboard and that's why i missed it...

**Comment by donbourne** [comment]
@NissesSenap , I'm interested to see how we can get that to work.

> Btw @donbourne do you want me to close this issue and create one in the open-liberty-operator repo instead

yes.  please do that so we can discuss in that project.

**Comment by NissesSenap** [comment]
I have created feature request https://github.com/OpenLiberty/open-liberty-operator/issues/190 in the open-liberty operator instead.
We will continue the discussion there.
