### ISSUE TITLE
Problems with minify for new EE compatibility feature for Jakarta EE

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#13052]
The minify operation attempts to resolve the configured set of features and then takes the results in order to determine what "minimal" set of files should be included into a packaged server.  The current behavior for minify is odd because it disregards all the rules that pertain to singleton features and tolerates.  This allows for a server configuration to include multiple versions of a feature (e.g. servlet-3.1, servlet-4.0, servlet-5.0) and packages up all that is required for all the versions to work.  In order to accomplish this the minify operation simply includes all the preferred versions of the included features and does not process anything having to do with tolerates.  The Liberty build takes advantage of this behavior in order to package up the various Liberty profiles during the build.  But this behavior causes problems for the following type of scenario.

```
A-1.0 -> B-1.0;tolerate=2.0
B-1.0 -> eeCompatible-8.0
B-2.0 -> eeCompatible-9.0
C-1.0 -> eeCompatible-9.0
```
If a server configured with features A-1.0 and C-1.0 is minified then it will include only features A-1.0, B-1.0, C-1.0 and omit B-2.0 because B-1.0 is the preferred version from A-1.0.  When the minified server is started it will cause errors that indicate A-1.0 conflicts with C-1.0 though the chain with B-1.0 -> eeCompatible-8.0.

This issue is not necessarily new, it is only becoming more likely to happen now that we have introduced the eeCompatible feature for the various versions of EE (across both Java EE and Jakarta EE versions) and we have been renaming all our jakarta EE versions of Java EE features (except for Servlet) which causes the new versions of the Jakarta EE features to not directly conflict with their Java EE singleton counterparts, instead they conflict because of the eeCompatible version they require.

Minify operation needs to be fixed and it should happen before Jakarta impl is released as GA.  There are several ways to solve this problem.  The following are only the ones I have considered so far.

1. Change minify to enforce singletons.  This will ensure the packaged server includes the minimal required features in order to successfully start the server.  But it changes the behavior in such a way that it will require changes in our build.  This also implies that it may cause issues for customers or other parts of the pipeline that may use minify and depend on the current behavior.
1. Change minify to include all preferred and tolerated features and do not enforce singletons.  This will ensure the packaged server includes at least all the required features in order to successfully start the server, but it may end up including more than necessary.  This likely has less potential impact to the Liberty users.  It is unclear if this would be a problem for the usage of minify for the build, perhaps it would cause some of the profiles to include unwanted versions?
1. Change minify to first enforce singletons, but if any singleton conflict is found then fallback to the current behavior.  An alternative fallback would be to fallback to the behavior 2.

The advantage of option 3 is that it potentially requires little or no change to our packaging in the Liberty build.  It also should have minimal impact on end users.  This is assuming that when a server configuration has no singleton conflicts then a minify operation should package up the absolute minimum set of features required for the server configuration.  Any time a conflict is found then the minify assumes the user is trying to package up multiple versions of some features and it should be allowed to.

**Comment by NottyCode** [comment]
After discussion we are going to implement 3 with a fallback to current behaviour behind a switch which is disabled by default.

**Comment by tjwatson** [comment]
#12982 has been fixed to address this design issue.  Closing.
