### ISSUE TITLE
Review 3rd party packages exposed from Weld 4

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#13099]
I'd rather we didn't expose any 3rd party packages ... but here is what was carried over from Weld 3;

Bundle-Name: WebSphere CDI Weld Third Party API
Bundle-SymbolicName: io.openliberty.cdi.3.0.thirdparty
Bundle-Description: WebSphere CDI 3.0 Weld Third Party API

Export-Package:\
 org.jboss.weld.context;version=4.0.0, \
 org.jboss.weld.context.*;version=4.0.0

**Comment by Emily-Jiang** [comment]
Those APIs were required to be exposed by some of our customers.
