### ISSUE TITLE
BETA BLOG 20900: JakartaEE: WebSocket 2.0 Support

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#13116]
a. Which Liberty feature does it relate to?

   i. Human-readable name (eg WebSockets feature)

> Jakarta WebSocket 2.0

   ii. Feature name (eg websockets-1.0)

> websocket-2.0

   iii. Is this a new feature or is it an update to an existing feature for this release?

> This is a new feature for Jakarta EE 9

   iv. Provide the fully qualified name of all public features ( as '*.esa' filenames) that are delivered as part of this work

       (eg: com.ibm.websphere.appserver.transportSecurity-1.0.esa)

       For example new or changed .esa files for public features in dev/com.ibm.websphere.appserver.features/build/libs/repo/

> io.openliberty.websocket-2.0.esa

b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc

> application developers

c. Write a sentence or two that introduces it to someone new to the general technology/concept.

>  This feature is part of the Jakarta EE9 features. The largest change in this feature is it has been updated to use and reference the new jakarta namespace. Previously the APIs used a javax namespace, but as part of Jakarta EE9, the packages were updated from javax to jakarta.

d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)

> Application developers can start working with the new jakarta namespaces as part of Jakarta EE9. The functionality of the feature will be the same as the previously released Jakarta EE8 feature but with updated packages and references to the new jakarta namespace. Currently the integration with CDI is not completed.

 
e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.

> The following feature can be included in your server.xml:

```
    <featureManager>
        <feature>websocket-2.0</feature>
    </featureManager>
```
 
f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.
`Additional information about the Jakarta WebSocket 2.0 specification can be found here: https://jakarta.ee/specifications/websocket/2.0/`
g. Attach any images to this work item as .png files.

**Comment by lauracowen** [comment]
Thanks, @pnicolucci
