### ISSUE TITLE
When to add a new feature for enabling Jakarta support

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#13137]
This issue is for discussing the approaches for how new Liberty public and protected features are created when enabling existing Liberty features for Jakarta 9 support.

There are 4 types of features to consider here:

1. A feature that has no usage of jakarta packages at all.
1. A feature that has no jakarta types used in its own defined API or SPI but it enables `com.ibm.websphere.appserver.servlet` and/or `com.ibm.websphere.appserver.transaction` features as an implementation detail
1. A feature that has no jakarta types used in its own defined API or SPI but it enables some other jakarta feature (except `com.ibm.websphere.appserver.servlet` or `com.ibm.websphere.appserver.transaction`)
1. A feature that has jakarta types included in its own defined API or SPI packages

For type 1 there is no need to define a new feature for jakarta support.  The existing one should be able to work with Jakarta 9.

For type 4 a new version of the feature is required because the API/SPI for the feature will have breaking changes because of the use of jakarta 9 types.  Spec features such as Servlet-4.0 fall into this category, but Liberty specific features may also fall into this category if some Liberty specific API/SPI has Jakarta types used within its API signatures (except for servlet).

For type 3 a new version of the feature is required because the feature toleration rules do not allow a tolerates list to cross the boundary from Java EE 8 to Jakarta EE 9 because we are renaming all jakarta feature names, except the servlet one.

For type 2 the existing feature that supports Java EE 8 servlet or transaction should be updated to now tolerate servlet-5.0 and or tolerate the appropriate transaction features.  This involves adding a tolerates for "5.0" for servlet (`com.ibm.websphere.appserver.servlet-3.0; ibm.tolerates:="3.1,4.0,5.0"`).  Any bundles that may need transforming need to be moved to two auto features.  One for the Java EE version and one for the Jakarta EE 9 version.  The auto features are then enabled based on the presence of the original feature and the version(s) of servlet/transaction the bundles are for.  This allows for an existing feature to support both Java EE and Jakarta EE 9 without introducing a new version of the public or protected feature.

This approach avoids having to introduce new versions of externals if possible when only servlet 5.0 or transaction 2.0 are being used from jakarta.  This approach has been taken for the jdbc and the webBundle features.

**Comment by tjwatson** [comment]
There is an issue to how we have done servlet 5.0.  We did not rename the public feature but we did rename the private feature that contains the servlet 5.0 API (`io.openliberty.jakarta.servlet-5.0`).  This has an unfortunate side-effect.  Our features that enable the public servlet feature `com.ibm.websphere.appserver.servlet` may be able to tolerate version 5.0.  But any of our features that only need the API and don't mandate the full public servlet feature have no ability to tolerate version 5.0.  I don't think we should have renamed the private feature for servlet 5.0 APIs.

**Comment by NottyCode** [comment]
We shouldn't be introducing new versions of restConnector which according to slack has happened. We also shouldn't be creating new versions of collective controller.

**Comment by tjwatson** [comment]
I'm not saying we have introduced a new version of restConnector.  I'm saying that I was reviewing a PR that was about to introduce it.  That lead me to document what I think we should be doing for cases like this so that the strategy is more widely understood and used where possible.

**Comment by pnicolucci** [comment]
@tjwatson @tevans78  should we move the servlet-5.0 private API feature back to the original name and not using the io.openliberty prefix? If so, our team can start working on that.

**Comment by tevans78** [comment]
The name of the servlet API **private feature** is not particularly important, it can be changed back if required. However, to be clear, please do not rename the API **bundle**, that should stay as `io.openliberty.jakarta.servlet.5.0`.

**Comment by tjwatson** [comment]
I recommend we rename the private servlet-5.0 feature name back.  As Tom Evans indicated the bundles should remain io.openliberty prefixed.  Bundle names are completely internal and we could choose to go through and rename all our existing bundles without impacting the externals.

**Comment by pnicolucci** [comment]
Ok I'll get a PR linked here with the changes.

**Comment by pnicolucci** [comment]
Looking at this a bit more closely the servlet 4.0 private API feature for example is:

**Comment by pnicolucci** [comment]
Looking at this more closely the servlet 4.0 private api feature is:

`com.ibm.websphere.appserver.javax.servlet-4.0`

However for Servlet 5.0 we would have something like:

`com.ibm.websphere.appserver.jakarta.servlet-5.0`

I'm not sure this helps us at all with the tolerations given then javax->jakarta change.  Also seems odd to keep the javax name for a Jakarta API private feature. Thoughts @tjwatson  ?

**Comment by tjwatson** [comment]
No if any of the feature name besides the `-<version>` part change then the tolerates no longer can apply to later versions.  I agree it will be odd to have a feature name (even if private) include `javax` in its name.  On the other hand we could rename all the private servlet api features at anytime because they have no externals that would break customers:

com.ibm.websphere.appserver.javax.servlet -> io.openliberty.servlet.api

leaving us with:

- io.openliberty.servlet.api-3.0
- io.openliberty.servlet.api-3.1
- io.openliberty.servlet.api-4.0
- io.openliberty.servlet.api-5.0

But we can do that any time, even after GA if necessary.  So perhaps we don't do anything here until a concrete case comes up where we have a feature that we want to tolerate the api feature across the Jakarta boundary.

**Comment by tjwatson** [comment]
BTW I quite like that feature name scheme.  The current way is confusing when looking at the features directory.  Only one with deep knowledge could glance at the feature manifest names and know what the difference is between `com.ibm.websphere.appserver.javax.servlet-4.0.mf` and `com.ibm.websphere.appserver.servlet-4.0.mf`

**Comment by tjwatson** [comment]
In order to avoid having to define a new sessionCache-2.0 feature for jakarta (issue #12984) we need to address this private feature name for the servlet.api features. This is being handled by issue #13242.  @pnicolucci, this issue is currently being looked at by @anjumfatima90.  Please let her know ASAP if you are already doing this rename.  Also let us know if there are strong objections to renaming the private features to all be `io.openliberty.servlet.api`

**Comment by pnicolucci** [comment]
@tjwatson @anjumfatima90  we have not started this work yet as we were waiting for a use case. It looks like we have one now. Let me know if you need anything. From my point of view I like the `io.openliberty.servlet.api` naming convention as it clearly states it is an api feature where previously that was difficult to determine at a glance.

**Comment by dazavala** [comment]
@tjwatson, fyi: Closing now as this issue served its purpose.
