### ISSUE TITLE
Override the EclipseLink package version in the thirdparty API bundles

### ISSUE THREAD

**Issue by dazey3** [OpenLiberty/open-liberty#13144]
In the previous jpa-2.0/jpa-2.1 third-party bundles, we didn't override the default package version. Therefore, we inherited the EclipseLink package versions (2.6.X.WAS or 2.7.X). This is the root cause of all the Feature Checker issues we have had, with those bundles, over the years. We should patch that issue with this new JPA feature.

For instance, looking at `wlp\dev\api\third-party\com.ibm.websphere.appserver.thirdparty.eclipselink.2.7_1.0.29.jar`:

```
Export-Package:
...
org.eclipse.persistence.jpa.config;version="2.0.16";
    uses:="javax.persistence,javax.persistence.spi",org.eclipse.persistence.internal.jpa.config;version="2.0.16";uses:="org.eclipse.persistence.internal.jpa.metadata.accessors,org.eclipse.persistence.jpa.config",
org.eclipse.persistence.internal.jpa.config.additionalcriteria;version="2.0.16";
    uses:="org.eclipse.persistence.internal.jpa.config,org.eclipse.persistence.internal.jpa.metadata.additionalcriteria,org.eclipse.persistence.jpa.config",
org.eclipse.persistence.internal.jpa.config.cache;version="2.0.16";
...
org.eclipse.persistence.internal.jpa.metamodel.proxy;version="2.7.4";
    uses:="javax.persistence.metamodel,org.eclipse.persistence.internal.jpa",
org.eclipse.persistence.internal.jpa.modelgen;version="2.7.4";
    uses:="org.eclipse.persistence.internal.jpa.deployment,org.eclipse.persistence.internal.jpa.metadata,org.eclipse.persistence.internal.jpa.metadata.accessors.classes,org.eclipse.persistence.internal.jpa.metadata.accessors.objects,org.eclipse.persistence.internal.jpa.modelgen.objects",
org.eclipse.persistence.internal.jpa.modelgen.objects;version="2.7.4"
...
```
Notice that we did override SOME of the package versions. However, other exported packages didn't get overridden and instead inherited the package versions from the EclipseLink bundles.

**Comment by jgrassel** [comment]
Hey, Will, can this issue be considered resolved, given the changes we made to Eclipselink 3.0's bnd.bnd file?

**Comment by dazey3** [comment]
I think this issue is resolved. We currently override all the package versions with the same version value: `3.0.0`. This should be sufficient.
