### ISSUE TITLE
featureUtility doesn't work with ShowCodeDetailsInExceptionMessages enabled

### ISSUE THREAD

**Issue by Thihup** [OpenLiberty/open-liberty#13142]
**Describe the bug**
Running the featureUtility with ShowCodeDetailsInExceptionMessages causes the process to fail

**Steps to Reproduce**
`JVM_ARGS="-XX:+ShowCodeDetailsInExceptionMessages" ./featureUtility installServerFeatures defaultServer`

**Expected behavior**
Work the same way it does with the ShowCodeDetailsInExceptionMessages disabled

**Diagnostic information:**
 - OpenLiberty Version: 19.0.0.7
 - Java Version OpenJ9: 
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.21.0, JRE 14 Linux amd64-64-Bit Compressed References 20200715_149 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - 1d231bd6a2 based on jdk-14.0.2+12)
 - Java Version HotSpot: 
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)

**Additional context**
The OpenJ9 JVM 0.21 enabled this feature by default, while Hotspot JDK 14 didn't enable it yet. So it fails on OpenJ9 JVM while in Hotspot not.
However, in JDK 15, this flag will be enabled by default in JDK 15 [1], thus failing too.
Disabling this flag in OpenJ9 JVM, the process works fine.

HotSpot flag enabled output:
```
Initializing ...
Resolving remote features. This process might take several minutes to complete.
Preparing assets for installation. This process might take several minutes to complete.
Cannot invoke "Object.equals(Object)" because the return value of "java.util.Map.get(Object)" is null
```

OpenJ9 output:
```
Initializing ...
Resolving remote features. This process might take several minutes to complete.
Preparing assets for installation. This process might take several minutes to complete.
Cannot invoke "java/lang/Object.equals(Ljava/lang/Object;)Z"

```

1. http://jdk.java.net/15/release-notes#JDK-8233014

**Comment by Thihup** [comment]
Running with JDK 15 requires to disable this flag:
`JVM_ARGS="-XX:+ShowCodeDetailsInExceptionMessages" ./featureUtility installServerFeatures defaultServer`

**Comment by bensonlatibm** [comment]
Should be fixed via https://github.com/OpenLiberty/open-liberty/issues/13926
