### ISSUE TITLE
Rename com.ibm.websphere.appserver.thirdparty.eclipselink.3.0

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#13152]
`com.ibm.websphere.appserver.thirdparty.eclipselink.3.0` should have been named `io.openliberty…`

My preference would be `io.openliberty.jpa.3.0.thirdparty`. I prefer that pattern since it lets you update the eclipselink version internally (for upstream bug fixes etc) without having to rename projects and bundles.

**Comment by jgrassel** [comment]
Delivered with https://github.com/OpenLiberty/open-liberty/pull/15683
