### ISSUE TITLE
Fix eclipselink artifact coordinates in bnd files

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/open-liberty#13156]
**Describe the bug**
The thirdparty eclipselink projects have issues finding their dependencies saying that they are not found.  It was found out that the issue here is that the artifacts are not in GAV format.  They are only in AV format.  The bnd files for all three thirdparty eclipselink projects should be updated to be in GAV format in both the Include-Resources and buildpath sections of the bnd files.

**Steps to Reproduce**
Pull in eclipselink thirdparty 3.0 project into eclipse.  It won't compile without a lot of effort and retrying many things.  This has happened in the past with the 2.6 and 2.7 projects whenever bringing in new versions.

**Expected behavior**
Eclipse is able to build all of open liberty without lots of work arounds to get things working.

**Comment by jgrassel** [comment]
Delivered with #14333
