### ISSUE TITLE
Enable JakartaEE 9 audit fat tests in com.ibm.ws.webcontainer.security.jacc.1.5_fat

### ISSUE THREAD

**Issue by jvanhill** [OpenLiberty/open-liberty#13160]
The audit fats in `com.ibm.ws.webcontainer.security.jacc.1.5_fat` were disabled for the Jakarta EE 9 repeat. When `audit-1.0` (or 2.0) has been migrated for Jakarta EE 9, these tests should be re-enabled.

**Comment by jvanhill** [comment]
@kristip17 - You can close this one if you have enabled this FATs with your audit work.

**Comment by kristip17** [comment]
This was done under #14179
