### ISSUE TITLE
Consolidate multiple versions of slf4j-simple

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#13184]
```
org.slf4j:slf4j-simple:1.7.25
org.slf4j:slf4j-simple:1.7.26
org.slf4j:slf4j-simple:1.7.28
```

Tom suggested to move all references to the latest level here per the review of PR #13169

**Comment by Yushan-Lin** [comment]
latest version of slf4j-simple:1.7.30

**Comment by Yushan-Lin** [comment]
uploaded to Artifactory: https://na.artifactory.swg-devops.com/artifactory/webapp/#/artifacts/browse/simple/General/wasliberty-open-liberty/org/slf4j/slf4j-simple/1.7.30/slf4j-simple-1.7.30.jar
