### ISSUE TITLE
Update build to not depend on Nashorn scripting engine

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#13192]
In Java 15 the Nashorn script engine is removed. This isn't an issue for any of our product or test code, but is used in a few places for our build infrastructure where we use Ant.  

For example, in `fattest.simplicity/auotFVT-defaults/src/ant/launch.xml` we have:
```xml
		<script language="javascript">
			<![CDATA[
			var minTestJava = project.getProperty("fat.minimum.java.level");
			var javaVersion = parseFloat(project.getProperty("java.specification.version"));
			if(minTestJava != null && javaVersion < parseFloat(minTestJava))
				project.setProperty("skip.java.level", true);
        ]]>
		</script>
```

We have 2 options for the script blocks:
A. Translate the `<script>` blocks in to "pure ant" scripting so there is no sub-script
B. Check-in the nashorn.jar from JDK 8 and add it to the script classpath (may be legal implications here)

**Comment by gjwatts** [comment]
We went with option B and have all the necessary files updated.
