### ISSUE TITLE
CDI 2.0 configuration

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#1321]
In CDI spec, it requires the implementation to provide a way to disable implicit bean archive scanning. In CDI 1.2, we have the following configuration in server.xml.

```xml
<cdi12 enableImplicitBeanArchives="false" />
```

In CDI 2.0
I propose to change to the following configuration
```xml
<cdi enableImplicitBeanArchives="false" />
```

However, this will lead to migration issue from the app using cdi-1.2 feature to cdi-2.0 feature. The ideal way will be no migration and there is no version indication and it works for the future CDI versions.

**Comment by Emily-Jiang** [comment]
I have been thinking about this after the design call. How about the following suggestion:
1. use system property com.ibm.ws.cdi.enableImplicitBeanArchives from CDI 2.0 and onwards.

Actually, in tWAS, we use this property to disable implicit bean archive scanning. I think this is cleaner as we took completely different route as cdi 1.2, so this is no confusion. We can also remove the migration issue cleanly by doing this:

Read the system property first

-  if it is set, use its value regardless.

- if it is not set, check the <cdi12 ...>, if it is set, use its value.

**Comment by NottyCode** [comment]
Using JVM System properties over server.xml configuration violates the Liberty design principles.

**Comment by Emily-Jiang** [comment]
will environment variables be an option?

**Comment by Emily-Jiang** [comment]
The other option is to read server.xml first and then look at JVM system properties.

**Comment by NottyCode** [comment]
Decision is to stick with cdi12 and update the element name and description to indicate that it is applicable to cdi-1.2 or newer features.

**Comment by Emily-Jiang** [comment]
https://github.com/OpenLiberty/open-liberty/issues/1870 will implement this design decision.
