### ISSUE TITLE
Does bootstrap.properties possible to read environment variable?

### ISSUE THREAD

**Issue by kencytbb** [OpenLiberty/open-liberty#13248]
Hi everyone I would like to use configmap to override some configuration in bootstrap.properties file
For example in the bootstrap.properties file I have 1 property:

`clientRequest=http://localhost:9080/api/`

I've created a environment variable in docker file:

ENV API_HOST http://localhost:9080

And I would like to change the value of property in bootstrap.properties like this:

`clientRequest=${env.API_HOST}/api/`

but it does not work.

How can I configure the value in bootstrap.properties as I expect?

**Comment by aguibert** [comment]
It's not possible to have variables in the bootstrap.properties, but instead you can set the variables in other ways.

There are several different sources that config variables can come from. The priority goes:

1. The value in the `<variable value="…​"/>` attribute in server.xml
2. Java system properties (i.e. jvm.options)
3. bootstrap.properties
4. environment variables
5. The value in the `<variable defaultValue="…​"/>` attribute in server.xml

So I would suggest doing a combination of option (5) and (4). \
So you could have this in server.xml:

```xml
<variable name="API_HOST" defaultValue="http://localhost:9080"/>

<variable name="clientRequest value="${API_HOST}/api/"/>
```

then, when you need to override this in docker with environment variables you can do something like:
`-e API_HOST=http://myhost.com:9088`

-----

If you don't need to have the values available in server.xml, a simpler approach would be to use MP Config in your application code like this:

```java
@Inject
@ConfigProperty(name = "API_HOST", defaultValue = "http://localhost:9080")
String apiHost;
```

which could also be overridden in the same way using environment variables at docker runtime.

**Comment by kencytbb** [comment]
> It's not possible to have variables in values for bootstrap.properties, but instead you can set the variables in other ways.
> 
> There are several different sources that config variables can come from. The priority goes:
> 
> 1. The value in the `<variable value="…​"/>` attribute in server.xml
> 2. Java system properties (i.e. jvm.options)
> 3. bootstrap.properties
> 4. environment variables
> 5. The value in the `<variable defaultValue="…​"/>` attribute in server.xml
> 
> So I would suggest doing a combination of option (5) and (4).
> So you could have this in server.xml:
> 
> ```
> <variable name="API_HOST" defaultValue="http://localhost:9080"/>
> 
> <variable name="clientRequest value="${API_HOST}/api/"/>
> ```
> 
> then, when you need to override this in docker with environment variables you can do something like:
> `-e API_HOST=http://myhost.com:9088`
> 
> If you don't need to have the values available in server.xml, a simpler approach would be to use MP Config in your application code like this:
> 
> ```java
> @Inject
> @ConfigProperty(name = "API_HOST", defaultValue = "http://localhost:9080")
> String apiHost;
> ```
> 
> which could also be overridden in the same way using environment variables at docker runtime.

Hi aguibert,
Thank you for quick reply, I'm using MP as well, in my case I would like to use environment variable for rest client of MP is it possible?
For example: 

`personKey/mp-rest/url=${env.PERSON_HOST}/api`

For you Suggestion to use (5) and (4) options, but the declare is variable, it does not system property because I use System.getProperty("systemProperty"). 
And for system configure should I put all system property or MP Config/ Rest client config in server.xml file? Because I think server.xml contain many things.

**Comment by aguibert** [comment]
if you define `personKey/mp-rest/url=${env.PERSON_HOST}/api` in a server.xml `<variable>` that should work

**Comment by kencytbb** [comment]
> if you define `personKey/mp-rest/url=${env.PERSON_HOST}/api` in a server.xml `<variable>` that should work

In case I would define it as <property> or system property in server.xml does is possible to do that @aguibert ?

**Comment by kencytbb** [comment]
For the rest client of MP 
I go with this solution:
`<webApplication contextRoot="e-commerce" id="e-commerce" location="e-commerce.war">
		<classloader commonLibraryRef="hibernate"/>
		<appProperties>
			<property name="person/mp-rest/url" value="${env.PERSON_HOST}/api"/>			
		</appProperties>
	</webApplication>
`

**Comment by kencytbb** [comment]
Hi @aguibert  do you have any idea to config system property in server.xml file?
As Wildfly server it has tag <system-properties> inside the standalone.xml file. So I wonder could we config system property in server.xml file? Because I would like to override some system property in different environment.

**Comment by aguibert** [comment]
Similar to how you can set ENV variables in the `${server.config.dir}/server.env` file, you can set JVM system properties in the `${server.config.dir}/jvm.options` file. See documentation here: https://openliberty.io/docs/20.0.0.8/reference/config/serverConfiguration.html#jvm-options

**Comment by kencytbb** [comment]
Hi @aguibert thank you for your comment, but I would like to define a system property or environment variable inside the server.xml because it is xml file so that I can use ${} syntax to override some properties. Do we have any options to do that?

**Comment by aguibert** [comment]
Correct, since jvm.options and server.env do not support variable substitution, you will have to look for some other ways to get these configuration values to your application. The `<variable>` element in server.xml seems like the ideal way to do this because it goes in server.xml, supports variable substitution, and can be changed while the server is running if needed. 
If the value you are setting isn't required to be a particular type of property (e.g. ENV var or JVM system property), then the `<variable>` route should be sufficient, because you can still obtain the value in your application using one of the `mpConfig` features and MP Config API

**Comment by kencytbb** [comment]
> Correct, since jvm.options and server.env do not support variable substitution, you will have to look for some other ways to get these configuration values to your application. The `<variable>` element in server.xml seems like the ideal way to do this because it goes in server.xml, supports variable substitution, and can be changed while the server is running if needed.
> If the value you are setting isn't required to be a particular type of property (e.g. ENV var or JVM system property), then the `<variable>` route should be sufficient, because you can still obtain the value in your application using one of the `mpConfig` features and MP Config API

Thank you, maybe I need to find the way to adapt with my application because my application depend on the others so the others use system.getproperty that is reason why I need config the system property can read ENV Variable.
