### ISSUE TITLE
Create microProfile-4.0 convenience feature

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#13278]
The new feature should include

mpOpenAPI-2.0
mpRestClient-2.0
mpMetrics-3.0
mpConfig-2.0
mpFaultTolerance-3.0
mpJWT-1.2
mpHealth-3.0
mpOpenTracing-2.0

servlet-4.0
javax.annotation-1.3 (private API - is this needed to be listed here?)
cdi-2.0
jaxrs-2.1
jaxrsClient-2.1
jsonb-1.0
jsonp-1.1

**Comment by Emily-Jiang** [comment]
mpJWT-1.2
