### ISSUE TITLE
Add ability to output 'effective server.xml'

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/open-liberty#13296]
**Is your feature request related to a problem? Please describe.**
See https://cloud-platform.ideas.ibm.com/ideas/TWAS-I-248
The above RFE is considered useful and has been requested by multiple customers.

**Describe the solution you'd like**
The ability to output the effective server.xml - the server configuration once all sources of configuration have been merged (similar to maven's concept of an effective pom).  This could be an option on the server command, for example.

**Describe alternatives you've considered**
No alternatives considered. 

**Additional context**
None

**Comment by h-hub** [comment]
@gcharters since this is labeled as a ```good first issue``` I'm thinking of giving it a try. May I start working on this ?

**Comment by gcharters** [comment]
@h-hub so sorry I missed your comment.  If you still have the time, by all means, yes, please do give it a try.

**Comment by samwatibm** [comment]
RFE's have moved: https://cloud-platform.ideas.aha.io/ideas/TWAS-I-248

**Comment by brenthdaniel** [comment]
We also discussed this in a design issue ( https://github.com/OpenLiberty/open-liberty/issues/10883 ) a while back. At the time most people felt like the REST config API was a more effective way to see "in use" config than an XML document with everything in it.

**Comment by lauracowen** [comment]
Would it be useful then for us to document this use of the REST config API in the OL docs? /cc @dmuelle

**Comment by cbridgha** [comment]
Closing at this time - Outlook for resources and priority is too low to justify keeping open
