### ISSUE TITLE
Microprofile GraphQL Performance Regression

### ISSUE THREAD

**Issue by jdmcclur** [OpenLiberty/open-liberty#13301]
We have a MPGraphQL regression in 20.0.0.9. I see a new builder factory being created.
```
  Parent      0   0.00  17.10           0         430    J:io/smallrye/graphql/execution/context/SmallRyeContext.<init>(Ljavax/json/JsonObject;)V
    Self      0   0.00  17.10           0         430    J:javax/json/Json.createBuilderFactory(Ljava/util/Map;)Ljavax/json/JsonBuilderFactory;
   Child      0   0.00  17.10           0         430    J:javax/json/spi/JsonProvider.provider()Ljavax/json/spi/JsonProvider;
 ```

This looks to be a new class: https://github.com/smallrye/smallrye-graphql/blob/master/server/implementation/src/main/java/io/smallrye/graphql/execution/context/SmallRyeContext.java 

Need a cache fix like:  https://github.com/smallrye/smallrye-graphql/pull/186

**Comment by jhanders34** [comment]
#regression

**Comment by phillip-kruger** [comment]
The context is per request, so will be recreate per request, not sure if cache will work here

**Comment by jhanders34** [comment]
We are currently testing a fix from Andy that changes:
```
    private final JsonBuilderFactory jsonbuilder = Json.createBuilderFactory(null);
```
to:

```
    private static final JsonBuilderFactory jsonbuilder = Json.createBuilderFactory(null);
```

Just making the JsonBuilderFactory reference static so not creating it each time.

**Comment by phillip-kruger** [comment]
Ok sure that should be fine, I thought you want to cache the whole context object. Thanks for explaining

**Comment by jhanders34** [comment]
I guess should have referenced smallrye/smallrye-graphql#179 since that is where we added the static final reference to the Reader and Object factory.

**Comment by jdmcclur** [comment]
Phillip, I think we can make the ObjectFactory this static: 
https://github.com/smallrye/smallrye-graphql/blob/0d9ff4e1e10baff2a1236dceddbb03bd4b567161/server/implementation/src/main/java/io/smallrye/graphql/execution/context/SmallRyeContext.java#L194
