### ISSUE TITLE
jwt-1.0 feature JwtBuilder needs ability to add headers to the token

### ISSUE THREAD

**Issue by brutif** [OpenLiberty/open-liberty#1330]
We  need to assure that when JwtBuilder creates a token  in the mp-jwt flow, "typ" is set to "JWT" in the header as required by the spec.  In the other token flows (ID), this should not occur as it would be a behavior change. 

The JwtBuilder builder Java api needs a to be improved so headers can be added to the token.  (currently JwtSigner adds only the "alg" key to the header when a token is created)  If you want to create an mp-jwt token using the builder api, there's no way to get the required "typ" attribute into the header. 

If we wanted to get fancy, we could optionally enhance the metatype so headers can be specified in there, similar to the way claims are specified today.

**Comment by brutif** [comment]
I'm leaning towards NOT overengineering this thing, just make a simple change so that if we are creating a JWT token, add the missing header, don't add support for arbitrary headers as that wasn't the problem.

**Comment by brutif** [comment]
#link 1360

**Comment by brutif** [comment]
To avoid test failures, this needs to wait until commercial liberty fat tests are updated on pull 9679

**Comment by ayoho** [comment]
Fixed by #1360
