### ISSUE TITLE
Built-in feature suggestion mechanism

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#13327]
## Problem

Often times Liberty users are not aware of the Liberty features they need to enable in their server.xml. I have seen all of the following scenarios occur when a user hits a CNFE due to not enabling enough features:
 - User adds `provided` scope umbrella dependency and wonders why they get a CNFE at runtime
 - User adds some API jar inside their app, or worse, API and an implementation of a technology already offered in a Liberty feature
 - User enables an umbrella feature like `javaee-8.0`, which may be far more than is needed, and don't know how to properly analyze what individual features are actually needed for their app

The proper way for a user to solve this problem would be for the user to look through the list of features and be able to know which API packages (e.g. `javax.persistence`) map to which feature names (e.g. `Java Persistence API`).  This may be a trivial mapping for experienced users to make, but it can be more difficult for new users.

## Proposed solution

Any time an application hits a `ClassNotFoundException` or a `NoClassDefFoundError`, we can inspect the class name that was not found and check if there is a liberty feature that offers that API. Then, we can provide an enhanced error message suggesting which Liberty feature to enable.

For example, instead of:
```
ClassNotFoundException: javax.persistence.PersistenceProvider
```
We could issue a message like:
```
CWWKL0084W: The javax.persistence.PersistenceProvider class could not be loaded. Try enabling the jpa-2.1 feature or a newer version of the feature in the server.xml file.
```

This sort of solution was already used for the Java APIs removed in Java SE 9, so we already have feature suggestions for JAX-B and JAX-WS, but we could expand this mechanism to be generic to cover all Liberty features. This may be particularly useful if we decide to rename most of the Jakarta EE 9 features from their previous basenames.

**Comment by tjwatson** [comment]
While discussing this design issue we should also consider #13393

**Comment by ggam** [comment]
Not technically related, but similar from a UX point of view: #11813

**Comment by aguibert** [comment]
good point @ggam, I know it is a long-standing design principle of Liberty to ignore any unrecognized server.xml configuration, but I agree that it can be confusing to users and would be nice if we could at least warn them the config they are trying to use requires enabling another feature.

**Comment by ggam** [comment]
You are totally right, it's a feature request and not a bug. But it's very
annoying coming from WildFly or other servers which validate schema.
Perhaps that (optional) validation would also be something to consider. It
would  definitely help newcomers.

**Comment by tevans78** [comment]
Need to decide if this should work for all features or only those that are locally installed. If it is all features then we need to generate and store some additional metadata ... a mapping from API classes to feature names.

We would like to do this but it should be placed on the backlog and prioritized.

**Comment by malincoln** [comment]
Agreement to close.
