### ISSUE TITLE
RPM based install - Log files dissappear after start

### ISSUE THREAD

**Issue by lostiniceland** [OpenLiberty/open-liberty#13342]
**Describe the bug**
We install WLP using the official RPM packages.

After starting the server, the logs are available under /var/log/openliberty/myserver, but dissappear after a couple of seconds

```
[root@xyz logs]# ll
total 52
-rw-r-----. 1 openliberty openliberty 13539 Aug  6 16:37 console.log
-rw-r-----. 1 openliberty openliberty 30861 Aug  6 16:37 messages.log
drwxr-x---. 2 openliberty openliberty  4096 Aug  6 16:37 state
[root@xyz logs]# ll
total 4
drwxr-x---. 2 openliberty openliberty 4096 Aug  6 16:37 state
```

**Steps to Reproduce**
Start server, watch log folder

**Expected behavior**
Logfiles are not deleted

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.7
 - Java Version: 
```
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)

```
 - server.xml 
```
<server description="myserver">

    <featureManager>
        <feature>webProfile-8.0</feature>
        <feature>mpConfig-1.4</feature>
        <feature>mpHealth-2.2</feature>
        <feature>ssl-1.0</feature>
        <feature>jaxws-2.2</feature>
        <feature>jaxb-2.2</feature>
      </featureManager>

  <httpEndpoint id="defaultHttpEndpoint"
  host="*"
  httpPort="8080"
  httpsPort="8443"/>

    <logging consoleFormat="simple" consoleLogLevel="INFO" messageFormat="json" messageSource="message,trace,accessLog,ffdc,audit"/>
</server>
```

I am not seeing this behaviour on my local desktop, so I guess it is related to the RPM install

**Comment by bensonlatibm** [comment]
I can't seem to reproduce this issue on my system.

Can you provide some more details, please?
1. What version of the OS are you using?
2. How did you create the server 'myserver'?
3. What command are you using to start the server?

Log locations are determined by the LOG_DIR variable.  That should be set in the server.env file for Openliberty or within the server itself.
Can you attach the contents of myserver's server.env?  (eg. /var/lib/openliberty/usr/servers/myserver/server.env)
and also the contents of /opt/ol/etc/server.env?

**Comment by lostiniceland** [comment]
Just tried some more investigation and as it turns out, the team managed to hide some stupid logic which really deleted the log-files on first invocation!!!!
Sorry to have wasted your time.
