### ISSUE TITLE
If the include in the server.xml is not available the server (application) ist still starting

### ISSUE THREAD

**Issue by c-koell** [OpenLiberty/open-liberty#13371]
**Describe the bug**
We include a static external server.xml file into the main server.xml file.
```
<server>
   	<featureManager>
        ....
	<include location="http://internal.com/files/dummy/server.xml" optional="false"/>
</server>
```
If the server is starting the first time and the external resource is available it will be read and all works fine. 
On subsequent server restarts it could happen that the external resource is unavailable (http status 404 or 500) and the server logs that the include is not availabe but it starts the application..
Only following message will be logged.
```
[07.08.20, 10:57:49:088 MESZ] 00000017 com.ibm.ws.config.xml.internal.XMLConfigParser               E CWWKG0014E: Der Konfigurationsparser hat einen XML-Syntaxfehler beim Parsing des Konfigurationsstamms und der referenzierten Konfigurationsdokumente gefunden. Fehler: Elementtyp "META" muss mit dem entsprechenden Endtag "</META>" beendet werden. Datei: http://internal.com/files/dummy/server.xml Zeile: 1 Spalte: 140
```
**Expected behavior**
I think the server (application) should not start  if the external resource is not available. I have tried to start the server the first time with the external resource unavailable and then the server does not start the application.
All subsequent server restarts with a working external resource will also fail until i clear the workarea folder.
Is there a caching functionality that i have to disable ?

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.8
 - Java Version: OpenJDK Runtime Environment (11.0.7+10)

**Comment by brenthdaniel** [comment]
It looks like the request is getting a response back, but it isn't in the form that the configuration parser expects. Do you know what the actual response is? Is there a last-modified header being sent?

**Comment by c-koell** [comment]
You are right. 

In my test i have changed the include url on second startup to to a path that does not exist on the server. The server returns a error page with http status 404, but the application is starting

The other way around ... if i start the server the first time with a invalid url (error page wih http status 404) the application is not starting. On second startup and valid include the application is still not starting.
After clearing the workarea folder the application startsup .

I'm afraid we don't send a last-modified header on a valid response. but i will check that ...

**Comment by brenthdaniel** [comment]
It's fine to not have a last-modified header. I would expect that if there isn't one, we would attempt to reload the file every time. I think it's possible that the error page could be sending the same last-modified value for each request so we assume that it doesn't need to be updated. That's just a guess, though, I haven't tried to reproduce it. It's also possible that we just aren't handling remote resources correctly when we decide whether to use cached configuration.

**Comment by c-koell** [comment]
Are there any news here ?

**Comment by brenthdaniel** [comment]
Hi, 
I would still like to get more information on your specific scenario. I have found a couple of issues here, but I don't think either one is related to what you're experiencing. 

I've found that:
1) When onERROR is set to FAIL in bootstrap.properties, the server is not shutting down when a remote, non-optional include fails to resolve at startup. 
2) Completely unrelated, but there's a timing error in configuration startup that can lead to an NPE. Somehow the tests I was running made this almost guaranteed. 

What *may* be happening in your case is that the server you're connecting to is sending back an error page with a 'last modified' header. We will use that header to determine if the remote resource has changed or not. If no header is sent back, we set the last modified value to the current system time (which would result in an update.) If a header is sent and the value is from before the last configuration update timestamp, we will not update the configuration. 

Another possibility is that the remote resource is only temporarily unavailable. We have some retry logic in the configuration loading code that will make another attempt to load a resource if it fails. You would still see the parser error, but the configuration would be successfully loaded on the second attempt.

**Comment by brenthdaniel** [comment]
I fixed the two problems I mentioned above in #13961

**Comment by c-koell** [comment]
Hi thanks for your update !

I will test our scenario again with a valid "last modified" header. I will inform you once i have tested it.

greets
claus

**Comment by c-koell** [comment]
Hi again !

I have found some time to test with the current 20.0.0.11 version.

I have splitted my tests into two scenarios.

1. Changing the content in the included file and check if it will be refreshed on server (re-)start
   Now we send a valid last-modified header and everything works fine. The local cached file in the workarea folder will be refreshed if a newer last-modified header will be send.

2. Invalid include URL
   If i try to something like
   ````
   <server>
      ...
      <include location="http://no.valid.host.com/files/dummy/server.xml" optional="false"/>
    </server>
   ````
   the server ist still starting. We see following error on startup but as sayed the server is still starting
   ``
   [29.10.20, 12:46:37:439 MEZ] 00000016 com.ibm.ws.config.xml.internal.XMLConfigParser               E CWWKG0090E: Die Konfigurationsressource http://no.valid.host.com/files/dummy/server.xml ist nicht vorhanden oder kann nicht gelesen werden. 
   ``

What do you mean with "When onERROR is set to FAIL in bootstrap.properties" ? How can i set that config property ?

**Comment by brenthdaniel** [comment]
Hi, 
Create the file 'bootstrap.properties' in the same directory as server.xml (if it doesn't already exist) and add the following line:
`onError=FAIL`

The variable has to be set in bootstrap.properties instead of server.xml because otherwise it would not take effect until after server.xml was parsed. When it is set to 'FAIL', configuration parsing errors will cause the server to exit. The default is WARN, which will cause errors to be reported but will not prevent the server from starting.

**Comment by c-koell** [comment]
That works fine !

Thank you @brenthdaniel for the hint regarding the variable !
