### ISSUE TITLE
Unhandled Exception, Bus Error when we try to start the liberty server

### ISSUE THREAD

**Issue by posriniv** [OpenLiberty/open-liberty#13389]
**Describe the bug**
The websphere liberty server crashes when run as a container on Redhat Openshift Container Platform 4.4 with the following error logs:
[platform-auth-service.log](https://github.com/OpenLiberty/open-liberty/files/5050418/platform-auth-service.log)

**Steps to Reproduce**
If we run any command on the container like `java -version`, `keytool` or try to start the liberty server, we see this bus error

**Expected behavior**
The liberty should startup without any errors.

**Diagnostic information:**
 - OpenLiberty Version: We see this with 19.0.0.11 and 20.0.0.5 on a particular system
 - Java Version: IBM JAVA 1.8.0_sr6fp10 and  IBM JAVA 1.8.0_sr6fp5
 - server.xml configuration: 
[server.xml](https://github.com/OpenLiberty/open-liberty/files/5050400/server-xml.txt)

 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log` - We didn't see any logs in messages.log

**Additional context**
 - We see the following javacore and Snap files being written onto the container file system:
[javacore.tar.gz](https://github.com/OpenLiberty/open-liberty/files/5050439/javacore.tar.gz)
[snap.tar.gz](https://github.com/OpenLiberty/open-liberty/files/5050420/snap.tar.gz)

**Comment by bpaskin-ibm** [comment]
This appears to be an issue with the JRE, not Liberty itself.  You are using the latest JRE released on 4 August.  Can you try using the previous JRE or a slightly older version and see if it cleared?

**Comment by posriniv** [comment]
@bpaskin-ibm We actually used olders JREs
```
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 8.0.6.10 - pxa6480sr6fp10-20200408_01(SR6 FP10))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200402_443261 (JIT enabled, AOT enabled)
OpenJ9   - 35ef566
OMR      - 4bca4f4
IBM      - 55acf4a)
JCL - 20200407_01 based on Oracle jdk8u251-b08
```
and 
```
bash-4.4$ java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 8.0.6.5 - pxa6480sr6fp5-20200111_02(SR6 FP5))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200108_436782 (JIT enabled, AOT enabled)
OpenJ9   - 7d1059c
OMR      - d059105
IBM      - c8aee39)
JCL - 20200110_01 based on Oracle jdk8u241-b07
```
These didn't work.

**Comment by bpaskin-ibm** [comment]
You mentioned that you could not do a `java -version` from within the container.  Are you able to do that with these versions?  If so, what error are you now receiving with Liberty when you start?

**Comment by alexandrakisin** [comment]
I copied the java folder from the container to my node :
```
kubectl cp  auth-idp-pbssg:/opt/ibm/java -n kube-system -c platform-auth-service /root/java
```
And then run java -version command from copied directory (/root/java/jre/bin) :
```
[root@proxy bin]# ./java -version
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 8.0.5.41 - pxa6480sr5fp41-20190919_01(SR5 FP41))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190911_427071 (JIT enabled, AOT enabled)
OpenJ9   - d581d49
OMR      - ca4db84
IBM      - 5cfdf9c)
JCL - 20190918_01 based on Oracle jdk8u221-b11
```

**Comment by bpaskin-ibm** [comment]
Ok, so what error are you receiving when starting Liberty now since the `-java version` issue is not happening?  You should not run Liberty or Java as root in the container.  This can cause some issues.  I usually recommend that the `java` dir is placed under the `/liberty` directory and then set the env variable `JAVA_HOME=/liberty/java/jre`.

**Comment by alexandrakisin** [comment]
`java --version` is not working on the container. I run it outside from the container by copying the java folder to external server. 
if you run `java -verison` inside the container you get an exception:
```bash-4.4$ java -version
Unhandled exception
Type=Bus error vmState=0x00000000
J9Generic_Signal_Number=00000028 Signal_Number=00000007 Error_Value=00000000 Signal_Code=00000002
Handler1=00007F9A23CFE650 Handler2=00007F9A235E3670 InaccessibleAddress=00007F99C0000000
RDI=00007F9A24097060 RSI=0000000000000008 RAX=00007F9A24097380 RBX=00007F9A24097060
RCX=00007F9A2400B650 RDX=0000000000000000 R8=0000000000000000 R9=0000000000000003
R10=00007F9A240008D0 R11=0000000000000160 R12=00007F9A24097060 R13=00007F99C0000000
R14=0000000000000001 R15=0000000000000080
RIP=00007F9A21C9E31B GS=0000 FS=0000 RSP=00007F9A28CEC470
EFlags=0000000000010202 CS=0033 RBP=00007F99C0000000 ERR=0000000000000006
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=00007F99C0000000
xmm0 0000003000000020 (f: 32.000000, d: 1.018558e-312)
xmm1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm2 ffffffff00000002 (f: 2.000000, d: -nan)
xmm3 4059000000000000 (f: 0.000000, d: 1.000000e+02)
xmm4 67726f5f0a353931 (f: 171260208.000000, d: 2.053437e+190)
xmm5 2e796e6f6d726168 (f: 1836212608.000000, d: 8.181846e-85)
xmm6 dddddd000a62696c (f: 174221680.000000, d: -1.456651e+144)
xmm7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm8 00007f9a22947cea (f: 580156672.000000, d: 6.931740e-310)
....
```

**Comment by paulcheeseman** [comment]
The javacores show that the crash happened with IBM Java 8.0.5.41, which is only supported for up to RHEL 8.0.

**Comment by bpaskin-ibm** [comment]
As mentioned the crashes are happening with an older version of the JRE.  Can you try with 8.0.6.10?

Version [support](https://www.ibm.com/support/knowledgecenter/en/SSYKE2_8.0.0/com.ibm.java.80.doc/user/supported_env_80.html#supported_env_80__linux).

**Comment by alexandrakisin** [comment]
I did the following :
- Download java - ibm-java-jre-8.0-6.15-linux-x86_64.tgz file 

- Copy this file to the container with the command :
`kubectl cp ibm-java-jre-8.0-6.15-linux-x86_64.tgz auth-idp-pbssg:/tmp -n kube-system -c platform-auth-service`

- Then attached to the container and untar the file and then tried to run the new java and got the same error
```
oc exec -it auth-idp-pbssg -c platform-auth-service bash
cd /opt/ibm
tar xvzf /tmp/ibm-java-jre-8.0-6.15-linux-x86_64.tgz
cd /opt/ibm/ibm-java-x86_64-80/jre/bin
JAVA_HOME=/opt/ibm/ibm-java-x86_64-80/jre/


./java -version
Unhandled exception
Type=Bus error vmState=0x00000000
J9Generic_Signal_Number=00000028 Signal_Number=00000007 Error_Value=00000000 Signal_Code=00000002
Handler1=00007FDC11C26F70 Handler2=00007FDC11515C10 InaccessibleAddress=00007FDBC0000000
RDI=00007FDC0C08C5F0 RSI=0000000000000008 RAX=00007FDC0C096CB0 RBX=00007FDC0C08C5F0
RCX=00007FDC0C00AA90 RDX=0000000000000000 R8=0000000000000000 R9=0000000000000003
R10=00007FDC0C0008D0 R11=0000000000000160 R12=00007FDC0C08C5F0 R13=00007FDBC0000000
R14=0000000000000001 R15=0000000000000080
RIP=00007FDC0B56D79B GS=0000 FS=0000 RSP=00007FDC12B5F4A0
EFlags=0000000000010202 CS=0033 RBP=00007FDBC0000000 ERR=0000000000000006
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=00007FDBC0000000
xmm0 0000003000000020 (f: 32.000000, d: 1.018558e-312)
xmm1 00000000000000ff (f: 255.000000, d: 1.259867e-321)
xmm2 ffffffff00000002 (f: 2.000000, d: -nan)
xmm3 4059000000000000 (f: 0.000000, d: 1.000000e+02)
xmm4 6176616a2e6e7573 (f: 778990976.000000, d: 3.146502e+161)
xmm5 54535f4e55533d72 (f: 1431518592.000000, d: 1.655158e+98)
xmm6 76616a2e6e757344 (f: 1853191040.000000, d: 1.713657e+262)
xmm7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm8 dd006b6f6f68396a (f: 1869101440.000000, d: -9.776703e+139)
xmm9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm11 0000000049d70a38 (f: 1238829568.000000, d: 6.120632e-315)
xmm12 000000004689a022 (f: 1183424512.000000, d: 5.846894e-315)
xmm13 0000000047ac082f (f: 1202456576.000000, d: 5.940925e-315)
xmm14 0000000048650dc0 (f: 1214582272.000000, d: 6.000833e-315)
xmm15 0000000046b73e38 (f: 1186414080.000000, d: 5.861665e-315)
Module=/opt/ibm/ibm-java-x86_64-80/jre/lib/amd64/compressedrefs/libj9jit29.so
Module_base_address=00007FDC0B30D000
Target=2_90_20200724_452227 (Linux 4.18.0-147.20.1.el8_1.x86_64)
CPU=amd64 (16 logical CPUs) (0xbca239000 RAM)
----------- Stack Backtrace -----------
(0x00007FDC0B56D79B [libj9jit29.so+0x26079b])
(0x00007FDC0B56DAEB [libj9jit29.so+0x260aeb])
(0x00007FDC0B462367 [libj9jit29.so+0x155367])
J9VMDllMain+0xb44 (0x00007FDC0B4504C4 [libj9jit29.so+0x1434c4])
(0x00007FDC11C39231 [libj9vm29.so+0xa6231])
(0x00007FDC11CD0280 [libj9vm29.so+0x13d280])
(0x00007FDC11BA4D74 [libj9vm29.so+0x11d74])
(0x00007FDC11C41A0F [libj9vm29.so+0xaea0f])
(0x00007FDC11516973 [libj9prt29.so+0x1c973])
(0x00007FDC11C3BBDD [libj9vm29.so+0xa8bdd])
J9_CreateJavaVM+0x75 (0x00007FDC11C31D65 [libj9vm29.so+0x9ed65])
(0x00007FDC12135285 [libjvm.so+0x12285])
JNI_CreateJavaVM+0xa82 (0x00007FDC12EEEB02 [libjvm.so+0xab02])
(0x00007FDC138D4A84 [libjli.so+0xfa84])
(0x00007FDC13AEF2DE [libpthread.so.0+0x82de])
clone+0x43 (0x00007FDC133FA133 [libc.so.6+0xfc133])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2020/08/10 21:21:34 - please wait.
JVMDUMP032I JVM requested System dump using '/opt/ibm/ibm-java-x86_64-80/jre/bin/core.20200810.212134.242.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/lib/systemd/systemd-coredump %P %u %g %s %c %h" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.245.
JVMDUMP012E Error in System dump: The core file created by child process with pid = 245 was not found. Expected to find core file with name "/opt/ibm/ibm-java-x86_64-80/jre/bin/core.245"
JVMDUMP032I JVM requested Java dump using '/opt/ibm/ibm-java-x86_64-80/jre/bin/javacore.20200810.212134.242.0002.txt' in response to an event
JVMDUMP012E Error in Java dump: /opt/ibm/ibm-java-x86_64-80/jre/bin/javacore.20200810.212134.242.0002.txt
JVMDUMP032I JVM requested Snap dump using '/opt/ibm/ibm-java-x86_64-80/jre/bin/Snap.20200810.212134.242.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /opt/ibm/ibm-java-x86_64-80/jre/bin/Snap.20200810.212134.242.0003.trc
JVMDUMP032I JVM requested JIT dump using '/opt/ibm/ibm-java-x86_64-80/jre/bin/jitdump.20200810.212134.242.0004.dmp' in response to an event
JVMDUMP013I Processed dump event "gpf", detail "".
```

**Comment by bpaskin-ibm** [comment]
Hi, I have this version of Java running successfully in an OCP container with RHEL 8.2.  I suggest you open a support ticket with IBM to help you debug your Java issue as this is not an OpenLiberty issue.

**Comment by alexandrakisin** [comment]
Can you send me the link please where I can open a support ticket

**Comment by bpaskin-ibm** [comment]
Sure: https://www.ibm.com/mysupport .

**Comment by paulcheeseman** [comment]
Looks like it's crashing while trying to allocate the JIT code cache. Here are the symbols for top few frames of the backtrace above:

```
(0x00007FDC0B56D79B [libj9jit29.so+0x26079b])                     -->    OMR::CodeCacheManager::allocateCodeCacheRepository()
(0x00007FDC0B56DAEB [libj9jit29.so+0x260aeb])                     -->    OMR::CodeCacheManager::initialize()
(0x00007FDC0B462367 [libj9jit29.so+0x155367])                     -->    onLoadInternal()
J9VMDllMain+0xb44 (0x00007FDC0B4504C4 [libj9jit29.so+0x1434c4])   -->    J9VMDllMain()
...                                                                      ...
```
We will need to take a look at a jextracted core file. That's best handled in the context of an IBM support case for data privacy compliance etc.

**Comment by alexandrakisin** [comment]
@paulcheeseman So what you suggest , should I open a support ticket in IBM or do you want to me to provide you with additional information ?

**Comment by paulcheeseman** [comment]
@alexandrakisin - Open a support case and you will be helped through the process to gather the data we need, including a jextracted core file (i.e. a core file that's been processed with `jre/bin/jextract`).

**Comment by alexandrakisin** [comment]
I'm opening a ticker at ibm mysupport , which type of support should I choose - product support or other support services ?

**Comment by paulcheeseman** [comment]
Product support - specifically, the IBM product with which the IBM JRE was provided.

**Comment by posriniv** [comment]
The IBM Java team fixed the problem. JVM was tried to use huge pages but operating system was not configured for that. When the huge pages were disabled  on the worker by running the command : `echo 0 >  /proc/sys/vm/nr_hugepages`, liberty started working. Closing this issue.
