### ISSUE TITLE
Update for Servlet 5 namespace

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#13449]
It looks like we need to update our DDParser to allow the 5.0 versioning, very similar to what we had to do for Servlet 4: https://github.com/OpenLiberty/open-liberty/issues/565

For example we need to add some tests or better yet try and transform our existing tests if possible to use:

`<web-app version="5.0" xmlns="https://jakarta.ee/xml/ns/jakartaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/web-app_5_0.xsd">`

Currently we get the follow exception:

> Caused by: com.ibm.ws.javaee.ddmodel.DDParser$ParseException: CWWKC2262E: The server is unable to process the 5.0 version and the https://jakarta.ee/xml/ns/jakartaee namespace in the /WEB-INF/web.xml deployment descriptor on line 20.
> 	at com.ibm.ws.javaee.ddmodel.web.WebAppDDParser.createRootParsable(WebAppDDParser.java:99)
> 	at com.ibm.ws.javaee.ddmodel.DDParser.parseRootElement(DDParser.java:578)
> 	at com.ibm.ws.javaee.ddmodel.web.WebAppDDParser.parse(WebAppDDParser.java:32)
> 	at com.ibm.ws.javaee.ddmodel.web.WebAppEntryAdapter.adapt(WebAppEntryAdapter.java:59)

**Comment by pmd1nh** [comment]
https://github.com/OpenLiberty/open-liberty/pull/13484

**Comment by pmd1nh** [comment]
Does the namespace have to be HTTPS?  <web-app version="5.0" xmlns="**https**://jakarta.ee/xml/ns/jakartaee"
