### ISSUE TITLE
Port PI91323 to liberty

### ISSUE THREAD

**Issue by benjamin-confino** [OpenLiberty/open-liberty#1352]
An injection exception is thrown if a @produces method returns a null. However dependent scoped producers are aloud to return a null.

**Comment by ewhoch** [comment]
This issue really doesn't make sense. The APAR has no context here, and the description is minimal, and nobody is assigned. Please put in some better information regarding the issue and a better summary.

**Comment by benjamin-confino** [comment]
duplicate of #1495
