### ISSUE TITLE
Eclipselink 2.6 assets not available for the public to build

### ISSUE THREAD

**Issue by jgrassel** [OpenLiberty/open-liberty#1354]
Have been observing this since Friday with building Liberty (external using Maven and DHE, not artifactory):

> Task :com.ibm.websphere.appserver.thirdparty.eclipselink:jar FAILED
warning: Unused Export-Package instructions: [org.eclipse.persistence.javax.*] 
error  : ${repo} macro refers to an artifact org.eclipse.persistence.jpa.modelgen-2.6.5.WAS-v20171212-22b68cc (EXACT) that has an error: org.eclipse.persistence.jpa.modelgen;version=2.6.5.WAS-v20171212-22b68cc Not found in [bnd-cache [/Users/arcticfox/Dev/Liberty/open-liberty/dev/cnf/cache/3.5.0/bnd-cache r/w=false], MavenBndRepository [localRepo=/Users/arcticfox/Dev/Liberty/open-liberty/dev/cnf/local, storage=Local, inited=true], MavenBndRepository [localRepo=/Users/arcticfox/Dev/Liberty/open-liberty/dev/cnf/local, storage=Release, inited=true], MavenBndRepository [localRepo=/Users/arcticfox/.m2/repository, storage=RemotePublic, inited=true], MavenBndRepository [localRepo=/Users/arcticfox/.ibmdhe/repository, storage=RemoteIBM, inited=true], MavenBndRepository [localRepo=/Users/arcticfox/.m2/repository, storage=DummyRepo, inited=true], MavenBndRepository [localRepo=/Users/arcticfox/.m2/repository, storage=RemotePublish, inited=true]]
error  : Can not find JAR file '!/!META-INF/maven/*'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':com.ibm.websphere.appserver.thirdparty.eclipselink:jar'.
> com.ibm.websphere.appserver.thirdparty.eclipselink has errors, 2 errors were reported

**Comment by dazey3** [comment]
The reason for this failure was due to an overwrite in the artifactory repository. This issue should be fixed for artifactory and DHE by #1359

**Comment by jgrassel** [comment]
Got a clean build, thanks!
