### ISSUE TITLE
MP JWT 1.2: Support accepting encrypted JWT tokens using JSON Web Encryption (JWE) and use MP Config to specify the location of the private RSA key to decrypt the content encryption key (CEK) used to decrypt the content

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/open-liberty#13575]
As a developer, I want my MP JWT endpoint to accept encrypted JWT tokens using JSON Web Encryption (JWE) and use MP Config to specify the location of the private RSA key to decrypt the content encryption key (CEK) used to decrypt the content.

**Comment by ayoho** [comment]
I believe all of the product code development is done for this support.
