### ISSUE TITLE
gRPC: issue matching client service name on fully specified target on the <grpcTarget> element 

### ISSUE THREAD

**Issue by epj** [OpenLiberty/open-liberty#13586]
While testing the hello world client, found that the fully specified service name doesn't work correctly, i.e. <grpcTarget target="helloworld.Greeter" ...  />  A wildcard target does work though.

**Comment by wtlucy** [comment]
I documented this configuration incorrectly.  Since a given `<grpcTarget/>` configuration gets applied to a `io.grpc.ManagedChannel`, then this `target` should reference a hostname rather than a service name.  It will probably make sense to rename this configuration from `target` -> `host`.
