### ISSUE TITLE
Beta Blog for 20.0.0.10 beta - Jakarta Persistence 3.0

### ISSUE THREAD

**Issue by jgrassel** [OpenLiberty/open-liberty#13595]
a. Which Liberty feature does it relate to?

   i. Human-readable name (eg WebSockets feature)
- `Jakarta Persistence 3.0`

   ii. Feature name (eg websockets-1.0)
- `jpa-3.0` and `jpaContainer-3.0`

   iii. Is this a new feature or is it an update to an existing feature for this release?
- `This is a new feature to support the Jakarta Persistence 3.0 specification.`
b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc
- `Application developers and administrators`

c. Write a sentence or two that introduces it to someone new to the general technology/concept.
- `Jakarta Persistence can be used to map Java objects with RDBMS objects, providing a means to persist new data, as well as fetch, modify, and remove existing data, from the RDBMS.`
d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)
- `Jakarta Persistence 3.0 is the first version of JPA under the Jakarta umbrella of technologies.  APIs have been repackaged to the jakarta.persistence namespace.  The jpa-3.0 feature includes Eclipselink 3.0-RC1.` 
e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.
 
f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.
- https://jakarta.ee/specifications/persistence/3.0/
- https://github.com/eclipse-ee4j/jpa-api
- https://github.com/eclipse-ee4j/eclipselink
g. Attach any images to this work item as .png files.

**Comment by jgrassel** [comment]
The changes with JPA 3.0 are largely the "Big Bang" changes of package names from`javax.persistence.*` to `jakarta.persistence.*`.  This similarly affects property names, for example `javax.persistence.lock.scope` becomes `jakarta.persistence.lock.scope`.

This also affects the schema addresses for files like `persistence.xml' and `orm.xml`.

For example, `persistence.xml` files for JPA 3.0 application should have the following format:
```
      <persistence xmlns="https://jakarta.ee/xml/ns/persistence"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://jakarta.ee/xml/ns/persistence
          https://jakarta.ee/xml/ns/persistence/persistence_3_0.xsd"
        version="3.0">
          ...
      </persistence>
```

Another example, `orm.xml` files for JPA 3.0 application should have the following format:
```
      <entity-mappings xmlns="https://jakarta.ee/xml/ns/persistence/orm"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://jakarta.ee/xml/ns/persistence/orm
          https://jakarta.ee/xml/ns/persistence/orm_3_0.xsd"
        version="3.0">
          ...
      </entity-mappings>
```

**Comment by tkburroughs** [comment]
Blogged for 20.0.0.10-beta; closing
