### ISSUE TITLE
Enable option to allow serializing access to session data

### ISSUE THREAD

**Issue by randyclee** [OpenLiberty/open-liberty#13624]
Edit the metatype.xml and metatype.properties to add allowSerializedSessionAccess, serializedSessionAccessMaxWaitTime and accessSessionOnTimeout. 

The Aha Idea is https://cloud-platform.ideas.ibm.com/ideas/TWAS-I-151

RFE 234439

**Comment by zhang-ca** [comment]
The Servlet API supports concurrent access to a session in a given server instance. WebSphere Liberty server provides an option to prevent the concurrent access to a session in a given server instance so that concurrent modification of a session does not occur in a given server instance.

**Comment by zhang-ca** [comment]
Preventing concurrent access to a session is achieved by synchronizing the requests based on session. When this option is turned on, a session is obtained for the request before invoking the servlet and requests are synchronized by locking the session for the servlet initiation time. Note that synchronization is based on the memory copy of session. So this feature cannot serialize requests across servers based on session when session affinity fails.

**Comment by zhang-ca** [comment]
https://openliberty.io/docs/21.0.0.6/reference/config/httpSession.html
