### ISSUE TITLE
el-4.0 NLS file named incorrectly

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#13622]
dev/com.ibm.websphere.appserver.features/visibility/public/el-4.0/resources/l10n/com.ibm.websphere.appserver.el-4.0.properties

should be named `io.openliberty.el-4.0.properties` to match the long feature name.

**Comment by tevans78** [comment]
servlet-5.0 is wrong too

https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.websphere.appserver.features/visibility/public/servlet-5.0/resources/l10n/com.ibm.websphere.appserver.servlet-5.0.properties

**Comment by pnicolucci** [comment]
Servlet won't change since we didn't rename the servlet long name using the `io.openliberty` prefix. Just using this to fix up the el feature files.
