### ISSUE TITLE
JSON-B transient and property annotation collide

### ISSUE THREAD

**Issue by sdaschner** [OpenLiberty/open-liberty#13640]
When mapping a class via JSON-B, and annotating fields as follows, the result throws an error because of mismatching types:

```java
public class Coffee {

    @JsonbTransient
    private Order order;

    @JsonbProperty("order")
    private URI orderLink;

    Coffee() {
        order = new Order();
        orderLink = URI.create("http://localhost/");
    }

    // getters & setters
}
```

this results in: 

```
[ERROR   ] Unable to serialize property 'order' from com.sebastian_daschner.openliberty.Coffee
[ERROR   ] Generating incomplete JSON
[ERROR   ] Problem with writing the data, class com.sebastian_daschner.openliberty.Coffee, ContentType: application/json
```

If both properties `order` and `orderLink` have the same type, it works as expected (i.e. `orderLink` is serialized as `"order"`).

However, if we annotate `@JsonbProperty` on the setter instead, it works:

```java
public class Coffee {

    @JsonbTransient
    private Order order;

    private URI orderLink;

    // [...]

    @JsonbProperty("order")
    public URI getOrderLink() {
        return orderLink;
    }

}
```

Response:

```json
{"order":"http://localhost/"}
```

There seems to be an unexpected type link of the (ignored) property with the default serialized JSON key `"order"`, and the custom name binding.

Tested with `Open Liberty 20.0.0.8/wlp-1.0.43.cl200820200721-1900 on Eclipse OpenJ9 VM, version 14+36`

**Comment by aguibert** [comment]
This issue was also raised in Quarkus so I'm just going to track it at the source in Yasson here:
https://github.com/eclipse-ee4j/yasson/issues/444
