### ISSUE TITLE
Reconsume latest MicroProfile Config 2.0 snapshot

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#13644]
https://repo1.maven.org/maven2/org/eclipse/microprofile/config/microprofile-config-api/2.0-M1/microprofile-config-api-2.0-M1.jar

If the RC1 API is available then we should use that instead

**Comment by Azquelt** [comment]
With the 2.0 M1 API + a snapshot smallrye impl, we have the following tests failing:

Config 1.2 FAT bucket FULL (from 22 tests):
- [ ] converterPrioritySPITest_CONFIG20_EE8
- [ ] optionalConverterTest_CONFIG20_EE8

Config 1.1 FAT bucket FULL (from 314 tests):
- [ ] testMethodUnnamed_CONFIG20_EE8
- [ ] testConstructorUnnamed_CONFIG20_EE8
- [ ] testNonExistantKey_CONFIG20_EE8
- [ ] testDogConverterMissing_CONFIG20_EE8
- [ ] testClassLoaderCache_CONFIG20_EE8
- [ ] testMultiApplication_CONFIG20_EE8
- [ ] testUserLoaderErrors_CONFIG20_EE8
- [ ] defaultsGetConfigPathProcEnv_CONFIG20_EE8
- [ ] defaultsMixedOrdinals_CONFIG20_EE8
- [ ] defaultsOrdinalFromSource_CONFIG20_EE8
- [ ] testLargeConfigSources_CONFIG20_EE8
- [ ] testLargeDynamicUpdates_CONFIG20_EE8

**Comment by tevans78** [comment]
The tests above have now been disabled so that we can attempt to get into the next beta. Emily and I have been through the failures and there probably isn't anything concerning/unexpected for beta level code.

**Comment by tevans78** [comment]
Using snapshot builds of the API, TCK and SmallRye Config, as of 23rd Sept, these are now the failing TCKs;
366 tests, 2 failures, 35 errors
    [ ]                                expressionMissing
    [ ]                                withoutExpansion
    [ ]                                defaultExpressionComposedEmpty
    [ ]                                escape
    [ ]                                simpleExpression
    [ ]                                composedExpressions
    [ ]                                infiniteExpansion
    [ ]                                arrayEscapes
    [ ]                                multipleExpansions
    [ ]                                noExpression
    [ ]                                escapeBraces
    [ ]                                noExpressionComposed
    [ ]                                defaultExpression
    [ ]                                defaultExpressionComposed
    [ ]                                multipleExpressions
    [ ]                                defaultExpressionEmpty
    [ ]                                testEnvironmentConfigSource
    [ ]                                testInjectedConfigSerializable
    [ ]                                testConfigProfileWithDev
    [ ]                                testConfigPropertiesPlainInjection
    [ ]                                testConfigPropertiesWithPrefix
    [ ]                                testNoConfigPropertiesAnnotationInjection
    [ ]                                testConfigPropertiesDefaultOnBean
    [ ]                                testConfigPropertiesWithoutPrefix
    [ ]                                testConfigPropertiesNoPrefixOnBeanThenSupplyPrefix
    [ ]                                testConfigPropertiesNoPrefixOnBean
    [ ]                                testConfigProfileWithDev
    [ ]                                testConfigProfileWithDev
    [ ]                                expressionNoDefault
    [ ]                                expression
    [ ]                                testConfigProfileWithDev
    [ ]                                configValueEmpty
    [ ]                                configValue
    [ ]                                configValueInjection
    [ ]                                test
    [ ]                                testConfigProfileWithDev
    [ ]                                testConfigProfileWithDev

**Comment by Azquelt** [comment]
Running with the latest snapshots of smallrye and the TCK, I have the following problems:

Multiple tests have beans which are static inner classes of the test class. The test class and its inner classes are included in the .jar (which has a beans.xml), and then automatically added by arquillian to the .war as well (which has no beans.xml). Liberty sees both classes, makes them beans and then gets an ambiguous bean exception.

This problem affects multiple classes:
```CDIPropertyExpressionsTest
ConfigPropertyFileProfileTest
ProdProfileTest
ConfigProviderTest
InvalidConfigProfileTest
DevConfigProfileTest
ConfigValueTest
TestCustomConfigProfile
TestConfigProfileTest```

For `PropertyExpressionsTest`, expressions do not get resolved because `OLSmallRyeConfigProviderResolver.getBuilder()` does not add the default interceptors when creating the builder (contrast with `SmallRyeConfigProviderResolver`).

Once this problem is fixed, `PropertyExpressionsTest` still fails because the `@AfterMethod` call runs on both the client and server, and when it runs on the client, the MP Config Impl is not available.

**Comment by tevans78** [comment]
This was completed
