### ISSUE TITLE
Problems with jacc-2.0 feature

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/open-liberty#13659]
@dbarfield reported seeing these messages diring testing:

![image](https://user-images.githubusercontent.com/2151186/91207763-464c8b00-e6d7-11ea-8562-8859d7fd0e14.png)

The javadoc by that name doesn't exist, and we should be looking at the feature definition, / bnd file combination to make sure they match.   Some use io.openliberty, some use com.ibm.ws

**Comment by jvanhill** [comment]
@cbridgha - I imagine this is an issue with all features. We need something that is going to transform or regenerate the Javadoc. As far as I know, the transformer does NOT do that yet. Not quite sure why I changed the version from the one that exists. I thought I avoided that for others. Must have been on auto-replace versions in the feature file.

I can change the version to 1.0, but that doesn't fix the Javadoc generation or renaming issue; or, I can wait until we decide what to do there.

**Comment by jvanhill** [comment]
I also wonder if the JAR file name is wrong in the feature as well. Perhaps that works by bundle name?

`-jars=io.openliberty.jacc.2.0; location:=dev/api/ibm/`

**Comment by dbarfield** [comment]
@jvanhill "I imagine this is an issue with all features." I don't think this is the case.  As part of the testing of the beta we install all installable items (addons, features, samples) using WDT.  This was the only one that failed.

**Comment by jvanhill** [comment]
@dbarfield - The issue with all features is that they are going to be pointing at un-transformed Javadoc.

The version issue was my issue.
