### ISSUE TITLE
Remote ejb business method declares observes 

### ISSUE THREAD

**Issue by benjamin-confino** [OpenLiberty/open-liberty#1365]
The following failure was seeon when EJB32Test is run on CDI 2.0

[ERROR   ] CWWKZ0002E: An exception occurred while starting the application ejbMisc. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DefinitionException: WELD-000088: Observer method must be static or local business method:  [EnhancedAnnotatedMethodImpl] public com.ibm.ws.cdi12test.remoteEjb.ejb.TestObserver.observeRemote(@Observes EJBEvent) 	at com.ibm.ws.cdi12test.remoteEjb.ejb.TestObserver.observeRemote(TestObserver.java:0)

Note that the test app is currently uninstalled from dropins at the end of the test run. To run on CDI 2.0 the test will either need to be modified to install the app a second time or the code to remove the test will need to be removed.

**Comment by Emily-Jiang** [comment]
https://issues.jboss.org/browse/CDI-545 clarified the CDI spec and made the test case invalid.

**Comment by Emily-Jiang** [comment]
Close this one as the previous CDI 1.2 spec was incorrect and the change in CDI 2.0 was to correct that behavior.
