### ISSUE TITLE
Cannot get SessionContext

### ISSUE THREAD

**Issue by altuga** [OpenLiberty/open-liberty#13709]
**Describe the bug**
Cannot get SessionContext 

If there is a stack trace, please include the FULL stack trace (without any `[internal classes]` lines in it). To find the full stack trace, you may need to check in `$WLP_OUTPUT_DIR/messages.log`

**Steps to Reproduce**

```
import javax.annotation.Resource;
import javax.ejb.Asynchronous;
import javax.ejb.SessionContext;
import javax.ejb.Stateless;


@Stateless
public class DoesntMatter {

    @Resource
    SessionContext sc;

    public void save() {
        sc.setRollbackOnly();

    }

}

```
 WELD-001474: Class com.kodcu.boot.Doesntmatter is on the classpath, but was ignored because a class it references was not found: javax.ejb.SessionContext.
[INFO] 

**Expected behavior**
Not get  WELD-001474 exception. 

**Diagnostic information:**
 - OpenLiberty version : Open Liberty 20.0.0.8/wlp-1.0.43.cl200820200721-1900)
 - Java Version: version 1.8.0_152-ea-b05 
 - server.xml configuration (WITHOUT sensitive information like passwords)
```

<?xml version="1.0" encoding="UTF-8"?>
<server description="${project.name}">

    <featureManager>
        <feature>microProfile-3.3</feature>
        <feature>jpa-2.2</feature>
        <feature>jaxrs-2.1</feature>
        <feature>jsonb-1.0</feature>
        <feature>cdi-2.0</feature>
    </featureManager>


    <httpEndpoint id="defaultHttpEndpoint"
                  httpPort="9080"
                  httpsPort="9443"/>

    <webApplication location="${project.name}.war" contextRoot="/">
        <classloader apiTypeVisibility="+third-party" />
    </webApplication>
    <mpMetrics authentication="false"/>
```

**Additional context**

**Comment by jhanders34** [comment]
If you want to use ejb function you will need to add one of the ejb features to your server.xml.  Adding ejbLite-3.2 or ejb-3.2 are the likely candidates to resolve this issue for you.

**Comment by altuga** [comment]
It worked. Thanks.
