### ISSUE TITLE
How to change the extraction directory while running the jar configured using open liberty 

### ISSUE THREAD

**Issue by jainchirag21064** [OpenLiberty/open-liberty#13727]
Hi All,
We are trying to deploy the runnable jar on Azure App service of type Windows
While executing the java -jar app.jar command the jar is being extracted to the Users directory 
Users directory is not having enough space to accommodate all the extracted content.

Is there a way for us to create runnable jar with option of defining the location where it can extract the liberty packages and run the application?

![image](https://user-images.githubusercontent.com/13871439/91738724-31796700-ebb1-11ea-8324-8b1568a70a6a.png)

**Comment by aguibert** [comment]
hi @jainchirag21064, yes you can set the `WLP_JAR_EXTRACT_ROOT` or `WLP_JAR_EXTRACT_DIR` environment variable

See this doc for further details: https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_setup_jarserver.html

**Comment by jainchirag21064** [comment]
Hi @aguibert ,
I tried adding the following in the server.xml as a variable but its still not reflecting may be that's not the correct place to set any idea where shall i add ? in pom.xml?

<variable name="wlp.jar.extract.root" value="$(CustomDir)" />

**Comment by jainchirag21064** [comment]
Hi @aguibert ,
Any suggestion would be helpful

**Comment by bpaskin-ibm** [comment]
Hi, if this is a Unix based system, then you can do 
```
export WLP_JAR_EXTRACT_ROOT=/path/to/extraction
java -jar target/app.jar
```
Brian

**Comment by jainchirag21064** [comment]
Thanks @bpaskin-ibm ,
Tried that it worked but not on Azure AppService Windows.
Its now leading to some other problem we are not able to reach the application on described port 8080 as well as port 80

**Comment by aguibert** [comment]
that sounds like a separate issue now @jainchirag21064. Is the runtime extracting into the location specified in `WLP_JAR_EXTRACT_ROOT` now?

**Comment by jainchirag21064** [comment]
Hi @aguibert ,
Yes it is thanks for help

**Comment by aguibert** [comment]
great, you're welcome @jainchirag21064!

Going to close out this issue since the original question has been answered
