### ISSUE TITLE
Log of liberty does not support GB18030 characters

### ISSUE THREAD

**Issue by ShirleySunCN** [OpenLiberty/open-liberty#13742]
**Is your feature request related to a problem? Please describe.**
#Defect 
![image](https://media.github.ibm.com/user/32299/files/833dcf80-e090-11ea-9319-2fbf3c2533c9)
As you can see, I specific a war file named with gb18030 characters "⺌童༘༙€㐎d㐏ᠧᠨᠩꀏحخد郂㘎€b㐅㐆ᠤꀍ༖瞳༗بةتثخد郂㊣€㐋ᠧᠨᠩ༘༙بةتثجحد铜郂" and also configure it in server.xml

But after I start the server, in log file:
<img width="1263" alt="image" src="https://media.github.ibm.com/user/32299/files/ae282380-e090-11ea-8dc0-1f7519f8c060">

```
[20-8-17 10:51:37:485 IST] 00000032 bm.ws.app.manager.war.internal.WARDeployedAppInfoFactoryImpl I CWWKZ0136I: formlogin 应用程序正在使用 C:\Program Files\IBM\wlp\usr\servers\oidc_gb18030\apps\童??????d????????????????郂b??????????瞳??????????????郂㊣??????????????????????????铜郂.war 中的归档文件。

```
It displays the mess code for the gb18030 characters.
I test it in windows 2012, the windows's language is Chinese.

**Describe the solution you'd like**
**Here is response from ibm liberty developer:**
According to :
https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_logging.html

This would appear to be a limitation on Windows:
On all operating systems, logs are written in the default system encoding.
```
- For Windows platforms On Windows systems, there are two types of encoding: OEM code page, which is used for console output, and ANSI code page, which is used to read and write files. The console.log file uses the OEM code page, and all other logs use the ANSI code page.
- For distributed platforms On all other operating systems, all log files use the default encoding.
```
--- 
**Describe alternatives you've considered**

**Additional context**
All production sold in Chinese market should support GB18030 characters.
test data:
```
Sample data 1	通€㐀ᠠꀇ༐بة㊣郂 
Sample data 2	€酮خد㐁ᠡꀈ༑㘚郂
Sample data 3	€㐂دᠢꀉ༒通郂
Sample data 4	a€㐃㐄ᠣꀊꀋꀌ桐༓༔༕بةتثجحخد㊣﹔﹕﹖我嗀狦郂
Sample data 5	㘎€b㐅㐆ᠤꀍ༖瞳༗بةتثخد郂
Sample data 6	秊€㐇༘༙同ᠥꀎبةتثجحخد郂
Sample data 7	€铜ꀏc㐊ᠦ༘༙بةتد秊郂
Sample data 8	㊣€㐋ᠧᠨᠩ༘༙بةتثجحد铜郂 
Sample data 9	بةحخد༘༙€㐌ꀏ㐍ᠧᠨᠩ⺌彤郂
Sample data 10	⺌童༘༙€㐎d㐏ᠧᠨᠩꀏحخد郂
```

**Comment by Yushan-Lin** [comment]
@ShirleySunCN can you check what your `file.encoding` is set to in your system?

**Comment by Yushan-Lin** [comment]
@ShirleySunCN Not sure if you're still following this issue, let me know otherwise I will close it.
