### ISSUE TITLE
FAT: SSO LTPA support authentication filter

### ISSUE THREAD

**Issue by utle** [OpenLiberty/open-liberty#13801]
New FAT for SSO LTPA support authentication filter.

**Comment by Zech-Hein** [comment]
Delivered new FAT tests in [CL PR 22542](https://github.ibm.com/was-liberty/WS-CD-Open/pull/22542)

**Comment by Zech-Hein** [comment]
Created Feature Test Summary Here: https://github.com/OpenLiberty/open-liberty/issues/14861
