### ISSUE TITLE
PostgreSQL tables are not automatically generated for transaction recovery.

### ISSUE THREAD

**Issue by jonhawkes** [OpenLiberty/open-liberty#13817]
Transaction recovery logs are not automatically created when PostgreSQL is used to hold the logs.

**Comment by jakub-pomykala** [comment]
It's possible to configure Liberty to use a database for its transaction logs as documented [here](https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_store_logs_in_rdb.html). PostgreSQL used to be one of the databases for which the necessary tables had to be created manually using the documented DDL as a guide. Now, Liberty can automatically create these tables for postgreSQL.
