### ISSUE TITLE
need a better description for logstashCollector's source attribute

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#13814]
https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/reference/config/logstashCollector.html just says:
Specifies a source to be used by the logstash collector.

Need to say what the valid values are.  more like consoleSource or messageSource descriptions from 
https://openliberty.io/docs/20.0.0.9/reference/config/logging.html

**Comment by Yushan-Lin** [comment]
Opened issue to update description: https://github.com/OpenLiberty/docs/issues/2581
