### ISSUE TITLE
GA blog for OL Grafana dashboard support for Thanos datasource

### ISSUE THREAD

**Issue by Yushan-Lin** [OpenLiberty/open-liberty#13856]
**a) Which Liberty feature does it relate to?**
**i) Human-readable name**
MicroProfile Metrics 2.x
MicroProfile Metrics 1.x
**ii) Feature name**
mpMetrics-2.x (i.e. mpMetrics-2.0, mpMetrics-2.2 and mpMetrics-2.3)
mpMetrics-1.1
**iii)Is this a new feature or is it an update to an existing feature for this release?**
This is an update to the Grafana dashboards used by mpMetrics-1.x and mpMetrics-2.x, that is not a part of the Liberty product.
**iv) Provide the fully qualified name of all public features ( as '*.esa' filenames) that are delivered as part of this work**
N/A
**b) Who is the target audience?**
Application developers and administrators who use Liberty's MicroProfile Metrics 2.x and  MicroProfile Metrics 1.x features.
**c) What does this feature provide in general? Write a sentence or two that introduces it to someone new to the concept.**
The Grafana dashboard provides a wide range of time-series visualizations of MicroProfile Metrics data such as CPU, Servlet, Connection Pool, and Garbage Collection metrics. It is powered by a Prometheus datasource which is configured to ingest data from one or more Liberty servers' /metrics endpoint, enabling us to view on Grafana in near real-time.
**d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)**
Previously, we have only provided support for visualizing mpMetrics data via Grafana in Liberty servers, that used Prometheus as the data source. In Kubernetes environment such as OpenShift Container Platform (OCP), users can use Thanos to query and store metrics data from multiple clusters. The previous Grafana Dashboards did not work when Thanos was set as the data source. The new Grafana dashboard allows users using Thanos as the data source to display mpMetrics data.

**e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.**
First you need to have open liberty with metrics enabled, deployed on your Kubernetes environment. If you do not already have Grafana and Prometheus setup, there are guides for setting up monitoring in [RHOCP 4.2+](https://www.ibm.com/support/knowledgecenter/en/SSCSJL_4.2.x/guides/guide-app-monitoring-ocp4.2/guide-app-monitoring-ocp4.2.html).

The updated Grafana dashboards for Liberty on OKD and RHOCP can be found in our [open-liberty-operator](https://github.com/OpenLiberty/open-liberty-operator/tree/master/deploy/dashboards/metrics) repository. The dashboards were updated to support Thanos as a data source in [RHOCP 4.3+](https://github.com/OpenLiberty/open-liberty-operator/tree/master/deploy/dashboards/metrics/RHOCP4.3-GrafanaOperator3.0.2-Grafana5.2), as Thanos is included in those versions of RHOCP.

1. Download the [Grafana Dashboard](https://github.com/OpenLiberty/open-liberty-operator/tree/master/deploy/dashboards/metrics/RHOCP4.3-GrafanaOperator3.0.2-Grafana5.2), and apply the configured dashboard to your Grafana instance.

2. Now you can visualize your Grafana dashboards with Thanos as the data source:

**mpMetrics-1.x dashboard**
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/31770221/92936671-617a0300-f418-11ea-927e-3f03d989a5fd.png">

**mpMetrics-2.x dashboard**
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/31770221/92936536-32fc2800-f418-11ea-99c7-a210e9083cd8.png">

**f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.**
The dashboard can be found on Grafana's website at  https://github.com/OpenLiberty/open-liberty-operator/tree/master/deploy/dashboards/metrics/
You can read more about Prometheus to create your own custom visualizations at https://prometheus.io/docs/prometheus/latest/querying/basics/
You can read more information about Thanos in RHOCP at https://www.openshift.com/blog/federated-prometheus-with-thanos-receive
**g. Attach any images to this work item as .png files**

**Comment by donbourne** [comment]
This seems like too light an intro to Thanos as a concept/topic.  I'd suggest we reduce answer to question "e" to just talk about how we have a dashboard that now works when your are using Thanos, which you may have from OCP 4.3.

**Comment by Yushan-Lin** [comment]
@donbourne I updated "e" so it just talks about the dashboards.

**Comment by donbourne** [comment]
"there are Kabanero guides for setting up monitoring in RHOCP 4.2+." -- we should point to the ICP4A KC ( https://www.ibm.com/support/knowledgecenter/en/SSCSJL_4.2.x/guides/guide-app-monitoring-ocp4.2/guide-app-monitoring-ocp4.2.html ) rather than the kabanero guide for that.

"The dashboards for Thanos were updated for RHOCP 4.3+, as Thanos is included in those versions of RHOCP." -- this might make people question whether the dashboard still works for Prometheus.  suggest you word it so it indicates we support both.

**Comment by Yushan-Lin** [comment]
@donbourne I changed "The dashboards for Thanos were updated for RHOCP 4.3+, as Thanos is included in those versions of RHOCP." -> "The dashboards were updated to support Thanos as a data source in RHOCP 4.3+, as Thanos is included in those versions of RHOCP."

**Comment by donbourne** [comment]
Looks good to me!

**Comment by Yushan-Lin** [comment]
Published: https://openliberty.io/blog/2020/10/23/kerberos-grafana-200011.html
