### ISSUE TITLE
mpJwt 1.2 performance

### ISSUE THREAD

**Issue by jdmcclur** [OpenLiberty/open-liberty#13879]
I tried out a simple jwt scenario, and I do see a bit of a performance regression.
 
This problem affects mpJwt-1.1, but is worse in mpJwt-1.2.
 
It looks like for each request, we are getting values for mpJwt properties here:
https://github.com/OpenLiberty/open-liberty/blob/fa509424ef59adee9c758f2676e0e7dc9e647dba/dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/config/MpConfigUtil.java#L79
 
In jwt 1.1 this is only one property (at least in my scenario):
mp.jwt.verify.publickey
 
But in jwt 1.2, this includes more:
mp.jwt.verify.publickey
mp.jwt.decrypt.key.location
mp.jwt.verify.audiences
mp.jwt.token.header
mp.jwt.token.cookie
mp.jwt.verify.publickey.algorithm
 
 
This call eventually gets down to the mpConfig code here, which throws a NoSuchElementException because the properties aren't set (I think), which the link above catches:
https://github.com/OpenLiberty/open-liberty/blob/fa509424ef59adee9c758f2676e0e7dc9e647dba/dev/com.ibm.ws.microprofile.config.1.1/src/com/ibm/ws/microprofile/config/impl/AbstractConfig.java#L176
 
The slowest part of the code is the Tr.formatMessage.
 
Is this something that needs to be done every request? Can the properties change?

**Comment by ayoho** [comment]
I've just merged https://github.com/OpenLiberty/open-liberty/pull/13988 which should hopefully make this problem a little bit better. Generally speaking, though, we do need to get the MP Config properties for each new request that comes in because the properties can differ depending on the application being accessed. Before my PR, our code could potentially be making three calls to read the MP Config properties for a given request. My PR should change that so we only read the properties once per request.

**Comment by jdmcclur** [comment]
Excellent, I'll try it out when I get a chance. I haven't had time to look at the code in detail, but I wonder if there is a better way handle non-existent properties than throwing/catching an error. May be more of a question for mpconfig.

**Comment by jdmcclur** [comment]
This change looks good. 

- mpJWT-1.2 now performs as well as mp-JWT-1.1 did previous to the fix
- mpJWT-1.1 also got a bit faster with this change, so mpJWT-1.2 is slightly slower than mpJWT-1.1 because of the extra properties, at least in this super simple primitive case.
- It would be good to look at the throw/catch issue at some point.

**Comment by jdmcclur** [comment]
It looks like with mpConfig-2.0, the try/catch code is taking more time. We moved to using smallrye, which is taking longer to generate the NoSuchElementException.
```
 Parent      0   0.00   0.34           0          24    J:io/smallrye/config/SmallRyeConfig.getOptionalValue(Ljava/lang/String;Ljava/lang/Class;)Ljava/util/Optional;
  Parent      0   0.00  12.69           0         884    J:io/smallrye/config/SmallRyeConfig.getValue(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;
    Self      0   0.00  13.04           0         908    J:io/smallrye/config/SmallRyeConfig.getValue(Ljava/lang/String;Lorg/eclipse/microprofile/config/spi/Converter;)Ljava/lang/Object;
   Child      0   0.01  11.93           1         831    J:io/smallrye/config/ConfigMessages_$bundle.propertyNotFound(Ljava/lang/String;)Ljava/util/NoSuchElementException;
   Child      0   0.00   1.09           0          76    J:io/smallrye/config/SmallRyeConfig.getConfigValue(Ljava/lang/String;)Lio/smallrye/config/ConfigValue;
   Child      0   0.00   0.01           0           1    J:io/smallrye/config/Converters$BuiltInConverter.convert(Ljava/lang/String;)Ljava/lang/Object;
```
one step lower:
```
  Parent      0   0.00  11.39           0         793    J:io/smallrye/config/ConfigMessages_$bundle.propertyNotFound(Ljava/lang/String;)Ljava/util/NoSuchElementException;
    Self      0   0.00  11.39           0         793    J:io/smallrye/config/ConfigMessages_$bundle._copyStackTraceMinusOne(Ljava/lang/Throwable;)V
   Child      0   0.01  11.37           1         792    J:java/lang/Throwable.getStackTrace()[Ljava/lang/StackTraceElement;
   Child      0   0.01   0.01           1           1    J:java/lang/Throwable.setStackTrace([Ljava/lang/StackTraceElement;)V
```

@Azquelt is going to open an issue against Smallrye about this, but he mentioned that the mpJwt code could call getOptionalValue() instead of getValue() and avoid the try/catch code.

**Comment by Azquelt** [comment]
In general, causing exceptions to be thrown should be avoided on non-exceptional code paths, but in this case the smallrye logging code always extracts the stack trace when it creates the exception so there's an additional penalty if the stack trace is never going to be used.

**Comment by ayoho** [comment]
@jdmcclur This morning I merged my PR that should fix this performance issue, so the latest code in integration should be able to be used to verify that this has been fixed.
