### ISSUE TITLE
MicroProfile 4.0 long feature names

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#13871]
All of the new MicroProfile 4.0 features use a long feature name which starts with `io.openliberty`.
All older MicroProfile features use long feature names which start with `com.ibm.websphere`.

This means that the server does not recognise singleton features correctly. For example, `com.ibm.websphere.appserver.mpConfig-1.4` and `io.openliberty.mpConfig-2.0` should be mutually exclusive singletons but are not.

One solution might be to introduce a private `mpCompatible-4.0` feature, similar to what we have done with eeCompatible. This can be done because no cross version compatibility is required; MP 4.0 features only work with other MP 4.0 features.

Otherwise we may have to rename all of the MicroProfile 4.0 features.

**Comment by tjwatson** [comment]
This is related to the previous discussions around Jakarta EE feature names changing from Java EE (issue #9214).  There we decided against having a mechanism to alias fully qualified feature names.

**Comment by tevans78** [comment]
We will create a `mpCompatible-4.0` feature following the same pattern as `eeCompatible-9.0`. This should include documentation updates to clarify the potential conflicts.

As a follow-on we should update the special error messages that are output when a mpCompatible conflict is detected. Again this is the same as has been done for eeCompatible.

**Comment by tevans78** [comment]
Eventually we decided to rename the MicroProfile 4.0 features back to `com.ibm.websphere.appserver.*`
https://github.com/OpenLiberty/open-liberty/issues/14641

The mpCompatible-x.x features are still required to prevent mixing and matching of 4.0 features with non-4.0 features (excluding stand-alone features).

**Comment by tevans78** [comment]
Everything has now been renamed. There may still be some usability improvements we could make in the kernel about feature compatiblity error messages ... but that is separate from this work and does not block MP 4.0.
