### ISSUE TITLE
Investigate testEnsureJSF23FeatureAndJSF22FeatureAreSingletonFeatures_EE9_FEATURES Failure

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#13890]
com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23JSF22SingletonFeatureTest.java

testEnsureJSF23FeatureAndJSF22FeatureAreSingletonFeatures -- Test Skipped for now

Expected:
`[ERROR   ] CWWKF0033E: The singleton features jsf-2.2 and faces-3.0 cannot be loaded at the same time.  The configured features jsf-2.2 and jsf-2.3 include one or more features that cause the conflict. Your configuration is not supported; update server.xml to remove incompatible features.`

Actual:
```
[ERROR   ] CWWKF0044E: The features jsf-2.2 and el-4.0 cannot be loaded at the same time.  The feature jsf-2.2 of Java EE 7 is incompatible with the feature el-4.0 of Jakarta EE 9.  The configured features jsf-2.2 and faces-3.0 include an incompatible combination of features.  Your configuration is not supported.  Update the configuration to use features that support either the Jakarta EE or Java EE programming models, but not both.
[ERROR   ] CWWKF0029E: Could not resolve module: com.ibm.ws.jsp.jstl.facade.jakarta [67]
  Unresolved requirement: Import-Package: org.apache.taglibs.standard.extra.commons.collections.iterators; version="[2.2.0,3.0.0)"
    -> Export-Package: org.apache.taglibs.standard.extra.commons.collections.iterators; bundle-symbolic-name="com.ibm.ws.jsp"; bundle-version="1.0.45.202009082229"; version="2.2.0"; uses:="org.apache.taglibs.standard.extra.commons.collections"
       com.ibm.ws.jsp [30]
         Unresolved requirement: Import-Package: junit.framework; resolution:="optional"
         Unresolved requirement: Import-Package: junit.textui; resolution:="optional"
         Unresolved requirement: Import-Package: org.apache.xml.serialize; resolution:="optional"
         Unresolved requirement: Import-Package: org.apache.xml.serializer; resolution:="optional"
         Unresolved requirement: Import-Package: com.ibm.websphere.servlet.error; version="0.0.0"
  Unresolved requirement: Import-Package: org.apache.taglibs.standard.extra.commons.collections; version="[2.2.0,3.0.0)"
    -> Export-Package: org.apache.taglibs.standard.extra.commons.collections; bundle-symbolic-name="com.ibm.ws.jsp"; bundle-version="1.0.45.202009082229"; version="2.2.0" 
```

**Comment by volosied** [comment]
Related to  #13088

**Comment by volosied** [comment]
See  #13928

**Comment by pnicolucci** [comment]
Running the test I see the following in the output.txt:

> [10/07/2020 23:00:33:603 EDT] 001 FeatureReplacementAction       setup                          I Original features:  [jsf-2.2, jsf-2.3]
> [10/07/2020 23:00:33:603 EDT] 001 FeatureReplacementAction       getReplacementFeature          I No feature replacement found for [ jsf-2.2 ]. Verifying if feature name was changed on EE9.
> [10/07/2020 23:00:33:603 EDT] 001 FeatureReplacementAction       getReplacementFeature          I Replace base feature [ jsf ] with EE9 feature [ faces ]
> [10/07/2020 23:00:33:603 EDT] 001 FeatureReplacementAction       getReplacementFeature          I Replace feature [ jsf-2.2 ] with [ faces-3.0 ]
> [10/07/2020 23:00:33:603 EDT] 001 FeatureReplacementAction       getReplacementFeature          I No feature replacement found for [ jsf-2.3 ]. Verifying if feature name was changed on EE9.
> [10/07/2020 23:00:33:603 EDT] 001 FeatureReplacementAction       getReplacementFeature          I Replace base feature [ jsf ] with EE9 feature [ faces ]
> [10/07/2020 23:00:33:603 EDT] 001 FeatureReplacementAction       getReplacementFeature          I Replace feature [ jsf-2.3 ] with [ faces-3.0 ]
> [10/07/2020 23:00:33:603 EDT] 001 FeatureReplacementAction       setup                          I Resulting features: [faces-3.0]
> [10/07/2020 23:00:33:603 EDT] 001 FeatureReplacementAction       setup                          I Config: ServerConfiguration
> FeatureManager{feature="faces-3.0" }Logging{maxFileSize="20" maxFiles="10" traceFormat="BASIC" traceSpecification="*=info:org.apache.myfaces.*=all:com.ibm.ws.jsf*=all"isoDateFormat="false"}[IncludeElement{location="../fatTestPorts.xml" }]

`FeatureReplacementAction.java` looks to actually replace both `jsf` features with the `faces-3.0` feature which does not give us the outcome we want. I think the best resolution for this test is to create a new test class / server and test to ensure that the `jsf-2.3` and `faces-3.0` features can't be loaded at the same time.
