### ISSUE TITLE
Feature Test Summary for grpc-1.0 and grpcClient-1.0

### ISSUE THREAD

**Issue by wtlucy** [OpenLiberty/open-liberty#13948]
**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

A new FAT bucket has been added to test both new gRPC features: `com.ibm.ws.grpc_fat`.  The intention of this bucket is to test `grpc-1.0` and `grpcClient-1.0` as extensively as possible: basic functionality, the new configuration parameters, application deployment behavior, integration with other features, etc. are verified.

Current test classes:
* `HelloWorldTest`: basic client and server test
    * Two apps are installed: `HelloWorldService.war` contains a grpc service implementation, and `HelloWorldClient.war` contains a Servlet that makes use of `grpcClient-1.0` to access the service defined in `HelloWorldService.war`.  This covers the essential case of using gRPC in a typical EE scenario.
* `HelloWorldTlsTest`: verify TLS support
    * The same two apps are installed, however this time TLS is enabled on the server.  Basic SSL functionaliy is tested, as well as TLS mutual auth, SSL outboundfilter mapping, and error cases.
* `HelloWorldCDITests`: basic test with CDI artifacts
    * verify that CDI artifacts work as expected when defined in`grpc-1.0` services as well as in Interceptors
* `SecureHelloWorldTest`: basic test with servlet security enabled 
    * verifies that web.xml security-constraints are enforced when appSecurity is enabled
* `ClientConfigTests`: validate the server.xml grpcClient configuration options 
    * covers basic `<grpcClient/>` support, updating existing elements, removing elements, `host` matching, and error cases.  Every `<grpcClient/>` config option is covered.
* `GrpcMetricsTest`: verifies metrics integration
* `ServiceConfigTests`: verify the server.xml `<grpc/>` configuration options work as expected
    * covers basic `<grpc/>` support, updating existing elements, removing elements, `target` matching, and error cases.  Every `<grpc/>` config option is covered.
* `ServiceSupportTests`: verifies basic `grpc-1.0` application support
    * covers installing apps, handling multiple apps, duplicate service errors, in-place updates, invalid service deployments
* `ServiceInterceptorTests`: test liberty ServerInterceptor integration
    * covers adding a basic server.xml-defined interceptor, multiple interceptors, annotation-defined interceptors, and mixing server.xml and annotation-defined interceptors
* `ClientHeaderPropagationTests`: more thoroughly tests relating to grpcClient header
    * verify multiple use cases for `headersToPropagate`, and additionally the properties involved with overriding headers including `overrideAuthority` and `userAgent`
* `ClientInterceptorTests`: test liberty ClientInterceptor integration
    * covers a basic interceptor registration, multiple registrations, and an error case
* `StoreServicesRESTClientTests`: test a large microservices-style collection of applications, driven via a microprofile rest client
    * see `ProducerEndpointFATServlet` and `ConsumerEndpointFATServlet`
    * verifies primarily that grpc compatibility can work well in conjunction with REST services.  Client, server, and bidirectional streaming RPC cases are tested extensively.  SSL is verified, as well as the  basic, jwt, and oauth auth mechanisms.
* `StoreConsumerServletClientTests`: tests the microservices-style consumer application, driven via a servlet client
    * further verifies basic functionality of the consumer app (including basic auth)
* `StoreProducerServletClientTests`: tests the microservices-style producer application, driven via a servlet client
    * further verifies a variety of streaming RPC cases
* `StoreServicesSecurityTests`: additional jwtSso-specific security tests
    * verifies a JWT auth flow: the test client retrieves a valid JWT token and propagates it via a grpcClient call. The invalid auth token case is additionally verified.

If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)? 

N/A

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

> We think 4 is appropriate.  We have added tests covering the golden paths, and additionally we've added a good number of tests covering error scenarios (mostly relating to configuration).

for epic: #8637

**Comment by ayoho** [comment]
LGTM.
