### ISSUE TITLE
GA requestProbeServlet auto feature

### ISSUE THREAD

**Issue by isaacrivriv** [OpenLiberty/open-liberty#13953]
Move servlet auto feature with [requestProbeServlet](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.servlet5.0-requestProbeServlet1.0.feature) from beta to ga

**Comment by pnicolucci** [comment]
Closing in favor of issue 15884
