### ISSUE TITLE
BETA BLOG - MicroProfile OpenAPI 2.0 Support

### ISSUE THREAD

**Issue by msmiths** [OpenLiberty/open-liberty#13970]
1. Which Liberty feature does your update relate to?
    
   Human-readable name (eg WebSockets feature):

> MicroProfile OpenAPI 2.0
   
   Feature name (eg websockets-1.0): 

> mpOpenAPI-2.0

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.

> application developers

3. Write a paragraph to summarises the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.

> The [OpenAPI v3 specification][openapi-spec] defines a standard, language-agnostic, interface for describing REST APIs which allows documentation to be generated from the APIs themselves. The [MicroProfile OpenAPI specification][spec] provides a unified Java API for the OpenAPI v3 specification which allows Java developers to generate OpenAPI v3 documents from their JAX-RS applications.

   - What was the problem before and how does your update make their life better? (Why should they care?)

> Version 2.0 of the MicroProfile OpenAPI specification introduces some new annotations that simplify the process of generating OpenAPI documentation for your REST APIs. It also introduces a new MicroProfile Config property prefix that can be used to define the schema for Java classes that you do not have the source code for.

> ### @SchemaProperty
> The `@SchemaProperty` annotation has been added to allow you to include properties in the definition of a schema when using the `@Schema` annotation. Previously, the `@Schema` annotation did not allow you to define any properties. Properties were introspected from the implementation class.
> With the introduction of the `@SchemaProperty` annotation, a list of properties can now defined using the `properties` attribute on the `@Schema` annotation, as follows:
>```
>@Schema(
>    name = "User",
>        description = "Telephone number to contact the user”,
>        implementation = User.class,
>        properties = {
>            @SchemaProperty(
>                name = "phone",
>                description = "Telephone number to contact the user”
>            )
>        }
>    )} 
>```

> ### @RequestBodySchema
> The `@RequestBodySchema` annotation has been added to provide a shorthand mechanism to specify the schema for a request body. Previously, defining the schema for a request body required the use of three different annotations, as follows:
>```
>@RequestBody(
>    content = {
>        @Content(
>            schema = @Schema(
>                implementation = MyRequestObject.class
>            )
>        )
>    }
>)
>```
> With the introduction of the `@RequestBodySchema` annotation, this can be simplified to the following:
>```
>@RequestBodySchema(MyRequestObject.class) 
>```

> ### @APIResponseSchema
> The `@APIResponseSchema` annotation has been added to provide a shorthand mechanism to specify the schema for a response body. Previously, defining the schema for a response body required the use of three different annotations, as follows:
>```
>@APIResponse(
>    content = {
>            @Content(
>                schema = @Schema(
>                    implementation = MyResponseObject.class
>                )
>            )
>        }
>    )
>```
> With the introduction of the `@RequestBodySchema` annotation, this can be simplified to the following:
>```
>@APIResponseSchema(MyResponseObject.class)
>```

> ### mp.openapi.schema.*
> The `mp.openapi.schema.*` MicroProfile Config property prefix has been added to allow you to define the schema for Java classes using configuration rather than code. The use of this property is functionally equivalent to the use of the `@Schema` annotation on a Java class, but may be used in cases where you do not have access to the source code of a class. The remainder of the property key must be the fully-qualified class name and the value must be a valid OpenAPI schema object, specified in the JSON format.
> For example, in the case where an application wishes to represent Java `Date`s in epoch milliseconds, the following configuration could be used (line escapes and indentation added for readability):
>```
>mp.openapi.schema.java.util.Date = { \
>    "name": "EpochMillis" \
>    "type": "number", \
>    "format": "int64", \
>    "description": "Milliseconds since January 1, 1970, 00:00:00 GMT" \
>  }
>```

   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.

> Enable OpenAPI 2.0 in the server.xml, along with any other features you’re using.
   
>```
>    <featureManager>
>        <feature>mpOpenAPI-2.0</feature>
>    </featureManager>
>```
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?

> * Get an introduction to MicroProfile OpenAPI with the Open Liberty guides
>   * [Documenting RESTful APIs][guide-documenting-restful-apis]
> * Reference the [Javadoc][javadoc]
> * Reference the full [specification][spec], including the [2.0 release notes][release-notes]
> * Report any issues [on Github][ol-repo]

[openapi-spec]: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md
[spec]: https://download.eclipse.org/microprofile/microprofile-open-api-2.0-RC3/microprofile-openapi-spec.html
[release-notes]: https://download.eclipse.org/microprofile/microprofile-open-api-2.0-RC3/microprofile-openapi-spec.html#release_notes_20
[javadoc]: https://download.eclipse.org/microprofile/microprofile-open-api-2.0-RC3/apidocs/
[guide-documenting-restful-apis]: https://openliberty.io/guides/microprofile-openapi.html
[ol-repo]: https://github.com/OpenLiberty/open-liberty/

**Comment by jakub-pomykala** [comment]
Closing as this is live [here](https://openliberty.io/blog/2020/09/29/microprofile-openapi-beta-200011.html#openAPI)
