### ISSUE TITLE
Login is not working with new cloud Identity credentials

### ISSUE THREAD

**Issue by shruti-sigi** [OpenLiberty/open-liberty#14016]
**Describe the bug**
Login is not working with new cloud ID credentials

**Steps to Reproduce**
1. Go to `https://dashboard-qadev.orderoptimizer.ibm.com/qa02/OptimizerDashboard`
2. Try to login with IBMID credentials 
3.See the error as `CWOAU0073E: An error was encountered while authenticating a user. Please try authenticating again, or contact the site administrator if the problem persists.`

**Expected behavior**
Login should work with new Cloud Identity credentials

<img width="1437" alt="Screenshot 2020-09-18 at 12 50 02 PM" src="https://user-images.githubusercontent.com/34883903/93568519-ed0e0980-f9ad-11ea-9075-015cce12fbe2.png">

For reference attaching logs
TRACES REMOVED

**This is blocking the IBMid migration from IDaaS to Cloud Identity (CI)**
**We observe this issue in liberty version 19.0.0.9 and 20.0.0.9**

**Below are the OIDC configuration**
`<openidConnectClient id="${openid.id}" clientId="${openid.id}" clientSecret="${openid.clientsecret}" redirectToRPHostAndPort="${openid.redirect.url}" discoveryEndpointUrl="${openid.discovery.endpoint.url}" includeIdTokenInSubject="true" userIdentityToCreateSubject="preferred_username" uniqueUserIdentifier="preferred_username" scope="openid" httpsRequired="true" signatureAlgorithm="RS256" isClientSideRedirectSupported="false" mapIdentityToRegistryUser="true" />`

**Property values are**

{
   "openid_id":"NWE4YWY2NzItZjVhMi00",
   "openid_deployment_mode":"production",
   "npsurl":"https://nebula-cdn.kampyle.com/we/28600/onsite/embed.js",
   "tenant_map_latitude":"37.50",
   "tenant_map_longitude":"-94.00",
   "openid_clientsecret":"XXXXXXXXX",
   "redirect_url":"https://dashboard-qadev.orderoptimizer.ibm.com",
   "openid_authorization_endpoint_url":"https://login.ibm.com/v1.0/endpoint/default/authorize",
   "openid_token_endpoint_url":"https://login.ibm.com/v1.0/endpoint/default/token",
   "openid_discovery_endpoint_url":"https://login.ibm.com/oidc/endpoint/default/.well-known/openid-configuration",
   "openid_issuer_identifier":"https://login.ibm.com/oidc/endpoint/default"
}

clientID-NWE4YWY2NzItZjVhMi00
secret-XXXXXXXXXXXXXXXXX

**Comment by shruti-sigi** [comment]
@teddyjtorres : I am sharing the logs here
[sep_22_latest_logs.zip](https://github.com/OpenLiberty/open-liberty/files/5259702/sep_22_latest_logs.zip)

**Comment by shruti-sigi** [comment]
hi @teddyjtorres: i have removed the stylesheet and tried
in both environment prod and preprod(qa)

In preprod(qa) it worked, but sometimes i got error message
UI URI-https://dashboard-qadev.orderoptimizer.ibm.com/qa02/OptimizerDashboard/

CWOAU0073E: An error was encountered while authenticating a user. Please try authenticating again, or contact the site administrator if the problem persists.

In prod , first time when i tried login i was able to login and tried logout and again login ,that time i got message
prod UI URl is:https://dashboard-preview.orderoptimizer.ibm.com/support/OptimizerDashboard

CWOAU0073E: An error was encountered while authenticating a user. Please try authenticating again, or contact the site administrator if the problem persists.

later tried almost 10 times, i was not able to login
here are the logs i have captured for the above scenarios

[Uploading server_23_sep_logs.zip…]()

**Comment by teddyjtorres** [comment]
Removed traces from issue.

**Comment by teddyjtorres** [comment]
Closing since the issue has been resolved.
