### ISSUE TITLE
JSP ValidateVisitor.ELCheckType triggers NoSuchMethodError

### ISSUE THREAD

**Issue by brideck** [OpenLiberty/open-liberty#14111]
A handful of tests in the JSP TCK triggers the following error:
java.lang.NoSuchMethodError: org.apache.el.lang.ELSupport.coerceToNumber(Ljava/lang/Object;Ljava/lang/Class;)Ljava/lang/Number;
	at com.ibm.ws.jsp.translator.visitor.validator.ValidateVisitor.ELCheckType(ValidateVisitor.java:1777)
	at com.ibm.ws.jsp.translator.visitor.validator.ValidateVisitor.validateCustomTagAttribute(ValidateVisitor.java:1720)
	at com.ibm.ws.jsp.translator.visitor.validator.ValidateVisitor.validateCustomTagAttributeValues(ValidateVisitor.java:1401)
	at com.ibm.ws.jsp.translator.visitor.validator.ValidateVisitor.visitCustomTagStart(ValidateVisitor.java:284)
	at com.ibm.ws.jsp.translator.visitor.JspVisitor.processJspElement(JspVisitor.java:370)
	at com.ibm.ws.jsp.translator.visitor.JspVisitor.processChildren(JspVisitor.java:423)
	at com.ibm.ws.jsp.translator.visitor.JspVisitor.processJspElement(JspVisitor.java:238)
	at com.ibm.ws.jsp.translator.visitor.JspVisitor.visit(JspVisitor.java:220)
	at com.ibm.ws.jsp.translator.JspTranslator.processVisitors(JspTranslator.java:130)
	at com.ibm.ws.jsp.translator.utils.JspTranslatorUtil.translateJsp(JspTranslatorUtil.java:266)
	at com.ibm.ws.jsp.translator.utils.JspTranslatorUtil.translateJspAndCompile(JspTranslatorUtil.java:113)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.translateJsp(AbstractJSPExtensionServletWrapper.java:540)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper._checkForTranslation(AbstractJSPExtensionServletWrapper.java:457)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.checkForTranslation(AbstractJSPExtensionServletWrapper.java:247)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionProcessor.findWrapper(AbstractJSPExtensionProcessor.java:508)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionProcessor.getServletWrapper(AbstractJSPExtensionProcessor.java:351)
	...

**Comment by pnicolucci** [comment]
`ValidateVisitor` is failing on this line:

```
        if (ELArithmetic.isNumberType(type)) {
            ELSupport.coerceToNumber(obj, type);
        }
```

If I look at `ELSupport` in Expression Language 3.0 I see the following:

```
    protected static final Number coerceToNumber(final Number number,
            final Class<?> type) throws ELException {
        if (Long.TYPE == type || Long.class.equals(type)) {
            return Long.valueOf(number.longValue());
        }
        if (Double.TYPE == type || Double.class.equals(type)) {
            return new Double(number.doubleValue());
        }
        if (Integer.TYPE == type || Integer.class.equals(type)) {
            return Integer.valueOf(number.intValue());
        }
        if (BigInteger.class.equals(type)) {
            if (number instanceof BigDecimal) {
                return ((BigDecimal) number).toBigInteger();
            }
            if (number instanceof BigInteger) {
                return number;
            }
            return BigInteger.valueOf(number.longValue());
        }
        if (BigDecimal.class.equals(type)) {
            if (number instanceof BigDecimal) {
                return number;
            }
            if (number instanceof BigInteger) {
                return new BigDecimal((BigInteger) number);
            }
            return new BigDecimal(number.doubleValue());
        }
        if (Byte.TYPE == type || Byte.class.equals(type)) {
            return Byte.valueOf(number.byteValue());
        }
        if (Short.TYPE == type || Short.class.equals(type)) {
            return Short.valueOf(number.shortValue());
        }
        if (Float.TYPE == type || Float.class.equals(type)) {
            return new Float(number.floatValue());
        }
        if (Number.class.equals(type)) {
            return number;
        }

        throw new ELException(MessageFactory.get("error.convert",
                number, number.getClass(), type));
    }

    public static final Number coerceToNumber(final Object obj,
            final Class<?> type) throws ELException {
        return coerceToNumber(null, obj, type);
    }

    public static final Number coerceToNumber(final ELContext ctx, final Object obj,
            final Class<?> type) throws ELException {

        if (ctx != null) {
        	boolean originalIsPropertyResolved = ctx.isPropertyResolved();
        	try {
        		Object result = ctx.getELResolver().convertToType(ctx, obj, type);
        		if (ctx.isPropertyResolved()) {
        			return (Number) result;
        		}
        	} finally {
        		ctx.setPropertyResolved(originalIsPropertyResolved);
        	}
        }

        if (!COERCE_TO_ZERO) {
            if (obj == null && !type.isPrimitive()) {
                return null;
            }
        }

        if (obj == null || "".equals(obj)) {
            return coerceToNumber(ZERO, type);
        }
        if (obj instanceof String) {
            return coerceToNumber((String) obj, type);
        }
        if (ELArithmetic.isNumber(obj)) {
            return coerceToNumber((Number) obj, type);
        }

        if (obj instanceof Character) {
            return coerceToNumber(Short.valueOf((short) ((Character) obj)
                    .charValue()), type);
        }

        throw new ELException(MessageFactory.get("error.convert",
                obj, obj.getClass(), type));
    }

    protected static final Number coerceToNumber(final String val,
            final Class<?> type) throws ELException {
        if (Long.TYPE == type || Long.class.equals(type)) {
            try {
                return Long.valueOf(val);
            } catch (NumberFormatException nfe) {
                throw new ELException(MessageFactory.get("error.convert",
                        val, String.class, type));
            }
        }
        if (Integer.TYPE == type || Integer.class.equals(type)) {
            try {
                return Integer.valueOf(val);
            } catch (NumberFormatException nfe) {
                throw new ELException(MessageFactory.get("error.convert",
                        val, String.class, type));
            }
        }
        if (Double.TYPE == type || Double.class.equals(type)) {
            try {
                return Double.valueOf(val);
            } catch (NumberFormatException nfe) {
                throw new ELException(MessageFactory.get("error.convert",
                        val, String.class, type));
            }
        }
        if (BigInteger.class.equals(type)) {
            try {
                return new BigInteger(val);
            } catch (NumberFormatException nfe) {
                throw new ELException(MessageFactory.get("error.convert",
                        val, String.class, type));
            }
        }
        if (BigDecimal.class.equals(type)) {
            try {
                return new BigDecimal(val);
            } catch (NumberFormatException nfe) {
                throw new ELException(MessageFactory.get("error.convert",
                        val, String.class, type));
            }
        }
        if (Byte.TYPE == type || Byte.class.equals(type)) {
            try {
                return Byte.valueOf(val);
            } catch (NumberFormatException nfe) {
                throw new ELException(MessageFactory.get("error.convert",
                        val, String.class, type));
            }
        }
        if (Short.TYPE == type || Short.class.equals(type)) {
            try {
                return Short.valueOf(val);
            } catch (NumberFormatException nfe) {
                throw new ELException(MessageFactory.get("error.convert",
                        val, String.class, type));
            }
        }
        if (Float.TYPE == type || Float.class.equals(type)) {
            try {
                return Float.valueOf(val);
            } catch (NumberFormatException nfe) {
                throw new ELException(MessageFactory.get("error.convert",
                        val, String.class, type));
            }
        }

        throw new ELException(MessageFactory.get("error.convert",
                val, String.class, type));
    }
```

In the Expression Language 4.0 we have the following:

    protected static final Number coerceToNumber(final Number number,
            final Class<?> type) throws ELException {
        if (Long.TYPE == type || Long.class.equals(type)) {
            return Long.valueOf(number.longValue());
        }
        if (Double.TYPE == type || Double.class.equals(type)) {
            return Double.valueOf(number.doubleValue());
        }
        if (Integer.TYPE == type || Integer.class.equals(type)) {
            return Integer.valueOf(number.intValue());
        }
        if (BigInteger.class.equals(type)) {
            if (number instanceof BigDecimal) {
                return ((BigDecimal) number).toBigInteger();
            }
            if (number instanceof BigInteger) {
                return number;
            }
            return BigInteger.valueOf(number.longValue());
        }
        if (BigDecimal.class.equals(type)) {
            if (number instanceof BigDecimal) {
                return number;
            }
            if (number instanceof BigInteger) {
                return new BigDecimal((BigInteger) number);
            }
            return new BigDecimal(number.doubleValue());
        }
        if (Byte.TYPE == type || Byte.class.equals(type)) {
            return Byte.valueOf(number.byteValue());
        }
        if (Short.TYPE == type || Short.class.equals(type)) {
            return Short.valueOf(number.shortValue());
        }
        if (Float.TYPE == type || Float.class.equals(type)) {
            return Float.valueOf(number.floatValue());
        }
        if (Number.class.equals(type)) {
            return number;
        }

        throw new ELException(MessageFactory.get("error.convert",
                number, number.getClass(), type));
    }

    public static final Number coerceToNumber(final ELContext ctx, final Object obj,
            final Class<?> type) throws ELException {

        if (ctx != null) {
            boolean originalIsPropertyResolved = ctx.isPropertyResolved();
            try {
                Object result = ctx.getELResolver().convertToType(ctx, obj, type);
                if (ctx.isPropertyResolved()) {
                    return (Number) result;
                }
            } finally {
                ctx.setPropertyResolved(originalIsPropertyResolved);
            }
        }

        if (!COERCE_TO_ZERO) {
            if (obj == null && !type.isPrimitive()) {
                return null;
            }
        }

        if (obj == null || "".equals(obj)) {
            return coerceToNumber(ZERO, type);
        }
        if (obj instanceof String) {
            return coerceToNumber((String) obj, type);
        }
        if (ELArithmetic.isNumber(obj)) {
            return coerceToNumber((Number) obj, type);
        }

        if (obj instanceof Character) {
            return coerceToNumber(Short.valueOf((short) ((Character) obj)
                    .charValue()), type);
        }

        throw new ELException(MessageFactory.get("error.convert",
                obj, obj.getClass(), type));
    }

    protected static final Number coerceToNumber(final String val,
            final Class<?> type) throws ELException {
        if (Long.TYPE == type || Long.class.equals(type)) {
            try {
                return Long.valueOf(val);
            } catch (NumberFormatException nfe) {
                throw new ELException(MessageFactory.get("error.convert",
                        val, String.class, type));
            }
        }
        if (Integer.TYPE == type || Integer.class.equals(type)) {
            try {
                return Integer.valueOf(val);
            } catch (NumberFormatException nfe) {
                throw new ELException(MessageFactory.get("error.convert",
                        val, String.class, type));
            }
        }
        if (Double.TYPE == type || Double.class.equals(type)) {
            try {
                return Double.valueOf(val);
            } catch (NumberFormatException nfe) {
                throw new ELException(MessageFactory.get("error.convert",
                        val, String.class, type));
            }
        }
        if (BigInteger.class.equals(type)) {
            try {
                return new BigInteger(val);
            } catch (NumberFormatException nfe) {
                throw new ELException(MessageFactory.get("error.convert",
                        val, String.class, type));
            }
        }
        if (BigDecimal.class.equals(type)) {
            try {
                return new BigDecimal(val);
            } catch (NumberFormatException nfe) {
                throw new ELException(MessageFactory.get("error.convert",
                        val, String.class, type));
            }
        }
        if (Byte.TYPE == type || Byte.class.equals(type)) {
            try {
                return Byte.valueOf(val);
            } catch (NumberFormatException nfe) {
                throw new ELException(MessageFactory.get("error.convert",
                        val, String.class, type));
            }
        }
        if (Short.TYPE == type || Short.class.equals(type)) {
            try {
                return Short.valueOf(val);
            } catch (NumberFormatException nfe) {
                throw new ELException(MessageFactory.get("error.convert",
                        val, String.class, type));
            }
        }
        if (Float.TYPE == type || Float.class.equals(type)) {
            try {
                return Float.valueOf(val);
            } catch (NumberFormatException nfe) {
                throw new ELException(MessageFactory.get("error.convert",
                        val, String.class, type));
            }
        }

        throw new ELException(MessageFactory.get("error.convert",
                val, String.class, type));
    }

**Comment by pnicolucci** [comment]
As you can see in the Expression Language 4.0 class we're missing:

```
    public static final Number coerceToNumber(final Object obj,
            final Class<?> type) throws ELException {
        return coerceToNumber(null, obj, type);
    }
```

I believe the best route to do here is to just update `ValidateVisitor` to call `coerceToNumber(null, obj, type);`

**Comment by pnicolucci** [comment]
My initial thought here is that the ELSupport helper methods were reduced as this one that is missing isn't really giving anything helpful.

**Comment by pnicolucci** [comment]
The `com.ibm.ws.jsp` component depends on el 2.2 which only has the following:

```
public static final Number coerceToNumber(Object obj) {
    if (obj == null)
      return ZERO; 
    if (obj instanceof Number)
      return (Number)obj; 
    String str = coerceToString(obj);
    if (isStringFloat(str))
      return toFloat(str); 
    return toNumber(str);
  }
  
  protected static final Number coerceToNumber(Number number, Class<?> type) throws ELException {
    if (long.class == type || Long.class.equals(type))
      return new Long(number.longValue()); 
    if (double.class == type || Double.class.equals(type))
      return new Double(number.doubleValue()); 
    if (int.class == type || Integer.class.equals(type))
      return new Integer(number.intValue()); 
    if (BigInteger.class.equals(type)) {
      if (number instanceof BigDecimal)
        return ((BigDecimal)number).toBigInteger(); 
      if (number instanceof BigInteger)
        return number; 
      return BigInteger.valueOf(number.longValue());
    } 
    if (BigDecimal.class.equals(type)) {
      if (number instanceof BigDecimal)
        return number; 
      if (number instanceof BigInteger)
        return new BigDecimal((BigInteger)number); 
      return new BigDecimal(number.doubleValue());
    } 
    if (byte.class == type || Byte.class.equals(type))
      return new Byte(number.byteValue()); 
    if (short.class == type || Short.class.equals(type))
      return new Short(number.shortValue()); 
    if (float.class == type || Float.class.equals(type))
      return new Float(number.floatValue()); 
    if (Number.class.equals(type))
      return number; 
    throw new ELException(MessageFactory.get("error.convert", number, number.getClass(), type));
  }
  
  public static final Number coerceToNumber(Object obj, Class<?> type) throws ELException {
    if (obj == null || "".equals(obj))
      return coerceToNumber(ZERO, type); 
    if (obj instanceof String)
      return coerceToNumber((String)obj, type); 
    if (ELArithmetic.isNumber(obj))
      return coerceToNumber((Number)obj, type); 
    if (obj instanceof Character)
      return coerceToNumber(new Short((short)((Character)obj).charValue()), type); 
    throw new ELException(MessageFactory.get("error.convert", obj, obj.getClass(), type));
  }
  
  protected static final Number coerceToNumber(String val, Class<?> type) throws ELException {
    if (long.class == type || Long.class.equals(type))
      try {
        return Long.valueOf(val);
      } catch (NumberFormatException nfe) {
        throw new ELException(MessageFactory.get("error.convert", val, String.class, type));
      }  
    if (int.class == type || Integer.class.equals(type))
      try {
        return Integer.valueOf(val);
      } catch (NumberFormatException nfe) {
        throw new ELException(MessageFactory.get("error.convert", val, String.class, type));
      }  
    if (double.class == type || Double.class.equals(type))
      try {
        return Double.valueOf(val);
      } catch (NumberFormatException nfe) {
        throw new ELException(MessageFactory.get("error.convert", val, String.class, type));
      }  
    if (BigInteger.class.equals(type))
      try {
        return new BigInteger(val);
      } catch (NumberFormatException nfe) {
        throw new ELException(MessageFactory.get("error.convert", val, String.class, type));
      }  
    if (BigDecimal.class.equals(type))
      try {
        return new BigDecimal(val);
      } catch (NumberFormatException nfe) {
        throw new ELException(MessageFactory.get("error.convert", val, String.class, type));
      }  
    if (byte.class == type || Byte.class.equals(type))
      try {
        return Byte.valueOf(val);
      } catch (NumberFormatException nfe) {
        throw new ELException(MessageFactory.get("error.convert", val, String.class, type));
      }  
    if (short.class == type || Short.class.equals(type))
      try {
        return Short.valueOf(val);
      } catch (NumberFormatException nfe) {
        throw new ELException(MessageFactory.get("error.convert", val, String.class, type));
      }  
    if (float.class == type || Float.class.equals(type))
      try {
        return Float.valueOf(val);
      } catch (NumberFormatException nfe) {
        throw new ELException(MessageFactory.get("error.convert", val, String.class, type));
      }  
    throw new ELException(MessageFactory.get("error.convert", val, String.class, type));
  }
```

**Comment by pnicolucci** [comment]
So I think at this point there are two ways to resolve this:

1) Add the missing method to the EL 4 implementation in open liberty as an overlay
2) Get the tomcat open source to add the method back in and pull that change into open liberty when available in a release.

**Comment by pnicolucci** [comment]
Opened the following bug in tomcat to see if we can get these methods added back into ELSupport.java.
