### ISSUE TITLE
Update EclipseLink 2.7 binaries to 2.7.1

### ISSUE THREAD

**Issue by dazey3** [OpenLiberty/open-liberty#1411]
Currently, OpenLiberty is using the 2.7 WAS branch for the EclipseLink binary source control. This branch is  a separate branch, source controlled by the WAS JPA team. For JPA 2.2, we are deviating from this strategy and I am updating EclipseLink to use the official release tags EclipseLink 2.7 service branch uses.

Code changes between current 2.7.1_WAS and 2.7.1 include:

- [Bug 525526: upgrade to ASM 6.0 final](https://bugs.eclipse.org/bugs/show_bug.cgi?id=525526)
- [Bug 521954: Eclipselink 2.7 is not able to parse ORM XML files using the 2.2 schema](https://bugs.eclipse.org/bugs/show_bug.cgi?id=521954)
- [Bug 525854 - Fix Java SE platform detection and clean up platform code](https://bugs.eclipse.org/bugs/show_bug.cgi?id=525854)
- [Bug 414974: allow eclipselink.archive.factory and eclipselink.target-server to be specified as an integration property](https://bugs.eclipse.org/bugs/show_bug.cgi?id=414974)
- [Bug 508974: NPE in DirectCollectionMapping.compareListsForChange](https://bugs.eclipse.org/bugs/show_bug.cgi?id=508974)
- [Bug 525402 - StaticWeaveProcessor must ignore module-info.class in Java 9](https://bugs.eclipse.org/bugs/show_bug.cgi?id=525402)
- [Bug 291546 - Performance degradation due to usage of Vector in DescriptorEventManager](https://bugs.eclipse.org/bugs/show_bug.cgi?id=291546)
- [Bug 522635 - ConcurrentModificationException when triggering lazy load from conforming query](https://bugs.eclipse.org/bugs/show_bug.cgi?id=522635)
- [Bug 510204 - Temporary StdErrLogger code removal - Fixed java.lang.ClassCircularityError](https://bugs.eclipse.org/bugs/show_bug.cgi?id=510204)
- [Bug 522635 - Reverting IdentityMap#elements() return type to plain Enumeration](https://bugs.eclipse.org/bugs/show_bug.cgi?id=522635)

**Comment by daliasheasha** [comment]
Changes were delivered under: https://github.com/OpenLiberty/open-liberty/pull/1461
