### ISSUE TITLE
Changes between mpConfig 1.4->2.0 need documenting

### ISSUE THREAD

**Issue by Joseph-Cass** [OpenLiberty/open-liberty#14138]
Changing from Liberty's implementation of MicroProfile Config in mpConfig 1.4 to SmallRye's implementation in mpConfig 2.0 will alter functionality outside of MicroProfile's specification. 

These changes need to be clearly listed and documented.

**Comment by Joseph-Cass** [comment]
Differences from 1.4 -> 2.0:

- Liberty's additional default converters will no longer be available:
  - mpConfig 1.1
    - AtomicIntegerConverter
    - AtomicLongConverter
    - AutomaticConverter
    - BitSetConverter
    - CurrencyConverter
    - DateTimeConverter
    - IdentityConverter
    - InstantConverter
    - OptionalConverter
    - URIConverter
    - URLConverter
  - mpConfig 1.2
    - ClassConverter
    - ListConverter
    - SetConverter
  - mpConfig 1.4
    - CharacterConverter

**Comment by tevans78** [comment]
An Injected SmallRye Config is not serializable if all of it's ConfigSources are not serializable: https://github.com/smallrye/smallrye-config/issues/405

**Comment by Joseph-Cass** [comment]
Currently, when a ConfigProperty is Injected for a type with no converter, the error message references where and which property is failing its injection. For 2.0, a "No converter" error is thrown, but it does not say where from. This could be a future enhancement to the 2.0 code.

**Comment by Joseph-Cass** [comment]
SmallRye implementation doesn't have methods for accessing cache for ConfigProviderResolver. e.g. getConfigCacheSize(), hence the following FATs don't run anymore: https://github.com/OpenLiberty/open-liberty/blob/1768c73fdb36b0a72e06213e84bc88a969b7f0ed/dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/ClassLoaderCacheTest.java

**Comment by Joseph-Cass** [comment]
This is being written up more formally here: https://github.com/OpenLiberty/open-liberty/issues/14709

**Comment by tevans78** [comment]
This issue was replaced by #14709
