### ISSUE TITLE
Missing Exported Version in io.openliberty.faces.internal 

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#14133]
When looking at the **io.openliberty.faces.internal**  manifest.mf, the following are exported:
```
org.apache.myfaces.cdi.util;version="[3.0,4)",
org.apache.myfaces.config.annotation;version="[3.0,4)",
org.apache.myfaces.ee;version="[3.0,4)",
org.apache.myfaces.shared.util, <- not sure why this doesn't have a version? 
org.apache.myfaces.spi;version="[3.0,4)",
org.apache.myfaces.util;version="[3.0,4)",
org.apache.myfaces.webapp;version="[3.0,4)",
```

_Originally posted by @volosied in https://github.com/OpenLiberty/open-liberty/pull/13839#discussion_r490489647_

**Comment by volosied** [comment]
Correction: Imported, Not exported:

Import-Package: ....
 org.apache.myfaces.cdi.util;version="[3.0,4)",org.apache.myfaces.conf
 ig.annotation;version="[3.0,4)",org.apache.myfaces.ee;version="[3.0,4
 )",**org.apache.myfaces.shared.util**,org.apache.myfaces.spi;version="[3.
 0,4)",org.apache.myfaces.util;version="[3.0,4)",org.apache.myfaces.we
 bapp;version="[3.0,4)",org.osgi.framework;version="[1.9,2)",org.osgi.
 service.component;version="[1.4,2)",jakarta.faces.webapp;version="[3.
 0,4.0)"

**Comment by volosied** [comment]
org.apache.myfaces.shared.util is part of the shared-public bundle: https://github.com/apache/myfaces/tree/2.3.x/shared-public/src/main/java/org/apache/myfaces/shared/util

It's don't see it exported by the impl jar, which explains why it doesn't have a version associated with it

**Comment by pnicolucci** [comment]
@volosied how does our MyFaces 2.3 bundle look? Does that have a version associated with it? If not then I think we're likely fine to leave this as is for 3.0. Let me know!

**Comment by volosied** [comment]
I don't see any differencees, even when building with 2.3.7:

 ache.myfaces.config.annotation;version="[2.3,3)",org.apache.myfaces.e
 e;version="[2.3,3)",**org.apache.myfaces.shared.util**,org.apache.myfaces
 .spi;version="[2.3,3)",org.apache.myfaces.util;version="[2.3,3)",org.

And transformed:
 ig.annotation;version="[3.0,4)",org.apache.myfaces.ee;version="[3.0,4
 )",**org.apache.myfaces.shared.util**,org.apache.myfaces.spi;version="[3.
 0,4)",org.apache.myfaces.util;version="[3.0,4)",org.apache.myfaces.we

**Comment by pnicolucci** [comment]
Go ahead and close, good investigation here.
