### ISSUE TITLE
Expression Language 3.0 value lookup performance improvement

### ISSUE THREAD

**Issue by epj** [OpenLiberty/open-liberty#14175]
Lookup performance can be improved for certain Expression Language 3.0 values.  By optimizing EL 3.0 context handling and classloader calls, the evaluations of EL unscoped and static expressions perform better with this fix.  This is a port of Apache bug fix 62453.  Also includes Apache bug 63781 to support multiple java levels correctly.

**Comment by pnicolucci** [comment]
@epj can you be a bit more specific as to what improvements you're looking to make to the Expression Language? Which version of the expression language are you updating? Is there a corresponding change in the open source?

Or is this a change to the JSP engine?
