### ISSUE TITLE
Feature Test Summary for OpenAPI 2.0

### ISSUE THREAD

**Issue by scottcurtis2605** [OpenLiberty/open-liberty#14186]
Epic: #11020 

**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

## Test Summary for Open Liberty OpenAPI 2.0
For the introduction of the OpenAPI 2.0 feature, we aimed to maximise code coverage through automated FAT and TCK tests through various means. This strategy involved three steps: 

1. Executing the Eclipse [Microprofile OpenAPI TCKs](https://github.com/eclipse/microprofile-open-api/tree/master/tck) specific to 2.0's new functionality. This is detailed in the **New OpenAPI 2.0 Features** section of the summary.

2. Updating the existing [test bucket from OpenAPI 1.x](https://github.com/eclipse/microprofile-open-api/tree/master/tck) to repeat 1.x tests against 2.0, and implementing new 1.x tests to maximise compatibility for the [SmallRye](https://github.com/smallrye/smallrye-open-api) implementation of OpenAPI 2.0. This is detailed in the **OpenAPI 1.x Repeated FATs** section of the summary.

3. Implementing a [new FAT bucket](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.microprofile.openapi.2.0.internal_fat) specifically for 2.0, testing what we believed necessary. This is detailed in the **OpenAPI 2.0 Specific FATs** section of the summary.

## New OpenAPI 2.0 Features
Below is the list of new features exclusive to OpenAPI 2.0 (taken from the [2.0 release notes](https://download.eclipse.org/microprofile/microprofile-open-api-2.0-RC3/microprofile-openapi-spec.html#release_notes_20)), each followed by a sub-list of the PRs from the [MicroProfile Open Api TCKs](https://github.com/eclipse/microprofile-open-api/tree/master/tck) which test the feature. These TCKs are ran from the [io.openliberty.microprofile.openapi.2.0.internal_fat_tck ](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.microprofile.openapi.2.0.internal_fat_tck) bucket.

### [API/SPI Changes](https://download.eclipse.org/microprofile/microprofile-open-api-2.0-RC3/microprofile-openapi-spec.html#_apispi_changes)
- The `@SchemaProperty` annotation has been added to allow the properties for a schema to be defined 
&nbsp;&nbsp;&nbsp;&nbsp;- [This PR](https://github.com/eclipse/microprofile-open-api/pull/384) includes updates to an example application. The [JAXRSApp](https://github.com/MikeEdgar/microprofile-open-api/blob/d214d04881c40fc9464f758e501f3829683fd93d/tck/src/main/java/org/eclipse/microprofile/openapi/apps/airlines/JAXRSApp.java#L97) and [AirlinesAppTest](https://github.com/MikeEdgar/microprofile-open-api/blob/d214d04881c40fc9464f758e501f3829683fd93d/tck/src/main/java/org/eclipse/microprofile/openapi/tck/AirlinesAppTest.java#L666) classes now implement a single test to validate inline schema definitions with `@SchemaProperty`.

- The `@RequestBodySchema` annotation has been added to provide a shorthand mechanism to specify the schema for a request body. 
&nbsp;&nbsp;&nbsp;&nbsp;- [This PR](https://github.com/eclipse/microprofile-open-api/pull/410) includes updates to an example application. The [PetResource](https://github.com/MikeEdgar/microprofile-open-api/blob/6f3b3f89a826469d8230dd18ee1fcbac99b67012/tck/src/main/java/org/eclipse/microprofile/openapi/apps/petstore/resource/PetResource.java#L458) and [PetStoreAppTest](https://github.com/MikeEdgar/microprofile-open-api/blob/6f3b3f89a826469d8230dd18ee1fcbac99b67012/tck/src/main/java/org/eclipse/microprofile/openapi/tck/PetStoreAppTest.java#L216) classes now implement a single test to validate positive `@RequestBodySchema` POST functionality from a client perspective.

- The `@APIResponseSchema` annotation has been added to provide a shorthand mechanism to specify the schema for a response body.
&nbsp;&nbsp;&nbsp;&nbsp;- [This PR](https://github.com/eclipse/microprofile-open-api/pull/410) includes updates to an example application. The [PetResource](https://github.com/MikeEdgar/microprofile-open-api/blob/6f3b3f89a826469d8230dd18ee1fcbac99b67012/tck/src/main/java/org/eclipse/microprofile/openapi/apps/petstore/resource/PetResource.java) and [PetStoreAppTest](https://github.com/MikeEdgar/microprofile-open-api/blob/6f3b3f89a826469d8230dd18ee1fcbac99b67012/tck/src/main/java/org/eclipse/microprofile/openapi/tck/PetStoreAppTest.java) classes now implement two tests to validate `@APIResponseSchema` positive POST and GET functionality from a client perspective.

- The `mp.openapi.schema.*` MicroProfile Config property has been added to allow the schema for a specific class to be specified. This property would typically be used in cases where the application developer does not have access to the source code of a class.
&nbsp;&nbsp;&nbsp;&nbsp;- [This PR](https://github.com/eclipse/microprofile-open-api/pull/403) includes updates to an example application. The [PetStoreApp](https://github.com/MikeEdgar/microprofile-open-api/blob/c79ad357ad77e63e64652a49de95f5ae14597670/tck/src/main/java/org/eclipse/microprofile/openapi/apps/petstore/PetStoreApp.java), [OASConfigSchemaTest](https://github.com/MikeEdgar/microprofile-open-api/blob/c79ad357ad77e63e64652a49de95f5ae14597670/tck/src/main/java/org/eclipse/microprofile/openapi/tck/OASConfigSchemaTest.java#L47), and [schema-microprofile-config.properties](https://github.com/MikeEdgar/microprofile-open-api/blob/c79ad357ad77e63e64652a49de95f5ae14597670/tck/src/main/resources/schema-microprofile-config.properties) classes were updated to provide a test to validate positive class Schema Registration without access to a class source by using `mp.openapi.schema.*`. 

### [Functional Changes](https://download.eclipse.org/microprofile/microprofile-open-api-2.0-RC3/microprofile-openapi-spec.html#_functional_changes)
- Getter methods on model interfaces that return a list or map now return a copy of the list/map containing the same items. This list/map CAN be immutable.
&nbsp;&nbsp;&nbsp;&nbsp;- [This PR](https://github.com/eclipse/microprofile-open-api/pull/288) includes the [ModelConstructionTest](https://github.com/jmini/microprofile-open-api/blob/3f92f469d88e7ecf3d6f4fbefee857bfa26ba2a5/tck/src/main/java/org/eclipse/microprofile/openapi/tck/ModelConstructionTest.java) class to validate immutability holds on `list/map` collections containing `openapi/models/` interfaces.

- Setter methods on model interfaces that take a list or a map as a parameter MUST not use the list/map instance directly.
&nbsp;&nbsp;&nbsp;&nbsp;- [This PR](https://github.com/eclipse/microprofile-open-api/pull/293) includes updates to the [ModelConstructionTest](https://github.com/jmini/microprofile-open-api/blob/3f92f469d88e7ecf3d6f4fbefee857bfa26ba2a5/tck/src/main/java/org/eclipse/microprofile/openapi/tck/ModelConstructionTest.java) class (as modified above) to to ensure `list/map` setters can accept immutable `list/maps`.

### [Other Changes](https://download.eclipse.org/microprofile/microprofile-open-api-2.0-RC3/microprofile-openapi-spec.html#_other_changes)
- JavaDoc updates to clarify the behaviour of getter methods on model interfaces that return a list or map.
&nbsp;&nbsp;&nbsp;&nbsp;- [This PR](https://github.com/eclipse/microprofile-open-api/pull/288) contains updates for this feature. Of course, no tests for JavaDocs.

- TCK updates to verify that getter methods on model interfaces return a list or map, return a copy of underlying collection.
&nbsp;&nbsp;&nbsp;&nbsp;- Changes in [this PR](https://github.com/eclipse/microprofile-open-api/pull/288), mentioned in Functional Changes above, updates the [ModelConstructionTest](https://github.com/jmini/microprofile-open-api/blob/3f92f469d88e7ecf3d6f4fbefee857bfa26ba2a5/tck/src/main/java/org/eclipse/microprofile/openapi/tck/ModelConstructionTest.java) class to validate immutability holds on `list/map` collections containing `openapi/models/` interfaces.

## New and Updated FATs Beyond New OpenAPI 2.0 Features
The specification update between MicroProfile OpenAPI 1.1 and 2.0 has resulted in [incompatible changes](https://download.eclipse.org/microprofile/microprofile-open-api-2.0-RC3/microprofile-openapi-spec.html#_incompatible_changes). Therefore, the following [PR](https://github.com/OpenLiberty/open-liberty/pull/13589) provides new FATs exclusive to 2.0, and updates to repeat those from 1.x against 2.0.

### OpenAPI 1.x Updated FATs 
The existing OpenAPI 1.x FAT bucket, [com.ibm.ws.microprofile.openapi_fat](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.microprofile.openapi_fat), has been updated to provide coverage and compatibility for the [SmallRye](https://github.com/smallrye/smallrye-open-api) implementation of OpenAPI 2.0. This requires 1.x FATs to be repeated, and in some cases, new 2.0-compatable implementations of tests within this bucket.

The following are the 1.x tests which have been updated to be repeated against version 2.0:
  
- [ApplicationProcessorTest](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/ApplicationProcessorTest.java)
- [OpenAPIValidationTestOne](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestOne.java)
- [OpenAPIValidationTestTwo](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestTwo.java)
- [OpenAPIValidationTestThree](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestThree.java)
- [OpenAPIValidationTestFour](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestFour.java)
- [OpenAPIValidationTestFive](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestFive.java)
- [OpenAPIValidationTestSix](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestSix.java)
- [ProxySupportTest](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/ProxySupportTest.java)
- [EndpointAvailabilityTest](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/EndpointAvailabilityTest.java)
- [UICustomizationTest](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/UICustomizationTest.java)

In addition, the following 1.x classes were updated with 2.0-compatable tests to account for the SmallRye implementation differences between 1.x and 2.0. This ensures compatibility between the [com.ibm.ws.microprofile.openapi_fat](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.microprofile.openapi_fat) bucket and OpenAPI 2.0.

- [OpenAPIValidationTestOne](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestOne.java) - [testInfoValidation20](https://github.com/OpenLiberty/open-liberty/blob/e6a072e640715fd26d9229929544152767e55083/dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestOne.java#L92) to be ran in place of [testInfoValidation](https://github.com/OpenLiberty/open-liberty/blob/e6a072e640715fd26d9229929544152767e55083/dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestOne.java#L75) under OpenAPI 2.0.
- [OpenAPIValidationTestThree](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestThree.java) - [testBlankInfo20](https://github.com/OpenLiberty/open-liberty/blob/e6a072e640715fd26d9229929544152767e55083/dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestThree.java#L71) to be ran in place of [testBlankInfo](https://github.com/OpenLiberty/open-liberty/blob/e6a072e640715fd26d9229929544152767e55083/dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/validation/fat/OpenAPIValidationTestThree.java#L61) under OpenAPI 2.0.

- [ApplicationProcessorTest](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/ApplicationProcessorTest.java) class has been duplicated accross to the [2.0 bucket](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/ApplicationProcessorTest.java), due to the necessity of underlying environment changes to execute [testCompleteFlow](https://github.com/OpenLiberty/open-liberty/blob/4f9a23c3ddd68e4ae69605b550e2642290270808/dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/ApplicationProcessorTest.java#L89) against 2.0. The remaining tests within [ApplicationProcessorTest](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/ApplicationProcessorTest.java) are natively ran within the 1.x bucket, against 2.0.

### OpenAPI 2.0 Specific FATs 
The following FAT test classes present in the [io.openliberty.microprofile.openapi.2.0.internal_fat](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.microprofile.openapi.2.0.internal_fat) bucket from the [FATSuite](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/FATSuite.java).

- [CacheTest](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/cache/CacheTest.java), which tests scenarios involving the model cache; this was implemented to improve performance by avoiding rescans of classes upon server restart.
- [DeploymentTest](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/DeploymentTest.java), which tests scenarios which were previously missing in previous buckets - these ensure OpenAPI works correctly when the app is deployed in different formats (ear, war, etc.).

## As a team
**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

As per @tevans78's comment, "We discussed at length and agreed, on average, a score of 4".

**Comment by tevans78** [comment]
We discussed at length and agreed, on average, a score of 4.

**Comment by ayoho** [comment]
Additional negative scenarios are being added to the TCK and being tracked by https://github.com/smallrye/smallrye-open-api/issues/621. With those appearing to be in hand, I'll go ahead and close out this test summary.
