### ISSUE TITLE
WAS Liberty Profile console log buffer limit prevents logDNA from parsing 8k+ log entries correctly

### ISSUE THREAD

**Issue by guang-shi** [OpenLiberty/open-liberty#14197]
We are integrating Business Analytics (Cognos) logging with logDNA in IBMCloud. We are using log4j2's ConsoleAppender with JSONLayout to log to System.out. 
Json log entries over 8k are broken up into chunks which doesn't allow logDNA to parse the 8k+ log entries correctly. 
There was a similar issue https://github.com/OpenLiberty/open-liberty/issues/6095 fixed in 19.0.0.5. But we are still seeing it in WLP 20.0.0.7.

[messages.log](https://github.com/OpenLiberty/open-liberty/files/5293548/messages.log)

**Steps to Reproduce**
1. Configure log4j2 ConsoleAppender with the JSONLayout
<Appenders>
	<Console name="consoleAppender" target="SYSTEM_OUT">
		<JSONLayout properties="true" complete="false" compact="false"/>
	</Console>
</Appenders>
2. Generate a log with stacktrace

**Expected behavior**
Expected: There should be one log entry with json format
Actual: the log entry was broken up into 3 chunks (see attached messages.log file)

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.7

 - Java Version:
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 8.0.6.0 - pxa6480sr6-20191107_01(SR6))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20191106_432135 (JIT enabled, AOT enabled)
OpenJ9   - f0b6be7
OMR      - 18d8f94
IBM      - 233dfb5)
JCL - 20191016_01 based on Oracle jdk8u231-b10

 - server.xml configuration (WITHOUT sensitive information like passwords)
n/a

 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`
messages.log attached.

**Additional context**
n/a

**Comment by Yushan-Lin** [comment]
@guang-shi do you have more information about how your log4j configuration looks like and how the exception is being logged? I can't reproduce the issue.

**Comment by guang-shi** [comment]
@Yushan-Lin sure. here is our log4j ConsoleAppender configuration:
<Appenders>
	<Console name="consoleAppender" target="SYSTEM_OUT">
		<JSONLayout properties="true" complete="false" compact="false"/>
	</Console>
</Appenders>
We use SLF4J in our microservice and our common logging component provides the log4j binding through log4j-slf4j-impl-2.7.jar
In my test, I just log an exception with stacktrace to generate large json log entry.

**Comment by Yushan-Lin** [comment]
@guang-shi It looks like log4j 2 chunks the logs before it's directed to Liberty.
I reproduced the issue and this is the trace:
```
16:30:01.401 0x13896400       j9trc_aux.1        - [9] java.io.PrintStream.write (PrintStream.java:561) (Compiled Code)
16:30:01.401 0x13896400       j9trc_aux.1        - [10] org.apache.logging.log4j.core.util.CloseShieldOutputStream.write (CloseShieldOutputStream.java:53)
16:30:01.401 0x13896400       j9trc_aux.1        - [11] org.apache.logging.log4j.core.appender.OutputStreamManager.writeToDestination (OutputStreamManager.java:262)
16:30:01.401 0x13896400       j9trc_aux.1        - [12] org.apache.logging.log4j.core.appender.OutputStreamManager.flushBuffer (OutputStreamManager.java:294)
16:30:01.401 0x13896400       j9trc_aux.1        - [13] org.apache.logging.log4j.core.appender.OutputStreamManager.drain (OutputStreamManager.java:351)
16:30:01.401 0x13896400       j9trc_aux.1        - [14] org.apache.logging.log4j.core.layout.TextEncoderHelper.drainIfByteBufferFull (TextEncoderHelper.java:260)
16:30:01.401 0x13896400       j9trc_aux.1        - [15] org.apache.logging.log4j.core.layout.TextEncoderHelper.writeAndEncodeAsMuchAsPossible (TextEncoderHelper.java:199)
16:30:01.401 0x13896400       j9trc_aux.1        - [16] org.apache.logging.log4j.core.layout.TextEncoderHelper.writeChunkedEncodedText (TextEncoderHelper.java:112)
16:30:01.401 0x13896400       j9trc_aux.1        - [17] org.apache.logging.log4j.core.layout.TextEncoderHelper.writeEncodedText (TextEncoderHelper.java:79)
16:30:01.401 0x13896400       j9trc_aux.1        - [18] org.apache.logging.log4j.core.layout.TextEncoderHelper.encodeChunkedText (TextEncoderHelper.java:143)
16:30:01.401 0x13896400       j9trc_aux.1        - [19] org.apache.logging.log4j.core.layout.TextEncoderHelper.encodeText (TextEncoderHelper.java:58)
16:30:01.401 0x13896400       j9trc_aux.1        - [20] org.apache.logging.log4j.core.layout.StringBuilderEncoder.encode (StringBuilderEncoder.java:68)
16:30:01.401 0x13896400       j9trc_aux.1        - [21] org.apache.logging.log4j.core.layout.StringBuilderEncoder.encode (StringBuilderEncoder.java:32)
16:30:01.401 0x13896400       j9trc_aux.1        - [22] org.apache.logging.log4j.core.layout.PatternLayout.encode (PatternLayout.java:219)
16:30:01.401 0x13896400       j9trc_aux.1        - [23] org.apache.logging.log4j.core.layout.PatternLayout.encode (PatternLayout.java:57)
16:30:01.401 0x13896400       j9trc_aux.1        - [24] org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent (AbstractOutputStreamAppender.java:177)
16:30:01.401 0x13896400       j9trc_aux.1        - [25] org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend (AbstractOutputStreamAppender.java:170)
16:30:01.401 0x13896400       j9trc_aux.1        - [26] org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append (AbstractOutputStreamAppender.java:161)
16:30:01.401 0x13896400       j9trc_aux.1        - [27] org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender (AppenderControl.java:156)
16:30:01.401 0x13896400       j9trc_aux.1        - [28] org.apache.logging.log4j.core.config.AppenderControl.callAppender0 (AppenderControl.java:129)
16:30:01.401 0x13896400       j9trc_aux.1        - [29] org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion (AppenderControl.java:120)
16:30:01.401 0x13896400       j9trc_aux.1        - [30] org.apache.logging.log4j.core.config.AppenderControl.callAppender (AppenderControl.java:84)
16:30:01.401 0x13896400       j9trc_aux.1        - [31] org.apache.logging.log4j.core.config.LoggerConfig.callAppenders (LoggerConfig.java:448)
16:30:01.401 0x13896400       j9trc_aux.1        - [32] org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent (LoggerConfig.java:433)
16:30:01.401 0x13896400       j9trc_aux.1        - [33] org.apache.logging.log4j.core.config.LoggerConfig.log (LoggerConfig.java:417)
16:30:01.401 0x13896400       j9trc_aux.1        - [34] org.apache.logging.log4j.core.config.LoggerConfig.log (LoggerConfig.java:403)
16:30:01.401 0x13896400       j9trc_aux.1        - [35] org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log (AwaitCompletionReliabilityStrategy.java:63)
16:30:01.401 0x13896400       j9trc_aux.1        - [36] org.apache.logging.log4j.core.Logger.logMessage (Logger.java:146)
16:30:01.401 0x13896400       j9trc_aux.1        - [37] org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage (AbstractLogger.java:2116)
16:30:01.401 0x13896400       j9trc_aux.1        - [38] org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely (AbstractLogger.java:2100)
16:30:01.401 0x13896400       j9trc_aux.1        - [39] org.apache.logging.log4j.spi.AbstractLogger.logMessage (AbstractLogger.java:1994)
16:30:01.401 0x13896400       j9trc_aux.1        - [40] org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled (AbstractLogger.java:1966)
16:30:01.401 0x13896400       j9trc_aux.1        - [41] org.apache.logging.log4j.spi.AbstractLogger.debug (AbstractLogger.java:317)
16:30:01.401 0x13896400       j9trc_aux.1        - [42] application.servlet.LibertyServletLog4.doGet (LibertyServletLog4.java:52)
```
It looks like the chunking is being done in:
https://github.com/apache/logging-log4j2/blob/6bdc516b0779a4a1746b6ff56294088d359fc523/log4j-core/src/main/java/org/apache/logging/log4j/core/layout/TextEncoderHelper.java#L58 and
https://github.com/apache/logging-log4j2/blob/6bdc516b0779a4a1746b6ff56294088d359fc523/log4j-core/src/main/java/org/apache/logging/log4j/core/layout/StringBuilderEncoder.java#L68

It looks like the default buffer size is 8k and it gets chunked before the log gets to Liberty.

**Comment by guang-shi** [comment]
@Yushan-Lin Are you using the log4j's ConsoleAppender which writes to stdout? It supposed to be unbuffered if I understand their doc correctly: https://logging.apache.org/log4j/2.x/manual/cloud.html

**Comment by Yushan-Lin** [comment]
@guang-shi I'm using the console appender. This is my log4j 2 configuration :
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
  <Properties>
	   <Property name="log-path">logs</Property>
  </Properties>
  
  <appenders>

    <Console name="STDOUT" target="SYSTEM_OUT">
    </Console>
  </appenders>
  <Loggers>
    <Logger name="application.servlet.LibertyServlet" level="debug">
      <AppenderRef ref="STDOUT"/>
    </Logger>
    <Root level="debug">
      <AppenderRef ref="STDOUT"/>
    </Root>
  </Loggers>
</Configuration>
```

**Comment by guang-shi** [comment]
@Yushan-Lin ok, can you try the JSONLayout for the ConsoleAppender instead of the default PatternLayout? I wonder if it goes through the same code path. thanks
`<JSONLayout properties="true" complete="false" compact="false"/>`

**Comment by Yushan-Lin** [comment]
@guang-shi I tried to reproduce your situation and realized that the log4j-slf4j-impl-2.7 does chunk the stack trace:
[messages.log](https://github.com/OpenLiberty/open-liberty/files/5308067/messages.log)

If you upgrade to the latest version of the api 2.13.3, you won't have this issue.
[message_2.13.3.log](https://github.com/OpenLiberty/open-liberty/files/5308061/message_2.13.3.log)

**Comment by guang-shi** [comment]
@Yushan-Lin wow, thank you so much for finding the root cause of this! I will definitely try 2.13.3 on our side. Please feel free to close the issue. Thanks again!

**Comment by hmozaffari** [comment]
> @Yushan-Lin Are you using the log4j's ConsoleAppender which writes to stdout? It supposed to be unbuffered if I understand their doc correctly: https://logging.apache.org/log4j/2.x/manual/cloud.html

I also faced same issue with Liberty version 19.0.0.5 and Log4j2 2.16. Log4j claims it is unbuffered but "ConsoleAppender" is extending "AbstractOutputStreamAppender" which is buffered. I ended up using "log4j.encoder.byteBufferSize" system variable and increased the buffer size.

**Comment by Kadams64** [comment]
This string buffer size issue still exists up to Log4j2 2.20.0 and Liberty version 23.0.0.1

The related code in log4j2 2.20 can be found here=>  [log4j-core/util/Constants.java ](https://github.com/apache/logging-log4j2/blob/release-2.x/log4j-core/src/main/java/org/apache/logging/log4j/core/util/Constants.java)(log4j2 GitHub)
- and this specific block of code, where the default value is clearly `8 x 1024` bytes:
```
    /**
     * Default size of ByteBuffers used to encode LogEvents without allocating temporary objects.
     * <p>
     * The default value is {@value}, users can override with system property "log4j.encoder.byteBufferSize".
     * </p>
     * @see org.apache.logging.log4j.core.layout.ByteBufferDestination
     * @since 2.6
     */
    public static final int ENCODER_BYTE_BUFFER_SIZE = size("log4j.encoder.byteBufferSize", 8 * 1024);
```

I confirmed that this can be 'worked around' by setting the `log4j.encoder.byteBufferSize` system property as per @hmozaffari 's comment above.  For example, adding this to the Liberty `jvm.options` will set the string buffer size to 128 KB

`-Dlog4j.encoder.byteBufferSize=131072`

However, I don't consider this to be a 'fix' as it will still fail with messages that exceed the configured buffer size.

A proper (?) fix would be for Liberty's log interceptor to have some additional intelligence so that structured (JSON) messages coming from applications via log4j2 are correctly recognized even if they are sent in 'blocks'
- note that I'm observing that log4j2's 'chunking' of messages breaks Liberty's ability to 'pass through' application JSON messages 
- i.e.: `WLP_LOGGING_APPS_WRITE_JSON=true` /` appsWriteJson= true` doesn't work if log4j2 chunks a message
- ... and Liberty's interceptor 'wraps' such messages in a way that effectively breaks proper message aggregation e.g.: via EFK or LokiStack

**Comment by Kadams64** [comment]
As this issue is closed, I've opened a new defect/bug for the issue in my comment above=> https://github.com/OpenLiberty/open-liberty/issues/24460
