### ISSUE TITLE
Redeploy applications when shared library is changed

### ISSUE THREAD

**Issue by Thihup** [OpenLiberty/open-liberty#14208]
I was using the loose application and the dev experience is great. Always redeploys the application correctly.

However, I need to extract some libraries that I declared it at the loose application in a shared library because it is used by more than one application.
With this change now I have to always restart the Open Liberty to it load the changes.

This makes the dev experience unpleasant. Is there any configuration or something to have the same redeploy as in the loose application?

**Comment by cherylking** [comment]
Hello @Thihup, glad to hear you are having a good dev experience for the most part. I wanted to follow up with a couple of clarifying questions.

1) Are you using the liberty-maven-plugin to build/deploy your application to Liberty?
2) If yes to the first question, are you aware of `dev` mode? This is a goal that creates the Liberty server, installs the features and deploys the application before starting the server for you. See more info here: https://github.com/OpenLiberty/ci.maven/blob/master/docs/dev.md#dev
3) Finally, if you are using `dev` mode, please see the `copyDependencies` parameter that we've added in our most recent milestones (https://github.com/OpenLiberty/ci.maven/releases/tag/liberty-maven-3.3-M3)

Please note that if the changes in the shared library require no change to the pom.xml plugin configuration, then those changes will still not be picked up by `dev` mode. If however you add something to the `copyDependencies` configuration or change a version in the GAV coordinate, those should be picked up.

**Comment by Thihup** [comment]
Unfortunately, I'm unable to use the liberty dev mode. I have to use the installed server because ours is a legacy app that we cannot migrate to a Maven or Gradle project to use that. 
Our application is constructed at `apps/app.war.xml` and declared at server.xml.

The server.xml is basically:
```xml
<server>
    <library name="global">
       <fileset dir="${server.config.dir}/libs" includes="*.jar" />
    </library>
   <webApplication id="id" location="${server.config.dir}/apps/app.war>
       <classloader />
   </webApplication>
</server>
```

app.war.xml
```
<archive>
    <dir targetInArchive="/WEB-INF/lib" sourceOnDisk="${server.config.dir}/libs" />
</archive>
```
And the second app is in the dropins folder, using the libraries from the shared library.

If we declare the dependencies at the loose application XML, it works great, because whenever we change some jar the app is redeployed, but using the shared libraries, that behavior doesn't happen.

**Comment by Thihup** [comment]
Our solution was to use a loose application as an EAR and put the libraries in the "libs" folder, so when we change any library all applications will be redeployed
