### ISSUE TITLE
The jwt-1.0 feature will expose remote API to return JWT for authenticated user

### ISSUE THREAD

**Issue by chunlongliang-ibm** [OpenLiberty/open-liberty#1421]
Liberty jwt-1.0 feature can build JWT from jwtBuilder configuration attribute and provided user identity. This new issue is to provide capability that remote client can authenticate to jwt-1.0 feature and receive JWT based on authenticated credential. Here are the necessary setup and steps for remote client to exchange authenticated credential for JWT.
1.  Configure jwt-1.0 feature and define jwtBuild configuration. For example
<featureManager>
    <feature>jwt-1.0</feature>
    ...
</featureManager>
<jwtBuilder id="defaultJWT" signatureAlgorithm="RS256">
</jwtBuilder>

with this configuration, the jwtBuilder of "defaultJWT" will expose JWT building API like this
https://<host_name>:<ssl_port>/jwt/ibm/api/<jwtBuilder_configuration_id>/jwt
2.  Client application can call above API to exchange authenticated credential for JWT.

**Comment by brutif** [comment]
completed on #1472
