### ISSUE TITLE
Update JSP core ELSupport method calls and remove overlays in EL 4.0 implementation

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#14232]
Changes in open liberty proposed here: https://github.com/OpenLiberty/open-liberty/issues/14111

https://bz.apache.org/bugzilla/show_bug.cgi?id=64778

**Comment by pnicolucci** [comment]
Alternatively if tomcat doesn't restore the methods in the EL implementation we may be able to add the ValidateVisitor class to the jsp 2.3 bundle calling into the new methods for jsp 2.3 + and update the 3.0 EL implementation to a newer version or at least update ELSupport to the latest version.

**Comment by volosied** [comment]
BZ Issue 64778 marked as WONTFIX

**Comment by pnicolucci** [comment]
Making this change looks less and less likely as I look further into it. The new methods for example:

 ```
public static final String coerceToString(final ELContext ctx, final Object obj) {

        if (ctx != null) {
            boolean originalIsPropertyResolved = ctx.isPropertyResolved();
            try {
                Object result = ctx.getELResolver().convertToType(ctx, obj, String.class);
                if (ctx.isPropertyResolved()) {
                    return (String) result;
                }
            } finally {
                ctx.setPropertyResolved(originalIsPropertyResolved);
            }
        }

        if (obj == null) {
            return "";
        } else if (obj instanceof String) {
            return (String) obj;
        } else if (obj instanceof Enum<?>) {
            return ((Enum<?>) obj).name();
        } else {
            return obj.toString();
        }
    }
```

The above uses `ctx.getELResolver().convertToType(ctx, obj, String.class);` and the `convertToType` is new to EL 3.0.
