### ISSUE TITLE
How detect when an ExecutorService is shutdown?

### ISSUE THREAD

**Issue by Thihup** [OpenLiberty/open-liberty#14241]
Currently, I'm getting the CWWKE1202E error, meaning that we are submitting tasks after the executor has been shut down. 
However, I'd like to know if there is a way to detect that the executor was shutdown.
There is a method called `ExecutorService.isShutdown()`, but it always throws IllegalStateException.
Digging the code, it is something like this:

ManagedExecutorServiceImpl
```
public boolean isShutdown() {
        if (this.allowLifeCycleMethods) {
            return this.getNormalPolicyExecutor().isShutdown();
        } else {
            throw new IllegalStateException(new UnsupportedOperationException("isShutdown"));
        }
    }
```

So, I'd like to know how to _allow lifecycle methods_ to be enabled.

**Comment by aguibert** [comment]
Any unmanaged executors can be shutdown (e.g. `Executors.newFixedThreadPool(x)`) but any managed executors (i.e. executors obtained via `@Inject` or JNDI lookup) cannot be shut down according to the spec.

When you are using a ManagedExecutorService (or ManagedScheduledExecutorService) it will be backed by the Liberty thread pool and never needs to be explicitly shut down because it will automatically be shutdown when liberty itself shuts down.

**Comment by Thihup** [comment]
Sure! In my case I don't need to shutdown the ExecutorService, I just wanna know if it was already shut down by the server so I won't submit more tasks. 
Something like this: 
```
if (!executor.isShutdown())
   executor.submit(() -> {})
```

**Comment by aguibert** [comment]
how are you obtaining the executor service? If it's a managed executor service variant, it'll never be shutdown unless the server itself is shut down

**Comment by Thihup** [comment]
I'm getting the Executor service via JNDI. The error occurs when the server is shutting down.
```java
ExecutorService executor = InitialContext.doLookup("java:comp/DefaultManagedExecutorService");
while (true) {
    if (!executor.isShutDown())
        executor.submit(() -> {})
    Thread.sleep(2000);
}
```

**Comment by aguibert** [comment]
This is according to the EE Concurrency spec section 3.1.6: https://github.com/eclipse-ee4j/concurrency-api/blob/master/specification/src/main/asciidoc/jakarta-concurrency.adoc#316-lifecycle

Which states:

> The lifecycle of a ManagedExecutorService is managed by an application server. All lifecycle operations on the ManagedExecutorService interface will throw a java.lang.IllegalStateException exception. This includes the following methods that are defined in the java.util.concurrent.ExecutorService interface: awaitTermination(), isShutdown(), isTerminated(), shutdown(), and shutdownNow()

So basically you can assume a ManagedExecutorService will never be shutdown, so there is no need for you to check `isShutdown()` before submitting work -- just submit the work outright.

**Comment by aguibert** [comment]
I'll assume this question is answered since there hasn't been any activity in a few days. If there are still questions we can reopen or raise a new issue
