### ISSUE TITLE
BETA BLOG - mpLRACoordinator-1.0 and mpLRA-1.0

### ISSUE THREAD

**Issue by yongja79** [OpenLiberty/open-liberty#14352]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on the OpenLiberty.io blog, and potentially elsewhere, to promote this beta of Open Liberty.

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature does your update relate to?
    
   Human-readable name (eg WebSockets feature):

> LRA Coordinator and LRA Participant 

   Feature name (eg websockets-1.0): 

> mpLRACoordinator-1.0 and mpLRA-1.0

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.
> application developer

3. Write a paragraph to summarises the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.
> Long Running Actions (LRA) provides a cloud native transaction model based on a compensating Saga model which allows loosely coupled services to coordinate long running activities guaranteeing eventual data consistency without the need to take locks on data. 

   - What was the problem before and how does your update make their life better? (Why should they care?)
   
> The features provide a Coordinator to which LRAs are registered along with any corresponding compensating method and the participant which allows microservice methods to be annotated to create a new or join an existing LRA, compensate and completed an LRA.

   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.
   
> Enable the LRA Coordinator in the server.xml, along with any other features you’re using

```
<featureManager>
    <feature>cdi-2.0</feature>
    <feature>jaxrs-2.1</feature>
    <feature>mpLRACoordinator-1.0</feature>
</featureManager>
```
> Enable LRA Participants in the server.xml, along with any other features you’re using

```
<featureManager>
    <feature>cdi-2.0</feature>
    <feature>jaxrs-2.1</feature>
    <feature>mpLRA-1.0</feature>
</featureManager>
```

> To start or join a LRA use the `@LRA` annotation. Depending on the type provided it may always create a new LRA, join the existing LRA or create a new one, join the existing LRA or continue outside one if none is provided, etc. A full list of options can be found in the Microprofile Long Running Actions [specifications](https://github.com/eclipse/microprofile-lra/blob/master/spec/src/main/asciidoc/microprofile-lra-spec.adoc).
An example of always creating a new LRA when called would be:  
```    
    @LRA(LRA.Type.REQUIRES_NEW)
    @Path(“/start”)
    @PUT
    public void startAction(@HeaderParam(LRA_HTTP_CONTEXT_HEADER) URI lraId)
    {
        /*
         * Business logic that may call upon other services to participate in this Long Running Action
         */
         return Response.ok().build();
    } 
```

> Once the LRA had been successfully finished all participating service will have their `@Complete` annotated methods called to perform the necessary cleanup 
```
    @Complete
    @Path("/complete")
    @PUT
    public Response completeAction(@HeaderParam(LRA_HTTP_CONTEXT_HEADER) URI lraId)
    {
        /*
         * Business logic to cleanup resources once the LRA has closed successfully
         */
         return Response.ok().build();
    } 
```

> Should a service in an LRA be cancelled or timeout the `@Compensate` methods for each participating service in the LRA will be called
```
    @Compensate
    @Path("/compensate")
    @PUT
    public Response compensateAction(@HeaderParam(LRA_HTTP_CONTEXT_HEADER) URI lraId)
    {
        /*
         * As the LRA has been cancelled business logic to compensate any changes is necessary
         */
         return Response.ok().build();
    }
```

   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?

> Microprofile Long Running Actions [Specification](https://github.com/eclipse/microprofile-lra/blob/master/spec/src/main/asciidoc/microprofile-lra-spec.adoc) 
## What happens next?

- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by austin0** [comment]
Blog has been published, closing.
