### ISSUE TITLE
Transform server.xml for jakarta testing

### ISSUE THREAD

**Issue by KyleAure** [OpenLiberty/open-liberty#14374]
Introduce a method to allow developers to transform their server.xml when repeating tests using jakarta.

Currently, the [FeatureReplacementAction](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java) swaps out features.  But in the case of the `JakartaEE9Action` a helper method to replace `javax.*` string in server.xml to `jakarta.*` would be helpful for configurations like the one here:

https://github.com/OpenLiberty/open-liberty/blob/80e12eb6c090e9c53de6488d0eb3a51ac4e3fa48/dev/com.ibm.ws.jca_fat/publish/servers/com.ibm.ws.jca.fat/server.xml#L54-L56

Where we are providing class names in server config.

**Comment by KyleAure** [comment]
Things to consider: might not want to do a blanket javax -> jakarta as this would transform things like `javax.sql.XADataSource` which are not changing. Perhaps reusing the existing `jakarta-xml-master.properties` and creating a custom properties file for transforming server.xml class names would be the most appropriate.

**Comment by KyleAure** [comment]
@dazavala Jared Anderson had seen this issue and indicated that there might already be plans to fix this in the JMS product code by tolerating both `javax` and `jakarta` class names.  
Wondering if you have done any investigation on this under #11851 
Thanks.

**Comment by dazavala** [comment]
@KyleAure I solved that problem for the underlying JMS config metatypes by transforming the metatype content using the properties in file jakarta-messaging-metatype.xml.  For this issue we can apply a similar solution to transform the content of JMS config elements in server.xml.  We have not delivered a solution for this issue, which I expect will require a new method to the ee9 repeat action -- i.e. a rule builder method -- that causes the rule to transform the non-feature content of the server.xml file using a prescribed transform properties file(s).

**Comment by KyleAure** [comment]
Thanks for the insight Dave.  I have a draft PR for what we could do on the test infrastructure side to transform the server.xml when we find `javax` class names in strings. 

But what I was thinking on the product code side, is say a customer was using JMS-2.x and had configured `destinationType="javax.jms.Topic"`
They update their server.xml to use messaging-3.0 and forget to update destination type to `jakarta.jms.Topic` would it be possible to warn them about the mistake, and then use the jakarta class name during runtime.  Or if that is too hand hold-y give them a custom error message and continue to fail them?

**Comment by KyleAure** [comment]
Update based on conversation had internally:

> I think replacing the config is a bit heavy handed.  Maybe we can just introduce a general warning message like:
> `The configured feature {0} is part of the JakartaEE 9 specification and has an attribute {1} on element {2} that contains a javax package {3}`
> That way if other specs also need to provide this warning it is versatile enough to do so.

**Comment by KyleAure** [comment]
I think a better solution for this will be to do the following:

In FATClient addEnvVar: 
```
server.addEnvVar("TOPIC", JakartaEE9Action.isActive() ? "jakarta.jms.Topic" : "javax.jms.Topic");
```

In server.xml use ${env.VAR}: 
```
<javaPermission className="javax.security.auth.PrivateCredentialPermission" signedBy="${env.PERMISSION}" principalType="*" principalName="*" actions="read"/>
``

In Annotation on FATServlet use ${env.VAR}:
```
 @JMSDestinationDefinition(name = "java:global/env/jms/dest1",
                           interfaceName = "${env.DESTINATION_INTERFACE}",
                           resourceAdapter = "ConfigTestAdapter",
                           destinationName = "3605 Hwy 52N, Rochester, MN 55901")
```
