### ISSUE TITLE
Server.xml config sources do not respect config_ordinal

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#14377]
**Describe the bug**
The spec allows the ordinal of a built in config source to be changed by defining a property named `config_ordinal` which is read from that config source
> Note that a special property config_ordinal can be set within any built-in ConfigSource implementation. The default implementation of getOrdinal() will attempt to read this value. If found and a valid integer, the value will be used. Otherwise the respective default value will be used.

However, our built in config sources for server.xml variables and `<appProperties>` do not change their ordinal if a property with `config_ordinal` is set.

**Comment by mbroz2** [comment]
Fixes: https://github.com/OpenLiberty/open-liberty/issues/11357
