### ISSUE TITLE
Verify JSF Provider Features After Name Change

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#14437]
As #14436 is addressed, we should verify the JSF singleton features work as expected as we only want one JSF provider at a time. 

Singleton features go off based on namings, so there may be some unintended consequences.

**Comment by pnicolucci** [comment]
Features don't contain any content here so we should validate that is expected as well and only used for avoiding loading more than one provider at a time.

**Comment by volosied** [comment]
I'm seeing that all the proper conflicts occur between jsfContainer-2.3, facesContainer-3.0, jsf-2.2, jsf-2.3, and faces-3.0.

Here's some of the one I tested:
facesContainer-3.0 & jsfContainer-2.3
- `[ERROR   ] CWWKF0044E: The facesContainer-3.0 and jsfContainer-2.3 features cannot be loaded at the same time. The facesContainer-3.0 feature of Jakarta EE 9 is incompatible with the jsfContainer-2.3 feature of Java EE 8. The facesContainer-3.0 and jsfContainer-2.3 configured features include an incompatible combination of features. Your configuration is not supported. Update the configuration to use features that support either the Jakarta EE or Java EE programming models, but not both.`
facesContainer-3.0 & jsf-2.2
- `[ERROR   ] CWWKF0044E: The facesContainer-3.0 and jsf-2.2 features cannot be loaded at the same time. The facesContainer-3.0 feature of Jakarta EE 9 is incompatible with the jsf-2.2 feature of Java EE 7. The facesContainer-3.0 and jsf-2.2 configured features include an incompatible combination of features. Your configuration is not supported. Update the configuration to use features that support either the Jakarta EE or Java EE programming models, but not both.`
facesContainer-3.0 & faces-3.0
- `[ERROR   ] CWWKF0033E: The singleton features io.openliberty.facesProvider-3.0.0.Container and io.openliberty.facesProvider-3.0.0.MyFaces cannot be loaded at the same time.  The configured features facesContainer-3.0 and faces-3.0 include one or more features that cause the`
