### ISSUE TITLE
Move hcagent code from WS-CD to Open Liberty

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#14491]
`logstashCollector-1.0` has moved to Open Liberty in #9291.  However, the Health Center code is still in WS-CD.

Investigate and see if the following projects need to be moved to Open Liberty

com.ibm.ws.collector.manager.hcagent
com.ibm.ws.collector.manager.hcclassloader
com.ibm.ws.collector.manager.hcmonitoringjar

**Comment by donbourne** [comment]
check with Alasdair - was leaving this in WS-CD intentional?

**Comment by Channyboy** [comment]
HC code was not moved over as it is part of IBM Java and isn't open source.

**Comment by Channyboy** [comment]
```
As part of https://github.com/OpenLiberty/open-liberty/pull/9291 to move 
the logstashCollector-1.0 feature (and supporting projects that enable the use of 
its' various sources) from WS-CD to OpenLiberty these `com.ibm.ws.collector.manger*`<1>
projects were intentionally left in WS-CD Open. The use of the Health Center API 
is IBM Java specific and can not be used or provided within an open source project 
(i.e OpenLiberty).
 
 <1> The relevant projects are:
 com.ibm.ws.collector.manager.hcagent
 com.ibm.ws.collector.manager.hcclassloader
 com.ibm.ws.collector.manager.hcmonitoringjar
```
