### ISSUE TITLE
BETA BLOG - RESTful Web Services 3.0

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#14514]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on the OpenLiberty.io blog, and potentially elsewhere, to promote this beta of Open Liberty.

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature does your update relate to? Beta Blog release for #11803 
    
   Human-readable name (eg WebSockets feature): RESTful Web Services 3.0
   
   Feature name (eg websockets-1.0): `restfulWS-3.0` and `restfulWSClient-3.0`

2. Who is the target persona? Who do you expect to use the update? **application developers**

3. Write a paragraph to summarises the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.

   - What was the problem before and how does your update make their life better? (Why should they care?)
   
   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.
   
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?

RESTful Web Services 3.0 (formerly known as JAX-RS) is now available in Open Liberty Betas! The 3.0 implementation like most EE9 technologies changes to use the new package name (`javax.*` to `jakarta.*`), but Liberty's implementation is changing to use RESTEasy.  Changing the underlying implementation will result in some behavioral differences from previous versions, and we are documenting those.  In the meantime, please give it a try - and if you encounter any issues, please let us know!

You can enable RESTful Web Services 3.0 by using the `restfulWS-3.0` feature in the server.xml.  If you only need a RESTful client, then you can use `restfulWSClient-3.0` instead.  

If you want to learn more about RESTful Web Services or see what is coming in future releases, please visit the community page at: https://github.com/eclipse-ee4j/jaxrs-api 

## What happens next?

- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by austin0** [comment]
Blog has been published, closing.
