### ISSUE TITLE
BETA BLOG - MicroProfile Config 2.0

### ISSUE THREAD

**Issue by Joseph-Cass** [OpenLiberty/open-liberty#14519]
**NOT FINISHED- POSTING FOR COLLABORATION**

The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on the OpenLiberty.io blog, and potentially elsewhere, to promote this beta of Open Liberty.

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature does your update relate to?
    
   Human-readable name (eg WebSockets feature):

>  MicroProfile Config 2.0
   
   Feature name (eg websockets-1.0): 

> mpConfig-2.0

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.

> Application developers

3. Write a paragraph to summarises the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.

   > [MicroProfile Config](https://github.com/eclipse/microprofile-config) is a specification which OpenLiberty implements to allow application configuration from different locations (ConfigSources). In the previous versions, OpenLiberty has implemented the specification in its own codebase. However, for MicroProfile Config 2.0 it consumes [SmallRye's implementation](https://github.com/eclipse/microprofile-config) of the specification.
MicroProfile Config 2.0 is a major version release (from 1.4) which introduces API/SPI changes and functional changes.

   - What was the problem before and how does your update make their life better? (Why should they care?)
### Functional Changes
   > - Provide a way to retrieve a number of related configuration properties with a specified prefix into a CDI bean, using the `@[ConfigProperties]((https://github.com/eclipse/microprofile-config/blob/master/api/src/main/java/org/eclipse/microprofile/config/inject/ConfigProperties.java)` annotation.
   >```
   >@ConfigProperties(prefix="customer")
   >@Dependent
   >public static class BeanOne {
   >    private String name;
   >    int age;
   >}
   >```
   >retrieves the following defined properties for the `name` and `age` fields:
   >```
   >customer.name=Bob
   >customer.age=24
   >```
   > - Allows end users to easily determine which was the "winning" ConfigSource (the ConfigSource with the highest ordinal) for a specified property via [ConfigValue](https://github.com/eclipse/microprofile-config/blob/master/api/src/main/java/org/eclipse/microprofile/config/ConfigValue.java). A `ConfigValue` object holds information about the configuration property name, configuration value, the ConfigSource name from where the configuration property was loaded and the ordinal of the ConfigSource. Users can access these values with the following method: 
   >```
   >ConfigValue cv = Config.getConfigValue(String propertyName);
   >cv.getSourceName() // the config source that supplies the configure value for the above property
   >```
   > - Enables an application to include configuration for different environments and development stages while only one of them is active (e.g. dev, test, prod) via [Configuration Profiles](https://download.eclipse.org/microprofile/microprofile-config-2.0-RC1/microprofile-config-spec.html#configprofile). The Config profile can be specified via the `mp.config.profile` property, which can be set in any of the configuration sources. Once it is set, the corresponding properties associated with the active profile are used.  The value can also be set at application start-up, for example:
   >```
   >java -jar myapp.jar -Dmp.config.profile=testing
   >```
   >The `mp.config.profile` property can works on property level and config file level.
   > 

   >>- On Property level
   >> The property can be utilised by setting Config property values specific to the selected profile. For example, the `vehicle.name` property in the following example would be set to `bike` from the previous Config start up command:

   >>```
   >>%dev.vehicle.name=car
   >>%testing.vehicle.name=bike
   >>vehicle.name=lorry
   >>```
   >>If `mp.config.profile` was not set, `vehicle.name` would be set to `lorry`.
   >> 

   >>- On microprofile-config.property level

   >>The property `mp.config.profile` also activates the corresponding `microprofile-config-<mp.config.profile>.properties` while `microprofile-config.properties` as the fallback.
   > - Support [Property Expressions](https://download.eclipse.org/microprofile/microprofile-config-2.0-RC1/microprofile-config-spec.html#property-expressions), which provides a way to set and expand variables in property values. For example, in the following configuration properties, the property`server.url` will be resolved to `http://example.org/endpoint`:
   >```
   >server.url=http://${server.host}/endpoint
   >server.host=example.org
   >```
   >**Note**: Previous working configuration may behave differently (if the used configuration contains values with Property Expressions syntax).
   > -  Two new methods have been introduced to [Config.java](https://github.com/eclipse/microprofile-config/blob/master/api/src/main/java/org/eclipse/microprofile/config/Config.java):
   >     - `Config.getValues(String propertyName, Class<T> propertyType)`
   >     - `Config.getOptionalValues(String propertyName, Class<T> propertyType)` 
   >
   >The methods have been added to allow users to retrieve multi-valued properties as lists instead of arrays. The methods return the resolved property values with the specified `propertyType` for the specified `propertyName`.

   > - `OptinalInt`, `OptionalLong` and `OptionalDouble` are now provided as built-in Converters. The new Converters can be used like any of the other built-in [Converters](https://download.eclipse.org/microprofile/microprofile-config-2.0-RC1/microprofile-config-spec.html#converter), converting injected Config property values to a defined Type:
   >```
   >@Inject
   >@ConfigProperty(name = "my.optional.int.property")
   >   private OptionalInt optionalIntProperty;
   >```

### Incompatible Changes
  >If you move up from MicroProfile Config 1.x, 2.x, please take care of the following incompatible changes.

>-  ConfigSource#getPropertyNames is no longer a default method. The implementation of a ConfigSource must implement this method. 

>- Previous versions of the specification would not evaluate Property Expressions. As such, previous working configuration may behave differently (if the used configuration contains values with Property Expressions syntax). Set the property `mp.config.property.expressions.enabled` with the value of `false`

 >- Empty values or other special characters are no longer valid Config property values. This means that `Config.getValue(String propertyName, Class<T> propertyType)` will never return null; a `NoSuchElementException` will be thrown if either a Config property value is not defined, is defined as an empty string, or its converter returns `null`. In the previous release, the empty value was returned as an empty value. For more information, please refere to this [section](https://download.eclipse.org/microprofile/microprofile-config-2.0-RC1/microprofile-config-spec.html#_config_value_conversion_rules)

   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.

   > Enable the MicroProfile Config 2.0 feature in the server.xml.

   >```
   ><featureManager>
   >    <feature>mpConfig-2.0</feature>
   ></featureManager>
   >```
   
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?

   > [Release Notes for MicroProfile Config 2.0](https://download.eclipse.org/microprofile/microprofile-config-2.0-RC1/microprofile-config-spec.html#release_notes_20)
[MicroProfile Config 2.0 Milestone](https://github.com/eclipse/microprofile-config/milestone/8?closed=1)

## What happens next?

- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by lauracowen** [comment]
That's fine - @jakub-pomykala @austin0 won't start on this until Monday. When they've taken the info they need, they'll close the issue - at that point, make sure any changes go directly to them rather than just modifying existing text in here which they won't be able to see (and it may not be easy to merge into their edited text in the post draft).

**Comment by austin0** [comment]
Blog has been published, closing.
