### ISSUE TITLE
BETA BLOG - Connectors-2.0

### ISSUE THREAD

**Issue by KyleAure** [OpenLiberty/open-liberty#14515]
1. Which Liberty feature does your update relate to?
    
   Human-readable name (eg WebSockets feature): `Jakarta Connectors 2.0`
   
   Feature name (eg websockets-1.0): `connectors-2.0`

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.

```
Application Developer
```

3. Write a paragraph to summarises the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.

```	
This feature allows Open Liberty users that want to use the latest release of the Jakarta Resource specification https://github.com/eclipse-ee4j/jca-api within their application.

The main update to connectors to come out of this feature is the change from the javax namespace to jakarta.
```

   - What was the problem before and how does your update make their life better? (Why should they care?)

```
Open Liberty is keeping our connectors implementation up to date with the latest specification.
```
   
   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.

```xml
<!-- Users can activate this feature using -->
<server>
    <featureManager>
      <feature>connectors-2.0</feature>
    </featureManager>
</server>
```

```
All other `resourceAdapter` configurations within server.xml can remain unchanged for current applications.
```

   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?

```
Spec Project: https://github.com/eclipse-ee4j/jca-api
Spec API: https://mvnrepository.com/artifact/jakarta.resource/jakarta.resource-api
Spec Javadoc: https://jakarta.ee/specifications/connectors/2.0/apidocs/jakarta/resource/package-summary.html
```

**Comment by austin0** [comment]
Blog has been published, closing.
