### ISSUE TITLE
FTS for #10786 MP Rest Client 2.0

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#14523]
**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

All previous MP Rest Client 1.X FAT tests will be repeated using the `mpRestClient-2.0` feature (and appropriate dependent features like `mpConfig-2.0`, etc.). 

A new 2.0 TCK FAT project will verify that the implementation passes the MP Rest Client TCK. The TCK tests all of the new features in MP Rest Client 2.0 including:
- Multi-valued HTTP query parameter styles
- SSEs
- Specifying HTTP proxy host/server
- JSON-B customization for serializing/deserializing JSON objects
- Automatically following HTTP redirect responses

These tests work with Arquillian, TestNG and use WireMock to simulate the server.  For multi-valued query parameters, the test used WireMock to determine that the user-configured parameter style was sent to the server. For SSEs, the TCK verified that events were consumed as a reactive streams Publisher - the MP Rest Client TCK also included a TCK test from Reactive Streams verifying that an implementation of MP Rest Client 2.0 would pass the RS TCK. WireMock also allows for testing of HTTP proxy servers - the TCK contains tests that the proxy server works when configured correctly, but also tests that it fails appropriately when it is configured incorrectly.  For `ContextResolver<Jsonb>`, the TCK has a test similar to what we used in previous Liberty releases that verifies that a user can configure the JSON-B config used for that client's requests. Automatic redirects were tested in such a way that when enabled, it would verify that it invoked two server endpoints (the original endpoint which would return a redirect response - and the ultimate end-location containing the entity) and it would verify that only the original endpoint was invoked if the setting was disabled (default).  

New FAT tests have been added (in the `com.ibm.ws.microprofile.rest.client_fat` FAT project) that provide additional testing of MP Rest Client 2.0 features - specifically SSE via Reactive Streams.  These tests verify that the client receives the expected number of events from the server - and tests different event types including `InboundSseEvent` (which allows the client to obtain additional info from each event), `String`, `int`, and a custom POJO.

For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature.

If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

**4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.**

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

**4**

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by andymc12** [comment]
FTS for #10786

**Comment by ayoho** [comment]
LGTM 👍
