### ISSUE TITLE
Verify variable replacement honoured in server.xml

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#14525]
The variable and appProperties defined in server.xml will opt in for this variable replacement support and comply with the same rules as other config sources such as default configure sources and custom configure sources.
```
<variable name=”key1" value=”${somekey}" />
    <webApplication location=”app1.war"> 
	   <appProperties> 
	         <property name=”key2" value=”${otherKey}"/> 
	   </appProperties> 
	</webApplication>

    <webApplication location=”app2.war"/> 

```

In app1.war, its microprofile-config.properties has the following properties defined
```
somekey=blah 
otherKey=Boo
```
```
@Inject @ConfigProperty(name="key1") String key1; // the value will be blah
@Inject @ConfigProperty(name="key2") String key2; // the value will be Boo
```
In app2.war, its microprofile-config.properties has the following property defined
```
somekey=splash
```
```
@Inject @ConfigProperty(name="key1") String key1; // the value will be splash
```

**Comment by Joseph-Cass** [comment]
I have made a test for this locally which passed. Waiting for some other PRs to merge before I create a PR for the test.

**Comment by Emily-Jiang** [comment]
Can you associate your PR with this issue? @Joseph-Cass
