### ISSUE TITLE
MP 4.0 Beta blog

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#14522]
Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature does your update relate to?
    
   Human-readable name (eg WebSockets feature): MicroProfile Config 4.0
   
   Feature name (eg websockets-1.0): microProfile-4.0

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.

Application Developer

3. Write a paragraph to summarises the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.

Open Liberty 20.0.0.12-beta provides most feature updates for MicroProfile 4.0-M1, which includes updates to MicroProfile Config, Fault Tolerance, Metrics, Health, Open Tracing, Open API and JWT, detailed below. While MictoProfile Rest Client is part of MicroProfile 4.0-M1 but this feature narrowly missed this beta train. 

MicroProfile 4.0:
Add link to the following beta release note
Config 2.0
Fault Tolerance 3.0
Metrics 3.0
Health 3.0
Open API 2.0
JWT 1.2
Open Tracing 2.0

   
   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.

<feature>microProfile-4.0</feature>
   
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?
More information regarding the updates can be found [here](https://download.eclipse.org/microprofile/microprofile-4.0-M1/microprofile-spec-4.0-M1.html#microprofile4.0-M1).
## What happens next?

- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by austin0** [comment]
Blog has been published, closing.
