### ISSUE TITLE
Plugin Generator can cause server shutdown delay

### ISSUE THREAD

**Issue by wtlucy** [OpenLiberty/open-liberty#14532]
When a server shutdown is initiated while before the plugin-cfg generator has completed, quiesce warnings such as `CWWKE1106W: 1 shutdown operations did not complete during the quiesce period` can be thrown. The plugin-cfg generator should be updated to abort file generation if a shutdown is detected.

**Comment by wtlucy** [comment]
#15135 adds some new server shutdown checks in the plugin-cfg generator logic which will allow it to stop generation more gracefully.  I'll close this, but we can reopen if more shutdown problems emerge here.

**Comment by jhanders34** [comment]
Bill should this be marked as a release bug?

**Comment by wtlucy** [comment]
@jhanders34 it should, I've updated the tag - thanks for pointing this out
