### ISSUE TITLE
GA BLOG - Kerberos authentication for JDBC data sources

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#14545]
The information you provide here will be included in the Open Liberty GA release blog post ([example](https://openliberty.io/blog/2020/07/30/json-logging-open-liberty-20008.html)), which will be published on the OpenLiberty.io blog, and potentially elsewhere, to promote this release of Open Liberty.

Please provide the following information the week before the GA date (to allow for review and publishing):

1. Which Liberty feature does your update relate to?
    
   Human-readable name (eg WebSockets feature): Java Database Connectivity
   
   Feature name (eg websockets-1.0): jdbc-4.0, jdbc-4.1, jdbc-4.2, jdbc-4.3

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.

Application developers and operations

3. Write a paragraph to summarises the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.

Kerberos is a commonly used ticket-based authentication protocol. In this release of OpenLiberty we have added support for using Kerberos authentication with JDBC data sources.

   - What was the problem before and how does your update make their life better? (Why should they care?)

Before this release, it was technically possible to use Kerberos authentication with JDBC data sources, but the configuration was complex and un-documented. Also, there was no connection pooling support when using Kerberos authentication for data sources.
   
   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.

To use this feature, you must enable one of the JDBC features in your server.xml. Configuration for a data source may look like this:

```xml
<server>

  <featureManager>
    <feature>jdbc-4.2</feature>
  </featureManager>

  <!-- optional config: This is only needed if you need to customize the location of keytab or krb5.conf -->
  <kerberos keytab="${server.config.dir}/security/krb5.keytab" configFile="${server.config.dir}/security/krb5.conf"/>

  <authData id="myKerberosAuth" krb5Principal="krbUser"/>

  <library id="db2DriverLib">
    <fileset dir="${server.config.dir}/db2"/>
  </library>

  <dataSource jndiName="jdbc/krb/basic" containerAuthDataRef="myKerberosAuth">
    <jdbcDriver libraryRef="db2DriverLib"/>
    <properties.db2.jcc databaseName="${DB2_DBNAME}" serverName="${DB2_HOSTNAME}" portNumber="${DB2_PORT}"/>
  </dataSource>

</server>
```
   
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?

There will be a dedicated doc page posted about this new functionality soon. See this issue for current details: https://github.com/OpenLiberty/docs/issues/2460

If you have previously provided this information for an Open Liberty beta blog post and nothing has changed since the beta, just provide a link to the published beta blog post and we'll take the information from there.

## What happens next?

- Your paragraph will be included in the GA release blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the GA blog post).

**Comment by jakub-pomykala** [comment]
@austin0

**Comment by frowe** [comment]
Since the GA blog is published, I'm closing this.  If that is premature, reopen.
