### ISSUE TITLE
microprofile-primitives performance throughput regression

### ISSUE THREAD

**Issue by jdmcclur** [OpenLiberty/open-liberty#14600]
I am seeing a small regression in 20.0.0.12 with some of the microprofile-primitive runs.

A profile of the java code isn't showing me too much, but one area where it got slower is here:

```
  Parent      0   0.38   0.63          26          43    J:com/ibm/wsspi/webcontainer/collaborator/CollaboratorHelper.preInvokeCollaborators(Lcom/ibm/wsspi/webcontainer/collaborator/ICollaboratorMetaData;Ljava/util/EnumSet;)V
  Parent      0   0.70   1.09          48          75    J:com/ibm/wsspi/webcontainer/collaborator/CollaboratorHelper.postInvokeCollaborators(Lcom/ibm/wsspi/webcontainer/collaborator/ICollaboratorMetaData;Ljava/util/EnumSet;)V
 
    Self      0   1.08   1.72          74         118    J:com/ibm/ws/webcontainer/security/WebAppSecurityCollaboratorImpl.isCDINeeded()Z
 
   Child      0   0.10   0.32           7          22    J:java/util/Collections$UnmodifiableCollection$1.next()Ljava/lang/Object;
   Child      0   0.00   0.15           0          10    J:java/lang/Float.valueOf(Ljava/lang/String;)Ljava/lang/Float;
   Child      0   0.00   0.07           0           5    J:java/util/Collections$UnmodifiableCollection.iterator()Ljava/util/Iterator;
   Child      0   0.03   0.04           2           3    J:java/lang/String.substring(I)Ljava/lang/String;
   Child      0   0.04   0.04           3           3    J:java/util/Collections$UnmodifiableCollection$1.hasNext()Z
   Child      0   0.01   0.01           1           1    J:java/lang/String.startsWith(Ljava/lang/String;)Z
 ```

Here is the change:
https://github.com/OpenLiberty/open-liberty/commit/e4830bd16bb364cb3cd8d0bfb5a3e139d5cfe26e#diff-baa03d5f5b67c180a725b93b2a1c05f3fc0f34cfc4ced59faf3ae31f45ca8c57

Looks like we are looping through features looking for things which is taking ~1.5% longer than it did before.

**Comment by jdmcclur** [comment]
#regression

**Comment by jhanders34** [comment]
@jvanhill This appears to be caused by your PR as mentioned by Joe.   Looks like we need a better solution.

**Comment by jvanhill** [comment]
@jhanders34 @jdmcclur - I was trying to prevent us from having to update the code again in the future should another appSecurity feature be created as I don't really like the fact that we have feature name checks in the code. Didn't really think this would cause much of a regression. I guess I will change it back to directly lookup appSecurity-3.0 and appSecurity-4.0.

**Comment by jvanhill** [comment]
Oops... didn't mean to close.
