### ISSUE TITLE
Complete/Improve Upstream Arquillian Container PR33 for 2153-EnableShouldThrowExceptionDefinitionException 

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#1462]
The log scraping was would fail for non English and so the commiter requested an
improvement to handle. Also investigate nested exceptions and testable=true support.

fork repo cloned at /Users/hutchig/git/hutchig/arquillian-container-was
see
https://github.com/arquillian/arquillian-container-was/pull/33
https://github.com/hutchig/arquillian-container-was/tree/2153-EnableShouldThrowExceptionDefinitionException

**Comment by hutchig** [comment]
I plan to work on this today as I think it will help Neil make progress with his testable=true investigations.

**Comment by Emily-Jiang** [comment]
Wait for Gerhard for external review and then merge.
