### ISSUE TITLE
Add automatic crosslinking between feature gendoc and API/SPI javadoc

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/open-liberty#14631]

**Comment by lauracowen** [comment]
Status: I believe this is being handled as one of the long-term doctools items by @hlhoots.

**Comment by malincoln** [comment]
Per @hlhoots  this is still valid.

**Comment by hlhoots** [comment]
This feature depends on https://github.com/OpenLiberty/open-liberty/issues/14629 which generates the javadoc for the Open Liberty api/spi which is currently being worked.  Once it is completed we should be able to move forward with this change.

This change will update the adoc output generated in the build to have a reference from the Open Liberty API / SPI javadoc reference to the actual javadoc.

An example for appAuthorization-2.0.adoc is:

```
== Liberty API packages provided by this feature
* javadoc:com.ibm.wsspi.security.authorization.jacc[]
// end::apis[]
// tag::requirements[]
```

Where the * javadoc:com.ibm.wsspi.security.authorization.jacc[] reference would point to the physical location of the javadoc:

"/docs/modules/reference/io.openliberty.jacc_1.0-javadoc/com/ibm/wsspi/security/authorization/jacc/package-summary.html">

**Comment by hlhoots** [comment]
The function for this feature was delivered as part of https://github.com/OpenLiberty/open-liberty/issues/14629.  Closing out.
