### ISSUE TITLE
Autogenerate tracing group documentation for server features

### ISSUE THREAD

**Issue by ggam** [OpenLiberty/open-liberty#14630]
I sometimes need to raise the tracing level of a specific feature (e.g. to debug a problem). I haven't found any documentation for the available "tracing components", so I usually end up looking at the source code for the class names.

Manually maintaining that content would be very tedious, but most feature packages are annotated `@TraceOptions` which already provide a default component. See for example:
- https://github.com/OpenLiberty/open-liberty/blob/675d10e67b049cea7afdac5e8069e49e4cb80d7e/dev/com.ibm.ws.classloading.bells/src/com/ibm/ws/classloading/bells/internal/package-info.java#L15
- https://github.com/OpenLiberty/open-liberty/blob/675d10e67b049cea7afdac5e8069e49e4cb80d7e/dev/com.ibm.ws.jndi/src/com/ibm/ws/jndi/package-info.java

Those annotations could be scanned and added to the autogenerated docs. Not all features have all their packages annotated, but the result would be complete enough to make a difference in my opinion.

**Comment by lauracowen** [comment]
Status: I believe this is being handled as one of the long-term doctools items by @hlhoots.

**Comment by malincoln** [comment]
Per @hlhoots this is still valid.

**Comment by malincoln** [comment]
Agreed to close.
