### ISSUE TITLE
Cryptic exception when session max count exceeded

### ISSUE THREAD

**Issue by zhang-ca** [OpenLiberty/open-liberty#14651]
Customer set the HTTP session timeout to 22 days (not sure why)
after 30m of run , the production server stopped serving new requests.
customer opened a PMR since the logs didn't reveal anything special other than:
1/31/17 0:16:56:499 GST] 0000017c webapp        E com.ibm.ws.webcontainer.webapp.WebApp logServletError SRVE0293E: [Servlet Error]-[GadgetAPIServlet]: java.lang.IllegalStateExceptionˆM
        at com.ibm.ws.session.http.HttpSessionImpl.isNew(HttpSessionImpl.java:313)ˆM
        at com.ibm.ws.session.SessionContext.doSecurityCheck(SessionContext.java:559)ˆM
        at com.ibm.ws.session.SessionContext.getIHttpSession(SessionContext.java:519)ˆM
        at com.ibm.ws.session.SessionContext.getIHttpSession(SessionContext.java:426)ˆM
        at com.ibm.ws.webcontainer.srt.SRTRequestContext.getSession(SRTRequestContext.java:113)

Request to output an error message if the application generated more http sessions than the max.

**Comment by lauracowen** [comment]
Status: I'm not sure why Jakub and I are assigned to this as we don't work on the open-liberty codebase. I think this needs to be reviewed and reassigned by @NottyCode

**Comment by malincoln** [comment]
@pnicolucci I see Chuck reassigned to your team so fyi.

**Comment by pnicolucci** [comment]
@zhang-ca is this actually a feature ? I see you have it labeled as an epic but the code was already merged quite some time ago. Should this just have been a release_bug perhaps?

**Comment by zhang-ca** [comment]
This came from RFE [236534](https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/External%20Request%20For%20Enhancements#action=com.ibm.team.workitem.viewWorkItem&id=236534).

It was delivered as APAR in tWAS, is it the same as release_bug?
