### ISSUE TITLE
Handling of encrypted token when consumer can't decrypt

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#14652]
Test case JwtConsumerApiConfigTests_encryptedToken_consumerDoesNotDecrypt may need to be re-worked.
It passes an encrtyped token to the consumer.  The consumer does not have a key management key alias defined.  It tries to decrypt, but fails when the keys don't match.
Should we even attempt to handle an encrypted token when we don't have a key management key alias?  Should there be a concept of a default alias, ...

**Comment by ayoho** [comment]
I actually did update this flow under https://github.com/OpenLiberty/open-liberty/pull/14847. In the new logic, we'll check the JWS vs. JWE requirements based on the configuration and fail/proceed accordingly. In this case, we'll check the config and see that the `keyManagementKeyAlias` config attribute and `mp.jwt.decrypt.key.location` MP Config property are missing, which means the runtime will only accept JWTs in JWS format. You'll end up with the following error message:
> CWWKS6031E: The JSON Web Token (JWT) consumer [RS256] cannot process the token string. CWWKS6063E: The token in the request is not in JSON Web Signature (JWS) format, but the [RS256] JWT consumer only accepts tokens that are in JWS format.
