### ISSUE TITLE
A list of potential breaking changes for a user upgrading mpConfig 1.x->2.0

### ISSUE THREAD

**Issue by Joseph-Cass** [OpenLiberty/open-liberty#14709]
MicroProfile Config 2.0 is a major version release with plenty of [new features listed here](https://download.eclipse.org/microprofile/microprofile-config-2.0-RC1/microprofile-config-spec.html#release_notes_20).

However, an OpenLiberty user has to be aware of 2 key sets of changes which may impact any existing configuration when upgrading from mpConfig 1.x->2.0:

1. For previous mpConfig versions, OL has implemented the specification in its own codebase. However, for mpConfig 2.0 it consumes [SmallRye's implementation](https://github.com/smallrye/smallrye-config) of the specification. This means that any mpConfig functionality that OL implemented beyond the scope of the specification will be lost from 1.x->2.0.
    - Converters for `AtomicInteger` and `AtomicLong` are no longer provided. Attempting to convert an injected value to one of these types may throw the following exception: `SRCFG02006: The property <yourProperty> cannot be converted to class java.util.concurrent.atomic.AtomicInteger/AtomicLong`
    - Values looked up from `Config` are no longer cached for a short period of time. In mpConfig 1.x, requests for the same config key within this time period (default up to five seconds) would return the same object without calling the config sources. In mpConfig 2.0, this caching is not done.
    - When conversion to a type is needed and a converter for that type is not available, coverters for subtypes of that type will no longer be used. For example, in mpConfig-1.x if a converter was registered for type `Dog` (which `extends Animal`), then a type `Animal` variable could be injected which would use the `Dog` converter, e.g.  
        ```
        @Inject
        @ConfigProperty(name = "DOG_KEY")
        Animal myAnimal;
        ```
2. Changes in the mpConfig specification from 1.4->2.0 introduced [some incompatibility changes](https://download.eclipse.org/microprofile/microprofile-config-2.0-RC1/microprofile-config-spec.html#_incompatible_changes). Some of these are by-products of new features, and others are intentional specification clarifications/changes.
    - [ConfigSource.getPropertyNames()](https://github.com/eclipse/microprofile-config/blob/bc0ea9932f29da9ced7a323f75741cd8b33dbe38/api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java#L144) is no longer a default method provided by the specification. Any custom Config Sources which use this method will need to implement the method, otherwise a `java.lang.AbstractMethodError` will be thrown.
    - [Property Expression](https://download.eclipse.org/microprofile/microprofile-config-2.0-RC1/microprofile-config-spec.html#property-expressions) is a new feature which may impact existing configurations. From mpConfig 2.0 Config Properties can include references to other Config Properties by using the following syntax: `${anotherConfigPropertyName​}`.  As such, any Config Properties which contain values with Property Expression syntax may behave differently.
    - [Config Property value conversion rules](https://download.eclipse.org/microprofile/microprofile-config-2.0-RC1/microprofile-config-spec.html#_config_value_conversion_rules) have been updated such that the empty value and other special characters are no longer valid values for particular return types. Attempting to call `getValue()` on an injected empty value (`""`) for type String for example will throw a `java.util.NoSuchElementException`

**Comment by Emily-Jiang** [comment]
MicroProfile Config 2.0 is a major version release with plenty of [new features listed here](https://download.eclipse.org/microprofile/microprofile-config-2.0-RC1/microprofile-config-spec.html#release_notes_20).

However, an OpenLiberty user has to be aware of 2 key sets of changes which may impact any existing configuration when upgrading from mpConfig 1.x->2.0:

1. For previous mpConfig versions, OL has implemented the specification in its own codebase. However, for mpConfig 2.0 it consumes [SmallRye's implementation](https://github.com/smallrye/smallrye-config) of the specification. This means that any mpConfig functionality that OL implemented beyond the scope of the specification will be lost from 1.x->2.0.
    - Converters for `AtomicInteger` and `AtomicLong` are no longer provided, because it is not widely used. Attempting to convert an injected value to one of these types may throw the following exception: `SRCFG02006: The property <yourProperty> cannot be converted to class java.util.concurrent.atomic.AtomicInteger/AtomicLong`. If you need to convert a string to `AtomicInteger` to `AntomicLong`, you can convert to `Integer` or `Long` and then create an `AtomicIneger` or `AtomicLong`. Alternatively, you can create your own converter for `AtomicInteger` or `AtomicLong`.
    - Values looked up from `Config` are no longer cached for a short period of time. In mpConfig 1.x, requests for the same config key within this time period (default up to five seconds) would return the same object without calling the config sources. In mpConfig 2.0, this caching is not done.
    - When conversion to a type is needed and a converter for that type is not available, coverters for subtypes of that type will no longer be used. For example, in mpConfig-1.x if a converter was registered for type `Dog` (which `extends Animal`), then a type `Animal` variable could be injected which would use the `Dog` converter, e.g.  
        ```
        @Inject
        @ConfigProperty(name = "DOG_KEY")
        Animal myAnimal;
        ```
The recommended approach is to use the above converter to convert to `Dog`, which is efficiently an `Animal`.
2. Changes in the mpConfig specification from 1.4->2.0 introduced [some incompatibility changes](https://download.eclipse.org/microprofile/microprofile-config-2.0-RC1/microprofile-config-spec.html#_incompatible_changes). Some of these are by-products of new features, and others are intentional specification clarifications/changes.
    - [ConfigSource.getPropertyNames()](https://github.com/eclipse/microprofile-config/blob/bc0ea9932f29da9ced7a323f75741cd8b33dbe38/api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java#L144) is no longer a default method provided by the specification. Any custom Config Sources which use this method will need to implement the method, otherwise a `java.lang.AbstractMethodError` will be thrown.
    - [Property Expression](https://download.eclipse.org/microprofile/microprofile-config-2.0-RC1/microprofile-config-spec.html#property-expressions) is a new feature which may impact existing configurations. From mpConfig 2.0 Config Properties can include references to other Config Properties by using the following syntax: `${anotherConfigPropertyName​}`.  As such, any Config Properties which contain values with Property Expression syntax may behave differently.
    - [Config Property value conversion rules](https://download.eclipse.org/microprofile/microprofile-config-2.0-RC1/microprofile-config-spec.html#_config_value_conversion_rules) have been updated such that the empty value and other special characters are no longer valid values for particular return types. Attempting to call `getValue()` on an injected empty value (`""`) for type String for example will throw a `java.util.NoSuchElementException`

**Comment by tevans78** [comment]
From our perspective, this issue is closed. The documentation issue itself is still open: https://github.com/OpenLiberty/docs/issues/3443
