### ISSUE TITLE
CWWKS1460E error when registering a new OAuth client using Db2 in Oracle compatibility mode

### ISSUE THREAD

**Issue by jensengelke** [OpenLiberty/open-liberty#14734]
**Describe the bug**
```
CWWKS1460E: The OAuth feature encountered an error while running the [INSERT] operation with the [OXAtazhmodYdxPHHWHHO] OpenID Connect client in the cached database.
```
is observed in a WLP 20.0.0.9 environment using Db2 in Oracle compatibility mode when registering a new OAuth client via /oidc/endpoint/<id>/registration.

The issue has been narrowed down to
```
Assignment of a NULL value to a NOT NULL column "TBSPACEID=2, TABLEID=6, COLNO=3" is not allowed.
```
being caused by trying to insert `""` as client_name - which is treated as NULL in Db2 with Oracle compat mode. The column for DISPLAYNAME is specified as NOT NULL though.

The code should be updated to insert the real client_name (if specified) or the client_id as a fallback for DISPLAYNAME (truncation may be required to fit into the column).

**Steps to Reproduce**
Any OIDC client registration with Db2 in Oracle compatibility mode.

**Expected behavior**
Clients can register.

**Diagnostic information:**
 - WebSphere Liberty Version:  20.0.0.9
 - Java Version: 
```
sh-4.4$ java -version
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 8.0.6.15 - pxa6480sr6fp15-20200724_01(SR6 FP15))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200724_452227 (JIT enabled, AOT enabled)
OpenJ9   - 4ce4b9d
OMR      - 08b0594
IBM      - 70917a2)
JCL - 20200720_01 based on Oracle jdk8u261-b13
```
 - server.xml configuration: n/a
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`: n/a

**Additional context**
PMR TS004035515

**Comment by chunlongliang-ibm** [comment]
@jensengelke You should mention the code path and its potential code fix that we discussed in slack

**Comment by jensengelke** [comment]
@chunlongliang-ibm 
https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/plugins/db/CachedDBOidcClientProvider.java#L845 is passing an empty string as displayName.

Instead the value to be passed should be
```
displayName = (null == getClientName()) ? getClientName() : getClientId();
```
