### ISSUE TITLE
mpConfig-2.0: getOptionalValue performance

### ISSUE THREAD

**Issue by jdmcclur** [OpenLiberty/open-liberty#14752]
In my primitives with mpOpentracing enabled, I am seeing a regression with microProfile-4.0 compared to microProfile-3.3. 10% in the worst case.

This is showing up in the profile. Opentracing looks up an optional config variable.
```
  Parent      0   0.04   3.20           3         236    J:io/openliberty/opentracing/internal/OpentracingService.process(Ljava/net/URI;Ljava/lang/String;Lio/openliberty/opentracing/internal/filters/SpanFilterType;)Z
 
    Self      0   0.04   3.20           3         236    J:io/openliberty/opentracing/internal/OpentracingConfiguration.getServerSkipPattern()Ljava/lang/String;
 
   Child      0   0.04   2.97           3         219    J:io/smallrye/config/SmallRyeConfig.getOptionalValue(Ljava/lang/String;Ljava/lang/Class;)Ljava/util/Optional;
   Child      0   0.01   0.19           1          14    J:org/eclipse/microprofile/config/ConfigProvider.getConfig(Ljava/lang/ClassLoader;)Lorg/eclipse/microprofile/config/Config;
 ```

Looking farther down the profile, it looks like we spend a lot of time iterating over the server.xml default variables (and getting env variables). This gets worse the more these methods are called.

This looks like it was recently added:
```
  Parent      0   0.18   1.53          13         113    J:io/openliberty/microprofile/config/internal/serverxml/ServerXMLVariableConfigSource.getProperties()Ljava/util/Map;
 
    Self      0   0.18   1.53          13         113    J:io/openliberty/microprofile/config/internal/serverxml/ServerXMLDefaultVariableConfigSource.getServerXMLVariables()Ljava/util/Map;
 
   Child      0   0.01   0.42           1          31    J:java/util/stream/ReferencePipeline.collect(Ljava/util/stream/Collector;)Ljava/lang/Object;
   Child      0   0.11   0.39           8          29    J:com/ibm/ws/config/xml/internal/variables/ConfigVariableRegistry.getAllLibertyVariables()Ljava/util/Collection;
   Child      0   0.00   0.33           0          24    J:java/util/stream/Collectors.toMap(Ljava/util/function/Function;Ljava/util/function/Function;)Ljava/util/stream/Collector;
   Child      0   0.14   0.22          10          16    J:java/util/Collections$UnmodifiableCollection.stream()Ljava/util/stream/Stream;
``` 

I am not sure why this didn't show up before, but this is a bit high also.
```
  Parent      0   0.08   1.17           6          86    J:io/smallrye/config/ConfigValueConfigSourceWrapper.getConfigValue(Ljava/lang/String;)Lio/smallrye/config/ConfigValue;
 
    Self      0   0.08   1.17           6          86    J:io/smallrye/config/EnvConfigSource.getValue(Ljava/lang/String;)Ljava/lang/String;
 
   Child      0   0.08   0.80           6          59    J:java/util/Collections$UnmodifiableMap.get(Ljava/lang/Object;)Ljava/lang/Object;
   Child      0   0.12   0.15           9          11    J:io/smallrye/config/EnvConfigSource.replaceNonAlphanumericByUnderscores(Ljava/lang/String;)Ljava/lang/String;
   Child      0   0.00   0.11           0           8    J:java/lang/String.toUpperCase()Ljava/lang/String;
   Child      0   0.00   0.03           0           2    J:io/smallrye/config/EnvConfigSource.getProperties()Ljava/util/Map;
 ```

This might need to be a different issue: In the test with the biggest regression (10%), I am also injecting a ConfigProperty into a default/Dependent Scoped Jax-RS Bean. This seems to be slower in mpConfig-2.0 than before. Looking at the profile is hurting my brain because the impls are different, but here is one difference.

In 2.0, an AbstractProducerBean is used, and the code path below is eventually more convoluted (some Method.invokes).
```
  Parent      0   0.02   8.79           1         529    J:org/jboss/weld/bean/ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(Ljavax/enterprise/inject/spi/Bean;Lorg/jboss/weld/manager/BeanManagerImpl;Ljavax/enterprise/context/spi/CreationalContext;)Ljava/lang/Object;
 
    Self      0   0.02   8.79           1         529    J:org/jboss/weld/contexts/unbound/DependentContextImpl.get(Ljavax/enterprise/context/spi/Contextual;Ljavax/enterprise/context/spi/CreationalContext;)Ljava/lang/Object;
   rSelf      0   0.03   0.56           2          34
 
   Child      0   0.00   5.07           0         305    J:org/jboss/weld/bean/AbstractProducerBean.create(Ljavax/enterprise/context/spi/CreationalContext;)Ljava/lang/Object;
   Child      0   0.00   3.27           0         197    J:org/jboss/weld/bean/ManagedBean.create(Ljavax/enterprise/context/spi/CreationalContext;)Ljava/lang/Object;
   Child      0   0.05   0.43           3          26    J:org/jboss/weld/contexts/unbound/DependentContextImpl.addDependentInstance(Ljava/lang/Object;Ljavax/enterprise/context/spi/Contextual;Lorg/jboss/weld/contexts/WeldCreationalContext;)V
 ```

In 1.4, a ConfigPropertyBean is used and the code path below is more straightforward.
```
  Parent      0   0.04   6.28           3         439    J:org/jboss/weld/bean/ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(Ljavax/enterprise/inject/spi/Bean;Lorg/jboss/weld/manager/BeanManagerImpl;Ljavax/enterprise/context/spi/CreationalContext;)Ljava/lang/Object;
 
    Self      0   0.04   6.28           3         439    J:org/jboss/weld/contexts/unbound/DependentContextImpl.get(Ljavax/enterprise/context/spi/Contextual;Ljavax/enterprise/context/spi/CreationalContext;)Ljava/lang/Object;
   rSelf      0   0.03   0.50           2          35
 
   Child      0   0.03   2.93           2         205    J:com/ibm/ws/microprofile/config/cdi/ConfigPropertyBean.create(Ljavax/enterprise/context/spi/CreationalContext;)Ljava/lang/Object;
   Child      0   0.00   2.76           0         193    J:org/jboss/weld/bean/ManagedBean.create(Ljavax/enterprise/context/spi/CreationalContext;)Ljava/lang/Object;
   Child      0   0.01   0.54           1          38    J:org/jboss/weld/contexts/unbound/DependentContextImpl.addDependentInstance(Ljava/lang/Object;Ljavax/enterprise/context/spi/Contextual;Lorg/jboss/weld/contexts/WeldCreationalContext;)V
```

**Comment by Azquelt** [comment]
@jdmcclur I'm reasonably confident in my assumption that the bigger numbers are bad, but what do each of the columns actually mean in these results?

**Comment by jdmcclur** [comment]
Good Question. This is taken from a sampling profile I did for a couple minutes, where I am pinging the server to find where it is "slow". 

First look at the Self Row. In the very right is how many times this method showed up in a sample somewhere on the stack (113). The column to the left of that is how many times it was on the bottom on the stack/currently doing work (13). To the left of that is the same information shown in percentages of everything going on (1.53% total, .18% on the bottom).  The "Parent" is the method that called Self, and the "Child" methods are methods called by "Self." In the real profile you can click up and down the stack to look at more things. So, I think of it as the "Self"method  and all its children are taking 1.53% of the time when I run this test.
```
Parent      0   0.18   1.53          13         113    J:io/openliberty/microprofile/config/internal/serverxml/ServerXMLVariableConfigSource.getProperties()Ljava/util/Map;
 
    Self      0   0.18   1.53          13         113    J:io/openliberty/microprofile/config/internal/serverxml/ServerXMLDefaultVariableConfigSource.getServerXMLVariables()Ljava/util/Map;
 
   Child      0   0.01   0.42           1          31    J:java/util/stream/ReferencePipeline.collect(Ljava/util/stream/Collector;)Ljava/lang/Object;
   Child      0   0.11   0.39           8          29    J:com/ibm/ws/config/xml/internal/variables/ConfigVariableRegistry.getAllLibertyVariables()Ljava/util/Collection;
   Child      0   0.00   0.33           0          24    J:java/util/stream/Collectors.toMap(Ljava/util/function/Function;Ljava/util/function/Function;)Ljava/util/stream/Collector;
   Child      0   0.14   0.22          10          16    J:java/util/Collections$UnmodifiableCollection.stream()Ljava/util/stream/Stream;
```

In this case, 1.53% isn't a huge deal, especially in a primitive, but it is an area slower than mp-3.3, so I am pointing it out.

**Comment by Azquelt** [comment]
> In my primitives with mpOpentracing enabled, I am seeing a regression with microProfile-4.0 compared to microProfile-3.3. 10% in the worst case.


> This is showing up in the profile. Opentracing looks up an optional config variable.
> 
> ```
>   Parent      0   0.04   3.20           3         236    J:io/openliberty/opentracing/internal/OpentracingService.process(Ljava/net/URI;Ljava/lang/String;Lio/openliberty/opentracing/internal/filters/SpanFilterType;)Z
>  
>     Self      0   0.04   3.20           3         236    J:io/openliberty/opentracing/internal/OpentracingConfiguration.getServerSkipPattern()Ljava/lang/String;
>  
>    Child      0   0.04   2.97           3         219    J:io/smallrye/config/SmallRyeConfig.getOptionalValue(Ljava/lang/String;Ljava/lang/Class;)Ljava/util/Optional;
>    Child      0   0.01   0.19           1          14    J:org/eclipse/microprofile/config/ConfigProvider.getConfig(Ljava/lang/ClassLoader;)Lorg/eclipse/microprofile/config/Config;
> ```

I suspect this will be consistently slower due to a lack of top-level caching in 2.0.

> Looking farther down the profile, it looks like we spend a lot of time iterating over the server.xml default variables (and getting env variables). This gets worse the more these methods are called.
> 
> This looks like it was recently added:
> 
> ```
>   Parent      0   0.18   1.53          13         113    J:io/openliberty/microprofile/config/internal/serverxml/ServerXMLVariableConfigSource.getProperties()Ljava/util/Map;
>  
>     Self      0   0.18   1.53          13         113    J:io/openliberty/microprofile/config/internal/serverxml/ServerXMLDefaultVariableConfigSource.getServerXMLVariables()Ljava/util/Map;
>  
>    Child      0   0.01   0.42           1          31    J:java/util/stream/ReferencePipeline.collect(Ljava/util/stream/Collector;)Ljava/lang/Object;
>    Child      0   0.11   0.39           8          29    J:com/ibm/ws/config/xml/internal/variables/ConfigVariableRegistry.getAllLibertyVariables()Ljava/util/Collection;
>    Child      0   0.00   0.33           0          24    J:java/util/stream/Collectors.toMap(Ljava/util/function/Function;Ljava/util/function/Function;)Ljava/util/stream/Collector;
>    Child      0   0.14   0.22          10          16    J:java/util/Collections$UnmodifiableCollection.stream()Ljava/util/stream/Stream;
> ```

The change here was due a bugfix #14576, it will affect 1.3+ (though on pre-2.0 the impact may be hidden by caching).

I've made this code a bit more performant in #14783 - turns out Streams was noticably slower than a for-loop here.

> I am not sure why this didn't show up before, but this is a bit high also.
> 
> ```
>   Parent      0   0.08   1.17           6          86    J:io/smallrye/config/ConfigValueConfigSourceWrapper.getConfigValue(Ljava/lang/String;)Lio/smallrye/config/ConfigValue;
>  
>     Self      0   0.08   1.17           6          86    J:io/smallrye/config/EnvConfigSource.getValue(Ljava/lang/String;)Ljava/lang/String;
>  
>    Child      0   0.08   0.80           6          59    J:java/util/Collections$UnmodifiableMap.get(Ljava/lang/Object;)Ljava/lang/Object;
>    Child      0   0.12   0.15           9          11    J:io/smallrye/config/EnvConfigSource.replaceNonAlphanumericByUnderscores(Ljava/lang/String;)Ljava/lang/String;
>    Child      0   0.00   0.11           0           8    J:java/lang/String.toUpperCase()Ljava/lang/String;
>    Child      0   0.00   0.03           0           2    J:io/smallrye/config/EnvConfigSource.getProperties()Ljava/util/Map;
> ```

You pointed out to me on Slack that this might be because although the EnvConfigSource has a cache, it doesn't cache missing values. I'll have a look at this next.

> This might need to be a different issue: In the test with the biggest regression (10%), I am also injecting a ConfigProperty into a default/Dependent Scoped Jax-RS Bean. This seems to be slower in mpConfig-2.0 than before. Looking at the profile is hurting my brain because the impls are different, but here is one difference.
> 
> In 2.0, an AbstractProducerBean is used, and the code path below is eventually more convoluted (some Method.invokes).
> 
> ```
>   Parent      0   0.02   8.79           1         529    J:org/jboss/weld/bean/ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(Ljavax/enterprise/inject/spi/Bean;Lorg/jboss/weld/manager/BeanManagerImpl;Ljavax/enterprise/context/spi/CreationalContext;)Ljava/lang/Object;
>  
>     Self      0   0.02   8.79           1         529    J:org/jboss/weld/contexts/unbound/DependentContextImpl.get(Ljavax/enterprise/context/spi/Contextual;Ljavax/enterprise/context/spi/CreationalContext;)Ljava/lang/Object;
>    rSelf      0   0.03   0.56           2          34
>  
>    Child      0   0.00   5.07           0         305    J:org/jboss/weld/bean/AbstractProducerBean.create(Ljavax/enterprise/context/spi/CreationalContext;)Ljava/lang/Object;
>    Child      0   0.00   3.27           0         197    J:org/jboss/weld/bean/ManagedBean.create(Ljavax/enterprise/context/spi/CreationalContext;)Ljava/lang/Object;
>    Child      0   0.05   0.43           3          26    J:org/jboss/weld/contexts/unbound/DependentContextImpl.addDependentInstance(Ljava/lang/Object;Ljavax/enterprise/context/spi/Contextual;Lorg/jboss/weld/contexts/WeldCreationalContext;)V
> ```
> 
> In 1.4, a ConfigPropertyBean is used and the code path below is more straightforward.
> 
> ```
>   Parent      0   0.04   6.28           3         439    J:org/jboss/weld/bean/ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(Ljavax/enterprise/inject/spi/Bean;Lorg/jboss/weld/manager/BeanManagerImpl;Ljavax/enterprise/context/spi/CreationalContext;)Ljava/lang/Object;
>  
>     Self      0   0.04   6.28           3         439    J:org/jboss/weld/contexts/unbound/DependentContextImpl.get(Ljavax/enterprise/context/spi/Contextual;Ljavax/enterprise/context/spi/CreationalContext;)Ljava/lang/Object;
>    rSelf      0   0.03   0.50           2          35
>  
>    Child      0   0.03   2.93           2         205    J:com/ibm/ws/microprofile/config/cdi/ConfigPropertyBean.create(Ljavax/enterprise/context/spi/CreationalContext;)Ljava/lang/Object;
>    Child      0   0.00   2.76           0         193    J:org/jboss/weld/bean/ManagedBean.create(Ljavax/enterprise/context/spi/CreationalContext;)Ljava/lang/Object;
>    Child      0   0.01   0.54           1          38    J:org/jboss/weld/contexts/unbound/DependentContextImpl.addDependentInstance(Ljava/lang/Object;Ljavax/enterprise/context/spi/Contextual;Lorg/jboss/weld/contexts/WeldCreationalContext;)V
> ```

The different code path is because 1.4 uses a custom `Bean` impl whereas 2.0 uses a producer method. From my local profiling, it looked like they had slow parts outside of the config code in approximately the same place (primarily `BeanManagerImpl.getInjectableReference` where it's getting a reference to an `InjectionPoint` object), but that the 2.0 impl takes much longer to do the actual lookup due to lack of caching (compare time spent in `Config14Impl.getCachedRawValue()` (1.4) with time spent in `ConfigProducerUtil.getRawValue()` (2.0))

**Comment by Azquelt** [comment]
Next time we consume smallrye-config, we should pick up smallrye/smallrye-config#440 which will cache the result of failed lookups from the env config source.

**Comment by jdmcclur** [comment]
Excellent, can you let me know next time we consume it and I'll rerun my tests.
