### ISSUE TITLE
Add trace for support team of unshared connections that are both closed or not closed by the container

### ISSUE THREAD

**Issue by jmstephensgit** [OpenLiberty/open-liberty#14761]
User Story,

As the support team debugging the connection manager using a JDBC connection when WAS=j2c=all trace is enabled, add tracing of unshared connections that are both closed and not closed by the web or ejb container at the end of the scope of the local transaction coordinator (LTC), so that I have enough information to be able to debug the missing connection close for the user to correct the error in the application code.

**Comment by njr-11** [comment]
Covering this under the solution to #14760 (informational message to users about leaked connections).  Leaked connection stacks that are not logged as an informational message will be traced instead.
