### ISSUE TITLE
FAT Approval Test Summary: 9786 Read Kubernetes config in as Liberty config variables

### ISSUE THREAD

**Issue by brenthdaniel** [OpenLiberty/open-liberty#14768]
**1) All testing is automated and exists in the com.ibm.ws.config.variables_fat. There are also existing tests that touch on this function in com.ibm.ws.config_fat, but nothing specific was added there. 

Testing in the FAT framework uses files created by the test suite to simulate the work that the service binding operator or an administrator would do. Scenarios covered include:

1. Reading a variable from a simple file (eg, wlp/usr/servers/server1/bindings/simple -> ${simple} )
2. Reading a variable from a file within a directory (eg wlp/usr/servers/server1/bindings/account_db/username -> ${account_db/username} )
3. Testing the case where no variables are defined
4. Ensuring that reading a large binary file results in an error
5. Test changing the directory where variables are specified
6. Test merge behavior when variables are defined in server.xml, bootstrap.properties, etc, as well as on the file system.
7. Test an empty file
8. (Implicitly) test that variables are updated when the files are changed on the file system
9. Test that variables are updated when using mbean configuration updates
10. Test reading variables from properties files
11. Test creating/updating/deleting entries in property files and make sure changes are reflected in configuration

**2) 

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

**Comment by ayoho** [comment]
I agree with the evaluation and think the coverage is sufficient 👍
