### ISSUE TITLE
CDI.current is null if called from a different thread

### ISSUE THREAD

**Issue by rdehuyss** [OpenLiberty/open-liberty#14779]
**Describe the bug**
CDI.current() is null when called from a different thread.

**Steps to Reproduce**
Call CDI.current() from a different thread.

Example:
```
    @GET
    @Path("/test-cdi")
    @Produces(MediaType.APPLICATION_JSON)
    public SimpleResponse testCDI() {

        new Thread(() -> {
            LOGGER.info("Before CDI call");
            LOGGER.info("Test CDI: " + CDI.current());
        }).start();

        return new SimpleResponse("Job Enqueued");
    }
```

**Expected behavior**
CDI not to be null

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.11
 - Java Version: [i.e. full output of `java -version`]
```
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9+11-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```
 - server.xml configuration (WITHOUT sensitive information like passwords)
```xml
<server description="JobRunr Open Liberty MicroProfile server">
    <featureManager>
        <feature>jaxrs-2.1</feature>
        <feature>jsonp-1.1</feature>
        <feature>jsonb-1.0</feature>
        <feature>cdi-2.0</feature>
        <feature>mpConfig-1.4</feature>
    </featureManager>

    <variable name="default.http.port" defaultValue="9080"/>
    <variable name="default.https.port" defaultValue="9443"/>

    <webApplication context-root="/" location="example-microprofile.war"/>

    <httpEndpoint host="*" httpPort="${default.http.port}" httpsPort="${default.https.port}" id="defaultHttpEndpoint"/>
</server>
```
**Additional context**
- CDI.current() is not null in Quarkus (also called from a different thread).

**Comment by benjamin-confino** [comment]
Hello. 

Calling `CDI.current()` from inside a `new Thread()` is not supported as `CDI.current()` requires context that `new Thread()` does not propagate into the new thread. 

Please use a `ManagedExecutorService` instead.

**Comment by tevans78** [comment]
@rdehuyss Note that the reason it works ok in Quarkus is that there is only ever one application running. In Open Liberty there can be multiple applications running in the same server and so some context is required.
