### ISSUE TITLE
Test Failure: org.eclipse.microprofile.metrics.tck.metrics.ConcurrentGaugeFunctionalTest.testMinMax

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#14785]
RTC 279247

```
testMinMax:java.util.concurrent.TimeoutException: null
at org.eclipse.microprofile.metrics.tck.util.TimeUtil.waitForNextMinute(TimeUtil.java:61)
at org.eclipse.microprofile.metrics.tck.metrics.ConcurrentGaugeFunctionalTest.testMinMax(ConcurrentGaugeFunctionalTest.java:86)
```

**Comment by Channyboy** [comment]
See https://github.com/eclipse/microprofile-metrics/blob/master/tck/api/src/main/java/org/eclipse/microprofile/metrics/tck/util/TimeUtil.java

Potential cause for error could be that the background thread that the `Timer` uses for the scheduled task has been held up for 5 seconds or more.

Will update the TCK code to extend wait time by 5-10 seconds.

**Comment by fmhwong** [comment]
No occurrences in last 2 weeks.

**Comment by Channyboy** [comment]
Also See associated PR on Microprofile Metrics: https://github.com/eclipse/microprofile-metrics/pull/620
