### ISSUE TITLE
MP Config 2.0 escape characters in Config Property Values

### ISSUE THREAD

**Issue by Joseph-Cass** [OpenLiberty/open-liberty#14837]
The following System property value `C:\ibm-ucd\agent\opt\groovy-1.8.8\bin\` is interpreted as `C:ibm-ucdagentoptgroovy-1.8.8in\` when derived from a Default ConfigSource on a Windows machine.

This should not be the behaviour, and we should have a test for this, perhaps even a TCK.

**Comment by Azquelt** [comment]
This is probably the relevant part of the smallrye code: https://github.com/smallrye/smallrye-config/blob/mpconfig20/implementation/src/main/java/io/smallrye/config/ExpressionConfigSourceInterceptor.java#L55-L57

**Comment by Joseph-Cass** [comment]
This was resolved in this commit: https://github.com/smallrye/smallrye-config/commit/468aaf1dc992834bb6488ac2c06910dd0cc1b72e

I will write a FAT for it now.
