### ISSUE TITLE
GA BLOG - Support for Custom JNDI Names for Enterprise Beans

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#14850]
The information you provide here will be included in the Open Liberty GA release blog post ([example](https://openliberty.io/blog/2020/07/30/json-logging-open-liberty-20008.html)), which will be published on the OpenLiberty.io blog, and potentially elsewhere, to promote this release of Open Liberty.

Please provide the following information the week before the GA date (to allow for review and publishing):

1. Which Liberty feature does your update relate to?
    
   Human-readable name (eg WebSockets feature):   
    > Enterprise JavaBeans
    > Enterprise JavaBeans Lite
    > Enterprise JavaBeans Home Interfaces
    > Enterprise JavaBeans Remote
    > Enterprise JavaBeans Persistent Timers  
     
   Feature name (eg websockets-1.0): 
    > ejb-3.2
    > ejbLite-3.2
    > ejbHome-3.2
    > ejbRemote-3.2
    > ejbPersistentTimer-3.2  
  
2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.

> Application developer

3. Write a paragraph to summarises the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.

   - What was the problem before and how does your update make their life better? (Why should they care?)
   
   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.
   
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?

If you have previously provided this information for an Open Liberty beta blog post and nothing has changed since the beta, just provide a link to the published beta blog post and we'll take the information from there.

## What happens next?

- Your paragraph will be included in the GA release blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the GA blog post).

---------
### What is Support for Custom JNDI Names for Enterprise Beans?

Support for Custom JNDI Names for Enterprise Beans (EJBs) is an enhancement to all existing enterprise beans features that allows an application to configure and use custom JDNI names for looking up and/or injecting enterprise beans, and to also use legacy default JNDI names from WebSphere traditional.

Prior to this enhancement, Liberty only supported looking up enterprise beans using the specification define JNDI names :  `java:global/<app>/<module>/<bean>!<interface>` & variations for `java:app` and `java:module`.

Without any additional configuration, the default JNDI names that were available on WebSphere traditional are now available for applications to use to lookup and/or inject enterprise beans.  Also, rather than using the defaults, a custom name for each EJB may be specified in the `ibm-ejb-jar-bnd.xml` file (or `ibm-ejb-jar-bnd.xmi` file for EJB 2.x and 1.x modules). This file is the same format as used by WebSphere traditional. These new JNDI name options are available in addition to the existing specification required names.

#### Easier Migration for Enterprise Bean Applications

Custom JNDI name support for enterprise beans provides an easier migration path for applications from other platforms (including WebSphere traditional).

Prior to Java EE 6, the Enterprise Beans specification did not prescribe the JNDI names required for enterprise beans, so every platform provided platform specific default names and custom binding file formats. Since Liberty only supported the specification defined JNDI names, migrating applications from other platforms often requires code changes to modify the platform specific JNDI names to the newer specification defined names.

Since Liberty now supports the same default JNDI names, and same binding file format as WebSphere traditional, code changes to modify the JNDI lookup names are no longer required when migrating EJB applications from WebSphere traditional to Liberty.
Migration from other platforms is also simplified because applications may be migrated without changing code, but instead migrating the other platform specific binding files to the new Liberty platform specific binding file format.

#### Application Configuration details

Full details about the legacy default bindings provided, as well as the syntax for declaring custom JNDI names in the ibm-ejb-jar-bnd.xml file, including examples, may be found in the following Knowledge Center article:

https://www.ibm.com/support/knowledgecenter/SSEQTP_9.0.5/com.ibm.websphere.base.doc/ae/cejb_bindingsejbfp.html

Custom bindings may be configured for an application in the following three locations.

##### 1 : Specify Custom bindings in `ibm-ejb-jar-bnd.xml` for EJB 3.x
Following are examples of how to configure custom bindings for EJB 3.x beans in an EJB JAR module or WAR module in `ibm-ejb-jar-bnd.xml`

Specify a binding per interface:
```
   <session name="NoInterceptorBasicStateless">
      <interface class="com.ejbs.InventoryService" binding-name="ejb/Inventory"/>
   </session>
```
Specify a component id (a prefix for default long form bindings)
```
   <session name="AccountServiceBean" component-id="Dept549/AccountProcessor"/>
```
Simple binding name (one name used for both local and remote)
```
   <session name="AccountServiceBean" simple-binding-name="ejb/AccountService"/>
```
Local and Remote home specific binding names
```
   <session name="AccountServiceBean" local-home-binding-name="ejblocal:AccountService"/>
   <session name="AccountServiceBean" remote-home-binding-name="ejb/services/AccountService"/>
```

##### 2 : Specify Custom bindings in server.xml
Following is an example of how to configure custom bindings for EJB 3.x beans in an EJB JAR module or WAR module in `server.xml` in the `<application>` or `<ejbApplicationd>` elements:
```
   <ejbApplicationlocation="EJBTest.jar">
      <ejb-jar-bnd>
         <session name="InventoryServiceBean">
            <interface class="com.ejbs.InventoryService" binding-name="ejb/Inventory"/>
         </session>
      </ejb-jar-bnd>
   </ejbApplication>
```
##### 3 : Specify Custom bindings in ibm-ejb-jar-bnd.xmi for EJB 1.x/2.x 
Following is an example of how to configure custom bindings for EJB 1.x or 2.x beans in an EJB JAR module in `ibm-ejb-jar-bnd.xmi`

EJB 1.x and 2.x provide a single JNDI name that applies to both the remote and local home:
```
   <ejbBindings xmi:id="BeanBinding_8" jndiName="suite/r6x/base/misc/poollimits/SLCMTTxTimeoutHome">
      <enterpriseBean xmi:type="ejb:Session" href="META-INF/ejb-jar.xml#SLCMTTxTimeout"/>
   </ejbBindings>
```
For a bean with both a remote and local home, the above will provide the following custom bindings:
```
   Remote Home : suite/r6x/base/misc/poollimits/SLCMTTxTimeoutHome
   Local Home  : local:suite/r6x/base/misc/poollimits/SLCMTTxTimeoutHome
```

#### Feature configuration details

Support for custom and legacy default JNDI names is enabled by default for all Enterprise Bean (EJB) features. This support will not interfere with the existing specification defined `java:` support.  However, it is possible to completely disable the new support with the following setting in server.xml:
```
    <ejbContainer bindToServerRoot=“false"/>
```
It is also possible to disable just the legacy short form default JNDI name support (i.e. the bean is bound using the interface name) with the following setting in server.xml:
```
   <ejbContainer disableShortDefaultBindings=“true"/>
```
Since the new support for customer JNDI names and legacy defaults provider alternative JNDI names, it is now possible to disable the EJB specification required JNDI names.  This is done in server.xml as follows:
```
   <ejbContainer bindToJavaGlobal=“false"/>
```
Finally, the following new configuration attribute on the `<ejbContainer>` element in open-liberty enables the WebSphere traditional behavior of failing application start when multiple beans are bound to the same JNDI name:
```
    <ejbContainer customBindingsOnError=“FAIL"/>
```

**Comment by jakub-pomykala** [comment]
Done, thank you!
