### ISSUE TITLE
Should the TransactionManager be exposed for better integration with Spring JPA

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#1487]
The Spring JPA technology does not currently integrate with Liberty's transaction service because the [`org.hibernate.engine.transaction.jta.platform.spi.JtaPlatform`](https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/java/org/hibernate/engine/transaction/jta/platform/spi/JtaPlatform.java) from Liberty does not have a proper implementation.

Thus far, Hibernate has not been able to make a proper implementation of `JtaPlatform` for interop with Liberty because one of the methods requires the application server to expose its TransactionManager (TxM) to Hibernate.  Access to the TxM is significant because it would allow non-Liberty applications/libraries to fully manipulate transactions (see [TransactionManager javadoc](https://docs.oracle.com/javaee/7/api/javax/transaction/TransactionManager.html))

Currently we have a dynamic proxy implementation of `JtaPlatform` called `com.ibm.ws.jpa.hibernate.LibertyJtaPlatform` which is active for the jpaContainer-2.1 feature.  This works because the `LibertyJtaPlatform` uses an internal accessor method to obtain a TxM and return it to Hibernate.

The current set of WAS-Hibernate integration code dates back to early tWAS and reflects into WAS JTA extension APIs, which still work on Liberty, but much of the WAS-Hibernate integration code still cannot be implemented (i.e. throws UnsupportedOperationException).
[WebSphereExtendedJtaPlatform source](https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/java/org/hibernate/engine/transaction/jta/platform/internal/WebSphereExtendedJtaPlatform.java)
  
Some options:
1. Register TxM in JNDI under `java:comp/LibertyTransactionManager` and implement a `LibertyJtaPlatform` and contribute to Hibernate
1. Create/extend the IBM-API in tx.jta.extensions bundle to add a method which expose the TxM and implement a `LibertyJtaPlatform` and contribute to Hibernate
1. Move LibertyJtaPlatform to the transaction feature and expose it as IBM-API.  Update Hibernate to look for `LibertyJtaPlatform` and apply it.  (Note, this would still expose the TxM)

**Comment by NottyCode** [comment]
It turns out that there is already an API exposed for this. However it was exposed by mistake so it is being checked to ensure it does the right thing. In principle it is agreed that this should be accessible. However a trace statement should be logged when the API is used in case improper use causes problems.

**Comment by aguibert** [comment]
I did confirm that the following maven dependency is available publicly and contains the necessary API:
https://mvnrepository.com/artifact/com.ibm.websphere.appserver.api/com.ibm.websphere.appserver.api.transaction/1.1.19

**Comment by lostiniceland** [comment]
@aguibert @NottyCode Please consider reopening this. I came across this issue after opening [this](https://developer.ibm.com/answers/questions/495925/openliberty-inject-jta-transactionmanager-in-start.html) question on IBM Answers community.

I need the ability to lookup the JTA TransactionManager (CMP) via JNDI to integrate a Camunda BPMN engine. 

Currently I am using the ibm-specific api and configure Camunda programatically as a workaround. But a better approach is to use a Camunda configuration-file and this approach only supports TransactionManager via JNDI-lookup.

It would be great if we could lookup the TransactionManger via _java:comp/TransactionManager_

**Comment by aguibert** [comment]
hi @lostiniceland, this issue was specifically for integrating better with Hibernate.

We have considered putting the TransactionManager into JNDI in the past, but decided against it. Also, `java:comp/TransactionManager` is not a spec-defined JNDI name, so that JNDI lookup should not be considered portable. If a non-portable solution is sufficient, you can call `com.ibm.tx.jta.TransactionManagerFactory.getTransactionManager()`

**Comment by lostiniceland** [comment]
But were's the problem? The TransactionManager interface is portable, the only thing not portable at the moment is the String under which it is available in JNDI. This could be fixed in JEE 9 and it shouldnt be much of a problem for the vendors to change a config String.
Or are there other technical concerns why the actual vendor TransactionManagerImpl cannot easily be made available?

**Comment by schowave** [comment]
Is it possible to access the `com.ibm.tx.jta.TransactionManagerFactory.getTransactionManager()` also under JakartaEE? I don't find a fitting artifact on maven central to be able to compile my Code while moving to JakartaEE 9. In the runtime package it is available in the jar: `wlp/dev/api/ibm/io.openliberty.transaction_1.1.60.jar`...
