### ISSUE TITLE
BETA BLOG - Using Kubernetes secrets in Liberty variables

### ISSUE THREAD

**Issue by brenthdaniel** [OpenLiberty/open-liberty#14889]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on the OpenLiberty.io blog, and potentially elsewhere, to promote this beta of Open Liberty.

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature does your update relate to?
    
   Human-readable name (eg WebSockets feature): Liberty configuration variables
   
   Feature name (eg websockets-1.0): N/A (this is core kernel function)

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.
   DevOps engineers who want to use Kubernetes secrets in a Liberty environment. 

3. Write a paragraph to summarises the update, including the following points:
    In a cloud environment, sensitive information such as passwords and OAuth tokens may be stored in Kubernetes secrets. To access these secrets today in Liberty via configuration variables they would need to be exposed as environment variables in a Kubernetes pod. This update will allow configuration variables to be automatically populated from Kubernetes secrets without having to expose them as environment variables. 
  
    To make use of this function, the Kubernetes secrets need to be mapped to the file system, either by using the service binding operator or by mounting the secrets to a volume in the pod definition. Files will be read from the location defined in the SERVICE_BINDING_ROOT environment variable, which defaults to WLP_CONFIG_DIR/bindings. The variable name will be taken from the name of the file, and the value will be the contents of the file. 

  For example, we may have a Kubernetes secret named 'account_database' that contains a username and password:

![image](https://user-images.githubusercontent.com/5082719/98569260-f22d5d80-2266-11eb-9601-9980e89084d7.png)

  The service binding operator can automatically map that secret to the file system, or it could be done manually in a deployment definition:

![image](https://user-images.githubusercontent.com/5082719/98569384-1852fd80-2267-11eb-8818-c83a851e939e.png)

The above definition will result in the files /bindings/account_db/username and /bindings/account_db/password being created when the pod is created. Liberty will create variables from both files, and users can access them using normal Liberty variable syntax, `${account_db/username}` and `${account_db/password}`. 

References:
  Service Binding specification: https://github.com/k8s-service-bindings/spec
  Kubernetes Secrets: https://kubernetes.io/docs/concepts/configuration/secret/

 
## What happens next?

- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by jakub-pomykala** [comment]
Done. Thank you
