### ISSUE TITLE
GA BLOG - grpc-1.0 and grpcClient-1.0

### ISSUE THREAD

**Issue by wtlucy** [OpenLiberty/open-liberty#14890]
The information you provide here will be included in the Open Liberty GA release blog post ([example](https://openliberty.io/blog/2020/07/30/json-logging-open-liberty-20008.html)), which will be published on the OpenLiberty.io blog, and potentially elsewhere, to promote this release of Open Liberty.

Please provide the following information the week before the GA date (to allow for review and publishing):

1. Which Liberty feature does your update relate to?
    
   Human-readable name (eg WebSockets feature): 
   > gRPC and gRPC Client

   Feature name (eg websockets-1.0): 
   > grpc-1.0 and grpcClient-1.0

If you have previously provided this information for an Open Liberty beta blog post and nothing has changed since the beta, just provide a link to the published beta blog post and we'll take the information from there.

> These new features were discussed in the August beta blog post:
https://github.com/OpenLiberty/open-liberty/issues/12696
https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html

>Since the August beta, we've created small sample application.  It would be useful to link to that as well: https://github.com/OpenLiberty/sample-grpc

## What happens next?

- Your paragraph will be included in the GA release blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the GA blog post).

**Comment by jakub-pomykala** [comment]
Thank you!
