### ISSUE TITLE
Core application stack for Open Liberty - v1.0 

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/open-liberty#14892]
# Release v1.0 of the java-openliberty devfile stack.

![image](https://user-images.githubusercontent.com/4081634/108520849-1d2d4180-7299-11eb-874e-13999f7dd2be.png)

(from UFO precursor at "IBM-only" link :  https://ibm.box.com/s/g3olqch64kh81jja9oyo9bo5jtwp4rx1 )

##  WHAT IS BEING DELIVERED?

The stack delivers a devfile pointing to
 * an outer loop build: Dockerfile + deploy template (using Open Liberty operator)
 * starter(s)
 * a custom stack image

##  WHO USES IT?

* A developer (Jane) - using our devfile directly in her project or customizing or extending ours with her own
* An architect/team lead (Champ) - customizing or extending our devfile, possibly with stack image, and starter(s), and making available via a devfile registry.

## WHAT TOOLS DO YOU USE IT WITH ?

It fits into the devfile ecosystem, allowing use with:
* OpenShift Do (odo) 
* Eclipse Che-like IDE environments.  

Our devfile becomes "content" then for this framework or ecosystem.

### NOTE ON DEPENDENCIES !

A set of design details and release plans are contingent on plans for these other tools.  These details and plans are dependencies then of our feature here.  We will make the dependency details clearer as required and as we're able to.

## HISTORY

This builds upon work in #9343 delivered as tech preview in IBM Cloud Pak For Applications v4.3 in 4Q20.  It also represents the revolution and replacement the appsody/kabanero-based java-openliberty "stack" technology.

# PROPOSED FEATURE CONTENT

### Basics
* Project format - "ideal POM" - existing WAR module
* Inner loop – liberty:dev mode + hotTests
* Outer loop – Multi-stage Dockerfile & OL Operator deployment, pipeline? (RedHat) 
* Custom, multi-arch (x/p/z) stack image with maven / OL caches
* Starter project – "default" starter =>  MicroProfile 4 + JAX-RS + IT
* Customizable (branch/fork) & Extensible (inherit/parent) – (Jane and/or Champ)
### Database integration 
* JPA Starter - prototype w/ PostgreSQL (come back -> DB2 +commercial DBs?)
* integration with common k8s ways (manifest, Helm, operator-backed)
### Ecosystem (RedHat) 
* Devfile 2.2 -  integrates with:    a)  odo v2 CLI  b) IDE (Che/Theia/VSCode)
* Custom Devfile Registry tools
* Integration with Service Binding Operator 
### Documentation
* openliberty.io/docs,  Open Liberty guide, Red Hat doc

**Comment by scottkurz** [comment]
Finer-grained tracking of work will be performed in application-stack repo epic:  https://github.com/OpenLiberty/application-stack/issues/116

**Comment by yeekangc** [comment]
Splitting the work into #19019 and #14892.  Work is already in progress.  Then, #19019 is what we will focus on (delivering) first.  So, pausing on #14892 (so to speak) and focusing on #19019.

**Comment by yeekangc** [comment]
Closing per discussion with @NottyCode @gcharters.  Will file new epics for any future devfile work.
