### ISSUE TITLE
 HTTP Strict-Transport-Security not supported in webContainer in server.xml or not missing document

### ISSUE THREAD

**Issue by Kenzku** [OpenLiberty/open-liberty#14902]
`<webContainer addstricttransportsecurityheader="max-age=31536000;includeSubDomains" />` is not support or documented at https://openliberty.io/docs/20.0.0.7/reference/config/webContainer.html

I can set this value based on WebSphere liberty, the according to https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_sec_hsts.html

but the same setting is missing from OpenLiberty

**Comment by pmd1nh** [comment]
checking see if we have exposed it via metatype

**Comment by pnicolucci** [comment]
This work was done here: https://github.com/OpenLiberty/open-liberty/issues/13515

**Comment by pnicolucci** [comment]
Closing this issue as the metatype is now exposed and documented: https://openliberty.io/docs/21.0.0.1/reference/config/webContainer.html

**Comment by Kenzku** [comment]
@pnicolucci Thanks for the update
