### ISSUE TITLE
MPConfig 1.2: support array, List and Set converter

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#1490]
Implementations must now support the array converter (eclipse/microprofile-config#259). For the array converter, the programmatic lookup of a property (e.g. config.getValue(myProp, String[].class)) must support the return type of the array. For the injection lookup, an Array, List or Set must be supported as well (e.g. @Inject @ConfigProperty(name="myProp") private List<String> propValue;).

**Comment by tevans78** [comment]
fixed under #1491
