### ISSUE TITLE
mpConfig1.2: Implementations must also support Class converter (#267)

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#1492]
Implementations must also support Class converter (https://github.com/eclipse/microprofile-config/issues/267)
```
Class<?> testClass = config.getValue("tck.config.test.javaconfig.converter.class", Class.class);
Class<?>[] testClasses = config.getValue("tck.config.test.javaconfig.converter.class.array", Class[].class);
```
https://github.com/eclipse/microprofile-config/blob/1.2/spec/src/main/asciidoc/converters.asciidoc#built-in-converters

**Comment by tevans78** [comment]
fixed under #1491
