### ISSUE TITLE
mpConfig 1.2: spi updates

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#1493]
The ConfigBuilder SPI has been extended with a method that allows for a converter with the specified class type to be registered (eclipse/microprofile-config#205). This change removes the limitation, which was unable to add a lambda converter, from the previous releases.

**Comment by tevans78** [comment]
The implementation of this SPI change has been included in PR #1532 but still needs additional tests added ... so will use this issue to do that.
