### ISSUE TITLE
BETA BLOG - MP Rest Client 2.0 #10786

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#14949]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on the OpenLiberty.io blog, and potentially elsewhere, to promote this beta of Open Liberty.

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature does your update relate to?
    
   Human-readable name (eg WebSockets feature): **MicroProfile REST Client 2.0**
   
   Feature name (eg websockets-1.0): `mpRestClient-2.0`

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.

**Application Developer**

3. Write a paragraph to summarise the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.

   - What was the problem before and how does your update make their life better? (Why should they care?)
   
   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.
   
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?

> MicroProfile REST Client is a type-safe client API enabling rapid development of applications capable of consuming RESTful services.  Version 2.0 is the latest update and add support for HTTP proxy servers, automatically following HTTP redirects, additional configuration options for JSON-B providers and how multiple query parameters should be specified, and support for Server Sent Events.
> 
> To enable this feature, add `<feature>mpRestClient-2.0</feature>` to you list of features in the `<featureManager>` element - the `microprofile-4.0` convenience feature will also enable this feature.
> 
> For examples of how to these new features, please refer to the [specification document](http://download.eclipse.org/microprofile/microprofile-rest-client-2.0-RC2/microprofile-rest-client-2.0-RC2.html) or the [MP Rest Client project page](https://github.com/eclipse/microprofile-rest-client).

## What happens next?

- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by andymc12** [comment]
This is the beta blog entry for epic issue #10786.

**Comment by jakub-pomykala** [comment]
Done. Thank you

**Comment by andymc12** [comment]
@Emily-Jiang requested that we update this blog entry to include more details.

**Comment by andymc12** [comment]
I made suggested updates in PR https://github.com/OpenLiberty/blogs/pull/1118

Note, it includes an embedded video link from my personal YouTube channel.  Ideally this video would be hosted under the [IBM Developer channel](https://www.youtube.com/user/developerworks/featured) - @GraceJansen said she would look into this on Monday.

**Comment by jakub-pomykala** [comment]
Closing this issue as the blog has been updated and the video is live on IBM Developer.
