### ISSUE TITLE
Not seeing APIs for apidiscovery

### ISSUE THREAD

**Issue by sunnypatel2141** [OpenLiberty/open-liberty#14980]
Our service uses `feature>apiDiscovery-1.0</feature>` in server.xml.

For our production system, we have `<apiDiscovery publicURL="replication/v2" />`.

The logs for this server print out the following:
```
[INFO    ] SESN0176I: A new session context will be created for application key default_host/ibm/api/explorer
[AUDIT   ] CWWKT0016I: Web application available (default_host): https://ibm-replication-apiserver-558cf857d6-649xn:9443/ibm/api/explorer/
[AUDIT   ] CWWKT0016I: Web application available (default_host): https://ibm-replication-apiserver-558cf857d6-649xn:9443/replication/v2/explorer/
[INFO    ] SESN0176I: A new session context will be created for application key default_host/replication/v2/explorer
```

We have an Ingress where we're tied to https://api.dataplatform.dev.cloud.ibm.com/replication/v2/explorer/ endpoint. But this is showing no APIs. 
<img width="870" alt="Screen Shot 2020-11-16 at 11 42 45 AM" src="https://user-images.githubusercontent.com/12205238/99281726-dabf1900-2800-11eb-82f0-7e0ac0aa25cd.png">

There's dev environment where we don't have `<apiDiscovery publicURL="replication/v2" />`, and the endpoint there is showing the same thing: https://dmclego4vip1.canlab.ibm.com/api/explorer/

Comparatively, we have **openapi** configured at a separate endpoint and no issues seeing things there: https://dmclego4vip1.canlab.ibm.com/openapi/ui#

**Comment by sunnypatel2141** [comment]
Also seeing the following in the logs:
```
[ERROR   ] CWWKE0701E: bundle com.ibm.ws.rest.api.discovery:1.0.46.cl201120201014-1215 (102)[com.ibm.ws.rest.api.discovery.APIProviderAggregator(346)] : The setServerStartedPhase2 method has thrown an exception java.lang.NoSuchMethodError: com/fasterxml/jackson/databind/introspect/AnnotatedMember.getType(Lcom/fasterxml/jackson/databind/type/TypeBindings;)Lcom/fasterxml/jackson/databind/JavaType; (loaded from file:/opt/ibm/wlp/lib/io.openliberty.com.fasterxml.jackson_2.11.46.jar by org.eclipse.osgi.internal.loader.EquinoxClassLoader@c4a58292[io.openliberty.com.fasterxml.jackson:2.11.46.cl201120201014-1215(id=170)]) called from class v2.io.swagger.jackson.ModelResolver (loaded from file:/opt/ibm/wlp/lib/com.ibm.ws.io.swagger.core_1.0.46.jar by org.eclipse.osgi.internal.loader.EquinoxClassLoader@8f950fce[com.ibm.ws.io.swagger.core:1.0.46.cl201120201014-1215(id=100)]).
]
```

**Comment by NottyCode** [comment]
There is no feature in Open Liberty called apiDiscovery. There is a stabilized feature in WebSphere Liberty which is upstream of this project. If you are having problems with WebSphere Liberty you need to contact IBM support.

**Comment by sunnypatel2141** [comment]
It worked by changing server.xml with:
```
    <featureManager>
        <feature>jaxrs-2.1</feature>
        <feature>openapi-3.0</feature>
        <feature>mpOpenAPI-1.1</feature>
    </featureManager>
```

And DockerFile: `RUN /opt/ibm/wlp/bin/installUtility install jaxrs-2.1 openapi-3.0 mpOpenAPI-1.1 --acceptLicense 
`
