### ISSUE TITLE
Migrate servlet-3.1 tests away from Shared Server

### ISSUE THREAD

**Issue by isaacrivriv** [OpenLiberty/open-liberty#14989]
Update tests for *com.ibm.ws.webcontainer.servlet.3.1_fat* to stop using the deprecated Shared Server.

JSPServerHttpUnit was done here: https://github.com/OpenLiberty/open-liberty/issues/16449
VHServerHttpUnit was  done here: https://github.com/OpenLiberty/open-liberty/issues/16452
HttpSessionAttListener was done here: https://github.com/OpenLiberty/open-liberty/issues/16468
WCServerHttpUnit was done here: https://github.com/OpenLiberty/open-liberty/issues/16478
UpgradeWrite/ReadListenerHttpUnit was done here: https://github.com/OpenLiberty/open-liberty/issues/16557
UpgradeReadWriteTimeoutHttpUnit  was done here: https://github.com/OpenLiberty/open-liberty/issues/16568
AsyncRead/WriteListenerHttpUnit was done here: https://github.com/OpenLiberty/open-liberty/issues/16638
FormLoginReadListenerTest was done here: https://github.com/OpenLiberty/open-liberty/issues/16741
CDINoInjectionTests was done here: https://github.com/OpenLiberty/open-liberty/issues/16797
CDITests was done here: https://github.com/OpenLiberty/open-liberty/issues/17421
NBMultiReadTest was done here: https://github.com/OpenLiberty/open-liberty/issues/19935

**Comment by tssmith04** [comment]
Remaining Test Classes:
- [x] CDIBeanInterceptorServletTest
- [x] CDIListenersTest
- [x] CDIServletFilterListenerDynamicTest
- [x] CDIServletFilterListenerTest
- [x] CDIServletInterceptorTest
- [x] CDIUpgradeHandlerTest
- [x] WCServerTest
