### ISSUE TITLE
GA BLOG - MicroProfile Metrics 3.0 for 21.0.0.3

### ISSUE THREAD

**Issue by Channyboy** [OpenLiberty/open-liberty#15045]
# **This item is a place holder for now. The MicroProfile Metric 3.0 specification has yet to be released. Thus the mpMetrics-3.0 has yet to be GAed.**

- Development progress update

  - a. Which Liberty feature does it relate to?
    - i. Human-readable name (eg WebSockets feature)
      - `MicroProfile Metrics 3.0`
    - ii. Feature name (eg websockets-1.0)
      - `mpMetrics-3.0`
    - iii. Is this a new feature or is it an update to an existing feature for this release?
      - `This is a new feature to support the MicroProfile Metrics 3.0 specification.`
    - iv. Provide the fully qualified name of all public features ( as '*.esa' filenames) that are delivered as part of this work
       (eg: com.ibm.websphere.appserver.transportSecurity-1.0.esa)
      - `io.openliberty.org.eclipse.microprofile.metrics-3.0.esa`

       For example new or changed .esa files for public features in dev/com.ibm.websphere.appserver.features/build/libs/repo/

  - b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc
    - `Application developers and administrators`
  - c. Write a sentence or two that introduces it to someone new to the general technology/concept.
     - `MicroProfile Metrics 2.3 enables developers to instrument metrics in their (microservice) applications for easy monitoring by their operations team.`
  - d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)

MicroProfile Metrics 3.0 (as part of MicroProfile 4.0) introduces new metric values for the existing SimpleTimer and Timer metrics. Additionally a new REST metric is introduced for better monitoring and handling of unmapped exceptions. Manual configuration for re-usability has been removed. A notable change to the MP Metrics programming model regarding CDI Producers has been made. Lastly a medley of API improvements and refactoring have been added in this release.

**SimpleTimer**

The SimpleTimer metric now tracks and reports the highest and lowest recorded time duration of the previous complete minute. See the [SimpleTimer.java](https://github.com/eclipse/microprofile-metrics/blob/3b1a03b4834a9a7c660c79cbf4c3c515f8f8494b/api/src/main/java/org/eclipse/microprofile/metrics/SimpleTimer.java) for more more information in the Javadoc.

**Histogram**
The Histogram metric now exposes the summation of values recorded in both OpenMetrics format and JSON format. In JSON format it is exposed as `sum`. In OpenMetrics format it is exposed as `sum` under the `summary` type.

**Timer**
The Time metric now  tracks and reports the total elapsed time duration. See the [Timer.java](https://github.com/eclipse/microprofile-metrics/blob/3b1a03b4834a9a7c660c79cbf4c3c515f8f8494b/api/src/main/java/org/eclipse/microprofile/metrics/Timer.java) for more information in the Javadoc. This elapsed time value is exposed as a `sum` under the `summary` type in OpenMetrics format. Under JSON format, it is exposed as `elapsedTime`.

**REST metric**
A new `REST.request.unmappedException.total` metric that is backed by a _counter_ metric has been introduced. Similar to the `REST.request` metric, there will be one unique metric for each REST endpoint identified by a class and method label. The new REST metric will count the amount of times the request ends in an unmapped exception. The `REST.request` metric corresponding to this REST endpoint will not record any values if an unmapped exception has occurred.

**CDI Producer**
The `@Metrics` annotation will no longer support the method target (i.e it can not be annotated on a method). Additionally, it will not support usage with CDI Producers. 

  - e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.

```
<feature>mpMetrics-3.0</feature>
```

  - f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

[MicroProfile Metrics 3.0 Release Page](https://github.com/eclipse/microprofile-metrics/releases/tag/3.0)
[Release Notes](https://github.com/eclipse/microprofile-metrics/blob/3.0-RC1/spec/src/main/asciidoc/changelog.adoc)

- g. Attach any images to this work item as .png files.

**Comment by jakub-pomykala** [comment]
Closing. This is live [here](https://openliberty.io/blog/2021/03/19/microprofile40-open-liberty-21003.html#metrics)
