### ISSUE TITLE
Enabling Openapi-3.1 and Reactive Messaging 1.0 fails

### ISSUE THREAD

**Issue by Warkdev** [OpenLiberty/open-liberty#15061]
**Describe the bug**
Hello, I'm trying since few days to enable both features mentionned in the title together. However, it keeps failing on a feature conflict.

**Steps to Reproduce**
Enable the following features in a freshly created app server:

```xml
<feature>jpa-2.2</feature>
        <feature>jsonb-1.0</feature>
        <feature>cdi-2.0</feature>
        <feature>jaxrs-2.1</feature>
        <feature>mpconfig-1.3</feature>
        <feature>openapi-3.1</feature>
        <feature>mpReactiveMessaging-1.0</feature>
```

**Expected behavior**
Both features should be loadable at the same time.

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.11
 - Java Version: Java 14
 - server.xml configuration (WITHOUT sensitive information like passwords)
```xml
<server description="ZeroAuthDB">
    <featureManager>
        <feature>jpa-2.2</feature>
        <feature>jsonb-1.0</feature>
        <feature>cdi-2.0</feature>
        <feature>jaxrs-2.1</feature>
        <feature>mpconfig-1.3</feature>
        <feature>openapi-3.1</feature>
        <feature>mpReactiveMessaging-1.0</feature>
    </featureManager>

    <variable name="default.http.port" defaultValue="8080"/>
    <variable name="version.mariadb" defaultValue="2.7.0"/>
    <variable name="mariadb.lib" defaultValue="${shared.resource.dir}/mariadb-java-client-${version.mariadb}.jar"/>

    <httpEndpoint httpPort="${default.http.port}" id="defaultHttpEndpoint" hosts="*" />

    <jpa defaultJtaDataSourceJndiName="jdbc/<sensitive info>" entityManagerPoolCapacity="5"/>
    <library id="MARIADBLIB" name="Library for Maria DB">
        <file name="${mariadb.lib}"/>
    </library>
    <dataSource id="AuthDBDS" jndiName="jdbc/AuthDBDS">
    	<jdbcDriver javax.sql.DataSource="org.mariadb.jdbc.Driver" libraryRef="MARIADBLIB"/>
<!-- sensitive info here -->
    </dataSource>
    <webAppSecurity singleSignonEnabled="false"/>
    <basicRegistry id="basic" realm="dummyRealm">
    </basicRegistry>
</server>
```

**Comment by tjwatson** [comment]
`com.ibm.websphere.appserver.openapi-3.1` does not tolerate different versions of `mpConfig`.  Instead it gets loaded through the dependency on `com.ibm.websphere.appserver.mpOpenAPI-1.0`.  `com.ibm.websphere.appserver.mpOpenAPI-1.0` does tolerate other versions of `mpConfig` but because `openapi-3.1` does not specify that it can tolerate the different versions of `mpConfig` then the preferred version `mpConfig-1.2` from `mpOpenAPI-1.0` must be loaded instead.

If `openapi-3.1` really can tolerate different versions of mpConfig then it is going to have to include mpConfig with the necessary toloerates like this:

`com.ibm.websphere.appserver.mpConfig-1.2; ibm.tolerates:="1.3, 1.4"`

**Comment by Warkdev** [comment]
Hello,

Thank for the answer, that's still not clear for me. I tried almost all combinations of mpConfig-1.x and none of them allowed both features to run together. I even made a very dumb matrix:

```
reactive messaging 
-> cdi-2.0
-> concurrent-1.0
-> mpConfig-1.3
-> mpConfig-1.4
-> mpReactiveStreams-1.0
openapi-3.1
-> distributedMap-1.0
--> jndi-1.0
-> jaxrs-2.0
--> jaxrsClient-2.0
--> json-1.0
--> servlet-3.1
-> jaxrs-2.1
--> jaxRSClient-2.1
--> servlet-4.0
-> mpOpenAPI-1.0
--> jaxrs-2.0
--> jaxrs-2.1
--> mpConfig-1.2
--> mpConfig-1.3
--> mpConfig-1.4
--> servlet-3.1
--> servlet-4.0
-> servlet-3.1
-> servlet-4.0
-> ssl-1.0
```
And couldn't spot the real issue. Is that in the definition of the openapi-3.1 itself ? Where can this be updated/corrected ?

Regards.

**Comment by tjwatson** [comment]
> And couldn't spot the real issue. Is that in the definition of the openapi-3.1 itself ? Where can this be updated/corrected ?

Thanks for being proactive.  My comment was meant for someone familiar with the development of the `com.ibm.websphere.appserver.openapi-3.1` feature so they could look at fixing your issue...

At this point there is no good work around I can see for you short of hacking the `wlp/lib/features/com.ibm.websphere.appserver.openapi-3.1.mf` file and adding the following line:

```
 com.ibm.websphere.appserver.mpConfig-1.2; ibm.tolerates:="1.3, 1.4"; type="osgi.subsystem.feature",
```

After this line:
```
Subsystem-Content: com.ibm.websphere.appserver.mpOpenAPI-1.0; type="osgi.subsystem.feature",
```

But we really need someone familiar with the `openapi-3.1` feature to verify that it can really handle these various versions of `mpConfig`.
