### ISSUE TITLE
MP OpenAPI 2.0 uses the same NLS message range as 1.0 and 1.1

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#15108]
Instead of duplicating messages across multiple bundles, we should create a common bundle containing the NLS messages.

**Comment by Azquelt** [comment]
We need to check whether the the range used for OpenAPI messages actually overlaps with the range used for ORB.

**Comment by tevans78** [comment]
> We need to check whether the the range used for OpenAPI messages actually overlaps with the range used for ORB.

It doesn't clash but it could be documented better
https://github.ibm.com/was-liberty/WS-CD-Open/wiki/NLS-Message-Prefixes
