### ISSUE TITLE
Unable to get a message driven bean to work on Liberty version 20.0.0.7

### ISSUE THREAD

**Issue by viveknvasu** [OpenLiberty/open-liberty#15152]
Hello,

I have been trying to get a Java message driven bean (MDB) to work on Liberty 20.0.0.7, but I think I may be missing something. I have followed all the configs as described in the link below.

https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_dep_msg_mdbwmq.html

I can see that the MDB is being registered by Liberty. When I put a message on the MQ queue, I immediately see log messages in Liberty which means that my listener has been configured to listen to messages on the queue. However, there is an error where Liberty is unable to inject the MDB bean for use.

From the trace logs, I see that the Websphere Liberty Bean deployment archive (BDA) is null. Below is code from getEjbDescriptor() method of the CDIEJBManagedObjectFactoryImpl class where I get a null.

_open-liberty-gm-20.0.0.7\dev\com.ibm.ws.cdi.weld\src\com\ibm\ws\cdi\impl\managedobject\CDIEJBManagedObjectFactoryImpl.java
 WebSphereBeanDeploymentArchive bda = super.getCurrentBeanDeploymentArchive();_

 // above line returns null. **WebSphereBeanDeploymentArchive cannot be obtained for some reason**

 Below is a snippet from the Liberty log:

[ERROR ] CNTR0019E: EJB threw an unexpected (non-declared) exception during invocation of method "onMessage". Exception data: java.lang.NullPointerException

at com.ibm.ws.cdi.impl.managedobject.CDIEJBManagedObjectFactoryImpl.getEjbDescriptor(CDIEJBManagedObjectFactoryImpl.java:147)

Any help would be greatly appreciated. Thanks..

Vivek Vasu
System Analyst
IBM

**Comment by viveknvasu** [comment]
<img width="943" alt="Untitled" src="https://user-images.githubusercontent.com/25295036/100828785-eb6cc180-3485-11eb-80f0-b83ce95fb78c.png">

**Comment by benjamin-confino** [comment]
Hello. 

Please can you post your full logs. And if possible instructions to recreate locally. 

I see in the screenshot that you have a FutureTask on the stack. Does that come from your application code?

**Comment by viveknvasu** [comment]
Hello Benjamin,

I have enabled the trace string as described by you .. Please let me know which portion of the trace log I should paste here. 

Thanks,
Vivek

**Comment by tkburroughs** [comment]
@benjamin-confino 

From the logs, it appears the EJB Container is setting the ComponentMetaData for the EJB on the current thread, and CDI finds that, but doesn't find a BeanDeploymentArchive:

```
[12/3/20 11:42:24:927 IST] 00000125 UncachedActiv >  atActivate (BeanId(OMEntAppProjWeb#OMEntAppProjWeb-20.8.0-SNAPSHOT.war#OrdMgtMDB, null)) Entry  
                                 ContainerTx@97f02d8d#tid=9f16ce4d(LTC)
[12/3/20 11:42:24:927 IST] 00000125 EJSHome       >  createBeanO(ContainerTx, activate) activate = true Entry 
[12/3/20 11:42:24:928 IST] 00000125 BeanOFactory  >  create: com.ibm.ws.ejbcontainer.mdb.internal.MessageEndpointFactoryImpl@87f2f3a6 Entry 
[12/3/20 11:42:25:910 IST] 00000125 BeanO         >  BeanO Entry 
[12/3/20 11:42:25:912 IST] 00000125 BeanO         <  BeanO Exit 
[12/3/20 11:42:25:912 IST] 00000125 MessageDriven >  initialize Entry 
[12/3/20 11:42:26:419 IST] 00000125 CallbackConte >  begin: tx=CompatLTC, contexts=CallbackBean Entry 
[12/3/20 11:42:26:419 IST] 00000125 EJBThreadData 3   pushCallbackBeanO: BMMessageDrivenBeanO(BeanId(OMEntAppProjWeb#OMEntAppProjWeb-20.8.0-SNAPSHOT.war#OrdMgtMDB, null), PRE_CREATE)
.
.
.
[12/3/20 11:42:26:427 IST] 00000125 CDIContainerI >  getClassBeanDeploymentArchive Entry  
                                 class oem.edge.ordmgt.shipments.OrdMgtMDBBean
[12/3/20 11:42:26:428 IST] 00000125 CDIContainerI >  getCurrentDeployment Entry 
[12/3/20 11:42:26:428 IST] 00000125 CDIContainerI >  getCurrentModuleMetaData Entry 
[12/3/20 11:42:26:428 IST] 00000125 CDIContainerI <  getCurrentModuleMetaData Exit  
                                 com.ibm.ws.ejbcontainer.osgi.internal.metadata.OSGiEJBModuleMetaDataImpl@48030e1a[OMEntAppProjWeb#OMEntAppProjWeb-20.8.0-SNAPSHOT.war]
[12/3/20 11:42:26:428 IST] 00000125 CDIContainerI >  getDeployment Entry  
                                 com.ibm.ws.container.service.app.deploy.internal.ApplicationMetaDataImpl@1be547d8[OMEntAppProjWeb]
[12/3/20 11:42:26:429 IST] 00000125 CDIRuntimeImp >  getApplicationSlot Entry 
[12/3/20 11:42:26:429 IST] 00000125 CDIRuntimeImp <  getApplicationSlot Exit  
                                 com.ibm.ws.runtime.metadata.MetaDataSlotImpl@bd5b0b42[ApplicationMetaData:3:com.ibm.ws.cdi.weld_1.0.42.cl200720200625-0300 [106]]
[12/3/20 11:42:26:429 IST] 00000125 CDIContainerI <  getDeployment Exit  
                                 WebSphere CDI Deployment for OMEntAppProjWeb
[12/3/20 11:42:26:430 IST] 00000125 CDIContainerI <  getCurrentDeployment Exit  
                                 WebSphere CDI Deployment for OMEntAppProjWeb
[12/3/20 11:42:26:430 IST] 00000125 CDIContainerI <  getClassBeanDeploymentArchive Exit  
                                 null
```
Wondering if CDI should have created then when the application started; but didn't for some reason?  I don't see calls to create it, but I may not be looking for it properly... or the trace may have wrapped. I was expecting to see a call to get the EJBEndpoints for the module.  BTW, there is only one EJB in the module, this MDB.

@viveknvasu 

Can you describe how the MDB is packaged and configured.  For example, is the MDB class in the WAR classes directory, or is it packed in a JAR in the WAR lib directory?  Are you using the `@MessageDriven` annotation, or do you have an `ejb-jar.xml` that defines the MDB there?  (or both)?

**Comment by viveknvasu** [comment]
Hi Tracy,

The MDB is part of a WAR file. 

Inside the WAR, in the WEB-INF\**lib** directory is the OMBEEntAppProjEJB-20.8.0-SNAPSHOT.jar.
Inside the above JAR is my MDB class (OrdMgtMDBBean.class)

In WEB-INF dir is the **ejb-jar.xml** and **ibm-ejb-jar-bnd.xml**

I do not see usage of @MessageDriven .. so it is just the ejb-jar.xml

Thanks,
Vivek

**Comment by benjamin-confino** [comment]
@tkburroughs 

> From the logs, it appears the EJB Container is setting the ComponentMetaData for the EJB on the current thread, and CDI finds that, but doesn't find a BeanDeploymentArchive:

To expand on this. If `getCurrentBeanDeploymentArchive` fails then CDI falls back to `getCDIRuntime().getCurrentBeanManager()`. The key difference is that when it finds a bda through  `getCurrentBeanDeploymentArchive` CDI will look for the EJB in all descendent BDAs. If it can't it will just search the current BeanManager alone. 

This could be key if the beanmanager we need is a jar's bean manager. The actual bean manager we find is

`getCurrentBeanManager Exit`
`                                 Weld BeanManager for OMEntAppProjWeb#OMEntAppProjWeb-20.8.0-SNAPSHOT.war [bean count=31]`

Unfortunately I cannot say which bean manager holds the EjbDescrpitor as the logs end after it is started. @viveknvasu could you get expanded logs that catch everything from application startup. Maybe by adding maxFileSize="20" maxFiles="10"  to your logging statement

The string to look for in the logs is `addEjbDescriptor` that's the method that registers an EJB to a bda.

**Comment by benjamin-confino** [comment]
As a followup. 

The fact CDI doesn't find the bda is still very weird, and likely to be the ultimate cause of the problem. You can see that it's found a deployment `WebSphere CDI Deployment for OMEntAppProjWeb` and the fact it can't find the bda means that CDI cannot find the class `oem.edge.ordmgt.shipments.OrdMgtMDBBean` in either the BDA's metadata, or by attempting to load the class with a classloader. 

I couldn't find any mention of OMBEEntAppProjEJB-20.8.0-SNAPSHOT.jar in the logs. But hopefully the full logs will include it. Otherwise the question is, why is that jar missing.

**Comment by tkburroughs** [comment]
@benjamin-confino OMBEEntAppProjEJB-20.8.0-SNAPSHOT.jar  likely won't show up in the trace unless ClassLoader trace is enabled.  OMBEEntAppProjEJB-20.8.0-SNAPSHOT.jar  is NOT an EJB Module in this scenarios... it is just a library JAR in the WAR.  The application classloader should include it on the classpath, but there won't be a separate "ModuleMetadata" for it; as it is considered part of the WAR module.

**Comment by benjamin-confino** [comment]
@tkburroughs 

It should show up in the CDI trace. For example here's a line of trace from our fat tests creating a BDA for a WEB-INF/lib

```
[03/12/2020, 11:31:09:660 GMT] 0000003f id=00000000 com.ibm.ws.cdi.impl.weld.BeanDeploymentArchiveImpl           > <init> Entry  
                                                                                                               WebSphere CDI Deployment for aroundConstructApp
                                                                                                               aroundConstructApp#aroundConstructApp.war#WEB_INF_LIB#WEB-INF/lib/utilLib.jar
                                                                                                               CDIArchive: WEB-INF/lib/utilLib.jar
                                                                                                               com.ibm.ws.cdi.liberty.CDIRuntimeImpl@2626e73e
```

**Comment by viveknvasu** [comment]
Please find attached the complete trace.log 
[dec04_trace.zip](https://github.com/OpenLiberty/open-liberty/files/5641712/dec04_trace.zip)

Thanks
Vivek

**Comment by benjamin-confino** [comment]
I'm looking at the new logs. Something that immediately jumps out. 

When I search for the string `BeanDeploymen >  <init> Entry` I only find two occurrences 

```
[12/4/20 14:33:24:445 IST] 00000039 BeanDeploymen >  <init> Entry  
                                 WebSphere CDI Deployment for OMEntAppProjWeb
                                 OMEntAppProjWeb#com.ibm.ws.org.jboss.weld3_1.additionalClasses
                                 CDIArchive: com.ibm.ws.org.jboss.weld3_1
--
[12/4/20 14:33:25:309 IST] 00000039 BeanDeploymen >  <init> Entry  
                                 WebSphere CDI Deployment for OMEntAppProjWeb
                                 OMEntAppProjWeb#com.ibm.ws.org.hibernate.validator.cdi_1.additionalClasses
                                 CDIArchive: com.ibm.ws.org.hibernate.validator.cdi_1
```

However there's clearly more than two BDAs in the app since I can see others. For example: `BDA for OMEntAppProjWeb#OMEntAppProjWeb-20.8.0-SNAPSHOT.war#WEB_INF_LIB#WEB-INF/lib/DepProject-20.8.0-SNAPSHOT.jar(WEB_INF_LIB)`

Given how early the first appearance of this BDA is in the logs, I think we're missing a first part of the log. Did your server create multiple trace.log files? Liberty moves onto extra files when it hits its file size limit (though 35 MB is not a default limit.). Or can you think of some other way we might be missing logs? 

------------------------

But more importantly I think I've found something. (Sorry, I should have spotted this one yesterday)

```
[12/3/20 8:53:36:146 IST] 00000037 WebSphereCDID <  getBeanDeploymentArchives Exit  
                                 [BDA for OMEntAppProjWeb#com.ibm.ws.messaging.jms.2.0.cdi_1.additionalClasses(RUNTIME_EXTENSION), BDA for OMEntAppProjWeb#com.ibm.ws.org.hibernate.validator.cdi_1.additionalClasses(ON_DEMAND_LIB), BDA for OMEntAppProjWeb#OMEntAppProjWeb-20.8.0-SNAPSHOT.war#WEB_INF_LIB#WEB-INF/lib/omnifaces-3.6.jar(WEB_INF_LIB), BDA for OMEntAppProjWeb#com.ibm.ws.beanvalidation.v20.cdi_1.additionalClasses(RUNTIME_EXTENSION), BDA for OMEntAppProjWeb#OMEntAppProjWeb-20.8.0-SNAPSHOT.war(WEB_MODULE), BDA for OMEntAppProjWeb#com.ibm.ws.security.javaeesec.cdi_1.additionalClasses(RUNTIME_EXTENSION), BDA for OMEntAppProjWeb#OMEntAppProjWeb-20.8.0-SNAPSHOT.war#WEB_INF_LIB#WEB-INF/lib/DepProject-20.8.0-SNAPSHOT.jar(WEB_INF_LIB), BDA for OMEntAppProjWeb#com.ibm.ws.transaction.cdi_1.additionalClasses(RUNTIME_EXTENSION), BDA for OMEntAppProjWeb#com.ibm.ws.org.apache.myfaces.2.3_1.additionalClasses(RUNTIME_EXTENSION), BDA for OMEntAppProjWeb#com.ibm.ws.org.jboss.weld3_1.additionalClasses(ON_DEMAND_LIB)]
```

The lack of a BDA here is likely the problem. There's two ways CDI might not recognise the BDA. The first is that CDI never saw the archive, the second is that this method returned true

```
    public final boolean skipCreatingBda(CDIArchive archive) {
        //only skip this if it is a leaf archive
        boolean skip = isImplicitBeanArchivesScanningDisabled(archive);
        skip = skip && (archive.getBeansXml() == null);
        skip = skip && (!(archive.getType() == ArchiveType.WEB_MODULE));
        return skip;
    }
```

That method should be traced, but I can't find `skipCreatingBda` in any of your three trace files. But before we create a new file to try and catch that, we can check the above cases. @viveknvasu do you have implicit bean archive scanning disabled? And either way, as an experiment what happens if you stick a beans.xml file into OMBEEntAppProjEJB-20.8.0-SNAPSHOT.jar? (See: https://stackoverflow.com/questions/13056336/cdi-beans-xml-where-do-i-put-you)

**Comment by viveknvasu** [comment]
Hello Benjamin,

Yes we did have _bean archive scanning_ disabled in server.xml.

<cdi12 enableImplicitBeanArchives="false"/>

So, I put a beans.xml into OMBEEntAppProjEJB\ejbModule\META-INF\ and the original error is now gone 👍 

Thanks a lot to Benjamin & Tracy for your help and time ..

Regards,
Vivek

**Comment by benjamin-confino** [comment]
Glad to hear it's all sorted
