### ISSUE TITLE
MP Config 2.0 Feature Test Summary

### ISSUE THREAD

**Issue by Joseph-Cass** [OpenLiberty/open-liberty#15179]
**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

The test strategy for this feature is a little complex. Since a large part of delivering the feature was consuming [SmallRye's implementation](https://github.com/smallrye/smallrye-config) of [MicroProfile Config](https://github.com/eclipse/microprofile-config), a lot of the work involved adapting our old FAT tests (from mpConfig-1.x) to be compatible with mpConfig-2.0.

This was achieved by:
* Repeating appropriate mpConfig-1.x FAT tests against the mpConfig-2.0 implementation:
  * [BasicConfigTests](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/BasicConfigTests.java)
  * [ClassLoadersTest](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/ClassLoadersTest.java)
  * [DefaultSourcesTest](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/DefaultSourcesTest.java)
  * [OrdinalsForDefaultsTest](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/OrdinalsForDefaultsTest.java)
  * [SimultaneousRequestsTest](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/SimultaneousRequestsTest.java)
  * [SharedLibTest](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/SharedLibTest.java)
  * [StressTest](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.config.1.1_fat/fat/src/com/ibm/ws/microprofile/config/fat/tests/StressTest.java)
* Creating mpConfig-2.0 specific tests within the 2.0 FAT bucket for existing functionality which changed from 1.X-> 2.0
  * [DefaultSourcesTestServlet](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/defaultSources/DefaultSourcesTestServlet.java)
  * [ClassLoadersTestServlet](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/classLoader/ClassLoadersTestServlet.java)
  * [ConvertersTestServlet](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/converter/ConvertersTestServlet.java)
* Creating mpConfig-2.0 specific tests within the 2.0 FAT bucket for new functionality which needs testing against Liberty specific components
  * [PropertyExpressionTestServlet](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/propertyExpression/PropertyExpressionTestServlet.java) tests that the new `PropertyExpression` functionality works in a `variable` and an `appProperty` set in a `server.xml` file in a Liberty application.
  * [UnwrapServlet](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/unwrap/UnwrapServlet.java) tests that the new `Config.unwrap()` method returns the expected values in a Liberty application.

The functionalities of the [new features in mpConfig-2.0](https://download.eclipse.org/microprofile/staging/microprofile-config-2.0/microprofile-config-spec-2.0.html#release_notes_20) are covered by an extensive set of [TCKs](https://github.com/eclipse/microprofile-config/tree/master/tck) from MicroProfile Config. We run it from [io.openliberty.microprofile.config.2.0.internal_fat_tck](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.microprofile.config.2.0.internal_fat_tck) against Java EE 8:
* `Config.getValues()` and `Config. getOptionalValue()` are new methods for the Config class which each return a `List` of a specified Config Property: 
  * A plethora of tests were added to [ArrayConverterBean](https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/ArrayConverterBean.java) and [ArrayConverterTest](https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/ArrayConverterTest.java) in [this PR](https://github.com/eclipse/microprofile-config/pull/501/files).
* `@ConfigProperties` is a new annotation which provides a way to retrieve a number of related configuration properties with a specified prefix into a CDI bean: 
  * [ConfigPropertiesTest](https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigPropertiesTest.java) and [ConfigPropertiesMissingPropertyInjectionTest](https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/broken/ConfigPropertiesMissingPropertyInjectionTest.java) were added in [this PR](https://github.com/eclipse/microprofile-config/pull/565/files).
* `ConfigValue.java` is a new class which holds extra information about a Config Property:
  * [ConfigValueTest](https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigValueTest.java) was added in [this PR](https://github.com/eclipse/microprofile-config/pull/551/files).
* `Config.getConverter()` is a new method added to the Config class to expose the conversion mechanism in the Config API:
  * Tests using `getConverter()` were added to [ArrayConverterTest](https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/ArrayConverterTest.java), [ClassConverterTest](https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/ClassConverterTest.java), [ConverterTest](https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/ConverterTest.java), [CustomConverterTest](https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/CustomConverterTest.java), and [ImplicitConverterTest](https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/ImplicitConverterTest.java) in [this PR](https://github.com/eclipse/microprofile-config/pull/495).
* `Config.unwrap()`  is a new method to provide a way to access the underlying implementation and use implementation specific API's:
  * [Config.unwrap()](https://github.com/eclipse/microprofile-config/blob/795080d31fc57ba17dc2506425acfee3b4566b72/api/src/main/java/org/eclipse/microprofile/config/Config.java#L293) was added in [this PR](https://github.com/eclipse/microprofile-config/pull/576). No TCKs were added for this method since there's no requirement for vendors to implement it. We don't expose the SmallRye API, so we didn't need any extra tests beyond what's in [UnwrapServlet](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.microprofile.config.2.0.internal_fat/fat/src/io/openliberty/microprofile/config/internal_fat/apps/unwrap/UnwrapServlet.java).
* `Configuration Profiles` is a new feature which allows for an "active profile" to be set as a Config Property which defines which set (profile) of Config Properties should be used:
  * 6 test files were added to a new [tck/profile](https://github.com/eclipse/microprofile-config/tree/master/tck/src/main/java/org/eclipse/microprofile/config/tck/profile) folder in [this PR](https://github.com/eclipse/microprofile-config/pull/554/files): ConfigPropertyFileProfileTest, DevConfigProfileTest, InvalidConfigProfileTest, ProdProfileTest, TestConfigProfileTest, and TestCustomConfigProfile.
* `OptinalInt`, `OptionalLong` and `OptionalDouble` are new built-in converters: 
  * Tests for each were added to [CdiOptionalInjectionTest](https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/CdiOptionalInjectionTest.java) in [this PR](https://github.com/eclipse/microprofile-config/pull/530).
* `Property Expression` is a new feature which allows for variables between Config Properties:
  * [CDIPropertyExpressionsTest](https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPropertyExpressionsTest.java) and [PropertyExpressionsTest](https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/PropertyExpressionsTest.java) were added in [this PR](https://github.com/eclipse/microprofile-config/pull/577/files).

TCKs were also added for the following behaviour updates/clarifications:
* Empty Value and special character behaviour updates:
  * Many tests were added to a new [tck/emptyvalue](https://github.com/eclipse/microprofile-config/tree/master/tck/src/main/java/org/eclipse/microprofile/config/tck/emptyvalue) folder in [this PR](https://github.com/eclipse/microprofile-config/pull/598/files).
* Converters for primitive wrappers behaviour update: 
  * [CustomConverterTest](https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/CustomConverterTest.java) was created and 5 files were added to a new [tck/converters/custom](https://github.com/eclipse/microprofile-config/tree/master/tck/src/main/java/org/eclipse/microprofile/config/tck/converters/custom) folder in [this PR](https://github.com/eclipse/microprofile-config/pull/519/files): BooleanConverter, CharacterConverter, DoubleConverter, IntegerConverter, and LongConverter.
* Converters being passed `null` behaviour update:
  * [NullConvertersTest](https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/converters/NullConvertersTest.java) added in [this PR](https://github.com/eclipse/microprofile-config/pull/542/files).
* Converting to `null` behaviour update:
  * 2 test files were added to [tck/converters/convertToNull](https://github.com/eclipse/microprofile-config/tree/master/tck/src/main/java/org/eclipse/microprofile/config/tck/converters/convertToNull) in [this PR](https://github.com/eclipse/microprofile-config/pull/618/files).

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

_Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:_

_0 - No automated testing delivered_

_1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature._

_2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths_

_3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level._

_4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide._

_5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature._

_Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)_

We have reviewed this as a team and gave a score of 4.

**Comment by ayoho** [comment]
Coverage looks good to me, particularly with the delivery of https://github.com/OpenLiberty/open-liberty/pull/15567 👍
