### ISSUE TITLE
Design Issue: Should the JAX-RS 2.1 feature expose the JSONB API packages?

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#152]
To expose or not to expose... JSONB from JAX-RS 2.1

During our design issue conversation centered around which JSON provider to use
for JAX-RS 2.1 (Issue #125), a controversial topic arose around the idea of whether or not to
expose the JSONB APIs when a user only configures the JAX-RS 2.1 feature.  This
text intends to document the pros and cons of such an approach.

Background:

In JAX-RS 2.0, we chose to use Jackson to implement the JSON provider mechanism.
Unlike our JAX-RS 1.1 approach, we chose _not_ to expose the Jackson APIs.  This
meant that users could convert JSON to objects and vice versa without a custom
MessageBodyReader/MessageBodyWriter, but only if their objects strictly
conformed to the JSON without needing custom annotations, etc. This approach is
a somewhat limiting out-of-the-box experience but allows for much greater
flexibility to the user.  For example, if they want to use a newer version of 
Jackson, they can simply provide whatever version of Jackson they want in their
application, and the Liberty runtime will select it - no need for parentLast
classloading, common shared libraries, or other tricks.

Aside from the Jackson decision in JAX-RS 2.0, there is other precedent for not 
exposing APIs.  The Persistence Service used by various components in Liberty 
depends on JPA, but does not expose the JPA APIs.  These components depend on an
internal JPA feature allowing them full access to the JPA programming model, but 
not forcing user applications into using Liberty's JPA APIs/implementation.

Benefits of exposing JSONB:

* Users can take full advantage of the JSONB programming model without needing
to explicitly add the `jsonb-1.0` feature.

Drawbacks of exposing JSONB:

* Users wanting to package their own version of JSONB must resort to classloader 
tricks to use their implementation. 

* We are stuck with providing these APIs - the spec gives us some wiggle room 
with regard to "products that do not package JSONB" - and so a Liberty server 
that specifies the `jaxrs-2.1` feature without the `jsonb-1.0` feature could 
in theory use Jackson or some other JSON conversion tool that might provide
better performance, more options, etc. 

Benefits of not exposing JSONB:

* Users have much easier time bringing their own implementation with their app. 
No classloading tricks!

* Better isolation - users don't get APIs that they didn't ask for in the
feature manager.

* More flexibility for providing different out-of-the-box JSON providers.

Drawbacks of not exposing JSONB:

* Potential user confusion - they must enable the `jsonb-1.0` feature in order
to explicitly use the JSONB functionality.

Ultimately, I heavily favor **not** exposing the JSONB APIs in the JAX-RS 2.1 
feature.  We've been burned far too many times for exposing things to users that
they would rather package themselves (Commons Logging, SLF4J, JPA providers,
bean validation frameworks, etc.).  We've used this model several times in
Liberty development - persistence service, removing JAX-RS APIs from the 
`restConnector-2.0` feature.

**Comment by NottyCode** [comment]
+1 to go with @andymc12's proposal

**Comment by andymc12** [comment]
Also, per discussion on the 2017-09-26 design issues call, we determined that if we do not expose the JSON-B APIs with only `jaxrs-2.1` feature configured, then we need to make sure we have a test case for the scenario where a user packages their own JSON-B API/Impl with their app.  I've opened issue #264 to build this test case.

**Comment by andymc12** [comment]
Hearing no no-votes, I think we have consensus.  Closing this issue.
