### ISSUE TITLE
WIP GA BLOG - MicroProfile Fault Tolerance 3.0

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#15255]
The information you provide here will be included in the Open Liberty GA release blog post ([example](https://openliberty.io/blog/2020/07/30/json-logging-open-liberty-20008.html)), which will be published on the OpenLiberty.io blog, and potentially elsewhere, to promote this release of Open Liberty.

Please provide the following information the week before the GA date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name (eg WebSockets feature): MicroProfile Fault Tolerance 3.0
   
   Short feature name (eg websockets-1.0): mpFaultTolerance-3.0

2. Who is the target persona? Who do you expect to use the update? Application developer, Operations

3. Write a paragraph to summarises the update, including the following points:

MicroProfile Fault Tolerance allows developers to easily apply strategies for mitigating failure to their code. It provides annotations which developers can add to methods to use bulkhead, circuit breaker, retry, timeout and fallback strategies.

Fault Tolerance 3.0 overhauls the metrics automatically exported by Fault Tolerance to take advantage of metric tags to make it easier to use those metrics to understand when and where your application is failing.

Information which was previously included in the metric name is now included as metric tags, making it much easier to query for data from multiple methods and pick out which, if any, is causing issues.

.Example
Old metric:: `application:ft.<name>.timeout.callsTimedOut.total`
New metric:: `base:ft.timeout.calls.total{method="<name>", timedOut="true"}`

This change is **not backwards compatible**, so if you have dashboards which reference the old metrics, you'll need to update them to use the new metrics. Hopefully though, you'll find the new format much more useful as the tags make it possible to aggregate related metrics, to display metrics from multiple methods on one graph or to list your methods sorted by a metric so you can quickly see which methods are timing out or using their fallback.

**[IF DONE]**: We've updated the [Open Liberty mpMetrics dashboard][metrics-dashboard] to include some of these new metrics, so you can take advantage of some of these metrics without having to write your own queries.

For further information:
* Get an introduction to MicroProfile Fault Tolerance with the Open Liberty guides
  * [Failing fast and recovering from errors][guide-retry-timeout]
  * [Preventing repeated failed calls to microservices][guide-cb-fallback]
* Reference the [Javadoc][javadoc]
* Reference the full [specification][spec]
  * New format for metrics is detailed in [chapter 11][spec-metrics]
* Report any issues [on Github][ol-repo]

[javadoc]: https://download.eclipse.org/microprofile/microprofile-fault-tolerance-3.0-RC2/apidocs/
[spec]: https://download.eclipse.org/microprofile/microprofile-fault-tolerance-3.0-RC2/microprofile-fault-tolerance-spec.html
[spec-metrics]: https://download.eclipse.org/microprofile/microprofile-fault-tolerance-3.0-RC2/microprofile-fault-tolerance-spec.html#_integration_with_microprofile_metrics
[guide-retry-timeout]: https://openliberty.io/guides/retry-timeout.html
[guide-cb-fallback]: https://openliberty.io/guides/circuit-breaker.html
[ol-repo]: https://github.com/OpenLiberty/open-liberty/
[metrics-dashboard]: https://grafana.com/grafana/dashboards/11706

## What happens next?

- Your paragraph will be included in the GA release blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the GA blog post).

**Comment by jakub-pomykala** [comment]
Closing. Issue was used in [A Deep Dive into MicroProfile 4.0 with Open Liberty](https://openliberty.io/blog/2021/03/19/microprofile40-open-liberty-21003.html#fault-tolerance) and mentioned in blog post 
 for GA 21.0.0.3
