### ISSUE TITLE
Feature Test Summary for MicroProfile 4.0

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#15253]
This is the FTS for https://github.com/OpenLiberty/open-liberty/issues/11014
This only covers testing for the `microProfile-4.0` convenience feature. The "child" features should each have their own FTS.

**1) 
The existing "hello world" tests for the MicroProfile convenience features have been modified to also repeat against MP 4.0.
These simply test that the features will start and that a simple app can be run. They are not in-depth functional tests as that would be done by the FAT buckets for the individual features. Most interractions between the features are tested by SVT.

Internally, we have added some private `mpCompatible-x.x` features which restrict which feature combinations may work together. These are similar to the `eeCompatible-x.x` features. We have added some extra tests to check some of these compatibility combinations. They cover positive and negative tests with both MicroProfile and Jakarta EE, along with some of the standalone MicroProfile features, such as mpGraphQL-1.0 and mpReactiveMessaging-1.0.
https://github.com/OpenLiberty/open-liberty/pull/15301
- testMicroProfile40 - simple sniff test, should always pass
- testMP40andConcurrent10 - This should pass despite the fact that concurrent-1.0 pulls in the MP Context Propagation 1.0 API, the implementation for which is NOT MP 4.0 compatible
- testMP40andConcurrent20 - Should fail because concurrent-2.0 depends on eeCompatible-9.0 and MP 4.0 is only compatible with EE 8
- testMP40andEE8 - should always pass
- testMP40andEE9 - should always fail as MP 4.0 is only compatible with EE 8
- testMP40andMP33 - should fail because the two microProfile features are singletons
- testMP40andMPConfig14 - should fail because MP 4.0 contains MP Config 2.0 which can not be started at the same time as 1.4
- testMP40andCtxPropagtion10 - should fail because mpContextPropagation-1.0 is not compatible with MP 4.0
- testMP40andCtxPropagtion11 - should always pass
- testMP33plusStandalone - (microProfile-3.3 plus mpGraphQL-1.0 and mpReactiveMessaging-1.0) should always pass
- testMP40plusStandalone - (microProfile-4.0 plus mpGraphQL-1.0) should always pass
-- We have some plans to let mpReactiveMessaging-1.0 support MP 4.0, but it doesn't at the moment https://github.com/OpenLiberty/open-liberty/issues/15440

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

**4** - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

**Comment by ayoho** [comment]
LGTM 👍
