### ISSUE TITLE
[Question]How to hot delpoy a multiple maven modules project or enable hot code replacement

### ISSUE THREAD

**Issue by unidevel** [OpenLiberty/open-liberty#1527]
Hi, guys:
     I have a maven project which contains multiple java modules which will build to jar file then put to WEB-INF/lib directory. I need restart liberty each time I make some change and run mvn to build.

The dir structure is something like

```shell
project
   |- pom.xml
   |- target/
   |     |- project.war
   |     |- project/
   |     |      |- WEB-INF/web.xml
   |     |      |- ...
   |- moduleA
   |     |- pom.xml
   |     |- target/classes
   |     |     |- META-INF/web-fragment.xml
   |     |     |- com
   |     |- ...
   |- moduleB
   |     |- pom.xml
   |     |- target/classes
   |     |     |- META-INF/web-fragment.xml
   |     |     |- com
   |     |- ...
```

What I want to do is to do an exploded deployment which use the target/classes directories and the main war dir - target/project, so that I can use hot code replacement.

Is there any guide or suggestion to setup such an env?

**Comment by ewhoch** [comment]
@andymc12 could you take a look to see if this would work for hot code replace? I'm not sure it would, since even if the app was exploded and we recognized it, there is a limited set of changes we'd recognize without an application restart.

**Comment by aguibert** [comment]
@unidevel I recommend going through the maven guide if you haven't already:
https://openliberty.io/guides/maven-intro.html
(or if you prefer Gradle, there is a gradle guide too)

The maven and gradle plugins for Liberty use "loose applications" by default, which means in `${server.config.dir}/apps/YOUR_APP_NAME.war.xml`

The loose app config will look something like this:
```xml
<archive>
    <dir sourceOnDisk="/path/to/your/project/src/main/webapp" targetInArchive="/"/>
    <dir sourceOnDisk="/path/to/your/project/build/classes/java/main" targetInArchive="/WEB-INF/classes/"/>
</archive>
```

If you run `mvn package`, or if you use an IDE such as Eclipse, it will output .class files from your application into `/path/to/your/project/build/classes/java/main`.  Liberty will see the .class file updates and depending on the nature of the change your app will either be hot-updated or restarted, but Liberty should not need to restart.

Using the Maven example, if you go through the whole thing you'll end up with a working Liberty HelloServlet project that uses Maven.  From there, you can run `mvn liberty:start-server` to start the Liberty server and go to localhost:9080/ServletSample/servlet to view the servlet output.  Then, if you make a code change such as changing the servlet output slightly and run `mvn package` and then refresh your web browser, you'll see the new message.  Or if you use an IDE with auto-build enabled, you just have to save the HelloServlet.java file and refresh your web browser.

**Comment by unidevel** [comment]
@ewhoch @aguibert Thanks, I also found https://www.ibm.com/support/knowledgecenter/en/SS7K4U_liberty/com.ibm.websphere.wlp.zseries.doc/ae/rwlp_loose_applications.html, using the same way you provide. 

I also found an example when I created a liberty app, there is the file `WEB-INF/ibm-web-ext.xml`, seems can perform scan and auto-restart
```xml
<?xml version="1.0" encoding="UTF-8"?>
<web-ext
	xmlns="http://websphere.ibm.com/xml/ns/javaee"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://websphere.ibm.com/xml/ns/javaee http://websphere.ibm.com/xml/ns/javaee/ibm-web-ext_1_0.xsd"
	version="1.0">

	<reload-interval value="3"/>
	<enable-directory-browsing value="false"/>
	<enable-file-serving value="true"/>
	<enable-reloading value="true"/>
	<enable-serving-servlets-by-class-name value="false" />

</web-ext>

```

**Comment by aguibert** [comment]
@unidevel in addition to the `ibm-web-ext.xml` file, you can configure application polling rate in the server.xml:

```xml
<!-- out of the box this is enabled and set to 500ms -->
<applicationMonitor pollingRate="5s"/>
```

For full doc, see: [applicationMonitor configuration element](https://www.ibm.com/support/knowledgecenter/en/SSD28V_8.5.5/com.ibm.websphere.wlp.core.doc/autodita/rwlp_metatype_core.html#mtFile5)
