### ISSUE TITLE
Create WebSocket private API features for older WebSocket features

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#15325]
https://github.com/OpenLiberty/open-liberty/issues/15323 addressed Jakarta EE9 features.

This issue should be used to address the websocket-1.0 and websocket-1.1 API bundles and the features that pull in the API bundles to now leverage the private API features.

**Comment by isaacrivriv** [comment]
Making the changes saw that there were inconsistencies loading features when changing the order of the feature list which gave way to this [issue](https://github.com/OpenLiberty/open-liberty/issues/15734). Some changes have been made to fix the issue but still require the fixes in this [PR](https://github.com/OpenLiberty/open-liberty/pull/15729) before trying the changes again
