### ISSUE TITLE
update jwtBuilder metatype description to clearly describe the claim

### ISSUE THREAD

**Issue by chunlongliang-ibm** [OpenLiberty/open-liberty#15431]
in the metatype jwtBuilder, the attribute "claims"  is defined as "Specify a comma separated list of claims to include in the token.", see https://www.ibm.com/support/knowledgecenter/SS7K4U_liberty/com.ibm.websphere.liberty.autogen.zos.doc/ae/rwlp_config_jwtBuilder.html. This might give customer false impression that they can list any private claims in this attribute. The fact is that this claims only limit attributes exist in user registry.

Here is suggested change:

Change from
“Specify a comma separated list of claims to include in the token." to something like: 
“Specify a comma separated list of claims to include in the token. These claims must be existing user attributes that are defined for the subject of this JWT in the user registry.”

**Comment by ayoho** [comment]
We can also use this issue to enhance the description of the `trustStoreRef` attribute since it is now being used to look up information relevant to JWEs.
