### ISSUE TITLE
API document is not produced for ear apps

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty#1545]
Document served at /openapi is not showing the document for any of the APIs from the WeatherMPOpenAPI.war (contained within SVT app SocialSphereMPOpenAPI.ear)

Extracting and putting the WeatherMPOpenAPI.war within the 'dropins' directory produces document for endpoints.

Instructions:
(1) extract whole usr directory under your Open Liberty wlp dir: http://ausgsa.ibm.com/projects/w/was_defects/ss_mpopenapi/usr.zip  
(2) Extract http://ausgsa.ibm.com/projects/w/was_defects/ss_mpopenapi/db2jars.zip to a location on your machine and within the server.xml replace 'C:/db2jars' with your location.

**Comment by leochr** [comment]
@arturdzm please add a description for the webmodule (OSGi) handling work here.

**Comment by tam512** [comment]
#link 250839
