### ISSUE TITLE
Control SelfExtract for *nix based containers

### ISSUE THREAD

**Issue by lborupj** [OpenLiberty/open-liberty#15471]
When packaging OpenLiberty into a self-extracting archive (JAR) and adding that to an image based upon the distroless ( https://github.com/GoogleContainerTools/distroless ) Java 11 image, you get an error saying that chmod is not available (as expected) BUT it would be really nice if I could set ENV vars to control whether chmod'ing to executable and other native tools should/can be used.

I have a work around (not pretty) to set "-Dos.name=windows" even though it is running on linux but atleast OL extracts archive and does start.

**Comment by cbridgha** [comment]
Thanks - we'll take a look
