### ISSUE TITLE
JPA trying to create whats already there

### ISSUE THREAD

**Issue by bwa** [OpenLiberty/open-liberty#15476]
Using OpenLiberty 20.0.0.12 with JPA-2.2 and Postgres, the Eclipselink is trying to create structures which is already in the database and failing the current transaction.

PostgreSQL 9.6.18
PostgreSQL JDBC Driver 42.2.9

persistence.xml is set to 

`<property name="eclipselink.ddl-generation" value="create-or-extend-tables"/>`

the message is :

```

[INFO] [WARNING ] CWWJP9991W: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.7.v20200504-69f2c2b80d): org.eclipse.persistence.exceptions.DatabaseException
[INFO] Internal Exception: org.postgresql.util.PSQLException: ERROR: constraint "fk_historikk_device_id" for relation "historikk" already exists
[INFO] Error Code: 0
[INFO] Call: ALTER TABLE Historikk ADD CONSTRAINT FK_Historikk_DEVICE_id FOREIGN KEY (DEVICE_id) REFERENCES Device (id)
[INFO] Query: DataModifyQuery(sql="ALTER TABLE Historikk ADD CONSTRAINT FK_Historikk_DEVICE_id FOREIGN KEY (DEVICE_id) REFERENCES Device (id)")
[INFO] [WARNING ] CWWJP9991W: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.7.v20200504-69f2c2b80d): org.eclipse.persistence.exceptions.DatabaseException
[INFO] Internal Exception: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
[INFO] Error Code: 0
[INFO] Call: ALTER TABLE Device_Historikk ADD CONSTRAINT FK_Device_Historikk_Device_id FOREIGN KEY (Device_id) REFERENCES Device (id)

```

If it's already there, then the JPA should not try to create it, I guess. Could it be a case issue ?

**Comment by bwa** [comment]
Thanks @steven1046 
Found that is was using the wrong repo, but today could not fint it, to moveit myself, until I saw that you have done what I should have done at the beginning. Sorry for the mistake, the repo name is easy to misspell.

**Comment by jgrassel** [comment]
Probably related to https://bugs.eclipse.org/bugs/show_bug.cgi?id=525893 , we'll take a look into it.

**Comment by bwa** [comment]
Great, this is actually aborting the transaction, so It's a problem.

**Comment by jgrassel** [comment]
Good afternoon, @bwa

I haven't had a lot of luck reproducing the issue you are experiencing with Eclipselink and Postresql.  I was wondering if you would be willing to provide a demonstration of the failure with a sample application?  I've made available a set of simple maven projects, with a basic JPA application and uses Open Liberty, which can be modified with the intention of problem demonstrating.  I've made it available on github.com at https://github.com/jgrassel/JPASandbox; if you can fork the project and push to your local github space a branch modified to use postgresql (you don't need to modify the project to create a postgresql docker container, just modify the server.xml and change the datasource to a postgresql type (with genericized connection info) and I should be able to work with that.

**Comment by bwa** [comment]
@jgrassel Actually, I do have a project that can be tested locally.

It does have a bunch of commented code, but if you clone it, update the server.xml with a postgres instance of you own, and run steps to reproduce from readme.md, you should get some errors. at least I do ...

https://github.com/bwa/openliberty-JPA-issues

**Comment by jgrassel** [comment]
Hello, I've had a chance to experiment with your scenario.  It looks like a misconfiguration is the cause of your misfortune.

First, you're using the same datasource for your jta and non-jta references:
```
        <jta-data-source>jdbc/datasourceJPA</jta-data-source>
        <non-jta-data-source>jdbc/datasourceJPA</non-jta-data-source>
```

You cannot do that, the non-jta datasource must be pointed to a non-transactional datasource.  I modified your persistence.xml to the following:

```
        <jta-data-source>jdbc/datasourceJPA</jta-data-source>
        <non-jta-data-source>jdbc/datasourceJPANJTA</non-jta-data-source>
```

and added the following to the server.xml:

```
    <dataSource jndiName="jdbc/datasourceJPANJTA" transactional="false">
        <jdbcDriver libraryRef="postgresLib"/>
        <!-- replace alues below with some appropriate -->
        <properties serverName="192.168.0.90" 
                    portNumber="5432"
                    databaseName="postgres"
                    currentSchema="test"
                    user="user"
                    password="password"/>
    </dataSource>
```
And it then started working.  The important key here is the `transactional="false"` which makes this datasource a non-jta datasource (meaning it won't enlist to a JTA transaction.), which is used by the schema management tooling in Eclipselink.

**Comment by bwa** [comment]
Great, It works here also. I still need to create the schema in advance, but the main trouble here was that I really did not know that I needed a non-transactional datasource to create the tables. It was not needed with derby as I recall. But now I know.

Thank you for investigating. Hopefully others will learn from this.
