### ISSUE TITLE
Investigate mpGraphQL-1.0 Warnings

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#15496]
The mpGraphQL-1.0 feature often outputs an unnecessary warning on startup. 

```
W CWWWC0002W: No servlet definition is found for the ExecutionServlet servlet name in the AuthorizationFilter filter mapping.
```

This is likely a misconfiguration that could be avoided. The result is that several tests have to be configured to ignore this warning when they didn't really do anything that should have required it. For example, all that [MPCompatibleTest](https://github.com/OpenLiberty/open-liberty/blob/59b60f2aa5c1bb95f9f9e5dee6ec7c5d974d9584/dev/io.openliberty.microprofile.internal_fat/fat/src/io/openliberty/microprofile/internal/test/suite/MPCompatibleTest.java#L267) does is check to see if the features start up with a basic application. A warning like this should not be output and need to be ignored.

My best guess is that [GraphQLAuthorizationServletContainerInitializer](https://github.com/OpenLiberty/open-liberty/blob/59b60f2aa5c1bb95f9f9e5dee6ec7c5d974d9584/dev/com.ibm.ws.microprofile.graphql.authorization/src/com/ibm/ws/microprofile/graphql/authorization/component/GraphQLAuthorizationServletContainerInitializer.java#L40) is registering the filter before the servlet itself has been registered by [GraphQLServletContainerInitializer](https://github.com/OpenLiberty/open-liberty/blob/59b60f2aa5c1bb95f9f9e5dee6ec7c5d974d9584/dev/com.ibm.ws.io.smallrye.graphql/src/com/ibm/ws/io/smallrye/graphql/component/GraphQLServletContainerInitializer.java#L212)

I expect it is possible to make sure that GraphQLServletContainerInitializer always starts before GraphQLAuthorizationServletContainerInitializer

**Comment by tevans78** [comment]
The FFDC was fixed but the warning is still produced.

**Comment by jhanders34** [comment]
The problem addressed in the attached PR is that the servlet is only added conditionally, and the security servlet initializer was adding it unconditionally even when the servlet wasn't added for non mpGraphQL applications.
