### ISSUE TITLE
Web binding overrides aren't properly recognized with autoExpand apps on

### ISSUE THREAD

**Issue by ewhoch** [OpenLiberty/open-liberty#1553]
A combination of server.xml overriding WAR bindings for a WAR inside of an EAR along with autoExpand=true causes things like contextRoot and virtual-host to not be recognized by the runtime.

This would be for server.xml snippets like:

```	
<application location="DefaultApplication.ear">
	<web-bnd moduleName="DefaultWebApplication">
		<virtual-host name="application-1" />
	</web-bnd>
</application>
 ```

As a workaround, setting <applicationManager autoExpand="false"/> causes the problem to not happen, however this can cause issues if the application depends on getRealPath as it won't return a location on disk anymore.

**Comment by hlhoots** [comment]
Developer verified. Closing for now.
