### ISSUE TITLE
BETA BLOG - expandLocation property for AutoExpand

### ISSUE THREAD

**Issue by hlhoots** [OpenLiberty/open-liberty#15548]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty.

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name (eg WebSockets feature): Liberty configuration variables
   
   Short feature name (eg websockets-1.0): N/A. Application Manager

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.
Liberty developers / administrators who want to set an auto expand location for their application to a different  location than the default  of ${server.config.dir}/apps/expanded/

3. Write a paragraph to summarises the update, including the following points:
   
This enhancement would allow the user to specify a expansion location (expandLocation) on the applicationManager configuration to be utilized when the autoExpand attribute is set to "true". As currently implemented, when an application is autoExpanded the default location for the expanded files are hard coded to ${server.config.dir}/apps/expanded/.

After this change, the user would be able to configure that location to a new value on the filesystem. Thus for example:

`<applicationManager autoExpand="true" expandLocation="${server.config.dir}/myApps/" />
`

would result in the application being expanded at ${server.config.dir}/myApps/{appname}/

This enhancement gives users more flexibility regarding the location of their expanded applications.

References:
https://openliberty.io/docs/20.0.0.12/reference/config/applicationManager.html

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by jakub-pomykala** [comment]
Published in 21.0.0.3-beta on 19th of February 2021
