### ISSUE TITLE
GA BLOG - New way to configure NBF Claim in jwtBuilder

### ISSUE THREAD

**Issue by mmerali96** [OpenLiberty/open-liberty#15553]
Feature Epic: #11868
The information you provide here will be included in the Open Liberty GA release blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this newly released feature/function of Open Liberty.

Please provide the following information the week before the GA date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
      The jwtBuilder element in the jwt-1.0 feature.
   Human-readable name (eg WebSockets feature):
     JWT Builder
   Short feature name (eg websockets-1.0): 
        jwt-1.0
2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.
    Application Developer, Security/System Admin
3. Write a paragraph to summarises the update, including the following points:

  - A sentence or two that introduces the update to someone new to the general technology/concept.

The jwtBuilder element is being enhanced with a new attribute called nbfOffset which will be used to configure the NBF claim in a JWT payload. The time set for the nbfOffset will be added to the current time and the result will be used to determine when JWT will start to be accepted for processing. The value must be a NumericDate.

   - What was the problem before and how does your update make their life better? (Why should they care?)

The jwtBuilder element did not have a way to configure the "not before" claim. This update provides a way to configure the  NBF claim.

   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.

To configure the NBF claim using jwtBuilder, add the following to your sever.xml configuration file. If the JWT was issued at the current time, then the token can only be used after 1800s from the current time.
   ```<jwtBuilder nbfOffset="1800s" />```

   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?

https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_sec_build_jwt.html
https://openliberty.io/docs/20.0.0.8/reference/config/jwtBuilder.html

If you have previously provided this information for an Open Liberty beta blog post and nothing has changed since the beta, just provide a link to the published beta blog post and we'll take the information from there.

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the GA release blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the GA blog post).

**Comment by austin0** [comment]
21.0.0.1 GA blog live here: https://openliberty.io/blog/2021/01/22/jwtbuilder-redirects-21001.html
