### ISSUE TITLE
BETA BLOG - Jakarta Messaging 3.0 support

### ISSUE THREAD

**Issue by dazavala** [OpenLiberty/open-liberty#15551]
[Epic #11851]

FYI, Support for Jakarta Messaging 3.0 released in the 21.0.0.1-beta for open-liberty jakartaee9.  We will include messaging-3.0 in the 21.0.0.2-beta blog.  For this issue we may also update the 21.0.0.1-beta blog with the same exact content, to make it clear that the feature is available there as well.

The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty.

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name (eg WebSockets feature):  **Jakarta Messaging 3.0** 
   
   Short feature name (eg websockets-1.0):  **messaging-3.0, messagingClient-3.0, messagingServer-3.0, messagingSecurity-3.0**

2. Who is the target persona? Who do you expect to use the update?  **Application developer** 

3. Write a paragraph to summarizes the update, including the following points:

> 

> **Jakarta Messaging 3.0**
> 
> Jakarta Messaging is an API and services that enable applications to create, send, and receive messages via loosely coupled, reliable asynchronous communications.  Support for version 3.0 updates the API and services to the `jakarta.*` namespace and introduces four new features for Jakarta EE 9: `messaging-3.0`, `messagingClient-3.0`, `messagingServer-3.0`, `messagingSecurity-3.0`.
>
>Configuration is the same as the corresponding features for Jakarta EE 8 (`jms-2.0`, `wasJmsClient-2.0`, `wasJmsServer-1.0`, `wasJmsSecurity-1.0`) with one exception: version 3.0 support does not introduce a new feature corresponding to `jmsMdb-1.0`.  Instead, use Jakarta EE 9 feature `mdb-4.0` when deploying message-driven beans to connect to MQ providers, JCA resource adapters, or the embedded messaging server.
> 
> To enable the new Jakarta EE 9 messaging features, add them to your `server.xml`.  Here's a feature configuration that enables applications to access message queues via the Messaging 3.0 API, enables message-driven beans to connect to the embedded messaging server, and enables JNDI lookups for messaging resources.
> 
> ```
>  <featureManager>
>        <feature>messagingClient-3.0</feature>
>        <feature>mdb-4.0</feature>
>        <feature>jndi-1.0</feature>
>  </featureManager>
> ```
> 
> For more information please refer to the [Jakarta Messaging 3.0 specification](https://jakarta.ee/specifications/messaging/3.0/).

_**IF WE UPDATE [21001-beta topic ](https://openliberty.io/blog/2020/10/27/microprofile40-jakartaee9-beta-200012.html#jakarta)**_

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by dazavala** [comment]
@jakub-pomykala This issue is ready for your consideration.

**Comment by austin0** [comment]
21.0.0.2-beta blog live here: https://openliberty.io/blog/2021/01/26/ee9-messaging-security-21002-beta.html
