### ISSUE TITLE
BETA BLOG - Jakarta Security 2.0 support, expanded Jakarta EE 9 support for security features

### ISSUE THREAD

**Issue by jvanhill** [OpenLiberty/open-liberty#15555]
[Epic #14014]
[Epic #14098]
[Epic #14198]
[Epic #14711]
[Epic #14858]
[Epic #11864]

The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty.

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name (eg WebSockets feature):
```
- Application Security 4.0 (Jakarta Security 2.0)
- Application Security for Client 1.0
- Audit 1.0
- Kerberos Constrained Delegation for SPNEGO 1.0
- Java Connector Architecture Security Inflow 1.0
- JSON Web Token 1.0
- Password Utilities 1.0
- Simple and Protected GSSAPI Negotiation Mechanism 1.0
```
   
   Short feature name (eg websockets-1.0): 
```
- appSecurity-4.0
- appSecurityClient-1.0
- audit-1.0
- constrainedDelegation-1.0
- jcaInboundSecurity-1.0
- jwt-1.0
- passwordUtilities-1.0
- spnego-1.0
```

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.

`Application Developer`

3. Write a paragraph to summarises the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.

```
The new `appSecurity-4.0` feature has been created to support Jakarta EE 9 and introduces Jakarta Security 2.0 support. The `appSecurityClient-1.0`, `audit-1.0`, `constrainedDelegation-1.0`, `jcaInboundSecurity-1.0`, `jwt-1.0`, `passwordUtilities-1.0` and `spnego-1.0` features have been updated to also support Jakarta EE 9.
```

   - What was the problem before and how does your update make their life better? (Why should they care?)
   ` None of the listed features supported Jakarta EE 9.`
   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.
   `The appSecurity-4.0 feature must be added to server.xml when using application security with Jakarta EE 9. The other features will automatically adapt to the level of Java EE or Jakarta EE that is already in use, so no change is needed when using them with Jakarta EE 9.`
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?
` The Jakarta Security 2.0 specification can be found here: https://jakarta.ee/specifications/security/2.0/`

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by mbroz2** [comment]
Is there anything new in Application Security 4.0 (Jakarta Security 2.0), or is it just namespace update?  If the former, can you provide a paragraph regarding the changes/new content?

**Comment by jvanhill** [comment]
> Is there anything new in Application Security 4.0 (Jakarta Security 2.0), or is it just namespace update? If the former, can you provide a paragraph regarding the changes/new content?

There is no new functionality, other than to support the namespace change.

**Comment by austin0** [comment]
21.0.0.2-beta blog live here: https://openliberty.io/blog/2021/01/26/ee9-messaging-security-21002-beta.html
