### ISSUE TITLE
Cloudant stanza ignores username and password

### ISSUE THREAD

**Issue by jwalcorn** [OpenLiberty/open-liberty#15561]
**Describe the bug**
You get a 401 error back from Cloudant if you specify the username and password fields in the cloudant stanza in your server.xml.  So this fails:

    <cloudant id="myCloudant" libraryRef="cloudantLib" url="${CLOUDANT_URL}" username="${CLOUDANT_ID}" password="${CLOUDANT_PASSWORD"/>
    <cloudantDatabase jndiName="cloudant/AccountDB" databaseName="${CLOUDANT_DB}" create="true" cloudantRef="myCloudant"/>

All works if you put a containerAuthDataRef in the <cloudant> stanza instead, pointing at an authData with the username and password in there instead.  So this works:

    <authData id="cloudantCredentials" user="${CLOUDANT_ID}" password="${CLOUDANT_PASSWORD}"/>
    <cloudant id="myCloudant" libraryRef="cloudantLib" url="${CLOUDANT_URL}" containerAuthDataRef="cloudantCredentials"/>
    <cloudantDatabase jndiName="cloudant/AccountDB" databaseName="${CLOUDANT_DB}" create="true" cloudantRef="myCloudant"/>

**Steps to Reproduce**
Create a Cloudant service.  I made one in the IBM Cloud and pointed my OL container at that.  I fully expect the same would happen with a Cloudant installed locally into your OpenShift cluster.  Then just add the server.xml snippets above and copy the Cloudant jars into the container and reference them from a library in the server.xml, and do an @Resource injection of the Cloudant database into your code.  When your JAX-RS service starts up, you'll see the 401 when the injection is attempted.

**Expected behavior**
The "username" and "password" fields of the <cloudant> stanza should be honored.

**Diagnostic information:**
 - OpenLiberty Version: [e.g. 19.0.0.8]:
 20.0.0.12 (wlp-1.0.47.cl201220201111-0736)
 
 - Java Version: [i.e. full output of `java -version`]
 openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 11 Linux amd64-64-Bit Compressed References 20201022_810 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - 3b09cfd7e9 based on jdk-11.0.9+11)

 - server.xml configuration (WITHOUT sensitive information like passwords)
https://github.com/IBMStockTrader/account/blob/master/src/main/liberty/config/server.xml
 
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`
[ERROR   ] CWOWB1000E: A CDI error has occurred: CWNEN0030E: The server was unable to obtain an object instance for the java:comp/env/com.ibm.hybrid.cloud.sample.stocktrader.account.AccountService/accountDB reference.  The exception message was: CWNEN1006E: The server was unable to obtain an object for the cloudant/AccountDB binding with the com.cloudant.client.api.Database type. The exception message was: com.cloudant.client.org.lightcouch.CouchDbException: 401 Credentials are incorrect for server https://878ff489-3ab9-4d2d-86db-016f19864439-bluemix.cloudantnosqldb.appdomain.cloud:443/_session.

**Additional context**
Discussed with various Liberty guys at https://ibm-cloud.slack.com/archives/C30NGTBFS/p1610605700002800
Also, there's a pattern where you can encode the id and pwd in the URL, like https://${CLOUDANT_ID}:${CLOUDANT_PASSWORD}@${CLOUDANT_HOST}, but I wasn't using that.  Perhaps with that specified as the URL, you wouldn't need to specify the id and pwd anywhere else.

**Comment by njr-11** [comment]
It looks like there is a typo in the configuration of the `password` attribute,
```
password="${CLOUDANT_PASSWORD"/>
```
should be
```
password="${CLOUDANT_PASSWORD}"/>
```
