### ISSUE TITLE
OIDC client userIdentifier and userIdentityToCreateSubject descriptions are confusing

### ISSUE THREAD

**Issue by barbj** [OpenLiberty/open-liberty#15585]
An internal customer had a problem distinguishing between these properties in the OIDC client doc, https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.liberty.autogen.nd.doc/ae/rwlp_config_openidConnectClient.html

**userIdentifier**  (no default)
_Specifies a JSON attribute in the ID token that is used as the user principal name in the subject. If no value is specified, the JSON attribute "sub" is used._

**userIdentityToCreateSubject** (default=sub)
_Specifies a user identity in the ID token used to create the user subject._

Chunlong said that **userIdentityToCreateSubject**  is an old property and that **userIdentifier**, **groupidentifier**, **realmIdentifier** were added together.

After some discussion, Chunlong verified the following:

**userIdentifier** and **userIdentityToCreateSubject** mean exactly the same thing.
They both default to 'sub'.
If you enter a value for both, the value for **userIdentifier** will only be used. 

This is what I propose:

<hr></hr>

**userIdentifier**  (default=sub)
_Specifies a JSON attribute in the ID token that is used as the user principal name in the subject. If no value is specified, the JSON attribute "sub" is used._

**userIdentityToCreateSubject** (default=sub)
_Specifies a JSON attribute in the ID token that is used as the user principal name in the subject. If no value is specified, the JSON attribute "sub" is used.  The value for this property is overridden by the value for userIdentifier, if specified._

**Comment by brutif** [comment]
@barbj Thanks for running this down!  I was looking at metatype.properties and scratching my head.
