### ISSUE TITLE
Loose application with variable substitution in the apps.war.xml  is not packaged by server package command

### ISSUE THREAD

**Issue by hlhoots** [OpenLiberty/open-liberty#15636]
This design issue is in reference to the problem described in detail in issue #15620.

Problem: When running the server package command with a loose application .war.xml file that uses server variable substitution, those parts of the loose application are not packaged.  However that configuration does work for a normal server, just not in the package case since the server is not started at the time of packaging and has no way to access the needed variable information.

```
<archive>
     <dir sourceOnDisk="${io.openliberty.tools.projectRoot}/src/main/webapp" targetInArchive="/"/>
</archive>
```

`Error: CWWKE0094W: The server cannot package the application files because one or more location symbols in the ${io.openliberty.tools.projectRoot}/src/main/webapp file is unknown.`

Possible solutions:
1.  Document that variable substitution is not allowed in loose  .war.xml files.   
2. Try to start up the server so the information is there at the time of the package command.  Downside is that it would most likely increase packaging time.
3. Create a separate config parser that only loads variables, but that would leave some potential gaps (eg, if a component registered a variable when it got activated, the application would have access to that in the server case but not in the package case)

**Comment by tevans78** [comment]
Agreed that documentation only needed ... option 1

**Comment by hlhoots** [comment]
Link to doc that should be updated: https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_loose_applications.html

**Comment by hlhoots** [comment]
Created an issue to have the docs updated accordingly at https://github.ibm.com/websphere/liberty-docs/issues/2209

**Comment by hlhoots** [comment]
Closing this design issue out and will track via the docs defect listed above and the original issue listed above.
