### ISSUE TITLE
Design of server quiesce

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#1564]
Liberty server quiesce doesn't allow time for application workload to complete. It also doesn't stop all inbound traffic. Things to consider:

1) Stop accepting inbound http ports
2) Stop accepting inbound messaging ports
3) Stop accepting inbound IIOP ports
4) Stop accepting inbound SIP ports
5) Stop accepting inbound network ports missed above.
6) Stop processing MDBs
7) Allow time for app work to complete
8) Allow time for work scheduled on server executor prior to quiesce starting to finish.

Current design doesn't do 6-8. Consider whether we should reuse the server pause support, so pause everything that is pausable. Only http traffic is currently pausable though. Should that be expanded. How to allow time for 7 & 8.

**Comment by NottyCode** [comment]
Current investigation on the solution is here:

Only the http transport is a pausablecomponent. This is because the httpendpoint implements the pause method, rather than the channel framework and channel chains. We should look at moving the pausable component implementation into the channel chain. The id used is specified on the endpoint, so we also need to ensure that gets passed down, and if we have multiple with the same id all should be shutdown. This is a bit different from today.

Then we should update the quiesce listeners so we have 1 that basically calls pause on all pausable components. We should remove the server quiesce listener for the channel framework, and any others that are now redundant.

We need a way to efficiently mark the tasks queued for the server thread pool. Any tasks queued prior to quiesce starting should be allowed up to 30 seconds to complete. When either they are all done, or 30 seconds is up then we can start running shutdown. It was suggested we could start a new thread pool, but that will require new threads to be created which will be inefficient.

**Comment by tevans78** [comment]
@brenthdaniel are you happy with the resolution of this issue? can it be closed?
