### ISSUE TITLE
Netty - Create bundle project

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#15668]
Create a bundle project that will provide core Netty libraries for consumption by other Liberty bundles. Currently this only includes the grpc client bundles, but going forward we'll use it for developing the potential channel framework replacement.

**Comment by hutchig** [comment]
Anyone looking at this can find a strawman in https://github.com/OpenLiberty/open-liberty/pull/15709

**Comment by wtlucy** [comment]
resolved by #15668
