### ISSUE TITLE
Netty - Explore feasibility of WsByteBuffer compatibility

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#15670]
- https://github.com/hutchig/open-liberty/issues/6
- performance must be similar

**Comment by hutchig** [comment]
References:

- https://engineering.linkedin.com/blog/2021/taming-memory-fragmentation-in-venice-with-jemalloc

**Comment by hutchig** [comment]
How do we test performance?
https://jmeter.apache.org/ was mentioned but I don't yet have a code resource that uses it. Will search.

**Comment by hutchig** [comment]
Clients of WsByteBuffer are:
<img width="402" alt="image" src="https://user-images.githubusercontent.com/2861921/106585295-12577a80-653f-11eb-87b1-091765c251a1.png">

**Comment by hutchig** [comment]
Where are:

**Comment by hutchig** [comment]
Practical testing:
alias buftest='cd ~/libertyGit/open-liberty/dev && ./gradlew com.ibm.ws.channelfw:test --tests "com.ibm.ws.bytebuffer.test.*" ;  grep "testcase name" ~/libertyGit/open-liberty/dev/com.ibm.ws.channelfw/build/libs/test-reports/test/*.xml'

**Comment by hutchig** [comment]
https://mvnrepository.com/artifact/io.netty/netty-buffer/usages?sort=popular

**Comment by hutchig** [comment]
Netty Buffer Leaks:
https://dzone.com/articles/how-to-identify-and-troubleshoot-a-netty-memory-le
https://logz.io/blog/netty-bytebuf-memory-leak/
https://github.com/micronaut-projects/micronaut-core/issues/2770
https://netty.io/wiki/reference-counted-objects.html

**Comment by hutchig** [comment]
Netty Buffer users:
https://mvnrepository.com/artifact/io.netty/netty-buffer/usages?sort=popular

**Comment by hutchig** [comment]
Boxnote looking at a method by method comparison:
https://ibm.ent.box.com/notes/772293546984

**Comment by hutchig** [comment]
Don't forget:
(but no details here)
~/libertyGit/WS-CD-Open/dev
$ ls | grep channel
com.ibm.ws.channel.ssl_bvt
com.ibm.ws.channel.ssl_fat
com.ibm.ws.channelfw.aio_zfat
com.ibm.ws.channelfw_bvt
com.ibm.ws.channelfw_fat
com.ibm.ws.zos.channel.console
com.ibm.ws.zos.channel.local
com.ibm.ws.zos.channel.local_test
com.ibm.ws.zos.channel.local_ztest
com.ibm.ws.zos.channel.wola
com.ibm.ws.zos.channel.wola.odi
com.ibm.ws.zos.channel.wola_test
com.ibm.ws.zos.channel.wola_zfat
com.ibm.ws.zos.channel.wola_ztest

**Comment by hutchig** [comment]
Updated link: https://ibm.box.com/s/o5uq5c7exr29mbyjps6jkvki9i9rdeg6 to feature comparison table.

**Comment by hutchig** [comment]
This has been completed
