### ISSUE TITLE
BETA BLOG - Jakarta XML Web Services 3.0 Support

### ISSUE THREAD

**Issue by neuwerk** [OpenLiberty/open-liberty#15689]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty.

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name (eg WebSockets feature): XML Web Services 3.0
   
   Short feature name (eg websockets-1.0): xmlWS-3.0

2. Who is the target persona? Who do you expect to use the update? Application Developer

3. Write a paragraph to summarises the update, including the following points:

> Jakarta XML Web Services 3.0 is an API that enables applications to create SOAP based Web Services, and was formerly known as JAX-WS. Support provides the following updated APIs: XML Web Services 3.0, Jakarta Web Services Metadata 3.0, Jakarta SOAP with Attachments 2.0. Support also introduces the `xmlWS-3.0` feature, as well as the Application Client Container support for XML Web Services 3.0 via the `jakartaeeClient-9.0` convenience feature.
> 
> The `xmlWS-3.0` feature provides the Jakarta EE 9 XML Web Services 3.0 tools for Top Down and Bottom Up Web Services Creation: `wsgen` and `wsimport`. These can be found in a new location in the Open Liberty image: `wlp/bin/xmlWS/`. Both commands preform nearly identical to the Jakarta EE 8 tooling, with the exception that the `-target` argument is no longer required.
> 
> The implementation of Jakarta XML Web Services 3.0 in Open Liberty is based on Apache CXF 3.4.1. This provides numerous improvements and fixes over the forked version of CXF 2.6.2 in use by the Jakarta EE 8 `jaxws-2.3` feature (Note: Not all CXF 3.4.1 functionality is available in `xmlWS-3.0`, but watch this space for updates.) 
> 
> To enable the new Jakarta EE 9 XML Web Services 3.0 feature, add the `xmlWS-3.0` feature to your server.xml. Here's an example of what the feature configuration looks like: 
> 
> ```
>     <featureManager>
>           <feature>xmlWS-3.0</feature>
>     </featureManager>   
> ```
> 
>  To run Jakarta XML Web Services on the Application Client Container: Here's an example of what the `client.xml` configuration looks: 
> 
> ```
>     <featureManager>
>           <feature>jakartaeeClient-9.0</feature>
>     </featureManager>   
> ```
> 
> For more information see the [Jakarta XML Web Services Specification](https://jakarta.ee/specifications/xml-web-services/), and the [Apache CXF 3.4 Migration Guide](https://cxf.apache.org/docs/34-migration-guide.html)
> 

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by neuwerk** [comment]
#11862

**Comment by samwatibm** [comment]
Adding release:21003-beta to track current work even though the corresponding Epic went out in 21002-beta

**Comment by jakub-pomykala** [comment]
This has been published in 21.0.0.2-beta which can be found [here](https://openliberty.io/blog/2021/01/26/ee9-messaging-security-21002-beta.html#xmlws)
