### ISSUE TITLE
Create a guide to demonstrate how to enable connection to an IDaaS

### ISSUE THREAD

**Issue by jtmulvey** [OpenLiberty/open-liberty#15706]
There are a growing number of use cases that would benefit from showing how to easily connect to an IDaaS, such as IBM Verify. One is for developers testing in local environments (ie: remotely at home) where they wish to share a user registry with other developers on their team.  This is essentially a specialized use case that extends LIberty's OIDC feature, similar to the SocialLogin feature, but offering a richer set of capabilities like those offered by Verify.

**Comment by NottyCode** [comment]
@jtmulvey Can you clarify what you are looking for in this guide? Our guides generally deal with the technology, not the productization of the technology and this reads like write a guide to indicate how to configure Open Liberty to work with an IBM product.

**Comment by yeekangc** [comment]
Right, Jim, can you please elaborate on what is behind or equivalent to IBM Verity technology-wise that we should consider and cover with a guide?

**Comment by jtmulvey** [comment]
@NottyCode @yeekangc I opened this issue to enable us to show how easy it is to configure Liberty to connect an IDaaS like Okta (https://www.okta.com/identity-101/idaas/) or Ping O(https://www.pingidentity.com/en/resources/client-library/articles/identity-as-a-service-idaas.html) Auth0 (https://auth0.com/blog/what-is-idaas/) or IBM Verify (https://www.ibm.com/products/verify-for-workforce-iam).  Enterprise-grade IDaaS's are very much on the rise now for large customers, especially those with built in fraud detection features (ie: IBM Trusteer), and this guide would demonstrate how easy it is to enable Liberty to hook up to these.  I suggest we consider examples demonstrating how to connect to Okta and IBM Verify, both offer free usage up to a maximum number of requests.

**Comment by yeekangc** [comment]
@Charlotte-Holt copied this over to https://github.com/OpenLiberty/guides-common/issues/591 already.  Closing and will copy Jim's feedback over.
