### ISSUE TITLE
Add 'expandLocation' property for autoExpanded Apps

### ISSUE THREAD

**Issue by hlhoots** [OpenLiberty/open-liberty#15705]
Hi.  I am adding a new expandLocation property in https://github.com/OpenLiberty/open-liberty/issues/15132.  Opening this issue to have that new property added to this link for open liberty:  https://openliberty.io/docs/21.0.0.1/reference/config/applicationManager.html

Name: expandLocation
Type: String
Default: ${server.config.dir}/apps/expanded/
Description: The expandLocation attribute enables a user to set the location where the autoExpanded application is located. The default location is ${server.config.dir}/apps/expanded/.

Not sure on a target date.  Just now getting the focal approval poritons started.

**Comment by dmuelle** [comment]
Hi @hlhoots - after checking with @NottyCode , I'm going to close this issue as the information will be picked up from the metatype automatically and added to the gendoc. Thanks
