### ISSUE TITLE
BETA BLOG - Ability to control whether thread dumps are collected when a hung request is detected in the Request Timing feature

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/open-liberty#15730]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty.

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name (eg WebSockets feature):
   - `Request Timing 1.0`
   
   Short feature name (eg websockets-1.0): 
   - `requestTiming-1.0`

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.
   - `Operation Administrators`

3. Write a paragraph to summarises the update, including the following points:
   
The Request Timing feature (requestTiming-1.0) provides diagnostic information when the duration of any request exceeds the configured threshold. It provides a way to monitor requests with respect to time, where it can automatically detect slow and hung requests all while providing detailed information back, such as, warning messages, thread stacks, and the creation of thread dumps for hung requests, to help diagnose the cause of the slow or hung request, in Open Liberty.

When a hung request is detected in the Request Timing feature, a warning message is written in the messages log file along with a dump of the tree of events that happened during the request. Following that, a set of three thread dumps will be initiated, 1 minute apart. After the completion of the three thread dumps, further set of three thread dumps are created only if new requests are detected to be hanging.

Some operations teams do not want thread dumps to be generated, whenever a hung request is detected in the requestTiming-1.0 feature, because there will be unwanted java thread dumps for requests that are known to be normally long and the process of generating them will impact performance. In previous Open Liberty releases, there was no option to disable the thread dumps from being generated each time a hung request is detected.

You can now control whether the Request Timing feature collects thread dumps dumps or not when a hung request is detected. By simply configuring the **NEW** `enableThreadDumps` Request Timing server configuration attribute, to false, thread dumps will not be created during hung requests. Thread dumps will be created, by default, if the new server configuration attribute is set to true or not specified at all.
   
The new Request Timing server configuration attribute can be configured in your server.xml as follows:

`<requestTiming includeContextInfo="true" slowRequestThreshold="120s" hungRequestThreshold="10s" sampleRate="1" enableThreadDumps="false"></requestTiming>`

The `enableThreadDumps` server configuration attribute can also be used in embedded Request Timing sub-elements: 
`<servletTiming/>` or `<jdbcTiming/>`, as follows:

`<requestTiming includeContextInfo="true" slowRequestThreshold="120s" hungRequestThreshold="10s" sampleRate="1">
        <servletTiming appName="MyApp" servletName="MyServletApp" slowRequestThreshold="100s" hungRequestThreshold="5s" enableThreadDumps="false"/>
    </requestTiming>`

NOTE: An embedded `<servletTiming/>` or `<jdbcTiming/>` configuration in the server.xml file overrides the configured slow and hung request threshold that are defined in `<requestTiming/>`. 
   
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?
For more information on the Request Timing feature, please refer to the following documentations:
- https://openliberty.io/docs/21.0.0.1/reference/feature/requestTiming-1.0.html
- https://openliberty.io/docs/21.0.0.1/reference/config/requestTiming.html

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by jakub-pomykala** [comment]
Published in 21.0.0.3-beta on 19th of February 2021
