### ISSUE TITLE
Subsystem content order is not consistent - leads to unpredictable feature resolution

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#15734]
Liberty features may include zero or more other features.  This is specified by listing the features (with type="osgi.subsystem.feature") in the `Subsystem-Content` feature manifest header.  In the feature manifest there is an order to the listed features.  When Liberty parses the `Subsystem-Content` header the specified features included end up being put into a Map, keyed by the included feature name.  The end result is that the order is not maintained at runtime when the feature manager is processing the configured features.

The order of included features does influence the algorithm used in the feature resolver.  In particular it may influence the decision on which version to select in the face of ibm.toleration (this is being observed in issue #15377).

Consider the following features:

```
FeatureA:
  FeatureB-1; tolerates:="2"
  eeCompatible-7; tolerates:="6, 8"

FeatureB-1
  eeCompatible-6; tolerates:="7, 8"

FeatureB-2
  eeCompatible-7; tolerates:="6, 8"
```

Depending on the order the included features are processed by the feature resolver this will end up enabling either `eeCompatible-6` or `eeCompatible-7`, both of which are valid decisions to make.  But the actual order that gets processed at runtime is dependent on the hashing algorithm of HashMap.  We could make this consistent by having the runtime preserve the order specified in the feature manifest for the included features.  But this risks breaking zero-migration by enabling a different set of features.  But it also will make it more consistent for future release of Liberty and/or Java versions.

Background details:

The order matters to the resolver algorithm because the first included features get added to the decision list first and each decision that has to be postponed (because of multiple available matching versions) gets added to the postpone decision list in the order they are found.  If `FeatureB-1` is processed first then its postponed decision (between version 1 and 2) is added first and then the decision for eeCompatible (between versions 7, 6, and 8) is added second.  After the first pass when all the immediate decisions possible have been made the resolver will pick off the first postponed decision and make a selection.  Here it picks off `FeatureB-1; tolerates:="2"` and tries the preferred version 1 as its decision (note it makes a record that a decision has been made incase it needs to backtrack for a later conflict). Now it traverses into FeatureB-1 dependencies for the first time.  Here it finds `eeCompatible-6; tolerates:="7, 8"` and has to postpone that decision, a discovery is made that the eeCompatible decision has already been postponed so the dependency for preferred version 6 is recorded.

After traversing all the dependencies again making all the immediate decisions possible (based on FeatureB-1 being selected) the resolver will pick off the next postponed decision and make a selection.  This time it is for eeCompatible for which two dependency chains have different preferred versions (6 vs. 7).  The resolver always selects the lowest preferred version that can satisfy all the tolerations.  In this case eeCompatible 6 is selected.

If the reverse order is processed then the `eeCompatible-7; tolerates:="6, 8"` postponed decision will be made first, without any knowledge yet that `FeatureB-1` has a preference of version 6.  In this case eeCompatible-7 will be selected.

As long as the hashing algorithm of HashMap is consistent then the selected features will be consistent.  But something else the will affect the order is adding a new feature dependency:

```
FeatureA:
  FeatureB-1; tolerates:="2"
  FeatureC-1; tolerates:="2"
  eeCompatible-7; tolerates:="6, 8"

FeatureC-1
  eeCompatible-7; tolerates:="6, 8"

FeatureC-2
  eeCompatible-8; tolerates:="6, 7"
```

When only `FeatureB-1` and `eeCompatible-7` are included the order may be consistently kept `FeatureB-1`, `eeCompatible-7` always resulting in eeCompatible-6 being selected.  But adding the new include of `FeatureC` may change the order in the Map such that either `FeatureC-1` or `eeCompatible-7`are processed before the decision on `FeatureB-1`.  Both cases would result in eeCompatible-7 being selected instead of eeCompatible-6

**Comment by tevans78** [comment]
Agreed that consistency is desirable but need to talk with stack products to see if a change would affect them.

**Comment by tjwatson** [comment]
PR #15729 and PR #17075 have addressed this design issue.  Closing.
