### ISSUE TITLE
EjbTimerTest.testCDIScopeViaEJBTimer may be operating incorrectly

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#15789]
https://github.com/OpenLiberty/open-liberty/pull/15583#discussion_r569518954

> the call to /ejbTimer/Timer appears to increment the session scoped counter after setting up a timer, rather than when that timer executes, contrary to the javadoc on this test method. (See EjbSessionBean#incCountersViaTimer)

**Comment by tevans78** [comment]
@benjamin-confino  Can this be closed? What is remaining?

**Comment by benjamin-confino** [comment]
It can be closed.
