### ISSUE TITLE
Create a server dump introspector for MicroProfile Config

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#15804]
To do this, we need to provide a DS that implements `com.ibm.wsspi.logging.Introspector`. It may be that we want more than one version for the different MP Config implementations we have.

The introspector should dump out the contents of each Config instance in the classloader cache; the keys, values and the resolved Config Sources that provided them.

**Comment by hutchig** [comment]
I remember mentioning this in the scrum?
https://github.com/OpenLiberty/open-liberty/issues/14001
If not needed can you close it?

**Comment by Azquelt** [comment]
The following things need considering before attempting this again:
* inclusion of sensitive config (passwords etc.)
* mitigating the risks of dumping a very large config source

**Comment by Azquelt** [comment]
We discussed this and decided:
* We should make a best effort to mask values where the config name suggests it might be sensitive (e.g. contains password, pass, pwd, key etc.)
* We think the risk of causing problems by dumping a very large config source are very small.
