### ISSUE TITLE
KRB5: Kerberos for Ldap: Feature Test Summary

### ISSUE THREAD

**Issue by kristip17** [OpenLiberty/open-liberty#15802]
This is the Feature Test Summary for #12794

## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

This is a new feature under the umbrella of the LdapRegistry feature and required new unit and FAT tests, as well as new FAT infrastructure to test the Kerberos login options (ticketCache/keytab).

We used the ApacheDS infrastructure to start a Directory Server, Ldap Server and Kerberos Server (KDC) locally so we can do the Kerberos bind, fetch tickets, try different ticketCaches and keytabs. Added infrastructure to start ApacheDS during the beforeClass/afterClass on the FATSuite to save on start/stop time.

### List of FAT projects affected

* Created a new fat project `com.ibm.ws.security.wim.adapter.ldap_fat.krb5`

### Test strategy

* What functionality is new or modified by this feature? We added the `bindAuthenticationMechanism` to LdapRegisty. Setting this new attribute to `simple` (default) or `none` matches the current behavior. The new behavior is `GSSAPI` (aka Kerberos, aka krb5) which allows the user to bind to the Ldap server either using a ticketCache (ccache) or keytab. As part of the new attributes for LdapRegistry, we added `krb5Principal` and `krb5TicketCache`. The LdapRegistry can now also make use of the existing `Kerberos` service config that provides a krb5 config file and keytab. This is similar to the behavior in AuthData for datasources.
* What are the positive and negative tests for that functionality?

General structure:

-  the ApacheDS infrastracture is started in a beforeClass/afterClass globally for the bucket.

- There's a general helper class.

- There's a base UserLoginTest that the different bind type tests will expand on. It has a `baseline login` test where I do a good/bad password check of a user, isValidUser, getGroupsForUser and getUsersForGroup.

**Test Coverage**
`SimpleBindTest` -- running baseline login in the following scenarios:
- BindAuthMech is simple
- BindAuthMech is none, Ldap allows anon bind and disallows
- BindAuthMech is not set
- BindAuthMech is set to an invalid value
- BindAuthMech starts as simple and we update to GSSAPI (Kerberos), should swap dynamicaly

`TicketCacheBindTest`
- Golden path/baseline login with ticketCache (w and w/o ContextPool)
- Cannot contact KDC (bad port)
- Empty, missing, or invalid `krb5PrincipalName`
- Empty, missing, or read-only  `krb5TicketCache`
- Start with expired cache, manually update to valid
- Swap to keytab, should update dynamically

`TicketCacheBindMultiRegistryTest`
- Use two Ldaps (ApacheDS and UnboundID) with allowOp = false. Confirm that neither registry can login when ApacheDS is down or cache is expired (and recovers when Apacheds is up, valid cache).
- Use two Ldaps (ApacheDS and UnboundID) with allowOp = true. Confirm that UnboundID can login when ApacheDS is down or cache is expired (and recovers when Apacheds is up, valid cache).

`TicketCacheBindLongRunTest`
- Restart ApacheDS server, confirm login recovers after LDAP restart, with and without context pool

`TicketCacheBindExpiredTest`
- Start with a valid certificate that is renewable and expires during runtime, verify ticket is renewed, with and without context pool
- Start with a valid certificate that is not renewable and expires during runtime, ticket is not renewed, but manual renew works. With and without context pool.
-
`KeytabBindTest`
- Golden path/baseline login with keytab
- Empty, missing, or invalid `krb5PrincipalName`
- Empty, missing, or read-only  `krb5TicketCache`
- Swap to ticketCache, should update dynamically

`KeytabBindMultiRegistryTest`
- Use two Ldaps (ApacheDS and UnboundID) with allowOp = false. Confirm that neither registry can login when ApacheDS is down (and recovers when Apacheds is up).
- Use two Ldaps (ApacheDS and UnboundID) with allowOp = true. Confirm that UnboundID can login when ApacheDS is down (and recovers when Apacheds is up).

`Krb5ConfigTest`
- Golden path with both keytab and ticketcache
- Empty, missing config with keytab and ticketcache
- Removed config during run with keytab and ticket cache, w and w/o ContextPool
- Swap config to valid and invalid file, keytab and ticketcache

Krb5ConfigJVMProp
- Run with config set via JVM prop at startup

`KeytabBadPrincipalNameTest`
- Bad principalName with and without realm name

`TicketCacheBadPrincipalNameTest`
- Bad principalName with and without realm name

`RealmNameJVMProp`
- Test with the JVM property for the realm name.

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

Ran a standalone Liberty server using our Active Directory Ldap Server configured for Keberos. Ran with ticketCache and keytab. made config updates to swap between simple/GSSPI/ticketCache/keytab. Ran with using the OS default for the `krb.ini` file.

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

Confidence assessment is 4. I've added several golden path, regression and error path tests.

**Comment by ayoho** [comment]
Coverage looks good to me 👍
