### ISSUE TITLE
GA BLOG - trustedHeaderOrigin Configuration Improvements

### ISSUE THREAD

**Issue by wtlucy** [OpenLiberty/open-liberty#15814]
The information you provide here will be included in the Open Liberty GA release blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this newly released feature/function of Open Liberty.

Please provide the following information the week before the GA date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name (eg WebSockets feature):
HTTP Channel
   
   Short feature name (eg websockets-1.0): 
N/A

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.
Operations

3. Write a paragraph to summarises the update, including the following points:

"WebSphere private headers" in the form `$WSXX` are used by WebSphere-aware proxies to provide information about original requests. The values provided by these headers are made available to the application via `ServletRequest` APIs like `getRemoteHost()`. Two HTTP Dispatcher custom properties are provided by Liberty to control over which remote hosts are allowed to send WebSphere private headers: `trustedHeaderOrigin` and `trustedSensitiveHeaderOrigin`. Ideally, these properties should be configured to only trust known proxy servers which will be forwarding requests to the Liberty server.

Previously, `trustedHeaderOrigin` and `trustedSensitiveHeaderOrigin` only accepted `*`, `none`, or a list of full IP addresses (eg. `"127.0.0.1, 192.168.6.6"`). As requested by customers, both properties can now additionally be configured with IP address wildcards and hostnames. As an example, the following list which will be valid for either property:`"localhost, 127.0.0.1, 192.168.*.*, 0:0:0:0:0:ffff:*:*, *.ibm.com"`

The same list as a server.xml example:
```    
<httpDispatcher trustedHeaderOrigin="*" trustedSensitiveHeaderOrigin="localhost, 127.0.0.1, 192.168.*.*, 0:0:0:0:0:ffff:*:*, *.ibm.com"/>
```

For more information about these properties, see https://openliberty.io/docs/21.0.0.2/reference/config/httpDispatcher.html#

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the GA release blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the GA blog post).

For #9809

**Comment by jakub-pomykala** [comment]
Published in 21.0.0.2 GA on 19th of February 2021
