### ISSUE TITLE
Method invocation on closed SseBroadcaster not resulting in IllegalStateException

### ISSUE THREAD

**Issue by jim-krueger** [OpenLiberty/open-liberty#15810]
The javadoc for javax.ws.rs.sse.SseBroadcaster.close() states:
"Subsequent calls have no effect and are ignored. Once the SseBroadcaster is closed, invoking any other method on the broadcaster instance would result in an IllegalStateException being thrown."

The current behavior in Liberty is to allow these closed instances to be re-registered, re-opened, and re-used.

**Comment by andymc12** [comment]
fixed by #17566
