### ISSUE TITLE
Update scope attribute description in the jwtBuilder config element

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/open-liberty#15820]
Original issue opened in the Liberty docs repo: https://github.ibm.com/websphere/liberty-docs/issues/2179.

In the `jwtBuilder` config element, we need to update the description of the `scope` attribute to remove the leading "scope.desc=".

See https://openliberty.io/docs/21.0.0.1/reference/config/jwtBuilder.html. 

Existing description: "scope.desc=Specify a white space separated list of OAuth scopes."
Update description: "Specify a white space separated list of OAuth scopes."

**Comment by jaimb1** [comment]
Just opened a PR for this issue: https://github.com/OpenLiberty/open-liberty/pull/16047

**Comment by jaimb1** [comment]
Reading the guidelines here: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions#release-bugs
Should this issue have a `release bug` tag in addition to `bug`?

**Comment by ayoho** [comment]
I'll invoke developer's discretion here and say this fix doesn't need to be considered a release bug. While the metatype description is customer-facing, it doesn't have an effect on the behavior of the runtime. I think its effect is low enough to not need to be considered a release bug.
