### ISSUE TITLE
Complete support for Filter

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty#1583]
We need to complete the Filter support in Open Liberty.

The Filter class specified by user (via MP Config) is already read and relevant filter methods are invoked. But some of the filter logics are missing/not handled:

- [x] The tree must be traversed from bottom-to-top (so low level items are filtered first, before their ancestors). The model walker for filter needs to support this.
- [x] Returning 'null' from a filter method should remove the item from the tree
- [x] Returning a new object should replace the item
- [x] Some tests for filter are in the TCK. Include any additional automated tests that's needed.
-----------------

MP OpenAPI 1.0 spec on Filter : https://github.com/eclipse/microprofile-open-api/blob/master/spec/src/main/asciidoc/microprofile-openapi-spec.adoc#filter

4.4. Filter
There are many scenarios where application developers may wish to update or remove certain elements and fields of the OpenAPI document. This is done via a filter, which is called once after all other documentation mechanisms have completed.

4.4.1. OASFilter
The OASFilter interface allows application developers to receive callbacks for various key OpenAPI elements. The interface has a default implementation for every method, which allows application developers to only override the methods they care about. To use it, simply create an implementation of this interface and register it using the mp.openapi.filter configuration key, where the value is the fully qualified name of the filter class.

Sample META-INF/microprofile-config.properties
mp.openapi.filter=com.mypackage.MyFilter
Vendors are required to call the registered filter once for each filtered element. For example, the method filterPathItem is called for each corresponding PathItem element in the model tree. This allows application developers to filter the element and any of its descendants.

The order of filter methods called is undefined, with two exceptions:
- All filterable descendant elements of a filtered element must be called before its ancestor.
- The filterOpenAPI method must be the last method called on a filter (which is just a specialization of the first exception).

**Comment by mrglavas** [comment]
Opened https://github.com/OpenLiberty/open-liberty/issues/1967 for follow-on testing work. Close this work item once the PR has been merged into the collaboration branch.

**Comment by mrglavas** [comment]
PR has been merged into the team collaboration branch.
