### ISSUE TITLE
Investigate improvements to mpConfig 1.x trace

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#15864]
Currently we have comprehensive trace for mpConfig 1.x, but we need to review what gets traced at the `event` level.

Ideally, `event` should contain enough information to diagnose common problems while still being understandable to the user. It should use terms that users are likely to understand from the API, rather than referring to internal components.

**Comment by tevans78** [comment]
We will do this when the need arises (a customer issue).
