### ISSUE TITLE
Investigate improvements to MP Config 2.0 trace

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#15865]
mpConfig-2.0 uses smallrye and so does not have the same automatic instrumentation as mpConfig-1.x. We need to check that sufficient low-level trace is output to allow us to diagnose problems.

In addition, we should make sure that adequate trace is output at `event` level.

To accomplish some of the above, we might need to enable the LoggingInterceptor included in the smallrye implementation but not enabled by default.

**Comment by tevans78** [comment]
We will do this when the need arises (a customer issue).
