### ISSUE TITLE
Produce a valid OpenAPI document from pure JAX-RS 2.0 applications

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty#1587]
https://github.com/eclipse/microprofile-open-api/blob/master/spec/src/main/asciidoc/microprofile-openapi-spec.adoc#documentation-mechanisms

- [ ] Test: Make a pure JAX-RS app and ensure that the annotations are scanned and a document is generated.

Spec states:

The MP OpenAPI specification requires vendors to produce a valid OpenAPI document from pure JAX-RS 2.0 applications. This means that vendors must process all the relevant JAX-RS annotations (such as @Path and @Consumes) as well as Java objects (POJOs) used as input or output to JAX-RS operations. This is a good place to start for application developers that are new to OpenAPI: just deploy your existing JAX-RS application into a MP OpenAPI vendor and check out the output from /openapi!

The application developer then has a few choices:

Augment those JAX-RS annotations with the OpenAPI Annotations. Using annotations means developers don’t have to re-write the portions of the OpenAPI document that are already covered by the JAX-RS framework (e.g. the HTTP method of an operation).

**Comment by arturdzm** [comment]
Testes basic JAX-RS application +  few special scenarios such as BeanParam and returning Pojo from the method instead of Response. Seems to be overall in good shape
