### ISSUE TITLE
BETA BLOG - Automatic Cleanup of Leaked Connections

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#15882]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty.

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name (eg WebSockets feature): **JDBC, JCA, and JMS features**
   
   Short feature name (eg websockets-1.0): **jdbc-4.3, jdbc-4.2, jdbc-4.1, jdbc-4.0, jca-1.7, jms-2.0**

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.
**Liberty server administrator**

3. Write a paragraph to summarises the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.
   **Liberty connection management is enhanced with the ability to automatically detect and close unsharable connections that are left open by the application across the end of a request.**

   - What was the problem before and how does your update make their life better? (Why should they care?)
   **Occasionally, application code might forget to close an unsharable connection that it obtains, which prevents the connection from being returned to the connection pool for use by other requests. Over time, these leaked connections can degrade performance and eventually exhaust the connection pool.  Liberty connection management now has the ability to detect and automatically close these leaked connections to prevent this from happening.**
   
   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.
   
   To take advantage of this new capability, configure one of the Liberty features that leverages the `connectionManager` element. For example, JDBC:
```
<featureManager>
  <feature>jdbc-4.2</feature>
  <feature>jndi-1.0</feature>
  <!-- more features -->
</featureManager>
```

Configure connection managers for your data sources to enable the new `autoCloseConnections` attribute,

```
<dataSource id="DefaultDataSource">
  <connectionManager maxPoolSize="10" autoCloseConnections="true"/>
    <jdbcDriver libraryRef="PostgreSQL"/>
    <properties.postgresql databaseName="TESTDB" serverName="localhost" portNumber="5432"/>
</dataSource>

<library id="PostgreSQL">
    <file name="/usr/local/postgresql/postgresql-42.2.18.jar"/>
</library>
```
   
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?
**connectionManager config documentation, which will eventually end up in a location like this:**
https://openliberty.io/docs/21.0.0.3/reference/config/connectionManager.html

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by jakub-pomykala** [comment]
Published in 21.0.0.3-beta on 19th of February 2021
