### ISSUE TITLE
Jakarta EE 9 compatibility

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/open-liberty#15926]
Create a blog post that communicates that Open Liberty is Jakarte EE 09 compatible.

**Comment by tevans78** [comment]
@jhanders34 You got the beta versions wrong, you meant `21.0.0.2-beta` and `21.0.0.3-beta`

**Comment by jhanders34** [comment]
> > Open Liberty 20.0.0.2-beta is the first release...
> > Open Liberty 20.0.0.3-beta is the first release...
> 
> @jhanders34 You meant `21.0.0.2-beta` and `21.0.0.3-beta`

I fixed it now.  New year, new number.  Ugh.

**Comment by jhanders34** [comment]
Following the blogs repository README, I created https://github.com/OpenLiberty/blogs/issues/1166 to track this blog requirement and attached a PR to the issue.

**Comment by jhanders34** [comment]
Blog has been made public.  Closing out this issue.
