### ISSUE TITLE
Add mpConfig-2.0 FAT for Property Expression nested depth

### ISSUE THREAD

**Issue by Joseph-Cass** [OpenLiberty/open-liberty#15953]
[The spec for Property Expressions](https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#property-expressions) states that:
```
The number of recursion lookups is not infinite, but a limited number for composed expressions. Implementations are encouraged to limit the number to 5, but they can use higher limits if they wish to. When the number of allowed lookups exceeds the limit, an IllegalArgumentException is thrown.
```

SmallRye Config supports a nested depth of 32:
https://github.com/smallrye/smallrye-config/blob/e5efad0380b813160675ca90bbf8619069d84ccb/implementation/src/main/java/io/smallrye/config/ExpressionConfigSourceInterceptor.java#L19

And tests the behaviour for infinite expanssion:
https://github.com/smallrye/smallrye-config/blob/e5efad0380b813160675ca90bbf8619069d84ccb/implementation/src/test/java/io/smallrye/config/ExpressionConfigSourceInterceptorTest.java#L96-L102

We should probably add additional FATs for:
1. Max depth Property Expansion in a Liberty specific default Config Source (Liberty server.xml)
2. Edge case depths (i.e. 31, 32, 33)
3. A sensible error message is output.

We should probably also document that the max recursion depth is 32 somewhere. Not sure where would be the best place for that.

**Comment by tevans78** [comment]
The existing SmallRye tests are sufficient. We don't need to add more. Closing.
