### ISSUE TITLE
Masking of sensitive values in trace in MP Config

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#15970]
In MP Config, there's no way to indicate that a particular value is sensitive and shouldn't be included in trace or logs.

Currently, our implementation makes no effort to identify sensitive values, all config keys and values may be included in the trace.log of a running server.

Should we try to improve this by:
* Treating all values as sensitive?
* Using some heuristic based on the key name to guess at whether the value is likely to be sensitive (e.g. if the key name contains "password", the value is probably sensitive)?
* Adding a way for users to mark certain config values as sensitive. (Either adding the scheme to the specification, or implementing it as an extension)

**Comment by tevans78** [comment]
We're not going to do this work in the existing versions of MP Config. Closing
