### ISSUE TITLE
SQLServer JDBC driver not recognized when defining a datasource on wlp-javaee7-17.0.04

### ISSUE THREAD

**Issue by abotos** [OpenLiberty/open-liberty#1597]
Hi,

I have trouble defining a SQL Server data source on **wlp-javaee7-17.0.0.4** (while for Oracle everything works like a charm). I'm trying to use **sqljdbc-4.1.jar** as the JDBC driver, but WLP does not recognize it. The issue, as far as I can tell, lies in the class **com.ibm.ws.jdbc.internal.JDBCDrivers** from **com.ibm.ws.jdbc_1.0.19.jar** where the following code is found:
```
classes = new String[]{"com.microsoft.sqlserver.jdbc.SQLServerDataSource", "com.microsoft.sqlserver.jdbc.SQLServerConnectionPoolDataSource", "com.microsoft.sqlserver.jdbc.SQLServerXADataSource"};
classNamesByPID.put("com.ibm.ws.jdbc.dataSource.properties.microsoft.sqlserver", classes);
classNamesByKey.put("SQLJDBC4.JAR", classes);
classNamesByKey.put("SQLJDBC.JAR", classes);
```
as compared to the similar code for the Oracle JDBC driver:
```
classes = new String[]{"oracle.jdbc.pool.OracleDataSource", "oracle.jdbc.pool.OracleConnectionPoolDataSource", "oracle.jdbc.xa.client.OracleXADataSource"};
classNamesByPID.put("com.ibm.ws.jdbc.dataSource.properties.oracle", classes);
classNamesByKey.put("OJDBC", classes);
```
Since the keys used in this map for SQLServer represent full JAR names, they do not match with other versions of the SQLServer JDBC driver. For all other drivers, e.g. Oracle, the keys in the map are really keys that can match several versions of that given driver.

From my point of view this is a bug, as the even newer versions of the SQL Server JDBC drivers have names like **mssql-jdbc** with full maven coordinates like **com.microsoft.sqlserver:mssql-jdbc:6.2.2.jre8**, and will therefore also not be recognized.

Please correct the keys in that map for SQL Server, in order for it to be possible that current versions of the SQL Server JDBC driver are automatically recognized.

BR,
Anghel

**Comment by njr-11** [comment]
Pull #1606 updates the autodetection for Microsoft SQL Server JDBC Driver to allow more general forms of sqljdbc in the JAR file name as well as the mssql-jdbc names found on maven.
