### ISSUE TITLE
WAS Liberty Profile throws NullPointerException in SRTServletRequest.getCookies

### ISSUE THREAD

**Issue by ilya-goldstein** [OpenLiberty/open-liberty#16016]
**Describe the bug**

We see an intermittent NullPointerException in SRTServletRequest.getCookies()

**Incomplete** stack trace:
```
java.lang.NullPointerException: null
	at com.ibm.ws.webcontainer.srt.SRTServletRequest$SRTServletRequestHelper.access$1300(SRTServletRequest.java:3374) ~[?:?]
	at com.ibm.ws.webcontainer.srt.SRTServletRequest.getCookies(SRTServletRequest.java:1689) ~[?:?]
	at javax.servlet.http.HttpServletRequestWrapper.getCookies(HttpServletRequestWrapper.java:108) ~[com.ibm.websphere.javaee.servlet.3.1_1.0.42.jar:?]
	at com.ibm.bi.logging.glug.support.web.P2PDRequestWrapper.getCookiesFromRequest(P2PDRequestWrapper.java:94) ~[glug-support-11.2.0-21020909.jar:11.2.0-21020909]
	at com.ibm.bi.logging.glug.support.web.P2PDRequestWrapper.getCookies(P2PDRequestWrapper.java:66) ~[glug-support-11.2.0-21020909.jar:11.2.0-21020909]
	at com.ibm.ws.jaxrs20.server.JaxRsHttpServletRequestAdapter.getCookies(JaxRsHttpServletRequestAdapter.java:683) ~[?:?]
	at javax.servlet.http.HttpServletRequestWrapper.getCookies(HttpServletRequestWrapper.java:108) ~[com.ibm.websphere.javaee.servlet.3.1_1.0.42.jar:?]
```

I can provide full stack trace via IBM Slack.

**Steps to Reproduce**
We don't have a reproducible test case. It's an intermittent bug.

**Expected behavior**
getCookies() doesn't throw NPE

**Diagnostic information:**
 - OpenLiberty Version:
WebSphere Application Server 20.0.0.7 (wlp-1.0.42.cl200720200625-0300)
 - Java Version: 
java.version = 1.8.0_231
java.runtime = Java(TM) SE Runtime Environment (8.0.6.0 - pxa6480sr6-20191107_01(SR6))

 - server.xml configuration (WITHOUT sensitive information like passwords)
can provide if needed 

 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`
n/a

**Additional context**
 - WLP runs in a docker container in an IKS cluster
 - OS: CentOS 7

**Comment by pmd1nh** [comment]
Hi,

It is possible that the app's wrapped request object (P2PDRequestWrapper) retains/caches a stale request object.  Coupling with intermittent frequency, I think that is most likely the case.

Can you set this webContainer custom property in the server.xml and try  to reproduce the issue.

    `<webContainer com.ibm.ws.webcontainer.checkrequestobjectuse="true"/>  `

You may see a log message

"ERROR: Wrong request object in use on Thread."

if the checker detects a wrong request object is used.

Can you also set the trace in the server.xml if possible?

` <logging traceSpecification="*=info=enabled:com.ibm.ws.webcontainer*=all:com.ibm.wsspi.webcontainer*=all:HTTPChannel=all:GenericBNF=all" maxFileSize="40" maxFiles="20" traceFormat="BASIC"/>
`

**Comment by ilya-goldstein** [comment]
@pmd1nh -- Thank you for your suggestions.

> Can you set this webContainer custom property in the server.xml and try to reproduce the issue.
> 
> ```
> `<webContainer com.ibm.ws.webcontainer.checkrequestobjectuse="true"/>  `
> ```

Yes. webContainer is already present in the server.xml. I'm going to add `com.ibm.ws.webcontainer.checkrequestobjectuse="true"` to the existing element.


> Can you also set the trace in the server.xml if possible?
> 
> `<logging traceSpecification="*=info=enabled:com.ibm.ws.webcontainer*=all:com.ibm.wsspi.webcontainer*=all:HTTPChannel=all:GenericBNF=all" maxFileSize="40" maxFiles="20" traceFormat="BASIC"/>`

We configure logging in `bootstrap.properties`. 

```
# redirect console.log to messages.log
com.ibm.ws.logging.console.log.level=OFF
com.ibm.ws.logging.copy.system.streams=false

# limit the messages.log to 10MB per file and max 5
com.ibm.ws.logging.max.file.size=10
com.ibm.ws.logging.max.files=5
```

What is the right syntax of traceSpecification in bootstrap.properties?

**Comment by pmd1nh** [comment]
the logging trace spec is set in the server.xml

**Comment by ilya-goldstein** [comment]
Can I set the trace spec in the server.xml while keeping the settings in bootstrap.properties?

For context:

We direct all logging to messages.log. Container startup script tails messages.log to stdout. LogDNA agents collect the logs from stdout and send them to the cloud instance of LogDNA.

**Comment by pmd1nh** [comment]
I think both setting will work.  However, our logging will write to trace.log.  

For now, we can just set the custom property and don't worry about the trace.  The "ERROR: Wrong request object in use on Thread." is independent.  Let's confirm our suspicion with the property and go from there.

**Comment by ilya-goldstein** [comment]
@pmd1nh 

I saw one NPE in the last 24 hours. The message "ERROR: Wrong request object in use on Thread." is **not** present in the logs.

Here's webContainer element pulled from a live system:
```
<webContainer
   skipMetaInfResourcesProcessing="true"
   deferServletLoad="false"
   com.ibm.ws.webcontainer.servewelcomefilefromextendeddocumentroot="true"
   invokeFilterInitAtStartup="false"
   disableXPoweredBy="true"
   displaytextwhennoerrorpagedefined="error, see logs"
   com.ibm.ws.webcontainer.checkrequestobjectuse="true"
/>
```

I will reach out to you on IBM Slack to show the full stack trace in the NPE.

**Comment by ilya-goldstein** [comment]
@pmd1nh -- You were right. This was an issue with retained request object. Synchronous thread that handled the original request was passing the request object to an asynchronous background thread. The NPE was happening in the background thread. This is the reason why the stack trace didn't show any web container frames near the top of the call chain.

I'm closing the issue. Thank you very much for your help.
