### ISSUE TITLE
Add tests for beans.xml with new XML namespace

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#16018]
The CDI-3.0 spec [updates the XML namespace of beans.xml to `https://jakarta.ee/xml/ns/jakartaee`](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#_major_changes).

We should add tests for this.

We should also check for any references to the old namespace (`http://xmlns.jcp.org/xml/ns/javaee`), schema URL or schema file in our code to check if there's anything we need to update there.

Example beans.xml from the spec:
```xml
<beans xmlns="https://jakarta.ee/xml/ns/jakartaee"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/beans_3_0.xsd"
        version="3.0">
   <alternatives>
      <class>com.acme.myfwk.InMemoryDatabase</class>
      <stereotype>com.acme.myfwk.Mock</stereotype>
      <stereotype>com.acme.site.Australian</stereotype>
   </alternatives>
</beans>
```

**Comment by tevans78** [comment]
Duplicated by #13925
