### ISSUE TITLE
MicroProfile Config 2.0 video

### ISSUE THREAD

**Issue by Joseph-Cass** [OpenLiberty/open-liberty#16022]
A video demonstrating the new features in mpConfig-2.0 may be a good idea

**Comment by Joseph-Cass** [comment]
Issue for uploading the video here: https://github.ibm.com/IBMCode/IBMCodeContent/issues/5956

**Comment by jakub-pomykala** [comment]
Closing issue as video is live [here](https://developer.ibm.com/videos/microprofile-config-2-demo/)
