### ISSUE TITLE
JWT Cache causes OOM

### ISSUE THREAD

**Issue by jdmcclur** [OpenLiberty/open-liberty#16039]
It looks like a JWT Cache was added recently. 
https://github.com/OpenLiberty/open-liberty/pull/15904/commits/0ddb504fcf048133bdb74fbbe257ec969a32f006

It helps performance, especially when using JWEs.
However, with a -Xmx256m heap size when I reach around 20,000 entries I run out of memory. It looks like the size is fixed to 50,000 entries.

Can we bring this down to a lower number and make it configurable?

**Comment by jhanders34** [comment]
#regression
