### ISSUE TITLE
Can not close response output stream at the end of dispatch forward

### ISSUE THREAD

**Issue by pmd1nh** [OpenLiberty/open-liberty#16053]
**Describe the bug** 
When the server's response is wrapped and used in the dispatch forward, the response's output stream is not closed before exiting the forward.

**Steps to Reproduce**  
Wrap the response object then dispatch forward.  Upon returning from forward, write data into the response.  These extra data after dispatch forward will be seen by the client.

**Expected behavior**  
The response's outputStream is closed before exiting dispatch forward.

**Diagnostic information:**  
- OpenLiberty: any
-- Affected feature(s) [servlet]
 
**Additional context**  
In general, there is no disruption in the flow or any exception.  Client receives normal response data.  

In a case where an application continues writing after the forward, additional data will be written into the response (since the response output stream is not closed).  In that case, these extra data are seen by the client.  This is probably the only symptom observed from the client.

**Comment by pnicolucci** [comment]
Adding this to the servlet 5.0 epic just to easily track the behavior differences for servlet-5.0

**Comment by pnicolucci** [comment]
@pmd1nh please update the description of this release bug so that it follows/conforms to the [Bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)

**Comment by pmd1nh** [comment]
updated description

**Comment by pnicolucci** [comment]
This was reverted here: https://github.com/OpenLiberty/open-liberty/pull/18965 and a new issue was opened here https://github.com/OpenLiberty/open-liberty/issues/18966 however I feel we should just add a new PR to this issue to keep everything tidy. Any questions let me know.

**Comment by pnicolucci** [comment]
Removing this issue from the Jakarta EE9 Servlet 5.0 epic as it needs to be further discussed in the Servlet community.

**Comment by pnicolucci** [comment]
`https://github.com/eclipse-ee4j/servlet-api/issues/426` : Spec Issue for discussion

**Comment by pmd1nh** [comment]
Showing up in 6.0

https://github.com/eclipse-ee4j/servlet-api/projects/3
