### ISSUE TITLE
Add tests for beta image

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#16075]
**Describe the bug**
Apparently there is no dedicated test suites running against beta images. In 21.0.0.2-beta, we found out MicroProfile Fault Tolerance feature did not work after the beta image was published. Talking with @tevans78 , some bringup tests were executed against the overall image but there is no bring up tests executed for beta images only. There is a gap and we should run some tests against beta images.

**Comment by cbridgha** [comment]
Closing this is a dup of #13643
