### ISSUE TITLE
Feature Test Summary for LG-293: Add ability for requestTiming hungRequest detection to not collect javacores

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/open-liberty#16104]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

### List of FAT projects affected

* com.ibm.ws.request.timing_fat

### Test strategy

* What functionality is new or modified by this feature?
* What are the positive and negative tests for that functionality?
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

This feature adds a new boolean Request Timing server configuration attribute (`enableThreadDumps=false`), which allows users to control whether thread dumps are created, when a hung request is detected.

The following new test cases were added, under the Test suite: HungRequestEnableThreadDumps
- **testEnableThreadDumpsNotSpecified** : Tests when the boolean "enableThreadDumps" attribute is not specified, the thread dumps should be created when the hung request is detected.
- **testThreadDumpsDisabled** : Tests when the boolean attribute "enableThreadDumps=false", the thread dumps will not be created when the hung request is detected.
- **testDynamicThreadDumpsDisable** : Tests when the boolean attribute "enableThreadDumps" is set to false dynamically, after server starts, with no attribute specified.
- **testDynamicThreadDumpsEnable** : Tests when the boolean attribute "enableThreadDumps" is set to true dynamically, after server starts with "enableThreadDumps=false".
- **testGlobalThreadDumpsDisableLocalThreadDumpsEnable** : Tests when the root requestTiming element has "enableThreadDumps=false" and the sub-element JDBC/servletTiming has "enableThreadDumps=true". The sub-element configuration should override the root element configuration, hence when a hung request is detected, thread dumps will be created.
- **testGlobalThreadDumpsEnableLocalThreadDumpsDisable** : Tests when the root requestTiming element does not have the "enableThreadDumps" attribute specified and the sub-element JDBC/servletTiming has "enableThreadDumps=false". The sub-element configuration should override the root element configuration, hence when a hung request is detected, thread dumps will not be created.
- **testInvalidEnableThreadDumpsAttributeValue** : Tests when the boolean attribute value ("enableThreadDumps=flase") is specified incorrectly in the server configuration. The default configuration will be used ("enableThreadDumps=true"), where thread dumps will be created.

In addition to the above automated test cases, the functionality was also tested manually.

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

Our confidence level is 4, we have delivered all the automated testing that covers both positive and negative test paths for this feature. We also included error scenarios, where the new attribute is specified incorrectly.

**Comment by ayoho** [comment]
Coverage looks good to me based on the functionality added 👍
