### ISSUE TITLE
BETA BLOG - Update 21001-beta forward for missing features.

### ISSUE THREAD

**Issue by jvanhill** [OpenLiberty/open-liberty#16114]
[Epic #14198]
[Epic #14014]

`NOTE: THE REASON FOR THIS ISSUE IS TO RETROACTIVELY ADD THESE FEATURES THAT WERE DELIVERED IN THE 21001 BETA TO THE 21001 BETA BLOG POST, AS WELL AS LIST IT IN THE CUMULATIVE EE9 FEATURES RELEASED TO DATE IN ALL SUBSEQUENT BETA BLOG POSTS.`

The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty. For this post to be included in the beta issue please make sure that this is completed by the end of Friday following the GM (Wednesday). 

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name (eg WebSockets feature):
- Password Utilities 1.0 
- Jakarta Connectors 2.0 Inbound Security
   
   Short feature name (eg websockets-1.0): 
- passwordUtilities-1.0
- connectorsInboundSecurity-2.0

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.
- application developer

3. Write a paragraph to summarises the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.

```The connectorsInboundSecurity-2.0 was added to provide inbound security support for the Jakarta EE 9 connectors-2.0 feature. The passwordUtilities-1.0 feature was updated to support Jakarta EE 9.```

   - What was the problem before and how does your update make their life better? (Why should they care?)
   `None of the listed features supported Jakarta EE 9.`

   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.
```
The connectorsInboundSecurity-2.0 feature must be added to server.xml when using connectors-2.0 inbound security with Jakarta EE 9. The passwordUtilities-1.0 featurs will automatically adapt to the level of Java EE or Jakarta EE that is already in use, so no change is needed when using them with Jakarta EE 9.
```   

   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?
`n/a`

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by jakub-pomykala** [comment]
https://github.com/OpenLiberty/blogs/pull/1388

**Comment by jakub-pomykala** [comment]
Now Merged into staging. Closing this issue.
