### ISSUE TITLE
Fix ee9 el-4.0 tck signature failure

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#16176]
A new annotation was added to the jakarta.el.ExpressionFactory in the Tomcat EL API:
`@ServiceConsumer(value=jakarta.el.ExpressionFactory.class)`

This causes the signature test for the class to fail as it does not match the EL Spec Reference jar.

Annotation should be removed from Liberty. 

Links:
https://github.com/eclipse-ee4j/jakartaee-tck/issues/643
https://github.com/apache/tomcat/commit/9d3896a434e35cf8e9ebf1c95a81e1fcb739866e

**Comment by jhanders34** [comment]
#regression
