### ISSUE TITLE
[Question] MicroProfile vs Quarkus/SmallRye

### ISSUE THREAD

**Issue by vvavepacket** [OpenLiberty/open-liberty#16183]
Help me understand - Is OpenLiberty implementing the MicroProfile specifications? I was using a different runtime previously like Quarkus and for me to use MicroProfile features like reactive-messaging, config, fault-tolerance, etc, I need to rely on SmallRye as an implementation of MicroProfile.

How exactly does OpenLiberty achieve the same? Is it safe to say that SmallRye is not required since OpenLiberty is like Quarkus + SmallRye?

**Comment by andymc12** [comment]
Short answer: yes. Open Liberty implements the MicroProfile specifications just like Quarkus or Wildfly, etc.

Open Liberty also implements the Jakarta EE (formerly Java EE) specifications, so one nice thing that you can do with Liberty is mix and match technologies from both.  For example, you could use MP features like config and fault-tolerance with Jakarta features like JPA and BeanValidation and JAX-RS (which is also part of MP...).  

>How exactly does OpenLiberty achieve the same?

Liberty does this via "features" in the server config.  So if you wanted the feature I mentioned above, you would configure your server like this:
```
<featureManager>
  <feature>jaxrs-2.1</feature>
  <feature>jpa-2.2</feature>
  <feature>beanValidation-2.0</feature>
  <feature>mpConfig-1.4</feature>
  <feature>mpFaultTolerance-2.1</feature>
</featureManager>
```

> Is it safe to say that SmallRye is not required since OpenLiberty is like Quarkus + SmallRye?

Yes and no.   Yes, in that Open Liberty provides the implementation. No, in that Liberty uses some SmallRye implementations under the covers (ex: SmallRye GraphQL).  So, your pom.xml (assuming you're using Maven) would need to depend on the MP APIs that you want, but the scope should be "provided" to avoid packaging them in your app.  

If you want to get started with Liberty quickly, I'd suggest looking through the guides at: https://openliberty.io/guides/

Hope this helps!

**Comment by vvavepacket** [comment]
@andymc12 Really helps!! Closing this ticket!
