### ISSUE TITLE
Bval20: SVT testing

### ISSUE THREAD

**Issue by nmittles** [OpenLiberty/open-liberty#162]
"As a SVT tester, I want to include Bean Validation 2.0 function in my test applications"

Work with the SVT team to integrate new Bean Validation 2.0 function into their test scenarios. One of the main concerns here is performing some long running scenarios to flesh out any memory/performance problems similar to what was done for bval 1.1.

**Comment by njr-11** [comment]
Closing as duplicate because it is covered by the SVT team
