### ISSUE TITLE
LDAP connection support Kerberos authentication 

### ISSUE THREAD

**Issue by utle** [OpenLiberty/open-liberty#16204]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty. For this post to be included in the beta issue please make sure that this is completed by the end of Friday following the GM (Wednesday). 

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

Feature issue: #12794

1. Which Liberty feature(s) does your update relate to? LdapRegistry
    
   Human-readable name (eg WebSockets feature): LDAP User Registry 
   
   Short feature name (eg websockets-1.0): ldapRegistry-3.0

2. Who is the target persona? Who do you expect to use the update? Operations teams with LDAP servers that support Kerberos binding (provide a  Key Distribution Center (KDC)) and would prefer to using the new LDAP User Registry bind option (GSSAPI/Kerberos) over the current options (none or simple bind).

3. Write a paragraph to summarises the update, including the following points:
   
LDAP Bind operations are used to authenticate clients (and the users or applications behind them) to the directory server, to establish an authorization identity that will be used for subsequent operations processed on that connection, and to specify the LDAP protocol version that the client will use. Prior to this update, LDAP binds anonymously  or with a bindDN user and  a bindPassword (simple authentication) were supported. This update adds a new option to bind to LDAP: GSSAPI/Kerberos. Kerberos is an authentication mechanism that allows a client and service to mutually authenticate via a Key Distribution Center (KDC). Using a Kerberos credential cache (ccache) or a Kerberos keytab file are both supported.

To update an LdapRegistry from using no bind credentials or using a bindDN and password to using the GSSAPI/Kerberos option, you will need to set the bind authentication mechanism type using the new LdapRegistry attribute, `bindAuthMechanism`: `bindAuthMechanism="GSSAPI"`. You will also need the Kerberos principal or Service Principal Name: `krb5Principal="user1@EXAMPLE.COM"`

If you are using a Kerberos credential cache (ticket cache or ccache) to store the Kerberos credentials, add the ticket cache file name to the LdapRegistry with the new attribute `krb5TicketCache`: `krb5TicketCache="${server.config.dir}/security/krb5-user1.cc" `

If you are using a custom Kerberos configuration file (krb.conf or krb.ini), set the file name using the global Kerberos configuration element:
```
<kerberos configFile="${server.config.dir}/security/krb5.conf"/>
```

If you are using a Kerberos keytab file to store encrypted keys for principals, set the file using the global Kerberos configuration element
```
<kerberos keytab="${server.config.dir}/security/krb5.keytab" configFile="${server.config.dir}/security/krb5.conf"/>
```

If the Kerberos configuration file is not defined, Open Liberty will attempt to resolve using the JDK default locations and the OS default locations.

For the Kerberos credentials, the locations are checked in the following order: the ticket cache (if provided), the configured keytab file, the JDK default location.

LdapRegistry example, using a ticket cache and custom Kerberos config file:

```
<kerberos keytab= configFile="${server.config.dir}/security/krb5.conf"/>

<ldapRegistry id="LDAP" realm="SampleLdapADRealm" host="ldap_hostname" port="389" ignoreCase="true"  baseDN="DC=example,DC=com" bindAuthMechanism="GSSAPI" krb5Principal="user1@EXAMPLE.COM" krb5TicketCache="${server.config.dir}/security/krb5-user1.cc" ldapType="Custom"  />
```

LdapRegistry example, using a keytab and custom Kerberos config file:

```
<kerberos keytab= configFile="${server.config.dir}/security/krb5.conf"/>

<ldapRegistry id="LDAP" realm="SampleLdapADRealm" host="ldap_hostname" port="389" ignoreCase="true"  baseDN="DC=example,DC=com" bindAuthMechanism="GSSAPI" krb5Principal="user1@EXAMPLE.COM" ldapType="Custom"  />
```

More information on [LdapRegistry](https://openliberty.io/docs/latest/reference/feature/ldapRegistry-3.0.html).

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by jakub-pomykala** [comment]
Closing as live in [21.0.0.4-beta](https://openliberty.io/blog/2021/03/22/ldap-kerberos-21004beta.html)
