### ISSUE TITLE
Pull in MicroProfile JWT API jars from maven

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#1621]
Currently the source files obtained from MP git repo was check into Open Liberty. This is error prone. The source files in the project com.ibm.websphere.org.eclipse.microprofile.jwt.1.0 should be removed and the api jar should be downloaded from maven and uploaded to artifactory.

**Comment by brutif** [comment]
#1650

**Comment by brutif** [comment]
resolved on pull 1650
