### ISSUE TITLE
Configurable enumerated option list with fill-in-the-blank

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#16220]
There are a number of scenarios that we have come across where a configuration attribute is open-ended but has a subset of well-known, recommended (often spec-defined) values, or where a configuration attribute has some discouraged or deprecated values that we would prefer not to present to users.

An example of the former is the JDBC transaction isolation level, where the JDBC spec defines some values, but some JDBC vendors add their own vendor-specific extensions,

```
  <AD id="isolationLevel" type="String" ...>
   <Option value="TRANSACTION_READ_UNCOMMITTED" .../>
   <Option value="TRANSACTION_READ_COMMITTED" .../>
   <Option value="TRANSACTION_REPEATABLE_READ" .../>
   <Option value="TRANSACTION_SERIALIZABLE" .../>
   <Option value="TRANSACTION_SNAPSHOT" .../> <!-- vendor-defined extension for SQL Server -->
```

In the above, we hard-coded the vendor extension into our metatype, which works for the particular JDBC driver that it pertains to (once we got it added), but if a different JDBC vendor has an extension here, the user is currently prevented from configuring it.

An example of the latter scenario is what the PostgreSQL driver did with their `targetServerType` config attribute, where they add 3 new options, identical in meaning to 3 of the old (and now deprecated) options, continuing to honor both,

```
  <AD id="targetServerType" ... type="String">
   <Option value="any"             label="any"/>
   <Option value="primary"         label="primary"/>
   <Option value="secondary"       label="secondary"/>
   <Option value="preferSecondary" label="preferSecondary"/>
   <!-- Deprecated, but still permitted, by PostgreSQL JDBC Driver: -->
   <Option value="master"          label="master"/>
   <Option value="slave"           label="slave"/>
   <Option value="preferSlave"     label="preferSlave"/>
  </AD>
  ```
  
If we don't want to show the 3 deprecated options, but continue to let the user configure them, while keeping the 4 favored options in our schema for usability, then we would need an extension to metatype/schema/tooling to enable this.

Proposal 3 of design issue #16122 covers this as follows:

Introduce a custom type for config options that enumerates valid types but otherwise allows any value, in which case we could omit all of the deprecated values from explicitly showing up, while still permitting them, and a customer could add any vendor-specific options for direct pass-though to the driver,

```
  <AD id="myConfigAttribute" ... type="String" ibm:type="option+">
   <Option value="MyFirstOption"   label="..."/>
   <Option value="MySecondOption"  label="..."/>
   <Option value="MyThirdOption"   label="..."/>
  </AD>
```

This could be represented in schema as a union of string and the enum.

**Comment by cbridgha** [comment]
After evaluating the relative priorities and constraints this item is not likely to complete in next 2 years, we are going to close for now - we can revisit if needed.
