### ISSUE TITLE
CWWKG0081E always includes default value for boolean attribute even when none specified

### ISSUE THREAD

**Issue by SueBayliss** [OpenLiberty/open-liberty#16233]
**Describe the bug**
If the AD definition in a metatype.xml file for a boolean attribute does not set a default value, then when evaluating that attribute which has been specified with an invalid value in server.xml, the CWWKG0075E message includes "**The default value of false will be used.**" which is misleading.

**Steps to Reproduce**
We intentionally define a boolean attribute without a default value, because at runtime if the value is not specified on this particular element, we want to use the value of the attribute specified on a different element (we have a hierarchical precedence of where an attribute can be set and at what scope it applies).  

For example:
```
    <OCD id="com.ibm.zosconnect.apirequesters.metatype" ibm:alias="apiRequesters" name="%apiRequesters.name" description="%apiRequesters.desc">
        <AD id="requireAuth" required="false" type="Boolean" name="%requireAuth.apirs.name" description="%requireAuth.apirs.desc"/>
        ...
    </OCD>
```

If server.xml is configured with: `<zosconnect_apiRequesters requireAuth="invalid">` then the following error message is issued:
CWWKG0075E: The value invalid is not valid for attribute requireAuth of configuration element zosconnect_apiRequesters. The validation message was: CWWKG0081E: The value invalid for boolean attribute requireAuth is invalid. Valid values are "true" and "false". The default value of false will be used.

This is misleading, because the default value of false is not always correct. The value specified on the more global element takes effect and that defaults to true.

**Expected behavior**
The CWWKG0081E message, which is used as an insert to message CWWKG0075E, should only include the text "The default value of <defaultValue> will be used.", if a default value is specified for that attribute in the metatype.xml AD definition.

**Diagnostic information:**
 - OpenLiberty Version: 21.0.0.1
 - Java Version: (Using openLiberty code included in Liberty for zOS) Java(TM) SE Runtime Environment (8.0.6.11 - pmz6480sr6fp11-20200602_01(SR6 FP11))
 - server.xml configuration:
```
 <?xml version="1.0" encoding="UTF-8"?>
<server description="zCEE server for API requester">
	<featureManager>
		<feature>zosconnect:apiRequester-1.0</feature>
	</featureManager>
	<zosconnect_zosConnectManager requireAuth="true" />
	<zosconnect_apiRequesters requireAuth="invalid" />
</server>
```
 - messages.log file messages:
[3/15/21 10:37:02:576 GMT] 00000020 com.ibm.ws.config.xml.internal.ConfigRefresher               A CWWKG0016I: Starting server configuration update.
[3/15/21 10:37:02:653 GMT] 00000020 com.ibm.ws.config.xml.internal.ConfigUpdater                 E CWWKG0075E: The value invalid is not valid for attribute requireAuth of configuration element zosconnect_zosConnectAPIs. The validation message was: CWWKG0081E: The value invalid for boolean attribute requireAuth is invalid. Valid values are "true" and "false". The default value of false will be used..
[3/15/21 10:37:02:704 GMT] 000003e4 com.ibm.ws.config.xml.internal.ConfigRefresher               A CWWKG0017I: The server configuration was successfully updated in 0.127 seconds.

**Additional context**
Looking at openLiberty source code:

- com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages.nlsprops defines the messages:

   - error.attribute.validation.exception=CWWKG0075E: The value {2} is not valid for attribute {1} of configuration element {0}. The validation message was: **{3}**.
   - error.invalid.boolean.attribute=CWWKG0081E: The value {0} for boolean attribute {1} is invalid. Valid values are "true" and "false". **The default value of {2} will be used.**

So error.invalid.boolean.attribute=CWWKG0081E message assumes there will always be a default for a boolean!

- The AttributeValidationException and associated exception messageis thrown by com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigEvaluator.java method processString:

   - The insert {2} for error.invalid.boolean.attribute=CWWKG0081E message  is always initialized to "**false**", with comment "// "false" is the default default), and then overwritten with the actual default value if one is defined in the attribute description. So this logic does know whether there is a default value defined for the attribute.

   - This exception is caught by by com.ibm.ws.config/src/com/ibm/ws/config/xml/internal/ConfigUpdater.java method. Which then issues the CWWKG0075E message, where e.getMessage() is used as insert {3} in the message.

**Comment by brenthdaniel** [comment]
Effectively, the default value for a boolean metatype attribute will always be `false` because `Boolean.valueOf(null)` will return `false`.

**Comment by SueBayliss** [comment]
@brenthdaniel Hi Brent, Thanks for response.
Our confusion is that configuration error message says default is false, So systems admin reading message thinks this is the case.  But no (default) value is set for the attribute in the properties map passed to the class configured to process the element. 
i.e.  In the class with `@Component` annotation where configurationPid matches the metatype OCD id value for the element,  its `modified(ComponentContext cc, Map<String, Object> properties)  `method, can choose to check whether properties.get("requireAuth") is null, and if so perform logic to set the boolen value based on some alternative internal information, which may result in value being set to true.

Maybe this is an unusual use case?
FYI: Our aim is for customers to be able to configure an attribute (e.g. requireAuth) at various scopes, e.g. Either globally for all resources in the server, or for all resources of a specific type (e.g. all apiRequesters) in the server or for a specific resource of that type (e.g. an apiRequester). Where the global value has a default, but there is a precedence that if configured, specific resource overrides all resources of that type, which in turn overrides the global value. So we only want to set a default at the global scope (as value to be used if not configured anywhere else).

**Comment by SueBayliss** [comment]
@brenthdaniel Hi Brent,
Thanks for the information. We understand that most people will want a default for a boolean, and that would usually be false.
We're happy to close this issue, can you do that for us please.
