### ISSUE TITLE
BETA BLOG - Build multipart payloads for your JAX-RS client and services

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#16249]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty. For this post to be included in the beta issue please make sure that this is completed by the end of Friday following the GM (Wednesday). 

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to? #16031 
    
   Human-readable name (eg WebSockets feature): **JAX-RS / aka Jakarta RESTful Web Services**
   
   Short feature name (eg websockets-1.0): **jaxrs-2.0 / jaxrs-2.1 / restfulWS-3.0 (beta only)**

2. Who is the target persona? Who do you expect to use the update? **application developer**

3. Write a paragraph to summarises the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.

> Often, a RESTful service or client will need to send multiple disparate pieces of data in the same request, for example uploading a resume/CV with a picture, and text for name and address. This is usually done using `multipart/form-data`. 

   - What was the problem before and how does your update make their life better? (Why should they care?)
 
> While Liberty currently has APIs to enable users to _receive_ multipart/form-data payloads, it does not have any APIs to enable _send_ multipart payloads - until now. With the new `AttachmentBuilder` API, users can now send multipart requests from their JAX-RS clients or send multipart payloads as responses from their JAX-RS resources.

   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.

> To send a multipart request, you will need to enable the `jaxrs-2.0` or `jaxrs-2.1` feature. Presumably, if you are already using JAX-RS, one of these features is already enabled. To send a multipart payload, you must send an instance of `List<IAttachment>`.  Each object in that list represents a single attachment part.  Here is an example of creating and sending a multipart request from a JAX-RS client:
```
List<IAttachment> attachments = new ArrayList<>();

attachments.add(AttachmentBuilder.newBuilder("blogPost")
                                 .inputStream(new FileInputStream("/path/to/yesterdaysBlogPost.xml"))
                                 .fileName("myRenamedBlogPost.asciidoc")
                                 .contentType("text/asciidoc")
                                 .contentId("myBlogPostID")
                                 .header("X-PriorityLevel", "Medium")
                                 .build());

attachments.add(AttachmentBuilder.newBuilder("file1")
                                 .inputStream("some.xml", new FileInputStream("/path/to/myPicture.png"))
                                 .contentType("image/png")
                                 .build());

attachments.add(AttachmentBuilder.newBuilder("authorName")
                                 .inputStream(new ByteArrayInputStream("John Doe".getBytes()))
                                 .build());

Response response = client.target(BLOG_SITE_URI)
                          .request()
                          .post(Entity.entity(attachments, MediaType.MULTIPART_FORM_DATA));
``` 
   
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?
> [multipart/form-data RFC 7578](https://tools.ietf.org/html/rfc7578)
> Javadocs should be posted at some point... I'll plan to update this once I have a URL.

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by jakub-pomykala** [comment]
Blog now in prod - closing.
