### ISSUE TITLE
Nullpointer exception during authorization using OidcLogic

### ISSUE THREAD

**Issue by pa1pandey** [OpenLiberty/open-liberty#16282]
Exact Error:
2021-03-17T16:35:08.566866580Z [ERROR   ] CWWKS9109E: An unexpected exception occurred during Trust Association. The exception is java.lang.NullPointerException
2021-03-17T16:35:08.569872735Z 	at com.ibm.ws.security.openidconnect.clients.common.OidcClientHttpUtil.getSSLSocketFactory(OidcClientHttpUtil.java:66)

Tags using in server.xml
<sslDefault sslRef="customizeSSLConfig" />
	<ssl id="customizeSSLConfig" 
		trustStoreRef="serverTrustStore" />
	<keyStore id="serverTrustStore"
		location="path/trusstore.jks"
		password="somepassword" type="JKS" />
	
        <oidcLogin
        id="liberty-aad-oidc-abc" clientId="ABCD"
        clientSecret="vsffsfsffsdfsdfsfsfsfsfsffs"
        signatureAlgorithm="RS256" 
        authorizationEndpoint="pingurl/as/authorization.oauth2"
        redirectToRPHostAndPort="https://host:9449"
        scope="openid roles profile department email"
        tokenEndpoint="pingurl/as/token.oauth2"
        userInfoEndpointEnabled="true"
        userInfoEndpoint="ping url/idp/userinfo.openid"
        sslRef="customizeSSLConfig"
        />

When the auth url is hit it redirects correctly to ping login page and after entering creds and submitting request it fails to authorize with above mentioned error in log.

[ffdc_log.zip](https://github.com/OpenLiberty/open-liberty/files/6163723/ffdc_log.zip)

**Comment by teddyjtorres** [comment]
Hi. Please confirm is there is an ssl element named customizeSSLConfig and there is either an ssl-1.0 or transportSecurity-1.0 feature configured in the server.xml. Thanks.

**Comment by pa1pandey** [comment]
that's correct! following features are added in server.xml
                `<feature>transportSecurity-1.0</feature>
		<feature>ssl-1.0</feature>
		<feature>socialLogin-1.0</feature>`
