### ISSUE TITLE
Produce error if internal configuration is used in server.xml

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#16318]
Similar to issue #14081

In #14081 it was decided to look at producing an error message if a beta configuration type is used with a non-beta Liberty installation.  Should the same thing be considered for internal configuration types?

It is very likely that bundles included in liberty contain defaults that use internal configuration types though and these must not cause an error.  This design issue is to discuss if this is necessary or if we should continue to allow use of internal configuration without error.

**Comment by tjwatson** [comment]
Agreement on design call was to fold the solution of this issue into the solution for  design issue #14081

If a message is to be produced it should behave similar or be the same as the message for the beta attribute usage.  In both cases the error message would be logged but the config would be passed through the same as it is today.  For internal attributes we will need to differentiate configuration included in default instances included in feature bundles vs. the config set by the user.  Only configuration set by the user should produce the error message.

Leaving this issue open for discussion again in two weeks.

**Comment by cbridgha** [comment]
Merged this issue into: https://github.com/OpenLiberty/open-liberty/issues/14081
