### ISSUE TITLE
JavaDoc missing for CDIExtensionMetadata

### ISSUE THREAD

**Issue by SoftlySplinter** [OpenLiberty/open-liberty#16335]
**Describe the bug**
The SPI bundle `com.ibm.websphere.appserver.spi.cdi` can be found in the `dev/spi/ibm` directory, but has no corresponding JavaDoc ZIP file in the `dev/spi/ibm/javadoc` directory.

This only really affects the class `io.openliberty.cdi.spi.CDIExtensionMetadata`.

**Steps to Reproduce**
List the directory contents for `dev/spi/ibm/javadoc`

**Expected behavior**
There is a JavaDoc ZIP file `dev/spi/ibm/javadoc/com.ibm.websphere.appserver.spi.cdi_<version>-javadoc.zip`

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.12
 
**Additional context**
None

**Comment by benjamin-confino** [comment]
This should be fixed by #15541 however we are discussing the possibility of adding a second  javadoc zip for the jakarta transformed code.

**Comment by benjamin-confino** [comment]
jakarta transformed javadoc can now be found in wlp/dev/spi/ibm/javadoc/io.openliberty.cdi.spi_1.1-javadoc.zip
