### ISSUE TITLE
Feature Test Summary - JDBC SSL/TLS Testing Scenarios

### ISSUE THREAD

**Issue by KyleAure** [OpenLiberty/open-liberty#16421]
### List of FAT projects affected

* com.ibm.ws.jdbc_fat_db2
* com.ibm.ws.jdbc_fat_oracle
* com.ibm.ws.jdbc_fat_postgresql
* com.ibm.ws.jdbc_fat_sqlserver

### Test strategy

* What functionality is new or modified by this feature?
  * There is no new functionality to WebSphere for this epic.  SSL/TLS connection support is not part of the JDBC specification so each JDBC database driver has it's own implementation and support for establishing TLS connections. 
* What are the positive and negative tests for that functionality?
  * DB2: testDB2SecureConnection: establishes a secure connection to a DB2 database running in a docker environment that has TLSv1.2 enabled.  properties.db2.jcc sslConnection="true". Uses ssl-1.0 keystore element as a key/trust store
  * Oracle: testSimpleConnection: establishes an unsecure connection to an Oracle database running in a docker environment that has TLSv1.2 enabled on a different port. 
  * Oracle: testOracleWallet: establishes a secure connection to an Oracle database running in a docker environment that has TLSv1.2 enabled, and uses a successful TLS handshake to authenticate the user. Uses OracleWallet as a key/trust store.
  * Postgres: testSSLNonValidating: establishes a secure connection to a Postgres database running in a docker environment that has TLSv1.2 enabled. Uses native PostgreSQL driver properties to configure key/trust store.
  * Postgres: testSSLBasic: establishes a secure connection to a Postgres database running in a docker environment that has TLSv1.2 enabled. Uses ssl-1.0 keystore element as a key/trust store.
  * SQLServer: testDatasourceWithSSL: establishes a secure connection to a SQLServer database running in a docker environment that has TLSv1.2 enabled.  properties.microsoft.sqlserver encrypt="true". Establishes trust based on protocol alone, no key/trust store. 
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)
  * Manual testing done for Traditional WebSphere to ensure that the same properties / config work in both. 
  * Internal link to repo: https://github.ibm.com/websphere/was-ssl-sample

## Confidence Level

Team vote results (hosted outside of GitHub)

4  (unanimous)

**Comment by ayoho** [comment]
LGTM 👍
