### ISSUE TITLE
Ambiguous dependencies for type JobContext with apache batchee java batch

### ISSUE THREAD

**Issue by agtadadik** [OpenLiberty/open-liberty#16537]
**Describe the bug**
I have an EAR application which is using apache batchee as java batch implementation. It includes dependency of batchee-jbatch and batchee-cdi. I deployed this application on openliberty version 21.0.0.3 with javaee-7.0 as feature in server.xml

Below exception is thrown during application startup.
org.jboss.weld.exceptions.DeploymentException: WELD-001409: Ambiguous dependencies for type JobContext with qualifiers @Default
  at injection point [BackedAnnotatedField] ...
  Possible dependencies: 
  - Producer Method [JobContext] with qualifiers [@Any @Default] declared as [[UnbackedAnnotatedMethod] @Produces public org.apache.batchee.container.cdi.BatchProducerBean.getJobContext()],
  - Producer Method [JobContext] with qualifiers [@Any @Default] declared as [[UnbackedAnnotatedMethod] @Produces @Dependent public com.ibm.ws.jbatch.cdi.BatchProducerBean.getJobContext()]
	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:370)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:284)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:137)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:158)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:501)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:61)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:59)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at com.ibm.ws.threading.internal.PolicyTaskFutureImpl.run(PolicyTaskFutureImpl.java:714)
	at com.ibm.ws.threading.internal.PolicyExecutorImpl.runTask(PolicyExecutorImpl.java:1158)
	at com.ibm.ws.threading.internal.PolicyExecutorImpl$GlobalPoolTask.run(PolicyExecutorImpl.java:190)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Diagnostic information:**
 - OpenLiberty Version: 21.0.0.3
 - Java Version: 1.8.0_221

**Additional context**
I tried adding -Dcom.ibm.ws.jbatch.disable=true in jvm.options file (at \liberty\wlp\usr\shared). But this has no effect. 

Is apache batchee application supported on open liberty?

**Comment by scottkurz** [comment]
No, the `-Dcom.ibm.ws.jbatch.disable=true` option only disables the WebSphere batch impl in traditional WebSphere, but not Open Liberty.   

I wonder if there's a way to package the batch API in the app and run without the batch feature activated.   Will look into this.

**Comment by scottkurz** [comment]
@agtadadik  

I can describe a way to run with batchee-jbatch, batchee-cdi in Open Liberty, but by using batchee-cdi, I wonder if you're still going to run into trouble with other integration with CDI and runtime-managed features.

But just focusing on batch, you can bypass the Open Liberty batch impl and use batchee by:

1. disabling the batch, cdi features in server.xml
2. packaging the batch-api within your application

### 1. server.xml

```xml
<server>
    <featureManager>
        <!-- Don't use the aggregate feature and don't use batch or cdi 
        <feature>cdi-2.0</feature>
        <feature>batch-1.0</feature>
        <feature>javaee-7.0</feature>
        -->
        <!--  Just use the other features you want to use -->
        <feature>servlet-3.1</feature>
        <feature>jaxrs-2.0</feature>
        <feature>appSecurity-2.0</feature>
    </featureManager>
```

### 2. pom.xml

Package the batch+inject APIs within the app (use default **compile** scope not **provided**)  along with the batchee dependencies.

```xml
    <dependencies>
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-web-api</artifactId>
            <version>8.0.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.batch</groupId>
            <artifactId>jakarta.batch-api</artifactId>
            <version>1.0.2</version>
        </dependency>      
        <dependency>
            <groupId>org.apache.batchee</groupId>
            <artifactId>batchee-jbatch</artifactId>
            <version>0.6</version>
        </dependency>
        <dependency>
            <groupId>org.apache.batchee</groupId>
            <artifactId>batchee-cdi</artifactId>
            <version>0.6</version>
        </dependency>
        <dependency>
            <groupId>jakarta.inject</groupId>
            <artifactId>jakarta.inject-api</artifactId>
            <version>1.0.1</version>
        </dependency>
    </dependencies>
```

As I mentioned upfront though, I wonder if using batchee-cdi is going to work if you require CDI integrated with other server features.    

If you do hit a problem with this approach, let us know.   Also, it could be helpful for us to understand more details on the motivation of why you are using this approach, to try to best help.

**Comment by scottkurz** [comment]
I'm going to close this for now but feel free to re-open if you'd like.
