### ISSUE TITLE
Single Sign-On (SSO) LTPA and JWT support authentication filter

### ISSUE THREAD

**Issue by utle** [OpenLiberty/open-liberty#16552]
Please provide the following information the week before the GA date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   SSO LTPA:
      - Application Security: appSecurity-1.0, appSecurity-2.0, appSecurity-3.0 and appSecurity-4.0    
  
  SSO JWT:
      - JSON Web Token :  jwtSso-1.0

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.
Administrator and application developer.

3. Write a paragraph to summarises the update, including the following points:  
   Customer can use the authentication filter to filter out which HTTP servlet request to use LTPA  and JWT or not  for SSO authentication.  See the authentication filter article for more information.

**Comment by jakub-pomykala** [comment]
Blog now in prod - closing.
