### ISSUE TITLE
GA BLOG - LDAP connection supports Kerberos authentication

### ISSUE THREAD

**Issue by kristip17** [OpenLiberty/open-liberty#16583]
If you have previously provided this information for an Open Liberty beta blog post and nothing has changed since the beta, just provide a link to the published beta blog post and we'll take the information from there.

Beta blog -- https://github.com/OpenLiberty/open-liberty/issues/16204

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the GA release blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the GA blog post).

**Comment by jakub-pomykala** [comment]
Closing as live in [21.0.0.4](https://openliberty.io/blog/2021/04/16/mp-context-propagration-21004.html)

**Comment by utle** [comment]
It's beta in 21.0.0.4 and GA in 21.0.0.5 so I think we still need to update the 21.0.0.5 GA BLOG, right?

**Comment by austin0** [comment]
Blog is live: https://openliberty.io/blog/2021/05/14/ldap-multipart-21005.html

Closing.
