### ISSUE TITLE
Bval20: Create Open Liberty guide

### ISSUE THREAD

**Issue by nmittles** [OpenLiberty/open-liberty#166]
Write an Open Liberty guide for Bean Validation 2.0.

**Comment by NottyCode** [comment]
Hey, we have been tracking the guide work over in the guides-common, so I raised an issue for this over there as [Issue 8](https://github.com/OpenLiberty/guides-common/issues/8).

I'd suggest closing this one, but wasn't sure if you wanted to track this work here for your convenience.

**Comment by nmittles** [comment]
Keeping this story for team sizing/velocity tracking purposes.  It is technically a duplicate of:
https://github.com/OpenLiberty/guides-common/issues/8

We will work/close both issues at the same time.

**Comment by alexsm82** [comment]
Closing since this work will be tracked in the guides repo under https://github.com/OpenLiberty/guides-common/issues/8.
