### ISSUE TITLE
Allow JDBC and other libraries in application

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#1661]
Users should be able to include JDBC driver JARs and other binaries (Cloudant/Couch/Mongo libraries) within their application, and configure server-defined and application-defined resources (@DataSourceDefinition) without needing to otherwise specify/configure libraries.

**Comment by aguibert** [comment]
Cancelling this epic because this use case is better solved by the recent enhancements to the Liberty Maven plugin here:
https://github.com/OpenLiberty/ci.maven/issues/705
