### ISSUE TITLE
Create layer that calls into criu library via gRPC

### ISSUE THREAD

**Issue by dettmoney** [OpenLiberty/open-liberty#16621]
Currently we are using a method to call into criu via jni with the library found here: https://github.com/chflood/JavaCriuJar.

If we can replace this dependence with gRPC calls we can eliminate the dependence on C code and help the user experience.

Here's the criu repo: https://github.com/checkpoint-restore/criu
Some more info on how to call out to criu using gRPC: https://criu.org/RPC

**Comment by tjwatson** [comment]
This is part of #16384

**Comment by tjwatson** [comment]
We plan to use Open J9 to call criu.  We have no need to investigate this gRPC solution anymore.
