### ISSUE TITLE
JakartaEE: PackageRename: Make adminCenter-1.0 work with Jakarta EE 9

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/open-liberty#16640]
I believe the bulk of the work here is transforming the com.ibm.ws.ui bundle and update the feature to have appropriate private features that bring in the right bundle depending on if using Java EE 6 / 7 / 8 or if using Jakarta EE 9.  Additionally there will need to be test updates to do repeats with Jakarta EE 9 features in order to get FAT approval for the feature.

**Comment by malincoln** [comment]
Discussed with Katie and she confirmed it can be closed.
