### ISSUE TITLE
Jakarta EE 9: PackageRename: Make batchManager work with Jakarta EE 9

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/open-liberty#16646]
Either we need to have batchManager-1.0 be able to handle EE 7, 8 and 9 like we do with the other value add feature or we need to make a new batchManager-2.0.  The batchManager script is the tricky part, but no matter what we do, either option will work, but I think we will likely need to have a batchManager2 script file unless we come up with a more sophisticated solution.  Additionally FAT updates would need to be made to test this out accordingly.

**Comment by malincoln** [comment]
@scottkurz @cgianfra pls close if there's no remaining tasks. Thanks
