### ISSUE TITLE
jdbcDriver optional for dataSource

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#1664]
"As a user of Liberty, I want to omit the jdbcDriverRef from dataSource config and include JDBC JARs within my application, so that my application can be a single binary which is everything I need to deploy."

**Comment by njr-11** [comment]
Feature was canceled. Can be reopened if necessary.

**Comment by mikekuzak** [comment]
Is this possible now on 22.0.0.6 ? We have the exact same use case.

**Comment by njr-11** [comment]
> Is this possible now on 22.0.0.6 ? We have the exact same use case.

No, the feature was put on hold and later deprioritized and canceled in favor of other items that were higher priority at the time.  You can open a [new issue](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=) to request it again if you like.
