### ISSUE TITLE
microprofile-config.properties is not loaded in OASFilter

### ISSUE THREAD

**Issue by srnjak** [OpenLiberty/open-liberty#16661]
I upgraded to OpenLiberty 21.0.0.4, because I wanted to start using Microprofile 4.0.

It seems that bug described and fixed in https://github.com/OpenLiberty/open-liberty/issues/9204 is present again.

**Comment by Azquelt** [comment]
Hi, thanks for reporting this, I'm sorry we missed it when we released mpOpenApi-2.0. The fix has now been merged (with a test so we shouldn't miss it again) and I'll let you know when it's available in a nightly Open Liberty build.

**Comment by Azquelt** [comment]
The fix is available in Open Liberty nightly builds from `2021-04-23, 11:00` onwards (available from https://openliberty.io/downloads/#development_builds )
