### ISSUE TITLE
microprofile.faulttolerance.metrics.fat.tests.CDIFallbackTest Access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#1667]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_ahvW0Ps0EeefH4uRV76YPQ&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider

com.ibm.ws.fat.util.browser.WebBrowserException: The body of Web Browser 1 Response 1 does not contain: SUCCESS - Response body: ERROR: Caught exception attempting to call test method testFallback on servlet com.ibm.websphere.microprofile.faulttolerance.metrics.app.FallbackServlet java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "accessDeclaredMembers") 	at java.security.AccessController.throwACE(AccessController.java:157) 	at java.security.AccessController.checkPermissionHelper(AccessController.java:217) 	at java.security.AccessController.checkPermission(AccessController.java:349) 	at java.lang.SecurityManager.checkPermission(SecurityManager.java:562) 	at java.lang.Class.checkMemberAccess(Class.java:200) 	at java.lang.Class.getDeclaredMethods(Class.java:992) 	at io.astefanutti.metrics.cdi.MetricsInterceptor.metrics(MetricsInterceptor.java:83) 	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73) 	at org.jboss.weld.interceptor.proxy.WeldInvocationContext.invokeNext(WeldInvocationContext.java:83) 	at org.jboss.weld.interceptor.proxy.WeldInvocationContext.proceed(WeldInvocationContext.java:115) 	at org.jboss.weld.injection.producer.ConstructorInterceptionInstantiator$1.aroundConstruct(ConstructorInterceptionInstantiator.java:100) 	at org.jboss.weld.injection.ConstructorInjectionPoint.invokeAroundConstructCallback(ConstructorInjectionPoint.java:109) 	at org.jboss.weld.injection.ConstructorInjectionPoint.invokeAroundConstructCallbacks(ConstructorInjectionPoint.java:95) 	at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:78) 	at org.jboss.weld.injection.producer.AbstractInstantiator.newInstance(AbstractInstantiator.java:28) 	at org.jboss.weld.injection.producer.InterceptorApplyingInstantiator.newInstance(InterceptorApplyingInstantiator.java:62) 	at org.jboss.weld.injection.producer.ConstructorInterceptionInstantiator.newInstance(ConstructorInterceptionInstantiator.java:66) 	at org.jboss.weld.injection.producer.BasicInjectionTarget.produce(BasicInjectionTarget.java:112) 	at org.jboss.weld.injection.producer.BeanInjectionTarget.produce(BeanInjectionTarget.java:186) 	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:158) 	at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96) 	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100) 	at org.jboss.weld.bean.ContextualInstanceStrategy$CachingContextualInstanceStrategy.get(ContextualInstanceStrategy.java:177) 	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50) 	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:99) 	at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:125) 	at com.ibm.websphere.microprofile.faulttolerance.metrics.app.beans.FallbackBean$Proxy$_$$_WeldClientProxy.connectA(Unknown Source) 	at com.ibm.websphere.microprofile.faulttolerance.metrics.app.FallbackServlet.testFallback(FallbackServlet.java:44) 	at componenttest.app.FATServlet.doGet(FATServlet.java:67) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255) 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743) 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:440) 	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1154) 	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4962) 	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314) 	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:995) 	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279) 	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1009) 	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:412) 	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:371) 	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:530) 	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:464) 	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:329) 	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:300) 	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:165) 	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:74) 	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:501) 	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:571) 	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:926) 	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1015) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 	at java.lang.Thread.run(Thread.java:785)  	at com.ibm.ws.fat.util.browser.WebResponse.verifyResponseBody(WebResponse.java:880) 	at com.ibm.ws.fat.util.browser.WebResponse.verifyResponseBodyContains(WebResponse.java:837) 	at com.ibm.ws.fat.util.SharedServer.verifyResponse(SharedServer.java:232) 	at com.ibm.websphere.microprofile.faulttolerance.metrics.fat.tests.CDIFallbackTest.testFallback(CDIFallbackTest.java:34) |  
-- | --
  | Unsupported browser |

**Comment by Emily-Jiang** [comment]
I think I've fixed this as part of the issue #686. Please verify after the changes under #686
