### ISSUE TITLE
[Question] Is it possible to define chunksize or disable it in jaxws client

### ISSUE THREAD

**Issue by c-koell** [OpenLiberty/open-liberty#16681]
Hi!

We are using openliberty to run a jaxws client. We send huge data to a andpoint and we should increase the chunksize or we should disable it.
After searching i have found following question https://www.ibm.com/mysupport/s/question/0D50z00005pgfTw/accessing-jaxws-cxf-api-clientproxy-in-liberty-profile?language=de which points to a other problem, but it uses the HTTPClientPolicy.
My plan was to define the chunksize described like here https://cxf.apache.org/docs/client-http-transport-including-ssl-support.html
I tried to use the HTTPClientPolicy
```
Client client = ClientProxy.getClient(myPort);
HTTPConduit http = (HTTPConduit) client.getConduit();
HTTPClientPolicy httpClientPolicy = new HTTPClientPolicy();
httpClientPolicy.setAllowChunking(false);
```
I have added the following dependencies in my pom.xml
```
<dependency>
  <groupId>org.apache.cxf</groupId>
  <artifactId>cxf-rt-transports-http</artifactId>
  <version>3.4.1</version>
  <scope>provided</scope>
</dependency>
<dependency>
  <groupId>org.apache.cxf</groupId>
  <artifactId>cxf-rt-frontend-jaxws</artifactId>
  <version>3.4.1</version>
  <scope>provided</scope>
</dependency>
```
and my server.xml looks like
```
<featureManager>
  ...
  <feature>jaxws-2.2</feature>
</featureManager>
<webApplication location="TestService.war" contextRoot="/">
  <classloader apiTypeVisibility="+third-party"/>
</webApplication>
```
But i get always a java.lang.ClassNotFoundException: org.apache.cxf.frontend.ClientProxy

So my question is how is it possible to configure the cxf impl if we use only jaxws.

Thanks for any help
Claus

**Comment by neuwerk** [comment]
@c-koell Hey! You can disable Chunking with the jaxws-2.2 feature via CXF properties, but you can't use the CXF API's directly (i.e. HTTPClientPolicy). If your intention is to continue to use the jaxws-2.2 feature, the first step I recommend is removing the CXF dependencies you've added to your pom.xml, as that will conflict with our jaxws-2.2 feature. 

Next, if you need to disable Chunking, you should be able to do it in a couple of ways. Here's a link to our Knowledge Center document that outlines how to set custom HTTP properties on a JAX-WS client using the ibm-ws-bnd.xml file

https://www.ibm.com/docs/en/was-liberty/zos?topic=djwal-enabling-http-conduit-client-properties-user-custom-properties

An example of the ibm-ws-bnd.xml file that set the AllowChunking property to false would look something like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<webservices-bnd xmlns="http://websphere.ibm.com/xml/ns/javaee" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://websphere.ibm.com/xml/ns/javaee http://websphere.ibm.com/xml/ns/javaee/ibm-ws-bnd_1_0.xsd"
		version="1.0">
	<service-ref name="service/SimpleEchoService">
		<port name="SimpleEchoPort">
			<properties vendor="IBM" />
		</port>
		<properties http.conduit.client.AllowChunking="false" />
	</service-ref>
	...
</webservices-bnd>
```

You can also set this configuration in the `server.xml` with the `webApplication`, `enterpriseApplication` depending on type of app you are deploying. An example of setting the `http.conduit.client.AllowChunking` in a `server.xml` looks like this:

```
<server description="JAXWS Web Sample Server">
    <featureManager>
        <feature>jsp-2.3</feature>
        <feature>jaxws-2.2</feature>        
        <feature>localConnector-1.0</feature>
        <feature>jsf-2.2</feature>
    </featureManager>
    
    <httpEndpoint id="defaultHttpEndpoint" httpPort="9131" />
    

  <webApplication name="TestService" location="TestService.war" contextRoot="/">
  		
      <webservices-bnd moduleName="TestService">
  	<service-ref name="service/SimpleEchoService">
		<port name="SimpleEchoPort">
			<properties vendor="IBM" />
		</port>
		<properties http.conduit.client.AllowChunking="false" />
	</service-ref>

   	</webservices-bnd>
   </application>

</server>
```

The Knowledge Center document describes how to programmatically retrieve the config values on the Client's `BindingProvider` object, but you could also set them programmatically the like so: 

```
Echo echo = echoService.getEchoPort();
BindingProvider bp = (BindingProvider)echo;
bp.getRequestContext().put("http.conduit.client.AllowChunking", "false");
```
Any one of the three methods, should disable Chunking on the Client while using the jaxws-2.2 feature.  Hope this helps, and please let me know if you have any issues setting the property!

**Comment by c-koell** [comment]
Hi @neuwerk !

Thank you very much for the fast response. I have tried with ibm-ws-bnd.xml file and it works like a charm ;-)
You have saved my day !

greets
claus

**Comment by neuwerk** [comment]
@c-koell That's great that it worked, and I'm happy to help!
