### ISSUE TITLE
Doing "server create" fails to create .classCache

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#167]
When I download the 17003 RC image here: http://openliberty.io/downloads/
and invoke `wlp/bin/server create` to create a defaultServer, I get the following error:

> $ bin/server create
JVMSHRC559E Failed to create a directory "c:/atemp/openliberty-17.0.0.3-RC/wlp/usr/servers/.classCache" for the shared class cache
JVMSHRC686I Failed to startup shared class cache. Continue without using it as -Xshareclasses:nonfatal is specified
Server defaultServer created.

OpenLiberty should not report an error creating the default server out of the box for Windows/Cygwin users (have not confirmed if this also occurs on Linux or not)

**Comment by NottyCode** [comment]
Out of interest does that happen if you create wlp/usr/server out of the box? I know that the default usr folder structure doesn't exist in the openliberty.zip, but it does for WebSphere Liberty so that might be the issue here. A quick experiment would tell.

**Comment by aguibert** [comment]
If I manually make the `usr` dir (and even manually make the `usr/.classCache` dir) the error still occurs.  

This seems to just be a cosmetic issue -- if I follow it up with a `wlp/bin/server start` the defaultServer starts fine.  Also if I follow it up with creating a different server such as `wlp/bin/server create anotherServer` that also works fine.

**Comment by aguibert** [comment]
also occurs doing `wlp/bin server help` out of the box -- java version info:

```
$ java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build pwa6480sr1-20150417_01(SR1))
IBM J9 VM (build 2.8, JRE 1.8.0 Windows 7 amd64-64 Compressed References 20150410_243669 (JIT enabled, AOT enabled)
J9VM - R28_Java8_SR1_20150410_1531_B243669
JIT  - tr.r14.java_20150402_88976.03
GC   - R28_Java8_SR1_20150410_1531_B243669_CMPRSS
J9CL - 20150410_243669)
JCL - 20150413_01 based on Oracle jdk8u45-b13
```

**Comment by NottyCode** [comment]
You say you created the usr dir, but the cache is stored in usr/server so you would need to create usr/servers not just usr directory. Did you just create usr, or was that a typo?

**Comment by aguibert** [comment]
Good catch -- yes I was only creating the usr/ dir.
When I create the `wlp/usr/servers/` dir this goes away. 

@NottyCode So to fix this, should we simply add an empty `wlp/usr/servers/` dir in the openliberty zip?

**Comment by aguibert** [comment]
removing 17003 tag as this error message doesn't cause any harm and is not necessary to get into the 17003 stabilization branch

**Comment by aguibert** [comment]
This problem no longer occurs, so I'm closing this issue.
