### ISSUE TITLE
Feature Test Summary for LG-301: Add Liberty requestTiming metrics to /metrics

### ISSUE THREAD

**Issue by Channyboy** [OpenLiberty/open-liberty#16709]
Epic: LG-301: Add Liberty requestTiming metrics to /metrics #15781 
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

As part of LG-301 the request timing monitor bundles have been migrated over from WS-CD to Open Liberty. This includes the FATS at `com.ibm.ws.request.timing.monitor_fat`. The new functionality where in metrics are added to the existing metrics, but based on the MBean data from the `request.timing.monitor` bundle was tested by adding an additional test to the  `com.ibm.ws.request.timing.monitor_fat` fat project. The FAT test added is `RequestTimingMetricsTest.java`. This test tests all of the new metrics (which mirrors the MBean data). As a result, the _test_ mirrors the existing tests in the `com.ibm.ws.request.timing.monitor_fat` project. Instead of interrogating the Mbean for the data, we interrogate the metrics on the `/metrics` endpoint. Beside testing for the appropriate value, we test that the output is formatted in the expected manner. The test also uses repeat test to go through the different mpMetrics-2.x and mpMetric-3.x (currently 3.0 is released only) features.

### List of FAT projects affected

* `com.ibm.ws.request.timing.monitor_fat`

### Test strategy

* What functionality is new or modified by this feature?
**New vendor metrics in mpMetricx-2.x and mpMetrics-3.x that use the request timing monitor bundle's Mbeans.**
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
The new functionality (i.e. the metrics reported) relies on the Mbeans provided by request timing monitor bundle. The FAT tests mirror the existing `com.ibm.ws.request.timing.monitor_fat` tests where we check for the expected value from running the test-application. The test-application causes slow requests and hung requests. We check that the the metrics show the expected values. 

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)
**No manual tests.**

## Confidence Level

**5**

**Comment by Channyboy** [comment]
@OpenLiberty/fat-approvers

**Comment by ayoho** [comment]
Coverage seems fine to me 👍
