### ISSUE TITLE
mvnOutput files on z/OS machines are outputted in EBCDIC

### ISSUE THREAD

**Issue by Joseph-Cass** [OpenLiberty/open-liberty#16756]
In the TCK buckets, the `mvnOutput` file (and the `Launcher.log` file) are output in z/OS specific encoding. 

This is an issue for a few reasons:

1. Build monitors triaging and developers fixing TCK defects caused during `mvn build` have to know how to decode EBCDIC files which can be difficult (especially on Mac OS)
2. The exception message generated in the `output.txt` files is not being generated properly in `mvnUtils` since it cannot read the `mvnOutput` file: https://github.com/OpenLiberty/open-liberty/blob/ce8c828dab6d29f18b566e00623f2b0435c78e68/dev/fattest.simplicity/src/componenttest/topology/utils/MvnUtils.java#L189-L217

**Comment by tevans78** [comment]
We will do this when the need arises (a build break test failure).
