### ISSUE TITLE
Feature Test Summary for: Extend SPI to allow for additional bean defining annotations 

### ISSUE THREAD

**Issue by benjamin-confino** [OpenLiberty/open-liberty#16809]
For Epic: https://github.com/OpenLiberty/open-liberty/issues/15540

## Test Strategy

This change modifies the Liberty's CDI extension SPI adding a new method `getBeanDefiningAnnotationClasses` which allows users to define an annotation or annotations that CDI will treat as a Bean Defining Annotation. 

We test this new method by creating a user feature that uses this method to register a couple of annotations, then check that CDI will inject them correctly.

In addition we create a second test-bundle that is a close duplicate of the first, and registered through the SPIMetaData class in the first bundle. We extensively test cross injection between the two bundles. We do this because the new method is to be used to register javax/jakarta annotations that live outside the liberty bundle that enables them, and so cross-bundle registering is required. Furthermore since we were using cross-bundle registering for annotations we also enabled them for extensions and classes, the second test-bundle to cover all the same points as the original. 

There are no negative tests as the interface is extremely narrow, one method that the user will override which is intended to contain a one line method to return a set.

There are no manual tests, however the jax-rs team are using this interface and thus provide a real world test.

### List of FAT projects affected

* com.ibm.ws.cdi.extension_fat - delivered in: https://github.com/OpenLiberty/open-liberty/pull/15541

## Confidence Level

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

**Comment by ayoho** [comment]
Benjamin is working on adding one additional negative test scenario under https://github.com/OpenLiberty/open-liberty/pull/17450. That test seems to be simple and in hand, so I think the coverage here looks good. 👍
