### ISSUE TITLE
Remove OL#1679 overlay on delivery of Eclipselink 2.7.3

### ISSUE THREAD

**Issue by jgrassel** [OpenLiberty/open-liberty#1683]
#1679, an issue that blocked JPA 2.2 Feature shipping requirements, necessitated overlaying an Eclipselink class because the change (https://bugs.eclipse.org/bugs/show_bug.cgi?id=529907) missed the Eclipselink 2.7.1 release.  The change was committed and expected to be available in Eclipselink 2.7.2.  Therefore, when switching OpenLiberty to Eclipselink 2.7.2, we need to remove the overlay.

Steps:
1. **Delete** dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
2. **Edit** dev/com.ibm.websphere.appserver.thirdparty.eclipselink.2.7/bnd.bnd:

Remove the following from the "Include-Resource:" block:
`  org/eclipse/persistence/internal/jpa=${bin}/org/eclipse/persistence/internal/jpa`
_(remember to remove the `,\ ` on the previous line)_

Remove the following from the "instrument.classesExcludes:" block:
`  org/eclipse/persistence/internal/jpa/*.class`
_(remember to remove the `,\ ` on the previous line)_

Remove the following from the "-buildpath:" block:
`  org.eclipse.persistence.core;version=2.7.1.v20171221-bd47e8f;strategy=exact,\`

**Comment by dazey3** [comment]
Handled during delivery of https://github.com/OpenLiberty/open-liberty/issues/4587
