### ISSUE TITLE
BETA BLOG - Request Timing Metrics for 21.0.0.6 beta 

### ISSUE THREAD

**Issue by Channyboy** [OpenLiberty/open-liberty#16950]
**For Epic: LG-301 - https://github.com/OpenLiberty/open-liberty/issues/15781**

The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty. For this post to be included in the beta issue please make sure that this is completed by the end of Friday following the GM (Wednesday). 

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name (eg WebSockets feature): 
**Request Timing feature and MicroProfile Metrics features (2.x + 3.0)**
   
   Short feature name (eg websockets-1.0): 
**`requestTiming-1.0` + (`mpMetrics-2.0` OR `mpMetrics-2.2`, OR `mpMetrics-2.3` OR `mpMetrics-3.0`)**

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.
**Operations**

3. Write a paragraph to summarises the update, including the following points:
   
It was always the case that the request timing feature kept track of the slow and hung requests for servlet requests with a RequestTimingStats MXBean. The Microprofile Metrics features on the other hand would always provide _vendor_ metrics that are distinct to the Open Liberty runtime. These vendor metrics are typically sourced from the MXBeans provided by various components in the Open Liberty runtime. However, until now the two have not crossed paths. Starting with this 21.0.0.5 beta the RequestTimingStats MXBean will now have it's data retrieved by the Microprofile Metrics for reporting on the `/metrics` (or /metrics/vendor) endpoint.  This functionality is compatible with the MicroProfile Metrics features 3.0 and 2.x. 

Here is a sample output of the new request timing metrics in Prometheus exposition formatted.
```
# TYPE vendor_requestTiming_activeRequestCount gauge
# HELP vendor_requestTiming_activeRequestCount The number of servlet requests currently running.
vendor_requestTiming_activeRequestCount 1

# TYPE vendor_requestTiming_requestCount_total counter
# HELP vendor_requestTiming_requestCount_total The number of servlet requests since the server started.
vendor_requestTiming_requestCount_total 3

# TYPE vendor_requestTiming_hungRequestCount gauge
# HELP vendor_requestTiming_hungRequestCount The number of servlet requests that are currently running but are hung.
vendor_requestTiming_hungRequestCount 0

# TYPE vendor_requestTiming_slowRequestCount gauge
# HELP vendor_requestTiming_slowRequestCount The number of servlet requests that are currently running but are slow.
vendor_requestTiming_slowRequestCount 0
```

To be able to retrieve request timing metrics from `/metrics` you will need to enable both the `requestTiming-1.0`  feature in combination with one of the following MicroProfile Metric features: `mpMetrics-2.0`, `mpMetrics-2.2` or `mpMetrics-2.3` or `mpMetric-3.0`. Then you will need to configure the request timing thresholds for slow or hung requests.

The following example demonstrate enabling request timing metrics for `mpMetrics-3.0` with a sample threshold configurations for both slow and hung servlet requests.

```
    <featureManager>
	<feature>mpMetrics-3.0</feature>
	 <feature>requestTiming-1.0</feature>
         [...] <!-- other features omitted for brevity -->
    </featureManager>

    <requestTiming sampleRate="1" slowRequestThreshold="10s">
		<servletTiming
			slowRequestThreshold="2s"
    		        hungRequestThreshold="10s"/>
    </requestTiming>

```

You can learn more about the request timing feature here https://openliberty.io/docs/latest/reference/feature/requestTiming-1.0.html
You can learn more about Monitoring with Metrics here : https://openliberty.io/docs/21.0.0.4/introduction-monitoring-metrics.html
You can learn more about the (servlet) request timing MXbean here: https://openliberty.io/docs/21.0.0.4/jmx-metrics-list.html#request-timing-stats
   
## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by austin0** [comment]
Blog is live: https://openliberty.io/blog/2021/05/18/metrics-jee9-21006-beta.html

Closing
