### ISSUE TITLE
Fix TCK test failures

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty#1700]
- [x] Run the TCK tests and list the failures.
- [x] Open separate issues as needed and fix them

**Comment by janamanoharan** [comment]
List of failures:
- [] testCallbackOperationAnnotations (AirlinesAppTest:428)
- [] testComponents (AirlinesAppTest.java:726)
- [] testExampleObject (AirlinesAppTest.java:655) 
- [] testExcludePackage (OASConfigExcludePackageTest.java:49)
- [] testExcludedClass (OASConfigExcludeClassTest.java:49)
- [] testExcludedClasses (OASConfigExcludeClassesTest.java:50)
- [] testFilterHeader (FilterTest.java:165)
- [] testFilterParameter (FilterTest.java:120)
- [] testFilterPathItemEnsureOrder (FilterTest.java:80)
- [] testHeaderInComponents (AirlinesAppTest.java:811)
- [] testParameter (AirlinesAppTest.java:311)
- [] testRefHeaderInAPIResponse (AirlinesAppTest.java:791)
- [] testRefHeaderInEncoding (AirlinesAppTest.java:802)
- [] testScanClass (OASConfigScanClassTest.java:46)
- [] testScanClasses (OASConfigScanClassesTest.java:46)
- [] testScanPackage (OASConfigScanPackageTest.java:46)
- [] testSchema (AirlinesAppTest.java:630)
- [] testServer (OASConfigServersTest.java:42)
- [] testTagsInOperations(AirlinesAppTest.java:703)

**Comment by leochr** [comment]
FYI, results from running the TCK tests (stand-alone, not the FAT project) with the latest code from rest-api branch:
Tests run: 211, Failures: 9, Errors: 0, Skipped: 0
org.eclipse.microprofile.openapi.tck.AirlinesAppTest.testCallbackOperationAnnotations
org.eclipse.microprofile.openapi.tck.AirlinesAppTest
org.eclipse.microprofile.openapi.tck.FilterTest.testFilterParameter
org.eclipse.microprofile.openapi.tck.FilterTest.testFilterPathItemEnsureOrder
org.eclipse.microprofile.openapi.tck.AirlinesAppTest.testParameter
org.eclipse.microprofile.openapi.tck.AirlinesAppTest.testRefHeaderInAPIResponse
org.eclipse.microprofile.openapi.tck.AirlinesAppTest.testRefHeaderInEncoding
org.eclipse.microprofile.openapi.tck.AirlinesAppTest.testSchema
org.eclipse.microprofile.openapi.tck.ModelReaderAppTest.testSchema
org.eclipse.microprofile.openapi.tck.AirlinesAppTest.testTagsInOperations

**Comment by mrglavas** [comment]
The filter related test failures will be resolved by https://github.com/OpenLiberty/open-liberty/issues/1583:
org.eclipse.microprofile.openapi.tck.FilterTest.testFilterParameter
org.eclipse.microprofile.openapi.tck.FilterTest.testFilterPathItemEnsureOrder

**Comment by leochr** [comment]
FYI, with the code in the team branch last Friday, observed only these 3 failures:
testCallbackOperationAnnotations
testParameter
testSchema

**Comment by leochr** [comment]
TCK is passing 100% now.
