### ISSUE TITLE
Support UserInfo response in JWT format

### ISSUE THREAD

**Issue by ayoho** [OpenLiberty/open-liberty#17072]
Add support for processing UserInfo responses in JWT format, per section 5.3.2 of the OIDC spec (https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse).

The Liberty runtime currently expects the UserInfo response to be a plain JSON object. There are two instances of code that handles interactions with the UserInfo endpoint that I've found so far where that expectation is set:
- `AccessTokenAuthenticator.getUserInfoFromToken()` (https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/AccessTokenAuthenticator.java#L522)
- `UserInfoHelper` (https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/UserInfoHelper.java)

Those locations need to be updated to handle `application/jwt` responses from UserInfo endpoints as described in the spec.

Relevant portions of section 5.3.2 of the OIDC spec:
> The UserInfo Claims MUST be returned as the members of a JSON object unless a signed or encrypted response was requested during Client Registration. The Claims defined in Section 5.1 can be returned, as can additional Claims not specified there.
> ...
> Upon receipt of the UserInfo Request, the UserInfo Endpoint MUST return the JSON Serialization of the UserInfo Response as in Section 13.3 in the HTTP response body unless a different format was specified during Registration [OpenID.Registration]. The UserInfo Endpoint MUST return a content-type header to indicate which format is being returned. The content-type of the HTTP response MUST be application/json if the response body is a text JSON object; the response body SHOULD be encoded using UTF-8.
> 
>  If the UserInfo Response is signed and/or encrypted, then the Claims are returned in a JWT and the content-type MUST be application/jwt. The response MAY be encrypted without also being signed. If both signing and encryption are requested, the response MUST be signed then encrypted, with the result being a Nested JWT, as defined in [JWT].
> 
> If signed, the UserInfo Response SHOULD contain the Claims iss (issuer) and aud (audience) as members. The iss value SHOULD be the OP's Issuer Identifier URL. The aud value SHOULD be or include the RP's Client ID value.

**Comment by teddyjtorres** [comment]
Awaiting FATs.
