### ISSUE TITLE
security-role to group mapping not working as expected with auth-method MP-JWT

### ISSUE THREAD

**Issue by jitendrakalyan** [OpenLiberty/open-liberty#17096]
We have simple webapp with a couple of JSPs. we want to deploy it on open liberty server (MicroProfile) and do authentication and authorization using MP-JWT. The plan is to have Webseal authenticate the user and generate a JWT. The WebApp will verify the JWT is valid and provide access to resources based on groups claim. 

web.xml
===============================================================

`<login-config>` 
`<auth-method>MP-JWT</auth-method>` 

`<realm-name>MP-JWT</realm-name>`

`</login-config>` 

 `<security-role>`
    `<role-name>Role1</role-name>`
  `</security-role>`

  `<security-role>`
    `<role-name>Role2</role-name>`
  `</security-role>`

	<security-constraint>
		<web-resource-collection>
			<web-resource-name>HR Users</web-resource-name>
			<url-pattern>/page1.jsp</url-pattern>
			 <http-method>GET</http-method>
		</web-resource-collection>
		<auth-constraint>
			<description>HR users</description>
			<role-name>Role1</role-name>
		</auth-constraint>
	</security-constraint>
	
	<security-constraint>
		<web-resource-collection>
			<web-resource-name>Users</web-resource-name>
			<url-pattern>/page2.jsp</url-pattern>
			 <http-method>GET</http-method>
		</web-resource-collection>
		<auth-constraint>
			<description>users</description>
			<role-name>Role2</role-name>
		</auth-constraint>
	</security-constraint>
</web-app>

server.xml
===================================================================

  `  <featureManager>`
  `     <feature>microProfile-4.0</feature>`
	`	<feature>jsp-2.3</feature>`
	`	 <feature>servlet-4.0</feature>`
	`	<feature>mpJwt-1.2</feature>`
    `</featureManager>`

  `<ssl id="defaultSSLConfig" trustDefaultCerts="true" />`
   `<keyStore id="defaultTrustStore" password="secret"/>`

  `  <httpEndpoint host="*" id="defaultHttpEndpoint"
                  httpPort="9080"
                  httpsPort="9443" />`

   ` <applicationManager autoExpand="true"/>`

  `  <jspEngine keepGenerated="true"/>`
  
 `  <mpJwt id="mp-jwt" mapToUserRegistry="false"/> `
   
  `<application type="war" contextRoot="JWTOL" location="JWTOL" id="JWTOL" name="JWTOL">
     <application-bnd>
            <security-role name="Role1">
                <group name="Group1" />
            </security-role>
			<security-role name="Role2">
                <group name="Group2" />
            </security-role>
        </application-bnd>
    </application> `

`<mpJWT userNameAttribute="upn" groupNameAttribute="groups"/> `

</server>

The server is not recognizing/acknowledging the security-role to group mapping in the server xml. Infact JWT authorization only works if  <application-bnd> is removed. Then it directly takes group claim matches it to the role configured in web.xml and authorizes access. I couldn't find anything in the documentation that points to any different configuration for role and group mapping. This is not a JAX-RS application. We are not using any annotations. It is simply a couple of JSPs. We want to test this out so we can proceed to migrate our legacy java webapp applications to open liberty server from WebSphere.

**Comment by teddyjtorres** [comment]
If there is no user registry, then please specify an access-id in the "group" elements. Otherwise, there is an attempt to get the access-id from a user registry, which it does not appear to be configured, and the role is not mapped.

For example, the access-id for a subject's group built from a JWT would have this format,
```
<group access-id="group:realm_from_iss_claim/groupname" />
```

**Comment by jitendrakalyan** [comment]
Thank you for your response @teddyjtorres I have added the access Id like you said but it didn't make any difference. Is there anything else I am missing ?


` <application  location="JWTOL.war" contextRoot="/" >`
		
`	<authorization-roles id="myAuthRoles">`

   `        <security-role id="secRole1" name="HR-USERS">`
      `          <group access-id="group:MP-JWT/admin" id="admin" name="admin" />`
   `        </security-role> `
`			<security-role  id="secRole2" name="USERS">`
  `             <group access-id="group:MP-JWT/user" id="user" name="user" />`
    `        </security-role>`
`		</authorization-roles>`

  `  </application> `

**Comment by teddyjtorres** [comment]
Per our slack discussion, please add

```
<feature>appSecurity-2.0</feature>
```
or a later version.

Please also ensure the "iss" claim in the JWT matches the realm name used in the access-id.

Regards.

**Comment by teddyjtorres** [comment]
I apologize, adding mpJwt-1.2 will automatically include appSecurity-3.0, so there is no need to add appSecurity-2.0.

**Comment by jitendrakalyan** [comment]
@teddyjtorres Thank you for your help. matching the iss claim with auth method/ Realm name along with using access-id in group element resolved the issue.

Server.xml
 `   <featureManager>`
`       <feature>microProfile-4.0</feature> `
	`	<feature>jsp-2.3</feature>`
	`	 <feature>servlet-4.0</feature>`
   ` </featureManager>`

`  <ssl id="defaultSSLConfig" trustDefaultCerts="true" />`
  ` <keyStore id="defaultTrustStore" password="secret"/>`

  `  <httpEndpoint host="*" id="defaultHttpEndpoint" httpPort="9080" httpsPort="9443" />`
  
   ` <jspEngine keepGenerated="true"/>`
  
   `<mpJwt id="mp-jwt" issuer="MP-JWT" /> `

  `<webApplication  location="JWTOL.war" contextRoot="/" >`
	`	 <application-bnd>`
      `      <security-role name="HR-USERS">`
          `      <group access-id="group:MP-JWT/admin" id="group1" name="admin" />`
      `      </security-role>`
		`	<security-role name="USERS">`
              `  <group access-id="group:MP-JWT/user" id="group1" name="user" />`
         `   </security-role>`
        `</application-bnd>`

 `   </webApplication> `
	
`</server>`

web.xml

`<login-config> `
`<auth-method>MP-JWT</auth-method> `

`<realm-name>MP-JWT</realm-name>`

`</login-config>`

`  <security-role>`
  `  <role-name>HR-USERS</role-name>`
  `</security-role>`

 ` <security-role>`
  `  <role-name>USERS</role-name>`
  `</security-role>`
	
 `  <security-constraint>`
	`	<web-resource-collection>`
		`	<web-resource-name>HR Users</web-resource-name>`
			`<url-pattern>/HRindex.jsp</url-pattern>`
		`</web-resource-collection>`
		`<auth-constraint>`
			`<description>HR Users</description>`
			`<role-name>HR-USERS</role-name>`
		`</auth-constraint>`
	`</security-constraint>`
	
	`	<security-constraint>`
	`	<web-resource-collection>`
			`<web-resource-name>Users</web-resource-name>`
			`<url-pattern>/index.jsp</url-pattern>`
		`</web-resource-collection>`
		`<auth-constraint>`
		`	<description>Users</description>`
			`<role-name>USERS</role-name>`
		`</auth-constraint>`
	`</security-constraint>`

**Comment by teddyjtorres** [comment]
You are welcome.

**Comment by krismarc** [comment]
@jitendrakalyan, @teddyjtorres
have you ever tried the same with Azure AAD/EntraID? I'd love to see some sample. I'm lost what needs to be configured as group access-id also mpJWT itself is not that clear to me. My goal is to migrate from regular User Registry that queries internal AD.

There's a sample https://github.com/Azure-Samples/liberty-aad-oidc which works, however it has it's own authorization logic. I had a hope that I could migrate from User Registry to oidc/mpJWT by simply mapping AAD groups/roles and continue using my RolesAllowed annotations.

Simply saying, I'd like to migrate my applications with minimal code related changes and keep it on OL's config/web.xml level

**Comment by teddyjtorres** [comment]
Hi @krismarc,

I am no longer with IBM. Please follow up with @ayoho or @arkarkala. Thanks!
