### ISSUE TITLE
Trace specification does not correctly for jakarta 9 feature io.openliberty.org.jboss.resteasy.validator.provider

### ISSUE THREAD

**Issue by dettmoney** [OpenLiberty/open-liberty#17108]
I'm executing the SPECjEnterprise2018 benchmark which contains bean validation tests that are expected to fail the validation. I want to suppress the warnings from org.jboss.resteasy.plugins.validation.GeneralValidatorImpl that are printed to the messages.log since they are expected. I've tried many different additions to the traceSpecification, including org.jboss.*=error, org.jboss.resteasy.plugins.validation.GeneralValidatorImpl=error, org.jboss.*=all=disabled, etc. But I still get the warnings in my log like this:
[5/10/21 13:10:30:694 CDT] 000000d9 org.jboss.resteasy.plugins.validation.GeneralValidatorImpl   W register.arg0.address.phone: numeric value out of bounds (<12 digits>.<0 digits> expected), register.arg0.address.phone: size must be between 8 and 12, register.arg0.address.city: size must be between 1 and 30

This is a relatively new feature that is part of the servlet-5.0 new jaxrs implementation (resteasy).

**Comment by donbourne** [comment]
@dettmoney , try any of these for the traceSpecification

```
org.jboss.resteasy.plugins.validation.GeneralValidatorImpl=off
org.jboss.resteasy.plugins.validation.GeneralValidatorImpl=severe
org.jboss.resteasy.plugins.validation.GeneralValidatorImpl=fatal
org.jboss.*=off
org.jboss.*=severe
org.jboss.*=fatal
```

**Comment by dettmoney** [comment]
I tried all six of those separately, and none suppressed the warning messages.

**Comment by pgunapal** [comment]
@dettmoney As per our slack discussion, the class `org.jboss.resteasy.plugins.validation.GeneralValidatorImpl` uses the [Tr](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.logging.core/src/com/ibm/websphere/ras/Tr.java) class to log the [warnings ](https://github.com/OpenLiberty/open-liberty/blob/82d5a09c64e56e92fc36f6a67730152a3eb5a2f5/dev/io.openliberty.org.jboss.resteasy.validator.provider/src/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java#L209). Unfortunately, a limitation in using the Tr class to log messages in Liberty, is that we can't control the logging levels using the trace specification in message.log, when messages are logged using `Tr.*` in Liberty. The message.log file will **always** contain `INFO` level messages and above. Hence, Liberty logging does not work similar to the WebSphere Application Server traditional logging. Furthermore, only the `FINE`, `FINER`, and `FINEST` trace levels can be controlled in the trace.log file, via the trace specification,  in Liberty.

However, if you use [JUL Logger](https://docs.oracle.com/javase/8/docs/api/java/util/logging/Logger.html) to log messages in Liberty, you can control the log levels via the trace specification, something like `Logger.warning()`.
