### ISSUE TITLE
oidc icons not being package inside the zip file for Open Liberty build 

### ISSUE THREAD

**Issue by aknguyen7** [OpenLiberty/open-liberty#17150]
The problem is we currently have an issue with packaging due to the icons are not include in the OL zip.
For example, when we have multiple icons in the .feature file, these doesn't seem to be pick up to be include in certain .zip files. With OIDC icons they are using Subsystem-Endpoint-Icons in the `com.ibm.websphere.appserver.openidConnectServer-1.0.mf` feature file. The icons are under the `build.image/wlp/lib/features/icons/com.ibm.websphere.appserver.openidConnectServer-1.0`

I think this problem has always been there as it was not handle multiple icons. The `openliberty-dev-21.0.0.4-XXX.zip` includes the icons but not other zips like `openliberty-all-21.0.0.4-xxxxxx.zip`, Chuck Bridgham said if the zip doesn’t use feature packager then it includes the icons

![image](https://user-images.githubusercontent.com/30509453/118147887-a6a26a80-b3d5-11eb-9e1a-25571e4da305.png)

I talked to Wendy Raschke then Ethan Fritz and he looked at the build.image/build.gradle file. Those other zips are created by this task https://github.com/OpenLiberty/open-liberty/blob/integration/dev/build.image/build.gradle#L106
Those other zips use minify to be created and `openliberty-dev-xxx.zip` is just a zip task so it includes everything in the directory structure. He pointed 
to the file under https://github.com/OpenLiberty/open-liberty/blob/2fd4a880754c37a988c5ed9ac4f1ea5988e465d6/dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/PackageCommand.java

I have also talk to Dave Zavala for PackageCommand.java

**Comment by aknguyen7** [comment]
PR  #17191

**Comment by dazavala** [comment]
@aknguyen7  FYI: PR17191 merged today.  You should be able to verify and close this issue in a day or two. 

During the automated build some of the targets/tasks in build.image/build.gradle invoke the **server package <targetServer> --include=minify** command and then collect the content of the minified server into the target build image.  The causal problem is the content of the minified server lacks the subsystem endpoint icons.  PR 17191 resolves the problem.

**Comment by dazavala** [comment]
@aknguyen7 I verified endpoint icons build into the zipOpenLibertyAll target.  Closing the issue.

**Comment by k8vance88** [comment]
@dazavala it appears we are seeing this problem again.  See https://github.com/OpenLiberty/open-liberty/issues/21923

**Comment by k8vance88** [comment]
Actually my mistake, I do see the image in OL.  They are missing from Liberty builds only.
