### ISSUE TITLE
Multiple entries may be added to the Authentication Cache for a custom cache key hashtable login 

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/open-liberty#17155]
**Describe the bug**
Under high stress environment, duplicate entries may be added to the Authentication Cache for one custom cache key. It may cause an increased authentication and an extra memory usage. 

**Steps to Reproduce**
Send multiple requests that will result in the same custom cache key, such as configure a TAI (TrustAssociationInterceptor) and send requests that makes TAI to create the same custom cache key.  

**Expected behavior**
For the initial login with the request, Liberty may create authcache entries with several different keys (one for token, another for the cache key etc). After that, the cache entries for the same subject should not grow. 

**Diagnostic information:**
 - OpenLiberty Version: [e.g. 19.0.0.8]  Any supported version
 - Java Version: [i.e. full output of `java -version`] Any supported version 
 - server.xml configuration (WITHOUT sensitive information like passwords)  
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

To diagnose, eclipse memory analyzer tool was used (https://www.eclipse.org/mat/) with IBM Extension. 
"IBM Extensions" -> "WebSphere Application Server" -> "Security" -> "Authentication Cache Overview" 
it shows the entries as well as the keys. 

**Additional context**

**Comment by utle** [comment]
Fixed by https://github.com/OpenLiberty/open-liberty/pull/17147

**Comment by una-tapa** [comment]
I guess I should have closed this issue.   Additional code is checked in via Issue 17605 PR 17642
