### ISSUE TITLE
OpenLiberty ignores application classes from jakarta.* packages

### ISSUE THREAD

**Issue by chkal** [OpenLiberty/open-liberty#17249]
**Describe the bug**
I'm currently working on running the Jakarta MVC 2.0 TCK against Eclipse Krazo on OpenLiberty. The TCK deploys different applications to the application server which contain classes from the package namespace `jakarta.mvc.tck.*`. For some weird reason OpenLiberty seems to ignore these classes. I was able to reproduce this issue with a minimal application which just contains JAX-RS classes. See "Steps to reproduce" below.

**Steps to Reproduce**
A small application reproducing this issue can be found [here](https://github.com/chkal/openliberty-jakarta-packages). This app contains two JAX-RS application subclasses. The first is using the package `jakarta.foobar` and the other one `other.foobar`. If you deploy this app to OpenLiberty 21.0.0.6-beta only the latter one works and the former one results in 404 errors.

Detailed steps to reproduce:
  * Build [this app](https://github.com/chkal/openliberty-jakarta-packages) 
  * Deploy the app to OpenLiberty 21.0.0.6-beta with the feature `jakartaee-9.0` being enabled.
  * Open http://localhost:8080/liberty-test/ in your browser
  * The first link results in a 404 error (JAX-RS application + resource in package `jakarta.foobar`)
  * Clicking the second link will work fine (JAX-RS application + resource in package `other.foobar`)

**Expected behavior**
The expected behavior is that JAX-RS applications using the package namespace `jakarta.*` work the same way as applications that use other packages.

**Diagnostic information:**
 - OpenLiberty 21.0.0.6-beta with `jakartaee-9.0` feature enabled
 - OpenJDK Runtime Environment 18.9 (build 11.0.11+9)
 - Linux 5.11.18-200.fc33.x86_64 x86_64 GNU/Linux

**Additional context**
cc: @andymc12

**Comment by volosied** [comment]
Hi,

I've merged changes that will address this issue. They should be included in the next liberty release (21007).

**Comment by chkal** [comment]
@volosied Awesome. Thank you so much for helping with this.
