### ISSUE TITLE
Replace the prohibited terms from code due June 30, 2022

### ISSUE THREAD

**Issue by anjumfatima90** [OpenLiberty/open-liberty#17254]
Replace the prohibited terms from the code with alternative terms. The terms to avoid and the replacement terms have been listed [here](https://w3.ibm.com/w3publisher/inclusive-it-terminology/terms-to-replace)

**Comment by mbroz2** [comment]
All previously known terms have been removed in the above PRs.  However, 4 more instances have been identified while working on the Sept and March terms, and will be removed via https://github.com/OpenLiberty/open-liberty/pull/19988
