### ISSUE TITLE
epic 16384. Error reporting and globalization for CRIU

### ISSUE THREAD

**Issue by sebratton** [OpenLiberty/open-liberty#17298]
Need to investigate how we will handle error reporting related to CRIU failures. Is CRIU itself globalized? Can we depend on whatever localization of error messaging occurs in CRIU?
 These questions pertain to 
* failures captued in liberty runtime as a result of CRIU operations failing
* when direct calls to criu fail (e.g. invoking `criu restore snapshot`: is it sufficient to capture failure messages from criu and point the user to them)?
CRIU does define RC for direct invocation, for example, [restore command return codes](https://criu.org/C_API#restore). Should we base error reporting on the RC reported in cases like this and localize messages ourselves?

**Comment by sebratton** [comment]
This is part of issue #16384

**Comment by tjwatson** [comment]
We are no longer calling CRIU directly.  Instead it is being invoked by the JVM.  The JVM returns to us various exception types and we base our own translatable messages based on the type of exception the JVM returns.  I do not think criu itself has translations for its error messages, but that is very much out of our control.

We have already added translation messages for other errors that happen outside of Java in the `server` script.  I am going to close this issue.  Sam, if you feel there is more work here then please reopen.
