### ISSUE TITLE
RTC250841: SVT: problems in UI when using basicHTTP in @SecurityScheme

### ISSUE THREAD

**Issue by tam512** [OpenLiberty/open-liberty#1734]
- Using Open Liberty build https://rtpgsa.ibm.com/projects/l/liberty.build/liberty/WASX.LIBERTY/daily/20180110-1030.37.linux/linux/zipper/externals/installables/openliberty-all-17.0.0.4-20180110-1117.zip
- Add annotation @SecurityScheme to the SocialSphere app, and add @SecurityRequirement to POST and DELETE operations 
- See below are code snippet
```
@SecurityScheme(
	    securitySchemeName = "basicAuth",
	    description = "authentication needed to access weather app",
	    type = SecuritySchemeType.HTTP,
	    scheme = "basic"
	)
...........
...........
	@javax.ws.rs.POST
	@Path("{location}")
	@SecurityRequirement(name = "basicAuth")
...............
..............

	@javax.ws.rs.DELETE
	@Path("{location}")
	@SecurityRequirement(name = "basicAuth")
```
- When viewing app api doc /openapi, I can see basicAuth is listed under components
  securitySchemes:
    basicAuth:
      type: http
      description: authentication needed to access weather app
      scheme: basic

and basicAuth under DELETE and POST operations
     security:
      - basicAuth: []
- When viewing UI /api/explorer/, I can see Authorize button with the unlocked lock and the locks are also on each operation in the UI.
- Problem 1: when click on Authorize button, I see "Available authorizations basicAuth  (http, Basic)" and I can login with any bogus username and password and it will authorize it ok.  So what user registry does it use to verify username/password in this panel?  I have LDAP registry enabled on Liberty server.
- Problem 2: I can run any operation get, post, put & delete without login.  

I put my OL usr directory at http://ausgsa.ibm.com/projects/w/was_defects/issue10010/usr_OLServer1.zip  source app is under usr\servers\OLServer1\apps\WeatherMPOpenAPI.war

**Comment by tam512** [comment]
#link 250841

**Comment by tam512** [comment]
This problem is still in build https://libfsfe03.hursley.ibm.com/liberty/personal/1/arturdzm-1977-20180205-1455-_6cxTUAp6EeiTR7j3BTw-RQ/wlp-arturdzm-1977-20180205-1455.zip

**Comment by leochr** [comment]
We originally thought it’s IBM’s custom code that’s causing the pop-up, but we verified that the open-source UI has the same behaviour. So we won’t fix it (at least for 1Q). We have documented it here :
https://www-03preprod.ibm.com/support/knowledgecenter/SSAW57_liberty_test/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_mpopenapi.html

**Comment by mrglavas** [comment]
@arturdzm Check whether this issue can be closed now.

**Comment by arturdzm** [comment]
1. Basic auth does not validate at the time entering credentials, this is due the fact that there is no single endpoint can be used to tell if user has access to all APIs, for example 1 user can be allowed to invoke GETs but not DELETEs
2. It's the job of the server/endpoint to verify/request for credentials, otherwise it would be big security vulnerability if authentication layer was in the UI. 
Also basic auth is most primitive way of securing APIs and should not be really used in practice. API tokens or oauth2 should be used instead
