### ISSUE TITLE
GA BLOG -  Request Timing Metrics for 21.0.0.6 

### ISSUE THREAD

**Issue by Channyboy** [OpenLiberty/open-liberty#17398]
**For Epic: LG-301 - https://github.com/OpenLiberty/open-liberty/issues/15781**
Similar to beta blog : https://github.com/OpenLiberty/open-liberty/issues/16950|
The blog is published at : https://openliberty.io/blog/2021/05/18/metrics-jee9-21006-beta.html

But now to include a screenshot.

The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty. For this post to be included in the beta issue please make sure that this is completed by the end of Friday following the GM (Wednesday). 

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name (eg WebSockets feature): 
**Request Timing feature and MicroProfile Metrics features (2.x + 3.0)**
   
   Short feature name (eg websockets-1.0): 
**`requestTiming-1.0` + (`mpMetrics-2.0` OR `mpMetrics-2.2`, OR `mpMetrics-2.3` OR `mpMetrics-3.0`)**

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.
**Operations**

3. Write a paragraph to summarises the update, including the following points:

The request timing feature (requestTiming-1.0) is used to keep track of the slow and hung requests for servlet requests with a RequestTimingStats MXBean. The Microprofile Metrics features (mpMetrics-X.X) on the other hand provides vendor metrics that are distinct to the Open Liberty runtime.

Starting with the Open Liberty 21.0.0.6-beta the RequestTimingStats MXBean will now have it’s data retrieved by the MicroProfile Metrics feature for reporting on the /metrics (or /metrics/vendor) endpoint. This functionality is compatible with both the 2.X and 3.X MicroProfile Metrics features.

Below is a sample output of the new request timing metrics:
```
# TYPE vendor_requestTiming_activeRequestCount gauge
# HELP vendor_requestTiming_activeRequestCount The number of servlet requests currently running.
vendor_requestTiming_activeRequestCount 1

# TYPE vendor_requestTiming_requestCount_total counter
# HELP vendor_requestTiming_requestCount_total The number of servlet requests since the server started.
vendor_requestTiming_requestCount_total 3

# TYPE vendor_requestTiming_hungRequestCount gauge
# HELP vendor_requestTiming_hungRequestCount The number of servlet requests that are currently running but are hung.
vendor_requestTiming_hungRequestCount 0

# TYPE vendor_requestTiming_slowRequestCount gauge
# HELP vendor_requestTiming_slowRequestCount The number of servlet requests that are currently running but are slow.
vendor_requestTiming_slowRequestCount 0
```

To be able to retrieve request timing metrics from /metrics you will need to enable both the requestTiming-1.0 feature in combination with one of the following MicroProfile Metric features: mpMetrics-2.0, mpMetrics-2.2 or mpMetrics-2.3 or mpMetric-3.0.

To begin recieving metrics you will need to configure the request timing thresholds for slow or hung requests. The following example demonstrates enabling request timing metrics for mpMetrics-3.0, with a sample threshold configuration for both slow and hung servlet requests.
```
    <featureManager>
      <feature>mpMetrics-3.0</feature>
      <feature>requestTiming-1.0</feature>
      <!-- other features omitted for brevity -->
    </featureManager>

    <requestTiming sampleRate="1" slowRequestThreshold="10s">
      <servletTiming
        slowRequestThreshold="2s"
        hungRequestThreshold="10s"/>
    </requestTiming>
```

The below screenshot illustrate the usage of the four new metrics in Grafana.

![requestCountThings](https://user-images.githubusercontent.com/2858176/120572942-d0eeb300-c3ea-11eb-9737-24ed5b71d885.jpg)

For more information regarding Request Timing with MicroProfile Metrics:

* link:{url-prefix}/docs/latest/reference/feature/requestTiming-1.0.html[Request Timing Documentation]
* link:{url-prefix}/docs/latest/introduction-monitoring-metrics.html[Monitoring with Metrics]
* link:{url-prefix}/docs/latest/jmx-metrics-list.html#request-timing-stats[Request Timing MXBean Documentation]

**Comment by jakub-pomykala** [comment]
Blog live [here](https://openliberty.io/blog/2021/06/11/request-timing-21006.html)
