### ISSUE TITLE
CRIU dump and restore in containers

### ISSUE THREAD

**Issue by ymanton** [OpenLiberty/open-liberty#17391]
This is a summary of my experiments thus far with dumping and restoring processes inside a container. I've been experimenting with self-dumping specifically, but many of these insights likely apply when invoking `criu dump` as well.

- Dumping a target process that is running as PID1 isn't possible. CRIU needs to be able to run outside of the PID tree of the target process, but if the target process is PID1 every process will be in its PID tree and CRIU will fail to dump.
- Open Liberty images run the Java process as PID1 by default (`docker-server.sh` -> `exec /opt/ol/wlp/bin/server run`).
- Running a shell as PID1 (e.g. by invoking `server run` without using `exec`) gets around the problem, but breaks signal handling because the shell will not forward signals to its children by default; the shell script being executed would have to do that explicitly. If signals aren't forwarded things like `ctrl+c` and `docker kill` don't work smoothly.
- Running with `docker run --init` also gets around the problem and will tell the container runtime to start an init process as PID 1 and run the entrypoint defined in the image as a child; the init process will forward signals automatically.
- Running as a child of PID1 will usually result in the target process running with a low PID, e.g. 6.
- CRIU will try to restore the target process to its original PID or fail otherwise. If the target process runs with a low PID it can be tricky to have that PID be available at restore-time. You can influence the PID new processes will get by writing to `/proc/sys/kernel/ns_last_pid`; forcing the target process to a high PID makes life easier on the restore side and allows you to run scripts/gdb/strace, etc. without inadvertently occupying the target PID.
- Self-dumping a process in a container requires that we close the file descriptors for `stdin/stdout/stderr` (file descriptors 0,1,2) prior to the dump; otherwise the restore will silently fail for currently unknown reasons. This isn't required outside of a container. It may have something to do with how the container is started, or the specific container runtime, or something else.
- If you close `stdin/stdout/stderr` prior to the dump you can still write to at least `stdout` on restore and nothing bad seems to happen; e.g. `printf()` after restore won't crash, even though no output will be seen anywhere. The restored process doesn't have file descriptors 0,1,2 open.

**Comment by ymanton** [comment]
FYI @tjwatson.

**Comment by ymanton** [comment]
Re: needing to close `stdin/stdout/stderr`, the problem boils down to the fact that when a container is running in detached mode, these descriptors are attached to pipes which are connected to external processes (i.e. processes that are not going to be checkpointed). When we attempt to restore the process we're doing so in a new container, with new pipes, and we therefore have to tell criu to restore the old pipes by mapping them to the new pipes.

At checkpoint time, a process running in a detached container as the following file descriptors open:

```
lrwx------ 1 root root 64 Jun 15 19:15 0 -> /dev/null
l-wx------ 1 root root 64 Jun 15 19:15 1 -> pipe:[2886009]
l-wx------ 1 root root 64 Jun 15 19:15 2 -> pipe:[2886010]
```

At restore time, it has the following:

```
lrwx------ 1 root root 64 Jun 15 19:15 0 -> /dev/null
l-wx------ 1 root root 64 Jun 15 19:15 1 -> pipe:[2886506]
l-wx------ 1 root root 64 Jun 15 19:15 2 -> pipe:[2886507]
```

In order for CRIU to restore the original pipes we have to pass the following options at restore time:

```
--inherit-fd fd[1]:pipe:[2886009] --inherit-fd fd[2]:pipe:[2886010]
```

This tells CRIU that the old `pipe:[2886009]` and `pipe:[28860010]` are now connected to the current fd `1` and `2`.

**Comment by tjwatson** [comment]
> * Running a shell as PID1 (e.g. by invoking `server run` without using `exec`) gets around the problem, but breaks signal handling because the shell will not forward signals to its children by default; the shell script being executed would have to do that explicitly. If signals aren't forwarded things like `ctrl+c` and `docker kill` don't work smoothly.
> * Running with `docker run --init` also gets around the problem and will tell the container runtime to start an init process as PID 1 and run the entrypoint defined in the image as a child; the init process will forward signals automatically.

I opened issue #18048 to look into this.

> * CRIU will try to restore the target process to its original PID or fail otherwise. If the target process runs with a low PID it can be tricky to have that PID be available at restore-time. You can influence the PID new processes will get by writing to `/proc/sys/kernel/ns_last_pid`; forcing the target process to a high PID makes life easier on the restore side and allows you to run scripts/gdb/strace, etc. without inadvertently occupying the target PID.

There are issues with writing to `/proc/sys/kernel/ns_last_pid` because it requires to be run as root.  During a docker run to perform a checkpoint we could force it to start as root in order to do the write to `/proc/sys/kernel/ns_last_pid` and then switch to a non-root user before starting the Java process for Liberty, but this is rather complicated.  Another solution is to force some PIDs to be "consumed" during a checkpoint operation.  In my experiment I did this by invoking a simple no-op shell script over and over until the PID count got "high enough".  A bit of a hack, but should not cost that much and we are not as concerned about performance on the checkpoint prepare side.

> * Self-dumping a process in a container requires that we close the file descriptors for `stdin/stdout/stderr` (file descriptors 0,1,2) prior to the dump; otherwise the restore will silently fail for currently unknown reasons. This isn't required outside of a container. It may have something to do with how the container is started, or the specific container runtime, or something else.
> * If you close `stdin/stdout/stderr` prior to the dump you can still write to at least `stdout` on restore and nothing bad seems to happen; e.g. `printf()` after restore won't crash, even though no output will be seen anywhere. The restored process doesn't have file descriptors 0,1,2 open.

This will be tracked by issue #17812

**Comment by tjwatson** [comment]
Most of this is enabled by changes int the `ci.docker` repo or the `criu` repo to enable us to do checkpoint and restore in container.
