### ISSUE TITLE
Implement caching mechanism for OIDC client inbound propagation

### ISSUE THREAD

**Issue by ayoho** [OpenLiberty/open-liberty#17404]
Access tokens received by OIDC clients that require or support inbound propagation should implement a cache to avoid costly re-processing of tokens. This can apply to both opaque and JWT access tokens.

https://github.com/openliberty/open-liberty/issues/17060 contains much of the technical detail as far as where to get started with this issue. For opaque tokens, the [SingleTableCache](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/structures/SingleTableCache.java) might offer a good solution. It's possible that cache could be used for both opaque and JWT access tokens. However the JWT consumer code uses the [JwtCache](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/JwtCache.java) class to maintain a cache of processed JWTs. That class might be more suited to be reused here for JWT access tokens.

**Comment by teddyjtorres** [comment]
Awaiting for new FATs.

**Comment by chunlongliang-ibm** [comment]
when this feature is available? which service release include this feature?

**Comment by teddyjtorres** [comment]
It is in 21.0.0.9 beta. You can try it out by adding the openidConnectClient's accessTokenCacheEnabled and accessTokenCacheTimeout attributes. For the moment, setting tokenReuse="true" is also required. This will change in an upcoming update for opaque tokens.

**Comment by teddyjtorres** [comment]
FATs delivered in https://github.ibm.com/websphere/WS-CD-Open/pull/24449.
