### ISSUE TITLE
Behavior when prepare / snapshot / restore operations fail

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#17431]
For the two phases a checkpoint can be done (`features` and `applications`) the current implementation in the `criu` branch will catch the SnapshotFailed exception and does nothing (prompting the automatic FFDC processing of the exception).

The behavior of this exception case needs to be defined for the different stages of the call to `Checkpoint.snapshot`.  For context here are the stages that happen in Java code:

0) Precheck for criu support
1) A call to all registered `SnapshotHook` services to prepare for the snapshot
2) A call to tell CRIU to dump the current process and terminate the current process of execution
... some time later
3) A native CRIU restore operation resumes the process at the point stage 2 terminated the process
4) If the native CRIU restore operation succeeds then all registered `SnapshotHook` services gathered in step 1 are called to restore from the snapshot.

A SnapshotFailed exception can be thrown by the `Checkpoint.snapshot` method for the following reasons as defined by `SnapshotFailed.Type`

```
    public enum Type {
        UNSUPPORTED,  // if not on Linux or the criu command is not available (precheck at stage 0)
        PREPARE_ABORT,  // If one of the SnapshotHooks fail in prepare (stage 1)
        SNAPSHOT_FAILED, // if the call to criu dump fails (stage 2)
        RESTORE_ABORT; (stage 4)
    }
```
Note there is no type for when the native criu restore operation fails (stage 3) because this will fail before we are able to run any Java code on the restore side.

For the exception types on the prepare/snapshot side (`UNSUPPORTED`, `PREPARE_ABORT`, `SNAPSHOT_FAILED`) the invocation of `server run myServer --checkpoint=<phase>` should terminate with an error of some kind.  This is necessary to ensure a container image build (e.g docker) can fail if a snapshot of the features/applications fails while creating the image.

On the restore side it is unclear if the server run/start should log and error exit with some error code or simply log the error and continue with the server start process.  The configured `com.ibm.wsspi.kernel.service.utils.OnErrorUtil.OnError` enum should probably be checked to see if it is set to FAIL or not.  For example, like this code does `com.ibm.ws.jca.internal.Utils.ignoreWarnOrFail()`

**Comment by vijaysun-omr** [comment]
I agree that it is probably better to define a mode wherein we can start up a server normally if the restore fails. So the `ignoreWarnOrFail` approach seems reasonable to me wherein the default could be `warn` perhaps.

**Comment by vijaysun-omr** [comment]
I am not 100% sure `PREPARE_ABORT` or `RESTORE_ABORT` reasons can be flagged correctly in every case since some of the hooks being run are JVM ones that may put the JVM into a state where it is not possible to allow Java code to run in the future to check the error reasons.

**Comment by vijaysun-omr** [comment]
@tajila may have some thoughts on this sort of reason tracking since we presumably need to create a similar notion at the JVM layer.

**Comment by tajila** [comment]
Overall the following makes sense to me:

```
    public enum Type {
        UNSUPPORTED,  // if not on Linux or the criu command is not available (precheck at stage 0)
        PREPARE_ABORT,  // If one of the SnapshotHooks fail in prepare (stage 1)
        SNAPSHOT_FAILED, // if the call to criu dump fails (stage 2)
        RESTORE_ABORT; (stage 4)
    }
```

The JVM layer is essentially stage 2, so the comment could be `// if JVM hook fails or the call to criu dump fails (stage 2)`
, but perhaps that is an implementation detail that liberty doesn't need to concern itself with. Our intention has always been to make the JVM hooks opaque to the application (in this case liberty).

> Note there is no type for when the native criu restore operation fails (stage 3) because this will fail before we are able to run any Java code on the restore side.

Strictly speaking this isn't true. CRIU could succeed to restore the JVM, but a problem could occur with a JVM restore hook which would cause us to not be able to restore the application. We could decide that if this occurs we just shutown and liberty doesn't have to deal with it. Or we could propagate this up via an exception, in which case I think you need to handle a stage3.

Here is what I had in mind from the JVM API perspective:

```
public class J9CRIUSupport
    public static bool isCRIUSupportEnabled()
    
    //the cpDataDir parameter may not be necessary
    //if this method returns it means the JVM restore was successful, otherwise an exception is thrown 
    public static void checkpointJVM(String cpDataDir) throws UnsupportedOperationException, CheckpointFailedException, RestoreFailedException;
}
```

**Comment by tjwatson** [comment]
Closing this issue.  The JVM has enhanced its exception types so we can detect the different error conditions.  For both checkpoint and restore if a failure occurs then the server process terminates with errors.

On the restore side we log the error and exit and the server script will restart the server "normally" not from a checkpoint process.
