### ISSUE TITLE
Unable to use OpenLiberty server in IntelliJ SpringBoot 

### ISSUE THREAD

**Issue by dbnex14** [OpenLiberty/open-liberty#17435]
I am unable to find any information how to add Open Liberty server to IntelliJ Ultimate and use with SpringBoot app.

- How to add open liberty server to IntelliJ
- Where is the server.xml and how to update it
- How to use all that for a Spring Boot app

**Comment by NottyCode** [comment]
The IntelliJ Ultimate support for WebSphere includes support for Open Liberty. A recent release of IntelliJ updated the name of the server adapter to WebSphere/Liberty:

![image](https://user-images.githubusercontent.com/1906689/121018163-2240ce80-c76c-11eb-9f36-162729a39ec8.png)

The IntelliJ documentation for this is here: https://www.jetbrains.com/help/idea/run-debug-configuration-websphere-server.html

There are also some Open Liberty tools: https://plugins.jetbrains.com/plugin/14856-open-liberty-tools which we blogged about here: https://openliberty.io/blog/2020/09/03/open-liberty-tools-intellij.html and there is a YouTube video: https://www.youtube.com/watch?v=GIIhtdXwJ9A

**Comment by dbnex14** [comment]
That video and blog links you shared are the very reason why I created
ticket about horribly poor documentation.  Not helpful at all.
