### ISSUE TITLE
Evaluate and pull the changes from swagger-core RC4

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty#1744]
Evaluate the list of changes in RC4 and pull in the necessary changes (enhancement and bug fixes). This approach is probably better since we made lots of changes on top of rc3.

https://github.com/swagger-api/swagger-core/releases/tag/v2.0.0-rc4

**Comment by leochr** [comment]
@navidsh please add a comment here about the sub-resource and open separate issue.

**Comment by mrglavas** [comment]
@navidsh Can you open a separate issue for any technical debt and close this one? Thanks.

**Comment by navidsh** [comment]
Created #2417. Closing this one.
