### ISSUE TITLE
I can't enable javaee-8.0 feature

### ISSUE THREAD

**Issue by habeascorpse** [OpenLiberty/open-liberty#1747]
Hello,

when i trying to enable javaee-8.0 feature on server.xml, an error message occour:

 "Uma definição de recurso não pode ser localizada para o recurso javaee-8.0. Tente executar o comando bin/installUtility install javaee-8.0 para instalar o recurso."

it's in portuguese, but it mean that i need to execute the command bin/installUtillity install javaee-8.0
but doesn't exist this command.

**Comment by aguibert** [comment]
hi @habeascorpse, where OpenLiberty driver are you using?  

Note that `javaee-8.0` is not fully completed yet, so you wont' find it in the official released images (e.g. 17.0.0.4).  Right now it's only available in the development builds, both of which can be found on:
https://openliberty.io/downloads/

**Comment by aguibert** [comment]
Closing this issue as I believe it's sufficiently answered by my previous response.  If there are further questions feel free to add more comments and reopen the issue.
