### ISSUE TITLE
Add FAT test for OAuth client registration illegal characters

### ISSUE THREAD

**Issue by ayoho** [OpenLiberty/open-liberty#17501]
Test follow up to #14575.

Add new tests for:
- Attempt to register a new OAuth client with illegal characters in the `client_id` parameter
- Attempt to register a new OAuth client with illegal characters in the `client_secret` parameter

Per the OAuth 2.0 spec, valid characters for these two parameters are in the `%20-7E` range (basically all the printable characters on a standard English keyboard). If a value outside of that range appears anywhere in the values for either of those parameters, the following should occur:
- HTTP 400 response sent back from the OP
- CWWKS1423E message emitted in the OP server log
- JSON error response will be returned back to the browser, which includes:
    - An `"error"` entry with the value `"invalid_client_metadata"`
    - An `"error_description"` entry with the CWWKS1423E message as the value

**Comment by c00crane** [comment]
Adding tests in the WS-CD stream (25861).

**Comment by c00crane** [comment]
Tests merged into integration earlier today.
