### ISSUE TITLE
openidConnectClient sharedKey attribute is not exposed TS005702317

### ISSUE THREAD

**Issue by barbj** [OpenLiberty/open-liberty#17508]
The **openidConnectClient** **sharedKey** attribute is referred to here: https://www.ibm.com/docs/en/was-liberty/core?topic=connect-configuring-json-web-token-authentication-openid , but I don't see it on here: https://openliberty.io/docs/21.0.0.5/reference/config/openidConnectClient.html

It appears to be hidden:
`<AD id="sharedKey" name="internal" description="internal use only" required="false" type="String" ibm:type="password" />`

**Comment by teddyjtorres** [comment]
The public clientSecret attribute should be used. This is consistent with the spec.

```
If the JWT alg Header Parameter uses a MAC based algorithm such as HS256, HS384, or HS512, the octets of the UTF-8 representation of the client_secret corresponding to the client_id contained in the aud (audience) Claim are used as the key to validate the signature.
```

The reference to the internal sharedKey attribute will be removed from the https://www.ibm.com/docs/en/was-liberty/core?topic=connect-configuring-json-web-token-authentication-openid article.
