### ISSUE TITLE
Update com.ibm.ws.jaxrs21.providers.json.JsonBProvider constructor to get rid of the test check

### ISSUE THREAD

**Issue by WhiteCat22** [OpenLiberty/open-liberty#1750]
com.ibm.ws.jaxrs21.providers.json.JsonBProvider relies on getting the javax.json.bind.spi.JsonbProvider from an OSGI service reference. In a testing scenario the service reference is not available. We added a check to determine if we are testing or in production but it isn't a very good solution and we should refactor it.

**Comment by andymc12** [comment]
I'm fine with the "test check" in cases where we know we don't need a JSON-B provider.  But in cases like TCK where we do need one but not in the "pure server" environment where we can use OSGi to find the provider implementation, I created an approach that will look for the JSON-B provider using `ServiceLoader` in PR #1945 .
