### ISSUE TITLE
Investigate jsfContainer-2.3 with MyFaces 2.3-Next

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#17545]
Worth looking into this configuration to see if jsfContainer is compatible with MyFaces 2.3-Next. Initial testings shows it is not, but it may be a trivial fix to address this problem (or not).

MyFaces 2.3-Next is not necessarily the supported implementation as opposed to the preferred regular 2.3.x implementation. Nevertheless, some users may find it useful.

**Comment by pnicolucci** [comment]
We already offer a facesContainer-3.0 and facesContainer-4.0 features so this work isn't necessary at this time. Closing the issue.
