### ISSUE TITLE
Liberty 21.0.0.6 : unexpected CWWKZ0002E+WELD-001408 on injection point wrapped by CDI Portable extension

### ISSUE THREAD

**Issue by ghost** [OpenLiberty/open-liberty#17546]
Dear all,

Suppose to proceed with CDI Portable extension that wrap inject points field type (https://docs.jboss.org/weld/reference/latest/en-US/html/extend.html#_wrapping_an_injectiontarget) as follow:

A) server.xml feature == "javaee-7.0"

B) In application code, suppose the following injection point

    @Inject @MyQualifier private MyInterface injectPoint;

C) Having in a jar dependency 

- a CDI portable extension that, for MyQualifier annot, override the inject field type as follow (any type to Object.class) :

		class MyCDIExtension implements javax.enterprise.inject.spi.Extension {
		...

			<X> void processAnnotatedType(@Observes ProcessAnnotatedType<X> pat, BeanManager beanManager) {
				AnnotatedTypeBuilder<X> builder; //usage of deltaspike as a facility
				for (AnnotatedField<? super X> f : pat.getAnnotatedType().getFields())
				{
					if (f.isAnnotationPresent(MyQualifier.class)) {
						builder = null!=builder ? builder : new AnnotatedTypeBuilder<X>().readFromType(pat.getAnnotatedType()); //usage of deltaspike as a facility
						builder.overrideFieldType(f, Object.class); //usage of deltaspike as a facility to alter inject point from MyInterface to Object
					}
				}
				if (builder != null)
				{
				    pat.setAnnotatedType(builder.create());
				}
			}

- the CDI portable extension declaration (with required beans.xml)

		META-INF/services/javax.enterprise.inject.spi.Extension
			mypackage.MyCDIExtension

For a not-yet identified reason, in liberty 21.0.0.6, the CDI container metamodel seems to be wrongly constructed, and then implies:

		CWWKZ0002E (...) com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type MyInterface with qualifiers @MyQualifier

which seems to be a non-sens due to the fact that the concerned inject point is not a "MyInterface" anymore but "Object" due to the spi extension.
 
Additional information: 
* the following approach is tested and validated within **Websphere traditional 8.5** + **Websphere traditional 9.0** + **JBoss 6.[3,4]** + **Jboss 7.[0,1,2,3]**)

* org.jboss.weld.*=finest shows that spi ext is seems to be nicely take in charge:

		[15/06/2021 18:11:45:724 CEST] 0000005f id=00000000 org.jboss.weld.manager.BeanManagerImpl                       1 addBean WELD-000106: Bean: Extension [class mypackage.MyCDIExtension] with qualifiers [@Default]; wsjar:file:/F:/(...)myjar.jar!/META-INF/services/javax.enterprise.inject.spi.Extension@1[mypackage.MyCDIExtension@32832269]

		[15/06/2021 18:11:45:725 CEST] 0000005f id=00000000 org.jboss.weld.bootstrap.ExtensionBeanDeployer               1 deployBean WELD-000168: Extension bean deployed: Extension [class mypackage.MyCDIExtension] with qualifiers [@Default]; wsjar:file:/F:(...).jar!/META-INF/services/javax.enterprise.inject.spi.Extension@1[mypackage.MyCDIExtension@32832269]

		[15/06/2021 18:11:45:934 CEST] 0000005f id=00000000 org.jboss.weld.bootstrap.events.ContainerLifecycleEvents     2 fireProcessAnnotatedType Sending PAT using the default event resolver: [BackedAnnotatedType] public  class mypackage.MyCDIExtension

==> Is there any knowed limitations wihtin liberty 21.x around CDI PAT ? a missing feature to declare ? a conflit with [OSGi approach](https://www.ibm.com/docs/api/v1/content/SSD28V_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.spi.cdi_1.0-javadoc/io/openliberty/cdi/spi/CDIExtensionMetadata.html?view=embed) ?

EDIT (retested in a simplied project) : 
* ko with OpenLiberty having server.xml feature == "javaee-7.0" (weld v.2.4.8)
* ko with OpenLiberty having server.xml feature == "javaee-8.0" (weld v.3.1.4 final) 
* ok within jboss7.3 (weld v.3.1.2)

Thank for any help,

**Comment by benjamin-confino** [comment]
Hello @placidetmuzo

I've attempted to recreate this issue, however when I run the test application I wrote (see attached, source is included) I get an `WELD-001409: Ambiguous dependencies` exception. Which is what I would expect when I set the type of an injection point to Object.

I have used `Open Liberty 21.0.0.6/wlp-1.0.53.cl210620210527-1900` and the only feature in my server.xml is `javaee-7.0`. 

Perhaps you could upload your application and I can see if I can reproduce the error if I run your code. 

Regards
Benjamin

> a conflit with OSGi approach ?

The OSGi approach is written to allow Liberty features to add items into CDI's model of an application. You can think of it as adding additional extensions/puesdo extensions to an application. We use it to do things like make JAX-RS and CDI interoperate properly But it's additional extensions, not a change to extensions registered via `META-INF/services/javax.enterprise.inject.spi.Extension`

**Comment by ghost** [comment]
Hello @benjamin-confino,

Thanks for your reply. (I’m afraid I missed your attached source)

You'll find at 
[https://github.com/placidetmuzo/cdiext](https://github.com/placidetmuzo/cdiext)
the effective cleaned part mentionned above, linked to a "SimpleRestApi" class for test, that could be executed as follow:

        cd <path>/cdiext
        mvn liberty:run

If needed, here is the workflow

http request -> SimpleRestApi -> @Inject MyInterface [solved as Object from GenericDelegateExtension] -> GenericDelegateProducer -> "This is ok" as Object implementation.

Expected Behavior : http://127.0.0.1:9080/cdiext/simplerestapi display ["This is ok"] as response.
Obtained Behavior : message (Open Liberty 21.0.0.6/wlp-1.0.53.cl210620210527-1900)

       CWWKZ0002E: (...) : com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type MyInterface with qualifiers @GenericDelegateQualifier
      [INFO]   at injection point [BackedAnnotatedField] @Inject @GenericDelegateQualifier private com.cdryx.SimpleRestApi.anInterface
      [INFO]   at com.cdryx.SimpleRestApi.anInterface(SimpleRestApi.java:0)


FYI, re-tested ok on JBoss 7.3 using http://127.0.0.1:8080/cdiext/cdiext/simplerestapi

regards,

**Comment by benjamin-confino** [comment]
[RecreateInjectionFailure.zip](https://github.com/OpenLiberty/open-liberty/files/6669173/RecreateInjectionFailure.zip)
Let me try upload again, then I'll look at your source.

**Comment by benjamin-confino** [comment]
A quick update to keep you in the loop: I've verified that this works if I create a proxy class and inject that into the `@Path` endpoint. My suspicion is that this difference in behavior is due to the way JAX-RS manually invokes CDI to do it's injection, I think that the CDI extension is updating CDI's metamodel but not JAX's metamodel so this proxy class moves the updated fields away from JAX's metamodel. 

To test this theory I am porting the application to jakarta to run against a development branch where JAX-RS integrates into CDI the proper way to see if the application will start working there. [Edit] The test was negative.

**Comment by ghost** [comment]
Hello, @benjamin-confino 

I think I have a part of explanation of the observed unexpected behavior : please have a look at branche https://github.com/placidetmuzo/cdiext/tree/WORKAROUND
* addition of IYamlSpec
* move of REST annot from SimpleRestApi to IYamlSpec

As soon as the REST annotations are moved to an external interface, then CDI seems not to scan so early the @Inject MyInterface  then everything initialize and run nicely.

In our complete WAS 8.5 / WAS 9.x project, that is the exact implementation so that everything work well also in this traditional IBM env.

So, is the behavior difference between WAS/Tradi/Liberty and Jboss may be due to the fact that Jaxrs implementations are different ? could be I suppose

**Comment by ghost** [comment]
Hello @benjamin-confino 
There was a message collision ... yes, I'm agree : moving @path is a solution.

Thank again for your help.

**Comment by benjamin-confino** [comment]
@placidetmuzo I'm very glad you found a solution. 

I've identified what's going on behind the scenes but it's complicated. The JAX team will be investigating their CDI interop to see if they can prune the codepath that leads to us hitting this error.

**Comment by ghost** [comment]
@benjamin-confino Thank you for the information. The structure I belong to is very interessed in any change/corrective/additional information around this subject.
regards,
