### ISSUE TITLE
Feature Test Summary - Enable JPA bind literal as parameter at a server scope

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#17551]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

### List of FAT projects affected

* com.ibm.ws.jpa.tests.jpaconfig_jpa_2.1_fat
* com.ibm.ws.jpa.tests.jpaconfig_jpa_2.2_fat
* com.ibm.ws.jpa.tests.jpaconfig_jpa_3.0_fat

### Test strategy

* What functionality is new or modified by this feature?

    * This new JPA enhancement adds the ability to declare "default" JPA persistence properties, to all container-managed persistence contexts, as a Liberty server.xml configuration.

* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)

    * We have basic tests that set "default" persistence properties in server.xml and verify those properties are being picked up by the persistence provider.
    * We have more complex tests that set duplicate persistence properties in server.xml and persistence.xml. These tests validate that if duplicate properties exist in both locations, yet reference different values, those defined in the new server.xml "default" properties will override those defined in persistence.xml; as defined in JPA Specification section 3.4.4.3.
    *  We have tests that set duplicate persistence properties in server.xml and ejb-jar.xml. These tests validate that persistence properties passed through EJB deployment descriptor `persistence-context-ref` override those defined in the new server.xml "default" properties.

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

    * There are no manual tests

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

- [ ] 0 - No automated testing delivered

- [ ] 1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

- [ ] 2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

- [ ] 3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

- [x] 4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

- [ ] 5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by dave-waddling** [comment]
Hi, having reviewed this Feature Test Summary all looks to be good. Please can you add the 'FAT Complete' label to the parent epic to confirm all of the code is delivered, at that point I'll check the SOE results before granting the approval. Cheers!

**Comment by tkburroughs** [comment]
@dave-waddling Ah, thanks, I couldn't remember the label name; `FAT complete` has now been added.

BTW, it seems that instructions for adding that label have been removed from the process documentation... I thought it used to be described in the process; but I could not find that information; now it just seems to indicate to add the `target:ga` label to indicate FAT is complete and ready for review.  May want to get that added back into the FTS template.

Perhaps the template isn't the correct place, but I couldn't find it documented in the development process.

**Comment by dave-waddling** [comment]
Hi @tkburroughs,

You're right about it missing from the process documentation, I'll follow up and see if it's been purposefully removed or just gone missing! Thanks for pointing that out.

All of the testing is passing cleanly in the latest SOE and as per my previous comment I've reviewed the FTS and all looks good. I'll add the approval to the parent epic now.

**Comment by tkburroughs** [comment]
FAT complete; closing
