### ISSUE TITLE
Feature Test Summary for LG-313: MicroProfile Health 3.1

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/open-liberty#17550]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

### List of FAT projects affected

FAT tests will include the MP Health Check 3.1 TCK - this currently passes 100%, which was added under the io.openliberty.microprofile.health.3.1.internal_fat_tck project.

### Test strategy

* What functionality is new or modified by this feature?
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

The TCK tests the following:

    SingleReadinessSuccessfulTest
    SingleReadinessFailedTest
    SingleLivenessSuccessfulTest
    SingleLivenessFailedTest
    SingleStartupSuccessfulTest
    SingleStartupFailedTest
    OnlySuccessfulProcedureTest
    NoProcedureSuccessfulTest
    MultipleReadinessFailedTest
    MultipleProceduresFailedTest
    MultipleLivenessFailedTest
    MultipleStartupFailedTest
    JsonSchemaValidationTest
    HealthCheckResponseAttributesTest
    HealthCheckResponseValidationTest
    DelayedCheckTest
    ConfigTest
    CDIProducedProceduresTest
    EnforceQualifierTest
    DelegateHealthSuccessfulTest

A new FAT project was also created as io.openliberty.microprofile.health.3.1.internal_fat, to test the Liberty specific scenarios when using MP Config property to test the ability to change the default overall startup status for Startup Health Checks. The test suite (DefaultOverallStartupStatusUpAppStartupTest) includes a positive test case (testDefaultStartupOverallStatusUpAtStartUpSingleApp), also a negative test case (testInvalidDefaultStartupOverallStatusProperty). 

Another test suite  (SlowAppStartupHealthCheckTest) was added in the above bucket, which tests the application startup states in Open Liberty. The following test case (testSlowAppStartUpHealthCheck) tests whether if a deployed application is slow to start up, the startup endpoint should return DOWN, until all the deployed applications have started. Another test case (testStartupEndpointOnServerStart) tests the startup endpoint, as soon as the server starts. The startup end point will be continuously polled, until it returns 200 response code, once all the deployed applications have started. This test mimics how the Kubernetes Startup probe work.

Additionally, the existing com.ibm.ws.microprofile.health.2.0_fat project was modified to repeat some tests for mpHealth-3.1 feature.

Manual testing was also completed, to verify the basic functionality.

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

4
The current automated testing that we have, adequately tests a broad spectrum of features offered by our updated project.

**Comment by ayoho** [comment]
LGTM 👍
