### ISSUE TITLE
Configuration to add public url

### ISSUE THREAD

**Issue by AthreyVinay** [OpenLiberty/open-liberty#17561]
I am trying to find a configuration setting to specify a public url instead of accessing swagger ui on /openapi/ui. Is there one for this? Thanks

**Comment by Azquelt** [comment]
Hi, not quite sure what you're asking.

Most of the config options are listed in the spec for MP OpenAPI [1.x][1x-config] or [2.0][20-config]. These are MP Config properties, so you can set them anywhere that MP Config looks (e.g. system properties (in `bootstrap.properties`), environment variables or `<variable>` entries in server.xml)

If your application is exposed at a public URL and the generated OpenAPI documentation is not correctly pointing to it, you may need to set `mp.openapi.servers` to have the public URL included in the OpenAPI document (which will then be read by the swagger UI).

If you're trying to have the swagger UI appear somewhere other than `/openapi/ui` then I don't think there's a config option for that. The openapi documentation is always at `/openapi` and the UI at `/openapi/ui`. If you're running liberty behind a web server, you may be able to configure that make the swagger UI appear at a different place, but I think the UI will expect to be able to load the openapi document from `/openapi`.

If you're trying to do something else, then please do explain your scenario in more detail. Also, please include which features you have in your server.xml.

[1x-config]: http://download.eclipse.org/microprofile/microprofile-open-api-1.1/microprofile-openapi-spec.html#_core_configurations
[20-config]: https://download.eclipse.org/microprofile/microprofile-open-api-2.0/microprofile-openapi-spec-2.0.html#_core_configurations

**Comment by AthreyVinay** [comment]
Hi @Azquelt - thanks for responding & apologies for the confusion.
So the feature I have enabled is:
`<feature>microProfile-3.0</feature>`

So what I am trying to do is something like this property here: 
`mp.openapi.extensions.liberty.public.url=/v1/this_is_an_example_uri/api` but this gets enabled only when `openapi-3.0` feaure is enabled.

I don't mind getting the openapi doc from `/openapi`. But is there a way to get it from `/v1/this_is_an_example_uri/openapi` & ui from `/v1/knowledge_accelerators/openapi/ui` ? This is what I am trying to do. Thanks in advance.

**Comment by Azquelt** [comment]
No, there's currently no way to do that in liberty.

As you noted, the `openapi-3.0` feature did have this option, but the `mpOpenApi` features stick more closely to just what's in the specification.

**Comment by AthreyVinay** [comment]
So if my application is deployed in a cluster with other applications, how would I specify the route to the swagger doc?

Is there a workaround?

**Comment by AthreyVinay** [comment]
Thank you so much for the call @Azquelt and discussing about the workarounds.

As advised, I will raise a feature request for the above with more details, thanks again. ⭐
