### ISSUE TITLE
Configuration property to change /openapi/ui and /openapi route

### ISSUE THREAD

**Issue by AthreyVinay** [OpenLiberty/open-liberty#17573]
**Is your feature request related to a problem? Please describe.**
I want to modify the the location of where I find the ui and docs from `/openapi/ui` and `/openapi` to a more customizable uri.
Something like `/this_is_an_example_uri/openapi/ui`

**Describe the solution you'd like**
A configuration property like: `mp.openapi.extensions.liberty.public.url=/v1/this_is_an_example_uri/api`  available in `openapi-3.0` feature.

**Describe alternatives you've considered**
Add a static openapi.yaml file and serve it up as an endpoint.

**Additional context**
more info from here: https://github.com/OpenLiberty/open-liberty/issues/17561

**Comment by ilovechai** [comment]
Usecase: Allow mpOpenApi to support multiple applications deployed on separate servers. 

https://github.com/OpenLiberty/open-liberty/issues/16628 solves mpOpenApi to support multiple applications on a single server which means that in the above use case, the mpopenapi endpoint will still collide with applications using mpopenapi in separate servers. 

Solution would be to allow customizing public url configuration property `mp.openapi.extensions.liberty.public.url` like in `openapi-3.0`

Impact: 
- endpoint collison with other applications in separate servers
- prevents from upgrading to Jakarta as Jakarta uses mpOpenApi3.0

**Comment by malincoln** [comment]
I discussed with @Azquelt and this is still valid.

**Comment by tevans78** [comment]
This is being worked under https://github.com/OpenLiberty/open-liberty/issues/25011

**Comment by Azquelt** [comment]
This function has been delivered in 23.0.0.12.
