### ISSUE TITLE
criu dump switch required by liberty (file locks)

### ISSUE THREAD

**Issue by sebratton** [OpenLiberty/open-liberty#17639]
We need a dump to capture file locks via the criu_set_file_locks(true) api for example.
And the restore command must be be issued with the --file-locks switch.

Liberty utilizes file locks to ensure only one server can access the workarea and to support checking for server status. 

It might make sense to provide a more general mechanism to set criu dump switches via the open J9 API.

**Comment by tjwatson** [comment]
The server script has been updated to use `--file-locks` on restore and the OpenJ9 API has the method org.eclipse.openj9.criu.CRIUSupport.setFileLocks(boolean) which we call from Liberty to checkpoint.  I think we are done here.
