### ISSUE TITLE
JavaMail tries to use a resource file that only exists in the implementation

### ISSUE THREAD

**Issue by Thihup** [OpenLiberty/open-liberty#17666]
**Describe the bug**
The JavaMail 1.6 API tries to use a resource file that only exists in the implementation

**Expected behavior**
The javax.mail.Session constructor (from `wlp/dev/api/spec/com.ibm.websphere.javaee.mail.1.6_1.0.53.jar`) tries to load the resource `/META-INF/javamail.default.address.map`, that is required. However, this file only exists in the implementation (`wlp/lib/com.ibm.ws.com.sun.mail.javax.mail.1.6_1.6.53.jar`) and it is not able to find it, so it causes a warning to show up:
```
[WARNING ] expected resource not found: /META-INF/javamail.default.address.map
```

**Diagnostic information:**
 - OpenLiberty Version: 21.0.0.6
 - Java Version: 
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
Eclipse OpenJ9 VM AdoptOpenJDK-16.0.1+9 (build openj9-0.26.0, JRE 16 Linux amd64-64-Bit Compressed References 20210421_23 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - cea22090ecf based on jdk-16.0.1+9)

**Additional context**
https://github.com/eclipse-ee4j/mail/blob/v1.x/mail/src/main/java/javax/mail/Session.java#L255
https://github.com/eclipse-ee4j/mail/blob/v1.x/mail/src/main/java/javax/mail/Session.java#L1101

**Comment by NottyCode** [comment]
In the server runtime Liberty loads javax.mail.Session from the `wlp/lib/com.ibm.ws.com.sun.mail.javax.mail.1.6_1.6.53.jar` the jar in `wlp/dev` is only there for compiling the code, not for runtime. Are you trying to use the jar in `wlp/dev` in a client JVM, or are you seeing the error in the Liberty server runtime? If the latter I suspect something else is going on.

**Comment by Thihup** [comment]
I'm seeing the error in the Liberty runtime. 
Actually, I was trying to find out why it wasn't finding the resource, so I searched for the warning message and I've found it in the two jars. However, only one of them has the resource. So I had a feeling that it could be the cause, but I'm not sure yet.
I'm not including any javax.mail in the application, just including the javaMail-1.6 feature.

**Comment by Thihup** [comment]
Maybe it is missing something like:
```
  <property name="resources" type="String" value="META-INF/javamail.default.address.map"/>
```
in the `com.ibm.ws.javamail_1_6_1_6.ResourceProvider.xml`?

**Comment by Thihup** [comment]
I gave it a try and including it in the `wlp/lib/com.ibm.ws.javamail.1.6_1.6.53.jar/OSGI-INF/com.ibm.ws.javamail_1_6_1_6.ResourceProvider.xml` the warning did not show up.

**Comment by andymc12** [comment]
@neuwerk should this file be visible to user apps?
This file ( https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.javamail.1.6/bnd.bnd ) seems to indicate that only the `META-INF/mailcap` file is required, but maybe that changed between 1.5 and 1.6?

Assuming that this file needs to be user-visible, the fix should be to add it to the `app-resources` list on line 53.  

@Thihup thanks for testing that out.  Assuming it is the right solution, would you be interested in opening a PR for it?

**Comment by Thihup** [comment]
@andymc12  I'm not entirely sure if this file should be user-visible, but the constructor of javax.mail.Session tries to load it. As I don't have experience with OSGi, I don't know if it is possible to just "export" this resource to the API.
I could open the PR, sure.

**Comment by andymc12** [comment]
@Thihup yeah, it sure sounds like it should be loaded by the user.  In OSGi, you can only export packages - so we use a Resource Provider mechanism to enable loading of resource files - like ServiceLoader files, etc.  That's what ends up creating the ResourceProvider.xml file that you edited. 

To add this file, you just need to add it to the bnd file as another entry for `app-resources` - separated by a pipe (`|`) like this:
```
app-resources= \
  META-INF/mailcap |\
  META-INF/javamail.default.address.map
```
in the bnd file: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.javamail.1.6/bnd.bnd

Thanks again for catching this!

**Comment by neuwerk** [comment]
@Thihup thanks for opening this issue! @andymc12 is totally right and the way to fix this is by adding `javamail.default.address.map` to the `app-resource` header. The only thing I want to add, is that there are two other resources for defaults that I believe should also be added. It would be super helpful if you could open a PR for the fix, but would you mind including the other missing resources like so? 

```
app-resources= \
  META-INF/javamail.default.address.map | \
  META-INF/javamail.default.providers | \
  META-INF/javamail.charset.map | \
  META-INF/mailcap

**Comment by neuwerk** [comment]
Also, forgot to say please feel free to reach out if you run into any issues making the changes.

**Comment by Thihup** [comment]
FYI: https://github.com/OpenLiberty/open-liberty/pull/17673

**Comment by neuwerk** [comment]
@Thihup the build results were good, so I've reviewed and merged the PR for you!

**Comment by Thihup** [comment]
As the fix was merged I'm closing this issue.
