### ISSUE TITLE
FTS: Allow mpOpenAPI to support multiple applications and modules

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#17700]
## Test Strategy

For #16628 

The basic requirements for this feature are:
* Merge several OpenAPI documents into a single document
* Provide a way of configuring which applications should documented using OpenAPI

Merging OpenAPI documents is not straightforwards due to the number of elements in an OpenAPI document which must be unique. Here is the strategy used for merging each part of an OpenAPI document:
* Paths and servers
  * Paths lists all the different paths accessible within the application. Servers lists the base URL of the server. The server and path are combined to get the full URL for the operation.
    * servers can be declared at the top level, for a particular path or for a particular operation
  * If all servers present at the top level end with the application context root (or if the document contains no servers), the context root is removed from each server and prepended to each path
  * This ensures that the full URL for each path remains the same, but that paths from different applications do not clash (since the application context root will be unique)
  * If two documents to be merged still contain the same path, the second document cannot be included in the merged documentation and a warning is emitted.
  * After making these changes, if the servers at the top level in all the documents to merge is not identical, the servers are removed from the top level and copied under each path
* Operation IDs
  * Operations may declare an ID and if they do it must be unique
  * If two documents to be merged contain identical operation IDs, then the second one is renamed and references to it updated
* Components
  * Each component is a reusable object that can be referenced from multiple places within the document
  * If two documents to be merged contain a component of the same type with the same name:
    * if they're identical, the second one is omitted
    * if they're not identical, the second one is renamed and all references to it are updated with the new name
* Info
  * Provides information about the application being documented
  * If the info section is identical across all documents to be merged, it is retained in the merged documentation
  * If it is not identical, it is replaced by a basic section which indicates that the documentation has been merged from multiple applications
* security
  * Indicates the authorization required to access the application
  * If this section is identical across all documents to be merged, it is retained in the merged documentation
  * If it is not identical, it is removed and copied under each operation which doesn't already declare its own security requirements
* tags
  * Provides a logical grouping of operations
  * Tags may be defined at the top level, or they may be referenced elsewhere in the document without prior definition
  * If two documents declare a tag with the same name and definition, the second copy is omitted
  * If two documents declare a tag with the same name but a different definition, the second copy is renamed and references to it updated
  * If a tag is used without prior definition, it is not changed
* externalDocs
  * provides a link to external documentation
  * If this section is identical across all documents to be merged, it is retained in the merged documentation, otherwise it is removed
* extensions
  * most parts of the model can have extensions added (free-form key-value pairs where the key must begin "x-")
  * if two models to be merged define an extension with the same key but different values at the top level of the model, this is detected as a clash, the models are not merged and a warning message is emitted

We provide the following configuration options:
* `mp.openapi.extensions.liberty.merged.include` - `(all | first | (<appname>[/<modulename>], ...))`
  * Configures which modules should have OpenAPI documentation generated
* `mp.openapi.extensions.liberty.merged.exclude` - `(none | (<appname>[/<modulename>], ...))`
  * Configures which modules should not have OpenAPI documentation generated
  * Overrides `.include`
* `mp.openapi.extensions.liberty.merged.info` - JSON formatted info section
  * Overrides the contents of the info section.
  * Applied after any merging of documentation is complete, so that the user can provide a new info section for the merged documentation.

### List of FAT projects affected

* io.openliberty.microprofile.openapi.2.0.internal_fat

### Test strategy

* Merging OpenAPI documents and resolving clashes
  * Unit tests
    * All unit tests are of the form "when merging these input documents, do we get exactly this output document" and therefore implicitly test basic merge behaviour.
    * Test that the context root is prepended to each path when no servers are present
      * Test that when servers are present at the top level and do not end with the context root, the context root is not prepended to each path
      * Test that when servers are present at the top level and do end with the context root, the context root is removed from each server and prepended to each path
      * Test that when servers are present under paths or operations and end with the context root, the context root is removed from each server and prepended to each path
    * Test that when two documents to be merged contain different server definitions at the top level, the servers definitions are removed from the top level and added to each path in the document.
    * Test that if, after attempting to prepend the context root, two models contain the same path the second model is not merged and an appropriate merge problem message is generated
    * Test that when component names clash, the component from the second model is renamed and all references to it are updated
      * Test that when component names clash but the components themselves are identical, the component is not renamed  references are not updated and the second instance of the component is simply omitted
    * Test that if operation IDs clash, the operation ID from the second model is renamed and all references to it are updated
    * Test that tag clashes are handled correctly
      * If tag declarations have the same name but a different definition, then the tag in the second document is renamed and references updated
      * If tag declarations are identical, the tag declaration from the second document is omitted and references are unchanged
      * If the tag is not declared but is used, the reference is kept as-is
    * Test that when security requirements declared at the top level are not identical, they are removed from the top level and copied under each operation
    * Test that if the documents to merge contain an identical externalDocs section, it is retained in the merged document but otherwise it is removed.
    * Test that if the documents to merge contain an identical info section, it is retained in the merged document but otherwise it is replaced by a basic info section saying that it is documentation merged from several apps.
    * Test that a model which is not merged due to an unresolvable clash does not cause components or tags to be renamed.
    * Test that if two documents to be merged contain clashing extensions at the top level, the second model is not merged and an appropriate merge problem message is generated #19218
  * Existing unit tests
    * The older `openapi-3.1` feature provided a similar ability to merge OpenAPI documentation when used with the `mpOpenApi-1.0` feature. It had some unit tests for the merge logic which we've adapted to run against `mpOpenApi-2.0`.
  * FAT Tests
    * With the server configured to merge all applications
      * Test that when one application is deployed, its OpenAPI document is returned with no changes
      * When more applications are deployed, their OpenAPI documents are merged
      * When an application is removed, its documentation is removed from the merged OpenAPI document
      * When an EAR is deployed, OpenAPI documentation is generated for each web module and merged
      * A deployed war which doesn't contain a JAX-RS application is ignored
      * A deployed war within an ear which doesn't contain a JAX-RS application is ignored
      * When two applications with clashing paths are deployed, a Warning is emitted listing the path which clashed and the modules which contained that path.

* Configuration tests
  * FAT tests
    * With no configuration, an OpenAPI document is only generated for the first module deployed (retaining the current behaviour)
      * Test with both .war and .ear
    * include config can be set to a list of app names, OpenAPI documents are only generated and merged for those applications
    * include config can be set to all and exclude config set to an app name, OpenAPI documents are generated for all apps other than the excluded app
    * include config can be set to appname/modulename to select a single war within an ear. OpenAPI documentation is only generated for this war
    * include config can be set to all and exclude config set to a list of appname/modulename to exclude wars within an ear. OpenAPI documentation is generated for the other modules
    * info config can be set to override the info section when two wars are deployed and their documentation merged
    * info config can be set to override the info section when one war is deployed (i.e. info still overridden when no merging is done)
    * If info config is invalid JSON, an error is emitted and the config is ignored
    * If info config contains an info section which is missing a required field (e.g. title or version), an error is emitted and the config is ignored

* Manual tests
  * Deploy two apps with merging enabled and check that the OpenAPI UI can be used to test operations
  * Note that the UI is mostly a just Swagger UI so we do not expect new issues as long as we have created a correct OpenAPI document

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Our confidence level is:

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

**Comment by dave-waddling** [comment]
Hi @Azquelt, 

This Feature Test Summary is looking good but please can you add your confidence level?
 
Also I note that PR #19218 didn't make it into this week's SOE so approval will be blocked until the next SOE (the one launched next Friday).

**Comment by Azquelt** [comment]
Thanks @dave-waddling, I've discussed it with the team and we've agreed on 4 as our confidence level.

**Comment by dave-waddling** [comment]
Hi @Azquelt, thanks for adding the confidence. The testing is passing cleanly in the latest SOE so I'll add the approval to the parent epic now. Thanks!
