### ISSUE TITLE
BETA BLOG - MP 4.1

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#17738]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty. For this post to be included in the beta issue please make sure that this is completed by the end of Friday following the GM (Wednesday). 

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name (eg WebSockets feature): `MicroProfile 4.1`
   
   Short feature name (eg websockets-1.0): `microProfile-4.1`

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.
`Application developer and operation`
3. Write a paragraph to summarises the update, including the following points:
   MicroProfile 4.1 improves developer experience with updates to the Health  feature. MicroProfile 4.1 also defines compatible implementation requirements for runtimes, which must pass all of the MicroProfile component specification TCKs including Config 2.0, Fault Tolerance 3.0, Rest Client 2.0, Health 3.1, Metrics 3.0, Open Tracing 2.0, Open API 2.0, and JWT propagation 1.2. This beta driver will be used as a compatible implementation for releasing MicroProfile 4.1.
   
   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.
   Include the following in the server.xml to enable the MicroProfile 4.1 feature in Open Liberty:
<feature>microProfile-4.1</feature>
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?
[MicroProfile 4.1 Release](https://github.com/eclipse/microprofile/releases/tag/4.1-RC1)
## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by jakub-pomykala** [comment]
live [here](https://openliberty.io/blog/2021/07/12/logging-format-21008-beta.html)
