### ISSUE TITLE
BETA BLOG - Jakarta EE 9.1 convenience features

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/open-liberty#17737]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty. For this post to be included in the beta issue please make sure that this is completed by the end of Friday following the GM (Wednesday). 

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name (eg WebSockets feature): Web Profile 9.1, Jakarta EE 9.1 and Jakarta EE 9.1 client
   
   Short feature name (eg websockets-1.0): webProfile-9.1, jakartaee-9.1 and jakartaeeClient-9.1

2. Who is the target persona? Who do you expect to use the update? application developers

3. Write a paragraph to summarises the update, including the following points:

Jakarta EE 9.1 convenience features are included in this beta release in the all beta zip file, but not the Jakarta EE 9 beta zip file.  The 9.1 features are duplicates of the Jakarta EE 9.0 convenience features.  In the future the 9.0 convenience features will be removed and only the 9.1 ones will remain.  Users of the Jakarta EE 9 convenience features should look to transition to use 9.1 in preparation of 9.0 being removed.   
   
   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.

To enable Jakarta EE 9.1 features you would add them to your server.xml or client.xml feature list such as:

```
<featureManager>
    <feature>webProfile-9.1</feature>
</featureManager>
```

```
<featureManager>
    <feature>jakartaee-9.1</feature>
</featureManager>
```

```
<featureManager>
    <feature>jakartaeeClient-9.1</feature>
</featureManager>
```
   
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by jhanders34** [comment]
This issue is associated with Epic #16115

**Comment by jakub-pomykala** [comment]
live [here](https://openliberty.io/blog/2021/07/12/logging-format-21008-beta.html)
