### ISSUE TITLE
Create MP 4.1 TCK Certification for Observability MP Specs (Health, Metrics, OT)

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/open-liberty#17730]
Similar to what we did for MP 4.0 TCK certifications, we have to create a TCK certifications PR for the MP 4.1 release with the Open Liberty 21.0.0.8-beta release build. The build will be available after this weekend's (July 3-4th) SOE run. (Watch out in the #was-microprofile Slack channel for the build to use to extract the TCK results from).

Open Liberty Certifications Repo: https://github.com/OpenLiberty/certifications

For reference, I have linked the previous TCK results PR for the MP Specs for MP 4.0, where the layout should be similar to new MP 4.1 Specs (MP Health 3.1 (new), MP Metrics 3.0, MP OpenTracing 2.0):

MP Health 3.0: https://github.com/OpenLiberty/certifications/pull/75
MP Metrics 3.0: https://github.com/OpenLiberty/certifications/pull/80
MP OpenTracing 2.0: https://github.com/OpenLiberty/certifications/pull/74

**Comment by fmhwong** [comment]
PR for Health and OT: https://github.com/OpenLiberty/certifications/pull/101

**Comment by Channyboy** [comment]
Metrics: https://github.com/OpenLiberty/certifications/pull/102

**Comment by fmhwong** [comment]
Both PRs are merged
