### ISSUE TITLE
Enable Varargs EL Tests After Update to Tomcat EL 10.0.8

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#17750]
Varargs Bug Fix --  #17447

Currently, we are using 10.0.7.  Done in Update  -- #17669 

Tests are currently skipped, and will need to be enabled. 

10.0.8 contains the complete varargs fix for expression language.

**Comment by pnicolucci** [comment]
closing this as we'll do the update here :https://github.com/OpenLiberty/open-liberty/issues/18322
