### ISSUE TITLE
mpReactiveMessaging-1.0 conflicts with microProfile-4.0

### ISSUE THREAD

**Issue by RuiBaiXYZ** [OpenLiberty/open-liberty#17829]
**Describe the bug**
[ERROR   ] CWWKF0033E: The singleton features mpConfig-1.3 and mpConfig-2.0 cannot be loaded at the same time.  The configured features mpReactiveMessaging-1.0 and microProfile-4.0 include one or more features that cause the conflict. Your configuration is not supported; update server.xml to remove incompatible features.

**Steps to Reproduce**
start openliberty server

**Expected behavior**
OpenLiberty Server is normally started.
Do we have a plan to update mpReactiveMessaging to support _[MicroProfile Reactive Messaging 2.0](https://github.com/eclipse/microprofile-reactive-messaging/releases/tag/2.0)_

**Diagnostic information:**
 - OpenLiberty Version: 21.0.0.7
 - Java Version:
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
Eclipse OpenJ9 VM AdoptOpenJDK-11.0.11+9 (build openj9-0.26.0, JRE 11 Linux amd64-64-Bit Compressed References 20210421_975 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - 7796c80419 based on jdk-11.0.11+9)

``` 
- server.xml configuration (WITHOUT sensitive information like passwords)
```
  <!-- Enable features -->
  <featureManager>
    <feature>beanValidation-2.0</feature>
    <feature>javaMail-1.6</feature>
    <feature>jpa-2.2</feature>
    <feature>localConnector-1.0</feature>
    <feature>microProfile-4.0</feature>
    <feature>concurrent-1.0</feature>
    <feature>mpReactiveMessaging-1.0</feature>
 </featureManager>
```
[messages.log](https://github.com/OpenLiberty/open-liberty/files/6805646/messages.log)

**Additional context**
Relative resources:
#15440
https://github.com/eclipse/microprofile-reactive-messaging

**Comment by tevans78** [comment]
mpReactiveMessaging-1.0 and microProfile-4.0 are not supported together. I am going to change this from a bug to an enhancement request.

**Comment by bcoveny** [comment]
+1

Cannot use newer features due to dependency issues.  Can be frustrating not being able to utilize features and having to regress back to manual workarounds.

**Comment by RuiBaiXYZ** [comment]
Ref to this ticket
#19889
