### ISSUE TITLE
Liberty OP fails RP-initiated logout with an ID token signed using the RS256 algorithm

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/open-liberty#17842]
The OP fails with the following message when the RP calls the end_session_endpoint with an ID token that was signed using RS256:

> CWWKS1625E: The OpenID Connect provider failed to validate the ID token due to [com.ibm.ws.security.openidconnect.token.IDTokenValidationFailedException: Exception Message:java.lang.String incompatible with java.security.Key
	at com.ibm.ws.security.openidconnect.token.JWT.verifySignatureOnly(JWT.java:507)
	at com.ibm.ws.security.openidconnect.web.OidcEndpointServices.processEndSession(OidcEndpointServices.java:422)

The expected behavior is for the OP to logout the end user the ID token is for.

**Comment by SebaM** [comment]
Team, any updates here?

**Comment by ayoho** [comment]
Tests added in GHE under 29197 on April 12th.
