### ISSUE TITLE
BETA BLOG - New method to determine active endpoints

### ISSUE THREAD

**Issue by brenthdaniel** [OpenLiberty/open-liberty#17864]
1. Which Liberty feature(s) does your update relate to?
    None - This is part of the Liberty kernel and does not apply to any specific feature

   Human-readable name (eg WebSockets feature): N/A
   
   Short feature name (eg websockets-1.0): N/A

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.
    Operations can use the new method to monitor endpoint activation. Liberty embedders can use the new method to determine when endpoints are available for use. 

3. Write a paragraph to summarises the update, including the following points:
   
   The ServerEndpointControlMBean can currently be used to pause and resume endpoints, including HTTP and messaging ports. It can also determine if an endpoint is currently paused. However, there is no way to determine programmatically if an endpoint exists and is active. This update provides a new method on the mbean, isActive, that will determine if an endpoint exists, has started, and is not paused.

**Comment by ryan-storey** [comment]
Beta blog is now in prod!

**Comment by ryan-storey** [comment]
Blog live [here](https://openliberty.io/blog/2021/08/06/important-fixes-21008.html)!
