### ISSUE TITLE
mpOpenTracing errors shouldn't veto the call being traced

### ISSUE THREAD

**Issue by jwalcorn** [OpenLiberty/open-liberty#17875]
**Describe the bug**
If you enable MicroProfile OpenTracing, and something goes wrong when the feature tries to create a trace span, that shouldn't cause the whole call being traced to fail.

If there is a stack trace, please include the FULL stack trace (without any `[internal classes]` lines in it). To find the full stack trace, you may need to check in `$WLP_OUTPUT_DIR/messages.log`
This was a problem reported by someone using the UI microservice in my Stock Trader sample (https://github.com/IBMStockTrader/trader), so I don't have the actual stack trace, just this screenshot which shows that a NoSuchMethodError caused the whole REST call to fail.
![image](https://user-images.githubusercontent.com/28963246/125858789-3f41f42f-77ca-4efc-b4ed-20f4102b4f6a.png)

**Steps to Reproduce**
They used my current Trader microservice, which expects to be run with MicroProfile 4.0, so it bundles the MP4 level Jaeger client jars in its WEB-INF/lib.  But they mistakenly built that on an older Docker image of Open Liberty, from some time in first quarter (I'd guess perhaps 21.0.0.2), when they ran my Docker build.  So that led to the mismatch.

**Expected behavior**
Obviously this wouldn't work - I'm not complaining that trace spans didn't get created.  I just would like it to be that such exceptions would get caught, and a nice message output in the log, but still let the REST call complete successfully.  No one would want to miss out on a million dollar payment because of a problem creating a trace span for Jaeger.

**Diagnostic information:**
 - OpenLiberty Version: [e.g. 19.0.0.8]
 - Java Version: [i.e. full output of `java -version`]
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`
I didn't get this from the guy that reported the issue, and he's since fixed the problem (I told him to `docker pull` a newer Open Liberty and that did indeed fix the problem) and no longer has the environment available.  But I'm pretty sure running any app that bundles the 1.5.0 level of the Jaeger client jar in its war on a release of Liberty from before MP 4.0 came in would cause the problem.

**Additional context**
This wasn't using any fancy mpOT code, like the `@Traced` annotation.  It was just the tracing that happens automatically for JAX-RS calls.  That makes it especially pernicious, that even if you aren't trying to use mpOpenTracing in your code, the stuff that happens automatically is enough to veto your business logic.

**Comment by tonyreigns** [comment]
This has been resolved in #19461 . Closing issue.
