### ISSUE TITLE
MicroProfile metrics not working on @RequestScoped bean

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/open-liberty#1791]
I added an @Gauge metric to a service method (see https://github.com/gcharters/cloud-native-examples/blob/master/serviceC/src/main/java/test/ServiceC.java).  When this service is @RequestScoped, if I hit the service endpoint twice, the second request fails with the exception shown below.  I believe this is because we get a second instances and MP Metrics is trying to defines the same Metric again.  Should the metrics be class-based rather than instance-based?

[INFO] [ERROR   ] SRVE0315E: An exception occurred: java.lang.Throwable: java.lang.IllegalArgumentException: A metric named test.ServiceC.numProps already exists
[INFO] 	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5006)
[INFO] 	at [internal classes]
[INFO] Caused by: java.lang.IllegalArgumentException: A metric named test.ServiceC.numProps already exists
[INFO] 	at com.ibm.ws.microprofile.metrics.impl.MetricRegistryImpl.register(MetricRegistryImpl.java:163)
[INFO] 	at [internal classes]
[INFO] 	at test.ServiceC$Proxy$_$$_WeldClientProxy.getProperty(Unknown Source)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] 	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:633)

**Comment by Channyboy** [comment]
Clarification of this issue in mpmetric spec: https://github.com/eclipse/microprofile-metrics/pull/367
An ID item will be opened to clarify this in our knowledge center documentation as well.
