### ISSUE TITLE
TBASIC Logging Format Option - Feature Test Summary

### ISSUE THREAD

**Issue by tonyreigns** [OpenLiberty/open-liberty#17938]
For #15910 

This feature introduces a new logging format option into Liberty, TBASIC, which matches the tWAS basic logging format. The new format option already exists in Liberty for the BASIC trace format and was built on the default logging code, so the logic is mostly the same. 

The fat project affected is: **com.ibm.ws.logging_fat**
Tests added: 
**- testTBasicConsoleFormat()** - Tests that when the TBASIC format option is configured for console.log, the resulting logs are in the TBASIC format. This is confirmed using REGEX.

**-  testTBasicFormatWithClassMessage()** - Tests that when the TBASIC format option is configured for console.log using a custom servlet that provides a method name, the resulting logs will display the method name provided and that they're in the TBASIC format. This is confirmed using REGEX. The method name will never appear unless provided and the logging format is set to TBASIC.

**- tBasicHeaderTest()** - Tests that when the TBASIC format option is configured for messages.log, the resulting logs are in the TBASIC format. This is confirmed using REGEX.

The FAT tests created ensure that when the TBASIC format option is used, the resulting logs are in the TBASIC format. This is tested for both messages and console logs.  No tests were created for the trace format option as no new functionality was added, The TBASIC alias was added under the existing case for the BASIC logging format in a switch statement , which has several FAT tests already.

Manual tests were done by setting the logging format options using several of the methods available, such as using server.xml, server.env, and bootstrap.properties. During every manual test, we ensured that the configured logging format was reflected in the logs. There are no negative outcomes to entering an incorrect logging format name as the messages, console and trace logs all have defaults that they will fall back on.

This is a very basic logging format that is almost identical to the default logging formats along with a few changes to the spacing and characters displayed for the package name. These changes have already been in the 21008 beta and have been tested extensively. 

Our confidence rating is a 4.

**Comment by tonyreigns** [comment]
@ayoho I'd appreciate it if you could review this when you have a chance, thank you.

**Comment by tonyreigns** [comment]
Looks like Adam's away.

@mhldr Please review when you're able to, thank you.

**Comment by sabolo** [comment]
Approved
