### ISSUE TITLE
JavaEESecCDIExtension.processAnnotatedType receives events for all annotated types

### ISSUE THREAD

**Issue by neilgsyoung** [OpenLiberty/open-liberty#1794]
While working on issue #1659 I noticed that when I bring up an OL server with appSecurity-3.0 and cdi-2.0 features I get the Weld message,

`Observer method [BackedAnnotatedMethod] public com.ibm.ws.security.javaeesec.cdi.extensions.JavaEESecCDIExtension.processAnnotatedType(@Observes ProcessAnnotatedType<T>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.`

@Emily-Jiang tells me that receiving all events will impair performance and this should be fixed.

**Comment by Emily-Jiang** [comment]
You should use @WithAnnotations and supply the type of classes you wish to observe. Otherwise, the performance will suffer. Please see ValidationExtension.java for an example usage.

**Comment by toshiyamamoto** [comment]
This issue will be resolved once https://github.com/OpenLiberty/open-liberty/pull/1931 is merged.

**Comment by toshiyamamoto** [comment]
This issue should be resolved by now. Please verify and close the issue. Thank you.

**Comment by toshiyamamoto** [comment]
Since there is no response from the originator and I have verified this issue has been resolved, it is being closed. If there is any problem with it, please reopen.

**Comment by neilgsyoung** [comment]
I'm sorry to be slow to look at this Toshi. I can confirm that  your fix does address this issue. Thank you.
