### ISSUE TITLE
Fix SRVE8501E Warning 

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#17950]
**Describe the bug**  
If mpMetrics-2.3 (or monitor-1.0) & some servlet feature are enabled with `enableTraditionalPMI` set as true, we’ll encounter the following warning:
`[WARNING ] SRVE8501E: The servlet container did not load with an acceptable version.`

This occurs because of when WebContainer.addGlobalListener() and  WebContainer.setVersion() and called (Note: Different classes) 

 https://github.com/OpenLiberty/open-liberty/blob/2fd4a880754c37a988c5ed9ac4f1ea5988e465d6/dev/com.ibm.ws.webcontainer.monitor/src/com/ibm/ws/webcontainer/monitor/WebContainerMonitor.java#L59 
 
 https://github.com/OpenLiberty/open-liberty/blob/36aa8032bc2d47b6d4e332052ff2221f71a52e3b/dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/WebContainer.java#L1569
 
 The occurs here getServletContainerSpecLevel call occurs here. 
 https://github.com/OpenLiberty/open-liberty/blob/c237b98426d1be2cbff9731d5b0560332d43e33a/dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/WebContainer.java#L325
 
 Current behavior fails to add listener to the `sessionIdListeners`  list. 
 ________
 
**Steps to Reproduce**  
Enable the mpMetrics-2.3 (or monitor-1.0) feature & some servlet feature with `enableTraditionalPMI` set as true,

**Expected behavior**  
The `[WARNING ] SRVE8501E: The servlet container did not load with an acceptable version.` is avoided and`javax.servlet.http.HttpSessionIdListener` are correctly added to the list.

**Additional context**  
This issue is similar to one that occurred in JSPExtensionFactory when updating the spec level version for Pages-3.0

**Comment by volosied** [comment]
Spoke to Tom Watson about this.  There doesn't appear to be any simple direct solution. Otherwise, we'd need to significantly refactor the com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/WebContainer class.

I tried adding `; start-phase:=CONTAINER_LATE` to the com.ibm.ws.webcontainer.monitor bundle to have it load later, but that didn't resolve the problem. 

I'm thinking we need to create a queue of listeners and then add those once the setVersion method  is called.

**Comment by mbroz2** [comment]
@volosied the info you have in the description is good, but can you please update the description of this release bug so that it follows/conforms to the [Bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)

**Comment by mbroz2** [comment]
@pnicolucci can you handle ^ in Volodymyr's absence?

**Comment by pnicolucci** [comment]
@mbroz2 done.
