### ISSUE TITLE
Testing and test framework for CRIU

### ISSUE THREAD

**Issue by sebratton** [OpenLiberty/open-liberty#17968]
What do we need to test:
- All liberty features should function correctly through a feature checkpoint/restore. To do this a representative subset (TBD) of features tested by FATS in OL and CL will need to be tested through checkpoint/restore. (can we leverage the feature verifier here)?
- A subset of application technologies (ejb, jaxrs, etc. ) will need to be tested through an application checkpoint restore.
- From time to time a new feature may be added which breaks under checkpoint-restore. The feature developer will need to fix with a hook(s). A general framework is needed to facilitate adding new tests of this.
- Testing CRIU framework itself. Much can be accomplished via unit test
- Testing in container - a suite of testing specialized for in container work flows is needed
- Need testing the bin/server script for criu functionality.

Until openJ9 with the needed criu support is released, we will need a specialized build queue that uses a non-released j9 VM.

**Comment by tjwatson** [comment]
Sam, it may be good to get issues opened for remaining test infrastructure we need, or link existing ones to put in the InstantOn backlog here.

**Comment by tjwatson** [comment]
I'm going to close this as done.  We can open a new issue if we need additional tracking for a test framework for InstantOn
