### ISSUE TITLE
`@Schema(multipleOf = )` can throw `NumberFormatException` in `mpOpenAPI-2.0` feature

### ISSUE THREAD

**Issue by rslemos** [OpenLiberty/open-liberty#17972]
I'm trying to use attribue `multipleOf` of `@org.eclipse.microprofile.openapi.annotations.media.Schema` but I've found some minor bugs.

(in all cases the field I'm annotating with `@Schema` is a `BigDecimal` field)

**With `multipleOf = 1`, then upon application deploy the server shows:**

> [INFO] [ERROR   ] CWWKO1650E: Validation of the OpenAPI document produced the following error(s):
> [INFO]
> [INFO]  - Message: The Schema Object must have the "multipleOf" property set to a number strictly greater than zero, Location: #/components/schemas/...

Either the validation is wrong and `multipleOf = 1` should be accepted. Or the message should go "...strictly greater than one".

Even with such an "ERROR", the OpenAPI document is generated, with `multipleOf = 1`. (IMHO this message should then be downgraded to a WARNING).

Edit: a separate issue was opened for this: #18002 

**With `multipleOf = 0.99999d` (or `0.5`) I've got:**

The same as with `multipleOf = 1`: same misleading error message, the generated OpenAPI document is ok, with `multipleOf = 0.99999` (or `0.5`).

**With `multipleOf = 0.1` (or `0.1d`, or `0.2`, or `0.0001d`, or `1.1d`, or `1.1`), I've got:**
> [INFO] [ERROR   ] CWWKO1661E: An error occurred when processing application margem-intraday_service and an OpenAPI document was not produced. The error was: java.lang.NumberFormatException.

The OpenAPI document is mostly empty (as promised by the error message):
```yaml
---
openapi: 3.0.3
info:
  title: Generated API
  version: "1.0"
servers:
- url: http://localhost:9080
- url: https://localhost:9443
paths: {}
```

(in ffdc):

> Exception = java.lang.NumberFormatException
> Source = io.openliberty.microprofile.openapi20.ApplicationProcessor
> probeid = 239
> Stack Dump = java.lang.NumberFormatException
>         at java.math.BigDecimal.<init>(BigDecimal.java:497)
>         at java.math.BigDecimal.<init>(BigDecimal.java:383)
>         at java.math.BigDecimal.<init>(BigDecimal.java:809)
>         at java.math.BigDecimal.valueOf(BigDecimal.java:1277)
>         at io.smallrye.openapi.runtime.io.schema.SchemaFactory.readAttr(SchemaFactory.java:329)
>         at io.smallrye.openapi.runtime.io.schema.SchemaFactory.readSchema(SchemaFactory.java:156)
>         at io.smallrye.openapi.runtime.scanner.dataobject.AnnotationTargetProcessor.readSchemaAnnotatedField(AnnotationTargetProcessor.java:312)
>         at io.smallrye.openapi.runtime.scanner.dataobject.AnnotationTargetProcessor.processField(AnnotationTargetProcessor.java:160)
>         at io.smallrye.openapi.runtime.scanner.dataobject.AnnotationTargetProcessor.process(AnnotationTargetProcessor.java:64)
>         at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.lambda$depthFirstGraphSearch$1(OpenApiDataObjectScanner.java:262)
>         at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
>         (... many java.util.stream frames ...)
>         at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
>         at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.depthFirstGraphSearch(OpenApiDataObjectScanner.java:262)
>         at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.process(OpenApiDataObjectScanner.java:213)
>         at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.process(OpenApiDataObjectScanner.java:160)
>         at io.smallrye.openapi.runtime.io.schema.SchemaFactory.introspectClassToSchema(SchemaFactory.java:477)
>         at io.smallrye.openapi.runtime.io.schema.SchemaFactory.readClassSchema(SchemaFactory.java:365)
>         at io.smallrye.openapi.runtime.io.schema.SchemaFactory.readSchema(SchemaFactory.java:217)
>         at io.smallrye.openapi.runtime.io.schema.SchemaFactory.readSchema(SchemaFactory.java:80)
>         at io.smallrye.openapi.runtime.io.schema.SchemaFactory.readSchema(SchemaFactory.java:65)
>         at io.smallrye.openapi.runtime.io.mediatype.MediaTypeReader.readMediaType(MediaTypeReader.java:49)
>         at io.smallrye.openapi.runtime.io.content.ContentReader.readContent(ContentReader.java:53)
>         at io.smallrye.openapi.runtime.io.requestbody.RequestBodyReader.readRequestBody(RequestBodyReader.java:124)
>         at io.smallrye.openapi.runtime.scanner.spi.AnnotationScanner.processRequestBody(AnnotationScanner.java:782)
>         at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.processResourceMethod(JaxRsAnnotationScanner.java:402)
>         at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.lambda$processResourceMethods$0(JaxRsAnnotationScanner.java:252)
>         at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
>         at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
>         at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
>         at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
>         at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
>         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
>         (... many java.util.stream frames ...)
>         at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
>         at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.processResourceMethods(JaxRsAnnotationScanner.java:250)
>         at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.processResourceClass(JaxRsAnnotationScanner.java:220)
>         at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.processResourceClasses(JaxRsAnnotationScanner.java:196)
>         at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.scan(JaxRsAnnotationScanner.java:126)
>         at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.scan(OpenApiAnnotationScanner.java:118)
>         at io.smallrye.openapi.runtime.OpenApiProcessor.modelFromAnnotations(OpenApiProcessor.java:136)
>         at io.smallrye.openapi.runtime.OpenApiProcessor.modelFromAnnotations(OpenApiProcessor.java:117)
>         at io.openliberty.microprofile.openapi20.ApplicationProcessor.generateModel(ApplicationProcessor.java:263)
>         at io.openliberty.microprofile.openapi20.ApplicationProcessor.processWebModule(ApplicationProcessor.java:200)
>         at io.openliberty.microprofile.openapi20.ApplicationProcessor.processApplication(ApplicationProcessor.java:112)
>         at io.openliberty.microprofile.openapi20.ApplicationRegistry.processApplication(ApplicationRegistry.java:136)
>         at io.openliberty.microprofile.openapi20.ApplicationRegistry.addApplication(ApplicationRegistry.java:70)
>         at io.openliberty.microprofile.openapi20.ApplicationListener.applicationStarting(ApplicationListener.java:45)
>         at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:51)
>         at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStarting(StateChangeServiceImpl.java:50)
>         at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:547)
>         at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:508)
>         at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:349)
>         at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
>         at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:149)
>         at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1352)
>         at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:897)
>         at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
>         (...)
> 

Here I don't know if `0.1` (or `0.2` or `0.0001d`) is a valid value for this property (though I could not find any spec strictly forbidding it). Any way the error report should be cleaner. At least it could say in which annotation it choked (the "Location: #/components/schemas/..." part I've got earlier with `multipleOf = 1`).

**With `multipleOf = 1.9` (or `2.5d`), I've got:**

Everything works fine. No error message. OpenAPI document correctly generated.

**Expected behavior**
I was trying to document my endpoint to tell that it accepts decimal values no more precise than `0.0001` (i.e. a `BigDecimal` with scale 4). To this end I've tried `multipleOf = 0.0001d`.

I don't know if the specs allow for fractional `multipleOf`. If not, then I expect a clearer error/warning message stating the fact (actually in this case I'd expect the attribute `multipleOf` to be `int`).

**Diagnostic information:**
 - OpenLiberty Version: 21.0.0.6/wlp-1.0.53.cl210620210527-1900
 - Java Version:  Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_271-b09 (en_BR)
 - server.xml configuration 
   > Installing features: [jsonb-1.0, jndi-1.0, cdi-2.0, passwordutilities-1.0, jdbc-4.2, localconnector-1.0, ejblite-3.2, jaxrs-2.1, concurrent-1.0, appsecurity-3.0, mpopenapi-2.0, beanvalidation-2.0, jpa-2.2, mphealth-3.0]
 and one minor oddity related to `<classloader apiTypeVisibility="+third-party" commonLibraryRef="..."/>`

**Comment by Azquelt** [comment]
Hi, thanks for reporting this.

> Either the validation is wrong and `multipleOf = 1` should be accepted. Or the message should go "...strictly greater than one".

The message is correct, the validation check is wrong. The validation checks for schema objects come from [JSON Schema Validation][json-schema-validation] and [5.1][multiple-of-validation] lists this requirement for `multipleOf`.

I think I can see the bug in the validation code, I will make a fix and add a test.

> **With multipleOf = 0.1 (or 0.1d, or 0.2, or 0.0001d, or 1.1d, or 1.1), I've got:**
> 
>    [INFO] [ERROR ] CWWKO1661E: An error occurred when processing application margem-intraday_service and an OpenAPI document was not produced. The error was: java.lang.NumberFormatException.

This part surprises me, I'm not sure why we should get a `NumberFormatException` when converting from a `double` in the `@Schema(multipleOf)` annotation to a `BigDecimal`. I'll have to do some more investigation to reproduce the problem and find out why this is happening.

[json-schema-validation]: https://datatracker.ietf.org/doc/html/draft-wright-json-schema-validation-00
[multiple-of-validation]: https://datatracker.ietf.org/doc/html/draft-wright-json-schema-validation-00#section-5.1

**Comment by rslemos** [comment]
I've started the server in remote debug mode with a breakpoint `BigDecimal.valueOf`.

Here is what I've found at this point, inspecting the callstack:

- at java.math.BigDecimal.valueOf(BigDecimal.java:1277)
  `arg0` is `NaN`;

- at io.smallrye.openapi.runtime.io.schema.SchemaFactory.readAttr(SchemaFactory.java:329)
  `rawValue` is an instance of `Double`, whose value is `NaN`;

- at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.depthFirstGraphSearch(OpenApiDataObjectScanner.java:262)
  `this.rootClassInfo.fields[5].name` matches the field name annotated with the offending `@Schema(multipleOf)`
  `this.rootClassInfo.fields[5].annotations[0].name` is `Schema`
  `this.rootClassInfo.fields[5].annotations[0].values[4].name` is `multipleOf`
  `this.rootClassInfo.fields[5].annotations[0].values[4].value` is `NaN`


So I decided to inspect the fields myself (from inside the server). I've implemented it by means of a `HealthCheck`:

```java
public class BigDecimalReadinessCheck implements HealthCheck {
  private static final String NAME = "bigdecimal";

  public HealthCheckResponse call() {
    HealthCheckResponseBuilder builder = HealthCheckResponse.named(NAME);

    System.getProperties().entrySet().stream()
      .forEach(entry -> builder.withData(entry.getKey().toString(), entry.getValue().toString()));

    try {
      Schema s = MyClass.class.getDeclaredField("myField").getAnnotation(Schema.class);

      return builder
        .up()
        .withData("annotation.multipleOf", String.valueOf(s.multipleOf()))
        .build();
    } catch (Exception e) {
      return builder
        .down()
        .withData("exception", e.getMessage())
        .build();
    }
  }
}
```

Starting the server (got the usual "CWWKO1661E: An error occurred when processing application..." I've mentioned in the OP) and curling for the health url, I've got (omiting any possibly sensitive data):

```json
      {
         "data" : {
            "BigDecimal" : "1.0E-14",
            "annotation.multipleOf" : "1.0E-4",
            "awt.toolkit" : "sun.awt.windows.WToolkit",
            "com.ibm.db2.java.TMClassName" : "com.ibm.wsspi.zos.tx.RRSTXSynchronizationManager",
            "com.ibm.ws.beta.edition" : "false",
            "file.encoding" : "UTF-8",
            "file.encoding.pkg" : "sun.io",
            "file.separator" : "\\",
            "ibm.cds.suppresserrors" : "true",
            "java.awt.graphicsenv" : "sun.awt.Win32GraphicsEnvironment",
            "java.awt.headless" : "true",
            "java.awt.printerjob" : "sun.awt.windows.WPrinterJob",
            "java.class.version" : "52.0",
            "java.rmi.server.hostname" : "127.0.0.1",
            "java.rmi.server.randomIDs" : "true",
            "java.runtime.name" : "Java(TM) SE Runtime Environment",
            "java.runtime.version" : "1.8.0_271-b09",
            "java.specification.name" : "Java Platform API Specification",
            "java.specification.vendor" : "Oracle Corporation",
            "java.specification.version" : "1.8",
            "java.util.logging.manager" : "com.ibm.ws.kernel.boot.logging.WsLogManager",
            "java.vendor" : "Oracle Corporation",
            "java.vendor.url" : "http://java.oracle.com/",
            "java.vendor.url.bug" : "http://bugreport.sun.com/bugreport/",
            "java.version" : "1.8.0_271",
            "java.vm.info" : "mixed mode",
            "java.vm.name" : "Java HotSpot(TM) 64-Bit Server VM",
            "java.vm.specification.name" : "Java Virtual Machine Specification",
            "java.vm.specification.vendor" : "Oracle Corporation",
            "java.vm.specification.version" : "1.8",
            "java.vm.vendor" : "Oracle Corporation",
            "java.vm.version" : "25.271-b09",
            "javax.management.builder.initial" : "com.ibm.ws.kernel.boot.jmx.internal.PlatformMBeanServerBuilder",
            "jdk.attach.allowAttachSelf" : "true",
            "kernel.launch.time" : "50578491287900",
            "line.separator" : "\r\n",
            "org.apache.aries.blueprint.preemptiveShutdown" : "false",
            "org.apache.cxf.stax.allowInsecureParser" : "1",
            "org.jboss.weld.xml.disableValidating" : "true",
            "os.arch" : "amd64",
            "os.name" : "Windows 10",
            "os.version" : "10.0",
            "path.separator" : ";",
            "sun.arch.data.model" : "64",
            "sun.cpu.endian" : "little",
            "sun.cpu.isalist" : "amd64",
            "sun.desktop" : "windows",
            "sun.io.unicode.encoding" : "UnicodeLittle",
            "sun.java.launcher" : "SUN_STANDARD",
            "sun.jnu.encoding" : "Cp1252",
            "sun.management.compiler" : "HotSpot 64-Bit Tiered Compilers",
            "sun.net.http.retryPost" : "false",
            "sun.os.patch.level" : "",
            "user.country" : "BR",
            "user.language" : "en",
            "user.script" : "",
            "user.timezone" : "America/Sao_Paulo",
            "user.variant" : "",
            "wlp.process.type" : "server",
            "wlp.user.dir.isDefault" : "false",
            "wlp.workarea.dir" : "workarea/"
         },
         "name" : "bigdecimal",
         "status" : "UP"
      }
```

So..... the `0.0001d` is there in the classfile. The culprit is somewhere after the reflection and before `BigDecimal.valueOf`.

**Comment by rslemos** [comment]
`javap -p -v` over the class with the field annotated with `@Schema(multipleOf)`: [here I had to omit almost everything]

```
  Compiled from "MyClass.java"
public class my.pkg.MyClass
  minor version: 0
  major version: 52
  flags: ACC_PUBLIC, ACC_SUPER
Constant pool:
    #8 = Utf8               Lorg/eclipse/microprofile/openapi/annotations/media/Schema;
    #9 = Utf8               description
   #17 = Utf8               required
   #18 = Integer            1
   #19 = Utf8               minimum
   #20 = Utf8               -999999999999999.9999
   #21 = Utf8               maximum
   #22 = Utf8               +999999999999999.9999
   #23 = Utf8               multipleOf
   #24 = Double             1.0E-4d
{

  private java.math.BigDecimal myField;
    descriptor: Ljava/math/BigDecimal;
    flags: ACC_PRIVATE
    RuntimeVisibleAnnotations:
      0: #8(#9=s#16,#17=Z#18,#19=s#20,#21=s#22,#23=D#24)

}
SourceFile: "MyClass.java"
```

This also proves that the classfile is correctly compiled and annotated with runtime visible `@Schema(multipleOf = 0.0001d)`.

I hope it helps. I can investigate it further if you need me to.

**Comment by rslemos** [comment]
I've indexed my classes using Jandex (version 2.0.3.Final) and then dumped the index. The annotation comes out as `@Schema(multipleOf = NaN)`.

[This pull request](https://github.com/wildfly/jandex/pull/114) seems to correct a bug related to reading 64-bit values (then they are reinterpreted as IEEE-754 64-bit). Apparently it is targeted to 2.4.0.Final (no due date).

So it is really just a matter of luck which doubles are usable or not (as of now):
- 0.0001d is not (yields NaN);
- 0.00010000000727595762d works;
- 0.00009999997089616955d also works.

**Comment by Azquelt** [comment]
Thanks for the information, that's really helpful and I'll see if we can get some tests added to jandex as well to ensure that PR really fixes the issue you're seeing. It's odd that the PR was merged back in April but hasn't been included in recent releases, I'll try to make sure it does get included in the next release.

I'm going to split this issue in two so that it gets included in the release notes correctly when I fix the first part. I'll create a new issue for the incorrect validation check and this issue will just be for the `NumberFormatException` which I won't be able to fix until we get a new version of jandex.
