### ISSUE TITLE
Move Endpoint API and implementation to independent bundle

### ISSUE THREAD

**Issue by wtlucy** [OpenLiberty/open-liberty#17980]
Similar to #16439 - currently the EndPointInfo API `com.ibm.websphere.endpoint.EndPointInfoMBean` is provided and implemented by the `com.ibm.ws.channelfw` bundle. We should move this into a standalone bundle along the lines of `com.ibm.ws.endpoint` or `io.openliberty.endpoint`. The new bundle will include at least `com.ibm.websphere.channelfw.EndPointMgr`, `com.ibm.websphere.channelfw.EndPointInfo`, and `com.ibm.websphere.endpoint.EndPointInfoMBean`, as well as their implementations. See #18081

**Comment by hutchig** [comment]
It may be possible to test this has a good scope if it removes/replaces the dependancy on the channelfw that one of @wtlucy Bill's prototypes/PRs 
- [ ] Insert Name]
has replacing it with the bundle created by this PR instead.

**Comment by hutchig** [comment]
Done
