### ISSUE TITLE
Wrong char count in ServletOutputStream with non-ASCII characters skips content

### ISSUE THREAD

**Issue by barulheira** [OpenLiberty/open-liberty#18009]
The ServletOutputStream skips the last chars when using `print` or `println` to print content with multi-byte characters in UTF-8.
The amount of chars skipped matches the difference between char count and byte count, on each `print` or `println`.
It doesn't matter whether it's done in the end of the response.
Changing to another encoding (e. g. ISO-8859-1) doesn't fix this.
No problem when using `write` instead of `print`.
No problem when using only ASCII characters.
No problem when using `PrintWriter response.getWriter()`.

**Steps to Reproduce**
Get a `response.getOutputStream()` and print some text with non-ASCII content.
On each `print` or `println`, some characters will be skipped in the end.
`out.println("'ATENÇÃO!'"); // Skips last 2 characters`
will print out:
`'ATENÇÃO`
A minimal web app is attached.

**Expected behavior**
It should print: `'ATENÇÃO!'`

**Diagnostic information:**
Open Liberty 21.0.0.7

**Additional context**
This `s.length()` here may be the cause:
https://github.com/OpenLiberty/open-liberty/blob/16559e1b2c20a373a83185aad2d64b70960f0fee/dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/response/WCOutputStream.java#L199
[bug.zip](https://github.com/OpenLiberty/open-liberty/files/6903599/bug.zip)

Thanks @Thihup

**Comment by wtlucy** [comment]
Thanks for reporting this @barulheira - you're correct, the `WCOutputStream` should be writing the length of the encoded bytes rather than the length of the original string.

**Comment by Thihup** [comment]
FYI, there are more two suspicious calls here:

https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/osgi/response/WCOutputStream31.java#L400

https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/osgi/response/WCOutputStream31.java#L552

**Comment by wtlucy** [comment]
This is fixed with #18022. @barulheira if you'd like to verify the behavior you can check out [this build](http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/personal/_eDz40PRoEeuj_9vf1o2UsA/openliberty-all-21.0.0.9-202108031142.zip), otherwise the fix will be in the 21.0.0.9 release.
