### ISSUE TITLE
Make LibbyBot take account of whether a PR is a draft

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#18039]
Draft PRs are useful for file comparison, collaborating on branches, squad reviews and triggering builds without getting sucked into the mainstream pipeline/process. However, some of the LibbyBot automated actions (characterized as those that involve other people) kick in too early at the draft stage. This is very understandable as they pre-date the existence of draft PRs. It would be useful to choose which actions will be applied to draft PRs (e.g. keep the action on #build), and which ( suggest @OpenLiberty/message-reviewer, L2-reviewer, delivery-reviewers review requests etc ) kick in only on a 'ready for review' real PR and then update LibbyBot to take account of this.

https://github.community/t/dont-run-actions-on-draft-pull-requests/16817
has:
```if: github.event.pull_request.draft == false```
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads
has:
```draft": false,"```
https://docs.github.com/en/rest/reference/pulls
has
``` "draft": false```

**Comment by wraschke** [comment]
Gordon, this isn't where my squad looks at to organize our work. Please open in the other location I had requested. I'm closing this.

**Comment by hutchig** [comment]
I had already raised it here at that point, apologies.

Also, I believe that this is all open source and the fix will be at
https://github.com/OpenLiberty/open-liberty/actions/runs/1094507418/workflow#L7
so that this IS the correct place for the main issue to be raised IMHO.

Nonetheless, I will leave this closed, and have created a similar issue (number 24521)
where you have requested in order for you to manage it in your backlog.
