### ISSUE TITLE
In container checkpoint restore will not do proper signal handling

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#18048]
From #17391

> * Running a shell as PID1 (e.g. by invoking server run without using exec) gets around the problem, but breaks signal handling because the shell will not forward signals to its children by default; the shell script being executed would have to do that explicitly. If signals aren't forwarded things like ctrl+c and docker kill don't work smoothly.
> * Running with docker run --init also gets around the problem and will tell the container runtime to start an init process as PID 1 and run the entrypoint defined in the image as a child; the init process will forward signals automatically.

It is unclear if the `--init` workaround is an acceptable solution in production.  I may be better to fix this without the need for `--init`.  Need to investigate if the restore script can do the proper signal handling.

**Comment by anjumfatima90** [comment]
My investigation shows that both `ctrl+c` and `docker stop` to stop the running docker container are working smoothly without any error messages. I got return code 0 from `docker stop <containerId>; echo "return code = $?"`.

The pstree output also shows:

```
containerd-shim(5694)──server(5715)───criu(5782)───java(5792)──Default Executo(5793)
```
According to @ymanton, The first process after containerd-shim is server, followed by criu, followed by java (with pid=5792), server and criu both run and exit quickly, so java ends up being the main process in the container and will therefore get the signals that Docker forwards to the container.

**Comment by anjumfatima90** [comment]
It seems like I misunderstood the problem here. `docker stop` wasn't working the same as `ctrl+c`. Using `dumb-init` to run as PID 1 to solve this problem. https://github.com/Yelp/dumb-init
```
ENTRYPOINT ["/usr/bin/dumb-init","--rewrite", "15:2", "--"]
```
Docker stop sends SIGTERM (15). It is rewriting to SIGINT (2) which is like ctrl+c to shutdown our server gracefully.

**Comment by tjwatson** [comment]
The work to use dumb-init is done in the `ci.docker` repo for the `beta-instanton` container image.  Closing this as done.
