### ISSUE TITLE
Update Krb5LoginModuleWrapper to use JavaInfo.isAvailable

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#18054]
https://github.com/OpenLiberty/open-liberty/blob/4576c78e465cadf06a5d59ebe631a8df9f8570e1/dev/com.ibm.ws.security.kerberos.auth/src/com/ibm/ws/security/kerberos/auth/Krb5LoginModuleWrapper.java#L38

Suggest replacing the isIBMLoginModuleAvailable method and replacing the `isIBMJdk8` variable...
```
public static final boolean IBM_LOGIN_MODULE_AVAILABLE = JavaInfo.isAvailable(COM_IBM_SECURITY_AUTH_MODULE_KRB5LOGINMODULE);
```

**Comment by utle** [comment]
Fixed by https://github.com/OpenLiberty/open-liberty/pull/17951/
