### ISSUE TITLE
Rename variables in Krb5Common.java

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#18055]
This is a follow on issue from a comment in https://github.com/OpenLiberty/open-liberty/pull/18011/files#r682446808

https://github.com/OpenLiberty/open-liberty/blob/d1b458f48a2826f1535ab31444cc5116f948739e/dev/com.ibm.ws.security/src/com/ibm/ws/security/krb5/Krb5Common.java#L38
https://github.com/OpenLiberty/open-liberty/blob/d1b458f48a2826f1535ab31444cc5116f948739e/dev/com.ibm.ws.security/src/com/ibm/ws/security/krb5/Krb5Common.java#L41

The variable names and comments should not refer to a specific JVM. Instead they should just describe the availability of the classes. e.g. `isIBMKrb5LoginModuleAvailable`. It should be note that this code is the same as described here: https://github.com/OpenLiberty/open-liberty/pull/18053

**Comment by utle** [comment]
Fixed by https://github.com/OpenLiberty/open-liberty/pull/18071
