### ISSUE TITLE
Review OracleHelper.checkIBMJava8()

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#18051]
https://github.com/OpenLiberty/open-liberty/blob/4576c78e465cadf06a5d59ebe631a8df9f8570e1/dev/com.ibm.ws.jdbc/src/com/ibm/ws/rsadapter/impl/OracleHelper.java#L886

https://github.com/OpenLiberty/open-liberty/pull/18011 removed the code's reliance on the JVM vendor string. However, the whole method should be reviewed and improved. In general, we do not want to be checking to see which JVM we are running on; instead we should check if some given function is available.

A number of specific recommendations were made in the review comments for 18011
https://github.com/OpenLiberty/open-liberty/pull/18011/files#r682442147
- perhaps the method would be better named `assertIBMKerberosSupported`
- use JavaInfo.isAvailable("oracle.jdbc.OracleDatabaseMetaData") before trying to load it
- catching Exception seems a little too broad; only catch exceptions which are expected in the event that the Class can not be loaded
- Check that the error messages produced are still accurate

**Comment by njr-11** [comment]
> In general, we do not want to be checking to see which JVM we are running on; instead we should check if some given function is available.

In this case, the kerberos login module is available, but the Oracle JDBC driver doesn't work correctly with it, and Oracle support has told our support team that they don't support it prior to their 21c driver.  There is nothing we can do within our code to specifically ask the Oracle JDBC driver for this information at run time. The best we can do is ask the Oracle JDBC for its version and take action based on what the Oracle support team has told us, and we are already doing that.

> perhaps the method would be better named assertIBMKerberosSupported

That's a good name to replace `checkIBMJava8` with. I'm in favor of changing it.

> use JavaInfo.isAvailable("oracle.jdbc.OracleDatabaseMetaData") before trying to load it

I don't see the point of this. I looked at the implementation of JavaInfo.isAvailable and it attempts to load the class, traps the exception if raised, and returns true or false.  That's the same pattern we already have, except that our code is able to use the correct classloader which has the Oracle driver on it.  JavaInfo.isAvailable uses the thread context class loader and often wouldn't be accurate.

> catching Exception seems a little too broad; only catch exceptions which are expected in the event that the Class can not be loaded

I agree it is unnecessarily broad here, and it would have been preferable to let unexpected exceptions flow back to the caller.  However, given that the code is already written this way, we need to consider if allowing an exception to flow back to the caller could break them where they are currently working.  It seems this is possible, so what little benefit would be derived from doing this is not worth the risk.

> Check that the error messages produced are still accurate

The error message refers specifically to "IBM Java 8 SDK" and seems good enough.
