### ISSUE TITLE
Feature Test Summary for MP Context Propagation 1.3

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#18065]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

### List of FAT projects affected

* com.ibm.ws.concurrent.mp.1.3_fat_tck - created this test bucket to run MicroProfile Context Propagation 1.3 TCK against our mpContextPropagation-1.3 feature.

* com.ibm.ws.concurrent.mp_fat_jakarta - created this test bucket for any new tests that we want to write specifically in the new jakarta packages.  Given that MicroProfile Context Propagation 1.3 doesn't add any new function, we didn't actually need to do this yet, but are just preparing for the future.  We started the bucket out covering a couple of different scenarios from previous MicroProfile Context Propagation releases that should still be working.

   - testCopy - ManagedExecutor.copy was added in 1.2 and should still be working in 1.3. With this method, you should be able to copy from an unmanaged completion stage that lacks context propagation to create a copied stage that uses the managed executor to propagate thread context.

   - testCustomContextIsNotPropagatedByDefault - Verify that custom thread context types are not propagated by the default ManagedExecutorService.

   - testCustomContextIsPropagatedWhenConfigured - Verify that custom thread context types are propagated if configured on the builder.

   - testWithContextCapture - ThreadContext.withContextCapture was enhanced in 1.2 to enable the copied completion stages to have async dependent stages that run on the product's default executor, which for us is the Liberty global thread pool. This enhancement should continue to be in place for 1.3.

### Test strategy

* What functionality is new or modified by this feature?
_**None. The sole purpose of MicroProfile Context Propagation 1.3 is to deliver its TCK with jakarta packages instead of javax, so that implementations can certify against Jakarta EE 9+ features.**_
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
_**Apart from the use of jakarta packages rather than javax, the tests are identical to MP Context Propagation 1.2, and have the same positive/negative testing as before.**_
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)
_**None**_

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

**_4_**

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by ayoho** [comment]
Sounds good to me 👍
