### ISSUE TITLE
Update Smallrye Graphql

### ISSUE THREAD

**Issue by Thihup** [OpenLiberty/open-liberty#18062]
**Is your feature request related to a problem? Please describe.**
The current version of Smallrye Graphql (it seems to be 1.0.9) does not support using records because there is no public constructor without arguments.

**Describe the solution you'd like**
Using a newer version, they allow to use the @JsonbCreator annotation to allow use records.

**Describe alternatives you've considered**
Convert my class back to a normal class

**Additional context**
https://github.com/smallrye/smallrye-graphql/blob/main/common/schema-builder/src/main/java/io/smallrye/graphql/schema/creator/type/InputTypeCreator.java#L93

**Comment by WhiteCat22** [comment]
Hi, thank you for your request. We'll upgrade SmallRye GraphQL in the near future (no ETA yet)

**Comment by WhiteCat22** [comment]
Hi @Thihup, We've upgraded to 1.0.26 as part of https://github.com/OpenLiberty/open-liberty/pull/19364
