### ISSUE TITLE
netty - WebSocket support

### ISSUE THREAD

**Issue by wtlucy** [OpenLiberty/open-liberty#18086]
Update the existing WebSocket implementation `com.ibm.ws.wsoc` to work with netty. There are two important areas to consider: 
1. inbound connections via protocol upgrade
2. outbound connections.

This work is dependent on HTTP support, which will be added via https://github.com/OpenLiberty/open-liberty/issues/18084

**Comment by pnicolucci** [comment]
closing in favor of: https://github.com/OpenLiberty/open-liberty/issues/25473
