### ISSUE TITLE
Feature Test Summary - Configurable Response Headers

### ISSUE THREAD

**Issue by mrsaldana** [OpenLiberty/open-liberty#18109]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

This feature includes a new test file under the existing Web Container servlet 4.0 FAT bucket: `com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCResponseHeadersTest.java`

It makes use of a single servlet and a series of tests that will send requests over to said servlet in order to trigger different scenarios associated to use of the <headers> configuration element. All testing is automated and will be added to the OL repository as part of the configurable response headers beta feature. 

### List of FAT projects affected

* com.ibm.ws.webcontainer.servlet.4.0_fat

**Comment by mrsaldana** [comment]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

This feature includes a new test file under the existing Web Container servlet 4.0 FAT bucket: `com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCResponseHeadersTest.java`

It makes use of a single servlet and a series of tests that will send requests over to said servlet in order to trigger different scenarios associated to use of the <headers> configuration element. All testing is automated and will be added to the OL repository as part of the configurable response headers beta feature. 

### List of FAT projects affected

* com.ibm.ws.webcontainer.servlet.4.0_fat

**Comment by mrsaldana** [comment]
### Test strategy

* What functionality is new or modified by this feature?
The <httpEndpoint> server configuration element will now be able to be configured with a <headers> sub-element. This configuration defines four attribute options: 

1. `add` - Defines a header that will be added to all outgoing responses for the endpoint as if the `HttpServletResponse.addHeader` API was used. 
2. `set` - Defines a header to be set to all outgoing responses for the endpoint as if the `HttpServletResponse.setHeader` API was used. 
3. `setIfMissing` - Defines a header to be set to all outgoing responses for the endpoint only when a header with the configured header name is not already present. 
4.  `remove` - Defines a header that will be removed from all outgoing responses for the endpoint when present. 

Header name and value pairs are delimited by the `:` colon character. 

When the HTTP transport is ready to write out the response, a header compliance method is internally invoked. This method is being updated to consume the configured <headers> values. It will add, set or set if missing, and remove all headers accordingly.  

* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? 

The `WCResponseHeadersTest.java` has a set of tests that evaluates misconfigurations of the <headers> element. The rest of the tests will provide properly configured values. In both cases, a request will be made to the server and the response will be evaluated to see if the expected headers are present. The majority of the tests will use a single servlet on the default application, varying the request parameter to alter application specific headers on the response. This application, regardless of the parameter utilized, will add a `applicationVerificationHeader` header to the response. 

One single test will not use the default application, using instead an existing application on the WebContainer servlet 4.0 bucket that enables login authorization. This will test that the configurable headers are present at each response: before and after successful login is achieved. This tests the specific customer-facing scenario that led to the development of this feature.  

* What manual tests are there (if any)? 
There are no manual tests associated to this feature.

**Comment by mrsaldana** [comment]
### Individual Test Descriptions


The following are descriptions for each test in `WCResponseHeadersTest.java`

1. testHeaderBootstrapping 

> Header Symbolic Configuration
> 
> Tests that the <headers> element can be configured symbolically.  A single bootstrap property for each of the <headers>attributes is written to the bootstrap.properties file when the setUp method is first ran. This test will use those property names within each attribute configuration and test that the response contains all values. The following is a snippet from the set up method showing the key value pairs for the bootstrapping: 
> 
> > writeBootstrapProperty(server, "add.header", "bootstrappedAddHeader:addHeaderValue");
> > writeBootstrapProperty(server, "set.header", "bootstrappedSetHeader:setHeaderValue");
> > writeBootstrapProperty(server, "set.if.missing.header", "bootstrappedSetIfMissingHeader:setIfMissingValue");
> > writeBootstrapProperty(server, "remove.header", "customHeader");
> 
> To test the "remove" option, ${remove.header} will map to the header [customHeader], which is a header added by the application by means of the "testCondition=singleHeader" request parameter. The application will also add the header [appVerificationHeader]. 
> 
> Expectations: 
> Present headers - [bootstrappedAddHeader:addHeaderValue], bootstrappedSetHeader:setHeaderValue], [bootstrappedSetIfMissingHeader:setIfMissingValue], [appVerificationHeader]
> Missing headers - [customHeader]

2. testHeaderMisconfiguration_EmptyHeaderName

> Header Misconfiguration Series Test 1/4
> 
> This test will purposely misconfigure the add, set, setIfMissing, and remove attributes by providing empty header names. It is expected that the empty header name CWWKT0042W message will logged on all four configurations. Therefore, the test specifically checks that 4 instances of CWWKT0042W are present in the log file. 
> 
> Good configurations should continue working. Therefore, this test will also define correct configuration on all attributes. The test will be invoked with the request parameter [testCondition=singleHeader], which will add the response header [customHeader:appValue]. 
> 
> The remove attribute is configured to remove this header, so it is expected to not appear on the response headers. The application will also add the header [appVerificationHeader]. 
> 
> Expected present headers: [addHeader: addValue], [addHeader: addValue2], [setHeader], [setIfMissingHeader], [appVerificationHeader]
> Expected removed header: [customHeader]

3. testHeaderMisconfiguration_DuplicateHeaderName

> Header Misconfiguration Series Test 2/4
> 
> This test will purposely misconfigure the add, set, setIfMissing, and remove attributes by providing duplicate header names. It is expected that the duplicate header name CWWKT0043W message will logged three times.
> 
> Good configurations should continue working. Therefore, this test will also define correct configurations on all attributes. The test servlet will be invoked with the parameter [testCondition=singleHeader], which will add the response header [customHeader:appValue]. 
> 
> The remove attribute will remove this header, so it is expected to not appear on the written response headers. The application will also add the header [appVerificationHeader]. 
> 
> Expected bad header: [badHeader], [anotherBadHeader], [yetAnotherBadHeader] resulting in three CWWKT0043W messages
> Expected present headers: [addHeader:addValue], [addHeader:addValue2], [setHeader], [setIfMissingHeader], [appVerificationHeader]
> Expected removed header: [customHeader]  

4. testHeaderMisconfiguration_PreviouslyDuplicatedHeaderName

> Header Misconfiguration Series Test 3/4
> 
> This test will purposely misconfigure the add, set, setIfMissing, and remove attributes by providing previously duplicated header names. That is, it will provide three times the same header name. It is expected that the previously duplicated header name CWWKT0044W message will logged two times.
> 
> Good configurations should continue working. Therefore, this test will also test correct configurations on all attributes. The test servlet will be invoked with the parameter [testCondition=singleHeader], which will add the response header [customHeader:appValue]. 
> 
> The remove attribute will remove this header, so it is expected to not appear on the written response headers. The application will also add the header [appVerificationHeader]. 
> 
> Bad Headers: [badHeader], [anotherBadHeader] resulting in two CWWKT0044W messages
> Expected present headers: [addHeader], [setHeader], [setIfMissingHeader], [appVerificationHeader]
> Expected removed headers: [customHeader]

5. testHeaderMisconfiguration_CaseInsensitivity

> Header Misconfiguration Series Test 4/4
> 
> This will test that the configuration of the <headers> element are case insensitive. The test will be invoked with the parameter [testCondition=singleHeader], which will add the response header [customHeader:appValue]. This will also add a verification header [appVerificationHeader]. 
> 
> Since the add configuration can add multiple instances of the same header name, casing is irrelevant and will be ignored for the purpose of this test. 
> 
> Test Phase 1: Misconfiguration case-insensitive detection
> 
> > This test phase will misconfigure a header in the set, setIfMissing, and remove attributes by providing the same header name using different casing. It is expected that this will result with the CWWKT0044W "previously detected duplicate header" message.
> 
> Test Phase 2: Case insensitivity when <headers> configuration is consumed by the transport
> 
> > The configuration will test the set attribute by configuring the same header that the application will add to the response in all capital letters: [CUSTOMHEADER: testValue]. It is expected that the resulting response header will contain the value "testValue" and not the application defined "appValue". 
> > 
> > The setIfMissing attribute will be tested by setting the verification header in all capital letters [APPVERIFICATIONHEADER: badValue]. This header is add by the application with no value, so it is expected that no value is found for it. 
> > 
> > The remove attribute will be tested by configuring the date header in all capital letters [DATE]. Every response written by the transport contains a [Date] header, so it is expected that this response not contain it. 
> 
> Expected bad headers: [badHeader] resulting in one CWWKT0044W message
> Expected present headers: [CUSTOMHEADER: testValue], [appVerificationHeader]
> Expected removed header: [Date]

6. testAddHeader

> Simple Configuration Series 1/4: "add" attribute
> 
> Tests that the "add" configuration of the <headers> element is able to properly append multiple headers to the response that are configured with the same name. 
> 
> The application will add the [appVerificationHeader] header to the response. No further application interaction is expected. 
> 
> Expected headers: [customHeader:testValue], [customHeader:testValue2], [appVerificationHeader]

7. testSetHeader

> Simple Configuration Series 2/4: "set" attribute
> 
> Tests that the "set" configuration of the <headers> element is able to properly set the configured header on a response. 
> 
> The application will add the [appVerificationHeader] header to the reponse. No further application interaction is expected. 
> 
> Expected headers: [customHeader: testValue], [appVerificationHeader]

8. testSetIfMissingHeader

> Simple Configuration Series 3/4: "setIfMissing" attribute
> 
> Tests that the "setIfMissing" configuration of the <headers> element is able to properly set the configured header on a response when no other header of the same name is present. 
> 
> The application will add the [appVerificationHeader] header to the response. No further application interaction is expected. 
> 
> Expected headers: [customHeader, testValue], [appVerificationHeader]. 

9. testRemoveHeader

> Simple Configuration Series 4/4: "remove" attribute
> 
> Tests that the "remove" configuration of the <headers> element is able to properly remove the configured header from a response. 
> 
> The configuration will be set to remove any header whose name is [customHeader]. 
> 
> The test servlet will be invoked with the parameter [testCondition=singleHeader], which will add the response header [customHeader:appValue]. The application will also add the [appVerificationHeader] header to the response. The application will also add the [appVerificationHeader] header to the response. No further application interaction is expected. 
> 
> Expected header: [appVerificationHeader]
> Expected removed header: [customHeader]

10. testAddHeaderWithHeaderPresent

> Tests that the "add" configuration of the <headers> element is able to properly append headers to the response without overwriting existing headers that share the same name. 
> 
> A request with the [testCondition=singleHeader] parameter will result in the application adding the header [customHeader:appValue]. The application will also add the [appVerificationHeader] header to the response. 
> 
> Expected headers: [customHeader:testValue], [customHeader:appValue], [appVerificationHeader]

11. testSetHeaderWithHeaderPresent

> Tests that the "set" configuration of the <headers> element is able to properly overwrite an existing header that shares its name with a configured "set" header. 
> 
> The configuration will define the header [customHeader:testValue] on the "set" attribute. 
> 
> The test servlet will be invoked with the parameter [testCondition=singleHeader], which will add the response header [customHeader:appValue]. The application will also add the [appVerification Header] to the response. No further application interaction is expected. 
> 
> It is expected that the app [customHeader] be overwritten by the configuration. 
> 
> Expected headers: [customHeader: testValue], [appVerificationHeader]

12. testSetIfMissingHeaderWithHeaderPresent

> Tests that the "setIfMissing" configuration of the <headers> element does not overwrite an existing header that shares its name with a configured "setIfMissing" header. 
> 
> The configuration will define the header [customHeader:testValue] on the "setIfMissing" attribute. 
> 
> The test servlet will be invoked with the parameter [testCondition=singleHeader], which will add the response header [customHeader: appValue]. The application will also add the [appVerificationHeader] header to the response. No further application interaction is expected. 
> 
> It is expected that the app [customHeader] will not be overwritten by the configuration. 
> 
> Expected headers: [customHeader: appValue], [appVerificationHeader]

13. testRemoveMultipleAppHeader

> Tests that the "remove" configuration of the <headers> element removes multiple all instances of the defined header name. 
> 
> The configuration will use the "add" attribute to define two headers with the same name: [customConfigHeader:testValue] and [customConfigHeader: testValue2]. 
> 
> The test servlet will be invoked with the parameter [testCondition=multipleHeaders], which will add the response headers: [customHeader:appValue] and [customHeader:appValue2]. The application will also add the [appVerificationHeader] to the response. No further application interaction is expected. 
> 
> Expected present headers: [appVerificationHeader]
> Expected missing headers: [customConfigHeader], [customHeader]

14. testCookieHeaders_Add

> Cookie Header Test Series Test 1/4: "add" attribute configuration
> 
> Test the interaction of the <headers> configuration with response Cookie objects and "Set-Cookie" headers. 
> 
> This test will set a request parameter [testCondition=testCookies], which will instruct the servlet to add the following "Set-Cookie" header and Cookie object to the response:
> 
> > response.addHeader("set-cookie", "chocolate=chip; SameSite=None");
> > response.addCookie(new Cookie("vanilla", "sugar"));
> 
> Cookie objects should be converted into "Set-Cookie" headers by the transport. The application will also add the header [appVerificationHeader]. 
> 
> This test specifically tests the "add" configuration with a [set-cookie: oatmeal] header. It is expected that the response will write out all three chocolate, vanilla, and oatmeal cookies in the form of "set-cookie" headers. 
> 
> Expected headers: [set-cookie: chocolate=chip; SameSite=None], [set-cookie: vanilla=sugar], [set-cookie: oatmeal], [appVerificationHeader]

15. testCookieHeaders_Set

> Cookie Header Test Series 2/4 - "set" attribute configuration
> 
> Test the interactions of the <headers> configuration with response Cookie objects and "Set-Cookie" headers. 
> 
> This test will set a request parameter [testCondition=testCookies], which will instruct the servlet to add the following "Set-Cookie" header and Cookie object to the response:
> > response.addHeader("set-cookie", "chocolate=chip; SameSite=None");
> > response.addCookie(new Cookie("vanilla", "sugar"));
> 
> Cookie objects should be converted into "Set-Cookie" headers by the transport. The application will also add the header [appVerificationHeader]. 
> 
> This test specifically tests the "set" configuration with the [set-cookie: oatmeal] header. It is expected that the servlet defined [chocolate] and [vanilla] values be overwritten. 
> 
> Expected present headers: [set-cookie: oatmeal], [appVerificationHeader]
> Expected missing headers: [set-cookie: chocolate=chip; SameSite=None], [set-cookie: vanilla=sugar]

16. testCookieHeaders_SetIfMissing

> Cookie Header Test Series Test 3/4 - "setIfMissing" attribute configuration
> 
> Test the interactions of the <headers> configuration with response Cookie objects and "Set -Cookie" headers. 
> 
> This test will set a request parameter [testCondition=testCookies], which will instruct the servlet to add the following "Set-Cookie" header and Cookie object to the response:
> > response.addHeader("set-cookie", "chocolate=chip; SameSite=None");
> > response.addCookie(new Cookie("vanilla", "sugar"));
> 
> Cookie objects should be converted into "Set-Cookie" headers by the transport. The application will also add the header [appVerificationHeader]. 
> 
> This test specifically tests the "setIfMissing" configuration with the [set-cookie: oatmeal] header. It is expected that the response will be written out with both [chocolate] and [vanilla] "set-cookie" headers. 
> 
> Expected present headers: [set-cookie: chocolate=chip; SameSite=None], [set-cookie: vanilla=sugar], [appVerificationHeader]
> Expected missing headers: [set-cookie: oatmeal]

17. testCookieHeaders_Remove

Cookie Header Test Series Test 4/4 - "remove" attribute configuration

> Test the interaction of the <headers> configuration with response Cookie objects and "Set-Cookie" headers. 
> 
> This test will set a request parameter [testCondition=testCookies], which will instruct the servlet to add the following "Set-Cookie" header and Cookie Object to the response: 
> > response.addHeader("set-cookie", "chocolate=chip; SameSite=None");
> > response.addCookie(new Cookie("vanilla", "sugar"));
> 
> Cookie objects should be converted into "Set-Cookie" headers by the transport. The application will also add the header [appVerificationHeader]. 
> 
> This specifically tests the "remove" configuration with "set-cookie". No "set-cookie" headers are expected. 
> 
> Expected present headers: [appVerificationHeader]
> expected missing headers:  [set-cookie: chocolate=chip; SameSite=None], [set-cookie: vanilla=sugar], [set-cookie: oatmeal]

18. testHeadersDuringLogin

> Tests that the <headers> configuration is applied to all responses in the process of authenticating an end-user to a secure application. The server configuration will configure the "add" attribute with the header [foo:bar]. 
> 
> First Request - 
> Expected  Response Code: 302
> Expected Response Header: [foo:bar]
> 
> Second Request - Login page
> Expected Response Code: 200
> Expected Response Header: [foo:bar]
> 
> Third Request - Perform Login
> Expected Response: 302
> Expected Response Header: [foo:bar]
> 
> Fourth Request - Application Servlet
> Expected Response: 200
> Expected Response Header: [foo:bar]

19. testHeadersNoContextRoot

> Tests that the <headers> configuration is applied to a response that results on a 404 status due to context root not being found. The configuration will define a single [addHeader] under the "add" option.
> 
> Expected present header: [addHeader]
> Expected response status: 404

20. testRemoveMissingHeader

> Tests the "remove" configuration of the <headers> element by specifying a header that will not be present in the response. 
> 
> Expected present header: [appVerificationHeader]
> Expected missing header: [undefinedHeader]
> Expected response status: 200

**Comment by mrsaldana** [comment]
### Confidence Level 

5 - We have delivered all automated testing we believe is needed for this feature. The testing covers all golden path cases as well as all the error/outlying scenarios that make sense. We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

**Comment by ayoho** [comment]
Coverage looks good to me 👍
