### ISSUE TITLE
Confirm that checkpoint-1.0 feature does not support client

### ISSUE THREAD

**Issue by sebratton** [OpenLiberty/open-liberty#18115]
Currently it has
IBM-Process-Types: server

**Comment by tjwatson** [comment]
We originally were going to use the IBM-Process-Types header to control what can be enabled on client vs. server.  But for reasons I don't recall, the list of public features we allow to be enabled on the client is hard coded in the feature manager implementation.

**Comment by tjwatson** [comment]
Discussed with Alasdair.  Current thinking is that we don't have a need to do checkpoint for the client process.
