### ISSUE TITLE
RTC250842: SVT: server url is not generated in /openapi when using META-INF/openapi.json 

### ISSUE THREAD

**Issue by tam512** [OpenLiberty/open-liberty#1812]
- Use Open Liberty build https://rtpgsa.ibm.com/projects/l/liberty.build/liberty/WASX.LIBERTY/daily/20180124-1037.55.linux/linux/zipper/externals/installables/openliberty-all-17.0.0.4-20180124-1123.zip
- Install allergyForecast war file which has META-INF/openapi.json api document
- View api doc at http://aussvt105.rtp.raleigh.ibm.com:85/openapi/ and the server url shows only /  as below.  The url should be http://host:port/ and https://host:https_port
```
openapi: 3.0.0
info:
  title: AllergyForecast REST APIs
  description: Discover REST APIs
  version: 1.0.2
servers:
- url: /
tags:
- name: Allergy Forecast API
  description: Allergy Forecast by location
```
The OL usr directory is at http://ausgsa.ibm.com/projects/w/was_defects/issue1812/usr.zip  .  The application is under apps

**Comment by tam512** [comment]
#link 250842

**Comment by leochr** [comment]
@tam512 where can I find the allergyForecast app? Want to try to replicate the issue.

**Comment by tam512** [comment]
@leochr It is in  http://ausgsa.ibm.com/projects/w/was_defects/issue1812/usr.zip under apps

**Comment by leochr** [comment]
merged fix into team branch

**Comment by mrglavas** [comment]
@tam512 Please verify and close. Thanks.

**Comment by tam512** [comment]
Verified using build https://rtpgsa.ibm.com/projects/l/liberty.build/liberty/WASX.LIBERTY/daily/20180216-1309.27.linux/linux/zipper/externals/installables/openliberty-all-18.0.0.1-20180216-1410.zip
