### ISSUE TITLE
Full  gRPC EE9 FAT Enablement once MP-5.0 is created

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#18137]
Only a portion of our gRPC tests run in the EE9 repeat action.  This is due to many of the servers using mpMetrics-2.3. However, there is no feature replacement to an EE9 compatible version.  

I spoke to Jared Anderson and he said MP 5.0 would be out in the next few months. 

We will follow up then. 

gRPC EE9 Epic -- #16647.

**Comment by pnicolucci** [comment]
I removed this from epic #16647 since this work is not required for GA.
