### ISSUE TITLE
Serviceability / JAX-RS 3.0: Print all JAX-RS endpoints in dump introspector

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#18145]
Part of epic issue #11803: 

Ideally, we would have a dump introspector in `restfulWS-3.0` that would print out all of the endpoints for a given application.

So suppose we have app1.war with the following code:
```
@ApplicationPath("rest")
public class MyApp extends Application {...}

@Path("resource1")
public class MyResource {

    @GET
    public Response get() {...}

    @POST
    @Path("/new")
    public Response postNew(SomeObject so) {...}

    @Path("/sub")
    public SubResource subResource() {
        return new SubResource();
    }

    @DELETE
    @Path("/{id}")
    public Response delete(@PathParam("id") String id) {...}
}

public class SubResource {

    @GET
    public Response getFromSub() {...}
}
```

we would expect to see something like this in the introspector output:
```
app1 endpoints:
- GET /rest/resource1
- POST /rest/resource1/new
- GET /rest/resource1/sub
- DELETE /rest/resource1/{id}
```

It might also be nice to correlate those endpoints to the class/methods of origin like:
```
app1 endpoints:
- GET /rest/resource1 - Resource1#get
- POST /rest/resource1/new - Resource1#postNew
- GET /rest/resource1/sub - SubResource#getFromSub
- DELETE /rest/resource1/{id} - Resource1#delete
```

**Comment by WhiteCat22** [comment]
Did some investigation and I was able to accomplish a crude version by printing out `fullpath` in `org.jboss.resteasy.core.ResourceMethodRegistry.processMethod()`

**Comment by WhiteCat22** [comment]
Next step is to implement the Logging Introspector as a JAX-RS Dynamic Feature.
One improvement is to also print the method parameters.
See #18581, #19023
