### ISSUE TITLE
JSF faces-config parser throws NPE when namespace missing

### ISSUE THREAD

**Issue by wtlucy** [OpenLiberty/open-liberty#18155]
The Jakarta Faces 3.0 changes in https://github.com/OpenLiberty/open-liberty/pull/14427 added logic to check for the new `https://jakarta.ee/xml/ns/jakartaee` namespace in `faces-config.xml` files. Because the new logic uses `String.contentEquals()`, if a `faces-config.xml` file declares a version but not a namespace, a `NullPointerException` will be thrown during app startup:

```Exception = java.lang.NullPointerException
Source = com.ibm.ws.container.service.state.internal.ApplicationStateManager
probeid = 54
Stack Dump = java.lang.NullPointerException
	at java.lang.String.contentEquals(String.java:4086)
	at com.ibm.ws.javaee.ddmodel.jsf.FacesConfigDDParser.createRootParsable(FacesConfigDDParser.java:93)
	at com.ibm.ws.javaee.ddmodel.DDParser.parseRootElement(DDParser.java:590)
	at com.ibm.ws.javaee.ddmodel.jsf.FacesConfigDDParser.parse(FacesConfigDDParser.java:37)
	at com.ibm.ws.javaee.ddmodel.jsf.FacesConfigAdapter.adapt(FacesConfigAdapter.java:53)
	at com.ibm.ws.javaee.ddmodel.jsf.FacesConfigAdapter.adapt(FacesConfigAdapter.java:26)
        ........
```

Note this affects all JSF features on Liberty: `jsf-2.0`, `jsf-2.2`, `jsf-2.3`, and `faces-3.0`. 

As a workaround, `faces-config.xml` descriptors should declare valid namespaces, ie. `http://java.sun.com/xml/ns/javaee`, `http://xmlns.jcp.org/xml/ns/javaee`, or `https://jakarta.ee/xml/ns/jakartaee`.

**Comment by mbroz2** [comment]
@wtlucy @jhanders34 is this actually a release bug?  Isn't this issue only for a feature that is still in beta?

**Comment by jhanders34** [comment]
It applies to all versions of JSF.  We iterate over the list of possible namespaces and if one was not specified in the faces-config xml file, we were getting a NullPointerException.

**Comment by mbroz2** [comment]
Ah, I misread.  The changes made for enablement of Jakarta Faces 3.0 made a breaking change for all versions of JSF.  
I'll make sure this (the affected versions of JSF are not limited to 3.0) is clear in the blog post.... and it would probably make sense to update the description in this issue as well to list all the versions affected or at least call out that they're all affected.

**Comment by wtlucy** [comment]
Good point @mbroz2, I've updated the description here for clarity
