### ISSUE TITLE
Feature Test Summary - 16079 ServerEndpointControl MBean needs isActive method to return true when exists, started, not paused 

### ISSUE THREAD

**Issue by brenthdaniel** [OpenLiberty/open-liberty#18159]
## Test Strategy

* Tests were added to verify behavior of the new method in normal and error scenarios. 

### List of FAT projects affected

* com.ibm.ws.kernel.boot_fat

### Test strategy

* The feature adds a single method to the ServerEndpointControl mbean to determine if an endpoint is available and not paused. 
* Positive tests were added for testing valid endpoints in situations where they are active and when they are paused. Negative tests were added for testing invalid endpoints. 

## Confidence Level

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

**Comment by sabolo** [comment]
Approved
