### ISSUE TITLE
JDT / ECJ will move away from supporting Java 8, make sure JSP supports compiles from Java 8 through 17+ levels

### ISSUE THREAD

**Issue by epj** [OpenLiberty/open-liberty#18169]
JDT will be moving the ECJ code base to Java 11 as minimum compile level as of the 2021-09 release.  So we may need to carry two versions of ECJ, one that supports levels down to Java 8, and one that supports Java 11 through 17 and beyond.

**Comment by volosied** [comment]
Now supports Java 11, 17, and 21 via https://github.com/OpenLiberty/open-liberty/pull/25494
