### ISSUE TITLE
Add support for Extension and Extensions annotations

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty#1818]
Add support for the Extension and Extensions annotations from the MicroProfile OpenAPI spec. Also handle scenarios involving annotations precedence/overrides (if any).

TCK should have some tests to cover these annotations. Ensure that all relevant scenarios are covered. 

- [ ] Extension
- [ ] Extensions

**Comment by leochr** [comment]
@arturdzm please add the extension scenarios we discussed to cover

**Comment by arturdzm** [comment]
Added support for Extensions annotations on Type (OpenAPI) and Method(Operation) level
