### ISSUE TITLE
CDI: Transformed Jakarta EE9 application failed to start 

### ISSUE THREAD

**Issue by jagraj** [OpenLiberty/open-liberty#18186]
**Describe the bug**
We are migrating EE8 application to Jakarta EE9 runtime and we got into following failure. We are packaging apache wink binaries as third party jars in the application and wink.jar has blank beans.xml file and the app fails to start with this. The same application works fine with EE8 runtime.

Here is the failure..

```
[INFO    ] unregistering MBean org.apache.cxf:bus.id=WSBankEJB-Server-Bus,type=Bus,instance.id=1636490514
[INFO    ] unregistering MBean org.apache.cxf:bus.id=WSBankEJB-Server-Bus,WorkQueueManager=Bus.WorkQueueManager,type=WorkQueueManager,instance.id=419418693
[INFO    ] unregistering MBean org.apache.cxf:bus.id=CreditCardEJB-Server-Bus,WorkQueueManager=Bus.WorkQueueManager,type=WorkQueueManager,instance.id=1954498716
[INFO    ] unregistering MBean org.apache.cxf:bus.id=CreditCardEJB-Server-Bus,type=Bus,instance.id=1681040651
[ERROR   ] CWWKZ0106E: Could not start web application GarageSaleLibertyEAR8-LooseConfig.
[ERROR   ] CWWKZ0002E: An exception occurred while starting the application GarageSaleLibertyEAR8-LooseConfig. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DefinitionException: WELD-000071: Managed bean with a parameterized bean class must be @Dependent: class org.apache.wink.common.internal.providers.entity.csv.CsvDeserializerProvider
[INFO    ] SESN8502I: The session manager found a persistent storage location; it will use session persistence mode=DATABASE
[INFO    ] SRVE9103I: A configuration file for a web server plugin was automatically generated for this server at C:\MyData\MyWDTWorkspaces\GarageSale\GarageSaleEE7\garageSale-ee7\GarageSaleRuntimeUtil\target\wlp\usr\servers\garageSaleServer\logs\state\plugin-cfg.xml.

```
Please find the logs as an attachment to this issue.
[CDI_App_Start_Failure.zip](https://github.com/OpenLiberty/open-liberty/files/6983843/CDI_App_Start_Failure.zip)

**Steps to Reproduce**
1. Install WebSphere Liberty beta runtime
2. Deploy application with thirdParty jars packages and one of the jar contains blank beans.xml file 
3. The you will get into this problem.

**Expected behavior**

**Diagnostic information:**
 - OpenLiberty Version: Open Liberty 21.0.0.9-beta/wlp-1.0.55.cl210820210727-1323
 - Java Version: OpenJDK 64-Bit Server VM, version 1.8.0_292-b10
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**

**Comment by Azquelt** [comment]
From the trace, it appears that an extension is making `CsvDeserializerProvider` application scoped:

```
[8/13/21 12:02:32:101 EDT] 00000020 id=00000000 org.jboss.weld.bootstrap.events.ContainerLifecycleEvents     2 fireProcessAnnotatedType Sending PAT using the default event resolver: [BackedAnnotatedType] public @Provider @Consumes class org.apache.wink.common.internal.providers.entity.csv.CsvDeserializerProvider
[8/13/21 12:02:32:104 EDT] 00000020 id=00000000 org.jboss.weld.bootstrap.events.ProcessAnnotatedTypeImpl     1 setAnnotatedType WELD-000148: ProcessAnnotatedType.setAnnotatedType() called by io.openliberty.org.jboss.resteasy.common.component.LibertyResteasyCdiExtension@7dd1e9: org.jboss.resteasy.cdi.JaxrsAnnotatedType@5d88d3f8 replaced by org.jboss.resteasy.cdi.JaxrsAnnotatedType@5d88d3f8
```

The second line isn't too helpful since it doesn't show the details of the annotated type, but later we see this:
```
[8/13/21 12:02:36:406 EDT] 0000003c id=00000000 org.jboss.weld.util.Beans                                    2 getBeanConstructor WELD-001536: Found [] constructors annotated with @Inject for [EnhancedAnnotatedTypeImpl] public @ApplicationScoped @Provider @Consumes class org.apache.wink.common.internal.providers.entity.csv.CsvDeserializerProvider
```

Here, we can see the new annotated type now has the `@ApplicationScoped` annotation.

I can see that `LibertyResteasyCdiAnnotation` is adding the `@ApplicationScoped` scope to all providers which is likely causing the problem.
https://github.com/OpenLiberty/open-liberty/blob/3ff45a5563caa2d3e92d4382e118231d364a35b0/dev/io.openliberty.org.jboss.resteasy.server/src/io/openliberty/org/jboss/resteasy/common/component/LibertyResteasyCdiExtension.java#L90-L102

@andymc12 Do you remember why we do this? Is it a new requirement in JAX-RS 3.0 or just a change in implementation?

**Comment by Azquelt** [comment]
From the [Jakarta RESTful Web Services specification][restful-spec-11-2-3]:
> In a product that supports CDI, implementations MUST support the use of CDI-style Beans as root resource classes, providers and Application subclasses. Providers and Application subclasses MUST be singletons or use application scope.

The same language is in the JAX-RS spec for v2.0 and 2.1 and v1.1 has a similar statement for Managed Beans.

So according to the spec, your `Provider` isn't allowed to be a `Dependent` scoped bean (which is what it will be if you have a beans.xml in the same archive and no other scope annotation on the class).

Although there's no spec change between 2.1 and 3.0, we did change our implementation. While older jax-rs features allowed this, the `restfulws-3.0` feature forces all Providers to be `ApplicationScoped`.

I'm not entirely sure what this spec requirement means in practise when CDI is enabled and the Provider is not a bean at all, but it is fairly clear that if a Provider is a bean, it can't be a Dependent scoped bean.

[restful-spec-11-2-3]: https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#cdi
