### ISSUE TITLE
Update the UI

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty#1823]
- [x] Change the UI endpoint from /api/explorer to /openapi/ui
- [x] Change the default logo to something other than IBM logo (e.g. Open Liberty logo : [logo1](https://avatars3.githubusercontent.com/u/28316667?s=200&v=4) or [logo2](https://www.ibm.com/developerworks/community/blogs/IndustryBPTSE/resource/BLOGS_UPLOADED_IMAGES/OL_logo_stacked_navy_wht-450x170.png) or [logo3](https://openliberty.io/img/small_logo_grey.svg) or [logo4](https://static.oschina.net/uploads/space/2017/0920/085917_LAVb_2720166.png))
- [x] Add test(s) to ensure that the UI endpoint is available. See openapi, apiDiscovery in Commercial Liberty for such tests. Can be reused.

**Comment by mrglavas** [comment]
Selected [logo3](https://openliberty.io/img/small_logo_grey.svg) for the default logo. Use #191C2C as the default background color. This matches very well with the current openliberty.io website.

**Comment by mrglavas** [comment]
This issue is resolved by PRs: arturdzm/open-liberty#53 and arturdzm/open-liberty#59.

**Comment by mrglavas** [comment]
PRs have been merged into the team's collaboration branch.
