### ISSUE TITLE
Feature Test Summary for Concurrency 3.0 for Jakarta EE 10

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#18259]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**
Primarily write new automated test buckets for new specification function, which is extensive.
Where it makes sense, add to existing test buckets, such as the test buckets for interoperability with CDI and MicroProfile.
Instruct the core test bucket for Concurrency, com.ibm.ws.concurrent_fat, to repeat with Jakarta EE 10 features.
Automate the 3.0 version of the Concurrency TCK to run as a Liberty FAT bucket.

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_
The standard test framework is used.

### List of FAT projects affected

* com.ibm.ws.concurrent_fat_jakarta

  ConcurrencyErrorTest:
  - testBeanApplicationFailsToInstall
  - testClassApplicationFailsToInstall
  - getThreadName
  - getThreadNameNonAsyc
  - getState
  - getStateFromService

  ConcurrencyJSPTest:
  - maxAsyncTest: Configure a managed-scheduled-executor within a web fragment and verify that its max-async (1) and context propagation settings are honored.
  - securityPropogatedTest: Uses the default ContextService, which propagates security, to confirm that a ContextService can propagate security context inside a JSP
  - securityClearedTest: Uses java:app/concurrent/securityClearedContextSvc, to confirm that a ContextService can clear security context inside a JSP
  - securityUnchangedTest: Uses java:app/concurrent/securityUnchangedContextSvc, to confirm that a ContextService can leave security context unchanged inside a JSP. Tests both on the thread to confirm Security context is available, and on a separate thread to confirm it is not propagated.
  - threadPriorityTest: Configure a managed-thread-factory within a web fragment and verify that its priority (7) and context propagation settings are honored.

  ConcurrencyTest:
  - testCompletedAndFailedStages: Covers the new ManagedExecutorService API methods: completedStage and failedStage, ensuring propagation of context to dependent stages.
  - testContextServiceDefinitionPropagatesApplicationContext: Look up an application-defined ContextService that is configured to propagate the application component's name space. Verify that the ContextService provides access to the application component's name space by attempting a lookup from a contextualized completion stage action.
  - testContextServiceDefinitionPropagatesThirdPartyContext: Look up an application-defined ContextService that is configured to propagate some third-party context (ZipCode and List), clear other third-party context (Priority and Timestamp), and leave other types of context, such as Application, unchanged. Verify that the ContextService behaves as configured.
  - testCopy: Verify that the ManagedExecutorService copy(stage) and copy(CompletableFuture) methods create copies that propagate thread context to dependent stages that are created from the copy.
  - testCurrentContextExecutor: Use currentContextExecutor to capture a snapshot of the current thread context and apply it elsewhere at later points in time.
  - testEJBAnnoContextServiceDefinition: Use a ContextService from a ContextServiceDefinition that is defined in an EJB.
  - testEJBAnnoManagedExecutorDefinition: Use a ManagedExecutorService from a ManagedExecutorDefinition that is defined in an EJB.
  - testEJBAnnoManagedScheduledExecutorDefinition: Use a ManagedScheduledExecutorService from a ManagedScheduledExecutorDefinition that is defined in an EJB.
  - testEJBAnnoManagedThreadFactoryDefinition: Use a ManagedThreadFactory from a ManagedThreadFactoryDefinition that is defined in an EJB.
  - testEJBAnnoManagedThreadFactoryInitialization: Use a ManagedThreadFactory from a ManagedThreadFactoryDefinition that is defined in an EJB that has not been previously initialized/invoked.
  - testEJBContextServiceDefinition: Use a ContextService that is defined by another ContextServiceDefinition in an EJB.
  - testEJBManagedExecutorDefinition: Use a ManagedExecutorService that is defined by another ManagedExecutorDefinition in an EJB.
  - testEJBDDManagedScheduledExecutorDefinition: Use a ManagedScheduledExecutorService that is defined by another ManagedScheduledExecutorDefinition in an EJB.
  - testEJBDDManagedThreadFactoryDefinition: Use a ManagedThreadFactory that is defined by another ManagedThreadFactoryDefinition in an EJB.
  - testFailedFuture: Verify that a ManagedExecutorService propagates context to dependent stages that are created from a failedFuture().
  - testForcedCompletionOfCopies: Verify that forced completion of a copied stage neither impacts the original, nor other copies.
  - testGetContextServiceFromManagedExecutorDefinition: Verify that it is possible to obtain the nested ContextService of a ManagedExecutorService that is configured as a ManagedExecutorDefinition, and that when withContextCapture is invoked on this ContextService, the resulting CompletableFuture is backed by the ManagedExecutorService, subject to its concurrency constraints (maxAsync=1) and runs tasks under the context propagation settings of its nested ContextService.
  - testGetContextServiceFromManagedScheduledExecutorDefinition: Verify that it is possible to obtain the nested ContextService of a ManagedScheduledExecutorService that is configured as a ManagedScheduledExecutorDefinition, and that when withContextCapture is invoked on this ContextService, the resulting CompletableFuture is backed by the ManagedScheduledExecutorService, subject to its concurrency constraints (maxAsync=2) and runs tasks under the context propagation settings of its nested ContextService.
  - testGetContextServiceFromServerXMLWithContextCapture: Verify that it is possible to obtain the nested ContextService of a ManagedExecutorService that is configured in server.xml, and that when withContextCapture is invoked on this ContextService, the resulting CompletableFuture is backed by the ManagedExecutorService, subject to its concurrency constraints, and runs tasks under the context propagation settings of its nested ContextService.
  - testGetExecutionProperties: Per the spec JavaDoc, ContextService.getExecutionProperties can be used on a contextual proxy obtained by createContextualProxy, but otherwise raises IllegalArgumentException.
  - testManagedExecutorDefinitionAnno: Verify that a ManagedExecutorService that is injected from a ManagedExecutorDefinition abides by the configured maxAsync and the configured thread context propagation/clearing that makes it possible to access third-party context from async completion stage actions.
  - testManagedExecutorDefinitionAppDD: Verify that a ManagedExecutorService that is defined in application.xml abides by the configured maxAsync and the configured thread context propagation/clearing that makes it possible to access third-party context from async completion stage actions.
  - testManagedScheduledExecutorDefinitionAnno: Verify that a ManagedScheduledExecutorService that is injected from a ManagedScheduledExecutorDefinition abides by the configured maxAsync and the configured thread context propagation that makes it possible to look up resource references in the application component's namespace.
  - testManagedScheduledExecutorDefinitionAppDD: Verify that a ManagedScheduledExecutorService that is defined in application.xml abides by the configured maxAsync and the configured thread context propagation that makes it possible to look up resource references in the application component's namespace.
  - testManagedThreadFactoryDefinitionAnno: Verify that a ManagedThreadFactory that is injected from a ManagedThreadFactoryDefinition creates threads that run with the configured priority and with the configured thread context that makes it possible to look up resource references in the application component's namespace.
  - testManagedThreadFactoryDefinitionAppDD: Verify that a ManagedThreadFactory that is defined in application.xml  creates threads that run with the configured priority and with the configured thread context that makes it possible to look up resource references in the application component's namespace.
  - testNestedContextService2WithContextCapture: Verify that it is possible to use nested ContextService without ever having obtained the managed executor that it is nested under, and that is possible to use the withContextCapture methods which create completion stages that are backed by that managed executor. Verify that the completion stages run on the managed executor, subject to its concurrency constraints, and runs tasks under the context propagation settings of its nested ContextService.
  - testOneShotTimerWithZonedTrigger: Schedule a one-shot timer with a ZonedTrigger that implements only getZoneId and the getNextRunTime method that accepts a ZonedDateTime. Record the LastExecution and ensure that the methods which specify a ZoneId are working and return times that are consistent with what the ZonedTrigger asks for.
  - testParallelStreamRunsOnManagedThreadFactory:  Verify that a parallel stream can run on a ForkJoinPool that uses a ManagedThreadFactory to create its ForkJoinWorkerThreads, and that those threads run with the application component context of the the application that looked up or injected the ManagedThreadFactory. Verify this by attempting a resource reference lookup from the parallel stream operations.
  - testReferencedContextServiceWithContextCapture3: Verify that it is possible to obtain a ContextService that is referenced by multiple managed executors, and that is possible to use the withContextCapture methods which create completion stages that are backed by the respective managed executor. Verify that the completion stages run on the managed executor, subject to its concurrency constraints, and runs tasks under the context propagation settings of the ContextService. Part 1 - This test covers usage of the managedScheduledExecutorService concurrent/executor3.
  - testReferencedContextServiceWithContextCapture4: Verify that it is possible to obtain a ContextService that is referenced by multiple managed executors, and that is possible to use the withContextCapture methods which create completion stages that are backed by the respective managed executor. Verify that the completion stages run on the managed executor, subject to its concurrency constraints, and runs tasks under the context propagation settings of the ContextService. Part 2 - This test covers usage of the managedScheduledExecutorService concurrent/executor4.
  - testRepeatingTimerWithZonedTrigger: Schedule a repeating timer with a ZonedTrigger that rejects the deprecated methods of Trigger and implements only the ZonedTrigger methods that were added in Concurrency 3.0 / EE 10.
  - testRunAsyncWithDefaultContextPropagation: Verify that the ManagedExecutorService runAsync runs the completion stage action with context captured per the java:comp/DefaultContextService when the ManagedExecutorDefinition does not specify any value for context.
  - testSerializeProxyFromAppDefinedContextServiceClearRemaining: An application defined ContextService that either clears or leaves unchanged all third party context types must be able to create serializable contextual proxies.
  - testSerializeProxyFromAppDefinedContextServicePropagateAppOnly: An application defined ContextService that only propagates built-in types must be able to create serializable contextual proxies.
  - testSerializeProxyFromAppDefinedContextServicePropagateRemaining: An application defined ContextService that either clears or leaves unchanged all third party context types must be able to create serializable contextual proxies.
  - testSerializeProxyFromDefaultContextService: The default ContextService, java:comp/DefaultContextService, must be able to create serializable contextual proxies.
  - testSerializeProxyFromServerConfigContextService: A ContextService from server configuration must be able to create serializable contextual proxies.
  - testSkipEveryOtherExecution: Schedule a repeating timer that skips every other execution.
  - testThirdPartyContextForPropagationFailsToSerialize: Third party context types that are configured to be propagated must fail to serialize.
  - testWebDDContextServiceDefinition: Use a ContextService that is defined by a context-service in a web module deployment descriptor.
  - testWebDDManagedExecutorDefinition: Use a ManagedExecutorService that is defined via managed-executor in a web module deployment descriptor.
  - testWebDDManagedScheduledExecutorDefinition: Use a ManagedScheduledExecutorService that is defined via managed-scheduled-executor in a web module deployment descriptor.
  - testWebDDManagedThreadFactoryDefinition: Use a ManagedThreadFactory that is defined by managed-thread-factory in a web module deployment descriptor.
  - testWebMergedContextServiceDefinitionClearedAndPropagated: Use a ContextService that is defined by the merging of a ContextServiceDefinition and a context-service in a web module deployment descriptor, which replaces the cleared and propagated context types.
  - testWebMergedContextServiceDefinitionClearedAndUnchanged: Use a ContextService that is defined by the merging of a ContextServiceDefinition and a context-service in a web module deployment descriptor, which replaces the cleared and unchanged context types.
  - testWebMergedContextServiceDefinitionPropagated: Use a ContextService that is defined by the merging of a ContextServiceDefinition and a context-service in a web module deployment descriptor, which replaces the propagated context types.
  - testWebMergedManagedExecutorDefinitionAsync: Use a ManagedExecutorService that is defined by the merging of a ManagedExecutorDefinition and a managed-executor in a web module deployment descriptor, which replaces the maxAsync that it uses.
  - testWebMergedManagedExecutorDefinitionContext: Use a ManagedExecutorService that is defined by the merging of a ManagedExecutorDefinition and a managed-executor in a web module deployment descriptor, which replaces the context service that it uses.
  - testWebMergedManagedScheduledExecutorDefinitionAsync: Use a ManagedScheduledExecutorService that is defined by the merging of a ManagedScheduledExecutorDefinition and a managed-scheduled-executor in a web module deployment descriptor, which replaces the maxAsync that it uses.
  - testWebMergedManagedScheduledExecutorDefinitionContext: Use a ManagedScheduledExecutorService that is defined by the merging of a ManagedScheduledExecutorDefinition and a managed-scheduled-executor in a web module deployment descriptor, which replaces the context service that it uses.
  - testWebMergedManagedThreadFactoryDefinitionContext: Use a ManagedThreadFactory that is defined by the merging of a ManagedThreadFactoryDefinition and a managed-thread-factory in a web module deployment descriptor, which replaces the context service that it uses.
  - testWebMergedManagedThreadFactoryDefinitionPriority: Use a ManagedThreadFactory that is defined by the merging of a ManagedThreadFactoryDefinition and a managed-thread-factory in a web module deployment descriptor, which replaces the priority.

* com.ibm.ws.concurrent_fat_cdi

  ConcurrentCDIServlet:
  - testAppScopedBeanAsyncMethodLooksUpDefaultResource: Asynchronous method can look up a Jakarta EE default resource.
  - testAppScopedBeanAsyncMethodLooksUpResourceInJavaComp: Asynchronous method can look up a resource in the application component's name space.
  - testAppScopedBeanAsyncMethodLooksUpUserTransaction: Asynchronous method can look up UserTransaction.
  - testAppScopedBeanAsyncMethodRaisesCompletionException: Asynchronous method fails by raising CompletionException.
  - testAppScopedBeanAsyncMethodRaisesError: Asynchronous method fails by raising a RuntimeException subclass.
  - testAppScopedBeanAsyncMethodRaisesRuntimeException: Asynchronous method fails by raising a RuntimeException subclass.
  - testAppScopedBeanAsyncMethodReturnsCompletableFuture: A managed bean that is ApplicationScoped can have an asynchronous method that returns CompletableFuture and runs asynchronously to the calling thread.
  - testAppScopedBeanAsyncMethodReturnsCompletionStage: An asynchronous method that returns CompletionStage will run asynchronously to the calling thread.
  - testAppScopedBeanMethodWithoutAnnotationIsNotAsync: A managed bean that is ApplicationScoped can have some asynchronous methods, but other methods do not run asynchronously to the calling thread.
  - testAsyncOnSuperclassMethod: The Asynchronous annotation can be placed on a method of a superclass of a CDI managed bean.
  - testAsyncTxMandatory: When an asynchronous method is also annotated with Transactional(MANDATORY) it must be rejected because the transaction cannot be established on the async method thread in parallel to the caller.
  - testAsyncTxNever: When an asynchronous method is also annotated with Transactional(NEVER) it must be rejected.
  - testAsyncTxNotSupported: When an asynchronous method is also annotated with Transactional(NOT_SUPPORTED), the Transactional interceptor must be applied second, such that the method runs under no transaction.
  - testAsyncTxRequired: When an asynchronous method is also annotated with Transactional(REQUIRED) it must be rejected because the transaction cannot be established on the async method thread in parallel to the caller.
  - testAsyncTxRequiresNew: When an asynchronous method is also annotated with Transactional(REQUIRES_NEW), the Transactional intercept must be applied second, such that the method runs under a new transaction.
  - testAsyncTxSupports: When an asynchronous method is also annotated with Transactional(SUPPORTS) it must be rejected because the transaction cannot be established on the async method thread in parallel to the caller.
  - testInterruptAsyncMethod: Interrupt asynchronous and inline asynchronous methods.
  - testInvokeInlineWithClearedTransactionAndAppContext: Verify that when a task runs inline, the transaction and application context are cleared from the thread when the managed executor's ContextServiceDefinition lets those context types default to being cleared.
  - testInvokeInlineWithinSameTransaction: Verify that when a task runs inline, the transaction remains on the thread when the managed executor's ContextServiceDefinition specifies that transaction context remain unchanged
  - testInvokeInlineWithinSameTransactionAndAppContext: Verify that when a task runs inline, the application context and transaction remain on the thread when the managed executor's ContextServiceDefinition specifies that application and transaction context remain unchanged.
  - testInvokeInlineWithinSameTransactionWithAppContextCleared: Verify that when a task runs inline, the transaction remains on the thread and the application context is cleared when the managed executor's ContextServiceDefinition specifies that transaction context remain unchanged and the application context is cleared.
  - testInvokeInlineWithSameAppContext_TranSuspendedByExecutionProperty: Verify that when a task runs inline, the application context remains on the thread but the transaction does not when the managed executor's ContextServiceDefinition specifies that both application and transaction context remain unchanged, but an execution property overrides the transaction context to suspend it.
  - testBeanSubmitsManagedTask: From the bean, submit a concurrent task.
  - testBeanSubmitsManagedTaskThatInvokesTxNever: Submit a concurrent task to invoke a bean method with transaction attribute NEVER
  - testBeanSubmitsManagedTaskThatInvokesTxRequiresNew: Submit a concurrent task to invoke a bean method with transaction attribute REQUIRES_NEW
  - testBeanSubmitsManagedTaskThatInvokesTxSupports: Submit a concurrent task to invoke a bean method with transaction attribute SUPPORTS
  - testManagedBeanAsyncMethod: Invoke an asynchronous method on a CDI managed bean that isn't otherwise annotated
  - testObtrudeAsynchronousMethod: Use the CompletableFuture obtrude methods to replace the result or exception of asynchronous methods that are in progress, already completed, or queued for execution.
  - testRemainingContextPropagated: Verify that application context is propagated when the ContextServiceDefinition does not configure it explicitly, but specifies to propagate all remaining context types.
   - testRemainingContextUnchangedNoneCleared: Verify that transaction context and application context are left alone when the ContextServiceDefinition does not configure them explicitly, but specifies to leave all remaining context types unchanged.
   - testRemainingContextUnchangedSomeCleared: Verify that transaction context is left alone while application context is cleared when the ContextServiceDefinition does not configure transaction context explicitly, but specifies to leave all remaining context types unchanged.
   - testRequestScopedBeanAsyncMethodAnnotationsConflict: Specify the asynchronous method annotation at both class and method level, with conflicting values for the executor parameter. Verify that method level takes precedence.
   - testRequestScopedBeanAsyncMethodTimesOut: Asynchronous method times out per the configured startTimeout.
   - testSessionScopedBeanAsyncMethodExecutorNotAnExecutor: Try to use an asynchronous method for which the executor parameter points to a JNDI name that is something other than a ManagedExecutorService.
   - testSessionScopedBeanAsyncMethodExecutorNotFound: Try to use an asynchronous method for which the executor parameter points to an executor JNDI name that does not exist.
   - testSessionScopedBeanAsyncMethodRunsOnSpecifiedExecutor: Verify that asynchronous methods run on the specified executor. To do this, invoke methods in excess of the maximum concurrency and confirm that it limits the number running at the same time, and attempt to queue up async methods in excess of the maximum queue size.
   - testServletSubmitsBeanToManagedExecutor: Verify that a bean that implements Callable can be submitted to a managed executor.
   - testServletSubmitsManagedTaskThatInvokesTxNever: Submit a concurrent task to invoke a bean method with transaction attribute NEVER
   - testServletSubmitsManagedTaskThatInvokesTxRequiresNew: Submit a concurrent task to invoke a bean method with transaction attribute REQUIRES_NEW
   - testServletSubmitsManagedTaskThatInvokesTxSupports: Submit a concurrent task to invoke a bean method with transaction attribute SUPPORTS
   - testSingletonScopedBeanAsyncMethodInvokesAnotherAsyncMethod: Verify that one async method can invoke another. The first async method is on a Singleton bean and the second async method is on a DependentScoped bean.
   - testTransactionContextCleared: Verify that transaction context is cleared per the ContextServiceDefinition configuration.
   - testTransactionContextPropagated: Verify that transaction context is propagated per the ContextServiceDefinition configuration.
   - testTransactionContextPropagatedToAsyncMethod: Verify that transaction context is propagated to an asynchronous method, per configuration of the ManagedExecutorService's ContextServiceDefinition.
   - testTransactionContextPropagatedToAsyncTask: Verify that transaction context is propagated to an asynchronous task, per configuration of the ManagedExecutorService's ContextServiceDefinition.
   - testTransactionContextPropagatedToAsyncTaskInline: Verify that transaction context is propagated to an inline asynchronous task, per configuration of the ManagedExecutorService's ContextServiceDefinition.
   - testTransactionContextPropagatedToCompletableFuture: Verify that transaction context is propagated to a completion stage action, per the configuration of the managed executor's ContextServiceDefinition.
   - testTransactionContextPropagatedWithContextCapture: Verify that transaction context is propagated to completion stages that obtained via ContextService.withContextCapture.
   - testTransactionContextUnchanged: Verify that transaction context is left unchanged per the ContextServiceDefinition configuration.
   - testTransactionContextUnchangedForInlineCompletionStageAction: Verify that transaction context is left unchanged per the ContextServiceDefinition configuration, and allows an inline completion stage action to run in the transaction that is already on the thread.
   - testTransactionScopedBeanAsyncMethod: Invoke an asynchronous method on a transaction scoped bean.
   - testUnspecifiedContextTypesCleared: When ContextServiceDefinition does not specify ALL_REMAINING for any category of context, ALL_REMAINING is automatically added to the cleared types. Verify that application context and transaction context are cleared from the thread while running the task.

* com.ibm.ws.concurrent_fat_zcontext

  SimZOSContextProviderTest:
  - testInterruptOnDeactivate: Verify that ForkJoinWorkerThreads which are created by a ManagedThreadFactory are interrupted upon deactivate of the ManagedThreadFactory just as other managed threads are.

  SimZOSContextTestServlet:
  - testClearSimulatedSyncToOSThreadContext: Configure to clear SyncToOSThread context and verify that the fake context type that we are using to simulate it is cleared from the thread.
  - testClearSimulatedZOSWLMContext: Configure to clear the fake z/OS WLM context and verify that it is cleared from the thread.
  - testPropagateSimulatedSyncToOSThreadContext: Configure to propagate SyncToOSThread context and verify that the fake context type that we are using to simulate it propagates to the thread.
  - testPropagateSimulatedZOSWLMContext: Configure to propagate zosWLMContext and verify that the fake context type that we are using to simulate it propagates to the thread.

* com.ibm.ws.concurrent.mp_fat_jakarta

  MPContextProp2_0_TestServlet
  - testAsynchronousNotAllowedOnClass: Verify that Asynchronous is not allowed at the class level.
  - testAsyncMethodUsesJakartaEEManagedExecutorService: Invoke an asynchronous method that relies on a Jakarta EE ManagedExecutorService while MicroProfile Context Propagation is enabled.
  - testAsyncMethodUsesResourceRefToManagedExecutor: Invoke an asynchronous method that uses a resource reference to the default managed executor as a MicroProfile ManagedExecutor.
  - testCopy: ManagedExecutor.copy was added in 1.2 and should still be working. With this method, you should be able to copy from an unmanaged completion stage that lacks context propagation to create a copied stage that uses the managed executor to propagate thread context.
  - testCustomContextIsNotPropagatedByDefault: Verify that custom thread context types are not propagated by the default ManagedExecutorService.
  - testCustomEEContextIsPropagatedWhenConfigured: Verify that custom thread context types are propagated if configured on the ContextServiceDefinition.
  - testCustomMPContextIsPropagatedWhenConfigured: Verify that custom thread context types are propagated if configured on the builder.
  - testDefaultManagedExecutorService: java:comp/DefaultManagedExecutorService can be used interchangeably as a MicroProfile ManagedExecutor or as a Jakarta EE ManagedExecutorService.
  - testFaultToleranceAsyncMethod: Jakarta EE Concurrency should not interfere with MicroProfile FaultTolerance Asynchronous when only the MicroProfile annotation is present.
  - testFaultToleranceClassLevelAsynchronousCollidesWithMethod: A method that is annotated with Jakarta EE Concurrency's Asynchronous must fail if the class is annotated with MicroProfile Fault Tolerance Asynchronous.
  - testFaultToleranceCollidesOnSameAsyncMethod: A method that is annotated with Jakarta EE Concurrency's Asynchronous must fail if the method is also annotated with MicroProfile Fault Tolerance Asynchronous.
  - testIntermixMicroProfileAndJakartaEECompletionStages: Use a MicroProfile ManagedExecutor and a Jakarta EE ManagedExecutorService to create completion stages and combine the two to create dependent stages, ensuring that each dependent stage runs with the configured context propagation of the managed executor of the stage that creates the dependent stage.

* io.openliberty.jakarta.concurrency.3.0_fat_tck
  Runs the Jakarta Concurrency 3.0 specification TCK

### Test strategy

* What functionality is new or modified by this feature?
**Jakarta Concurrency 3.0 specification**
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
**Refer to above lists of tests**
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)
**To be determined based on z/OS Java 11 outcome**

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**5**

**Comment by ayoho** [comment]
Coverage looks good 👍
