### ISSUE TITLE
Usability changes to bin/server checkpoint

### ISSUE THREAD

**Issue by sebratton** [OpenLiberty/open-liberty#18263]

**Comment by sebratton** [comment]
From slack conversation with Tom Watson:
_He _[Alasdair]_ recommends we go with an approach that uses a checkpoint action instead of --checkpoint option on the run|start action._

`server checkpoint <server name> --at=features|applications`

_I'm not sure where that leaves us for doing run vs start mode though._

_I think it would be nice if you could enable debug on restore for a checkpoint that was not setup for debug_

**Comment by tjwatson** [comment]
This has been done in the `criu` branch
