### ISSUE TITLE
Performance Document filter option for monitor feature with mpMetrics/microProfile features.

### ISSUE THREAD

**Issue by jdmcclur** [OpenLiberty/open-liberty#18288]
When mpMetrics-x.x  (or the convenience microProfile-x.x feature) is enabled, the monitor-1.0 feature is enabled to provide vendor metrics. This adds a small performance overhead, especially the WebContainer monitor group. If customer's do not care about the vendor metrics, they can add a filter in the server.xml, so only the REST group will be monitored.

```
<monitor filter="REST"/>
```

I think this should be documented better and maybe put in the Performance Cookbook.

**Comment by jdmcclur** [comment]
@Channyboy - has then been done?

**Comment by Channyboy** [comment]
@jdmcclur Working on it now :b

**Comment by Channyboy** [comment]
OL doc issue : https://github.com/OpenLiberty/docs/issues/4762

**Comment by Channyboy** [comment]
From the document issue : "content is now on vNext and will publish with 21.0.0.12"
