### ISSUE TITLE
Bug: AdminCenter SRVE0190E: File not found: /images/tools/wasdev_142x142.png

### ISSUE THREAD

**Issue by lavenal** [OpenLiberty/open-liberty#18282]
**Describe the bug**  

After upgrading Liberty from 20.0.0.11 to 21.0.0.4, the wasdev.net bookmark in Liberty Admin Center connected to a collective controller environment was missing an icon and pointed to a wrong URL when clicking on it.

The following error was also logged in the collective controller:

[2/3/21, 17:33:24:439 EST] 000001d4 extension W com.ibm.ws.webcontainer.extension.DefaultExtensionProcessor handleRequest SRVE0190E: File not found: /images/tools/wasdev_142x142.png

**Steps to Reproduce**  

- Install Liberty 20.0.0.11 or earlier version and create a collective controller with adminCenter-1.0 feature in it
- start the collective controller
- bring up Admin Center
- upgrade to Liberty to 2.0.0.12 or later version
- start the collective controller
- bring up Admin Center

**Diagnostic information:**  
 - Liberty Versions before upgrade: 20.0.0.11 or earlier 
 - Liberty Versions upgraded to: 20.0.0.12 or later
 - Affected feature: adminCenter-1.0 in a collective controller
 - messages.log with the following error during Admin Center startup
 [2/3/21, 17:33:24:439 EST] 000001d4 extension W com.ibm.ws.webcontainer.extension.DefaultExtensionProcessor handleRequest SRVE0190E: File not found: /images/tools/wasdev_142x142.png

**Comment by mbroz2** [comment]
@lavenal the info you have in the description is good, but can you please update the description of this release bug so that it follows/conforms to the [Bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)

**Comment by lavenal** [comment]
@mbroz2 The issue description is updated. Let me know if it needs further changes. Thanks.
