### ISSUE TITLE
Externalize transactionSupport=“NoTransaction” | “LocalTransaction” | “XATransaction” for connectionFactory

### ISSUE THREAD

**Issue by jmstephensgit** [OpenLiberty/open-liberty#18300]
As a user of Liberty Application Server and connection factories, I would like to override “XATransaction”  transactional support of a resource adapter to “LocalTransaction” or “NoTransaction”.

The transactionSupport value being used must be supported by the resource adapter for the override to work with the expected behavior.

**Comment by NottyCode** [comment]
I can see this causing a number of problems if used incorrectly which could result in users hitting problems. For this reason I think we need to go through the full design process.

**Comment by dgonzalo-sgt** [comment]
Hi! Just as a user involved in this, please, if possible keep backwards compatibility with the undocumented feature.
We had to use this to get last-participant-support for a single non-XA resource (a non XA capable Tibco EMS queue used via the GenericRA JCA adapter) involved in an XA transaction. This was during a migration from WAS classic, where LPS worked perfectly with the included connector, so as not to require modifying the (very, very old) application.

**Comment by frowe** [comment]
At least one scenario has been identified where the use of this can cause errors (see https://github.com/openliberty/open-liberty/issues/18776).  We also haven't seen sufficient demand for this to justify prioritizing it over work.  Because of this,  we will not be externalizing this as a configuration attribute.
