### ISSUE TITLE
Secure connection over AT-TLS policy times out

### ISSUE THREAD

**Issue by jianguo05** [OpenLiberty/open-liberty#18325]
On z/OS platform, JES which is z/OS JOB subsystem utilizes mail notification function provided by z/OSMF running on Liberty. Usually, after z/OSMF server starts, JES is notified to be able to connect z/OSMF via SSL. Then JES will connect to z/OSMF and send mail about job status. In this case, a AT-TLS policy agent is started after JES has been connected to z/OSMF. With the policy agent started, JES is no longer to be able to connect to z/OSMF via SSL.

   Teddy from Liberty suggested below trace information collected from both java and Liberty sides. The traces do not show another ClientHello message from the client side. it looks like that after policy agent, no SSL handshake reaches z/OSMF side (more precisely, Liberty code). For the record,  this connection uses SSL services (via HTTP Toolkit), not AT-TLS.

-Djavax.net.debug=true
logging='*=info:SSL=all:com.ibm.ws.security.*=all:zos.native.03=all'

   Then Josh from z/OS communication team provided the analysis in below(The following information comes from RTC system).

Just to clarify the insight from the TCPIP perspective referring to the doc submitted on 7/13 (APYTEL.DUMP.APYTEL.D210713.T150300.S00001) ... 

In the successful case, we observed that the client hello message was sen to the server side application (IZUSVR1 which is z/OSMF server).  After the message arrived we see the server side application issue a socket SELECT/POLL request to determine if there is data to read.  The TCPIP stack responds to the select request indicating that data is available to read and subsequently IZUSVR1 then issues a socket READ request to read the data (reading in the client hello).  Following this we see IZUSVR1 issue a socket write to send the server hello message.

In the failing case, we observed that the client hello message was sent to the server side application (IZUSVR1 which is z/OSMF server).  However, we never see a socket SELECT/POLL nor a socket READ request come from IZUSVR1 to read the client hello.  The next activity on this connection is when the JES client side connection times out and the FIN is sent when closing the connection.

      Then new trace information is asked by Teddy and new issue is opened.

*=info:SSL=all:com.ibm.ws.security.*=all:zos.native.03=all:ChannelFramework=all:HTTPChannel=all:SSLChannel=all
JVM_OPTIONS=-Djavax.net.debug=true

**Comment by teddyjtorres** [comment]
Closing this issue. Please follow up via Slack if needed.
