### ISSUE TITLE
Look for Oracle JDBC driver that supports Java 16+

### ISSUE THREAD

**Issue by gjwatts** [OpenLiberty/open-liberty#18341]
The current public Oracle JDBC driver we use for testing (ojdbc8_g.jar v21.1.0.0) only supports Java 8-15.  So we currently we have an Oracle JDBC Kerberos test in the `com.ibm.ws.jdbc_fat_krb5` FAT limited to only test through Java 15.  Once Oracle releases a driver update that supports Java 16+, we can remove/update that test restriction.

This issue to to remind us to do that. 😃

**Comment by KyleAure** [comment]
My guess is that Oracle will release a driver that supports Java 17.  But may not release an ojdbc8 driver that supports up to Java 17.  We will need to wait and see.
