### ISSUE TITLE
Warning CWWKS9590W when strong ciphers are configured

### ISSUE THREAD

**Issue by santoshjpawar** [OpenLiberty/open-liberty#18353]
We have configured the Ciphers Suites to the liberty server. In server.xml we have,  

```
<ssl id="defaultSSLConfig"
.....
enabledCiphers="SSL_ECDHE_RSA_WITH_AES_256_CBC_SHA384 TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 "
....
```

When added this, start getting the below warnings:
```
[WARNING ] CWWKS9590W: The SSL_ECDHE_RSA_WITH_AES_256_CBC_SHA384 requested cipher suite appears to have [integrity, confidentiality, establishTrustInTarget, strong, noexport] association options that do not match the specified [integrity, confidentiality, establishTrustInTarget, noexport, tls] supported options and the [integrity, confidentiality] required options.
[WARNING ] CWWKS9590W: The TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 requested cipher suite appears to have [integrity, confidentiality, establishTrustInTarget, strong, noexport, tls] association options that do not match the specified [integrity, confidentiality, establishTrustInTarget, noexport, tls] supported options and the [integrity, confidentiality] required options.
```

In this case,
Supported Association Options list is [integrity, confidentiality, establishTrustInTarget, noexport, tls]
Required Association Options list is [integrity, confidentiality]

As per our discussion with Liberty team - **"When using the enabledCiphers attribute with strong ciphers, it is not possible to eliminate the CWWKS9590W message without removing the strong ciphers. We need to open an issue to fix this."**

Hence opening this issue to fix this in the Liberty code.

**Comment by teddyjtorres** [comment]
@utle Hi Ut. The code in https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/security/csiv2/config/ssl/SSLConfig.java#:~:text=private%20String%5B%5D-,filter,-(String%5B%5D%20candidateCipherSuites%2C%20String needs updating.

The CWWKS9590W message should not display for a cipher suite that has the "strong" option, but that otherwise satisfies the required and supported options.

**Comment by utle** [comment]
fixed by https://github.com/OpenLiberty/open-liberty/pull/20559
