### ISSUE TITLE
LDAP identity store doesn't accept String.format(...) descriptor %s in groupSearchFilter

### ISSUE THREAD

**Issue by utle** [OpenLiberty/open-liberty#1836]
The LdapIdentityStore should accept the String.format(...) descriptor %s in the groupSearchFilter.

This means that only one attribute can be recognized when searching for group membership on groups.

The code should be updated so that if the groupSearchFilter contains the %s descriptor, that we generated the LDAP filter by replacing the %s with the DN of the user. Otherwise; the LDAP filter should be generated in the way it is now by adding in the groupMemberAttribute=CALLERDN.

**Comment by ryanesch** [comment]
Added this functionality in https://github.com/OpenLiberty/open-liberty/pull/1885
