### ISSUE TITLE
Feature Test Summary for JDBC config-based exception identification

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#18366]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

### List of FAT projects affected

* com.ibm.ws.jdbc_fat_heritageinterop - an Open Liberty test bucket that tests the many integration points that are provided on the Open Liberty side to enable the legacy tWAS function.

testAuthorizationError - Verifies that when an authorization error occurs, only the connection on which the error occurred is removed from the pool.

testConnectionCleanup - Verifies that doConnectionCleanup is invoked on a data store helper that uses this notification to restore the default list of client info properties.

testConnectionSetup - Verifies that doConnectionSetup was performed on a new connection. Verifies that doConnectionSetupPerGetConnection is invoked for each first connection handle. Verifies that doConnectionCleanupPerCloseConnection is invoked upon closing or dissociating the last connection handle.

testConnectionSetupPerTransaction - Verifies that doConnectionCleanupPerTransaction is invoked exactly once for each global transaction or Local Transaction Containment (which is not actually a transaction).

testDataStoreHelperUnspecified - It should be possible to configure exception replacement without specifying a data store helper, in which case a default is assigned.

testDefaultIsolationLevel - Confirm that a dataSource that is configured with heritageSettings can be injected and has the transaction isolation level that is assigned as default by the DataStoreHelper.

testDefaultQueryTimeout - Confirm that a data store helper's doStatementCleanup is capable of resetting the configured default queryTimeout from the dataSource configuration.

testIsConnectionError - Verify that the data store helper is invoked to determine if an exception indicates a connection error, even when exceptions are not replaced.

testIsShareable - Verifies that the type of sharing indicated by the isShareable legacy operation is consistent with the resource reference.

testIsXADataSource - Verifies that the isXADataSource legacy operation returns the correct value based on the dataSource configuration.

testLoadClassesFromHeritageBundle - Verifies that API classes can be loaded from the mock heritage API bundle fragment.

testLoadClassFromJDBCBundle - Verifies that the ConnectionWaitTimeoutException class can be loaded from the com.ibm.ws.jdbc bundle

testMapExceptionAndReplaceIt - Verify that the data store helper is invoked to map and replace exceptions.

testMatchCurrentCatalog - Verify that WSDataSource.getConnection(conspec) can be used to match and share a connection based on its catalog attribute.

testMatchCurrentHoldability - Verify that WSDataSource.getConnection(conspec) can be used to match and share a connection based on its cursor holdability attribute.

testMatchCurrentIsolationLevel - Verify that WSDataSource.getConnection(conspec) can be used to match and share a connection based on its isolation level.

testMatchCurrentNetworkTimeout - Verify that WSDataSource.getConnection(conspec) can be used to match and share a connection based on its network timeout.

testMatchCurrentReadOnly - Verify that WSDataSource.getConnection(conspec) can be used to match and share a connection based on its read only attribute.

testMatchCurrentSchema - Verify that WSDataSource.getConnection(conspec) can be used to match and share a connection based on its schema attribute.

testMatchCurrentTypeMap - Verify that WSDataSource.getConnection(conspec) can be used to match and share a connection based on its typeMap attribute.

testMatchCurrentUser - Verify that WSDataSource.getConnection(conspec) can be used to match and share a connection based on its user name attribute.

testObjectClosedException - Verify that ObjectClosedException is raised when attempting operations on a closed JDBC artifact.

testStaleStatement - Cause an error that we have arbitrarily mapped to StaleStatementException in the data store helper. Verify that the statement is not cached and that the error is surface to the application as a StaleConnectionException. This matches the legacy behavior.

testStatementCachingBasedOnIsolationLevel - Confirm that doesStatementCacheIsoLevel causes prepared statements to be cached based on the isolation level that was present on the connection at the time the statement was created.

testStatementCleanup - Confirm that doStatementCleanup is invoked when reusing statements from the statement cache.

testUserDefinedExceptionMap - Confirm that setUserDefinedMap is supplied with the identifyException configuration.

testUserDefinedExceptionMapOverridesDefaults - Verify that the user-defined error map (configured via identifyException) takes precedence when both the data store helper and the identifyException configuration have a conflicting mapping.

testTransactionBranchesLooselyCoupled - Confirm that locks are not shared between transaction branches that are loosely coupled.

testTransactionBranchesTightlyCoupled - Confirm that locks are shared between transaction branches that are tightly coupled.

* com.ibm.ws.jdbc_fat_v41 - an existing bucket where we have chosen to cover the new identifyException function that is added to Open Liberty under this feature.

testConfigUpdateIdentifyException - Verify configuration updates that add, remove, and modify identifyException elements.

testInvalidConfig_noTarget - Verify that a an <identifyException> element with no 'as' attribute defined raises an error in logs

testIdentify1234Stale - Verify that once a connection goes stale (as indicated by server.xml config) it is removed from the connection pool.

testUnmappedError - Test that a non-configured error code does NOT map to a stale connection

testRemovedMapping - Verify that a user can configure a 'None' mapping for one of the built-in sqlstate mappings

testRemovedMapping_stateAndCode - Test removing a mapping for only a specific sqlcode and sqlstate. Normally SQLState 08003 maps to stale, but here we have explicitly configured sqlState=08003 and errorCode=1234 to map to "None" to remove the mapping

testNoMappings - Verify that a datasource with no identifyException mappings properly identifies builtin mappings as stale connections

testBuiltinMappings - Test that a datasource with several identifyException elements still properly identifies builtin error codes and sqlstates

testManyMappings - Test a datasource that has multiple `identifyException` elements. All of the elements should be honored

testInvalidConfig_bogusTarget - Test that we can lookup a datasource with an invalid `identifyException as="..."` attribute, and legacy exception values do not identify as stale when legacy function is not enabled.

testInvalidConfig_noStateOrCode - Verify that if a datasource is configured with no sqlState or errorCode on an `identifyException` element then it should not be accessible.

testStateAndCode_01 - Test a datasource that has identifyMapping of errorCode=5001 and sqlState=E5001 mapped to stale. If we get an exception with that exact errorCode and sqlState, it should map to a stale.

testStateAndCode_02 - Test a datasource that has identifyMapping of errorCode=5001 and sqlState=E5001 mapped to stale. If we get an exception with only the matching errorCode, the exception should NOT map to stale.

### Test strategy

* What functionality is new or modified by this feature?

_You gain the ability to configure how SQLExceptions are identified by Liberty (as stale connections, stale statements, unsupported function, or not identified) based on the SQL state and error code.  This matches an ability that traditional WebSphere Application Server has to configure how these exceptions are identified._

* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)

_See the summary of tests above._

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

_None_

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

**4**

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by ayoho** [comment]
Coverage sounds good to me 👍
