### ISSUE TITLE
webAppSecurity's allowAuthenticationFailOverToAuthMethod options reference non-existent keys in metatype.properties

### ISSUE THREAD

**Issue by jvanhill** [OpenLiberty/open-liberty#18372]
The `webAppSecurity`'s `allowAuthenticationFailOverToAuthMethod` attribute description contains options whose metatype references non-existent keys in the OSGI-INF/l10n/metatype.properties files.

> APP_DEFINED
%allowAuthenticationFailOverToAuthMethod.APP_DEFINED
BASIC
%allowAuthenticationFailOverToAuthMethod.BASIC
FORM
%allowAuthenticationFailOverToAuthMethod.FORM

See: https://openliberty.io/docs/21.0.0.8/reference/config/webAppSecurity.html

**Comment by utle** [comment]
Fixed by https://github.com/OpenLiberty/open-liberty/pull/22228
