### ISSUE TITLE
Error needed when trying to checkpoint without the checkpoint-1.0 feature enabled

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#18378]
Somewhere (probably in the feature manager) we need to put a check to produce an error if the `checkpoint` action is done but the checkpoint-1.0 feature is not enabled.  This same check should also produce an error with a beta-guard while the `checkpoint-1.0` feature is in beta.

**Comment by sebratton** [comment]
this work was merged by PR #18510
