### ISSUE TITLE
Create PluginGenerator Lock to to Address FileNotFoundExceptions 

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#18404]
**Describe the bug**  

During the generation of the `plugin-cfg.xml` file the following exception may occur:

>Stack Dump = java.io.FileNotFoundException: C:\Users\jazz_build\Build\jazz-build-engines\wasrtc\EBCPROD\build\dev\image\output\wlp\usr\servers\com.ibm.ws.security.openidconnect.server-1.0_fat.feature\logs\state\\.plugin-cfg.xml (The process cannot access the file because it is being used by another process)

**Steps to Reproduce**  
The `plugin-cfg-.xml` is generated automatically upon server start in addition to the following actions:

1. When an application is deployed to the server
2. When an application is undeployed from the server
3. When an application programmatically modifies the session cookie configuration name during application initialization
4. When server configuration is updated

When multiple threads attempt to work on the plugin-cfg.xml, it can lead to the FileNotFoundException exception above. 

**Expected behavior**  
The `plugin-cfg.xml` file is generated without error.

**Additional context**  
N/A

**Comment by mbroz2** [comment]
@volosied please update the description of this release bug so that it follows/conforms to the [Bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)

**Comment by mbroz2** [comment]
@pnicolucci can you handle ^ in Volodymyr's absence?

**Comment by pnicolucci** [comment]
@mbroz2 done.
