### ISSUE TITLE
If JAVA_HOME is not set the java9.options file is not always read by the server script

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#18412]
This bit of logic in the `server` script has issues:

```
  JPMS_MODULE_FILE_LOCATION="${JAVA_HOME}/lib/modules"
  if [ -z "${JAVA_HOME}" ]; then
    JPMS_MODULE_FILE_LOCATION=$(dirname $(dirname $(which java)))/lib/modules
  fi

  # If we are running on Java 9, apply Liberty's built-in java 9 options
  if [ -f "${JPMS_MODULE_FILE_LOCATION}" ]; then
    mergeJVMOptions "${WLP_INSTALL_DIR}/lib/platform/java/java9.options"
  fi

```

Typically on linux systems like ubuntu the java executable file is symbolically linked like this:

```
$ ls -l /usr/bin/java
lrwxrwxrwx 1 root root 22 Apr 10 20:27 /usr/bin/java -> /etc/alternatives/java
$ ls -l /etc/alternatives/java
lrwxrwxrwx 1 root root 57 Aug 19 10:17 /etc/alternatives/java -> /usr/lib/jvm/<java installation>/bin/java

```

Then the symbolic links are manipulated with something like `sudo update-alternatives --config java`

The problem is that $(dirname $(dirname $(which java))) is not following the symbolic links.  Where `which java` returns `/usr/bin/java` the result ends up being `/usr/lib/modules` which does not exist.  So we end up not reading in the java9.options.

Could look at using something like `readlink` to get the real path to where the `java` executable is.

**Comment by hlhoots** [comment]
We should also talk about the java9.options file, and perhaps add its contents into the server / client launch manifest jars (see concept in PR #12716.  Maybe this would give us the option of getting rid of the java9.options file altogether?

**Comment by Thihup** [comment]
@hlhoots Would it be possible not to remove the java9.options file? Currently, we're using it in our launcher to be able to follow the changes done in this file to not hit an illegal-access that Open Liberty requires.

**Comment by tjwatson** [comment]
> @hlhoots Would it be possible not to remove the java9.options file? Currently, we're using it in our launcher to be able to follow the changes done in this file to not hit an illegal-access that Open Liberty requires.

@Thihup is that because your launcher uses the `ServerBuilder` and you are trying to deal with the issue described in #18258 ?

**Comment by Thihup** [comment]
@tjwatson We're currently using [Java Service Wrapper](https://wrapper.tanukisoftware.com/doc/english/home.html) to start Open Liberty instead of using the server.sh/server.bat. So we need to provide all the same flags as the server.sh/server.bat to it start correctly.
Today, we parse the java9.options to add the correct flags to the wrapper.conf. Removing it would require that we use another way (like parsing the JAR manifest)

**Comment by tjwatson** [comment]
> @tjwatson We're currently using [Java Service Wrapper](https://wrapper.tanukisoftware.com/doc/english/home.html) to start Open Liberty instead of using the server.sh/server.bat. So we need to provide all the same flags as the server.sh/server.bat to it start correctly.
> Today, we parse the java9.options to add the correct flags to the wrapper.conf. Removing it would require that we use another way (like parsing the JAR manifest)

I don't like the idea that the file `wlp/lib/platform/java/java9.options` is an API others read.  Not sure it is documented anywhere as such, but I understand why you would want to do what you doing here.  But similarly, I would not like the manifest headers of the ws-server.jar to be considered API either (probably even less so).  If we decide `java9.options` must remain in the Liberty installation then I would want that file to remain the authoritative source of the `--add-opens` settings and our build of the various launching JARs would somehow read that to produce the necessary JAR manifest headers.

**Comment by Thihup** [comment]
The main reason of using the java9.options is that it is enabling us to use Java 16 and soon the Java 17. If we were using Java 11 the `--illegal-access=permit` would be enough, but as we're targeting Java 17, we need to provide the `--add-opens` and `--add-exports`.
We don't mind if the name changes or even if the format changes, as long as we can count on it being present to automate the process of upgrading Open Liberty.

**Comment by tjwatson** [comment]
Design call Sept. 7th 2021

Look to implement changes to the build to automatically add the headers `Add-Exports` and `Add-Opens` to the JARs used by the command scripts.  We do not plan to remove the current `wlp/lib/platform/java/java9.options` file but do advise that this file is considered an internal.  We should use this file in the build to automatically add the necessary headers to our JARs where appropriate.  We assume such headers can be added even for JARs that must continue to work on Java 8.

@Thihup does does [Java Service Wrapper](https://wrapper.tanukisoftware.com/doc/english/home.html) end up invoking `java -jar <path to ws-server.jarf>`?  If so then when we add these headers to the JAR it may make it unnecessary for you to read this file.

**Comment by Thihup** [comment]
@tjwatson Unfortunately, no.
It invokes this main class: [WrapperSimpleApp](https://wrapper.tanukisoftware.com/jdoc/org/tanukisoftware/wrapper/WrapperSimpleApp.html#main-java.lang.String:A-).
The first argument is the class to initialize.
So, the wrapper works something like this with our current configuration:
```
java (---add-opens from java9.options) -cp ... org.tanukisoftware.wrapper.WrapperSimpleApp com.ibm.ws.kernel.boot.cmdline.EnvCheck defaultServer
```

**Comment by brenthdaniel** [comment]
The resolution to this should also take into account that `which` is not always installed. `command -v` might be a better choice if we keep the current code for loading java9.options

**Comment by jimblye** [comment]
Any idea why we go to so much trouble to find where java is installed on disk and then to see if it has a "lib/modules" directory?   If we just want to know if we are using java 9 or higher, why can't we just do this?:

```
javaVersion=$("$JAVA_CMD" -version 2>&1 | awk -F '"' '/version/ {print $2}')

# Extract the major version (e.g., 1, 9, 10, 11). 
 # Java switched from using 1.x version numbers in version 9
majorVersion=$(echo "$javaVersion" | awk -F. '{print $1}')

if [ "$majorVersion" -ge 9 ]; then
  echo "Java version is $javaVersion, which is >= 9."
else
  echo "Java version is $java_version, which is < 9.  Anything prior to 9 will display as 1."
fi
```

JAVA_CMD has already been determined by the time we reach this point in the code.

Here:

```
 if [ -z "${JAVA_HOME}" ]
  then
    if [ -z "${JRE_HOME}" ]
    then
      if [ -z "${WLP_DEFAULT_JAVA_HOME}" ]
      then
        # Use whatever java is on the path
        JAVA_CMD=java
      else
        substitutePrefixVar "${WLP_DEFAULT_JAVA_HOME}" WLP_INSTALL_DIR "${WLP_INSTALL_DIR}"
        JAVA_HOME=${substitutePrefixVarResult}
        JAVA_CMD=${JAVA_HOME}/bin/java
      fi
    else
      JAVA_HOME=${JRE_HOME}
      JAVA_CMD=${JRE_HOME}/bin/java
    fi
  else
    if [ -f "${JAVA_HOME}/jre/bin/java" ]
    then
        JAVA_CMD=${JAVA_HOME}/jre/bin/java
    else
        JAVA_CMD=${JAVA_HOME}/bin/java
    fi
  fi
```
