### ISSUE TITLE
Move workarea backup for checkpoint to be under the actual workarea/checkpoint folder

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#18425]
Currently for the `checkpoint` operation a workarea backup is created when a server checkpoint is complete.  This backup is located as a peer to the workarea folder named workarea-checkpoint.  We should avoid leaving this as a peer folder of the workarea.  It would be better to keep the backup under the workarea/checkpoint folder.

**Comment by sebratton** [comment]
#build
