### ISSUE TITLE
Make sure AuthData is restored properly

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#18420]
`com.ibm.websphere.security.auth.data.AuthData` can be configured in server.xml and be influenced by variable substitution which may come from environment variables or from vault style directory variables from config.  We need to make sure that a restored server from checkpoint can properly update any `AuthData` objects with the latest config.  This may all be covered already by work to have Liberty config verify that the config hasn't changed on restore and if config has changed then a config event should be published that updates the `AuthData` objects.  But this needs to be verified and we need to make sure such changes do not force application restarts with an applications checkpoint has been done.

**Comment by tjwatson** [comment]
@dettmoney Do you recall the behavior here?  Was there any testcase added to verify it?

**Comment by dettmoney** [comment]
I did do a bit of manual InstantOn testing with AuthData user/passwords from the server.xml last year. I believe I did a checkpoint with AuthData in the server.xml, then changed the user/password, finally did the restore. From what I recall I did verify the user/password updated properly. I don't think we have any automated testing for this.

**Comment by tjwatson** [comment]
This is tested in #24542
