### ISSUE TITLE
MicroProfile 4.x: OutOfMemoryError: GC overhead limit exceeded when starting/stopping lots of apps

### ISSUE THREAD

**Issue by brideck** [OpenLiberty/open-liberty#18426]
When running the CDI TCK with `microProfile-4.1` added to the Liberty server feature list, the server eventually runs out of memory, throwing `java.lang.OutOfMemoryError: GC overhead limit exceeded` from all of its threads.  This behavior does not normally occur with this TCK, and is only present when the microProfile feature is included in the server config.

The CDI TCK consists of hundreds of applications that are added to the server, started, and then stopped as the tests execute.  Analysis of a heap dump collected when the server was actively throwing the OOM errors has indicated that OLSmallRyeConfigProviderResolver is failing to release resources when the test applications are stopped.  There is a known memory leak in SmallRye (https://github.com/smallrye/smallrye-config/issues/277) and an attempt has been made to work around it in Open Liberty (https://github.com/OpenLiberty/open-liberty/pull/14550).  The current suspicion is that the GLOBAL_CONFIG_APPLICATION_NAME case is not being handled correctly, so those applications are never released.

**Comment by brideck** [comment]
Access to the heap dumps is available upon request.

**Comment by tevans78** [comment]
The root cause of this issue is the MP Config spec's assumption that there is a 1:1 relationship between Applications and ClassLoaders.... https://github.com/eclipse/microprofile-config/issues/546

We're fighting a losing battle until the spec is fixed ... and that would have to be a major version change.
