### ISSUE TITLE
JSF throws ClassNotFoundException for o.a.m.el.convert.ValueExpressionToValueBinding

### ISSUE THREAD

**Issue by wtlucy** [OpenLiberty/open-liberty#18437]
**Describe the bug**  
A JSF application using `jsf-2.2` or `jsf-2.3` can encounter a `ClassNotFoundException` for the internal MyFaces class `ValueExpressionToValueBinding`, even if that class isn't directly referenced by the app. This issue occurs because the `org.apache.myfaces.el.convert` package is not currently made available (by Liberty's `jsf-2.2` and `jsf-2.3` bundles) to the thread context classloader. 

```
[ERROR   ] SRVE0315E: An exception occurred: java.lang.Throwable: javax.servlet.ServletException: org.apache.myfaces.el.convert.ValueExpressionToValueBinding
        at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5119)
        at [internal classes]
Caused by: javax.servlet.ServletException: org.apache.myfaces.el.convert.ValueExpressionToValueBinding
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:230)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: org.apache.myfaces.el.convert.ValueExpressionToValueBinding
        at java.lang.Class.forNameImpl(Native Method)
        at java.lang.Class.forName(Class.java:407)
        at javax.faces.component._ClassUtils.classForName(_ClassUtils.java:145)
        ... 1 more
```

**Steps to Reproduce**  
Applications with custom tags using [Application.createValueBinding(String)](https://docs.oracle.com/javaee/6/api/javax/faces/application/Application.html#createValueBinding(java.lang.String)) deployed with `jsf-2.2` or `jsf-2.3`can hit this:

```
@FacesComponent(tagName = "valueBindingTag", createTag=true, namespace="http://openliberty.io/jsf")
public class ValueBindingTag extends UIComponentBase {
...
    @Override
    public void encodeBegin(FacesContext context) throws IOException {
        ValueBinding test = getFacesContext().getApplication().createValueBinding("test"); // CNFE here
        this.setValueBinding("test", test);
    }
...
```

**Expected behavior**  
This `ClassNotFoundException` should not be thrown

**Diagnostic information:**  
 - OpenLiberty Version: [e.g. 21.0.0.8 - 21.0.0.10]
 - Affected feature(s) `jsf-2.2`, `jsf-2.3`

**Additional context**  
N/A

**Comment by mbroz2** [comment]
@wtlucy please update the description of this release bug so that it follows/conforms to the [Bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
