### ISSUE TITLE
saml web sso sp initiated login flow resulting in buildup of WASSamlReq_xx cookies

### ISSUE THREAD

**Issue by arunavemulapalli** [OpenLiberty/open-liberty#18430]
Description:
Server is rejecting the requests to applications protected by samlWeb-2.0 feature with Bad Request (400) errors.
Steps:
When samlWeb-2.0 feature is enabled in liberty , liberty saml service provider redirects the request to authenticate with saml identity provider. During this process, liberty saml sp creates the WASSamlReq* cookie. Usually the exchanges between sp and IdP are not frequent, but in some not normal working scenarios (samesite settings, servers on different domains etc…) we saw multiple messages flow between sp and IdP and this results in buildup of these cookies and leads to the Bad Request error

Expected Behavior:
The applications protected by saml sso handles requests successfully

Diagnostic information:
- OpenLiberty version - reported on 19.0.0.6 and 20.0.0.6 but it is there from the beginning of the version where we introduced samlWeb-2.0 support
- Affected features - samlWeb-2.0
- Java version - 1.8.0_191

Server config snippet:

`
    
   <server description="authorization server">
        <featureManager>
        <feature>openidConnectServer-1.0</feature>
        <feature>jdbc-4.0</feature>
        <feature>appSecurity-2.0</feature>
        <feature>ldapRegistry-3.0</feature>
        <feature>localConnector-1.0</feature>
        <feature>samlWeb-2.0</feature>
        <feature>ssl-1.0</feature>
        <feature>adminCenter-1.0</feature>
        <feature>transportSecurity-1.0</feature>
        </featureManager>

        <samlWebSso20
                id="defaultSP"
                spCookieName="jazzop_sso_cookie_idp"
                forceAuthn="true"
                authFilterRef="samlAuthFilter"
                enabled="true">
    </samlWebSso20>

    <authFilter id="samlAuthFilter">
        <requestUrl id="samlRequestUrl" urlPattern="/authorize|/personalTokenManagement" matchType="contains" />
                <userAgent id="samlUserAgent" agent="Mozilla|Opera|app-password-enabled" matchType="contains"/>
    </authFilter>

        <openidConnectProvider id="oidc” oauthProviderRef=“OP” sessionManaged="true" />

        <oauthProvider id="OP"
            httpsRequired="true"
                autoAuthorize="true"
                customLoginURL=“/OP/form/login"
                accessTokenLifetime="7201"
                authorizationGrantLifetime="604801"
                passwordGrantRequiresAppPassword="true"
                internalClientId="AppPasswordClient"
                internalClientSecret=..
                trackOAuthClients="true">
            <databaseStore dataSourceRef="OAuthFvtDataSource" />
        </oauthProvider>
...
..
..

`

**Comment by mbroz2** [comment]
@arunavemulapalli please update the description of this release bug so that it follows/conforms to the [Bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
