### ISSUE TITLE
InvalidationTimeout doesn't work

### ISSUE THREAD

**Issue by pmezzomo** [OpenLiberty/open-liberty#18449]
Hello! 

I need to increase the application session time from 30 minutes to 24 hours.

I made the change to the server.xml file using the tag InvalidationTimeout, but it's not working.

` <httpSession invalidationTimeout="1440m"/>`

Do I need any additional configuration to increase session time?

Thank you!

**Comment by zhang-ca** [comment]
@pmezzomo can you enable the session trace : 
`com.ibm.ws.session.*=all`
I should able to find out the cause. Thanks.

**Comment by zhang-ca** [comment]
Also check web.xml, it might be overridden by 
```
         <session-config>

             <session-timeout>30</session-timeout>

          </session-config> 
```

**Comment by pmezzomo** [comment]
@zhang-ca we used the <session-config> with 1440, but it did not work. So I added this configuration, the session timeout increase 1h20m, but still some information does not load on the page after 30 minutes.
```
    <server description="http_timeout_config">    
     <httpSession invalidationTimeout="5h" invalidateOnUnauthorizedSessionRequestException="false"/>
    </server>
```
The 30 minutes is not configured in the code. I don't understand what's going on.

Thank you!

**Comment by zhang-ca** [comment]
It appears the session was invalidated by someone instead of timeout. Can you enable the session trace :
com.ibm.ws.session.*=all

**Comment by pmezzomo** [comment]
@zhang-ca I will enable  the session trace. Thank you!

**Comment by pmezzomo** [comment]
Hello @zhang-ca ! I believe we found the problem. Do you know what could be used to configure "**Idle** session timeout"? Thank you!

**Comment by zhang-ca** [comment]
Session timeout calculation based on idle time (that is, inactive session). What is "Idle session timeout" ?

**Comment by pmezzomo** [comment]
@zhang-ca We were able to keep the session for the user at 1 hour and 30 min, but he needs to be active. It's working. If the user leaves the session open for more than 10 minutes without action on the page, it expires. The page loses connection to the Backend. Do you know how we can configure this time of inactive session?

**Comment by zhang-ca** [comment]
This may not related to session, it look like either security token or backend connection timeout. 10 minutes time out is unusual for session in this case. Do you have any logs?

**Comment by zhang-ca** [comment]
The issue most likely due to nested <server> elements enclosed the `<httpSession>`

```
<server description="new server">
    ...
    <server description="http_timeout_config">    
     <httpSession invalidationTimeout="5h" invalidateOnUnauthorizedSessionRequestException="false"/>
    </server>
    ...
</server>
```

**Comment by zhang-ca** [comment]
The problem was solve with the data from this link.
https://www.ibm.com/docs/en/was-liberty/nd?topic=liberty-configuring-authentication-cache-in
