### ISSUE TITLE
Verify result of applying update to a checkpointed system

### ISSUE THREAD

**Issue by sebratton** [OpenLiberty/open-liberty#18507]
If ifix and fixpack force a clean then the checkpoint is erased. If there is any path to applying a fix without clearing out the checkpoint then we probably need to detect that and block the server checkpoint from being used after the update.

**Comment by tjwatson** [comment]
InstantOn is for container use.  Ifixes must be applied at container creation time.  This will be before any checkpoint is taken.

For on-host, when an iFix is applied the server typically does a clean start.  But the code that does that is early and will have run during the checkpoint process.  So on restore we would not detect this.  If we decide to support on-host scenario then we likely need some restore logic that detects this and force the server to restart and not use the checkpoint image to restart.

**Comment by tjwatson** [comment]
This is not a concern for restore.
