### ISSUE TITLE
Startup hang caused by plugin-cfg generator changes

### ISSUE THREAD

**Issue by wtlucy** [OpenLiberty/open-liberty#18530]
**Describe the bug**  
In server environments with restricted thread counts (via [maxThreads](https://openliberty.io/docs/21.0.0.7/reference/config/executor.html)), the changes made in #17161 can cause server startup to hang. Those changes introduced logic to perform the hostname lookup task in a separate thread via [ExecutorService.submit()](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ExecutorService.html#submit(java.lang.Runnable)); the existing logic performing the submit blocks waiting for the task to complete - which can cause a hang because the [ExecutorService](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ExecutorService.html) has no threads available to complete the task, and other threads are waiting on the thread that originally submitted the task.

**Steps to Reproduce**  
Deploy a server with a large number of applications (eg. 20) with a restricted max thread count configuration, eg. `<executor maxThreads="6"/>`

**Expected behavior**  
Server startup should never hang

**Diagnostic information:**  
 - OpenLiberty Version: 21.0.0.7 - 21.0.0.9
 - Affected feature(s): all

**Additional context**  
N/A

**Comment by jhanders34** [comment]
#regression

**Comment by mbroz2** [comment]
@wtlucy please update the description of this release bug so that it follows/conforms to the [Bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
