### ISSUE TITLE
JAX-RS 3.0 App endpoints never register when unmapped application is found in WAR classpath

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#18565]
@rumanaHaque discovered an issue with her SVT app.  The app was an EAR file that contained multiple WARs. None of them had an `Application` subclass but specified a `<servlet-name>jakarta.ws.rs.core.Application</servlet-name>`.  However, the EAR had a library that contained an `Application` subclass, so the `RESTfulServletContainerInitializer` was incorrectly attempting to map that application subclass to the servlet mapping class.  The result is that the `<servlet-class>` was never added to the servlet registration and all JAX-RS endpoints in the WARs were ignored.

**Comment by rumanaHaque** [comment]
Tested the patch for this fix, and I was able to access my JAX-RS urls after the fix.
