### ISSUE TITLE
Update logging metatype to better describe formats

### ISSUE THREAD

**Issue by frowe** [OpenLiberty/open-liberty#18638]
In com.ibm.ws.logging/resources/OSGI-INF/l10n/metatype.properties and com.ibm.ws.logging.osgi/resources/OSGI-INF/l10n/metatype.properties currently, these aliases are defined for trace.format:
```
trace.basic=Use the basic trace format.
trace.tbasic=Alias for the basic trace format.
trace.enhanced=Use the enhanced basic trace format.
trace.advanced=Use the advanced trace format.
```
These are useless for helping the user to decide which format to pick and don't describe what the various formats look like.  Consider expanding the alias to include details of the format or example of the output.

**Comment by dmuelle** [comment]
see also: https://github.com/OpenLiberty/docs/issues/4677

Docs issue for TBASIC and log format descriptions
