### ISSUE TITLE
Testing for: Add remote port option to the HTTP access log formats

### ISSUE THREAD

**Issue by kgibm** [OpenLiberty/open-liberty#18641]
## Test Strategy

Testing strategy for issue #18132

The PR shows the strategy in detail: https://github.com/OpenLiberty/open-liberty/pull/18133/files

Strategy:

1. The `CustomAccessLogFieldsTest` class already tests non-standard custom options so we add `ibm_remotePort` to the `newFields` field that does this (and add `%{remote}p` to all of the necessary test `server.xml` files).
2. A new test `testDifferentPortSpecifications` is added which specifically tests the contents of this new format. It enables the `*=info:com.ibm.ws.tcpchannel.internal.TCPReadRequestContextImpl=all` trace specification and then watches for the `read (async) requested for local` trace statement which will have the ephemeral port which is the compared to what is found in the JSON HTTP access log line (starting with `liberty_accesslog`).

### List of FAT projects affected

* `dev/com.ibm.ws.logging_fat`

### Test strategy

* What functionality is new or modified by this feature?
    * New, optional custom access log specifier `%{remote}p` which prints the remote (ephemeral) port of the client for that request.
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
    * Tests that the value of `%{remote}p` actually matches the ephemeral port value provided by the operating system.
    * Tests the functionality of `%p` and `%{remote}p` in either order since some of the logic of processing `%p` depends on order due to them both being the `p` specifier.
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)
    * None

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

* Kevin: 5

**Comment by kgibm** [comment]
@mrsaldana Manuel, please add your thoughts above when you have a chance.

**Comment by mrsaldana** [comment]
I concur that this contains the proper testing and do not think there is a gap in testing for this new access log directive. 

- Manuel: 5

**Comment by dave-waddling** [comment]
Hi @kgibm, FTS looks good having reviewed it and the testing is delivered and passed perfectly in the latest SOE. I've added the FAT Focal approval to the parent epic.

**Comment by kgibm** [comment]
@dave-waddling Thanks!
