### ISSUE TITLE
Upgrade ASM to 9.2

### ISSUE THREAD

**Issue by gjwatts** [OpenLiberty/open-liberty#18650]
Open Liberty relies on [ASM](https://asm.ow2.io/index.html).  We are currently running ASM 9.1, but to support Java 18, we need to upgrade to [ASM 9.2](https://asm.ow2.io/versions.html).

ASM related changes also need to be made to Eclipselink and covered in issue #18653.

These 2 changes are completely isolated from each other and can be delivered separately.

**Comment by tkburroughs** [comment]
All work complete.
