### ISSUE TITLE
Update Eclipselink to use ASM 9.2

### ISSUE THREAD

**Issue by gjwatts** [OpenLiberty/open-liberty#18653]
Update Eclipselink to use ASM 9.2.

**Comment by dazey3** [comment]
@gjwatts This has actually been integrated for awhile now, but the PRs for the blocking issues were not linked appropriately. That has been fixed and everything is integrated. Can we go ahead and close this out?

**Comment by gjwatts** [comment]
@dazey3 Thanks for taking care of that Will.  Yes, please close this issue out.

**Comment by tkburroughs** [comment]
Complete
