### ISSUE TITLE
After installing Liberty version 21.0.08, our Maximo application starts to hang upon logging in.

### ISSUE THREAD

**Issue by rontiris** [OpenLiberty/open-liberty#18660]
Opened Git Issue using personal email.
I can be reached via my IBM email..  tom.rontiris@us.ibm.com or through slack @tomrontiris

**Description**
Occurs on both **Open Liberty and Websphere Liberty**

Once we upgraded the Liberty server to use **21.0.0.8** we started to notice a problem logging into Maximo.
- We were originally using 21.0.06 which was working fine.
- We also tested using 21.0.0.7 which was working fine too.

**Steps to Reproduce**
1. Bring up the Maximo Login Page.
2. Enter username and password and click ok.
3. The Maximo start center appears to be stuck loading (see screen shots)
(sometimes the page will render, but after using Maximo it will begin to hang

**Expected behavior**
The startcenter/pages are expected to render and be displayed without hanging

**Diagnostic information:**
product = **Open Liberty 21.0.0.8** (wlp-1.0.55.cl210820210727-1323)
wlp.install.dir = C:/OpenLiberty/wlp/
java.home = C:\OpenLiberty\wlp\java\sdk
java.version = 11.0.11
java.runtime = Java(TM) SE Runtime Environment (11.0.11+9)
os = Windows 10 (10.0; amd64) (en_US)
process = 48104@DESKTOP-EEGNKUL

also happens

product = **WebSphere Application Server 21.0.0.8** (wlp-1.0.55.cl210820210727-1323)
wlp.install.dir = /opt/ibm/wlp/
server.output.dir = /opt/ibm/wlp/output/defaultServer/
java.home = /opt/ibm/java/jre
java.version = 1.8.0_291
java.runtime = Java(TM) SE Runtime Environment (8.0.6.31 - pxa6480sr6fp31-20210510_01(SR6 FP31))
os = Linux (4.18.0-193.41.1.el8_2.x86_64; amd64) (en_US)
process = 10@10.254.17.69

**Comment by rontiris** [comment]
Open Liberty Logs, xml, screnshots
[openLiberty21008.zip](https://github.com/OpenLiberty/open-liberty/files/7211658/openLiberty21008.zip)

Websphere Liberty 21.0.0.8 - Messages.log
[websphereliberty21008.zip](https://github.com/OpenLiberty/open-liberty/files/7211678/websphereliberty21008.zip)

**Comment by rontiris** [comment]
Not sure if its related to a recent fix that was made in 21.0.0.8.  Looking through the release notes, there appears to have been a JSP Logic change (https://github.com/OpenLiberty/open-liberty/issues/17828) made, not sure if its related or the cause of our issue?

**Comment by jvanhill** [comment]
@rontiris - If you have opened a support case at https://www.ibm.com/mysupport, is it ok if we close this issue?
