### ISSUE TITLE
NullPointerException in JaxRsFactoryImplicitBeanCDICustomizer

### ISSUE THREAD

**Issue by jim-krueger** [OpenLiberty/open-liberty#18663]
There currently is a potential for the following NPE in the 21.0.0.9 service release:
java.lang.NullPointerException at com.ibm.ws.jaxrs20.cdi.component.JaxRsFactoryImplicitBeanCDICustomizer.getClassFromCDI(JaxRsFactoryImplicitBeanCDICustomizer.java:241)

**Comment by una-tapa** [comment]
Closing as the fix was merged.

**Comment by mbroz2** [comment]
@jim-krueger @una-tapa please update the description of this release bug so that it follows/conforms to the [Bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)

**Comment by punktilious** [comment]
What's the trigger for this and is there a workaround other than using 21.0.0.11? We see this NPE on some requests in our performance environment (using 21.0.0.9). Is it a concurrency issue?
