### ISSUE TITLE
Jakarta EE9: stream was already closed!

### ISSUE THREAD

**Issue by jagraj** [OpenLiberty/open-liberty#18681]
**Describe the bug**
I transformed my EE8 application to Jakarta EE9 runtime and I am getting following error warnings in the log.
I did enable trace specification `*=info:com.ibm.ws.webcontainer*=all:com.ibm.wsspi.webcontainer*=all:com.ibm.ws.webcontainer31*=all:HTTPChannel=all:TCPChannel=all:websockets=all:com.ibm.ws.jsf*=all:org.apache.myfaces*=all:SSLChannel=all ` and collected the logs and you can find them as an attachment to this issue.

```
[WARNING ] Error trying to load and send resource stylesheet.css with library css :com.ibm.ws.http2.upgrade.H2Exception: stream was already closed!
com.ibm.ws.http2.upgrade.H2Exception: stream was already closed!
[WARNING ] SRVE8115W: WARNING: Cannot set status. Response already committed.
[WARNING ] Error trying to load and send resource utils.js with library null :com.ibm.ws.http2.upgrade.H2Exception: stream was already closed!
com.ibm.ws.http2.upgrade.H2Exception: stream was already closed!
[WARNING ] SRVE8115W: WARNING: Cannot set status. Response already committed.
```

If there is a stack trace, please include the FULL stack trace (without any `[internal classes]` lines in it). To find the full stack trace, you may need to check in `$WLP_OUTPUT_DIR/messages.log`

**Steps to Reproduce**
1. Install GarageSale Jakarta EE9 application.
2. Perform few transactions and I get these errors in the log.

**Expected behavior**
We should not see these errors in the logs.

**Diagnostic information:**
 - OpenLiberty Version: 21.0.0.10 (wlp-1.0.57.cl211020210919-1100)
 - Java Version: 1.8.0_292
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**
Here are the logs with the trace.
[stream-closed.zip](https://github.com/OpenLiberty/open-liberty/files/7218352/stream-closed.zip)

**Comment by wtlucy** [comment]
Hi @jagraj, these warnings occur because the client you're using is ending HTTP/2 streams before the server/app can send over complete resources. That's typical behavior for a client, but for better or worse we throw the `IOException`/`H2Exception` so that applications can handle the condition. See https://github.com/OpenLiberty/open-liberty/issues/12490.

There's a configuration property you can set to disable this IOE behavior:
`<httpOptions id="http_options_id" ThrowIOEForInboundConnections="false"/>`

**Comment by pnicolucci** [comment]
@jagraj can this issue be closed with the solution that @wtlucy provided?

**Comment by jagraj** [comment]
Thank you, closing this issue now.
