### ISSUE TITLE
Avoid inferring caller in LogRecord.getSourceClassName and LogRecord.getSourceMethodName in Liberty HPEL

### ISSUE THREAD

**Issue by ellen-lau** [OpenLiberty/open-liberty#18695]
Currently the logging speed of Liberty HPEL is much slower than in tWAS HPEL (reported to be 6-7x slower), mainly because Liberty HPEL keeps calling JUL's `inferCaller()` when logging System.out.print events. A similar issue #7433 was fixed for logging but not for HPEL. 

The following stack trace highlights the issue:
```
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/J9VMInternals.getStackTrace(Native Method)
4XESTACKTRACE                at java/lang/Throwable.getInternalStackTrace(Throwable.java:292(Compiled Code))
4XESTACKTRACE                at java/lang/Access.getStackTraceDepth(Access.java:108(Compiled Code))
4XESTACKTRACE                **at java/util/logging/LogRecord.inferCaller(LogRecord.java:557(Compiled Code))**
4XESTACKTRACE                **at java/util/logging/LogRecord.getSourceClassName(LogRecord.java:319(Compiled Code))**
4XESTACKTRACE                at com/ibm/ws/logging/hpel/impl/LogRecordWrapper.<init>(LogRecordWrapper.java:75(Compiled Code))
4XESTACKTRACE                at com/ibm/ws/logging/hpel/handlers/LogRecordHandler$SerializationBuffer.serialize(LogRecordHandler.java:190(Compiled Code))
4XESTACKTRACE                at com/ibm/ws/logging/hpel/handlers/LogRecordHandler.processEvent(LogRecordHandler.java:95(Compiled Code))
4XESTACKTRACE                at com/ibm/ws/logging/hpel/handlers/LogRecordHandler.publish(LogRecordHandler.java:236(Compiled Code))
4XESTACKTRACE                at com/ibm/ws/logging/internal/hpel/HpelTraceServiceWriter$NoCloseLogRecordHandler.publish(HpelTraceServiceWriter.java:305(Compiled Code))
4XESTACKTRACE                at com/ibm/ws/logging/internal/hpel/HpelTraceServiceWriter.repositoryPublish(HpelTraceServiceWriter.java:283(Compiled Code))
4XESTACKTRACE                at com/ibm/ws/logging/internal/hpel/HpelBaseTraceService.echo(HpelBaseTraceService.java:46(Compiled Code))
4XESTACKTRACE                at com/ibm/ws/logging/internal/impl/BaseTraceService$TrOutputStream.flush(BaseTraceService.java:1626(Compiled Code))
4XESTACKTRACE                at java/io/PrintStream.flush(PrintStream.java:362(Compiled Code))
4XESTACKTRACE                at com/ibm/ws/logging/internal/impl/BaseTraceService$TeePrintStream.println(BaseTraceService.java:1556(Compiled Code))
```

tWAS HPEL avoids this by setting `LogRecord.setSourceClassName("")` and `LogRecord.logRecord.setSourceMethodName("")` right after LogRecord is created, so that `inferCaller()` in the JUL methods `getSourceClassName()` and `getSourceMethodName()`  later on will be skipped. 

This functionality can be potentially applied to Liberty HPEL as a fix; from testing, the performance looks to have a significant increase (~450%).

<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 20.0px 'Helvetica Neue'"><b>Before Change (average over 5 trials)</b></p>

Action | Threads | Duration (s) | Delay (ms) | Actions Completed | Actions per Second
-- | -- | -- | -- | -- | --
log | 1 | 90 | 0 | 3774511 | 41938.4
<br class="">
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 20.0px 'Helvetica Neue'"><b>After Change (average over 5 trials)</b></p>

Action | Threads | Duration (s) | Delay (ms) | Actions Completed | Actions per Second
-- | -- | -- | -- | -- | --
log | 1 | 90 | 0 | 17179946.4 | 190888
<br class="">

**Comment by donbourne** [comment]
@ellen-lau , You mentioned this is for System.out.print events -- do we successfully get the source class name in those cases?  I expect we don't... so at least for the System.out.print case this seems like an obvious thing to block.  in that simple case, I think you could use the loggerName to determine if the call came from System.out / System.err.

**Comment by mbroz2** [comment]
@ellen-lau plz update the first comment to follow the [Bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
Also, should this issue be tagged with `performance` label?
