### ISSUE TITLE
Tags of gauges are ignored by OpenLiberty

### ISSUE THREAD

**Issue by jonasrutishauser** [OpenLiberty/open-liberty#18711]
**Describe the bug**
MP Metrics 3.0 Implementation of OpenLiberty ignores Tags when registering a gauge.

**Steps to Reproduce**
Use `metricRegistry.gauge(String, Supplier, Tags...)` or `metricRegistry.gauge(MetricID, Supplier)` with tags.
The only Method that works is `metricRegistry.gauge(Metadata, Supplier, Tags...)`.

**Expected behavior**
Tags are not ignored.

**Diagnostic information:**
 - OpenLiberty Version: all
 - Java Version: all
 - server.xml configuration with `mpMetrics-3.0` enabled

**Additional context**

**Comment by mbroz2** [comment]
Fixed via https://github.com/OpenLiberty/open-liberty/pull/19139
