### ISSUE TITLE
NPE when creating an HttpAuthenticationMechanism with the default package

### ISSUE THREAD

**Issue by benjamin-confino** [OpenLiberty/open-liberty#18836]
When you create a HttpAuthenticationMechanism with the default package:

As part of creating a bean for it weld will call getPackage() on the class object. In some environments getPackage() will return null and promptly cause an NPE

Thus far the only environment I have seen this is in the CICS team's test environment. 

The fix is to update weld to 3.1.8.Final where they explicitly check for the default package. This will be done under issue #18835

**Comment by benjamin-confino** [comment]
This is the weld issue: https://issues.redhat.com/browse/WELD-2674 - it looks like this applies in more contexts than HttpAuthenticationMechanism

**Comment by mbroz2** [comment]
@benjamin-confino please update the description of this release bug so that it follows/conforms to the [Bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
