### ISSUE TITLE
The com.ibm.websphere.logging.WsLevel class is not visible as an API

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/open-liberty#18844]
**Describe the bug**  
The `com.ibm.websphere.logging.WsLevel` API is not exposed in an API jar for applications to compile against, as it is not present in the `wlp/dev/api/ibm/` directory. As such no javadoc is present as well.

Liberty APIs:  https://www.ibm.com/docs/en/was-liberty/nd?topic=interfaces-liberty-api

The [WsLevel class](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.logging.core/src/com/ibm/websphere/logging/WsLevel.java) is marked as an IBM-API-Package in the kernelCore-1.0.mf, however, it does not get packaged into an API jar.

In WebSphere traditional, it is visible as an API (https://www.ibm.com/docs/en/wash/8.5?topic=SSCKBL_8.5.5/com.ibm.websphere.javadoc.doc/web/apidocs/com/ibm/websphere/logging/WsLevel.html).

**Steps to Reproduce**  
Use the `com.ibm.websphere.logging.WsLevel` class to add WsLevels to your application logs, when trying to compile the application, the WsLevel class will not be found and errors will be thrown.

**Expected behavior**  
The `com.ibm.websphere.logging.WsLevel` API should be present in the `wlp/dev/api/ibm/` directory and exposed as an API jar, where applications can use the WsLevel class. The corresponding JavaDoc should be available as well.

**Diagnostic information:**  
 - OpenLiberty Version: 16.0.0.2-22.0.0.5
 - Affected feature(s): N/A, part of the Liberty Kernel.
 - Java Version: Java 8+
 - server.xml configuration (WITHOUT sensitive information like passwords): N/A

**Comment by pgunapal** [comment]
After discussing it interally, it was determined that there was not a real use case for making the `com.ibm.websphere.logging.WsLevel` class visible as an API to applications and also making the javadoc publicly available. As an alternative, the application can use new Level with similar attributes to the levels that WsLevel provides (e.g. AUDIT).

**Comment by pgunapal** [comment]
Re-opening, as the `com.ibm.websphere.logging.WsLevel` class not being exposed as an API is causing problems, when older applications that use this class are updating their dependencies to the latest version of Liberty, those applications that have code to access this class, can not access it anymore during compile time. Looks like when the migration happened for 16.0.0.2 to switch from 8.5.5.x, the `com.ibm.websphere.logging.WsLevel` class was removed from the API jars.

**Comment by mbroz2** [comment]
@pgunapal please update the description (first comment) of this `release bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
