### ISSUE TITLE
Fix PasswordUtil.passwordEncode() with "hash" option

### ISSUE THREAD

**Issue by acdemyers** [OpenLiberty/open-liberty#18866]
**Describe the bug**  
The PasswordUtil.passwordEncode() API is not honoring  "hash" encoding option.  If a user call passwordEncode() with a password and the "hash" option an null values is always returned.

The "hash" encoding option works fine from the securityUtillity command line tool.

**Steps to Reproduce**  

In code 

   ```
 String hashPassword = SecurityUtility.passwordEncode("hash", "testpassword");

    if (hashPassword != null)
      System.out.println("Hash password is " + hashPassword);
   else
     System.out.println("Failed to create the hashed password");

```

**Expected behavior**  

The SecurityUtility.passwordEncode() API with the "hash" option is expected to return a hashed password.

**Diagnostic information:**  
 - OpenLiberty Version:  Since the feature was added to Liberty until 210011
 - Affected feature(s) : <feature>passwordUtilities-1.0</feature>
 - Java Version: n/a
 - server.xml configuration:  Just add the feature <feature>passwordUtilities-1.0</feature> and Application code has to call the API

**Additional context**

**Comment by mbroz2** [comment]
@acdemyers please update the description of this release bug so that it follows/conforms to the [Bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
