### ISSUE TITLE
RTC 250837: SVT: api doc server url has pod name as host in ICp environment

### ISSUE THREAD

**Issue by tam512** [OpenLiberty/open-liberty#1888]
- Test with ICp 2.1.0.1 GA.  
- Deploy ibm-open-liberty V 1.0.0 Helm chart using images tamdocker/mp-ol-social:mp  ( _This image was tested on stand-alone docker )_
<img width="587" alt="screen shot 2018-01-30 at 1 02 31 pm" src="https://user-images.githubusercontent.com/22480038/35585579-f162f176-05bd-11e8-9861-43649390a926.png">
<img width="645" alt="screen shot 2018-01-30 at 1 05 12 pm" src="https://user-images.githubusercontent.com/22480038/35585684-44374280-05be-11e8-8ea6-6865f9480c5e.png">

- After it's done deploying, I see that the pod was started ok
```
[root@aussvt107 icp]# kubectl get pod
NAME                                                              READY     STATUS    RESTARTS   AGE
mp-ol-social-ibm-open-li-779df996cd-9tznp   1/1       Running   0          2h
```
-  The container log shows url for /openapi and /api/explorer as following:

[1/30/18 16:24:05:873 UTC] 0000002a com.ibm.ws.http.internal.VirtualHostImpl                     A CWWKT0016I: Web application available (default_host): http://mp-ol-social-ibm-open-li-779df996cd-9tznp:80/api/explorer/
................
................
[1/30/18 16:24:06:804 UTC] 0000002c com.ibm.ws.http.internal.VirtualHostImpl                     A CWWKT0016I: Web application available (default_host): http://mp-ol-social-ibm-open-li-779df996cd-9tznp:80/openapi/
- View /openapi by pointing to the proxy machine ip or host (e.g. https://proxy100.rtp.raleigh.ibm.com/openapi), and I see that the server urls have the pod's name as hostname 
```
servers:
- url: http://mp-ol-social-ibm-open-li-779df996cd-9tznp:80/SocialSphereWebService
- url: https://mp-ol-social-ibm-open-li-779df996cd-9tznp:443/SocialSphereWebService
```
- When running GET in "Try it out", it throws error TypeError: Failed to fetch.  I don't see any error in the container log

**Comment by tam512** [comment]
#link 250837

**Comment by tam512** [comment]
I see the same issue after deployed the application to IBM Cloud (public)
pod's name:  
```
# kubectl get pods
NAME                                       READY     STATUS    RESTARTS   AGE
mp-ol-social-ibm-open-li-776bb6f9d-mtg2r   1/1       Running   0          1h
```
- server url in /openapi
```
servers:
- url: http://mp-ol-social-ibm-open-li-776bb6f9d-mtg2r:80/SocialSphereWebService
- url: https://mp-ol-social-ibm-open-li-776bb6f9d-mtg2r:443/SocialSphereWebService
```
- Failure in running 'Try it out' button for GET is TypeError: NetworkError when attempting to fetch resource.

**Comment by mrglavas** [comment]
@tam512 Please verify and close.

**Comment by tam512** [comment]
Verified using build https://rtpgsa.ibm.com/projects/l/liberty.build/liberty/WASX.LIBERTY/daily/20180216-1309.27.linux/linux/zipper/externals/installables/openliberty-all-18.0.0.1-20180216-1410.zip
