### ISSUE TITLE
JakartaEE: Transformer: Direct rules do not override package rename rules

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#18907]
Eclipse transformer issue:
Direct rules do not override package rename rules
https://github.com/eclipse/transformer/issues/190

Part of: JakartaEE: Deliver Jakarta EE 9
#9876

The transformer issue has been delivered, via:
https://github.com/eclipse/transformer/pull/196

**Comment by bjhargrave** [comment]
I am not sure that direct rules should take precedence over package renames. Need to be careful to change such behavior.
