### ISSUE TITLE
NullpointerException in JSP after upgrade

### ISSUE THREAD

**Issue by DantePichardo** [OpenLiberty/open-liberty#18941]
**Describe the bug**  
Upgraded to 21.0.0.9 with fix IFPH39418. The eba web app no longer works, when I try to open the login page, it crashes.

BundleLoader[com.ibm.ws.webcontainer_1.1.56.cl210920210824-2341] found local class com.ibm.websphere.servlet.response.StoredResponseCompat 13ms
	ModuleClassLoader[com.ibm.ws.webcontainer_1.1.56.cl210920210824-2341].loadClass(javax.servlet.http.HttpServletResponseWrapper)
	BundleLoader[com.ibm.ws.webcontainer_1.1.56.cl210920210824-2341].findClass(javax.servlet.http.HttpServletResponseWrapper)
	BundleLoader[com.ibm.ws.webcontainer_1.1.56.cl210920210824-2341] loading from import package: javax.servlet.http -> [com.ibm.websphere.javaee.servlet.3.1_1.0.56.cl210920210824-2341]
	BundleLoader[com.ibm.websphere.javaee.servlet.3.1_1.0.56.cl210920210824-2341].findLocalClass(javax.servlet.http.HttpServletResponseWrapper)
	BundleLoader[com.ibm.websphere.javaee.servlet.3.1_1.0.56.cl210920210824-2341] found local class javax.servlet.http.HttpServletResponseWrapper 0ms
	BundleLoader[com.ibm.ws.webcontainer_1.1.56.cl210920210824-2341] found local class com.ibm.websphere.servlet.response.StoredResponse 33ms
	BundleLoader[com.ibm.ws.webcontainer_1.1.56.cl210920210824-2341] found local class com.ibm.websphere.servlet.filter.ChainedResponse 36ms
	ModuleClassLoader[com.ibm.ws.webcontainer_1.1.56.cl210920210824-2341].loadClass(com.ibm.ws.webcontainer.util.ApplicationErrorUtils)
	BundleLoader[com.ibm.ws.webcontainer_1.1.56.cl210920210824-2341].findClass(com.ibm.ws.webcontainer.util.ApplicationErrorUtils)
	BundleLoader[com.ibm.ws.webcontainer_1.1.56.cl210920210824-2341].findLocalClass(com.ibm.ws.webcontainer.util.ApplicationErrorUtils)
	ModuleClassLoader[com.ibm.ws.webcontainer_1.1.56.cl210920210824-2341 - /Users/dantepichardo/Documents/development/522/vtd_web/server/server/lib/com.ibm.ws.webcontainer_1.1.56.jar].findClassImpl(com.ibm.ws.webcontainer.util.ApplicationErrorUtils)
	  read 6608 bytes from /Users/dantepichardo/Documents/development/522/vtd_web/server/server/lib/com.ibm.ws.webcontainer_1.1.56.jar!/com/ibm/ws/webcontainer/util/ApplicationErrorUtils.class
	  defining class com.ibm.ws.webcontainer.util.ApplicationErrorUtils
	BundleLoader[com.ibm.ws.webcontainer_1.1.56.cl210920210824-2341] found local class com.ibm.ws.webcontainer.util.ApplicationErrorUtils 14ms
	ModuleClassLoader[com.ibm.ws.webcontainer_1.1.56.cl210920210824-2341].loadClass(java.lang.StackTraceElement)
	ModuleClassLoader[com.ibm.ws.webcontainer_1.1.56.cl210920210824-2341].loadClass(com.ibm.websphere.ras.TruncatableThrowable)
	BundleLoader[com.ibm.ws.webcontainer_1.1.56.cl210920210824-2341].findClass(com.ibm.websphere.ras.TruncatableThrowable)
	BundleLoader[com.ibm.ws.webcontainer_1.1.56.cl210920210824-2341] loading from import package: com.ibm.websphere.ras -> [org.eclipse.osgi_3.16.0.cl210920210824-2341]
[ERROR   ] SRVE0777E: Exception thrown by application class 'java.io.File.<init>:277'
java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at com.ibm.ws.jsp.webcontainerext.JspDependent.isOutdated(JspDependent.java:84)
	at [internal classes]

	in this line:
	
	getServletContext( ).getRequestDispatcher( "/login.jsp" ).forward( request, response );

**Steps to Reproduce**  
Open the login page, using /Login path, which forwards to login.jsp

**Expected behavior**  
Open the login page

**Diagnostic information:**  
 - OpenLiberty Version: [21.0.0.9]
 - Affected feature(s) [jsp-2.2]
 - Java Version: Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_241-b07 16_Jan_2020_14_44 Mac OS X x64(SR6 FP5) (en_MX)
java version "1.8.0_241"
Java(TM) 2 Runtime Environment, Standard Edition (IBM build 1.8.0_241-b07 16_Jan_2020_14_44 Mac OS X x64(SR6 FP5))
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
IBM Java ORB build orbdev-userlvl-20200106.1711
XML build XL TXE Java 1.0.62
XML build IBM JAXP 1.6.1
XML build XML4J 4.5.31

 - server.xml configuration

 <featureManager>
        <feature>jsp-2.2</feature>
        <feature>jsf-2.0</feature>
        <feature>wab-1.0</feature>
        <feature>jndi-1.0</feature>
        <feature>servlet-3.1</feature>
        <feature>appSecurity-2.0</feature>
        <feature>usr:hydraJAAS</feature>
        <feature>ssl-1.0</feature>
        <feature>websocket-1.1</feature>
        <feature>ejbLite-3.1</feature>
        <feature>jaxrs-1.1</feature>
        <feature>cdi-1.0</feature>
        <feature>localConnector-1.0</feature>
        <feature>jwt-1.0</feature>
    </featureManager>

    <variable name="jaas.host" value="localhost"/>

    
    <httpEndpoint host="*" httpPort="${default.http.port}" httpsPort="${default.https.port}" id="defaultHttpEndpoint" sslOptionsRef="SSLOptions"/>
    <jspEngine prepareJSPs="-1" recompileJspOnRestart="true"/>
    <applicationMonitor dropinsEnabled="false" updateTrigger="disabled"/>
    <webContainer deferServletLoad="true" disablexPoweredBy="true" skipMetaInfResourcesProcessing="true"/>
    
     
    <application context-root="resources" id="com.ibm.storage.hydra.gui.resources" location="com.ibm.storage.hydra.gui.resources" name="com.ibm.storage.hydra.gui.resources" type="war"/>
    <application context-root="help" id="com.ibm.storage.hydra.gui.help" location="com.ibm.storage.hydra.gui.help.war" name="com.ibm.storage.hydra.gui.help" type="war"/>
    <enterpriseApplication id="com.ibm.storage.message" location="com.ibm.storage.message.ear" name="com.ibm.storage.message">
        <classloader commonLibraryRef="global_ear_lib"/>
    </enterpriseApplication>
    <osgiApplication id="com.ibm.storage.hydra.gui.application" location="com.ibm.storage.hydra.gui.application.eba" name="com.ibm.storage.hydra.gui.application"/>

    
    <bundleRepository filesetRef="ext_plugins, int_plugins" id="global_eab_lib">
    </bundleRepository>
    <library filesetRef="ext_plugins, int_plugins" id="global_ear_lib">
    </library>
    <fileset dir="plugins" id="int_plugins"/>
    <fileset dir="${shared.app.dir}/plugins" id="ext_plugins"/>
    
        
    <keyStore id="TS7700Keystore" location="${tls.keystore}" password="***"/>
    <keyStore id="HydraMIKeystore" location="${ssl.keystore}" password="***" type="JKS"/>
    <keyStore id="HydraMITruststore" location="${ssl.truststore}" password="***" type="JKS"/>
    
    <ssl enabledCiphers="TLS_DHE_RSA_WITH_AES_128_CBC_SHA TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 TLS_DHE_RSA_WITH_AES_256_CBC_SHA TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384" id="SSLConfig" keyStoreRef="HydraMIKeystore" serverKeyAlias="${default.https.cert.alias}" sslProtocol="TLS" trustStoreRef="HydraMITruststore"/>
    <sslOptions id="SSLOptions" sslRef="SSLConfig"/>
    
    
    <jaasLoginModule className="com.ibm.storage.hydra.security.CIMJaasLoginModuleImpl" id="Jaas2.HydraCIM" libraryRef="DummyLibrary">
        <options debug="${jaas.debug}" host="${jaas.host}" namespace="${jaas.cim.namespace}"/>
    </jaasLoginModule>
    <jaasLoginModule className="com.ibm.storage.hydra.security.CIMTestJaasLoginModuleImpl" id="CIMTestJaasLoginModuleImpl" libraryRef="DummyLibrary">
        <options debug="${jaas.debug}" host="${jaas.host}" namespace="${jaas.cim.namespace}"/>
    </jaasLoginModule>
    <jaasLoginModule className="com.ibm.security.ess.client.authn.WSTrustLoginModule" id="WSTrustLoginModule1" libraryRef="DummyLibrary">
        <options ESSConfigFile="${jaas.ess.primary.config}"/>
    </jaasLoginModule>
    <jaasLoginModule className="com.ibm.security.ess.client.authn.WSTrustLoginModule" id="WSTrustLoginModule2" libraryRef="DummyLibrary">
        <options ESSConfigFile="${jaas.ess.alternate.config}"/>
    </jaasLoginModule>
    <jaasLoginModule className="com.ibm.storage.hydra.security.CIMJaasHelper" id="CIMJaasHelper" libraryRef="DummyLibrary"/>
    <jaasLoginModule className="com.ibm.storage.hydra.security.ESSTestJaasLoginModuleImpl" id="ESSTestJaasLoginModuleImpl" libraryRef="DummyLibrary"/>
    <jaasLoginModule className="com.ibm.storage.hydra.security.LDAPLoginModule" id="LDAPLoginModule" libraryRef="DummyLibrary"/>
    <jaasLoginModule className="com.ibm.storage.hydra.security.LDAPTestJaasLoginModule" id="LDAPTestJaasLoginModule" libraryRef="DummyLibrary"/>
        <jaasLoginContextEntry id="Jaas2.HydraCIM" name="Jaas2.HydraCIM">
        <loginModuleRef>Jaas2.HydraCIM</loginModuleRef>
    </jaasLoginContextEntry>
    <jaasLoginContextEntry id="Jaas2.TestHydraCIM" name="Jaas2.TestHydraCIM">
        <loginModuleRef>CIMTestJaasLoginModuleImpl</loginModuleRef>
    </jaasLoginContextEntry>
    <jaasLoginContextEntry id="Jaas2.ESS.Server1" name="Jaas2.ESS.Server1">
        <loginModuleRef>WSTrustLoginModule1</loginModuleRef>
        <loginModuleRef>CIMJaasHelper</loginModuleRef>
    </jaasLoginContextEntry>
    <jaasLoginContextEntry id="Jaas2.ESS.Server2" name="Jaas2.ESS.Server2">
        <loginModuleRef>WSTrustLoginModule2</loginModuleRef>
        <loginModuleRef>CIMJaasHelper</loginModuleRef>
    </jaasLoginContextEntry>
    <jaasLoginContextEntry id="Jaas2.ESS.Server1.NoCIM" name="Jaas2.ESS.Server1.NoCIM">
        <loginModuleRef>WSTrustLoginModule1</loginModuleRef>
    </jaasLoginContextEntry>
    <jaasLoginContextEntry id="Jaas2.ESS.Server2.NoCIM" name="Jaas2.ESS.Server2.NoCIM">
        <loginModuleRef>WSTrustLoginModule2</loginModuleRef>
    </jaasLoginContextEntry>
    <jaasLoginContextEntry id="Jaas2.TestESS" name="Jaas2.TestESS">
        <loginModuleRef>ESSTestJaasLoginModuleImpl</loginModuleRef>
    </jaasLoginContextEntry>
    <jaasLoginContextEntry id="Jaas2.LDAP.Server" name="Jaas2.LDAP.Server">
        <loginModuleRef>LDAPLoginModule</loginModuleRef>
        <loginModuleRef>CIMJaasHelper</loginModuleRef>
    </jaasLoginContextEntry>
    <jaasLoginContextEntry id="Jaas2.LDAP.Server.NoCIM" name="Jaas2.LDAP.Server.NoCIM">
        <loginModuleRef>LDAPLoginModule</loginModuleRef>
    </jaasLoginContextEntry>
    <jaasLoginContextEntry id="Jaas2.TestLDAP" name="Jaas2.TestLDAP">
        <loginModuleRef>LDAPTestJaasLoginModule</loginModuleRef>
    </jaasLoginContextEntry>
    <library description="Classes are loaded from the JAAS feature, this is included because the login module has the attribute required." id="DummyLibrary" name="DummyLibrary"/>
        
    
    <logging consoleLogLevel="AUDIT" logDirectory="logs" maxFileSize="4" maxFiles="10" messageFileName="server.log"/>
    <basicRegistry/>
    
    <jndiEntry jndiName="BUILD_MODE" value="false"/>
    <jwtBuilder expiresInSeconds="-1" id="jwtBuilder" issuer="cluster0" keyAlias="jwtks" keyStoreRef="TS7700Keystore" sharedKey="***"/>
    <jwtConsumer id="jwtConsumer" issuer="cluster0" sharedKey="***" trustStoreRef="TS7700Keystore" trustedAlias="jwtks"/>
</server>

 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**

**Comment by epj** [comment]
Can you please recreate the issue with this trace in effect:  \*=info:com.ibm.ws.webcontainer\*=all:com.ibm.wsspi.webcontainer\*=all:HTTPChannel=all:GenericBNF=all:com.ibm.ws.jsp=finer

I don't need the trace from server startup, just start the trace before your login is attempted for the first time on the server.   

Send along trace.log and messages.log.   Thanks @DantePichardo .

**Comment by DantePichardo** [comment]
[ffdc_21.10.11_20.46.20.0.log](https://github.com/OpenLiberty/open-liberty/files/7326372/ffdc_21.10.11_20.46.20.0.log)
[messages.log](https://github.com/OpenLiberty/open-liberty/files/7326376/messages.log)
[trace_21.10.11_21.04.12.0.log](https://github.com/OpenLiberty/open-liberty/files/7326408/trace_21.10.11_21.04.12.0.log)

**Comment by epj** [comment]
The trace does not include the start of the login.jsp request.  Were there additional trace logs besides the one?  Can you please also send up the web.xml and ibm-web-ext.xml for your app?

**Comment by DantePichardo** [comment]
[trace_21.10.11_21.04.10.0.log](https://github.com/OpenLiberty/open-liberty/files/7330630/trace_21.10.11_21.04.10.0.log)
[trace_21.10.11_21.04.10.1.log](https://github.com/OpenLiberty/open-liberty/files/7330641/trace_21.10.11_21.04.10.1.log)
[trace_21.10.11_21.04.10.2.log](https://github.com/OpenLiberty/open-liberty/files/7330642/trace_21.10.11_21.04.10.2.log)
[trace_21.10.11_21.04.11.0.log](https://github.com/OpenLiberty/open-liberty/files/7330644/trace_21.10.11_21.04.11.0.log)

[trace_21.10.11_21.04.11.1.log](https://github.com/OpenLiberty/open-liberty/files/7330647/trace_21.10.11_21.04.11.1.log)
[trace_21.10.11_21.04.11.2.log](https://github.com/OpenLiberty/open-liberty/files/7330652/trace_21.10.11_21.04.11.2.log)
[trace_21.10.11_21.04.11.3.log](https://github.com/OpenLiberty/open-liberty/files/7330655/trace_21.10.11_21.04.11.3.log)

**Comment by DantePichardo** [comment]
[web.xml.log](https://github.com/OpenLiberty/open-liberty/files/7330686/web.xml.log
[ibm-web-ext.xmi.log](https://github.com/OpenLiberty/open-liberty/files/7330688/ibm-web-ext.xmi.log)
)

I changed the extension so github allows me to upload those.

**Comment by DantePichardo** [comment]
I closed ticket by mistake, please re-open if needed.

**Comment by epj** [comment]
[10/11/21 21:04:11:433 CDT] 00000496 id=00000000 com.ibm.ws.jsp.webcontainerext.JSPExtensionContext           2 getRealPath FileNotFound exception while obtaining realPath: null, exception was: java.io.FileNotFoundException: /WEB-INF/tlds/storage.tld

This error is trapped before the NPE but the missing file appears to be the cause of the NPE.   Can you check that /WEB-INF/tlds/storage.tld exists in your application?  If it is indeed missing, please either add the file or remove its taglib call from the JSP, and see if the NPE goes away.   

Meanwhile, our code shouldn't hit a NPE so I'll continue to work on a fix for it.
