### ISSUE TITLE
Investigate weld-osgi-bundle versions in feature files

### ISSUE THREAD

**Issue by benjamin-confino** [OpenLiberty/open-liberty#18973]
Our feature files have outdated versions of the weld osgi bundle. We need to investigate if this is causing problems, if it can be updated without issue, and if there's a way to link things so this automatically updates to the latest version.

**Comment by benjamin-confino** [comment]
I'm closing this so it will appear in the release fix lists. The problem is resolved but currently we'll need to manually update these file next time we update weld.

**Comment by mbroz2** [comment]
@benjamin-confino please update the description of this release bug so that it follows/conforms to the [Bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
