### ISSUE TITLE
Environment data at top of messages.log differs for standard logging vs binary logging

### ISSUE THREAD

**Issue by alanh-ibm-uk** [OpenLiberty/open-liberty#19020]
In z/OS Connect EE we are trying to encourage customers to move from standard logging to binary logging for performance reasons. However, we have noticed some differences between the two (even after removing z/OS Connect EE features and just using Liberty ones).
Standard logging shows the env as:
********************************************************************************
product = WAS FOR Z/OS 21.0.0.9, z/OS Connect 03.00.48 (wlp-1.0.56.cl210920210824-2341)
wlp.install.dir = /u/ctgperf/21009/wlp/
server.config.dir = /var/zosconnect/servers/apirequesterLiberty/
java.home = /u/ctgperf/java8sr6/J8.0_64
java.version = 1.8.0_231
java.runtime = Java(TM) SE Runtime Environment (8.0.6.0 - pmz6480sr6-20190816_01(SR6))
os = z/OS (02.03.00; s390x) (en_US)
process = 16843242@WINMVS22 
********************************************************************************
whereas binary logging shows the env as:
************ Start Display Current Environment ************
WAS FOR Z/OS 21.0.0.9, z/OS Connect 03.00.48 (wlp-1.0.56.cl210920210824-2341) running with process name server1 and process id 16843030
Host Operating System is z/OS, version 02.03.00
Java version = 1.8.0_281, Java Compiler = j9jit29, Java VM name = IBM J9 VM
Java Home = /java/java80_bit64_sr6_fp26/J8.0_64
Classpath = /u/ctgperf/21009/bin/tools/zosconnect.jar:/usr/include/java_classes/ifaedjreg.jar:/usr/include/java_classes/IRRRacf.jar:/u/ctgperf/21009/bin/../wlp/bin/tools/ws-javaagent.jar:/u/ctgperf/21009/bin/../wlp/bin/tools/ws-javaagent.jar
Java Library path = /java/java80_bit64_sr6_fp26/J8.0_64/lib/s390x/compressedrefs:/java/java80_bit64_sr6_fp26/J8.0_64/lib/s390x:/java/java80_bit64_sr6_fp26/J8.0_64/lib/s390x/compressedrefs:/java/java80_bit64_sr6_fp26/J8.0_64/lib/s390x/j9vm:/java/java80_bit64_sr6_fp26/J8.0_64/lib/s390x:/java/java80_bit64_sr6_fp26/J8.0_64/../lib/s390x:/java/java80_bit64_sr6_fp26/J8.0_64/lib/icc:/java/java80_bit64_sr6_fp26/J8.0_64/lib/s390x:/usr/lib/java_runtime:/u/ctgperf/21009/bin/../runtime/lib/native/zos:
************* End Display Current Environment *************
When viewing the standard log, we find wlp.install.dir and server.config.dir very useful, but these are missing from the binary log.
Similarly, when viewing the binary log, we find Classpath and Java Library path useful, but these are missing from the standard log.
It would be great if the same data (with all these fields) appeared in both.

**Comment by mbroz2** [comment]
Fixed via https://github.com/OpenLiberty/open-liberty/pull/19393
