### ISSUE TITLE
Feature Test Summary for MicroProfile JWT 2.0

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#19032]
## Test Strategy
The general test strategy for the Jakarta EE 9 Feature is to repeat all tests run for Jakarta EE 8 by transforming them to use the Jakarta packages. Both mp.jwt FAT projects have been updated to to run with EE9.

### List of FAT projects affected
- com.ibm.ws.security.mp.jwt.1.1_fat - tests mpJwt 1.1 function and repeats for 1.2.  A repeat with 2.0 (which incorporating EE9) has now been added
- com.ibm.ws.security.mp.jwt.1.2_fat - tests mpJwt 1.2 function.  A repeat with 2.0 (which incorporating EE9) has now been added
- io.openliberty.microprofile.jwt.2.0.internal_fat_tck added to cover Jakarta EE and new mpJwt-2.0 feature.

### Test strategy

* No new function was added and therefore no new tests needed to be added
* Logic was added to the FAT projects to transform the test test apps and configurations to run with the jakarta packages
* The repeats run in LITE mode, but both projects were run in FULL Mode with EE9/mpJwt-2.0

## Confidence Level
5

**Comment by c00crane** [comment]
#17844

**Comment by clarkek123** [comment]
https://github.com/OpenLiberty/open-liberty/issues/18759  incorporated the new MP JWT 2.0 TCK FAT.

**Comment by ayoho** [comment]
I gave this FAT approval, so I'll go ahead and close this out.
