### ISSUE TITLE
Feature Test Summary for JWT SSO (Security SSO)

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#19035]
## Test Strategy
The general test strategy for the Jakarta EE 9 Feature is to repeat all tests run for Jakarta EE 8 by transforming them to use the Jakarta packages. The jwtSso FAT project has been updated to to run with EE9.

### List of FAT projects affected
- com.ibm.ws.security.jwtsso_fat - All tests already repeated with noMpJwt,  mpJwt 1.0 and 1.2.  Repeats were added for mpJwt 2.0 (including EE9) as noMpJwt with EE9.
- com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1	- removal of jwtSso-1.0 during transform for EE9 repeat removed
- com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1	- removal of jwtSso-1.0 during transform for EE9 repeat removed
- com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1	- removal of jwtSso-1.0 during transform for EE9 repeat removed
- com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1	- removal of jwtSso-1.0 during transform for EE9 repeat removed
- com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1	- removal of jwtSso-1.0 during transform for EE9 repeat removed
- com.ibm.ws.security.oidc.server_fat(.oidc) - remove skips for EE9 repeats from several test cases (test case is in com.ibm.ws.security.oidc.server_fat, but runs as part of com.ibm.ws.security.oidc.server_fat.oidc)
- com.ibm.ws.security.saml.sso_fat - remove skips for EE9 repeats from several test cases
- com.ibm.ws.security.social_fat(.LibertyOP) - remove skips for EE9 repeats from several test cases (test case is in com.ibm.ws.security.social_fat, but runs as part of com.ibm.ws.security.social_fat.LibertyOP)

### Test strategy

* No new function was added and therefore no new tests needed to be added
* Logic was added to the FAT projects to transform the test apps and configurations to run with the jakarta packages
* Repeats were added to run the tests with and without EE9
* Tests that were shipped when running with EE9 have not had the "skip" removed and they are now running both without and with EE9.
* Configs that had the jwtSso-1.0 feature removed when running with EE9 have been restored (the removal has been removed)

## Confidence Level
5

**Comment by c00crane** [comment]
#18952

**Comment by c00crane** [comment]
Not needed

**Comment by c00crane** [comment]
#link 19150

**Comment by c00crane** [comment]
#19150

**Comment by ayoho** [comment]
LGTM 👍
