### ISSUE TITLE
Checkpoint - investigate suspending threads before prepare and resuming after restore

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#19040]
Investigate if it is possible to suspend running Liberty threads before doing a prepare operation for checkpoint and then resume the threads after running the restore hooks when restoring the process.

This is to protect threads from resuming "too early" before any restore hooks have successfully restored their state to acceptable levels.

**Comment by vijaysun-omr** [comment]
Some thought to kick off the discussion on the possible sequencing :

1. Some Liberty thread wants to initiate a checkpoint and calls the API offered by (OpenJ9) JVM to do so.
2. The first step in this JVM API routine to checkpoint would be to require all threads to yield, along similar lines to what happens for a GC (say)
3. The JVM API routine then "resumes" the Liberty thread that wanted to do the checkpoint and runs the pre-checkpoint hooks on that thread
4. If the Liberty thread that wanted to do the checkpoint does not return from executing all the pre-checkpoint hooks within a certain time interval T (can be configured) then we declare a timeout has occurred and then return an error saying that the checkpoint could not be taken within the configured time interval T (automatically handles the deadlock case).   
5. If the Liberty thread that wanted to do the checkpoint does return from executing all the pre-checkpoint hooks within time interval T, then we pass execution down to the JVM layer to do whatever pre-checkpoint hooks it wants to run also on this checkpoint-requesting thread

In this scheme on the restore side, the only two threads in a runnable state would be the checkpoint-requesting one and another thread that is keeping track of elapsed time. So we avoid any race conditions on the restore side with other random threads, but the checkpoint-requesting thread would have to perform resumptions of both JVM threads (GC, JIT) and Java application threads interspersed with the tasks of running the JVM hooks and Liberty hooks in that order. Basically doing the "meta level" tasks of resuming threads and running hooks in the opposite order to what happened in the checkpoint run with the possibility again, that running some restore hook method falls victim to a deadlock, and in such a case, the thread keeping track of elapsed time would have to detect a timeout and return an error code saying that the restore was unsuccessful.

There may be things that are missing or unworkable in this, but I wanted to put down these thoughts so that we have something to evolve.

**Comment by vijaysun-omr** [comment]
fyi @tajila since you are interested in this topic

**Comment by vijaysun-omr** [comment]
I thought about whether I went too far in connecting up the checkpoint/restore process between Liberty and the JVM and its possible that I did, perhaps my position is better stated as : we should try to do as many of of those steps independently at the two layers as possible but if we cannot or do not want to make it work for some reason, e.g. use of Thread.suspend when its deprecated, then look for better options by connecting up the process across the two layers

**Comment by tjwatson** [comment]
think we may need some JVM assistance here for a few reasons:
- The Thread suspend/resume methods are deprecated and perhaps should be avoided at the liberty level because I can see it being removed at some point
- There is no reliable way for liberty to make sure it gets ALL the active threads because the Thread API to get active threads is inherently full of timing issues.
- It may be hard for Liberty to know what threads from the JVM that is should not suspend vs. its own threads.

Perhaps what we need is for `CRIUSupport.checkpointJVM` method to take two callable functions like this:

```java
	/**
	 * Checkpoint the JVM. This operation will use the CRIU options set by the options setters.
	 * <p>
	 * First the JVM will yield and pause all application threads from execution.  Then the specified
	 * prepare function will be run on the same thread that is calling this method.  If prepare returns true
	 * then the JVM will proceed with the checkpoint; otherwise the JVM will throw a checkpoint exception
	 * indicating that prepare failed.  Before throwing the exception the JVM will resume all threads that had
	 * been paused.
	 * <p>
	 * When the process is restored the JVM will control how the application threads are resumed.  Before
	 * resuming the application threads the specified restore function will be called.  If resume does not
	 * return true then a restore exception is thrown.  Before returning, all paused threads will be resumed,
	 * even if a restore exception is thrown.
	 * 
	 * @param prepare a function run after the JVM has paused all application threads and before the JVM checkpoint is performed
	 * @param restore a function run after the JVM has restored but before resuming all suspended threads
	 * @throws UnsupportedOperationException if CRIU is not supported
	 * @throws JVMCheckpointException if a JVM error occurred before checkpoint
	 * @throws SystemCheckpointException if a CRIU operation failed
	 * @throws RestoreException if an error occurred during or after restore
	 */
	public void checkpointJVM(Callable<Boolean> prepare, Callable<Boolean> restore)
```

Another option is to have the prepare and restore callables set with setters on the CRIUCheckpoint instance:

```java
	/**
	 * Sets the prepare hook which is called after pausing all application threads and before the process checkpoint
	 * is done.
	 * <p>Default: null
	 *
	 * @param prepare a function run after the JVM has paused all application threads and before the JVM checkpoint is performed
	 * @return this
	 */
	public CRIUSupport setPrepare(Callable<Boolean> prepare) {
                ...
	}

	/**
	 * Sets the restore hook which is called before resuming all suspended threads.
	 * <p>Default: null
	 *
	 * @param restore a function run after the JVM has restored but before resuming all suspended threads
	 * @return this
	 */
	public CRIUSupport setRestore(Callable<Boolean> restore) {
		...
	}
```

Then the JVM could do the timeout implementation like Vijay suggests.

**Comment by tajila** [comment]
I agree with Tom, I don't think the Thread.suspend/resume APIs should be used, they are deprecated but more importantly they do complicate yielding in the JVM. Also, I think it is easier for the JVM to track all the Threads that need to be paused.

It sounds like we are moving to a direction where the JVM runs all the hooks. I think this is a simpler model from a hook coordination perspective. 

On checkpoint:
1. Call checkpoint API
2. JVM suspends all other Threads
-------- enter single threaded phase ----------
3. Run application hooks
4. Run JVM hooks
5. Checkpoint JVM

On Restore:
1. Restore JVM
2. Run JVM hooks
3. Run application hooks
-------- exit single threaded phase ----------
4. Resume all other threads
5. Return from checkpoint API

Note: Its effectively "single threaded"

Personally, I prefer the `setPrepare(Callable<Boolean> prepare)` variant of the API. @tjwatson do you have a need for ordering/dependency between the hooks?

**Comment by tjwatson** [comment]
> Personally, I prefer the `setPrepare(Callable<Boolean> prepare)` variant of the API. @tjwatson do you have a need for ordering/dependency between the hooks?

I'm fine with the `setPrepare/setRestore` variants.  I think it is more consistent with the current "builder" API for `CRIUSupport`.  

For hook ordering:  I am suggesting the prepare and restore callables to be singletons for the `CRIUSupport` instance.  So it is a `set` operation, not an `add` operation.  The only order the JVM needs to be concerned about is when to call the prepare and restore with respect to the JVMs own hooks.  I agree with the order you have outlined for that.  Any ordering required by Liberty's prepare/restore hooks would be handled within our own prepare and restore callable functions.

**Comment by vijaysun-omr** [comment]
I am not sure the step 3 on both checkpoint and restore side are actually running in single threaded mode, in that I feel that we want the GC (and maybe the JIT) threads to be active while the application hooks run since they are "Java code".  It is single threaded wrt "Java threads"

The step 4 on the checkpoint side and step 2 on the restore side for JVM hooks may be some combination of "Java code" and "native (JVM) code" and so we may want the GC (and maybe the JIT) threads to be active when the "Java code" JVM hooks run but we may choose to be literally in single threaded mode when we run the "native (JVM) code" hooks if that is needed for some particular fixup task (e.g. walking the Java heap). 

Does this match others' thinking ?

**Comment by tajila** [comment]
> Does this match others' thinking ?

Yes, the effectively single threaded part means from an application perspective there is only a single thread running, and that is the thread running the hooks. The GC/JIT (and Timer) threads are not included in this.

Perhaps, it is more accurate to say "JVM suspends all other application Threads"

**Comment by tjwatson** [comment]
> Does this match others' thinking ?

From the callers point of view this is single threaded so I believe this conversation to be an implementation detail of the JVM.  For example, how the timeout is implemented in face of deadlock may be implemented with another running thread.  Any other threads the JVM needs for its own purposes should be fine and an implementation detail that I hope the caller will not need to know much about.  But such threads should only run JVM code, not user code when in "single threaded mode".

As an aside, I'm not sure how important it is for the GC to run while in "single threaded mode".  I would expect the JVM to optimize the heap during checkpoint after all hooks have been run and I would expect that to do "as much" GC as feasible before the process is checkpointed.  On the restore side for the short time we are in "single threaded mode" I would hope very little garbage will be created.  Perhaps resume the GC just before resuming all the application threads to do some cleanup while all the threads are already yielding to the GC (keep in mind I only pretend to know what is required for GC to run).

**Comment by tajila** [comment]
> As an aside, I'm not sure how important it is for the GC to run while in "single threaded mode". 

Any time java code is being executed there is always the potential that a GC may occur. In addition some GC policies operate concurrently, so the GC threads may be required to be active even if a collection is not required. But all of this is implementation detail and the application doesn't need to be aware. I do think we should perform a global collect+compact before checkpoint so we can minimize the size of the image, and delay the first GC upon restore for as long as possible.

> we may want the GC (and maybe the JIT) threads to be active when the "Java code" JVM hooks run but we may choose to be literally in single threaded mode when we run the "native (JVM) code" hooks if that is needed for some particular fixup task (e.g. walking the Java heap).

I'm not sure we will need to suspend the GC threads. Even when we are running non-Java JVM hooks, we will have VMAccess so we won't need to worry about interference from the GC when mutating the heap.

**Comment by DanHeidinga** [comment]
> On checkpoint:
> 
> 1. Call checkpoint API
> 2. JVM suspends all other Threads
>    -------- enter single threaded phase ----------
> 3. Run application hooks
> 4. Run JVM hooks
> 5. Checkpoint JVM

This strikes me as having all the same issues as `Thread::suspend`/`Thread::resume` and will be very prone to deadlocks.  Assume a Liberty thread is in a `synchronized` method operating on some internal data structure when step `(2)` happens and is suspended while holding that monitor.  If the application hooks in step `(3)` need to process the same data as the Liberty thread and attempt to take that lock, deadlock will occur.

There's some options here:
* Inject a `CheckpointInProgressException` into the blocked thread and resume it so it exits the monitor by throwing to nearest catch point for the CIPE.  All the same problems as `Thread::stop`.  Mentioned for completeness but not a good option.
* Wake the blocked thread up and allow it to proceed until it releases the monitor the `hook` needs.  Block it after that.  May require waking other threads to allow complicated synchronized accesses to proceed (ie: Thread A holds Lock1, waiting on Lock2, held by Thread B, etc).
* Have the application implement its own coordination layer to quiesce its threads akin to the volatile boolean `threadSuspended` suggested in [1].
* Throw a "DeadLockDetectedException" if the application hooks ever attempt to acquire a lock that's already held by another thread.  Would prevent Snapshot and report the problem on a thread that may be ready to handle it by ie waiting and retrying the snapshot later.

The same problem exists on the restore side with running Java-level hooks.  I think the only viable options here are either for the application layer to quiesce its own threads, or for the JVM to throw if the hooks attempt to take an owned monitor.

[1] http://cr.openjdk.java.net/~iris/se/12/latestSpec/api/java.base/java/lang/doc-files/threadPrimitiveDeprecation.html

**Comment by tjwatson** [comment]
> > On checkpoint:
> > 
> > 1. Call checkpoint API
> > 2. JVM suspends all other Threads
> >    -------- enter single threaded phase ----------
> > 3. Run application hooks
> > 4. Run JVM hooks
> > 5. Checkpoint JVM
> 
> This strikes me as having all the same issues as `Thread::suspend`/`Thread::resume` and will be very prone to deadlocks. Assume a Liberty thread is in a `synchronized` method operating on some internal data structure when step `(2)` happens and is suspended while holding that monitor. If the application hooks in step `(3)` need to process the same data as the Liberty thread and attempt to take that lock, deadlock will occur.

Exactly, this is something we need to be able to detect and handle.

> 
> There's some options here:
> 
> * Inject a `CheckpointInProgressException` into the blocked thread and resume it so it exits the monitor by throwing to nearest catch point for the CIPE.  All the same problems as `Thread::stop`.  Mentioned for completeness but not a good option.

I think this is problematic, and not really something we should do.

> * Wake the blocked thread up and allow it to proceed until it releases the monitor the `hook` needs.  Block it after that.  May require waking other threads to allow complicated synchronized accesses to proceed (ie: Thread A holds Lock1, waiting on Lock2, held by Thread B, etc).

This sounds overly complicated, not sure how easy it would be to coordinate given that waking up a thread may cause it to dive deeper into a nested synchronization on another lock or quickly jump out and into an unrelated lock.

> * Have the application implement its own coordination layer to quiesce its threads akin to the volatile boolean `threadSuspended` suggested in [1].

This is certainly advisable, but generally I'm not sure how easy we can get every thread in Liberty to block on some common signal to wait at the proper place before checkpoint.


> * Throw a "DeadLockDetectedException" if the application hooks ever attempt to acquire a lock that's already held by another thread.  Would prevent Snapshot and report the problem on a thread that may be ready to handle it by ie waiting and retrying the snapshot later.

I think some combination of throwing a `DeadLockDetectedException` if a hook attempts to acquire a lock that's already held by a paused thread and having the application coordinate its own threads (as much as feasible) before calling checkpoint may be a good start.

> 
> The same problem exists on the restore side with running Java-level hooks. I think the only viable options here are either for the application layer to quiesce its own threads, or for the JVM to throw if the hooks attempt to take an owned monitor.

I think the JVM needs to throw an exception regardless if a hook attempts to take an owned monitor by a paused thread.  It will always be possible for the application to make some mistake in quiescing its own threads.  I think it is better to fail the checkpoint/restore if this deadlock is detected.  As you say, on the checkpoint side the caller may be able to "fix" its state and try again to recover or simply fail at that point.

But how would this flow in practice?  We have this flow suggested:

checkpointJVM -> suspendThreads -> callPrepare -> runJVMHooks -> checkpointProcess

At `callPrepare` the Callable<Boolean> is called.  Some code in there tries to acquire a held monitor, at this point the `DeadLockDetectedException` is thrown.  What if the callable implementation catches such an exception and continues on to return true?  Would the JVM just continue on with the checkpoint?

What would happen on the restore side if deadlock is detected?  We have this flow suggested:

Restore JVM -> runJVMHooks -> callRestore -> resumeAllThreads -> return

What happens if the restore itself catches DeadlockDetectedException? and returns true?  Are all threads resumed and then return from checkpointJVM with no restore exception?  I think an exception should be thrown from checkpointJVM when prepare/resume thrown a runtime exception or if they return false/null.  In all cases when checkpointJVM returns all threads must be resumed regardless of if an exception occurs.  The caller supplying the prepare/resume can then decide how it wants to proceed.

> 
> [1] http://cr.openjdk.java.net/~iris/se/12/latestSpec/api/java.base/java/lang/doc-files/threadPrimitiveDeprecation.html

**Comment by tajila** [comment]
> There's some options here:

@DanHeidinga what do you think about having a configurable time limit for all the hooks to be completed by?

> Inject a CheckpointInProgressException into the blocked thread and resume...

Agreed, this is difficult to do and very problem prone.

> Wake the blocked thread up and allow it to proceed until it releases the monitor the hook needs. Block it after that...
> May require waking other threads to allow complicated synchronized accesses to proceed (ie: Thread A holds Lock1, waiting on Lock2, held by Thread B, etc).

There is no guarantee that this will end, it may continue indefinitely so we would still need another fallback.

> Have the application implement its own coordination layer to quiesce its threads akin to the volatile boolean threadSuspended suggested in [1].

Solves the problem in the application layer, but this could in theory happen with JVM hooks running code (JCL code) that we may not be necessarily aware of. I think this solution needs a fallback as well.

> Throw a "DeadLockDetectedException" if the application hooks ever attempt to acquire a lock that's already held by another thread. Would prevent Snapshot and report the problem on a thread that may be ready to handle it by ie waiting and retrying the snapshot later.

Probably the cleanest solution, but it does add some overhead in our locking paths. Also, its not trivial work as there will have to be JIT (codegen) changes.

**Comment by DanHeidinga** [comment]
> I think the JVM needs to throw an exception regardless if a hook attempts to take an owned monitor by a paused thread. It will always be possible for the application to make some mistake in quiescing its own threads. I think it is better to fail the checkpoint/restore if this deadlock is detected. As you say, on the checkpoint side the caller may be able to "fix" its state and try again to recover or simply fail at that point.

Reading your response I came to the same conclusion - some kind of `DeadLockDetectedException` is essential if we want the application level hooks to run as though single threaded.  There's some additional complexity around what **single threaded** means if an application hook can spawn new threads, especially if there are APIs that can spawn helper threads for you.  Do we keep such threads paused or let them run?

Now, back to the deadlock problem....
> 
> But how would this flow in practice? We have this flow suggested:
> 
> checkpointJVM -> suspendThreads -> callPrepare -> runJVMHooks -> checkpointProcess
> 
> At `callPrepare` the Callable is called. Some code in there tries to acquire a held monitor, at this point the `DeadLockDetectedException` is thrown. What if the callable implementation catches such an exception and continues on to return true? Would the JVM just continue on with the checkpoint?

Why wouldn't it?  The `DeadLockDetectedException` is a signal to the provider of the application hooks that they may be in an inconsistent state.  If they - as the author of that code - say to proceed, why would the JVM second guess them?

> 
> What would happen on the restore side if deadlock is detected? We have this flow suggested:
> 
> Restore JVM -> runJVMHooks -> callRestore -> resumeAllThreads -> return
> 
> What happens if the restore itself catches DeadlockDetectedException? and returns true? Are all threads resumed and then return from checkpointJVM with no restore exception? 

Again, I don't see we wouldn't.  If the single application hook (from the JVM's perspective) reports success, then that's a successful restore regardless of whether we detected a deadlock or not between the saved state and the hooks - they as the hook author said it's ok.

> I think an exception should be thrown from checkpointJVM when prepare/resume thrown a runtime exception or if they return false/null. 

Agreed.  If the user hook indicates failure, then we should abort the checkpoint process or terminate the VM on restore.

> In all cases when checkpointJVM returns all threads must be resumed regardless of if an exception occurs. The caller supplying the prepare/resume can then decide how it wants to proceed.

Right, if the user's hook returns success, the JVM will then resume the threads.

There's still a lot of risk in this process but it at least starts to bring the errors to the forefront by forcing the user to make a decision on how to handle the `DeadlockDetectedException` exception

**Comment by DanHeidinga** [comment]
> > There's some options here:
> 
> @DanHeidinga what do you think about having a configurable time limit for all the hooks to be completed by?

I think we'll want it eventually but I'd be tempted to leave it out for now.  Once we add it, then we need to handle the configuration options to allow the user to specify how long the timeout period should be, and provide some diagnostics on it, and ....

I'd put a little bit of thought into how to make it work and then leave it as a TODO for now.  It's not much different than having a rogue finalizer sleep forever and block the finalization queue.... we used to do a lot of work to handle that gracefully and eventually ripped it out as its better handled by the app.


> > Have the application implement its own coordination layer to quiesce its threads akin to the volatile boolean threadSuspended suggested in [1].
> 
> Solves the problem in the application layer, but this could in theory happen with JVM hooks running code (JCL code) that we may not be necessarily aware of. I think this solution needs a fallback as well.

Good point that this could occur in the JCL layer as well.
> 
> > Throw a "DeadLockDetectedException" if the application hooks ever attempt to acquire a lock that's already held by another thread. Would prevent Snapshot and report the problem on a thread that may be ready to handle it by ie waiting and retrying the snapshot later.
> 
> Probably the cleanest solution, but it does add some overhead in our locking paths. Also, its not trivial work as there will have to be JIT (codegen) changes.

I think this can mostly be handled in the out of line cases as it's fine if the thread attempting to lock exhausts the spin counts and then falls back to the blocking acquire which I thought was always out of line.  @vijaysun-omr correct me if I'm wrong here

**Comment by vijaysun-omr** [comment]
Yes, we never handle the contended case for monitor entry in line in JITed code, you would get into the `jitMonitorEntry` helper

**Comment by tjwatson** [comment]
> There's some additional complexity around what **single threaded** means if an application hook can spawn new threads, especially if there are APIs that can spawn helper threads for you. Do we keep such threads paused or let them run?

I agree, this is a complexity.   My initial thought is to keep it as simple as possible and have these threads immediately enter the paused state and do not let them start until the resume phase.  That may make sense on the resume side since the resume hook is already agreeing to do some process asynchronously, it may just happen a bit later than they expected and if the resume hook blocks on the async work to complete then they will cause a deadlock.

But I am less sure on the checkpoint side.  If a checkpoint hook does some async work they likely would want that work to complete before the checkpoint is done.  I can see arguments for pausing and for allowing new threads of work during the prepare and restore hook calls.

> > At `callPrepare` the Callable is called. Some code in there tries to acquire a held monitor, at this point the `DeadLockDetectedException` is thrown. What if the callable implementation catches such an exception and continues on to return true? Would the JVM just continue on with the checkpoint?
> 
> Why wouldn't it? The `DeadLockDetectedException` is a signal to the provider of the application hooks that they may be in an inconsistent state. If they - as the author of that code - say to proceed, why would the JVM second guess them?

Agreed

> 
> > What would happen on the restore side if deadlock is detected? We have this flow suggested:
> > Restore JVM -> runJVMHooks -> callRestore -> resumeAllThreads -> return
> > What happens if the restore itself catches DeadlockDetectedException? and returns true? Are all threads resumed and then return from checkpointJVM with no restore exception?
> 
> Again, I don't see we wouldn't. If the single application hook (from the JVM's perspective) reports success, then that's a successful restore regardless of whether we detected a deadlock or not between the saved state and the hooks - they as the hook author said it's ok.

Agreed


> I think we'll want it eventually but I'd be tempted to leave it out for now. Once we add it, then we need to handle the configuration options to allow the user to specify how long the timeout period should be, and provide some diagnostics on it, and ....

I do not see the benefit of a timeout if we have a "single threaded" execution and a runtime exception thrown when a deadlock is detected.  What would cause a timeout in this case?

**Comment by tjwatson** [comment]
> > Throw a "DeadLockDetectedException" if the application hooks ever attempt to acquire a lock that's already held by another thread. Would prevent Snapshot and report the problem on a thread that may be ready to handle it by ie waiting and retrying the snapshot later.
> 
> Probably the cleanest solution, but it does add some overhead in our locking paths. Also, its not trivial work as there will have to be JIT (codegen) changes.

Would this additional overhead only be for the duration of the JVM's life up to and including running the resume hooks?  In other words can we go back to "normal" locking paths once JVM decides to resume all threads and checkpointJVM returns?  I'm not concerned about taking additional (reasonable) overhead on the checkpoint side but it is important for the resume side to go back to "normal" optimal performance as quickly as possible.

**Comment by vijaysun-omr** [comment]
Since the extra logic to detect that we are in this checkpoint mode and throw the exception would go into the `jitMonitorEntry` helper as opposed to JIT generated code, I think the overhead would be fairly minimal. `jitMonitorEntry` helper (and others like it) are not considered to be performance critical enough and so adding some complexity in there for the (rare in practice) contended case won't affect performance after a restore I expect.

**Comment by tajila** [comment]
> Probably the cleanest solution, but it does add some overhead in our locking paths. Also, its not trivial work as there will have to be JIT (codegen) changes.

Given that the JIT will use the runtime helpers I now think this is a much simpler solution than I had first thought.

> I do not see the benefit of a timeout if we have a "single threaded" execution and a runtime exception thrown when a deadlock is detected. What would cause a timeout in this case?

The timeout solution is basically a catch-all for for all indefinitely blocking operations that may occur within the hooks.

**Comment by DanHeidinga** [comment]
> > There's some additional complexity around what **single threaded** means if an application hook can spawn new threads, especially if there are APIs that can spawn helper threads for you. Do we keep such threads paused or let them run?
> 
> I agree, this is a complexity. My initial thought is to keep it as simple as possible and have these threads immediately enter the paused state and do not let them start until the resume phase. That may make sense on the resume side since the resume hook is already agreeing to do some process asynchronously, it may just happen a bit later than they expected and if the resume hook blocks on the async work to complete then they will cause a deadlock.

It would be easy to code something up that created some helper threads to process additional work asynchronously and then wait on Condition (or join the threads) and wait indefinitely due to the helpers being paused.  I'm sure we can create an infinite set of "bad" situations so being clear on what should work and what absolutely will fail provides some ability of users to "do the right thing".

> 
> But I am less sure on the checkpoint side. If a checkpoint hook does some async work they likely would want that work to complete before the checkpoint is done. I can see arguments for pausing and for allowing new threads of work during the prepare and restore hook calls.

They can run into that without needing to create new threads though - any `.parallel()` operation on a Stream in a hook will be indefinitely blocked as the threads in the common ForkJoinPool will be blocked.  I'd have to look at the locking carefully to see if we'd ever detect this with the design we have so far.

Anyone using an existing thread pool will be in for a surprise if they're waiting on a response from a helper thread.

**Comment by vijaysun-omr** [comment]
A deadlock can also also occur with `java/util/concurrent` lock usage, rather than the standard `synchronized` usage. This would also need to be detected in some way.

**Comment by tjwatson** [comment]
Is it time to open an Open J9 issue to track the JVM side?

**Comment by vijaysun-omr** [comment]
Yes I think so

**Comment by tajila** [comment]
> A deadlock can also also occur with java/util/concurrent lock usage, rather than the standard synchronized usage. This would also need to be detected in some way.

While locking is the common case, a thread could be blocked indefinitely for other reasons. Examples are:

Class | method |  
-- | -- | --
java.lang.Object | wait |  
java.lang.Process | waitFor 
java.io.File | All file I/O operations |  
java.io.FileInputStream | open, read, skip |  
java.io.FileOutputStream | open, write |  
java.io.RandomAccessFile | open, read, write, seek |  
java.net.InetAddress | All lookup operations
java.nio.MappedByteBuffer | force |  
java.nio.channels.Selector | All blocking selection operations |  
java.nio.channels.FileChannel | read, write, lock, truncate, force, transferTo |  
java.nio.file | All file I/O operations |

**Comment by tjwatson** [comment]
> While locking is the common case, a thread could be blocked indefinitely for other reasons. Examples are:

But are these cases more likely in "single threaded" mode?  I'm not against adding some timeout to the hook operations, but I was thinking it would be to address issues that are out of control of the hook implementation (like trying to obtain a lock held by a paused thread).

**Comment by tajila** [comment]
>  I'm sure we can create an infinite set of "bad" situations so being clear on what should work and what absolutely will fail provides some ability of users to "do the right thing".

Any operation that has a `timeout` variant could be an issue. I think the only solution that can catch "malicious" code is the hook timeout solution. But in general, I think these cases can be considered programmer error.

**Comment by tajila** [comment]
> But are these cases more likely in "single threaded" mode? 

I don't think so, I just added them for completeness. I think standard java synchronization is the most likely scenario (which we have solutions for identifying) but the others are a possibility. Timeouts on hooks gives us the added security for all the other cases.

**Comment by tjwatson** [comment]
I'm going to close this issue.  We have moved to using new API in j9 to provide prepare and restore hooks which the JVM will run in "single-thread-mode".
