### ISSUE TITLE
MicroProfile 5.0 - Feature Test Summary

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#19080]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

In general, only sniff-testing is done for the umbrella features. More specific functional testing is done by the individual component FAT buckets.

### List of FAT projects affected

The following existing tests are now repeated for MicroProfile 5.0
`io.openliberty.microprofile.internal_fat/fat/src/io/openliberty/microprofile/internal/test/suite/BasicJAXRSCDITest.java`
`io.openliberty.microprofile.internal_fat/fat/src/io/openliberty/microprofile/internal/test/suite/ConfiguredJAXRSCDITest.java`
`io.openliberty.microprofile41.internal_fat/fat/src/io/openliberty/microprofile41/internal/test/suite/BasicHealthTest.java`

A single new MP 5.0 specific test has been added to verify compatibility with EE9 features and incompatibility with EE8 and lower
`io.openliberty.microprofile5.internal_fat/fat/src/io/openliberty/microprofile5/internal/test/suite/MP5CompatibleTest.java`

* 

### Test strategy

* What functionality is new or modified by this feature?
  * This is just an umbrella feature, it does not add any functionality of it's own
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
  * Only some basic feature compatibility testing has been added on top of repeating the existing tests.
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)
  * None

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

**5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.**

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by ayoho** [comment]
Coverage in line with the rest of MP. LGTM 👍
