### ISSUE TITLE
Throughput performance degradation in eclipselink due to Thread.getStackTrace calls

### ISSUE THREAD

**Issue by dettmoney** [OpenLiberty/open-liberty#19087]
Describe the bug
I have a simple REST/JPA application running on open liberty that performs jpa queries. A change to the org.eclipse.persistence.internal.helper.ConcurrencyManager class is causing a 75% throughput performance degradation for that particular application (~26k req/sec down to ~6k req/sec). See eclipselink issue: https://github.com/eclipse-ee4j/eclipselink/issues/1343 for more details.

Steps to Reproduce
Take any simple jpa application that uses the jpa-2.2 feature and compare throughput application between 21.0.0.7 and 21.0.0.11

Expected behavior
No throughput degradation between liberty releases.

Diagnostic information:
OpenLiberty Version: 21.0.0.8, 21.0.0.9, 21.0.0.10, 21.0.0.11
Affected feature(s): jpa-2.2
Java Version:
server.xml: <feature>jpa-2.2</feature>
Additional context

**Comment by jhanders34** [comment]
#regression

**Comment by dettmoney** [comment]
@dazey3 The fix was merged into the master branch of eclipselink. Hopefully 3.0 and 2.7 are soon to follow, then we can decide next steps.

**Comment by dettmoney** [comment]
Closing this as the fix has been merged

**Comment by mbroz2** [comment]
@dettmoney please update the description of this release bug so that it follows/conforms to the Bug report template
