### ISSUE TITLE
MP Open API 3.0 - Feature Test Summary

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#19083]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

MP Open API 3.0 is just a Jakarta EE 9 transformation of MP Open API 2.0. There is no new function other than basing on Jakarta EE 9. Testing is done by repeating existing buckets and adding in the official new TCK.

### List of FAT projects affected

We intend to repeat the following FAT buckets to cover MP Open API 3.0;
* com.ibm.ws.microprofile.openapi_fat
  * https://github.com/OpenLiberty/open-liberty/pull/19347
* io.openliberty.microprofile.openapi.2.0.internal_fat
  * https://github.com/OpenLiberty/open-liberty/pull/19365

The following bucket is new and already passes;
* io.openliberty.microprofile.openapi.3.0.internal_fat_tck

### Test strategy

* What functionality is new or modified by this feature?
  * No significantly new function other than being based on Jakarta EE 9
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
  * N/A
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)
  * None

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

**2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths**

**Currently we only have the TCK running. While we believe that is good enough for release, we are still working to get the other two FAT buckets to be correctly repeated against the new feature.
https://github.com/OpenLiberty/open-liberty/pull/19137 (Now https://github.com/OpenLiberty/open-liberty/pull/19347)**

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by ayoho** [comment]
Coverage sounds in line with all other features, so I think this looks good 👍
