### ISSUE TITLE
Keep track of changes to metatype between Servlet 5.0 and Servlet 6.0

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#19119]
1) https://github.com/OpenLiberty/open-liberty/issues/16053
2) https://github.com/OpenLiberty/open-liberty/issues/20419

**Comment by volosied** [comment]
I've updated the servlet 5.0 EPIC to list the defaults which changed in servlet-5.0:
https://github.com/OpenLiberty/open-liberty/issues/11819#issue-602872991

**Comment by pmd1nh** [comment]
Servlet 6.0 metatype: 
`skipEncodedCharVerification` default is false

Remove beta flag upon GA in https://github.com/openliberty/open-liberty/issues/24165

**Comment by pnicolucci** [comment]
make sure we have information in: https://github.com/OpenLiberty/docs/issues/5832

**Comment by pnicolucci** [comment]
Closing this as the docs reflect all the information here. No further changes to the meta type are expected.
