### ISSUE TITLE
Update jwtSso-1.0 feature to work with Jakarta EE 9 and MP 5.0

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/open-liberty#19150]
jwtSso-1.0 feature depends on MP and Jakarta APIs.  As such it will not work until it is updated to work with EE9 and MP 5.0 APIs.

**Comment by teddyjtorres** [comment]
Fixes https://github.com/OpenLiberty/open-liberty/issues/18952

**Comment by tevans78** [comment]
Reopening story until it has FAT approval
