### ISSUE TITLE
Microprofile does not provide app name/context root in /metrics, /health, ... endpoints

### ISSUE THREAD

**Issue by dbnex14** [OpenLiberty/open-liberty#19213]
**Describe the bug**  
If I have 10 applications running on same server (Liberty).  As it looks, Microprofile/liberty do not provide a way to distinguish btw apps hosted by server in the /metrics urls.  **How do I show /metrics and /health point by the application distinguishing the end points by app?**

**Steps to Reproduce**  
Annotate a method with any of the Metrics annotation.  For example, here is @Counted Microprofile annotation:
`@Counted(name="blah", displayName="blah blah", description="blah blah blah")`

**Expected behavior**  
Instead of this endpoint showing metrics for all 10 apps
`https://myserver/metrics`

I would like to have app context root in the endpoint so I can distinguish btw these 10 apps like:

```
https://myserver/app1/metrics
https://myserver/app2/metrics
https://myserver/app3/metrics
...
https://myserver/app10/metrics
```

**Diagnostic information:**  
 - OpenLiberty Version: 21.0.0.3 and 20.0.0.3
 - Affected feature(s) [e.g. mpHealth-3.0]
 - Java Version: OpenJDK 11 and Oracle JDK 11
 - server.xml configuration (WITHOUT sensitive information like passwords)
  Here are my enabled features in server.xml:
```
  <featureManager>
    <feature>jndi-1.0</feature>
    <feature>appSecurity-2.0</feature>
    <feature>localConnector-1.0</feature>
    <feature>monitor-1.0</feature>
    <feature>jsf-2.3</feature>
    <feature>jaxrs-2.1</feature>
    <feature>jsp-2.3</feature>
    <feature>jca-1.7</feature>
    <feature>jdbc-4.2</feature>
    <feature>jaxws-2.2</feature>
    <feature>ejbLite-3.2</feature>
    <feature>wmqJmsClient-2.0</feature>
    <feature>servlet-4.0</feature>
    <feature>microProfile-3.2</feature>
</featureManager>
```

**Comment by Channyboy** [comment]
Discussed at : https://github.com/eclipse/microprofile-metrics/issues/652
