### ISSUE TITLE
Feature Test Summary

### ISSUE THREAD

**Issue by jonhawkes** [OpenLiberty/open-liberty#19225]
## Test strategy

Currently SQL operations on transaction recovery logs, where the logs are stored in a database, are only retried if an SQLTransientException is encountered. Optionally, when a server.xml transaction attribute is configured, the new functionality allows more general SQLExceptions to be retried.

The following new tests have been added to the testsuites listed above and are run against each of DB2, Derby, Oracle, Postgresql and SQL Server.

testHADBNewBehaviourRuntimeFailover -  Test that non-transient (as well as transient) sqlcodes lead to an operation retry
when a server has the new enableLogRetries server.xml attribute set.
testHADBConnectFailover - Simulate an unexpected sqlcode on the first attempt to connect to the database. The server should fail to start and report errors.
testHADBNewBehaviourConnectFailover - Simulate an unexpected sqlcode on the first attempt to connect to the database. In this case the new enableLogRetries server.xml attribute is set so that the server will retry the connect and start successfully.
testHADBNewBehaviourMultiConnectFailover - Simulate an unexpected sqlcode on the first attempt to connect to the database. In this case the new enableLogRetries server.xml attribute is set so that the server will retry the connect and start successfully.
testDuplicationInRecoveryLogsRestart - Inject duplicate recovery log entries into a database log, crash the server and test
that transaction recovery succeeds. There is a possibility that database failure can lead to duplicate transaction log entries. This test confirms that such duplicates are handled with integrity on server restart.
testDuplicationInRecoveryLogsRuntime - Inject duplicate recovery log entries into a database log and test that such duplicates are handled with integrity at runtime.
testAbsenceOfDuplicatesInRecoveryLogs - This is the control test for testDuplicationInRecoveryLogsRestart to confirm the absence of duplicate recovery log records in the general case where a server crashes.
testHADBRecoverableFailureMultipleRetries - Test the setting of the "logRetryLimit" server.xml attribute. Set the parameter to 3 retries but simulate more than 3 (actually 5) failures in the test so that the server fails and stops.

## List of FAT projects affected

com.ibm.ws.transaction.DB2HADB_fat
com.ibm.ws.transaction.DerbyHADB_fat
com.ibm.ws.transaction.OracleHADB_fat
com.ibm.ws.transaction.PostgresqlHADB_fat
com.ibm.ws.transaction.SQLServerHADB_fat

There are no manual tests.

## Confidence Level

5

**Comment by ayoho** [comment]
I'm not seeing any of the projects listed under "List of FAT projects affected" as literal names of actual FAT buckets. I'm therefore assuming each of those entries mean the following FATs (correct me if I'm wrong):
- com.ibm.ws.transaction.DB2HADB_fat
    - com.ibm.ws.transaction.hadb_fat.db2.1
    - com.ibm.ws.transaction.hadb_fat.db2.2
- com.ibm.ws.transaction.DerbyHADB_fat
    - com.ibm.ws.transaction.hadb_fat.derby
    - com.ibm.ws.transaction.hadb_fat.derby.1
    - com.ibm.ws.transaction.hadb_fat.derby.2
- com.ibm.ws.transaction.OracleHADB_fat
    - com.ibm.ws.transaction.hadb_fat.oracle.1
    - com.ibm.ws.transaction.hadb_fat.oracle.2
- com.ibm.ws.transaction.PostgresqlHADB_fat
    - com.ibm.ws.transaction.hadb_fat.postgresql.1
    - com.ibm.ws.transaction.hadb_fat.postgresql.2
- com.ibm.ws.transaction.SQLServerHADB_fat
    - com.ibm.ws.transaction.hadb_fat.sqlserver.1
    - com.ibm.ws.transaction.hadb_fat.sqlserver.2

**Comment by ayoho** [comment]
@jonhawkes or @neilgsyoung - can either of you double check me on my previous comment?

**Comment by jonhawkes** [comment]
@ayoho you are correct.

**Comment by ayoho** [comment]
LGTM 👍
