### ISSUE TITLE
Issue 11911: FAT Approval Test Summary

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#19274]
## Test Strategy (Issue #11911)

Testing is following the same strategy as was performed for descriptor parsing -- by a combination of unit, FAT, and BVT testing.  Nearly all particular tests are through unit tests, since most of the parsing function is platform agnostic.  A subset of cases is tested through FATs.

## Confidence Level

My estimate of the confidence level is *4*:

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

## List of FAT Projects Affected

The following comprise the test components for deployment descriptors:

- Open Liberty
com.ibm.ws.javaee.ddmodel (unit tests)
com.ibm.ws.javaee.ddmodel.ws (unit tests)
**com.ibm.ws.javaee.ddmodel.fat** (FAT) (*relocated from Commercial Liberty*)
- Commercial Liberty
com.ibm.ws.javaee.ddmodel_bvt (BVT)
com.ibm.ws.javaee.ddmodel.ws_bvt (BVT)
**com.ibm.ws.javaee.ddmodel.fat** (FAT) (*relocated to Open Liberty)

Note the relocation of FAT tests from Commercial Liberty to Open Liberty

**Test Relocation**

This update moved and updated the FAT project "com.ibm.ws.javaee.ddmodel_fat" from Commercial Liberty to Open Liberty.  See https://github.com/OpenLiberty/open-liberty/pull/17781 and https://github.ibm.com/websphere/WS-CD-Open/pull/25339.

Open Liberty is the correct location for descriptor parsing tests, since the parsing function is present in Open Liberty.  Having the test function in Commercial Liberty considerably slows new development of descriptor parsing code.

## Test Overview

The feature provides two general updates:

1. More cases of partial headers are allowed for deployment descriptors.
2. Error and warning messages were made more informative.

The bulk of testing updates was to verify the correct parsing of deployment descriptors having partial headers.

See the section *Header Tests* for a listing of the typical cases which were tested.  Similar cases are tested for all of the descriptor types.

Most test updates were to unit tests.  However, for each descriptor type, a "minimal" case (a header having just one of the expected elements), a "partial" case (a header having one of the expected elements missing), and a "non-valid" case (a header which contains non-valid values) are included as FAT tests.

## General Testing Notes

- XML header tests were moved to a new "Header" unit test class:
  AppTestBase -> AppTest, AppHeaderTest  

- Test refactoring to provide greater reuse:
  AppTestBase -> AppTest, AppHeaderTest

- Existing tests which were slight variations (e.g., changing the provisioned version) were consolidated into loops.  This reduced the sprawl of unit test cases.

- Non-trivial XML contents were added.  Previously, many tests had empty XML content.  The parsing of XML contents is sensitive to the parse of the XML Header.

- Unit tests were added to "com.ibm.ws.javaee.ddmodel.ws".

- "Web" versions of EJB tests were changed to run using a repeat action which reconfigures the placement of the EJB resource.

**Unit Test Table**

* "Base" classes have no tests.
* Core test classes often show a decreased count due to consolidation or relocation of tests.  No actual test cases were removed.
* "Header" classes, as new test classes, have zero (0) initial test counts.
* The bulk of new tests are new "header" tests.  This matches the primary goal of the update, which was to adjust the processing of header information.
 
(Test counts were correct when this documentation was created, but will likely change over time.)

```
(Initial Count) Final Count) (Test Class)

             com.ibm.ws.javaee.ddmodel.DDTestBase

             com.ibm.ws.javaee.ddmodel.app.AppTestBase
 ( 0) (19)      com.ibm.ws.javaee.ddmodel.app.AppHeaderTest
 (33) ( 2)      com.ibm.ws.javaee.ddmodel.app.AppTest

             com.ibm.ws.javaee.ddmodel.appbnd.AppBndTestBase
 ( 0) (16)      com.ibm.ws.javaee.ddmodel.appbnd.AppBndHeaderTest
 ( 8) (11)      com.ibm.ws.javaee.ddmodel.appbnd.AppBndTest
             com.ibm.ws.javaee.ddmodel.appext.AppExtTestBase
 ( 0) (14)      com.ibm.ws.javaee.ddmodel.appext.AppExtHeaderTest
 ( 8) ( 8)       com.ibm.ws.javaee.ddmodel.appext.AppExtTest

             com.ibm.ws.javaee.ddmodel.bval.ValidationConfigTestBase
 (11) (21)     com.ibm.ws.javaee.ddmodel.bval.ValidationConfigTest

             com.ibm.ws.javaee.ddmodel.client.AppClientTestBase
 ( 0) (19)      com.ibm.ws.javaee.ddmodel.client.AppClientHeaderTest
 (24) ( 1)      com.ibm.ws.javaee.ddmodel.client.AppClientTest

             com.ibm.ws.javaee.ddmodel.common.CommonTestBase
 ( 3) ( 3)      com.ibm.ws.javaee.ddmodel.common.AdministeredObjectTest
 ( 3) ( 3)      com.ibm.ws.javaee.ddmodel.common.ConnectionFactoryTest
 ( 3) ( 3)      com.ibm.ws.javaee.ddmodel.common.JMSConnectionFactoryTest
 ( 3) ( 3)      com.ibm.ws.javaee.ddmodel.common.JMSDestinationTest
 ( 3) ( 3)      com.ibm.ws.javaee.ddmodel.common.MailSessionTest
 ( 3) ( 3)      com.ibm.ws.javaee.ddmodel.common.PersistenceContextRefTest
  
 ( 8) ( 0)     com.ibm.ws.javaee.ddmodel.commonbnd.RefBindingsGroupTest [relocated **]

             com.ibm.ws.javaee.ddmodel.ejb.EJBJarTestBase
 (12) (12)     com.ibm.ws.javaee.ddmodel.ejb.EJBJarAssemblyDescriptorTest
 ( 2) ( 2)     com.ibm.ws.javaee.ddmodel.ejb.EJBJarEnterpriseBeanTest
 ( 0) (14)     com.ibm.ws.javaee.ddmodel.ejb.EJBJarHeaderTest
 ( 7) ( 7)     com.ibm.ws.javaee.ddmodel.ejb.EJBJarInterceptorTest
 ( 8) ( 8)     com.ibm.ws.javaee.ddmodel.ejb.EJBJarMDBeanTest
 ( 1) ( 1)     com.ibm.ws.javaee.ddmodel.ejb.EJBJarRelationshipsTest
 (24) (24)     com.ibm.ws.javaee.ddmodel.ejb.EJBJarSessionBeanTest
 (15) (13)     com.ibm.ws.javaee.ddmodel.ejb.EJBJarTest

               com.ibm.ws.javaee.ddmodel.ejbbnd.EJBJarBndTestBase
 (17) (17)     com.ibm.ws.javaee.ddmodel.ejbbnd.EJBJarBndErrorTest
 ( 0) (16)     com.ibm.ws.javaee.ddmodel.ejbbnd.EJBJarBndHeaderTest
 ( 4) ( 4)     com.ibm.ws.javaee.ddmodel.ejbbnd.EJBJarBndInterfaceTest
 ( 6) ( 6)     com.ibm.ws.javaee.ddmodel.ejbbnd.EJBJarBndJCAAdapterTest
 ( 1) ( 1)     com.ibm.ws.javaee.ddmodel.ejbbnd.EJBJarBndListenerPortTest
 (12) (12)     com.ibm.ws.javaee.ddmodel.ejbbnd.EJBJarBndMDBeanTest
 (21) (21)     com.ibm.ws.javaee.ddmodel.ejbbnd.EJBJarBndSessionBeanTest
 (14) (14)     com.ibm.ws.javaee.ddmodel.ejbbnd.EJBJarBndTest
 ( 5) ( 0)     com.ibm.ws.javaee.ddmodel.ejbbnd.EJBJarBndTestWeb [as repeat]

             com.ibm.ws.javaee.ddmodel.ejbext.EJBJarExtTestBase
 ( 8) ( 8)     com.ibm.ws.javaee.ddmodel.ejbext.EJBJarExtBeanErrorTest
 (21) (21)     com.ibm.ws.javaee.ddmodel.ejbext.EJBJarExtBeanTest
 ( 0) (14)     com.ibm.ws.javaee.ddmodel.ejbext.EJBJarExtHeaderTest
 ( 3) ( 3)     com.ibm.ws.javaee.ddmodel.ejbext.EJBJarExtTest
 ( 3) ( 0)     com.ibm.ws.javaee.ddmodel.ejbext.EJBJarExtTestWeb

             com.ibm.ws.javaee.ddmodel.jsf.JSFAppTestBase
 ( 0) (21)    com.ibm.ws.javaee.ddmodel.jsf.JSFAppHeaderTest
 (18) (17)    com.ibm.ws.javaee.ddmodel.jsf.JSFAppTest

 (10) (14)    com.ibm.ws.javaee.ddmodel.managedbean.ManagedBeanBndTest

 ( 5) (16)    com.ibm.ws.javaee.ddmodel.permissions.PermissionsTest

             com.ibm.ws.javaee.ddmodel.web.WebAppTestBase
 ( 0) (12)     com.ibm.ws.javaee.ddmodel.web.WebAppHeaderTest
 (16) ( 9)     com.ibm.ws.javaee.ddmodel.web.WebAppTest
             com.ibm.ws.javaee.ddmodel.web.WebFragmentTestBase
 ( 0) (12)     com.ibm.ws.javaee.ddmodel.web.WebFragmentHeaderTest
 (12) ( 4)     com.ibm.ws.javaee.ddmodel.web.WebFragmentTest

             com.ibm.ws.javaee.ddmodel.webbnd.WebAppBndTestBase
 ( 0) (17)     com.ibm.ws.javaee.ddmodel.webbnd.WebAppBndHeaderTest
 ( 0) ( 8)     com.ibm.ws.javaee.ddmodel.webbnd.WebAppBndReferencesTest [** relocated]
 (20) ( 9)     com.ibm.ws.javaee.ddmodel.webbnd.WebAppBndTest

             com.ibm.ws.javaee.ddmodel.webext.WebAppExtTestBase
 ( 0) (15)     com.ibm.ws.javaee.ddmodel.webext.WebAppExtHeaderTest
 (29) (28)     com.ibm.ws.javaee.ddmodel.webext.WebAppExtTest
  
             com.ibm.ws.javaee.ddmodel.ws.DDTestBase_Webservices
               com.ibm.ws.javaee.ddmodel.ws.WebservicesTestBase
 ( 0) ( 1)     com.ibm.ws.javaee.ddmodel.ws.WebserviceTest
 ( 0) (20)     com.ibm.ws.javaee.ddmodel.ws.WebservicesHeaderTest
```

**Header Tests**

"Header" tests enumerate the primary cases of descriptors having incomplete or incorrect header information.  For example, `com.ibm.ws.javaee.ddmodel.web.WebAppHeaderTest`.  Other header tests have a similar collection of cases tested.

Tests which remove one of the usual header elements:
```
testEE6Web30NoSchema
testEE6Web30NoSchemaInstance
testEE6Web30NoSchemaLocation
testEE6Web30NoXSI
testEE6Web30NoVersion
testEE6Web30NoID
```

Tests which contain only one of the usual header elements:
```
testWebVersionOnly
testWebSchemaOnly
```

Error tests which contain only one of the usual header elements:
```
testVersionOnlyUnknown
testVersionOnlyUnprovisioned
testSchemaOnlyUnknown
testSchemaOnlyUnprovisioned
```

** FAT Table **

- Project "open-liberty/dev/com.ibm.ws.javaee.ddmodel_fat"
- Package "com.ibm.ws.javaee.ddmodel.suite"

FAT tests were updated for issue #11911 by the addition of four test classes which replicate "full" header tests with "minimal" and with "partial" headers:
```
  DDValidTests

  DDValidAppTests
    (MH) DDValidAppMinimalHeaderTests
    (PH) DDValidAppPartialHeaderTests

  DDValidModTests
    (MH) DDValidModMinimalHeaderTests.java
    (PH) DDValidModPartialHeaderTests.java
```
"Non-valid" tests are unchanged.  These test matching of configuration based bindings and extensions data with parsed descriptor data.
```
DDNonValidTests
  testUnnamedWebBndModuleName
  testDupeWebBndModuleName
  testUnnamedWebExtModuleName
  testDupeWebExtModuleName
  testUnnamedEJBBndModuleName
  testDupeEJBBndModuleName
  testUnnamedEJBExtModuleName
  testDupeEJBExtModuleName
```

"Application" tests are for applications packaged within an Enterprise Application Archive (EAR) file.

"Valid application" tests are for two test case categories:

1. "NoBindings" cases test the handling of configuration based bindings and extensions when no application based bindings or extensions data is present:
```
DDValidAppTests
  testEJBBindingsNoBindings_Application
  testEJBExtensionNoBindings_Application
  testWebBindingsNoBindings_Application
  testWebExtensionNoBindings_Application
  testWebserviceBindingsNoBindings_Application
```

2. All other cases test basic descriptor parsing.  For all other cases, a "full" header case, a "partial" header case, and a "minimal" header case are tested, with the test cases split across three test classes:
```
DDValidAppTests
  (MH) DDValidAppMinimalHeaderTests
  (PH) DDValidAppPartialHeaderTests

  testApplicationExtension_Application
  testAutoInstall_Application
  testBindingsConfig_Application
  testConfig_Application
  testEJBBindings_Application
  testEJBExtension_Application
  testManagedBeanBindings_Application
  testSecurityRoleOverrides_Application
  testWebBindings_Application
  testWebExtension_Application
  testWebserviceBindings_Application
```

"Module" tests are for applications packaged using module archive files (WAR and JAR files).

"Valid module" tests are for two test case categories:

1. "NoBindings" cases test the handling of configuration based bindings and extensions when no application based bindings or extensions data is present:
```
DDValidModTests
  testEJBBindingsNoBindings_Module
  testEJBExtensionNoBindings_Module
  testWebBindingsNoBindings_Module
  testWebExtensionNoBindings_Module
```

2. All other cases test basic descriptor parsing.  For all other cases, a "full" header case, a "partial" header case, and a "minimal" header case are tested, with the test cases split across three test classes:
```
DDValidModTests
  (MH) DDValidModMinimalHeaderTests.java
  (PH) DDValidModPartialHeaderTests.java

  testAutoInstall_Module
  testBindingsConfig_Module
  testEJBBindings_Module
  testEJBExtension_Module
  testManagedBeanBindings_Module
  testWebBindings_Module
  testWebExtension_Module
  testApplicationExtensionFromWebApp_Module
  testSecurityRoleOverridesFromWebApp_Module
```

**Comment by dave-waddling** [comment]
Hi @tbitonti, 

This Feature Test Summary looks good to me. PR [25339](https://github.ibm.com/websphere/WS-CD-Open/pull/25339) has only recently been merged and so an approval will be blocked until those testing changes have gone through the next SOE. If all testing passes then I should be able to grant the FAT Focal approval next Monday. 

Also please note that I added a comment to #11911 regarding correctly tagging features to ensure the FAT Focal reviewers are aware of the feature and when it is ready for review.
