### ISSUE TITLE
Duplicate message key in com.ibm.ws.ui.tool.explore

### ISSUE THREAD

**Issue by pnickoll** [OpenLiberty/open-liberty#19316]
Duplicate message key in /com.ibm.ws.ui.tool.explore/resources/WEB-CONTENT/jsExplore/nls/zh/explorerMessages.js

Line 312 : NO_APPS_RUNNING : "No Apps Running",
Line 452 : NO_APPS_RUNNING : "{0}: no apps running", // serverName[]

According to @k8vance88 :

You're right there are 2 of them.  It appears the code is favoring:
Line 452 : NO_APPS_RUNNING : "{0}: no apps running", // serverName[]

However, I have searched the code and cannot find anywhere that we use that message

**Comment by XiaojuanChen** [comment]
Another duplicate key in this file:
Line532:  SAVE: "Save",
Line554: SAVE: "Save",

Could you help to fix together? Thanks!

**Comment by k8vance88** [comment]
We should be able to fix these issues on our side. Added it to our backlog.

**Comment by mbroz2** [comment]
@k8vance88 @lavenal @pnickoll is this actually a `release bug`?  It's unclear to me based on the conversation.  
If it is, please update the description of this `relesae bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)

**Comment by lavenal** [comment]
I don't see it as a release bug.

**Comment by mbroz2** [comment]
If it is not a `release bug`, then we need to get the tag removed quickly. 
If it is a release bug, then update the description using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
