### ISSUE TITLE
Policy attachments file: policy-attachments-server.xml is not processed 

### ISSUE THREAD

**Issue by sawadood** [OpenLiberty/open-liberty#19334]
The policy attachments file: policy-attachments-server.xml packaged under META-INF of an EJB module of a Web services provider is not processed.

**Comment by mbroz2** [comment]
@sawadood plz update the first comment to follow the [Bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
