### ISSUE TITLE
19368 Feature Test Summary

### ISSUE THREAD

**Issue by dazavala** [OpenLiberty/open-liberty#19357]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

> Epic [19368](https://github.com/OpenLiberty/open-liberty/issues/19368) delivers two enhancements to open-liberty feature `bells-1.0`: 
> - BELL SPI visibility 
> - BELL properties configuration and injection
>
> Comprehensive functional tests for both enhancements will deliver to FAT projects within the Liberty FAT framework, only.
>

### List of FAT projects affected (OpenLiberty/open-liberty)

> - com.ibm.ws.classloading.bells_fat
> 
>   New tests: **BellSpiVisibilityTest.java** and **BellPropertiesFat.java**
>
> - io.openliberty.jcache.internal_fat.hazelcast 
>    io.openliberty.jcache.internal_fat.infinispan
>
>   Tests provided for Distributed Auth Cache feature. 
>

### Test strategy

**What functionality is new or modified by this feature**?

> _For BELL SPI visibility:_
> - A new BELL attribute `spiVisiblity` enables BELL services to extend/implement/use SPI interfaces exported by Liberty features. The attribute is `false` by default and applies to all services provided by the BELL.
> - The class loading gateway and kernel infrastructure use a new `All SPI` OSGi region to support SPI package visibility.
> - At the component level the class loading service provides an internal SPI interface and method, `com.ibm.ws.library.spi.SpiLibrary::getSpiClassLoader()`, for use by features to get an instance of a shared library class loader that can see (load) SPI packages. The BELLs feature and the Distributed Auth Caches feature use the SpiLibrary interface.
> - In BELL use-cases a shared library will see SPI packages only when referenced by a BELL that is configured with `spiVisibility="true"`. Applications cannot see SPI packages when referencing a shared library that is also referenced by a BELL w/ SPI visibility. 
> - The server does not support SPI visibility for BELLs that reference the Liberty global library. 
>
> _For BELL properties c & i:_
> - A new BELL element `<Properties/>` will enable users to configure `name="value"` attributes. BELL properties are type `String` and apply to all services provided by BELL. 
> - When configured, BELL properties will inject, at runtime, as an unmodifiable `Map(<String>,<String>)` into to all BELL services either named in the BELL configuration or discovered in the BELL library. 
> - To enable property injection a user must define a single-arg constructor or an updateBell() method -- both having a single parameter of type `Map<String,String>` -- in their BELL service implementation classes. The server will issue a warning when properties cannot be injected into a BELL service.  The updateBell() method is for non-destructive BELL updates, which are not yet supported by the bells-1.0 feature.
>
> _For Distribute Auth Caches:_
> - In DAC use-cases a shared library class loader will see SPI packages only when the library is referenced by attribute `JCacheLibraryRef` within a `<cacheProvider/>` configuration. The user cannot disable SPI visibility for the referenced library as it is required by the DAC feature runtime.

**What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)**

> _Component-level scenarios that verify SPI packages are visible to an SPI library class loader:_
> - None. The new `SPI Library` class loading support is verified in use-case scenarios in the BELL and Distributed Auth Cache FATs.
>  
> _The main working scenario for BELL SPI visibility:_
> - Verify feature SPI interfaces link to (load for) BELL services impl classes when `spiVisibility` is set to `"true"`  
>
> _Negative variations of the main scenario:_
> -  Verify feature SPI interfaces **do not** link to (load for) BELL service impl classes when `spiVisibility` is `"false"`. 
> - Verify the server defaults `spiVisibility` to `false` when not set.
> - Verify feature SPI packages **do not** load for applications (resources) that reference a library that is also referenced by a BELL with SPI visibility.
> - Verify the server emits an error message and disables SPI visibility for BELLs that reference the Liberty `global` shared library. 
>
> _The main working scenarios for BELL properties c & i:_
> - Verify the exact set of configured properties inject into server implementation instances of services named in the BELL configuration or disovered in the referenced library.
> - Verify Liberty variables resolve in BELL property values.
> - Verify the server accepts duplicate property names and uses the value of the last duplicated property name.
>
> _Negative variations of the main scenario:_
> - Verify the server **warns** whenever it cannot inject (propagate) BELL service properties to a target service because the service implementation class lacks the necessary injection methods.
> - Verify the server fails with a configuration parse error for malformed properties.
>

**What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)**

> None
>

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

> 5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

> The only additional testing I would consider is component level verification of the SPI library classloader to verify fringe cases or to quickly verify changes to the class loader implementation. For instance, are _all_ feature SPI packages made visible at the class loading gateway? Does SPI visibility work with API type visibilty for a library?  Such a test would offer more confidence that the kernel's OSGi region support for SPI visibility is working as designed.  But that said, the Liberty FAT suite provides indirect coverage of fringe cases.  For instance, the OSGi applications FATs are extremely sensitive to changes in how feature SPI is collected and provisioned by the kernel. Furthermore, the DAC FAT verifies all SPI packages exported by the DAC feature are made visible to the SPI library instance through the gateway, and that default API-type settings are not otherwise exposing the same packages to applications.

**Comment by ayoho** [comment]
Coverage looks good to me 👍
