### ISSUE TITLE
Metric suitable for alerting for up/down in OpenLiberty 21.0.0.11 with mpMetrics-2.3

### ISSUE THREAD

**Issue by corporate-gadfly** [OpenLiberty/open-liberty#19371]
I was reading the [metric reference list](https://openliberty.io/docs/21.0.0.11/metrics-list.html) and was wondering if you had any suggestions on which metric to use for up/down graphing **and** alerting.

**Comment by corporate-gadfly** [comment]
Closing, as I can use the built-in prometheus time series for `up{job="<job-name>", instance="<instance-id>"}`: 1 if the instance is healthy, i.e. reachable, or 0 if the scrape failed.

**Comment by donbourne** [comment]
@corporate-gadfly , thanks for the suggestion on this.  I'm wondering if we should work with MicroProfile to get all health checks from mpHealth to automatically have a corresponding metrics in mpMetrics.
