### ISSUE TITLE
Cookie Prefix on this cookie

### ISSUE THREAD

**Issue by pahameel** [OpenLiberty/open-liberty#19385]
Hello,
We just finished install and configuring the liberty, and we are running the vulnerability test and found this

<html><body>

Set-Cookie | There is no Cookie Prefix on this cookie.
-- | --

</body>
</html>

https://scotthelme.co.uk/tough-cookies/

How to fix this/ or configure in server.xml file?
This is the value i have updated in server.xml file

\<httpSession allowOverflow="false" maxInMemorySessionCount="100" alwaysEncodeUrl="true" cookieSameSite="Strict" cookieSecure="true"  /\>

**Comment by zhang-ca** [comment]
You can simply add cookie prefix to the default cookie name as cookieName="__Secure-JSESSIONID" in `<httpSession>`

**Comment by pahameel** [comment]
Thanks @zhang-ca for providing the solution. You dont know i have spent 2 days with IBM and researching myself on this.

Thanks again.
