### ISSUE TITLE
preferred compression algorithm leads to warning

### ISSUE THREAD

**Issue by bmarwell** [OpenLiberty/open-liberty#19414]
**Describe the bug**  

From the [tutorial about compression](https://openliberty.io/blog/2020/04/22/http-response-compression.html), I configured this snippet onm OL 21.0.0.11:

```xml
    <compression serverPreferredAlgorithm="deflate|gzip|x-gzip|zlib|identity|none">
```

Now I see this warning:

```log
[WARNING ] CWWKT0033W: An attempt was made to configure deflate|gzip|x-gzip|zlib|identity|none as the server-preferred algorithm. The supported values are gzip, x-gzip, zlib, deflate, identity, and none. The default configuration none is used instead.
```

**Steps to Reproduce**  

Follow linked tutorial

**Expected behavior**  

An INFO message that the compression algorithms have been configured.

**Diagnostic information:**  
 - OpenLiberty Version: 21.0.0.11
 - Affected feature(s) [e.g. mpHealth-3.0]
 - Java Version: [semeru 17 pre-release 0.29.1-m1](https://github.com/ibmruntimes/semeru17-binaries/releases/tag/jdk-17.0.1%2B12_openj9-0.29.1-m1)
 - server.xml configuration (WITHOUT sensitive information like passwords)
   see above
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`
   n/a

**Additional context**  

n/a

**Comment by NottyCode** [comment]
@bmarwell the tutorial is trying to indicate that you should specify one of those values, not use that value literally. So I think you should do something like this instead:

```
<compression serverPreferredAlgorithm="gzip">
```

**Comment by bmarwell** [comment]
Thanks. I would never have guessed that from reading the guide (even now!). It looks very much like an example.

**Comment by NottyCode** [comment]
@bmarwell yes I would not be comfortable saying user error to this one. I'll see if we can improve that blog post, although it is old it still comes up.
