### ISSUE TITLE
Update EclipseLink to support Java 18

### ISSUE THREAD

**Issue by gjwatts** [OpenLiberty/open-liberty#19423]
Running through the initial testing of Java 18 and several FATs are failing with this error message (for various different classes):
```
[11/15/21, 22:31:16:724 PST] 00000022 eclipselink.ps.metadata    
CWWKD0292E: The <various class names> class was compiled with an unsupported JDK. Report this error to the EclipseLink open source project.
```
I assume an update of EclipseLink is needed to correct.  If this is not the case, please let me know.

**Comment by jgrassel** [comment]
Eclipselink is running with ASM 9.2, which supports JDK 18.  JPA FATs with Java 18 runs have all been clean.
