### ISSUE TITLE
Improve Access Log %D directive documentation

### ISSUE THREAD

**Issue by mrsaldana** [OpenLiberty/open-liberty#19482]
The current wording used to describe the functionality of the %D directive is confusingly worded. Setting an example value would help clear out doubts as to what the resulting value should be expected to be.

**Comment by JDUNNIN** [comment]
Same for `%{R}W`.

**Comment by mrsaldana** [comment]
https://openliberty.io/docs/21.0.0.4/access-logging.html has already been updated with a format example that includes both `%D `and `%{R}W` . These have corresponding values indicating that the values are in microseconds and what they measure:

> The elapsed time of the request in microseconds, end-to-end, including client and network time
> 
> The elapsed time in microseconds until the first bytes of the response are sent. This value is often a close approximation of application response time.
