### ISSUE TITLE
Duplicate Files Defining Same Component (Property.jsx and property.jsx)

### ISSUE THREAD

**Issue by clara0** [OpenLiberty/open-liberty#19487]
**Describe the bug**  
When cloning the repo, a warning (see below) appears. Both `Property.jsx` and `property.jsx` define the same component, meaning one of them is redundant.

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'dev/com.ibm.ws.openapi.ui/swagger-ui/src/core/components/Property.jsx'
  'dev/com.ibm.ws.openapi.ui/swagger-ui/src/core/components/property.jsx''

```
**Steps to Reproduce**  
Every time you clone the repo, you see above warning.

**Expected behavior**  
No warning when the repo is cloned, and no duplicate files in project.

**Diagnostic information:**  
 - OpenLiberty Version: current
 - Affected feature(s): UI
 - Java Version: N/A
 - server.xml configuration: N/A

**Comment by Azquelt** [comment]
Thanks, I missed this when I updated the version of swagger-ui in #19320
