### ISSUE TITLE
Unpredicable logging when setting trace file name to messages.log

### ISSUE THREAD

**Issue by nadiramra** [OpenLiberty/open-liberty#19559]
Logging issue. I am running 21.0.0.12, and in my bootstrap.properties file, I have:

```
com.ibm.ws.logging.console.log.level=OFF                             
com.ibm.ws.logging.copy.system.streams=false                                                     
com.ibm.ws.logging.message.file.name=messages.log                    
com.ibm.ws.logging.message.format=TBASIC                              
com.ibm.ws.logging.trace.file.name=messages.log                         
com.ibm.ws.logging.trace.format=TBASIC                               
com.ibm.ws.logging.trace.specification=*=info:com.ibm.ws.*=all 
```

In my server.xml file, I have:
`<logging suppressSensitiveTrace="true"/>  `

Something weird happens when trace file name is set to messages.log.  I started with a clean logs directory, it uses messages.log for tracing, but seems to also create messages_21.12.06_09.32.14.0.log and use for non-tracing.

**Expected behavior**  
The expectation is that logging/tracing messages would be in messages.log.  That is not what is happening.  Liberty should recognize that messages file name and trace file name is one and the same and should optimize writing records to messages.log (or configured file name)

**Comment by pgunapal** [comment]
@nadiramra After further investigating this issue, this is working as designed. We do not support adding traces to the message.log file using basic logging format. You would have to use JSON logging and the `com.ibm.ws.logging.message.source` property to direct everything to one file. If you want to add the traces into a common place without using JSON format, you can set the trace file name to `stdout`, which would make it go to the console.log file. The drawback to that is that the console.log file is not rollable, hence the file might grow indefinitely.
