### ISSUE TITLE
CDI 2.0: Java Batch API bundle needs a version range on its import statement to support cdi-2.0

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#1960]
First discovered in RTC 247973 - https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemName/com.ibm.team.workitem.WorkItem/247973

`com.ibm.websphere.javaee.batch.1.0/bnd.bnd` has an optional import for `javax.enterprise.util` but does not specify a version. So at build time it defaults to version 1.1. It needs a range so that it can also accept version 2.0 at runtime;

`javax.enterprise.util; version="[1.1,3)";resolution:=optional`

**Comment by scottkurz** [comment]
@tevans78 , I'm not too familar with bndtools.   A naive question would be "should the build generate the range automatically?"  Not that I'm planning on investigating further now.   Curious if you have an opinion, but I'm sure it's a whole other issue.

**Comment by tevans78** [comment]
Did I say bndtools? That is the eclipse plugin part. This is just "bnd" and I don't know if it should or should not... @Emily-Jiang might know better
