### ISSUE TITLE
BETA BLOG - MP GraphQL 2.0

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#19636]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty. For this post to be included in the beta issue please make sure that this is completed by the end of Friday following the GM (Wednesday). 

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to? #19529 
    
   Human-readable name (eg WebSockets feature): MicroProfile GraphQL 2.0
   
   Short feature name (eg websockets-1.0): `mpGraphQL-2.0`

2. Who is the target persona? Who do you expect to use the update? **application developer**

3. Write a paragraph to summarises the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.

   - What was the problem before and how does your update make their life better? (Why should they care?)
   
   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.
   
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?

MicroProfile GraphQL 2.0 incorporates Jakarta EE 9.1 dependencies.  This allows developers to continue using the same functionality provided by MP GraphQL 1.0 but with the updated Jakarta components such as CDI 3.0, Jakarta REST 3.0, JSON-B 2.0, etc. Functionally, version 2.0 behaves the same as 1.0 because it uses the same version of the underlying implementation ([SmallRye GraphQL](https://github.com/smallrye/smallrye-graphql)).  If you'd like to learn more about MP GraphQL, see our previous [blog post about MP GraphQL 1.0](https://openliberty.io/blog/2020/06/10/microprofile-graphql-open-liberty.html) and our [blog post on how to use the GraphiQL UI and third-party Client APIs](https://openliberty.io/blog/2020/08/28/graphql-apis-open-liberty-20009.html).

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by WhiteCat22** [comment]
epic
https://github.com/OpenLiberty/open-liberty/issues/19529
