### ISSUE TITLE
Logging bootstrap property com.ibm.ws.logging.hideMessage causees unexpected behavior

### ISSUE THREAD

**Issue by nadiramra** [OpenLiberty/open-liberty#19685]
in my bootstrap.properties file using Liberty 21.0.0.12, I have

com.ibm.ws.logging.console.log.level=OFF                      
com.ibm.ws.logging.copy.system.streams=false                  
com.ibm.ws.logging.hideMessage=                               
com.ibm.ws.logging.log.directory=${server.output.dir}/logs    
com.ibm.ws.logging.max.file.size=25                           
com.ibm.ws.logging.max.files=1                                
com.ibm.ws.logging.message.file.name=messages.log             
com.ibm.ws.logging.message.format=SIMPLE                      
com.ibm.ws.logging.trace.file.name=trace.log                  
com.ibm.ws.logging.trace.format=ENHANCED                      
com.ibm.ws.logging.trace.specification=*\=info                

because the hideMessage property does not have a value, liberty seems to not write anything to messages.log except stdout/stderr messages, and uses the trace.log to write out what was expected in messages.log.

When I remove the property or set the property with a value, everything works as expected.

**Comment by donbourne** [comment]
Thanks for reporting that @nadiramra .  That does indeed sound unexpected.

**Comment by Channyboy** [comment]
See https://github.com/OpenLiberty/open-liberty/issues/19688
