### ISSUE TITLE
Record objects failing silently with Jakarta EE 9.1

### ISSUE THREAD

**Issue by rdean** [OpenLiberty/open-liberty#19698]
I'm experimenting with Java 17 and JakartaEE 9.1 restful services and running into issues with `Record` objects.

I generated a project with a simple greeting service that returns a `Record` type:

```java
    @GET
    @Path("{name}")
    @Produces(MediaType.APPLICATION_JSON)
    public GreetingResponse greeting(@PathParam("name") String name) throws WebApplicationException {
      return new GreetingResponse("Hello, " + name); 
    }
```
where `GreetingResponse` is 

```java
public record GreetingResponse(String greeting) { }
```

When accessing the resource
```sh
curl http://localhost:9080/hello-world/api/v1/greeting/Robert
```
the response is 
```javascript
{}
```

No error message is produced in the logs.

Yasson was [recently updated](https://github.com/eclipse-ee4j/yasson/releases/tag/2.0.3) to support `Record` types.  I flirted with the jsonbContainer-2.0 feature but the documentation is unclear on how to configure in server.xml or where to put the jar / whether or not a `<bell>` is required.

**Comment by WhiteCat22** [comment]
Hi @rdean, thank's for bringing this to our attention. I am out of the office today, but I'll investigate on Monday.

**Comment by WhiteCat22** [comment]
Hi @rdean 

I think I have this reproduced, or close. What is the HTTP status code of your curl command? When I try to hit my endpoint I'm getting a `404`.

My hunch is that our JAX-RS implementation (Resteasy 4.7.2.Final) doesn't yet support record types. At first I thought that the issue was probably that we don't ship a MessageBodyWriter that supports record types. But, with no errors in the logs and getting a 404, I think the error is even earlier than message serialization. Rather, Resteasy isn't finding the endpoint at all.

Here is the basic application I'm using to reproduce with Java 17 temurin
```
@Path("/")
public class PrototypeResource {

    @GET
    @Path("echo")
    public GreetingResponse hello() {
        return new GreetingResponse("Hello World!");
    }

    public record GreetingResponse(String greeting) { }

}
```

```
@ApplicationPath("/")
public class PrototypeApplication extends Application {}
```
I'm deploying the application via the `dropins` directory and using the `restfulWS-3.0` feature in my `server.xml`

**Comment by rdean** [comment]
I got a `200 OK` response with an empty JSON block for payload.
```
projects/liberty/jee-example is 📦 0.0.1-SNAPSHOT via ☕ v17.0.1 
❯ curl http://localhost:9080/jee9-example/api/v1/salutation/Robert -v
*   Trying 127.0.0.1:9080...
* Connected to localhost (127.0.0.1) port 9080 (#0)
> GET /jee9-example/api/v1/salutation/Robert HTTP/1.1
> Host: localhost:9080
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Language: en-US
< Content-Length: 2
< Date: Mon, 03 Jan 2022 22:51:57 GMT
< 
* Connection #0 to host localhost left intact
{}%                                                                                                                                           
```

**Comment by rdean** [comment]
I added my example to a personal repo on GitHub: https://github.com/rdean/jee-example

**Comment by WhiteCat22** [comment]
Thanks!

**Comment by WhiteCat22** [comment]
@rdean I was able to reproduce the issue with your provided sample, thank you!

When I enabled Liberty trace I found what I expected:
```
ss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl 1 getMessageBodyWriter MessageBodyWriter: io.openliberty.restfulWS30.jsonb20provider.JsonBProvider
```

What this means is that Liberty is selecting our built in `JsonBProvider` (MessageBodyWriter) to serialize the response object.

I did some searching and found this blog post:
https://rmannibucau.metawerx.net/java-14-record-class-type-and-json-b.html

Basically, JSONB doesn't currently support record types. But that article is from 2019 and references Johnzon, we use Yasson as our JSONB implementation in Open Liberty.

So I found this article:
https://dev.to/cchacin/java-14-records-with-jakartaee-json-b-160n

It's a little bit newer, but references Yasson. Ultimately it says the same thing. Records will likely be supported in future versions of JSONB.

Where does that leave us now? Currently, to serialize record types you'll have to provide your own MessageBodyWriter that supports serialization of java record types to json.

It looks like Jackson 2.12.3 can do this:
https://dev.to/brunooliveira/practical-java-16-using-jackson-to-serialize-records-4og4

**Comment by WhiteCat22** [comment]
Here's a blog on how to bring your own Jackson with your application: https://openliberty.io/blog/2020/11/11/byo-jackson.html

**Comment by inad9300** [comment]
Now that Java 17 support is officially claimed, I think it is important to get this fixed (or at least to more visibly communicate about this exception).

**Comment by WhiteCat22** [comment]
I took a look and we currently depend on Yasson 2.0.1 for EE9 and 3.0.0. for EE10. 

Record support was added to Yasson [2.0.3](https://github.com/eclipse-ee4j/yasson/releases/tag/2.0.3).

So, this works with EE10, but we need to update EE9 to 2.0.3.

**Comment by bmarwell** [comment]
Hi @WhiteCat22!
Actually, 2.0.3 is not enough!

2.0.3 does not support :

```java
    final JsonbConfig jsonbConfig =
        new JsonbConfig()
            .withPropertyVisibilityStrategy(new PrivateVisibilityStrategy())
            .withPropertyNamingStrategy(PropertyNamingStrategy.LOWER_CASE_WITH_UNDERSCORES);
```

When using Jsonb, it will still try to look for a property "firstName" instead of "first_name".
Updating to Yasson 3.x.x fixes this behaviour.

**Comment by jhanders34** [comment]
We upgraded to 2.0.4.  Does that resolve the issue?

**Comment by bmarwell** [comment]
Nope, 2.0.4 still has the wrong behaviour. Just updated my new IT:
https://github.com/bmarwell/jaxrs-test-showcase/pull/61

Jsonb is instantiated here: https://github.com/bmarwell/jaxrs-test-showcase/blob/70b783a1853c7c35fcf21ac56ebcd64d505cc174/app/web/rest-impl/src/main/java/io/github/jaxrstesting/web/rest/impl/data/DataInitializer.java

Works fine in the unit test:
https://github.com/bmarwell/jaxrs-test-showcase/blob/70b783a1853c7c35fcf21ac56ebcd64d505cc174/app/web/rest-impl/src/test/java/io/github/jaxrstesting/web/rest/impl/data/DataInitializerTest.java

Fails in the Open Liberty IT.

Fails in my unit test when I downgrade from 3.0.2 to 2.0.4.

To execute the test, use `mvn verify`. You can change the version in the pom.xml of the PR to see for yourself. Always reproducible.

Workaround: use the jsonbContainer + bells-Feature (untested):

```xml
<server>
  <featureManager>
    <feature>jsonbContainer-1.0</feature>
  </featureManager>

  <bell libraryRef="johnzon"/>

  <library id="johnzon">
    <fileset dir="${server.config.dir}/johnzon"includes="*.jar"/>
  </library>
</server>
```

**Comment by bmarwell** [comment]
I dug into this a little further. Neither yasson 3 can be used (different API, would need jsonbContainer-3.0), nor johnzon (Uses classifiers, which is not supported by Liberty).

However, adding some null checks revealed that this is in fact a problem in Yasson. Yasson seems to ignore the PropertyNamingStrategy in any version of 2.x / 3.x. Will open a bug over there.

// edit: https://github.com/eclipse-ee4j/yasson/issues/583

**Comment by bmarwell** [comment]
... here's the PR
https://github.com/eclipse-ee4j/yasson/pull/584
