### ISSUE TITLE
Runnable jar hangs after CTRL + C

### ISSUE THREAD

**Issue by jeroenagroeneveld** [OpenLiberty/open-liberty#19707]
**Describe the bug**  
A running runnable jar can supposedly be stopped with a signal from CTRL + C. Using this signal stops the server, but does not end the runnable jar ("hangs", i.e. does not return to the shell prompt). The JVM keeps running. Terminating the JVM returns to the prompt.
The last line to appear in the logs reads: CWWKE0036I: The server defaultServer stopped after 6,356 seconds.
The temporary extract folder is not cleaned.

Server version 20.0.0.12 shows the expected behaviour, but more recent versions such as 21.0.0.12 do not.
The issue can be overcome by using "cmd /c" instead of "cmd /k" in method stopServer() from dev/wlp.lib.extract/src/wlp/lib/extract/ShutdownHook.java

**Steps to Reproduce**  
1. Create a runnable jar, e.g. following https://openliberty.io/guides/getting-started.html#running-the-application-from-a-minimal-runnable-jar
2. Start the server from Windows command prompt, e.g. java -jar guide-getting-started.jar
3. Press CTRL + C
4. Wait indefinitely for process to end and return to the prompt

**Expected behavior**  
After CTRL + C firstly the server stops and then the runnable jar terminates as well.

**Diagnostic information:**  
 - OpenLiberty Version: 21.0.0.12 (I think this affects all 21.0.0.* versions, but this has not been tested)
 - Java Version: java 1.8.0_281, openjdk version "11" 2018-09-25
 - server.xml configuration unchanged from the getting-started guide

**Additional context**  
The runnable jar was started under Windows 10. The same behaviour was found with both the Windows Command Prompt and Git Bash.

**Comment by cbridgha** [comment]
@jeroenagroeneveld thanks for raising - we are investigating...

**Comment by hlhoots** [comment]
Merged a fix for this.  Closing for now.
