### ISSUE TITLE
Migrate Open Tracing FAT buckets to run against Open Telemetry

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#19752]
Since MP OpenTelemetry is a replacement for MP OpenTracing, we need to be reasonably confident that all the same use cases will work properly. The first step is to copy and convert the existing tests to use the new API.

There may be additional FAT tests required as well. A separate issue should be opened for that.

Part of https://github.com/OpenLiberty/open-liberty/issues/19172

**Comment by Azquelt** [comment]
I compared the `mpTelemetry` tests with those for `mpOpenTracing` and I found the following tests missing:
- Tracing all HTTP methods (GET/POST/HEAD etc.)
- Tracing a variety of HTTP response codes
- Tracing a request to a non-existent path within a JAX-RS app
- Async JAX-RS server using `@Suspended AsyncRequest`

As these are all JAX-RS related, I've added them to #23448
