### ISSUE TITLE
Update version of Kafka used for the Reactive Messaging tests

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#19762]
Our tests use the confluent platform docker images.

In some tests we're using 5.4.3 (kafka 2.4.3) and in other tests we're using 4.0.0 (kafka 1.0.0).

The correspondence between confluent plaform versions and kafka versions is listed on [this page][cp-kafka-versions].

When we update, we will probably have to re-do some of the work to enable authentication with the broker and deploy the necessary credentials and certificates as it's dependent on the structure of the older confluent platform docker images.

Kafka currently uses log4j v1 which is EOL since 2015, though they [don't list any known vulnerabilities][kafka-cves] unless the JMS appender is used.

[Work is currently underway][kafka-log4j2] for Kafka to move up to a supported version of log4j2, but this hasn't been completed yet.

[cp-kafka-versions]: https://docs.confluent.io/platform/current/installation/versions-interoperability.html#
[kafka-cves]: https://kafka.apache.org/cve-list
[kafka-log4j2]: https://issues.apache.org/jira/browse/KAFKA-9366

**Comment by tevans78** [comment]
Michal suggested that we would expect/recommend most users to move up to the latest version of Kafka ... so that is what we should test with. Don't worry too much about the older versions.

**Comment by Azquelt** [comment]
Kafka have [switched to reload4j](https://issues.apache.org/jira/browse/KAFKA-13660) (a maintained [fork of log4j 1.x](https://reload4j.qos.ch/)) as of 3.1.1 and 3.2.0 and plan to move to log4j2 in 4.0.0.
