### ISSUE TITLE
Callback is not serialized correctly

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty#1978]
When the callback is a ref, it doesn't serialize it correctly. Instead it treats it as a Map. Probably have to write its own serializer.

Tried to create a serializer like the SchemaSerializer, but it didn't work, probably because Callback extends Map. So look into Path/Paths (which is also Map).

**Comment by arturdzm** [comment]
Added custom CallbackSerializer to handle this scenario
