### ISSUE TITLE
OpenIdConnectClient not working with proxy settings given in jvm.options

### ISSUE THREAD

**Issue by dyapasrikanth** [OpenLiberty/open-liberty#19832]
**Describe the bug**  
OpenIdConnectClient not taking proxy settings given in jvm.options, because of that I am always getting connection timeout. How can I fix it?

**Steps to Reproduce**  
Mentioned proxy settings in `jvm.options` are not being used while connecting to OP

`jvm.options`
```
-Dhttp.proxyHost=localhost
-Dhttp.proxyPort=3128
```

**Expected behavior**  
proxy settings mentioned at the` jvm.options` should be considered or need to provide a way to specify the http proxy for openIdConnectClient feature

**Diagnostic information:**  
 - OpenLiberty Version: [21.0.0.12]
 - Affected feature(s) [openidConnectClient]
 - Java Version: [openjdk version "11.0.2" 2019-01-15]

`server.xml`

```
<openidConnectClient id="auth-handler"
                         clientId="${openid.provider.clientId}"
                         clientSecret="${openid.provider.clientSecret}"
                         authFilterRef="appAuthFilter"

                         discoveryEndpointUrl="${openid.provider.url}/.well-known/openid-configuration"
></openidConnectClient>
```

**Comment by teddyjtorres** [comment]
Hi.

Please set the `useSystemPropertiesForHttpClientConnections` attribute as follows, `<openidConnectClient useSystemPropertiesForHttpClientConnections="true" />`. That setting should cause the HTTP client used by the openIdConnectClient feature to the use the `http*`  system properties as documented in https://www.ibm.com/docs/en/was-liberty/nd?topic=configuration-openidconnectclient.

For reference, https://hc.apache.org/httpcomponents-client-4.5.x/current/httpclient/apidocs/org/apache/http/impl/client/HttpClientBuilder.html documents the system properties the HTTP client would use when the attribute is set.

Regards,
Teddy

**Comment by teddyjtorres** [comment]
Please see also the notes about using a proxy in step 2 of https://www.ibm.com/docs/en/was-liberty/nd?topic=connect-configuring-openid-client-in-liberty.

**Comment by dyapasrikanth** [comment]
Thanks for your response, but it only worked when I use individual urls like authorization, token. Looks like its an issue with [discoveryEndpointUrl](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientConfigImpl.java#L1136) handling code. Maybe it's not obeying the given flag.

**Comment by teddyjtorres** [comment]
Hi,

Thank you for verifying that it works when using individual urls. I reviewed the indicated code used for creating a connection to discoveryEndpointUrl and determined that it needs to be updated to use the `useSystemPropertiesForHttpClientConnections` attribute.

Thank you for opening this issue. We will create a fix.

Regards,
Teddy

**Comment by meiaus** [comment]
This is fixed via https://github.com/OpenLiberty/open-liberty/pull/21271.
