### ISSUE TITLE
The output of  ./wlp/bin/productInfo featureInfo missing new lines

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/open-liberty#19831]
**Describe the bug**  
I ran 22.0.0.1 ~and 21.0.0.12~. It gives me
```
acmeCA-2.0adminCenter-1.0appClientSupport-1.0appSecurity-1.0appSecurity-2.0appSecurity-3.0appSecurityClient-1.0audit-1.0batch-1.0batchManagement-1.0beanValidation-1.1beanValidation-2.0bells-1.0cdi-1.2cdi-2.0cloudant-1.0concurrent-1.0constra ...
```
before, 21.0.0.12  and 21.0.0.11 give me
```
acmeCA-2.0 [2.0.0]
appClientSupport-1.0 [1.0.0]
appSecurity-1.0 [1.1.0]
appSecurity-2.0 [1.0.0]
appSecurity-3.0 [1.0.0]
appSecurityClient-1.0 [1.0.0]
....
```

The ` [...]` version was removed by design but missing the new lines .

**Steps to Reproduce**  
- cd wlp/bin
- ./productInfo featureInfo

**Expected behavior**  
- the features should be listed by separated lines 

**Diagnostic information:**  
- Open Liberty 22.0.0.1 

**Additional context**  
- none

**Comment by tevans78** [comment]
I don't think this was broken in 21.0.0.12, only 22.0.0.1

**Comment by gkwan-ibm** [comment]
If this bug can be fixed in 22.0.0.1, it is a release bug, otherwise it is not

**Comment by jhanders34** [comment]
#regression

**Comment by mbroz2** [comment]
@gkwan-ibm or @tevans78 plz update the description using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
