### ISSUE TITLE
CDI 4.0 FTS

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#19870]
## Test Strategy

The _vast_ majority of testing for CDI 4.0 is implemented by adding repeats to existing buckets;

- [x] [com.ibm.ws.cdi.2.0_fat](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.cdi.2.0_fat)
- [x] [com.ibm.ws.cdi.annotations_fat](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.cdi.annotations_fat)
- [x] [com.ibm.ws.cdi.api_fat](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.cdi.api_fat)
- [x] [com.ibm.ws.cdi.beansxml.implicit_fat](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.cdi.beansxml.implicit_fat)
- [x] [com.ibm.ws.cdi.beansxml_fat](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.cdi.beansxml_fat)
- [x] [com.ibm.ws.cdi.ejb_fat](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.cdi.ejb_fat)
- [x] [com.ibm.ws.cdi.extension_fat](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.cdi.extension_fat)
- [x] [com.ibm.ws.cdi.jee_fat](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.cdi.jee_fat)
- [x] [com.ibm.ws.cdi.jndi_fat](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.cdi.jndi_fat)
- [x] [com.ibm.ws.cdi.lifecycle_fat](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.cdi.lifecycle_fat)
- [x] [com.ibm.ws.cdi.noncontextual_fat](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.cdi.noncontextual_fat)
- [x] [com.ibm.ws.cdi.third.party_fat](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.cdi.third.party_fat)
- [x] [com.ibm.ws.cdi.visibility_fat](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.cdi.visibility_fat)
- [x] [io.openliberty.cdi.3.0.internal_fat](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.cdi.3.0.internal_fat)
- [x] [io.openliberty.cdi.core_fat](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.cdi.core_fat)

A new CDI 4.0 specific FAT bucket is also being added to test Build Compatible Extensions and the new behaviour of an empty beans.xml file
[io.openliberty.cdi.4.0.internal_fat](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.cdi.4.0.internal_fat)

The CDI 4.0 TCK is also run as part of the regular EE10 CTS testing

## Confidence Level

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

**Comment by ayoho** [comment]
LGTM 👍
