### ISSUE TITLE
"ERROR: Input redirection is not supported, exiting the process immediately" reported with Open Liberty as a service on Win

### ISSUE THREAD

**Issue by hlhoots** [OpenLiberty/open-liberty#19897]
**Describe the bug**  
When running Open Liberty as a service on Windows, the following error is output when the timeout / retry logic is executed on start or stop: ERROR: Input redirection is not supported, exiting the process immediately.  

If there is a stack trace, please include the FULL stack trace (without any `[internal classes]` lines in it). To find the full stack trace, you may need to check in `$WLP_OUTPUT_DIR/messages.log`

Standard out was: ERROR: Input redirection is not supported, exiting the process immediately.
ERROR: Input redirection is not supported, exiting the process immediately.
ERROR: Input redirection is not supported, exiting the process immediately.
ERROR: Input redirection is not supported, exiting the process immediately.
ERROR: Input redirection is not supported, exiting the process immediately.

**Steps to Reproduce**  
No easy way to reproduce

**Expected behavior**  
Server start script should loop the specified number of times waiting for the server to start properly WITHOUT echoing the ERROR message to the console.

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.1
 - Affected feature(s) NA
 - Java Version: ALL
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**  
NA

**Comment by mbroz2** [comment]
@hlhoots plz update the description using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
