### ISSUE TITLE
Feature Test Summary - In Liberty plugin generation Implement configurable property for IgnoreAffinityRequests #19208

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#19905]
## Test Strategy

The plugin config generator is tested in unit test. This feature will add an additional test.

### List of FAT projects affected

* None - the function under test is unit tests.

### List of unites projects

* com.ibm.ws.webcontainer

#### What functionality is new or modified by this feature? 
This feature exposes configuration for generating an attribute in the plugin config generation that is currently hardcoded.

#### Positive tests
A new unit test is added that configures this property and validates the written plugin-cfg.xml has the value set according to the configuration

## Confidence Level

5

**Comment by ayoho** [comment]
Coverage sounds fine
