### ISSUE TITLE
Update ProxyServicesImpl after deprecated methods were removed by Weld 5

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#19911]
Multiple methods from org.jboss.weld.serialization.spi.ProxyServices were removed.

If you are an integrator, you probably implemented this interface at some point in time; these methods weren’t used by Weld anyway, so they are now gone for good.

Here is a link to the issue removing it.
https://issues.redhat.com/browse/WELD-2702

**Comment by tevans78** [comment]
It may be that if the methods are never called then they can be removed. Need to check if they are being called elsewhere.

https://github.com/OpenLiberty/open-liberty/blob/e65a099ee72b33bb86b665f450e23642984a8578/dev/io.openliberty.cdi.4.0.internal.weld/src/com/ibm/ws/cdi/proxy/AbstractProxyServices.java#L87

https://github.com/OpenLiberty/open-liberty/blob/e65a099ee72b33bb86b665f450e23642984a8578/dev/io.openliberty.cdi.4.0.internal.weld/src/com/ibm/ws/cdi/proxy/AbstractProxyServices.java#L187

**Comment by benjamin-confino** [comment]
The final part of this was completed with PR 23816
