### ISSUE TITLE
SVT: AdminCenter hangs on Liberty collective using early PersonalBuild for feature 18696 beta testing

### ISSUE THREAD

**Issue by hanczaryk** [OpenLiberty/open-liberty#19930]
SVT: AdminCenter hangs on Liberty collective using early PersonalBuild for feature 18696 beta testing

Katie pointed me to a PersonalBuild that I could utilize for very early SVT beta testing of feature 18696 (https://github.com/OpenLiberty/open-liberty/issues/18696).

I was able to validate on a single Liberty server config using that PersonalBuild with -Dcom.ibm.ws.beta.edition=true set in the jvm.options, allowed the user to view and utilize the new test connection button in the UI.

I attempted to setup a small Liberty collective (one collective controller and one collective member) using the same PersonalBuild with -Dcom.ibm.ws.beta.edition=true set in the jvm.options.  With the -Dcom.ibm.ws.beta.edition=true set in the jvm.options, the adminCenter appears to hang when attempting to view the collective member's server config.  

Here is the screenshot of the UI showing the collective controller and collective member.
![image](https://user-images.githubusercontent.com/30906029/151190416-cbffcc5c-2ca1-48b1-b916-5e9ab099522a.png)

Here is the screenshot of the UI showing the browser after I have clicked on the member (BServer) where it just hangs in this state.
![image](https://user-images.githubusercontent.com/30906029/151190682-1f4a7231-755e-47e1-8a94-8082aca54b20.png)

If I stop the collective, remove the -Dcom.ibm.ws.beta.edition=true from jvm.options, and then restart the collective, I'm able to follow the same steps but the UI doesn't hang and successfully shows the member BServer's server.xml.  Here is the screenshot.
![image](https://user-images.githubusercontent.com/30906029/151191502-caa7f3d5-2bfd-4869-b24a-af9f5a1cf58a.png)

**Comment by k8vance88** [comment]
This issue has been fixed. The validation feature is available in beta builds.

**Comment by hanczaryk** [comment]
@k8vance88 I'll personally be doing the testing for this feature and I'll be out of the office until the new year.  SVT will attempt in early 2023.
