### ISSUE TITLE
Enable the OpenAPI validator

### ISSUE THREAD

**Issue by mrglavas** [OpenLiberty/open-liberty#1996]
Enable validation in the ApplicationProcessor. Report separate and distinct messages for errors and warnings from each validation event.

**Comment by leochr** [comment]
@mrglavas as part of this change, could you please also modify the configuration value of the validation flag: it should be OASConfig.EXTENSIONS_PREFIX + "liberty.validation"

**Comment by mrglavas** [comment]
@leochr Just made the change locally. It will be in the PR that I submit.

**Comment by mrglavas** [comment]
Delivered by PR: https://github.com/arturdzm/open-liberty/pull/25/
