### ISSUE TITLE
OpenID Connect: Double URL Encoded State Parameter in Redirect location

### ISSUE THREAD

**Issue by mjwhale** [OpenLiberty/open-liberty#19960]
**Describe the bug**  
An apparent regression of a very early bug:
https://www.ibm.com/support/pages/apar/PI25813

When receiving a state parameter from the RP it appears Liberty returns the state double encoded.

The issue appears to occur when processing the liberty page to authorize the RP:
https://www.oauth-login.com/oidc/endpoint/rp/authorize
Payload state:  yyyyyyyyyyyyyyyyy

Which results in a response code 302:
and a redirect location of:
https://oauth-openshift.apps.ocp4.example.com/oauth2callback/openid?code=xxxxxxxx&state=zzzzzzzzzzzzzzzzzz

The double encoding is proven because the response location URL includes a state parameter that can be decoded back to the Payload state that was returned in the previous request.

This behaviour can be seen in trace statements before and after the submission of the "Allow client rp to access the following data:" page:

Redirect from processing user login:
[1/28/22, 7:36:03:960 UTC] 00000051 id=00000000 com.ibm.ws.webcontainer.srt.SRTServletResponse               > sendRedirect ENTRY location --> https://www.oauth-login.com/oidc/endpoint/rp/authorize?client_id=rp&redirect_uri=https%3A%2F%2Foauth-openshift.apps.ocp4.example.com%2Foauth2callback%2Fopenid&response_type=code&scope=openid&state=Y3NyZj1idWJsVGFJdjV3ajJJSFB2eVRHZmU0S1lCZzdzRmdURHBLYkNQS18zOVFrJnRoZW49JTJGb2F1dGglMkZhdXRob3JpemUlM0ZjbGllbnRfaWQlM0Rjb25zb2xlJTI2aWRwJTNEb3BlbmlkJTI2cmVkaXJlY3RfdXJpJTNEaHR0cHMlMjUzQSUyNTJGJTI1MkZjb25zb2xlLW9wZW5zaGlmdC1jb25zb2xlLmFwcHMub2NwNC5leGFtcGxlLmNvbSUyNTJGYXV0aCUyNTJGY2FsbGJhY2slMjZyZXNwb25zZV90eXBlJTNEY29kZSUyNnNjb3BlJTNEdXNlciUyNTNBZnVsbCUyNnN0YXRlJTNEZmQ3NWRlN2M%3D [com.ibm.ws.webcontainer31.srt.SRTServletResponse31@b41ca664]

Redirect from processing authorize:
[1/28/22, 7:36:21:616 UTC] 00000051 id=00000000 com.ibm.ws.webcontainer.srt.SRTServletResponse               > sendRedirect ENTRY location --> https://oauth-openshift.apps.ocp4.example.com/oauth2callback/openid?code=HCYfKgIL4WfBxJuqmOFBnY79MDCQb9&state=Y3NyZj1idWJsVGFJdjV3ajJJSFB2eVRHZmU0S1lCZzdzRmdURHBLYkNQS18zOVFrJnRoZW49JTJGb2F1dGglMkZhdXRob3JpemUlM0ZjbGllbnRfaWQlM0Rjb25zb2xlJTI2aWRwJTNEb3BlbmlkJTI2cmVkaXJlY3RfdXJpJTNEaHR0cHMlMjUzQSUyNTJGJTI1MkZjb25zb2xlLW9wZW5zaGlmdC1jb25zb2xlLmFwcHMub2NwNC5leGFtcGxlLmNvbSUyNTJGYXV0aCUyNTJGY2FsbGJhY2slMjZyZXNwb25zZV90eXBlJTNEY29kZSUyNnNjb3BlJTNEdXNlciUyNTNBZnVsbCUyNnN0YXRlJTNEZmQ3NWRlN2M%253D [com.ibm.ws.webcontainer31.srt.SRTServletResponse31@b41ca664]

the location response contains a state of:
Y3NyZj1idWJsVGFJdjV3ajJJSFB2eVRHZmU0S1lCZzdzRmdURHBLYkNQS18zOVFrJnRoZW49JTJGb2F1dGglMkZhdXRob3JpemUlM0ZjbGllbnRfaWQlM0Rjb25zb2xlJTI2aWRwJTNEb3BlbmlkJTI2cmVkaXJlY3RfdXJpJTNEaHR0cHMlMjUzQSUyNTJGJTI1MkZjb25zb2xlLW9wZW5zaGlmdC1jb25zb2xlLmFwcHMub2NwNC5leGFtcGxlLmNvbSUyNTJGYXV0aCUyNTJGY2FsbGJhY2slMjZyZXNwb25zZV90eXBlJTNEY29kZSUyNnNjb3BlJTNEdXNlciUyNTNBZnVsbCUyNnN0YXRlJTNEZmQ3NWRlN2M%253D

which can be decoded back to the payload that is seen in the redirect response of the login page:
Y3NyZj1idWJsVGFJdjV3ajJJSFB2eVRHZmU0S1lCZzdzRmdURHBLYkNQS18zOVFrJnRoZW49JTJGb2F1dGglMkZhdXRob3JpemUlM0ZjbGllbnRfaWQlM0Rjb25zb2xlJTI2aWRwJTNEb3BlbmlkJTI2cmVkaXJlY3RfdXJpJTNEaHR0cHMlMjUzQSUyNTJGJTI1MkZjb25zb2xlLW9wZW5zaGlmdC1jb25zb2xlLmFwcHMub2NwNC5leGFtcGxlLmNvbSUyNTJGYXV0aCUyNTJGY2FsbGJhY2slMjZyZXNwb25zZV90eXBlJTNEY29kZSUyNnNjb3BlJTNEdXNlciUyNTNBZnVsbCUyNnN0YXRlJTNEZmQ3NWRlN2M%3D

when the redirect is processed by Openshift the following message is printed:
AuthenticationError: illegal base64 data at input byte 379 

Presumably becuase it is trying to base64 decode a double URLencoded value

**Steps to Reproduce**  
Steps to reproduce the bug:

Configure Liberty with support for an OpenIDConnect Provider and Openshift as the relying party.

Login to Openshift ensuring to select the configured OpenID connect login option.

The login process should present the Liberty login page.  After login the 'Allow' page is presented.  Following the submission of the allow page, the redirect to Openshift is performed with the double URL encoded parameters.  Login fails.

**Expected behavior**  
The payload state in the redirect URL should be returned in the same state as it was received.

**Diagnostic information:**  
 - OpenLiberty Version: [e.g. 21.0.0.8 - 21.0.0.10] 21.0.0.12
 - Affected feature(s) [e.g. mpHealth-3.0]         oauth-2.0, openidConnectServer-1.0
 - Java Version: [i.e. full output of `java -version`]
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**  

```
<server>
    <featureManager>
        <feature>oauth-2.0</feature>
        <feature>transportSecurity-1.0</feature>
        <feature>openidConnectServer-1.0</feature>
        <feature>transportSecurity-1.0</feature>
    </featureManager>

    <httpEndpoint host="*" httpPort="${default.http.port}" httpsPort="${default.https.port}" id="defaultHttpEndpoint">
        <sslOptions sslRef="mySSLConfig" />
    </httpEndpoint>

    <ssl id="mySSLConfig" keyStoreRef="myKeyStore" trustStoreRef="myTrustStore" sslProtocol="TLSv1.2" />

    <keyStore id="myKeyStore" location="${server.config.dir}/resources/mykeystore.p12_route" password="xxxxxxxxxxxx" type="PKCS12" />

    <keyStore id="myTrustStore" location="${server.config.dir}/resources/mytruststore.p12_route" password="xxxxxxxxxx" type="PKCS12" />

    <oauth-roles>
        <authenticated>
            <special-subject type="ALL_AUTHENTICATED_USERS" />
        </authenticated>
        <clientManager>
            <group name="clientAdministrator" />
            <user name="testuser" />
        </clientManager>
    </oauth-roles>

    <openidConnectProvider id="rp" oauthProviderRef="oauth" />

    <oauthProvider id="oauth">
        <localStore>
            <client name="rp" secret="xxxxxxxxxxx" displayname="rp" scope="openid profile email" redirect="https://oauth-openshift.apps.ocp4.example.com/oauth2callback/openid" enabled="true" />
        </localStore>
    </oauthProvider>

    <basicRegistry id="basic" realm="BasicRealm">
        <user name="testuser" password="xxxxxxxxxxxx" />
        <user name="testuser2" password="xxxxxxxxxxx" />
        <user name="testuser3" password="xxxxxxxxxxx" />
    </basicRegistry>

    <webAppSecurity allowFailOverToBasicAuth="true" />

</server>
```

**Comment by ayoho** [comment]
Thanks for opening an issue - we'll take a look to see what's happening.
