### ISSUE TITLE
featureUtility does not pass all features from server.xml to repository resolver

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/open-liberty#19991]
**Describe the bug**  
After the fix in #19871, there are still issues where a featureUtility does not pass in the list of all of the features from the server.xml file to the repository resolver.  If a feature is already installed it ends up not passing it.  There may be difference decisions made on which features to install with a combination of features that are not made when only one feature is passed to the repository resolver.   As such all features need to be passed even if the features are installed.  I believe this should include if all features are already installed to make sure nothing else shows up as being needed.  If the list of feature returned from the resolveAsSet are all installed including all private and auto features, then there is truly nothing to install.

**Steps to Reproduce**  
There are easy ways to reproduce this issue.  

1. Download Jakarta EE 8 image from 21.0.0.12 or 22.0.0.1 and replace the repository.resolver bundle with one from a 22.0.0.2 build with #19871 resolved in it
2. Create a server with a server.xml file in it with the jakartaee-9.1 and federatedRegistry-1.0 feature in it.
3. Run featureUtility installServerFeatures serverName

**Expected behavior**  
The io.openliberty.wimcore.internal.ee-9.0.mf feature should be installed because with the combination of ee9 and federatedRegistry-1.0, it will choose the ee9 tolerated feature.

**Comment by Azquelt** [comment]
> If the list of feature returned from the resolveAsSet are all installed including all private and auto features, then there is truly nothing to install.

Actually, the resolver will only return something for features which need to be installed. If everything is already installed, you should get back an empty collection.

**Comment by Azquelt** [comment]
For general reference, the Javadoc on the public methods of [`RepositoryResolver`][repo-resolver] is fairly thorough and if there's a particular scenario in question, the unit tests in [`ResolutionTests`][resolution-tests] may well cover it.

[repo-resolver]: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/RepositoryResolver.java
[resolution-tests]: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.repository.resolver/test/com/ibm/ws/repository/resolver/ResolutionTests.java

**Comment by jhanders34** [comment]
The LGP / LMP scenario may be different since it starts with a kernel image.  Here is what I suggest for that scenario to see if those need to be updated as well.  Obviously those are updated in a different repo.

1. Run the LGP / LMP with 21.0.0.12 or 22.0.0.1 and replace the repository.resolver bundle with one from a 22.0.0.2 build with #19871 resolved in it
2. Create a server with a server.xml file in it with the jakartaee-8.0 and federatedRegistry-1.0 feature in it and have the plugin install those features on the kernel.
3. Update the server.xml file with the jakartaee-9.1 and federatedRegistry-1.0 feature in it.
4. The plugin should update to install jakartaee-9.1 and the wimcore internal ee-9.0 feature.

**Comment by jjiwooLim** [comment]
FeatureUtility/InstallUtility is now passing all features (including features that are already installed) to `resolveAsSet` api. No changes required for LGP/LMP, will pick up the changes from openlibery PR. 

Closed liberty PR for installUtility: https://github.ibm.com/websphere/WS-CD-Open/pull/26039
