### ISSUE TITLE
Multi module maven application failed to start with looseConfig option

### ISSUE THREAD

**Issue by jagraj** [OpenLiberty/open-liberty#19994]
I am developing my application using Liberty WDT tools.I have multi module maven application and I am trying to deploy application to liberty server and it is failed to start with `liberty:start` goal. I have `<looseApplication>true</looseApplication>` property set to start my application in loose config mode.The same application starts fine with `liberty:dev` mode but not with `liberty:start`.Here are the class loader errors during application start.

```
[INFO    ] FFDC1015I: An FFDC Incident has been created: "java.lang.NoClassDefFoundError: com/ibm/websphere/svt/gs/tax/session/InventorySession com.ibm.ws.injectionengine.InjectionProcessorManager.getAllDeclaredFields 249" at ffdc_22.01.26_15.52.17.0.log
[WARNING ] CWNEN0047W: Resource annotations on the fields of the com.ibm.websphere.svt.gs.gsjsfweb.websockets.GarageSaleWebSocketSessionBean class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: com/ibm/websphere/svt/gs/tax/session/InventorySession
[INFO    ] FFDC1015I: An FFDC Incident has been created: "java.lang.NoClassDefFoundError: com/ibm/websphere/svt/gs/tax/session/CustomerSession com.ibm.ws.injectionengine.InjectionProcessorManager.getAllDeclaredFields 249" at ffdc_22.01.26_15.52.17.1.log
[WARNING ] CWNEN0047W: Resource annotations on the fields of the com.ibm.websphere.svt.gs.gsjsfweb.websockets.GarageSaleDashboardEndPoint class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: com/ibm/websphere/svt/gs/tax/session/CustomerSession
[INFO    ] FFDC1015I: An FFDC Incident has been created: "java.lang.NoClassDefFoundError: com/ibm/websphere/svt/gs/tax/entity/ProdReview com.ibm.wsspi.injectionengine.MethodMap.getAllDeclaredMethods 106" at ffdc_22.01.26_15.52.17.2.log
[WARNING ] CWNEN0049W: Resource annotations on the methods of the com.ibm.websphere.svt.gs.gsjsfweb.utils.GarageSaleManagedBeanUtil class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: com/ibm/websphere/svt/gs/tax/entity/ProdReview
[INFO    ] registering MBean org.apache.cxf:bus.id=GSjsf20LibertyWeb-Client-Bus,type=Bus,instance.id=463868583: org.apache.cxf.bus.ManagedBus@37e7273e
[INFO    ] registered org.apache.cxf:bus.id=GSjsf20LibertyWeb-Client-Bus,type=Bus,instance.id=463868583
[INFO    ] registering MBean org.apache.cxf:bus.id=GSjsf20LibertyWeb-Client-Bus,WorkQueueManager=Bus.WorkQueueManager,type=WorkQueueManager,instance.id=1428955989: org.apache.cxf.bus.managers.WorkQueueManagerImplMBeanWrapper@7eb4307d
[INFO    ] WELD-000411: Observer method [BackedAnnotatedMethod] org.apache.myfaces.cdi.JsfArtifactProducerExtension.processAnnotatedType(@Observes ProcessAnnotatedType<T>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
[INFO    ] WELD-000411: Observer method [BackedAnnotatedMethod] org.apache.myfaces.config.annotation.CdiAnnotationProviderExtension.processAnnotatedType(@Observes ProcessAnnotatedType<T>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
[INFO    ] HV000001: Hibernate Validator 7.0.0.Final
[INFO    ] WELD-000119: Not generating any bean definitions from com.ibm.websphere.svt.gs.gsjsfweb.websockets.GarageSaleWebSocketSessionBean because of underlying class loading error: Type com.ibm.websphere.svt.gs.tax.session.InventorySession not found.  If this is unexpected, enable DEBUG logging to see the full error.
[INFO    ] WELD-000119: Not generating any bean definitions from com.ibm.websphere.svt.gs.gsjsfweb.websockets.GarageSaleDashboardEndPoint because of underlying class loading error: Type com.ibm.websphere.svt.gs.tax.session.CustomerSession not found.  If this is unexpected, enable DEBUG logging to see the full error.
[INFO    ] WELD-000119: Not generating any bean definitions from com.ibm.websphere.svt.gs.gsjsfweb.utils.GarageSaleManagedBeanUtil because of underlying class loading error: Type com.ibm.websphere.svt.gs.tax.entity.ProdReview not found.  If this is unexpected, enable DEBUG logging to see the full error.
[INFO    ] WELD-000119: Not generating any bean definitions from com.ibm.websphere.svt.gs.gsjsfweb.websockets.GarageSaleWebSocketsUtil because of underlying class loading error: Type com.ibm.websphere.svt.gs.tax.entity.Inventory not found.  If this is unexpected, enable DEBUG logging to see the full error.
[INFO    ] FFDC1015I: An FFDC Incident has been created: "org.jboss.weld.resources.spi.ResourceLoadingException: Error while loading class com.ibm.websphere.svt.gs.gsjsfweb.utils.GarageSaleManagedBeanUtil com.ibm.ws.cdi.impl.weld.BeanDeploymentArchiveImpl 946" at ffdc_22.01.26_15.52.20.0.log
[INFO    ] FFDC1015I: An FFDC Incident has been created: "org.jboss.weld.resources.spi.ResourceLoadingException: Error while loading class com.ibm.websphere.svt.gs.gsjsfweb.websockets.GarageSaleDashboardEndPoint com.ibm.ws.cdi.impl.weld.BeanDeploymentArchiveImpl 946" at ffdc_22.01.26_15.52.20.1.log
[WARNING ] WELD-001469: Method initializeEndpoints defined on class com.ibm.websphere.svt.gs.gsjsfweb.utils.GarageSaleJSFWSClientInterceptor is not defined according to the specification. It is annotated with @jakarta.interceptor.AroundConstruct but it does not have zero parameters.

[INFO    ] FFDC1015I: An FFDC Incident has been created: "org.jboss.weld.exceptions.DeploymentException: Exception List with 2 exceptions:
Exception 0 :
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type GarageSaleWebSocketSessionBean with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private com.ibm.websphere.svt.gs.gsjsfweb.websockets.InventoryOnSaleProgEndpoint.garageSaleWebSocketSessionBean
  at com.ibm.websphere.svt.gs.gsjsfweb.websockets.InventoryOnSaleProgEndpoint.garageSaleWebSocketSessionBean(InventoryOnSaleProgEndpoint.java:0)
WELD-001474: Class com.ibm.websphere.svt.gs.gsjsfweb.websockets.GarageSaleWebSocketSessionBean is on the classpath, but was ignored because a class it references was not found: com.ibm.websphere.svt.gs.tax.session.InventorySession.

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:378)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:290)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:143)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:164)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:526)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:64)
```

**Comment by jagraj** [comment]
@kathrynkodama 

Here are my results for your above request. I executed all these steps from command line not from WDT workspace.

1. Application worked with this option but I don't think so looseConfig working here. I see an ear file is installed into the apps folder rather after running `liberty:run` from the project where we have liberty maven plugin is defined. I also see *.xml file created in apps folder when I executed `clean install` goals. 

![image](https://user-images.githubusercontent.com/713849/151392809-94f13a92-2952-48bd-9ed1-633de3cf4f0f.png)

2. Application failed to start with this option with class loader issues, I executed `mvn clean install` and then executed `mvn liberty:start` from my liberty-maven-plugin project. I don't see ear file deployed in this scenario.

![image](https://user-images.githubusercontent.com/713849/151397848-b6696032-efeb-4d7b-a360-c2abca50a360.png)

**Comment by dazavala** [comment]
Regarding the classloading trace from `looseConfig_logs_trace.zip`:  The CNFE for class `com/ibm/websphere/svt/gs/tax/session/InventorySession` is due to neither the EAR loader (id=32750421) nor Web module loader contain a classpath entry for the ProdReviewTaxShipRateEJB module -- i.e. the loose config classes or jar path that contains the InventorySession class.  The CNFE (also noted as NCDFE) occurs while processing annotations for classes in Web module GSJSFLibertyWeb.  The `InventorySession` class is simply not visible to the web module classloader.

The logs show no indication of processing module `ProdReviewTaxShipRateEJB`.  This begs the question whether/how the loose config for the EAR references the `ProdReviewTaxShipRateEJB` module, and whether the application artifacts reside where expected in the workspace (loose config targets).  

The EJB module is "in-WAR" for this deployment, and the EJB module jar is in the Web module's web-inf/lib directory within the workspace.  There is no ejb-jar.xml as the EJB classes are annotated.  I would expect the EJB module jar to be on the classpath of the Web module classloader, but it is not.  

FYI...

The xml for the loose config is loading as expected: 
> [2/1/22, 16:53:09:957 EST] 00000028 id=00000000 bm.ws.app.manager.ear.internal.EARDeployedAppInfoFactoryImpl I CWWKZ0134I: The GarageSaleLibertyEAR8-LooseConfig application is using the loose application definition at the **C:\MyData\LibertyInstalls\wlp\usr\servers\garageSaleServer\apps\GarageSaleLibertyEAR.ear.xml** location.

The EAR classloader (id=32750421) has classpath entries:

> C:\MyData\MyWDTWorkspaces\GarageSale\GarageSaleEE7\garageSale-ee7\CreditCardEJB\target\classes,
> C:\MyData\MyWDTWorkspaces\GarageSale\GarageSaleEE7\garageSale-ee7\WSBankEJB\target\classes, 
> C:\MyData\MyWDTWorkspaces\GarageSale\GarageSaleEE7\garageSale-ee7\GarageSaleEJB\target\classes, 
> C:\MyData\MyWDTWorkspaces\GarageSale\GarageSaleEE7\garageSale-ee7\CreditCardDBJPA\target\classes, 
> C:\MyData\MyWDTWorkspaces\GarageSale\GarageSaleEE7\garageSale-ee7\WSBankDBJPA\target\classes, 
> C:\MyData\MyWDTWorkspaces\GarageSale\GarageSaleEE7\garageSale-ee7\GarageSaleWSClient\target\classes,
> C:\MyData\MyWDTWorkspaces\GarageSale\GarageSaleEE7\garageSale-ee7\WASPersonaWebServicesHandlerAPI\target\classes, 
> C:\MyData\MyWDTWorkspaces\GarageSale\GarageSaleEE7\garageSale-ee7\GarageSaleDBJPA\target\classes

And the child web module classloader (d=6d2b762f) has classpath entries:

> C:\MyData\MyWDTWorkspaces\GarageSale\GarageSaleEE7\garageSale-ee7\GSJSFLibertyWeb\src\main\webapp,
> C:\MyData\MyWDTWorkspaces\GarageSale\GarageSaleEE7\garageSale-ee7\GarageSaleEJB\target\classes, 
> C:\MyData\MyWDTWorkspaces\GarageSale\GarageSaleEE7\garageSale-ee7\GSJSFLibertyWeb\target\classes, 
> C:\MyData\MyWDTWorkspaces\GarageSale\GarageSaleEE7\garageSale-ee7\GSJSFLibertyWeb\src\main\webapp\WEB-INF\lib\dojo-faces-1.3_00.jar]

**Comment by jagraj** [comment]
@dazavala 
Here is the loose config file that I am attaching to this issue.

[GarageSaleLibertyEAR.ear.xml.zip](https://github.com/OpenLiberty/open-liberty/files/8027543/GarageSaleLibertyEAR.ear.xml.zip)

**Comment by dazavala** [comment]
@jagraj I found a helpful [doc on liberty loose config](https://www.ibm.com/docs/en/was-liberty/base?topic=liberty-loose-applications).  I believe the unexpected classloader configuration for the web module is caused by the app’s loose config descriptor (xxx.ear.xml), which contains no target mapping to web-inf/lib/ProdReviewTaxShipRateEJB.jar within the GSjsf20LibertyWeb `<archive/>`.   Problem may resolve by adding a dependency jar to the web module.  I noticed dojo-faces-1.3_00.jar is in web-inf/lib, which I can't yet explain, as this jar is also not referenced by xxx.ear.xml; the jar may be referenced in the `GSJSFLibertyWeb\META-INF/MANIFEST.MF#class-path:` attribute.  Also, for normal app deployment as ejb-in-war, it is sufficient to nest the EJB jar into the web module's web-inf/lib directory -- just as you advised.

**Comment by jagraj** [comment]
@dazavala 

I have dependency module defined in pom.xml for `ProdReviewTaxShipRateEJB`  in my web module.

```
		<dependency>
			<groupId>com.ibm.ws.svt.gs.garagesale-ee9</groupId>
			<artifactId>ProdReviewTaxShipRateEJB</artifactId>
			<version>0.0.1-SNAPSHOT</version>
			<type>ejb</type>
		</dependency>
```

**Comment by jagraj** [comment]
@dazavala 

I removed <type>ejb</type> and set it to default type which is `jar` packaging and now I see loose config xml file created with classes and manifest entry for `ProdReviewTaxShipRateEJB` module. 

Thanks for all your help in debugging this issue.

```
    <archive targetInArchive="/GSjsf20LibertyWeb.war">
        <dir sourceOnDisk="C:\MyData\MyWDTWorkspaces\GarageSale\GarageSaleEE7\garageSale-ee7\GSJSFLibertyWeb\src\main\webapp" targetInArchive="/"/>
        <dir sourceOnDisk="C:\MyData\MyWDTWorkspaces\GarageSale\GarageSaleEE7\garageSale-ee7\GSJSFLibertyWeb\target\classes" targetInArchive="/WEB-INF/classes"/>
        <file sourceOnDisk="C:\MyData\MyWDTWorkspaces\GarageSale\GarageSaleEE7\garageSale-ee7\GSJSFLibertyWeb\target\tmp\META-INF\MANIFEST.MF" targetInArchive="/META-INF/MANIFEST.MF"/>
        <archive targetInArchive="/WEB-INF/lib/ProdReviewTaxShipRateEJB.jar">
            <dir sourceOnDisk="C:\MyData\MyWDTWorkspaces\GarageSale\GarageSaleEE7\garageSale-ee7\ProdReviewTaxShipRateEJB\target\classes" targetInArchive="/"/>
            <file sourceOnDisk="C:\MyData\MyWDTWorkspaces\GarageSale\GarageSaleEE7\garageSale-ee7\ProdReviewTaxShipRateEJB\target\tmp\META-INF\MANIFEST.MF" targetInArchive="/META-INF/MANIFEST.MF"/>
        </archive>
    </archive>

```

**Comment by dazavala** [comment]
@jagraj Thanks for posting your progress and closing the issue.  I located the WDT technical contact, [@mattcolegate](https://ibm-cloud.slack.com/team/W3G2KT716), if you need a second opinion regarding the appropriate maven dependency type for an ejb-in-war module.
