### ISSUE TITLE
RP FAT updates for 18105 (OIDC Back-Channel Logout)

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#20049]
Update to the OIDC RP FAT test projects for logout.
Test invalid request content, mismatch sid values, stopped servers, stopped and restarted servers, ...
#20044

**Comment by c00crane** [comment]
https://github.com/OpenLiberty/open-liberty/pull/21677 delivers the base set of tests

**Comment by ayoho** [comment]
Resolved by various PRs.
