### ISSUE TITLE
server commands not working on IBM i after checkpoint changes

### ISSUE THREAD

**Issue by gjwatts** [OpenLiberty/open-liberty#20063]
**Describe the bug**
On IBM i, with the changes introduced to the `server` command line script in PR #19856, the `server` command with any option fails on 22.0.0.2 with this error:
```
server: 001-0050 Syntax error on line 1339: token "!" not expected.
```

The problematic line (1339) in question is:
```
if [ "${ACTION}" = "checkpoint" ] || ! serverHasCheckpoint; then
```

Changing it to:
```
if [ "${ACTION}" = "checkpoint" ] || [ ! serverHasCheckpoint ]; then
```
Removes that issue.

After that change, there is now another problem when starting the server (debug, run, start):
```
server: 001-0055 Error found creating file /QIBM/UserData/WebSphere/LibertyServer/V21.0.0.11/Express_2/wlp/output/servers/greg210011/workarea/checkpoint/restoreTime. No such path or directory
```
That needs to get fixed and the `stop` command will need to be verified once the start commands are working.

**Steps to Reproduce**  
Install Liberty 22.0.0.2 and attempt to use the `server` command.

**Expected behavior**  
The `server` command should function correctly.

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.2
 - Affected feature(s) All
 - Java Version: N/A

**Additional context**

**Comment by gjwatts** [comment]
Closing since PR #20079 is now merged.

**Comment by mbroz2** [comment]
@gjwatts All `release bug` issues must use the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=) in the description/first comment.

**Comment by gjwatts** [comment]
@mbroz2 Thanks for letting me know.  Do I need to change anything in this issue?  Or was that for future reference?

**Comment by mbroz2** [comment]
The first comment of this issue should be replaced with the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=) and populated accordingly

**Comment by gjwatts** [comment]
@mbroz2 Thank you and done.
