### ISSUE TITLE
Develop Unit tests for verifying OpenAPI parser. 

### ISSUE THREAD

**Issue by a-saf** [OpenLiberty/open-liberty#2009]
Use the test documents from #2008 to creates tests to verify that the parser creates models containing all the information from the docs and serialize correctly.

**Comment by mrglavas** [comment]
@a-saf I'm marking this as technical debt, assuming you haven't started it yet.

**Comment by a-saf** [comment]
List of models to check:

- [ ] Info
- [ ] Contact
- [ ] License
- [ ] Components
- [ ] Callback
- [ ] Content
- [ ] Discriminator
- [ ] ServerVariable
- [ ] ServerVariables
- [ ] Server
- [ ] Components
- [ ] Paths
- [ ] PathItem
- [ ] Operation
- [ ] ExternalDocumentation
- [ ] Parameter
- [ ] RequestBody
- [ ] MediaType
- [ ] Encoding
- [ ] APIResponse
- [ ] APIResponses
- [ ] Example
- [ ] Link
- [ ] Header
- [ ] Tag
- [ ] Schema
- [ ] XML
- [ ] Security Scheme
- [ ] Security Requirement
- [ ] Scopes
- [ ] OAuthFlow
- [ ] OAuthFlows
- [ ] OpenAPI
