### ISSUE TITLE
SIP on Netty subproject: use common packaging strategy

### ISSUE THREAD

**Issue by epj** [OpenLiberty/open-liberty#20115]
The packaging of the draft SIP changes likely needs to be re-thought. Currently this PR results in new bundles being added to the runtime by a GA feature, which is the desired end result but is probably not OK for this type of code.

**Comment by hutchig** [comment]
There is this in the metatype.xml:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/2861921/154076564-8be4465d-e0fa-4a21-9ad6-e17edd81a0a9.png">

(Note: ibm:beta=true)

**Comment by pnicolucci** [comment]
The main question here is can we add new bundles to a GA feature. The consensus has been `yes` as long as all the new code is properly beta guarded. Our beta guard design will be outlined here:  https://github.com/OpenLiberty/open-liberty/issues/20117

I'll close this issue as the way the SIP PR is laid out currently is fine relating to the new bundles in the GA feature as long as everything is beta guarded.
