### ISSUE TITLE
CDI 4.0 Configuration Options

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#20122]
The current CDI configuration metatype is `cdi12`. `cdi12` was originally chosen because the configuration option being added (`enableImplicitBeanArchives`) would not apply to CDI 1.0, only to 1.2 and above. However, this remains potentially confusing when you are using something other than CDI 1.2.

CDI 4.0 is adding a new configuration option to allow backwards compatible behaviour for archives with an empty beans.xml (provisionally called `emptyBeansXMLExplicitArchive`). It really does not seem like a good idea to add a CDI 4.0+ specific option into a configuration metatype called `cdi12`. That would be even more confusing.

-------------
**Option 1.**

Simply add the new option to the existing `cdi12` configuration.  e.g.
```
<cdi12 enableImplicitBeanArchives="false" emptyBeansXMLExplicitArchive="true"/>
```
Clear documentation would be required to say which CDI versions each option applied to.
`cdi12` = Contexts And Dependency Injection V1.2 Or Newer
`enableImplicitBeanArchives` = Enable scanning implicit bean archives.
`emptyBeansXMLExplicitArchive` = An Archive with an empty beans.xml file is considered to be an explicit bean archive. Applies to CDI 4.0 or newer.

I really don't like adding a CDI 4.0+ specific option to a config element called `cdi12`.

-------------
**Option 2.**

Create a new metatype called `cdi40` that only has the new the new option (currently called emptyBeansXMLExplicitArchive) e.g.
```
<cdi12 enableImplicitBeanArchives="false"/>
<cdi40 emptyBeansXMLExplicitArchive="true"/>
```
While this is the simple addition of a new option, it is potentially confusing that you may have to use two different CDI config elements.
`cdi12` = Contexts And Dependency Injection V1.2 Or Newer
`enableImplicitBeanArchives` = Enable scanning implicit bean archives.
`cdi40`= Contexts And Dependency Injection V4.0 Or Newer
`emptyBeansXMLExplicitArchive` = An Archive with an empty beans.xml file is considered to be an explicit bean archive.

This option feels like repeating the same mistake as before. If another new option is required for CDI 5.0 then do we have to keep creating new version specific metatypes?

-------------
**Option 3.** (Recommended)

Create a new metatype called just `cdi` that has both the new option (currently called emptyBeansXMLExplicitArchive) and the old one (enableImplicitBeanArchives) e.g.
```
<cdi12 enableImplicitBeanArchives="true"/>     <!-- would be ignored because it is set to false below -->
<cdi enableImplicitBeanArchives="false" emptyBeansXMLExplicitArchive="true"/>
```
Obviously we can not remove the old `cdi12` configuration. In both cases, the default value for `enableImplicitBeanArchives` is `true` so if either one is set to `false` then that would take precedence.

If `emptyBeansXMLExplicitArchive` is set when using a version less than 4.0, it would just be ignored.

Clear documentation would be required to say which CDI versions each option applied to.
`cdi`= Contexts And Dependency Injection
`enableImplicitBeanArchives` = Enable scanning implicit bean archives. Applies to CDI 1.2 or newer.
`emptyBeansXMLExplicitArchive` = An Archive with an empty beans.xml file is considered to be an explicit bean archive. Applies to CDI 4.0 or newer.

This is my preferred option. While we can not remove `cdi12`, we can discourage its use in favour of the new `cdi` element. We will not have the same issues again in the future. Clear documentation will be important though.

-------------
**Option 4.**

Create a new metatype called `cdi40` that has both the new option (currently called emptyBeansXMLExplicitArchive) and the old one (enableImplicitBeanArchives) e.g.
```
<cdi12 enableImplicitBeanArchives="true"/> <!-- would be ignored because it is set to false below -->
<cdi40 enableImplicitBeanArchives="false" emptyBeansXMLExplicitArchive="true"/>
```
This is more or less the same as Option 3 but with a name that makes it clearer that it is for CDI 4.0+. Similarly we can not remove the old `cdi12` configuration. If `enableImplicitBeanArchives` is set to `false` on either one, then that would take precedence.
`cdi40`=Contexts And Dependency Injection V4.0 Or Newer
`enableImplicitBeanArchives` = Enable scanning implicit bean archives.
`emptyBeansXMLExplicitArchive` = An Archive with an empty beans.xml file is considered to be an explicit bean archive.

This brings the downsides of Options 2 & 3 but without any additional upsides.

**Comment by tevans78** [comment]
Agreed that option 3 was the correct choice. Do not want to continue propagating the previous design choice. Documentation will be very important. Displaying an error message at runtime is also strongly desired should there be a conflict between the two configuration elements. This may present some implementation challenges but there are some options available.

**Comment by Emily-Jiang** [comment]
I could not join the call but I don't think the option 3 is the right choice as it's not self explainatory but rely on documentations. It also adds complication when using together with the old metatype. The option 2 makes more sense as they are self explainatory and the metatype element name means from which version onwards. There is no overlapping with other metatype.

**Comment by NottyCode** [comment]
@Emily-Jiang my issue with any of the options that involve the version number is that for people using CDI 2.0 or 3.0 it isn't obvious that the cdi12 element has relevant configuration for them when it does. The same will happen with cdi40 when we have a new release of cdi, 4.x or 5.0, it won't be clear that the cdiNN configuration option will be relevant. We don't create new cdi config elements for each new release, and I'd be very much against doing that. 

I understand the concern around people needing docs to know about these, but given the names for these I don't think I would ever set them without reference to documentation because I have zero idea what either of them do based on the names. As a result I'd likely be setting them because I read some example, or because I looked at the docs where it would tell you both what it does and what versions it is applicable to.

**Comment by Emily-Jiang** [comment]
well, comparing both 2 and 3, if you think doc is needed for both options, so be it. At least, for option 2, there won't be any clashes and override concern while option 3 has. Also with the number in the name, it will reflect which spec version introduces the behaviour change so that you can refer to the right spec for more info. Having that said, if most people prefer option 3, I will go with the flow.

**Comment by tevans78** [comment]
Initial impl completed, closing this design issue
