### ISSUE TITLE
jsonpContainer-2.0 and jsonbContainer-2.0 features incorrectly use default providers.

### ISSUE THREAD

**Issue by nmittles** [OpenLiberty/open-liberty#20165]
The jsonpContainer-2.0 and jsonbContainer-2.0 features incorrectly use default providers. Instead, these features should allow for the plugging in of third party JSON-P and JSON-B provider implementations.

**Comment by mbroz2** [comment]
@nmittles  All `release bug` issues must use the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=) in the description/first comment.
