### ISSUE TITLE
Social Login FAT updates for 18105 (OIDC Back-Channel Logout)

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#20169]
Update to the Social client FAT test projects for logout.
Test invalid request content, mismatch sid values, stopped servers, stopped and restarted servers, ...
https://github.com/OpenLiberty/open-liberty/issues/20044

**Comment by ayoho** [comment]
The bulk of the relevant tests have already been delivered, so I'm closing this as resolved.
