### ISSUE TITLE
BETA BLOG - Distributed Security Caches

### ISSUE THREAD

**Issue by jvanhill** [OpenLiberty/open-liberty#20209]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty. For this post to be included in the beta issue please make sure that this is completed by the end of Friday following the GM (Wednesday). 

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name (eg WebSockets feature): 
    - `Application Security 1.0`
    - `Application Security 2.0`
    - `Application Security 3.0`
    - `Application Security 4.0 (Jakarta Security 2.0)`
    - `Distributed Security Cache Support 1.0`
    - `JCache Session Persistence 1.0`
   
   Short feature name (eg websockets-1.0): 
    - `appSecurity-1.0`
    - `appSecurity-2.0`
    - `appSecurity-3.0`
    - `appSecurity-4.0`
    - `distributedSecurityCache-1.0`
    - `sessionCache-1.0`

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations. 
 
    - `application developer`

3. Write a paragraph to summarises the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.
   
 > Distributed security cache support has been introduced so that multiple Liberty servers can share caches via a JCache provider.

   - What was the problem before and how does your update make their life better? (Why should they care?)

> Prior to this feature, the authentication (subject) and logged out cookie caches were restricted to be local and in-memory. Multiple servers were unable to benefit from their peers' caches and each server started with a cold cache.
>
> As part of this feature both caches can now both be stored in a distributed JCache. This can improve performance and failure recovery, reduce the load on backend user registries and improve the security posture of the server.
   
   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.

> NOTE: When using the new distribute caching functionality in this beta release, the feature `distributedSecurityCache-1.0` needs to be included in the list of features in the server.xml file. This beta-only feature that is used to expose the JCache APIs to the 3rd party JCache provider. When the distributed caching functionality is GA'd, this feature will no longer be available.

```
========================================================================
Configuring a Distributed Authentication Cache
========================================================================
```

> Because the creation of a subject might affect performance, Liberty provides an authentication cache to store a subject after an authentication of a user is successful. The authentication cache now can be distributed using a 3rd party JCache provider. To configure the distributed authentication cache, use the following server.xml configuration:

```
    <featureManager>
        <feature>appSecurity-3.0</feature>
        <feature>distributedSecurityCache-1.0</feature>
    </featureManager>

    <!-- 
        The 3rd-party JCache provider library that Liberty will use to manage and connect to the cache.
     -->
    <library id="JCacheProviderLib">
        <fileset dir="${shared.resource.dir}" includes="jcacheprovider.jar" />
    </library>

    <!-- 
        Configure the JCache cache instance.
     -->
    <cache id="AuthCache" name="AuthCache">
        <cacheManager uri="uri://someuri">
            <properties prop1="value1" prop2="value2" />

            <cachingProvider libraryRef="JCacheProviderLib" />
        </cacheManager>
    </cache>

    <!-- 
        Configure the authentication cache.
     -->
    <authCache cacheRef="AuthCache" />
```

> If your Liberty environment injects custom principals or credentials into your subject (for instance in a custom LoginModule or Trust Association Interceptor (TAI)), in order to store them in the distributed authentication cache, they will need to be Serializable. Additionally, it is important that the shared library that contains those classes is made available to the caching provider and any other configurations that need access to those classes. If the same shared library is not used for each, ClassCastExceptions could be encountered when working with the classes retrieved from the distributed cache.

    <featureManager>
        <feature>appSecurity-3.0</feature>
        <feature>distributedSecurityCache-1.0</feature>
    </featureManager>

    
    <library id="JCacheProviderLib">
        <fileset dir="${shared.resource.dir}" includes="jcacheprovider.jar" />
    </library>

    
    <library id="CustomLib">
        <fileset dir="${shared.resource.dir}" includes="customlibrary.jar" />
    </library>

    
    <cache ... >
        <cacheManager ... >
            <cachingProvider libraryRef="JCacheProviderLib,CustomLib" />
        </cacheManager>
    </cache>

    
    <jaasLoginContextEntry id="system.WEB_INBOUND"
        name="system.WEB_INBOUND"
        loginModuleRef="custom, hashtable, userNameAndPassword, certificate, token" />

    <jaasLoginModule id="custom"
        className="org.acme.CustomLoginModule"
        controlFlag="REQUIRED" libraryRef="CustomLib" />

    
    <application ...>
        <classloader commonLibraryRef="CustomLib" />
    </application>

>A few points to consider when configuring a JCache cache for use with the authentication cache.
>- the distributed authentication cache is comprised of keys and values of type Object
>- to match the behavior of the local authentication cache, set a least recently used eviction (LRU) policy with a maximum entry count of 25000 and an entry TTL of 600 seconds. Note that with distributed caches, partitioning of the cache can lead to an actual capacity below the configured value. 
>- if your JCache provider supports it, configure a client-side cache to reduce transactions to the distributed cache. If the client-side cache supports storing the entries as deserialized objects, this can further improve performance.
>- support in the beta is currently limited to LTPA and JWT. Single sign-on methods such as SPNEGO, Oauth, OIDC and SAML (etc) are not yet supported
>- Subjects in the distributed cache should be treated as you would treat other security-sensitive information, such as usernames and passwords. Configure your JCache provider to secure the data while it is in motion and at rest. This should include encryption and access control.

```
========================================================================
Configuring a Distributed Logged-Out Cookie Cache
========================================================================
```
> The logged-out cookie cache stores LTPA and JWT cookies that have been logged-out. The logged-out cookie cache can now be distributed using a 3rd party JCache provider ensuring that logged out cookies are enforced across multiple servers. To configure the distributed logged-out cookie cache, use the following server.xml configuration:

```
    <featureManager>
        <feature>appSecurity-3.0</feature>
        <feature>distributedSecurityCache-1.0</feature>
    </featureManager>

    <!-- 
        The 3rd-party JCache provider library that Liberty will use to manage and connect to the cache.
     -->
    <library id="JCacheProviderLib">
        <fileset dir="${shared.resource.dir}" includes="jcacheprovider.jar" />
    </library>

    <!-- 
        Configure the JCache instances.
     -->
    <cache id="LoggedOutCookieCache" name="LoggedOutCookieCache">
        <cacheManager uri="uri://someuri">
            <properties prop1="value1" prop2="value2" />

            <cachingProvider libraryRef="JCacheProviderLib" />
        </cacheManager>
    </cache>

    <!-- 
        Configure the authentication cache to use the JCache. 
     -->
    <webAppSecurity loggedoutCookieCacheRef="LoggedOutCookieCache" />
```

>A few points to consider when configuring a JCache cache for use with the logged-out cookie cache.
>- the distributed logged-out cookie cache is comprised of keys and values of type Object
>- to match the behavior of the local logged-out cookie cache, configure the cache with a maximum entry count of 10000 and an entry TTL of unlimited. Note that with distributed caches, partitioning of the cache can lead to an actual capacity below the configured value. The cache capacity should be large enough that no cookies that have not expired will be evicted due to new logged out cookies being inserted into the cache.
>- if your JCache provider supports it, configure a client-side cache to reduce transactions to the distributed cache. If the client-side cache supports storing the entries as deserialized objects, this can further improve performance.

```
========================================================================
Configuring a Session Cache with the new Distributed Cache Configuration
========================================================================
```
> The sessionCache-1.0 feature has been updated to allow use of the new distributed cache configuration elements to allow common configuration across all features that use JCache. This eliminates the need to configure JCache separately for the session cache.

```
    <featureManager>
        <feature>distributedSecurityCache-1.0</feature>
        <feature>sessionCache-1.0</feature>
    </featureManager>

    <!-- 
        The 3rd-party JCache provider library that Liberty will use to manage and connect to the cache.
     -->
    <library id="JCacheProviderLib">
        <fileset dir="${shared.resource.dir}" includes="jcacheprovider.jar" />
    </library>

    <!-- 
        Configure the JCache cache manager.
     -->
    <cacheManager id="CacheManager" uri="uri://someuri">
        <properties prop1="value1" prop2="value2" />

        <cachingProvider libraryRef="JCacheProviderLib" />
    </cacheManager>

    <!--
        Configure the HTTP session cache.
     -->
    <httpSessionCache cacheManagerRef="CacheManager" ... />
```

```
========================================================================
Configuring Multiple Caches
========================================================================
```
> When configuring multiple distributed caches, instead of nesting the cacheManager configuration element within the cache element, the cache element needs to refer to the cache manager via the cacheRef attribute.

```
    <featureManager>
        <feature>appSecurity-3.0</feature>
        <feature>distributedSecurityCache-1.0</feature>
        <feature>sessionCache-1.0</feature>
    </featureManager>

    <!-- 
        The 3rd-party JCache provider library that Liberty will use to manage and connect to the cache.
     -->
    <library id="JCacheProviderLib">
        <fileset dir="${shared.resource.dir}" includes="jcacheprovider.jar" />
    </library>

    <!-- 
        Configure the JCache cache manager.
     -->
    <cacheManager id="CacheManager" uri="uri://someuri">
        <properties prop1="value1" prop2="value2" />

        <cachingProvider libraryRef="JCacheProviderLib" />
    </cacheManager>

    <!-- 
        Configure the JCache cache instances.
     -->
    <cache id="AuthCache" name="AuthCache" cacheManagerRef="CacheManager" />
    <cache id="LoggedOutCookieCache" name="LoggedOutCookieCache" cacheManagerRef="CacheManager" />

    <!-- 
        Configured the authentication cache, logged-out cookie cache and HTTP session cache.
     -->
    <authCache cacheRef="AuthCache" />
    <webAppSecurity loggedoutCookieCacheRef="LoggedOutCookieCache" ... />
    <httpSessionCache cacheManagerRef="CacheManager" ... />
```
   
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?

- https://www.ibm.com/docs/en/was-liberty/base?topic=liberty-configuring-authentication-cache-in
- https://www.ibm.com/docs/en/was-liberty/base?topic=manually-configuring-liberty-session-persistence-jcache

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by jvanhill** [comment]
We need to update the beta-blog to no longer have the `distributedSecurityCache-1.0` feature included, as it is no longer required.

**Comment by mbroz2** [comment]
For this issue, we'll likely just want to have a small entry in 22.0.0.10-beta post that focuses on the update, and then just links 22.0.0.4-beta for the deeper information.

If we have enough room in the 22.0.0.10-beta, then we can copy the content from 22.0.0.4-beta and just update the code snippets to drop the feature and drop the NOTE
