### ISSUE TITLE
401 instead of 403 returned with LibertyAuthFilter on restfulWS-3.0

### ISSUE THREAD

**Issue by schowave** [OpenLiberty/open-liberty#20205]
**Describe the bug**  
For authentication and authorization, we are currently setting a new security context in the "ContainerRequestContext". 
This is because we are validating against two Jwt Tokens and the build in mpjwt functionality is not working for us.

Everything worked fine with the  <feature>jaxrs-2.1</feature> feature, but when moving to the new <feature>restfulWS-3.0</feature> feature, we receive an 401 status code, where we actually would expect a 403 status code. It seems thtat the implementation of LibertyAuthFilter has changed a little from [jaxrs-2.1](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.jaxrs.2.1.common/src/com/ibm/ws/jaxrs20/security/LibertyAuthFilter.java) to [restfulWS-3.0](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.restfulWS30.appSecurity/src/io/openliberty/restfulWS30/appSecurity/LibertyAuthFilter.java). 
For the "200 Case" this is working very well, but if the User is not **authorized**, first the User from the SecurityContext is taken and although he/she is authenticated but not authorized, afterwards the user from the HttpServletRequest is checked for authentication and authorization as well. As we do not set the User in the HttpServletRequest, it is evaluated as Unauthenticated. 

In the jaxrs20 implementation the logic was working fine, but in the restfulWS30 implementation we get this unexpected behaviour.

**Steps to Reproduce**  
--

**Expected behavior**  
An unauthorized User (authenticated, but not authorized) should evaluate to 403 status code.

**Diagnostic information:**  
 - OpenLiberty Version: [22.0.0.2]
 - Affected feature(s) [restfulWS-3.0]
 - Java Version: [17.0.2+8_openj9-0.30.0]
 - server.xml configuration:
 `  <featureManager>
    <feature>persistence-3.0</feature>
    <feature>localConnector-1.0</feature>
    <feature>microProfile-5.0</feature>
    <feature>beanValidation-3.0</feature>
  </featureManager>`

Any help is appreciated!

**Comment by jim-krueger** [comment]
Hi @schowave I believe that this is the same problem that was reported under issue [12050](https://github.com/OpenLiberty/open-liberty/issues/12050).  Unfortunately the associated PR [19653](https://github.com/OpenLiberty/open-liberty/pull/19653/commits) is still in our "integration" level.  Please watch the commits for this PR and once they have gone to "release" you can try this again and I assume the issue will be resolved.  Thanks
