### ISSUE TITLE
Support JDK 18 in Open Liberty: Feature Test Summary

### ISSUE THREAD

**Issue by jgrassel** [OpenLiberty/open-liberty#20259]
## Test Strategy

Please note, this Feature Test Summary provided is used to claim https://github.com/OpenLiberty/open-liberty/issues/18614 and not to introduce any new or modified Open Liberty functionality.

Normally FAT testing is designed to validate the functionality of a new or changed feature in Open Liberty. Since there is no new OL functionality to test, the associated FAT test is just a validation check to make sure we are running on Java 18. To accomplish that, this FAT uses a WAR file for testing that has been compiled at Java 18 using functionality that is specific to Java 18.

The real testing validation for Java 18 is done via our entire suite of Open Liberty and WebSphere Liberty FAT buckets.

### List of FAT projects affected

* io.openliberty.java.internal_fat - https://github.com/OpenLiberty/open-liberty/pull/20012

### Test strategy

* What functionality is new or modified by this feature?
  * No new Liberty functionality is added or changed by this feature
* What are the positive and negative tests for that functionality? 
  * This FAT adds one simple test to ensure we are running on Java 18 by using functionality that is specific to Java 18.  It creates an inner class which extends `java.net.spi.InetAddressResolverProvider`, which is part of [JEP418](https://openjdk.java.net/jeps/418).  The test will fail with a `ClassNotFoundException` should an earlier JDK attempt to compile it.
* Testing specifics
  * For several weeks now, we have been running nightly (M-F) Java 18 builds using the latest [Java 18 OpenJDK Hotspot builds](https://jdk.java.net/18/) and tracking defects.  This build runs in lite mode against all the Open and WebSphere Liberty FATs.  We also periodically run a build against all the same FATs in full mode to make sure we discover any Java 17 specific defects.

## Confidence Level

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

**Comment by dave-waddling** [comment]
Hi, the testing described seems sufficient to me and has also been passing cleanly in the SOE. I'm happy to approve at this time.
