### ISSUE TITLE
Update autoStart attribute display name to be easier to translate. 

### ISSUE THREAD

**Issue by frowe** [OpenLiberty/open-liberty#2035]
In the file com.ibm.ws.jca/resources/OSGI-INF/l10n/metatype.properties, we just added properties for the new activation spec attribute (done under https://github.com/OpenLiberty/open-liberty/issues/319)
```
autoStart=Auto start
autoStart.desc=Configures whether the message endpoints associated with this activation 
```
specification start automatically or need to be manually started using the resume command. 
The attribute name is ambiguous for translation. Do we mean car or automatic? It probably should have been "Automatic Start" like app mgr:
```
appmgr.autoStart.name=Automatically start
appmgr.autoStart.desc=Indicates whether or not the server automatically starts the application.
```
Likewise the resourceAdapter config element needs to be updated from "Auto start" to "Automatically start"

**Comment by wraschke** [comment]
The LAOS continuous build at https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_6s01QAyuEeiTR7j3BTw-RQ shows the com.ibm.ws.cdi.2.0_fat test com.ibm.ws.cdi20.fat.tests.SecureAsyncEventsTest.testSecureAsyncObserverUsingRunAsWithAuthority failing with

junit.framework.AssertionFailedError: 2018-02-08-15:10:35:097 The response did not contain "[SUCCESS]".  Full output is:"
ERROR: Caught exception attempting to call test method testSecureAsyncObserverUsingRunAsWithAuthority on servlet secureAsyncEventsApp.web.SecureAsyncEventsServlet
java.util.concurrent.TimeoutException
<really long stack trace>

It fails all three times that the build runs it, so it's a hard break.

Given that the two personal builds for pull request 2043 show the test failure, and that the PR is included in the build, I reverted https://github.com/OpenLiberty/open-liberty/pull/2043. Done under https://github.com/OpenLiberty/open-liberty/pull/2093.
