### ISSUE TITLE
JakartaEE 10: Revert EJB 4.0 Schema and DD Parser Changes

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#20386]
A new version of the EJB specification will not be provided for Jakarta EE 10.  The EJB 4.0 must not be updated for EJB 10, as the spec has not been updated to support it.

The following PR updated the EJB 4.,0 schema to incorrectly reference a Jakarta EE 10 schema.  Also multiple EJB DD perser files were incorrectly updated to introduce a version 5.0; as well as tests, etc.

https://github.com/OpenLiberty/open-liberty/pull/20318

All of the changes for EJB 4.0 need to be reverted.  The EJB 4.0 schema should not support any new Jakarta EE 10 elements; that would require a new version of the EJB specification. This is consistent with EJB 3.2, which was not updated for Java EE 8.

**Comment by tevans78** [comment]
#regression
