### ISSUE TITLE
Investigate impact of using -Xshareclasses with checkpoint

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#20392]
Consideration is needed when using checkpoint with `-Xshareclasses`.  One theory is that `-Xshareclasses` helps with startup time when launching the server without checkpoint.  But with checkpoint we may already be past the point in startup where the share class cache would benefit the startup time when restoring a checkpoint liberty server process.

Initial investigations show that using `-Xshareclasses:none` for a server checkpoint do not seem to show a slow down in restoring a liberty server.  In theory this could help reduce the overall container size which contains a checkpoint server process image.  But this does not prove to be true.  It seems that an OpenJ9 process image using `-Xshareclasses` is significantly smaller than a process that has SCC disabled.  We theorize that a `criu` dump does not include any content loaded into memory from the memory mapped file containing the SCC.

We need to investigate if these observations are accurate.  If these observations prove to be true then the best option may be to simply have the liberty checkpoint process use the SCC just like a normal Liberty launch.

**Comment by tjwatson** [comment]
@dettmoney It would be good to get this confirmed.  Right now it appears that using an SCC in the container layers helps reduce the process image size and the overall container image size.  I would like that confirmed though.

**Comment by dettmoney** [comment]
I did an experiment with pingperf where I updated the populate_scc.sh, the ci.docker Dockerfile.ubi.openjdk17, and the jvm.options file used for my jvm with the -Xshareclasses:none property, replacing any existing shareclasses prop. There are four different images produced through the process, so I noted the image sizes for both the baseline and the shareclasses:none runs:

Baseline:131ms startup/232ms first request
Ubi (214MB)
1212 (1.59GB)
Rest-intro-application (1.62GB)
Rest-intro-checkpoint (1.73GB)

Shareclasses:none in populate_scc, Dockerfile, and jvm.options:256ms startup/276ms first request
Ubi (214MB)
1212 (1.52GB)
Application (1.52GB)
Checkpoint (1.67GB)

Three of the images are smaller without the scc, but there was a noticeable increase in startup time. Let me know if I've used the proper methodology for my test.

**Comment by tjwatson** [comment]
Can you also measure the size of the process image from the checkpoint.  That is under `workarea/checkpoint/image`, get the size of the complete directory content.  I assume it will be smaller when SCC is enabled given that the delta between applications to checkpoint is smaller when SCC is enabled vs when it is not enabled.  0.11GB vs 0.15GB about a 0.04GB difference or 40MB.

Furthermore, I assume it is this 40MB difference in the process image size that is increasing the `criu restore` time for startup for the non-scc case.

**Comment by tjwatson** [comment]
> Baseline:131ms startup/232ms first request

vs

> Shareclasses:none in populate_scc, Dockerfile, and jvm.options:256ms startup/276ms first request

It is curious that the delta from startup to first request is 101ms for the baseline (scc-enabled) vs 20ms Sharedclasses:none.  Is that accurate?  If so we need to figure out where that extra 80 ms is being spent for the baseline.  I really would expect the time between startup and first request to be nearly identical between the two.

On second thought I think the baseline should be slightly faster if the `configure.sh` script was run during the application container creation, where we populate the SCC for the application startup.  That should include storing classes in the SCC that are needed post restore before first request.

Can you also time the startup/first-request for running the base application image for both the ssc-enabled vs scc-disabled images?

**Comment by dettmoney** [comment]
The image directory in container with no scc was 139M. With scc enabled, it was 109M. I agree it is strange that the startup time increases so much with no scc, but the first request time is not as affected. I will look into it more.

**Comment by tjwatson** [comment]
> I agree it is strange that the startup time increases so much with no scc, but the first request time is not as affected. I will look into it more.

Baseline:131ms startup/232ms first request

Shareclasses:none in populate_scc, Dockerfile, and jvm.options:256ms startup/276ms first request

Maybe I am reading this incorrectly.  Is that time for first request in addition to the startup time?  So the overall time to first request for the Baseline is:

131(startup) + 232(first request) = 363 (overall)

And for no-scc:

256(startup) + 276(first request) = 532 (overall)

If that is the case then it makes more sense to me the numbers we see here.

**Comment by dettmoney** [comment]
Both the startup time and the first request time are the actual times, so for baseline, startup is 131ms. Total first request time is 232ms (not 363). Same for the no-scc run.

**Comment by tjwatson** [comment]
> Both the startup time and the first request time are the actual times, so for baseline, startup is 131ms. Total first request time is 232ms (not 363). Same for the no-scc run.

OK, then something really does need investigated.  I've no idea why the codepath between the two would cause the SCC-enabled case to take 80ms longer from startup to first-request vs the SCC-disabled case.  It sure would be nice if the total time to first-request for the SCC-enabled case was 131(startup) / 151(first request) where it only took 20 ms delta from the startup time.

**Comment by tjwatson** [comment]
No more work planned for this issue.  Closing.  We can open a new issue for other investigations.
