### ISSUE TITLE
CRIU: Support Non-persistent EJB Timers created during checkpoint

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#20402]
An application may be configured to automatically create EJB timers during deployment (both persistent and non-persistent). For CRIU, the EJB Container should be updated to determine when a checkpoint is occurring and defer the creation of automatic non-persistent timers until after restore, or reschedule the start time upon restore.

**Background**
EJB timers in general (including "non-persistent" timers) have interesting semantics around scheduling. Specifically, EJB timers are expected to schedule next timeout operations based on when an application creates the timer, rather than when the last timeout occurred.

For example, if an application creates a timer at exactly 3:00, which is scheduled to run every 5 minutes; then the next timeout is calculated from 3:00, and not just the last time it successfully ran. If at 3:30, the server is stopped, and then re-started an hour later at 4:30, then the next scheduled timeout is still 3:35 in the past.... so when the server re-starts, the timer will run 12 times immediately to catch up on all the missed expiration.

Therefore, when using CRIU, if an image of the server is captured today, which includes existing EJB timers (either persistent or non-persistent), then every time that image is used, the timers will run "catch-up" timeouts from the point the CRIU image was captured. The number of "catch-up" timeouts will increase over time. If the image is restarted an hour later, there will be 12 catch-up timeouts, after 2 hours, it would be 24 etc.

One option considered for CRIU for automatically created EJB timers would be to defer the creation of the timers until after restore. likely some type of hook or listener would need to be implemented to create the timers after restore. Unfortunately this solution would require considerable change effecting both the automatic and programmatic creation of timers and would not be compliant with the EJB specification regarding the transactional nature of timer creation.

**Solution**

The implemented solution is as follows:
1. Non-persistent timers (whether automatically created by the container or programmatically created during application start from a `@Startup @Singleton`) are created normally.
2. When any checkpoint phase is enabled, the execution of all above created non-persistent timers is paused until after restore.
3. On restore; the start time of each non-persistent timer is recalculated to ensure the first timeout is after the time of restore (to avoid timers running repeatedly for catch-up processing).
4. If the EJB Container is restarted for any reason after restore, non-persistent timer processing is as if checkpoint were not enabled.

**Note:** Persistent timers have additional considerations that will be addressed by #18778

**Comment by tjwatson** [comment]
@tkburroughs Is there more work needed on this one?

**Comment by tkburroughs** [comment]
@tjwatson The product code is complete; had not closed since I had not delivered testing.  As long as testing was included in the checkpoint FAT, then this is ready to close.

**Comment by tjwatson** [comment]
Tests are in checkpoint FATs.  I'm going to close this as done.
