### ISSUE TITLE
Servlet 6.0: Update Cookie class, related classes and the specification to remove references to RFC 2109 and to replace them with RFC 6265.

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20415]
Spec issue: `https://github.com/eclipse-ee4j/servlet-api/issues/37`

See "Appendix A: Change Log" here: https://github.com/eclipse-ee4j/servlet-api/blob/master/spec/src/main/asciidoc/servlet-spec-body.adoc

**Comment by pmd1nh** [comment]
Cookie class is the jakarta implemented class in the jakarta.servlet.http.

https://github.com/markt-asf/servlet-api/commit/d5dac4ac68e2dcae096ba3ca914e971885bde08b

https://github.com/jakartaee/servlet/blob/5650e7831609ad2b436d7582ef0a39785f317008/api/src/main/java/jakarta/servlet/http/Cookie.java

There is no work item for WC in this area.

Closed.
