### ISSUE TITLE
Servlet 6.0: Provide generic attribute support to cookies, including session cookies, to provide support for additional attributes such as the SameSite attribute.

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20417]
Spec issue: `https://github.com/eclipse-ee4j/servlet-api/issues/175`

See "Appendix A: Change Log" here: https://github.com/eclipse-ee4j/servlet-api/blob/master/spec/src/main/asciidoc/servlet-spec-body.adoc

API links:

Cookie: https://jakarta.ee/specifications/servlet/6.0/apidocs/jakarta.servlet/jakarta/servlet/http/cookie

HttpServletRequest.getCookies: https://jakarta.ee/specifications/servlet/6.0/apidocs/jakarta.servlet/jakarta/servlet/http/httpservletrequest

HttpServletResponse.addCookie: https://jakarta.ee/specifications/servlet/6.0/apidocs/jakarta.servlet/jakarta/servlet/http/httpservletresponse#addCookie(jakarta.servlet.http.Cookie)

**Comment by pmd1nh** [comment]
https://github.com/OpenLiberty/open-liberty/pull/22039

**Comment by pnicolucci** [comment]
@pmd1nh  some thoughts for additional tests. Let me know if you feel these are necessary:

1) error conditions for setAttribute
2) Do we have any tests for calling getAttribute on Cookie or SessionCookieConfig?
3) I know session has a precedence order, do you think we need some testing for these or are you confident you didn't change how these rules are handled?

> From Allan: highest -> lowest. i.e. the SessionCookieConfig programmatic configuration will override the web.xml, and the web.xml will override the server.xml.

https://www.ibm.com/support/pages/http-session-time-out-settings-and-overwrite-precedence-rules

Ans:
1. yes, there are tests to setAttribute after contextInitialized to cause IllegalStateException.  Also setAttribute with null and invalid name to cause IllegalArguementException.

2. there are  getAttribute tests to retrieve attributes that set from both specific getter and setAttribute.
3. SCI and XML tests are in place to test the precedence orders.

**Comment by pnicolucci** [comment]
Also review code delivered for Exceptions/Messages that need translation, for example: dev/io.openliberty.session.6.0.internal/src/io/openliberty/session/impl/SessionCookieConfigImpl60.java

**Comment by pmd1nh** [comment]
web.xml parser for new attribute element is included
