### ISSUE TITLE
Servlet 6.0: Correct the list of valid orderings for example 2 in Section 8.2.2, “Ordering of web.xml and web-fragment.xml”.

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20421]
Spec issue: `https://github.com/eclipse-ee4j/servlet-api/issues/365`

See "Appendix A: Change Log" here: https://github.com/eclipse-ee4j/servlet-api/blob/master/spec/src/main/asciidoc/servlet-spec-body.adoc

Per discussion, this was a clarification.  There was no functional change.  This issue will be used to add test cases as needed for the cases covered by the documentation update.

**Comment by pmd1nh** [comment]
Item for WCCM

**Comment by tbitonti** [comment]
The update is a textual correction to the specification document.  The ordering rules weren't actually changed.

That being said, this is a good case to test.

**Comment by tbitonti** [comment]
For notes on the example which is the subject of the clarification:
https://ibm.box.com/s/168cr04bw0qsz4kmz63uqlzctoq6f9lm

**Comment by pmd1nh** [comment]
@tbitonti is there any test added for this one, Tom?

**Comment by tbitonti** [comment]
### Issue 365

Correct the list of valid orderings for example 2 in Section 8.2.2, “Ordering of web.xml and web-fragment.xml”.

#### Example 2:

* Document *no id*:
```
<after>
  <others/>
</after>
<before>
  <name>C</name>
</before>
```

  * Document B:
```
<before>
  <others/>
</before>
```

  * Document C:
```
no ordering
```

  * Document D:
```
<after>
  <others/>
</after>
```

  * Document E:
```
<before>
  <others/>
</before>
```

  * Document F:
```
*no ordering*
```

* Previous documentation:
```
B, E, F, <no id>, C, D
B, E, F, <no id>, D, C
E, B, F, <no id>, C, D
E, B, F, <no id>, D, C
E, B, F, D, <no id>, C
B, E, F, D, <no id>, D
```

* Updated documentation:
```
B, E, F, <no id>, C, D
B, E, F, <no id>, D, C
E, B, F, <no id>, C, D
E, B, F, <no id>, D, C
E, B, F, D, <no id>, C
B, E, F, D, <no id>, C
```

**Comment by tbitonti** [comment]
Merged.
