### ISSUE TITLE
Servlet 6.0: Relax the requirements set out in Section 6.2.2, “Wrapping Requests and Responses” and allow the container to wrap Requests and Responses to meet the requirements of implementing the RequestDispatcher functionality.

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20427]
Spec issue: `https://github.com/eclipse-ee4j/servlet-api/issues/411`

See "Appendix A: Change Log" here: https://github.com/eclipse-ee4j/servlet-api/blob/master/spec/src/main/asciidoc/servlet-spec-body.adoc

**Comment by pmd1nh** [comment]
There is no work item for this issue.

1. Container itself does not use any wrap of request and response object before going through the filters/servlet.
2. Container has its own internal way to convey information from one resource to the next without the need to wrap request/response itself.
