### ISSUE TITLE
Servlet 6.0: Clarify the Javadoc for ServletRequest.isAsyncStarted() to align it with the specification text.

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20433]
See "Appendix A: Change Log" here: https://github.com/eclipse-ee4j/servlet-api/blob/master/spec/src/main/asciidoc/servlet-spec-body.adoc

`https://github.com/jakartaee/servlet/pull/450`

**Comment by pmd1nh** [comment]
There is mainly javadoc 's texture updating to align with servlet spec text.
Four tests in this isAsyncStarted are in com.ibm.ws.webcontainer_fat_IWAS/fat/src/com/ibm/ws/fat/lwas/AsyncServletTest.java.

No additional work for this.
