### ISSUE TITLE
Servlet 6.0: Add a new method getErrorOnELNotFound() to JspPropertyGroupDescriptor to align with changes in the Jakarta Pages 3.1 specification.

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20432]
See "Appendix A: Change Log" here: https://github.com/eclipse-ee4j/servlet-api/blob/master/spec/src/main/asciidoc/servlet-spec-body.adoc

**Comment by volosied** [comment]
getErrorOnELNotFound is added to the API: [jakarta.servlet.descriptor.JspPropertyGroupDescriptor;](https://jakarta.ee/specifications/servlet/6.0/apidocs/jakarta.servlet/jakarta/servlet/descriptor/jsppropertygroupdescriptor#getErrorOnELNotFound())

However, this method is used via Pages 3.1 in the PR linked directly above
