### ISSUE TITLE
Expression Language 5.0: Add support for coercing a LambdaExpression instance to a functional interface method invocation

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20449]
Spec issue: `https://github.com/jakartaee/expression-language/issues/45`

See "A.1. Changes between 5.0 and 4.0" here: https://github.com/jakartaee/expression-language/blob/master/spec/src/main/asciidoc/ELSpec.adoc

**Comment by pnicolucci** [comment]
There are a number of good TCK tests that were added for this functionality: https://github.com/eclipse-ee4j/jakartaee-tck/commit/7ca569bb50860e669ecce488ad95d89f9e9f8c3c 

All we need for this is a small FAT test to ensure that we can fail fast if we find an issue with Lambda Coercing.

**Comment by volosied** [comment]
In progress: working on a fat test
