### ISSUE TITLE
Using javax.persistence.AttributeConverter via @Converter annotation with JPA 2.2 feature

### ISSUE THREAD

**Issue by ljgp** [OpenLiberty/open-liberty#20461]
**Describe the use case that you want to enable:**
I want to annotate a field of type OffsetDateTime with a @Converter annotation in order for the system to convert it to/from an Oracle TimestampTz type database field.

**Describe why this is important to you:**
Because we might want to compare the time of a certain action with timestamps from other external systems.

**Diagnostic information:**
OpenLiberty 22.0.0.2, JPA 2.2, Jdbc driver ojdbc8 21.1.0.0

**Additional context**
The same functionality (conversion) is offered by Oracle extensions for JPA which are being mentioned in another feature request, https://github.com/OpenLiberty/open-liberty/issues/14894

Description of what I tried so far:

I am trying to use JPA 2.2 to map a record in an Oracle database containing a TIMESTAMPTZ field.

Directly mapping it to an OffsetDateTime (which I thought JPA 2.2 should support) yields an error:

```
[INFO] Caused by: Exception [EclipseLink-3002] (Eclipse Persistence Services - 2.7.10.v20211216-fe64cd39c3): org.eclipse.persistence.exceptions.ConversionException
[INFO] Exception Description: The object [oracle.sql.TIMESTAMPTZ@b53c6c57], of class [class oracle.sql.TIMESTAMPTZ], from mapping [org.eclipse.persistence.mappings.DirectToFieldMapping[dateDeletedRdd-->DOCUMENT_DELETE_
ACTION.rdddatedeleted]] with descriptor [RelationalDescriptor(nl.rotterdam.xyz.model.DocumentDeleteAction --> [DatabaseTable(DOCUMENT_DELETE_ACTION)])], could not be converted to [class java.time.OffsetDateTime
].
[INFO]  at org.eclipse.persistence.exceptions.ConversionException.couldNotBeConverted(ConversionException.java:81)
```

I added a converter annotation to do the conversion, see below. However, this causes a ClassCastException:

```
Caused by: java.lang.ClassCastException: oracle.sql.TIMESTAMPTZ incompatible with oracle.sql.TIMESTAMPTZ
[INFO]  at nl.rotterdam.xyz.model.helper.Timestamptz2ZonedDateTimeConverter.convertToEntityAttribute(Timestamptz2ZonedDateTimeConverter.java:11)
[INFO]  at org.eclipse.persistence.mappings.converters.ConverterClass.convertDataValueToObjectValue(ConverterClass.java:164)
[INFO]  ... 53 more
```

I did add the jdbc driver to the application classloader:

```
<application location="xyz-server.war" type="war" context-root="xyz">
    <classloader commonLibraryRef="jdbcLib"/>
 </application>
<dataSource id="xyzjpadatasource" jndiName="jdbc/xyzjpadatasource">
    <jdbcDriver libraryRef="jdbcLib" />
    <properties.oracle URL="jdbc:oracle:thin:@localhost:49161:xe" user="xyzusr" password="xyzpwd"/>
</dataSource>
```

as described in this issue:

https://github.com/OpenLiberty/open-liberty/issues/14894
EclipseLink Oracle Extension Support #14894 

I also tried I did using the JPA 2.2 feature as if it were an external feature, combined with the EclipseLink Oracle Extension jar 
(https://mvnrepository.com/artifact/org.eclipse.persistence/org.eclipse.persistence.oracle), but it resulted in exactly the same ClassCastException.
 
Questions:

1) Is this supposed to work ? If so, this would have to be a bugreport, since I am not sure I submitted it as a feature request.
2) Is there another way to use the Oracle TimestampTz field with JPA 2.2 in OpenLiberty ?

Code (edited for brevity):

```
@Entity
@Table(name = "DOCUMENT_DELETE_ACTION")
@Data
public class XyzAction extends AbstractXyzEntity {
    @Column(name = "actiontimestamp")
    @Convert(converter = Timestamptz2ZonedDateTimeConverter.class)
    private OffsetDateTime dateDeletedRdd;
}

import oracle.sql.TIMESTAMPTZ;

@Converter
public class Timestamptz2ZonedDateTimeConverter
        implements AttributeConverter<OffsetDateTime, TIMESTAMPTZ> {
    @Override
    public TIMESTAMPTZ convertToDatabaseColumn(OffsetDateTime offsetDateTime) {
        return TIMESTAMPTZ.of( offsetDateTime);
    }
    @Override
    public OffsetDateTime convertToEntityAttribute(TIMESTAMPTZ timestamptz) {
        return timestamptz.toOffsetDateTime();
    }
}
```

**Comment by jgrassel** [comment]
Curious about the ClassCastException, if the class is sourced from the same ClassLoader, I would expect compatibility.  Can you confirm that your application doesn't have an oracle jar bundled inside of it, that would be getting picked up by the application classloader (which would make it a "different class" even though it's the same bytecode)?

**Comment by ljgp** [comment]
Good question, will double check this.

**Comment by ljgp** [comment]
Why didn't I think of this myself ? Indeed, I used the wrong scope on the dependency for the jdbc driver in pom.xml, so it _was_ being included in the application. Changed it to scope provided and the conversion works !

Thanks a lot for your fast and polite response !

**Comment by ljgp** [comment]
Feature request closed because feature is present and works as expected, the problem was in my code.
