### ISSUE TITLE
MP Metrics with Micrometer prototype

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#20506]
Building from initial implementation from smallrye, build a MicroProfile Metrics implementation prototype that uses Micrometer for metrics.

- require a specific micrometer major/minor version that user provides in a shared lib (similar to what we had for zipkin/jaeger) so that Liberty doesn't ship it / support it directly
- use the micrometer prometheus meter registry
- create a meter binder for Liberty metrics (one per component, or one overall?)
- provide a /metrics endpoint
- apps should be able to add their metrics into same meter registry that Liberty uses
- data for all server metrics comes from monitor-1.0.  if monitor-1.0 filters out some metrics then our meter binder wouldn't get those metrics
- assume, at least to start, that there is only one app running on the server, or that all apps using the same metric names would share the metrics

**Comment by Channyboy** [comment]
Closing this issue as the main item to track would be https://github.com/OpenLiberty/open-liberty/issues/20018 now that the "prototype" has been merged.
