### ISSUE TITLE
JSP untranslated info messages

### ISSUE THREAD

**Issue by epj** [OpenLiberty/open-liberty#20538]
**Describe the bug**  
JSP can output untranslated messages like this:
Requested jdkSourceLevel=17, but forcing to 17 because it is the min supported by Java 12+
This particular message is redundant anyway since there is no level change.  So redundant messages should be removed, and where they aren't redundant either issue translated messages or move to trace or debug status.

**Steps to Reproduce**  
Run Liberty with a JDK at version 12 or higher and request jdkSourceLevels at or below 1.7 (specified as 17 on this option).

**Expected behavior**  
Messages should be in the correct category, or translated if general info messages.

**Comment by volosied** [comment]
Will close once #25494 is merged in.

**Comment by volosied** [comment]
Java 8 source is now the default.  

Messages will be translated: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.jsp/resources/com/ibm/ws/jsp/resources/messages.nlsprops#L1281-L1283
