### ISSUE TITLE
Update Gradle Wrapper to 7.4.1

### ISSUE THREAD

**Issue by KyleAure** [OpenLiberty/open-liberty#20549]
User Story: 
As a developer of Open Liberty, I need to be able to develop and test code locally to ensure regressions are not introduced based on the JDK version and JDK Vendor.  The next long term release of Java is Java 17 and the current Gradle wrapper version we are using (Gradle 6.8.3) does not support the following JDK version(s) and vendor(s)
- JDK 16
- JDK 17
- ADOPTIUM
- IBM_SEMERU

To support these versions and vendors we must upgrade the Gradle wrapper to 7.4.1.
Release Notes: https://docs.gradle.org/7.4.1/release-notes.html
Release Download: https://gradle.org/releases/
Compatibility Matrix: https://docs.gradle.org/current/userguide/compatibility.html
Upgrade Instructions: https://github.com/OpenLiberty/open-liberty/wiki/Updating-Gradle-and-Bnd-Version#updating-gradle

Current behavior when trying to use JDK 17 Adoptium:
```
running ./gradlew build.example.testcontainers_fat:buildandrun  -Dfat.test.mode=LITE

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wlp-bndPlugins:compileJava'.
> java.lang.IllegalAccessError: class org.gradle.internal.compiler.java.ClassNameCollector (in unnamed module @0x30f2d630) cannot access class com.sun.tools.javac.code.Symbol$TypeSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x30f2d630
```

**Comment by gjwatts** [comment]
@fritze2 Would you please review this issue and see if this is something we could work towards please?  We are not sure what all blockers there are in getting gradlew pushed up to 7.4.1.  We have been at 6.8.3 for a while now and according to [this chart](https://docs.gradle.org/current/userguide/compatibility.html), that only supports up to Java 15 (which is no longer supported).
With Java 16 the defaults changed for enforcing JPMS and now that Java 17 (LTS) has been around for a little while, it would be good to investigate getting gradle updated to work with the now enforced JPMS rules.

**Comment by wraschke** [comment]
This was completed around March 5.
