### ISSUE TITLE
Rendering of /openapi/ui page fails between OL 22.0.0.2 and 22.0.0.3.

### ISSUE THREAD

**Issue by dannemano** [OpenLiberty/open-liberty#20572]
OpenAPI GUI fails to render between version 22.0.0.2 and 22.0.03.

Using feature mpOpenAPI-1.1.

When navigating to /openapi/ui/ the OpenAPI UI is rendered correctly on 22.0.0.2.
When on 22.0.0.3 the render fails because resource:
openapi/ui/liberty-swagger-ui-d02953ea8a1cbb49e027.css 
is missing. (Error 404 is given)

**Steps to Reproduce**  
Use feature mpOpenAPI-1.1 and create a JAX-RS endpoint. Go to openapi/ui and it renders correctly.

Change Open Liberty version from 22.0.2 to 22.0.3 and the error is received.

**Expected behavior**  
Navigating to <server>/openapi/ui/ should render correctly.

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.3
 - Affected feature(s) mpOpenAPI-1.1
 - Java Version: Java 11.

**Comment by Emily-Jiang** [comment]
@dannemano thanks for reporting this! This is a known issue and [this](https://www.ibm.com/support/pages/ph44666openapi-ui-missing-css) ifix is available to fix this. Please follow the instruction provided by the ifix and patch the image.

**Comment by dannemano** [comment]
Thank you for the quick response!
