### ISSUE TITLE
WebSocket 2.1: Clarify that a zero or negative value disables the session idle timeout and improve the language used in the Javadoc for the other timeouts

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20587]
Spec issue: `https://github.com/jakartaee/websocket/issues/382`

See "A.1. Changes Between 2.1 and 2.0" here: https://github.com/jakartaee/websocket/blob/master/spec/src/main/asciidoc/WebSocket.adoc

**Comment by volosied** [comment]
Text:
```
Set the number of milliseconds before this session will be closed by the container if it is inactive, i.e. no
     * messages are either sent or received in that time. A value that is zero or negative indicates that this timeout
     * will not be used.
   ```
I think we are good here. Another no-op :) 

https://github.com/OpenLiberty/open-liberty/blob/4deecd59397e86ceb8c6d41efd74f7553dde2ae0/dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/SessionIdleTimeout.java#L42-L50

**Comment by volosied** [comment]
We are compliant and tests are added here: 
https://github.com/OpenLiberty/open-liberty/blob/7f5f98c197ab004b256e5a7b03502170168d7c33/dev/io.openliberty.wsoc.2.1.internal_fat/fat/src/io/openliberty/wsoc/tests/Basic21Test.java#L183-L201
