### ISSUE TITLE
WebSocket 2.1: Add a getter for the default platform configurator

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20582]
Spec issue: `https://github.com/jakartaee/websocket/issues/207`

See "A.1. Changes Between 2.1 and 2.0" here: https://github.com/jakartaee/websocket/blob/master/spec/src/main/asciidoc/WebSocket.adoc

**Comment by volosied** [comment]
This was changed within the API here: https://github.com/jakartaee/websocket/commit/398cb667ae6a4d340a22a1b3cfe4e5b0382424a9

Our IBM concrete class is found here: https://github.com/OpenLiberty/open-liberty/blob/2fd4a880754c37a988c5ed9ac4f1ea5988e465d6/dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/configurator/DefaultServerEndpointConfigurator.java 

The API issue mentioned `The access to the configurator is needed to be able to call @PreDestroy for CDI beans`, but I don't believe that's the case for us.

All in all, I think this is a no-op for us as the `DefaultServerEndpointConfigurator` is now available publicly via `getContainerDefaultConfigurator`.

**Comment by isaacrivriv** [comment]
I agree with @volosied here https://github.com/OpenLiberty/open-liberty/issues/20582#issuecomment-1119037013 this is a no-op for us. Verified manually that the public method can be accessed so we should be good to go here.

**Comment by isaacrivriv** [comment]
Reopened to add automated test for this
