### ISSUE TITLE
WebSocket 2.1: Added JPMS module descriptors that define the client module name as jakarta.websocket.client and the server module name as jakarta.websocket with the server module depending on the client module

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20589]
See "A.1. Changes Between 2.1 and 2.0" here: https://github.com/jakartaee/websocket/blob/master/spec/src/main/asciidoc/WebSocket.adoc

**Comment by volosied** [comment]
Discussing this in `#was-jakartaee`. I think this is another no-op for us since we don't need to include `module-info.class` in our liberty bundle API.  Will update this issue if anything changes.

**Comment by pnicolucci** [comment]
We are not planning to include the module-info in the API JARs for Open Liberty. The module-info was required for the Jakarta EE artifacts that were published but are not being enforced in signature tests etc.
