### ISSUE TITLE
WebSocket 2.1: Clarify the expected handling of user properties

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20586]
Spec issue: `https://github.com/jakartaee/websocket/issues/235`

See "A.1. Changes Between 2.1 and 2.0" here: https://github.com/jakartaee/websocket/blob/master/spec/src/main/asciidoc/WebSocket.adoc

**Comment by volosied** [comment]
Will need an implementation change. We pass in a empty object for each onOpen call. I believe the session should be shared between  ServerEndpointConfig.getUserProperties? I need to look this this more. 
 
https://github.com/OpenLiberty/open-liberty/blob/2fd4a880754c37a988c5ed9ac4f1ea5988e465d6/dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/SessionImpl.java#L140-L142

Attached tck test for this. (endpoint is localhost:9080/wsc_ee_jakarta_websocket_server_serverendpointconfig_web/programatic/userproperties) 

[wsc_ee_jakarta_websocket_server_serverendpointconfig_web.war.zip](https://github.com/OpenLiberty/open-liberty/files/8691321/wsc_ee_jakarta_websocket_server_serverendpointconfig_web.war.zip)

**Comment by volosied** [comment]
Arguments passed in likely need to be modified to have a _copy_ of the user properties.

https://github.com/OpenLiberty/open-liberty/blob/gm-22.0.0.6/dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/AnnotatedEndpoint.java#L185

Might be relevant later
https://github.com/OpenLiberty/open-liberty/blob/23749a21aae93d1f1441d0c207dbf39cacddd4be/dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/EndpointManager.java#L201-L207

_____

ServerEndpointConfig stored here: 
https://github.com/OpenLiberty/open-liberty/blob/4deecd59397e86ceb8c6d41efd74f7553dde2ae0/dev/com.ibm.ws.wsoc/src/com/ibm/ws/wsoc/EndpointManager.java#L36
