### ISSUE TITLE
WebSocket 2.1: Clarify the expected behaviour for Session.getRequestURI(). The full URI should be returned

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20585]
Spec issue: `https://github.com/jakartaee/websocket/issues/228`

See "A.1. Changes Between 2.1 and 2.0" here: https://github.com/jakartaee/websocket/blob/master/spec/src/main/asciidoc/WebSocket.adoc

**Comment by volosied** [comment]
This will require a code change.

Testing showed that `/basic/codedTextQueryParms` was returned.

https://github.com/OpenLiberty/open-liberty/blob/2fd4a880754c37a988c5ed9ac4f1ea5988e465d6/dev/io.openliberty.wsoc.internal_fat/test-applications/basic.war/src/basic/war/ProgrammaticServerEP.java#L694

Logging also showed the same: 
```
com.ibm.ws.wsoc.SessionImpl  < getRequestURI Exit  
/basic/codedTextQueryParms
```
                                                                                                               
                                                                                                               

We'll need to return the complete URI instead as stated here: https://github.com/jakartaee/websocket/commit/de291c2da257c1bdafb6a5b32e84ddf6ed6f8db3
