### ISSUE TITLE
Determine behavior when a server is packaged with a checkpoint image

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#20649]
Need to test what happens when a server containing a checkpoint image is packaged.

- Should we even package anything from the `workarea/checkpoint` folder when packaging a server?  Initially I think not.
- If the image is included is there any scenario that would lead to a successful restore?

**Comment by KeenanMcCarthy** [comment]
After testing checkpoint and restore with the checkpoint-1.0 feature, and packaging the server with the minify and runnable flags, it appears that the workarea directory in the archive file is empty. Therefore the checkpoint images are not present in the packaged server.
