### ISSUE TITLE
Servlet 60: Update to final API when available

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20642]

**Comment by pmd1nh** [comment]
Also reset the export to version 6.0.0 in **io.openliberty.jakarta.servlet.6.0/bnd.bnd** 

It is temporarily exporting servlet 6.0 API as version 5.0.0.  Reason: making it easier to not modify current EE9 dependencies which are used temporarily as the underline for EE10 until official APIs are available.

**Comment by pmd1nh** [comment]
https://github.com/OpenLiberty/open-liberty/pull/21535 has updated the official servlet API and also exported as 6.0

**Comment by pnicolucci** [comment]
All work for this issue is completed now since #21535 was merged.
