### ISSUE TITLE
Extra text found in description of connectionManager purgePolicy

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#20669]
**Describe the bug**  
Documentation for purgePolicy setting of connectionManager has been corrupted.

Prior to https://github.com/OpenLiberty/open-liberty/commit/e83f0f7b98acc21722a10a7294223d55ad228647 it was:

```
purgePolicy.desc=Specifies which connections to destroy when a stale connection is detected in a pool.
```

But after https://github.com/OpenLiberty/open-liberty/commit/e83f0f7b98acc21722a10a7294223d55ad228647 it now has a bunch of unrelated text:

```
purgePolicy.desc=Specifies which connections to destroy when a stale connection is detected in a pool. This setting can provide a major improvement on large multi-core (8+) machines by reserving the specified number of database connections for each thread.
Using thread local storage for connections can increase performance for applications on multi-threaded systems. When you set numConnectionsPerThreadLocal to 1 or more, these connections per thread are stored in thread local storage. When you use numConnectionsPerThreadLocal, consider two other values:
The number of application threads
The connection pool maximum connections
For best performance, if you have n applications threads, you must set the maximum pool connections to at least n times the value of the numConnectionsPerThreadLocal attribute and you must use the same credentials for all connection requests. For example, if you use 20 application threads, set the maximum pool connections to 20 or more; If you set the value of numConnectionPerThreadLocal attribute as 2 and there are 20 application threads, set the maximum pool connection to 40 or more.
```

We need to determine if this was the result of an errant merge, and if so, whether the additional text should have gone somewhere else.

**Steps to Reproduce** 
View generated documentation for connectionManager and scroll to purgePolicy setting,
https://openliberty.io/docs/22.0.0.3/reference/config/connectionManager.html

**Expected behavior**  
The purgePolicy setting should contain only its own description.

**Diagnostic information:**  
 - OpenLiberty Version: 21.0.0.5 - latest
 - Affected feature(s) jdbc-4.3, jdbc-4.2, jdbc-4.1, jdbc-4.0, connectors-2.0, jca-1.7, jca-1.6
 - Java Version: all

**Additional context**

**Comment by dmuelle** [comment]
Description was fixed and approved by @jmstephensgit, changes merged to integration  in #20680
