### ISSUE TITLE
Exceptions thrown from MDBs when stopping a server that is running a JMS messaging engine

### ISSUE THREAD

**Issue by sakerl** [OpenLiberty/open-liberty#20714]
When stopping a Liberty server that runs a JMS server, MDBs can generate FFDC incidents involving the JMS server not being accessible.
This appears to occur because, when the MDBs are begin closed, they internally attempt to close their JMS Connections, which are no longer value because the Messaging Engine has already quiesced.

**Comment by samwatibm** [comment]
@sakerl Can you confirm this is resolved by https://github.com/OpenLiberty/open-liberty/pull/20765 and associate the PR with this issue?  Should this be tagged as a release bug and closed for 22.0.0.5?  In which case this is semi-urgent as GM is tomorrow.  Thanks.
