### ISSUE TITLE
Pages 3.1: Deprecate methods that override ELResolver.getFeatureDescriptors() as that method has been deprecated as of EL 5.0.

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20734]
See "C.1. Changes between JSP 3.1 and JSP 3.0" here: https://github.com/eclipse-ee4j/jsp-api/blob/master/spec/src/main/asciidoc/ServerPages.adoc

**Comment by pnicolucci** [comment]
New deprecated methods:

1) https://github.com/jakartaee/pages/blob/5d66a05ad96ffb9e87fa4cbe13aa03968996949b/api/src/main/java/jakarta/servlet/jsp/el/ImplicitObjectELResolver.java
2) https://github.com/jakartaee/pages/blob/5d66a05ad96ffb9e87fa4cbe13aa03968996949b/api/src/main/java/jakarta/servlet/jsp/el/ScopedAttributeELResolver.java

**Comment by pnicolucci** [comment]
No action to take on this issue. The signature tests from the tck should test this.

**Comment by volosied** [comment]
This method is used in some parts of the code: 

https://github.com/OpenLiberty/open-liberty/blob/2fd4a880754c37a988c5ed9ac4f1ea5988e465d6/dev/com.ibm.ws.jsp.2.3/src/org/apache/jasper/el/ELResolverImpl.java#L122-L125


We will need to make updates when it is removed in the next Expression Language release.
