### ISSUE TITLE
Pages 3.1: Clarify the meaning of 'scope' in the context of scripting variables associated with custom actions.

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20736]
Spec issue: `https://github.com/eclipse-ee4j/jsp-api/issues/42`

See "C.1. Changes between JSP 3.1 and JSP 3.0" here: https://github.com/eclipse-ee4j/jsp-api/blob/master/spec/src/main/asciidoc/ServerPages.adoc

**Comment by isaacrivriv** [comment]
Following the changes in the issue, no functionality was added or changed for this. There were conflicting statements between javadocs and the specification and clarifications were made to clear it up and make it consistent by no behavior changes was introduced. We should be good to go here.

**Comment by volosied** [comment]
I agree with Isaac. 

Another thing to point out if anyone run into the problem reported  in Spec issue 42: 
```
note that users have full flexibility by setting declare=false for the scripting variables and explicitly declaring them as required
```

**Comment by pnicolucci** [comment]
@isaacrivriv I agree, I think you can close this one as a no-op!
