### ISSUE TITLE
Pages 3.1: Clarify that the EL environment within a JSP has a set of default imports consistent with the default imports for the scripting environment. Refactor the ScopedAttributeELResolver to remove the special handling for imports and unresolved variables.

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20737]
Spec issue: `https://github.com/eclipse-ee4j/jsp-api/issues/44`

See "C.1. Changes between JSP 3.1 and JSP 3.0" here: https://github.com/eclipse-ee4j/jsp-api/blob/master/spec/src/main/asciidoc/ServerPages.adoc

**Comment by pnicolucci** [comment]
@volosied anything left for this with the lastest set of of PR merges?

**Comment by volosied** [comment]
@pnicolucci  Looking a bit closer, I should verify the default imports match both for Expression Language and for scriptlets. 

But this can be followed up on at a later time.

**Comment by volosied** [comment]
We write the default packages here for EL: 
https://github.com/OpenLiberty/open-liberty/blob/b7cbd80cebbed98edb43050ed078a16ecdfbb815/dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/translator/visitor/generator/GenerateJspVisitor.java#L310-L313

Standard Imports are defined here:
https://github.com/OpenLiberty/open-liberty/blob/2fd4a880754c37a988c5ed9ac4f1ea5988e465d6/dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/Constants.java#L18-L22

However, we could organize the code to have the jakarta imports under the Constants class. We can follow up post GA.
