### ISSUE TITLE
Pages 3.1: Create jakarta.pages.3.1 bundle

### ISSUE THREAD

**Issue by pmd1nh** [OpenLiberty/open-liberty#20746]

**Comment by pmd1nh** [comment]
https://github.com/OpenLiberty/open-liberty/pull/20747

**Comment by pnicolucci** [comment]
This has been done already, nothing remaining to do.

**Comment by pnicolucci** [comment]
https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.jakarta/pages.3.1.bnd
