### ISSUE TITLE
Enable Pages-3.1 feature 

### ISSUE THREAD

**Issue by pmd1nh** [OpenLiberty/open-liberty#20751]
Currently, pages-3.1 feature is pointing to pages-3.0 bundle.  When ready, it needs to point to the new pages-3.1 bundle.

**Comment by pnicolucci** [comment]
This is done: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.websphere.appserver.features/visibility/public/pages-3.1/io.openliberty.pages-3.1.feature#L38 / https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.websphere.appserver.features/visibility/public/pages-3.1/io.openliberty.pages-3.1.feature#L42
