### ISSUE TITLE
Feature Test Summary for Issuer as Filter for OIDC 

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#20761]
## Test Strategy

The tests for this feature will include an OP, RP and RS.  The test will access apps on the RP which will use the OP to create an access_token.  The normal filtering is used to use the correct rp client/op to create the token.
The test will then use that access_token and invoke a protected app on the RS server.  The RS configs will not use auth_filters, but will rely on using the issuer within the access_token to choose the proper openidconnectclient to access the protected app.

All tests are contained in the standard FAT framework - there are no manual tests

### List of FAT projects affected

* com.ibm.ws.security.oidc.client_fat.jaxrs

### Test strategy

* The new function of this feature is filtering/choosing the openidconnectclient to use  to gain access to a protected resource by matching the issuer contained in an access_token to the issuer within the openidconnectclient config that supports/requires inboundPropagation.
(Some of the tests perform multiple sub-tests some positive and some negative - those tests are noted in both the positive and negative lists)

* Positive Tests

- * JaxRSClientIssuerClaimAsFilterTests_BasicTest - good end to end test (config with matching issuer found and the rest of the config validates the access_token)
- * JaxRSClientIssuerClaimAsFilterTests_BasicTestAnother - another good end to end test - shows that we'll select the proper config to handle the request
- * JaxRSClientIssuerClaimAsFilterTests_IssuerMatchesClientsDefaultIssuer - test that has a config that does not explicitly specify the issuer - shows that runtime will use the default issuer for that config to match the access_token presented to the RS server
- * JaxRSClientIssuerClaimAsFilterTests_MultipleClient_oneUsingFilter_oneUsingIssuerAsFilter - RS server config has mutliple clients that can consume the access_token.  One client uses an authFilter and a request to use an app that matches the authFilter, will use that config.  A request to use an app that does not match that filter uses the other openidconnectclient
- * JaxRSClientIssuerClaimAsFilterTests_FilterContentTypo_issuerMatches - the openidconnectclient specifies an authFilter, but there is a typo in the urlPattern of the filter - show that we'll still choose that config because the issuer match
- * JaxRSClientIssuerClaimAsFilterTests_FilterRefTypo_issuerMatches - the openidconnectclient specifies an authFilterRef that doesn't exist - show that we'll still choose that config because the issuer matches
- * JaxRSClientIssuerClaimAsFilterTests_NonDefaultIssuer - multiple things tested with this (some positive/some negative) - there are multiple clients using the same OP provider (and therefore the same issuer which is NOT the default) - some of the openidconnectclients have authFilters that match the app name, some don't, some have the correct issuer in the config others don't
- * JaxRSClientIssuerClaimAsFilterTests_oidcAuthnHintAndOidcClientVariations_noAuthFilter_defaultIssuerMatches - multiple things tested with this (some positive/some negative) - the openidconnectclient does not specify an authFilterRef, and the default issuer matches what's in the token - tests behavior with either oidcAuthnHint or oidc_client in the header - when the hint parms match the client, the tests should expect success 
- * JaxRSClientIssuerClaimAsFilterTests_oidcAuthnHintAndOidcClientVariations_noAuthFilter_specifiedIssuerMatches - multiple things tested with this (some positive/some negative) - the openidconnectclient does not specify an authFilterRef, and the specific issuer matches what's in the token - tests behavior with either oidcAuthnHint or oidc_client in the header - when the hint parms match the client, the tests should expect success 
- * JaxRSClientIssuerClaimAsFilterTests_oidcAuthnHintAndOidcClientVariations_authFilterMatches_defaultIssuerMatches - multiple things tested with this (some positive/some negative) - the openidconnectclient specifies an authFilterRef, and the default issuer matches what's in the token - tests behavior with either oidcAuthnHint or oidc_client in the header - when the hint parms match the client, the tests should expect success 
- * JaxRSClientIssuerClaimAsFilterTests_oidcAuthnHintAndOidcClientVariations_authFilterMatches_specifiedIssuerMatches - multiple things tested with this (some positive/some negative) - the openidconnectclient specifies an authFilterRef, and the specific issuer matches what's in the token - tests behavior with either oidcAuthnHint or oidc_client in the header - when the hint parms match the client, the tests should expect success 

* Negative Tests

- * JaxRSClientIssuerClaimAsFilterTests_BasicTestAnotherButSigAlgMismatch - issuer matches client config - there is a signature algorithm mismatch between the openidconnectclient and the access_token
- * JaxRSClientIssuerClaimAsFilterTests_NoClientMatchesIssuerOrFilter - the issuer in the access_token does not match the issuer in any of the clients.  We should receive a 401 status and error messages in the server log indicating that the issuer is not trusted
- * JaxRSClientIssuerClaimAsFilterTests_NonDefaultIssuer - multiple things tested with this - there are multiple clients using the same OP provider (and therefore the same issuer which is NOT the default) - some of the openidconnectclients have authFilters that match the app name, some don't, some have the correct issuer in the config others don't
- * JaxRSClientIssuerClaimAsFilterTests_oidcAuthnHintAndOidcClientVariations_noAuthFilter_defaultIssuerMatches - multiple things tested with this (some positive/some negative) - the openidconnectclient does not specify an authFilterRef, and the default issuer matches what's in the token - tests behavior with either oidcAuthnHint or oidc_client in the header - when the hint parms do not match the client, the tests should expect a failure 
- JaxRSClientIssuerClaimAsFilterTests_oidcAuthnHintAndOidcClientVariations_noAuthFilter_defaultIssuerDoesNotMatch - multiple things tested with this - the openidconnectclient does not specify an authFilterRef, and the default issuer does not match what's in the token - tests behavior with either oidcAuthnHint or oidc_client in the header - when the hint parms do not match the client, the tests should expect a hint failure, otherwise expect issuer mismatch failure
- * JaxRSClientIssuerClaimAsFilterTests_oidcAuthnHintAndOidcClientVariations_noAuthFilter_specifiedIssuerMatches - multiple things tested with this (some positive/some negative) - the openidconnectclient does not specify an authFilterRef, and the specific issuer matches what's in the token - tests behavior with either oidcAuthnHint or oidc_client in the header - when the hint parms do not match the client, the tests should expect a failure 
- * JaxRSClientIssuerClaimAsFilterTests_oidcAuthnHintAndOidcClientVariations_noAuthFilter_specifiedIssuerDoesNotMatch - multiple things tested with this - the openidconnectclient does not specify an authFilterRef, and the specific issuer does not match what's in the token - tests behavior with either oidcAuthnHint or oidc_client in the header - when the hint parms do not match the client, the tests should expect a hint failure, otherwise expect issuer mismatch failure
- * JaxRSClientIssuerClaimAsFilterTests_oidcAuthnHintAndOidcClientVariations_authFilterMatches_defaultIssuerMatches - multiple things tested with this (some positive/some negative) - the openidconnectclient specifies an authFilterRef, and the default issuer matches what's in the token - tests behavior with either oidcAuthnHint or oidc_client in the header - when the hint parms do not match the client, the tests should expect a failure 
- * JaxRSClientIssuerClaimAsFilterTests_oidcAuthnHintAndOidcClientVariations_authFilterMatches_defaultIssuerDoesNotMatch - multiple things tested with this - the openidconnectclient specifies an authFilterRef, and the default issuer does not match what's in the token - tests behavior with either oidcAuthnHint or oidc_client in the header - when the hint parms do not match the client, the tests should expect a hint failure, otherwise expect issuer mismatch failure
- * JaxRSClientIssuerClaimAsFilterTests_oidcAuthnHintAndOidcClientVariations_authFilterMatches_specifiedIssuerMatches - multiple things tested with this (some positive/some negative) - the openidconnectclient specifies an authFilterRef, and the specific issuer matches what's in the token - tests behavior with either oidcAuthnHint or oidc_client in the header - when the hint parms do not match the client, the tests should expect a failure 
- * JaxRSClientIssuerClaimAsFilterTests_oidcAuthnHintAndOidcClientVariations_authFilterMatches_specifiedIssuerDoesNotMatch - multiple things tested with this - the openidconnectclient specifies an authFilterRef, and the specific issuer does not match what's in the token - tests behavior with either oidcAuthnHint or oidc_client in the header - when the hint parms do not match the client, the tests should expect a hint failure, otherwise expect issuer mismatch failure
- * JaxRSClientIssuerClaimAsFilterTests_OpaqueToken_NoFilter - the openidconnectclient does not specify an authFilterRef - the OP creates an opaque token - show that we will not get to the protected app upon request and that the log will contain "selectNonFiltered" to show that we're not trying to filter based on the issuer (which we won't be able to find the issuer in the opaque token).
- * JaxRSClientIssuerClaimAsFilterTests_JWEToken_NoFilter - the openidconnectclient does not specify an authFilterRef - the "OP" creates an JWE token - show that we will not get to the protected app upon request and that the log will contain "selectNonFiltered" to show that we're not trying to filter based on the issuer (which we won't be able to find issuer in the JWE token).

## Confidence Level

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

**Comment by c00crane** [comment]
#20168

**Comment by c00crane** [comment]
Tests delivered via: https://github.com/OpenLiberty/open-liberty/pull/20956

**Comment by ayoho** [comment]
LGTM 👍
