### ISSUE TITLE
Port  MYFACES-4431 to JSF (Custom Navigation Handler Thows NPE during Flow Handling) 

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#20762]
**Describe the bug**  
When entering a flow while using a custom navigation handler, the following NPE may occur:

```java.lang.NullPointerException   org.apache.myfaces.application.NavigationHandlerImpl.getNavigationCaseFromFlowStructure(NavigationHandlerImpl.java:958) org.apache.myfaces.application.NavigationHandlerImpl.getNavigationCommand(NavigationHandlerImpl.java:773) org.apache.myfaces.application.NavigationHandlerImpl.handleNavigation(NavigationHandlerImpl.java:133) org.apache.myfaces.application.NavigationHandlerImpl.handleNavigation(NavigationHandlerImpl.java:121) org.primefaces.application.DialogNavigationHandler.handleNavigation(DialogNavigationHandler.java:113) org.apache.myfaces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:140) org.primefaces.application.DialogActionListener.processAction(DialogActionListener.java:54) javax.faces.component.UICommand.broadcast(UICommand.java:120) javax.faces.component.UIViewRoot._broadcastAll(UIViewRoot.java:1255) javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:420) javax.faces.component.UIViewRoot._process(UIViewRoot.java:1741) javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:935) org.apache.myfaces.lifecycle.InvokeApplicationExecutor.execute(InvokeApplicationExecutor.java:42) org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:195) org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:142) javax.faces.webapp.FacesServlet.service(FacesServlet.java:204)```

**Steps to Reproduce**  
Steps to reproduce the bug

1) 	 Use a custom navigation-handler within the faces-config.xml of a JSF enabled application.  For example: 
```
	<application>
		<navigation-handler>org.primefaces.application.DialogNavigationHandler</navigation-handler>
	</application>
```

2) Send a request to enter into a JSF flow. 

The server will encounter a NPE during the request handling. 

**Expected behavior**  
No null pointer exceptions should occur here. 

**Diagnostic information:**  
 - OpenLiberty Version: All versions prior 22.0.0.5
 - Affected feature(s) jsf-2.2, jsf-2.3, faces-3.0
 - Java Version: N/A

**Additional context**  
Open Source Issue can be found here: https://issues.apache.org/jira/browse/MYFACES-4431

**Comment by pnicolucci** [comment]
@volosied please mark this a `release bug` and use the [bug report template.](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
