### ISSUE TITLE
Jakarta Tags 3.0: Rename Tag URIs to 'jakarta.tags.*'

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20779]
Spec issue: `https://github.com/eclipse-ee4j/jstl-api/issues/144`

See "B.1. Changed between Jakarta Standard Tag Library 2.0 and Jakarta Standard Tag Library 3.0" here: https://github.com/eclipse-ee4j/jstl-api/blob/master/spec/src/main/asciidoc/jakarta-stl.adoc

**Comment by volosied** [comment]
Test application use new URIs here: https://github.com/OpenLiberty/open-liberty/tree/2e67c73e92be1203e465beccc4b15705830f0059/dev/io.openliberty.pages.3.1.internal_fat/test-applications/TestTagsEE10.war/resources
