### ISSUE TITLE
LG-327: Open Liberty Operator Monitoring guide update for OCP 4.10

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#20789]
Need to retest the OLO Monitoring guide at https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/openshift-monitoring.adoc and check against OpenShift docs to look for any required updates.

**Comment by ellen-lau** [comment]
Changes were made with this PR: https://github.com/OpenLiberty/open-liberty-operator/pull/342
