### ISSUE TITLE
Review WebConfigParamsLogger for untranslated messages and correct log level

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20794]
https://issues.apache.org/jira/browse/MYFACES-4561

This issue should work to address the following for Jakarta Faces 4.0:

1) Review WebConfigParamsLogger for untranslated messages and work to get them translated.
2) Review WebConfigParamsLogger to determine if any of the messages can be moved to DEBUG vs INFO messages. We need to consider this, especially if for some reason we can't get these messages translated.
3) Determine if any of this work should be backported to `faces-3.0`, `jsf-2.3` or `jsf-2.2` in Open Liberty

**Comment by tevans78** [comment]
I think that all of the messages which start `No context init parameter` should be debug.
e.g. https://github.com/OpenLiberty/open-liberty/blob/c98166231afa4e8d2de14c9e2e85bf760451688c/dev/com.ibm.ws.jsf.2.2/src/org/apache/myfaces/webapp/WebConfigParamsLogger.java#L96
There are 138 others!

**Comment by volosied** [comment]
In progress here:  https://issues.apache.org/jira/browse/MYFACES-4561

I created a PR and, if it's approved, we can ask the community to backport it.

**Comment by volosied** [comment]
This will be pulled in via https://github.com/OpenLiberty/open-liberty/pull/24370 

Once it's merged, the "No context init parameter" will no longer be logged by default.

**Comment by pnicolucci** [comment]
> This will be pulled in via #24370
> 
> Once it's merged, the "No context init parameter" will no longer be logged by default.

To clarify the change is for MyFaces 4.0 +

**Comment by pnicolucci** [comment]
This is now included in OL with the delivery of RC5. I'll close this issue and open a new one to look at our older features to see if there is anything we can do.
