### ISSUE TITLE
Faces 4.0: Faces 4.0: OutputScript/OutputStyleSheet Remove 'type' attribute if HTML5

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20813]
User Story:
As a user of Open Liberty and the Faces 4.0 feature, I want to be able to user outputScript and outputStylesheet in HMTL 5 without warnings related to default 'type' attributes.

Previously the default renders of <h:outputStylesheet> and <h:outputScript> wrote out the 'type' attribute when rendering the <script> and <link> tags. On HTML 5 this resulted in a warning being emitted, as the generated 'type' was also the default 'type'.

Spec issue: `https://github.com/jakartaee/faces/issues/1565`

See: https://balusc.omnifaces.org/2021/11/whats-new-in-faces-40.html#skipResourceType

**Comment by nmittles** [comment]
Resolved by PR #24149
