### ISSUE TITLE
Faces 4.0: rename "jsf" throughout source code to "faces"

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20816]
Spec issue: `https://github.com/jakartaee/faces/issues/1552`

See: https://balusc.omnifaces.org/2021/11/whats-new-in-faces-40.html

**Comment by volosied** [comment]
All renames were done upstream. As for our tests, we did it on a case by case basis (code was split into faces40 folder and (jsf22,jsf23) )
