### ISSUE TITLE
Faces 4.0: add <f:websocket onerror>

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20836]
User Story:
As a user of Open Liberty and the Faces 4.0 feature, I want to be able to trigger immediate feedback that a websocket connection has gone lost.

The new onerror websocket attribute fills this role:
`<f:websocket channel="push" onerror="errorListener" onclose="closeListener" />`

See: https://balusc.omnifaces.org/2021/11/whats-new-in-faces-40.html#websocketOnerror

**Comment by nmittles** [comment]
Resolved by PR  #24126
