### ISSUE TITLE
Faces 4.0: First class support for creating views in Java

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#20846]
User Story:
As a user of Open Liberty and the Faces 4.0 feature, I want to be able to create facelet views completely in Java without the use of a facelet file (xhmtl).

This is accomplished by declaring an @View annotation on a JSF Facelet . The @View support class, method, and fields.

Spec issue: `https://github.com/jakartaee/faces/issues/1581`

See: https://balusc.omnifaces.org/2021/11/whats-new-in-faces-40.html

**Comment by nmittles** [comment]
Resolved by 24121.
