### ISSUE TITLE
create blog about how OL and WAS work with OpenTelemetry agent

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#20853]
Open Telemetry agent can be used with WAS and Liberty

- what works and what doesn't when people try that?  
- what's missing that people might want?

**Comment by fmhwong** [comment]
Blog post is at https://ibm.ent.box.com/notes/1073067711514

**Comment by fmhwong** [comment]
Published at https://community.ibm.com/community/user/wasdevops/blogs/felix-wong/2023/04/04/distributed-tracing-with-opentelemetry-automatic-i

**Comment by fmhwong** [comment]
It has been decided that the OL part is not needed.
