### ISSUE TITLE
Tracking disabled tests for repeat on EE10_FEATURES

### ISSUE THREAD

**Issue by pmd1nh** [OpenLiberty/open-liberty#20854]
Tests are added with @SkipForRepeat(EE10_FEATURES).  They do not work due to changed/deprecated/removed API.
They will be reactivate once EE10 is ready.

Most of these tests are related to session area (or JSP which also triggers session path)
(java.lang.NoClassDefFoundError: jakarta.servlet.http.HttpSessionContext which is removed)

FAT 4.0:
1. WCAddJspFileTest <Updated 6/23 re-enabled via 21076>
2. WCSameSiteCookieAttributeTests  <Updated 6/23 re-enabled via 21076>
3. WCSameSiteCookieAttributeSecurityTest  <Updated 6/23 re-enabled via 21076>
4. WCServerTest      //This test needs to be updated since its reponse looking for HttpSessionImpl which not return anymore
5. WC5JakartaServletTest  <Updated 6/23 re-enabled via 21076>
6. WCSendRedirectRelativeURLTrue  <Updated 6/23 re-enabled via 21076>
7. WCSendRedirectRelativeURLDefault  <Updated 6/23 re-enabled via 21076>
8. WC5GetContextPath  <Updated 6/23 re-enabled via 21076>
9. WCSCIHandlesTypesTest  <Updated 6/23 re-enabled via 21076>
10. WCResponseHeadersTest <Updated 6/23 re-enabled via 21076>
11. WCServerPropertyTest <Updated 6/23 re-enabled via 21076>

FAT 3.1:
1. WCServerHttpUnit (3 tests) <Updated 6/23 re-enabled via 21076>
2. HttpSessionAttListenerHttpUnit <Updated 6/23 re-enabled via 21076>
3. JSPServerHttpUnit <Updated 6/23 re-enabled via 21076>
4. WCServerTest <Updated 6/23 re-enabled via 21076>
5. com.ibm.ws.webcontainer.servlet31.fat.tests.CDIListenersTest <Updated 6/23 re-enabled via 21076>
6. com.ibm.ws.webcontainer.servlet31.fat.tests.CDIServletFilterListenerDynamicTest <Updated 6/23 re-enabled via 21076>
7. com.ibm.ws.webcontainer.servlet31.fat.tests.CDIServletFilterListenerTest <Updated 6/23 re-enabled via 21076>
8. com.ibm.ws.webcontainer.servlet31.fat.tests.CDIServletInterceptorTest <Updated 6/23 re-enabled via 21076>
9. FormLoginReadListenerTest (FULL mode)

Concurrent_FAT:
1. test.jakarta.concurrency.ConcurrencyJSPTest (5 tests) //disable in FATSuite as this test was created for EE10 so cannot use SkipForRepeat
(Note: 	
"com.ibm.ws.concurrent_fat_jakarta FAT tests" is the Name.  These are written for EE10 so there is No Repeat action. (i.e you won't see EE10_FEATURES subfix)

<Updated 6/23 re-enabled via 21076>

CDI: (run under Full mode)
1. com.ibm.ws.cdi.api.fat.tests.CDIAPITests
3. com.ibm.ws.cdi.jee.jsf.SimpleJSFTest
4. com.ibm.ws.cdi.jee.jsf.SimpleJSFWithSharedLibTest
5. com.ibm.ws.cdi.ejb.tests.StatefulSessionBeanInjectionTest
6. com.ibm.ws.cdi.jee.jsp.SimpleJSPTest

**Comment by pmd1nh** [comment]
Issue for disable tests
https://github.com/OpenLiberty/open-liberty/issues/20869

**Comment by pmd1nh** [comment]
Most of the tests were re-enabled in 21076.  Remaining tests that need to be re-enable:

FAT4:
WCServerTest //This test needs to be updated since its reponse looking for HttpSessionImpl which not return anymore
Completed here: https://github.com/OpenLiberty/open-liberty/pull/21631

FAT3: (re-enabled in #21696  )
FormLoginReadListenerTest (FULL mode)

CDI: (run under Full mode) (July 11 completed in #21696  )

    com.ibm.ws.cdi.api.fat.tests.CDIAPITests
    com.ibm.ws.cdi.jee.jsf.SimpleJSFTest
    com.ibm.ws.cdi.jee.jsf.SimpleJSFWithSharedLibTest
    com.ibm.ws.cdi.ejb.tests.StatefulSessionBeanInjectionTest
    com.ibm.ws.cdi.jee.jsp.SimpleJSPTest

**Comment by jonhawkes** [comment]
There are tests with this problem in transactions. The first bunch I found are in com.ibm.ws.transaction.core_fat.cdi (being added in  https://github.com/OpenLiberty/open-liberty/pull/21624). The SkipForRepeats are in TransactionalTestServlet.java.

**Comment by pnicolucci** [comment]
@jonhawkes what is the issue you're seeing? Do you require a specific Servlet 6.0 feature to enable these tests for EE 10? Is there an existing Servlet 6.0 error that required you to disabled these tests?

**Comment by tevans78** [comment]
@pnicolucci This is the first time that the transactions FAT buckets have been repeated against EE10. Here is the top part of the stack that Jon showed me.
```
[02/07/2022, 23:04:17:770 BST] 00000036 SystemErr     R   java.lang.NoClassDefFoundError: jakarta.servlet.http.HttpSessionContext
[02/07/2022, 23:04:17:771 BST] 00000036 SystemErr     R   	at [com.ibm.ws](http://com.ibm.ws/).webcontainer.session.impl.HttpSessionContextImpl.createSessionObject(HttpSessionContextImpl.java:952)
[02/07/2022, 23:04:17:795 BST] 00000036 SystemErr     R   	at [com.ibm.ws](http://com.ibm.ws/).session.WasHttpSessionAdapter.adapt(WasHttpSessionAdapter.java:55)
[02/07/2022, 23:04:17:795 BST] 00000036 SystemErr     R   	at [com.ibm.ws](http://com.ibm.ws/).session.http.HttpSessionObserver.sessionCreated(HttpSessionObserver.java:112)
[02/07/2022, 23:04:17:795 BST] 00000036 SystemErr     R   	at [com.ibm.ws](http://com.ibm.ws/).session.SessionEventDispatcher.sessionCreated(SessionEventDispatcher.java:85)
[02/07/2022, 23:04:17:796 BST] 00000036 SystemErr     R   	at [com.ibm.ws](http://com.ibm.ws/).session.SessionManager.createISession(SessionManager.java:295)
[02/07/2022, 23:04:17:796 BST] 00000036 SystemErr     R   	at [com.ibm.ws](http://com.ibm.ws/).session.SessionManager.createSession(SessionManager.java:727)
[02/07/2022, 23:04:17:796 BST] 00000036 SystemErr     R   	at [com.ibm.ws](http://com.ibm.ws/).webcontainer.session.impl.HttpSessionContextImpl.getIHttpSession(HttpSessionContextImpl.java:537)
[02/07/2022, 23:04:17:796 BST] 00000036 SystemErr     R   	at [com.ibm.ws](http://com.ibm.ws/).webcontainer.session.impl.HttpSessionContextImpl.getIHttpSession(HttpSessionContextImpl.java:666)
```

**Comment by pnicolucci** [comment]
> @pnicolucci This is the first time that the transactions FAT buckets have been repeated against EE10. Here is the top part of the stack that Jon showed me.
> 
> ```
> [02/07/2022, 23:04:17:770 BST] 00000036 SystemErr     R   java.lang.NoClassDefFoundError: jakarta.servlet.http.HttpSessionContext
> [02/07/2022, 23:04:17:771 BST] 00000036 SystemErr     R   	at [com.ibm.ws](http://com.ibm.ws/).webcontainer.session.impl.HttpSessionContextImpl.createSessionObject(HttpSessionContextImpl.java:952)
> [02/07/2022, 23:04:17:795 BST] 00000036 SystemErr     R   	at [com.ibm.ws](http://com.ibm.ws/).session.WasHttpSessionAdapter.adapt(WasHttpSessionAdapter.java:55)
> [02/07/2022, 23:04:17:795 BST] 00000036 SystemErr     R   	at [com.ibm.ws](http://com.ibm.ws/).session.http.HttpSessionObserver.sessionCreated(HttpSessionObserver.java:112)
> [02/07/2022, 23:04:17:795 BST] 00000036 SystemErr     R   	at [com.ibm.ws](http://com.ibm.ws/).session.SessionEventDispatcher.sessionCreated(SessionEventDispatcher.java:85)
> [02/07/2022, 23:04:17:796 BST] 00000036 SystemErr     R   	at [com.ibm.ws](http://com.ibm.ws/).session.SessionManager.createISession(SessionManager.java:295)
> [02/07/2022, 23:04:17:796 BST] 00000036 SystemErr     R   	at [com.ibm.ws](http://com.ibm.ws/).session.SessionManager.createSession(SessionManager.java:727)
> [02/07/2022, 23:04:17:796 BST] 00000036 SystemErr     R   	at [com.ibm.ws](http://com.ibm.ws/).webcontainer.session.impl.HttpSessionContextImpl.getIHttpSession(HttpSessionContextImpl.java:537)
> [02/07/2022, 23:04:17:796 BST] 00000036 SystemErr     R   	at [com.ibm.ws](http://com.ibm.ws/).webcontainer.session.impl.HttpSessionContextImpl.getIHttpSession(HttpSessionContextImpl.java:666)
> ```

@pmd1nh FYI, can you take a look?

**Comment by pmd1nh** [comment]
I pulled and rebuilt the integration branch, confirmed that #21624 is there

pmdinhMP> ~/1_WAS/ASLibertyGit/Dev_Jun16/open-liberty/dev (integration) $ git log |grep 21624
427:    Merge pull request #21624 from jonhawkes/ee10-1

I try the following locally but no test is run:

./gradlew --no-daemon com.ibm.ws.transaction.core_fat.cdi:buildandrun -Dfat.test.class.name=com.ibm.ws.transactional.web.TransactionalTestServlet -Dfat.test.mode=LITE

./gradlew --no-daemon com.ibm.ws.transaction.core_fat.cdi:buildandrun -Dfat.test.class.name=com.ibm.ws.transactional.web.TransactionalTestServlet

./gradlew --no-daemon com.ibm.ws.transaction.core_fat.cdi:buildandrun -Dfat.test.class.name=com.ibm.ws.transactional.web.TransactionalTestServlet -Dfat.test.mode=FULL

@jonhawkes   How can I run this test locally?

**Comment by pmd1nh** [comment]
I fetched and rebuilt the latest integration branch and commented out all 3 @SkipForRepeat(SkipForRepeat.EE10_FEATURES) tests.  All work fine:

############
./gradlew --no-daemon com.ibm.ws.transaction.core_fat.cdi:buildandrun -Dfat.test.class.name=com.ibm.ws.transaction.test.TransactionalTest -Dfat.test.method.name=testNE008b -Dfat.test.mode=FULL

FATSuite	TransactionalTestServlet.testNE008b	Success		2.175
FATSuite	TransactionalTestServlet.testNE008b_EE8_FEATURES	Success		1.801
FATSuite	TransactionalTestServlet.testNE008b_EE9_FEATURES	Success		1.945
**FATSuite	TransactionalTestServlet.testNE008b_EE10_FEATURES	Success		1.605**

############
./gradlew --no-daemon com.ibm.ws.transaction.core_fat.cdi:buildandrun -Dfat.test.class.name=com.ibm.ws.transaction.test.TransactionalTest -Dfat.test.method.name=testRE010b -Dfat.test.mode=FULL

FATSuite	TransactionalTestServlet.testRE010b	Success		2.420
FATSuite	TransactionalTestServlet.testRE010b_EE8_FEATURES	Success		2.265
FATSuite	TransactionalTestServlet.testRE010b_EE9_FEATURES	Success		2.080
**FATSuite	TransactionalTestServlet.testRE010b_EE10_FEATURES	Success		1.939**

############
./gradlew --no-daemon com.ibm.ws.transaction.core_fat.cdi:runfat -Dfat.test.class.name=com.ibm.ws.transaction.test.TransactionalTest -Dfat.test.method.name=testSU012b -Dfat.test.mode=FULL
FATSuite	TransactionalTestServlet.testSU012b	Success		0.629
FATSuite	TransactionalTestServlet.testSU012b_EE8_FEATURES	Success		0.441
FATSuite	TransactionalTestServlet.testSU012b_EE9_FEATURES	Success		0.505
**FATSuite	TransactionalTestServlet.testSU012b_EE10_FEATURES	Success		0.507**

Re-enable these tests in #21696

**Comment by jonhawkes** [comment]
@pmd1nh Yes, these work fine now. Thanks.

**Comment by pmd1nh** [comment]
Enabled 
FAT3:
FormLoginReadListenerTest (FULL mode)

FATSuite | test_Login_AsyncRL_Exceptions | Success |   | 4.394
-- | -- | -- | -- | --
FATSuite | test_Login_AsyncRL_variousDataLengths | Success |   | 0.517
FATSuite | test_Login_AsyncRL_Exceptions_EE8_FEATURES | Success |   | 5.301
FATSuite | test_Login_AsyncRL_variousDataLengths_EE8_FEATURES | Success |   | 0.751
FATSuite | test_Login_AsyncRL_Exceptions_EE9_FEATURES | Success |   | 5.059
FATSuite | test_Login_AsyncRL_variousDataLengths_EE9_FEATURES | Success |   | 0.665
FATSuite | test_Login_AsyncRL_Exceptions_EE10_FEATURES | Success |   | 4.755
FATSuite | test_Login_AsyncRL_variousDataLengths_EE10_FEATURES | Success |   | 0.579


All pass locally.

**Comment by pmd1nh** [comment]
All EE10 tests are now enabled.
