### ISSUE TITLE
Feature Test Summary - LG-278 stack trace joiner

### ISSUE THREAD

**Issue by Channyboy** [OpenLiberty/open-liberty#20878]
## Test Strategy

Related to : https://github.com/OpenLiberty/open-liberty/issues/1598

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

### List of FAT projects affected

* `com.ibm.ws.logging_fat`

### Test strategy

The feature introduced a new functionality to the underlying OpenLiberty logging platform. A new configuration value allows for the "joining" or "merger" of stack trace output (from `exception.printStackTrace()` calls) to console/messages.log/trace.log.  Prior to the introduction of this feature, each line of the stack trace was emitted as separate log records. The new functionality merges/joins it into a single log record. This functionality can be configured though server.xml, an environment variable and a bootstrap property.

New tests were included into the existing `com.ibm.ws.logging_fat` FAT project in the `StackTraceJoinerTest` test class. The core strategy of the tests is to verify in the console(.log), messages.log and trace.log that when a `printStrackTrace()` occurs from the test application that when the functionality is configured that a single log record for the stacktrace is observed in the logs. Additional tests are present to test that the correct hierarchy of configuration is read (i.e. if all 3 configuration strategies are used). Additional tests are also present for the enabling and disabling of the functionality during runtime (i.e. server.xml) are honored.

No automated tests.

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

`4`

**Comment by ayoho** [comment]
> No automated tests.

I assume that's just a leftover line, because you do describe automated tests that were added. And in that case, the coverage sounds good to me 👍
