### ISSUE TITLE
wsSecurity-1.1 *TokenInceptors are not ordered before WSSecurityLibertyCallerInterceptor

### ISSUE THREAD

**Issue by jonasrutishauser** [OpenLiberty/open-liberty#20912]
**Describe the bug**
The wsSecurity-1.1 `*TokenInterceptor`s (e.g., `UsernameTokenInterceptor`) are not always ordered before the `WSSecurityLibertyCallerInterceptor` as there is no `addBefore()` or `addAfter()` respectively.

**Steps to Reproduce**  
Deploy a custom feature which adds an additional interceptor which should be ordered after the `WSSecurityLibertyCallerInterceptor`:
```java
public class CustomInterceptor extends AbstractSoapInterceptor {
   public CustomInterceptor() {
      super(Phase.PRE_PROTOCOL);
      addAfter("com.ibm.ws.wssecurity.cxf.interceptor.WSSecurityLibertyCallerInterceptor");
   }
   [...]
}
```
As there is no dependency between the `*TokenInterceptor`s and the `WSSecurityLibertyCallerInterceptor` cxf will now order the `WSSecurityLibertyCallerInterceptor` before the `*TokenInterceptor`s and a login is no longer possible.

**Expected behavior**  
It should not happen that the required ordering of the `wsSecurity-1.1` interceptors is destroyed by a custom feature.

**Diagnostic information:**  
 - OpenLiberty Version: all Versions until now
 - Affected feature(s): wsSecurity-1.1
 - Java Version: doesn't matter

**Additional context**  
The simplest solution will be to add the following line to every `*TokenInterceptor`:
```java
      addBefore(WSSecurityLibertyCallerInterceptor.class.getName());
```

**Comment by arunavemulapalli** [comment]
This is addressed by the above mentioned PR.
