### ISSUE TITLE
Secured JAX-WS Service as CDI Bean does not have a Principal if mpJwt is enabled

### ISSUE THREAD

**Issue by jonasrutishauser** [OpenLiberty/open-liberty#20911]
**Describe the bug**  
If a JAX-WS service is a CDI Bean and injects a principal it works as long as the feature `mpJwt` is not enabled.
If the service is a stateless bean it always works.

**Steps to Reproduce**  
Deploy this Service with a UNT policy attachment:
```java
@Dependent
@WebService(serviceName="SimpleService", targetNamespace = "https://example.com/sample/")
public class SimpleServiceImpl implements SimpleService {
   @Inject
   private Principal principal;

   @WebMethod
   public String getCaller() {
      return principal.getName();
   }
}
```
If the feature `mpJwt` is enabled to result will be null. If the feature `mpJwt` is not enabled to name of the user in the UNT will be returned.

**Expected behavior**  
The result should be the same regardless of the `mpJwt` feature activation.

**Diagnostic information:**  
 - OpenLiberty Version: should be all versions until now
 - Affected feature(s): wsSecurity-1.1 in combination with mpJwt-*
 - Java Version: doesn't matter

**Additional context**  
I think the problem is, that the class `WSSecurityLibertyCallerInterceptor` only sets the runAs subject (despite its name) and the `PrincipalBean` of the mpJwt Feature uses the caller subject.

**Comment by teddyjtorres** [comment]
Greetings,
Thank you for opening this issue. In order to debug the problem, please clarify which mpJwt feature is used and how it was configured. Please indicate if a JWT is meant to be used for authentication when accessing the JAX-WS resource.

We will review the class WSSecurityLibertyCallerInterceptor only setting the runAs subject and its effect on the PrincipalBean of the mpJwt Feature.

Regards,
Teddy

**Comment by jonasrutishauser** [comment]
I tested with the version 1.1 and 1.2 of mpJwt.

The mpJwt feature is not expected to be used by the JAX-WS resource and therefore the problem occurs with every possible configuration (or even with missing configuration).
There is simply a JAX-WS resource which expects a Username-Token and a JAX-RS resource which expects a JWT-Token in the same application.
Our current workaround is to change the CDI JAX-WS bean to a EJB (`@Stateless` instead of `@Dependent`) which will put the runAs Subjected to the Caller Subject.

**Comment by teddyjtorres** [comment]
Thank you for your clarifications. We are reviewing the issue since a principal has to be injected there.

Regards,
Teddy

**Comment by arunavemulapalli** [comment]
I think we should set the caller subject in addition to the runAs (this behavior matches with the other was runtime also) after we are done with the wssecurity caller token processing

**Comment by arunavemulapalli** [comment]
this issues is already addressed
code change is delivered by the above mentioned PR
