### ISSUE TITLE
Doc: - Clarify properties attribute usage under datasource metatype

### ISSUE THREAD

**Issue by bmarwell** [OpenLiberty/open-liberty#20971]
**Describe the use case that you want to enable:**

Similar to https://github.com/OpenLiberty/open-liberty/issues/20970, I would like to chose the interface which is being used for opening database connections.

E.g.

```xml
<properties.postgresql
    localSocketAddress="192.168.53.14"
/>
```

(or a hostname or interface name)

**Describe why this is important to you:**

Using a specific interface allows tightening firewall rules.
The default route should not open access to databases when other applications might be able to use them as well, but do not need access.

**Additional context**

* Similar to case https://github.com/OpenLiberty/open-liberty/issues/20970
* For PostgreSQL, this would be the JDBC property "localSocketAddress".
* IBM Case TS009204430

**Comment by njr-11** [comment]
If you are using a version of the PostgreSQL JDBC driver that has the [setLocalSocketAddress(value)](https://github.com/pgjdbc/pgjdbc/blob/a7f42ead0f6a9031b4e5bb79d689aaa682a92335/pgjdbc/src/main/java/org/postgresql/ds/common/BaseDataSource.java#L1222) method, Liberty will invoke that method on the driver when you configure `localSocketAddress="192.168.53.14"`.  Are you raising the issue because that isn't working or because the schema/documentation for `properties.postgresql` doesn't show the `localSocketAddress` option?

**Comment by bmarwell** [comment]
Tried it, liberty will just fail starting. I opened a case at IBM and attached the logs there. It was complaining about exceeding attributes or similar...

**Comment by njr-11** [comment]
> Tried it, liberty will just fail starting. I opened a case at IBM and attached the logs there. It was complaining about exceeding attributes or similar...

Please post the full error message here, including the entire exception stack and all cause exceptions.  You might be able to find this information in messages.log or FFDC.  Also attach your server.xml and other configuration files (having first removed any passwords or other sensitive information you might have in there).  This information is needed to assess what is going wrong.

**Comment by bmarwell** [comment]
Will set up a small example project, sorry I wasn't able to do it until now!

**Comment by bmarwell** [comment]
@njr-11 sorry to have let you wait.

Error code:
```
[INFO] [ERROR   ] CWWKG0074E: Unable to update the configuration for dataSource with the unique identifier DefaultDataSource because of the exception: Attribute properties exceeded maximum allowed size 1.
```

This is an example project:
https://github.com/bmarwell/liberty-issue-20971

You can see the error in the GH action's test or just after running in the test directory.

**Comment by njr-11** [comment]
Thanks for providing the configuration and other files.  The error is due to specifying multiple properties elements under your data source,
```
    <properties
      URL="jdbc:postgres://db/liberty"
    />
    <properties.postgresql
        localSocketAddress="192.168.53.14"
    />
```

You should switch to 
```
  <dataSource id="DefaultDataSource" jndiName="jdbc/postgresql">
    <jdbcDriver
        libraryRef="postgresqllib"
    />
    <properties.postgresql
        URL="jdbc:postgres://db/liberty"
        localSocketAddress="192.168.53.14"
    />
  </dataSource>
```

or
```
  <dataSource id="DefaultDataSource" jndiName="jdbc/postgresql">
    <jdbcDriver
        libraryRef="postgresqllib"
    />
    <properties
        URL="jdbc:postgres://db/liberty"
        localSocketAddress="192.168.53.14"
    />
  </dataSource>
```

**Comment by bmarwell** [comment]
@njr-11 ohhh I see. Well, this is not mentioned in the docs: https://openliberty.io/docs/latest/reference/config/dataSource.html#dataSource/properties.postgresql

On the contrary, I always thought I had better used both `properties` (for generic attributes) and `properties.<dbname>` for db specific attributes.

Same for these docs: https://openliberty.io/docs/latest/relational-database-connections-JDBC.html
For MySQL, the generic properties are being used, the driver specific ones for all the other examples.

Should this be mentioned a little bit more explicitly? If you agree, this issue could be closed with a PR to the docs.

**Comment by njr-11** [comment]
I can see how that second link would lead to misinterpretation.
The first link is pointing to documentation that is generated from the code (metatype) so we could use this issue to add some clarification there and then a separate issue to improve the relational-database-connections-JDBC doc page.
