### ISSUE TITLE
Checkpoint fails for acmeair applications with configured keystore

### ISSUE THREAD

**Issue by dettmoney** [OpenLiberty/open-liberty#21009]
@tjwatson @vijaysun-omr 
There's a problem during checkpoint when using the following daily java version that supports criu. java version for the jdk is:
```
openjdk version "11.0.15-internal" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15-internal+0-adhoc.jenkins.BuildJDK11x86-64linuxcriuNightly)
Eclipse OpenJ9 VM (build master-7f4fdc29cf7, JRE 11 Linux amd64-64-Bit Compressed References 20220429_15 (JIT enabled, AOT enabled)
OpenJ9   - 7f4fdc29cf7
OMR      - 81b79405da6
JCL      - f947388a0ef based on jdk-11.0.15+10)

```
The error I see is:
Launching AcmeAuth (WebSphere Application Server 22.0.0.6/wlp-1.0.65.cl220620220502-0300) on Eclipse OpenJ9 VM, version 11.0.15-internal+0-adhoc.jenkins.BuildJDK11x86-64linuxcriuNightly (en_US)
[AUDIT   ] CWWKE0001I: The server AcmeAuth has been launched.
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
**[ERROR   ] CWPKI0033E: The keystore located at /criu/20220502/wlp/usr/servers/AcmeAuth/resources/security/key.p12 did not load because of the following error: PKCS12 not found**
...

The same checkpoint using the following jdk version works fine:
```
openjdk version "11.0.15-internal" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15-internal+0-adhoc.jenkins.BuildJDK11x86-64linuxcriuNightly)
Eclipse OpenJ9 VM (build master-56fe4ecc86d, JRE 11 Linux amd64-64-Bit Compressed References 20220422_10 (JIT enabled, AOT enabled)
OpenJ9   - 56fe4ecc86d
OMR      - db8e9577a19
JCL      - 3a97e7814e0 based on jdk-11.0.15+10)
```

**Comment by dettmoney** [comment]
I prototyped a fix to delay running the `com/ibm/ws/ssl/internal/KeystoreConfigurationFactory.updated(String, Dictionary)` method until restore time. For the Auth acmeair microservices app, APPLICATIONS checkpoint, first response time increased from around 350ms to 590ms.

**Comment by vijaysun-omr** [comment]
@dettmoney can I please see profiles (scs) for the post restore period with and without your change ?

**Comment by tjwatson** [comment]
Can this be closed?
