### ISSUE TITLE
Review the name of the CDI emptyBeansXMLExplicitBeanArchive config attribute

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#21019]
As part of CDI 4.0 and new attribute is needed to allow backwards compatibility when an empty beans.xml is used.

In previous versions of CDI, an empty beans.xml file meant that the archive was an Explicit Bean Archive ... the equivalent of `bean-discovery-mode=ALL` ... all classes in the archive are eligible to be CDI Beans

In CDI 4.0, an empty beans.xml file means that the archive is an Implicit Bean Archive ... the equivalent of `bean-discovery-mode=ANNOTATED` ... only classes that are annotated with bean defining annotations may be CDI Beans.

The initial config attribute chosen was `emptyBeansXMLExplicitBeanArchive=true|false`. This attribute is a verbose description of what the spec requires but may not be clear enough outside of that context. There was also some concern about the length of the attribute name.

**Comment by Azquelt** [comment]
It's not much shorter, but how about `emptyBeansXmlDiscoveryMode = annotated|all`

I think discovery mode is a bit easier to understand than explicit archive.

**Comment by tevans78** [comment]
Have established that the real limit is 50 chars. Still need to make sure that the name is clear though ... I agree that `emptyBeansXmlDiscoveryMode` is slightly better.

**Comment by scottkurz** [comment]
I think the UFO listed it as a boolean type value... in which case maybe:  `emptyBeansXmlDiscoveryModeAll`=**true | false**  might be better?   Does `emptyBeansXmlDiscoveryMode`  imply 'none' is a valid choice?  Would that be intended?

**Comment by tevans78** [comment]
We can limit the valid values to exclude `none`.

Another alternative I just thought of is `enableLegacyEmptyBeansXML=true|false`

**Comment by scottkurz** [comment]
I kind of like `enableLegacyEmptyBeansXML` as a boolean.   I think of someone who knows the correct terms as more likely to also have been following the spec history.. whereas "legacy" has more of a connotation: "just make it work like it used to" which seems to fit.

**Comment by Azquelt** [comment]
Having determined that we're not close to any length limit, here are our current options:
1. `emptyBeansXMLExplicitBeanArchive = true|false`
    * this is very close to the wording in the spec
    * only concern is that people may not know what's meant by "explicit bean archive"
2. `emptyBeansXmlBeanDiscoveryMode = annotated|all`
    * with the addition of "bean", this matches the wording found in the beans.xml
    * has the disadvantage that you need to also know the valid values and spelling mistakes are possible
3. `emptyBeansXmlBeanDiscoveryModeAll = true|false`
    * similar to above, but using a boolean option
4. `enableLegacyEmptyBeansXML = true|false`
    * Don't like this because it seems to imply that using an empty beans.xml is a legacy option (whereas actually it's enabling legacy behaviour)
5. `enableLegacyBehaviorForEmptyBeansXML=true|false`
    * Similar to option 4 but makes it clear that it is the behaviour that is legacy, not the empty beans.xml file itself

**Comment by Emily-Jiang** [comment]
I prefer either option 3 or 1 as the value will be boolean. Don't use the word `legacy` for empty beans.xml as it is the widely used in cdi lite and cdi full from version 4.0 and onwards, therefore option 4 is not a choice. Maybe option 4 can be worded to
`enableLegacyBehaviourForEmptyBeansXML=true|false` (added as option 5)
Option 2 has values so some spelling mistakes might occur.

**Comment by Azquelt** [comment]
Updated option 5 to US spelling (behaviour -> behavior)

**Comment by Azquelt** [comment]
The main conclusion was that we have two ways to go with this:
  * If this is an option that we encourage people to use if it helps them, it should be as usable as possible
    * In this case, `emptyBeansXmlBeanDiscoveryMode = annotated|all ` (option 2) makes the most sense because it mirrors the options in beans.xml which users are already familiar with
    * Ideally `none` would be a valid value to fully mirror the options available in beans.xml
  * If this is an option which users should only use for compatibility with older releases, it should be clear that it's a compatibility option
    * A name like `cdi3Compatibility = true | false` or `emptyBeansXmlCdi3Compatibility = true | false` would be more clear than the options above

Other points raised:
 * suggestion that config options shouldn't start with a verb like `enable`
 * there are other compatibility issues in the parsing of beans.xml, such as not respecting the default value for bean-discovery-mode when the user has referenced an older version of the schema
   * should a general "CDI 3 compatibility" option also revert those changes?
   * would it make sense to have a wider property, maybe `defaultBeansXmlDiscoveryMode` which would cover more than just the empty beans.xml case?

**Comment by tevans78** [comment]
This is most definitely a compatibility option. The recommended action is to avoid use of an empty beans.xml file. While there are going to be other changes in behaviour, this is the only compatibility option required by the spec. @Emily-Jiang @NottyCode and I had briefly talked about providing backwards compatibility for non-empty unversioned beans.xml files as well but decided against it. If that proves to be a mistake then we can add another option later.

Therefore, I think we will go with the suggested `emptyBeansXmlCdi3Compatibility = true | false`.

**Comment by Emily-Jiang** [comment]
Can you update `emptyBeansXmlCdi3Compatibility = true | false` to `emptyBeansXmlCDI3Compatibility = true | false.` as CDI is an acronym?
