### ISSUE TITLE
MP FaultTolerance 1.0: intermittent TCK test failure in RetryTest

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#2102]
251198: Test Failure (20180205-0208): com.ibm.ws.microprofile.faulttolerance.tck.FaultToleranceTckLauncher.launchFaultToleranceTCK
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemName/com.ibm.team.workitem.WorkItem/251198

Liberty - Mac EBC 20180205-0208
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_8TYSQAoPEeiTR7j3BTw-RQ

testClassLevelRetryMaxDuration(org.eclipse.microprofile.fault.tolerance.tck.RetryTest)  Time elapsed: 1.514 sec  <<< FAILURE!
java.lang.AssertionError: The max retry counter should be greater than 3 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.eclipse.microprofile.fault.tolerance.tck.RetryTest.testClassLevelRetryMaxDuration(RetryTest.java:163)

**Comment by Azquelt** [comment]
This failure looks like an infrastructure problem.

The test retries a a 100ms wait task with a maxDuration of 1000ms and ensures it runs more than twice. Unless there's something weird going on that should be no problem. The whole test should take barely more than 1 second and yet took 1.514 seconds in the build.

To me this sounds like a problem with the build engine giving an overly long wait while the test was running. If it were our test, I would increase the timeout. So far we've only seen it once so unless we start seeing it more, I would close it.

In the worst case we could exclude the test from running in the build.
