### ISSUE TITLE
Create Jakarta Tags 3.0 API Bundle

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#21022]
In the EL 5.0 API (PR https://github.com/OpenLiberty/open-liberty/pull/20597) , the 2.0 API was transformed. We should undo this when pulling in the new 3.0 API.

https://github.com/OpenLiberty/open-liberty/pull/20597/commits/399d94e5b878c94de84ec411b84f150e9bcb9be1

- Reminder: Export a version if bundles 2.0 and 3.0.

https://github.com/OpenLiberty/open-liberty/blob/2fd4a880754c37a988c5ed9ac4f1ea5988e465d6/dev/io.openliberty.jakarta.jstl.2.0/bnd.bnd#L17-L21

- Undo jakarta.el=jakarta.el transformation added in https://github.com/OpenLiberty/open-liberty/pull/20597

**Comment by volosied** [comment]
I think Jared got the first part.

JSTL 2.0 is no longer transformed: https://github.com/OpenLiberty/open-liberty/commit/1be202239c0cdb8bdb2088000d4cb612d531711f 

However, I think we still need to export the correct versions in 2.0 but 3.0 is already exporting versions. 


I see the jakarta.el transformation rule still exists: https://github.com/volosied/open-liberty/blob/fc542b9faf70f181310fd1f2c3d1625964ed951f/dev/wlp-jakartaee-transform/rules/jakarta-renames.properties#L70

**Comment by pnicolucci** [comment]
> I think Jared got the first part.
> 
> JSTL 2.0 is no longer transformed: [1be2022](https://github.com/OpenLiberty/open-liberty/commit/1be202239c0cdb8bdb2088000d4cb612d531711f)
> 
> However, I think we still need to export the correct versions in 2.0 but 3.0 is already exporting versions.
> 
> I see the jakarta.el transformation rule still exists: https://github.com/volosied/open-liberty/blob/fc542b9faf70f181310fd1f2c3d1625964ed951f/dev/wlp-jakartaee-transform/rules/jakarta-renames.properties#L70

@volosied  does this relate to : https://github.com/OpenLiberty/open-liberty/issues/21561 ?

**Comment by volosied** [comment]
It does relate to that https://github.com/OpenLiberty/open-liberty/issues/21561. 

We just need to ensure the exports and imports are correct and uniform between JSTL 2.0 and Tags 2.0.
- Ensure the correct ranges are used for the imports, and we export the proper versions ( JSTL 2.0 is missing export versions below). 

JSTL 2.0: 
```
Bundle-SymbolicName: io.openliberty.jakarta.jstl.2.0; singleton:=true
Bundle-Description: Jakarta Standard Tag Library, version 2.0

Export-Package: \
	jakarta.servlet.jsp.jstl.core,\
	jakarta.servlet.jsp.jstl.fmt,\
	jakarta.servlet.jsp.jstl.sql,\
	jakarta.servlet.jsp.jstl.tlv

Import-Package:  jakarta.servlet.jsp.jstl.*;version="[2.0.0,3.0.0)", \
 jakarta.servlet.jsp.*;version="[3.0.0,3.1.0)", \
 jakarta.servlet.*; version="[5.0.0,6.0.0)", \
```

Tags 3.0:
```
Export-Package: \
	jakarta.servlet.jsp.jstl.core;version=3.0.0,\
	jakarta.servlet.jsp.jstl.fmt;version=3.0.0,\
	jakarta.servlet.jsp.jstl.sql;version=3.0.0,\
	jakarta.servlet.jsp.jstl.tlv;version=3.0.0

Import-Package:  jakarta.servlet.jsp.jstl.*;version="[3.0.0,4.0.0)", \
 jakarta.servlet.jsp.*;version="[3.1.0,4.0.0)", \
 jakarta.servlet.*; version="[6.0.0,7.0.0)", \
```

**Comment by volosied** [comment]
^ Snippets were pulled from PR commits, so they may differ from integration
