### ISSUE TITLE
Update Dynacache to work with Servlet 6.0 

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#21029]
Initial investigation has shown that Dynacache has a dependency on : `jakarta.servlet.SingleThreadModel  ` which was removed in Servlet 6 .0.

See the following issue for additional details: https://github.com/openliberty/open-liberty/issues/20430

**Comment by kevin-ortega** [comment]
The only reference I found in dynacache for this class is in this servlet wrapper:
https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.dynacache.web/src/com/ibm/ws/cache/servlet/SingleThreadServletWrapper.java

I think this is a class carried over from tWAS and is not used in Liberty.   I can not find any code that instantiates this class.   It appears SingleThreadServletWrapper.java can simply be deleted but I will investigate further.
