### ISSUE TITLE
Unpooled vs PooledByteBufAllocator

### ISSUE THREAD

**Issue by epj** [OpenLiberty/open-liberty#21039]
Currently com.ibm.ws.sipcontainer/src/com/ibm/ws/sip/stack/transport/sip/netty/BaseConnection.java uses Unpooled.buffer() but should it pull from pooled instead (i.e. PooledByteBufAllocator)?

**Comment by hutchig** [comment]
Gordon to create a box document that discusses the approaches generically and has columns for approach (native-backed, wrapped, pooled, unpooled etc) and rows for actual buffers (and thus maybe a set of rows for SIP, a set of rows for WOLA etc.) and why we can use approach X but not X-1 and where the spring-head-source for the data/buffer actually is. Also refer to the JSR for foreign function/memory perhaps.

**Comment by epj** [comment]
Current Unpooled references in sipcontainer:
./src/com/ibm/ws/sip/channel/resolver/impl/netty/SipResolverTcpTransport.java:            ByteBuf newBuf = Unpooled.copiedBuffer(_bufferArray);
./src/com/ibm/ws/sip/channel/resolver/impl/netty/SipResolverTcpTransport.java:                            Unpooled.wrappedBuffer(readBuffers.toArray(new ByteBuf[readBuffers.size()])));
./src/com/ibm/ws/sip/channel/resolver/impl/netty/SipResolverTcpTransport.java:                ByteBuf newBuf = Unpooled.copiedBuffer(_bufferArray);
./src/com/ibm/ws/sip/stack/transport/sip/netty/BaseConnection.java:import io.netty.buffer.Unpooled;
./src/com/ibm/ws/sip/stack/transport/sip/netty/BaseConnection.java:             ByteBuf buffer = Unpooled.buffer(length, length);

**Comment by pnicolucci** [comment]
This should be discussed as part of : https://github.com/OpenLiberty/open-liberty/issues/20935
