### ISSUE TITLE
Liberty OIDC error is being returned with incorrect characters

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/open-liberty#21050]
**Describe the bug**  
Liberty OIDC error is being returned with incorrect characters. As reported by customer, when invoking the OP's `/authorize` endpoint with missing or incorrect parameters in traditional Chinese, the returned error message has a number of `????` instead of Chinese characters. The same happens for other non-ascii languages.

The error page shows,
```
"Accept-Language: zh-TW"
HTTP/1.1 200 OK
X-Powered-By: Servlet/3.0
Content-Language: en-DE
Transfer-Encoding: chunked
Date: Fri, 06 May 2022 08:42:36 GMT

CWOAU0033E: ????????????client_id
```

**Steps to Reproduce**  
Configure an OP using openidConnectServer-1.0 and corresponding elements.
1. Set browser language to zh-tw. (In Firefox, this is in the "Choose your preferred language for displaying pages" setting)
2. Access OP's authorization endpoint without any parameters (i.e. https://localhost:9443/oidc/endpoint/OP/authorize)
3. The error message displays with ?, CWOAU0033E: ????????????client_id

**Expected behavior**  
The page should contain the properly translated error message instead of `????????????`

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.3 (but earlier version can also be affected)
 - Affected feature(s): openidConnectServer-1.0
 - Java Version: [i.e. full output of `java -version`]
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**  
Further debugging of this issue indicates that the OAuth20AuthorizeRequestExceptionHandler is obtaining the PrintWriter from the HttpServletResponse without first setting the response's Locale. Although the error message is properly translated, the writer itself is created using the default `ISO-8859-1` charset, which causes the non-ascii characters to display as `?`.

Updating the OAuth20AuthorizeRequestExceptionHandler to call `setLocale(...)` first on the response before calling the `getWriter()` method should resolve this problem.

It was also found that using curl is not a reliable way to reproduce the problem since the shell would still display ? even after fixing the issue,

curl -sik https://localhost:9443/oidc/endpoint/OP/authorize -H "Accept-Language: zh-TW"
HTTP/1.1 200 OK
X-Powered-By: Servlet/3.1
Content-Language: zh-TW
Transfer-Encoding: chunked
Date: Tue, 17 May 2022 15:28:01 GMT

CWOAU0033E: ??|???n??????ɴ??ѼơGclient_id

while the browser shows the correct string,

CWOAU0033E: 遺漏必要的執行時期參數：client_id

**Comment by jensengelke** [comment]
Thanks @teddyjtorres

**Comment by teddyjtorres** [comment]
You're welcome.
