### ISSUE TITLE
Re-enable JSON-B tests after Yasson update

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#21051]
There are two EE10 JSON-B tests which have temporarily disabled until a J2S issue is resolved in Yasson
https://github.com/eclipse-ee4j/yasson/issues/557

The disabled tests can be found here
https://github.com/OpenLiberty/open-liberty/blob/f6b6fa8fe9f3ae7073fbc61a4a93a210c576b6cd/dev/io.openliberty.jakartaee10.internal_fat/fat/src/io/openliberty/jakartaee10/internal/apps/jakartaee10/web/WebProfile10TestServlet.java#L71

**Comment by KyleAure** [comment]
Fixed via PR #21557
