### ISSUE TITLE
SSE context and SSE broadcaster assigned to null after class-level injection 

### ISSUE THREAD

**Issue by ocseal** [OpenLiberty/open-liberty#21065]
**Description**
Using Open Liberty 22.0.0.3 or 22.0.0.5 and class-level SSE injection, a proxy object is being injected rather than the SSE. This results in the SSE broadcaster being assigned to null after sse.newBroadcaster() is called. 

**Steps to Reproduce**  
1. [Clone the repository](https://github.com/ocseal/cargotracker) and download the .jar file for Derby 10.14.2.0. 
2. Run Eclipse and import the project through "Import Existing Maven Projects".
3. Change the Derby jar/library path in the server.xml to the location of your installed Derby .jar.
4. Create a new Liberty 22.0.0.3 server and configure this server for the Cargo Tracker application through the Eclipse server setup wizard.
5. Start the created server. 
6. Navigate to http://localhost:8080/cargo-tracker and select "Administration Interface".
7. Select "Book" from the sidebar and select two different locations of your choice from the dropdown menu.
8. Select a date at least 30 days in advance of the current date and confirm. 
9. The error should now appear in the Eclipse console. 

**Expected behavior**  
A SSE object is injected and the SSE broadcaster is properly assigned to a broadcaster object. 

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.3 and 22.0.0.5
 - Affected feature(s): Jakarta EE 8, ejbLite-3.2
 - Java Version: 
     - openjdk 11.0.12 2021-07-20
     - OpenJDK Runtime Environment Homebrew (build 11.0.12+0)
     - OpenJDK 64-Bit Server VM Homebrew (build 11.0.12+0, mixed mode)
 - Attached in server.txt format since GitHub does not support .xml attachments
     - [server.txt](https://github.com/OpenLiberty/open-liberty/files/8665331/server.txt)
 - [messages.log](https://github.com/OpenLiberty/open-liberty/files/8665297/messages.log)

**Additional context**  
This issue did not appear when running the application on Payara. After creating a new broadcaster object in the tracking() method if the original broadcaster is set to null, a 'broken pipe' IOException is thrown where the SSEEventSink is closed prematurely.

**Comment by jim-krueger** [comment]
I neglected to update the issue following the resolution.   Ultimately @Context injection in the PostConstruct() method is not supported on OpenLiberty in EE8.  This issue was resolved by altering the test code.

**Comment by jim-krueger** [comment]
Closing this issue.  @ocseal, please let me know if you disagree or need this issue resolved further.

**Comment by gkwan-ibm** [comment]
hi @jim-krueger 

> Ultimately @context injection in the PostConstruct() method is not supported on OpenLiberty in EE8. 

Does it mean that OL didn't support the EE8 spec properly? Or the spec does not mention that?

**Comment by jim-krueger** [comment]
@gkwan-ibm  The consensus back in May was that the spec was not clear on this point and Chanun was able to work around this by moving this injection into his resource method instead.  

It is also important to note that the current direction for Jakarta Rest (JAXRS) is to move away from Context injection support.  
See [Section 1.1.1 of the Jakarta RESTful Web Services Specification ](https://jakarta.ee/specifications/restful-ws/3.1/jakarta-restful-ws-spec-3.1.html#context-injection)

**Comment by gkwan-ibm** [comment]
hi @jim-krueger 

 Does OL in EE8 support @context injection in the **PreConstruct**() method or the constructor?

**Comment by jim-krueger** [comment]
Hi @gkwan-ibm
I believe JAXRS in EE8 only supports Context injection on resource methods. So not in the PreConstruct() or constructor.
