### ISSUE TITLE
Correct Service Release and Fixpack processing in JavaInfo

### ISSUE THREAD

**Issue by jgrassel** [OpenLiberty/open-liberty#21060]
There exists Java implementations (such as Java Semeru for z/OS) which can return unexpected values for the `java.runtime` property, such as `IBM Semeru Runtime Certified Edition for z/OS (11.0.15-internal+0-adhoc.JENKINS.BuildJDK11s390xzosRelease)`.  When trying to process a Service Release number out of this, JavaInfo submits "" as an argument to `JavaInfo.parseIntSafe()`.

Before calling `parseIntSafe()`, there should be a `len > 0` check, as len will not increment past 0 if there is a non-digit character after the "sr" it finds in the string.

This is a low-risk bug, since the NumberFormatException is caught and logged with FFDC, and `parseIntSafe()` returns 0.  However, the extra FFDC can be avoided with some extra value checking.

**Comment by jgrassel** [comment]
Fix has been merged. Closing.

**Comment by mbroz2** [comment]
@jgrassel please update the description (first comment) of this `release bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
