### ISSUE TITLE
Refresh token is not cleaned up when a JWT access_token had been issued

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#21079]
**Describe the bug**  
OIDC end_session's refresh_token cleanup is different depending on the type of access_token issued.
The Liberty OP can issue opaque or JWT access_tokens.  When we run end_session when we're creating opaque access_tokens, the refresh_token is removed from the cache, when we've created jwt access_tokens, the refresh_token is NOT removed.

[jwtTokenExtraTrace.zip](https://github.com/OpenLiberty/open-liberty/files/8673549/jwtTokenExtraTrace.zip)
[opaqueTokenExtraTrace.zip](https://github.com/OpenLiberty/open-liberty/files/8673550/opaqueTokenExtraTrace.zip)

**Steps to Reproduce**  

- Setup 2 OIDC providers - one using opaque tokens and one using JWT tokens as access_tokens.  Configure an RP (openidconnectclient) to use each provider and have each client protect an app. (sample openidconnect providers and client configs are attached)

- Access the app protected by client1/provider1 and save the refresh_token created during that login.

- Access the app protected by client2/provider2 and save the refresh_token created during that login.

- Run end_session for provider1 - then try to refresh the tokens using the refresh_token (created by provider1) that you saved.  If this provider generated opaque access_tokens, the refresh should fail.

- Run end_session for provider2 - then try to refresh the tokens using the refresh_token (created by provider2) that you saved.  If this provider generated JWT access_tokens, the refresh will work.

**Expected behavior**  
Running end_session on providers that generate JWT access_tokens should invalidate the refresh_token (just like what happens when access_tokens are opaque)

**Diagnostic information:**  
 - OpenLiberty Version: any version prior to 22.0.0.6
 - Affected feature(s): openidConnectServer-1.0
 - Java Version: any
 - server.xml configurations: (only including the openidconnect config portions):
 OP - 
[OPServer.xml.txt](https://github.com/OpenLiberty/open-liberty/files/8833256/OPServer.xml.txt)
RP - 
[RPServer.xml.txt](https://github.com/OpenLiberty/open-liberty/files/8833259/RPServer.xml.txt)

 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**

**Comment by mbroz2** [comment]
@c00crane please update the description (first comment) of this `release bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
