### ISSUE TITLE
Custom claims not passed to the back end

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#21097]
**Describe the bug**  
When using MP Starter start.microprofile.io to generate service-a and service-b running on open liberty, the invocation to the service b no longer send out the custom claim on invoking the jwt backend via localhost:9080.

**Steps to Reproduce**  
1. Clone https://github.com/Emily-Jiang/mp-starter-ol-mvn.
2. Build `service-a` and `service-b` per the respective instructions.
3. Start both services.
4. Invoke http://localhost:9080/data/secured/test. Observe the value emitted for the `custom-value` claim.

**Expected behavior**  
The custom claim's value should be `Jessie specific value`.

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.5
 - Affected feature(s) mpJwt-1.0, mpJwt-1.1, mpJwt-1.2
 - Java Version: Java 11
 - server.xml configuration (WITHOUT sensitive information like passwords)
     - https://github.com/Emily-Jiang/mp-starter-ol-mvn/blob/main/service-a/src/main/liberty/config/server.xml
     - https://github.com/Emily-Jiang/mp-starter-ol-mvn/blob/main/service-b/src/main/liberty/config/server.xml

**Comment by jhanders34** [comment]
#regression

**Comment by jhanders34** [comment]
This defect was caused by the changes in #20700 and #20723 which exposed a hidden problem in the Claims.putAll method when there are claims with a null value.

**Comment by mbroz2** [comment]
@ayoho please update the description (first comment) of this `release bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
