### ISSUE TITLE
Investigate Checkpoint with Batch

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#21128]
Need to investigate now batch jobs are executed in the context of checkpoint/restore.

Initially it seems we need to somehow prevent job execution until the restore side.

**Comment by tjwatson** [comment]
@scottkurz This is why I was asking questions during the Batch design review.  I will need to discuss with you some details on when batch jobs are executed to understand the impacts checkpoint/restore may have on it.

**Comment by scottkurz** [comment]
I had a question too:  For an embedded DB like Derby would/should it work to prime the batch persistence code before taking the checkpoint?   I'm assuming this would be undesirable for an external DB since you'd need to get new DB connections anyway.

**Comment by tjwatson** [comment]
What is the common DB usage for batch persistence when running in a cloud container (e.g. docker image).  I have my doubts an embedded DB is used for that case, but maybe I am wrong?  If you database is "in-container" then I can see advantages to populating it during container image build.  But is that common?

**Comment by tjwatson** [comment]
Initial support for checkpoint will not include batch.

**Comment by tjwatson** [comment]
Tracking with epic #27747
