### ISSUE TITLE
Provide admin center with access to validation and config schema in a collective

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#21120]
User Story:
"As the Liberty admin center, we require a way to obtain schema for the /ibm/api/validation/ and /ibm/api/config/ endpoints so that the correct validation options can be presented to the end user on the panel for validating connectivity to configured resources."

The existing /openapi/platform/validation/ and /openapi/platform/config/ endpoints provide this, but are currently not accessible in a collective.

Options from the design call to achieve this are either of:

1. Add duplicate endpoints under /ibm/api that provide the same results as the /openapi/platform/validation/ and /openapi/platform/config/ endopints, or
2. Add routing to the /openapi endpoint.

**Comment by frowe** [comment]
From an email chain about what to name the actual endpoints. Do we want to use another name other than /ibm/api/​platform/validation/ and /ibm/api/platform/config/ for these new endpoints?  It was agreed to use the same endpoint name.

**Comment by nmittles** [comment]
All required function to enable the endpoints under /ibm/api/ has been delivered.  This new function is currently gated as Beta code.  Once the overall feature is ready to GA, the admincenter team will need to remove these beta gates.  See https://github.com/openliberty/open-liberty/issues/23399 for details.
