### ISSUE TITLE
Feature Test Summary For JSON Processing (JSONP) 2.1 for Jakarta EE 10

### ISSUE THREAD

**Issue by tabishop** [OpenLiberty/open-liberty#21137]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

Repackage and automate the TCK tests provided by the Jsonp api to ensure we are running all applicable tests that have already been created to verify that the jsonp implementation, parsson, we are shipping passes all required tests.

Re-ran the existing com.ibm.ws.jsonb_fat test suite using Jakarta EE 10 features.

New function testing for new enhancements provided with JsonP 2.1

#### io.openliberty.jakarta.jsonp.2.1_fat_tck
The JSON Processing TCK 2.1 includes the following components:

- JSONPSigTest 
  - JSON Processing TCK signature tests; check that all public APIs are supported and/or defined as specified in the JSON Processing Version 2.1 implementation under test.
- CollectorTests
  - Test all collectors returned by API
- ExceptionTests
   - Ensures JsonException messages are created correctly
- JsonArrayTests
   - Tests Json Array functions and error handling 
- JsonBuilderFactoryTests
   - Tests the JsonBuilderFactory API
- JsonCoding
   - Tests encoding/decoding Json Pointer as defined by RFC 6901
- JsonGeneratorFactoryTests
   - Tests creation and error handling for JsonGeneratorFactory class
- JsonGeneratorTests 
   - Tests generation of Json Objects and Arrays
- JsonNumberTests
   -  Equality, hashcode, and isIntegral tests for JsonNumber class
- JsonObjectTests
   - Tests JsonObject/JsonObjectBuilder API's.
- JsonParseEventTests
   - Test JsonParser.Event APIs
- JsonParserFactoryTests
   - Tests the JsonParserFactory API
- JsonParserTests
   - Tests the JsonParser parser. Verifies parsing of JsonObjects. Creates the JsonParser via the various APIs.
- JsonReaderFactoryTests
   - Tests the JsonReaderFactory API to create the readerFactory and reader using various APIs.
- JsonReaderTests
   - Test reading of objects and arrays of various formats and error handling using the JsonReader class
- JsonStreamingTests
   - Tests generation of Json data to various stream types (StringWriter, OutputStream 
- JsonStringTests
   - Tests JsonString equals methods and getChars methods
- JsonValueTests
   - Test JsonValue obect API methods.
- JsonWriterFactoryTests
   - Tests the JsonWriterFactory API to create the writerFactory and writer using various APIs
- JsonWriterTests
   -  Tests JsonWriter API's for writing out a JsonArray. Comparison is done by reading the JsonWriter output using JsonReader and recreating the JsonArray and than performing a JsonArray comparison for equality
- MergeTests
   - Tests the Json.createMergePatch and Json.createMergeDiff APIs using various inputs
- PatchTests
   - Tests the Json.createPatch and Json.createDiff APIs with various inputs 
- PointerTests
   - Tests creation and usage of the JsonPointer object
- JsonProviderTest
   -  Verifies it is possible to obtain the JsonProvider implementation from a System property
- Pluggability.JsonProviderTests
  - The JSON Processing Pluggability Tests which include tests for the API used to select a customer provider

#### com.ibm.ws.jsonb_fat (https://github.com/OpenLiberty/open-liberty/pull/21010)
Regression Testing - Container features

| Test Class | Description | What is tested |
| ----- | ----- | ----- |
| JSONBContainerTest | Uses jsonbContainer + jsonp features with a bell pointing to a thrid party implementation of Jsonb | Tests jsonb running in a servlet and CDI bean. Ensures the correct jsonb provider is used. Tests previous release features  |
| JSONBInAppTest | Uses jsonbContainer + jsonpContainer features with a bell pointing to yasson(RI) and a thrid party implementation of jsonp | Tests jsonb running in a servlet and CDI bean. Ensures the correct jsonb provider is used. Tests previous release features. |
| JSONBTest | Uses jsonb and jsonp features | Tests jsonb running in a servlet and CDI bean. Ensures the correct jsonb provider is used. Tests previous release features. |
| JSONPContainerTest | Uses jsonpContainer feature  with a bell pointing to a thrid party implementation of jsonp | Tests jsonp running in a servlet. Ensures the correct jsonp provider is used. Tests previous release features. |
| JsonUserFeatureTest | Uses jsonbContainer + jsonpContainer features with a bell pointing to yasson(RI) and a thrid party implementation of jsonp along with user features that use jsonb and jsonp during their activate methods | Tests jsonb and jsonp were able to be used during OSGi service method via injection. |

#### New feature testing
io.openliberty.jsonp.2.1_fat (https://github.com/OpenLiberty/open-liberty/pull/21445)
- testJSONCreateValueForNumber
  - Exercise the API of Json.createValue(Number) using int, long, Double, BigInteger, BigDecimal, and Number.
- testJSONGetCurrentEventFromParser
  - Validate the correct JsonParser.Event from the JSONParser.currentEvent() is returned at the start, during, and end of parsing JSON data.
- testJsonConfigDuplicateKeyStrategyDefault
  - Verify when a KeyStrategy is not provider the default behavior doesn't change over time. Parsson's default is the same as `KeyStartegy.LAST`.
- testJsonConfigDuplicateKeyStrategyFirst
  - Verify that `KeyStrategy.FIRST` returns the first occurrence of duplicate keys while reading JSON data.
- testJsonConfigDuplicateKeyStrategyLast
  - Verify that `KeyStrategy.LAST` returns the last occurrence of duplicate keys while reading JSON data.
- testJsonConfigDuplicateKeyStrategyNone
  - Verify that `KeyStartegy.NONE` prevents duplicate entries while reading JSON data by throwing a JsonException.

### Test strategy

* What functionality is new or modified by this feature?
    - JsonP 2.1 support provided by the parsson reference implementation
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
    - Required tests to pass the TCK were written and implemented by the parsson reference implementation TCK tests
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

Voting Results: 4
Voting Log: https://ibm-cloud.slack.com/archives/C31DXH4GJ/p1655744048436099

**Comment by ayoho** [comment]
Coverage sounds fine to me 👍
