### ISSUE TITLE
Transactions summary trace is missing

### ISSUE THREAD

**Issue by jonhawkes** [OpenLiberty/open-liberty#21148]
The TransactionSummary trace group which is used to provide ultra minimal trace for transaction creation and setRollbackOnly no longer works.

Set TransactionSummary=all trace and notice that regular Transaction=all trace is emitted.

Trace is emitted only for transaction creation and setRollbackOnly

This trace group is used when identifying what started a transaction or what rolled back a transaction in very high throughput systems where regular trace would be too big.

**Comment by jonhawkes** [comment]
TransactionSummary was inadvertently removed in June 2021.

**Comment by mbroz2** [comment]
@jonhawkes please update the description of this `relesae bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
