### ISSUE TITLE
Security 3.0: Update OidcHttpAuthenticationMechanism to use OidcClientCore Client to perform Authentication Request

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/open-liberty#21159]
Task: Update OidcHttpAuthenticationMechanism to use OidcClientCore Client to perform Authentication Request. OidcClientCore Client to implement an "AuthorizationCodeFlow". Perform discovery on first request.

Spec section: https://github.com/jakartaee/security/blob/master/spec/src/main/asciidoc/authenticationMechanism.adoc#authentication-dialog

> The authentication dialog that the authentication mechanism starts and coordinates follows the flow as defined by the OpenID Connect specification

...

> When the authentication mechanism determines authentication is required, for instance when the caller ("end-user" in OpenID Connect terminology) tries to access a protected resource without being authenticated, or when the caller explicitly initiates authentication, without being authenticated for the current request, an authentication request needs to be assembled and send to the authentication endpoint of the OpenID Connect provider. This request corresponds to step (1) in the OpenID Connect diagram depicted above. The location of this endpoint is configured by the providerURI attribute of the OpenIdAuthenticationMechanismDefinition annotation.
> The following values need to be passed to this endpoint unconditionally:
> 
> - ClientId value as taken from OpenIdAuthenticationMechanismDefinition.clientId
> - Scope value as taken from OpenIdAuthenticationMechanismDefinition.scope
> - Response Type value as taken from OpenIdAuthenticationMechanismDefinition.responseType
> - State value, must be generated by the authentication mechanism
> - RedirectURI value as taken from OpenIdAuthenticationMechanismDefinition.redirectURI (evaluated)

**Comment by jimmy1wu** [comment]
fat tests have been added for all required values:

clientId: https://github.com/OpenLiberty/open-liberty/pull/22429 (see ConfigurationTests.java)
scope: https://github.com/OpenLiberty/open-liberty/pull/23533
responseType: https://github.com/OpenLiberty/open-liberty/pull/23472
state: https://github.com/OpenLiberty/open-liberty/pull/23879 (verifies that `state` is not empty in auth endpoint req)
redirectURI: https://github.com/OpenLiberty/open-liberty/pull/23357
