### ISSUE TITLE
Security 3.0: Update OidcClientCore Client with overriding values

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/open-liberty#21158]
Task: Update OidcClientCore Client with overriding values.

Spec section: https://github.com/jakartaee/security/blob/master/spec/src/main/asciidoc/authenticationMechanism.adoc#metadata-configuration

> The values retrieved from the well known openid configuration endpoint can be overwritten if needed by using the OpenIdAuthenticationMechanismDefinition.providerMetadata structure.

**Comment by ayoho** [comment]
FAT coverage:
- GenericOIDCAuthMechanism servlet (used by most tests in ConfigurationTests)
    - Specifies a few overriding values in the `@OpenIdProviderMetadata` annotation.
- ConfigurationTests_noProviderURI_withProviderMetadata
    - Specifies most of the values available in the `@OpenIdProviderMetadata` annotation.

**Comment by ayoho** [comment]
FATs are being delivered in https://github.com/OpenLiberty/open-liberty/pull/24133 to cover the rest of the scenarios.
