### ISSUE TITLE
Security 3.0: Create OidcClientCore Client Discovery Subsystem

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/open-liberty#21157]
Task: Create OidcClientCore Client Discovery Subsystem. Discovery to be performed on first call to perform Authentication Request.

Spec section: https://github.com/jakartaee/security/blob/master/spec/src/main/asciidoc/authenticationMechanism.adoc#metadata-configuration

> The OpenID Connect authentication mechanism needs metadata about the OpenID Connect Provider to function properly. The OpenID Connect specification defines that this data can be read from the well known openid configuration endpoint which resides at [OpenID Connect Provider base URL].well-known/openid-configuration.

...

> The OpenIdAuthenticationMechanismDefinition.providerURI defines the base URL of the OpenID Connect Provider where the /.well-known/openid-configuration is appended to (or used as-is when it is the well known configuration URL itself). Reading the well known openid configuration endpoint can be done eagerly when the application is deployed or lazily at the time a secured URL is accessed for the first time.

**Comment by ayoho** [comment]
The following FATs should cover this:
- ConfigurationTests_minimumAnnotation
    - `providerURI`: Configured
    - `providerMetadata`: Not configured
- ConfigurationTests_maximumAnnotation
    - `providerURI`: Configured
    - `providerMetadata`: Configured, but with small subset of values
- ConfigurationTests_noProviderURI_withoutProviderMetadata
    - `providerURI`: Not configured
    - `providerMetadata`: Not configured
- ConfigurationTests_noProviderURI_withProviderMetadata
    - `providerURI`: Not configured
    - `providerMetadata`: Configured with valid values

Other FATs throughout the buckets have a mix of `providerMetadata` being configured or not configured for various purposes.
