### ISSUE TITLE
Security 3.0: Update OidcHttpAuthenticationMechanism to process redirection back from OP's authorization endpoint

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/open-liberty#21165]
Task: Update OidcHttpAuthenticationMechanism to process redirection back from OP's authorization endpoint.

Spec section: https://github.com/jakartaee/security/blob/master/spec/src/main/asciidoc/authenticationMechanism.adoc#authentication-dialog

> Step (3) in the OpenID Connect diagram depicted above, that is, when the OpenID Connect Provider calls us back, is detected by the authentication mechanism when a request contains a state request parameter. When that initial condition is satisfied, the following investigation and actions must be done by the authentication mechanism:
> 
> - If the request (without request parameters) does not match the redirectURI, or does not match the stored original URL (without request parameters) in case AuthenticationMechanismDefinition.redirectToOriginalResource is set to 'true', it must reply with a CredentialValidationResult.NOT_VALIDATED_RESULT value.
> - If there is no State value stored, it must reply with a CredentialValidationResult.NOT_VALIDATED_RESULT value.
> - If the State value in the request does not match the State value stored, it must reply with a CredentialValidationResult.INVALID_RESULT value.
> - If the request contains a parameter error, the authentication by the OpenID Connect Provider has failed and the authentication mechanism must reply with a CredentialValidationResult.INVALID_RESULT value.

> If none of the above listed additional conditions apply, the request is taken to be a valid callback and the authentication between the end-user (caller) and the OpenID Connect Provider is considered to have been successful. The authentication mechanism must now move to step (4) of the OpenID Connect diagram and mark this internally by clearing the stored State value (remove it from the HTTP session or Cookie).

**Comment by ayoho** [comment]
Jimmy delivered code for the redirectToOriginalResource changes at the end of last week.

**Comment by jimmy1wu** [comment]
we have good unit test coverage for the callback checks in [JakartaOidcAuthenticationResponseValidatorTest](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.security.oidcclientcore.internal/test/io/openliberty/security/oidcclientcore/authentication/JakartaOidcAuthenticationResponseValidatorTest.java) except for:
> If the State value in the request does not match the State value stored, it must reply with a CredentialValidationResult.INVALID_RESULT value.

in terms for fat coverage, i think we only have coverage for the error param case.

i will work on adding the missing unit test case and see what i can do for the remaining fat test cases.

**Comment by jimmy1wu** [comment]
added FAT tests in https://github.com/OpenLiberty/open-liberty/pull/24479 for each of the callback checks that checks that the that the correct http status is returned based on the  `CredentialValidationResult` and that the proper error message is logged when the `CredentialValidationResult` is `INVALID_RESULT`
