### ISSUE TITLE
Security 3.0: Update OidcHttpAuthenticationMechanism to use OidcClientCore's Storage Subsystem to store optional fields

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/open-liberty#21167]
Task: Update OidcHttpAuthenticationMechanism to use OidcClientCore's Storage Subsystem to store optional fields (or OidcClientCore's AuthorizationCodeFlow can be updated to do this)

Spec section: https://github.com/jakartaee/security/blob/master/spec/src/main/asciidoc/authenticationMechanism.adoc#authentication-dialog

> When available in the "Token Response", the optional fields "refresh_token" and "expires_in" must be stored internally.

**Comment by ayoho** [comment]
Development to support this should have been completed under https://github.com/OpenLiberty/open-liberty/pull/22219. We might consider updating FATs to double check that these are stored since our FATs output the data stored in the `OpenIdContext`.

**Comment by ayoho** [comment]
FATs that check on optional fields were delivered in https://github.com/OpenLiberty/open-liberty/pull/24358.
