### ISSUE TITLE
Security 3.0: Create OidcClientCore Storage Subsystem

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/open-liberty#21162]
Task: Create OidcClientCore Storage Subsystem allowing storing values either in cookies or HTTP Session and update OidcClientCore's AuthorizationCodeFlow to use it to store state and nonce.

Spec section: https://github.com/jakartaee/security/blob/master/spec/src/main/asciidoc/authenticationMechanism.adoc#authentication-dialog

> The State value, and also the Nonce value if requested, MUST be stored between requests so that these values can be validated when the OpenID Connect Provider later calls the supplied redirectURI. These values can either be stored serverside (in the HTTP Session) or clientside (as a Cookie). The value of the OpenIdAuthenticationDefinition.useSession attribute determines which one is used. In the case of storage through a Cookie, the Cookie must be defined as HTTPonly and must have the Secure flag set.

**Comment by ayoho** [comment]
As mentioned above, cookie storage should be fully implemented. Session storage still needs to be implemented.

**Comment by ayoho** [comment]
FATs to cover this:
- ConfigurationELValuesOverrideTests_useSession_false_useSessionExpression_true
- ConfigurationELValuesOverrideTests_useSession_false_useSessionExpression_false
- ConfigurationELValuesOverrideTests_useSession_true_useSessionExpression_true
- ConfigurationELValuesOverrideTests_useSession_true_useSessionExpression_false
- ConfigurationELValuesOverrideWithoutHttpSessionTests_useSession_false_useSessionExpression_true
- ConfigurationELValuesOverrideWithoutHttpSessionTests_useSession_false_useSessionExpression_false
- ConfigurationELValuesOverrideWithoutHttpSessionTests_useSession_true_useSessionExpression_true
- ConfigurationELValuesOverrideWithoutHttpSessionTests_useSession_true_useSessionExpression_false

Other FATs throughout our buckets don't specify `useSession`, so will use the default value. That should cover the scenarios that would relate to the storage subsystem.
