### ISSUE TITLE
Security 3.0: Implement IdentityStore for OIDC token validation

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/open-liberty#21169]
Task: Implement IdentityStore for OIDC token validation. Update the CDI Extension implementation to create the OidcClientIdentityStore bean. Perform validation.

Spec section: https://github.com/jakartaee/security/blob/master/spec/src/main/asciidoc/authenticationMechanism.adoc#authentication-dialog

> In order to correctly validate this token, the Jakarta Security implementation MUST install an IdentityStore capable of validating this credential. Note that in this version of the specification the type of both the Credential and IdentityStore are implementation specific. A future version of the specification may standardise these. For this reason the implementation specific identity store is now discussed in this chapter.

> The IdentityStore mentioned above must perform the following checks (also defined by the OpenID Connect specification):
> 
> - The issuer claim matches the issuer retrieved from the well known openid configuration endpoint or the issuer member of the OpenIdProviderMetadata construct.
> - A subject claim is present and contains a value.
> - The audience claim is present and is equal to the OpenIdAuthenticationMechanismDefinition.clientId
> - If multiple audience values are returned by the OpenID Connect Provider, an authorized party claim (azp) must be present.
> - If an authorized party claim (azp) is present, it must match the OpenIdAuthenticationMechanismDefinition.clientId
> - The expiration claim must be present and must be 'in the future' (a clock skew might be considered or configured in an implementation specific way)
> - The issued at claim must be present and must be 'in the past' (a clock skew might be considered or configured in an implementation specific way)
> - The not before claim can be present and if defined, must be 'in the past' (a clock skew might be considered or configured in an implementation specific way)
> 

> For the Identity Token, the following check must be performed additionally
> 
> - When nonce usage is configured, verify if the nonce value within the Identity Token is identical to the one that was specified in the authentication request.

**Comment by ayoho** [comment]
Test coverage:

Most of the test coverage was added in TokenValidationTests by https://github.com/OpenLiberty/open-liberty/pull/24358.

- The issuer claim matches the issuer retrieved from the well known openid configuration endpoint or the issuer member of the OpenIdProviderMetadata construct.
    - [x] `iss` missing: TokenValidatorTest (Unit test)
    - [x] `iss` doesn't match discovery document or OpenIdProviderMetadata annotation: TokenValidatorTest (Unit test)
    - [x] `iss` matches discovery document
    - [x] `iss` matches OpenIdProviderMetadata annotation
- A subject claim is present and contains a value.
    - [x] `sub` missing
    - [x] `sub` empty
    - [x] `sub` contains value
- The audience claim is present and is equal to the OpenIdAuthenticationMechanismDefinition.clientId
    - [x] `aud` missing
    - [x] `aud` empty
    - [x] `aud` doesn't match
    - [x] `aud` matches
- If multiple audience values are returned by the OpenID Connect Provider, an authorized party claim (azp) must be present.
    - [x] `azp` missing
    - [x] `azp` present
- If an authorized party claim (azp) is present, it must match the OpenIdAuthenticationMechanismDefinition.clientId
    - [x] `azp` doesn't match
    - [x] `azp` matches
- The expiration claim must be present and must be 'in the future' (a clock skew might be considered or configured in an implementation specific way)
    - [x] `exp` missing
    - [x] `exp` in the past
    - [x] `exp` valid
- The issued at claim must be present and must be 'in the past' (a clock skew might be considered or configured in an implementation specific way)
    - [x] `iat` missing
    - [x] `iat` in the future
    - [x] `iat` valid
- The not before claim can be present and if defined, must be 'in the past' (a clock skew might be considered or configured in an implementation specific way)
    - [x] `nbf` missing
    - [x] `nbf` in the future
    - [x] `nbf` valid

For the Identity Token, the following check must be performed additionally
- When nonce usage is configured, verify if the nonce value within the Identity Token is identical to the one that was specified in the authentication request.
    - [x] `nonce` does't match: ConfigurationUseNonceTests_useNonce_true_nonceDoesntMatch (FAT)
    - [x] `nonce` matches: ConfigurationUseNonceTests_useNonce_true (FAT)

**Comment by ayoho** [comment]
The rest of the validation steps should be getting finished in https://github.com/OpenLiberty/open-liberty/pull/24358.
