### ISSUE TITLE
Security 3.0: Update OidcHttpAuthenticationMechanism to use OidcClientCore's Storage Subsystem to store full request

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/open-liberty#21164]
Task: Update OidcHttpAuthenticationMechanism to use OidcClientCore's Storage Subsystem to store full request. Create an HttpAuthenticationMechanism interceptor implementation to automatically restore request using stored request.

Spec section: https://github.com/jakartaee/security/blob/master/spec/src/main/asciidoc/authenticationMechanism.adoc#authentication-dialog

> Additionally, if OpenIdAuthenticationMechanismDefinition.redirectToOriginalResource is set to 'true' and the authentication flow is container-initiated (as opposed to caller-initiated authentication) the authentication mechanism must store the full request as well. The full request here means all data that makes up the HttpServletRequest so that the container can restore this request later on in a similar way to how the "[LoginToContinue Annotation](https://github.com/jakartaee/security/blob/master/spec/src/main/asciidoc/authenticationMechanism.adoc#logintocontinue-annotation)" behaves.

**Comment by ayoho** [comment]
We may have to look to see whether we have a test for this scenario, specifically ensuring we have one that drives a container-initiated flow.

**Comment by jimmy1wu** [comment]
we have tests for `redirectToOriginalResource=true`:
https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.security.jakartasec.3.0.internal_fat/fat/src/io/openliberty/security/jakartasec/fat/tests/BasicOIDCAnnotationUseRedirectToOriginalResourceTests.java

however, they are all container-initiated. we'll need a test for caller-initiated (the full request should _not_ be stored if redirectToOriginalResource=true and it is caller-initiated).

> Additionally, if OpenIdAuthenticationMechanismDefinition.redirectToOriginalResource is set to 'true' and the authentication flow is container-initiated (as opposed to caller-initiated authentication) the authentication mechanism must store the full request as well.

**Comment by ayoho** [comment]
Chris is working on finishing up tests for this.

**Comment by ayoho** [comment]
Remaining tests were delivered in https://github.com/OpenLiberty/open-liberty/pull/24446.
