### ISSUE TITLE
Security 3.0: Update OidcClientCore Client to support conditional values for the Authentication Request

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/open-liberty#21161]
Task: Update OidcClientCore Client to support conditional values for the Authentication Request.

Spec section: https://github.com/jakartaee/security/blob/master/spec/src/main/asciidoc/authenticationMechanism.adoc#authentication-dialog

> The following values need to be passed to this endpoint conditionally:
> 
> - Nonce, must be generated by the authentication mechanism if OpenIdAuthenticationMechanismDefinition.useNonce is set to true
> - Response Mode value as taken from OpenIdAuthenticationMechanismDefinition.responseMode if defined
> - Display value as taken from OpenIdAuthenticationMechanismDefinition.display if defined
> - Prompt value as taken from OpenIdAuthenticationMechanismDefinition.prompt if defined
> - Extra values as taken from OpenIdAuthenticationMechanismDefinition.extraParameters if defined

**Comment by ayoho** [comment]
- Nonce: `useNonce` is true by default, so most (if not all) of our tests will already be passing in a nonce value
- Response mode: Does not appear to be tested
- Display: ConfigurationTests_maximumAnnotation sets `display = DisplayType.PAGE`
- Prompt: Does not appear to be tested
- Extra values: Does not appear to be tested

**Comment by jimmy1wu** [comment]
fat tests have been added for all conditional values:

- useNonce: https://github.com/OpenLiberty/open-liberty/pull/23683
- responseMode: https://github.com/OpenLiberty/open-liberty/pull/23648
- display: https://github.com/OpenLiberty/open-liberty/pull/24059
- prompt: https://github.com/OpenLiberty/open-liberty/pull/23990
- extraParameters: https://github.com/OpenLiberty/open-liberty/pull/23879

view associated pr for a summary of the fat test scenerios.
