### ISSUE TITLE
Security 3.0: Update OidcClientIdentityStore to create CredentialValidationResult

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/open-liberty#21173]
Task: Update OidcClientIdentityStore to create CredentialValidationResult with extracted caller name and groups.

Spec section: https://github.com/jakartaee/security/blob/master/spec/src/main/asciidoc/authenticationMechanism.adoc#caller-name-and-groups

> The Caller Name and optionally any Caller Groups provided by the OpenID Connect Provider must be present in the CredentialValidationResult that is returned by the implementation specific identity store that validates the Credential holding the Token Response as mentioned above.

**Comment by ayoho** [comment]
I believe this is being adequately tested in the normal positive test cases, the [ConfigurationUserInfoTests FATs](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationUserInfoTests.java), and the [IdentityStoreTests FATs](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.security.jakartasec.3.0.internal_fat/fat/src/io/openliberty/security/jakartasec/fat/tests/IdentityStoreTests.java).
