### ISSUE TITLE
Security 3.0: Update OidcClientCore's Logout Subsystem with a CustomLogoutStrategy

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/open-liberty#21179]
Task: Update OidcClientCore's Logout Subsystem with a CustomLogoutStrategy to redirect to the chosen redirectURI in addition of performing the LocalLogoutStrategy.

Spec section: https://github.com/jakartaee/security/blob/master/spec/src/main/asciidoc/authenticationMechanism.adoc#logout

> - Redirect to OpenIdAuthenticationMechanismDefinition.logout.redirectURI if OpenIdAuthenticationMechanismDefinition.logout.notifyProvider is set to false and OpenIdAuthenticationMechanismDefinition.logout.redirectURI is defined

**Comment by utle** [comment]
Fixed by #22580
