### ISSUE TITLE
Security 3.0: Update OidcClientIdentityStore to extract caller name and groups from tokens

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/open-liberty#21171]
Task: Update OidcClientIdentityStore to extract caller name and groups from tokens.

Spec section: https://github.com/jakartaee/security/blob/master/spec/src/main/asciidoc/authenticationMechanism.adoc#caller-name-and-groups

> The claim name that is used to define the Caller Name and optionally the Caller Groups from the OpenID Connect Provider can be defined by the following attributes:
> 
> - Caller Name: OpenIdAuthenticationMechanismDefinition.claimsDefinition.callerNameClaim
> - Caller Groups: OpenIdAuthenticationMechanismDefinition.claimsDefinition.callerGroupsClaim.

> The following logic is used to determine the value of each;
> 
> - If the specified claim exists and has a non-empty value in the Access Token, this Access Token claim value is taken.
> - If not resolved yet, and the specified claim exists and has a non-empty value in the Identity Token, this Identity Token claim value is taken.
> - If not resolved yet, and the specified claim exists and has a non-empty value in the User Info Token, this User Info Token claim value is taken.

**Comment by ayoho** [comment]
I believe this is being adequately tested in the normal positive test cases, the [ConfigurationUserInfoTests FATs](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.security.jakartasec.3.0.internal_fat.config/fat/src/io/openliberty/security/jakartasec/fat/config/tests/ConfigurationUserInfoTests.java), and the [IdentityStoreTests FATs](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.security.jakartasec.3.0.internal_fat/fat/src/io/openliberty/security/jakartasec/fat/tests/IdentityStoreTests.java).
