### ISSUE TITLE
Security 3.0: Create OidcClientCore Logout Subsystem

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/open-liberty#21177]
Task: Create OidcClientCore Logout Subsystem with a LocalLogoutStrategy that simply calls request.logout() to invalidate the HTTP Session. Update OidcHttpAuthenticationMechanism's cleanSubject() to delegate to OidcClientCore's Client to perform a Logout.

Spec section: https://github.com/jakartaee/security/blob/master/spec/src/main/asciidoc/authenticationMechanism.adoc#logout

> The cleanSubject method of the authentication mechanism has the following requirements

...

> - Invalidate the HTTP Session, if one is available

**Comment by utle** [comment]
Fixed by #22580

**Comment by teddyjtorres** [comment]
Reopening since the OidcHttpAuthenticationMechanism's cleanSubject() still needs to delegate to OidcClientCore's Client to perform a Logout.

**Comment by teddyjtorres** [comment]
There is still issue https://github.com/OpenLiberty/open-liberty/issues/24062 with logout.

**Comment by ayoho** [comment]
Re-closing now that https://github.com/OpenLiberty/open-liberty/issues/24062 is resolved.
