### ISSUE TITLE
Security 3.0: Implement OidcClientCore's Token Refresh

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/open-liberty#21175]
Task: Implement OidcClientCore's Token Refresh. Update OidcHttpAuthenticationMechanism to use OidcClientCore's Client to perform Token Refresh up to obtaining token but no token validation. Update OidcHttpAuthenticationMechanism to delegate token validation after token refresh to the IdentityStoreHandler if token refresh call was successful.

Spec section: https://github.com/jakartaee/security/blob/master/spec/src/main/asciidoc/authenticationMechanism.adoc#token-expiration

> - The token is refreshed when OpenIdAuthenticationMechanismDefinition.tokenAutoRefresh set to true
...

> In the case a refresh of the token is needed, the OpenID Connect provider refreshToken endpoint has to be called with the following parameters
> 
> - The ClientId value as taken from OpenIdAuthenticationMechanismDefinition.clientId
> - The ClientSecret value as taken from OpenIdAuthenticationMechanismDefinition.clientSecret 
> - The grant_type value set to the constant refresh_token
> - the refresh_token value set to the previously stored value from the refresh_token field of the Token Response

> When the call is successful and a new Access Token is received, the same logic is applied as described above;
> 
> - Validate tokens
> - Store in context
> - Determine the caller Name and Caller groups values (which can lead to more or less permissions in the application)

**Comment by utle** [comment]
Fixed by #22583
