### ISSUE TITLE
Security 3.0: Update OidcClientCore's Logout Subsystem to start a new Authentication Request

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/open-liberty#21180]
Task: Update OidcClientCore's Logout Subsystem to start a new Authentication Request.

Spec section: https://github.com/jakartaee/security/blob/master/spec/src/main/asciidoc/authenticationMechanism.adoc#logout

> - Redirect to the OpenID Connect Provider Authentication endpoint for re-authentication if the previous two conditions don’t hold. Be aware that a correct promptType must be defined so that this option works properly. Without any prompt defined, the Openid Connect Provider can immediately redirect to the callback (value of OpenIdAuthenticationMechanismDefinition.redirectURI) of the application and the end-user (caller) is then again authenticated within the application, effectively making logging out impossible.

**Comment by utle** [comment]
Fixed by #22580
