### ISSUE TITLE
WebProfile Transaction with checkpoint

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#21198]
Issue to track support of the transaction feature with checkpoint.

Need to investigate the impact of checkpoint/restore on transaction manager.  For example, we will need to ensure no active transactions are present when doing a checkpoint.  I believe such a transaction would not be able to be restored properly into multiple instances of the server.

See checklist to help evaluate work needed for checkpoint: https://github.com/OpenLiberty/open-liberty/issues/18664#issuecomment-1146218456

**Comment by tjwatson** [comment]
For the initial release of checkpoint we should look to prevent any transaction from getting initiated on the checkpoint side.  If there are valid use cases to have a transaction start and complete within a checkpoint image we need to understand such use cases before thinking of enabling transactions to be initiated on the checkpoint side.

We need to have tests that validate transactions can be initiated after the Liberty process is restored.

**Comment by tjwatson** [comment]
I'm closing this issue as it was tracking the work for the initial release of InstantOn.  Follow on transactions work will happen with a separate issue.

**Comment by dazavala** [comment]
Thank you, @tjwatson
