### ISSUE TITLE
Repeat Session FATs for Jakarta EE10

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#21200]
The following FAT buckets need to be executed for Jakarta EE10 (Servlet 6.0):

1. `com.ibm.ws.session.cache_fat` -> DONE
2. `com.ibm.ws.session.cache_fat_config` -> DONE
3. `com.ibm.ws.session.cache_fat_config_infinispan`-> not required
4. `com.ibm.ws.session.cache_fat_infinispan` -> not required
5. `com.ibm.ws.session.cache_fat_infinispan_container` ->DONE

An example of enabling a FAT bucket for Jakarta EE 10 can be found here:  https://github.com/OpenLiberty/open-liberty/pull/20639/files

**Comment by pnicolucci** [comment]
@zhang-ca it looks as though we're running all of the repeats in lite mode. We should try to avoid this and only run the latest feature set in lite mode and the other repeats in full mode. I'm working on a pull request for this and I'll send you a review so we can discuss it further next week.

**Comment by pnicolucci** [comment]
Link to the Open Liberty test documentation: https://github.com/OpenLiberty/open-liberty/wiki/FAT-Tests#repeating-fat-tests-for-different-featurejee-levels

> It is recommended that only the latest version of a feature should be tested in LITE mode. Other versions should only be repeated in FULL mode.

**Comment by zhang-ca** [comment]
Thanks for the Java level changes.
Reviewed the two buckets `com.ibm.ws.session.cache_fat_config_infinispan` &
`com.ibm.ws.session.cache_fat_infinispan` which didn't depends on the servlet tested.features and they didn't execute on EE9. So we will not execute them on EE10.

**Comment by pnicolucci** [comment]
All work is completed.
