### ISSUE TITLE
Checkpoint - MicroProfile fault tolerance @Timeout annotation

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#21235]
The `@Timeout` annotation can be used on a method to specify a specific timeout.  If there is user application code running during a `checkpoint` operation (with `--at=applications`) then it may be possible that a thread is in the middle of calling a method annotated with `@Timeout`.  If this occurs then it seems very likely the timeout will pass before the process resumes on restore.  What should happen for this scenario?  Some possibilities:

1. Fail at checkpoint if we detect any threads in the middle of a method call annotationed with `@Timeout`
2. Just let the method pause during the checkpoint.  On restore the timeout may have passed causing an immediate `TimeoutException` to occur.
3. Depending on how the timeout is calculated it may omit the delta of time "missed" between the checkpoint and restore operation.  For example, if `System.nanoTime` is used then the JVM is going to omit the "missed" time when `System.nanoTime` is called again.  On the other hand, if this is placed on some ScheduledExecutor that runs at the specified timeout then we need to see that the executor behaves correctly.

For simplicity I think it makes some sense to fail checkpoint if a method is in the middle of an `@Timeout` method.

**Comment by Azquelt** [comment]
The job of triggering the timeout is delegated to a scheduled executor: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/TimeoutStateImpl.java#L51

The scheduled task is a call to a method on the same class, so we would be able detect whether a checkpoint has happened and act accordingly, if the scheduled executor does run the task immediately after resuming the checkpoint.

I note that we also log a metric of how long the task took using `System.nanoTime`, I guess we might want to discard that.

**Comment by tjwatson** [comment]
> The job of triggering the timeout is delegated to a scheduled executor: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.faulttolerance.2.0/src/com/ibm/ws/microprofile/faulttolerance20/state/impl/TimeoutStateImpl.java#L51

Open J9 will be fixing the implementations of `java.util.concurrent.ScheduledExecutorService` that the JVM provides to correctly handle the "gap" time between checkpoint and restore such that the delays and periods behave appropriately.  For example, if you are into 1 minute of a 2 minute period and a checkpoint is done the on restore it will correctly determine that 1 minute still remains in the period.

> 
> The scheduled task is a call to a method on the same class, so we would be able detect whether a checkpoint has happened and act accordingly, if the scheduled executor does run the task immediately after resuming the checkpoint.
> 
> I note that we also log a metric of how long the task took using `System.nanoTime`, I guess we might want to discard that.

Open J9 is fixing nano time so that it correctly discards the "gap" time between the checkpoint and the restore.

Regardless of that I think the best initial support for this should detect that a timed method is getting entered on the checkpoint side and simply fail the checkpoint when this happens.  I think that will be the most simple thing to support initially.  If we find there are valid use cases where the execution of a timed method on the checkpoint side makes sense then we can enhance this to allow for that.

**Comment by tjwatson** [comment]
Testcase has been added that verifies option 3 from the description:

> Depending on how the timeout is calculated it may omit the delta of time "missed" between the checkpoint and restore operation. For example, if System.nanoTime is used then the JVM is going to omit the "missed" time when System.nanoTime is called again. On the other hand, if this is placed on some ScheduledExecutor that runs at the specified timeout then we need to see that the executor behaves correctly.

Nothing else is planned here for initial InstantOn release.
