### ISSUE TITLE
Checkpoint - MicroProfile Reactive Messaging connections

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#21236]
If an application is using MicroProfile Reactive messaging then during application startup the server implementation may attempt to make a connection to the configured messaging server.  This type of connection cannot be made successfully during a `checkpoint` operation.  One of the following possibilities may help ensure this is handled correctly for restoring a process that uses MP Reactive Messaging

1. Detect a checkpoint is happening and do not connect to the messaging server until restore
2. Fail checkpoint if reactive messaging server connection is attempted before the checkpoint happens
3. Close the possible connection on checkpoint.  On restore re-establish the connection based on the current configuration.

**Comment by tjwatson** [comment]
The initial release of #16384 Liberty checkpoint feature will not include MicroProfile Reactive Messaging.

**Comment by abutch3r** [comment]
This is being worked on under #26220 - this will add InstantOn support for Reactive Messaging 3.0, it will not be ported to Reactive Messaging1.0

**Comment by tjwatson** [comment]
I'm closing this issue since I don't think we have a need to track Reactive Messaging 1.0 for InstantOn.
