### ISSUE TITLE
Update Zipkin sample to be compatible with Jakarta EE 9

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#21242]
- Update Zipkin sample to be compatible with Jakarta EE 9

@gkwan-ibm mentioned the user feature should be installed in a new way.  Gilbert please provide the details.

**Comment by gkwan-ibm** [comment]
Following is the new way:
- the user feature esa and bom files are located at the Maven repo
- run liberty:prepare-feature
  - the esa and bom files will be downloaded to local
  - LMP will generate the json file
- run liberty:run/dev
  - the user feature will be installed

Of course, the pom.xml should have the required configuration.

References:
- https://openliberty.io/blog/2021/10/29/kube-secrets-210011.html#user_features
- https://github.com/OpenLiberty/ci.maven/blob/main/docs/prepare-feature.md
- https://github.com/OpenLiberty/ci.maven/blob/main/docs/install-feature.md
- draft blog: https://github.com/OpenLiberty/blogs/blob/userFeature/posts/2022-03-11-user-feature-install.adoc

**Comment by fmhwong** [comment]
@gkwan-ibm Do we just need to install the user feature with Maven only or we need to install it with the traditional way too?

**Comment by gkwan-ibm** [comment]
I expect the mp-opentracing guide will use the new way

**Comment by fmhwong** [comment]
@gkwan-ibm What do you plan to use this sample with?  Since MicroProfile is planning to remove OpenTracing from the platform in release 6.0, not sure we want to invest more in it.

**Comment by gkwan-ibm** [comment]
@fmhwong when will it happen? And will microprofile-opentracing-jaeger also be affected?

**Comment by gkwan-ibm** [comment]
If it will happen in next year, I think it is worth to do.

cc @yeekangc, what is your opinion?

**Comment by fmhwong** [comment]
AFAIK, MicroProfile 6 is planning to be released in 4Q 2022.  MicroProfile Telemetry 1.0 is planning to be released in June and implementation will follow.

**Comment by gkwan-ibm** [comment]
OL still supports MP5 and the guide won't be deprecated/removed shortly. I think it still worth to update the Zipkin sample to be compatible with Jakarta EE 9 and the guide

**Comment by gkwan-ibm** [comment]
hi @fmhwong, for my [comment](https://github.com/OpenLiberty/open-liberty/issues/21242#issuecomment-1152426161), any plan to address this issue?

**Comment by fmhwong** [comment]
> hi @fmhwong, for my [comment](https://github.com/OpenLiberty/open-liberty/issues/21242#issuecomment-1152426161), any plan to address this issue?

@gkwan-ibm , Anthony is working on this.

**Comment by fmhwong** [comment]
@gkwan-ibm We have created release 3.0 RC1 and it is available at
https://github.com/WASdev/sample.opentracing.zipkintracer/releases/tag/3.0-RC1
https://mvnrepository.com/artifact/net.wasdev.wlp.tracer/liberty-opentracing-zipkintracer/3.0-RC1

**Comment by fmhwong** [comment]
Release 3.0 created.
https://github.com/WASdev/sample.opentracing.zipkintracer/releases/tag/3.0
