### ISSUE TITLE
Admin Center upgrade bootstrap

### ISSUE THREAD

**Issue by k8vance88** [OpenLiberty/open-liberty#21243]
The upgrade isn't as simple as updating the Jars. There are some changes to our CSS that will need to be made. 

1 issue is with .sr_only needs to be migrated to a different CSS class. I suspect there will be other minor issues as well.

**Comment by k8vance88** [comment]
Sarin, I started this with this PR: https://github.com/OpenLiberty/open-liberty/pull/21506

I do not plan to deliver this PR.  Use the code in it to get started on this issue. Updating to the latest bootstrap breaks the UI look and feel.  

To get started pull my code and build it. Then open the server config tool and start testing. See this doc:
https://getbootstrap.com/docs/5.0/migration/

For sure we are hit by the .sr_only change.

**Comment by sarinjacobsunny** [comment]
OL PR - https://github.com/OpenLiberty/open-liberty/pull/21611
WS-CD-Open PR - https://github.ibm.com/websphere/WS-CD-Open/pull/27320

**Comment by sarinjacobsunny** [comment]
Merged PRs,
- https://github.ibm.com/websphere/WS-CD-Open/pull/27382
- https://github.com/OpenLiberty/open-liberty/pull/21611
- https://github.ibm.com/websphere/WS-CD-Open/pull/27329
