### ISSUE TITLE
Improve JPA FAT to enable more LITE testing

### ISSUE THREAD

**Issue by dazey3** [OpenLiberty/open-liberty#21260]
Recently, the JPA FAT had some test failures that only showed up in FULL FAT testing. The personal builds only run the JPA FAT in LITE mode, but most of the JPA FAT is FULL. That is because the JPA FAT has a very long runtime; too long for LITE. However, we could enable some portion of the existing testing for LITE testing mode. Doing this would help catch changes that break JPA without requiring a FULL FAT run.

- [x] [com.ibm.ws.jpa.tests.beanvalidation_fat](https://github.com/OpenLiberty/open-liberty/pull/21261)
- [x] [com.ibm.ws.jpa.tests.jpaconfig_fat](https://github.com/OpenLiberty/open-liberty/pull/21261)
- [x] [com.ibm.ws.jpa.tests.spec10.entity_fat](https://github.com/OpenLiberty/open-liberty/pull/21261)
- [x] [com.ibm.ws.jpa.tests.spec10.query_fat](https://github.com/OpenLiberty/open-liberty/pull/21261)

**Comment by tkburroughs** [comment]
Now part of framework; will be propagated to new FAT. Closing out.,
