### ISSUE TITLE
Verify that mpMetrics grafana dashboard works with latest mpMetrics versions

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#21268]
https://github.com/OpenLiberty/open-liberty-operator/blob/main/doc/observability-deployment.adoc refers to mpMetrics 2.3.  We need to verify that this works the same way with mpMetrics-4.0 and update the doc accordingly.  

Similarly we need to update the description at https://grafana.com/grafana/dashboards/11706

**Comment by Channyboy** [comment]
Link: https://grafana.com/grafana/dashboards/11706

Overview page has been updated to include mpMetrics-4.0 and the Grafana versions tested at 8.0.x and 8.5.x.
Instructions also updated to refer to `mpMetrics-4.0`.
