### ISSUE TITLE
Suggestion : Is it possible to have a GA Features that only contains Jakarta EE 9/Web Profile 9/MicroProfile 5 

### ISSUE THREAD

**Issue by RuiBaiXYZ** [OpenLiberty/open-liberty#21272]
Dear OpenLiberty team, Is it possible to split **All GA Features** to 
e.g. **GA Features 8** that only contains Jakarta EE 8/Web Profile 8/MicroProfile 4 
e.g. **GA Features 9** that only contains Jakarta EE 9/Web Profile 9/MicroProfile 5 

This will be useful for our production deploy, such as reduce the container size, pure Jakarta EE 9/MicroProfile 5 environment.

Looking forward to your kind reply.

**Comment by tevans78** [comment]
The Jakarta EE 9 package contains Jakarta EE 9/Web Profile 9/MicroProfile 5
The Jakarta EE 8 package contains Jakarta EE 8/Web Profile 8 ... and all MicroProfile versions from 1.3 through to 4.1.

However, for production deployment, I would recommend that you start with just the kernel and add in the only the features that you really need. One way to do that is using the `featureUtility` command https://openliberty.io/docs/latest/reference/command/featureUtility-commands.html

**Comment by RuiBaiXYZ** [comment]
@tevans78 Got it.  I am grateful for your reply and help.

So close this issue.
