### ISSUE TITLE
mpOpenTracing Performance - serverSkipPattern lookup.

### ISSUE THREAD

**Issue by jdmcclur** [OpenLiberty/open-liberty#21287]
With mpOpenTracing enabled, we currently spend time getting the serverskippatterm. This is somewhat slow because we're looking into mpConfig, which has to look for the property in all its config sources. It is worse when the property is null. It would be great if we didn't look for this on every request, and could cache it somehow, even if it's temporary. Or, at least consider doing it for Open Telemetry if it applies there.

https://github.com/OpenLiberty/open-liberty/blob/6356b6cc4047f0ff622f130261a706c761ca31fb/dev/io.openliberty.opentracing.2.0.internal/src/io/openliberty/opentracing/internal/OpentracingConfiguration.java#L27

```
Parent      0   0.03   2.99           2         193    J:io/openliberty/opentracing/internal/OpentracingService.process(Ljava/net/URI;Ljava/lang/String;Lio/openliberty/opentracing/internal/filters/SpanFilterType;)Z
 
    Self      0   0.03   2.99           2         193    J:io/openliberty/opentracing/internal/OpentracingConfiguration.getServerSkipPattern()Ljava/lang/String;
 
   Child      0   0.05   2.14           3         138    J:io/smallrye/config/SmallRyeConfig.getOptionalValue(Ljava/lang/String;Ljava/lang/Class;)Ljava/util/Optional;
   Child      0   0.00   0.82           0          53    J:org/eclipse/microprofile/config/ConfigProvider.getConfig(Ljava/lang/ClassLoader;)Lorg/eclipse/microprofile/config/Config;
   ```

**Comment by fmhwong** [comment]
@jdmcclur Since we will GA mpTelemetry-1.0 soon in 2023 and mpOpenTracing features will be stabilized.  Do you still want to pursuit this?

**Comment by fmhwong** [comment]
Close this as mpTelemetry-1.0 will be GAed in 23.0.0.3 and mpOpenTracing features will be stabilized.
