### ISSUE TITLE
Review `jakarta.servlet.resources` for Servlet 6.0

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#21300]
Servlet 5.0: https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.jakarta.servlet.5.0/src/jakarta/servlet/resources

Servlet 6.0: https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.jakarta.servlet.6.0

Servlet 6.0 does not include the additional resources that we normally include. There should be a JSP dependency on these that we'll find as we continue to do more testing.

**Comment by volosied** [comment]
As I transform com.ibm.ws.jsp for Tags 3.0 / Pages 3.1, I am encountering bundle resolution problems due this missing package. 

Update : Might just transformation version problems instead...


For easy reference where the files are used: https://github.com/OpenLiberty/open-liberty/blob/2fd4a880754c37a988c5ed9ac4f1ea5988e465d6/dev/com.ibm.ws.jsp/src/com/ibm/ws/jsp/taglib/TldParser.java#L68-L81
