### ISSUE TITLE
MicroProfile Rest Client with checkpoint

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#21314]
See checklist to help evaluate work needed for checkpoint: https://github.com/OpenLiberty/open-liberty/issues/18664#issuecomment-1146218456

**Comment by tjwatson** [comment]
In particular we need to check how the config is read for the rest client.  See https://download.eclipse.org/microprofile/microprofile-rest-client-2.0/microprofile-rest-client-spec-2.0.html#mpconfig

**Comment by tjwatson** [comment]
@KeenanMcCarthy can you update this issue with a description of what is tested for MicroProfile Rest Client?

**Comment by KeenanMcCarthy** [comment]
This application invokes a rest client proxy that queries an endpoint defined by the "test client" system variable. Initially this variable is set to a default endpoint and returns a default value. After the default value is confirmed, the server is checkpointed and the system variable is changed to an alternate value. Following restore, the rest client is invoked and the alternate endpoint is queried, then reset to the default through a POST request. However, in instances where the rest client is initialized at startup, the configuration change does not persist through checkpoint. This test is repeated for both Java 8 and Java 9.
