### ISSUE TITLE
WebProfile appSecurity with checkpoint

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#21319]
See checklist to help evaluate work needed for checkpoint: https://github.com/OpenLiberty/open-liberty/issues/18664#issuecomment-1146218456

**Comment by anjumfatima90** [comment]
The FAT tests if authorization and authentication provided by appsecurity works with checkpoint and restore. It also tests the update in authentication and authorization of users done after checkpoint and before restore is reflected during restore. If the user password was updated or when an unauthorized user was given authorization, the test confirms that the update in config was reflected during restore.
