### ISSUE TITLE
MicroProfile OpenTracing with checkpoint

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#21312]
See checklist to help evaluate work needed for checkpoint: https://github.com/OpenLiberty/open-liberty/issues/18664#issuecomment-1146218456

**Comment by tjwatson** [comment]
@anjumfatima90 Can you describe a the testing done for OpenTracing?

**Comment by anjumfatima90** [comment]
MicroProfile OpenTracing enables distributed tracing in microservices. Jaeger is an open source distributed tracing system that is compatible with the OpenTracing specification. The FAT test checks if spans are created across multiple servers. A span is a logical unit of work in Jaeger, which includes the name, starting time and duration of the operation. The trace instance can be configured using the environment variables and the FAT tests if the configuration change done after the checkpoint and before restore is positively reflected during restore. 
Previously, the server is configured with environment variables 
```JAEGER_SAMPLER_TYPE=const
JAEGER_SAMPLER_PARAM=1
```
Just before the restore, the configuration is changed to
```JAEGER_SAMPLER_TYPE=const
JAEGER_SAMPLER_PARAM=0
```
The tests make sure that the restore logs contain the message which indicates the sampler.param was changed. Checkpoint is done at application phase which means the trace config can be modified after the application has started. 

Note: The tests doesn't do a detail testing for different jaeger configurations listed [here](https://github.com/jaegertracing/jaeger-client-java/tree/master/jaeger-core#configuration-via-environment).
