### ISSUE TITLE
WebProfile jpa / persistence with checkpoint

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#21332]
See checklist to help evaluate work needed for checkpoint: https://github.com/OpenLiberty/open-liberty/issues/18664#issuecomment-1146218456

**Comment by sebratton** [comment]
This is an epic with only one sub-issue. Decided to close it any track the sub issue.

**Comment by tjwatson** [comment]
Removed label, not going to track this as part of InstantOn project.
