### ISSUE TITLE
WebProfile ssl with checkpoint

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#21342]
For checkpoint the ssl configuration needs to be able to come in on the restore side.  In particular we need to make sure that in-container tls configuration works as described at https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/

See checklist to help evaluate work needed for checkpoint: https://github.com/OpenLiberty/open-liberty/issues/18664#issuecomment-1146218456

**Comment by tjwatson** [comment]
@anjumfatima90 I assigned to you for now because you already added a testcase for SSL and have some investigations on how we can get the SSL initialization to happen on the restore side.  This has an added complication that we need to re-check ssl configuration on the restore side before bringing up the SSL stack in liberty.

**Comment by dettmoney** [comment]
https://github.com/OpenLiberty/open-liberty/pull/21210 is a performance prototype that reduces restore response times. It involves  pre-initializing the default SSLSocketFactory. There's a chance that will not be possible in light of this work to move ssl configuration to the restore side.
