### ISSUE TITLE
Automated tests for customization

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty#2134]
Include automated tests to ensure the functionality of customization is working as expected (initial pickup of customization files, file monitoring, restoring to default, etc).

Some of the the tests logic from openapi-3.0 can be reused.

Ensure there is no caching issues (UI is customized --> server is stopped and customization file is removed --> start server --> UI should be default).

**Comment by mrglavas** [comment]
This PR resolves this issue: https://github.com/arturdzm/open-liberty/pull/65 and has been merged into the team's collaboration branch.
