### ISSUE TITLE
Feature Test Summary - LG-324 (JUL) logged exceptions through parameters 

### ISSUE THREAD

**Issue by Channyboy** [OpenLiberty/open-liberty#21369]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

### List of FAT projects affected

* com.ibm.ws.logging.json_fat
* com.ibm.ws.logstash.collector_fat

### Test strategy

* What functionality is new or modified by this feature?

**This new functionality to the JSON logging introduces 2 new fields to the JSON log record (for messages and trace events) if the originating log statement received a `Throwable` as part of the logging methods parameters (e.g. `log(Level level, String msg, Throwable thrown)`. If a `Throwable` is detected as part of the log record then the following two fields are introduced `ibm_stackTrace` and `ibm_exceptionName`. The former field will present the stack trace as the value and the latter will present the type of exception. as the value Prior to the introduction of this functionality, the stack trace would've been appended to the logging statement's message under the `message` JSON field. This improvement allows for better log analysis by third party log analysis systems. Additionally, the logstash collector's feature (`logstashCollector-1.0`) JSON output also has been updated to include this functionality. For the Logstash JSON output however, the fields are `stackTrace` and `exceptionName` instead. The difference here is for consistency in terms of naming conventions for the existing  logstashCollector-1.0 feature's JSON output (i.e. no `ibm_` prefix.**
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)

**The tests for both the logging `com.ibm.ws.logging.json_fat` and `com.ibm.ws.logstash.collector_fat` include new tests to generate a logging statement from the application using three of the available JUL logging methods that takes parameters. Each JUL issued log has a different message. The tests then check for the existence of the JSON log records that contain the distinct messages and also  check for the two new fields contain the appropriate values relative to the `Throwable` was logged in the application.**

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

 **No manual tests**

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

4

**Comment by Channyboy** [comment]
Related to #17559

**Comment by ayoho** [comment]
Coverage sounds ok to me 👍
