### ISSUE TITLE
GA BLOG - Improve DB2 query performance on EclipseLink by altering parameter binding behavior

### ISSUE THREAD

**Issue by dazey3** [OpenLiberty/open-liberty#21380]
1. Which Liberty feature(s) does your update relate to?
    
   This feature is an enhancement to the following features:
    Java Persistence 2.1 (jpa-2.1)

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.

application developers

3. Write a paragraph to summarizes the update, including the following points:
   
This new JPA enhancement improves EclipseLink's DB2 and DB2 z/OS support by enabling parameter binding for JPA specification defined functions.

For DB2 and DB2 for z/OS, EclipseLink’s JPQL parameter binding is disabled when function expressions (SQRT, ABS, SUBSTR, COALESCE, etc.) exist within a JPQL query. This feature will allow EclipseLink to bind JPQL parameters for function expressions that accept untyped parameter markers on DB2 and DB2 z/OS. 
This feature will also allow EclipseLink to enable/disable parameter binding per expression, within a query, rather then for the whole of the query.

For DB2 and DB2 for z/OS, EclipseLink does not bind JPQL literal values as SQL parameter values. An EclipseLink specific persistence property currently exists `("shouldBindLiterals=true")` to allow EclipseLink users to bind all literal values as parameter values. For DB2 and DB2 for z/OS, this property is currently ignored by EclipseLink.
This feature will allow for the usage of the “shouldBindLiterals=true” EclipseLink persistence property to bind literals values as parameters on DB2 and DB2 z/OS; assuming it is legal to do so according to the database.

In order to start using the new feature, users need only add the new persistence property `eclipselink.jdbc.allow-partial-bind-parameters` to their `persistence.xml` properties :

### Example 1:
```xml
<persistence ... >
    <persistence-unit ... >
        <properties>
            <property name="eclipselink.jdbc.allow-partial-bind-parameters" value="true"/>
        </properties>
     </persistence-unit>
</persistence>
```

Alternatively, starting on Liberty 22.0.0.2 releases, users need only add the new `<defaultProperties>` configuration to their `<jpa>` configuration, in server.xml. This will apply the persistence property `eclipselink.jdbc.allow-partial-bind-parameters` to all persistence units within applications running on this server.

### Example 2:
```xml
<server>
    <featureManager>
        <feature>jpa-2.1</feature>
    </featureManager>
    ...
    <jpa>
        <defaultProperties>
            <property name="eclipselink.jdbc.allow-partial-bind-parameters" value="true"/>
        </defaultProperties>
    </jpa>
</server>
```

------------------

In the application, the user can take advantage of this feature with JPA JPQL queries and CriteriaBuilder API queries.

### Example 1:

```java
    Query query = em.createQuery("SELECT g FROM Guest g WHERE LENGTH(?1) > 2 AND g.lastName = TRIM(?1)");
    query.setParameter(1, “Crusher”);
```

By default, EclipseLink will generate the following SQL prepared statement on DB2 and DB2 z/OS:
```sql
    SELECT FIRSTNAME, LASTNAME FROM GUEST WHERE ((LENGTH('Crusher') > 2) AND (LASTNAME = TRIM('Crusher')))
```

With the new property `eclipselink.jdbc.allow-partial-bind-parameters` = `"true"`, EclipseLink will generate the following SQL prepared statement on DB2:
```sql
    SELECT FIRSTNAME, LASTNAME FROM GUEST WHERE ((LENGTH('Crusher') > 2) AND (LASTNAME = TRIM(?)))
```
and DB2 z/OS:
```sql
    SELECT FIRSTNAME, LASTNAME FROM GUEST WHERE ((LENGTH('Crusher') > 2) AND (LASTNAME = TRIM('Crusher')))
```

*Note*: With the Feature enabled, it appears that nothing has changed for DB2 z/OS. This is because it is illegal on DB2 z/OS to use an untyped parameter marker in this LENGTH or TRIM functions. There are many other functions that it is legal to use parameter markers on DB2 z/OS, but this example was chosen to show there are differences between the platforms and, with the feature enabled, EclipseLink knows what is legal on what platform.

### Example 2:

```java
    Query query = em.createQuery("SELECT g FROM Guest g WHERE LENGTH(?1) > 2 AND g.lastName = TRIM(?1)");
    query.setParameter(1, “Crusher”);
```

By default, EclipseLink will generate the following SQL prepared statement on DB2 and DB2 z/OS:
```sql
    SELECT FIRSTNAME, LASTNAME FROM GUEST WHERE ((LENGTH('Crusher') > 2) AND (LASTNAME = TRIM('Crusher')))
```

With the new property `eclipselink.jdbc.allow-partial-bind-parameters` = `"true"`, EclipseLink will generate the following SQL prepared statement on DB2:
```sql
    SELECT FIRSTNAME, LASTNAME FROM GUEST WHERE ((LENGTH('Crusher') > 2) AND (LASTNAME = TRIM(?)))
```
and DB2 z/OS:
```sql
    SELECT FIRSTNAME, LASTNAME FROM GUEST WHERE ((LENGTH('Crusher') > 2) AND (LASTNAME = TRIM('Crusher')))
```

However, with the addition of an existing EclipseLink property
```xml
    <property name="eclipselink.target-database-properties" value="shouldBindLiterals=true"/>
```
EclipseLink will generate the following SQL prepared statement on DB2:
```sql
    SELECT FIRSTNAME, LASTNAME FROM GUEST WHERE ((LENGTH('Crusher') > ?) AND (LASTNAME = TRIM(?)))
```
and DB2 z/OS:
```sql
    SELECT FIRSTNAME, LASTNAME FROM GUEST WHERE ((LENGTH('Crusher') > ?) AND (LASTNAME = TRIM('Crusher')))
```

Notice that with the addition of the "shouldBindLiterals" property, the literal value “2” will be bound as a parameter in the SQL string. Without the feature enabled, EclipseLink cannot enable binding for some parts of the query and instead will only enable/disable for the whole query. As we can see in this example, EclipseLink can enable some parameter binding while also respecting what is legal/illegal on DB2 and DB2 z/OS

https://github.com/OpenLiberty/open-liberty/issues/17837

**Comment by mbroz2** [comment]
Published: https://openliberty.io/blog/2022/06/07/microprofile-graphql-2-22006.html#db2
