### ISSUE TITLE
Add additional details to `exposeWebInfOnDispatch` Server configuration description

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#21398]
**Describe the bug**  
The Server configuration: https://openliberty.io/docs/latest/reference/config/webContainer.html  description for `exposeWebInfOnDispatch` does not provide enough information.

**Steps to Reproduce**  
N/A

**Expected behavior**  
Add additional information to provide Open Liberty users with better information for the `exposeWebInfOnDispatch` configuration.

**Diagnostic information:**  
N/A

**Additional context**  
N/A

**Comment by mbroz2** [comment]
@pnicolucci was this meant to be marked as a `release bug`? Seems more like a documentation bug.

**Comment by pnicolucci** [comment]
@mbroz2 yea, I think we can remove the `release bug` label from this one. We only updated the metatype description with no functional change. Anything else I need to do? Thanks!
