### ISSUE TITLE
CTS: EE8: JAX-RS bucket: SseEventSource reconnect should occur even after a SseEventsink close.

### ISSUE THREAD

**Issue by jkoehler22** [OpenLiberty/open-liberty#2149]
Failed test log:

[javatest.batch] ********************************************************************************
[javatest.batch] Beginning Test:  com/sun/ts/tests/jaxrs/jaxrs21/ee/sse/sseeventsource/JAXRSClient.java#connectionLostForDefault500msTest_from_standalone
[javatest.batch] ********************************************************************************
[javatest.batch] 
[javatest.batch] 02-12-2018 15:02:02:  Harness - harness.executeMode is set to "0"
[javatest.batch] 02-12-2018 15:02:02:  Harness - keywords (to be passed to tests) set to:  all
[javatest.batch] 02-12-2018 15:02:02:  Harness - sClassPathFromExecProps = 
[javatest.batch] command: com.sun.ts.lib.harness.ExecTSTestCmd CLASSPATH=:/cts2.1/jaxrstck/bin/xml/../../lib/tsharness.jar:/cts2.1/jaxrstck/bin/xml/../../lib/javatest.jar:/cts2.1/jaxrstck/bin/xml/../../tools/ant/lib/ant.jar:/cts2.1/jaxrstck/bin/xml/../../lib/jaxrstck.jar:/cts2.1/jaxrstck/bin/xml/../../lib/jaxb-xjc.jar:/cts2.1/jaxrstck/bin/xml/../../classes:/cts2.1/java/jre/../lib/tools.jar:/cts2.1/jaxrstck/bin/xml/../../lib/commons-httpclient-3.1.jar:/cts2.1/jaxrstck/bin/xml/../../lib/commons-logging-1.1.1.jar:/cts2.1/jaxrstck/bin/xml/../../lib/commons-codec-1.3.jar:/cts2.1/jaxrstck/bin/xml/../../lib/sigtest.jar:/cts2.1/wlp/lib/com.ibm.ws.org.glassfish.json.1.1_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.kernel.service_1.3.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.jsonp.1.1_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.1.common_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.servlet.4.0_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.annotation.1.2_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.annotation.1.1_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.jaxrs.2.1_1.0.20.jar:/cts2.1/wlp/dev/api/ibm/com.ibm.websphere.appserver.api.endpoint_1.0.20.jar:/cts2.1/wlp/dev/api/ibm/com.ibm.websphere.appserver.api.basics_1.2.20.jar:/cts2.1/wlp/dev/api/ibm/com.ibm.websphere.appserver.api.servlet_1.1.20.jar:/cts2.1/wlp/dev/api/ibm/com.ibm.websphere.appserver.api.jaxrs20_1.0.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.application_1.0.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.httptransport_2.0.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.globalhandler_1.0.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.servlet_2.1.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.containerServices_2.1.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.classloading_1.4.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.anno_1.0.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.javaeedd_1.3.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.artifact_1.2.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.0.client_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.core.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.rt.rs.service.description.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.rt.rs.sse.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.tools.common.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.tools.wadlto.jaxrs.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.container.service_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.logging.osgi_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.logging_1.0.20.jar:/cts2.1/wlp/lib/org.eclipse.osgi_3.12.50.jar:/cts2.1/wlp/lib/com.ibm.json4j_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.jsonb.1.0_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.jaxb.2.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.xlxp.1.5.3_1.0.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.kernel.service_1.5.20.jar:/cts2.1/wlp/dev/api/ibm/com.ibm.websphere.appserver.api.kernel.service_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.eclipse.yasson.1.0_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.cdi.2.0_1.0.20.jar:/cts2.1/otherJars/stax2-api-3.1.4.jar:/cts2.1/otherJars/woodstox-core-asl-4.2.0.jar:/cts2.1/wlp/lib/com.ibm.ws.org.glassfish.json.1.1_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.jsonp.1.1_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.wsoc.1.1_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.0.ejb_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.1.common_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.0.beanvalidation_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.0.cdi_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.0.client_1.0.20.jar:/cts2
.1/wlp/lib/com.ibm.ws.jaxrs.2.0.ejb_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.0.managedbeans_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.0.security_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.0.server_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.0.tools_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.0.web_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.cdi_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.ejb_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.core.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.rt.rs.service.description.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.rt.rs.sse.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.tools.common.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.tools.wadlto.jaxrs.3.2_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.annotation.1.2_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.annotation.1.1_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.container.service_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.kernel.service_1.3.20.jar:/cts2.1/wlp/lib/com.ibm.ws.logging.osgi_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.logging_1.0.20.jar:/cts2.1/wlp/lib/org.eclipse.osgi_3.12.50.jar:/cts2.1/wlp/lib/com.ibm.json4j_1.0.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.kernel.service_1.5.20.jar:/cts2.1/wlp/dev/api/ibm/com.ibm.websphere.appserver.api.kernel.service_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.jsonb.1.0_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.eclipse.yasson.1.0_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.cdi.2.0_1.0.20.jar:/cts2.1/otherJars/stax2-api-3.1.4.jar:/cts2.1/otherJars/woodstox-core-asl-4.2.0.jar DISPLAY=:0.0 HOME=/root windir= SYSTEMROOT= PATH=/nativelib /cts2.1/java/jre/bin/java -Dcts.tmp=/cts2.1/jaxrstck/bin/xml/../../tmp -Djava.endorsed.dirs= -Ddeliverable.class=com.sun.ts.lib.deliverable.tck.TCKDeliverable com.sun.ts.tests.common.vehicle.VehicleClient -p /cts2.1/jaxrstck/bin/xml/../../tmp/tstest.jte -t connectionLostForDefault500msTest -vehicle standalone
[javatest.batch] ************************************************************
[javatest.batch] * props file set to "/tmp/root-cts-props.txt"
[javatest.batch] ************************************************************
[javatest.batch] 02-12-2018 15:02:02:  [JAXRSCommonClient] Test setup OK
[javatest.batch] 02-12-2018 15:02:02:  [Request] Dispatching request: 'GET http://localhost:9080/jaxrs_jaxrs21_ee_sse_sseeventsource_web/su/reset' to target server at 'localhost:9080'
[javatest.batch] 02-12-2018 15:02:02:  ###############################
[javatest.batch] 02-12-2018 15:02:03:  TRACE: [WIRE] - >> GET http://localhost:9080/jaxrs_jaxrs21_ee_sse_sseeventsource_web/su/reset
[javatest.batch] 02-12-2018 15:02:03:  TRACE: [WIRE] - >> Accept:*/*
[javatest.batch] 02-12-2018 15:02:03:  TRACE: [WIRE] - << 200 OK
[javatest.batch] 02-12-2018 15:02:03:  TRACE: [WIRE] - << Content-Language: en-US
[javatest.batch] 02-12-2018 15:02:03:  TRACE: [WIRE] - << Content-Length: 5
[javatest.batch] 02-12-2018 15:02:03:  TRACE: [WIRE] - << content-type: application/octet-stream
[javatest.batch] 02-12-2018 15:02:03:  TRACE: [WIRE] - << Date: Mon, 12 Feb 2018 20:02:03 GMT
[javatest.batch] 02-12-2018 15:02:03:  TRACE: [WIRE] - << X-Powered-By: Servlet/4.0
[javatest.batch] 02-12-2018 15:02:03:  TRACE: [WIRE] - << RESET
[javatest.batch] 02-12-2018 15:02:03:  [Request] Dispatching request: 'POST http://localhost:9080/jaxrs_jaxrs21_ee_sse_sseeventsource_web/su/lost' to target server at 'localhost:9080'
[javatest.batch] 02-12-2018 15:02:03:  ###############################
[javatest.batch] 02-12-2018 15:02:03:  [Request] Adding entity: 3
[javatest.batch] 02-12-2018 15:02:03:  TRACE: [WIRE] - >> POST http://localhost:9080/jaxrs_jaxrs21_ee_sse_sseeventsource_web/su/lost
[javatest.batch] 02-12-2018 15:02:03:  TRACE: [WIRE] - >> Accept:*/*, Content-Type:text/plain
[javatest.batch] 02-12-2018 15:02:03:  TRACE: [WIRE] - >> 3
[javatest.batch] 02-12-2018 15:02:03:  TRACE: [WIRE] - << 200 OK
[javatest.batch] 02-12-2018 15:02:03:  TRACE: [WIRE] - << Content-Language: en-US
[javatest.batch] 02-12-2018 15:02:03:  TRACE: [WIRE] - << Content-Length: 1
[javatest.batch] 02-12-2018 15:02:03:  TRACE: [WIRE] - << content-type: text/plain
[javatest.batch] 02-12-2018 15:02:03:  TRACE: [WIRE] - << Date: Mon, 12 Feb 2018 20:02:03 GMT
[javatest.batch] 02-12-2018 15:02:03:  TRACE: [WIRE] - << X-Powered-By: Servlet/4.0
[javatest.batch] 02-12-2018 15:02:03:  TRACE: [WIRE] - << 3
[javatest.batch] 02-12-2018 15:02:07:  ERROR: The message was not received
[javatest.batch] 02-12-2018 15:02:07:  ERROR: Test case throws exception: The message was not received
[javatest.batch] 02-12-2018 15:02:07:  ERROR: Exception at:  
[javatest.batch] 02-12-2018 15:02:07:  ERROR: com.sun.ts.lib.harness.EETest$Fault: The message was not received
[javatest.batch] 	at com.sun.ts.tests.jaxrs.common.JAXRSCommonClient.fault(JAXRSCommonClient.java:730)
[javatest.batch] 	at com.sun.ts.tests.jaxrs.common.JAXRSCommonClient.assertTrue(JAXRSCommonClient.java:625)
[javatest.batch] 	at com.sun.ts.tests.jaxrs.common.JAXRSCommonClient.assertNotNull(JAXRSCommonClient.java:716)
[javatest.batch] 	at com.sun.ts.tests.jaxrs.jaxrs21.ee.sse.SSEJAXRSClient.querySSEEndpoint(SSEJAXRSClient.java:50)
[javatest.batch] 	at com.sun.ts.tests.jaxrs.jaxrs21.ee.sse.SSEJAXRSClient.querySSEEndpoint(SSEJAXRSClient.java:32)
[javatest.batch] 	at com.sun.ts.tests.jaxrs.jaxrs21.ee.sse.sseeventsource.JAXRSClient.connectionLostForDefault500msTest(JAXRSClient.java:187)
[javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
[javatest.batch] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
[javatest.batch] 	at java.lang.reflect.Method.invoke(Method.java:508)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.run(EETest.java:550)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:113)
[javatest.batch] 	at com.sun.ts.tests.common.vehicle.EmptyVehicleRunner.run(EmptyVehicleRunner.java:30)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:102)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:446)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:210)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.run(EETest.java:257)
[javatest.batch] 	at com.sun.ts.tests.common.vehicle.VehicleClient.main(VehicleClient.java:27)
[javatest.batch] 
[javatest.batch] 02-12-2018 15:02:07:  [JAXRSCommonClient] Test cleanup OK
[javatest.batch] STATUS:Failed.Test case throws exception: The message was not received
[javatest.batch] Failed. Test case throws exception: The message was not received
[javatest.batch] ********************************************************************************
[javatest.batch] Finished Test:  FAILED........com/sun/ts/tests/jaxrs/jaxrs21/ee/sse/sseeventsource/JAXRSClient.java#connectionLostForDefault500msTest_from_standalone

**Comment by jkoehler22** [comment]
**Line 3939812:** [2/12/18 15:02:03:836 EST] 00000032 id=         com.ibm.ws.jaxrs21.sse.LibertySseEventSinkImpl               > <init> Entry  
                                                                                                               org.apache.cxf.jaxrs.sse.OutboundSseEventBodyWriter@7b023925
                                                                                                               {org.apache.cxf.security.SecurityContext=org.apache.cxf.transport.http.AbstractHTTPDestination$2@28af458f, org.apache.cxf.continuations.ContinuationProvider=org.apache.cxf.transport.http.Servlet3ContinuationProvider@936314a8, org.apache.cxf.message.Message.PROTOCOL_HEADERS={Accept=[*/*], Cache-Control=[no-cache], connection=[keep-alive], Content-Type=[null], Host=[localhost:9080], Pragma=[no-cache], User-Agent=[Apache-CXF/3.2.1]}, org.apache.cxf.request.url=http://localhost:9080/jaxrs_jaxrs21_ee_sse_sseeventsource_web/su/sselost, org.apache.cxf.resource.method=public void com.sun.ts.tests.jaxrs.jaxrs21.ee.sse.sseeventsource.ServiceUnavailableResource.sseLost(javax.ws.rs.sse.SseEventSink,javax.ws.rs.sse.Sse), http.base.path=http://localhost:9080/jaxrs_jaxrs21_ee_sse_sseeventsource_web, HTTP.REQUEST=com.ibm.ws.jaxrs20.server.JaxRsHttpServletRequestAdapter@4e816237, Accept=*/*, org.apache.cxf.request.uri=/jaxrs_jaxrs21_ee_sse_sseeventsource_web/su/sselost, org.apache.cxf.transport.Destination=org.apache.cxf.transport.servlet.ServletDestination@10d420b3, HTTP.CONFIG=Servlet->com.ibm.websphere.jaxrs.server.IBMRestServlet
	getClassName->com.ibm.websphere.jaxrs.server.IBMRestServlet
	getName->com.sun.ts.tests.jaxrs.jaxrs21.ee.sse.sseeventsource.TSAppConfig
	mapping->/*
	loadOnStartupWeight->-1
	getInitParameters->null or empty init parametersisAsyncSupported->true
getDescription->null
, org.apache.cxf.message.Message.PATH_INFO=/jaxrs_jaxrs21_ee_sse_sseeventsource_web/su/sselost, org.apache.cxf.transport.https.CertConstraints=null, jaxrs.template.parameters={FINAL_MATCH_GROUP=[/]}, javax.servlet.http.HttpServletResponse=com.ibm.ws.webcontainer40.srt.SRTServletResponse40@a50dd1db, org.apache.cxf.message.Message.QUERY_STRING=null, HTTP.RESPONSE=com.ibm.ws.webcontainer40.srt.SRTServletResponse40@a50dd1db, org.apache.cxf.request.method=GET, org.apache.cxf.async.post.response.dispatch=true, org.apache.cxf.message.Message.IN_INTERCEPTORS=[org.apache.cxf.transport.https.CertConstraintsInterceptor@91884d97], HTTP_CONTEXT_MATCH_STRATEGY=stem, http.service.redirection=null, org.apache.cxf.message.Message.BASE_PATH=/jaxrs_jaxrs21_ee_sse_sseeventsource_web/, path_to_match_slash=/su/sselost, org.apache.cxf.configuration.security.AuthorizationPolicy=null, org.apache.cxf.jaxrs.model.OperationResourceInfoStack=[org.apache.cxf.jaxrs.model.MethodInvocationInfo@8e69fc76], HTTP.CONTEXT=com.ibm.ws.webcontainer40.facade.ServletContextFacade40@fd9d771c, org.apache.cxf.message.Message.FIXED_PARAMETER_ORDER=false, Content-Type=null}

	**Line 3939833:** [2/12/18 15:02:03:836 EST] 00000032 id=8e219a3c com.ibm.ws.jaxrs21.sse.LibertySseEventSinkImpl               < <init> Exit  
	L**ine 3940272:** [2/12/18 15:02:03:839 EST] 00000032 id=8e219a3c com.ibm.ws.jaxrs21.sse.LibertySseEventSinkImpl               > close Entry 
	**Line 3940399:** [2/12/18 15:02:03:842 EST] 00000032 id=8e219a3c com.ibm.ws.jaxrs21.sse.LibertySseEventSinkImpl               < close Exit

**Comment by jim-krueger** [comment]
This testcase no longer fails in the official CTS run for 18.0.0.2
