### ISSUE TITLE
Restoring from checkpoint after a host system reboot fails

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#21507]
When restoring a liberty checkpoint process either on-host or in-container after the host system has rebooted will fail.  I no longer have the error message handy.  It complained about a negative delta for the initial start time calculation from restore.  This is failing in the liberty restore hooks.  From the POV of criu and OpenJ9 the process did restore correctly.  But then Open Liberty tries to calculate the overall start time and is getting confused.  I suspect this may have to do with the recent changes to OpenJ9 around fixing up nano-time.  I'm fairly certain this worked before.  This failure also implies that it will likely fail if we try to restore a checkpoint process in-container on another host machine from where the container image was built.

**Comment by anjumfatima90** [comment]
With the current jvm `20220622_54`, we are the seeing the below error when doing a restore after rebooting the host which has done a checkpoint. Although, I am not sure about the exact jvm when this error started occuring.

`[ERROR   ] CWWKC0454E: The server failed to restore from a checkpoint with the following message: A negative value calculated for checkpointRestoreTimeDelta =-300581218004
`


```
openjdk version "11.0.16-internal" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16-internal+0-adhoc.jenkins.BuildJDK11x86-64linuxcriuNightly)
Eclipse OpenJ9 VM (build master-767229ad465, JRE 11 Linux amd64-64-Bit Compressed References 20220622_54 (JIT enabled, AOT enabled)
OpenJ9   - 767229ad465
OMR      - e287e61337d
JCL      - 2cc1edf4c8e based on jdk-11.0.16+7)
```

**Comment by tjwatson** [comment]
Turns out there is an issue in the JVM restore logic with restoring nano-time.  I'll reference the OpenJ9 issue once it is opened to track.

**Comment by tjwatson** [comment]
Tracking OpenJ9 issue with eclipse-openj9/openj9#15417

**Comment by tjwatson** [comment]
This issue is fixed by OpenJ9
