### ISSUE TITLE
Checkpoint fails for acmeair applications due to LTPA configuration error

### ISSUE THREAD

**Issue by dettmoney** [OpenLiberty/open-liberty#21518]
During checkpoint of acmeair microservice applications, the following error is seen:

**[ERROR   ] CWWKS4106E: LTPA configuration error. Unable to create or read LTPA key file: /criu/20220620/wlp/usr/servers/AcmeAuth/resources/security/ltpa.keys**

LTPA processing should likely be moved to restore time to account for differences in environments between checkpoint and restore times.

**Comment by tjwatson** [comment]
can this issue be closed?
