### ISSUE TITLE
Investigate any servlet auto features that need to be updated for Jakarta EE10

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#21527]
We need to look at the same work we did in Jakarta EE9 for Jakarta EE10: https://github.com/openliberty/open-liberty/issues/12259

**Comment by tevans78** [comment]
Expect this to be resolved via https://github.com/OpenLiberty/open-liberty/issues/21577

**Comment by pmd1nh** [comment]
No auto features for servlet-6.0 public feature.

**Comment by pmd1nh** [comment]
There is no auto features that need to be updated to work with servlet-6.0 feature.
