### ISSUE TITLE
UI generated by `openapi-3.1` feature doesn't show the link specific endpoints

### ISSUE THREAD

**Issue by andrewnet** [OpenLiberty/open-liberty#21526]
When you click an endpoint in the UI that is generated by the `openapi-3.1` feature, the clicked endpoint is expanded however the URL of the browser is not changed. As the result, we cannot pass a link to a specific endpoint to others for reference. The URL of the browser is expected to change to show the link to the clicked endpoint.

This used to work in the UI that is generated by the `apiDiscovery-1.0` feature and also works in the `petstore` demo UI in https://petstore.swagger.io/#/pet/addPet. 

#### UI generated by `openapi-3.1` does not show the correct URL
![image](https://user-images.githubusercontent.com/9754967/175326096-20dc320b-a6f2-4c81-a745-c71f9f7fe4b3.png)

#### UI generated by `apiDiscovery-1.0` shows the correct URL
![image](https://user-images.githubusercontent.com/9754967/175325800-51ff7066-135d-497a-91aa-f1e7a7469716.png)

#### UI in `petstore` shows the correct URL
 
![image](https://user-images.githubusercontent.com/9754967/175325883-6bddc8bc-dc7a-4ebb-98ad-42e57dc4f36e.png)

#### Diagnostic information:

* OpenLiberty Version: 22.0.0.4
* Affected feature(s): openapi-3.1, mpOpenApi (all versions)
* Java Version:
```console
sh-4.4$ java -version
Picked up JAVA_TOOL_OPTIONS: -XX:+IgnoreUnrecognizedVMOptions -XX:+UseContainerSupport -XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)
```
* server.xml configuration

```xml
<featureManager>
    <feature>jaxrs-2.0</feature>
    <feature>ssl-1.0</feature>
    <feature>openapi-3.1</feature>
    <feature>concurrent-1.0</feature>
    <feature>monitor-1.0</feature>
    <feature>localConnector-1.0</feature>
</featureManager>
```

CC @Azquelt

**Comment by Azquelt** [comment]
Retagged as an enhancement as I'm not aware of this functionality ever being present in the `openapi-3.1` feature.

**Comment by Azquelt** [comment]
Updated the affected features list since the UI is shared with the `mpOpenApi` features.

**Comment by ilovechai** [comment]
related: https://github.com/OpenLiberty/open-liberty/issues/17573

**Comment by Azquelt** [comment]
Went back and checked, it looks like this did previously work for `openapi-3.1` but was broken by #19535 in 22.0.0.2
