### ISSUE TITLE
Improve authFilter requestUrl pattern description in metatype

### ISSUE THREAD

**Issue by pcnchang** [OpenLiberty/open-liberty#21531]
URL of concern: https://openliberty.io/docs/latest/reference/config/authFilter.html#requestUrl

From https://www.ibm.com/docs/en/was-liberty/core?topic=liberty-authentication-filters
it appears the "urlPattern" can be pipe delimited to support multiple patterns.

Please revise that open liberty page so it saves time for people to realise how to specify multiple patterns in a single authFilter -> requestUrl element.

**Comment by dmuelle** [comment]
Hi @pcnchang - thanks for this feedback. The page you cite here is part our autogenerated documentation, which is maintained by development. I'm transferring this issue to the main development repo so it can be addressed there, and the filter value descriptions can be updated to clarify that you can specify a piped list of values.

I also updated our [Open Liberty concept topic on Authentication Filters](https://docs-draft-openlibertyio.mybluemix.net/docs/latest/authentication-filters.html) to include an example of using a piped values for a filter. The updates are currently in draft but will publish to production with the next docs release.

**Comment by dmuelle** [comment]
This issue was transferred from the docs repo because the page mentioned is part of the generated doc, which is not maintained by ID. The request is to add more information to the description of `authFilter -> requestUrl element` in the metatype so that it is clear that you can specify a piped list of values. I think the same information should be added to any other `authFilter` attributes that accept a piped list, such as `webApp`.

**Comment by pcnchang** [comment]
Thank you very much, David.

**Comment by utle** [comment]
@dmuelle  The metatype.xml already have samples for webApp and requestUrl with a pipe value. How is the generated doc work and who's the owner?

Here is the metatype
```
webApp=Web Application
webApp.desc=Specifies the web application name, for example, <webApp id="sample" name="app1|app2" matchType="notContain"/>.

requestUrl=Request URL
requestUrl.desc=Specifies the HTTP request URL, for example, <requestUrl id="sample" urlPattern="/account/checking|/account/saving" matchType="contains"/>.
```

**Comment by dmuelle** [comment]
I believe if the example was not enclosed in `<brackets>`, it would appear in the doc
```
webApp=Web Application
webApp.desc=Specifies the web application name, for example, webApp id="sample" name="app1|app2" matchType="notContain".
```

```
requestUrl=Request URL
requestUrl.desc=Specifies the HTTP request URL, for example, requestUrl id="sample" urlPattern="/account/checking|/account/saving" matchType="contains".
```

**Comment by utle** [comment]
Fixed by https://github.com/OpenLiberty/open-liberty/pull/21597
