### ISSUE TITLE
Minor issues with OpenAPI JAX-RS reader

### ISSUE THREAD

**Issue by navidsh** [OpenLiberty/open-liberty#2156]
DONE:
- Support SecurityRequirementsSet annotations
- Additional Properties: Model Deserializer needs to be fixed -> ModelDeserializer
- `@GET @Path("/c/{id}") public Response C(@Parameter(ref = "User") @QueryParam("user") User user) { return null; }`
- NPE when Response.implementation() is extending HashMap
- Handling simple types for anyOf, noneOf...
- Handling simple types
- Handling Schema: merging
- RequestBody from callback
- RequestBody not being scanned when method has no parameter
- Additional Properties: Schemas were being inlined instead of ref
- Properties: Sub-schemas were being inlined instead of ref
- Request body: Not being inlined.
- ArraySchema removed
- AnnotationsUtils.getSchema(Schema, Components): type setting for simple types need to be done

**Comment by leochr** [comment]
@arturdzm please open a separate issue for the low-priority items we identified.
