### ISSUE TITLE
Missing gradlew referenced by README

### ISSUE THREAD

**Issue by jessefarinacci** [OpenLiberty/open-liberty#216]
The README instructs developers to

> Run a gradle build.
> cd open-liberty/dev
> ./gradlew cnf:initialize
> ./gradlew assemble

But we do not include the gradlew program in the repository. The `./` is saying to use the current directory `gradlew`, which isn't included. Let's include it or update the instructions to say how to install gradle and leverage it.

**Comment by cbridgha** [comment]
Hi @jessefarinacci - Can you explain what you are seeing after clone?  the files are there in the /dev folder.
We also have the /dev/.gradlewrapper that handles if your disconnected from the network.

**Comment by jessefarinacci** [comment]
I'm not seeing gradlew in the top level checkout, so if I ought to be running the one in ./dev/gradlew, I'm happy to do that.. it seems to be working using that path. We should perhaps update the README to point to it instead of the nonexistent ./gradlew.

**Comment by jessefarinacci** [comment]
Nevermind, stupid error on my part.
