### ISSUE TITLE
Feature Test Summary For Connectors 2.1 for Jakarta EE 10

### ISSUE THREAD

**Issue by KyleAure** [OpenLiberty/open-liberty#21602]
## Test Strategy

Converted the com.ibm.ws.jca_fat_duplicates project to test deployment of a connectors 2.1 resource adapter deployment descriptor (only change from previous version was being able to support the updated version="2.1" attribute).

Updated the com.ibm.ws.jca_fat_example_anno project to test the new connectors 2.1 generics support on MappedRecord and IndexedRecord

The com.ibm.ws.rest.handler.validator_fat project was updated by Andrew Rouse as part of the MicroProfile updates so that it repeats on EE10 so that the ValidateJCATest will run the config validation rest endpoint tests against the new connectors-2.1 feature

Also updated existing JCA FAT buckets to repeat with EE10 to ensure the new connectors-2.1 feature is tested using existing test buckets

### List of FAT projects affected

* com.ibm.ws.jca_fat_duplicates - (see above)
* com.ibm.ws.jca_fat_example_anno - (see above)
* com.ibm.ws.rest.handler.validator_fat - (see above)
* com.ibm.ws.jca.1.7_fat - Updated to repeat on EE10
* com.ibm.ws.jca_fat - Updated to repeat on EE10 
* com.ibm.ws.jca_fat_bval - Updated to repeat on EE10
* com.ibm.ws.jca_fat_bvt.jms - Updated to repeat on EE10
* com.ibm.ws.jca_fat_bvt - Updated to repeat on EE10
* com.ibm.ws.jca_fat_classloading - Updated to repeat on EE10
* com.ibm.ws.jca_fat_configprops - Updated to repeat on EE10
* com.ibm.ws.jca_fat_derbyra - Updated to repeat on EE10
* com.ibm.ws.jca_fat_dynamicConfig - Updated to repeat on EE10
* com.ibm.ws.jca_fat_enterpriseApp - Updated to repeat on EE10
* com.ibm.ws.jca_fat_errorpaths - Updated to repeat on EE10
* com.ibm.ws.jca_fat_regr.cfg.prop - Updated to repeat on EE10

### Test strategy

* What functionality is new or modified by this feature?

-The test functionality for this feature update is very small. There is new added generic support for the MappedRecord and IndexedRecord classes. In addition to that, the only update was to support the string "2.1" for a supported version in a resource adapter deployment descriptor.

* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)

-Positive and Negative testing for existing JCA support is covered at the same level as previous releases by repeating the existing test buckets listed above for EE10

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

-None

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

Voting Result: 5
Voting Log: https://ibm-cloud.slack.com/archives/C31DXH4GJ/p1663361216386629

**Comment by ayoho** [comment]
LGTM 👍
