### ISSUE TITLE
create blog about using OL with Loki / Grafana

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#21620]
Would be helpful for Loki / Grafana community if we could publish a blog on using OL, with JSON logging, with Loki / Grafana for log aggregation and dashboard.

A few ideas:
- should cover the basic setup steps required for both OL and Loki/Grafana so readers can follow along
- could show how to create a good dashboard for OL (a combined how to for OL users and OL/Grafana users)
- possibly cover how to set up in Kubernetes (is there a handy way to set up Loki/Grafana to watch pod logs based on a selector?)
- could publish the dashboard to grafana.com

**Comment by fmhwong** [comment]
Decided in iteration planning call that this is not needed anymore

**Comment by ArneLimburg** [comment]
For others that find this ticket (like me), it would be interesting _why_ this is not needed any more.

**Comment by donbourne** [comment]
@ArneLimburg , IIRC we decided not to do this because our intent is to do a more all-encompassing blog including logging, metrics and distributed tracing with Loki / Grafana / Tempo  (see #23927).
