### ISSUE TITLE
Clean up IRequestResponseFactory60Impl.java if no new methods are required

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#21632]
A new `IRequest60Impl` was created for Servlet 6.0. Currently there are no new methods in this Interface so we'll need to revisit this if we end up not needing it we should remove the factory changes etc. [IRequestResponseFactory60Impl.java](https://github.com/OpenLiberty/open-liberty/pull/21525/files#diff-4335791aa89159df097f230ae82e239bd57323529f48b2bcd5bf7891c807f518)

Review other changes in https://github.com/OpenLiberty/open-liberty/pull/21525 to ensure we don't have any additional cleanup.

**Comment by pmd1nh** [comment]
IRequest60Impl has new methods to support Request ID work.
[IRequestResponseFactory60Impl.java] is used for both IRequest60Impl and IResponse60Impl (session attribute work)

No clean up is needed.
