### ISSUE TITLE
Servlet 6.0: Investigate Servlet 6.0 Deprecations and determine if any Open Liberty API/SPI requires deprecation

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#21647]
The Servlet 6.0 UFO should be updated with this information.

In addition look at the Deprecated methods that were removed in Servlet 6.0 and ensure our API/SPI are still ok.

**Comment by pmd1nh** [comment]
Resource used in the investigation

https://www.ibm.com/docs/en/was-liberty/nd?topic=SSAW57_liberty/com.ibm.websphere.javadoc.liberty.doc/spi_liberty_core.htm

for the [WebSphere WebContainer Servlet SPI](https://www.ibm.com/docs/api/v1/content/SSAW57_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.spi.servlet_2.9-javadoc/index.html)

All of the removed API were marked deprecated in the previous servlets.  They are finally removed in Servlet 6.0.
Our SPI do not use these removed classes/methods.

The only one change to SPI is in the new metaType SKIP_ENCODED_CHAR_VERIFICATION in [WCCustomProperties] which is documented accordingly.
