### ISSUE TITLE
PausableComponentException when closing message endpoints on server shutdown

### ISSUE THREAD

**Issue by ocseal** [OpenLiberty/open-liberty#21735]
**Describe the bug**  
Due to the waitForStop method waiting for the entire duration of the server quiesce time (https://github.com/OpenLiberty/open-liberty/issues/21734), the quiesce operations that occur after it are blocked. This causes the PausableComponentException since the pause operation was delayed until the server quiesce time elapsed. 

**Steps to Reproduce**  
1. Clone the repository from https://github.com/ocseal/cargotracker.
2. Download the HSQL DB .jar and modify the HSQL DB library filepath to fit your machine.
3. Run the app using 'mvn -P openliberty liberty:dev' and wait for the web application to become available.
4. Access the web application and route the unrouted cargo object, then select the map from the administration interface.
5. Stop the server using CTRL-C.
6. Restart the server using 'mvn -P openliberty liberty:dev' without cleaning the target and wait for the web application be available.
7. Stop the server using CTRL-C and observe the error.

**Expected behavior**  
The server should shut down properly without issues closing message endpoints. 

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.7
 - Java Version: 
     openjdk version "11.0.15" 2022-04-19
     OpenJDK Runtime Environment Homebrew (build 11.0.15+0)
     OpenJDK 64-Bit Server VM Homebrew (build 11.0.15+0, mixed mode)
 - server.xml configuration attached. 
 - [server.txt](https://github.com/OpenLiberty/open-liberty/files/9097196/server.txt)
 - trace.log attached
 - [trace.log](https://github.com/OpenLiberty/open-liberty/files/9097201/trace.log)

**Additional context**  
The relevant portion of the trace.log can be found by searching for the error code "CNTR4119W".

**Comment by tkburroughs** [comment]
Issue is that a different pauseable component is blocking during server quiesce, so the Message Endpoint pauseable components are not called until AFTER quiesce, at which time the applications have already started to shutdown. The Message Endpoint pause() method does not tolerate this, resulting in the following error:
```
Stack Dump = com.ibm.ws.kernel.launch.service.PauseableComponentException: CNTR4119W: The request to pause the message endpoint for the CargoHandledConsumer bean in the cargo-tracker.war module of the cargo-tracker application did not complete successfully because the endpoint is not active.
    at com.ibm.ws.ejbcontainer.mdb.internal.MessageEndpointFactoryImpl.pause(MessageEndpointFactoryImpl.java:494)
    at com.ibm.ws.runtime.update.internal.PauseableComponentQuiesceListener.serverStopping(PauseableComponentQuiesceListener.java:52)
    at com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl$3.run(RuntimeUpdateManagerImpl.java:380)
    at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
```

While issue https://github.com/OpenLiberty/open-liberty/issues/21734 should address the delay in calling pause during quiesce, this issue can address the fact that Message Endpoint pause doesn't tolerate being called concurrently with application stop.  In general, pause() should be considered successful when the application is stopping during server shutdown.
