### ISSUE TITLE
Feature Test Summary: LG-304: Time based log rollover for Liberty

### ISSUE THREAD

**Issue by ellen-lau** [OpenLiberty/open-liberty#21745]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

### List of FAT projects affected

com.ibm.ws.logging_fat (OL)
com.ibm.ws.transport.http_test (WS-CD)

* What functionality is new or modified by this feature?

LG-304 introduces the ability to do time-based log rollover for liberty logs: messages.log and trace.log, as well as liberty access logging logs: http_access.log. This functionality is enabled with the use of two new attributes, `rolloverStartTime` and `rolloverInterval`, where `rolloverStartTime` is the desired time of day when logs should first rollover, and `rolloverInterval` is the time interval in between consecutive log rollovers.

For example, a server with a `rolloverStartTime` of midnight and a `rolloverInterval` of 1 day will roll over its messages and trace logs once every day, at midnight.

For `rolloverStartTime`:
Use this setting alone or with the `rolloverInterval` attribute to enable time-based log rollover for `messages.log` and `trace.log` files. This setting specifies the scheduled time of day for logs to first rollover. The `rolloverInterval` setting duration begins at `rolloverStartTime`. Valid values follow a 24-hour ISO-8601 date-time format of HH:MM, where 00:00 represents midnight. Padding zeros are required. If the `rolloverInterval` attribute is specified, the default value of the `rolloverStartTime` attribute is 00:00, midnight.

For `rolloverInterval`:
Use this setting alone or with the `rolloverStartTime` attribute to enable time-based log rollover for `messages.log` and `trace.log` files. This setting specifies the time interval in between log rollovers, in minutes if a unit of time is not specified. Specify a positive integer followed by a unit of time, which can be days (d), hours (h), or minutes (m). For example, specify 5 hours as 5h. You can include multiple values in a single entry. For example, 1d5h is equivalent to 1 day and 5 hours. If the `rolloverStartTime` attribute is specified, the default value of the `rolloverInterval` attribute is 1 day. 

* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

The following new tests were added under test classes `TimeBasedLogRolloverTest.java` (com.ibm.ws.logging_fat) and `AccessLogRolloverTest.java` (com.ibm.ws.transport.http_test):

*Note: AccessLogTest.java only contains a subset of all the tests listed (since the access log config doesn't have env/bootstrap variables), the trace related tests (since the access log test only pertains to the http_access.log rollover), JSON related tests, etc).

`testTimedRolloverEnv()`: Tests that logs are rolled over using the environment variables for the attributes `rolloverInterval` and `rolloverStartTime`

`testTimedRolloverBootstrap()`: Tests that logs are rolled over using the bootstrap variables for the attributes `rolloverInterval` and `rolloverStartTime`

`testTimedRolloverXML()`: Tests that logs are rolled over using the server.xmlm attributes `rolloverInterval` and `rolloverStartTime`

`testTimedRolloverJsonLogs()`: Tests that logs are rolled over when JSON logs are enabled

`testTimedRolloverXMLOverrides()`: Tests that server.xml attribute configuration of `rolloverInterval` and `rolloverStartTime` overrides bootstrap.properties

`testMultipleRollovers()`: Tests that logs are continuously rolled over

`testTimedRolloverXMLUpdates()`: Tests updating server attributes `rolloverInterval` and `rolloverStartTime`

`testRolloverNoTraceSpecification()`: Tests that with no trace specification (aka no trace.log created), there is no trace.log rollover

`testMissingRolloverStartTime()`: Tests a missing `rolloverStartTime` value, checks if the value is set to its default

`testMissingRolloverInterval()`: Tests a missing `rolloverInterval` value, checks if the value is set to its default

`testEnableDisableTimedRollover()`: Tests enabling and disabling time-based log rollover

`testInvalidRolloverStartTime()`: Tests an invalid `rolloverStartTime` value, checks for a warning in the logs

`testInvalidRolloverInterval()`: Tests an invalid `rolloverInterval ` value, checks for a warning in the logs

`testMaxFileSizePriorityRolling()`: Tests that `maxFileSize` attribute (file rolling by size) takes precedence over time-based log rollover

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

**Confidence Level: 4**

**Comment by ellen-lau** [comment]
@dave-waddling for your review -- thanks!

**Comment by dave-waddling** [comment]
@ellen-lau Thanks for completing the FTS, all looks good and the testing is passing cleanly in the SOE. I'll add the approval to the feature issue now.

**Comment by ellen-lau** [comment]
FTS approved, so closing now.
