### ISSUE TITLE
Investigate/update/document the affect of httpsRequired on backchannelLogoutUri

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#21768]
Investigate if/how the setting of the OAuth config attribute  `httpsRequired` affects the value allowed/required for the backchannelLogoutUri.
We need to look at what happens with both confidential and public clients.

I'll add some additional tests and post the behavior that I'm currently seeing. We can decide what if anything may need to be updated.

**Comment by c00crane** [comment]
All of these tests have a bcl uri using http instead of https.
At the moment, all of these cases below are behaving the same way - all calls to the bcl uri are made
**BasicBCLTests_httpBackchannelLogoutUri_confidentialClient_httpsRequired_true** - would expect call not to be made because of httpsRequired
**BasicBCLTests_httpBackchannelLogoutUri_confidentialClient_httpsRequired_false** - expect bcl to be called (and it is)
**BasicBCLTests_httpBackchannelLogoutUri_publicClient_httpsRequired_true_withSecret** - would expect call not to be made (not sure what should prevent this - checking httpsRequired, or issue 21766)
**BasicBCLTests_httpBackchannelLogoutUri_publicClient_httpsRequired_false_withSecret** - issue 21766 should prevent this 
**BasicBCLTests_httpBackchannelLogoutUri_publicClient_httpsRequired_true_withoutSecret**- would expect call not to be made (not sure what should prevent this - checking httpsRequired, or issue 21766)
**BasicBCLTests_httpBackchannelLogoutUri_publicClient_httpsRequired_false_withoutSecret** - issue 21766 should prevent this

**Comment by jimmy1wu** [comment]
the `httpsRequired` attribute is used for ensuring that inbound requests to the oauth provider from a client use https (e.g., requests made to the provider's authorize, token, userinfo, etc. endpoints). since backchannel logout is an outbound request from the provider, the `httpsRequired` should not have an affect on the `backchannelLogoutUri`.
