### ISSUE TITLE
JAX-WS and CXF 3.4 upgrade Feature Test Summary

### ISSUE THREAD

**Issue by neuwerk** [OpenLiberty/open-liberty#21761]
## Test Strategy

Since this is an OSS update of jaxws-2.2, wsAtomicTranaction-1.2, and wsSecurity-1.1, the aims of the test will be able to merge the updates without causing regressions in the existing test infrastructure. Since jaxws-2.2 and jaxrs-2.1 will now be sharing a common code base the JAX-RS may also be effect so and eye needs to be on the regression of those post update. Some additional tests are needed to account for tests that were never added for changes to CXF 2.6.2 to account for those change being brought forward to CXF 3.4. 

### List of FAT projects affected

**JAX-WS**

- com.ibm.ws.jaxws.2.2.webcontainer_fat, 
- com.ibm.ws.jaxws.2.2.webcontainer_fat_extended, 
- com.ibm.ws.jaxws.clientcontainer_fat, 
- com.ibm.ws.jaxws.cdi_fat, 
- com.ibm.ws.jaxws.ejb_fat, 
- com.ibm.ws.jaxws.security_fat.
- com.ibm.ws.jaxws.X.wsat_fat, 
- io.openliberty.ws.jaxws.global.handler.internal_fat, 

**JAX-RS**

- com.ibm.ws.jaxrs.2.0_fat, 
- com.ibm.ws.jaxrs.2.1_fat, 
- com.ibm.ws.jaxrs.2.1_fat_executor, 
- io.openliberty.ws.jaxrs.global.handler.internal_fat, 
- com.ibm.ws.jaxrs.2.0_fat,
- com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,
- com.ibm.ws.jaxrs.2.0.client_fat,
- com.ibm.ws.jaxrs.2.1_fat,
- com.ibm.ws.jaxrs.2.1_fat_executor,
- com.ibm.ws.jaxrs.2.1_fat_extended,
- com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,
- com.ibm.ws.jaxrs.2.1.client_fat,
- com.ibm.ws.jaxrs.2.1.sse_fat,
- com.ibm.ws.jaxrs.2.x_fat_clientProps

**JAX-RS and JAX-WS common**

- io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat

**WS-AT specific**

- com.ibm.ws.wsat.common_fat, 
- com.ibm.ws.wsat.concurrent_fat, 
- com.ibm.ws.wsat.migration_fat.1, 
- com.ibm.ws.wsat.migration_fat.2, 
- com.ibm.ws.wsat.migration_fat.3, 
- com.ibm.ws.wsat.migration_fat.4, 
- com.ibm.ws.wsat.migration_fat.5, 
- com.ibm.ws.wsat.recovery_fat.multi.1, 
- com.ibm.ws.wsat.recovery_fat.multi.2, 
- com.ibm.ws.wsat.recovery_fat.multi.3, 
- com.ibm.ws.wsat.recovery_fat.multi.4, 
- com.ibm.ws.wsat.recovery_fat.single, 
- com.ibm.ws.wsat_fat.db, 
- com.ibm.ws.wsat_fat.ssl, 
- com.ibm.ws.wsat_fat.multi, 
- com.ibm.ws.wsat_fat.assertion, 
- com.ibm.ws.wsat_fat.dbs_optional, 
- com.ibm.ws.wsat_fat.dbs, 
- com.ibm.ws.wsat_fat.db_optional, 

**WS-Security**

- com.ibm.ws.wssecurity_fat.wsscxf.saml.3,
- com.ibm.ws.wssecurity_fat.wsscxf.1,
- com.ibm.ws.wssecurity_fat.wsscxf.saml.2,
- com.ibm.ws.wssecurity_fat.wsscxf.saml.4,
- com.ibm.ws.wssecurity_fat.wsscxf,
- com.ibm.ws.wssecurity_fat.wsscxf.saml.1,
- com.ibm.ws.wssecurity_fat.wsscxf.saml,
- com.ibm.ws.wssecurity_fat.wsscxf.saml.5, 

### Test strategy

* What functionality is new or modified by this feature?

OSS upgrade, so no new functionality added, only maintaining behavior post upgrade. 

* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)

The amount of testing we already have in place that were running against jaxws-2.2 with CXF 2.6.2 and now are running against jaxws-2.2 with CXF 3.2 make this hard to answer. See the above list of fat buckets for proof of coverage. I can say that we have added positive and negative tests specifically for changes to CXF 2.6.2 that we've needed to bring forward to CXF 3.2. Those tests are:

com.ibm.ws.jaxws.fat.LibertyCXFNegativePropertiesTest
com.ibm.ws.jaxws.fat.LibertyCXFPostivePropertiesTest

They are for testing properties that we've added for support to allow customers change from default behavior.  Lastly we've added a bucket of for testing a JAX-WS and JAX-RS app running on the same server to ensure that any change to one feature that may affect the other will be picked up going forward. That bucket is:

- io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

None

## Confidence Level - 5

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values: 5

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by dave-waddling** [comment]
Hi @neuwerk, thanks for completing the FTS, having reviewed all looks good. However, prior to approval please can you briefly triage the following defects in associated areas of the product to confirm these are not issues introduced by this feature:
- 291422
- 290412
- 291423
- 290713
- 291365

**Comment by neuwerk** [comment]
@dave-waddling should all be good to go! Thanks for bringing them to my attention.

**Comment by dave-waddling** [comment]
Hi @neuwerk, thanks for sorting those defects. As per our Slack discussion all looks good and the approval has been added to the feature epic.
