### ISSUE TITLE
BETA BLOG - CDI 4.0

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#21777]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty. For this post to be included in the beta issue please make sure that this is completed by the end of Friday following the GM (Wednesday). 

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name (eg WebSockets feature): Jakarta Contexts and Dependency Injection 4.0
   
   Short feature name (eg websockets-1.0): cdi-4.0

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.
   - Developers of Jakarta EE based applications

4. Write a paragraph to summarises the update, including the following points:
   
- A sentence or two that introduces the update to someone new to the general technology/concept.
  - CDI allows objects to be bound to lifecycle contexts, to be injected, to be associated with interceptors and decorators, and to interact in a loosely coupled fashion by firing and observing events.

- What was the problem before and how does your update make their life better? (Why should they care?)
  - As part of Jakarta EE 10 Core Profile, CDI 4.0 brings some functional updates and removes some previously deprecated APIs. This update also brings in new EE 10 versions of the Jakarta Annotations and Jakarta Interceptors APIs.
  - Support has been added for Build Compatibile Extensions, along with a new Metamodel that is less dependent on reflection at runtime.
 
```java
public class MyExtension implements BuildCompatibleExtension {
    @Enhancement(type=MyFooService.class)
    public void foo(ClassConfig clazz) {
        clazz.addAnnotation(MyQualifier.class)
    }
}
```
- In previous versions of CDI, an empty beans.xml file indicated that an archive should be treated as an Explicit Bean Archive (the equivalent of bean-discovery-mode="all"). In CDI 4.0, an empty beans.xml will now cause an archive to be treated as an Implicit Bean Archive (the equivalent of bean-discovery-mode="annotated"). Should it be needed, a configuration option has been provided to enable compatibility with previous versions.
- In previous versions of CDI, a non-empty beans.xml file which did not include a version attribute was defaulted to mean bean-discovery-mode="all". In CDI 4.0, it will now default to bean-discovery-mode="annotated".
- Two new Observable Container State Events have been added; Startup and Shutdown. Applications can listen for these events to be notified when the CDI container is starting up and being shut down.
- A new Handle API is added to make programatic lookup of Beans and Instances easier.
- (Jakarta Annotations 2.1) The @Priority annotation can now be applied to any program element. This is used by CDI 4.0 to allow Stereotypes to include a Pritory annotation.
- Some previously deprecated CDI APIs have been removed.
  - @New qualifier
    - Replaced by @Dependent beans (since CDI 1.1)
  - Bean#isNullable()
    - Not used by the implementation (since CDI 1.1)
  - BeanManager#fireEvent()
    - Use BeanManager.getEvent() instead (since CDI 2.0)
  - BeanManager#createInjectionTarget(AnnotatedType)
    - Replaced by BeanManager#getInjectionTargetFactory(AnnotatedType) (since CDI 1.1)
  - BeforeBeanDiscovery#addAnnotatedType(AnnotatedType)
    - Replaced by BeforeBeanDiscovery#addAnnotatedType(AnnotatedType, String) (since CDI 1.1)
 - The Liberty <cdi12> configuration element has been superseded by a new <cdi> element that applies to all versions of CDI (1.2 and newer).

```xml
<cdi enableImplicitBeanArchives="false" emptyBeansXmlCDI3Compatibility="true"/>
```
- The attribute `enableImplicitBeanArchives` is the same as it was in previous versions.
  - If set to "true" (default) then archives which do not contain a beans.xml file will be treated as Implicit Bean Archives and will be scanned for classes that have Bean Defining Annotations.
  - If set to "false" then archives which do not contain a beans.xml file will be not be scanned for annotated classes.
- The attribute `emptyBeansXmlCDI3Compatibility` only applies to CDI 4.0.
  - If set to "true" then an archive which contains an empty beans.xml file will be treated as an Explicit Bean Archive (as it was in CDI 3.0 and earlier)
  - If set to "false" (default) then an archive which contains an empty beans.xml file will be treated as an Implicit Bean Archive. This is the equivalent to setting bean-discovery-mode="annotated".

   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.

```xml
<featureManager>
  <feature>cdi-4.0</feature>
</featureManager>

<cdi enableImplicitBeanArchives="false" emptyBeansXmlCDI3Compatibility="true"/>
```
   
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by Emily-Jiang** [comment]
@tevans78 

> 
Write a paragraph to summarises the update, including the following points:
A sentence or two that introduces the update to someone new to the general technology/concept.

    CDI allows objects to be bound to lifecycle contexts, to be injected, to be associated with interceptors and decorators, and to interact in a loosely coupled fashion by firing and observing events.


This above sentence should cover the updated features not what CDI spec is trying to do.

**Comment by tevans78** [comment]
Was published here: https://openliberty.io/blog/2022/08/04/jakarta-core-profile-22009-beta.html
