### ISSUE TITLE
Provide a way for Custom User Registries to use the uniqueId instead of the securityName

### ISSUE THREAD

**Issue by wrodrig** [OpenLiberty/open-liberty#21808]
**Describe the bug**  
When using a CustomUserRegistry and making a programmatic API call like getRemoteUser, getCallerPrincipal or getUserPrincipal Open Liberty is returning the `securityName` instead of the `displayName`.

**Steps to Reproduce**  
- Configure a Custom User Registry using `bell-1.0`
- Authenticate to an application that prints getRemoteUser()

**Expected behavior**  
The following methods getRemoteUser, getCallerPrincipal or getUserPrincipal should return the `displayName`.

**Diagnostic information:**  
 - OpenLiberty Version: 21.0.0.1 - 22.0.0.11
 - Affected feature(s) bells-1.0, appSecurity-1.0, appSecurity-2.0, appSecurity-3.0
 - Java Version: All
 - server.xml configuration (WITHOUT sensitive information like passwords)

**Additional context**

**Comment by sfranz-drv** [comment]
@wrodrig Good morning. As the reporter of the issue, we are urgently waiting for the fix to complete our migration towards Liberty. Is there any way to speed up the process or pull request? Thank you very much and best regards, Stefan

**Comment by wrodrig** [comment]
@sfranz-drv sorry for the delay in my response. We wrapping up the work for this change and will be providing you with a fix within the next day or two. Thank you so much for your patience.

**Comment by mbroz2** [comment]
@wrodrig please update the description of this `release bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)

**Comment by wrodrig** [comment]
@mbroz2  Thanks for the reminder, I made the changes.
