### ISSUE TITLE
BCL not invoked when logout initiates from SAML

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#21811]
I have an OIDC OP that uses SAML for authentication.  I have an app protected by oidc on my RP.
I access the protected app and this works fine.
When I logout by initiating the request on the IDP (Shibboleth), I see it handling the request and making a request of on the SP.
The SP doesn't complete the request.  It looks like getMatchingConfig in BackchannelLogout fails since the requestUri, "/ibm/saml20/spOP/slo", doesn't find a matching oidc config.
[samlLogout1.zip](https://github.com/OpenLiberty/open-liberty/files/9144944/samlLogout1.zip)

**Comment by c00crane** [comment]
This is pretty much working with patches from Aruna (commits: 6dfdf85e19bbd4386d41923504a4002d8eea1c7e & 6af12f20c18bf9f9fc64a572e40418433d2709de)

**Comment by ayoho** [comment]
I believe support for this has been delivered.
