### ISSUE TITLE
CTS: EE8: JAX-RS bucket: After a 503 the SseEventSource reconnect never occurs even tho both the SseEventSource and the SseEventSink are not closed and the Retry-After is specified.

### ISSUE THREAD

**Issue by jkoehler22** [OpenLiberty/open-liberty#2190]
trace log:

	Line 3954350: [2/12/18 15:02:10:792 EST] 00000064 id=         com.ibm.ws.jaxrs21.sse.LibertySseEventSinkImpl               > <init> Entry  
	Line 3954371: [2/12/18 15:02:10:792 EST] 00000064 id=dcbfe702 com.ibm.ws.jaxrs21.sse.LibertySseEventSinkImpl               < <init> Exit  
	Line 3954828:                                                                                                                {Retry-After=[1]}
	Line 3954853:                                                                                                                javax.ws.rs.WebApplicationException: HTTP 503 Service Unavailable
	Line 3955102:                                                                                                                javax.ws.rs.WebApplicationException: HTTP 503 Service Unavailable
	Line 3955165: [2/12/18 15:02:10:804 EST] 00000064 id=         g.apache.cxf.cxf.rt.frontend.jaxrs.3.2:1.0.20.master(id=97)] W javax.ws.rs.WebApplicationException: HTTP 503 Service Unavailable

**Comment by jkoehler22** [comment]
test log:

[javatest.batch] ********************************************************************************
[javatest.batch] Beginning Test:  com/sun/ts/tests/jaxrs/jaxrs21/ee/sse/sseeventsource/JAXRSClient.java#defaultWaiting1s_from_standalone
[javatest.batch] ********************************************************************************
[javatest.batch] 
[javatest.batch] 02-12-2018 15:02:08:  Harness - harness.executeMode is set to "0"
[javatest.batch] 02-12-2018 15:02:08:  Harness - keywords (to be passed to tests) set to:  all
[javatest.batch] 02-12-2018 15:02:08:  Harness - sClassPathFromExecProps = 
[javatest.batch] command: com.sun.ts.lib.harness.ExecTSTestCmd CLASSPATH=:/cts2.1/jaxrstck/bin/xml/../../lib/tsharness.jar:/cts2.1/jaxrstck/bin/xml/../../lib/javatest.jar:/cts2.1/jaxrstck/bin/xml/../../tools/ant/lib/ant.jar:/cts2.1/jaxrstck/bin/xml/../../lib/jaxrstck.jar:/cts2.1/jaxrstck/bin/xml/../../lib/jaxb-xjc.jar:/cts2.1/jaxrstck/bin/xml/../../classes:/cts2.1/java/jre/../lib/tools.jar:/cts2.1/jaxrstck/bin/xml/../../lib/commons-httpclient-3.1.jar:/cts2.1/jaxrstck/bin/xml/../../lib/commons-logging-1.1.1.jar:/cts2.1/jaxrstck/bin/xml/../../lib/commons-codec-1.3.jar:/cts2.1/jaxrstck/bin/xml/../../lib/sigtest.jar:/cts2.1/wlp/lib/com.ibm.ws.org.glassfish.json.1.1_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.kernel.service_1.3.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.jsonp.1.1_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.1.common_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.servlet.4.0_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.annotation.1.2_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.annotation.1.1_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.jaxrs.2.1_1.0.20.jar:/cts2.1/wlp/dev/api/ibm/com.ibm.websphere.appserver.api.endpoint_1.0.20.jar:/cts2.1/wlp/dev/api/ibm/com.ibm.websphere.appserver.api.basics_1.2.20.jar:/cts2.1/wlp/dev/api/ibm/com.ibm.websphere.appserver.api.servlet_1.1.20.jar:/cts2.1/wlp/dev/api/ibm/com.ibm.websphere.appserver.api.jaxrs20_1.0.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.application_1.0.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.httptransport_2.0.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.globalhandler_1.0.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.servlet_2.1.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.containerServices_2.1.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.classloading_1.4.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.anno_1.0.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.javaeedd_1.3.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.artifact_1.2.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.0.client_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.core.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.rt.rs.service.description.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.rt.rs.sse.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.tools.common.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.tools.wadlto.jaxrs.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.container.service_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.logging.osgi_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.logging_1.0.20.jar:/cts2.1/wlp/lib/org.eclipse.osgi_3.12.50.jar:/cts2.1/wlp/lib/com.ibm.json4j_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.jsonb.1.0_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.jaxb.2.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.xlxp.1.5.3_1.0.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.kernel.service_1.5.20.jar:/cts2.1/wlp/dev/api/ibm/com.ibm.websphere.appserver.api.kernel.service_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.eclipse.yasson.1.0_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.cdi.2.0_1.0.20.jar:/cts2.1/otherJars/stax2-api-3.1.4.jar:/cts2.1/otherJars/woodstox-core-asl-4.2.0.jar:/cts2.1/wlp/lib/com.ibm.ws.org.glassfish.json.1.1_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.jsonp.1.1_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.wsoc.1.1_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.0.ejb_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.1.common_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.0.beanvalidation_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.0.cdi_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.0.client_1.0.20.jar:/cts2
.1/wlp/lib/com.ibm.ws.jaxrs.2.0.ejb_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.0.managedbeans_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.0.security_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.0.server_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.0.tools_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.2.0.web_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.cdi_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs.ejb_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.jaxrs_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.core.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.rt.rs.client.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.rt.rs.service.description.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.rt.rs.sse.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.tools.common.3.2_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.apache.cxf.cxf.tools.wadlto.jaxrs.3.2_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.annotation.1.2_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.annotation.1.1_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.container.service_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.kernel.service_1.3.20.jar:/cts2.1/wlp/lib/com.ibm.ws.logging.osgi_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.logging_1.0.20.jar:/cts2.1/wlp/lib/org.eclipse.osgi_3.12.50.jar:/cts2.1/wlp/lib/com.ibm.json4j_1.0.20.jar:/cts2.1/wlp/dev/spi/ibm/com.ibm.websphere.appserver.spi.kernel.service_1.5.20.jar:/cts2.1/wlp/dev/api/ibm/com.ibm.websphere.appserver.api.kernel.service_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.jsonb.1.0_1.0.20.jar:/cts2.1/wlp/lib/com.ibm.ws.org.eclipse.yasson.1.0_1.0.20.jar:/cts2.1/wlp/dev/api/spec/com.ibm.websphere.javaee.cdi.2.0_1.0.20.jar:/cts2.1/otherJars/stax2-api-3.1.4.jar:/cts2.1/otherJars/woodstox-core-asl-4.2.0.jar DISPLAY=:0.0 HOME=/root windir= SYSTEMROOT= PATH=/nativelib /cts2.1/java/jre/bin/java -Dcts.tmp=/cts2.1/jaxrstck/bin/xml/../../tmp -Djava.endorsed.dirs= -Ddeliverable.class=com.sun.ts.lib.deliverable.tck.TCKDeliverable com.sun.ts.tests.common.vehicle.VehicleClient -p /cts2.1/jaxrstck/bin/xml/../../tmp/tstest.jte -t defaultWaiting1s -vehicle standalone
[javatest.batch] ************************************************************
[javatest.batch] * props file set to "/tmp/root-cts-props.txt"
[javatest.batch] ************************************************************
[javatest.batch] 02-12-2018 15:02:09:  [JAXRSCommonClient] Test setup OK
[javatest.batch] 02-12-2018 15:02:10:  [Request] Dispatching request: 'GET http://localhost:9080/jaxrs_jaxrs21_ee_sse_sseeventsource_web/su/available' to target server at 'localhost:9080'
[javatest.batch] 02-12-2018 15:02:10:  ###############################
[javatest.batch] 02-12-2018 15:02:10:  TRACE: [WIRE] - >> GET http://localhost:9080/jaxrs_jaxrs21_ee_sse_sseeventsource_web/su/available
[javatest.batch] 02-12-2018 15:02:10:  TRACE: [WIRE] - >> Accept:*/*
[javatest.batch] 02-12-2018 15:02:10:  TRACE: [WIRE] - << 200 OK
[javatest.batch] 02-12-2018 15:02:10:  TRACE: [WIRE] - << Content-Language: en-US
[javatest.batch] 02-12-2018 15:02:10:  TRACE: [WIRE] - << Content-Length: 2
[javatest.batch] 02-12-2018 15:02:10:  TRACE: [WIRE] - << content-type: text/plain
[javatest.batch] 02-12-2018 15:02:10:  TRACE: [WIRE] - << Date: Mon, 12 Feb 2018 20:02:10 GMT
[javatest.batch] 02-12-2018 15:02:10:  TRACE: [WIRE] - << X-Powered-By: Servlet/4.0
[javatest.batch] 02-12-2018 15:02:10:  TRACE: [WIRE] - << OK
[javatest.batch] 02-12-2018 15:02:10:  [Request] Dispatching request: 'GET http://localhost:9080/jaxrs_jaxrs21_ee_sse_sseeventsource_web/su/available' to target server at 'localhost:9080'
[javatest.batch] 02-12-2018 15:02:10:  ###############################
[javatest.batch] 02-12-2018 15:02:10:  TRACE: [WIRE] - >> GET http://localhost:9080/jaxrs_jaxrs21_ee_sse_sseeventsource_web/su/available
[javatest.batch] 02-12-2018 15:02:10:  TRACE: [WIRE] - >> Accept:*/*
[javatest.batch] 02-12-2018 15:02:10:  TRACE: [WIRE] - << 200 OK
[javatest.batch] 02-12-2018 15:02:10:  TRACE: [WIRE] - << Content-Language: en-US
[javatest.batch] 02-12-2018 15:02:10:  TRACE: [WIRE] - << Content-Length: 2
[javatest.batch] 02-12-2018 15:02:10:  TRACE: [WIRE] - << content-type: text/plain
[javatest.batch] 02-12-2018 15:02:10:  TRACE: [WIRE] - << Date: Mon, 12 Feb 2018 20:02:10 GMT
[javatest.batch] 02-12-2018 15:02:10:  TRACE: [WIRE] - << X-Powered-By: Servlet/4.0
[javatest.batch] 02-12-2018 15:02:10:  TRACE: [WIRE] - << OK
[javatest.batch] 02-12-2018 15:02:14:  ERROR: The message was not received
[javatest.batch] 02-12-2018 15:02:14:  ERROR: Test case throws exception: The message was not received
[javatest.batch] 02-12-2018 15:02:14:  ERROR: Exception at:  
[javatest.batch] 02-12-2018 15:02:14:  ERROR: com.sun.ts.lib.harness.EETest$Fault: The message was not received
[javatest.batch] 	at com.sun.ts.tests.jaxrs.common.JAXRSCommonClient.fault(JAXRSCommonClient.java:730)
[javatest.batch] 	at com.sun.ts.tests.jaxrs.common.JAXRSCommonClient.assertTrue(JAXRSCommonClient.java:625)
[javatest.batch] 	at com.sun.ts.tests.jaxrs.common.JAXRSCommonClient.assertNotNull(JAXRSCommonClient.java:716)
[javatest.batch] 	at com.sun.ts.tests.jaxrs.jaxrs21.ee.sse.SSEJAXRSClient.querySSEEndpoint(SSEJAXRSClient.java:50)
[javatest.batch] 	at com.sun.ts.tests.jaxrs.jaxrs21.ee.sse.SSEJAXRSClient.querySSEEndpoint(SSEJAXRSClient.java:32)
[javatest.batch] 	at com.sun.ts.tests.jaxrs.jaxrs21.ee.sse.sseeventsource.JAXRSClient.defaultWaiting1s(JAXRSClient.java:123)
[javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
[javatest.batch] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
[javatest.batch] 	at java.lang.reflect.Method.invoke(Method.java:508)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.run(EETest.java:550)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:113)
[javatest.batch] 	at com.sun.ts.tests.common.vehicle.EmptyVehicleRunner.run(EmptyVehicleRunner.java:30)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:102)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:446)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:210)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.run(EETest.java:257)
[javatest.batch] 	at com.sun.ts.tests.common.vehicle.VehicleClient.main(VehicleClient.java:27)
[javatest.batch] 
[javatest.batch] 02-12-2018 15:02:14:  [JAXRSCommonClient] Test cleanup OK
[javatest.batch] STATUS:Failed.Test case throws exception: The message was not received
[javatest.batch] Failed. Test case throws exception: The message was not received
[javatest.batch] ********************************************************************************
[javatest.batch] Finished Test:  FAILED........com/sun/ts/tests/jaxrs/jaxrs21/ee/sse/sseeventsource/JAXRSClient.java#defaultWaiting1s_from_standalone
[javatest.batch] ********************************************************************************

**Comment by jkoehler22** [comment]
Reconnect support
The SseEventSource supports automated recuperation from a connection loss, including negotiation of delivery of any missed events based on the last received SSE event id field value, provided this field is set by the server and the negotiation facility is supported by the server. In case of a connection loss, the last received SSE event id field value is send in the "Last-Event-ID" HTTP request header as part of a new connection request sent to the SSE endpoint. Upon a receipt of such reconnect request, the SSE endpoint that supports this negotiation facility is expected to replay all missed events. Note however, that this is a best-effort mechanism which does not provide any guaranty that all events would be delivered without a loss. You should therefore not rely on receiving every single event and design your client application code accordingly. 
By default, when a connection the the SSE endpoint is lost, the event source will wait 500 ms before attempting to reconnect to the SSE endpoint. The SSE endpoint can however control the client-side retry delay by including a special retry field value in the any send event. JAX-RS SseEventSource tracks any received SSE event retry field values set by the endpoint and adjusts the reconnect delay accordingly, using the last received retry field value as the reconnect delay. 
In addition to handling the standard connection loss failures, JAX-RS SseEventSource automatically deals with any HTTP 503 Service Unavailable responses from an SSE endpoint, that contain a "Retry-After" HTTP header with a valid value. The HTTP 503 + "Retry-After" technique is often used by HTTP endpoints as a means of connection and traffic throttling. In case a HTTP 503 + "Retry-After" response is received in return to a connection request, JAX-RS SSE event source will automatically schedule a new reconnect attempt and use the received "Retry-After" HTTP header value as a one-time override of the reconnect delay.

**Comment by jim-krueger** [comment]
Fixed by #2857
