### ISSUE TITLE
Admin Center - OIDC Client Management tile is not displayed in Toolbox

### ISSUE THREAD

**Issue by meiaus** [OpenLiberty/open-liberty#21923]
I set up the liberty server to view OIDC tools in Admin Center, but didn't see OIDC Client Management tile:

![image](https://user-images.githubusercontent.com/27024803/182234162-eddcc5cf-c806-47d5-9ad6-919bcb656c10.png)

but when accessing via the endpoint URL `.../oidc/endpoint/OidcProvider/clientManagement`, the tool can be displayed

![image](https://user-images.githubusercontent.com/27024803/182234341-2f0abd6a-084b-41da-a8a1-c36253f03202.png)

Also, as a side tracking, please advise if the existing tiles of `OpenID Connect Users Token Management - OidcProvider` and `OpenID Connect Personal Token Management - OidcProvider` should be displayed with an unique image (colored icon)?

**Comment by meiaus** [comment]
@k8vance88

**Comment by meiaus** [comment]
fyi - the server.xml with the related config:

```
  ...
    <httpSession cookieSecure="true" cookieName="PTSESSID2" sslTrackingEnabled="true" invalidateOnUnauthorizedSessionRequestException="true"/>

        <openidConnectProvider id="OidcProvider" oauthProviderRef="OAuthProvider" keyStoreRef="defaultKeyStore" signatureAlgorithm="RS256" jwkEnabled="true"/>
    <oauthProvider id="OAuthProvider" autoAuthorizeParam="autoauthz" tokenFormat="mpjwt" passwordGrantRequiresAppPassword="true" internalClientId="client01" internalClientSecret="xxxxx" appPasswordLifetime="30d">
        <localStore>
            <client id="client01" name="client01" secret="xxxxx" displayname="client01" enabled="true" scope="openid profile email " appPasswordAllowed="true" appTokenAllowed="true">
                <redirect>${OIDC_CLIENT_REDIRECT}/oidcclient/redirect/client01</redirect>
            </client>
            <client id="client02" name="client02" secret="xxxxx" displayname="client02" scope="openid profile email ">
                <redirect>${OIDC_CLIENT_REDIRECT}/ibm/api/social-login/redirect/client02</redirect>
            </client>
        </localStore>
        <autoAuthorizeClient>client01</autoAuthorizeClient>
        <autoAuthorizeClient>client02</autoAuthorizeClient>
    </oauthProvider>
    <oauth-roles>
       <authenticated>
           <user name="adminUser"/>
           <special-subject type="ALL_AUTHENTICATED_USERS"/>
       </authenticated>
       <tokenManager>
           <!-- this user can manage the app-passwords and tokens of other users -->
            <user name="adminUser" />
       </tokenManager>
       <clientManager>
            <user name="adminUser" />
       </clientManager>
    </oauth-roles>
...
```

**Comment by lavenal** [comment]
Using my current local open-liberty dev image, I'm able to see the three OIDC tools in Admin Center with the version of oidc_server that I got from the security OIDC team back then during the initial implementation.

![image](https://user-images.githubusercontent.com/25039033/182251271-5da151fa-c4d7-4e10-8aa9-c4abd35b349a.png)

**Comment by lavenal** [comment]
<server>   
   
   
    <featureManager>      
      <feature>ssl-1.0</feature>
      <feature>jdbc-4.0</feature>
      <feature>appSecurity-2.0</feature>     
      <feature>openidConnectServer-1.0</feature>
      <feature>openidConnectClient-1.0</feature>
      <feature>servlet-3.1</feature>
      <feature>logstashCollector-1.0</feature>
      <feature>adminCenter-1.0</feature>
      <feature>websocket-1.1</feature>
      <feature>apiDiscovery-1.0</feature>
    </featureManager>

    <httpEndpoint id="defaultHttpEndpoint"
        host="*"
        httpPort="29080"
        httpsPort="29443" />

    <basicRegistry id="basic" realm="OpBasicRealm">
        <user name="admin" password="adminpwd" />
        <user name="test سج user" password="testuserpwd" />
        <user name="testuser" password="testuserpwd" />
        <user name="tokenuser" password="tokenuserpwd" />
        <user name="user1" password="security" />
        <user name="user2" password="security" />
     </basicRegistry> 

    <administrator-role>
        <user>admin</user>
        <user>testuser</user>
        <user>tokenuser</user>
        <user>test سج user</user>
    </administrator-role>
     
   <keyStore id="defaultKeyStore" password="keyspass" />

   <oauth-roles>
        <authenticated>
            <special-subject type="ALL_AUTHENTICATED_USERS" />  
        </authenticated>
	 <clientManager>
		<user name="testuser" /> 	 
		<user name="test سج user" />
	</clientManager>		
	 <tokenManager>
		<user name="tokenuser" /> 	 
		<user name="test سج user" />
        <user name="admin" /> 	 
	</tokenManager>		
    </oauth-roles>

    <httpSession invalidateOnUnauthorizedSessionRequestException="true" />

    <logging  traceSpecification="com.ibm.ws.security.*=all:com.ibm.ws.webcontainer.*=all:com.ibm.ws.security.oauth*=finest:com.ibm.ws.security.openidconnect.*=all:com.ibm.ws.security.oauth20.*=all:com.ibm.ws.ui.*=all:com.ibm.ws.session.*=all" traceFileName="trace.log" maxFileSize="50" maxFiles="10" />

    <openidConnectProvider id="OP" oauthProviderRef="OAUTH"/>  
    <oauthProvider id="OAUTH" httpsRequired="false"
        jwtAccessToken="false"
       passwordGrantRequiresAppPassword="true"
       accessTokenLifetime="7200s"
       internalClientId="c845821d837f42e3ae4c7b1dbcfbc3b7"
       internalClientPassword="kTdnSwBjna8uf3nOucNifvb6a1MSXtdbVPEnBNJPx2bZeAEmYk7sbaTKmDqy">
  	  <databaseStore dataSourceRef="OAuthFvtDataSource" /> 
    </oauthProvider>

    <dataSource id="OAuthFvtDataSource" jndiName="jdbc/OAuth2DB">
     <jdbcDriver libraryRef="DerbyLib" />
     <properties.derby.embedded
        databaseName="${server.config.dir}/db/derby/OAuth20DB"
        createDatabase="create" />
   </dataSource>

  <library id="DerbyLib">
    <fileset dir="${server.config.dir}/db/derby/db-derby-10.8.3.0-bin/lib"
      includes="derby.jar" />
    <fileset dir="${server.config.dir}/db/derby/db-derby-10.8.3.0-bin/lib"
      includes="derbyclient.jar" />
    <fileset dir="${server.config.dir}/db/derby/db-derby-10.8.3.0-bin/lib"
      includes="derbynet.jar" />
  </library>

    <application type="war" id="formlogin" name="formlogin" location="${server.config.dir}/apps/formlogin.war">
       
        <application-bnd>
            <security-role name="Employee">
                <special-subject type="ALL_AUTHENTICATED_USERS" />
            </security-role>
            <security-role name="Manager">
                <special-subject type="ALL_AUTHENTICATED_USERS" />
            </security-role>
            <security-role name="AllAuthenticated">
                <special-subject type="ALL_AUTHENTICATED_USERS" />
            </security-role>
        </application-bnd>
       
    </application>
</server>

**Comment by lavenal** [comment]
```
 <server>   
   
   <!-- Enable features -->
    <featureManager>      
      <feature>ssl-1.0</feature>
      <feature>jdbc-4.0</feature>
      <feature>appSecurity-2.0</feature>     
      <feature>openidConnectServer-1.0</feature>
      <feature>openidConnectClient-1.0</feature>
      <feature>servlet-3.1</feature>
      <feature>logstashCollector-1.0</feature>
      <feature>adminCenter-1.0</feature>
      <feature>websocket-1.1</feature>
    </featureManager>

    <httpEndpoint id="defaultHttpEndpoint"
        host="*"
        httpPort="29080"
        httpsPort="29443" />

    <basicRegistry id="basic" realm="OpBasicRealm">
        <user name="admin" password="adminpwd" />
        <user name="test سج user" password="testuserpwd" />
        <user name="testuser" password="testuserpwd" />
        <user name="tokenuser" password="tokenuserpwd" />
        <user name="user1" password="security" />
        <user name="user2" password="security" />
     </basicRegistry> 

    <administrator-role>
        <user>admin</user>
        <user>testuser</user>
        <user>tokenuser</user>
        <user>test سج user</user>
    </administrator-role>
     
   <keyStore id="defaultKeyStore" password="keyspass" />

   <oauth-roles>
        <authenticated>
            <special-subject type="ALL_AUTHENTICATED_USERS" />  
        </authenticated>
	 <clientManager>
		<user name="testuser" /> 	 
		<user name="test سج user" />
	</clientManager>		
	 <tokenManager>
		<user name="tokenuser" /> 	 
		<user name="test سج user" />
        <user name="admin" /> 	 
	</tokenManager>		
    </oauth-roles>

<httpSession invalidateOnUnauthorizedSessionRequestException="true" />
   
<logging  traceSpecification="com.ibm.ws.security.*=all:com.ibm.ws.webcontainer.*=all:com.ibm.ws.security.oauth*=finest:com.ibm.ws.security.openidconnect.*=all:com.ibm.ws.security.oauth20.*=all:com.ibm.ws.ui.*=all:com.ibm.ws.session.*=all" traceFileName="trace.log" maxFileSize="50" maxFiles="10" />
 
<openidConnectProvider id="OP" oauthProviderRef="OAUTH"/>  
    <oauthProvider id="OAUTH" httpsRequired="false"
        jwtAccessToken="false"
       passwordGrantRequiresAppPassword="true"
       accessTokenLifetime="7200s"
       internalClientId="c845821d837f42e3ae4c7b1dbcfbc3b7"
       internalClientPassword="kTdnSwBjna8uf3nOucNifvb6a1MSXtdbVPEnBNJPx2bZeAEmYk7sbaTKmDqy">
  	  <databaseStore dataSourceRef="OAuthFvtDataSource" /> 
</oauthProvider>
 
<dataSource id="OAuthFvtDataSource" jndiName="jdbc/OAuth2DB">
     <jdbcDriver libraryRef="DerbyLib" />
     <properties.derby.embedded
        databaseName="${server.config.dir}/db/derby/OAuth20DB"
        createDatabase="create" />
   </dataSource>

  <library id="DerbyLib">
    <fileset dir="${server.config.dir}/db/derby/db-derby-10.8.3.0-bin/lib"
      includes="derby.jar" />
    <fileset dir="${server.config.dir}/db/derby/db-derby-10.8.3.0-bin/lib"
      includes="derbyclient.jar" />
    <fileset dir="${server.config.dir}/db/derby/db-derby-10.8.3.0-bin/lib"
      includes="derbynet.jar" />
  </library>

    <application type="war" id="formlogin" name="formlogin" location="${server.config.dir}/apps/formlogin.war">
       
        <application-bnd>
            <security-role name="Employee">
                <special-subject type="ALL_AUTHENTICATED_USERS" />
            </security-role>
            <security-role name="Manager">
                <special-subject type="ALL_AUTHENTICATED_USERS" />
            </security-role>
            <security-role name="AllAuthenticated">
                <special-subject type="ALL_AUTHENTICATED_USERS" />
            </security-role>
        </application-bnd>
       
    </application>
</server>
```

**Comment by meiaus** [comment]
Thanks @lavenal for sharing the information.  I'll compare with the server configuration to see the difference.

**Comment by meiaus** [comment]
To clarify, from https://openliberty.io/docs/latest/oidc-tools.html, "To use any of the OIDC [Admin Center](https://openliberty.io/docs/latest/reference/feature/adminCenter.html) tools, you must enable the Admin Center and [OpenID Connect Provider](https://openliberty.io/docs/latest/reference/feature/openidConnectServer.html) features in your server.xml file and [configure OIDC](https://openliberty.io/blog/2019/09/13/microprofile-reactive-messaging-19009.html#oidc).", where https://openliberty.io/blog/2019/09/13/microprofile-reactive-messaging-19009.html#oidc pointed out:

```
<!--
         localStore for demo use, a backing database is used instead in production.
         When localStore is used, all client data and token status is held
         in memory only.
        -->
        <localStore>

          <!-- appPasswordAllowed and appTokenAllowed allow
          this client to create app-passwords and app-tokens -->
          <client displayname="RP" enabled="true"
                name="RP" secret="thesecret"
                scope="openid profile email"
                preAuthorizedScope="openid profile email"
                appPasswordAllowed="true"
                appTokenAllowed="true"
          >
                <redirect>https://localhost:19443/oidcclient/redirect/RP</redirect>
          </client>
        </localStore>
```
please advise if the problem is my configuration using local store?

**Comment by lavenal** [comment]
This is a question to the OIDC security team. I recalled using localStore at the beginning but didn't remember whether it actually worked for me. Eventually I switched to use the server.xml from Chunlong and Aruna and added the admin center configuration into it.

Could you add the following trace spec to your server.xml?

`<logging  traceSpecification="com.ibm.ws.security.*=all:com.ibm.ws.webcontainer.*=all:com.ibm.ws.security.oauth*=finest:com.ibm.ws.security.openidconnect.*=all:com.ibm.ws.security.oauth20.*=all:com.ibm.ws.ui.*=all:com.ibm.ws.session.*=all" traceFileName="trace.log" maxFileSize="50" maxFiles="10" />`

Then send me the trace. With the trace, I may be able to figure out what's going on in the admin center side. Thanks.

**Comment by meiaus** [comment]
Please find the trace.log:

[trace.log.zip](https://github.com/OpenLiberty/open-liberty/files/9245302/trace.log.zip)

**Comment by meiaus** [comment]
From the trace,

1. This seems to indicate 3 tools are detected:
```
[8/2/22, 15:58:47:991 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3 Current Feature Provisioning state: complete
[8/2/22, 15:58:47:991 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3 Final provisioning state: complete
[8/2/22, 15:58:47:991 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3 Processing feature openidConnectServer-1.0:
[8/2/22, 15:58:47:991 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3    SymbolicName:com.ibm.websphere.appserver.openidConnectServer-1.0
[8/2/22, 15:58:47:991 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3    IBMShortName:openidConnectServer-1.0
[8/2/22, 15:58:47:991 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3    Version:     1.0.0
[8/2/22, 15:58:47:991 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3    Name:        OpenID Connect Provider 1.0
[8/2/22, 15:58:47:992 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3 return map: {personalTokenManagement=OpenID Connect Personal Token Management, clientManagement=OpenID Connect Client Management, usersTokenManagement=OpenID Connect Users Token Management}

```

2. But during `determineProviderConfig`, it confirmed with local stores and when exiting, only 2 tools (personal token management and users token management) are returned.  Wondering if local stores has a limitation on client management?

```
8/2/22, 15:58:48:088 EDT] 0000002a id=0422c921 ibm.ws.security.openidconnect.server.plugins.UIHelperService > determineProviderConfig Entry 

...

[8/2/22, 15:58:48:152 EDT] 0000002a id=6885511b com.ibm.ws.security.oauth20.internal.LibertyOAuth20Provider  > createLocalStores Entry 
[8/2/22, 15:58:48:152 EDT] 0000002a id=00000000 com.ibm.ws.security.oauth20.internal.LibertyOAuth20Provider  3 Local store is enabled.
...
[8/2/22, 15:58:49:042 EDT] 0000002a id=6885511b com.ibm.ws.security.oauth20.internal.LibertyOAuth20Provider  > isLocalStoreUsed Entry 
[8/2/22, 15:58:49:042 EDT] 0000002a id=6885511b com.ibm.ws.security.oauth20.internal.LibertyOAuth20Provider  < isLocalStoreUsed Exit  
                                                                                                               true

...

[8/2/22, 15:58:49:042 EDT] 0000002a id=0422c921 ibm.ws.security.openidconnect.server.plugins.UIHelperService < determineProviderConfig Exit  
                                                                                                               {personalTokenManagement=/oidc/endpoint/OidcProvider/personalTokenManagement, name=OidcProvider, usersTokenManagement=/oidc/endpoint/OidcProvider/usersTokenManagement}
[8/2/22, 15:58:49:042 EDT] 0000002a id=00000000 ibm.ws.security.openidconnect.server.plugins.UIHelperService < getProviderInfo Exit  
                                                                                                               [{personalTokenManagement=/oidc/endpoint/OidcProvider/personalTokenManagement, name=OidcProvider, usersTokenManagement=/oidc/endpoint/OidcProvider/usersTokenManagement}]
[8/2/22, 15:58:49:042 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3 endpoint providers: [{personalTokenManagement=/oidc/endpoint/OidcProvider/personalTokenManagement, name=OidcProvider, usersTokenManagement=/oidc/endpoint/OidcProvider/usersTokenManagement}]
[8/2/22, 15:58:49:042 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3 endpointUrls: {usersTokenManagement.OidcProvider=/oidc/endpoint/OidcProvider/usersTokenManagement, personalTokenManagement.OidcProvider=/oidc/endpoint/OidcProvider/personalTokenManagement}
[8/2/22, 15:58:49:043 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3 Adding FeatureTool openidConnectServer.usersTokenManagement.OidcProvider-1.0:


[8/2/22, 15:58:49:043 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3    endpointName:      OpenID Connect Users Token Management - OidcProvider
[8/2/22, 15:58:49:043 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3    endpointShortName: usersTokenManagement.OidcProvider-1.0
[8/2/22, 15:58:49:043 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3    icon:              /ibm/api/adminCenter/v1/icons/com.ibm.websphere.appserver.openidConnectServer-1.0/usersTokenManagement
[8/2/22, 15:58:49:043 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3    url:               /oidc/endpoint/OidcProvider/usersTokenManagement
[8/2/22, 15:58:49:154 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3 Adding FeatureTool openidConnectServer.personalTokenManagement.OidcProvider-1.0:
[8/2/22, 15:58:49:154 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3    Description:       This feature enables web applications to integrate OpenID Connect  Server 1.0 for authenticating users instead of, or in addition to, the configured user registry.
[8/2/22, 15:58:49:154 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3    endpointName:      OpenID Connect Personal Token Management - OidcProvider
[8/2/22, 15:58:49:154 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3    endpointShortName: personalTokenManagement.OidcProvider-1.0
[8/2/22, 15:58:49:154 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3    icon:              /ibm/api/adminCenter/v1/icons/com.ibm.websphere.appserver.openidConnectServer-1.0/personalTokenManagement
[8/2/22, 15:58:49:154 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3    url:               /oidc/endpoint/OidcProvider/personalTokenManagement
[8/2/22, 15:58:49:154 EDT] 0000002a id=00000000 com.ibm.ws.ui.internal.v1.utils.FeatureToolService           3 Processing feature com.ibm.websphere.appserver.adminCenter.tool.explore-1.0:

...

```

**Comment by meiaus** [comment]
From https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.openidconnect.server/src/com/ibm/ws/security/openidconnect/server/plugins/UIHelperService.java:

```
...
clientadmin = ! provider.isLocalStoreUsed();
...

if (client != null) {
             map.put("personalTokenManagement", epPrefix + info.getName() + "/personalTokenManagement");
             map.put("usersTokenManagement", epPrefix + info.getName() + "/usersTokenManagement");
         }
         if(clientadmin) {
             map.put("clientManagement", epPrefix + info.getName() + "/clientManagement");
         }
         return map;

```

**Comment by meiaus** [comment]
@ayoho could you confirm if the above code indicates local store will not be used for the client management?  Thanks.

**Comment by meiaus** [comment]
@lavenal while waiting for @ayoho to confirm on the client management part, could you check if the other tools (personal/users token management) have an image icon issue? Thanks.

**Comment by ayoho** [comment]
@meiaus Correct, local store does not use the client management APIs so cannot be managed through Admin Center. The 19.0.0.9 blog that you have linked says
> Servers using a database (not this example) can now manage client registration at https://host/:port/oidc/endpoint/(provider id)/clientManagement:

followed by the screenshot for managing clients.

**Comment by lavenal** [comment]
@meiaus As shown in earlier screen capture of Admin Center, each of the three tools has its own icon. Please check your wlp image to confirm whether the following icon files exist:

wlp/lib/features/icons/com.ibm.websphere.appserver.openidConnectServer-1.0/clientManagement/OSGI-INF/clientManagement_142.png
wlp/lib/features/icons/com.ibm.websphere.appserver.openidConnectServer-1.0/clientManagement/OSGI-INF/clientManagement_78.png
wlp/lib/features/icons/com.ibm.websphere.appserver.openidConnectServer-1.0/personalTokenManagement/OSGI-INF/personalTokenManagement_142.png
wlp/lib/features/icons/com.ibm.websphere.appserver.openidConnectServer-1.0/personalTokenManagement/OSGI-INF/personalTokenManagement_78.png
wlp/lib/features/icons/com.ibm.websphere.appserver.openidConnectServer-1.0/usersTokenManagement/OSGI-INF/usersTokenManagement_142.png
wlp/lib/features/icons/com.ibm.websphere.appserver.openidConnectServer-1.0/usersTokenManagement/OSGI-INF/usersTokenManagement_78.png

**Comment by meiaus** [comment]
The test env is WebSphere Liberty:
```
# ./server version

WebSphere Application Server 22.0.0.8 (1.0.67.cl220820220719-1056) on Eclipse OpenJ9 VM, version 11.0.15+10 (en_US)

```
and didn't seem to have the files:

```
[root@3q22-liberty-1 icons]# pwd
/home/pent/wlp/lib/features/icons
[root@3q22-liberty-1 icons]# ls -lt
total 0
drwxrwxr-x 3 pent pent 22 Aug  1 12:49 com.ibm.websphere.appserver.adminCenter.tool.javaBatch-1.0
drwxrwxr-x 3 pent pent 22 Aug  1 12:49 com.ibm.websphere.appserver.adminCenter.tool.deploy-1.0
drwxrwxr-x 3 pent pent 22 Aug  1 12:49 com.ibm.websphere.appserver.adminCenter-1.0
drwxrwxr-x 3 pent pent 22 Aug  1 12:49 com.ibm.websphere.appserver.adminCenter.tool.explore-1.0
drwxrwxr-x 3 pent pent 22 Aug  1 12:49 com.ibm.websphere.appserver.adminCenter.tool.serverConfig-1.0

```

**Comment by lavenal** [comment]
I don't want why it doesn't have the com.ibm.websphere.appserver.openidConnectServer-1.0 directory under lib/features/icons. But it explains why you're not getting the icons. The directory is there in my dev driver of both open liberty and close liberty.

Katie tested this with a Liberty install she has this morning using the same server configuration that I have and confirmed that the OIDC tools were there in Admin Center. @k8vance88, could you check the version of your Liberty install?

**Comment by meiaus** [comment]
@lavenal quick clarification, to `have the com.ibm.websphere.appserver.openidConnectServer-1.0 directory under lib/features/icons`, is it from any liberty installation by default? or only appears when OIDC configuration is added to server.xml (to enable OIDC tools in Admin Center)?

**Comment by lavenal** [comment]
Since I usually don't do a liberty install, I won't be able to answer your question on whether any liberty install would lay down those icon files. But the existence of the icon files certainly are not dictated by server.xml. May be @k8vance88 could also let us know what kind of Liberty install she has in addition to the version I asked earlier.

**Comment by meiaus** [comment]
fyi - I see from OL repo: `https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.websphere.appserver.features/visibility/public/openidConnectServer-1.0/resources/icons/com.ibm.websphere.appserver.openidConnectServer-1.0` with the mentioned files, but not from `https://github.ibm.com/websphere/WS-CD-Open/tree/integration/dev/com.ibm.websphere.appserver.features/visibility/public`

**Comment by k8vance88** [comment]
I tested Open Liberty from the dev location. But not with our Admin center dev application.  I am installing 22008 and will see what I get.  I will install OL 22008 as well and see if it has the same issue.

**Comment by k8vance88** [comment]
They are missing from Liberty builds only.  Not OL. The OL builds were fixed via this issue:  See https://github.com/OpenLiberty/open-liberty/issues/17150.

**Comment by k8vance88** [comment]
We had this problem before.  See https://github.com/OpenLiberty/open-liberty/issues/17150

**Comment by meiaus** [comment]
Thanks @k8vance88 for verification.  I'll open new issue to track the missing in WebSphere Liberty build (see https://github.ibm.com/websphere/WS-CD-Open/issues/27465).
Will also reassign the current issue to SSO team for doc followup on local store related with client management.

**Comment by meiaus** [comment]
@ayoho as further discussed in the slack, per your comment "I’d add something to https://openliberty.io/docs/latest/oidc-tools.html#client to say client management through Admin Center is only for servers using a database store.", I'm reassigning the issue to SSO team for the doc update.  Thanks.

Also you pointed out `/clientManagement endpoint for an OP that uses localstore` may not be allowed (as I shared in the beginning of the issue using `.../oidc/endpoint/OidcProvider/clientManagement`), please also consider if any action to follow? (e.g., a separate issue to do code detection? or using this current issue to do doc update as well?)  Thanks.

**Comment by ayoho** [comment]
Opened https://github.com/OpenLiberty/open-liberty/issues/21957 to track investigating rejecting requests to the client management endpoint for OPs that use localstore.

**Comment by meiaus** [comment]
<del>@ayoho just to confirm, will #21957 also  handle the doc update regarding local store and client management?  otherwise, I was initially thinking #21923 can be used for the doc update here?</del>      See the new comment below.

**Comment by meiaus** [comment]
I've opened a new issue: https://github.com/OpenLiberty/open-liberty/issues/22010 to track the doc update on overall OIDC Tools related.
