### ISSUE TITLE
BETA BLOG - Open Liberty Instant On With Checkpoint and Restore

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#21977]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty. For this post to be included in the beta issue please make sure that this is completed by the end of Friday following the GM (Wednesday). 

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name: Instant On Checkpoint feature
   
   Short feature name:  checkpoint-1.0 

2. Who is the target persona? Who do you expect to use the update? Application Developer, Operations

    application developers, operations

3. Write a paragraph to summarise the update, including the following points:
    
   - A sentence or two that introduces the update to someone new to the general technology/concept.

     Open Liberty InstantOn allows applications running on Open Liberty to checkpoint the startup process and restore the application process very quickly, providing InstantOn behavior for the application.
   - What was the problem before and how does your update make their life better? (Why should they care?)

     Starting an application can take several seconds and sometimes minutes before being able to service the applications first request.  Longer startup times inhibit an applications ability to scale to zero when deployed in a cloud environment such as Kubernetes.  Restoring an application from a checkpoint process can take much less time, up to 10 times faster than starting the Liberty application from the beginning.
   
   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.

     For details on how to use Open Liberty InstantOn have a look at the InstantOn beta blog at: https://ibm.biz/InstantOn

   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by tjwatson** [comment]
Open Liberty 22.0.0.11-beta brings you an exciting feature that enables instant on for Jakarta EE and MicroProfile applications using Open Liberty, [OpenJ9](https://www.eclipse.org/openj9/) and a Linux technology called Checkpoint and Restore [CRIU](https://criu.org/).  In serverless environments it is important to have applications that can startup very quickly.  Instant on applications enable the application instances to scale to zero, for example, by using Kubernetes with technologies like Knative.  With instant on applications, when the application instances reach zero the KNative auto-scaler is able to quickly spin up new instances of your application without introducing high latency into your application performance.  Scale to zero can help reduce your overall cloud costs by reducing the overall number an application instance when it has no ongoing requests.

To enable instant on behavior for Jakarta EE and MicroProfile the Open Liberty 22.0.0.11-beta provides support for taking a checkpoint of the server process as it is being started.  The checkpoint is a record of the running server process which can be persisted and then very quickly restored to bring back the server process into the exact state it was in when the checkpoint was taken.  This enables the server instance, along with any configured applications to be restored multiple times into distinct instances of your application.

**Comment by tam512** [comment]
Please also state all prerequisites for InstantOn such as minimum OS kernel version of 5.9 or higher

**Comment by tjwatson** [comment]
Note that this is intended to be a standalone blog post.

**Comment by tjwatson** [comment]
This beta blog has been done for a while.  Closing.
