### ISSUE TITLE
Update MicroProfile Fault Tolerance to work with MP Metrics 5.0

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#22046]
We don't expect any code changes will be needed for MP FT, since the metric types MP FT uses are still the same.

- [x] update to tolerate MP Metrics 5.0
- [x] test to ensure metrics function as expected

This relates to epic #20018

**Comment by Azquelt** [comment]
#22063 has MP Fault Tolerance 4.0 tolerating MP60 and running tests with MP60 features (not passing yet because metrics is missing)

I'm waiting for the `mpMetrics-5.0` feature to be available to test with.

**Comment by Channyboy** [comment]
In MicroProfile Metrics 5.0, changes include removal of the `MetricType` class and the `MetricRegistry.register(..)` methods.

See (RC2 is current as of this post) https://download.eclipse.org/microprofile/microprofile-metrics-5.0.0-RC2/microprofile-metrics-spec-5.0.0-RC2.html#release_notes_5_0

This would affect the `MetricRecorder30Impl`.
- `MetricType` is used during `Metadata` creation 
- Gauges whos value are provided by a `Supplier` are registered with the `MetricRegistry.register(...)`. The [gauge supplier](https://download.eclipse.org/microprofile/microprofile-metrics-5.0.0-RC2/apidocs/org/eclipse/microprofile/metrics/MetricRegistry.html#gauge-org.eclipse.microprofile.metrics.Metadata-java.util.function.Supplier-org.eclipse.microprofile.metrics.Tag...-) can be used instead.

**Comment by Azquelt** [comment]
Further breaking changes
- `MetricRegistry.Type` has been removed, replaced by constants on `MetricRegistry`
- The `@RegistryType` qualifier has been replaced by `@RegistryScope`
  - This is used by the Fault Tolerance 4.0 TCK

**Comment by Channyboy** [comment]
In MP Metrics 5.0 PR for noship deliveryhttps://github.com/OpenLiberty/open-liberty/pull/22715

- Removed `mpMetrics-5.0` from the `io.openliberty.mpFaultTolerance4.0-metrics.feature` auto-feature 
See: https://github.com/OpenLiberty/open-liberty/pull/22715/commits/3d40d96bd9744f24001a0890e06412fce4164a2e

- Temporarily disabling MP 6 repeat for the FT TCKs in `io.openliberty.microprofile.faulttolerance.4.0.internal_fat_tck`
and use a new `RepeatTests` just for `MetricRemovalTest` in  `com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics` where MP6 repeat is skipped.
See:  https://github.com/OpenLiberty/open-liberty/pull/22715/commits/4f716954b9e4c214c7791d28fe8cd9a7162924e4

Will need to reactivate the Fault Tolerance Tests for MP 60 repeat tests.

**Comment by Azquelt** [comment]
This work was done in #22839 which included repeating the Fault Tolerance 4.0 TCK against `mpMetrics-5.0`. The TCK has fairly comprehensive tests for the required metrics so no further tests need to be added.
