### ISSUE TITLE
Expression Language 5.0: Validate generics migration information

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#22047]
Do any validation necessary for the comment here: https://github.com/OpenLiberty/open-liberty/issues/18730#issuecomment-1175344258

> Added generics migration problem to slide 34 Javac errors can occur, so casting needs to be added to JSP Expressions such as <%= expression %> ( This needs to be verified once the Liberty Page-3.1 is beta ready).

**Comment by volosied** [comment]
Original TCK Error:
```
PWC6199: Generated servlet error: reference to print is ambiguous both method print(char[]) in jakarta.servlet.jsp.JspWriter and method print(java.lang.String) in jakarta.servlet.jsp.JspWriter match
```

I tested the `jstl_core_iter_fortok_web` app from the JSTL TCK where the error above occurred.  (see attachment in `https://github.com/eclipse-ee4j/jakartaee-tck/issues/882` ) 

The `positiveForTokensDeferredValueTest.jsp` page rendered fine on Open Liberty with the Pages 3.1 feature, so I don't think this is a migration concern for us anymore. 

Nor have we seen this javac error in any of our FATs.

**Comment by volosied** [comment]
Related to #22047

Closing as I don't see any further action here.
