### ISSUE TITLE
Invalid character warning for colon in WorkQueueManagerImplMBeanWrapper objectName 

### ISSUE THREAD

**Issue by ocseal** [OpenLiberty/open-liberty#22040]
**Describe the bug**  
A colon character in the Apache CXF WorkQueueManagerImplMBeanWrapper class's objectName creates a warning and a javax.management.MalformedObjectNameException caused by the invalid ':' character when javax.management.ObjectName.construct is called. This issue occurs in Open Liberty 22.0.0.8 when it did not appear in 22.0.0.7.

[messages.log](https://github.com/OpenLiberty/open-liberty/files/9295104/messages.log)

**Steps to Reproduce**  
1. Clone the Cargo Tracker repository from https://github.com/ocseal/cargotracker/tree/OL-experimental and make sure Maven is set up properly.
2. Ensure you are running Java SE 8, Java SE 11, or Java SE 17 and make sure JAVA_HOME is set. 
3. Navigate to the cargotracker directory and develop the application with Liberty Maven Plugin: `mvn -P openliberty liberty:dev`.
4. Go to http://localhost:8080/cargo-tracker and select "Administration Interface".
5. Select the globe icon next to cargo object DEF789 to route the cargo. 
6. Return to the terminal and view the error.

**Expected behavior**  
The cargo routes properly but there should be no exception or warning in the terminal after routing is completed. The ObjectName construct() method should run without issue.

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.8
 - Affected feature(s): jaxws-2.2
 - Java Version: 
        IBM Semeru Runtime Open Edition 17.0.3.0 (build 17.0.3+7)
        Eclipse OpenJ9 VM 17.0.3.0 (build openj9-0.32.0, JRE 17 Mac OS X amd64-64-Bit Compressed References 20220422_155 (JIT enabled, AOT enabled)
        OpenJ9   - 9a84ec34e
        OMR      - ab24b6666
        JCL      - dc07fd49b92 based on jdk-17.0.3+7)
 - [server.txt](https://github.com/OpenLiberty/open-liberty/files/9295116/server.txt) xml Github unsupported. 

**Additional context**  
Attempting to work around by disabling the JAXWS feature.

**Comment by jhanders34** [comment]
#regression that was introduced by the JAXWS update to CXF 3.4.3.  FYI @neuwerk

**Comment by rumanaHaque** [comment]
Also hit the same issue while running the svt application ACME for the JAX-RS tests that I have.

**Comment by rumanaHaque** [comment]
Tested a successful patch from @jim-krueger for this defect. The patch got rid of the extra warning messages.
