### ISSUE TITLE
Updating to OSGi R8 Declarative Services Felix SCR implementation adds an implicit service property

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#22057]
# Background
The OSGi R8 Declarative Services specification added a new implicit service reference for something called a satisfying condition:

https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.component.html#service.component-satisfying.condition

When running with Felix SCR version 2.2.2 which implements OSGi R8 Declarative Services each component at runtime has an implicit service reference added named `osgi.ds.satisfying.condition`.  In addition to the named reference the reference also has a default `target` filter defined as `target="(osgi.condition.id=true)"`.  The end result is that SCR will automatically add a configuration key for every component named `osgi.ds.satisfying.condition.target` which default to a value of  `(osgi.condition.id=true)`.  The following is the complete component XML that is added by default at runtime by the R8 SCR implementation:

```
<reference name="osgi.ds.satisfying.condition"
    interface="org.osgi.service.condition.Condition"
    target="(osgi.condition.id=true)"
    policy="dynamic"
/>
```

The OSGi R8 framework always makes available in the service registry a registration of the `true` condition: `org.osgi.service.condition.Condition;osgi.condition:Boolean=true`

https://docs.osgi.org/specification/osgi.core/8.0.0/service.condition.html#service.condition-true.condition

This allows the implicit reference to the `true` condition from all the components to always be satisfied.  But it also allows for configuration to change the `osgi.ds.satisfying.condition.target` component configuration property to another filter so the component can be satisfied (enabled) by some other condition.

# Problem

With OSGi R8 SCR implementation every component receiving a configuration Map will now be giving a Map that contains the key `osgi.ds.satisfying.condition.target`.  Several of our components try to verify that the config map they are given does not contain unknown "extra" keys.  With OSGI R8 SCR we see several warnings in the logs complaining about the unknown key.  For Liberty code we can update all the places that do this check and make them ignore the new specified key.  See the second commit to the PR #22004 for all the spots found in Open Liberty that do this checking so far.  For example:

```java
    private boolean skipKey(String key) {
        return key.equals("id") ||
               key.equals("type") ||
               key.startsWith("service.") ||
               key.startsWith("component.") ||
               key.startsWith("config.") ||
               key.startsWith("objectClass") ||
               key.startsWith("osgi.ds.");
    }
```
Here the `key.startsWith("osgi.ds.")` was added to start ignoring (skipping) all keys that start with `osgi.ds.`.  Another option would be to ignore all keys that end with `.target` but that seems to general.

A concern is that this change in behavior could break other bundles from product extensions.

Also note that the OSGi specification makes this statement:
```
All component property names starting with a reference name followed by a full stop ('.' \u002E) are reserved for use by this specification.
```

https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.component.html#service.component-reference.properties

It should also be assumed that any keys that fall under `osgi.` should be treated as properties of the specification itself and their implementations.  Any property ending in `.target` could be there to configure a reference target filter and should likely be ignored by components receiving configuration.

**Comment by cbridgha** [comment]
Tom to socialize this to product extensions in embedders and other widely known channels. - Will come back in two weeks

**Comment by tjwatson** [comment]
The SCR update happened in PR #23596

No negative feedback from product extensions has been received regarding the additional configuration property.
