### ISSUE TITLE
Workarea cache ID for applications is unstable across server restarts.

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#22060]
### References

**Current discussion** "cics-liberty-slow-startup": https://ibm.enterprise.slack.com/archives/CNU11JKLZ/p1659087683048639

**Issue** "Unnecessary application expansion on restart": https://github.com/OpenLiberty/open-liberty/issues/22058

**Pull Request** "Order same-factory batches of configurations; generate PIDs with a counter for each factory PID.": https://github.com/OpenLiberty/open-liberty/pull/22200

**APAR** "UNNECESSARY FILE IO FOR CICS BUNDLES WITHIN LIBERTY JVM": https://smartcare.austin.ibm.com/cgi-bin/secure_pmr_apar_getter.pl?APAR=PH43575

**XXX Pull Request XXX** "Change workarea for application containers to the application ID, if available": https://github.com/OpenLiberty/open-liberty/pull/22025 **XXX Not in use XXX**

### Background

The Liberty Artifact File System creates three cache folders per application archive:

```
  wlp/usr/servers/test/workarea/org.eclipse.osgi/47/data:
    cache/<app-cache-id>
    cacheAdapt/<app-cache-id>
    cacheOverlay/<app-cache-id>
```

Various data is written to these cache folders.  In particular, when "autoExpand" is false, nested application archives are written to the "cache" folder:

For example, application archive "TS.ear" contains web module archive "TS.war", which contains library archive "TestServlet40.jar":

`  TS.ear -> TS.war -> WEB-INF/lib -> TestServlet40.jar`

The following workarea contents are generated:
```
  wlp/usr/servers/test/workarea/org.eclipse.osgi/47/data/cache/
    <app-cache-id>/.cache/TestServlet40.war
    <app-cache-id>/.cache/.cache/TestServlet40.war/WEB-INF/lib/TestServlet40.jar
```
The intent is for these cache folders to be retained when the server is stopped, and to be reused when the server is restarted.
(That is, as long as the applications remain configured when the server is stopped.  Removal of an application from the server configuration causes the cache folders of that application to be removed when the server is stopped.)

Key "application cache ID" values are used to link applications to the workarea.  Currently, the "service PID" value is used as the application cache ID.

### Problem

Any modification to the server configuration which changes the configuration time stamp can cause a different "service PID" value to be generated.  That is, regardless of the particular modifications which were made.  Most importantly, the update to the server configuration need not have updated any application configurations.

The result is that the nested archives of applications may be re-expanded on a startup.  This directly impacts startup performance, in proportion to the size of the application which is re-expanded:

1. There is extra IO re-expanding the archive.
2. Extra disk space is consumed by the duplicate expansion.
3. The class cache will see classes as arising from a new location, invalidating application classes previously stored in the class cache.
4. Use of disk space above previously set allocations will cause very timely expansion of the file system on Z/OS systems.

These performance impacts can become severe, for example, in environments which have many server instances each with a large application, and which are restarted in groups.

For example, see the current discussion "cics-liberty-slow-startup": https://ibm.enterprise.slack.com/archives/CNU11JKLZ/p1659087683048639

In the CICS test environment, the following duplication was noted:
```
LIBERTY2/workarea/org.eclipse.osgi/51/data/cache/com.ibm.ws.app.manager_28/.cache/WEB-INF/lib/sample-1.5.1.jar
LIBERTY2/workarea/org.eclipse.osgi/51/data/cache/com.ibm.ws.app.manager_31/.cache/WEB-INF/lib/sample-1.5.1.jar 
```
`<application id="SpringTest" location="/deploy/Spring/com.ibm.cics.springboot.SpringTest.war" type="war" />`

The CICS environment updates and restarts servers in groups of 6, with each application having web module archives which are 50MB or larger.  This causes all four of the noted problems.

### Analysis

The problem is the use of the unstable "service PID" as the "application workarea cache ID".

A solution will be to generate a cache ID which is stable across restarts for reasonable changes to the server configuration.

An initial and easy to implement solution is to use the configured application ID when one is available.  This is amenable to the current CICS APAR, which assigns the application name as the application ID.  (The linked pull request implements this solution, which has been tested through a personal build, but not yet in the CICS test environment where the problem was discovered.)

Requiring that an application ID be assigned is undesirable: An explicit configured value should not be necessary.

### Question

_Can the configured application ID be used as the cache ID for the workarea application cache, as either a temporary solution, or as the correct solution?  If a different solution is needed, how should the application cache ID be generated so that the value is stable across server restarts?_

**Comment by cbridgha** [comment]
Ran out of time and will come back to this in two weeks, but consensus was to use a generated key based on the file state (Hash value?) rather than introducing an end user requirement having an application "id" for cache benefit.

**Comment by tbitonti** [comment]
Discussed this within the Kernel team, and we will be trying a strategy of processing the configuration elements in their sequence (natural) order.  Further, counters are managed per factory PID.  That should ensure that similar configurations generate the same PIDs.  Net, PID generation should be more consistent.  Consequently, the generation of cache IDs does not need to be updated.

**Comment by tbitonti** [comment]
To guard against PID changes between updates, the configuration ID property is used as the first choice for the cache ID.  This is a best attempt.  Changes which re-order configuration elements or which add or remove elements will cause unpredictable PID assignments.

The resulting fix has both the original strategy, which is to prefer to use the ID property as the cache ID, and the second strategy, which is to order the processing of elements by sequence number.

This hybrid strategy provides a fix for the basic restart with no re-ordering changes of same type elements, for the case when no IDs are available.  The hybrid strategy also provides a work-around for re-ordering cases, that is, to require the ID property be assigned.

**Comment by tbitonti** [comment]
Followup for 30-Aug-2022:

### Summary

1. Use of the configuration "id" property is not satisfactory, since the "id" property is optional.
1. Instead, application elements are assigned IDs based on their order within the configuration.
1. The "id" property is still used when available, since the assigned "id" provides a clear indication of intent.
1. This strategy has limitations (which are not worse than current behavior).

### Reference

**Defect Issue** "Unnecessary application expansion on restart"
https://github.com/OpenLiberty/open-liberty/issues/22058

**Design Issue** "Workarea cache ID for applications is unstable across server restarts."
https://github.com/OpenLiberty/open-liberty/issues/22060

**APAR** "UNNECESSARY FILE IO FOR CICS BUNDLES WITHIN LIBERTY JVM"
https://smartcare.austin.ibm.com/cgi-bin/secure_pmr_apar_getter.pl?APAR=PH43575

**Pull Request** "Order same-factory batches of configurations; generate PIDs with a counter for each factory PID."
https://github.com/OpenLiberty/open-liberty/pull/22200

**Pull Request** (Merged into 22200) "Change workarea for application containers to the application ID, if available":
https://github.com/OpenLiberty/open-liberty/pull/22025

### Background

1. See the design issue 22060.
1. Note that problems of aligning "same" elements after server restarts is no different than current problems, which include alignment problems processing configuration updates.  Generally, changes to the order of same-type elements will result in misalignments.

### Updated fix strategy

1. When processing the initial configuration, generate identifiers for the the configuration elements in sequence order. Singleton elements are processed in sequence order.  Factory elements are processed in two steps: Factory elements are partitioned by factory ID.  The elements of this partition are processed an arbitrary order.  Factory elements within the partition for a specific factory ID are processed in sequence order.
2. Element IDs are assigned starting from 0.  A counter is used per factory ID.
3. Application cache IDs are assigned either using the "id" property from the configuration, or using the element ID. Preference is to the "id" property value.
4. Cache IDs are URL encoded to ensure safe file names are generated.

### Discussion

1. Giving preference to the "id" property ensures that identity assignment intents are respected by configuration processing.
2. Ordering configuration elements ensures that similar configurations obtain the same cache IDs.
3. Processing of configuration updates is unchanged.

### Limitations

1. Configuration updates which add and remove elements will result in misalignment of application cache IDs on restart.

For example, consider an initial configuration which has two application elements:

**Initial:**
`<application location="myApp1.ear"/>`
`<application location="myApp2.ear"/>`

Two updates are made, the first which removes "myApp1.ear", and a second which adds back "myApp1.ear" but as the second application:

**After first update:**
`<application location="myApp2.ear"/>`

**After second update:**
`<application location="myApp2.ear"/>`
`<application location="myApp1.ear"/>`

On the initial start, configuration IDs are assigned as follows:
`<application location="myApp1.ear"/>  ==> "com.ibm.ws.app.manager_0`
`<application location="myApp2.ear"/>  ==> "com.ibm.ws.app.manager_1`

After the restart, the configuration ID assignments are reversed:
`<application location="myApp2.ear"/>  ==> "com.ibm.ws.app.manager_0`
`<application location="myApp1.ear"/>  ==> "com.ibm.ws.app.manager_1`

**Comment by tbitonti** [comment]
Implemented and delivered.
See PR #22200
