### ISSUE TITLE
JPA 3.1 Feature Test Summary

### ISSUE THREAD

**Issue by jgrassel** [OpenLiberty/open-liberty#22077]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

Added a new FAT bucket `com.ibm.ws.jpa.tests.jpa_31_fat` which specifically validates the new function introduced in JPA 3.1.  Existing FAT buckets have been updated to include the EE10 repeat action so that all of the existing JPA FAT buckets will also run against JPA 3.1.

### List of FAT projects affected

New FAT:
com.ibm.ws.jpa.tests.jpa_31_fat

Existing FAT (many have new 3.1 specific projects deriving from a common project):
com.ibm.ws.jpa.tests.beanvalidation_jpa_3.1_fat
com.ibm.ws.jpa.tests.container.client_fat
com.ibm.ws.jpa.tests.container_hibernate_fat
com.ibm.ws.jpa.tests.container_modifyconfig_fat
com.ibm.ws.jpa.tests.eclipselink_jpa_3.1_fat
com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat
com.ibm.ws.jpa.tests.jpa_31_fat
com.ibm.ws.jpa.tests.jpa_fat
com.ibm.ws.jpa.tests.jpaconfig_jpa_3.1_fat
com.ibm.ws.jpa.tests.ormdiagnostics_3.0_fat
com.ibm.ws.jpa.tests.spec10.callback_jpa_3.1_fat
com.ibm.ws.jpa.tests.spec10.embeddable_fat
com.ibm.ws.jpa.tests.spec10.entity_jpa_3.1_fat
com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.1_fat
com.ibm.ws.jpa.tests.spec10.inheritance_jpa_3.1_fat
com.ibm.ws.jpa.tests.spec10.injection.defaultPersistenceUnit_fat
com.ibm.ws.jpa.tests.spec10.injection.dfi_fat
com.ibm.ws.jpa.tests.spec10.injection.dmi_fat
com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat
com.ibm.ws.jpa.tests.spec10.injection.jarfile_fat
com.ibm.ws.jpa.tests.spec10.injection.jndi_fat
com.ibm.ws.jpa.tests.spec10.injection.mdb_fat
com.ibm.ws.jpa.tests.spec10.issues_fat
com.ibm.ws.jpa.tests.spec10.packaging_jpa_3.1_fat
com.ibm.ws.jpa.tests.spec10.query_jpa_3.1_fat
com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_jpa_3.1_fat
com.ibm.ws.jpa.tests.spec10.relationships.manyXone_jpa_3.1_fat
com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_jpa_3.1_fat
com.ibm.ws.jpa.tests.spec10.relationships.oneXone_jpa_3.1_fat
com.ibm.ws.jpa.tests.spec20.entitymanager_fat
com.ibm.ws.jpa.tests.spec20.lock_fat
com.ibm.ws.jpa.tests.spec20.ordercolumn_fat
com.ibm.ws.jpa.tests.spec20.querylockmode_fat
com.ibm.ws.jpa.tests.spec20_fat
com.ibm.ws.jpa.tests.spec21.cdi_fat
com.ibm.ws.jpa.tests.spec21.issues_fat
com.ibm.ws.jpa.tests.spec21.txsynchronization_fat

* 

### Test strategy

* What functionality is new or modified by this feature?
** JPA 3.1 has added a number of new Query operators involving Java 8 Time API and EXTRACT(), and UUID as an ID type with auto-generated values.
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
* * The JPA 3.1 FAT bucket includes a basic bootstrap test to ensure that the jpa-3.1 feature is consumable, correctly bootstraps JPA 3.1 (Eclipselink 4.0), and performs simple CRUD operations to ensure its fundamental operability.  The rest of the FAT bucket contains tests which validate all of the new function introduced by th JPA 3.1 spec, which includes using UUID as a supported identity field type, automatic id generation for UUID identity types (using both AUTO and UUID generator type), new JPQL involving temporal type comparisons and extractions, the criteria API equivalent of said JPQL, and validating EntityManager/EntityManagerFactory autoclosable.
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)
** There are no manual tests

## Confidence Level: 4

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by tkburroughs** [comment]
With the delivery of https://github.com/OpenLiberty/open-liberty/pull/22384, FAT is now complete.

**Comment by ayoho** [comment]
LGTM 👍
