### ISSUE TITLE
BETA BLOG - Java 19 Support

### ISSUE THREAD

**Issue by jgrassel** [OpenLiberty/open-liberty#22166]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty. For this post to be included in the beta issue please make sure that this is completed by the end of Friday following the GM (Wednesday). 

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name (eg WebSockets feature):
   
   Short feature name (eg websockets-1.0): 

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.

3. Provide a summary of the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.

   - What was the problem before and how does your update make their life better? (Why should they care?)
   
   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.
   
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?

Java 19 is coming soon, and with it the following features and changes:
* [405](https://openjdk.org/jeps/405): Record Patterns (Preview)
* [422: ](https://openjdk.org/jeps/422)Linux/RISC-V Port
* [424: ](https://openjdk.org/jeps/424)Foreign Functions & Memory API (Preview)
* [425: ](https://openjdk.org/jeps/425)Virtual Threads (Preview)
* [426: ](https://openjdk.org/jeps/426)Vector API (Fourth Incubator)
* [427: ](https://openjdk.org/jeps/427)Pattern Matching for switch (Third Preview)
* [428: ](https://openjdk.org/jeps/428)Structured Concurrency (Incubator)

By taking advantage of trying out the new changes in Java 19 now, you get more time to review your applications, microservices and runtime environments and be a step ahead when it becomes generally available.

To give this a try today, [download the early access release of Java 19](https://jdk.java.net/19/), download and install the [22.0.0.10-beta](https://openliberty.io/downloads/#runtime_betas) version of Open Liberty, edit your Liberty server's [server.env file](https://openliberty.io/docs/22.0.0.10/reference/config/server-configuration-overview.html#server-env) to point JAVA_HOME to your Java 19 installation and start testing!

For more information on Java 19, please visit the Java 19 [release notes page](https://jdk.java.net/19/release-notes), [API Javadoc page](https://download.java.net/java/early_access/jdk19/docs/api/) or [download page](https://jdk.java.net/19/).
For more information on Open Liberty, please visit our [documentation page](https://openliberty.io/docs).

*Note: As we work toward full Java 19 support ourselves, please excuse any of our functionality that might not be 100% ready yet.

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
    - Once you've approved the code review, close this issue. 
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by gjwatts** [comment]
@ReeceNana Can this issue be closed now?

**Comment by gjwatts** [comment]
@mbroz2 Michal, can this be closed now?
