### ISSUE TITLE
Missing NLS strings for allowAuthenticationFailOverToAuthMethod options

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#22189]
**Describe the bug**  
If you look at the documentation for allowAuthenticationFailOverToAuthMethod the option descriptions all have untranslated nls constants. This is because in the [metatype.xml](https://github.com/OpenLiberty/open-liberty/blob/f755d5b238aeb4024ea4c2244b1cf7fa1d9bd209/dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/metatype/metatype.xml#L105) for the attribute it defines NLS constants for the options on lines [107](https://github.com/OpenLiberty/open-liberty/blob/f755d5b238aeb4024ea4c2244b1cf7fa1d9bd209/dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/metatype/metatype.xml#L107), [108](https://github.com/OpenLiberty/open-liberty/blob/f755d5b238aeb4024ea4c2244b1cf7fa1d9bd209/dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/metatype/metatype.xml#L108), [109](https://github.com/OpenLiberty/open-liberty/blob/f755d5b238aeb4024ea4c2244b1cf7fa1d9bd209/dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/metatype/metatype.xml#L109) but they are not defined in the [NLS file](https://github.com/OpenLiberty/open-liberty/blob/f755d5b238aeb4024ea4c2244b1cf7fa1d9bd209/dev/com.ibm.ws.webcontainer.security.app/resources/OSGI-INF/l10n/metatype.properties) for the metatype.

**Steps to Reproduce**  
Go to https://openliberty.io/docs/latest/reference/config/webAppSecurity.html and look at the first row in the table

**Expected behavior**  
I expect descriptions of the options and not NLS keys

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.10
 - Affected feature(s) appSecurity
 - Java Version: N/A
 - server.xml configuration (WITHOUT sensitive information like passwords) N/A
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log` N/A

**Additional context**

**Comment by utle** [comment]
Fixed by https://github.com/OpenLiberty/open-liberty/pull/22228
