### ISSUE TITLE
CTS: sigtest: Faces 4.0 failures

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#22198]
**Bold** failures still need issues opened

[javatest.batch] Missing Superclasses or Superinterfaces
[javatest.batch] ---------------------------------------
[javatest.batch] 
[javatest.batch] jakarta.faces.component.html.HtmlDoctype:                   interface @ jakarta.faces.component.Doctype
[javatest.batch] 
[javatest.batch] Missing Classes
[javatest.batch] ---------------
[javatest.batch] 
[javatest.batch] jakarta.faces.component.behavior.FacesBehavior$Literal
[javatest.batch] jakarta.faces.convert.FacesConverter$Literal
[javatest.batch] jakarta.faces.event.WebsocketEvent$Closed$Literal
[javatest.batch] jakarta.faces.event.WebsocketEvent$Opened$Literal
[javatest.batch] jakarta.faces.flow.builder.FlowBuilderParameter$Literal
[javatest.batch] jakarta.faces.flow.builder.FlowDefinition$Literal
[javatest.batch] jakarta.faces.model.FacesDataModel$Literal
[javatest.batch] jakarta.faces.push.Push$Literal
[javatest.batch] jakarta.faces.validator.FacesValidator$Literal
[javatest.batch] 
[javatest.batch] Added Classes
[javatest.batch] -------------
[javatest.batch] 
[javatest.batch] jakarta.faces.view.facelets.FaceletsResourceResolver
[javatest.batch] 
[javatest.batch] Missing Nested Classes
[javatest.batch] ----------------------
[javatest.batch] 
[javatest.batch] jakarta.faces.component.behavior.FacesBehavior:             nested public final static jakarta.faces.component.behavior.FacesBehavior$Literal
[javatest.batch] jakarta.faces.convert.FacesConverter:   nested public final static jakarta.faces.convert.FacesConverter$Literal
[javatest.batch] jakarta.faces.event.WebsocketEvent$Closed:                  nested public final static jakarta.faces.event.WebsocketEvent$Closed$Literal
[javatest.batch] jakarta.faces.event.WebsocketEvent$Opened:                  nested public final static jakarta.faces.event.WebsocketEvent$Opened$Literal
[javatest.batch] jakarta.faces.flow.builder.FlowBuilderParameter:            nested public final static jakarta.faces.flow.builder.FlowBuilderParameter$Literal
[javatest.batch] jakarta.faces.flow.builder.FlowDefinition:                  nested public final static jakarta.faces.flow.builder.FlowDefinition$Literal
[javatest.batch] jakarta.faces.model.FacesDataModel:     nested public final static jakarta.faces.model.FacesDataModel$Literal
[javatest.batch] jakarta.faces.push.Push:                nested public final static jakarta.faces.push.Push$Literal
[javatest.batch] jakarta.faces.validator.FacesValidator: nested public final static jakarta.faces.validator.FacesValidator$Literal
[javatest.batch] 
**[javatest.batch] Missing Fields
[javatest.batch] --------------
[javatest.batch] 
[javatest.batch] jakarta.faces.component.html.HtmlBody:  field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlColumn:field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlCommandButton:             field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlCommandLink:               field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlCommandScript:             field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlDataTable:                 field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlDoctype:                   field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlForm:  field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlGraphicImage:              field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlHead:  field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlInputFile:                 field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlInputHidden:               field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlInputSecret:               field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlInputText:                 field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")**
[javatest.batch] jakarta.faces.component.html.HtmlInputText$PropertyKeys:    field public final static jakarta.faces.component.html.HtmlInputText$PropertyKeys jakarta.faces.component.html.HtmlInputText$PropertyKeys.type
**[javatest.batch] jakarta.faces.component.html.HtmlInputTextarea:             field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlMessage:                   field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlMessages:                  field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlOutcomeTargetButton:       field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlOutcomeTargetLink:         field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlOutputFormat:              field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlOutputLabel:               field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlOutputLink:                field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlOutputText:                field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlPanelGrid:                 field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlPanelGroup:                field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlSelectBooleanCheckbox:     field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlSelectManyCheckbox:        field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlSelectManyListbox:         field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlSelectManyMenu:            field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlSelectOneListbox:          field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlSelectOneMenu:             field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch] jakarta.faces.component.html.HtmlSelectOneRadio:            field protected java.util.Map<java.lang.String,jakarta.el.ValueExpression> jakarta.faces.component.UIComponent.bindings
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch]**
[javatest.batch] Added Fields
[javatest.batch] ------------
[javatest.batch] 
[javatest.batch] jakarta.faces.component.FacesComponent: field public final static java.lang.String jakarta.faces.component.FacesComponent.NAMESPACE = "http://xmlns.jcp.org/jsf/component"
[javatest.batch] jakarta.faces.component.UISelectItemGroups:                 field public final static java.lang.String jakarta.faces.component.UISelectItemGroups.COMPONENT_FAMILY = "jakarta.faces.SelectItemGroups"
[javatest.batch]
[javatest.batch] Missing Methods
[javatest.batch] ---------------
[javatest.batch] 
[javatest.batch] jakarta.faces.component.UIWebsocket:    method public java.util.Collection<java.lang.String> jakarta.faces.component.UIWebsocket.getEventNames()
[javatest.batch] jakarta.faces.component.html.HtmlInputText:                 method public java.lang.String jakarta.faces.component.html.HtmlInputText.getType()
[javatest.batch] jakarta.faces.component.html.HtmlInputText:                 method public void jakarta.faces.component.html.HtmlInputText.setType(java.lang.String)
[javatest.batch] jakarta.faces.context.ExternalContextWrapper:               method public java.util.Map jakarta.faces.context.ExternalContextWrapper.getInitParameterMap()
[javatest.batch] jakarta.faces.render.Renderer:          method public java.lang.Object jakarta.faces.render.Renderer.getConvertedValue(jakarta.faces.context.FacesContext,jakarta.faces.component.UIComponent,java.lang.Object)
[javatest.batch]
[javatest.batch] Added Methods
[javatest.batch] -------------
[javatest.batch] 
[javatest.batch] jakarta.faces.component.UIData:         method protected java.util.regex.Pattern jakarta.faces.component.UIData.getSubIdPattern(jakarta.faces.context.FacesContext,char)
[javatest.batch] jakarta.faces.component.UIWebsocket:    method public java.util.Collection jakarta.faces.component.UIWebsocket.getEventNames()
[javatest.batch] jakarta.faces.component.html.HtmlDataTable:                 method protected java.util.regex.Pattern jakarta.faces.component.UIData.getSubIdPattern(jakarta.faces.context.FacesContext,char)
[javatest.batch] jakarta.faces.context.ExternalContextWrapper:               method public java.util.Map<java.lang.String,java.lang.String> jakarta.faces.context.ExternalContextWrapper.getInitParameterMap()
[javatest.batch] jakarta.faces.render.Renderer:          method public java.lang.Object jakarta.faces.render.Renderer.getConvertedValue(jakarta.faces.context.FacesContext,{jakarta.faces.render.Renderer%0},java.lang.Object)
[javatest.batch]
[javatest.batch] Added Constructors
[javatest.batch] ------------------
[javatest.batch] 
[javatest.batch] jakarta.faces.application.StateManagerWrapper:              constructor public jakarta.faces.application.StateManagerWrapper.init()
[javatest.batch]  anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
[javatest.batch]
[javatest.batch] Missed Annotations
[javatest.batch] ------------------
[javatest.batch] 
[javatest.batch] jakarta.faces.component.html.HtmlInputFile$PropertyKeys.alt:anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
[javatest.batch] jakarta.faces.component.html.HtmlInputFile$PropertyKeys.autocomplete:           anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
[javatest.batch] jakarta.faces.component.html.HtmlInputFile$PropertyKeys.maxlength:              anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
[javatest.batch] jakarta.faces.component.html.HtmlInputFile$PropertyKeys.readonly:               anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
[javatest.batch] jakarta.faces.component.html.HtmlInputFile$PropertyKeys.size:                   anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
[javatest.batch] jakarta.faces.component.html.HtmlInputFile.getAlt:          anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
[javatest.batch] jakarta.faces.component.html.HtmlInputFile.getAutocomplete: anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
[javatest.batch] jakarta.faces.component.html.HtmlInputFile.getMaxlength:    anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
[javatest.batch] jakarta.faces.component.html.HtmlInputFile.getSize:         anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
[javatest.batch] jakarta.faces.component.html.HtmlInputFile.isReadonly:      anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
[javatest.batch] jakarta.faces.component.html.HtmlInputFile.setAlt:          anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
[javatest.batch] jakarta.faces.component.html.HtmlInputFile.setAutocomplete: anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
[javatest.batch] jakarta.faces.component.html.HtmlInputFile.setMaxlength:    anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
[javatest.batch] jakarta.faces.component.html.HtmlInputFile.setReadonly:     anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
[javatest.batch] jakarta.faces.component.html.HtmlInputFile.setSize:         anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
[javatest.batch] jakarta.faces.component.html.HtmlInputSecret$PropertyKeys.alt:                  anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
[javatest.batch] jakarta.faces.component.html.HtmlInputSecret.getAlt:        anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
[javatest.batch] jakarta.faces.component.html.HtmlInputSecret.setAlt:        anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")

**Comment by pnicolucci** [comment]
https://issues.apache.org/jira/browse/MYFACES-4443

> [javatest.batch] Added Classes
> [javatest.batch] -------------
> [javatest.batch]
> [javatest.batch] jakarta.faces.view.facelets.FaceletsResourceResolver
> [javatest.batch]

**COMPLETED** in MyFaces Open Source. I didn't pull this one into OpenLiberty as it involves the removal of a class from the API jar. We can get this fix when we create and pull in another release of MyFaces 4.0.0

**All set in Open Liberty as well since we have RC2 now**

**Comment by pnicolucci** [comment]
https://issues.apache.org/jira/browse/MYFACES-4444

> [javatest.batch] Missed Annotations
> [javatest.batch] ------------------
> [javatest.batch]
> [javatest.batch] jakarta.faces.component.html.HtmlInputFile$PropertyKeys.alt:anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
> [javatest.batch] jakarta.faces.component.html.HtmlInputFile$PropertyKeys.autocomplete: anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
> [javatest.batch] jakarta.faces.component.html.HtmlInputFile$PropertyKeys.maxlength: anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
> [javatest.batch] jakarta.faces.component.html.HtmlInputFile$PropertyKeys.readonly: anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
> [javatest.batch] jakarta.faces.component.html.HtmlInputFile$PropertyKeys.size: anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
> [javatest.batch] jakarta.faces.component.html.HtmlInputFile.getAlt: anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
> [javatest.batch] jakarta.faces.component.html.HtmlInputFile.getAutocomplete: anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
> [javatest.batch] jakarta.faces.component.html.HtmlInputFile.getMaxlength: anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
> [javatest.batch] jakarta.faces.component.html.HtmlInputFile.getSize: anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
> [javatest.batch] jakarta.faces.component.html.HtmlInputFile.isReadonly: anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
> [javatest.batch] jakarta.faces.component.html.HtmlInputFile.setAlt: anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
> [javatest.batch] jakarta.faces.component.html.HtmlInputFile.setAutocomplete: anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
> [javatest.batch] jakarta.faces.component.html.HtmlInputFile.setMaxlength: anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
> [javatest.batch] jakarta.faces.component.html.HtmlInputFile.setReadonly: anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
> [javatest.batch] jakarta.faces.component.html.HtmlInputFile.setSize: anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
> [javatest.batch] jakarta.faces.component.html.HtmlInputSecret$PropertyKeys.alt: anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
> [javatest.batch] jakarta.faces.component.html.HtmlInputSecret.getAlt: anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")
> [javatest.batch] jakarta.faces.component.html.HtmlInputSecret.setAlt: anno 0 java.lang.Deprecated(boolean forRemoval=true, java.lang.String since="4.0")

**Comment by pnicolucci** [comment]
https://issues.apache.org/jira/browse/MYFACES-4451
> [javatest.batch]
> [javatest.batch] Added Constructors
> [javatest.batch] ------------------
> [javatest.batch]
> [javatest.batch] jakarta.faces.application.StateManagerWrapper: constructor public jakarta.faces.application.StateManagerWrapper.init()
> [javatest.batch] anno 0 java.lang.Deprecated(boolean forRemoval=false, java.lang.String since="")
> [javatest.batch]

**Completed** in MyFaces Open Source. and Open Liberty

**Comment by pnicolucci** [comment]
https://issues.apache.org/jira/browse/MYFACES-4452

> [javatest.batch]
> [javatest.batch] Added Methods
> [javatest.batch] -------------
> [javatest.batch]
> [javatest.batch] jakarta.faces.component.UIData: method protected java.util.regex.Pattern jakarta.faces.component.UIData.getSubIdPattern(jakarta.faces.context.FacesContext,char)
> [javatest.batch] jakarta.faces.component.html.HtmlDataTable: method protected java.util.regex.Pattern jakarta.faces.component.UIData.getSubIdPattern(jakarta.faces.context.FacesContext,char)

**Completed** in MyFaces Open Source and Open Liberty

**Comment by pnicolucci** [comment]
https://issues.apache.org/jira/browse/MYFACES-4453

> [javatest.batch] Missing Classes
> [javatest.batch] ---------------
> [javatest.batch]
> [javatest.batch] jakarta.faces.component.behavior.FacesBehavior$Literal
> [javatest.batch] jakarta.faces.convert.FacesConverter$Literal
> [javatest.batch] jakarta.faces.event.WebsocketEvent$Closed$Literal
> [javatest.batch] jakarta.faces.event.WebsocketEvent$Opened$Literal
> [javatest.batch] jakarta.faces.flow.builder.FlowBuilderParameter$Literal
> [javatest.batch] jakarta.faces.flow.builder.FlowDefinition$Literal
> [javatest.batch] jakarta.faces.model.FacesDataModel$Literal
> [javatest.batch] jakarta.faces.push.Push$Literal
> [javatest.batch] jakarta.faces.validator.FacesValidator$Literal
> [javatest.batch]

This should also resolve these:

> [javatest.batch] Missing Nested Classes
> [javatest.batch] ----------------------
> [javatest.batch]
> [javatest.batch] jakarta.faces.component.behavior.FacesBehavior: nested public final static jakarta.faces.component.behavior.FacesBehavior$Literal
> [javatest.batch] jakarta.faces.convert.FacesConverter: nested public final static jakarta.faces.convert.FacesConverter$Literal
> [javatest.batch] jakarta.faces.event.WebsocketEvent$Closed: nested public final static jakarta.faces.event.WebsocketEvent$Closed$Literal
> [javatest.batch] jakarta.faces.event.WebsocketEvent$Opened: nested public final static jakarta.faces.event.WebsocketEvent$Opened$Literal
> [javatest.batch] jakarta.faces.flow.builder.FlowBuilderParameter: nested public final static jakarta.faces.flow.builder.FlowBuilderParameter$Literal
> [javatest.batch] jakarta.faces.flow.builder.FlowDefinition: nested public final static jakarta.faces.flow.builder.FlowDefinition$Literal
> [javatest.batch] jakarta.faces.model.FacesDataModel: nested public final static jakarta.faces.model.FacesDataModel$Literal
> [javatest.batch] jakarta.faces.push.Push: nested public final static jakarta.faces.push.Push$Literal
> [javatest.batch] jakarta.faces.validator.FacesValidator: nested public final static jakarta.faces.validator.FacesValidator$Literal
> [javatest.batch]

**Completed** in MyFaces, PR and Open Liberty (didn't delete files). Files removed in RC2, we're all set here!

**Comment by pnicolucci** [comment]
https://issues.apache.org/jira/browse/MYFACES-4454
> Added Methods
> [javatest.batch] jakarta.faces.context.ExternalContextWrapper: method public java.util.Map<java.lang.String,java.lang.String> jakarta.faces.context.ExternalContextWrapper.getInitParameterMap()
> [javatest.batch] jakarta.faces.render.Renderer: method public java.lang.Object jakarta.faces.render.Renderer.getConvertedValue(jakarta.faces.context.FacesContext,{jakarta.faces.render.Renderer%0},java.lang.Object)

Will also fix the below:

> Missing Methods
> [javatest.batch] jakarta.faces.context.ExternalContextWrapper: method public java.util.Map jakarta.faces.context.ExternalContextWrapper.getInitParameterMap()
> [javatest.batch] jakarta.faces.render.Renderer: method public java.lang.Object jakarta.faces.render.Renderer.getConvertedValue(jakarta.faces.context.FacesContext,jakarta.faces.component.UIComponent,java.lang.Object)
> [javatest.batch]

**Completed** in MyFaces and Open Liberty

**Comment by pnicolucci** [comment]
https://issues.apache.org/jira/browse/MYFACES-4455

> [javatest.batch] Missing Superclasses or Superinterfaces
> [javatest.batch] ---------------------------------------
> [javatest.batch]
> [javatest.batch] jakarta.faces.component.html.HtmlDoctype: interface @ jakarta.faces.component.Doctype
> [javatest.batch]

**Completed in MyFaces and Open Liberty**

**Comment by pnicolucci** [comment]
https://issues.apache.org/jira/browse/MYFACES-4456 -> Completed in MyFaces Open Source
Pulling MYFACES-4456 into Open Liberty using issue: https://github.com/OpenLiberty/open-liberty/issues/22653

This is for missing function in MyFaces: https://github.com/openliberty/open-liberty/issues/20839

> [javatest.batch] Missing Methods
> [javatest.batch] ---------------
> [javatest.batch]
> [javatest.batch] jakarta.faces.component.html.HtmlInputText: method public java.lang.String jakarta.faces.component.html.HtmlInputText.getType()
> [javatest.batch] jakarta.faces.component.html.HtmlInputText: method public void jakarta.faces.component.html.HtmlInputText.setType(java.lang.String)
> 
> [javatest.batch] Missing Fields
> [javatest.batch] --------------
> [javatest.batch] jakarta.faces.component.html.HtmlInputText$PropertyKeys: field public final static jakarta.faces.component.html.HtmlInputText$PropertyKeys jakarta.faces.component.html.HtmlInputText$PropertyKeys.type

**Completed** in Open Liberty and MyFaces

**Comment by pnicolucci** [comment]
https://issues.apache.org/jira/browse/MYFACES-4457

Looks as though this is caused by: https://github.com/apache/myfaces/commit/3ab81996f0b2358d7cbb375aaf012396eaf7da9c

We had previously addressed this here:  https://issues.apache.org/jira/browse/MYFACES-4232 , then it was changed slightly here: https://github.com/apache/myfaces/commit/15fba5976117cbf5f686d97775d585687e78d875#diff-861505f2179ead924c6d11c51cbf707ef7d2f9e650141def73d1f07004d942bb

To remove the template we would need to update qdox to a new major version which isn't a quick task: https://issues.apache.org/jira/browse/MYFACES-4233

I think we should revert back to the template if possible
> [javatest.batch] Missing Methods
> [javatest.batch] ---------------
> [javatest.batch]
> [javatest.batch] jakarta.faces.component.UIWebsocket: method public java.util.Collection<java.lang.String> jakarta.faces.component.UIWebsocket.getEventNames()
> 
> [javatest.batch] Added Methods
> [javatest.batch] -------------
> [javatest.batch]
> [javatest.batch] jakarta.faces.component.UIWebsocket: method public java.util.Collection jakarta.faces.component.UIWebsocket.getEventNames()

**Completed** in MyFaces and Open Liberty

**Comment by pnicolucci** [comment]
https://issues.apache.org/jira/browse/MYFACES-4468 pulled into Open Liberty: https://github.com/OpenLiberty/open-liberty/issues/22790

> [javatest.batch] Added Fields
> [javatest.batch] ------------
> [javatest.batch]
> [javatest.batch] jakarta.faces.component.UISelectItemGroups: field public final static java.lang.String jakarta.faces.component.UISelectItemGroups.COMPONENT_FAMILY = "jakarta.faces.SelectItemGroups"
> [javatest.batch]

**Completed** in MyFaces, in progress in Open Liberty

**Comment by brideck** [comment]
In reviewing the latest signature test results, I noticed that it does not seem to like the changes that were made in the SelectItemGroup* space.

Here's what it reports now:
```
Missing Classes
---------------
jakarta.faces.component.UISelectItemGroup

Missing Fields
--------------
jakarta.faces.component.UISelectItemGroups:                 field public final static java.lang.String jakarta.faces.component.UISelectItems.COMPONENT_FAMILY = "jakarta.faces.SelectItems"

Added Fields
------------
jakarta.faces.component.UISelectItemGroups:                 field public final static java.lang.String jakarta.faces.component.UISelectItemGroups.COMPONENT_FAMILY = "jakarta.faces.SelectItemGroups"
```

**Comment by brideck** [comment]
You can ignore my last comment.  This has indeed all been fixed by 22790 making it into release.

**Comment by pnicolucci** [comment]
> [javatest.batch] Added Fields
> [javatest.batch] ------------
> [javatest.batch] 
> [javatest.batch] jakarta.faces.component.FacesComponent: field public final static java.lang.String jakarta.faces.component.FacesComponent.NAMESPACE = "http://xmlns.jcp.org/jsf/component"

https://issues.apache.org/jira/browse/MYFACES-4493
https://github.com/OpenLiberty/open-liberty/issues/23228

**Comment by pnicolucci** [comment]
The remaining `bindings` issues will be resolved with: https://issues.apache.org/jira/browse/MYFACES-4502 see the tck challenge: `https://github.com/jakartaee/faces/issues/1714`

Open Liberty issue: https://github.com/OpenLiberty/open-liberty/issues/23367

**Comment by pnicolucci** [comment]
Signature tests are now passing 100%. Closing this out as there is no remaining work.
