### ISSUE TITLE
Repeat existing tests against the microProfile-6.0 feature

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#22201]
These test buckets need to be repeated against the new microProfile-6.0 feature

https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.microprofile.internal_fat
https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.microprofile41.internal_fat
https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.microprofile5.internal_fat

**Comment by Azquelt** [comment]
@tevans78 This wasn't tagged or on the board and I'm not sure what the status of it is. Was this done in #22226 (which isn't linked to any issue) or is this follow on work from that PR?

**Comment by tevans78** [comment]
`io.openliberty.microprofile.internal_fat` already has an appropriate repeat that includes MP6.
`io.openliberty.microprofile41.internal_fat` needs to have its repeat updated to add MP6.
`io.openliberty.microprofile5.internal_fat` does not need a repeat as it is only a compatibility test (which is replicated by `io.openliberty.microprofile6.internal_fat`).
