### ISSUE TITLE
Faces 4.0: once we can start up a faces-4.0 application enable io.openliberty.org.apache.myfaces.4.0_fat tests again

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#22206]
1) Update server.xml to use the faces-4.0 feature
2) Update web.xml to version 6.0

**Comment by benjamin-confino** [comment]
com.ibm.ws.cdi.jee.jsp.SimpleJSPTest 
com.ibm.ws.cdi.jee.jsf.SimpleJSFWithSharedLibTest

will need re-enabling.
