### ISSUE TITLE
Faces 4.0: Update / test facesContainer-4.0 for Faces 4.0

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#22202]
Remaining work: https://github.com/OpenLiberty/open-liberty/pull/23139#issue-1424679973

**Comment by pnicolucci** [comment]
Things remaining to clean up: 

1) ~~ClassloadingTest switch order of isEE9 / isEE10 -> https://github.com/OpenLiberty/open-liberty/pull/24241~~
2) ~~debug SESN0066E/SRVE8114W in JSF22StatelessViewTests.java -> do we hit these in the standard bucket and does it require any additional investigation? -> https://github.com/OpenLiberty/open-liberty/pull/24242~~
3) ~~Switch order EE9/EE10 checks since EE10 executes in lite mode JSF23CDIGeneralTests.java -> https://github.com/OpenLiberty/open-liberty/pull/24241~~
4) ~~JSF23WebSocketTests in 2.3 bucket are commented out, we can likely check these now with RC2 and see if they work. -> https://github.com/OpenLiberty/open-liberty/pull/24249~~
5) ~~jsf.cotainer.2.3_fat.beanval / server.xml remove cdi add dynamically in test for 4.0 / cleanup if we enable cdi by default for faces-4.0. -> Done as part of https://github.com/OpenLiberty/open-liberty/pull/24264~~
6) 
    Mojarra Bugs Potentially?

   - ~~JSF22StatelessView_TestViewScopeManagedBeanTransient -> This one can be skipped for EE10 for Mojarra and MyFaces since it uses a ManagedBean and we already have a CDI bean test. https://github.com/OpenLiberty/open-liberty/pull/24272~~
   - ~~JSF22StatelessView_TestViewScopeCDIBeanTransient_Mojarra -> **The most we can do here is eventually open a bug against Mojarra.** -> opened an issue for us to look at this later: https://github.com/OpenLiberty/open-liberty/issues/24519~~


    Only one of concern:
    - ~~JSF22Flows_TestDeclarativeNavigation_MyFaces() -> https://github.com/OpenLiberty/open-liberty/pull/24264~~
7) ~~The facesContainer-4.0 future still enables the `pages-3.1` feature so we need to fix that! -> https://github.com/OpenLiberty/open-liberty/pull/24280~~

8) ~~Review for other disabled tests and look at getting them enabled: testCDIManagedProperty -> https://github.com/OpenLiberty/open-liberty/pull/24374~~

**Comment by volosied** [comment]
` SESN0066E/SRVE8114W ` occurred in Mojarra, I believe ( will need to verify)  I'm not sure what we can do in our FAT therefore, but we could open issue in the upstream community if we find out why.
