### ISSUE TITLE
Yoko marshals null fields incorrectly when the field is declared as a non-serializable class

### ISSUE THREAD

**Issue by joe-chacko** [OpenLiberty/open-liberty#22227]
When Yoko is marshalling a Java value object with a null field that is declared as a non-serializable class, it is marshalled incorrectly.

This does not cause any problems when two Liberty processes are communicating over IIOP, but it can cause problems when interoperating with other Java processes.

This is resolved in a recent fix to Yoko: https://github.com/OpenLiberty/yoko/issues/121

**Comment by mbroz2** [comment]
@joe-chacko please update the description of this `release bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)"
