### ISSUE TITLE
Feature Test Summary for Java 19 support in Open Liberty

### ISSUE THREAD

**Issue by gjwatts** [OpenLiberty/open-liberty#22229]
## Test Strategy

Please note, this Feature Test Summary provided is just used to claim [Java 19 Support in Open Liberty](https://github.com/OpenLiberty/open-liberty/issues/21142), which involves updating Open Liberty to correctly implement Java 19 interfaces and classes, but not to design new Open Liberty feature/function based on any new capabilities in Java 19.

Normally FATs designed to validate the functionality of a new or changed feature in Open Liberty.  For Java 19, the validation testing is covered in 3 different ways:

1.  The new [Java 19 FAT test](https://github.com/OpenLiberty/open-liberty/pull/22328) is just a simple check to make sure we are running on a Java 19 capable server.  To accomplish that, this FAT uses a WAR file for testing that has been compiled at the GA level of Java 19 using functionality that is specific to Java 19.
2.  Any FAT tests (listed later) added or changed to handle Java 19 specific changes.
3.  Our existing suite of Open Liberty and WebSphere Liberty FAT tests.  The vast majority of the testing validation for Java 19 is done this way.

### List of FAT projects affected

* `io.openliberty.java.internal_fat` - https://github.com/OpenLiberty/open-liberty/pull/22328
* `com.ibm.ws.concurrent.mp_fat/test-applications/MPConcurrentApp/src/concurrent/mp/fat/web/MPConcurrentTestServlet`
   - testNoNewMethods - Updated this test to tolerate the CompletableFuture interface having an additional 3 methods, which is the case on Java 19.
* `com.ibm.ws.threading_policy_fat/test-applications/basicfat/src/web/PolicyExecutorServlet`
   - testClose - Use ExecutorService.close to shut down the executor and await completion of running tasks, if on Java 19 or above. Otherwise, use shutdown and awaitCompletion.
   - testExceptionNow - Use Future.exceptionNow on futures for tasks that are: successfully completed, exceptionally completed, running, aborted due to exceeding start timeout, cancelled
   - testResultNow: Use Future.resultNow on futures for tasks that are: successfully completed, exceptionally completed, running, aborted due to exceeding start timeout, cancelled
* `com.ibm.ws.concurrent_fat_jakarta/test-applications/ConcurrencyTestWeb/src/test/jakarta/concurrency/web/ConcurrencyTestServlet`
   - testExceptionNow - Use Future.exceptionNow on managed completable futures that are successfully completed, exceptionally completed, running, forcibly completed, has its results replaced, cancelled
   - testResultNow - Use Future.resultNow on managed completable futures that are successfully completed, exceptionally completed, running, forcibly completed, has its results replaced, cancelled
* `com.ibm.ws.concurrent_fat/test-applications/concurrentSpec/src/fat/concurrent/spec/app/EEConcurrencyTestServlet`
   - testExceptionNowOnScheduledFuture - Test exceptionNow on a ScheduledFuture from a ManagedScheduledExecutorService.
   - testResultNowOnScheduledFuture - Test resultNow on a ScheduledFuture from a ManagedScheduledExecutorService.
* `com.ibm.ws.concurrent.mp_fat_jakarta/test-applications/MPContextProp2_0_App/src/concurrent/mp/fat/v20/web/MPContextProp2_0_TestServlet`
   - testClose - Use ExecutorService.close to shut down a MicroProfile ManagedExecutor and await completion of running tasks, if on Java 19 or above.  Otherwise, use shutdown and awaitCompletion.
* `com.ibm.ws.threading_fat/fat/src/com/ibm/ws/threading/fat/MemLeakTest`
   - testScheduleClose - Check for a message in the log file if running Java 19.
 
### Test strategy

* What functionality is new or modified by this feature?
  * Liberty now has implementations of several new Java 19 methods.
* What are the positive and negative tests for that functionality? 
  * This FAT adds one simple test to ensure we are running on Java 19 by using functionality that is specific to Java 19.
  * In this case, there is no correlation between what is being performed, to what is actually being tested, which is verification that we are running on Java 19.
* Testing specifics
  * For several weeks now, we have been running nightly (M-F) Java 19 builds using the latest [Java 19 OpenJDK Hotspot builds](https://jdk.java.net/19/) and tracking defects.  This build runs in lite mode against all the Open and WebSphere Liberty FATs.  We also periodically run a build against all the same FATs in full mode to make sure we discover any Java 19 specific defects.

## Confidence Level

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

Team voting for testing confidence level resulted in a 4.

**Comment by ayoho** [comment]
Looks fine to me 👍

**Comment by gjwatts** [comment]
Team voting for testing confidence level resulted in a 4.
