### ISSUE TITLE
Console source and message source logging server property values are not case insensitive

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/open-liberty#22251]
The `com.ibm.ws.logging.console.source` and `com.ibm.wslogging.message.source` server logging configuration property values are not case insensitive, as the other logging configuration property values. 

Configuring with upper case values does not work.
**bootstrap.properties file:**
com.ibm.ws.logging.console.source=MESSAGE,TRACE
com.ibm.wslogging.message.source=MESSAGE,trace

Only lower case values work.
**bootstrap.properties file:**
com.ibm.ws.logging.console.source=message,trace
com.ibm.wslogging.message.source=message,trace

**Comment by fmhwong** [comment]
@pgunapal Would you be able to look at this?
