### ISSUE TITLE
Design Issue: How to Handle Multiple APIs for a feature

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#22268]
Link to Epic: #18745

Description of Problem:

As part of EE10, some APIs were refactored into multiple jars. This includes the Websocket API which was split into client and server jars:
**Before (EE9):**
Both: `jakarta.websocket:jakarta.websocket-api:2.0.0`
**After (EE10):** 
Server: `jakarta.websocket:jakarta.websocket-api:2.1.0`
Client: `jakarta.websocket:jakarta.websocket-client-api:2.1.0`

CDI was similarly affected. 

How should the features files and the Liberty API bundles be handled? I see three potential options: 

- Should the two jars be built into one bundle?  If so, how should the maven coordinates be handled in the feature file? Which coordinate should be listed?  CDI takes this approach. See

https://github.com/OpenLiberty/open-liberty/blob/45adf915e8627187896ab9e5acc17bbb8e282dec/dev/io.openliberty.jakarta.cdi.4.0/bnd.bnd#L56-L59

https://github.com/OpenLiberty/open-liberty/blob/45adf915e8627187896ab9e5acc17bbb8e282dec/dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.cdi-4.0.feature#L7

- Or should each jar each be in their own bundle?  If so, can we list multiple maven coordinates in single feature file? This is the current approach for websockets. See 

https://github.com/OpenLiberty/open-liberty/blob/640508c05d5e7090e001ea0683e99c76828b4f14/dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.websocket-2.1.feature#L5-L7

- Otherwise, does each API need it's own private feature file?

**Comment by cbridgha** [comment]
Some additional investigation is needed to see how wide-spread this situation is (merging spec API jar's into a single bundle, or keeping the API bundles separate.  Separating the bundles works best with the existing "mavenCoordinates" property designated with each API jar, but this mechanism could be expanded to a comma separated list of spec jars that represent all of the packages included in the bundle.

The CDI example has set precedence merging the jar's into a single bundle - And breaking into multiple bundles would break existing customers using for compilation.

**Comment by cbridgha** [comment]
After a couple side discussions...  The way its setup with multiple jar's containing the api's is fine - no need for change here. - Possibly should enhance the "maven-coordinates" property - but that can be another issue.

**Comment by pnicolucci** [comment]
Closing this as there is nothing remaining for this issue and issue #22708 is opened.
