### ISSUE TITLE
Java 19 changes that can affect Liberty threading

### ISSUE THREAD

**Issue by gjwatts** [OpenLiberty/open-liberty#22270]
As a user of Open Liberty, Concurrency, and Java 19 I want to be able to use the new functionality that has been added to Futures and ExecutorServices when using the managed counterparts provided by Open Liberty.

Future: https://download.java.net/java/early_access/jdk19/docs/api/java.base/java/util/concurrent/Future.html
Completable Future: https://download.java.net/java/early_access/jdk19/docs/api/java.base/java/util/concurrent/CompletableFuture.html
ExecutorService: https://download.java.net/java/early_access/jdk19/docs/api/java.base/java/util/concurrent/ExecutorService.html

The upcoming change in Java 19 that the Kernel team needs to be aware of are additional methods added to:
`Future`
[resultNow](https://download.java.net/java/early_access/jdk19/docs/api/java.base/java/util/concurrent/Future.html#resultNow()), [exceptionNow](https://download.java.net/java/early_access/jdk19/docs/api/java.base/java/util/concurrent/Future.html#exceptionNow()), [state](https://download.java.net/java/early_access/jdk19/docs/api/java.base/java/util/concurrent/Future.html#state())

`ExecutorService`
[close](https://download.java.net/java/early_access/jdk19/docs/api/java.base/java/util/concurrent/ExecutorService.html#close())

The default implementations of the listed classes should be reviewed by the Kernel team to determine if they are acceptable or not and handle as necessary.

**Comment by brenthdaniel** [comment]
After reviewing the new methods, only minor additions to implement the new APIs were required. Changes were added in #22562 and tests were added to the threading FAT (which has yet to make it into open liberty.)
