### ISSUE TITLE
Get mpConfig-3.0 TCK running cleanly with EE10 (no compatibility options)

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#22283]
Currently the MP Config 3.0 TCK needs updates to work properly with CDI 4.0 - currently it's running with the CDI 3.0 compatibility option enabled.

We need the following changes integrated into a release of the TCK before we can pass it:
* eclipse/microprofile-config#743
* eclipse/microprofile-config#749

**Comment by tevans78** [comment]
Parking this issue since it requires a 3.0.3 version of MP Config

**Comment by tevans78** [comment]
Unlikely to be a 3.0.3 with these fixes so closing this issue.
