### ISSUE TITLE
fails to create Jose4jEllipticCurveJWK instance

### ISSUE THREAD

**Issue by arunavemulapalli** [OpenLiberty/open-liberty#22298]
OpenID Connect Client fails to validate JWT due to this error :
CWWKS1737E: The OpenID Connect client [clientid123] failed to validate the JSON Web Token. The cause of the error was: [CWWKS1739E: A signing key required by signature algorithm [ES256] was not available. ] …

Jose4jEllipticCurveJWK class is not storing the correct object type for “x5c” parameter, JWK therefore does not get successfully parsed and runtime fails to find the key to verify the JWT signature

**Comment by arunavemulapalli** [comment]
Fix the programming error
Jose4jEllipticCurveJWK is being populated with the parameters in the JWK. However, the Jose4jEllipticCurveJWK class is storing the String representations of each parameter value in the Map instead of the actual objects themselves. The "x5c" parameter value is meant to be an array of Strings (per https://datatracker.ietf.org/doc/html/rfc7517#section-4.7).

**Comment by covener** [comment]
FYI, This is in 22.0.0.11 but was not linked to a PR at GM time.
