### ISSUE TITLE
CRIU log level is not configurable for server checkpoint

### ISSUE THREAD

**Issue by dazavala** [OpenLiberty/open-liberty#22297]
Within `CRIU` support, the method `org.eclipse.openj9.criu.CRIUSupport.setLogLevel(int)` is never called from `io.openliberty.checkpoint.internal.openj9.ExecuteCRIU_OpenJ9.dump(Runnable,Runnable,File,String,File,File,boolean)`. The server checkpoint command cannot set (configure) the `CRIU` log level in order to gather debug diagnostics necessary to service `CRIU` failures during checkpoint. 

The server script defines environment variable `CRIU_LOG_LEVEL`, which is used to configure the `CRIU` log level for the restore command, only. The commands log `CRIU` diagnostics to their namesake files -- `checkpoint.log` and `restore.log` -- in the `${server.output.dir}/logs/checkpoint directory`. 

We need the same capability for checkpoint. And we can use the `CRIU_LOG_LEVEL` environment variable just as we do for restore, provided the key `CRIU_LOG_LEVEL` is added to the default list of immutable keys in the server script:
```
# Default list of immutable env vars for checkpoint
X_WLP_IMMUTABLE_VARS="-Dorg.eclipse.openj9.criu.ImmutableEnvVars=INVOKED,WLP_USER_DIR,WLP_OUTPUT_DIR,LOG_DIR,X_LOG_DIR,LOG_FILE,X_LOG_FILE,VARIABLE_SOURCE_DIRS,X_CMD"
```
Otherwise the JVM will return null when method `ExecuteCRIU_OpenJ9.dump` attempts to read the env var during checkpoint.

**Comment by tjwatson** [comment]
#22316 adds the support for this, but leaving this open to add tests.
