### ISSUE TITLE
Faces 4.0: Enable com.ibm.ws.jsf.2.3_fat tests for EE10

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#22368]
Init delivery of tests that are currently passing: PR:[ 22385](https://github.com/OpenLiberty/open-liberty/pull/22385)

1) Enable the remaining tests

Commented out tests in EE10-enabled test classes:

1) ~~The below tests need to be updated as they are looking in the Session map for the Session beans (ManagedBeans) but when using `@Named` beans the Session beans are no longer in the Session map so we need to work on a solution:
a. JSF23CDIConfigByACPTests  (testNavigationHandlerInjection_CDIConfigByACP)
b. JSF23CDIFacesInMetaInfTests  (testNavigationHandlerInjection_CDIFacesInMetaInf)
c. JSF23CDIFacesInWebXMLTests  (testNavigationHandlerInjection_CDIFacesInWebXML)
Initial work for these was done: https://github.com/OpenLiberty/open-liberty/pull/22488
**Enabled using this PR**: #23775~~

2) ~~AJAX request not working:
JSF23SelectOneRadioGroupTests.java (testSelectOneRadioGroup_AjaxRequest) : https://github.com/OpenLiberty/open-liberty/pull/22501 Enabling in this PR: https://github.com/OpenLiberty/open-liberty/pull/24377. This one will need to stay commented out now that RC5 is integrated. I'll update the comment here: #24553 and we'll test it manually for now here: https://github.com/OpenLiberty/open-liberty/issues/24387~~

3) ~~JSF23CDIGeneralTests.java (testInjectableELImplicitObjects (enabled as part of https://github.com/OpenLiberty/open-liberty/pull/22642), testSpecIssue790Test1, testSpecIssue1404And1423_JSF23NewAPIMethods(enabled again here: https://github.com/OpenLiberty/open-liberty/pull/24152)) : https://github.com/OpenLiberty/open-liberty/pull/22505~~

4) ~~JSF23UIRepeatConditionTests  (testUIRepeatCondition): https://github.com/OpenLiberty/open-liberty/pull/22525 This is another case where ajax looks to be working manually but HtmlUnit doesn't like it for some reason. -> https://github.com/OpenLiberty/open-liberty/pull/24345~~

5) ~~JSF23GeneralTests (testRepeated_ListenerFor_ResourceDependency_SpecIssue1430) : https://github.com/OpenLiberty/open-liberty/pull/22525 -> enabled again in: https://github.com/OpenLiberty/open-liberty/pull/24154~~

6) ~~JSF23WebSocketTests has two tests both of which are not executing currently and @volosied  is taking a look. These were enabled in:  https://github.com/OpenLiberty/open-liberty/pull/22642#pullrequestreview-1120478551 and then we had to disable one of them again due to a build break: https://github.com/OpenLiberty/open-liberty/issues/22728 -> https://github.com/OpenLiberty/open-liberty/pull/24268~~

7) ~~JSF23FacesDataModelTests.java (testFacesDataModelUIRepeat, testFacesDataModelChildUIRepeat) were disabled here: https://github.com/OpenLiberty/open-liberty/issues/22631 , I have an issue opened to enable these again once we do more investigation:  https://github.com/OpenLiberty/open-liberty/issues/22630. Re-enabled https://github.com/OpenLiberty/open-liberty/pull/24160~~

8) ~~JSF23SelectOneRadioGroupTests.java (testSelectOneRadioGroup_uiRepeat) was disabled here: testSelectOneRadioGroup_uiRepeat, I have an issue opened to enable these again once we do more investigation: https://github.com/OpenLiberty/open-liberty/issues/22630 -> Enabled here: https://github.com/OpenLiberty/open-liberty/pull/24292~~

9) ~~JSF23UIRepeatConditionTests.java (testUIRepeatConditionErrorEndTooLarge) was disabled here: https://github.com/OpenLiberty/open-liberty/issues/22631 , I have an issue opened to enable these again once we do more investigation: https://github.com/OpenLiberty/open-liberty/issues/22630. Enabled ;https://github.com/OpenLiberty/open-liberty/pull/24305~~

10) ~~JSF23CDIInjectionTests.java (testActionListenerInjection_CDIInjectionTests, testNavigationHandlerInjection_CDIInjectionTests, testViewScopeInjections), was disabled here https://github.com/OpenLiberty/open-liberty/pull/22558/files
**testActionListenerInjection_CDIInjectionTests and testNavigationHandlerInjection_CDIInjectionTests were enabled in PR**: #23775
**testViewScopeInjections** was enabled here: https://github.com/OpenLiberty/open-liberty/pull/24106~~

11) ~~https://github.com/OpenLiberty/open-liberty/pull/23340 -> enabled again here: https://github.com/OpenLiberty/open-liberty/pull/24249~~

12) ~~testCDIManagedProperty was disabled as part of:  https://github.com/OpenLiberty/open-liberty/pull/23502 -> https://github.com/OpenLiberty/open-liberty/pull/24374~~

**Comment by volosied** [comment]
## testSelectOneRadioGroup_AjaxRequest 
- (I think Paul already looked at this one)
 - Looks like some HTMLUnit / Ajax Problem.  I'm not sure why the first ajax request went though.  It fails on the second one. 
  - Manual test show correct response
  
<img width="408" alt="image" src="https://user-images.githubusercontent.com/5934310/219106219-6b0dd015-6953-4612-96d9-5112ff46752c.png">

 - Tried waiting via JSFUtils.waitForPageResponse, but it did _not_ work. 
 
 
 ## testCDIManagedProperty
 - Fails to due to an exception while working through the JavaScript:
```
 Caused by: java.lang.NullPointerException
	at com.gargoylesoftware.htmlunit.html.HtmlScript$2.execute(HtmlScript.java:232)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:257)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:747)
....
	at net.sourceforge.htmlunit.corejs.javascript.MemberBox.invoke(MemberBox.java:153)
	... 90 more
== CALLING JAVASCRIPT ==
  function () {
      return B.apply(A, arguments || []);
  }
```
- We can test again with RC5 as it has the JavaScript refactoring  change. 
- Manual test shows it works as expected
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/5934310/219106745-eb244a85-4ae8-4599-b968-4534ae0a73ae.png">

**Comment by pnicolucci** [comment]
All tests are enabled for EE10 with the exception of any listed here:  https://github.com/OpenLiberty/open-liberty/issues/24387
