### ISSUE TITLE
Restore time regression observed when running pingperf in container environment

### ISSUE THREAD

**Issue by dettmoney** [OpenLiberty/open-liberty#22390]
Between builds cl220820220629-1100 and cl220820220630-1100, I'm seeing a regression in containers when running pingperf with checkpoint restore. The first request time goes up from about 275ms on 0629-1100 to 350ms on 0630-1100. I do not see this same regression running on bare metal with no containers.

**Comment by tjwatson** [comment]
Can this be closed?
