### ISSUE TITLE
BETA BLOG - Jakarta EE 10: Support Jakarta WebSocket 2.1

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#22416]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty. For this post to be included in the beta issue please make sure that this is completed by the end of Friday following the GM (Wednesday). 

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name (eg WebSockets feature):
   > Jakarta WebSocket 2.1
  
   Short feature name (eg websockets-1.0): 
   > websocket-2.1

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.
   > This feature is for Jakarta Enterprise Edition (EE) application developers.
    
3. Provide a summary of the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.
   > This websocket-2.1 feature, which allows communication for endpoints via the Websocket protocol, is an implementation of the Jakarta EE 10 Websocket 2.1 Specification. It includes new features and behavior clarifications from 2.0. 
   
   - What was the problem before and how does your update make their life better? (Why should they care?)

>There have been several enchantments to improve websocket development. Firstly, when setting up dependencies, developers should notice the API jars have been refactored into client and server jars; however, both APIs are available in the websocket-2.1 feature.

>Developers can now register endpoints outside of the deployment phase of the web application (as there was previously a restriction). HTTP connection upgrades to the websocket protocol can now occur via the API's [ServerContainer#upgradeHttpToWebSocket​](https://jakarta.ee/specifications/websocket/2.1/apidocs/server/jakarta/websocket/server/servercontainer#upgradeHttpToWebSocket(java.lang.Object,java.lang.Object,jakarta.websocket.server.ServerEndpointConfig,java.util.Map)) rather than IBM's specific [WsWsocServerContainer#doUpgrade](https://www.ibm.com/docs/api/v1/content/SSD28V_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.wsoc_1.0-javadoc/com/ibm/websphere/wsoc/WsWsocServerContainer.html#doUpgrade(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse,javax.websocket.server.ServerEndpointConfig,java.util.Map)) SPI.

>Another change regards jakarta.websocket.Session#getUserProperties(), as the returned map is now a copy per endpoint instance (per websocket session). Additionally, the server session's user properties are initially populated by ServerEndpointConfig.getUserProperties(), thus allowing endpoints to retrieve properties set in [ServerEndpointConfig.Configurator#modifyHandshake​](https://jakarta.ee/specifications/websocket/2.1/apidocs/server/jakarta/websocket/server/serverendpointconfig.configurator#modifyHandshake(jakarta.websocket.server.ServerEndpointConfig,jakarta.websocket.server.HandshakeRequest,jakarta.websocket.HandshakeResponse)). This is similar to the client session as the user properties are a shallow copy from [EndpointConfig.getUserProperties()](https://jakarta.ee/specifications/websocket/2.1/apidocs/server/jakarta/websocket/EndpointConfig.html#getUserProperties()). More can be read in the API doc [here](https://jakarta.ee/specifications/websocket/2.1/apidocs/server/jakarta/websocket/session#getUserProperties()).

>Lastly, there were many clarifications in the spec, such as requiring [Session.getRequestURI()](https://jakarta.ee/specifications/websocket/2.1/apidocs/server/jakarta/websocket/session#getRequestURI()) to return the whole URI, and these clarifications can be viewed on the [Jakarta WebSocket 2.1](https://jakarta.ee/specifications/websocket/2.1/) page.
   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.
   
```
      <featureManager>
           <feature>websocket-2.1</feature>
      </featureManager>
```

   
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?
      > More information such as the JavaDocs, specification documents, and other details can be found at https://jakarta.ee/specifications/websocket/2.1/
 
## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
    - Once you've approved the code review, close this issue. 
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by pnicolucci** [comment]
This is for: https://github.com/OpenLiberty/open-liberty/issues/18745

**Comment by volosied** [comment]
@pnicolucci  I purposely left out of client-side SSL configuration from this blog post as it's not yet merged.

**Comment by pnicolucci** [comment]
Blog is live: https://openliberty.io/blog/2022/10/27/22.0.0.12-beta.html closing.

**Comment by volosied** [comment]
I wish to point out a mistake I made in the description:

`Another change regards jakarta.websocket.Session#getUserProperties(), as the returned map is now a copy per endpoint instance (per websocket session).`

What the [spec](https://jakarta.ee/specifications/websocket/2.1/jakarta-websocket-spec-2.1.html#handshake-modification) actually says: 
The user properties exposed during the *modifyHandshake()* method must
be a per WebSocket connection (i.e. per *Session*) shallow copy of the
user properties provided by **EndpointConfig.getUserProperties()**. When
the *Session* object is created these user properties, including any
modifications made during *modifyHandshake()*, must be used as the initial
user properties for the *Session*.

Can the blog be corrected in way?  It should say:

`Another change regards how user properties are handled. The map returned by EndpointConfig.getUserProperties() is now a copy per endpoint instance (per websocket session). Any new values added only exist for that connection.  This means this map is no longer a singleton in order to pass values to the jakarta.websocket.Session.getUserProperties.` A link to the spec might also be valuable.
