### ISSUE TITLE
Update NLS header in jsp component messages files

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#22421]
Update NLS header in jsp component:

#COMPONENTPREFIX JSPG **CWWJS**
#COMPONENTNAMEFOR JSPG C**WWJS** jsp

The above is missing from the translated file and was added to the English file here:  https://github.com/OpenLiberty/open-liberty/pull/22130

Without these, you can not add a suffix such as "E" to the message ID. In addition, the messages are not published: https://www.ibm.com/docs/en/was-liberty/core?topic=messages-jspg

**Comment by volosied** [comment]
Original error: 
```
 > Task :com.ibm.ws.jsp:globalize FAILED
[ant:validate]   (fatal) jsp.isthreadsafe.warning uses an unregistered component prefix (CWWJS)
```

**Comment by volosied** [comment]
The documentation is updated for the new prefix: https://www.ibm.com/docs/en/was-liberty/core?topic=messages-cwwjs 

And I seeCWWJS in the translated files: https://github.com/OpenLiberty/open-liberty/search?q=CWWJS 

Closing
