### ISSUE TITLE
Future support for Java 2 Security in Open Liberty

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#22437]
The Java Security Manager was [deprecated in Java 17][jep-411] for removal in a future version.

For this reason, Open Telemetry [are not willing to maintain support for the security manager][ot-issue] (which would mostly require adding `doPriviliged()` calls where the library is performing a secured action and may be called from application code).

What should our plan be for OpenLiberty's support of the Java Security Manager going forwards?

Other considerations:
 - Jakarta EE10 still has [Security Manager requirements][ee10-reqs] but notes that the Security Manager is deprecated and that [EE10 will be the last release with these requirements][ee10-deprecation]. We therefore shouldn't hit this issue with any libraries implementing an EE10 spec, but may do for EE11.

[jep-411]: https://openjdk.org/jeps/411
[ee10-deprecation]: https://jakarta.ee/specifications/platform/10/jakarta-platform-spec-10.0.html#securitymanager-deprecation
[ee10-reqs]: https://jakarta.ee/specifications/platform/10/jakarta-platform-spec-10.0.html#jakarta-ee-security-manager-related-requirements
[ot-issue]: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/6416

**Comment by Emily-Jiang** [comment]
I suggest to drop Java 2 security support as it has been deprecated in Java 17.

**Comment by Azquelt** [comment]
I can see the following options:
1. Drop support for the Java Security Manager altogether
2. Drop support for the Java Security Manager for new features
3. Maintain support for the Java Security Manager
    - Fork or avoid any open source libraries which do not support it

I think the second option strikes a balance of not immediately dropping support without locking ourselves into attempting to support it going forward as the community abandons it.

**Comment by Azquelt** [comment]
This was already discussed in #20289 - we have decided to continue supporting the security manager up to Java 17. This means that all features which run on Java 17 or earlier must support security manager.

We may revisit this if we meet wider resistance, but as a first action we need to engage better with open source communities and be prepared to do the work to support it. At the moment, the only case we have is the OpenTelemetry issue where, although they weren't enthusiastic, there was an invitation to discuss and present our case which we haven't done.
