### ISSUE TITLE
Nonship NoSQL feature for exploring Jakarta Data scenarios

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#22443]
User story:
"As developers/architects involved, we need a non-ship Jakarta NoSQL feature so that we can mock up scenarios with Jakarta NoSQL entities and explore how Jakarta Data can be designed to require either JPA or Jakarta NoSQL or tolerate both together."

**Comment by mswatosh** [comment]
Closing since we decided to go with the library path for Jakarta Data NoSQL providers
