### ISSUE TITLE
Does OL distribute restConnector.jar (client) via public maven repo

### ISSUE THREAD

**Issue by k1w1m8** [OpenLiberty/open-liberty#22466]
I wanted to write an OL restConnector client in Java, the instructions said take the restConnector.jar from the OL install folder.

Downloading and installing the entire OL zip to get a single jar seems ... heavyweight.

Is there an easy way to get this artifact via maven public repo?

**Comment by cbridgha** [comment]
Thanks for this question, and we agree its a bit much to download and unzip OL to get this jar.    Assigning this for investigation adding this artifact to our maven repo releases....

**Comment by hlhoots** [comment]
OL does not distribute the restConnector.jar individually.
