### ISSUE TITLE
Perform batch DB reads within global tran to lower number of JDBC connections needed per batch job

### ISSUE THREAD

**Issue by dmbelina** [OpenLiberty/open-liberty#225]
The database read operations performed by the batch container should be performed within the existing global transaction, reducing the number of connections needed per running java batch job.

**Comment by scottkurz** [comment]
Pasted code comment to give more detail on the issue, and the proposed resolution.

>  * Note that we use global transactions for database access, even reads which don't really need to be coordinated with anything else
>  * in any "atomic" manner. The reason for this is that we have execution flows in which multiple
>  * database reads/writes are performed in a sequence on a single thread, so a mix of global trans
>  * for the insert/updates and non-global trans for the reads would not allow these accesses to all
>  * be handled with a single database connection (per WebSphere connection pooling). This substantially
>  * complicates the question of "how many connections do I need?" and the related pooling settings needed
>  * to avoid deadlock, etc. Since a 2pc transaction involving only a single resource is optimized in WebSphere,
>  * there should be only a minimal performance hit to using a global tran in a single resource case such as
>  * one in which we just want to read from a single DB.
