### ISSUE TITLE
Create io.openliberty.jakarta.restfulWS.3.1.api_fat to test EE10 Jakarta Rest APIs

### ISSUE THREAD

**Issue by WhiteCat22** [OpenLiberty/open-liberty#22566]
We currently have `io.openliberty.jakarta.restfulWS.3.0.api_fat` to test the EE9 APIs, but rather than repeat those like our other FATs, we need to create a new set of tests to test the EE10 APIs.

We'll need to ensure that the minimum Java level for the EE10 tests is `Java 11`.

**Comment by jim-krueger** [comment]
Fixed under #22568
