### ISSUE TITLE
Tests don't fail immediately if the app doesn't start

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#2257]
We have some tests that deploy an app and then call `waitFotStringInLogUsingMark` to look for the app started message.

However, if the app started message does not appear, this method just returns `null` and our tests aren't checking the result so the test just continues.

**Comment by tevans78** [comment]
@peterbroadbent has kindly volunteered to take a look at this issue

**Comment by tevans78** [comment]
We will do this when the need arises (a build break test failure).
