### ISSUE TITLE
Disable GlobalHandlers by default in restfulWS-3.1 and xmlWS-4.0

### ISSUE THREAD

**Issue by WhiteCat22** [OpenLiberty/open-liberty#22598]
We are disabling GlobalHandlers by default in `restfulWS-3.1` and `xmlWS-4.0`.

Users can still enable GlobalHandler identical to previous feature versions by add the `com.ibm.websphere.appserver.globalhandler-1.0` feature to their user features. Users will also want to make sure their user features can tolerate multiple versions restfulWS and xmlWS if they plan to deploy the same app across multiple runtimes with different feature levels.

**Comment by jim-krueger** [comment]
Work completed under PR #24040
