### ISSUE TITLE
Gauge with tags gives Cannot reuse metric with MetricID

### ISSUE THREAD

**Issue by jwalcorn** [OpenLiberty/open-liberty#22592]
**Describe the bug**  
I'm using annotations to define a multi-valued gauge (that is, one we various tag values).  I keep a counter of how many accounts in my microservice belong to each of 6 "loyalty levels": Basic, Bronze, Silver, Gold, Platinum, and Unknown, and wanted to define a method that returns the corresponding counter for each tag value for this gauge.  Note I am not directly coding to a Metric Registry - this is all just happening due to annotations on methods.  At runtime, I get the exception below.

If there is a stack trace, please include the FULL stack trace (without any `[internal classes]` lines in it). To find the full stack trace, you may need to check in `$WLP_OUTPUT_DIR/messages.log`

```
Exception: Cannot reuse metric with MetricID MetricID{name='com.ibm.hybrid.cloud.sample.stocktrader.account.AccountService.account_loyalty', tags=[level="bronze"]}with Metadata DefaultMetadata{name='com.ibm.hybrid.cloud.sample.stocktrader.account.AccountService.account_loyalty', type=gauge, unit='null', description=null, displayName='Bronze'}. There already exists a Metadata for this metric name with different values: DefaultMetadata{name='com.ibm.hybrid.cloud.sample.stocktrader.account.AccountService.account_loyalty', type=gauge, unit='null', description=null, displayName='Basic'}
        at io.astefanutti.metrics.cdi30.MetricResolver.checkReusable(MetricResolver.java:388)
        at [internal classes]
        at com.ibm.hybrid.cloud.sample.stocktrader.account.AccountService$Proxy$_$$_WeldClientProxy.getAccounts(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.ibm.ws.jaxrs20.cdi.component.JaxRsFactoryImplicitBeanCDICustomizer.serviceInvoke(JaxRsFactoryImplicitBeanCDICustomizer.java:350)
```

**Steps to Reproduce**  
Just invoking my JAX-RS microservice results in the exception above

**Expected behavior**  
I'd hoped to have a working gauge with 6 tagged values, like so I could make a pie chart showing how many accounts are in each category.

**Diagnostic information:**  
 - OpenLiberty Version: [e.g. 21.0.0.8 - 21.0.0.10]  21.0.0.9
 - Affected feature(s) [e.g. mpHealth-3.0] mpMetrics-3.0
 - Java Version: [i.e. full output of `java -version`] Eclipse OpenJ9 VM, version 17.0.4.1+1
 - server.xml configuration (WITHOUT sensitive information like passwords) https://github.com/IBMStockTrader/account/blob/master/src/main/liberty/config/server.xml
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**  
The main microservice file is here: https://github.com/IBMStockTrader/account/blob/master/src/main/java/com/ibm/hybrid/cloud/sample/stocktrader/account/AccountService.java#L437-L465

I'm about to comment out these methods since they are causing problems, so line numbers may not match up shortly.  Anyway, here are the six methods and the annotations being used.  Am I doing something wrong here?  Are you just not allowed to have multi-valued (tagged) gauges via annotations in Liberty?  Happy to adjust code if there's a better way.  Thanks.

```
	@Gauge(name="account_loyalty", tags="level=basic", displayName="Basic", unit=MetricUnits.NONE)
	public int getBasic() {
		return basic;
	}

	@Gauge(name="account_loyalty", tags="level=bronze", displayName="Bronze", unit=MetricUnits.NONE)
	public int getBronze() {
		return bronze;
	}

	@Gauge(name="account_loyalty", tags="level=silver", displayName="Silver", unit=MetricUnits.NONE)
	public int getSilver() {
		return silver;
	}

	@Gauge(name="account_loyalty", tags="level=gold", displayName="Gold", unit=MetricUnits.NONE)
	public int getGold() {
		return gold;
	}

	@Gauge(name="account_loyalty", tags="level=platinum", displayName="Platinum", unit=MetricUnits.NONE)
	public int getPlatinum() {
		return platinum;
	}

	@Gauge(name="account_loyalty", tags="level=unknown", displayName="Unknown", unit=MetricUnits.NONE)
	public int getUnknown() {
		return unknown;
	}

```

**Comment by jwalcorn** [comment]
If needed, the Docker image for this microservice is available via `docker pull ibmstocktrader/account`

**Comment by donbourne** [comment]
Hi @jwalcorn , in MP Metrics, the metadata (units/displayname) has a 1-1 relationship with the metric name (in this case "account_loyalty"), so you're not allowed to register metrics with the same metric name but different metadata.  I think if you change your displayname to be something like "Loyalty" for all of the annotations, things should work.

**Comment by donbourne** [comment]
...basically you're failing the Metadata.equals check https://github.com/eclipse/microprofile-metrics/blob/ce5a2fdf3685c9058114930067f9370cf308b13d/api/src/main/java/org/eclipse/microprofile/metrics/DefaultMetadata.java#L139-L143

**Comment by jwalcorn** [comment]
Thanks Don, good to hear from you again.  I'll give that a try.

**Comment by jwalcorn** [comment]
Though I'm not sure if this will give me 6 different tags for the same multi-valued metric?  I wasn't wanting 6 separate, unrelated metrics.  For example, at this link I see multiple counter metrics being defined with the same name, with just different tag values, which is what I was wanting, but for gauges: https://blog.sebastian-daschner.com/entries/metrics-tags-microprofile

**Comment by jwalcorn** [comment]
Oh, you're saying use the same `displayName` (as well as the same `name`) for each tag.  Hmm.... a little counterintuitive, but I'll try that

**Comment by donbourne** [comment]
yes, exactly.  Think of Metadata as describing things related to the metric name, as you might think of Prometheus' HELP line.

**Comment by donbourne** [comment]
@jwalcorn , were you able to get it working (by using the same `displayName`)?

**Comment by donbourne** [comment]
@jwalcorn , I'm closing this one as I think the discussion above resolves it.  Feel free to reopen if there's any action required.
