### ISSUE TITLE
JakartaEE10 Erroneous Error message

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#22634]
I have a config that does not specify the providerURI, but, it **does** specify providerMetadata.  I'm getting 
`9/23/22, 9:20:04:469 CDT] 0000004b com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "io.openliberty.security.oidcclientcore.exceptions.OidcClientConfigurationException: CWWKS2401E: The configuration for the client_1 OpenID Connect client is not valid or is missing data. CWWKS2404E: The providerURI attribute for the client_1 OpenID Connect client is null or empty, and there is no metadata available for the OpenID Connect provider. io.openliberty.security.oidcclientcore.http.EndpointRequest 71" at ffdc_22.09.23_09.20.04.0.log
[9/23/22, 9:20:04:471 CDT] 0000004b io.openliberty.security.oidcclientcore.http.EndpointRequest  E CWWKS2401E: The configuration for the client_1 OpenID Connect client is not valid or is missing data. CWWKS2404E: The providerURI attribute for the client_1 OpenID Connect client is null or empty, and there is no metadata available for the OpenID Connect provider.
`
Getting an info or warning message about the missing providerURI would be ok, but, the message about the missing metadata is misleading - I have a providerMetadata.  Now, if this message is trying to tell me that I have providerMetadata, but it is missing information, it should say that.  It would help if it stated what was missing (even if it just showed the first thing that it found missing (and it could take several tries to get every value that we need))

`@OpenIdAuthenticationMechanismDefinition(
                                         clientId = "client_1",
                                         clientSecret = "mySharedKeyNowHasToBeLongerStrongerAndMoreSecureAndForHS512EvenLongerToBeStronger",
                                         claimsDefinition = @ClaimsDefinition(callerNameClaim = "sub"),
                                         redirectURI = "${providerBean.clientSecureRoot}/NoProviderURIInAnnotationWithProviderMetadata/Callback",
                                         providerMetadata = @OpenIdProviderMetadata(
                                                                                    authorizationEndpoint = "https://localhost:8920/oidc/endpoint/OP1/authorize",
                                                                                    tokenEndpoint = "https://localhost:8920/oidc/endpoint/OP1/token",
                                                                                    issuer = "https://localhost:8920/oidc/endpoint/OP1"))`

**Comment by c00crane** [comment]
I tried added all of the attributes that are defined as required and I still get that error message.

**Comment by jimmy1wu** [comment]
the original issue was fixed in: https://github.com/OpenLiberty/open-liberty/pull/22471/

i added some better additional messages when the issuer (required) and/or jwks uri (required) is not configured in the metadata and the provider uri is not set: https://github.com/OpenLiberty/open-liberty/pull/22990

**Comment by ayoho** [comment]
I'm going to be enhancing this in a new PR. My plan is to not emit an NLS message for failing to find the UserInfo claims since those claims aren't required. Instead I'll emit a debug message along the lines of
> The client_1 OpenID Connect client cannot create claims from the UserInfo data that was returned from the OpenID Connect provider. io.openliberty.security.oidcclientcore.exceptions.OidcClientConfigurationException: CWWKS2401E: The configuration for the client_1 OpenID Connect client is not valid or is missing data. CWWKS2404E: The OpenID Connect client cannot perform discovery because the providerURI attribute for the client_1 OpenID Connect client is null or empty.

**Comment by ayoho** [comment]
Should be resolved with the changes I delivered in https://github.com/OpenLiberty/open-liberty/pull/23117.

**Comment by ayoho** [comment]
@c00crane Let me know if the updates look good and we can close this out, or if we still need to improve something here.

**Comment by c00crane** [comment]
I'm getting an ffdc, but we are able to access the app with the info that is in the provider metadata - I agree that we should log a warning indicating that we can't get discovery data, but, should it be an ffdc?


`[1/27/23, 10:49:06:998 CST] 00000044 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "io.openliberty.security.oidcclientcore.exceptions.OidcClientConfigurationException: CWWKS2401E: The configuration for the client_1 OpenID Connect client is not valid or is missing data. CWWKS2404W: The OpenID Connect client cannot perform discovery because the providerURI attribute for the client_1 OpenID Connect client is null or empty. io.openliberty.security.jakartasec.identitystore.OidcIdentityStore 262" at ffdc_23.01.27_10.49.06.0.log`

**Comment by c00crane** [comment]
@ayoho - My Jan 27 is still what I see now - We should get a warning or some informational message in the log.  I don't think we need an ffdc though.
