### ISSUE TITLE
BETA BLOG - Messaging 3.1

### ISSUE THREAD

**Issue by AndrewDJBanks** [OpenLiberty/open-liberty#22632]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty. For this post to be included in the beta issue please make sure that this is completed by the end of Friday following the GM (Wednesday). 

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name: Jakarta Messaging 3.1
   
   Short feature name: Messaging 3.1

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.

3. Provide a summary of the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.

   - What was the problem before and how does your update make their life better? (Why should they care?)
   
   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.
   
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
    - Once you've approved the code review, close this issue. 
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by mbroz2** [comment]
@AndrewDJBanks @jhanders34 there's no information provided for this feature for the beta blog post.

I wrote up the following:

## Connection factory and destination definition annotations are now repeatable (Jakarta Messaging 3.1)
Jakarta Messaging is a set of APIs to standardize message communication between applications, defining how the messages are created, sent, received, and interpreted. Jakarta Messaging 3.1 provides minor changes and enhancements to the specification. Two noteworthy updates are the requirement for Java 11 and making the @JMSConnectionFactoryDefinition and @JMSDestinationDefinition annotations repeatable.

To enable the new Jakarta Messaging 4.0 feature, add the messaging-3.1 feature to your server.xml:

```
<featureManager>
   <feature>messaging-3.1</feature>
</featureManager>
```
For more information about Jakarta Messaging, refer to the following links:


- [Feature Documentation: Jakarta Messaging](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/docs/latest/reference/feature/messaging.html)

- [Specification: Jakarta Messaging](https://jakarta.ee/specifications/messaging/3.1/jakarta-messaging-spec-3.1.html)
