### ISSUE TITLE
HTTP Access logging need to log multiple X-Forwarded-For headers

### ISSUE THREAD

**Issue by loriadi** [OpenLiberty/open-liberty#22688]
**Describe the bug**  
When HTTP Access Logging is enabled to log specific headers, if that header is repeatable in a single HTTP request, such as X-Fowarded-For headers, only the first header with that name is logged.

**Steps to Reproduce**  
Send a single HTTP request to WebSphere Liberty which contains multiple same named valid headers and have Liberty configured to log that header in the HTTP Access Log. 

**Expected behavior**  
HTTP Access Logging should log a comma separated list of the multiple values of that header.
If HTTP Access Logging is configured no changes need to be made the current configuration.  The output that gets logged will now show a comma separated list of values rather than a single value for repeatable headers.

**Diagnostic information:**  
 - OpenLiberty Version: All
 - Affected feature(s): All if HTTP Access Logging is configured
 - Java Version: n/a
 - server.xml configuration
      The configuration may have something similar to the following, with My-Request-Header as the repeatable header name which may appear multiple times in the same HTTP request.
      
     <httpAccessLogging logFormat=' "%{My-Request-Header}i" '/>

**Additional context**  
n/a

**Comment by mbroz2** [comment]
@loriadi please update the description of this `release bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)"

**Comment by loriadi** [comment]
@mbroz2 Done
