### ISSUE TITLE
Problem in JSP Messages file

### ISSUE THREAD

**Issue by pnickoll** [OpenLiberty/open-liberty#22682]
A recently changed message does not fit the correct naming conventions:

#1, For file, com.ibm.ws.jsp/com/ibm/ws/jsp/resources/messages.nlsprops, Message ID must be 'aaaaannnns: ' (a=letter,n=number,s=A,E,I,W).  Found: 'CWWJS0001: T'.  Line: 1262
jsp.feature.not.loaded.correctly=CWWJS0001: The JSP [Pages] feature did not load with an acceptable version.

@volosied  It looks like under https://github.com/OpenLiberty/open-liberty/commit/4e6ee24025ca07b7e67b1d6a350e28feabc64a82 you removed this E from the message id.

Pre Change: jsp.feature.not.loaded.correctly=CWWJS0001E:
Post change: jsp.feature.not.loaded.correctly=CWWJS0001:

Was this done on purpose or by mistake?

**Comment by volosied** [comment]
Fixed under https://github.com/OpenLiberty/open-liberty/commit/51c134c4ea2b14465e29a04c938b2796d4f386d0

Closing issue.
