### ISSUE TITLE
TransactionSummary trace is incomplete

### ISSUE THREAD

**Issue by jonhawkes** [OpenLiberty/open-liberty#22704]
The TransactionSummary trace group which is used to provide ultra minimal trace for transaction creation and setRollbackOnly is incomplete.

Set TransactionSummary=all trace and notice that only a subset of the required trace is emitted.

This trace group is used when identifying what started a transaction or what rolled back a transaction in very high throughput systems where regular trace would be too big.

**Comment by jonhawkes** [comment]
https://github.com/OpenLiberty/open-liberty/pull/22706

**Comment by marcosfernandezgomez** [comment]
Hello John, I am working with the customer that opened the case on IBM regarding to the TransactionSummary trace issue. ¿Have you been able to fix it?

**Comment by jonhawkes** [comment]
The fix was merged at th end of Sep and I think it went into 22.0.0.11. I probably should have closed this issue to get it tagged properly. I'll do that now.

**Comment by jonhawkes** [comment]
The fix was merged at the end of Sep and I think it went into 22.0.0.11. I probably should have closed this issue to get it tagged properly. I'll do that now.
