### ISSUE TITLE
SSLContext defined in ClientBuilder.newBuilder().sslContext(sslcontext) not preserved with restfulWS-3.0

### ISSUE THREAD

**Issue by manudebouc** [OpenLiberty/open-liberty#22738]
**Describe the bug**  
We moved to restfulWS-3.0 feature and from what I understand there is a replacement of CXF with RESTEASY. We use to set our own sslContext using ClientBuilder.newBuilder().sslContext(sslcontext).hostnameVerifier(...);.  This was working well with CXF but is seems that moving to RESTEASY our sslContext is ignored and replaced by the default ssl config defined in server.xml (replacement done during build() method invocation.

No stack trace associated just an unexpected behavior.

**Steps to Reproduce**  
```
        SSLContext sslcontext = SSLContext.getInstance("TLSv1.2");
        sslcontext.init(null, new TrustManager[] { new X509TrustManager() {
          @Override
          public void checkClientTrusted(X509Certificate[] arg0, String arg1)
              throws CertificateException {
          }
          @Override
          public void checkServerTrusted(X509Certificate[] arg0, String arg1)
              throws CertificateException {
          }
          @Override
          public X509Certificate[] getAcceptedIssuers() {
            return new X509Certificate[0];
          }

        } }, null);
        ClientBuilder builder = ClientBuilder.newBuilder();
        builder.sslContext(sslcontext).hostnameVerifier((s1, s2) -> true);
        // sslcontext defined in builded is correct
        Client client = builder.build();
        // after build sslcontext defined in builded is reset to default present in server.xml
```

**Expected behavior**  
 We would like sslcontext specified in builder to be used so that our trustmanager is invoked instead of server.xml default one.

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.9/wlp-1.0.68.cl220920220815-1900
 - Affected feature(s) restfulWS-3.0
 - Java Version: Eclipse OpenJ9 VM, version 11.0.15-ea+10

**Additional context**  
Wondering if pb is there [https://github.com/OpenLiberty/open-liberty/blob/a2783947b1bf9afb184cb930a8bc60fc3[…]/restfulWS/internal/ssl/component/SslClientBuilderListener.java](https://github.com/OpenLiberty/open-liberty/blob/a2783947b1bf9afb184cb930a8bc60fc3c444f43/dev/io.openliberty.restfulWS.internal.ssl/src/io/openliberty/restfulWS/internal/ssl/component/SslClientBuilderListener.java#L62)
if no sslRef is defined or not found then jsseHelper.getSSLContext(sslRef, null, null) will return default ssl context and will override ssl buidler context. One option could be to use jsseHelper.getSSLContext method with tryDefault boolean that allows to control this default behavior

**Comment by WhiteCat22** [comment]
Thank you for opening this issue and suggesting a fix @manudebouc
