### ISSUE TITLE
Reporting FFDCs for JSP Translation Errors

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#22743]
This was brought up via Issue #22363.  In short, a customer found out that FFDCs were not consistent during JSP handling, and their error detection relied on FFDCs files.  This FFDC did exist in Liberty as removed (Work Item 50445) where this FFDC was reported heavily during JSP compilation ( `[com.ibm.ws](http://com.ibm.ws/).jsp.JspCoreException: JSPG0047E: Unable to locate tag library for uri http://java.sun.com/jsf/core` ) 

I said `not consistent` because if the JSP compiles fine the first time, but an edit is made to it which introduces an error, then the FFDC will be processed (different stack is followed as the JSP translated servlet is cached). 

PR for the proposed change: https://github.com/OpenLiberty/open-liberty/pull/22463

I added this FFDC in and verified that 

1) Only a few tests fail in our builds unlike before and that's because they aren't expecting this FFDC.
2) The same exception/error isn't reporting multiple FFDCs. Only in some scenario did I need to swap out this FFDC for another (to avoid having the same error reported twice . [See here and the testEL30ReservedWords test](https://github.com/OpenLiberty/open-liberty/pull/22463/files#diff-b2ea449953c398eeaafba770b89fafd007a4be94a409e5d423eb4334efbfae32R32). ) 

Questions:
1)  Is the FFDC appropriate here rather than just logging?  
   - I would say yes. The JSP fails to translate/compile and therefore will not run.

2) Can we add this new FFDC in? 
  -  It should only during JSP compilations errors, so I don't expect it to affect production environments. Mostly development, I assume.

**Comment by pnicolucci** [comment]
https://github.com/OpenLiberty/open-liberty/issues/22363#issuecomment-1269020476
