### ISSUE TITLE
PKCE parameters not copied by oauthForm.js

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/open-liberty#22786]
**Describe the bug**  
The consent page, while calling /authorize endpoint, does not pass all parameters from original request. This causes the PKCE's code_challenge and code_challenge_method parameters to be missing, resulting in an error from the authorization endpoint,

"CWOAU0033E%3A+A+required+runtime+parameter+was+missing%3A+code_challenge"

**Steps to Reproduce**  
Enable proofKeyForCodeExchange and publicClient for the registered OpenID Connect Client at the Liberty's Provider. Attempt to access a protected resource, then the request to the /authorize endpoint will contain the PKCE's code_challenge and code_challenge_method parameters. The consent page should be displayed. User consents. Then, Liberty OP's /authorize endpoint will return a response with an "error" and "error_description" with the CWOAU0033E message.

**Expected behavior**  
The PKCE's parameters should be accepted.

**Diagnostic information:**  
 - OpenLiberty Version: [e.g. 21.0.0.8 - 21.0.0.10]
 - Affected feature(s) openidConnectServer-1.0
 - Java Version: [i.e. full output of `java -version`]
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**

**Comment by rinkishimo** [comment]
hi, there is one more prerequisition while reproducing the bug: client must not have preauthorized all scopes (`"preauthorized_scope": "openid profile email phone"`). it would skip the consent page.
