### ISSUE TITLE
Add function to save logs, dump server, and increase timeout to wlp.lib.extract_fat

### ISSUE THREAD

**Issue by hlhoots** [OpenLiberty/open-liberty#22849]
The wlp.lib.extract_fat does not save off the logs for the test cases as they are outside of the normal framework.  Need to add code to manually save off the logs for troubleshooting purposes.  Also add a longer timeout (a few seconds longer that quiesce) and the ability to dump the server.

**Comment by jakspok** [comment]
hello please /asign thanks
