### ISSUE TITLE
Datasource changes are not propagating to JPA during dynamic config update

### ISSUE THREAD

**Issue by dazey3** [OpenLiberty/open-liberty#22865]
Changing the `<datasource>` properties (databaseName, password, portNumber, serverName, ect) in server.xml are not reflected in JPA applications. 

During server start, JPA Container does a JNDI lookup for the DataSource and provides that DataSource to the JPA provider, EclipseLink. After the configuration update fires, EclipseLink continues using the same DataSource that JPA Container provided. The DataSourceService isn't closing the ConnectionFactory, so everything continues to work. For JPA, the application needs to be restarted in order for this to work, however the DataSourceService is not refreshing the application.

**Comment by mbroz2** [comment]
@dazey3 please update the description of this `release bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
