### ISSUE TITLE
GA BLOG - Open Liberty and Java 19

### ISSUE THREAD

**Issue by gjwatts** [OpenLiberty/open-liberty#22869]
<Note to editor, this will be released as a standalone blog and must be released at the same time as https://github.com/OpenLiberty/docs/issues/5694>

Java 19 Support

Java 19 has been released and with it the following features:

[405: ](https://openjdk.org/jeps/405)Record Patterns (Preview)
[422: ](https://openjdk.org/jeps/422)Linux/RISC-V Port
[424: ](https://openjdk.org/jeps/424)Foreign Functions & Memory API (Preview)
[425: ](https://openjdk.org/jeps/425)Virtual Threads (Preview)
[426: ](https://openjdk.org/jeps/426)Vector API (Fourth Incubator)
[427: ](https://openjdk.org/jeps/427)Pattern Matching for switch (Third Preview)
[428: ](https://openjdk.org/jeps/428)Structured Concurrency (Incubator)

Java 19 is supported starting with Open Liberty 22.0.0.10 and newer.  To give this a try, [download Java 19](https://adoptium.net/temurin/releases/?version=19) and install at least the [22.0.0.10](https://openliberty.io/start/#runtime_releases) version of Open Liberty, edit your Liberty server's [server.env file](https://openliberty.io/docs/22.0.0.10/reference/config/server-configuration-overview.html#server-env) to point JAVA_HOME to your Java 19 installation and start testing!

For more information on Java 19, please visit the [release notes page](https://jdk.java.net/19/release-notes), [API Javadoc page](https://docs.oracle.com/en/java/javase/19/docs/api/index.html) or [migration guide](https://docs.oracle.com/en/java/javase/19/migrate/toc.htm).
For more information on Open Liberty, please visit our [documentation page](https://openliberty.io/docs).

Reminder:  To try out preview features in Java in Open Liberty, make sure to compile with `--enable-preview` and also add that same parameter to your `jvm.options` file.

**Comment by gjwatts** [comment]
@ReeceNana Hi Reece, this blog is actually now going to be a standalone blog and NOT tied to the 22.0.0.11 GA.  So it can be published after:
1.  @mbroz2 approves it
2.  The changes in https://github.com/OpenLiberty/docs/issues/5694 are published

@dmuelle FYI.

**Comment by dmuelle** [comment]
Hi @ReeceNana @mbroz2 please add me as a reviewer on the PR to publish this blog so I can time the updates to the 22.0.0.10 Java SE Doc to publish at the same time. Thanks

**Comment by gjwatts** [comment]
@mbroz2 Can I close out this issue now?

**Comment by mbroz2** [comment]
This was included in the [22.0.0.11 release blog post](https://openliberty.io/blog/2022/10/25/22.0.0.11.html#java19)
