### ISSUE TITLE
BETA BLOG - Jakarta Batch 2.1

### ISSUE THREAD

**Issue by cgianfra** [OpenLiberty/open-liberty#22950]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty. For this post to be included in the beta issue please make sure that this is completed by the end of Friday following the GM (Wednesday). 

Please provide the following information the week before the GA/beta date (to allow for review and publishing):

1. Which Liberty feature(s) does your update relate to?
    
   Human-readable name (eg WebSockets feature): Jakarta Batch 2.1
   
   Short feature name (eg websockets-1.0): batch-2.1

2. Who is the target persona? Who do you expect to use the update? eg application developer, operations. Application Developer & Operations

3. Provide a summary of the update, including the following points:

    The batch-2.1 feature is the implementation of Jakarta Batch 2.1 for use with other Jakarta EE 10 features. It can be activated by including the `batch-2.1` feature directly, or including `batchManagement-1.0` along with another EE 10 feature. For example:
    `<featureManager>`
    `   <feature>batchManagement-1.0</feature>`
    `   <feature>servlet-6.0</feature>`
    `</featureManager>`

    The updates in Jakarta Batch 2.1 primarily focus on improved integration with CDI. Discovery of Batch artifacts is now standardized via CDI, whereas before it was not fully defined in the specification.

    Previously, the default JobOperator was only made available from a static factory method, `BatchRuntime.getJobOperator()`. With Jakarta Batch 2.1, the default JobOperator is provided as a CDI bean unless one is defined by the user application, if an injectable field is available as defined by: 
    `@Inject` 
    `JobOperator jobOperator;`

    Finally, the BatchProperty annotation allowed for injection of String-type values only, but has been expanded to most other primitive types. For example:
    `@Inject @BatchProperty(name="p1") String p1;`
    This property can have other types in Jakarta Batch 2.1, including `Boolean`, `Integer`, `Long`, `Float`, and `Double`. Example:
     `@Inject @BatchProperty(name="p1") Integer p1;`

   - A sentence or two that introduces the update to someone new to the general technology/concept.

   - What was the problem before and how does your update make their life better? (Why should they care?)
   
   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.
   
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
    - Once you've approved the code review, close this issue. 
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by cgianfra** [comment]
@scottkurz Please take a look at the text to see if there's anything I missed or could explain differently, thanks!

**Comment by scottkurz** [comment]
@cgianfra   - A couple quick comments:
1. For `@BatchProperty` why don't you show a newly allowable example, e.g. one with an Integer type?
2. You might as well show a quick snippet injecting JobOperator.. it could be nothing more than the field w/ annotation.
3. I wouldn't say CDI integration wasn't "well-defined" before but just not "fully defined in the specification"  (don't want it to sound too bad before).
4. I don't think we usually write "EE10" (no space) but rather "EE 10".

**Comment by cgianfra** [comment]
Thanks @scottkurz , I updated the text with your suggestions.

**Comment by scottkurz** [comment]
LGTM
