### ISSUE TITLE
Bad or missing callerNameClaim logs failure, but proceeds to callback

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#22955]
I have a test servlet that defines a @OpenIdAuthenticationMechanismDefinition annotation.
the OpenIdConfig class returns either an invalid value or an empty string for the callerNameClaim.  The runtime will log an error, but then proceed to the application's specified callback.
Once in the callback, the openIdContext is not set.
It should never get that far

```
@OpenIdAuthenticationMechanismDefinition(providerURI = "${providerBean.providerSecureRoot}/oidc/endpoint/OP1", clientId = "client_1",
                                         clientSecret = "mySharedKeyNowHasToBeLongerStrongerAndMoreSecureAndForHS512EvenLongerToBeStronger",
                                         claimsDefinition = @ClaimsDefinition(callerNameClaim = "${openIdConfig.callerNameClaim}",
                                                                              callerGroupsClaim = "${openIdConfig.callerGroupsClaim}"),
                                         redirectURI = "${baseURL}/Callback")
```

**Comment by c00crane** [comment]
running with integration as of 10/13 + fix for issue 22956 and I'm getting:
`WWKS1652A: Authentication failed with status AuthStatus.SEND_FAILURE for the web request /badCallerNameClaim/Callback. The user defined Java Authentication SPI for Containers (JASPIC) service null has determined that the authentication data is not valid.`
So, there is still an issue.  (Other fixes have not resolved this)

**Comment by utle** [comment]
Fixed by https://github.com/OpenLiberty/open-liberty/pull/20850
