### ISSUE TITLE
Generating ssl key for FilterServer, when running FilterConfigTest takes too long

### ISSUE THREAD

**Issue by mbuamuh** [OpenLiberty/open-liberty#22965]
It takes too long to generate the ssl key, and as a result when stopping the FilterServer of the FilterConfigTest, the key is still being created. Consequently the process to delete server folder, which contains the key is blocked, by the key creation process.

**Comment by mbroz2** [comment]
@mbuamuh please update the description of this `release bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)

**Comment by mbroz2** [comment]
I'm removing `release bug` as this seems to be a test bug.  If this is incorrect @mbuamuh, let me know.
