### ISSUE TITLE
com.ibm.ws.jpa.container.v21.cdi lacks a package-info.java file

### ISSUE THREAD

**Issue by benjamin-confino** [OpenLiberty/open-liberty#22963]
Without this file trace will not be logged if the trace statement relies on trace groups

**Comment by mbroz2** [comment]
@benjamin-confino please update the description of this `release bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
