### ISSUE TITLE
AutoStopRule will swallow exceptions caused by errors in the log

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#2300]
Some of our tests use `ServerRules.startAndStopAutomatically` which internally uses `AutoStopRule`

`AutoStopRule` looks like it will swallow any exception thrown by `server.stopServer()` which means that errors or warnings in the logs won't cause test failures.

**Comment by tevans78** [comment]
This is now completed. The rule was removed.
