### ISSUE TITLE
Failed to parse Created TimeStamp in UsernameTokenValidator

### ISSUE THREAD

**Issue by jonasrutishauser** [OpenLiberty/open-liberty#23031]
**Describe the bug**  
Same Bug as #12523. Reintroduced with the cxf update.

**Steps to Reproduce**  
See #12523

**Expected behavior**  
See #12523

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.10
 - Affected feature(s): wsSecurity-1.1

**Additional context**  
See #12523

**Comment by jhanders34** [comment]
#regression

**Comment by neuwerk** [comment]
@jonasrutishauser thank you so much for opening the issue. Apologizes for the inconvenience of having to essentially reopen an issue for something  we had already fixed, as it's a shame that their was not test in place to let us know we regressed the fix when we upgraded CXF versions. I'll start working on a fix and update you when its done.

**Comment by neuwerk** [comment]
@jonasrutishauser #23063 was merged this morning, so it will be included in our next release. Apologies again for the inconvenience!
