### ISSUE TITLE
Feature Test Summary: Jakarta EE 10: Support Jakarta Activation 2.1

### ISSUE THREAD

**Issue by neuwerk** [OpenLiberty/open-liberty#23094]
## Test Strategy

Activation 2.1 support is handled in the same way that Activation 2.0 was supported in Jakarta EE 9: as a private feature for use by other Jakarta EE 10 public features i.e xmlWS-4.0 and mail-2.1.  The following fat buckets should provide coverage for the activation-2.1 feature:

### List of FAT projects affected

- com.ibm.ws.jaxws.2.2.webcontainer_fat
- com.ibm.ws.jaxws.2.2.webcontainer_fat_extended
- com.ibm.ws.jaxws.clientcontainer_fat
- com.ibm.ws.jaxws.cdi_fat
- com.ibm.ws.jaxws.ejb_fat
- com.ibm.ws.jaxws.X.wsat_fat
- io.openliberty.xmlws.4.0.internal_fat
- io.openliberty.mail.2.0.internal_fat

## Confidence Level

5

**Comment by ayoho** [comment]
LGTM 👍
