### ISSUE TITLE
Test mpOpenAPI-1.0 feature tolerates other EE8 features and mpConfig-1.2.

### ISSUE THREAD

**Issue by navidsh** [OpenLiberty/open-liberty#2311]
Add automated tests to ensure `mpOpenAPI-1.0` tolerates `jaxrs-2.1`,  `mpConfig-1.2` and `servlet-4.0`.

**Comment by mrglavas** [comment]
We did manually test but good to add automated tests to prevent regressions.

**Comment by janamanoharan** [comment]
can i pick this one up? @navidsh @mrglavas

**Comment by mrglavas** [comment]
@janamanoharan Yes, you can. I've assigned it to you.

**Comment by mrglavas** [comment]
Tests were delivered so closing the work item.
