### ISSUE TITLE
Look to remove "setThrowExceptionOnScriptError" from JSF23CDIGeneralTests#testCDIManagedProperty

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#23135]
Once the JavaScript is updated in Faces 4.0.0-RC3, we should look to see if we can remove  `webClient.getOptions().setThrowExceptionOnScriptError(false);` that was added in #23078 to avoid the `message=[missing ; after for-loop condition]` error.

**Comment by volosied** [comment]
Due to JS changes in RC5, this test will fail anyway.  This should be move to post-GA or closed, as we'll need to switch to selenium instead.

**Comment by tssmith04** [comment]
webClient.getOptions().setThrowExceptionOnScriptError(false); has been removed and testCDIManagedProperty passes on all repeats. So I'm closing this issue.
