### ISSUE TITLE
MP Telemetry 1.0 Feature Test Summary

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#23143]
Feature test summary for #19172

## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

### List of FAT projects affected

* `io.openliberty.microprofile.telemetry.1.0.internal_fat`
* `io.openliberty.microprofile.telemetry.1.0.internal_fat_tck`
* `io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat`

### Test strategy

This is a brand new feature, so everything is new and there's quite a lot to test. I've broken it down into its main sections.

#### Presence and basic functionality of the OpenTelemetry API #23447

MP Telemetry requires that we integrate [OpenTelemetry for Java][otel-java] and make its APIs available to applications. We need to check that the following APIs are available and can be used.

All of these APIs are implemented by OpenTelemetry, so we don't need thorough testing of every method, but we do want to poke every part of it and check the golden paths.

* Tracing API ([Javadoc][trace-javadoc])
  * Manual instrumentation using `SpanBuilder`
    * Jaeger FAT `spanTest`
  * Getting the current span and adding attributes
  * Nested spans
    * TCK `RestClientSpanTest`
* Baggage API ([Javadoc][baggage-javadoc])
* Context API ([Javadoc][context-javadoc])
* Resource SDK ([Javadoc][resource-javadoc])

[trace-javadoc]: https://www.javadoc.io/doc/io.opentelemetry/opentelemetry-api/1.18.0/io/opentelemetry/api/trace/package-summary.html
[baggage-javadoc]: https://www.javadoc.io/doc/io.opentelemetry/opentelemetry-api/1.18.0/io/opentelemetry/api/baggage/package-summary.html
[context-javadoc]: https://www.javadoc.io/doc/io.opentelemetry/opentelemetry-context/1.18.0/index.html
[resource-javadoc]: https://www.javadoc.io/doc/io.opentelemetry/opentelemetry-sdk-common/1.18.0/index.html

#### REST integration #23448

MP Telemetry needs to integrate with `restfulWS` and `mpRestClient`. Whenever a request is made or received by one of these features, MP Telemetry should create a span. Trace ID information should be sent via the HTTP headers so that the traces from both the client and server can be joined up. Baggage information should also be sent via the HTTP headers so that contextual information from the first service can be included in trace messages in the second service.

  * For each of these locations
    * JAX-RS server
    * JAX-RS client
    * MP Rest Client
  * We test
      * Creation of spans
      * Propagation of spanIds
      * Propagation of baggage
      * synchronous and async execution
      * Correct application of [Semantic convention attributes][semconv]
        * TCK `RestClientSpanTest` checks HTTP_STATUS, _METHOD, _SCHEME, _TARGET, _URL

There are several different standards for propagating spanIds and baggage. We need to test:
  * W3C tracer
    * TCK `RestClientSpanTest`
  * W3C baggage
    * Consumption tested in TCK `BaggageTest`
  * B3
  * Jaeger

#### CDI integration

MP Telemetry integrates with CDI, making several OpenTelemetry API objects available as CDI beans and adding an interceptor for the `@WithSpan` annotation

  * Test that adding `@WithSpan` to a method on a CDI bean results in a span being created when that method is called and check
    * Check the parent of the span is set correctly
    * Check that we can make several recusive calls to `@WithSpan` annotated methods
    * Check that `@SpanAttribute` can be used to add method parameters to the trace
    * Covered by #23450
  * CDI beans for:
    * `OpenTelemetry` #23670
    * `Tracer`
       * Covered in TCK `RestClientSpanTest`
    * `Span`
       * Covered in TCK `RestClientSpanTest`
    * `Baggage`
       * Covered in TCK `BaggageTest`
    * Further tests included in #23451

#### Configuration #23452

We must implement all the config properties relating to tracing listed in [OTel SDK Autoconfigure][autoconf], with the following changes:

* Config properties are read from MP Config
* Tracing is disabled by default #23892

We test:
* each applicable config property is respected
* the capitalisation rules for environment variables in MP Config are respected (if we do anything other than call `Config.getValue()`) 
* tracing is disabled by default #23892
* metrics and logs are always disabled #23646

#### Extensions #23453

We must support the parts of [OTel SDK Autoconfigure SPI][autoconf-spi] which relate to tracing

#### Trace exporters

MP Telemetry exports traces to a variety of trace servers. We must test each of them.

  * OTLP
     * io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat `JaegerOltpTest`
  * Legacy Jaeger protocol
     * io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat `JaegerLegacyTest`
  * Zipkin protocol
     * io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat `ZipkinTest`
  * Logging #23481 

We should test:
* all of the features available on `SpanBuilder`, ensuring the values make it through to the trace server #23177
* error messages that occur when the connection to the trace server is misconfigured #23456

#### Migration from OpenTracing

The `opentracing` and `mpOpenTracing` features are being stabilized as `mpTelemetry` provides similar functionality. We need to ensure that users can successfully migrate from one to the other.

* Ensure all test cases for the `opentracing` and `mpOpenTracing` features are covered by tests for `mpTelemetry` #19752
* Test propagation of span context between a server using `mpOpenTracing` and another server using `mpTelemetry` #24139 

#### Other integration points

There are a couple of things we should test as a result of bringing the Java OpenTelemetry implementation (which is designed for Java SE) into the Open Liberty environment

* Multiple application support #23461
  * Creation of separate `Resource` for each application with appropriate [attributes][resource-attributes]
* Propagating OTel context to async tasks started using `ManagedExecutor` #23868

#### Use of the OTel Java agent alongside the mpTelemetry feature #23206

There is an OpenTelemetry Java instrumentation agent which can automatically inject instrumentation into popular open source frameworks. We need to make sure that this works with liberty

Test that:
  * [configuration](https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/) of the agent works
  * we don't get duplicate traces when using `mpTelemetry` at the same time as the agent
  * correct behaviour when multiple apps are deployed

[autoconf]: https://github.com/open-telemetry/opentelemetry-java/tree/v1.18.0/sdk-extensions/autoconfigure
[semconv]: https://github.com/open-telemetry/opentelemetry-specification/tree/v1.13.0/specification/trace/semantic_conventions
[resource-attributes]: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.13.0/specification/resource/semantic_conventions/README.md
[otel-collector]: https://opentelemetry.io/docs/collector/
[ot-shim]: https://github.com/open-telemetry/opentelemetry-java/tree/main/opentracing-shim
[otel-java]: https://github.com/open-telemetry/opentelemetry-java
[autoconf-spi]: https://www.javadoc.io/doc/io.opentelemetry/opentelemetry-sdk-extension-autoconfigure-spi/1.18.0/index.html
[otlp-properties]: https://github.com/open-telemetry/opentelemetry-java/tree/v1.19.0/sdk-extensions/autoconfigure#otlp-exporter-span-metric-and-log-exporters

### Deferred until after release

The following are scenarios we would like to test but don't fall under the most common scenarios or are sufficiently low risk that we can release without them.

#### OpenTelemetry Collector 

Test use of `mpTelemetry` with the [OpenTelemetry Collector][otel-collector]. #23457

In particular, we want users to be able to

* convert OTLP traces to other formats
* exclude spans by URL
* enable security between OpenLiberty and the collector

We're not testing the collector itself here, we just want to test that `mpTelemetry` works with it and that specific user tasks can be accomplished using the collector.

We think this is low risk because to this feature treats the collector just as it would any other target for OTLP traces. We already test sending OTLP traces to the Jaeger server.

#### OpenTracing shim

- Test use of the [OpenTracing shim for OpenTelemetry][ot-shim] #23458

The OpenTracing shim is a tool to be used during migration to allow the OpenTracing API to be used with OpenTelemetry. It's a fairly simple wrapper provided by the OpenTelemetry project and we have no special integration for it.

#### Configure security for the OTLP exporter

* Test enabling security between OpenLiberty and the OTLP trace server #23455

The OTLP trace exporter has [properties for enabling security][otlp-properties] between liberty and the trace server. All of this code is entirely within the trace exporter so enabling security should be a matter of setting up certificates on both liberty and the trace server and setting the appropriate properties.

#### Original instructions

* What functionality is new or modified by this feature?
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

**Comment by ayoho** [comment]
LGTM 👍
