### ISSUE TITLE
Investigate Entity casting in various Bridge classes

### ISSUE THREAD

**Issue by pubgagrimm** [OpenLiberty/open-liberty#2317]
Investigate whether we should be doing Group/User casting in the assorted Bridge classes under com.ibm.ws.security.wim.registry.util.

For example,

Group group = (Group) returnList.get(0);

**Comment by jvanhill** [comment]
Closing this issue after Gary modified the UserRegistry bridge classes to only cast when necessary and issue trace messages when a class cannot be cast when necessary.

This will keep us from changing behavior for customers who have not configured their objectclasses for the PersonAccount and Group entities in their configuration.
