### ISSUE TITLE
Create Open Telemetry demo app

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#23196]
We need a sample app to show how to use Open Telemetry.

We can use this as the basis for the EOI demo and write a blog post around it.

It should be a standard maven project and include instructions so that end users can run it easily.

**Comment by Azquelt** [comment]
As a note, if we want to demo use of the agent jar, we should be able to use the [dependency:copy][copy-goal] goal to fetch it

[copy-goal]:https://maven.apache.org/plugins-archives/maven-dependency-plugin-LATEST/copy-mojo.html

**Comment by Yas-Franco** [comment]
We should show the user:
Config:
---
  - [x] Jaeger
  - [x] Zipkin
  - [x] Logging
  - [x] Enabling/ disabling tracing
 
 Maven goal
 ---
  - [x] Copy the Java agent
 
Span annotation
---
  - [ ] WithSpan annotation
  - [ ] Manual creation of spans: 
    - [ ] Parent/ child span creation
    - [x] Adding a span event
    - [ ] Setting span attributes
   
Tracing across multiple services: 
 ---
  1. **Inventory** should include:
  - [x] Feature configuration in `microprofile-config.properties`
  - [x] `mpTelemetry-1.0` enabled in the `server.xml`
  - [ ] Inventory resource with WIthSpan annotation
  - [x] Inventory manger with manual instrumentation (i.e. manual span creation using `Tracer`)
  
  2. **System** should include:
  - [x] Use the mvn:package goal to copy the java agent
  - [x] `jvm.options` with java agent configuration
  - [x] Resource that returns the system properties
