### ISSUE TITLE
Extend FAT testing for Authn 3.0.1 and Authz 2.1

### ISSUE THREAD

**Issue by emilytee** [OpenLiberty/open-liberty#23216]

**Comment by emilytee** [comment]
Adding tests per Adam:
getPolicyConfiguration(String contextID) with (A) a context ID that doesn’t exist, and (B) one that doesn’t have a policy config already.
A test for removeServerAuthModule(Object context) where the context referred to doesn’t exist.

**Comment by ayoho** [comment]
Should be resolved by https://github.com/OpenLiberty/open-liberty/pull/23257
