### ISSUE TITLE
Design review for URI paths rejection suspicious sequences

### ISSUE THREAD

**Issue by pmd1nh** [OpenLiberty/open-liberty#23279]
The EE 10 Servlet 6.0 clarifies the process for a request [URI ](https://jakarta.ee/specifications/servlet/6.0/jakarta-servlet-spec-6.0.html#uri-path-canonicalization)path before mapping it to a target resource (servlet/filter/security...).  One of the steps is to reject any suspicious sequences if detected in the URI : 

```
10 . Rejecting Suspicious Sequences.

If suspicious sequences are discovered during the prior processing steps, the request
must be rejected with a 400 bad request rather than dispatched to the target servlet. If 
a context is matched then the error handling of the context may be used to generate 
the 400 response. By default, the set of suspicious sequences is 
defined below, but may be configured differently by a container:

    The presence of a fragment in the URI

    Any path not starting with the "/" character (e.g. path/info)

    Any path starting with an initial segment of ".." (e.g. /../path/info)

    The encoded "/" character (e.g. /path%2Finfo)

    Any "." or ".." segment that had a path parameter (e.g. /path/..;/info)

    Any "." or ".." segment with any encoded characters (e.g. /path/%2e%2e/info)

    If empty segments are not removed, then ".." segment preceded by an empty segment (e.g. /path//../info)

    Any empty segment other than the last segment, with parameters (e.g. /path/;param/info )

    The "\" character encoded or not. (e.g. /path\info)

    Any control characters either encoded or not. (e.g. /path%00/info)

    Any illegal hex sequences following a % character

    Any illegal UTF-8 code sequences.

```

The current encoded characters that are rejected with a 400 Bad Request: 
%23 (#) - fragment
%2E (.) - dot
%2F (/) - forwardslash
%5C (\\) - backslash

These are the default but the Servlet Spec also states that they may be configured differently by a container:

`By default, the set of suspicious sequences is defined below, but may be configured differently by a container`

In addition, the spec also states :
`Servlet containers may provide container specific configuration options to vary the standard canonicalization process. Any such variations may have security implications and both Servlet container implementors and users are advised to be sure that they understand the implications of any such container specific canonicalization options.`

To be reviewed: 
1. Should Liberty provide an opt-out setting for backward compatibility or to ease a migration to the new servlet?
2. If there will be one, what should be the default behavior? via WC or JVM property?
3. Selective setting for each or one-setting-for-all ?

**Comment by idlewis** [comment]
This affects the IBMJMXConnectorREST servlet. Specifically, I think the default behaviour of rejecting encoded '/' will affect file transfer. From our docs:
```
Invoke a GET call to download the file.
GET https://myTarget.com:9443//IBMJMXConnectorREST/file/C%3A%2Ftemp%2FmyFile.txt
```
The above request would be rejected by the servlet container under the default servlet 6 behaviour

However, further digging suggests that, despite what our docs say, i.e.:
`{filePath} must be URL-encoded`
file transfer seems to work okay if '/' is left as a literal in the file specifier. This may just need an update to our docs

**Comment by idlewis** [comment]
This issue also affects the config and validation REST APIs. A number of fat tests fail when run with servlet 6. For example, a request to:

`https://localhost:9443:/ibm/api/config/adminObject/adminObject%5Bjava:global%2Fenv%2Feis%2FconSpec1%5D`
is expecting to retrieving an adminObject with a jndiName of
`java:global/env/eis/conSpec1`
But the request contains encoded '/', and so is rejected by the servlet container, before it reaches the rest handler


More investigation is probably need to see whether the config rest handler would cope if the %2F is replaced with a a literal '/'

**Comment by pmd1nh** [comment]
Investigating see if the rejection can be deferred until a servlet target is determined.  If the request is not for a servlet, let it passthrough.

**Comment by pmd1nh** [comment]
/IBMJMXConnectorREST/ is mapped to servlet  [JMXRESTProxyServlet](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.jmx.connector.server.rest/src/com/ibm/ws/jmx/connector/server/rest/JMXRESTProxyServlet.java)

/ibm/api/ is mapped to servlet [RESTProxyServlet](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.rest.handler/src/com/ibm/ws/rest/handler/internal/servlet/RESTProxyServlet.java)

So even with the deferring til the servlet is determined, these tests still fail.

**Comment by pmd1nh** [comment]
closed out. JMXconnector change its code to accommodate this servlet change.
