### ISSUE TITLE
Non-programming model function for InstantOn

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#23275]
This epic is to track additional functionality liberty features that need to be supported for InstantOn.  For example, support for bells-1.0 feature.

**Comment by NottyCode** [comment]
List of non-programming model features to consider for MVP:

- adminCenter-1.0
- restConnector-2.0
- audit-1.0
- acmeCA-2.0
- batchManagement-1.0
- sessionDatabase-1.0
- sessionCache-1.0
- distributedMap-1.0
- eventLogging-1.0
- federatedRegistry-1.0
- jwtSso-1.0
- constrainedDelegation-1.0
- ldapRegistry-3.0
- logstashCollector-1.0
- oauth-2.0
- openid-2.0
- openidConnectClient-1.0
- openidConnectServer-1.0
- passwordUtilities-1.1
- monitor-1.0
- requestTiming-1.0
- samlWeb-2.0
- spnego-1.0
- socialLogin-1.0
- webCache-1.0
- wsSecurity-1.1
- wsAtomicTransaction-1.2
- wsSecuritySaml-1.1

**Comment by tjwatson** [comment]
Here is the initial prioritization of the list

1 - must have for MVP
2 - nice to have for MVP
3 - not needed for MVP

### MUST HAVE
- [x] audit-1.0
- [x] bell-1.0
- [x] distributedMap-1.0
- [x] federatedRegistry-1.0
- [x] ldapRegistry-3.0
- [x] monitor-1.0
- [x] openidConnectClient-1.0
- [x] passwordUtilities-1.1
- [x] restConnector-2.0
- [x] sessionDatabase-1.0
- [x] socialLogin-1.0
- [x] webCache-1.0
- [ ] wsSecurity-1.1

### NICE TO HAVE
- [ ] 2 acmeCA-2.0
- [ ] 2 constrainedDelegation-1.0
- [ ] 2 eventLogging-1.0
- [ ] 2 jwtSso-1.0
- [ ] 2 requestTiming-1.0
- [ ] 2 samlWeb-2.0
- [x] 2 sessionCache-1.0
- [ ] 2 spnego-1.0
- [ ] 2 wsSecuritySaml-1.1

### NOT NEEDED
- [ ] 3 adminCenter-1.0
- [ ] 3 batchManagement-1.0
- [ ] 3 logstashCollector-1.0
- [ ] 3 oauth-2.0
- [ ] 3 openid-2.0
- [x] 3 openidConnectServer-1.0
- [ ] 3 wsAtomicTransaction-1.2

**Comment by tjwatson** [comment]
- [x] [restConnector-2.0](https://github.com/OpenLiberty/open-liberty/issues/23702)
- [x] [audit-1.0](https://github.com/OpenLiberty/open-liberty/issues/23703)
- [x] [bell-1.0](https://github.com/OpenLiberty/open-liberty/issues/23276)
- [x] [sessionDatabase-1.0](https://github.com/OpenLiberty/open-liberty/issues/23704)
- [x] [distributedMap-1.0](https://github.com/OpenLiberty/open-liberty/issues/23705)
- [x] [federatedRegistry-1.0](https://github.com/OpenLiberty/open-liberty/issues/23706)
- [x] [ldapRegistry-3.0](https://github.com/OpenLiberty/open-liberty/issues/23707)
- [x] [openidConnectClient-1.0](https://github.com/OpenLiberty/open-liberty/issues/23708)
- [x] [passwordUtilities-1.1](https://github.com/OpenLiberty/open-liberty/issues/23709)
- [x] monitor-1.0
- [x] [socialLogin-1.0](https://github.com/OpenLiberty/open-liberty/issues/23710)
- [x] [webCache-1.0](https://github.com/OpenLiberty/open-liberty/issues/23711)
