### ISSUE TITLE
Scripts do not respect the enable_variable_expansion indicator in server.env

### ISSUE THREAD

**Issue by jimblye** [OpenLiberty/open-liberty#23273]
**Describe the bug**  

The **server** script allows variable expansion in the **server.env** file when a comment, "# enable_variable_expansion",  is found in the file.   This is documented in the [Server Configuration Overview](https://openliberty.io/docs/latest/reference/config/server-configuration-overview.html).

However, the rest of the scripts under wlp/bin ignore the "# enable_variable_expansion" comment, and instead, respect the "# enable_variable_**resolution**" comment in server.env, which is NOT documented.   These are the affected scripts:

```
./ddlGen
./springBootUtility
./featureUtility
./xmlWS/wsimport
./xmlWS/wsgen
./jaxws/wsimport
./jaxws/wsgen
./serverSchemaGen
./jaxb/xjc
./jaxb/schemagen
./binaryLog
./securityUtility
./pluginUtility
./jaxrs/wadl2java
./auditUtility
./productInfo
./schemaGen
./batchManager
./xmlBinding/xjc
./xmlBinding/schemagen
```

**Steps to Reproduce**  
Create  a server.env.  
In the server.env add a comment:  # enable_variable_expansion
Reference a variable using syntax ${variable_name}, for example X=$host.
_An example is needed to show where variable expansion does not occur using one of the affected scripts._

**Expected behavior**  
Wherever the variable is referenced, it's expanded value should be available.

**Diagnostic information:**  
 - OpenLiberty Version: [e.g. 22.0.0.1 - 22.0.0.11]
 - Affected feature(s) [**wlp/bin scripts** (platforms except Windows)]

**Additional context**  
The scripts are generated in the open liberty build from file **dev/cnf/resources/bin/tool**.
When variable expansion support was added for server.env, at the last minute the enabling comment was changed from "# enable_variable_**resolution**" to "# enable_variable_**expansion**", but unfortunately the change was not also made in **dev/cnf/resources/bin/tool**.

Potentially, if someone reads the scripts, they might be depending on "# enable_variable_**resolution**".    Though this seems very unlikely, but possible. That enabler is not documented anywhere.

**Comment by cbridgha** [comment]
Although this is unfortunate - we can avoid any chance of breaking an existing customer if we start enabling for the other scripts on either of these comments - the one documented: "# enable_variable_expansion", and the one current "secret" comment: "# enable_variable_resolution".    Please add another test that exercises another script in this list.
