### ISSUE TITLE
Testing for new --timeout option for server stop command

### ISSUE THREAD

**Issue by jimblye** [OpenLiberty/open-liberty#23280]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

Four tests will be added:

1. Test stop command without --timeout option.   Ensures that new --timeout option is not required and that existing command still works.
2. Test stop command with valid timeout.  Using 5m (5 minutes) to avoid test failures due to race conditions.
3. Test with invalid argument.  For example --timeout=garbage.
4. Test -timeout on some other action other than "stop".   The --timeout is only valid for the stop action.

### List of FAT projects affected

* com.ibm.ws.kernel.boot_fat

### Test strategy

* What functionality is new or modified by this feature?

      --timeout command line option is new for the ./server stop command.    The main usage would be to extend the timeout beyond the 30-second default.   Customer would use this this to increase the wait-time if for some odd reason the server sometimes failed to stop within 30 seconds. The customer could set a smaller value, but the usefulness of changing the timeout value in that direction is questionable.
      
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
   The test cases are listed above.

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

    - Tested a short-duration timeout of < 1 second to ensure that timeout does occur.   Decided not to automate this since stop can be fast and could cause a race condition; meaning sometimes the stop would be fast enough to not timeout even though a small timeout value is set.

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by ayoho** [comment]
Coverage sounds good to me 👍
