### ISSUE TITLE
GA Jakarta EE 10 JSON Binding 3.0 and Processing 2.1 Features

### ISSUE THREAD

**Issue by KyleAure** [OpenLiberty/open-liberty#23289]
The following features need to be GAed for the release of `jsonb-3.0` and `jsonp-2.1` for 22.0.0.13 release

- [ ] io.openliberty.jsonb.compatibility.feature
- [ ] io.openliberty.jsonp.compatibility.feature
- [ ] io.openliberty.jsonbImpl-3.0.0.feature
- [ ] io.openliberty.jsonbImpl-3.0.1.feature
- [ ] io.openliberty.jsonbInternal-3.0.feature
- [ ] io.openliberty.jsonpImpl-2.1.0.feature
- [ ] io.openliberty.jsonpImpl-2.1.1.feature
- [ ] io.openliberty.jsonpInternal-2.1.feature
- [ ] io.openliberty.jsonb-3.0.feature
- [ ] io.openliberty.jsonbContainer-3.0.feature
- [ ] io.openliberty.jsonp-2.1.feature
- [ ] io.openliberty.jsonpContainer-2.1.feature

**Comment by njr-11** [comment]
separately covered by Jared
