### ISSUE TITLE
GA Jakarta EE 10 Connectors 2.1 Features

### ISSUE THREAD

**Issue by KyleAure** [OpenLiberty/open-liberty#23291]
The following features need to be GAed for the release of `connectors-2.1` for 22.0.0.13 release:

- [ ] io.openliberty.connectorsInboundSecurity-2.1.feature
- [ ] io.openliberty.connectionManager1.0.internal.ee-10.0.feature
- [ ] io.openliberty.connectors-2.1.internal.feature
- [ ] io.openliberty.jakarta.connectors-2.1.feature
- [ ] io.openliberty.appserver.connectors-2.1.feature
- [ ] io.openliberty.connectors-2.1.feature

**Comment by njr-11** [comment]
separately covered by Jared
