### ISSUE TITLE
Liberty with mpTelemetry-1.0 failed to export span when using OTEL_TRACES_EXPORTER=jaeger

### ISSUE THREAD

**Issue by hanczaryk** [OpenLiberty/open-liberty#23365]
**Describe the bug**  
I'm attempting to utilize the 5 AcmeAir microservices (repos are located at https://github.com/blueperf/) on Liberty with mpTelemetry-1.0 using OTEL_TRACES_EXPORTER=jaeger option as detailed in https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md

For the 5 microservice Dockerfile's I set the following env info

```
ENV OTEL_TRACES_EXPORTER=jaeger
ENV OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger-all-in-one-inmemory-collector:14250
ENV OTEL_SERVICE_NAME=XXXservice
ENV OTEL_SDK_DISABLED=false
ENV OTEL_METRICS_EXPORTER=none
```

I installed the Community Jaeger Operator (v1.39.0) and used the OpenShift console to create a Jaeger instance. Before creating the Jaeger instance, switch to the 'acmeair' namespace and use 'jaeger-all-in-one-inmemory' for the name.

With OTEL_TRACE_EXPORTER=jaeger, I observe the following error messages in bookingservice, customerservice and flightservice after loading the DB.

The following is a snippet from bookingservice's messages.log showing the error message.
```
[11/15/22, 15:27:06:287 UTC] 0000003a com.acmeair.loader.BookingLoader                             I Finished clearing in 0.028 seconds
[11/15/22, 15:27:07:103 UTC] 00000066 org.mongodb.driver.connection                                I Opened connection [connectionId{localValue:3}] to acmeair-booking-db:27017
[11/15/22, 15:27:11:274 UTC] 0000007b io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter   E Failed to export spans. The request could not be executed. Full error message: Broken pipe (Write failed)
```

Here is the head of messages.log showing open liberty build info.
```
[root@api.bphgo.cp.fyre.ibm.com logs]# head pod_logs/acmeair-bookingservice-768975d4f6-84s8n/messages.log 
********************************************************************************
product = Open Liberty 22.0.0.13 (wlp-1.0.72.cl221320221112-0300)
wlp.install.dir = /opt/ol/wlp/
server.output.dir = /opt/ol/wlp/output/defaultServer/
java.home = /opt/java/openjdk
java.version = 11.0.17
java.runtime = IBM Semeru Runtime Open Edition (11.0.17+8)
```

I've gathered and zipped the pod_logs for the 5 acmeair microservices which show the error messages for bookingservice, customerservice and flightservice after loading the DB.
[pod_logs_jaeger.zip](https://github.com/OpenLiberty/open-liberty/files/10013984/pod_logs_jaeger.zip)

I've captured the jaeger container pod logs and attached here.
[jaeger_container.log](https://github.com/OpenLiberty/open-liberty/files/10014255/jaeger_container.log)

I previously followed the same acmeair setup but used otlp instead of jaeger as follows.
```
ENV OTEL_TRACES_EXPORTER=otlp
ENV OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger-all-in-one-inmemory-collector:4317
ENV OTEL_SERVICE_NAME=XXXservice
ENV OTEL_SDK_DISABLED=false
ENV OTEL_METRICS_EXPORTER=none
```

I gathered and zipped the pod_logs for the 5 acmeair microservices using OTEL_TRACES_EXPORTER=otlp which works properly and shows no error message in the logs.  Also, I was able to validate in the Jaeger UI that traces could be found.
[pod_logs_otlp.zip](https://github.com/OpenLiberty/open-liberty/files/10013822/pod_logs_otlp.zip)

**Steps to Reproduce**  
Steps are detailed above using OpenShift OTEL_TRACES_EXPORTER=jaeger vs OTEL_TRACES_EXPORTER=otlp

**Expected behavior**  
I expect that no error messages should occur using OTEL_TRACES_EXPORTER=jaeger and the Jaeger UI should allow the user to find the traces for bookingservice, customerservice and flightservice after loading the DB.

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.13 (mpTelemetry-1.0 beta)
 - Affected feature(s) mpTelemetry-1.0
 - Java Version: [i.e. full output of `java -version`]

```
openjdk version "11.0.17" 2022-10-18
IBM Semeru Runtime Open Edition 11.0.17.0 (build 11.0.17+8)
Eclipse OpenJ9 VM 11.0.17.0 (build openj9-0.35.0, JRE 11 Linux amd64-64-Bit Compressed References 20221031_559 (JIT enabled, AOT enabled)
OpenJ9   - e04a7f6c1
OMR      - 85a21674f
JCL      - a94c231303 based on jdk-11.0.17+8)
```

 - server.xml configuration (WITHOUT sensitive information like passwords)
```
 <?xml version="1.0" encoding="UTF-8"?>
<server>
  <!-- Enable features -->
  <featureManager>
    <feature>microProfile-6.0</feature>
  </featureManager>

  <!-- To access this server from a remote client add a host attribute to the following element, e.g. host="*" -->
  <httpEndpoint 
    id="defaultHttpEndpoint" 
    host="*" 
    httpPort="${DEFAULT_HTTP_PORT}" 
    httpsPort="${DEFAULT_HTTPS_PORT}">
    <accessLogging 
      enabled="${ACCESS_LOGGING_ENABLED}" 
      filepath="${server.output.dir}/logs/http_defaultEndpoint_access.log" 
      logFormat='%h %u %t "%r" %s %b %D %{User-agent}i'>
    </accessLogging>
  </httpEndpoint>
  
  <monitor  filter="REST"/>
    
  <basicRegistry id="basic" realm="WebRealm">
    <user name="${env.USERNAME}" password="${env.PASSWORD}" />
  </basicRegistry>

  <administrator-role>
    <user-access-id>user:WebRealm/${env.USERNAME}</user-access-id>
  </administrator-role>

  <!-- Basic User Registry not to be used on /booking URL requests -->
  <authFilter id="mpJwtAuthFilter">
    <requestUrl id="request" urlPattern="/booking" matchType="notContain" />
  </authFilter>

  <mpJwt id="jwtUserConsumer" authFilterRef="mpJwtAuthFilter" ignoreApplicationAuthMethod="false" mapToUserRegistry="true" />

  <logging 
    consoleFormat="${LOGGING_FORMAT}" 
    consoleSource="message,trace,accessLog,ffdc,audit" 
    messageFormat="${LOGGING_FORMAT}" 
    messageSource="message,trace,accessLog,ffdc,audit" 
    traceSpecification="${TRACE_SPEC}" />

  <webApplication name="acmeair-bookingservice" location="acmeair-bookingservice-java-6.0.war" contextRoot="/booking">
    <classloader apiTypeVisibility="api,ibm-api,spec,stable,third-party" />
  </webApplication>

  <keyStore id="defaultKeyStore" password="XXX" />

  <cors 
    domain="/booking" 
    allowedOrigins="*" 
    allowedMethods="GET, DELETE, POST, OPTIONS" 
    allowedHeaders="*" 
    allowCredentials="true" 
    maxAge="3600" />
</server>
```

**Additional context**

**Comment by fmhwong** [comment]
The grpc-jaeger port of Jaeger on OpenShift is tls enabled.  OTel SDK doesn't have options to setup TLS when using `OTEL_TRACES_EXPORTER=jaeger`.  We need to deploy a OTel Collector as the middle person.

Microservice ---otlp--> Collector ---tls-grpc-jaeger--> Jaeger

Talked to @hanczaryk and confirmed he can see traces in Jaeger in this setup.
