### ISSUE TITLE
Feature Test Summary for RESTful WS 3.1

### ISSUE THREAD

**Issue by jim-krueger** [OpenLiberty/open-liberty#23382]
FTS for Epic Issue #18739

## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

- Existing JAX-RS 2.X and Jakarta Rest 3.0 FAT test cases are repeated using the new restfulWS-3.1 features.

- New FAT tests have been written in the following projects:
io.openliberty.jakarta.restfulWS.3.1.api_fat
io.openliberty.jakarta.rest.3.1.internal_fat_tck (runs core profile Jakarta Rest TCK)
io.openliberty.restfulWS.3.1_fat (See issues [22884](https://github.com/OpenLiberty/open-liberty/issues/22884), [22541](https://github.com/OpenLiberty/open-liberty/issues/22541))

- FAT tests changed to account for EE10 specific results
com.ibm.ws.jaxrs.2.1_fat_executor - changes due to Concurrency API adjustments PR [23783](https://github.com/OpenLiberty/open-liberty/pull/23783)
io.openliberty.ws.jaxrs.global.handler.internal_fat - see issue [22598](https://github.com/OpenLiberty/open-liberty/issues/22598)
io.openliberty.ws.jaxws.global.handler.internal_fat - see issue [22598](https://github.com/OpenLiberty/open-liberty/issues/22598)

- SVT tests are planned to be run and EE10 feature changes have been communicated to Brian Hanczaryk.
- CTS tests for EE10 have been run successfully : Added core profile TCK to FAT to execute with every build.

### List of FAT projects affected

* com.ibm.ws.jaxrs.2.0_fat
* com.ibm.ws.jaxrs.2.0.cdi.1.2_fat
* com.ibm.ws.jaxrs.2.0.client_fat
* com.ibm.ws.jaxrs.2.1_fat
* com.ibm.ws.jaxrs.2.1_fat_executor
* com.ibm.ws.jaxrs.2.1_fat_extended
* com.ibm.ws.jaxrs.2.1.cdi.2.0_fat
* com.ibm.ws.jaxrs.2.1.client_fat
* com.ibm.ws.jaxrs.2.1.sse_fat
* com.ibm.ws.jaxrs.2.x.webcontainer_fat
* com.ibm.ws.jaxrs.defaultexceptionmapper_fat
* io.openliberty.restfulWS.3.0_fat
* io.openliberty.restfulWS.3.0.cdi.3.0_fat
* io.openliberty.restfulWS.3.0.client_fat
* io.openliberty.jakarta.rest.3.1.internal_fat_tck
* io.openliberty.jakarta.restfulWS.3.1.api_fat
* io.openliberty.restfulWS.3.1_fat
* io.openliberty.ws.jaxrs.global.handler.internal_fat
* io.openliberty.ws.jaxws.global.handler.internal_fat 

### Test strategy

* What functionality is new or modified by this feature?
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

This Epic delivers the changes associated with the Jakarta Rest 3.1 Specification.  These changes were tested by the TCK, which we also run internally.  We did discover that the Multi-part function added with version 3.1 was not appropriately tested within the TCK and added tests to io.openliberty.restfulWS.3.1_fat to cover this gap.   Added testing included testing of old IAttachment and new spec-defined EntityPart requests with default and non-default media types.  We will be driving test additions for this function to the TCK post-EE10.

Beyond the changes due to the Jakarta Rest 3.1 specification, the existing Global Handler support, which had be included automatically with the restfulWS-3.0 and xml-3.0 feature, was changed to be optional.  This function is now provided via a protected feature that requires the restfulWS-3.1 or xml-4.0 features in addition to specification in the user feature's manifest file. EE10-specific testing was added via [PR 24040](https://github.com/OpenLiberty/open-liberty/pull/24040) to verify the correct behavior when this protected feature is configured properly and when it is not.

Also, in EE8, when the Liberty RESTful Web Services implementation was based on CXF, changes and tests were added to ensure that the proper context was maintained on threads involving the managed executor service for operations involving concurrency. These tests exist in the com.ibm.ws.jaxrs.2.1_fat_executor project.  These tests were skipped in EE9 because RESTEasy did not properly support this function.   Under [PR 23783](https://github.com/OpenLiberty/open-liberty/pull/23783) changes were made to both Open Liberty and RESTEasy override files to support this function.  As a results the tests in the aforementioned project have been enabled to run for EE10.

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

**Confidence Level**
4

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Justification for Confidence Level 4:**
Most of the RESTful Web Services 3.1 additions/changes for EE10 were provided to Open Liberty via RESTEasy 6.2.0.   With the EE10 addition of the io.openliberty.jakarta.rest.3.1.internal_fat_tck tests to our existing FAT suites much of the testing for these additions/changes has been covered.   Testing was then added for Jakarta Rest EE10 additions/changes that required Open Liberty-specific changes, such as the Multipart support, or were not part of the Jakarta 3.1 specification, such as Global Handler and Concurrency 3.0 support.

**Additional Testing Post-EE10**
- [Issue 23658](https://github.com/OpenLiberty/open-liberty/issues/23658): Add additional testing beyond the TCK for when Content-Type or Accept are missing in request.  No Liberty-specific changes made for this in EE10.
- [Issue 28751](https://github.ibm.com/websphere/WS-CD-Open/issues/28751): There is a gap in EJB testing that has existed since EE9.
- [Issue 24410](https://github.com/OpenLiberty/open-liberty/issues/24410): Add additional testing beyond the TCK for  MediaType.MULTIPART_FORM_DATA @FormParam requests containing EntityPart objects.

**Comment by jim-krueger** [comment]
@ayoho @dave-waddling  Can one (or both) of you please take a quick looks at this FTS?  Thanks

**Comment by ayoho** [comment]
LGTM 👍
