### ISSUE TITLE
A syntax error in JSP compile should consistently output error JSPG0077E 

### ISSUE THREAD

**Issue by epj** [OpenLiberty/open-liberty#23425]
**Describe the bug**  
JSPG0077E needs to be output to messages.log and console.log in all cases of a JSP Syntax Error (JspCoreException).   This message will be missing if the syntax error is hit in a JSP that previously wasn't compiled and precompile is disabled.

**Steps to Reproduce**  
Have a war containing a jsp with this line in it:
<%="hello jsp">
Attempting to call it, without precompile, results in a HTTP 500 error, but nothing is logged if it hadn't previously compiled on the server. 

**Expected behavior**  
The following message is output to messages.log and console.log from a JSP syntax error if precompile is enabled.  This message is missing without precompile if the servlet did not previously exist.  

[WARNING ] Unexpected exception while processing jsp /xxxx.jsp
/xxxx.jsp(2,1) JSPG0077E: End of file reached while processing scripting element "yyyyy"&gt;^M
 at Line: 1 Col: 1

**Diagnostic information:**  
 - OpenLiberty Version: all
 - Affected feature(s): jsp-2.2, jsp-2.3
 - Java Version: all
 - server.xml configuration: see above
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Comment by pnicolucci** [comment]
@epj are these messages in console.log and messages.log?

**Comment by epj** [comment]
Yes.  I'll update the text above to clarify.

**Comment by e30532** [comment]
@epj could you tell me the liberty version which will include the fixed code?
