### ISSUE TITLE
MP JWT should support JWTs signed with shared secret

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/open-liberty#2344]
The current mpJwt feature does not support tokens signed with a shared secret i.e. HMAC algorithms like HS256.

This is a common approach used to sign JWTs especially for simpler usages and for demonstration purposes.

What we have in Open Liberty for MP JWT should support such tokens to make it easier for users to work with mpJwt.

**Comment by brutif** [comment]
2526 has been committed, should be available in daily builds shortly.
