### ISSUE TITLE
Telemetry REST integration FAT tests

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#23448]
MP Telemetry needs to integrate with `restfulWS` and `mpRestClient`. Whenever a request is made or received by one of these features, MP Telemetry should create a span. Trace ID information should be sent via the HTTP headers so that the traces from both the client and server can be joined up. Baggage information should also be sent via the HTTP headers so that contextual information from the first service can be included in trace messages in the second service.

For each of these locations:
* JAX-RS server
* JAX-RS client
* MP Rest Client

We need to test:
* Creation of spans
* Propagation of spanIds
* Propagation of baggage
* synchronous and async execution
* Correct application of [Semantic convention attributes][semconv]
  * TCK `RestClientSpanTest` only checks HTTP_STATUS, HTTP_METHOD, HTTP_SCHEME, HTTP_TARGET, HTTP_URL, see if there are any others which should be present
  * There are [constants defined][semconv-javadoc] for each of the attributes in the spec

There are several different standards (selected [via configuration][propagation-config]) for propagating spanIds and baggage. We need to test:
  * W3C tracer (default for trace)
  * W3C baggage (default for baggage)
  * B3
  * Jaeger

[semconv]: https://opentelemetry.io/docs/reference/specification/metrics/semantic_conventions/http-metrics/
[semconv-javadoc]: https://www.javadoc.io/doc/io.opentelemetry/opentelemetry-semconv/1.18.0-alpha/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.html
[propagation-config]: https://github.com/open-telemetry/opentelemetry-java/tree/v1.18.0/sdk-extensions/autoconfigure#propagator

**Comment by benjamin-confino** [comment]
This PR also contains an update to these tests: https://github.com/OpenLiberty/open-liberty/pull/23630

**Comment by Azquelt** [comment]
Found a few more things that need testing when comparing our tests with older FATs for OpenTracing:

Fixed in #24229:
- [x] Test tracing of all of the supported HTTP methods (GET, POST, HEAD etc.) through JAX-RS
- [x] Test tracing different response codes received from JAX-RS (200, 500 etc)
- [x] Test async handling of a request on JAX-RS server side using `@Suspended` (#24125 does a similar test with `CompletionStage`)

Fixed in #24269:
- [ ] Test calling a non-existent path within a JAX-RS app - not entirely sure of the expected behaviour here
- [ ] Test calling a redirect (3xx with `Location` header set)

**Comment by Azquelt** [comment]
Ready to close once #24269 is merged.
