### ISSUE TITLE
maxFfdcAge - Feature Test Summary

### ISSUE THREAD

**Issue by tonyreigns** [OpenLiberty/open-liberty#23454]
## Test Strategy

For #19418 

This feature introduces a new logging configuration attribute into Liberty, maxFfdcAge which allows a user to set the maximum age before an FFDC file is deleted. Currently, the FFDC cleanup only occurs at midnight, so an internal configuration attribute, ffdcCleanupStartDelay, was added to force the cleanup to occur immediately. 

The fat project affected is: com.ibm.ws.logging_fat
Tests added:
- testFfdcCleanupDeletion() - Hits an endpoint that creates an FFDC file, sets the maxFfdcAge to 0 minutes and ensures that there was a successful deletion of the FFDC file.

- testFfdcCleanupNoDeletion() - Hits an endpoint that creates an FFDC file, sets the maxFfdcAge to 1 day and ensures that the FFDC file was not deleted since the FFDC file age will be less than 1 day.

- testFfdcCleanupNotConfigured() - Hits an endpoint that creates an FFDC file, no maxFfdcAge value is set ensures that the FFDC file was not deleted since no maxFfdcAge was set.

The FAT tests created ensure that when maxFfdcAge is used, deletion only occurs when the FFDC file ages are greater than the configured maxFfdcAge. No deletion will occur by this new feature if the maxFfdcAge is not set.

Manual tests were done by setting the maxFfdcAge attribute using several of the methods available, such as using server.xml, server.env, and bootstrap.properties. During every manual test, we ensured that the configured maxFfdcAge was adhered to.

These changes have already been in the 210013 beta and have been tested extensively.

Confidence level is 4.

**Comment by ayoho** [comment]
> Manual tests were done by setting the maxFfdcAge attribute using several of the methods available, such as using server.xml, server.env, and bootstrap.properties. During every manual test, we ensured that the configured maxFfdcAge was adhered to.

I'm curious why these weren't also added as FATs; they should be straightforward to create and run, and we'd then have them available continuously.

The new attribute is straightforward enough that I think the coverage is fine.

**Comment by tonyreigns** [comment]
> > Manual tests were done by setting the maxFfdcAge attribute using several of the methods available, such as using server.xml, server.env, and bootstrap.properties. During every manual test, we ensured that the configured maxFfdcAge was adhered to.
> 
> I'm curious why these weren't also added as FATs; they should be straightforward to create and run, and we'd then have them available continuously.
> 
> The new attribute is straightforward enough that I think the coverage is fine.

Hi Adam, the reason I only created test cases for the server.xml configuration is because I wasn't able to find a way to create an internal configuration attribute for server.env/bootstrap.properties, so I wasn't able to force the cleanup to occur immediately for testing purposes. 

I also can't use the server.xml `ffdcCleanupStartDelay` to test the other configurations because by the time the server.xml is loaded in, the configured maxFfdcAge from the server.env/bootstrap.properties is already scheduled for midnight. 

As you said, it was a straightforward enough feature so I figured the testing was enough. Hope that clears things up, thanks.
