### ISSUE TITLE
Tests for @WithSpan and @SpanAttribute

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#23450]
- [x] When `@WithSpan` is applied to a CDI method, a span is created and made current when that method is called as a [business method invocation][biz-method]
- [x] The created span is ended when the method returns
- [x] If `@SpanAttribute` is applied to a method parameter, the value of that parameter is added as an attribute to the created span
- [x] Call `@WithSpan` annotated method from a method that is also annoted with `@WithSpan`. Spans are started and ended appropriately for each one. 

[biz-method]:https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#biz_method

**Comment by Yas-Franco** [comment]
The pull request and issue have been updated. Recurisve calls to an annotated method do not generate spans because of a CDI issue.

**Comment by Azquelt** [comment]
You need to close the issue as well as moving it to the Done column. I think closing it will move it to Done automatically, but moving it to Done doesn't close it.
