### ISSUE TITLE
Support the OpenTelemetry logging exporter

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#23481]
Add support and tests for the [OpenTelemetry logging exporter](https://github.com/open-telemetry/opentelemetry-java/tree/v1.18.0/sdk-extensions/autoconfigure#logging-exporter)

Currently, the SDK Autoconfigure will allow you to configure it, but then complains that it can't find the exporter. We need to check if we're actually including it and if so why it's not available when we try to configure open telemetry.

**Comment by Yas-Franco** [comment]
The package was just missing from the bundle. I still need to add tests for this
