### ISSUE TITLE
Mail 2.1: mail-2.1 Feature Test Summary

### ISSUE THREAD

**Issue by neuwerk** [OpenLiberty/open-liberty#23494]
Test Strategy

Mail 2.1 is a nearly identical feature to Mail 2.1, with one exception they've removed the spec dependency on the RI. With the dependency broken, they've added on new API StreamProvider to help facilitate impl look up. In testing we've repeated all tests for mail 2.0, as well as added a new bucket to test the StreamProvider API is working as intended.

The StreamProvider API was introduced to break the specification's dependency on the reference implementation. The API provides the supported encoders/decoders types. There's no practical use case from a user point of view for this API, but since an instance of the StreamProvider can be returned by `Session.getSteamProvider()`, a user would be able to obtain an instance of it on Liberty. So in order to test this, we've added the `io.openliberty.mail.fat.StreamProviderTest` to a new bucket, `io.openliberty.mail.2.1.internal_fat` that essentially just makes sure all the related types of encoder/decoders can be obtained from the StreamProvider API when running on Liberty. 

List of FAT projects affected

    com.ibm.ws.jaxws.2.2.webcontainer_fat
    io.openliberty.mail.2.0.internal_fat
    io.openliberty.mail.2.1.internal_fat

Confidence Level

5

**Comment by ayoho** [comment]
LGTM 👍
