### ISSUE TITLE
XML Binding 4.0: xmlBinding-4.0 Feature Test Summary

### ISSUE THREAD

**Issue by neuwerk** [OpenLiberty/open-liberty#23493]
## Test Strategy

XML Binding 4.0  support is by and large the same feature as XML Binding 3.0, so 99% of all the tests that run with xmlBinding-3.0 can be repeated for 4.0.  There are two exceptions, any test that uses the deprecated jakarta.xml.bind.Validator API has to be skipped as that was removed by the SPEC, and new tests added for the changes to their implementation look up algorithm brought.

### List of FAT projects affected

com.ibm.ws.jaxb_fat (preexisting bucket with EE10 repeat action)
io.openliberty.xmlBinding.4.0.internal_fat (new for EE10 bucket)

### Test strategy

As mentioned in the summary, the Validator API was removed and how the spec discovers what implementation is being used changed. 

For the implementation discovery changes, we added tests that cover overriding the implementation shipped with liberty for a third-party implemenation. That is a positive scenario. We also test marshalling/unmarshalling with third-party and liberty specific implementations. We also test negative cases where the user specifies the wrong third-party implementation which results in a NCDFE.

## Confidence Level

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values: 5

**Comment by ayoho** [comment]
LGTM 👍
