### ISSUE TITLE
Guide: MicroProfile Telemetry 1.0

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#23509]
Create a new guide for MicroProfile OpenTelemetry 1.0 feature.

**Comment by fmhwong** [comment]
@gkwan-ibm A new guide is needed.

**Comment by gkwan-ibm** [comment]
Issue moved to [OpenLiberty/guides-common #888](https://github.com/OpenLiberty/guides-common/issues/888) via [**Zenhub**](https://www.zenhub.com/)
