### ISSUE TITLE
decode url query string before final redirection of the original request

### ISSUE THREAD

**Issue by arunavemulapalli** [OpenLiberty/open-liberty#23567]
**Describe the bug**  
Liberty users receiving 403 error when using SAML authentication in a JAS **cluster** environment intermittently

The messages.log may contain 
**CWOAU0062E: The OAuth service provider could not redirect the request because the redirect URI was not valid** after authenticating via SAML provider in a clustered JAS environment 

**Steps to Reproduce**  
Setup is something similar to 
IHS > liberty JAS instance (authentication is achieved for the apps using OpenIDConnectServer and samlWeb features and the authentication is done by a saml IdP)
When enabling a second clustered JAS server, users are receiving the above error intermittently after the authentication with the saml IdP
(with one cluster member, there are no issues)

**Expected behavior**  
Multiple JAS instances where OIDC authentication is propagted to saml IdP should work

**Diagnostic information:**  
 - OpenLiberty Version: [22.0.0.6]
 - Affected feature(s) [OpenIDConnectServer-1.0, samlWeb-2.0]
  - Java Version:  n/a
 - example server.xml configuration 
 `
  <server description="Jazz Authorization Server">
       
        <featureManager>
         <feature>openidConnectServer-1.0</feature>
         <feature>jdbc-4.0</feature>
        <feature>appSecurity-2.0</feature>
        <feature>ldapRegistry-3.0</feature>
        <feature>localConnector-1.0</feature>
        <feature>samlWeb-2.0</feature>
        <feature>ssl-1.0</feature>
        <feature>adminCenter-1.0</feature>
        <feature>transportSecurity-1.0</feature>
       </featureManager>

    
    <samlWebSso20
                id="defaultSP"
                spCookieName="saml_sso_cookie_idp"
                forceAuthn="false"
                spLogout="true"
                authFilterRef="samlAuthFilter"
                enabled="true">
    </samlWebSso20>

    <authFilter id="samlAuthFilter">
        <requestUrl id="samlRequestUrl" urlPattern="/authorize|/personalTokenManagement|/end_session" matchType="contains" />
                <userAgent id="samlUserAgent" agent="Mozilla|Opera|app-password-enabled" matchType="contains"/>
    </authFilter>

        <openidConnectProvider id="jazzop" oauthProviderRef="JazzOP" sessionManaged="true" />

        <oauthProvider id="JazzOP"
            httpsRequired="true"
                autoAuthorize="true"
                customLoginURL="/jazzop/form/login"
                accessTokenLifetime="7201"
                authorizationGrantLifetime="604801"
                passwordGrantRequiresAppPassword="true"
                  internalClientId="AppPasswordClient"
                internalClientSecret="xxxxxx"
                trackOAuthClients="true">
            <databaseStore dataSourceRef="OAuthFvtDataSource" />
        </oauthProvider>

    
    <application
     id="com.ibm.team.integration.jazzop"
     location="jazzop.war"
     name="com.ibm.team.integration.jazzop"
     context-root="jazzop"
     type="war">
     <application-bnd>
            <security-role name ..
            </security-role>
    </application-bnd>
     .............</application>

  </server>`
 

**Additional context**  
Enabling/setting up Session affinity would be a workaround for this issue.
In saml websso, where multiple SPs are involved and if the saml response from IdP comes back to the SP that did not originate the saml request, we end up redirecting the originial request with encoded query parameters

**Comment by mbroz2** [comment]
@arunavemulapalli please update the description using the [bug template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)

**Comment by arunavemulapalli** [comment]
done
