### ISSUE TITLE
Open Telemetry spans and baggage not correctly propagated when using asynchronous clients

### ISSUE THREAD

**Issue by benjamin-confino** [OpenLiberty/open-liberty#23572]
When a REST Client is used in a method traced by OpenTelementry trace ID information should be sent via the HTTP headers so that the traces from both the client and server can be joined up. Baggage information should also be sent via the HTTP headers so that contextual information from the first service can be included in trace messages in the second service.

Currently this works fine in normal circumstances but fails if the REST client is set up to run asynchronously. This is true for both a JAX-RS client and a microprofile rest client. 

To reproduce run io.openliberty.microprofile.telemetry.1.0.internal_fat with experimental tests enabled once #23571 is merged.

**Comment by Azquelt** [comment]
Updated title to clarify that propagation is only broken for asynchronous clients.

**Comment by Azquelt** [comment]
Removed `release bug` because I don't think we use that for function that's only in a beta release. I'll put it back later if it turns out I'm wrong.

**Comment by Azquelt** [comment]
I think we likely just need to provide a `ClientAsyncTaskWrapper` service which captures and applies the Open Telemetry `Context`.

We should be able to just use [`Context.wrap()`][wrap] to do that.

[wrap]: https://www.javadoc.io/doc/io.opentelemetry/opentelemetry-context/1.19.0/io/opentelemetry/context/Context.html
