### ISSUE TITLE
TRAS3005E error when starting InstantOn container

### ISSUE THREAD

**Issue by kgibm** [OpenLiberty/open-liberty#23606]
**Describe the bug**  

Running an InstantOn image shows the error `TRAS3005E` as the first message after starting:

```
$ podman run --rm --privileged -p 9080:9080 -p 9443:9443 -it localhost/libertydiag:instanton

[err] TRAS3005E: Failed to write messages to the /logs/messages.log file.
{"type":"liberty_message"[...]
```

However, the file `/logs/messages.log` exists in the running container and exercising a servlet that writes to `messages.log` succeeds:

```
$ curl -s -o /dev/null http://localhost:9080/servlet/Sleep
$ podman exec $(podman ps -q) tail -1 /logs/messages.log
[12/6/22, 14:05:26:316 UTC] 00000030 com.example.util.BaseServlet                                 I libertydiag: Done com.example.servlet.Sleep
```

**Steps to Reproduce**  

1. `git clone https://github.com/IBM/libertydiag`
2. `cd libertydiag`
3. `./mvnw -Dimage.build=false -Dimage.build.instanton=true clean deploy`
4. `podman run --rm --privileged -p 9080:9080 -p 9443:9443 -it localhost/libertydiag:instanton`

**Expected behavior**  

`TRAS3005E` doesn't seem accurate and errors are always concerning to see.

**Diagnostic information:**  
 - OpenLiberty Version: `FROM icr.io/appcafe/open-liberty:beta-instanton`
 - Affected feature(s): InstantOn
 - Java Version: `IBM Semeru Runtime Open Edition (17.0.5-ea+8)`
 - server.xml configuration: https://github.com/IBM/libertydiag/blob/752d02c96b493c79c023bd9cea51732a840dc764/src/main/liberty/config/server.xml
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`
[messages.log](https://github.com/OpenLiberty/open-liberty/files/10167123/messages.log)

**Additional context**  

* [Containerfile used to build the image](https://github.com/IBM/libertydiag/blob/752d02c96b493c79c023bd9cea51732a840dc764/Containerfile.instanton)
* [Maven steps to build the image](https://github.com/IBM/libertydiag/blob/752d02c96b493c79c023bd9cea51732a840dc764/pom.xml#L476-L562)

**Comment by tjwatson** [comment]
This is happening because of the logging configuration to hide messages:

```
  <logging
    traceSpecification="${TRACE_SPECIFICATION}"
    maxFileSize="${MAX_TRACE_SIZE_MB}"
    maxFiles="${MAX_TRACE_SIZE_COUNT}"
    hideMessage="CWMOT0000E"
  />
```
https://github.com/OpenLiberty/open-liberty/blob/018578fd59456f8dacb158b6064e0953ae0a444e/dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java#L387-L390

That code there is running  before we have re-established the log files for restore.  Somehow we need to delay this message on the restore side until after logging is restored.
