### ISSUE TITLE
Proposed copyright header changes for EPLv2 change

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/open-liberty#23625]
Required for the EPLv2 proposal under #23585 - Need to switch source headers to the new EPLv2 template

Existing header example: 

```
#*******************************************************************************
# Copyright (c) 2017, 2022 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#     IBM Corporation - initial API and implementation
#*******************************************************************************
```

Switching to:

```
#*******************************************************************************
# Copyright (c) 2017, 2022 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     IBM Corporation - initial API and implementation
#*******************************************************************************
```

**Comment by cbridgha** [comment]
Proposal made in reference to Eclipse recommendation here: https://www.eclipse.org/legal/epl-2.0/faq.php#h.q72cnghf29k0

**Comment by cbridgha** [comment]
Create sed scripts that do 2 replacements:

From 
`# are made available under the terms of the Eclipse Public License v1.0`
To
`# are made available under the terms of the Eclipse Public License 2.0`

AND

From 
`# http://www.eclipse.org/legal/epl-v10.html`
To
```
# https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
```

**Comment by tevans78** [comment]
Please make sure to include the eclipse Java file templates.

**Comment by cbridgha** [comment]
Java replacements:

From
 `* are made available under the terms of the Eclipse Public License v1.0`
 To 
`* are made available under the terms of the Eclipse Public License 2.0`

AND

From
`* http://www.eclipse.org/legal/epl-v10.html`
To
```
* http://www.eclipse.org/legal/epl-2.0/
* 
* SPDX-License-Identifier: EPL-2.0
```

**Comment by cbridgha** [comment]
PR: https://github.com/OpenLiberty/open-liberty/pull/23801

**Comment by cbridgha** [comment]
Merge complete - closing
