### ISSUE TITLE
Decide how mpTelemetry-1.0 should behave in the presence of the OTel agent

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#23640]
The [original design][ufo] says that `mpTelemetry-1.0` should allow the OTel instrumentation java agent to be optionally used, and that we'll make sure that using both together doesn't create duplicate spans (slides 18, 37, 45)

However, this still leaves a question:

- if the user [configures the agent not to trace something][config-components], should `mpTelemetry-1.0` still trace it?
  - on the one hand, it seems odd to trace something after the user has disabled tracing of it
  - on the other hand, maybe the user wants to see the span from `mpTelemetry-1.0` rather than the span from the agent

Complicating the matter slightly, the way we avoid double-tracing is different for our CDI integration vs. our REST integration:

- For REST integration, can we rely on the [span-suppression feature][suppression] built into the agent which avoids creating a span if another instrumentation module has already traced the event
  - This relies on instrumentation modules implementing the attribute extractors implementing `SpanKeyProvider` (an internal interface) to indicate which of the attributes they add to the span should be considered "keys" for determining whether a span has already been created for this event
  - For REST this works because we use the `HttpServerAttributesExtractor` from OpenTelemetry which implements `SpanKeyProvider`
- For `@WithSpan` on CDI beans integration, we can't rely on automatic span-suppression because `WithSpanInstrumentation` in the agent uses `CodeAttributesExtractor` and `MethodSpanAttributesExtractor`, neither of which implement `SpanKeyProvider` so there are no keys to do de-duplication
  - This does make sense. If you had a recursive method annotated with `@WithSpan`, you'd expect a new span for each recursive method call which would mean making a new span which has the same attributes as the current span.
  - Currently we disable our integration for `@WithSpan` if we detect that the agent is in use

I'm strongly of the opinion that this behaviour should be consistent for REST and for `@WithSpan` - if the user disables the relevant instrumentation in the agent, either `mpTelemetry-1.0` should instrument both or neither. This would mean either:
- The REST integration should be completely disabled when the agent is present
- The CDI `@WithSpan` integration must determine whether the agent instrumentation of `@WithSpan` is enabled or not

With the change in #23611, I chose the first option because it was simpler, but we need to decide whether that was the correct choice.

[ufo]: https://ibm.ent.box.com/file/968179787845?s=m6gabclow0ezgsar7zplpt91q5nfmhji
[config-components]: https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/#suppressing-specific-auto-instrumentation
[suppression]: https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/#instrumentation-span-suppression-behavior

**Comment by Azquelt** [comment]
@fmhwong pointed out that we should compare the spans produced by `mpTelemetry-1.0` (when the agent is present) with those produced by the agent itself to see if there's a viable reason that the user would prefer one or the other.

**Comment by Azquelt** [comment]
I've attached samples of the spans created by our `AgentTest`

This is a text representation after retrieving the spans from Jaeger

[testJaxRSClient-agent.txt](https://github.com/OpenLiberty/open-liberty/files/10219204/testJaxRSClient-agent.txt)
[testJaxRSClient-feature.txt](https://github.com/OpenLiberty/open-liberty/files/10219206/testJaxRSClient-feature.txt)
[testMPRestClient-agent.txt](https://github.com/OpenLiberty/open-liberty/files/10219207/testMPRestClient-agent.txt)
[testMPRestClient-feature.txt](https://github.com/OpenLiberty/open-liberty/files/10219208/testMPRestClient-feature.txt)
[testWithSpanBean-agent.txt](https://github.com/OpenLiberty/open-liberty/files/10219209/testWithSpanBean-agent.txt)
[testWithSpanBean-feature.txt](https://github.com/OpenLiberty/open-liberty/files/10219210/testWithSpanBean-feature.txt)

**Comment by Azquelt** [comment]
Outline of the differences

#### All cases

The agent includes additional tags on the process:
- `container.id` (should be the id of the container running the process, wrongly pulls a different id on my machine outside docker)
- `host.arch`
- `host.name`
- `os.description`
- `os.type`
- `process.command_line` (full command line for the process)
- `process.executable.path` (full path to `java` executable)
- `process.pid`
- `process.runtime.description`
- `process.runtime.name`
- `process.runtime.version`
- `telemetry.auto.version`

#### `@WithSpan` on a bean

Agent library name: `io.opentelemetry.opentelemetry-instrumentation-annotations-1.16`
Feature library name: `io.openliberty.microprofile.telemetry`

The agent includes additional tags on the span:
- `otel.library.version`
- `thread.name`
- `thread.id`
- `code.function` (the method name)
- `code.namespace` (the fully qualified class name)

#### JAX-RS server

Agent library name: `io.opentelemetry.servlet-5.0`
Feature library name: `io.openliberty.microprofile.telemetry`

The agent includes additional tags on the span:
- `otel.library.version`
- `thread.id`
- `thread.name`
- `net.host.port` (server's port)
- `net.host.name` (server hostname)
- `net.sock.host.addr` (server IP address)
- `net.sock.peer.addr` (client's address)
- `net.sock.peer.port` (client's port)
- `net.transport` (probably always ip_tcp)
- `http.flavor` (appears to be HTTP version e.g. 1.1 / 2.0)

#### JAX-RS client

Agent library name: `io.opentelemetry.apache-httpclient-4.0`
Feature library name: `Client Filter` (likely should be changed)

The agent includes additional tags on the span:
- `otel.library.version`
- `thread.name`
- `thread.id`
- `net.peer.port`
- `net.peer.name`
- `http.flavor`
- `net.transport`

#### MP Rest Client

Agent library name: `io.opentelemetry.apache-httpclient-4.0`
Feature library name: `Client filter` (likely should be changed)

The agent includes additional tags on the span:
- `otel.library.version`
- `thread.name`
- `thread.id`
- `net.peer.port`
- `net.peer.name`
- `http.flavor`
- `net.transport`

**Comment by Azquelt** [comment]
It looks like the span attribtues can be found listed in the [semantic conventions documentation](https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/) under General Attributes and Semantic conventions for HTTP spans.

There's separate documentation for [resource attributes](https://opentelemetry.io/docs/reference/specification/resource/semantic_conventions/) (which Jaeger calls process tags)

**Comment by Azquelt** [comment]
It is also worth noting that we can (and possibly should) enhance our existing integration to support some of these attributes which are currently logged by the agent and not by our feature.

**Comment by fmhwong** [comment]
If we disable the feature when the agent is present and we are not losing information, I agree with this approach.

**Comment by Azquelt** [comment]
Cool, that's what we're currently doing so there's no more work to do here.
