### ISSUE TITLE
OIDC Client Web Application cannot be assigned to virtual host other than default_host

### ISSUE THREAD

**Issue by UlrichLohrmann** [OpenLiberty/open-liberty#23749]
We use OpenID Connect and the OIDC Client Web Application. In one of our applicattions we have configured a virtual Host name other than "default_host". With this configuration, the OpenID Connect Client application cannot be accessed, a HTTP status code 404 is returned always. If we change the name of the virtual host to "default_host" everything works fine.

Is this a known limitation of the OpenID connect client Application or is there a way to configure the virtual Host the Open ID client application is connected with?

best regards
Ulrich

**Comment by teddyjtorres** [comment]
Hi @UlrichLohrmann,

If possible, please provide an example of the virtual host configuration. Please use a generic host in the example if the host name is internal or confidential.

The OpenID Connect Client does not have a virtual host. Therefore, we would like to determine which case documented in https://www.ibm.com/docs/en/was-liberty/nd?topic=liberty-using-virtual-hosts applies to your situation.

Thanks!

**Comment by UlrichLohrmann** [comment]
Hi @teddyjtorres,

Our use case from the link you provided is "Restricting access based on originating endpoint" and our virtual host configuration is

`
<virtualHost id="default_host">
    
    <hostAlias>*:9080</hostAlias>
    <hostAlias>*:9443</hostAlias>
    
    <hostAlias>*:80</hostAlias>
    <hostAlias>*:443</hostAlias>
</vrtualHost>
`

If the value of attribute "id" of <virtualHost> Element is different from "default_host" the OIDC Client web application cannot be accessed via ports of webserver, each HTTP request to /oidcclient/... results in HTTP 404.

So I would like to know whether I have to use "default_host" for the id of the <virtualHost> Element (which would not be a problem) or whether I can somehow configure the id of the virtual host configuration that has to be used for accessing oidcclient URL?

**Comment by UlrichLohrmann** [comment]
Any new activities here?

**Comment by teddyjtorres** [comment]
Hi @UlrichLohrmann,

I apologize for the delay. Since the system application for openidConnectClient does not specify a virtual host, then 

> "it is accessible by a proxied request that maps to the default virtual host"

 per https://www.openliberty.io/docs/latest/virtual-hosts.html#_isolate_applications_on_the_same_server.

Therefore, the "default_host" id should be used.

Regards,
Teddy

**Comment by UlrichLohrmann** [comment]
Hi @teddyjtorres 

thank you for clarification, that helped a lot.

Regards
Ulrich
