### ISSUE TITLE
CDI Shared Library bean visibility problems

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#23748]
**Describe the bug**  
There are a few places where we're mishandling common library Bean Deployment Archives (BDAs) which result in the following problems:

- Common lib BDAs can't see Runtime Extension BDAs (and vice-versa, if enabled for the runtime extension)
- Finding the BDA of a class in a common lib fails

**Steps to Reproduce**  
We expect that this breaks:

- Trying to inject a bean provided by a runtime extension into a bean from a shared lib
- Using `CDI.current()` from a class in a shared lib (doesn't fail until it tries to actually get the current `BeanManager`, as that requires looking up the BDA)
   - This may actually only be a problem if there's a class from a Runtime Extension on the stack and that Runtime Extension can't see the bean you're looking for as we do a stack walk and will find the Runtime Extension BDA
   - It may not fail if there's no other class in a BDA on the stack as we then fall back to the BDA of the current module which will usually work

**Expected behavior**  
The above scenarios should work.

**Diagnostic information:**  
 - OpenLiberty Version: current integration
 - Affected feature(s) `cdi-1.2`, `cdi-2.0`, `cdi-3.0`, `cdi-4.0` (beta)
 - Java Version: n/a (bug is present with any Java version)

**Additional context**  
When an application is deployed, CDI creates a Bean Deployment Archive (BDA) object for each archive within the application. The BDA object keeps track of what classes are available within that archive and which other BDAs it has visibility of. CDI Beans within a BDA must have visibility of another BDA to be able to inject or look up beans from that BDA.

For the purposes of CDI, common and private libraries should be considered part of the application.

"CDI Runtime Extensions" are CDI extensions or beans provided by another liberty feature (e.g. `mpFaultTolerance` adds a CDI runtime extension to add a CDI interceptor and process annotations using the CDI extension API). CDI creates an additional BDA for each Runtime Extension.

In general:
- All application BDAs should have visibility of other application BDAs if they can load classes from the archive of the other BDA
- All application BDAs should have have visibility of all Runtime Extension BDAs
- Some Runtime Extension BDAs should have visibility of all application BDAs (depending on the configuration of the Runtime Extension)

CDI was not considering common libraries as part of the application, causing two problems:
- the visibility rules were set up incorrectly so that common library BDAs could not see Runtime Extension BDAs (and vice-versa)
- when CDI would internally query for the BDA of a class in a common library, it would get the wrong result
  - often it would get a different application BDA and using that BDA would lead to the same result

**Fix plan:**
We need to add tests for these cases and update the code so that they work.

We think we need to:
 - change `WebSphereCDIDeploymentImpl.initializeOrderedBeanDeploymentArchives()` to include shared libs in `applicationBDAs`
 - update `WebSphereCDIDeploymentImpl.initializeInjectionServices()` to exclude shared libs

**Comment by mbroz2** [comment]
@Azquelt please update the description using the [bug template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)

**Comment by Azquelt** [comment]
@mbroz2 Updated, let me know if that's not enough / too much information.

**Comment by mbroz2** [comment]
that looks great, thanks
