### ISSUE TITLE
Update to TestNG 7.5.x

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#23781]
https://repo1.maven.org/maven2/org/testng/testng/7.7.1/

**Comment by tevans78** [comment]
I think this update is blocked by https://github.com/arquillian/arquillian-core/issues/427 which is fixed but not yet in a released version https://github.com/arquillian/arquillian-core/pull/440

**Comment by abutch3r** [comment]
TestNG 7.6.0 removed Java8 support as part of https://github.com/cbeust/testng/pull/2705 with minor code changes that prevent the use of that version, so given ongoing Liberty Java8 support, going to look at 7.5.0 which might resolve the arquillian issues and reduce the number of related changes that are required
