### ISSUE TITLE
Review CDI 4.0 docs

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#23837]
https://github.com/OpenLiberty/docs/issues/5754#issuecomment-1277930970

Note that links to the CDI 4.0 feature page and the cdi configuration element will not resolve until we have the autogenerated doc update, sometime after GM. All links will be checked after that doc is added and before this issue is closed.

If any further changes are needed just let David Mueller know. If not, you can add the Technical reviewed label to the issue and the changes will publish when the feature GAs.

**Comment by benjamin-confino** [comment]
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#cdi

`In CDI 4.0, a new Handle API is available to simplify programmatic inspection of bean metadata. This API avoids the need to create instances before they are required. You can obtain a Handle instance by using the Instance API, as shown in the following example.`

The following API example does not show obtaining a Handle instance from the Instnace API. Either the paragraph above or the example code needs to change to align with the other.

-------

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/cdi-beans.html

```
In CDI 3.0 and earlier, the presence of an empty beans.xml file or a beans.xml file with the bean-discovery-mode="all" attribute makes all of the potential objects CDI beans. Otherwise, only objects with CDI bean-defining annotations are CDI beans.

In CDI 4.0 and later, the presence an empty beans.xml file causes an archive to be treated as an implicit bean archive, the equivalent of setting the bean-discovery-mode="annotated" attribute. Only objects with CDI bean-defining annotations are CDI beans. If necessary, you can set the [cdi](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/cdi.html)emptyBeansXmlCDI3Compatibility attribute to enable compatibility with previous versions. Setting this attribute to true in CDI 4.0 causes an empty beans.xml file to be treated as an explicit beans archive.

Also in CDI 4.0 and later, a beans.xml file that does not specify a version attribute defaults to the bean-discovery-mode="annotated" attribute behavior. Therefore, by default, only objects with CDI bean-defining annotations are discovered as CDI beans. However, always properly specify a version for all beans.xml files, as shown in the previous example.
```
This uses inconsistent terminology. For example it's random if it mentions `bean-discovery-mode=` next to a configuration option. I suggest something like this to ensure full coverage and also to standardize the ordering and presentation of information.

In all version of CDI an archive can be an implicit bean archive, an explicit bean archive, nor not a bean archive:
* In an implicit bean archive only objects with CDI bean-defining annotations are CDI beans.
* In an explicit cdi archive all objects are CDI beans. Objects without a bean defining annotation are `@Dependent` scoped.
* If an archive is not a bean archive then no objects are CDI beans.

In CDI 3.0 and earlier:
* An archive with no beans.xml file is an implicit bean archive.
    * If the property `cdi12 enableImplicitBeanArchives="false"` is set an archive with no beans.xml file is not a bean archive.
* An archive with an empty beans.xml file is an explicit bean archive.
* An archive with a beans.xml file with the attribute bean-discovery-mode="all" is an explicit bean archive.
* An archive with a beans.xml file with the attribute bean-discovery-mode="annotated" is an implicit bean archive.
* An archive with a beans.xml file with the attribute bean-discovery-mode="none" is not a bean archive.

In CDI 4.0 and later:

* An archive with no beans.xml file is an implicit bean archive.
    * If the property `cdi12 enableImplicitBeanArchives="false"` is set an archive with no beans.xml file is not a bean archive.
* An archive with an empty beans.xml file is an implicit bean archive.
    * If the property [`cdi emptyBeansXmlCDI3Compatibility="true"`](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/cdi.html) is set to true an archive  with an empty beans.xml file is an explicit bean archive.
* An archive with a beans.xml file with the attribute bean-discovery-mode="all" is an explicit bean archive.
* An archive with a beans.xml file with the attribute bean-discovery-mode="annotated" is an implicit bean archive.
* An archive with a beans.xml file with the attribute bean-discovery-mode="none" is not a bean archive.

Note: If a beans.xml file has the `version` attribute, it will use the rules for the CDI version specified by that attribute. If not it will default to the version of CDI in use. You should always set a version attribute in a beans.xml file.

**Comment by tevans78** [comment]
Marked https://github.com/OpenLiberty/docs/issues/5754 as reviewed so this issue can be closed.
