### ISSUE TITLE
Default keystore file not getting detected on file monitoring

### ISSUE THREAD

**Issue by acdemyers** [OpenLiberty/open-liberty#23883]
**Describe the bug**  
The default SSLContext is not always getting reset with ssl-1.0 feature is used and a keystore changes.

**Steps to Reproduce**  
Enable file monitoring on the keystore that is used by the default SSL configuration.   Then modify the keystore expecting the sslContext to get updo on the process.

**Expected behavior**  
The process default SSL contest should get updated if the file monitor detects a change in the keystore used by the default SSL configuration.

**Diagnostic information:**  
 - OpenLiberty Version: any
 - Affected feature(s): ssl-1.0
 - Java Version: n/a
 
**Additional context**

**Comment by acdemyers** [comment]
Change has been merged.

**Comment by mbroz2** [comment]
@acdemyers please update the description using the [bug template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)

**Comment by acdemyers** [comment]
**Describe the bug**  
The default SSLContext is not always getting reset with ssl-1.0 feature is used and a keystore changes.

**Steps to Reproduce**  
Enable file monitoring on the keystore that is used by the default SSL configuration.   Then modify the keystore expecting the sslContext to get updo on the process.

**Expected behavior**  
The process default SSL contest should get updated if the file monitor detects a change in the keystore used by the default SSL configuration.

**Diagnostic information:**  
 - OpenLiberty Version: any
 - Affected feature(s): ssl-1.0
 - Java Version: n/a
 -
**Additional context**
