### ISSUE TITLE
Set GlobalOpenTelemetry

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#23923]
If a global `OpenTelemetry` instance is not set then `GlobalOpenTelemetry.get()` attempts to create and configure one automatically.

https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java#L69-L87

Since we may have multiple apps running which may have different configurations, we don't really have the concept of a single static `OpenTelemetry` object.

We can either:

- ensure that we set the global instance to a no-op implementation, so that it does nothing
- write an implementation of `OpenTelemetry` which, on every method call, looks up the correct `OpenTelemetry` instance for the current application and delegates the method call to it. We could then set that as the "global" instance.

**Comment by fmhwong** [comment]
This [warning](https://github.com/open-telemetry/opentelemetry-java/blob/8897dd4d5c635a667cfafc17ee595bbd08df2819/api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java#L33-L36) in the javadoc does not recommend using `GlobalOpenTelemetry` so I think we can set the global instance to a no-op implementation as @tevans78 suggested above.

**Comment by fmhwong** [comment]
Will the agent set the `OpenTelemetry` instance when it is present?

**Comment by Azquelt** [comment]
Yes, the agent does set `GlobalOpenTelemetry` when it is present. This is possible because the agent creates one `OpenTelemetry` instance for the whole server whereas our feature has to create one per application deployed as the configuration can be different per application.

**Comment by Azquelt** [comment]
If we go with the no-op implementation, we should probably output a warning in case the user does use it and wonders why it doesn't work.
