### ISSUE TITLE
ExpirationTimer can cause deadlocks in proxy mode

### ISSUE THREAD

**Issue by TiborBeres** [OpenLiberty/open-liberty#23938]
Expiration timer triggering proxy branch invalidation can cause deadlocks when sipcontainer is acting as a proxy.

**Comment by mbroz2** [comment]
@TiborBeres please update the description of this `release bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
