### ISSUE TITLE
FTS for EPLv2 update

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/open-liberty#23948]
## Test Strategy

For the most part MVT testing for the EPLv2 change in manual - I have verified with Jeff Mierzejewski (from SVT)
that OL license changes are verified via a diff change from previous release. - and he is aware of this change.

I will be manually verifying the EPL license is properly applied by inspecting all package zips (for license file)
Looking at the wlp/LICENSE file to be "Eclipse Public License - v 2.0"

The one automated test that is part of the build has been changed to reflect the epl2 changes...

The PR containing these changes is here:  https://github.ibm.com/websphere/WS-CD-Open/pull/28517/files

### List of FAT projects affected

None

## Confidence Level

Confidence is high on Liberty reporting / containing the proper license in our deliverables - 5

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by ayoho** [comment]
LGTM 👍
