### ISSUE TITLE
MicroProfile TCKs: Stabilize the wlp arquillian container jar in artifactory before GA

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#2394]
The container in use by all of the MP TCK buckets is here:
https://na.artifactory.swg-devops.com/artifactory/webapp/#/artifacts/browse/tree/General/wasliberty-open-liberty/com/ibm/ws/org/jboss/arquillian/container/arquillian-wlp-managed-8.5/1.0.0.Final-SNAPSHOT/arquillian-wlp-managed-8.5-1.0.0.Final-20180222.145920-3.jar

However, we should not use `-SNAPSHOT` for a GA release. So, the jar should be copied to a new fixed set of maven co-ords (check with Gordon what that should be) and the TCKs updated to point specifically at that version.

Note that a) this includes all MP TCKs, not just config and FT; and b) I expect this change will have to be made in the pre-GA clone branch. We might be able to leave it as-is in the development branches since I hope we will have moved to the up-stream version from maven central by the time we get to 18.0.0.2.

The same jar should also be uploaded to DHE so that the TCK buckets can be run outside of IBM. I'm not 100% sure who has access to do that??

**Comment by Azquelt** [comment]
Hmm, it's interesting that you see so many SNAPSHOT versioned jars. When I run the mpConfig TCK FAT project, I only get the arquillian-managed-wlp-8.5 and arquillian-parent-was SNAPSHOT jars.
