### ISSUE TITLE
Serviceability - Update MustGather docs for EE10 web-tier components.

### ISSUE THREAD

**Issue by pmd1nh** [OpenLiberty/open-liberty#23966]
This issue is tracking the changes to service MustGather document for EE10 web tier components (i.e servlet, pages, faces, websocket etc.)

**Servlet**: 
Update http://www-01.ibm.com/support/docview.wss?uid=swg21384592​
to contain new webcontainer trace specification for servlet-6.0 : `io.openliberty.webcontainer*=all`

**Pages**

**Faces**
Update https://www.ibm.com/support/pages/node/476701 to contain the new Faces trace specification for faces-4.0: `io.openliberty.faces*=all`

**WebSocket**

**Comment by krishnaj69** [comment]
@pmd1nh Sent document id 626051 for review

**Comment by pmd1nh** [comment]
Reviewed 
https://supportcontent.ibm.com/support/pages/node/626051/edit

and verified that new servlet 6.0 trace specification is updated in the MustGather.

```
Note: When using Jakarta EE 10 feature or servlet-6.0 feature with Liberty use below <logging> element

<logging traceSpecification="io.openliberty.webcontainer*=all:com.ibm.ws.webcontainer*=all:com.ibm.wsspi.webcontainer*=all:HTTPChannel=all:GenericBNF=all:HTTPDispatcher=all" traceFileName="trace.log" maxFileSize="100" maxFiles="10" traceFormat="BASIC" />
```

**Comment by krishnaj69** [comment]
Completed publish for
MustGather: Web container problems in WebSphere Application Server and WebSphere Liberty
 https://www.ibm.com/support/pages/node/626051

**Comment by krishnaj69** [comment]
I have updated mustgather docs @pmd1nh 
https://supportcontent.ibm.com/support/pages/node/476701/edit

Servlet Engine/Web Container

Note: When using Jakarta EE 10 feature or servlet-6.0 feature with Liberty use below trace string
io.openliberty.webcontainer*=all:com.ibm.ws.webcontainer*=all:com.ibm.wsspi.webcontainer*=all:HTTPChannel=all:GenericBNF=all:HTTPDispatcher=all

JSF

Note: When using faces-4.0 feature with Liberty use below trace string
com.ibm.ws.jsf*=all:org.apache.myfaces*=all:com.ibm.ws.webcontainer*=all:com.ibm.ws.jsp=all:io.openliberty.faces*=all

**Comment by pmd1nh** [comment]
looks good to me. Let me know when the publish is completed and we can close this out. Thanks! @krishnaj69

**Comment by pmd1nh** [comment]
There is no new string from Pages and WebSocket.  Close out this issue
