### ISSUE TITLE
Add option to support old format of start-info in multipart/related SOAP messages

### ISSUE THREAD

**Issue by sawadood** [OpenLiberty/open-liberty#23976]
In Liberty versions prior to 22.0.0.8, the start-info in multipart-related was formatted as follows:
           start-info="application/soap+xml"; action="sendAttachment"
In new Liberty versions, the start-info attribute is formatted as follows:
           start-info="application/soap+xml; action=\"sendAttachment\""

Some existing Web services applications that rely on the old format of start-info are failing with exceptions like this:
javax.xml.ws.soap.SOAPFaultException: The given SOAPAction \"sendAttachment\"" does not match an operation.

Need an option to support old format of start-info attribute in multipart/related SOAP messages.

**Comment by mbroz2** [comment]
@sawadood please update the description of this `release bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=).  Particularly, include how to enable the old format.
