### ISSUE TITLE
Possible performance issue in com.ibm.ws.wsat.service.impl.WebClientImpl

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#24048]
**Describe the bug**  
See issue #24047 for details

The following code seems to generate a large amount of overhead to keep creating and destroying the TCCL for the WebClientImpl class:
https://github.com/OpenLiberty/open-liberty/blob/14225e8f48a9040e72e0128f63ecd28de4f57f0f/dev/com.ibm.ws.wsat.common/src/com/ibm/ws/wsat/service/impl/WebClientImpl.java#L214-L235

It keeps calling `tranService.getThreadClassLoader(WebClientImpl.class);` and  `tranService.destroyThreadClassLoader(localLoader);` each call to invoke.

It would be far better to only call `tranService.getThreadClassLoader(WebClientImpl.class);` and `tranService.destroyThreadClassLoader(localLoader);` when the component is deactivated (or shutdown).

**Comment by jhanders34** [comment]
FYI @jonhawkes and @neuwerk

**Comment by tjwatson** [comment]
PR #24105 fixes this ... closing.
