### ISSUE TITLE
Aborted managed connections invoking endRequest and end are causing problems in JDBC driver code

### ISSUE THREAD

**Issue by nmittles** [OpenLiberty/open-liberty#24092]
Aborted managed connections are invoking Connection.endRequest() and XAResource.end(), which is causing problems in some JDBC drivers.

**Comment by nmittles** [comment]
#build

**Comment by mbroz2** [comment]
@nmittles please update the description of this `release bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
