### ISSUE TITLE
Is it possible to monitor the datasource PreparedStatement cache in Liberty?

### ISSUE THREAD

**Issue by NiallWard** [OpenLiberty/open-liberty#24112]
Hi

Is there any way to monitor the behaviours of the PreparedStatement cache on a datasource in Liberty (eg % full, #misses etc )? I can't immediately see anything when using mpMetrics 2.3 or JMX exporter to export metrics to Prometheus

**Comment by frowe** [comment]
no, there are no metrics related to cache hits/misses

**Comment by mbroz2** [comment]
@NiallWard if this is something you'd like to see added to Open Liberty, consider opening a [Feature Request](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=)

**Comment by KyleAure** [comment]
Closing since a feature request has been opened: https://github.com/OpenLiberty/open-liberty/issues/24142
