### ISSUE TITLE
Pages static imports en masse

### ISSUE THREAD

**Issue by isaacrivriv** [OpenLiberty/open-liberty#24182]
Follow up on comment about importing static en masse
https://github.com/OpenLiberty/open-liberty/blob/6abb8d5d951b5943b200c6d9e493c81141567e70/dev/io.openliberty.pages.3.1.internal.factories/src/org/apache/jasper/runtime/PageContextImpl.java#L855-L858

After implementing static imports for EL expressions in Pages 3.1 with #24015, we discovered that there are issues when trying to import en masse. Reading through the API we saw that [importStatic](https://jakarta.ee/specifications/expression-language/5.0/apidocs/jakarta.el/jakarta/el/importhandler#importStatic(java.lang.String)) is limited to a single method to be added. We may need to open a spec issue for this, couldn't find anything specific about importing static fields/methods en masse for this https://jakarta.ee/specifications/expression-language/5.0/jakarta-expression-language-spec-5.0.html#imports-of-packages-classes-and-static-fields

**Comment by volosied** [comment]
Closing -- see reason here: https://github.com/OpenLiberty/open-liberty/issues/25135#issuecomment-1736074154
