### ISSUE TITLE
Ensure mpOpenAPI-1.0 produces reasonable amount of logs

### ISSUE THREAD

**Issue by navidsh** [OpenLiberty/open-liberty#2420]
Go over `mpOpenAPI-1.0` produce reasonable amount of logs when the trace specification is set to `debug`.

In particular, make sure entering into/exiting from methods are now producing too much logs. If that is the case, turn off `instrumentation` for the trouble making packages/classes.

**Comment by mrglavas** [comment]
Determined that this is no longer an issue for mpOpenAPI-1.0. Closing.
