### ISSUE TITLE
monitor-1.0 returns strange values for standard deviation

### ISSUE THREAD

**Issue by gezielt** [OpenLiberty/open-liberty#24223]
The standard deviation coming from the Liberty MBean does look odd though. Even if the total execution count does not change, the ServletStats MBean returns slightly different values for standard deviation. It could be because a single pass algorithm is used to calculate the variance (rather than calculating the mean first and then another pass to accumulate the deltas from the mean). But jast wanted to clarify if there are any plans to make this mbean work more predictable? 

**Steps to Reproduce**  
We used Jconsole and our custom javaagent to see an output for the WebSphere:type=ServletStats,name=*  MXBean and in both places we see the same, here are some logs from our java agent:
=========== Begin ================                            
 requestCount: 5                                      
 maxValue: 335544                                     
 minValue: 4828                                       
 responseTime: 73291                                  
 standardDeviation: 127248                            
 ============ End =================                   
 =========== Begin ================                         
 requestCount: 5                                      
 maxValue: 335544                                     
 minValue: 4828                                       
 responseTime: 73291                                  
 standardDeviation: 111454                            
 ============ End =================                   
 =========== Begin ================                                 
 requestCount: 5                                      
 maxValue: 335544                                     
 minValue: 4828                                       
 responseTime: 73291                                  
 standardDeviation: 121192                            
 ============ End =================                   
 =========== Begin ================                        
 requestCount: 5                                      
 maxValue: 335544                                     
 minValue: 4828                                       
 responseTime: 73291                                  
 standardDeviation: 127238                            
 ============ End =================                   
 =========== Begin ================                          
 requestCount: 5                                      
 maxValue: 335544                                     
 minValue: 4828                                       
 responseTime: 73291                                  
 standardDeviation: 111466                            
 ============ End =================

Request count is the same but the standardDeviation is different each time

**Expected behavior**  
standardDeviation should be constant for the same amount of requests

**Diagnostic information:**  
 - Affected feature(s) [ monitor-1.0]

**Additional context**

**Comment by tonyreigns** [comment]
A fix has been merged and will be available in the upcoming 23.0.0.3 release.
