### ISSUE TITLE
Test mpTelemetry with/without concurrent-3.0

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#24225]
The async functionality in restfulWS-3.1 works slightly differently when concurrent-3.0 is enabled and this has caused bugs.

Ensure we are testing both configurations, particularly JAX-RS and MP Rest Client async functionality.

**Comment by benjamin-confino** [comment]
PR: https://github.com/OpenLiberty/open-liberty/pull/24749
