### ISSUE TITLE
Investigate why the MP Telemetry 1.0 TCK needs resteasy

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#24224]
The original tck pom.xml only includes the MP Rest Client API jar. Our version appears to need an implementation as well (resteasy). Would be nice to understand why and remove that dependency if possible as it brings a few other things with it as well.

https://github.com/OpenLiberty/open-liberty/blob/af62a3ce5541bffcf0d99eac00306adf6b1b64a5/dev/io.openliberty.microprofile.telemetry.1.0.internal_fat_tck/publish/tckRunner/tck/pom.xml#L91

**Comment by benjamin-confino** [comment]
When I removed that I got: java.lang.ClassNotFoundException: Provider for jakarta.ws.rs.client.ClientBuilder cannot be found.

I see that the tck does call ClientBuilder.newClient() in https://github.com/eclipse/microprofile-telemetry/blob/main/tracing/tck/src/main/java/org/eclipse/microprofile/telemetry/tracing/tck/TestApplication.java

I think what is happening is that upstream's pom is the compile time dependencies, where as a resteasy impl is a runtime dependency. Our pom needs to cover both compile and runtime dependencies.
