### ISSUE TITLE
SVT:  Unknown response type when invoking operations on UI using MS Edge browser

### ISSUE THREAD

**Issue by tam512** [OpenLiberty/open-liberty#2423]
- Test API UI /openapi/ui using Microsoft Edge on Windows 10 Enterprise 
- OL build is wlp-1.0.20.20180223-1037
- When invoke GET, I see that the response code is 200 but it for "Unknown response type" as in the following screen capture:
![image](https://user-images.githubusercontent.com/22480038/36687838-4edca724-1af0-11e8-8d4e-5620acf66fc2.png)

- The response content works fine on Firefox, Chrome and Internet Explorer as following:
![image](https://user-images.githubusercontent.com/22480038/36687912-818c2fc8-1af0-11e8-90fe-3190bc516b94.png)

**Comment by mrglavas** [comment]
@arturdzm is investigating. It's likely a problem with the browser. If we determine that it's a bug in MS Edge we would document it as a limitation if there's no sensible workaround.

**Comment by mrglavas** [comment]
@arturdzm Check whether this is still an issue after the UI resynchronization.

**Comment by mrglavas** [comment]
@arturdzm Is this still an issue after you updated to the latest UI?

**Comment by arturdzm** [comment]
I am suspecting issue with the app, first it shows 2 different endpoints (working case has /v2 in path
and 2nd thing is that in non working case (Edge) response headers do not set Content-Type header which is probably why its not working

**Comment by tam512** [comment]
- Re-open this defect since I still have problems running operations with MS Edge using build 20180530-0500.33   and I run them ok on Chrome.
-  I probably ran 2 different endpoints from the screen captures above since there are 4 different endpoints for Weather API
- Now I see different error when running GET on Weather API
``
Invariant Violation: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Blob%5D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
``
- Re-paste the screen shots with the same endpoints on the current build
- Run on MS Edge
![image](https://user-images.githubusercontent.com/22480038/40747787-fda607e2-6423-11e8-8203-7d6367cae111.png)

- run on Chrome
![image](https://user-images.githubusercontent.com/22480038/40747427-e5125f06-6422-11e8-901a-5a7337f814cc.png)

**Comment by tam512** [comment]
I did windows update to the Widnows10 machine to bring the MS Edge browser to latest version of browser 
```
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134
```
and I could run all API operations now.
close this issue
