### ISSUE TITLE
Ref handling for array schema

### ISSUE THREAD

**Issue by arturdzm** [OpenLiberty/open-liberty#2425]
Right now there is no way to create array schema with items as a reference:

Handle `@Schema(type=ARRAY, ref="User")` as:

```
type: array
items:
 $ref: "#/components/schemas/User"
```

**Comment by mrglavas** [comment]
@arturdzm Can you take another look at this? Fix or close?

**Comment by arturdzm** [comment]
Close for now, can use `@Schema(type=ARRAY, implementation=User.class)` for now
