### ISSUE TITLE
Jakarta EE10:Resource injections are null in one of my WebSocket server endpoint class

### ISSUE THREAD

**Issue by jagraj** [OpenLiberty/open-liberty#24256]
I am trying to inject resources with "@Resource" annotation  in my WebSocket server endpoint class and I am getting following NullPointerException. I am also attaching traces that I collected with the following trace spec "*=info:HTTPChannel=all:Injection=all:TCPChannel=all:com.ibm.ws.jsf*=all:com.ibm.ws.webcontainer*=all:com.ibm.ws.webcontainer31*=all:com.ibm.wsspi.webcontainer*=all:org.apache.myfaces*=all:websockets=all".
[ResourceInjections-NPE.zip](https://github.com/OpenLiberty/open-liberty/files/10711164/ResourceInjections-NPE.zip)

![image](https://user-images.githubusercontent.com/713849/218197096-27aeb40f-8ba8-4244-8990-3b41ff39b89c.png)

```
[err] java.lang.NullPointerException: Cannot invoke "com.ibm.wsspi.webservices.persona.api.WASPersonaWebServicesPMIService.getJAXWSMetricsFromHandler()" because "this.personaWebServicesPMIService" is null
[err] 	at com.ibm.websphere.persona.pmi.websockets.PersonaWebServicesPMIWebSocketEndpoint.sendAll(PersonaWebServicesPMIWebSocketEndpoint.java:250)
[err] 	at com.ibm.websphere.persona.pmi.websockets.PersonaWebServicesPMIWebSocketEndpoint.onOpen(PersonaWebServicesPMIWebSocketEndpoint.java:77)
[err] 	at jdk.internal.reflect.GeneratedMethodAccessor454.invoke(Unknown Source)
[err] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[err] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[err] 	at com.ibm.ws.wsoc.AnnotatedEndpoint.onOpen(AnnotatedEndpoint.java:187)
[err] 	at [internal classes]
[err] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[err] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[err] 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by tkburroughs** [comment]
Injection is failing due to the following error:

[2/10/23, 15:36:14:082 EST] 00000026 id=00000000 njectionengine.osgi.internal.IndirectJndiLookupObjectFactory 3 service object com.ibm.wsspi.webservices.persona.handler.WASPersonaWebServicesHandler@19f23885 does not implement com.ibm.wsspi.webservices.persona.api.WASPersonaWebServicesPMIService

InjectionEngine was able to locate the OSGi service for the user feature, but the API class from the application does not match the API class from the service.

**Comment by tkburroughs** [comment]
@jaridk Any thoughts on what might cause the user feature API to be loaded from both the APP and user feature?

**Comment by tkburroughs** [comment]
@jagraj Can you verify that the feature exports the user feature API class as API (see https://www.ibm.com/docs/en/was-liberty/base?topic=liberty-developing-feature-manually)... and that the application does NOT use  parent-last for classloading.

**Comment by jagraj** [comment]
@tkburroughs : I did compare with my Jakarta EE9 user feature which is built from eclipse OSGI tools and I found out that following entry is missing in my feature bundle. 

```
IBM-API-Package: com.ibm.wsspi.webservices.persona.api,
 com.ibm.wsspi.webservices.persona.handler

```

Now, I am not getting NPE. I am not getting any data in my WebSocket server endpoint. Here are the latest logs with the traces.

[LatestLogs-02132023.zip](https://github.com/OpenLiberty/open-liberty/files/10725962/LatestLogs-02132023.zip)

**Comment by tkburroughs** [comment]
@jagraj The traces show the previous error does not occur.  It appears all injection is now successful.  What exactly does it mean to say that you are not "getting any data in my WebSocket"?  You may need to contact someone familiar with WebSockets.

**Comment by jagraj** [comment]
After adding global webservices feature as a dependency feature then all my transactions working. Here is my SUBSYSTEM.MF file from my liberty user feature. Thanks for all your help in debugging this injection problem.

```
Subsystem-ManifestVersion: 1
Subsystem-SymbolicName: WASPersonaWebServicesHandlerFeature;visibility:=public
Subsystem-Version: 1.0.0.SNAPSHOT
Subsystem-Name: WASPersonaWebServicesHandlerFeature
Subsystem-Description: WASdev Top Parent POM.
Subsystem-Content: com.ibm.ws.svt.gs.garagesale-ee10.WASPersonaWebServicesHandler;version="[1.0.0,1.0.0]",
 io.openliberty.globalhandler-1.0; type="osgi.subsystem.feature"
IBM-API-Package: com.ibm.wsspi.webservices.persona.api,
 com.ibm.wsspi.webservices.persona.handler
IBM-Feature-Version: 2
IBM-ShortName: WASPersonaWebServicesHandlerFeature
Subsystem-Type: osgi.subsystem.feature
Subsystem-Vendor: IBM
```
