### ISSUE TITLE
aud missing in the response from the token endpoint should result in 401

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#24310]
If the token endpoint returns tokens without the "aud" claim, we should get a 401.  We're not, we're getting access to the protected app.

Test is TokenValidationTests_audMissing_jwt
[audMissing.zip](https://github.com/OpenLiberty/open-liberty/files/10744397/audMissing.zip)

**Comment by ayoho** [comment]
Should be resolved by https://github.com/OpenLiberty/open-liberty/pull/24314.

**Comment by c00crane** [comment]
Tests are now getting a 401.
