### ISSUE TITLE
XML Web Services 4.0 Feature Test Summary

### ISSUE THREAD

**Issue by neuwerk** [OpenLiberty/open-liberty#24316]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

In most ways functionality hasn't changed between EE9 for xmlWS-4.0 and add on features wsAtomicTransaction-1.2/wsSecurity-1.1. We are repeating all tests used in EE9 for EE10, and where functionality has changed we have added projects and made changes to reflect the changes in our existing projects. 

### List of FAT projects affected

_While not owned by our team, I'm including this as it provides coverage for our configuration integration in the ibm-ws-bnd.xml/server.xml_

com.ibm.ws.javaee.dd.model_fat

**XML WS 4.0 FAT Projects**

com.ibm.ws.jaxws.2.2.webcontainer_fat_extended
com.ibm.ws.jaxws.cdi_fat
com.ibm.ws.jaxws.clientcontainer_fat
com.ibm.ws.jaxws.ejb_fat
com.ibm.ws.jaxws.X.wsat_fat
Io.openliberty.xmlws.4.0.internal_fat
io.openliberty.ws.jaxws.tools_fat
io.openliberty.ws.jaxws.global.handler.internal_fat
io.openliberty.jaxws.security_fat

**XML WS 4.0 and WS-Security 1.1**

com.ibm.ws.wssecurity_fat.wsscxf.1
com.ibm.ws.wssecurity_fat.wsscxf.2
com.ibm.ws.wssecurity_fat.wsscxf.3
com.ibm.ws.wssecurity_fat.wsscxf.saml.1
com.ibm.ws.wssecurity_fat.wsscxf.saml.2
com.ibm.ws.wssecurity_fat.wsscxf.saml.3
com.ibm.ws.wssecurity_fat.wsscxf.saml.4
com.ibm.ws.wssecurity_fat.wsscxf.saml.5
com.ibm.ws.wssecurity_fat.wsscxf.saml.6

**XML WS 4.0 and WS-AtomicTransactions 1.2**

com.ibm.ws.wsat.common_fat
com.ibm.ws.wsat.concurrent_fat
com.ibm.ws.wsat_fat.assertion
com.ibm.ws.wsat_fat.db
com.ibm.ws.wsat_fat.db_optional
com.ibm.ws.wsat_fat.dbs
com.ibm.ws.wsat_fat.dbs_optional
com.ibm.ws.wsat_fat.multi
com.ibm.ws.wsat_fat.ssl
com.ibm.ws.wsat.migration_fat.1
com.ibm.ws.wsat.migration_fat.2
com.ibm.ws.wsat.migration_fat.3
com.ibm.ws.wsat.migration_fat.4
com.ibm.ws.wsat.migration_fat.5
com.ibm.ws.wsat.recovery_fat.lps
com.ibm.ws.wsat.recovery_fat.multi.1
com.ibm.ws.wsat.recovery_fat.multi.2
com.ibm.ws.wsat.recovery_fat.multi.3
com.ibm.ws.wsat.recovery_fat.multi.4
com.ibm.ws.wsat.recovery_fat.single.1
com.ibm.ws.wsat.recovery_fat.single.2

### Test strategy

* What functionality is new or modified by this feature?

For the XML WS 4.0 specification updates, we added provider lookup tests in this new project: 

`io.openliberty.xmlws.4.0.internal_fat`. The other major change we made was to remove xmlWS-4.0 and restfulWS-3.1 hard dependency on the global handler spi, so we've updated the `io.openliberty.ws.jaxws.global.handler.internal_fat` to handle the needed changes.

Lastly, we've migrated `io.openliberty.jaxws.security_fat` bucket from WS-CD-Open and added a new repeat for that bucket to run with EE10. 

* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)

The `io.openliberty.xmlws40.fat.ProviderLookup` test was added that does positive and negative tests that verify that the runtime can inject (or not) a web service client with a given ProviderImpl. This allows us to test the changes to how the specification API does its Provider implementation look up. 

The `io.openliberty.ws.jaxws.global.handler.internal_fat` has been modified for it's EE10 to repeat all existing tests with new "user" feature files that have the required `io.openliberty.globalhandler-1.0` protected feature added to the  `Subsystem-Content` of the feature files. 

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

N/A

## Confidence Level

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

4

**Comment by ayoho** [comment]
LGTM 👍
