### ISSUE TITLE
FFDC Incident

### ISSUE THREAD

**Issue by avri-log-on** [OpenLiberty/open-liberty#24321]
I have installed Open Liberty  Red Hat Enterprise Linux 8.6 running as a guest under z/VM 7.1.
The HTTPS access results in browser error. messages.log contains the following:
com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.lang.IllegalArgumentException: Current mode settings do not allow the use of CipherSuite TLS_AES_256_GCM_SHA384 com.ibm.ws.channel.ssl.internal.SSLConnectionLink 238" at ffdc_23.02.14_14.22.49.0.log
 
messages.log also contains 21 warnings in the form of:
com.ibm.ws.security.csiv2.config.ssl.SSLConfig               W CWWKS9590W: The TLS_EMPTY_RENEGOTIATION_INFO_SCSV requested cipher suite appears to have [] association options that do not match the specified [integrity, confidentiality, establishTrustInTarget, noexport, tls] supported options and the [integrity, confidentiality] required options.
The issue does not occur on other sites.

**Diagnostic information:**  
 - OpenLiberty Version: 20.0.0.12 (wlp-1.0.47.cl201220201111-0736)
 - Java Version: java version "1.8.0_351"
Java(TM) SE Runtime Environment (build 8.0.7.20 - pxz6480sr7fp20-20221020_01(SR7 FP20))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux s390x-64-Bit Compressed References 20220929_37824 (JIT enabled, AOT enabled)
OpenJ9   - 02180fe
OMR      - 48fc32a
IBM      - bf759bf)
JCL - 20220922_01 based on Oracle jdk8u351-b10

 - server.xml - attached
 - messages.log - attached

[ffdc_23.02.14_14.22.49.0.log](https://github.com/OpenLiberty/open-liberty/files/10746772/ffdc_23.02.14_14.22.49.0.log)
[messages.log](https://github.com/OpenLiberty/open-liberty/files/10746773/messages.log)
[liberty-bootstrap.properties.txt](https://github.com/OpenLiberty/open-liberty/files/10746808/liberty-bootstrap.properties.txt)
[server.xml.txt](https://github.com/OpenLiberty/open-liberty/files/10746809/server.xml.txt)

**Comment by acdemyers** [comment]
The ffdc error is what is preventing the https port from being used.   TLSv1.3 must be disabled, I'm thinking at the JDK.  We are attempting to set a TLSv1.3 cipher along with others on the https port.  You can probably get around this by adding a custom cipher list to your ssl configuration.   You can add a space separated list of ciphers to the enabledCiphers attribute and put it in your ssl element.  

I'm looking into a way to fix this.

**Comment by arkarkala** [comment]
@avri-log-on , can you elaborate about this working on other sites?  What are the differences if any (OS, JDK, config etc)?

**Comment by avri-log-on** [comment]
Other sites have the same versions of Red Hat, z/VM and JDK. However, all sites belong to different organizations, and may have been hardened in different ways. The people responsible for security are not prepared to share the exact mechanisms deployed.

We have compared server.xml and java.security, and there were no differences. What other configurations should be checked?

**Comment by avri-log-on** [comment]
I have mistakenly uploaded a wrong server.xml. The relevant items, AFAIK, are:
      
      <sslDefault sslRef="noSipersSSLSettings" />
      <ssl id="noSipersSSLSettings" keyStoreRef="defaultKeyStore"
            sslProtocol="${wave.liberty.ssl.protocol}"
            enabledCiphers="${wave.liberty.ssl.enabledCiphers}"
            clientAuthenticationSupported="true" />


The variables are defined in bootstrap.properties:
wave.liberty.ssl.protocol=TLSv1.2
wave.liberty.ssl.enabledCiphers=\
                                SSL_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 \
                                SSL_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 \
                                SSL_ECDHE_RSA_WITH_AES_256_GCM_SHA384 \
                                SSL_ECDHE_RSA_WITH_AES_128_GCM_SHA256 \
                                SSL_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 \
                                SSL_ECDHE_RSA_WITH_AES_256_CBC_SHA384 \
                                SSL_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 \
                                SSL_ECDHE_RSA_WITH_AES_128_CBC_SHA256 \
                                SSL_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 \
                                SSL_ECDH_RSA_WITH_AES_256_GCM_SHA384 \
                                SSL_ECDH_ECDSA_WITH_AES_128_GCM_SHA256 \
                                SSL_ECDH_RSA_WITH_AES_128_GCM_SHA256 \
                                SSL_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 \
                                SSL_ECDH_RSA_WITH_AES_256_CBC_SHA384 \
                                SSL_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 \
                                SSL_ECDH_RSA_WITH_AES_128_CBC_SHA256 \
                                SSL_RSA_WITH_AES_256_GCM_SHA384 \
                                SSL_RSA_WITH_AES_128_GCM_SHA256 \
                                SSL_RSA_WITH_AES_256_CBC_SHA256 \
                                SSL_RSA_WITH_AES_128_CBC_SHA256 \
                                TLS_EMPTY_RENEGOTIATION_INFO_SCSV

In addition, there is /usr/wave/websphere/wlp/usr/shared/jvm.options, containing:
-Dcom.ibm.jsse2.sp800-131=strict
-Djdk.tls.client.protocols=TLSv1.2
-Dhttps.protocols=TLSv1.2

AFAIK, the above setting ensure that TLSv1.3 is disabled on the server.

When we attempted to add TLS_AES_256_GCM_SHA384 to wave.liberty.ssl.enabledCiphers, the server exited with error. I do not have the log, but it was something about protocol not supported by TLSv1.2.

**Comment by acdemyers** [comment]
@avri-log-on  If your enabled ciphers is set I see no reason why TLS_AES_256_GCM_SHA384 would be used on that ssl configuration.  I wonder if the 'defaultSSLConfig' is being used where this is failing.   A 'defaultSSLConfig' will always get created if 'defaultKeyStore' exists.  You don't have anything configured to use 'defaultSSLConfig' in your configuration do you?

Can you get trace please.  Use trace string `com.ibm.ws.ssl.*=all:com.ibm.websphere.ssl.*=all:SSLChannel=all`.

**Comment by avri-log-on** [comment]
It turns out the customer had multiple Java installations on the workstation that issued the request. Since this caused additional problems, the customer removed all Java installations, and installed IBM Java 8. After that, the problem disappeared.

I still have no idea why the Java mix-up  caused TLS_AES_256_GCM_SHA384 to be used, but obviously this is not an Open Liberty issue. Thank you for your support.


P.S. Should I close the issue?

**Comment by acdemyers** [comment]
It seems after a cleanup of JVMs this issue was resolved.
