### ISSUE TITLE
LdapAdapter.getGroupsByOperationalAttribute does no filtering on results.

### ISSUE THREAD

**Issue by jvanhill** [OpenLiberty/open-liberty#2435]
The groups returned are not filtered for:

- base DN
- group search base
- group filter

These should be taken into consideration.

**Comment by ryanesch** [comment]
Operational attributes are in member-of style membership, which doesn't use group search filter eg.
dc=user1,o=ibm
cn=user1
ibm-allGroups=cn=group1,o=ibm...

This means the LDAP calls are "getAttributes", as opposed to "search" (which would use the filter). So it makes sense that operational attributes don't use the filter. I will add the search base to getGroupsForUser calls which go through operational attributes.

**Comment by ryanesch** [comment]
#5584
