### ISSUE TITLE
Different behavior with Numerical Query Params between webProfile-8.1 and webProfile-9.1

### ISSUE THREAD

**Issue by c-koell** [OpenLiberty/open-liberty#24362]
We have some problems after switching to webProfile-9.1 with Query Params in a Rest Endpoint
A empty Query Param leads to 
RESTEASY003870: Unable to extract parameter from http request: jakarta.ws.rs.QueryParam("val") value is ''

After reading https://openliberty.io/docs/latest/jakarta-ee-diff.html i have nothing found for that change.
It is absolutely the same as https://github.com/quarkusio/quarkus/issues/11464

**Steps to Reproduce**  
See the sample code in https://github.com/quarkusio/quarkus/issues/11464

**Expected behavior**  
Same behaviour as with webProfile-8.1

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.1
 - Affected feature(s) webProfile-9.1
 - Java Version: Eclipse OpenJ9 VM, Version 17.0.5+8

**Comment by jim-krueger** [comment]
Just for clarification.  Are you saying that the behavior in quarkus is the same as Liberty with webProfile-9.1?  Or is the quarkus behavior identical to webProfile-8.1.

**Comment by c-koell** [comment]
With webProfile-8.1 the value was null and with webProfile-9.1 we get a exception message as described in the quarkus issue.

**Comment by jim-krueger** [comment]
Yes, I realized that and deleted my question (apparently not before you started your response) thanks.

**Comment by c-koell** [comment]
@jim-krueger is there a plan to fix this ?

**Comment by jim-krueger** [comment]
Hi @c-koell.   I've communicated this issue to the RESTEasy SME and he considers this a bug and has written RESTEasy issue [3304](https://issues.redhat.com/browse/RESTEASY-3304).  I will be following this issue and will apply the fix to Open Liberty or potentially upgrade to the version of RESTEasy that contains this fix.

**Comment by c-koell** [comment]
@jim-krueger any news here ?

**Comment by jim-krueger** [comment]
This issue has not been resolved yet.  However looking at the RESTEasy issue listed above I see activity within the last week so hopefully it will be resolved soon.

**Comment by c-koell** [comment]
@jim-krueger great ! As i can see it will be available in 7.0.0. Hopefully Openliberty will update to this version soon if available.

**Comment by c-koell** [comment]
@jim-krueger there is now a release available. Is it possible that open liberty picks up that new version ?

**Comment by jim-krueger** [comment]
Hi,  RESTEasy 7.0.0 is only in an alpha release.   But it looks like this change has been back-ported to RESTEasy 6.2.7.  

What is your priority concerning this fix?  Upgrading to a more recent RESTEasy version is on our radar, but understanding your need will help me to prioritize this upgrade appropriately.    Thanks

**Comment by c-koell** [comment]
Hi @jim-krueger 

We have worked around this bug/feature in the meanwhile in some of our code. So the priority is not so high.

But we have other projects where we plan a upgrade where we like to see this fix.

**Comment by c-koell** [comment]
@jim-krueger any news here ?

**Comment by jim-krueger** [comment]
Hi,   Keep an eye on https://github.com/OpenLiberty/open-liberty/issues/28069.

**Comment by jim-krueger** [comment]
The fix for this should be included in Open Liberty 24.0.0.6.

**Comment by jim-krueger** [comment]
Closing so that this will be listed in the content for 24.0.0.6.  Please reopen if needed.
