### ISSUE TITLE
ws-security saml test project improvements

### ISSUE THREAD

**Issue by arunavemulapalli** [OpenLiberty/open-liberty#24402]
- add some lite tests that exercise CBH feature
<del>- instead of using CBH bundle copy, update test project to compile the bundle</del>

**Comment by meiaus** [comment]
3/03/2023 Per discussion with @arunavemulapalli, the issue will only address 1 task of adding lite test but not `compile the bundle`.  And also explained that in the current saml server common setup, there may not be a way to inject new server to allow the user-feature.bnd and fat.bnd to build before server starts.  We'll continue using the existing way of copying the pre-compiled CBH jar to the test path, and hope with the new test case added, we'll have a chance to capture the failure earlier during development time regarding unresolved package error when new runtime change is made next time.

**Comment by meiaus** [comment]
See the work complete via https://github.com/OpenLiberty/open-liberty/issues/24471.
