### ISSUE TITLE
Java Batch 2.1 FTS (EE 10)

### ISSUE THREAD

**Issue by cgianfra** [OpenLiberty/open-liberty#24413]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

There are two new pieces of function with this feature: new value types for BatchProperty CDI injection, and the ability to inject the default JobOperator via CDI.

The new test cases in the JBatch CDI FAT test:
1. That properly-defined BatchProperty injections of all new value types are processed correctly when defined in the JSL
2. That the same BatchProperty injections are processed correctly when values are submitted as job parameters
3. That the default JobOperator instance can be injected via CDI
4. That the expected failure condition occurs when a BatchProperty value is incorrectly defined

### List of FAT projects affected

* com.ibm.ws.jbatch.cdi_fat

### Test strategy

* What functionality is new or modified by this feature?

The @BatchProperty annotation can now handle additional types for injection, as opposed to just String. Additionally, the default JobOperator instance is now available as a CDI artifact.

* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)

Positive: The first new test verifies that the user can supply the new value types for BatchProperty injection, both as literals in the JSL or as job parameters at runtime, and that those injected values match the input. There is also verification that the default JobOperator is supplied if an injection point is provided.

Negative: Another new test verifies that when a BatchProperty value type is improperly defined (e.g., trying to inject a String value into an Integer field), the expected failure case occurs - the job fails, and FFDCs are created.

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

None

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

**4 -** We could potentially add dozens of additional tests checking the behavior of every improper value assignment combination (e.g. String to Integer, String to Double, String to Float, Float to Integer...), but we do not believe this would add any meaningful value.

**Comment by cgianfra** [comment]
Tests were delivered in PR #24325

**Comment by ayoho** [comment]
LGTM 👍
