### ISSUE TITLE
support server.xml as default dynamic config source for MP config

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#2442]
We would like to support server.xml as a default dynamic config source. I would like to agree on the list of properties. https://www.ibm.com/support/knowledgecenter/en/SSRTLW_8.5.1/com.ibm.websphere.wlp.nd.multiplatform.doc/autodita/rwlp_metatype_4ic.html

**Comment by aguibert** [comment]
Does this proposal also include a new server.xml config element specifically for MP-Config properties? 

Something along the lines of:
```xml
<server>
  <mpConfig prop1="one" prop2="two" prop3="three"/>
</server>
```

**Comment by Emily-Jiang** [comment]
I propose the following element in server.xml should be made available to the app:

<variable name="HTTP_default_var" value="8889" />

as it is equivalent to specify in bootstrapping.properties or jvm.options

For the new properties, I am suggesting to use this

<appProperties myProp=myValue
myProp2=myValue2
myProp3=myValue3/>

This application properties is visible to all application deployed this server.

For defining application scoped properties, 
<application context-root="helloworld" type="war" id="helloworld"
    location="helloworld.war" name="helloworld">
<properties myProp=helloValue/>
</application>

In this case, the property myProp should be visible to application helloworld only. I would myProp is helloValue instead of the myValue as defined globally.



<

**Comment by Emily-Jiang** [comment]
@aguibert I prefer not to use myConfig but use appProperties as this properties is tied to applications not MP Config only, as we might have other config model to utilise like, such as Config JSR382.

**Comment by NottyCode** [comment]
In the MP Config spec currently there are attributes that can't be encoded as an attribute name. If those don't change then we need to resurrect a design discussion that allowed for this:

<appProperties propName="value">
   <property name="something that can't be an attribute" value="value"/>
</appProperties>

This would all be encoded behind the ibm:extraProperties="true" so it wouldn't be encoded in every metatype and the config runtime would handle it.

**Comment by brenthdaniel** [comment]
Tom and I discussed a possible addition to our VariableRegistry SPI that would return all defined variables. However, this would return a lot more than just variables defined in server.xml. In particular, internal configuration variables of the form "UNIQUE_JNDINAME" or "WLP_VAR_IN_USE" should probably not be exposed to users. There are also any number of variables included in default configuration or bootstrap.properties that are reasonable to expose but would clutter the results.

**Comment by tevans78** [comment]
I think that having bootstrap.properties and variables from default configuration is OK but we should probably filter out the internal configuration variables. If we create an internal extension to VariableRegistry (not SPI) that returns everything then the MP Config Source implementation can do the job of filtering it down.

@brenthdaniel do you think we could come up with a regex or something to filter out the internal variables?

**Comment by tevans78** [comment]
There are currently two parts to this issue;

1) making variables available by (partially) exposing the contents of ConfigVariableRegistry to MP Config through a new internal interface

2) Since the proposed <appProperties> element is inside <application>, any changes result in a full application restart. What we want is for the app manager to (some how) know not to restart the app for changes to <appProperties>.

**Comment by Emily-Jiang** [comment]
All configurations defined in <variable> element will be available to all applications for the corresponding server. 

`<variable name="HTTP_default_var" value="8889" />`

For defining application scoped properties,

<application context-root="helloworld" type="war" id="helloworld"
    location="helloworld.war" name="helloworld">
<appProperties myProp=helloValue/>
</application>

**Comment by Emily-Jiang** [comment]
For implementation, @tevans78 has raised an issue #3047 for @brenthdaniel to provide a solution for 2 problems mentioned by Tom earlier.
