### ISSUE TITLE
Feature Test Summary MicroProfile JWT 2.1

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#24431]
## Test Strategy

**Test strategy & approach**
Configuration attributes control mpJwt behavior and can be defined in:
server.xml
microprofile-config.properties in META-INF of the test app
microprofile-config.properties in WEB-INF/classesMETA-INF of the test app
environment variables
system properties
Tests were created setting valid/invalid values for each of the new attributes in each of the supported locations.  Tests were also written to verify that we'll use the proper instance when values specified in multiple locations.
Tests were written to verify that the new config attributes are ignored when they are specified in the supported locations, but an older version of the mpJwt feature is used.  The older versions don't understand the new attributes.

All tests for this feature are automated.
The FAT projects should run on all OS' with all JDK's .

### List of FAT projects affected

* com.ibm.ws.security.fat.common.mp.jwt
* com.ibm.ws.security.mp.jwt.2.1_fat.commonTest
* com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-1.1
* com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-1.2
* com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-2.0
* com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-2.1

### Test strategy

* New configuration attributes were added to support the functional updates for mpJwt 2.1 and tests are being added to ensure that these new config attributes are used properly.
* tokenAge and keyManagementKeyAlgorithm were added to the mpJwt metadata (server.xml) - clockSkew had been added with mpJwt 1.2 and we already have tests for that in the 1.2 FATs
* mp.jwt.verify.token.age, mp.jwt.verify.clock.skew  and mp.jwt.decrypt.key.algorithm are now supported through the microprofile-config.properties file, environment variables and system properties.
* Valid, invalid, long and short values are used with the new attributes and success/failure are validated.  When successful, we validate key values within the response.  When unsuccessful, we'll verify status codes and look for error responses and error messages in the server logs.
* tests were created using the new config attributes and prior versions of the mpJwt feature - these test verify that the config attribute being tested is ignored (as the older feature doesn't understand it)
* Test cases:

- * Test tokenAge and keyManagementKeyAlgorithm in server.xml (clockSkew tested in a previous mpJwt version)
- - * MPJwt21ConfigUsingBuilderTests_Default_TokenAge()
- - * MPJwt21ConfigUsingBuilderTests_Long_TokenAge()
- - * MPJwt21ConfigUsingBuilderTests_Short_TokenAge()
- - * MPJwt21ConfigUsingBuilderTests_Empty_DecryptAlg()
- - * MPJwt21ConfigUsingBuilderTests_RSA_OAEP_MatchToken_DecryptAlg()
- - * MPJwt21ConfigUsingBuilderTests_RSA_OAEP_256_MismatchToken_DecryptAlg()
- - * MPJwt21ConfigUsingBuilderTests_Invalid_DecryptAlg()

- * Test clockSkep, tokenAge and keyManagementKeyAlgorithm in microprofile-config.properties
- - * MPJwt21MPConfigInApp_NoMPJwt21ConfigInServerXml_DefaultTokenAgeInMPConfig_InMetaInf_test()
- - * MPJwt21MPConfigInApp_NoMPJwt21ConfigInServerXml_LongTokenAgeInMPConfig_InMetaInf_test()
- - * MPJwt21MPConfigInApp_NoMPJwt21ConfigInServerXml_ShortTokenAgeInMPConfig_InMetaInf_test()
- - * MPJwt21MPConfigInApp_NoMPJwt21ConfigInServerXml_DefaultTokenAgeInMPConfig_UnderWebInf_test()
- - * MPJwt21MPConfigInApp_NoMPJwt21ConfigInServerXml_LongTokenAgeInMPConfig_UnderWebInf_test()
- - * MPJwt21MPConfigInApp_NoMPJwt21ConfigInServerXml_ShortTokenAgeInMPConfig_UnderWebInf_test()
- - * MPJwt21MPConfigInApp_NoMPJwt21ConfigInServerXml_DefaultClockSkewInMPConfig_InMetaInf_test()
- - * MPJwt21MPConfigInApp_NoMPJwt21ConfigInServerXml_LongClockSkewInMPConfig_InMetaInf_test()
- - * MPJwt21MPConfigInApp_NoMPJwt21ConfigInServerXml_ShortClockSkewInMPConfig_InMetaInf_test()
- - * MPJwt21MPConfigInApp_NoMPJwt21ConfigInServerXml_DefaultClockSkewInMPConfig_UnderWebInf_test()
- - * MPJwt21MPConfigInApp_NoMPJwt21ConfigInServerXml_LongClockSkewInMPConfig_UnderWebInf_test()
- - * MPJwt21MPConfigInApp_NoMPJwt21ConfigInServerXml_ShortClockSkewInMPConfig_UnderWebInf_test()
- - * MPJwt21MPConfigInApp_NoMPJwt21ConfigInServerXml_DefaultKeyMgmtKeyAlg_inMetaInf_test()
- - * MPJwt21MPConfigInApp_NoMPJwt21ConfigInServerXml_DefaultKeyMgmtKeyAlg_underWebInf_test()
- - * MPJwt21MPConfigInApp_NoMPJwt21ConfigInServerXml_MatchKeyMgmtKeyAlg_inMetaInf_test()
- - * MPJwt21MPConfigInApp_NoMPJwt21ConfigInServerXml_MatchKeyMgmtKeyAlg_underWebInf_test()
- - * MPJwt21MPConfigInApp_NoMPJwt21ConfigInServerXml_MismatchKeyMgmtKeyAlg_inMetaInf_test()
- - * MPJwt21MPConfigInApp_NoMPJwt21ConfigInServerXml_MismatchKeyMgmtKeyAlg_underWebInf_test()
- - * MPJwt21MPConfigInApp_NoMPJwt21ConfigInServerXml_InvalidKeyMgmtKeyAlg_inMetaInf_test()
- - * MPJwt21MPConfigInApp_NoMPJwt21ConfigInServerXml_InvalidKeyMgmtKeyAlg_underWebInf_test()

- * Test clockSkep, tokenAge and keyManagementKeyAlgorithm set as environment variables
- - * MPJwtGoodMP21ConfigAsEnvVars_DecryptAlg_test()
- - * MPJwtGoodMP21ConfigAsEnvVars_DecryptAlg_overriddenByServerXml_test()
- - * MPJwtGoodMP21ConfigAsEnvVars_ClockSkew_Test()
- - * MPJwtGoodMP21ConfigAsEnvVars_ClockSkewe_overriddenByServerXml_test()
- - * MPJwtGoodMP21ConfigAsEnvVars_TokenAge_Test()
- - * MPJwtGoodMP21ConfigAsEnvVars_TokenAge_overriddenByServerXml_test()

- * Test clockSkep, tokenAge and keyManagementKeyAlgorithm set as system properties
- - * MPJwtGoodMP21ConfigAsSystemProperties_TokenAge_test()
- - * MPJwtGoodMP21ConfigAsSystemProperties_TokenAge_overriddenByServerXml_test()
- - * MPJwtGoodMP21ConfigAsSystemProperties_ClockSkew_test()
- - * MPJwtGoodMP21ConfigAsSystemProperties_ClockSkew_overriddenByServerXml_test()
- - * MPJwtGoodMP21ConfigAsSystemProperties_DecryptAlg_test()
- - * MPJwtGoodMP21ConfigAsSystemProperties_DecryptAlg_overriddenByServerXml_test()

- * Test clockSkep, tokenAge and keyManagementKeyAlgorithm set in each supported location using older versions of mpJwt - test with 1.1, 1.2 and 2.0
- - * OlderMpJwtFeatures_GenericEnvVarsAndSystemPropertiesTests_ClockSkew_test() (run once as env_var and once as a system property)
- - * OlderMpJwtFeatures_GenericEnvVarsAndSystemPropertiesTests_TokenAge_test() (run once as env_var and once as a system property)
- - * OlderMpJwtFeatures_GenericEnvVarsAndSystemPropertiesTests_DecryptAlg_test()(run once as env_var and once as a system property)
- - * OlderMpJwtFeatures_ConfigInServerXmlTests_Short_TokenAge()
- - * OlderMpJwtFeatures_ConfigInServerXmlTests_RSA_OAEP_256_MismatchToken_DecryptAlg()
- - * OlderMpJwtFeatures_ConfigInServerXmlTests_Invalid_DecryptAlg()
- - * OlderMpJwtFeature_ConfigInAppTests_NoMPJwt21ConfigInServerXml_ShortTokenAgeInMPConfig_InMetaInf_test()
- - * OlderMpJwtFeature_ConfigInAppTests_NoMPJwt21ConfigInServerXml_ShortTokenAgeInMPConfig_UnderWebInf_test()
- - * OlderMpJwtFeature_ConfigInAppTests_NoMPJwt21ConfigInServerXml_ShortClockSkewInMPConfig_InMetaInf_test()
- - * OlderMpJwtFeature_ConfigInAppTests_NoMPJwt21ConfigInServerXml_ShortClockSkewInMPConfig_UnderWebInf_test()
- - * OlderMpJwtFeature_ConfigInAppTests_NoMPJwt21ConfigInServerXml_MismatchKeyMgmtKeyAlg_inMetaInf_test()
- - * OlderMpJwtFeature_ConfigInAppTests_NoMPJwt21ConfigInServerXml_MismatchKeyMgmtKeyAlg_underWebInf_test()
- - * OlderMpJwtFeature_ConfigInAppTests_NoMPJwt21ConfigInServerXml_InvalidKeyMgmtKeyAlg_inMetaInf_test()
- - * OlderMpJwtFeature_ConfigInAppTests_NoMPJwt21ConfigInServerXml_InvalidKeyMgmtKeyAlg_underWebInf_test()
* The mpJwt 1.1, 1.2 and 2.0 tests are also run with a repeat for mpJwt 2.1.  This means that all of the older/existing tests will be re-run using mpJwt 2.1 to make sure that existing function works properly with the new feature enabled.
* There are no manual tests

## Confidence Level
5 - all of the new attributes are tested with valid and invalid values.  We've tested with the values specified in multiple locations and made sure that the proper instance is used.  We've tested with and without the supporting feature.

**Comment by c00crane** [comment]
#20081

**Comment by teddyjtorres** [comment]
Thank you very much for the summary!

**Comment by ayoho** [comment]
LGTM 👍
