### ISSUE TITLE
JAX-RS NPE in Singleton EJB Sub Resource

### ISSUE THREAD

**Issue by WhiteCat22** [OpenLiberty/open-liberty#24444]
**Describe the bug**  
https://github.com/OpenLiberty/open-liberty/issues/24155 caused a bug where JAX-RS `@Context` injection into sub resource classes annotated with EJB's `@Singleton` wouldn't inject.

Code Example:
```
    @Context private UriInfo ui;

    @GET
    public String get() {
        return ui.getRequestUri(); // NPE
    }
```

If there is a stack trace, please include the FULL stack trace (without any `[internal classes]` lines in it). To find the full stack trace, you may need to check in `$WLP_OUTPUT_DIR/messages.log`

**Steps to Reproduce**  
- Create a JAX-RS sub resource class
- Annotate the sub resource class with `@Singleton`
- Attempt to inject `UriInfo` via `@Context`
- `UriInfo` is null

**Expected behavior**  
`UriInfo` should inject properly

**Diagnostic information:**  
 - OpenLiberty Version: < 23.0.0.3
 - Affected feature(s) `jaxrs-2.0`, `jaxrs-2.1`
 - Java Version: 
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**

**Comment by WhiteCat22** [comment]
Fixes #PH52888

**Comment by jhanders34** [comment]
#regression

**Comment by mbroz2** [comment]
@WhiteCat22 please update the description of this `release bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
