### ISSUE TITLE
Open Liberty log interceptor intercepts structured JSON application log messages > 8k from log4j2

### ISSUE THREAD

**Issue by Kadams64** [OpenLiberty/open-liberty#24460]
**Describe the bug**  
Log4j2 'breaks' structured (JSON) log messages > 8k into 'chunks'.  Liberty's log interceptor 'wraps' these 'chunked' application log messages in Liberty JSON, thereby breaking any log aggregation logic related to the application logs e.g.: EFK, LokiStack.
- this occurs when the Liberty `appsWriteJson` / `WLP_LOGGING_APPS_WRITE_JSON` property is set to `true`
- messages shorter than 8k are properly passed through
- changing the log4j2 system property `log4j.encoder.byteBufferSize` to a larger value than the default `8 x 1024` will overcome this issue until log4j application messages exceeding this size are produced

This is observed using multiple versions of log4j2 (e.g.: 2.17.1; 2.20.0) and multiple versions of Open Liberty (e.g.: 22.0.0.12; 23.0.0.1)

**Steps to Reproduce**  

1. configure Liberty with `appsWriteJson` = `true`
2. configure a deployed app with log4j2 to send structured (JSON) messages to the console
3. have the application produce a single log4j2 message > 8192 characters in length
4. observe that the large message is chunked into multiple messages that are incorrectly intercepted and wrapped in Liberty JSON
5. apply the log4j2 system property `log4j.encoder.byteBufferSize` to set a buffer size larger than the default
- e.g.: add this to the Liberty `jvm.options` to set the buffer to 128k: `-Dlog4j.encoder.byteBufferSize=131072`
6. observe that log4j2 application messages smaller than the size set in the previous step now 'work' i.e.: are not intercepted; however, larger messages will still be subject to the issue 

**Expected behavior**  
Liberty should correctly pass through structured JSON application messages from log4j2 even if they are 'chunked'

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.1 (also observed in 22.0.0.12)
 --  image as per icr.io/appcafe/open-liberty/23.0.0.1-full-java8-openj9-ubi
- log4j2 2.17.1 (also observed with 2.20.0)
- the log4j2 behaviour seems traceable to this log4j2 source code=>  [log4j-core/util/Constants.java ](https://github.com/apache/logging-log4j2/blob/release-2.x/log4j-core/src/main/java/org/apache/logging/log4j/core/util/Constants.java)(log4j2 GitHub)
-- and specifically this block of code
```
    /**
     * Default size of ByteBuffers used to encode LogEvents without allocating temporary objects.
     * <p>
     * The default value is {@value}, users can override with system property "log4j.encoder.byteBufferSize".
     * </p>
     * @see org.apache.logging.log4j.core.layout.ByteBufferDestination
     * @since 2.6
     */
    public static final int ENCODER_BYTE_BUFFER_SIZE = size("log4j.encoder.byteBufferSize", 8 * 1024);
```

**Additional context**

**Comment by fmhwong** [comment]
If Liberty were able to pass thru incomplete JSON fragments from applications, would you still need to append them back in the logging backend?  Would it be easier just to set the `log4j.encoder.byteBufferSize` to a bigger size?

**Comment by Kadams64** [comment]
> If Liberty were able to pass thru incomplete JSON fragments from applications, would you still need to append them back in the logging backend? Would it be easier just to set the `log4j.encoder.byteBufferSize` to a bigger size?

Setting log4j.encoder.byteBufferSize is a workaround, but the problem is setting it large enough to account for every possible message.  I also don't know what the impact of setting `log4j.encoder.byteBufferSize` to an arbitrarily large value e.g.: maxInt would be on, for example, JVM memory / heap consumption.

I understand  your point, though, and I don't know what the 'best' answer here is.  Minimally, Liberty should not wrap JSON fragments from the application in its own JSON.  That way the problem is clearly with log4j if it doesn't get ingested properly. 
- and log4j should probably not say 'console output is unbuffered' when clearly it is buffered and 'chunked'.  It is particularly frustrating that the property that controls this  (`log4j.encoder.byteBufferSize`) isn't even documented as a configurable property.  But this is not your problem ;)

But the outcome a normal deployer wants is (of course) that the application JSON gets to the console in a form that will be properly ingested by any log aggregation tooling.

**Comment by donbourne** [comment]
> I understand your point, though, and I don't know what the 'best' answer here is. Minimally, Liberty should not wrap JSON fragments from the application in its own JSON. That way the problem is clearly with log4j if it doesn't get ingested properly.

Currently Liberty just looks for "{" at the start and "}" at the end of a print to System.out to determine if a message is "JSON".  Tracking that something looks like it could be JSON across multiple System.out print calls would be complex.   

Liberty chunks System.out prints at 256kb, by default, so you may want to set your `log4j.encoder.byteBufferSize` to the same.  If log4j tries to write something larger to System.out then Liberty will break that into separate prints (which means prints from other threads could come between segments of your log4j output).  The implication of setting a larger value, for both Liberty's System.out chunking and for `log4j.encoder.byteBufferSize` is that multiple threads could end up holding onto that much data before streaming it out and reclaiming the memory.

**Comment by donbourne** [comment]
@Kadams64 , I'll close this, as there's currently no plan to change Liberty for this.  I'm interested to know if setting your `log4j.encoder.byteBufferSize` to 256k is workable for you.
