### ISSUE TITLE
Feature Test Summary : Jakarta EE 10 Core Profile, Web Profile, Platform

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/open-liberty#24480]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

**The general test strategy for the Jakarta EE 10 Feature is to repeat all tests run for Jakarta EE 9. It may be assumed that the features/components documented here had no new function introduced, other than support for the new deployment descriptor versions (web.xml, application.xml, ejb-jar.xml etc). Jakarta EE 9 features that did not have a version update in Jakarta EE 10 are also included in this test summary.  Additionally there is a FAT added that specifically tests Jakarta EE 10 convenience features.**

### List of FAT projects affected

- managedBeans-2.0
  - com.ibm.ws.managedbeans_fat
<p>

- enterpriseBeanLite-4.0
  - com.ibm.ws.ejbcontainer.async_fat
  - com.ibm.ws.ejbcontainer.exception_fat _(also Home & Remote)_
  - com.ibm.ws.ejbcontainer.interceptor_fat _(also PersistentTimer & mdb)_
  - com.ibm.ws.ejbcontainer.interceptor.v32_fat _(also Home)_
  - com.ibm.ws.ejbcontainer.session.async_fat _(also enterpriseBeans-4.0 & mdb)_
  - com.ibm.ws.ejbcontainer.session.passivation_fat
  - com.ibm.ws.ejbcontainer.timer.auto_fat
  - com.ibm.ws.ejbcontainer.timer.calendar_fat _(also enterpriseBeansHome & enterpriseBeansPersistentTimer)_
  - com.ibm.ws.ejbcontainer.timer.np.config_fat
  - com.ibm.ws.ejbcontainer.timer.np_fat
  - com.ibm.ws.ejbcontainer.timer.v32_fat
  - com.ibm.ws.ejbcontainer.tx_fat _(also mdb-4.0)_
  - com.ibm.ws.ejbcontainer.war_fat
  - com.ibm.ws.injection_fat _(also Remote & mdb)_
  - io.openliberty.ejbcontainer.v40_fat
<p>

- enterpriseBeansHome-4.0 _(i.e. EJB 2.x)_
  - com.ibm.ws.ejbcontainer.bindings_fat _(also Remote)_
  - com.ibm.ws.ejbcontainer.exception_fat _(also Lite & Remote)_
  - com.ibm.ws.ejbcontainer.legacy_fat _(also Remote)_
<p>

- enterpriseBeansPersistentTimer-4.0
  - com.ibm.ws.ejbcontainer.timer.persistent_fat
<p>

- enterpriseBeansRemote-4.0
  - com.ibm.ws.ejbcontainer.cdi_fat
  - com.ibm.ws.ejbcontainer.exception_fat _(also Lite & Home)_
  - com.ibm.ws.ejbcontainer.legacy_fat _(also Home)_
  - com.ibm.ws.ejbcontainer.remote_fat _(also Lite & Home)_
<p>

- enterpriseBeansRemoteClient-2.0 (private feature in application client)
  - com.ibm.ws.ejbcontainer.remote.client_fat _(also enterpriseBeans-4.0 convenience feature)_
<p>

- mdb-4.0
  - com.ibm.ws.ejbcontainer.mdb.jms_fat
  - com.ibm.ws.ejbcontainer.mdb.ra_fat
  - com.ibm.ws.ejbcontainer.session.async_fat _(also enterpriseBeans-4.0 and Lite)_
  - com.ibm.ws.ejbcontainer.tx_fat _(also Lite)_
<p>

- enterpriseBeans-4.0 _(convenience feature including all of the above)_
  - com.ibm.ws.ejbcontainer.remote.client_fat _(also RemoteClient)_
  - com.ibm.ws.ejbcontainer.session.async_fat _(also Lite and mdb-4.0)_
  - com.ibm.ws.ejbcontainer.legacy_fat
  - io.openliberty.ejbcontainer.v40_fat
<p>

- test that covers the EJB Container API
  - com.ibm.ws.ejbcontainer.bindings_fat
  - com.ibm.ws.ejbcontainer.injection_fat
  - com.ibm.ws.ejbcontainer.remote.client_fat
<p>

- transaction-2.0, jta-2.0
  - com.ibm.ws.transaction.cloud_fat.*
  - com.ibm.ws.transaction.core_fat.*
  - com.ibm.ws.transaction.db_fat
  - com.ibm.ws.transaction.hadb_fat.*
  - com.ibm.ws.transaction.recovery_fat.{1..3}
  - com.ibm.ws.tx.jta_fat
  - com.ibm.ws.tx.jta_fat_hibernate
<p>

- beanValidation-3.0
  - com.ibm.ws.beanvalidation.v11_fat
  - com.ibm.ws.beanvalidation.v20_fat
<p>

- passwordUtilities-1.0 and passwordUtilities-1.1
  - com.ibm.websphere.security_fat.1
  - com.ibm.ws.security.auth.data_fat
<p>

- jwt-1.0
  - com.ibm.ws.security.jwt_fat.builder
  - com.ibm.ws.security.jwt_fat.consumer
<p>

- spnego-1.0
  - com.ibm.ws.security.spnego_fat
  - com.ibm.ws.security.spnego_fat.1
<p>

- audit-1.0
  - com.ibm.ws.ejbcontainer.security.jacc_fat
  - com.ibm.ws.security.jaspic_fat
  - com.ibm.ws.webcontainer.security.jacc.1.5_fat
<p>

- oauth-2.0
  - com.ibm.ws.security.oauth_fat
<p>

- samlWeb-2.0
  - com.ibm.ws.security.saml.sso_fat
  - com.ibm.ws.security.saml.sso_fat
  - com.ibm.ws.security.saml.sso_fat.2
  - com.ibm.ws.security.saml.sso_fat.3
  - com.ibm.ws.security.saml.sso_fat.config
  - com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry
  - com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata
  - com.ibm.ws.security.saml.sso_fat.jaxrs
  - com.ibm.ws.security.saml.sso_fat.jaxrs.config
  - com.ibm.ws.security.saml.sso_fat.logout
  - com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest
  - com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout
  - com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated
<p>

- jdbc-4.x
  - com.ibm.ws.jdbc_fat_v41 - jdbc-4.1
  - com.ibm.ws.jdbc_fat_loadfromapp - jdbc-4.2
  - com.ibm.ws.jdbc_fat_krb5 when run with PostgreSQL - jdbc-4.2
  - Indirect coverage from many other FAT buckets throughout Liberty that use jdbc features and were switched to or repeat with Jakarta EE 10
<p>

- webBundle-1.0 (WAB) protected feature support
  - com.ibm.ws.app.manager.wab.installer_fat
  - com.ibm.ws.rest.handler.config.fat
<p>

- restConnector-2.0 and restHandler-1.0
  - com.ibm.ws.rest.handler.config_fat
  - com.ibm.ws.rest.handler.validator.cloudant_fat
  - com.ibm.ws.rest.handler.validator_fat
<p>

- sessionCache-1.0
  - com.ibm.ws.session.cache_fat
  - com.ibm.ws.session.cache_fat_config
  - com.ibm.ws.session.cache_fat_infinispan_container
<p>

- sessionDatabase-1.0
  - com.ibm.ws.cdi.lifecycle_fat
  - com.ibm.ws.session.cache_fat
<p>

- socialLogin-1.0
  - com.ibm.ws.security.social_fat.LibertyOP.1
  - com.ibm.ws.security.social_fat.LibertyOP.2
  - com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout
  - com.ibm.ws.security.social_fat.LibertyOP.claimPropagation
<p>

- openidConnectClient-1.0
  - com.ibm.ws.security.oidc.client_fat.1
  - com.ibm.ws.security.oidc.client_fat.2
  - com.ibm.ws.security.oidc.client_fat.claimPropagation
  - com.ibm.ws.security.oidc.client_fat.jaxrs
<p>

- openidConnectServer-1.0
  - com.ibm.ws.security.oidc.server_fat.backchannelLogout
  - com.ibm.ws.security.oidc.server_fat.oidc
<p>

- acmeCA-2.0
  - com.ibm.ws.security.acme_fat
<p>

- jakartaeeClient-10.0 / appClientSupport-2.0
  - com.ibm.ws.clientcontainer.8.0_fat
  - com.ibm.ws.clientcontainer.beanvalidation_fat
  - com.ibm.ws.clientcontainer.cdi_fat
  - com.ibm.ws.clientcontainer.json_fat
  - com.ibm.ws.ejbcontainer.remote.client_fat
  - com.ibm.ws.jaxws.clientcontainer_fat
  - com.ibm.ws.security.client_fat
<p>

- federatedRegistry-1.0
  - com.ibm.ws.security.wim.core_fat
<p>

- adminCenter-1.0
  - com.ibm.ws.ui_rest_fat
<p>

- grpc-1.0 / grpcClient-1.0
  - com.ibm.ws.grpc_fat 
<p>

- requestTiming-1.0
  - com.ibm.ws.request.timing_fat
  - com.ibm.ws.request.timing.hung_fat
  - com.ibm.ws.request.timing.monitor_fat
<p>

- webProfile-10.0 / jakartaee-10.0
  - io.openliberty.jakartaee10.internal_fat
<p>

OL functions that have tests in WL repo
---
- distributedMap-1.0, webCache-1.0 (depends on unsupported WL feature webCacheMonitor-1.0)
  - com.ibm.ws.dynacache_fat
  - com.ibm.ws.dynacache_fat_ext
  - com.ibm.ws.dynacache_fat_servlet31
<p>

- admincenter-1.0 (uses Selenium which cannot move to OL until we move to Selenium 4 which is in progress)
  - com.ibm.ws.ui.collective_fat
  - com.ibm.ws.ui_fat.gui
  - com.ibm.ws.ui.tool.explore_fat.gui.nd.rw.monitor
  - com.ibm.ws.ui.tool.explore_fat.gui.nd.rw.ws.monitor
  - com.ibm.ws.ui.tool.javaBatch_fat.gui
<p>

- monitor-1.0 (FAT that just has not moved to OL yet)
  - com.ibm.ws.monitor_fat
<p>

WL functions
---
- wmqMessagingClient-3.0
  - com.ibm.ws.messaging.jms20.wmq_fat_java7
  - com.ibm.ws.messaging.jms.wmq_zfat
  - com.ibm.ws.zos.wlm.ejb_zfat
  - com.ibm.ws.zos.wlm.ejb.svt_zfat
<p>

- core and ND features (clusterMember-1.0, collectiveController-1.0, collectiveMember-1.0, scalingController-1.0, scallingMember-1.0, dynamicRouting-1.0, healthAnalyzer-1.0, healthManager-1.0)
  - com.ibm.ws.collective.rest.notify_fat
  - com.ibm.ws.collective.routing.controller_fat
  - com.ibm.ws.collective.routing.member_fat
  - com.ibm.ws.dynamic.routing_fat
  - com.ibm.ws.dynamic.routing.ha_fat
  - com.ibm.ws.dynamic.routing.routingrules_fat
  - com.ibm.ws.health.action_fat
  - com.ibm.ws.health.analyzer_fat
  - com.ibm.ws.health.manager_fat
  - com.ibm.ws.scaling.controller_fat
  - com.ibm.ws.scaling.controller.extensions_fat
  - com.ibm.ws.scaling.member_fat
  - com.ibm.ws.scaling.member.registration_fat
  - com.ibm.ws.cluster_fat
  - com.ibm.ws.cluster.manager_fat
  - com.ibm.ws.cluster.member_fat
<p>

- z/OS features
  - batchSMFLogging
    - com.ibm.ws.jbatch.smflogging_zfat
  - zosLocalAdapters
    - com.ibm.ws.zos.ola_zfat
    - com.ibm.ws.jbatch_zfat
    - com.ibm.ws.jbatch.wola_zfat
  - zosRequestLogging
    - com.ibm.ws.zos.request.logging.saf_zfat
    - com.ibm.ws.zos.request.logging_zfat
    - com.ibm.ws.zos.wlm.context.servlet.async_zfat
  - zosSecurity
    - com.ibm.ws.jbatch.security_zfat
    - com.ibm.ws.security.authorization.saf_zfat
    - com.ibm.ws.security.credentials.saf_zfat
    - com.ibm.ws.security.registry.saf_zfat
    - com.ibm.ws.security.thread.webcontainer_zfat
    - com.ibm.ws.security.thread.zos.context_zfat
    - com.ibm.ws.security.thread.zos_zfat
  - zosTransaction
    - com.ibm.ws.jca_zfat
    - com.ibm.ws.zos.tx_zfat
    - com.ibm.ws.messaging.jms.wmq_zfat

### Test strategy

* What functionality is new or modified by this feature?  **Jakarta EE 10 convenience features for Web Profile and Platform added.**
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)  **Make sure that all features that are supposed to start with Jakarta EE 10 start cleanly.  If a feature is not supposed to work with Jakarta EE 10 features, make sure that it gives an eeCompatible feature conflict.**
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)  **None**
**com.ibm.ws.jdbc_fat_v43 - jdbc-4.3 not tested due to dependency in the test on a removed API in EE10.  After refactoring, it could be enabled to run on EE 10.  It was run manually and the tests that do not require that API all do pass.**

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

**4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.**

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by ayoho** [comment]
LGTM 👍
