### ISSUE TITLE
Feature Test Summary - Support Jakarta Security 3.0

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#24506]
## Test Strategy

Several FAT projects were updated or added in support of the Jakarta Security 3.0 Feature.
All testing for this feature is automated.
Tests were created to test the support of the OpenIdAuthenticationMechanismDefinition annotation.  This included tests to verify behavior of all attributes specified in the annotation and embedded annotations.  Different scopes, login, logout, refresh were tested.  Additional testing was done for Identity Stores as well as validation of tokens from the token endpoint and responses from userinfo.

Many test applications were created to vary the content of the new annotation using values and EL values.
Test applications were written to replace the Authorize, Token endpoint and Userinfo endpoints to give us the flexibility to return many variations of both valid and invalid responses.  This let us test that the runtime can handle good and bad responses from our or external OPs. Other test applications were written to test functions such as HttpServletRequest.logout() and SecurityContext.authenticate(...).

Some tests are repeated with the OP issuing opaque or jwt tokens.  Userinfo tests are run with the userinfo test app returning responses in json or jwt format.

### List of FAT projects affected

* Updated - existing tooling projects were updated with some tool enhancements and constants
  - com.ibm.ws.security.fat.common
  - com.ibm.ws.security.fat.common.jwt

* Created
  - io.openliberty.security.jakartasec.3.0.internal_fat
  - io.openliberty.security.jakartasec.3.0.internal_fat.common
  - io.openliberty.security.jakartasec.3.0.internal_fat.config
  - io.openliberty.security.jakartasec.3.0.internal_fat.logout
  - io.openliberty.security.jakartasec.3.0.internal_fat.refresh

### Test strategy

* Testing [Jakarta Security 3.0](https://jakarta.ee/specifications/security/3.0/jakarta-security-spec-3.0.html)
  * Test @OpenIdAuthenticationMechanismDefinition and all embedded annotations for protecting an application (in a way similar to and RP client)  (including login/logout/refresh)
  * Test appropriate flows between the server running the app and a Liberty OP
  * Test processing of tokens returned from the token endpoint
  * Test processing of responses from userinfo (especially jwt formatted responses) 

* General test behavior
  * For all tests, we verify that we've completed every step as expected - this means we've received the appropriate page, response, and response status
  * For Positive tests, we validate in detail the content of the application output.  The test applications log information from the HTTP request, the OpenIdContext and WSSubject and the test cases will verify selected important details from the apps in the response/log.
  * For Negative tests, we validate that we get the proper status code and message/full text in the response.  We also verify that we have the correct messages in the server logs and if appropriate, Expect/Allow FFDCs.
* projects
  * **io.openliberty.security.jakartasec.3.0.internal_fat.common** - project that supplies common tooling and generic apps
    * generic methods to record http request content, openIdContext content, WSSubject content
    * generic methods to validate content of output from http request content, openIdContext content, WSSubject content
    * generic methods to invoke and process the response from the various pages that the tests need to process
    * tools to create the openIdConfig.properties and providerConfig.properties files
    * tools to create test wars from generic test application source and appropriately built openIdConfig.properties and providerConfig.properties files.  (we can use the same app in multiple ways by using EL variables and different values in the properties files)
    * generic applications that use above methods to record http request, openIdContext and WSSubject contents and include general callback and openIdConfig classes that all test apps will use.
    * generic application that specifies most annotation values using EL variables 
  * **io.openliberty.security.jakartasec.3.0.internal_fat** - End to end tests
    * AuthenticationTests - test SecurityContext.authenticate(...
      * we have a test app that injects openIdContext, has the @OpenIdAuthenticationMechanismDefinition annotation defined, but no roles.  Depending on parms passed to the app, it will invoke securityContext.authenticate without newAuthentication, or with it including true/false.
      * Tests for all combinations of setting useSession(true/false/omitted) and redirectToOriginalResource(true/false/omitted) and newAuthentication(true/false/omitted) are included
        * test verify that the test app and callback are invoked the proper number of times, we're prompted to login when we should, and receive the approprate errors when we try to re-use a session created by a different user.
    * BasicOIDCAnnotationUseCallbacksTests - Basic end to end tests with common @OpenIdAuthenticationMechanismDefinition values specified as well as useRedirectToOriginalResource=false
    * BasicOIDCAnnotationUseRedirectToOriginalResourceTests - Basic end to end tests with common @OpenIdAuthenticationMechanismDefinition values specified as well as useRedirectToOriginalResource=true
    * BasicOIDCAnnotationWithOidcClientConfigTests - Basic end to end tests with common @OpenIdAuthenticationMechanismDefinition values specified - server.xml contains and RP config with values that conflict with the annotation.  Tests ensure that the annotation is used, not the RP config in the server.xml.
    * IdentityStoreTests - Tests an app with one IdentityStore and another app with multiple IdentityStores.  The OP does not return the group that the test apps require, but the IdentityStores do.  Tests validate that we do get access to the app because of the group info from the identity store.  Tests also verify that all of the groups listed are what we expect.
    * InjectionScopedTests - Tests app with @OpenIdAuthenticationMechanismDefinition that use various scopes (application, request and session)
    * TokenValidationTests - Test that the runtime can process the responses from the token endpoint.  We use a test token endpoint that allows the tests to return whatever content the test requires.  The tests will use tokens that include and omit all required claims and will check for for the appropriate status code, app output, or error messages in the server logs.  We also have tests that include claim values that do not match what the annotation values and validate the appropriate status code, responses, error messages in the server logs.
  * io.openliberty.security.jakartasec.3.0.internal_fat.config - configuration attribute tests - test all attributes in @OpenIdAuthenticationMechanismDefinition, @OpenIdProviderMetadata, and @ClaimsDefinition. (@LogoutDefinition is tested by the logout and refresh projects)  All attributes are tested with valid and invalid values.  Where appropriate, both attribute and attribute\<Expression\> are tested (Where Expression forms of the attribute exist, tests verify that this value overrides the non-Expression value).  Many of the attributes are simple to test and are included in a more generic test class.  Some attributes require more in depth testing and are tested in their own class.
    * ConfigurationClaimsDefinitionTests - tests attributes of @ClaimsDefinition
    * ConfigurationDisplayTests - test various settings of Display
    * ConfigurationELValuesOverrideTests - tests that the Expression value overrides the non-Expression value for some of the more basic attributes - uses http session set in the server.xml
    * ConfigurationELValuesOverrideWithoutHttpSessionTests - tests that the Expression value overrides the non-Expression value for some of the more basic attributes - DOES NOT use http session set in the server.xml
    * ConfigurationExtraParametersTests - tests with extraParameters/extraParametersExpression and validates these parms as well as others that are passed based on other config attributes.
    * ConfigurationPromptTests - tests for proper behavior with various settings of prompt/promptExpression
    * ConfigurationProviderMetadataTests - tests the attributes of @ProviderMetadata
    * ConfigurationResponseModeTests - tests for proper behavior with various settings of responseMode
    * ConfigurationScopeTests - tests for proper behavior with various settings of scope/scopeExpression
    * ConfigurationSigningTests - tests with different signing algorithms configured in the annotation - we test where these values match and do not match what he OP returns.  We test with OPs that return tokens signed with RS256, HS256 and none - the values in the annotation are individual or multiple instances of RS, ES or HS 256, 384, or 512.  The tests validate the content of the app output for cases where expect a good result and will verify status code, response output and error/warnings in the logs.  This class also validates the connectionTimeout and readTimeout config attributes by using a test jwks endpoint that just sleeps longer than the test configured timeout (as appropriate for what's being tested).
    * ConfigurationTests - test the majority of the config attributes.  These tests will set values that are valid (match what the OP will return), invalid (wont' match what the OP will return or may conflict with other configured attributes) or are omitted.  Values will be specified in the app, or using EL vars, or through Expression instances of the attribute.  
    * ConfigurationTokenMinValidityTests - tests the behavior with various settings of tokenMinValidity/tokenMinValidityExpression and token lifetime (configured in the OP)
    * ConfigurationUseNonceTests -  tests the behavior with various settings of useNonce/useNonceExpression
    * ConfigurationUserInfoTests - tests with a test userinfo endpoint that can return the response as either json or jwt - the runtime should handle either (the Liberty OP only produces json).  Test behavior where userinfo is needed as well as when the response is not needed as the info that the runtime needs comes from other sources.  Also test behavior (when using jwt responses) to show that the idTokenSigningAlgorithmsSupported value attribute does not matter.  Also test with userinfo_signing_alg_values_supported returned by discovery (The Liberty OP does not include this) - test with algorithms that do and do not match what the userinfo endpoint returns.
  * io.openliberty.security.jakartasec.3.0.internal_fat.logout - test logout functionality
    * BasicLogoutTests - test logout function including all attributes of @LogoutDefinition and endSessionEndpoint of @OpenIdProviderMetadata.  Test with tokens that do/don't expire based on values from the OP and/or values from the annotation in the app.  Test with/without redirect after the logout. Test with/without notifying the provider.
  * io.openliberty.security.jakartasec.3.0.internal_fat.refresh - test refresh behaviour 
    * BasicRefreshTests - test refresh function including all attributes of @LogoutDefinition.  Test with tokens that do/don't expire based on values from the OP and/or values from the annotation in the app.  Test with/without redirect after the logout. Test with/without notifying the provider. Test with OP's that do and don't allow refresh.
    
* There are NO manual tests

## Confidence Level

5

**Comment by c00crane** [comment]
Associated pulls:
#22326	Jakarta security fat setup	
#22429	Creating Jakarta security test project and provide dynamic config tooling	
#22893	Additional tests and more result validation	
#22984	Enable/add some tests now that runtime updates are delivered	
#23168	Jakarta security Logout tests	
#23324	Jakarta Security Refresh tests	
#23330	Add tests using OIDC clients and annotations in one server	
#23346	Update tests to use constants instead of true/false	
#23357	add fat tests for OpenIdAuthenticationMechanismDefinition redirectURI	
#23386	Deliver Jakarta userinfo tests	
#23408	Update the Jakarata security FAT tests to use the default RS256	
#23472	create fat tests for OpenIdAuthenticationMechanismDefinition responseType	
#23533	add fat tests for OpenIdAuthenticationMechanismDefinition scope	
#23589	Create Jakarta Security Signing FAT tests	
#23648	add fat tests for OpenIdAuthenticationMechanismDefinition responseMode	
#23683	add fat tests for OpenIdAuthenticationMechanismDefinition useNonce	
#23725	jakarta security 3.0 fat cleanup	
#23879	add fat tests for OpenIdAuthenticationMechanismDefinition extraParameters	
#23973	Jakarta Security Identity Store FAT	
#23990	add fat tests for OpenIdAuthenticationMechanismDefinition prompt and promptExpression	
#24020	Jakarta Logout test enhancement	
#24059	add fat tests for OpenIdAuthenticationMechanismDefinition display and displayExpression	
#24116	Jakarta Logout test enhancement	
#24133	Create FAT tests for @OpenIdProviderMetadata	
#24169	add fat tests for OpenIdAuthenticationMechanismDefinition tokenMinValidity and tokenMinValidityExpression	
#24358	Create Jakarta Token endpoint validation tests	
#24400	enable logout test after 24062 was resolved	
#24406	disable jakarta sec 3.0 tokenMinValidity fat tests	
#24428	fix and re-enable jakarta security 3.0 tokenMinValidity fat tests	
#24446	Create Jakarta securityContext.authenticate tests

**Comment by dave-waddling** [comment]
Approved, with the proviso that defect 294980 is revisited; see [discussion in Slack](https://ibm-cloud.slack.com/archives/C5TT8KEBE/p1678719791105409).

**Comment by teddyjtorres** [comment]
Thank you very much for these tests and summary!
