### ISSUE TITLE
Adding cerificate to key store throws "DerInputStream.getLength(): lengthTag=109, too big."

### ISSUE THREAD

**Issue by rasha-al-kafoury-ibm** [OpenLiberty/open-liberty#24523]
Hi,
We are trying to add DB certificate in the key store on the image by running the following command 

> RUN /opt/java/openjdk/jre/bin/keytool -importcert -keystore /opt/java/openjdk/jre/lib/security/cacerts  -storepass pass -noprompt  -alias redis-db -trustcacerts -file /opt/ibm/java/jre/lib/security/redis.crt
RUN echo "<server description=\"Default Server\"><keyStore id=\"defaultKeyStore\" location=\"/opt/java/openjdk/jre/lib/security/cacerts\" password=\"changeit\" /></server>" >  /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/keystore.xml

> 

But we found this error in the logs 

> E CWPKI0033E: The keystore located at /opt/java/openjdk/jre/lib/security/cacerts did not load because of the following error: DerInputStream.getLength(): lengthTag=109, too big.
W CWPKI0809W: There is a failure loading the defaultKeyStore keystore. If an SSL configuration references the defaultKeyStore keystore, then the SSL configuration will fail to initialize.

> 

We found that the microservice can't connect to the required DB.
Can you please advice on this issue?

**Comment by acdemyers** [comment]
Perhaps if you specify the keystore type as JKS it will work.   Add type="JKS" to the keystore element.

**Comment by rasha-al-kafoury-ibm** [comment]
@acdemyers 
The keystore type is already jks, when I run the command 

> bash-4.4$ /opt/java/openjdk/jre/bin/keytool  -keystore ./opt/java/openjdk/jre/lib/security/cacerts  -storepass pass-list

> 

The output is 

>Keystore type: jks
Keystore provider: SUN
Your keystore contains 143 entries
........

>

**Comment by acdemyers** [comment]
I was asking to set it on the keystore element like eg.

`<keyStore id="defaultKeyStore" location="/opt/java/openjdk/jre/lib/security/cacerts" password="changeit" type="jks" />`

**Comment by rasha-al-kafoury-ibm** [comment]
Ok let me try that

**Comment by rasha-al-kafoury-ibm** [comment]
That solved the issue, thanks

**Comment by acdemyers** [comment]
Closing, config change solved the issue.
