### ISSUE TITLE
Support JDK 20 in Open Liberty: Feature Test Summary

### ISSUE THREAD

**Issue by jgrassel** [OpenLiberty/open-liberty#24538]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

### List of FAT projects affected

* io.openliberty.java.internal_fat - https://github.com/OpenLiberty/open-liberty/pull/24541
* com.ibm.ws.jpa.tests.javasupport_fat - https://github.com/OpenLiberty/open-liberty/pull/24027

### Test strategy

* What functionality is new or modified by this feature?
  * No new Liberty functionality is added or changed by this feature
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.) 
  * The io.openliberty.java.internal_fat FAT adds one simple test to ensure we are running on Java 20 by using binaries compiled at the Java 20 level, and leveraging preview/incubator technology such as Records and Virtual Threads.
  * The com.ibm.ws.jpa.tests.javasupport_fat was added, which verifies that JPA can consume (and perform class transformation on) JPA persistence capable classes compiled at newer levels, including Java 20.
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)
  * There are no manual tests.

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by dave-waddling** [comment]
Hi @jgrassel, this FTS looks good though I note that the additional testing being delivered in #24541 is yet to be merged. It'll need to be merged and pass an SOE prior to my granting approval. Please can you reach out once that PR is merged? Thanks!

**Comment by jgrassel** [comment]
Merged yesterday morning, so should be good

From: Dave Waddling ***@***.***>
Date: Monday, March 6, 2023 at 9:55 AM
To: OpenLiberty/open-liberty ***@***.***>
Cc: Jody A Grassel ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [OpenLiberty/open-liberty] Support JDK 20 in Open Liberty: Feature Test Summary (Issue #24538)
Hi @jgrassel, this FTS looks good though I note that the additional testing being delivered in #24541 is yet to be merged. It'll need to be merged and pass an SOE prior to my granting approval. Please can you reach out once that PR is merged?
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

Hi @jgrassel<https://github.com/jgrassel>, this FTS looks good though I note that the additional testing being delivered in #24541<https://github.com/OpenLiberty/open-liberty/pull/24541> is yet to be merged. It'll need to be merged and pass an SOE prior to my granting approval. Please can you reach out once that PR is merged? Thanks!

**Comment by dave-waddling** [comment]
Hi @jgrassel, thanks for getting that testing delivered. Pleased to report that all is passing cleanly in the SOE so I'll add the FAT Focal Approval to the parent feature now :)
