### ISSUE TITLE
Application can't recover from exceptions thrown during startup

### ISSUE THREAD

**Issue by inad9300** [OpenLiberty/open-liberty#24578]
I am opening this ticket as a follow-up to https://github.com/OpenLiberty/ci.maven/issues/1588, as it was determined that the issue belonged to the Open Liberty runtime rather than the Maven plugin.

**Describe the bug**  

Exceptions thrown during application startup lead to the application crashing and being unable to restart even when the source of the problem is fixed. The following message is shown on any application restart attempts thereafter:

> During application startup, the application failed to start because multiple applications were found to have the name of \<my-application-name>.

**Steps to Reproduce**  

From https://github.com/OpenLiberty/ci.maven/issues/1588#issuecomment-1412725373:

> [create] this simple class and [enable] the CDI feature:
> 
> ```java
> @ApplicationScoped
> public class MyObserver {
> 
>     public void onInit(@Observes @Initialized(ApplicationScoped.class) Object bean ) {
>     	Class clazz = this.getClass();
>         // Uncomment to cause failure
>     	//clazz = null;
>     	System.out.println("From onInit(), in " + clazz.toString());    	
>     }
> }
> ```
> [...] All you'd need to do is:
>
> 1. `mvn liberty:run` # Wait for server and app to complete startup. The 'run' goal includes the "all-in-one" aspect of 'dev' (install + configure Liberty, deploy app) but it doesn't run in the "watcher" loop. It just runs the server in the foreground.
> 2. Make your app source change
> 3. `mvn compile` # watch app update
> 4. Make another source change
> 5. `mvn compile` # watch app update again
> [...]

**Expected behavior**  

The application should be able to restart after the code that throws an exception at startup is fixed.

**Diagnostic information:**  
- OpenLiberty Version: I am unable to determine. Actually, I would like help to do so. I believe the Maven plugin keeps it up to date automatically, but I don't know how to control this or how to check what's the current version of Open Liberty that I'm using.
- Affected feature(s): possibly all, don't know specifically
- Java Version: I'm using Docker image `eclipse-temurin:17.0.4.1_1-jdk-jammy`
- server.xml configuration: Please find it in https://github.com/OpenLiberty/ci.maven/issues/1587#issuecomment-1242933252

**Comment by pmd1nh** [comment]
@inad9300 Hi,  can you please collect a trace so I can debug this problem?
In server.xml set,
`
<logging traceSpecification="*=info=enabled:com.ibm.ws.webcontainer*=all:com.ibm.wsspi.webcontainer*=all:HTTPChannel=all:GenericBNF=all:com.ibm.ws.security.*=all:com.ibm.websphere.security.*=all" maxFileSize="50" maxFiles="20" traceFormat="BASIC"/>
`

(logging is on one line)

start the server (let the app the start and crash); dynamically update the onInit() so that the app can start (and show exception).

Thanks,

**Comment by inad9300** [comment]
Here you go. Let me know if there is anything else I can do.

```
[INFO] [AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 18.546 seconds.
[INFO] CWWKM2015I: Match number: 1 is [3/10/23, 9:09:09:301 UTC] 00000028 com.ibm.ws.kernel.feature.internal.FeatureManager            A CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 18.546 seconds..
[INFO] ************************************************************************
[INFO] *    Liberty is running in dev mode.
[INFO] *        Automatic generation of features: [ Off ]
[INFO] *        h - see the help menu for available actions, type 'h' and press Enter.
[INFO] *        q - stop the server and quit dev mode, press Ctrl-C or type 'q' and press Enter.
[INFO] *        
[INFO] *    Liberty server port information:
[INFO] *        Liberty server HTTP port: [ 4000 ]
[INFO] *        Liberty server HTTPS port: [ 4443 ]
[INFO] *        Liberty debug port: [ 7777 ]
[INFO] ************************************************************************
[INFO] Source compilation was successful.
[INFO] [AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:4000/
[INFO] [AUDIT   ] CWWKZ0009I: The application app has stopped successfully.
[INFO] [AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:4000/
[INFO] [AUDIT   ] CWWKZ0003I: The application app updated in 0.940 seconds.
[INFO] [ERROR   ] NO_USER_REGISTRY 
[INFO]                                  defaultOrb
[INFO]                                  10
[INFO] Source compilation was successful.
[INFO] [AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:4000/
[INFO] [AUDIT   ] CWWKZ0009I: The application app has stopped successfully.
[INFO] [AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:4000/
[INFO] [ERROR   ] SRVE0283E: Exception caught while initializing context: java.lang.NullPointerException: Cannot invoke "Object.toString()" because "npe" is null
[INFO]  at com.demo.rest.RestApplication.onInit(RestApplication.java:20)
[INFO]  at jdk.internal.reflect.GeneratedMethodAccessor1342.invoke(Unknown Source)
[INFO]  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[INFO]  at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
[INFO]  at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
[INFO]  at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168)
[INFO]  at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
[INFO]  at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
[INFO]  at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
[INFO]  at jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:125)
[INFO]  at org.jboss.weld.util.Observers.notify(Observers.java:166)
[INFO]  at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
[INFO]  at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
[INFO]  at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
[INFO]  at org.jboss.weld.bootstrap.BeanDeploymentModule.fireEvent(BeanDeploymentModule.java:93)
[INFO]  at org.jboss.weld.module.web.servlet.HttpContextLifecycle.fireEventForApplicationScope(HttpContextLifecycle.java:161)
[INFO]  at org.jboss.weld.module.web.servlet.HttpContextLifecycle.contextInitialized(HttpContextLifecycle.java:147)
[INFO]  at org.jboss.weld.module.web.servlet.WeldInitialListener.contextInitialized(WeldInitialListener.java:99)
[INFO]  at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated(WebApp.java:2468)
[INFO]  at [internal classes]
[INFO] 
[INFO] [ERROR   ] SRVE0265E: Error occured while notifying listeners of web application start: java.lang.NullPointerException: Cannot invoke "Object.toString()" because "npe" is null
[INFO]  at com.demo.rest.RestApplication.onInit(RestApplication.java:20)
[INFO]  at jdk.internal.reflect.GeneratedMethodAccessor1342.invoke(Unknown Source)
[INFO]  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[INFO]  at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
[INFO]  at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
[INFO]  at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168)
[INFO]  at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
[INFO]  at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
[INFO]  at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
[INFO]  at jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:125)
[INFO]  at org.jboss.weld.util.Observers.notify(Observers.java:166)
[INFO]  at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
[INFO]  at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
[INFO]  at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
[INFO]  at org.jboss.weld.bootstrap.BeanDeploymentModule.fireEvent(BeanDeploymentModule.java:93)
[INFO]  at org.jboss.weld.module.web.servlet.HttpContextLifecycle.fireEventForApplicationScope(HttpContextLifecycle.java:161)
[INFO]  at org.jboss.weld.module.web.servlet.HttpContextLifecycle.contextInitialized(HttpContextLifecycle.java:147)
[INFO]  at org.jboss.weld.module.web.servlet.WeldInitialListener.contextInitialized(WeldInitialListener.java:99)
[INFO]  at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated(WebApp.java:2468)
[INFO]  at [internal classes]
[INFO] 
[INFO] [AUDIT   ] CWWKZ0020I: Application app not updated.
[INFO] [AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:4000/
[INFO] Source compilation was successful.
[INFO] [ERROR   ] CWWKS9110E: During application startup, the application failed to start because multiple applications were found to have the name of app. Security authorization policies require that names be unique. Review the application configuration in the server.xml.
[INFO] [ERROR   ] CWWKZ0004E: An exception occurred while starting the application app. The exception message was: com.ibm.ws.container.service.metadata.MetaDataException: CWWKS9110E: Multiple applications have the name app. Security authorization policies requires that names be unique.
```

**Comment by pmd1nh** [comment]
@inad9300 can you upload/attach the trace.log which has detail information? Thanks!

**Comment by inad9300** [comment]
That makes more sense – I was wondering how the previous log could have been useful! :smile: 

Here it is, excepting some content prior to the "Server is started" message that I removed to accommodate for GitHub's upload limits: [trace.log](https://github.com/OpenLiberty/open-liberty/files/10944335/trace.log).

**Comment by scottkurz** [comment]
Would it be helpful to scope this issue specifically to the failure to cleanup + reuse the authorization policies (i.e., the CWWKS9110E: message, etc.)?

I understand from the end-user perspective how, until the app as a whole can be recycled, it looks like one problem with the runtime (and actually it looked like a problem with the Maven plugin until we helped narrow down the real cause).

But I think from the runtime perspective we're most likely going to end up needing to identify and fix these problems one component at time.

@pmd1nh  does that make sense to you?

If so we would probably want to ask @inad9300 to open separate problems for whatever similar issues exist for CDI or JPA .   (Or, if we have enough of an ability to recreate based on the details so far, perhaps we could open them ourselves).

**Comment by pmd1nh** [comment]
I'm able to recreate the problem, using a servlet app instead.  We have internal discussion about this finding.
