### ISSUE TITLE
pluginUtility merge action generates incorrect output for some inputs

### ISSUE THREAD

**Issue by brianxjx** [OpenLiberty/open-liberty#24584]
Merging of a large heterogeneous mix of plugin-cfg.xmls fails to properly organise all of the routes from all of the input plugin configs.

**Comment by mbroz2** [comment]
@brianxjx please update the description of this `release bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=)
