### ISSUE TITLE
MP Config: Investigate how to access elements from the server.xml

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#2459]
With reference to #2442 work out how to access ~variables and~ elements from the server.xml

~`<variable>` elements end up in Liberty's VariableRegistry~
`<appProperties>` elements nested inside `<application>` elements will end up in the OSGi Admin Service

edit: this issue is for the new appProperties element. #2643 will cover using variables.

**Comment by Emily-Jiang** [comment]
Investigate which existing elements from server.xml should be fed into app?

**Comment by tevans78** [comment]
e.g. <variable name="HTTP_default_var" value="8889" />

**Comment by tevans78** [comment]
mpConfig-1.3 created, initial investigation done and code merged. work to access variables or a different global element will be done under issue #2643
