### ISSUE TITLE
Propagate JWT token in case of Authorization Code Flow

### ISSUE THREAD

**Issue by pjk6** [OpenLiberty/open-liberty#24757]
Hi,

I am using the social login feature. After logging in (with Keycloak as OIDC provider) I would like to propagate the JWT token (got from the OIDC provider) to another secured microservice. I’m using the MicroProfile Rest Client to call the other microservice. But I don't know how to get the JWT token (provided by the OIDC provider) so it can be injected as a HTTP header into the call to the other microservice. All examples that I have seen describe this process for the implicit flow, but I haven't seen any examples how to do this for the Authorization Code Flow. Could you please help me?

Peter

**Comment by teddyjtorres** [comment]
Hi @pjk6,

The [Social Login APIs](https://www.ibm.com/docs/en/was-liberty/core?topic=api-websphere-security-social-media-10) can help you do what you need.

First, you can use the [UserProfileManager](https://www.ibm.com/docs/api/v1/content/SSD28V_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.social_1.0-javadoc/com/ibm/websphere/security/social/UserProfileManager.html) API's [getUserProfile()](https://www.ibm.com/docs/api/v1/content/SSD28V_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.social_1.0-javadoc/com/ibm/websphere/security/social/UserProfileManager.html#getUserProfile()) method to get the [UserProfile](https://www.ibm.com/docs/api/v1/content/SSD28V_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.social_1.0-javadoc/com/ibm/websphere/security/social/UserProfile.html). Then, use either UserProfile's [getAccessToken()](https://www.ibm.com/docs/api/v1/content/SSD28V_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.social_1.0-javadoc/com/ibm/websphere/security/social/UserProfile.html#getAccessToken()) (if the access token is a JWT token), or [getIdToken()](https://www.ibm.com/docs/api/v1/content/SSD28V_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.social_1.0-javadoc/com/ibm/websphere/security/social/UserProfile.html#getIdToken()) to obtain the JWT you need. For getIdToken(), the object returned is a [com.ibm.websphere.security.jwt.JwtToken](https://www.ibm.com/docs/api/v1/content/SSD28V_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.jwt_1.1-javadoc/com/ibm/websphere/security/jwt/JwtToken.html) instance. You can call its [compact()](https://www.ibm.com/docs/api/v1/content/SSD28V_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.jwt_1.1-javadoc/com/ibm/websphere/security/jwt/JwtToken.html#compact()) method to get the encoded value that is ready to use in the Authorization header in the call to the other microservice.

Thank you for using the Social Login feature.

Regards,
Teddy

**Comment by pjk6** [comment]
Hi Teddy,

Thanks a lot for your explanation! 

Regards,

Peter
