### ISSUE TITLE
Encrypted value for internalClientSecret within oauthProvider does not work

### ISSUE THREAD

**Issue by shubjit** [OpenLiberty/open-liberty#24804]
**Describe the bug**  
**internalClientSecret** and **internalClientId** parameters values within oauthProvider configuration of OpenID Connect Server are used to generate tokens for PersonalTokenManagement and UsersTokenManagement UI pages. Our customers use this feature for Non Web clients. However, if we encrypt the internalClientSecret value via securityUtility , the PersonalTokenManagement/UsersTokenManagement UI pages no longer works. Logs complain that ClientId and Secret are invalid.

**clientSecretEncoding** parameter, default seems to be **xor**, this does not seem to work for internalClientSecret attribute.

**Steps to Reproduce**  
Enable OpenID Connect Server feature and configure it to enable PersonalTokenManagement and UsersTokenManagement UI pages.
https://openliberty.io/docs/latest/reference/config/oauthProvider.html

Encrypt the value for **internalClientSecret**

Sample of oidcConnectProvider from server.xml below.

```
   <openidConnectProvider id="myTest" oauthProviderRef="MYTEST" sessionManaged="true" />

        <oauthProvider id="MYTEST"
               httpsRequired="true"
                autoAuthorize="true"
                accessTokenLifetime="7201" 
                authorizationGrantLifetime="604801"
                internalClientId="new-client"
                internalClientSecret="{xor}Pi8vci8+LCwoMC07"
                passwordGrantRequiresAppPassword="true"
                trackOAuthClients="true">
                <databaseStore dataSourceRef="MYDB" />
        </oauthProvider>
```

**Expected behavior**  
Encrypted passwords should be accepted and PersonalTokenManagement/UsersTokenManagement UI pages should be accessible.

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.12
 - Affected feature(s) openidConnectServer-1.0

**Additional context**  
If plain text value of the ClientSecret is updated as internalClientSecret value, the PersonalTokenManagement/UsersTokenManagement UI pages loads fine.

**Comment by ayoho** [comment]
@shubjit Thanks for opening this issue. I've just delivered https://github.com/OpenLiberty/open-liberty/pull/24805 that should resolve this issue. The fix should be available in the next release of Open Liberty.

**Comment by shubjit** [comment]
Thank you @ayoho for such for speedy fix. I will test on the next release and report if there are issues.

**Comment by shubjit** [comment]
Tested on 23.0.0.4 and it now works with encrypted values for internalClientSecret.
Thank you @ayoho
