### ISSUE TITLE
SpringBoot 3.0: Continuation placeholder

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#24850]
This placeholder represents the remainder of work required for open-liberty support of SpringBoot 3.0.

Search for issues with the text prefix "SpringBoot 3.0" or for the label "springboot-3.0" for a list of current issues.

The current issues are incomplete as regards providing complete support: As they are completed, additional issues will be created to represent additional discovered work.

Holding open until the release of Spring 3.0 support, at which time any outstanding work should have issues, and this placeholder will no longer be necessary.

**Comment by tbitonti** [comment]
Child of #19982.

**Comment by hlhoots** [comment]
Now that SB 3 has been delivered, closing this issue out.
