### ISSUE TITLE
[spring boot feature] Figure out the port for the virtual host

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#2486]
When configuring a virtual host for a spring boot application we need to be able to figure out what port is being used.  For explicit port settings this is not an issue because we know the port ahead of time when we are configuring the virtual host.  The issue is when zero is used then we will not know the port until the virtual host is opened.

This is needed to correctly report the listening port from org.springframework.boot.context.embedded.EmbeddedServletContainer.getPort()

**Comment by tjwatson** [comment]
Anjum has been looking into this one.  Reassigning.

**Comment by covener** [comment]
please keep in mind the common scenario where the virtual host / host aliases do not include any listening port. This includes an appserver behind a HTTP proxy or an IP sprayer doing NAT / portmapping.
