### ISSUE TITLE
[spring boot feature] session configuration 

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#2487]
Spring boot many settings for controlling session behavior:

server.session.cookie.comment
server.session.cookie.domain
server.session.cookie.http-only
server.session.cookie.max-age
server.session.cookie.name
server.session.cookie.path
server.session.cookie.secure
server.session.persistent
server.session.store-dir
server.session.timeout
server.session.tracking-modes

Need to investigate what these settings do and if they can be configured on liberty.

**Comment by tjwatson** [comment]
For session support we will be only supporting the settings in server.xml for things like:

server.session.persistent
server.session.store-dir
server.session.timeout

This task should be used to issue a warning if these options are used by a spring boot application.

**Comment by sebratton** [comment]
There are many session setting. For purposes or generating a warning, there will only be one issue if one or more of the following conditions are true:
-- isPersistentSession == true
-- getSessionTimeout != 30*60 (30 mins in seconds)

**Comment by tjwatson** [comment]
This is fixed in master.
