### ISSUE TITLE
Feature Test Summary for: SameSite=None incompatible Clients

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#24902]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

### List of FAT projects affected

* com.ibm.ws.webcontainer.servlet.4.0_fat.2

### Test strategy

* What functionality is new or modified by this feature?
`The behavior of SameSite=None header on cookies that are being sent to an incompatible client from the list [here](https://www.chromium.org/updates/same-site/incompatible-clients/) has been modified to be explicitly removed before being sent to the browser.`
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)

`The positive FAT tests for functionality submit a request to a servlet with specific User-Agents that are within the ranges of incompatible versions and check that the correct number of SameSite=None cookies are in the response. These tests are executed for every combination of incompatible client (UCBrowser, iOS, MacOS w/ Safari, MacOS w/ Embedded Browser, Chrome). We check how many cookies with SameSite=None headers are received in the response. We generate SameSite=None cookies in four different ways to guarantee the change works on all forms of cookie generation: request.getSession(), through server.xml, request.setHeader(...), and request.addHeader(...). Additionally, we maintain one default cookie to ensure there is no error with the request/response communication, if this cookie isn't received something went wrong. If an expected incompatible client version is sent in the User-Agent we expect to only get one (default cookie) as the correctCookieCount. If an expected compatible client version is sent in the User-Agent we expect to get 5 as the correctCookieCount (the four SameSite=None cookies + default).`
`The positive Unit tests also check specific User-Agents for compatibility. The primary difference between the Unit and FAT tests is that the Unit tests just check whether the User-Agent string gets returned as compatible/incompatible by the implementation, while the FAT tests actually send cookies and verify that the SameSite=None is removed from them when incompatible.`
`There are no negative tests, read below for explanation.`

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)
`N/A`

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

`I indicated a three because there is "minimal coverage of the error/outlying scenarios", however, this change will not cause any errors because of its inherent behavior. We just check **very** specific versions for being incompatible and remove the SameSite=None if that specific conditional is met. Otherwise, the cookies continue behaving as they have in all previous OpenLiberty versions. This change will only add beneficial behavior for the specific versions that are being checked.`

**Comment by dave-waddling** [comment]
Hi @pnicolucci, thanks for completing this FTS. The test strategy and coverage make sense and I think a confidence of 3 is acceptable for this feature, thank you for sharing your reasoning.

There is some defect work needed prior to approval and so I've reached out to you directly in Slack.
