### ISSUE TITLE
Update to EclipseLink 3.0.4

### ISSUE THREAD

**Issue by dazey3** [OpenLiberty/open-liberty#24978]
When EclipseLink 3.0.4 releases, update `io.openliberty.persistence.3.0.thirdparty` and deliver the new release

- revert #24977

**Comment by tkburroughs** [comment]
For reference, here is the PR for the last time this was done (i.e. 3.0.2 to 3.0.3) : https://github.com/OpenLiberty/open-liberty/pull/22016

**Comment by tkburroughs** [comment]
All work complete; closing.
