### ISSUE TITLE
Speed up com.ibm.ws.logging_fat

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#24970]
RTC 295561

The com.ibm.ws.logging_fat runs more than 3 hours in SOE builds and it failed with a timeout.

We either need to speed this up or split this into 2 buckets.

**Comment by fmhwong** [comment]
[fatoutput-com.ibm.ws.logging_fat.zip](https://github.com/OpenLiberty/open-liberty/files/11201307/fatoutput-com.ibm.ws.logging_fat.zip)

**Comment by tonyreigns** [comment]
Leaving issue open until I can verify that the logging failure isn't reoccurring.
