### ISSUE TITLE
server version command ignores JAVA_HOME set in server's server.env

### ISSUE THREAD

**Issue by ninadaa** [OpenLiberty/open-liberty#24981]
**Describe the bug**  
The `server version <serverName>` command ignores the `JAVA_HOME` variable that is set in the server's `server.env`file.
Instead it prints out the java version info of the java installation set by `JAVA_HOME` variable in shell environment (bash).

**Steps to Reproduce**  
 * set `JAVA_HOME` in shell envionment (e.g. set to Semeru 8 installation)
 * create server `myServer` and add `server.env` in `${WLP_INSTALL_DIR}/usr/servers/myServer/server.env`
 * set  `JAVA_HOME` (e.g. set to Semeru 11 installation) in `${WLP_INSTALL_DIR}/usr/servers/myServer/server.env`
 * run `${WLP_INSTALL_DIR}/bin/server version myServer`

**Expected behavior**  
When I run `server version <serverName>`  I expect it to display the version info related to the java installation I specified in the `server.env` of the server.

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.3

**Additional context**  
Works as expected if I change the server script to:
```
  version)
    #installEnv
    serverEnv
    javaCmd '' --version
```

**Comment by cbridgha** [comment]
Just to confirm...  `server start` does pickup the correct version right?  as seen in the logs...   
But I have confirmed this issue with the `server version` command. = We will investigate.

**Comment by cbridgha** [comment]
@ninadaa I did confirm if a server.env file is added to `${wlp.install.dir}/etc/server.env`. those values are picked up by the `server version` command.   still investigating as we do see some inconsistencies...

**Comment by ninadaa** [comment]
> Just to confirm... `server start` does pickup the correct version right? as seen in the logs... But I have confirmed this issue with the `server version` command. = We will investigate.

@cbridgha yes, `server start` picks the correct Java, only  `server version` does not.

**Comment by jimblye** [comment]
See opening comment in the [pull request](https://github.com/OpenLiberty/open-liberty/pull/25200).
