### ISSUE TITLE
Avoid static lock for BufferManagerImpl

### ISSUE THREAD

**Issue by Arjun-Sharma1** [OpenLiberty/open-liberty#2498]
Change implementation to avoid using the static lock: 
private static final ReentrantReadWriteLock RERWLOCK = new ReentrantReadWriteLock(true);

(move EMQ to separate class to avoid needing a static lock)

**Comment by ewhoch** [comment]
This was reverted in #2587, you can revert the revert commit in that PR to expedite redelivery with a fix.
