### ISSUE TITLE
Posting Form-Data with the new Jakarta EE 10 Multipart Support fails

### ISSUE THREAD

**Issue by gcw-it** [OpenLiberty/open-liberty#25017]
**Describe the bug**  
When posting multipart/form-data to a REST endpoint using the **@FormParam** annotation for an **EntityPart** or **InputStream** parameter, the request fails with a **400 Bad Request** response, and the following exception is logged:

```
jakarta.ws.rs.BadRequestException: RESTEASY003320: Failed processing arguments of public java.lang.String com.demo.rest.TestResource.upload(java.lang.String,jakarta.ws.rs.core.EntityPart) throws java.io.IOException
at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:120)
Caused by: java.lang.UnsupportedOperationException: SRVE8020E: Servlet does not accept multipart requests
at com.ibm.ws.webcontainer.srt.SRTServletRequest.prepareMultipart(SRTServletRequest.java:3838)
```

During deployment, when using an **EntityPart** parameter, the following warning is logged:
`SROAP04005: Could not find schema class in index: jakarta.ws.rs.core.EntityPart`

**Steps to Reproduce**  
Using a simple REST endpoint like the following, causes the error:
    
```
@POST
@Consumes(MediaType.MULTIPART_FORM_DATA)
public Response upload(@FormParam("file") EntityPart file) {
    return Response.accepted().build();
}
```
**Expected behavior**  
The form-data is submitted successfully and in this example, a **202 Accepted** response is sent.

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.3/wlp-1.0.75.cl230320230319-1900
 - Affected feature(s): jakartaee-10.0
 - Java Version: 
```
openjdk 17.0.6 2023-01-17
IBM Semeru Runtime Open Edition 17.0.6.0 (build 17.0.6+10)
Eclipse OpenJ9 VM 17.0.6.0 (build openj9-0.36.0, JRE 17 Linux amd64-64-Bit Compressed References 20230117_397 (JIT enabled,, AOT enabled)
OpenJ9   - e68fb241f
OMR      - f491bbf6f
JCL      - 927b34f84c8 based on jdk-17.0.6+10)
```
 - server.xml configuration: The default configuration from the current quickstarter:
```
<server description="test server">
  <featureManager>
    <feature>jakartaee-10.0</feature>
    <feature>microProfile-6.0</feature>
  </featureManager>
  <basicRegistry id="basic" realm="BasicRealm">
  </basicRegistry>
  <httpEndpoint id="defaultHttpEndpoint" httpPort="9080" httpsPort="9443" />
  <applicationManager autoExpand="true"/>
  <webApplication contextRoot="/test" location="test.war" />
  <ssl id="defaultSSLConfig" trustDefaultCerts="true" />
</server>

```

**Additional context**  
When using a **List&lt;EntityPart&gt; parts** method signature for the REST endpoint the error doesn't occur.

The problem can be mitigated by using a **web.xml** deployment descriptor with a suitable multipart configuration for the REST application, e.g.:

```
<servlet>
  <servlet-name>com.demo.rest.RestApplication</servlet-name>
  <multipart-config>
    <location>/tmp</location>
    <max-file-size>10485760</max-file-size>
    <max-request-size>2097152</max-request-size>
    <file-size-threshold>1048576</file-size-threshold>
  </multipart-config>
</servlet>
<servlet-mapping>
  <servlet-name>com.demo.rest.RestApplication</servlet-name>
  <url-pattern>/api/*</url-pattern>
</servlet-mapping>
```

**Comment by igbluz** [comment]
Hi @jim-krueger: I also found the same problem as you, I wanted to use
```
Response process(@FormParam("dossier") EntityPart dossier,
                 @FormParam("zipFile") InputStream zifFile) {
            
}
```
and finished with the same error. So I used List<EntityPart> which solved by now the problem. But having OpenApi in mind the FormParam should do it's job.

**Comment by kirankumar99** [comment]
Hi, I am submitting the form with files using jquery+Ajax by using FormData to Jakarata REST API 3.1. For me @FormParam EntityPart partname is working. But List<EntityPart> parts parameter is not working. when I print size of the parts in the REST method its giving me 0. any suggestion.. Thanks

**Comment by jim-krueger** [comment]
Hi @kirankumar99,   Can you please open a new issue for this with details containing what version of Open Liberty you are using, the scenario you are running, and the problem you are experiencing?    Thanks
