### ISSUE TITLE
Feature Test Summary - Configuration options to change the MP OpenAPI endpoints

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#25071]
## Test Strategy

Basic FAT tests which just check an HTTP request succeeds ensure that each endpoint can be reached are run in lite mode.

Selenium tests which ensure that the UI can be loaded and interacted with are run in full mode since they're slower. (Note we have existing Selenium tests which do run in lite mode with the endpoints in their default locations.)

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

### List of FAT projects affected

* com.ibm.ws.microprofile.openapi_fat
* io.openliberty.microprofile.openapi.ui.internal_fat

### Test strategy

* Make both endpoint locations configurable
  * Test that the endpoint shows up in the appropriate location
  * Test that there is a log message saying where the endpoint is
  * Test edge cases and invalid values for the endpoint (e.g. `/`, `.`, `..`, empty string, special characters)
  * Test setting the endpoint location to be the same as an application and another liberty feature endpoint
  * Test changing the config while the server is running
* The default UI endpoint is defined relative to the OpenAPI document endpoint
  * Test that the UI is at the correct location when only the OpenAPI document endpoint location is configured
* The UI needs to fetch the OpenAPI document from its endpoint
  * Add Selenium tests to ensure that the UI can find the OpenAPI document when custom endpoint locations are configured
* The UI still works for Authentication flows
  * Add Selenium tests to ensure that the UI can still perform an OAuth Login flow when custom endpoints locations are configured
  * Follow Manual test guide as defined here https://github.com/OpenLiberty/openapi-ui-test-app#check-our-modifications-to-swagger-ui-are-present for default and set paths 

## Confidence Level

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

**Comment by ayoho** [comment]
LGTM 👍
