### ISSUE TITLE
MP Config 1.3 Epic

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#2508]
MP Config 1.3 Epic

Feature 250909: User server.xml as the dynamic config source in OL
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=250909

The eclipse milestone is
https://github.com/eclipse/microprofile-config/milestone/4

**Comment by marikaj123** [comment]
https://bigblue.aha.io/features/API-2

**Comment by marikaj123** [comment]
beta blog_aug2018

**Comment by dave-waddling** [comment]
**FAT Focal Approval:** The mid-week SOE has good coverage of the MicroProfile Config buckets at this point and everything is passing acceptably. Approval granted.

**Comment by Emily-Jiang** [comment]
https://ibm.box.com/s/gezy61f5mnlr0yfpv4lmcc504duct5ma

**Comment by tevans78** [comment]
All dev work done, all approvals in place. Closing!!

**Comment by marikaj123** [comment]
Blog GA Info:  https://github.ibm.com/was-liberty/WS-CD-Open/issues/13159
