### ISSUE TITLE
Incompatable features for version 21.0.0.7

### ISSUE THREAD

**Issue by lancechant** [OpenLiberty/open-liberty#25107]
Hi there

We are upgrading from 21.0.0.1 to 21.0.0.7 and we have had the features pretty much the same except using microprofile-4.0 instead of 3.0. But as we upgraded to 21.0.0.7 (the other versions between were okay) we have this error 

`[INFO] [ERROR   ] CWWKF0033E: The singleton features com.ibm.websphere.appserver.javax.persistence.base-2.2 and com.ibm.websphere.appserver.javax.persistence.base-2.1 cannot be loaded at the same time.  The configured features appSecurity-3.0 and ejbPersistentTimer-3.2 include one or more features that cause the conflict. Your configuration is not supported; update server.xml to remove incompatible features.
[INFO] [WARNING ] CWWKF0046W: The configuration includes an incompatible combination of features. As a result, the feature manager did not install any features.`
Is there a way to fix this issue between appSecurity-3.0 and ejbPersistentTimer-3.2

We did a test with the latest version of OL, and had the same issue, we are just slowly going through each version to ensure no issues.

This is the feature list we currently use:

`<featureManager>
        <feature>microProfile-4.0</feature>
        <feature>usr:opentracingZipkin-0.33</feature>
        <feature>ejbLite-3.2</feature>
        <feature>jms-2.0</feature>
        <feature>beanValidation-2.0</feature>
        <feature>jdbc-4.3</feature>
        <feature>localConnector-1.0</feature>
        <feature>appSecurity-3.0</feature>
        <feature>jaxws-2.2</feature>
        <feature>jpaContainer-2.2</feature>
        <feature>ejbPersistentTimer-3.2</feature>
        <feature>mpContextPropagation-1.2</feature>
    </featureManager>
`

**Comment by NottyCode** [comment]
Have you tried with 23.0.0.3? 21.0.0.7 is almost two years old now, there were a few releases which had install issues that caused this kind of symptoms, but I believe they were all fixed. It is likely that you need to upgrade to a newer release.

**Comment by lancechant** [comment]
Yes I did test on 23.0.0.3 @NottyCode  and had the exact same error. I just mentioned the version that caused the issue to start which was 21.0.0.7 as 21.0.0.6 seems to be fine.

It seems to be with ejbPersistentTimer-3.2 as after a few rebuilds with different configs, that was always there and a different feature. it even complained about conflicting with microProfile-4.0

**Comment by lancechant** [comment]
Here is a repo that shows there error when the server is started with mvn liberty:dev https://github.com/lancechant/OL-singleton-error

**Comment by bpaskin** [comment]
With the features you listed in the original message I do not receive an error running 23.0.0.3 with Java 17.  I do receive an error from your code in your git repo. -Brian

**Comment by lancechant** [comment]
Hey @bpaskin , we are using java 11 for our project. And do you see anything wrong with the code in my repo? as it never complained before on the older version

**Comment by lancechant** [comment]
I found the issue, it was because of the `liberty-maven-plugin` plugin from maven. We were using version 3.1, but seems like that has some incompatibility with the newer versions, upgrading the plugin to 3.5.1 seems to fix it. I don't see anywhere saying which versions of OL it supports, and the feature list it uses if using an older version seems to cause the issue

**Comment by jhanders34** [comment]
https://github.com/OpenLiberty/ci.common/pull/277 has the details about the change in 21.0.0.7 that necessitated an update to the liberty maven plugin (LMP).  LMP version 3.4 and later has the fix.  Hopefully this explains why you were seeing this problem and why moving to a new version of the LMP resolved it.  I am going to close out this issue.  If you believe more needs to be done for this issue, please let me know.
