### ISSUE TITLE
MP Fault Tolerance 1.1 Epic

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#2511]
MP Fault Tolerance 1.1 Epic

249157: 1Q18 MicroProfile fault tolerance feature for Liberty
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemName/com.ibm.team.workitem.WorkItem/249157

The milestone is
https://github.com/eclipse/microprofile-fault-tolerance/milestone/3

Feature test summary:
https://github.com/OpenLiberty/open-liberty/issues/2515

**Comment by bsbyrd1** [comment]
My approval is based on the sizing of the ID work, and the expectation that the ID work can be completed before the last ID translation drop.

**Comment by Emily-Jiang** [comment]
STE: https://ibm.box.com/s/ibpr6szoddcasyuaaerlnobn7duktzog

**Comment by dave-waddling** [comment]
**FAT Focal Approval:** Feature Test Summary looks good and this is passing well in the SOE. Approval granted.

**Comment by marikaj123** [comment]
Blog GA Info: https://github.ibm.com/was-liberty/WS-CD-Open/issues/13158

**Comment by tevans78** [comment]
All done! Closing!
