### ISSUE TITLE
Feature Test Summary for OIDC Client PKCE support

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#25150]
## Test Strategy

**Test possible settings of the openidConnectClient and oidcLogin configuration attribute pkceCodeChallengeMethod.**

### List of FAT projects affected

* com.ibm.ws.security.oidc.client_fat.3
* com.ibm.ws.security.social_fat.LibertyOP.3

### Test strategy

* A new configuration attribute, pkceCodeChallengeMethod,  was added to the OIDC client config (openidConnectClient) and Social client config (oidcLogin) pkceCodeChallengeMethod.  
* Test that the client passes code_challenge and code_challenge_method as appropriate based on the setting of pkceCodeChallengeMethod
* Tests were created that set pkceCodeChallengeMethod to S256, plain, and disabled (as well as tests without setting  pkceCodeChallengeMethod) both with the OP client config attribute proofKeyForCodeExchange set to true or false.  All combinations of these config attributes were tested.  The tests verify that access to a protected is granted when appropriate and that the correct error status and messages are issued when access should not be granted.  Tests are also run using different signature algorithms.
* The same test combinations were created for an OIDC client and a Social client (using oidcLogin).
* The OP endpoints have already been tested to verify that they behave properly when code_challenge, code_challenge_method and code_verifier are omitted or incorrect, so that is not the focus of these tests.
* There are no manual tests needed to verify this feature.

## Confidence Level

5

**Comment by c00crane** [comment]
https://github.com/OpenLiberty/open-liberty/issues/19029

**Comment by c00crane** [comment]
First delivery of FAT - https://github.com/OpenLiberty/open-liberty/pull/25146
Add FAT in support of pkceCodeChallengeMethod="disabled" - https://github.com/OpenLiberty/open-liberty/pull/25341

**Comment by dave-waddling** [comment]
Looks good to me, though currently gating approval on the delivery of #25341 and a large number of untriaged defects in the Security FA.

**Comment by dave-waddling** [comment]
Hi @c00crane, thanks for looking over those defects. I can confirm SOE results are looking good so I'll add the approval to the feature epic now.
