### ISSUE TITLE
Remote EJB Transaction propagation     Liberty does support outbound or inbound transaction propagation?

### ISSUE THREAD

**Issue by AngeloRubens** [OpenLiberty/open-liberty#25269]
Hi All,

the last version of openliberty does  support remote ejb outbound or inbound transaction propagation?

Thanks.

**Comment by NottyCode** [comment]
We already have something open to track enabling this: https://github.com/OpenLiberty/open-liberty/issues/8967

I understand that this does work in limited scenarios such as if the JVMs are co-installed.
