### ISSUE TITLE
Feature Test Summary for Update Resolver so that it can better handle tolerates

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#25262]
Parent epic:
- #21992

## Test Strategy

When installing from the command line, all tolerated dependencies of the requested features will be installed. I.e. if a feature depends on `servlet-4.0` and tolerates `5.0` and `6.0`, `servlet-4.0`, `servlet-5.0` and `servlet-6.0` will all be installed. Previously, only `servlet-4.0` would be installed in this scenario.

This change is implemented with a change to the Repository Resolver: when `resolve()` is called, it will walk the dependency tree and return all tolerated versions of all dependencies of the requested features.

Though this is a small change semantically, it requires a change of approach in the way we resolve features. We used to delegate much of the resolution logic to the kernel feature resolver, but now this resolution will be done entirely within the repository resolver.

We will rely heavily on the existing suite of repository resolver tests and install tests to ensure that we haven't broken the resolution logic or changed it in a way that was not intended. Where the behaviour has been deliberately changed we will update the existing tests. For the problematic scenarios identified in the issue we will add new tests.

### List of FAT projects affected

* `com.ibm.ws.install.featureUtility_fat`

_Note: the repository resolver has a large suite of unit tests within `com.ibm.ws.repository.resolver`_

#### `RepositoryResolver.resolve()` is now completely handled by `RepositoryResolver`.

Previously we were relying on the kernel resolver to do some of the work. Now we're doing the work ourselves, there were a few areas where our test coverage needed improving.

  * Run existing install FAT tests and RepositoryResolver unit tests
  * New unit test: `testAutoFeatureDependencySatisfiesAnotherAutoFeature`
    * test for an autofeature having dependencies which then allow additional autofeatures to be activated
  * New unit test: `testAutoFeatureSatisfiedByNewFeatureAndInstalledFeature`
    * test for an autofeature becoming satisfied by a combination of existing features and newly installed features
  * New unit test: `testDontInstallFeaturesWhichEnableInstalledAutoFeature`
    * We have logic (and tests) to install the features which enable an autofeature if the user requests install of the autofeature from the command line. This tests ensures we _don't_ install features which enable an autofeature if the autofeature _wasn't_ specifically requested

#### `resolve()` should return all tolerated dependencies of the requested features

  * Ensure all existing repository resolver unit tests run both with `resolveAsSet` and with `resolve`, asserting the correct output for each
    * Previously tolerated dependencies were only considered when doing `resolveAsSet` and so most of the tolerated 
dependency unit tests did not test using `resolve()`
    * `testSet`
    * `testSetTransitivePublic`
    * `testSetTransitivePrivate`
    * `testSetTransitivePrivateTolerateNewer`
    * `testInstalledFeatureNeedsDifferentToleratedDependency`
    * `testInstalledAutoFeatureNeedsDifferentToleratedDependency`
  * New install FAT test: `testComplexVersionTolerates`
    * Test that installing `RestfulWS-3.0` installs all the tolerated dependencies
  * New install FAT test: `testResolveAsSetThenResolve`
    * Install from a server.xml containing `javaee8` + `adminCenter-1.0` (which will use resolveAsSet()) then install `jakartaee-9.1` from the command line (which will use resolve()). Check that the adminCenter private feature for EE9 support is installed.

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

**Comment by ayoho** [comment]
LGTM 👍
