### ISSUE TITLE
InstantOn Feature Test Summary

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#25294]
## Test Strategy

This the test summary for Open Liberty InstantOn Epic #16384 

The initial release of the InstantOn feature will only support Linux x86-64 platforms running with the latest Semeru Java releases for Java versions 17 and 11.  The Linux x86-64 machine must be running with Kernel version 5.9 or higher and must `criu` installed built from the `criu` fork maintained by the by the IBM Semeru Runtimes at https://github.com/ibmruntimes/criu.git where the current branch being tested is `march_ea_23`.

The test strategy for the initial release is not running the InstantOn FAT tests on the standard SOE farm of test machines.  This is because the Semeru Java support for CRIU is still in Early Access at the time of this writing.  The Semeru Java support for CRIU will have a publicly available release at the time Open liberty InstantOn has a GA release.  Once we have a Semeru Java release for Java 17 and Java 11 then the SOE build definitions can be updated as appropriate to be able to run the Open Liberty InstantOn FAT tests.

There is a requirement to be able to run the InstantOn FATs regularly against the `integration` branch now during the development of Open Liberty InstantOn and for the initial release of Open Liberty InstantOn.  To achieve this without impacting the existing SOE build definitions a new InstantOn build queue has been created.  This queue uses Ubuntu 22.04 x86-64 machines that have the required `criu` binary version installed from the CRIU fork at https://github.com/ibmruntimes/criu.git.  The build queue uses an array of 10 machines that are split into the following:

1. Five machines using the latest Semeru Early Access CRIU support Java 11 version
2. Five machines using the latest Semeru Early Access CRIU support Java 17 version

Daily builds are run on this queue against the `integration` branch of Open Liberty.  Additional, personal builds can be submitted to run updates from development branches used for a PR.  Each build on this queue will run the list of InstantOn FAT projects 10 times each.  This ensures that the FATs are run evenly across both Java 11 and Java 17 to ensure adequate coverage.  It also helps understand the stability of the tests being able to pass 10 times each build run.

FAT buckets for InstantOn fall into two types:

1. Buckets that require a fully supported CRIU host environment, including the correct version of Semeru Java that supports CRIU
2. Buckets that use an InstantOn stub that can mimic the prepare/restore hook execution as if it is running a checkpoint/restore but it is all done in a single normal Java process.

For buckets that require a fully supported CRIU host environment a new annotation called `componenttest.annotation.SkipIfCheckpointNotSupported` has been added which test classes can use to skip all tests within a test class or skip individual tests within a test class.  Tests with this annotation will be skipped if the host environment does not have the necessary prerequisites to support Open Liberty InstantOn.

Buckets that use an InstantOn stub for their test server (bootstrap property `io.openliberty.checkpoint.stub.criu=true`) can successfully run on any platform, there should be no need to scope these tests to only run on CRIU InstantOn supporting hosts.

Enhancements have been made to `componenttest.topology.impl.LibertyServer` to enable a testcase to configure a checkpoint to be taken for a test server instance.  The `LibertyServer` can then be used to restore the liberty server from the checkpoint and test against it.  Additionally, hooks are available to allow FAT test code to run at specific time.  For example, to do some configuration change to the server between the time a server is checkpointed to the time it is restored.  This is essential to testing out scenarios that apply configuration to a checkpointed Open Liberty process and then ensure the restored Liberty process behaves as expected according the the configuration at restore time.

### List of FAT projects affected
For InstantOn a strategy was taken to develop new FAT buckets instead of enhancing existing buckets.  This was to make it easier to reason about the FATs that require full CRIU supporting hosts.  The following buckets are the current set that require full CRIU supporting hosts:

* io.openliberty.checkpoint_fat
* io.openliberty.checkpoint_fat_beanvalidation
* io.openliberty.checkpoint_fat_persistence
* io.openliberty.checkpoint_fat_security_oidc_social
* io.openliberty.checkpoint_fat_transaction

These sets of tests are regularly run on the InstantOn build queue: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewDefinition&id=_driBwMB2EeyMPMLKUarGFg

The following buckets use the InstantOn stub (`io.openliberty.checkpoint.stub.criu=true`) and therefore do not require a full CRIU supporting host to run.  These tests execute with all the normal PR `#build` as well as on all the SOE test machines each run.

* com.ibm.ws.jpa.tests.container.checkpoint_jpa_2.1_fat
* com.ibm.ws.jpa.tests.container.checkpoint_jpa_2.2_fat
* com.ibm.ws.jpa.tests.container.checkpoint_jpa_3.0_fat
* com.ibm.ws.jpa.tests.container.checkpoint_jpa_3.1_fat
* io.openliberty.ejbcontainer.checkpoint_fat

### Test strategy

* What functionality is new or modified by this feature?
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

We rate our confidence level at 3.5:

> The InstantOn feature covers a very large set of Open Liberty features for a new piece of functionality.  The FATs attempt to cover as much as possible such that we can release the initial support for InstantOn in a reasonable amount of time.  We ensured that we have tests that enable each supported feature for InstantOn and developed a set of applications that exercise the various features.  We also have a set of configuration tests for the various features but we do not have as large of coverage on the configuration updates as there could be.  Test improvements for InstantOn will be a continuous effort as we gain more user experience with the functionality.  One such area that needs attention is in-container testing.  Right now we are depending on SVT to do the bulk of our automated container testing.  We need to pull this testing into development tests to catch issues earlier.  Other areas include expanding our coverage against supported Databases, making sure Server wide MP configuration changes work.

**Comment by anjumfatima90** [comment]
**General test behavior**

The tests encompasses testing both phases of checkpoint namely BEFORE_APP_START and AFTER_APP_START. However, in most of the tests, the checkpoint is performed after the application has started. This means that the tests primarily focus on verifying the behavior and functionality of the application on restore with a checkpoint being executed after the application has been initialized and is in a running state before the ports are open.

In positive tests, the aim is to verify the successful completion of each step (checkpoint/restore) as expected. This involves ensuring that the expected page, response, and response status are received, both with and without configuration updates. 

The negative tests focus on validating the proper handling of error scenarios. This includes verifying that the response contains the correct status code and message or full text. Additionally, the tests check if the server logs display the correct error messages and, if applicable, check for the occurrence of any expected FFDC events. 

The tests are repeated to test EE8, EE9 and EE10 features.

**List of FAT projects affected**

1. **io.openliberty.checkpoint_fat** 

- **BasicServletTest:**
     Features tested: servlet-4.0, servlet-5.0, servlet-6.0

     The test is conducted to validate the accessibility of the endpoint during the restore process of a simple servlet. The 
     checkpoint is performed after the application has started (AFTER_APP_START). The test aims to verify if the  expected 
     application page response is received during restore.

- **CheckpointFailTest:**

     The tests cover different scenarios in which the checkpoint can fail and ensure that the CheckpointFailedException is thrown 
      in those cases. Additionally, the tests verify that few failures occurring during the restore process do not result in the 
      throwing of a CheckpointFailedException. This validation ensures that any issues or failures during the checkpoint or 
      restore process are properly detected and reported through the appropriate exception.

- **CheckpointPhaseTest:** 

     The tests cover both phases in which the checkpoint can be performed, namely BEFORE_APP_START and 
     AFTER_APP_START. The tests ensure that the application hits the endpoint after every restore when the server is restored 
     multiple times. The tests also examine the behavior when multiple checkpoints are executed without a clean start, resulting 
     in the application hitting the endpoint during the restore process.

- **LogsVerificationTest:**

     The tests encompass the evaluation of messages and trace logs in various scenarios. They ensure that new log files are 
     generated during the checkpoint and restore processes. Also ensures that configuration specified by the bootstrap property 
     "com.ibm.ws.logging.max.files" controls the number of newly created logs. In the event that the messages log is deleted 
     after a checkpoint, a new file should be created during the restore process. Furthermore, the tests validate that the 
     environment property for message formatting, set after the checkpoint, is correctly applied during the restore. Additionally, 
     the tests verify the presence of appropriate logs for hidden messages. 

- **OSGiConsoleTest:** 
     Features tested: osgiConsole-1.0

     The tests verifies that the expected application page response is received on multiple restores when  osgiConsole feature is 
     configured inside server.xml.

- **LocalEJBTest:** 
     Features tested: ejbLite-3.2, enterpriseBeansLite-4.0

     The tests verifies that the expected application page response is received on multiple restores. Additionally, they validate the 
      behavior of non-persistent timers in the test EJB application. A timer is added to the application which goes off every 
      second.  It keeps track that it is not called too fast indicating some catchup calls on restore.  The expected result is that no                   
      catch calls are done on restore even if there is a significant time gap between the checkpoint and restore processes. The 
      test intentionally waits for 5 seconds before initiating the restore process, simulating the missing of 5 timer invocations.

- **CheckpointSPITest:**

     The tests validates the config on restore. They ensure that the server is restored with the set default configuration. 
     Additionally, verify that environment value, dropin config and files added to the variables directory overrides defaultValue in 
     restore. The tests also ensure that the ProtectedString trace strings must be different on every restore. And checks for the 
     occurrence of any expected FFDC events in case of failed checkpoint or restore.

- **CheckpointWithSecurityManager:**

     The test checks for appropriate FFDC events of checkpoint failure when the security manager is enabled in bootstrap 
     properties.

- **MPConfigTest:**
     Features tested: mpConfig-2.0, mpConfig-3.0

     The tests encompass the evaluation of the injected Config in various scenarios. 
     The Config is injected both statically using the @ConfigProperty annotation and dynamically using a Config object. The tests 
     aim to verify the functionality of the injected default value, annotation value, environment variable, and server configuration. 

     **MPConfigBean.java and MPConfigBeanWithApplicationScope.java**
     The testing of the injected config property, utilizing the @ConfigProperty annotation, is performed on both @RequestScoped 
     and @ApplicationScoped beans. The tests ensure that any configuration changes made after a checkpoint are accurately 
     read during restore.

     **ApplicationScopedOnCheckpointBean.java**
     During the checkpoint, it has been observed that when the statically injected config property (@ConfigProperty) is accessed 
     within @ApplicationScoped beans, any subsequent changes to the configuration made after the checkpoint are not reflected 
     upon restore. To address this issue, tests are conducted to verify if a warning message with the code CWWKC0651W is 
     being logged. This warning message serves to inform the user that the updated value of the property may not be utilized 
     during the restore process.

     **ApplicationScopedOnCheckpointBeanWithConfigObject.java and 
     ApplicationScopedOnCheckpointBeanWithConfigObjectProperties.java**
     For @ApplicationScoped beans, the config is dynamically injected. The tests are   performed to ensure that the updated 
     config is correctly read during the restore process, even if the config was accessed during the checkpoint. This verification 
     confirms that the dynamically updated config values are correctly read during restore for @ApplicationScoped beans.

- **AppsecurityTest:** 
     Features tested: appSecurity-3.0, appSecurity-4.0, appSecurity-5.0

     The tests ensure that only authenticated and authorized users can access the endpoint. If any changes are made to the 
     configuration following the checkpoint, the test ensures that the updated configuration is properly read during the restore 
     phase. During this process, when the configuration user “password” is updated after the checkpoint, the test verifies that the 
     endpoint is accessible with the new authentication password on restore. Additionally, when a new user is added to the group 
     of authorized users, the test verifies that the endpoint is accessed by the new user as well. 

- **MPJWTTest:**
     Features tested: mpJwt-1.2, mpJwt-2.0, mpJwt-2.1

     The tests are conducted to validate the accessibility of the endpoint during the restore process. If any changes are made to 
     the configuration following the checkpoint, the test ensures that the updated configuration is properly read during the restore 
     phase. During this process, the "clockSkew" configuration is adjusted to decrease the JWT token's expiration time. The test 
     verifies that authentication fails and the endpoint becomes inaccessible during restore due to the expired token. Additionally, 
     the "audiences" configuration is modified by assigning an incorrect audience after the checkpoint. The test verifies that 
     authentication fails and the endpoint remains inaccessible because the updated audience is not listed among the trusted 
     audiences in the JWT configuration. The tests verifies the appropriate error messages in the server logs .

- **SSLTest:**
     Features tested: ssl-1.0, transportSecurity-1.0

     The tests are conducted to validate the accessibility of the endpoint during the restore process in various scenarios involving 
     SSL configuration. These scenarios include cases where SSL is either explicitly configured or autogenerated. Additionally, 
     the tests account for situations where the keystore password is provided either during the checkpoint or during the restore 
     process using environment variables.

- **PasswordUtilsTest:**
     Features tested: passwordUtilities-1.1

     The tests cover the verification of programmatic login with default principal mapping, as well as the authentication data 
     username and password verification after the server is restored.

- **MPOpenTracingJaegerTraceTest:**
     Features tested: mpOpenTracing-2.0

     The test checks if a tracer containing spans is created across multiple servers. A span is a logical unit of work in Jaeger, 
     which includes the name, starting time and duration of the operation. During the test, the trace configuration is updated 
     using environment variables. Subsequently, the test ensures that the trace logs reflect the updated configuration being 
     correctly read during the restore process. 

- **MPFaultToleranceTimeoutTest:**
     Features tested: mpFaultTolerance-3.0, mpFaultTolerance-4.0

     The tests focus on examining the behavior of timeout during a checkpoint process. When the checkpoint command is 
     executed, the server spawns a thread that initiates a timeout. Upon server restore, the timeout method should resume, 
     disregarding the time that passed while the server was inactive. This test verifies that the timeout functionality is correctly 
     maintained across the checkpoint and restore process. An additional test is included to assess the behavior when a timeout 
     does not occur at the checkpoint. To ensure that a period greater than the expected timeout has passed, sleep is added 
     between the checkpoint and restore. This guarantees that sufficient time has elapsed to evaluate the timeout behavior 
     accurately.

- **ValidFeaturesTest:**
     Features tested: webProfile-8.0, webProfile-9.0, webProfile-10.0, microprofile-4.1, microprofile-5.0, microprofile-6.0 

     The tests verify that the checkpoint and restore works well without any issues when webProfile 8.0, 9.0, 10.0 and 
     microprofile 4.1, 5.0, 6.0 features are enabled inside server.xml. The tests cover individual scenarios where each version is 
     enabled individually and also combinations where both webProfile and microprofile versions are enabled simultaneously.

- **RESTclientTest:**
     Features tested: mpRestClient-2.0, mpRestClient-3.0

     The tests verify different endpoints during restore. The default baseURI defined in the server is verified. Subsequently, the 
     config is updated to an alternate endpoint. The test then verifies that the alternate endpoint was accessed successfully 
     during restore.

- **JNDITest:**
     Features tested: jndi-1.0

     The tests focus on validating the regular jndi resource lookup on restore. Subsequently updates config of jndiEntry before 
     restore and validates the application response when the endpoint is accessed.

- **CRIULogLevelTest:**

     The tests focus on testing various criu log levels. This is done by setting the environment variable CRIU_LOG_LEVEL 
     during the checkpoint. The tests cover scenarios where the CRIU_LOG_LEVEL property is set to negative values, non- 
     integer values, or values that are too large. In such cases, the expected outcome is the throwing of a 
     CheckpointFailedException, indicating an error during the checkpoint process. Additionally, the tests include a positive 
     scenario where the CRIU_LOG_LEVEL property is set to the highest level. In this case, the tests verify that the server can 
     successfully perform the checkpoint and restore operations without any issues.

- **WebSocketTest:**
     Features tested: websocket-1.1

     The tests focus on accessing the appropriate websocket server endpoint and based on the config set inside server.xml. This 
     is achieved by updating the server config between checkpoint and restore.

- **FacesTest:**
     Features tested: jsf-2.3

     The tests are centered around obtaining the correct response from the front-end server after it has been restored following a 
     checkpoint.

- **FacesBeanTest:**
     Features tested: jsf-2.3, ejbLite-3.2, faces-3.0, enterpriseBeansLite-4.0

    The tests are centered around obtaining the correct response from the server after it has been restored following a 
    checkpoint.


- **WebProfileJSPWithELTest:**
     Features tested: jsp-2.3, pages-3.0, pages-3.1

     The tests focus on getting the appropriate response page for request scoped and application scoped jsp after the server has 
     been restored following a checkpoint.

- **OpenAPITest:**
     Features tested: mpOpenAPI-2.0

     The tests modify the config and verify if the config change was reflected when the endpoint is accessed after restore.

- **MPMetricsTest:**
     Features tested: mpMetrics-3.0, mpMetrics-4.0

     The tests focus on testing the authentication config. When authentication is set to true the endpoint is only available on https 
     port whereas when the authentication config is updated to false, the endpoint becomes available at http port as well. The 
     config is updated between checkpoint and restore to verify that update in config was reflected on restore.

- **MPTelemetryTest:**
     Features tested: mpTelemetry-1.0

     The tests focus on testing the updated otel.service.name and otel.sdk.disabled config on restore. It verifies that the traces 
     have strings indicating the updated config.

- **WebProfileEARtest:**
     Features tested: webProfile-8.0

     The tests verify that the appropriate response page can be accessed when the server performs multiple restores.

- **MPHealthTest:**
     Features tested: mpHealth-3.1, mpHealth-4.0

     The tests verify the default health check of the application. The readiness and startup response config is read from the 
     application so the default is DOWN and we  expect a failed response code. However, when we update the config to UP and 
     checkpoint the application at BEFORE_APP_START phase and delay the start of application by adding a sleep. The health 
     check of the application returns a success response code until the application finally takes over and sets the config to 
     DOWN again. This ensures that the update in config after the checkpoint is accurately read during the restore process.

- **SlowAppStartTest:**

     The tests validate that slow start applications should fail if a checkpoint is requested at the AFTER_APP_START phase. The 
     reason for this failure is that the checkpoint process expects the application to have already started when it is initiated. Since 
     slow start applications have a delayed startup process, initiating a checkpoint after the AFTER_APP_START phase would 
     lead to an inconsistent state between the application and the checkpointed data. Hence, the tests ensure that the slow start 
     applications correctly handle this scenario by failing and preventing the checkpoint from proceeding. On the other hand the 
     tests also validate that there are no issues checkpointing the slow start applications at BEFORE_APP_START phase.

- **JsonbTest:**
     Features tested: jsonb-1.0, jsonb-2.0, jsonb-3.0

     The tests focus on getting the appropriate response page and validate the jsonb properties after the server has been 
     restored following a checkpoint.

- **JsonpTest:**
     Features tested: jsonp-1.1, jsonp-2.0, jsonp-2.1

     After the server has been restored following a checkpoint, the tests focus on adding the json patches to the document and 
     testing the url with json data. When the url is passed with the wrong pointer, an expected  JsonException is thrown whereas 
     when the url is passed with the right pointer, the test passes as expected.

- **ManagedBeansTest:**
     Features tested: managedBeans-1.0, managedBeans-2.0

     The tests focus on working of managed beans with checkpoint/restore. It ensures that the injected resource value and the 
     post construct value have the expected values when they are looked up during restore.

- **BellsTest:**
     Features tested: bells-1.0

     The tests focus on evaluating the registration and consumption of bells service when the checkpoint is done before app start 
     and after app start. For the BEFORE_APP_START phase, the tests verify that the bell service for the test interface should 
     be consumed during restore. On the other hand when the checkpoint is done AFTER_APP_START, the test verifies that the 
     bell service for the test interface should be consumed during the checkpoint. The tests also verify that the test interface is 
     injected with updated properties when the config is updated after checkpoint.

- **JaxWSVirtualHostTest:**
     Features tested: jaxws-2.2, xmlWS-3.0, xmlWS-4.0

     The tests verify that the appropriate response page can be accessed when the server performs checkpoint restore.

- **WebAppMessageTest:**
     Features tested: servlet-4.0, servlet-5.0, servlet-6.0

     The tests verify the appropriate application started messages in the logs when checkpoint is done using 
     BEFORE_APP_START and AFTER_APP_START. In case of BEFORE_APP_START, application started messages should 
     be found in restore logs whereas in case of AFTER_APP_START, application started messages should be found in 
     checkpoint logs.

- **URAPIs_Federation_2LDAPsTest:**
     Features tested: ldapRegistry-3.0

     The tests hit the servlet with different combinations of users names and patterns and checks if authentication passes or fails 
     when the server is restored.

- **SkipIfCheckpointNotSupportedAnnotationTest:**
     The tests verify that if criu is run on non supported jvms it should return an expected return code along with 
     CheckpointFailedException being thrown. Additionally, tests the positive scenario which tests for expected return code. 

- **RestConnectorTest:**
     Features tested: restconnector-2.0

     The tests verify that the web response from the endpoint ibm/api/config and ibm/api/config/datasource has expected data on 
      restore after modification of config after checkpoint.

- **AuditTest:**
     Features tested: audit-1.0

     The tests verify that there are expected counts of audit log files according to the auditFileHandler maxFiles config set inside 
     server.xml. The tests ensure that the updated config is correctly reflected during restore.

- **ConcurrencyTest:**
     Features tested: concurrent-1.0, concurrent-2.0, concurrent-3.0

     The tests verify that when a task is scheduled using ManagedExecutor or repeated using a trigger or managedExecutor's 
     repeating function with few seconds delay on checkpoint, a delay is noticed on restore with a two second margin of error.

- **MapCacheTest:**
     Features tested: distributedMap-1.0

     The tests verify the correct function of the distributed map with respect to timing out of map entries during restore. The 
     configuration of the distributed map is set in the application servlet.

- **WebCacheTest:**
     Features tested: webCache-1.0

     The test compares nanotime in cached response during restore. It involves passing a parameter to ensure that a different 
     time is returned in the response.

- **XMLbindingsTest:**
     Features tested: jaxb-2.2, xmlBinding-3.0, xmlBinding-4.0

     The tests verify that the expected xml web response is received when a server performs checkpoint/restore.

- **WebProfileJSPtest:**
     Features tested: jsp-2.3, pages-3.0, pages-3.1

     The tests verifies that the application context root and the extended document root gives expected jsp response when a 
     server performs checkpoint/restore.
		

2. **io.openliberty.checkpoint_fat_beanvalidation**
       Features tested: beanValidation-2.0, beanValidation-3.0

- **ClockProviderTest:**
            
     The tests verify the clock provided by the default validation configuration tracks
     time as expected, and that time zone does not adjust, from checkpoint to restore. They
     also verify the validation of basic temporal constraints for a java bean within checkpoint  and restore.

- **ManagedBeanTest:**

     The tests verify a restored server validates basic (built-in) Bean Validation constraints within a web application that uses a 
     CDI managed bean.


3. **io.openliberty.checkpoint_fat_persistence**

- **DB2Test:**
     Features tested: jdbc-4.2

     The tests verify that the properties which represent durations of time are set properly on the data source. Also, verify that 
     WAS JDBC statement wrappers can properly handle the NULL result set. They also ensure that the proper implementation 
     classes are used for the various data sources configured. Additionally checks that the locks are not shared between 
     transaction branches that are loosely coupled.

- **JPATest:**
     Features tested: jpa-2.2

     The tests verify a few CRUD operations such as create, read and delete after the server is restored.

- **SessionDatabaseTest:**
     Features tested: sessionDatabase-1.0

     The tests ensure that various types of objects can be stored in a session, serialized when the session is evicted from 
     memory, and deserialized when the session is accessed again. Also ensure that various types of objects can be stored in a 
     session, serialized when the session is evicted from memory, and deserialized when the session is accessed again after the 
     server is restored.


4. **io.openliberty.checkpoint_fat_security_oidc_social**

- **JASPIBasicAuthenticationTest:**
     Features tested: jaspic-1.1, appAuthentication-2.0, appAuthentication-3.0

     In these tests the server attempts to access a protected servlet configured for basic authentication with JASPI activated 
     during restore. When the login is done with a valid userId and password in the jaspi_basic role, it expects a response code 
     of 200 and the servlet is accessed. When it attempts to login with an invalid userId and invalid password, the tests verify that 
     JASPI authentication fails and returns a response code 403. And when the server attempts to login without credentials, the 
     tests verify that the JASPI authentication fails with a 401 return code.

- **OidcClientBasicTests:**
     Features tested: openidconnectclient-1.0, openidconnectserver-1.0

     The tests attempts to access a test servlet specifying a valid OP url after restore and verifies that the server should 
     authenticate and access the test servlet without issue.

- **LibertyOP_BasicTests_oauth_usingSocialConfig:**
     Features tested: openidconnectserver-1.0, socialLogin-1.0

     The tests verify that, when the server performs checkpoint/restore, the login page from social should be accessed after 
     entering a valid id/pwd in both cases when the subject principals includes and does not include a JWT. And when the client 
     secret is updated in the server.xml after checkpoint in both client and server, the tests verify that the login page should be 
     accessed after entering a valid id/pwd during restore.


5. **io.openliberty.checkpoint_fat_transaction**

     Features tested: transaction.1.2

- **RecoveryTest:**
     The tests verify the expected recovery of different servlets when the checkpoint is done.

- **ServletStartupTest:**

     The tests verify that the checkpoint fails with a CheckpointFailedException when a servlet begins a UserTransaction during 
     application startup when checkpoint is done at AFTER_APP_START phase whereas servlet initialization is completed 
     without any exception when checkpoint is done at BEFORE_APP_START phase.

- **ServletTest:**

     The tests verify that the servlets have JNDI access to transaction mgmt APIs and can perform basic transaction operations 
     upon restoring a server checkpointed at AFTER_APP_START. The test also verifies changes to the datasource 
     configuration are picked up at restore time before the datasource is injected into the test servlet.

- **StartupBeanTest:**

     The tests verify that the  checkpoint fails when a startup bean (EJB Session bean), or its container begins a transaction 
     during application startup. It also verifies that bean does not begin a container-managed transaction during application 
     deployment.

- **TransactionalBeanTest:**

    The tests verify that the server maintains transaction boundaries for @Transactional managed bean when it performs 
    checkpoint/restore.

- **TransactionLogTest:**

    The tests verify the checkpoint behaviors over transaction logging configurations. When transactions log to file and the 
     transaction log directory already exists, the tests ensure that that checkpoint fails. Also verifies the transaction logs to a 
     datasource within a restored server. It further ensures that the datasource configuration has updated
     with the config attribute declared in the server.env file.

- **TransactionManagerTest:**

    The tests verify the startup behaviors for the transaction manager and recovery services.
     It ensures that the Transaction Manager service startup executes during restore, only, for a server checkpointed at 
    AFTER_APP_START. Also ensure that the Transaction Manager  service does not begin recovery before server startup 
    completes during restore.

- **TransactionScopedBeanTest:**

     The tests verify the expected response is servlet response is received for different transaction scoped beans when the 
     server is restored.

**Comment by ayoho** [comment]
Testing sounds reasonably thorough, especially for the scope of this feature. All looks good 👍
