### ISSUE TITLE
Tracking WC / JSP properties default values for EE11

### ISSUE THREAD

**Issue by pmd1nh** [OpenLiberty/open-liberty#25292]
Record any WCCustomProperties that should change their default value.  We will review it at servlet version releases boundary.

**2023:**
=====

1. com.ibm.ws.webcontainer.set400scontoomanyparentdirs=false (default)  //true - Return 400 instead of 500 for non-valid URI

_(Updated May, 2023 - In servlet-6.0, we reject /../../../ during the canonicalizeURI process (servlet-6.0 feature) with a 400 Bad Request.  This property does not need to change its default value since it obsoletes in servlet-6.0+)_

2. JSPOption's _usePageTagPool_ property from false to true. 

It can assist with avoid OOM errors since the CDI tags would be destroyed in the `finally` block of the _jspService method.  See issues such as https://github.com/OpenLiberty/open-liberty/issues/11453

**Comment by volosied** [comment]
Can we also list JSP properties here? I would like to potentially change the JSPOption usePageTagPool from false to true.

Setting it to true has address a memory leak found in some scenarios: https://github.com/OpenLiberty/open-liberty/issues/11453

I will need some more investigation, but at least I have a note here.

**Comment by pmd1nh** [comment]
Note everything in this issue.

**Comment by pmd1nh** [comment]
Add all items to https://github.com/OpenLiberty/open-liberty/issues/27383

close this out.
