### ISSUE TITLE
CDI 1.2: Reconsume Weld 2.4.7

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#2532]
Weld 2.4.7 has been released and we need to reconsume it;
http://central.maven.org/maven2/org/jboss/weld/weld-osgi-bundle/2.4.7.Final/weld-osgi-bundle-2.4.7.Final.jar

Fixes this defect

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=250264

Also need to consume 2.4.7 into tWAS ASAP

Must tell Cassandra Tucker about the updated OSS dependency

**Comment by tevans78** [comment]
and update WS-CD-Open/dev/build.openliberty.legal/legal/com.ibm.ws.org.jboss.weld/ossc.xml

**Comment by benjamin-confino** [comment]
Completed in both liberty and twas
