### ISSUE TITLE
Sort out messages for MP OpenAPI endpoint configuration

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#25367]
We can see some cases where the MP OpenAPI endpoints could be configured in a way that's invalid (e.g. if it's configured the same as the context root for an application).

- [x] Investigate what messages are currently emitted when an OpenAPI endpoint is configured the same as:
  - An application context root
  - A path used by another feature (e.g. the mpMetrics `/metrics` endpoint)
- [x] Decide what messages are necessary for the user to diagnose the problem
  - Bear in mind that we probably can't change or suppress messages from the kernel that report the conflict unless we can recognise in advance that a conflict is going to happen.
  - We should also consider that applications can be deployed after the server has started, so the conflict may not occur immediately at startup
- [x] Check that the other messages which are emitted by OpenAPI are appropriate and result in a messages.log which is helpful in diagnosing problems.

**Comment by abutch3r** [comment]
If there is a conflict with an Applications context root we get the following error
```
com.ibm.ws.webcontainer E SRVE0164E: Web Application openapi-ui-test-app uses the context root /openapi-ui-test-app/*, which is already in use by Web Application OpenAPIUI. Web Application openapi-ui-test-app will not be loaded.
```
Which gives us a good indication that is the OpenAPI UI feature that is at fault for this conflict 

for the Document endpoint
```
ccom.ibm.ws.webcontainer E SRVE0164E: Web Application openapi-ui-test-app uses the context root /openapi-ui-test-app/*, which is already in use by Web Application MicroProfileOpenAPI. Web Application openapi-ui-test-app will not be loaded.
```
Which is not as clear, but provides enough information for a user to get started with, especially if accompanied by INFO messages during the activate process. 

If there is a conflict with another active feature e.g. MP Health we will get the following message.
```
com.ibm.ws.app.manager.wab.internal.WABInstaller E CWWKZ0208E: Bundle io.openliberty.microprofile.health.3.1.internal.jakarta_1.0.77.202304281135 [213] with context root /health cannot be installed into the web container because it has the same context root as the following bundles: [com.ibm.ws.microprofile.openapi.ui_1.0.78.202306061540 [155]]
```

These is a change it will be reversable depending on when OL installers the different WAB. Existing warning message backs up the statement.

From this there is an idea of which package is blocking the enablement of the feature.

As such for an applicaiton perspective the existing messages I believe are sufficient for both server startup and for later application deployment.

For WAB the error is not quite as clear and is messier to review, given this is package level info, but from that you could tell which one we have impacted.

**Comment by abutch3r** [comment]
Example log [messages.log](https://github.com/OpenLiberty/open-liberty/files/12109507/messages.log)

docPath conflicts with application path

**Comment by abutch3r** [comment]
With the WebContainer team having fixed the issue where by if a conflict occurs then both apps are stopped, so now only the second one is. here is the log whereby as OpenAPI is first, means the app doesn't start due to the conflict 
[messages.log](https://github.com/OpenLiberty/open-liberty/files/12749249/messages.log)
It is expected if a app comes along after we would see the same errors as here.

**Comment by abutch3r** [comment]
Having reviewed the messages, we are currently satisfied with them and no particular ID concerns. The messages provide details about valid characters and particular invalid combinations.

Conflict is only recognized within the the WebContainer and those messages are useful enough to see which won the race to start on a given path and what has then happened to the one that lost. 

We have the mentioned fix for WebContainer and the messages are enough for a user to see which of the endpoints they have that stops an app from starting or which app uses the same path as it.
