### ISSUE TITLE
CDI Transactional annotation is NOT allowed on EJB class

### ISSUE THREAD

**Issue by hantsy** [OpenLiberty/open-liberty#25363]
**Describe the bug**  

I tried to use CDI `@Transactional` on a `@Stateless` EJB bean, but failed.

**Steps to Reproduce**  
1. Git clone https://github.com/hantsy/jakartaee10-starter-boilerplate
2. Open a terminal, enter the project root folder 
3. Run `mvn clean liberty:run -Popenliberty` 
4. Use `@Transactioal` on `EjbTodoRepository` instead of `@TransactionAttribute`
5. You will get the error.

**Expected behavior**  
It should work according to the spec, also tested on Glassfish 7, WildFly 27.x

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.3
 - Affected feature(s) jakartaee-10
 - Java Version: 
    ```
      java -version
      java version "17.0.6" 2023-01-17 LTS
      Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190)
      Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)
    ```
 - server.xml configuration (WITHOUT sensitive information like passwords) https://github.com/hantsy/jakartaee10-starter-boilerplate/blob/master/src/main/liberty/config/server.xml
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`
   [messages.log](https://github.com/OpenLiberty/open-liberty/files/11583674/messages.log)

**Comment by jonhawkes** [comment]
This is as specified in the [EJB specification](https://download.oracle.com/otndocs/jcp/ejb-3_2-fr-eval-spec/index.html) section 7.1: It is illegal to associate JTA transactional interceptors with Enterprise JavaBeans. The EJB Container should fail deployment of such applications. This restriction may be removed in a future release of this specification.

Use the [@TransactionAttribute](https://docs.oracle.com/javaee/6/api/javax/ejb/TransactionAttribute.html) on EJBs

**Comment by hantsy** [comment]
But it works on GlassFish/WildFly, only failed on OpenLiberty

**Comment by jhanders34** [comment]
> But it works on GlassFish/WildFly, only failed on OpenLiberty

When you say that it works are you saying that it starts without error or that the Transactional annotation is honored?  If there isn't a TCK test for something in the spec, other implementors may not have that function in their product unfortunately.  With Liberty we strive to do what the spec says even if there isn't a TCK test to validate it.  That may be what has happened here.
