### ISSUE TITLE
4-6% Startup Time Regression in persistence-3.1 

### ISSUE THREAD

**Issue by eramos2** [OpenLiberty/open-liberty#25414]
**Describe the bug**  
There is a 4-6% Startup time regression in the Daytrader 10 benchmark, seen between Liberty builds 230420230418-0035 and 230520230423-1101 that is related to the EclipseLink for persistence-3.1 feature changes #24597 

**Steps to Reproduce**  
- Measure Startup time in 230420230418-0035 build 
- Measure Startup time in 230520230423-1101 build 
- Compare the Difference in Startup time between builds

**Expected behavior**  
By swapping io.openliberty.persistence.3.1.thirdparty.jar from 0418-0035 build into 0423-1101 build and run Startup time measurements we see that the Startup time regression is fixed.

**Diagnostic information:**  
 - OpenLiberty Version:
WebSphere Application Server 23.0.0.4 (1.0.76.cl230520230423-1101) on Eclipse OpenJ9 VM, version 11.0.17+8 (en_US)
 - Affected feature(s): persistence-3.1
 - Java Version: 
java version "11.0.17" 2022-10-18
IBM Semeru Runtime Certified Edition 11.0.17.0 (build 11.0.17+8)
Eclipse OpenJ9 VM 11.0.17.0 (build openj9-0.35.0, JRE 11 Linux amd64-64-Bit Compressed References 20221031_457 (JIT enabled, AOT enabled)
OpenJ9   - e04a7f6c1
OMR      - 85a21674f
JCL      - 2767d3a0b2 based on jdk-11.0.17+8)

**Comment by jhanders34** [comment]
#regression

**Comment by jhanders34** [comment]
Fixed with #25507
