### ISSUE TITLE
WithSpan anotation does not work when name or kind is set

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/open-liberty#25429]
**Describe the bug**  
Followed the example in the https://openliberty.io/docs/latest/microprofile-telemetry.html#manual doc. Annotated a bean's methods with `@WithSpan("name")`, but the Jagear server does not show traces for the annotated methods.

**Expected behavior**  
Jagear server should show traces for the annotated methods.

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.5
 - Affected feature(s): mpTelemetry-1.0
 - Java Version: 11

**Comment by Azquelt** [comment]
I've looked into @gkwan-ibm's scenario but I'm not sure yet why it isn't working but our FAT tests for this area pass.

**Comment by Azquelt** [comment]
@yasmin-aumeeruddy found that the problem only occurs when a name is provided in the annotation (e.g. `@WithSpan("myName")`).

Without the name, the span is created correctly.

From this we realised that we are missing `@Nonbinding` annotations on our copy of the `@WithSpan` annotation.

I will update the defect description to clarify when the problem occurs.
