### ISSUE TITLE
Use application contextRoot for JWT SSO cookie path

### ISSUE THREAD

**Issue by utle** [OpenLiberty/open-liberty#25431]
1) Investigate SSO code that call the common code SSOCookieHelper.createCookie with the new attribute useContextRootSSOCookiePath set to true
2) Add new tests for JWT SSO cookie that use contextRoot instead of "/"

**Comment by arunavemulapalli** [comment]
- create ltpa cookie (no jwtsso feature) with context root and access the protected resource again using the ltpa cookie (this time server has jwtsso feature and useLtpaIfJwtAbsent is true), request should succeed
- create ltpa cookie (no jwtsso feature) with context root , restart the server with jwtsso feature and access another protected resource  (different context root) using the ltpa cookie and request should fail
- create jwt sso cookie with no context root when accessing a protected resource and then access different protected resource with different context root and request should succeed with the jwt cookie
- create jwt sso cookie with context root set and this time request should fail when the test attempts the second request
