### ISSUE TITLE
Make updates to OpenAPI code that uses hardocded URL paths

### ISSUE THREAD

**Issue by abutch3r** [OpenLiberty/open-liberty#25439]
Based on the findings of https://github.com/OpenLiberty/open-liberty/issues/25434

Changes are required in the following places to accomodate if the OpenAPI UI or Document endpoints are changed by the developer.

Java:
- MP OpenAPI 1.0-1.1
-  [x] https://github.com/OpenLiberty/open-liberty/blob/e11eb2c708feaf2d33849675c5ed785938a179c7/dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/utils/ProxySupportUtil.java#L41
- MP OpenAPI 2.0+
- [x] https://github.com/OpenLiberty/open-liberty/blob/e11eb2c708feaf2d33849675c5ed785938a179c7/dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/utils/ProxySupportUtil.java#L58
- [x] https://github.com/OpenLiberty/open-liberty/blob/061e8b464b883ac6ebb727028e7ccd64669830f8/dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/servlets/ApplicationServlet.java#L75
which uses
https://github.com/OpenLiberty/open-liberty/blob/061e8b464b883ac6ebb727028e7ccd64669830f8/dev/io.openliberty.microprofile.openapi.2.0.internal/src/io/openliberty/microprofile/openapi20/internal/utils/Constants.java#L136

These will need to pull the result of processing of the config so that they are aware of what the endpoints have been actually set to - given we can default these if validation fails, this cannot come directly from config

js:
- OpenAPI UI
- [x] https://github.com/OpenLiberty/open-liberty/blob/e11eb2c708feaf2d33849675c5ed785938a179c7/dev/com.ibm.ws.openapi.ui/swagger-ui/src/openapi-liberty.js#L83

This should pull the path from the window e.g. `location.pathname` as that will be the UI endpoint.

**Comment by Azquelt** [comment]
We also have OpenAPI documents for platform config validation APIs which show up under `/openapi/platform` and I don't think have a UI.

I don't think we should move these, but we should test they still work when we change the mpOpenAPI config (don't see any reason why they wouldn't) and call it out in the design doc.
