### ISSUE TITLE
Check if the RSO integration with SmallRye Mutiny still needs a PrivilidgedAction

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#25450]
https://github.com/OpenLiberty/open-liberty/pull/25413#discussion_r1224172732

**Comment by Azquelt** [comment]
I tried removing it and we do get failures, but they're all within calls to `Infrastructure.<clinit>` which reads system properties and does service loading so we can probably avoid those by ensuring that class is initialized when our feature starts rather than on demand.
