### ISSUE TITLE
A better error for the NullPointer we get if WithSpan is on the class level

### ISSUE THREAD

**Issue by benjamin-confino** [OpenLiberty/open-liberty#25467]
In order to make the WithSpanInterceptor we had to allow the WithSpan annotation to be put onto a Type.

However in a fat test if you put WithSpan onto an application class you get an NPE from WithSpanInterceptor.MethodRequestSpanNameExtractor.extract - we should either remove Type as a target for WithSpan or put a better error method in.

**Comment by Azquelt** [comment]
As written, I don't think this is a bug. Users don't have access to the `WithSpan` annotation which we use internally, they should only have the version from the OTel instrumentation API, or from our third-party jar which does not permit use on a type.

However, [our current code](https://github.com/OpenLiberty/open-liberty/blob/823d991f3b63dff29e98d28acece16bacf3537b7/dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/common/cdi/AbstractWithSpanInterceptor.java#L124-L125) assumes that there will always be a `@WithSpan` annotation on the method which is not true - it's quite possible to bind an interceptor using a CDI extension without having the annotation be actually present on the method.

We should be using `CDIService.getInterceptorBindingsFromInvocationContext` to get the interceptor bindings which were used to call the method from the `InvocationContext`. (The next version of the Interceptors spec will include a similar public method, but for now we must use this internal method.)
