### ISSUE TITLE
Implement Histogram Prometheus type into MicroProfile Metrics features `mpMetrics-3.0` and `mpMetrics-4.0` 

### ISSUE THREAD

**Issue by Channyboy** [OpenLiberty/open-liberty#25519]
The design for the backport of the histogram functionality into mpMetrics-3.0 and mpMetrics-4.0 is identical to the mpMetrics-5.0/5.1 implementation. The Metrics 5.0/5.1 features are based on the Micrometer implementation which is the primary difference to our 3.0/4.0 implementation. We're using the same code from smallRye Metrics that Metrics v5.1 uses to parse and apply user configuration. Since the mpMetrics 3/4 features aren't based on Micrometer, we had to add our own implementation for histogram buckets into the liberty code.

UFO: Link to Metrics v5.1 UFO: https://ibm.ent.box.com/file/1268791012344?s=5qkwx6eyl2tzkmruq9hcg5i9nl0fdajv
FTS: Link to Feature Test Summary GH Issue : https://github.com/OpenLiberty/open-liberty/issues/28422
Beta Blog: Link to Beta Blog Post GH Issue : https://github.com/OpenLiberty/open-liberty/issues/28355
GA Blog: Link to GA Blog Post GH Issue : https://github.com/OpenLiberty/open-liberty/issues/28982

--------------------------------

With the existing MicroProfile Metrics specification, the technology provides a `Histogram` metric.
When exposed on the `/metrics` endpoint in Prometheus format, we expect to see an output similar to the following:
```
# TYPE application_file_sizes_mean_bytes gauge
application_file_sizes_mean_bytes 4738.231
# TYPE application_file_sizes_max_bytes gauge
application_file_sizes_max_bytes 31716
# TYPE application_file_sizes_min_bytes gauge
application_file_sizes_min_bytes 180
# TYPE application_file_sizes_stddev_bytes gauge
application_file_sizes_stddev_bytes 1054.7343037063602
# TYPE application_file_sizes_bytes summary
# HELP application_file_sizes_bytes Users file size
application_file_sizes_bytes_count 2037
application_file_sizes_bytes_sum 48123
application_file_sizes_bytes{quantile="0.5"} 4201
application_file_sizes_bytes{quantile="0.75"} 6175
application_file_sizes_bytes{quantile="0.95"} 13560
application_file_sizes_bytes{quantile="0.98"} 29643
application_file_sizes_bytes{quantile="0.99"} 31716
application_file_sizes_bytes{quantile="0.999"} 31716
```
We are primarily interested  `summary` type which includes quantiles of a specific values.

It would be of  useful if we can enhance the `mpMetrics-4.0` and `mpMetrics-5.0` features to output _histogram_ buckets alongside the quantiles/percentile output. This as a result will change the `summary` type to a `histogram` type. This functionality will be enabled through MP Config properties. This is chiefly a backport of the functionality slated to be incorporated with MicroProfile Metrics 5.1. See https://github.com/eclipse/microprofile-metrics/issues?q=is%3Aopen+is%3Aissue+milestone%3A5.1

However, for now,  the central piece would be to implement the mechanism for providing histogram bucket support in the (Liberty) implementation of MicroProfile Metrics ( of mpMetrics-3.0 and 4.0).

**Comment by tonyreigns** [comment]
Metrics v5.1 UFO: https://ibm.ent.box.com/file/1268791012344?s=5qkwx6eyl2tzkmruq9hcg5i9nl0fdajv

Metrics 3.0 and 4.0 will offer the same additional configuration abilities as Metrics 5.1 for configuring histograms, timers and percentiles. We're reusing the same code that Metrics 5.1 uses to pick up user configuration. Any configured buckets will have a "+Inf" bucket that tracks all values(as per Prometheus spec).

Users can configure their metrics by placing the following attributes in a `microprofile-config.properties` file bundled with their application archive.

| Configuration Attribute  | Description |
| ------------- | ------------- |
| mp.metrics.distribution.percentiles | Track custom percentiles  |
| mp.metrics.distribution.timer.buckets= | Enable and customize timer buckets  |
| mp.metrics.distribution.histogram.buckets=  | Enable and customize histogram buckets  |
| mp.metrics.distribution.percentiles-histogram.enabled | Enable default buckets  |
| mp.metrics.distribution.histogram.min-value | Set minimum value for histogram default buckets |
| mp.metrics.distribution.histogram.max-value  | Set maximum value for histogram default buckets  |
| mp.metrics.distribution.timer.min-value | Set minimum value for timer default buckets  |
| mp.metrics.distribution.timer.max-value | Set maximum value for timer default buckets   |


Here're a few examples:

Custom percentile configuration:
mp.metrics.distribution.percentiles=alpha.*=0.5,0.8

Prometheus output:
application_alpha_timer_seconds{quantile="0.5"} 0.0
application_alpha_timer_seconds{quantile="0.8"} 0.0


Histogram/Timer configuration:
mp.metrics.distribution.timer.buckets=
mp.metrics.distribution.histogram.buckets=alpha.timer=500ms,2s


Prometheus output:
application_alpha_timer_seconds_bucket{le="0.5"} 0.0
application_alpha_timer_seconds_bucket{le="2.0"} 0.0
application_alpha_timer_seconds_bucket{le="+Inf"} 0.0


Default Buckets:
Histograms have ~275 default buckets ranging from 0 to 1.7976931348623157E308
Timers have ~68 buckets ranging from 0 to 30.

Default percentiles example:
mp.metrics.distribution.percentiles-histogram.enabled=alpha.*=true
mp.metrics.distribution.timer.min-value=alpha.timer=300ms
mp.metrics.distribution.timer.max-value=alpha.timer=2s

Any timer/histogram with metric names that match alpha.* will output a default set of buckets. 
alpha.timer will only include the default buckets >= 0.3s and <=2s

**Comment by tonyreigns** [comment]
I've updated the initial issue description with more details related to the design of mpMetrics 3.0/4.0.

**Comment by tonyreigns** [comment]
Beta blog: https://github.com/OpenLiberty/open-liberty/issues/28355

**Comment by tonyreigns** [comment]
@OpenLiberty/demo-approvers Demo scheduled for EOI 24.14 

Thanks!

**Comment by chirp1** [comment]
Doc issue is: https://github.com/OpenLiberty/docs/issues/7399 We'll complete the documentation for 24.0.0.7. Approving epic.

**Comment by tonyreigns** [comment]
GA blog created: https://github.com/OpenLiberty/open-liberty/issues/28982

**Comment by donbourne** [comment]
@tonyreigns , can close now that this has shipped.
