### ISSUE TITLE
Pages 4.0: Remove the deprecated classes from the `jakarta.servlet.jsp.el` package

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#25541]

**Comment by volosied** [comment]
Completed via #27114

See: 

https://github.com/OpenLiberty/open-liberty/tree/78e44468bca205a280d904cdd708a0d35d8d4f03/dev/io.openliberty.pages.4.0.internal.factories/src/org/apache/jasper/el
