### ISSUE TITLE
Pages 4.0: Repeat existing Pages FATs with the `pages-4.0` feature

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#25548]

**Comment by volosied** [comment]
The following are repeated:
- io.openliberty.pages.3.1.internal_fat
- com.ibm.ws.jsp.2.3_fat

All we need do is create a com.ibm.ws.jsp_fat_lWAS.toleration.ee11 in Closed Liberty - `https://github.ibm.com/websphere/WS-CD-Open/pull/30989`

**Comment by volosied** [comment]
The CD PR (30989) was merged.

Closing this out
