### ISSUE TITLE
Pages 4.0: Remove the deprecated `isThreadSafe` page directive attribute

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#25544]

**Comment by volosied** [comment]
Completed via https://github.com/OpenLiberty/open-liberty/pull/27114

See test: 
https://github.com/OpenLiberty/open-liberty/blob/78e44468bca205a280d904cdd708a0d35d8d4f03/dev/io.openliberty.pages.4.0.internal_fat/fat/src/io/openliberty/pages40/fat/tests/Pages40ChangesTest.java#L70-L82
