### ISSUE TITLE
Pages 4.0: Remove the deprecated `jsp:plugin` action and related actions

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#25545]

**Comment by volosied** [comment]
Completed via https://github.com/OpenLiberty/open-liberty/pull/27114 

See Tests:
https://github.com/OpenLiberty/open-liberty/blob/78e44468bca205a280d904cdd708a0d35d8d4f03/dev/io.openliberty.pages.4.0.internal_fat/fat/src/io/openliberty/pages40/fat/tests/Pages40ChangesTest.java#L88-L139
