### ISSUE TITLE
Semicolon inside text parameter in Reason header will result in the sipcontainer dropping the request 

### ISSUE THREAD

**Issue by TiborBeres** [OpenLiberty/open-liberty#25646]
**Describe the bug**  

In case the sipcontainer receives a SIP request containing a semicolon inside the text parameter of the Reason header, the sipcontainer will not process the request correctly.  If SIP traces are enabled the traces will contain a StringIndexOutOfBoundsException. 

**Steps to Reproduce**  
Send a SIP request to the sipcontainer that contains a semicolon in it's text element. 
For example, a CANCEL request that contains this header:
Reason: SIP;cause=487;text="Originator canceled; Canceled" .

The sipcontainer will fail to parse the CANCEL request correctly, throwing a StringIndexOutOfBoundsException.

**Expected behavior**  
As the RFC does not restrict the presence of semicolons inside the text parameter, the sipcontainer should be able to handle requests containing semicolons inside the text parameter in the Reason header

**Diagnostic information:**  
- OpenLiberty Version: all open-liberty releases until version 23.0.0.8
- Affected feature: sipServlet-1.1
- Java Version: all supported Java

**Comment by lauracowen** [comment]
@TiborBeres please update the description of this `release bug` using the [bug report template](https://github.com/OpenLiberty/open-liberty/issues/new?assignees=&labels=release+bug&template=bug_report.md&title=).
