### ISSUE TITLE
Investigate OpenAPI docs exposed under `/openapi/platform`

### ISSUE THREAD

**Issue by abutch3r** [OpenLiberty/open-liberty#25648]
We expose documentation for config schema checking and validation APIs under `/openapi/platform` using RestHandler if the relevant features are enabled. We need to check that if the new MP OpenAPI endpoints are customized what the behavior is (does it remain (therefore no-op)) or does it in theory move/break

**Comment by Azquelt** [comment]
Updated issue description.

We're fairly sure that these endpoints won't be affected by changing the new configuration options so there should be nothing do to here but we do need to check.

- `/openapi/platform/config` should be retrievable if `restConnector-2.0` and `mpOpenAPI-3.1` are enabled.
- `/openapi/platform/validation` should be retrievable if `restConnector-2.0`, `mpOpenAPI-3.1` and any of `jdbc-4.1`-`4.3`, `connectors-2.0`-`2.1` or `cloudant-1.0` are enabled

**Comment by abutch3r** [comment]
Confirmed that both paths are unaffected when the MP OpenAPI Doc endpoint is changed to be non-default

so no changes required
