### ISSUE TITLE
Feature Test Summary -  for LTPA key rotation enhancement

### ISSUE THREAD

**Issue by Zech-Hein** [OpenLiberty/open-liberty#25669]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

### List of FAT projects affected

*  existing FAT project: _dev/com.ibm.ws.security.token.ltpa_fat/_

### Test strategy

* What functionality is new or modified by this feature?
   * Support LTPA keys rotation without causing the clients' existing tokens to re-authenticate (#18499).

* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)

**Automated Testcases:**

###  Existing FAT project: _dev/com.ibm.ws.security.token.ltpa_fat/_
1. `testLTPAFileCreationDeletion_monitorDirectory_true_monitorInterval_5`
2. `testLTPAFileReplacement_newValidKey_monitorDirectory_true_monitorInterval_5`
3. `testLTPAFileReplacement_newInvalidKey_monitorDirectory_true_monitorInterval_5`
4. `testLTPAFileCreationDeletion_monitorDirectory_false_monitorInterval_0`
5. `testLTPAFileReplacement_newValidKey_monitorDirectory_false_monitorInterval_0`
6. `testLTPAFileCreationDeletion_monitorDirectory_false_monitorInterval_5`
7. `testLTPAFileReplacement_newValidKey_monitorDirectory_false_monitorInterval_5`
8. `testLTPAFileCreationDeletion_monitorDirectory_true_monitorInterval_0`
9. `testLTPAFileReplacement_newValidKey_monitorDirectory_true_monitorInterval_0`
10. `testValidationKeys_fileNameAttribute`
       - fileName isn't configured
       - fileName is set to a non-existent file
       - fileName is in a different directory than the default ltpa.keys file
       - fileName points to a malformed file
11. `testValidationKeys_passwordAttribute`
       - password isn't configured
       - password is incorrect
12. `testValidationKeys_notUseAfterDateAttribute`
       - notUseAfterDate isn't configured
       - notUseAfterDate is empty
       - notUseAfterDate is set to an invalid date string
       - notUseAfterDate is set to a date in the past
13. `testConfiguredValidationKeys`
14. `testNotUseAfterDate_expiringAfterConfigurationAndUsage`
       - notUseAfterDate expires after usage

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

**4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.**

**Comment by ayoho** [comment]
I had some questions about whether certain negative scenarios were being covered in FATs. In particular:
- `fileName` isn't configured
- `fileName` is set to a non-existent file
- `fileName` is in a different directory than the default ltpa.keys file
- `fileName` points to a malformed file
- `password` isn't configured
- `password` is incorrect
- `notUseAfterDate` isn't configured
- `notUseAfterDate` is empty
- `notUseAfterDate` is set to an invalid date string
- `notUseAfterDate` is set to a date in the past
- `monitorDirectory` is set to true, but the LTPA keys directory contains a malformed .keys file

Then a general question about the `monitorDirectory` attribute: Are the other .keys files expected to be password protected? It was unclear to me how those .keys files would be loaded since the other configuration scenarios have a way to specify a password for the specific file and this scenario doesn't.

**Comment by Zech-Hein** [comment]
@ayoho We have finished adding remaining test cases and covered the scenarios you listed in your comment above.

Could you re-review when you get a chance?

**Comment by ayoho** [comment]
New coverage sounds good to me. After reading the UFO more closely, my question about the *.keys files' passwords was answered:
> Other *.keys will be used for only validation LTPA token, and they must use thesame password specify by the password attribute of ltpa element

LGTM 👍
