### ISSUE TITLE
SpringBoot 3.0: BETA BLOG

### ISSUE THREAD

**Issue by hlhoots** [OpenLiberty/open-liberty#25679]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty. For this post to be included in the beta issue please make sure that this is completed by the end of Friday following the GM (Tuesday). The beta and release blogs are created using automation and rely on you following the template's structure. **DO NOT REMOVE/ALTER THE `<GHA>` TAGS THROUGHOUT THIS TEMPLATE.**

Please provide the following information:
&#8203;<GHA-BLOG-RELATED-FEATURES>
1. Which Liberty feature(s) does your update relate to? 
    
Human-readable name (eg WebSockets feature):
Spring Boot 3 
Short feature name (eg websockets-1.0):
springboot-3.0
    </GHA-BLOG-RELATED-FEATURES>

    <GHA-BLOG-TARGET-PERSONA>
2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.  
    Liberty developers who want to take advantage of utilizing Spring Boot 3.x function within their Liberty applications.  Currently we support up through Spring Boot 3.1.
    </GHA-BLOG-TARGET-PERSONA>
   
    <GHA-BLOG-SUMMARY>
3. Provide a summary of the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.
   - What was the problem before and how does your update make their life better? (Why should they care?)
   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?  
    
Open Liberty currently supports running Spring Boot 1.5 and Spring Boot 2.0 applications.  Additionally, a Spring Boot 3.x applications can be exported as a .war file and executed on Liberty (https://openliberty.io/blog/2023/06/15/running-spring-boot-3.html).  With the creation of this new Spring Boot 3.0 feature, users will now have support for both .wars and .jars by enabling the springboot-3.0 feature.

This feature provides more complete support for running a Sprint Boot 3.0 application on Open Liberty as well as having the capability to thin the application when creating applications in containers.

To utilize the Spring Boot 3.x functionality, the user must be running with Java 17 or higher.  Additionally, if your application utilizes servlet, it will need to use servlet 6.0.  These features would be configured in the server.xml file as follows:

```
<features>
   <feature>springboot-3.0</feature>
   <feature>servlet-6.0</feature>
</features>
```
Additionally, in server.xml configuring your Spring Boot application is similar to previous Liberty Spring Boot versions:

```
 <springBootApplication id="spring-boot-app" location="spring-boot-app-0.1.0.jar" name="spring-boot-app" />
```

A few migration notes for using Spring Boot 3:

- Need JakartaEE10 versions of components.  See:

https://openliberty.io/docs/latest/reference/feature/webProfile-10.0.html

- Security configuration requires in-application modifications.  See:

https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter

https://docs.spring.io/spring-security/reference/servlet/authorization/authorize-http-requests.html

https://stackoverflow.com/questions/72381114/spring-security-upgrading-the-deprecated-websecurityconfigureradapter-in-spring

- A new server template is available:
springBoot3

    </GHA-BLOG-SUMMARY>

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
    - Once you've approved the code review, close this issue. 
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by cbridgha** [comment]
A couple comments:  
1) Rewording the 1st paragraph
Open Liberty currently supports running Spring Boot 1.5 and Spring Boot 2.x applications. With the creation of this new Spring Boot 3.0 feature, users will now have support for deploying Spring Boot 3.x applications by enabling the `springboot-3.0` feature. Liberty has always been able to support Spring Boot Applications packaged as a war, as demonstrated in this recent blog entry (https://openliberty.io/blog/2023/06/15/running-spring-boot-3.html). This new capability enables both "jar and war" support.
2) Similar to previous versions, SB application jar's can use the /dropins/spring folder, and skip server.xml entries.
