### ISSUE TITLE
Validation in Jakarta Data

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#25697]
User story:
"As a user of Jakarta Data, I would like Jakarta Data to integrate with Jakarta Validation so that entities can be validated for me."

The user can define validation constraints on entities.  Look into how validation could be automatically done, maybe triggered by `@Valid` on save operations or something else and how constraint violations are surfaced to the user.

```
@Repository
public interface Cars extends DataRepository<Car, Long> {
   @Valid 
   public void save(Car car);
}
```

```
@Repository
public interface Cars extends DataRepository<Car, Long> {
   public void save(@Valid Car car);
}
```

Micronaut does something similar to this:
```
@Repository
public interface Cars extends CrudRepository<@Valid Car, Long> {
   ...
}
```

**Comment by mswatosh** [comment]
Jakarta Persistence Section on Bean Validation:
https://jakarta.ee/specifications/persistence/3.0/jakarta-persistence-spec-3.0.html#a2366
