### ISSUE TITLE
Prototype Metrics for Fault Tolerance

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#2569]
Investigate what options are available for graphing and displaying metrics with Prometheus.

Use this to consider what metrics we might want to produce for Fault Tolerance features.

Meeting 2018-03-07 we suggested the following metrics
 - Retry
    - counter, how many times are we retrying
    - gauge, what percentage of the time do we retry
    - histogram, what is the average, median, 99th percentile number of retries for a request
 - Timeout
    - timer, Essentially automatically adding the `@Timed` annotation
    - histogram, percentile execution times
    - gauge, how often do we time out
 - Circuit breaker
    - timer, how long does it spend in open state?
    - histogram of pass/fail%?
    - how long since last circuit open?
    - mean time between failures?
    - can we have a graph over time of when the circuit was open?
 - Bulkhead
    - how full is the bulkhead?
    - for async: how long do threads wait for before starting

**Comment by Azquelt** [comment]
Started work on this. Currently have a counter automatically added if you have any FT annotations on a method.

**Comment by tevans78** [comment]
Done
