### ISSUE TITLE
fix the cache issue https://issues.jboss.org/browse/WELD-1130

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#2570]
This jira impacts us and we should investigate and submit a PR on Weld.

**Comment by Emily-Jiang** [comment]
@benjamin-confino

**Comment by benjamin-confino** [comment]
I've wrote a fix for weld, which we'll get in their next version.

**Comment by tevans78** [comment]
Weld update is complete
