### ISSUE TITLE
SpringBoot 3.0: Feature Test Summary

### ISSUE THREAD

**Issue by hlhoots** [OpenLiberty/open-liberty#25753]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

The core goals of the Spring3 Open Liberty FATs are:
1. Verification of existing function: Do all current Spring2 FATs run when converted to run as Spring3 FATs?
2. Verification of modified function, specifically, Java17 and JakartaEE dependencies.

No significant relevant new function was noted that is relevant to Open-Liberty FAT testing: Significant new function includes support for native executables and includes several internal Spring3 functional updates.  None of these is relevant to Open-Liberty FAT testing.

(1) Is provided by re-implementing all Spring2 tests as Spring3 tests.  Generally, this means porting FAT applications to build as Spring3 applications.  This also means creating new Spring3 versions of the existing Spring2 FATs.

In all cases, the port of applications, means changing to use the Spring3 gradle build plugin, means changing the external dependencies to Spring3 required versions, and means changing from javax package dependencies to jakarta package dependencies.  In a few cases, due to changes in function provided by external dependencies, application function requires updates to adapt to the dependency changes.

(2) Is provided by updates to specific test function: JakartaEE requirements are expressed in Open-Liberty as feature requirements.  Specifically, a Spring3 application which uses Servlets must use servlet-6.0, and one which uses WebSockets must use websocket-2.0. The Spring3 versions of the "Missing Feature" category of tests, "MissingServletTests30" and "MissingWebsocketFeatureTests30", has updates to test the new Spring 3 specific cases.

As a current test gap, the Java17 requirement is not currently tested within FATs, as the tests are configured currently to run using Java17.

During FAT reviews, possible security issues were noted based on the implementation of Feature dependency checking.  Based on these reviews, a new security enabled version of "MissingWebsocketFeatureTests30" is created.  No similar enabled security version of "MissingServletTests30" is created, because enabling security forces servlet-6.0 to be configured, which prevents the failure scenario from occurring.

### List of FAT projects affected

* com.ibm.ws.springboot.fat30_fat
  * io.openliberty.springboot.fat30.actuator.app
  * io.openliberty.springboot.fat30.app
  * io.openliberty.springboot.fat30.java.app
  * io.openliberty.springboot.fat30.multicontext.app
  * io.openliberty.springboot.fat30.war.app
  * io.openliberty.springboot.fat30.webanno.app
  * io.openliberty.springboot.fat30.webflux.app
  * io.openliberty.springboot.fat30.websocket.app

Spring3 FAT applications are created in separate projects (xxx.app).  Spring application creation uses standard maven tooling which sets best in the liberty environment as independent projects.

### Test strategy

* What functionality is new or modified by this feature?
  * The new spring boot 3 feature, "springBoot-3.0", was created and is tested by these FATs.
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
  * The testing for this new feature was duplicated from the Spring Boot 2 feature.  Similar tests are there to test all existing scenarios covered by the Spring Boot 3 feature. 
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)
  * None

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

Our confidence level is a 4 now that the 5 tests were fixed and merged on 8/4/2023

0 - No automated testing delivered
1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.
2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths
3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.
4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.
5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed).

---

Listing of tests:

- FATSuite
  - ApplicationArgsTests30
    - testServerAppArgs()
  - ApplicationStartedEventTests30
    - testApplicationStartedAfterModuleStarted()
  - CDITests30
    - testSpringBootApp30WithCDIFeatureEnabled()
  - CommonWebFluxTests30
    - testBasicWebFluxtAppServlet60()
    - testBlockingIOServlet60()
  - CommonWebServerTests30
    - testBasicSpringBootApplication30Servlet60()
    - testDefaultHostWithAppPort30()
  - ConfigActuatorXMLOverrideTests30
    - useDefaultHostForMainAndActuatorPorts()
    - useDefaultHostForMainConfigActuatorPorts()
    - useDefaultHostWithAppPortForMainConfigActuatorPorts()
    - useConfigForMainAndActuatorPorts()
    - useOverrideForMainAndActuatorPorts()
  - ConfigDropinRootTests30
    - testDropinsRoot()
  - ConfigServerXMLOverrideTests30
    - configServerXMLOverrideVirtualHost()
    - configServerXMLOverrideHttpEndpoint()
    - configureServerXMLOverrideSSL()
    - configureServerXMLOverrideKeyStores()
    - testDefaultHostWithAppPortconfigureServerXMLOverrideSSL()
    - testDefaultHostWithAppPortconfigureServerXMLOverrideKeyStores()
  - ConfigSpringBootApplicationClassloaderTests30
    - testSpringBootApplicationClassloaderDefaultVisibility()
    - testSpringBootApplicationClassloaderDefaultNoIbmApiVisibility()
  - ConfigSpringBootApplicationTagTests30
    - testSpringBootApplicationTag()
    - testContextParams()
    - testServerHeader()
  - ConfigSpringBootApplicationWithArgsTests30
    - testSpringAppArg1()
    - testSpringAppArg2()
  - EnableSpringBootTraceTests30
    - testEnableSpringBootTraceFor30()
  - ErrorPage30Test
    - test404ErrorPage()
    - testExceptionErrorPage()
    - testDefaultErrorPage()
  - ExceptionOccuredAfterAppIsAvailableTest30
    - testSpringAppWithExceptionInMainMethod()ExtractedAppTests30
    - testExtractedThinApp()
    - testExtractedFatApp()
    - testLooseApp()
  - GenerateWebServerPluginTests30
    - testPluginCfgGeneratedUsingDefaultVirtualHost()
    - testPluginCfgGeneratedUsingSpringBootVirtualHost()
  - InvalidAppTests
    - testNoManifest30()
    - testNoStartCLass30()
  - JakartaFeatureTests30
    - testBasicAppEnableJavaee10()
  - JSPTests30
    - testJSP()
    - testWelcomePage()
    - testWelcomePageOnDefaultHost()
  - MimeMapping30
    - testMimeMapping()
  - MissingServletTests30
    - testMissingServletFor30()
  - MissingSslFeatureTests30
    - testMissingSslFeatureFor30()
  - MissingWebsocketFeatureTests30
    - testMissingWebsocketFor30()
    - testMissingWebsocketWithSecurity()
  - MultiContextTests30
    - useDefaultHostPorts()
    - useDefaultHostWithAppPort()
    - useAppConfigPorts()
  - MultiModuleProjectTests30
    - testBeanInRootInitialized()
    - testBeanInModuleInitialized()
  - MultipleApplicationsNotSupported30
    - testMultipleApplicationsNotSupported()
  - NeedSpringBootFeatureTests30
    - testNeedSpringBootFeature30()
  - NonZipExtensionFilesInBootInfLibTests30
    - expectServerStartFailureWhenANonZipLibraryExistsInAppArchive()
    - expectServerStartSuccessWhenAZipLibraryWithNonZipExtensionExistsInAppArchive()
  - NoServletRequiredAppTests30
    - testNoServletRequiredFor30()
  - PreThinnedSpringBootTests30
    - testWithSharedCache()
  - SpringSecurityTests30
    - testSpringWithSecurity()
    - testSpringWithoutSecurity()
  - SSLMutualAuthTests30
    - testClientAuthNeedWithClientSideKeyStoreFor30()
    - testClientAuthNeedWithoutClientSideKeyStoreFor30()
    - testClientAuthWantWithoutClientSideKeyStoreFor30()
  - SSLTests30
    - testSSLSpringBootApplication30()
    - testSSLDefaultHostWithAppPort30()
  - TemplateTests30 {
    - testCreateSpringBoot3()
  - UnsupportedConfigWarningTest30
    - testUnsupportedSessionConfigWarning()
    - testUnsupportedCompressionWarning()
  - UseDefaultHostTest30
    - testUseDefaultHost30()
  - WarmStartTests30
    - testWarmStartConfig()
  - WebAnnotationTests30
    - testWebAnnotations()
  - WebSocketTests30
    - testEchoWebSocket30()
  - utility/SpringBootUtilityThinTest
    - testDefaultTargets()
    - testSetTargets()
    - testParentCache()
    - testThinWarRemovesLibProvided()

Initial FAT delivery was missing (had disabled) five failing FAT test classes.  The tests were enabled by these issues, which are now resolved (closed):

- "Enable Servlet and WebSocket missing feature FATs" https://github.com/OpenLiberty/open-liberty/issues/25767
- "Enable WebSocket FAT" https://github.com/OpenLiberty/open-liberty/issues/25765
- "Enable trace enablement FAT" https://github.com/OpenLiberty/open-liberty/issues/25764
- "Enable security FAT" https://github.com/OpenLiberty/open-liberty/issues/25763

**Comment by ayoho** [comment]
Thanks for all of the clarification! LGTM 👍
