### ISSUE TITLE
WebSocket 2.2: Clarify the responsibilities for sending ping messages.

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#25776]
`https://github.com/jakartaee/websocket/issues/176`

**Comment by tssmith04** [comment]
There is a ping/pong test found [here](https://github.com/OpenLiberty/open-liberty/blob/9a21b67fce0608874a280e5714c8d505408e067d/dev/io.openliberty.wsoc.internal_fat/fat/src/io/openliberty/wsoc/tests/all/AnnotatedTest.java#L219)

**Comment by pnicolucci** [comment]
@volosied  any objection to closing this issue?

**Comment by volosied** [comment]
Problem: ```The WebSocket spec does not specifically say who is responsible for sending ping messages and how often they should be sent. ```

Spec Update: 

```
 No notification mechanism is provided for applications to receive notification of ping messages
as responding with a pong message is an implementation responsibility.

Developers who wish to send a ping message may do so using the *RemoteEndpoint* API.

Developers who wish to send an unsolicited pong message may do so using the *RemoteEndpoint* API.
```

```
Implementations may provide an implementation specific mechanism to configure
the sending of regular ping messages for a WebSocket connection. Alternatively,
developers may opt to implement their own ping/pong strategy.
```


As described, notification is implementation-specific. No customer / users are requesting any new behavior, so I consider this a no-op for us.
