### ISSUE TITLE
Calling stop on an already stopped server hangs for 30 seconds and then reports an error on WSL

### ISSUE THREAD

**Issue by colvinco** [OpenLiberty/open-liberty#25782]
**Describe the bug**  
If you stop a server, and then attempt to stop it again, the command hangs and eventually reports an error, exiting with code `21`.
In version `22.0.0.13` the error was reported immediately, in `23.0.0.1` onwards the command waits for some time before erroring.

**Steps to Reproduce**  
Create a server with a simple server.xml ```<server description="demo server"></server>```
Run `./server start demo`, then run `./server stop demo` twice. On the second invocation (and any subsequent ones) the command will hang and report an error until you again start the server.

```
colvin@host:~/githome/Liberty/wlp/bin$ time ./server start demo

Starting server demo.
Server demo started with process ID 25136.

real    0m0.593s
user    0m0.106s
sys     0m0.025s
colvin@host:~/githome/Liberty/wlp/bin$ time ./server stop demo

Stopping server demo.
Server demo stopped.

real    0m0.169s
user    0m0.103s
sys     0m0.024s
colvin@host:~/githome/Liberty/wlp/bin$ time ./server stop demo

Stopping server demo.
Server demo stop failed. Check server logs for details.

real    0m30.093s
user    0m0.116s
sys     0m0.030s
```

**Expected behavior**  
As on Windows, the command should simply report that the server isn't running and exit gracefully.

```
Liberty\wlp\bin>server start demo
Starting server demo.
Server demo started.

Liberty\wlp\bin>server stop demo
Stopping server demo.
Server demo stopped.

Liberty\wlp\bin>server stop demo
Stopping server demo.
Server demo is not running.
```

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.1 - 23.0.0.6

**Comment by jhanders34** [comment]
#regression

**Comment by jimblye** [comment]
I am also having difficulty recreating this one.   What flavor of linux are you running?

```

root@purifies1:~/wlp/bin# ./server start

Starting server defaultServer.
Server defaultServer started with process ID 32112.
root@purifies1:~/wlp/bin# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
root@purifies1:~/wlp/bin# ./server stop

Stopping server defaultServer.
Server defaultServer stopped.
root@purifies1:~/wlp/bin# ./server stop

Stopping server defaultServer.
Server defaultServer is not running.
root@purifies1:~/wlp/bin# ./server stop

Stopping server defaultServer.
Server defaultServer is not running.
root@purifies1:~/wlp/bin# ./server stop

Stopping server defaultServer.
Server defaultServer is not running.
root@purifies1:~/wlp/bin# ./server stop

Stopping server defaultServer.
Server defaultServer is not running.
root@purifies1:~/wlp/bin# ./server stop

Stopping server defaultServer.
Server defaultServer is not running.
root@purifies1:~/wlp/bin# 
```

**Comment by jimblye** [comment]
root@purifies1:~/wlp/bin# ./server start

```
Starting server defaultServer.
Server defaultServer started with process ID 32112.
root@purifies1:~/wlp/bin# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
root@purifies1:~/wlp/bin# ./server stop

Stopping server defaultServer.
Server defaultServer stopped.
root@purifies1:~/wlp/bin# ./server stop

Stopping server defaultServer.
Server defaultServer is not running.
root@purifies1:~/wlp/bin# ./server stop

Stopping server defaultServer.
Server defaultServer is not running.
root@purifies1:~/wlp/bin# ./server stop

Stopping server defaultServer.
Server defaultServer is not running.
root@purifies1:~/wlp/bin# ./server stop

Stopping server defaultServer.
Server defaultServer is not running.
root@purifies1:~/wlp/bin# ./server stop

Stopping server defaultServer.
Server defaultServer is not running.
root@purifies1:~/wlp/bin# 
```

**Comment by colvinco** [comment]
Hi @jimblye, I'm using Ubuntu 22.04.1 in WSL, and I've also just tried in the openjdk:latest docker container, it happens in both. Wonder where the difference lies

```
colvin@host:~/githome/Liberty/wlp/bin$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

$ java -version
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)
```

```
bash-4.4# java -version
openjdk version "18.0.2.1" 2022-08-18
OpenJDK Runtime Environment (build 18.0.2.1+1-1)
OpenJDK 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)

bash-4.4# ./server start

Starting server defaultServer.
Server defaultServer started with process ID 51.
bash-4.4# ./server stop

Stopping server defaultServer.
Server defaultServer stopped.
bash-4.4# ./server stop

Stopping server defaultServer.
Server defaultServer stop failed. Check server logs for details.
```

**Comment by jimblye** [comment]
@colvinco 
When this fails and you get the "is already running." message, do you see messages in console.log similar to the following?:

```
WARNING: Illegal reflective access by com.ibm.ws.kernel.service.location.internal.Activator (file:/C:/temp/ol23-1/wlp/lib/com.ibm.ws.kernel.service_1.3.73.jar) to field javax.naming.spi.NamingManager.initctx_factory_builder
WARNING: Please consider reporting this to the maintainers of com.ibm.ws.kernel.service.location.internal.Activator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by jimblye** [comment]
This seems specific to WSL.   In the ServerLock.testServerRunning() method, **when the .sLock file exists AND we're running on WSL it will always return true.**  So we think that the server is running, but there is no .sCommand file, which would be the case when the server is still starting up ... but it isn't starting up ... and so we wait for 30 seconds for the .sCommand file to appear.   The .sCommand file gives us the information which we can use to send the stop command to the running server.

The .sLock file seems to always exist, which means on WSL testServerRunning is always going to return true:

```
            if (tryServerLock() && !FileUtils.isWSL()) {
                // we could obtain the server lock, server is not running
                return false;
            }
```
  
 I believe the new behavior is the wait for the .sCommand to appear, which was added because there is a case where starting and immediately stopping hangs when Liberty is running as a windows service.   
 
 Will need to think about how to best solve this.   Normally, the wait for .sCommand shouldn't be a problem because , before we do that, we check to see if the server is running ... and that  ... plus no .sCommand means the server must be starting.  So we wait.
 
 But ... on WSL, we seem to always think the server is running because of the check for isWSL().   That check most likely was added in error, and should be removed.

**Comment by colvinco** [comment]
Ah okay cool, that explains why I saw it in the docker container too as the daemon is running in WSL it reports the same version
```
sh-4.4# java a.java 
Linux
5.15.90.1-microsoft-standard-WSL2
```
