### ISSUE TITLE
Faces 4.1: Repeat existing Faces FATs with `faces-4.1`

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#25784]
- [x] com.ibm.ws.jsf.2.2_fat -> https://github.com/OpenLiberty/open-liberty/pull/27485
- [x] com.ibm.ws.jsf.2.3_fat -> https://github.com/OpenLiberty/open-liberty/pull/27485
- [x] io.openliberty.org.apache.myfaces.4.0_fat -> https://github.com/OpenLiberty/open-liberty/pull/27485
- [x] com.ibm.ws.jsf_fat_lWAS (ws-cd-open)
- [x] https://github.com/OpenLiberty/open-liberty/issues/27415

**Comment by tssmith04** [comment]
All of these tasks have been completed.
