### ISSUE TITLE
unable to capture the SAML authentication failure in GUI

### ISSUE THREAD

**Issue by vijayanjay** [OpenLiberty/open-liberty#25794]
**Describe the bug**  
When there is a failure of SAML authentication, the corresponding error is not capture in GUI.
Below message is displayed in GUI.
```
Cannot GET /ibm/saml20/errorMsg.jsp
```

**Steps to Reproduce**  
We are using samlWeb-2.0  feature from liberty for our SAML authentication.
While providing invalid metadata file, we could see below error in liberty logs.
`[7/18/23, 14:54:13:869 UTC] 000000a0 com.ibm.ws.security.saml.error.SamlException                 E CWWKS5023E: The identity provider (IdP) metadata file [/opt/ibm/wlp/usr/servers/defaultServer//resources/security/idpMetadata.xml] in the service provider (SP) [defaultSP] is not valid. The cause of the error is [No IDPSSODescriptor]
`
But the same issue is not adequately captured in the GUI. As a result, we encounter difficulties performing a graceful logout, and the cookies are not being cleared in the browser. This situation leads to consecutive authentication methods considering it as a SAML flow, causing further complications.

**Expected behavior**  
Corresponding error should be captured and displayed properly in the GUI.

**Diagnostic information:**  
Version information:
```
Product name: WebSphere Application Server
Product version: 23.0.0.5
Product edition: BASE_ILAN
```
Feature info:
```
apiDiscovery-1.0
appSecurity-2.0
cdi-2.0
concurrent-1.0
distributedMap-1.0
el-3.0
federatedRegistry-1.0
jaxrs-2.0
jaxrsClient-2.0
jdbc-4.1
jdbc-4.2
jndi-1.0
json-1.0
jsonp-1.0
jsp-2.2
jsp-2.3
jwt-1.0
ldapRegistry-3.0
oauth-2.0
openidConnectServer-1.0
restConnector-2.0
samlWeb-2.0
servlet-3.0
servlet-3.1
servlet-4.0
socialLogin-1.0
ssl-1.0

Product Extension: usr
customStoreSecurity-1.0
```

Please let us know if it is a bug or we missing something from the configuration perspective.

Capturing the SAML.xml contents for reference:
```
<server>
    <featureManager>
                <feature>samlWeb-2.0</feature>
    </featureManager>
    <keyStore id="samlKeyStore" password="insecurePass" location="${server.config.dir}/resources/security/saml.jks"/>
    <samlWebSso20 id="defaultSP" enabled="true" keyStoreRef="samlKeyStore" keyAlias="saml" authFilterRef="samlAuthFilter" nameIDFormat="unspecified" spHostAndPort="https://cp-console-ibm-common-services.apps.vijt.cp.fyre.ibm.com" createSession="true">
    </samlWebSso20>
    <authFilter id="samlAuthFilter">
       <requestUrl id="myRequestUrl" urlPattern="loginwithsaml" matchType="Contains"/>
    </authFilter>
</server>
```

**Comment by arunavemulapalli** [comment]
@vijayanjay 
In my local testing, I could see that we access and display the generic content of the default error page successfully errorMsg.jsp ( please note that the message content is very generic 
We have something like this displayed in the browser - 

HTTP Error 403 - Forbidden

we really don't display the server side error message (E CWWKS5079E:) that you see in the logs and this behavior is similar to our other sso features.
 
 having said that, I need to investigate why we are not able to access it in your env.. the one difference I can think of is that I don't have `spHostAndPort` in my configuration 

Can you please provide me server logs with your configuration and enable following trace -
(\<logging maxFileSize="0" traceSpecification="com.ibm.ws.webcontainer.\*=all=enabled:com.ibm.ws.security.saml.\*=all=enabled:*=info=enabled"\/>

also, try specifying error page url config attribute in the samlWebSso20 configuration and see if it works - 
something like this 
`errorPageURL="https://host:port/ibm/saml20/errorMsg.jsp"`

thanks
aruna

**Comment by vijayanjay** [comment]
Sure @arunavemulapalli 
We will test with below configuration and update you the result.
```
errorPageURL="https://host:port/ibm/saml20/errorMsg.jsp"


```

**Comment by ayoho** [comment]
Hi @vijayanjay. I'm going to close this issue. Feel free to re-open if any issues persist.
