### ISSUE TITLE
Feature Test Summary for supporting Java 21 in Open Liberty

### ISSUE THREAD

**Issue by gjwatts** [OpenLiberty/open-liberty#25924]
## Test Strategy

This Feature Test Summary is provided to add a new Java 21 specific FAT https://github.com/OpenLiberty/open-liberty/issues/25751 and not to introduce any new or modified Open Liberty functionality.

Virtual Threads (VT) are a new released feature in Java 21 and are covered in issue #25999.  To ensure VTs pose little to no risk for Open Liberty, manual VT testing has been performed by Chuck Bridgham.

Normally FAT testing is designed to validate the functionality of a new or changed feature in Open Liberty.  Since there is no new OL functionality to test, the associated FAT test is a validation check to make sure we are running on Java 21. To accomplish that, this FAT uses a WAR file for testing that has been compiled at Java 21 using functionality that is specific to Java 21.

The real testing validation for Java 21 is done via our entire suite of Open Liberty and WebSphere Liberty FAT buckets.

### List of FAT projects affected

* io.openliberty.java.internal_fat - https://github.com/OpenLiberty/open-liberty/issues/25751
* com.ibm.ws.jpa.tests.javasupport_fat - https://github.com/OpenLiberty/open-liberty/pull/25037

### Test strategy

* What functionality is new or modified by this feature?
  * No new Liberty functionality is added or changed by this feature
* What are the positive and negative tests for that functionality?
  * This FAT adds one simple test to ensure we are running on Java 21 by using functionality that is specific to Java 21 ([Nested Record Patterns](https://openjdk.org/jeps/440)).
* What manual tests are there (if any)?  None.

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

**Comment by ayoho** [comment]
LGTM 👍

**Comment by gjwatts** [comment]
Confidence level vote was 4
