### ISSUE TITLE
CWWKS1706E + CWWKS1739E errors occurs when minimal jwks data is provided by Identity Provider

### ISSUE THREAD

**Issue by ghost** [OpenLiberty/open-liberty#25927]
Dear all,

**Describe the bug**  
CWWKS1706E + CWWKS1739E errors occurs when minimal jwks data is provided by Idp

**Steps to Reproduce**  

This bug has been originally discovered when configuring "openidConnectClient" config element for a JSF webapp deployed in Open Liberty 23.0.0.7 having "jwkEndpointUrl" returning a minimal data (see below).

After analysis, **the original errors takes place within JwKRetriever class and can be reproduce by completing the Open Liberty Unit test** within `com.ibm.ws.security.common.jsonwebkey` module in `JwKRetrieverTest.java` class as follow : 

### 1 - Alter the jwk_test.json (open-liberty\dev\com.ibm.ws.security.common.jsonwebkey\test\com\ibm\ws\security\common\jwk\impl) file as follow

    {
    "kty": "RSA",
    "n": "rkCYJj7QPIURA+T0arwFkBWK/8PemAW/gppsY5p+uqwASoFNnHLOiUpS6k3NJRcb0QEu2MHjt7IKZ/mya4NgoAMfM+lm0+QmDhY1XFUrmKj0WQhp/Oc6X48kX2zDmu00GXjO3H2446IofTnBeWxIpClpH+aQ0rcCZlLOu/O/CDIHz30qpe4NT4MlkYUeKNltUBctNQP7VMJw4iPHCdsXlIfpVqzONWIdbsFTsk1r3ynrReOeIbP4JA2/sI03LdSS0XxMVYe7zwIb9dHmWlOjMcejNTEh4fRdNnwQYbU3aWhj55gNYpDxUvwazwN52Rm9XoTsv+pi0pj3SK0PeE3s1w==",
    "e": "AQAB"
    }

Please note that here above the `kid` and `use` key are intentionnaly missing (ie : not mandatory following https://www.ietf.org/rfc/rfc7517.txt).

### 2 - Add a new UT method in class JwKRetrieverTest.java within open-liberty\dev\com.ibm.ws.security.common.jsonwebkey\test\com\ibm\ws\security\common\jwk\impl

    @Test
    public void testGetPublicKeyFromJwk_relativeLocationPEM_noKidSpecified_minimalJWKS_RunTwice() throws Exception {
        keyLocation = RELATIVE_JWK_LOCATION;
        JwKRetriever jwkRetriever = new JwKRetriever(configId, sslConfigurationName, jwkEndpointUrl, jwkSet, sslSupport, hnvEnabled, null, null, signatureAlgorithm, publickey, keyLocation);

        PublicKey publicKey = jwkRetriever.getPublicKeyFromJwk(null, null, "sig", false);

        assertNotNull("REP_A1 : THIS ONE IS OK", publicKey);

        publicKey = jwkRetriever.getPublicKeyFromJwk(null, null, "sig", false);

        assertNotNull("REP_A2 : THIS ONE IS KO but should be OK", publicKey);

    }

3) The first `REP_A1` assert is validated but the second one `REP_A2` fall in error.

**Expected behavior**  

Both `assertNotNull("REP_A1",...)` and `assertNotNull("REP_A2", ...)` as described above should be ok.

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.7
 - Affected feature(s) openidConnectClient-1.0
 - Java Version: 17
 - server.xml configuration : not relevant
 - If it would be useful, upload the messages.log file : not relevant

**Additional context**  
JwKRetriever relies on optional "kid" and "use" key to store and retrieve already meet jwk.
When same key is meet twice, the `jwkSet` parameter store the same key several times then is rejeted by the `jwks.size() == 1` test within `com.ibm.ws.security.common.jwk.impl.JWKSet.java` (then null is sent as a Key and CWWKS1706E + CWWKS1739E occurs in upper layers) :
	
	    @Sensitive
		public Key getKeyBySetIdAndKeyText(@Sensitive String setId, @Sensitive String keyText, JwkKeyType keyType) {
			Key key = null;
			JSONWebKey jwk = getPEMKey(setId, keyText);
			if (jwk == null) {
				Set<JWK> jwks = jwksBySetId.get(keyText);
				if (jwks != null && jwks.size() == 1) {
					jwk = jwks.iterator().next();
				}
			}
			if (jwk != null) {
				key = getKeyForJwkKeyType(jwk, keyType);
			}
			return key;
		}

**Comment by ayoho** [comment]
Thank you for opening an issue, @placidetmuzo. I've got a potential fix in the works here: https://github.com/OpenLiberty/open-liberty/pull/25935.

**Comment by ghost** [comment]
@ayoho : thank you for the quick change.
