### ISSUE TITLE
Add tests for MP RM 3.0 Nack with kafka connector

### ISSUE THREAD

**Issue by abutch3r** [OpenLiberty/open-liberty#25969]
In MP RM 2.0 Negative Acknowledges (Nacks) were added in case of error cases

We should add some test cases similar to the existing Acknowledgement test cases 

For MP RM

**Comment by Azquelt** [comment]
We need to decide what (if anything) the kafka connector should do when a message it produced is nacked.

We could define some fallback logic within the connector itself, or we could expect the user to put in a processor to handle exceptions and re-routing.
