### ISSUE TITLE
Liberty self-extract uses excessive disk space

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#260]
Problem Background:
While running the MicroProfile conference app [1] with Liberty, there are 4 microservices that run on 4 different Liberty servers.  In order to be consistent with other application servers, Liberty is started with the self extracting jar (java -jar target/microservice-*.jar).

Each time we run "java -jar" to self extract Liberty, it creates an entirely new Liberty image with a single server at $USER_HOME/wlpExtract/<server_name>_<timestamp_ms>.  After running this repo twice, I have the following directories:
  microservice-schedule-liberty_482264804460972
  microservice-schedule-liberty_490704479741798
  microservice-session-liberty_482264842995412
  microservice-session-liberty_490704464140126
  microservice-speaker-liberty_482264789502970
  microservice-speaker-liberty_490704427471449
  microservice-vote-liberty_482264828692444
  microservice-vote-liberty_490704456719957

This equates to 450MB of disk space each time I want to run these 4 Liberty servers. We need to have a solution that is more conservative of disk space when re-running self extracting jars, as many build build tools such as Maven may be doing today.

Proposed solutions:
A) Remove old WLP images during self-extract
B) Re-use existing WLP image (get rid of the trailing underscore and numbers)

[1]: https://github.com/eclipse/microprofile-conference

**Comment by NottyCode** [comment]
Options discussed:

1) Delete on exit - issue with this is the logs are missing so if something goes wrong diagnosis is harder
2) Delete on exit, but leave the content of the logs folder
3) Delete on exit unless using a non-default extract dir. 
4) Delete on next start so there is at most 2 and normally 1 lying around. When doing this the first check would be whether the older server is running already. Also need to do async to startup.
5) Do 2 unless WLP_JAR_EXTRACT_DIR is set at which point don't delete.

Extract dir is set based on:

     * 1) ${WLP_JAR_EXTRACT_DIR}
     * 2) ${WLP_JAR_EXTRACT_ROOT}/<jar file name>_nnnnnnnnnnnnnnnnnnn
     * 3) default - <home>/wlpExtract/<jar file name>_nnnnnnnnnnnnnnnnnnn

Need to investigate whether to use a shutdown hook, or call delete on exit on the jar. If using delete on exit you have to do it in the right order, and you need to ensure files created during the run get captured. Might be easier to do delete in a shutdown hook but that might have issues on windows if the jvm has file locks.

Liberty already has a few shutdown hooks so using a shutdown hook might be problematic in terms of ordering. Need to investigate if deleteOnExit runs after shutdown hooks, probably does but need to be sure.

Overall preference is for option 5. It was discussed that deleting files in the usr folder, but outside of logs could make some debug harder, but the decision was made that this was likely a minor problem and we could revisit if such a condition occurs.

**Comment by aguibert** [comment]
I've opened issue #338 which will be used to deliver the implementation of option 5.
