### ISSUE TITLE
Include directories containing configDropins - Feature Test Summary

### ISSUE THREAD

**Issue by rsherget** [OpenLiberty/open-liberty#26006]
FTS for #25149 

## Test Strategy

There is a new FAT test in the com.ibm.ws.config_fat bucket that makes sure servers get configured correctly when a directory is used with the <include> tag. 

### List of FAT projects affected

* com.ibm.ws.config_fat

### Test strategy

* In the server.xml, a user can include more configuration files by adding the `<include>` tag. Previously, this could only be used by adding a file location or a URI, now it can also be used with a directory. It will check the directory for any configuration files.
* There is a positive test for making sure the server gets configured correctly with config files in a directory. As this is a modification and not an entirely new feature, there are already positive and negative tests.
* Theres automated testing for checking if the XML parser reads the includes directory properly.

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values: 4

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by ayoho** [comment]
Only had one question about a negative scenario: What happens if the directory being pointed to doesn't exist? Is there already a test for that?

**Comment by rsherget** [comment]
> Only had one question about a negative scenario: What happens if the directory being pointed to doesn't exist? Is there already a test for that?

It is processed the same way as a missing file, the user receives a message saying `configuration resource does not exist or cannot be read.`

While there is a test for including a file that does not exist, there is nothing explicitly testing a directory that does not exist.

**Comment by ayoho** [comment]
For completeness I think it would be useful to have a test to cover that scenario, but that's not something I'd hold up approval over. Aside from that, coverage sounds fine to me 👍
