### ISSUE TITLE
Fix Spnego FAT - localhost keytab needs to be re-created

### ISSUE THREAD

**Issue by Zech-Hein** [OpenLiberty/open-liberty#26015]
it seems the HTTP/localhost account or SPN on the KDC is no longer valid and need to be regenerated.

We will need to update the localhost keytab the tests use after generate a new keytab key for the HTTP/localhost account. We'll need 2 separate localhost.keytab files since the 2 KDC's are in different domains/forests

Internal Build Break Defect: 296965

**Comment by karel-harjono** [comment]
PR merged: https://github.com/OpenLiberty/open-liberty/pull/26124
