### ISSUE TITLE
mpTelemetry-1.0 does not work when the application contains no CDI beans

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#26043]
**Describe the bug**  
mpTelemetry-1.0 does not work when the application contains no CDI beans.

This is quite unusual as mpTelemetry is generally used with JAX-RS and JAX-RS resources are usually CDI beans, but the problem can be seen if the user is only using JAX-RS client or has a beans.xml with `bean-discovery-mode=none`.

TODO: Add details

**Steps to Reproduce**  

Deploy an app with a servlet which uses JAX-RS client to call another service. The app must have no CDI beans.

No spans are created when the JAX-RS client call is made.

TODO: Are any errors output?

**Expected behavior**  

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.3+ (all versions containing `mpTelemetry-1.0`)
 - Affected feature(s): `mpTelemetry-1.0`
 - Java Version: N/A

**Additional context**  

This occurs because CDI is disabled for performance reasons when the application contains no beans or extensions. `mpTelemetry-1.0` is internally relying on CDI being active.

**Comment by benjamin-confino** [comment]
Fixed in #26157 which creates a new way to access open telemetry via static methods that does not rely on CDI and uses in preference to CDI.
