### ISSUE TITLE
Set Smallrye.reactive.messaging to be in strict mode

### ISSUE THREAD

**Issue by abutch3r** [OpenLiberty/open-liberty#26082]
Smallrye Reactive Messaging is not Spec compliant out of the box. To make it so, strict mode must be set to `true` to cause it to emit DeploymentExceptions

```
smallrye-messaging-strict-binding=true
```

The TCK can be made to pass by supplying the above option in the bootstrap.properties.

As part of this we need to remove the option so that we know that it is working

**Comment by Azquelt** [comment]
See https://github.com/OpenLiberty/open-liberty/pull/17761/commits/fd8872f4d796976c5606673b8a195dbc6101f39e for an example of how we did something similar for MP OpenAPI
