### ISSUE TITLE
add JOSE head "typ" of "JWT" to jwt header in JWT builder

### ISSUE THREAD

**Issue by chunlongliang-ibm** [OpenLiberty/open-liberty#261]
Given that our JWT Builder only builds "JWT", it is preferred that we add {"typ":"JWT"} header to JwtBuilder, and also to the mpjwt access_token in OIDC provider.
In the class JwsSigner's method getSignedJwt, we can add this line code
         jws.setHeader("typ", "JWK");

**Comment by chunlongliang-ibm** [comment]
This change is also in line with MP-JWT spec, and current common practice in many vendors

**Comment by brutif** [comment]
This is a duplicate of issue 1330, which  will be fixed by pull 1360.  Closing as a duplicate.
