### ISSUE TITLE
Telemetry-1.0 Disabled warning message

### ISSUE THREAD

**Issue by Yas-Franco** [OpenLiberty/open-liberty#26158]
The warning message "The MicroProfile Telemetry Tracing feature is enabled but not configured to generate traces for the {0} application." does not appear when MicroProfile Telemetry 1.0 is not enabled.

**Steps to Reproduce**  
1. Enable the mpTelemetry-1.0 feature
2. Do not set "otel.sdk.disabled=false"
3. Make request to application 
The warning message shows up as `CWMOT5100.tracing.is.disabled` 

**Expected behavior**  
"The MicroProfile Telemetry Tracing feature is enabled but not configured to generate traces for the {0} application." should be in the logs"

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.9
 - Affected feature(s): mpTelemetry-1.0
 - server.xml configuration (WITHOUT sensitive information like passwords):
 ```	
 <featureManager>
		<feature>mpTelemetry-1.0</feature>
</featureManager>
```

**Comment by benjamin-confino** [comment]
Will be fixed by #26177 

The relevant line is dev/io.openliberty.microprofile.telemetry.1.0.internal/bnd.bnd line 56
