### ISSUE TITLE
Create Jakarta Annotations 3.0 feature

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#26166]
We now expect an [Annotations 3.0 spec](https://jakarta.ee/specifications/annotations/3.0/) in EE11 so we need the corresponding API feature created

**Comment by jhanders34** [comment]
This is the one EE 11 liberty feature I hadn't created yet since it was a late add.  I attached a PR to the issue that adds the annotation 3.0 feature.
