### ISSUE TITLE
Disable checkpoint byte transformation for resource provider classloaders

### ISSUE THREAD

**Issue by dazavala** [OpenLiberty/open-liberty#26174]
Discover whether byte transformation may be disabled for AppClassLoader instances that load resource provider classes.  Immediate examples include loaders for shared libraries referenced by `<jdbcProvider>` and loaders for standalone `<resourceAdapter>`s.  Currently, features cannot exercise provider classes during checkpoint at `beforeAppStart` without prematurely taking the checkpoint before any application class executes.  By design the server will start a checkpoint `beforeAppStart` when the JVM performs static initialization of an application class during its first use while the application is starting and requires a startup behavior (e.g. Run servlet `init()` at startup per `@WebServlet(loadOnStartup=1)`.

**Comment by tjwatson** [comment]
tracked in #27336
