### ISSUE TITLE
Make MP Telemetry 1.1 support Java 8

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#26190]
We're not sure we want to do this, but we may do since we're supporting older versions of EE which only require Java 8. OTel itself supports Java 8 so in theory it shouldn't be hard for us to do so.

- [ ] Change the compile level of all the bundles and remove the `Require-Capability` entry for Java version.
- [ ] Change the compile level of all relevant FAT projects
- [ ] Ensure FAT projects have repeats correctly configured so that LITE mode will run appropriate tests for builds which use Java 8.

**Comment by tevans78** [comment]
We have decided not to do this. We only need to support Java 11+.
