### ISSUE TITLE
Add support for Apache CXF property org.apache.cxf.service.scope

### ISSUE THREAD

**Issue by JulienCanchesHCL** [OpenLiberty/open-liberty#2627]
This issue is filed following up this [conversation](https://developer.ibm.com/answers/questions/435088/-30/#) at devWorks answers with @andymc12 .

I have a per-request JAX-RS resource with a method annotated with @PreDestroy. With Apache Wink, the @PreDestroy method was called after the return value of jax-rs methods was serialized. Using the Apache CXF version bundled in Liberty, the @PreDestroy method is called after the jax-rs method returns, but before the return value is serialized.

According to Apache CXF documentation, an option is available to change this behavior. Quoting from [this page](http://cxf.apache.org/docs/jaxrs-services-configuration.html#JAXRSServicesConfiguration-PostConstructandPreDestroy)

> Prototype beans will have their postconstruct and predestroy method called before a resource method is invoked and immediately after the invocation has returned but before the response has actually been serialized. You can indicate that the predestroy method has to be called after the request has completely gone out of scope (that is after the response body if any has been written to the output stream) by adding an "org.apache.cxf.jaxrs.service.scope" property with the value set to "request".

I need to set this property so my application continues working.

**Comment by andymc12** [comment]
Hi @JulienCanchesHCL - while looking into this further, I discovered that it should be possible to specify this property in your `Application` subclass without any changes in Liberty.  Can you try this in your application?

Here is an example:
```
@ApplicationPath("/myApp")
public class MyApp extends Application {

    @Override
    public Map<String, Object> getProperties() {
        Map<String, Object> props = new HashMap<String, Object>();
        props.put("org.apache.cxf.service.scope", "request");
        return props;
    }
...
}
```

In PR #2698, I'm adding support so that this property could be specified in the web.xml as a servlet init property - like this:
```
   <servlet>
     <servlet-name>ServiceScopeSpecifiedInWebXml</servlet-name>
     <servlet-class>com.ibm.websphere.jaxrs.server.IBMRestServlet</servlet-class>
     <init-param>
         <param-name>javax.ws.rs.Application</param-name>
         <param-value>test.service.scope.MyApp</param-value>
     </init-param>
     <init-param>
         <param-name>org.apache.cxf.service.scope</param-name>
         <param-value>request</param-value>
     </init-param>
   </servlet>
```

**Comment by JulienCanchesHCL** [comment]
Hi @andymc12,

Specifying the property in my Application subclass did the trick. Thanks a lot for the tip.

Regarding your second example. I don't think it matters, but I am not using a specific reference to IBMRestServlet in web.xml. I use the following declaration:
``` 
<servlet>
    <servlet-name>test.service.scope.MyApp</servlet-name>
</servlet>
```
I cannot find any more where I found this shortcut notation, but I am pretty sure it was on IBM Knowledge Center.
