### ISSUE TITLE
Investigate J2S error when running SimpleJSPTest against EE11

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#26327]
Repeating https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.cdi.jee_fat/fat/src/com/ibm/ws/cdi/jee/jsp/SimpleJSPTest.java against EE11 causes...

Begin AccessControlException report for for log file:
/Users/tevans/Liberty/openLibertyGit/open-liberty/dev/build.image/wlp/usr/servers/cdi12BasicServer/logs/SimpleJSPTest.log

============================================================

Found 2 total AccessControlExceptions in logs.
Found 2 unique occurrances.

============================================================

("java.util.PropertyPermission" "jakarta.el.BeanSupport.doNotCacheInstance" "read")
Stack: 
java.security.AccessControlException: Access denied ("java.util.PropertyPermission" "jakarta.el.BeanSupport.doNotCacheInstance" "read")java.base/java.security.AccessController.throwACE(AccessController.java:177)
java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:239)
java.base/java.security.AccessController.checkPermission(AccessController.java:386)
java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:416)
com.ibm.ws.kernel.launch.internal.MissingDoPrivDetectionSecurityManager.checkPermission(MissingDoPrivDetectionSecurityManager.java:47)
java.base/java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1160)
java.base/java.lang.System.getProperty(System.java:591)
java.base/java.lang.System.getProperty(System.java:574)
java.base/java.lang.Boolean.getBoolean(Boolean.java:282)
jakarta.el.BeanSupport.<clinit>(BeanSupport.java:31)
jakarta.el.BeanELResolver.property(BeanELResolver.java:255)
jakarta.el.BeanELResolver.getValue(BeanELResolver.java:84)
org.apache.jasper.el.JasperELResolver.getValue(JasperELResolver.java:113)
org.apache.el.parser.AstValue.getValue(AstValue.java:169)
org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190)
org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:811)
com.ibm._jsp._index._jspx_meth_c_out_0(_index.java:175)
com.ibm._jsp._index._jspService(_index.java:147)
com.ibm.ws.jsp.runtime.HttpJspBase.service(HttpJspBase.java:102)

("java.lang.RuntimePermission" "getClassLoader")
Stack: 
java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "getClassLoader")java.base/java.security.AccessController.throwACE(AccessController.java:177)
java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:239)
java.base/java.security.AccessController.checkPermission(AccessController.java:386)
java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:416)
com.ibm.ws.kernel.launch.internal.MissingDoPrivDetectionSecurityManager.checkPermission(MissingDoPrivDetectionSecurityManager.java:47)
java.base/java.lang.Thread.getContextClassLoader(Thread.java:567)
jakarta.el.ExpressionFactory.newInstance(ExpressionFactory.java:76)
jakarta.el.ExpressionFactory.newInstance(ExpressionFactory.java:62)
com.ibm.ws.jsp.webcontainerext.JSPExtensionFactory.getWrapperExpressionFactory(JSPExtensionFactory.java:146)

End of AccessControlException report.

**Comment by Azquelt** [comment]
Looks like this system property read was added without doPriv in jakartaee/expression-language#195

All security manager calls were removed from the EL API in jakartaee/expression-language#193

**Comment by Azquelt** [comment]
Security Manager is being removed from EE11 so EE11 fat repeats now automatically disable J2S.
