### ISSUE TITLE
Add EE11 Repeat to CDI FATs which use RestfulWS

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#26335]
RestEasy currently has a dependency on ManageBean which no long exists in EE11. At the moment there are some CDI FATs which use RestEasy and can not be repeated against EE11. That should change in future and the repeat should be added.

**Comment by tevans78** [comment]
https://github.com/OpenLiberty/open-liberty/pull/26347 should unblock this issue

**Comment by Yas-Franco** [comment]
Covered by [#29005](https://github.com/OpenLiberty/open-liberty/issues/29005)
