### ISSUE TITLE
Need JAX-RS 2.1 test case where user packages their own JSON-B API/implementation

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#264]
In JAX-RS 2.0 we had tests where a user packages their own version of Jackson, and we ensure that their data is transformed correctly according to their Jackson configuration.  In JAX-RS 2.1, we are changing the default JSON serialization technology to JSON-B, but like our 2.0 implementation, we are not exposing these APIs (by default -- it will be possible to expose these APIs if the user also enables the `jsonb-1.0` feature).  

We need test cases for the scenario where a user packages their own version of JSON-B (both API and implementation) in their application.

**Comment by WhiteCat22** [comment]
Currently blocked by 
https://github.com/OpenLiberty/open-liberty/issues/1128
