### ISSUE TITLE
Add MP 6.1 repeats to mpJwt-2.1 FATs

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#26411]
mpJwt-2.1 depends on mpConfig-3.0 but should tolerate mpConfig-3.1. We should repeat some of the JWT FATs against mpConfig-3.1 (MP 6.1).

**Comment by c00crane** [comment]
Added repeats for the Env Var and System Properties tests from the mpJwt 2.1 FAT project.  Only added the repeats to the 2.1 tests that run with mpJwt 2.1 (there are variations that run the 2.1 tests with mpJwt 1.1, 1.2 and 2.0 to ensure the proper behavior (2.1 function isn't supported) - those DO not repeat with mpConfig-3.1)
Do we need to verify any behavior of mpJwt 1.1 - 2.0 with mpConfig3-1?  (any server startup issues?)

**Comment by c00crane** [comment]
Only needs to be tested with mpJwt 2.1 - so, this work is complete.
