### ISSUE TITLE
MP Config 1.3: Liberty variables ConfigSource

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#2643]
This will access variables via the VariablesRegistry but need to exclude some system variables ... TBD

**Comment by tevans78** [comment]
@neilgsyoung I think you have the code for this ready to go?

**Comment by neilgsyoung** [comment]
metatype xml needs a couple of tweaks: such as capitilisation of some key words.

**Comment by neilgsyoung** [comment]
Closing as this has been resolved through issue #4223 and PR #4287
