### ISSUE TITLE
Mp Telemetry 1.1 Feature Test Summary

### ISSUE THREAD

**Issue by Yas-Franco** [OpenLiberty/open-liberty#26445]
For #25187 

### List of FAT projects affected

* `io.openliberty.microprofile.telemetry.1.0.internal_fat`
* `io.openliberty.microprofile.telemetry.1.1.internal_fat_tck`
* `io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat`

### Test strategy

External open source packages have been updated from OpenTelemetry version `1.19.0` to `1.29.0`

The feature is compatible with older MicroProfile versions and older Java EE versions (7+) . Therefore, Repeats are required for all of the aforementioned projects for MpTelemetry-1.1 with the following MicroProfile versions: 
- MP 1.4 (EE7)
- MP 4.1 (EE8)
- MP 5.0 (EE9)
- MP 6.1 (EE10)

In addition:
- Tests for the Java Agent are repeated with the [1.29 version](https://mvnrepository.com/artifact/io.opentelemetry.javaagent/opentelemetry-javaagent/1.29.0)
- Tests with the OpenTracing Shim are repeated with the [1.29 version](https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-opentracing-shim/1.29.0)

This is a minor spec update. The test changes are therefore only about compatibility with other existing features, repeating existing tests etc... Any test that currently runs against mpTelemetry-1.0 should also work with mpTelemetry-1.1. There are minor differences with test results that should be tested with these repeats: 
- The error message that appears in logs is different for MpTelemetry-1.1 when OpenTelemetry is configured with an invalid Jaeger exporter.
- The exception thrown by OpenTelemetry when the exporter is misconfigured is now `io.opentelemetry.sdk.autoconfigure.spi.ConfigurationException` instead of `java.lang.IllegalArgumentException`
- The span names do not include the http method type in mpTelemetry-1.1
- `PATCH` is not a supported HTTP method for Jax-Rs 2.0 and therefore we should not test this with MP 1.4 with MicroProfile Telemetry-1.1
- `.followRedirects()` is not a supported before Rest Client 2.0 and therefore we should not test this with MP 1.4 and MP 4.1 with MicroProfile Telemetry-1.1

The behaviour of the agent has slightly changed between the versions too. Although the agent is not supported, the tests we have show: 
- `HTTP.ROUTE` attribute results  differ for the 1.29 version of the agent 
- Version 1.29 of the agent generates two spans for JAX-RS requests while 1.19 generates 1

## Confidence Level

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

**Comment by ayoho** [comment]
LGTM 👍
