### ISSUE TITLE
Investigate and Re-enable SB Uber Jar packaging Liberty Tests.

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/open-liberty#26444]
We have a few tests that go through the SpringBoot packaging scenarios, inlcuding creating an Uber jar including all shared libs, the Spring runtime, and embedded Liberty itself.   There were some issues packaging after the SpringBoot Thinning util moved the shared libs under wlp.lib.extract

The commit to disable the tests is here: https://github.com/OpenLiberty/open-liberty/commit/0154bb5b0d76b840eab3a65bab0e3666d1a2e777

The same tests need to be re-enabled in the new SB3 fat as well...

**Comment by cbridgha** [comment]
Past debugging of issue:  https://github.com/OpenLiberty/open-liberty/issues/14982

**Comment by tjwatson** [comment]
I think the update to commons compress addressed the original issue with the uber JAR manifest not being correct (causing the test to fail).  #15522
