### ISSUE TITLE
rest-intro guide review comments. Only one tiny typo in a great guide. Some trivial feedback added.

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#2644]
Guide is just great and I was able to follow it easily as is - so the below is just nit-picking
input really (and one typo of 'it' to 'is').

- [x] Comment not error: The start repo did not have empty directories in it so my initial "vi src/main/java/io/openliberty/guides/rest/SystemApplication.java" needed to be preceeded with a "mkdir -p src/main/java/io/openliberty/guides/rest/" The use of a placeholder file (as is used in the server.xml) might have made this one step faster.

- [x] The @GET annotation on the method indicates that this method it to be called for the HTTP GET method.
'it' -> 'is'

- [x] 'The desired Content-Type for a JSON response is application/json with MediaType.APPLICATION_JSON instead of the String code'
I think could be
'The desired Content-Type for a JSON response is application/json with MediaType.APPLICATION_JSON instead of the String content type.'

- [x] In "Literal code is better because in the event of a spelling error, a compile failure occurs."
I did not know what the 'Literal code' bit was referring to.

- [x] I was not sure what 'the place holder text' was initially in 'Replace the placeholder text with the following XML code to update the src/main/liberty/config/server.xml file:'
This might be better as 
'Edit the src/main/liberty/config/server.xml file to update the placeholder text to be:' 

http://localhost:9080/LibertyProject/System/properties is was so cool to see this so quickly.
A great guide! It had a great level of REST - knowledge snippets and left me feeling I could go on and hack some more.

**Comment by hutchig** [comment]
@Ahmad-Ayyoub Forgive me for assigning this to you. If this was not the correct thing to do then feel free to assign back to me or forward correctly. I am happy to do a PR too but can't do that this morning (US time) I am afraid.

**Comment by JunyiSun** [comment]
Fixed by https://github.com/OpenLiberty/guide-rest-intro/pull/29, this issue can be closed
