### ISSUE TITLE
Clarify JWT builder metatype and update JWT builder docs

### ISSUE THREAD

**Issue by ayoho** [OpenLiberty/open-liberty#26453]
A recent case brought up some questions that could be addressed in our documentation, namely:
- Clarify the `expiresInSeconds` attribute in `jwtBuilder` defaults to the value of the `expiry` attribute if `expiresInSeconds` is set to a negative value.
- Using the configured keystore/key alias to generate a consistent JWK
    - If customers want keys to be consistent across Liberty servers and/or across server reboots, they can configure the `keyStoreRef` and `keyAlias` attributes to point to a specific keypair. The default JWK endpoint provided by Liberty (`https://<host_name>:<ssl_port>/jwt/ibm/api/<jwtBuilder_configuration_id>/jwk`) will still produce a JWK document but will use the public key pointed to by those configuration attributes to create a JWK representation of the key to send back.
- JWK creation and rotation
    - The keys get recalculated/rotated every 12 hours by default in the case jwkEnabled="true".
    - The keys get generated when creating the token, or when the JWK endpoint is invoked (whichever happens first).
    - The same keys are used for all tokens created by the same JWT builder.
- Clarify `kid` usage

**Comment by dmuelle** [comment]
opened #6964 to track on docs side

**Comment by ayoho** [comment]
Info has been publicly documented here: https://openliberty.io/docs/latest/json-web-token.html. Closing this issue as resolved.
