### ISSUE TITLE
Servlet 6.1: Clarify that Servlet containers are required to support HTTPS.

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#26482]
`https://github.com/jakartaee/servlet/issues/95`

**Comment by pmd1nh** [comment]
This is doc update.

https://github.com/jakartaee/servlet/commit/6727b53e342d72c21d5472ce63bdd8cfdd773dd6

Liberty servlet container has been supported HTTPS scheme.  The actual TLS (i.e HTTPS) functionality (i.e keyStore/credential ...) are actually taken place in channel.

There is no-op for this issue.
