### ISSUE TITLE
Servlet 6.1: Containers may provide an option to send redirects using a location header with a relative URL.

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#26487]
`https://github.com/jakartaee/servlet/issues/275`

**Comment by pmd1nh** [comment]
We added a property to send redirect using a relative URL in 21.0.0.1

Issue
PR: https://github.com/OpenLiberty/open-liberty/pull/12563

Blog:
https://openliberty.io/blog/2021/01/22/jwtbuilder-redirects-21001.html#redirects

No-op for this item.

**Comment by pmd1nh** [comment]
Repeating of the related tests in EE11: (with added change of sendRedirect methods from https://github.com/OpenLiberty/open-liberty/pull/27350)

```
com.ibm.ws.fat.wc.tests.WCSendRedirectRelativeURLDefault 4 1 0 10 s 23
testResponseSendRedirectToRelativeURL_Default 1 0 0 2 s 1
testResponseSendRedirectToRelativeURL_Default_EE9_FEATURES 1 0 0 2 s 2
testResponseSendRedirectToRelativeURL_Default_EE10_FEATURES 1 0 0 2 s 3
testResponseSendRedirectToRelativeURL_Default_EE11_FEATURES 1 1 0 2 s 4

com.ibm.ws.fat.wc.tests.WCSendRedirectRelativeURLTrue 4 0 0 10 s 22
testResponseSendRedirectToRelativeURL_True 1 0 0 2 s 1
testResponseSendRedirectToRelativeURL_True_EE9_FEATURES 1 0 0 2 s 2
testResponseSendRedirectToRelativeURL_True_EE10_FEATURES 1 0 0 2 s 3
testResponseSendRedirectToRelativeURL_True_EE11_FEATURES 1 0 0 2 s 4
```

**Comment by pnicolucci** [comment]
Thanks for verifying we have tests for this already Phu. Closing this issue out as there is no further work to be done.
