### ISSUE TITLE
Servlet 6.1: Clarify Javadoc for MultipartConfigElement and MultipartConfig that sizes are in bytes.

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#26496]
`https://github.com/jakartaee/servlet/issues/463`

**Comment by pmd1nh** [comment]
Mainly adding the words (in bytes) to clarify the size unit.

@param location the directory location where files will be stored
     * @param maxFileSize the maximum size allowed `(in bytes)` for uploaded files
     * @param maxRequestSize the maximum size allowed `(in bytes)` for multipart/form-data requests
     * @param fileSizeThreshold the size threshold `(in bytes)` after which files will be written to disk

Java standard unit is in byte (not bit).

No-ops for this issue.
