### ISSUE TITLE
Servlet 6.1: The Javadoc for HttpServletRequest.isTrailerFieldsReady() has been corrected to correctly describe the default implementation.

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#26499]
`https://github.com/jakartaee/servlet/issues/473`

**Comment by pmd1nh** [comment]
Fix Javadoc

old: `@implSpec The default implementation returns false.`
new: `@implSpec The default implementation returns {@code true}.`

Liberty has actually implemented this API so it does not use the `default returns value`

NO-OPs
