### ISSUE TITLE
Servlet 6.1: Clarify the behaviour of getDateHeader() and getIntHeader() when multiple headers with the same name are present in the HttpServletRequest. The expected behaviour is aligned with getHeader().

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#26490]
`https://github.com/jakartaee/servlet/issues/325`

**Comment by pmd1nh** [comment]
Main clarification sentence for each API:

**public long getDateHeader(String name);**
`If there are multiple headers
      with the same name, this method returns the value of the first header in the request`


**public int getIntHeader(String name);**
`If there are multiple headers with the same name, this method returns the value of the first header in the request.`
