### ISSUE TITLE
Servlet 6.1: Deprecate support for HTTP/2 server push and make implementaing support for this feature optional.

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#26502]
`https://github.com/jakartaee/servlet/issues/538`

**Comment by pmd1nh** [comment]
No-ops item.
Add to todo issue to update the UFO.

**Comment by pnicolucci** [comment]
#27383

**Comment by pnicolucci** [comment]
Mailing list thread: https://www.eclipse.org/lists/servlet-dev/msg00633.html

**Comment by pnicolucci** [comment]
@pmd1nh  latest comment in the Servlet Spec issue: `https://github.com/jakartaee/servlet/issues/538#issuecomment-1997680995` I think we're good to close this one out. Any objection?

**Comment by pmd1nh** [comment]
no-ops
