### ISSUE TITLE
Spring Boot 3.1.x

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/open-liberty#26517]
Many our our existing test projects, and other utilities are not all up to the latest 3.1.x version.   In the past a similar issue was opened to perform the latest upgrade for example 2.6-> 2.7. https://github.com/OpenLiberty/open-liberty/pull/21588

**Comment by tbitonti** [comment]
We delivered 3.2.x support in January - and existing issue (still open) will cover the test requirements (being upgraded)
