### ISSUE TITLE
Can't find resource for bundle com.ibm.ws.install.internal.resources.InstallKernel, key ERROR_IMPROPER_httpPROXY_FORMAT

### ISSUE THREAD

**Issue by chrispenske** [OpenLiberty/open-liberty#26512]
I keep getting an error related to the proxy when I try & use the featureManager command.  I listed my repositories.properties file.  This is definitely the right proxy setting as other tools use these same settings.  I tried the command without the repositories.properties file, but got the same error.  How can I get past this error? 

C:\wlp\bin>featureUtility installServerFeatures iserver
Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."
Initializing ...
Can't find resource for bundle com.ibm.ws.install.internal.resources.InstallKernel, key ERROR_IMPROPER_httpPROXY_FORMAT

**### repositories.properties**
proxyHost=http://proxy.test.com
proxyPort=80

**Comment by jjiwooLim** [comment]
Hi,

I see that the featureUtility cli picked up the following: `JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."`. Is this a property that you added? Has this ever worked before?

Could you please tell us the Liberty image and version you are using? Also, please try running the command again with the `--verbose` flag and upload the log here. 

Thank you

**Comment by jjiwooLim** [comment]
Which Java version are you using?
