### ISSUE TITLE
Feature Test Summary - LG-344: MicroProfile Metrics v5.1

### ISSUE THREAD

**Issue by Channyboy** [OpenLiberty/open-liberty#26520]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

### io.openliberty.microprofile.metrics.5.1.internal_fat_tck 

The `io.openliberty.microprofile.metrics.5.1.internal_fat_tck` runs the MicroProfile Metrics 5.1 TCK test suite.
The TCK was developed/updated along with API and specification changes to the MicroProfile Metrics 5.1 specification.

The changes to the MP Metrics 5.1 specification brings in new MP config values that allow for the configuration of how the _Histogram_ and _Timer_ metric behave in terms of the data it records and reports (in the Prometheus formatted output on the `/metrics` REST endpoint). These configurations include customizing the set of percentiles that both metrics can track and report, 
 and customizing the histogram buckets that both metrics can track and report. The TCK had been updated to include tests that tests the configuration in the `API` and `REST` modules. The former tests that the percentiles and buckets retrieved as configured. The latter testing the output in `/metrics` and verifies it is as expected. For the API tests, there are configurations/tests for a valid configuration, invalid configurations and configurations with both valid and invalid configurations. For the REST test, we test mainly valid configurations and concentrate on the validity/adherence of the expected Prometheus format. There is a mix of injected metrics and programmatically created metrics. Tests also tested against the use of a wild card  (i.e. *) in the configuration, which is supported.
 
 ### io.openliberty.microprofile.metrics.internal.5.x.monitor_fat
 We have created a repeat action to repeat the tests in this FAT to run with `mpMetrics-5.1`.

### io.openliberty.microprofile.metrics.internal.5.1_fat
This FAT bucket includes new tests that test some optional MP Config configurations that were not included in the TCK. These configurations enable default histogram-buckets for the _Timer_ and _Histogram_ metrics as well as setting a max and min value on those buckets. Tests include a valid configurations, invalid configurations and configurations with both valid and invalid values. The test tests that the output on `/metrics` is as expected. Tests also tested against the use of a wild card  (i.e. *) in the configuration, which is supported.

### SmallRye tests
As of MP Metrics 5.0, Open Liberty has been pulling the implementation for metrics from SmallRye which are currently main contributors too. We've also included unit tests on the SmallRye implementation to test the code where it parses and processes the configurations of the required and optional configuration and it's ability to match with metrics with the supported wildcard support. This included valid configurations, invalid configurations as well configurations with both valid and invalid values.
 
### List of FAT projects affected

- io.openliberty.microprofile.metrics.5.1.internal_fat_tck **(new)**
- io.openliberty.microprofile.metrics.internal.5.x.monitor_fat **(repeat tests)**
- io.openliberty.microprofile.metrics.internal.5.1_fat **(new)**

### Test strategy

* What functionality is new or modified by this feature?
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

4

**Comment by ayoho** [comment]
Since this feature is essentially just adding support for some new MP Config options that are processed by the SmallRye implementation brought in by Liberty, I'm satisfied with the coverage of testing here. 👍
