### ISSUE TITLE
Feature Test Summary - Provide new computed metrics for MicroProfile Metrics

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/open-liberty#26536]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

Automated tests were added to the existing FAT project below for MpMetrics-5.0, to ensure all the newly created computed metrics show up when the /metrics and with its corresponding URL parameters (/metrics?scope=vendor) endpoints are hit. The tests include positive tests, when all the required metrics that are needed for computation is available and the new computed metric is calculated and shown properly. The negative tests cases are also included to cover scenarios, where the required metrics are NOT available, hence the new computed metrics should NOT be calculated and created. We also included if the new computed metrics gracefully get unregistered when the respective application or server stops. We also include tests to cover the addition and subtraction of monitoring components of the monitor filter attribute in the server configuration, where it would directly affect if the corresponding computed metrics are calculated and shown or not. In addition, we included test cases when users set the appName via MP Config property, it should be correctly reflected in the new computed metric as well.

### List of FAT projects affected

* io.openliberty.microprofile.metrics.internal.3.x.monitor_fat
* io.openliberty.microprofile.metrics.internal.4.x.monitor_fat
* io.openliberty.microprofile.metrics.internal.5.x.monitor_fat

(The above FAT project is also repeated for the MpMetrics-5.1 feature)

### Test strategy

* What functionality is new or modified by this feature?
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

The following test cases are in the **ComputedMetricsTest** FAT suite, in the above FAT projects :

- **testComputedBaseMetrics()** - Tests if the computed base metrics are present in the "/metrics?scope=vendor" output, when the server starts and verifies that the new computed value is actually a valid Number, and not listed as a NaN.
- **testComputedServletMetrics()** - Tests if the computed servlet metrics are present in the "/metrics?scope=vendor" output, after a servlet is hit and verifies that the new computed value is actually a valid Number, and not listed as a NaN.
- **testComputedConnectionPoolMetrics()** - Tests if the computed Connection Pool metrics are present in the "/metrics?scope=vendor" output, after the corresponding JDBC application is hit and the corresponding data sources are created, and verifies that the new computed value is actually a valid Number, and not listed as a NaN. Also, checks if the corresponding computed Servlet metric is present in the endpoint for the JDBC test application.
- **testComputedRESTMetrics()** - Tests if the computed REST metrics present in the "/metrics?scope=vendor" output, after a REST application is hit and verifies that the new computed value is actually a valid Number, and not listed as a NaN. Also, checks if the corresponding computed Servlet metric is present in the endpoint for the REST test application.
- **testAllComputedMetrics()** - Tests if all the computed metrics are present in "/metrics" output, and verifies that the new computed value is actually a valid Number, and not listed as a NaN.
- **testDynamicStopRESTApplication()** - Tests when dynamically stopping the deployed REST application, the computed REST and corresponding Servlet metrics should NOT be shown.
- **testDynamicNoServletConnectionPoolInMonitorFilter()** - Tests when dynamically removing Connection Pool and WebContainer (Servlet) Monitoring components from the Filter attribute, the "/metrics?scope=vendor" output should not show those metrics.
- **testOnlyServletConnectionPoolInMonitorFilter()** - Tests when only configuring the Connection Pool and WebContainer (Servlet) Monitoring components in the Filter attribute, the "/metrics?scope=vendor" output should show both those metrics.
- **testOnlyServletInMonitorFilter()** - Tests when only WebContainer (Servlet) is configured in the Filter attribute, the "/metrics?scope=vendor" output should show only those metrics, not Connection Pool.
- **testOnlyConnectionPoolInMonitorFilter()** - Tests when only ConnectionPool is configured in the Filter attribute, the "/metrics?scope=vendor" output should show only those metrics, not Servlet.
- **testMPConfigAppNameProperty()** - Tests when the MP Config property "mp.metrics.appName" is set as an ENV variable,  the "/metrics?scope=vendor" output should show all the computed metrics, with the correct tags, including the mp config property value.
- **testMPConfigDefaultAppNameProperty()** - Tests when the MP Config property "mp.metrics.defaultAppName" is set as an ENV variable,  the "/metrics?scope=vendor" output should show all the computed metrics, with the correct tags, including the mp config property value.
- **testDynamicApplicationStopWithMpConfigPropSet()** - Tests when dynamically stopping the deployed REST application, the computed REST and corresponding Servlet metrics should NOT be shown, when the MP Config appName property is set.

In addition, manual testing was also performed to ensure correctness, such as creating dashboards and visualizing the metrics in AWS CloudWatch, to ensure they are calculated properly.

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

Our confidence level for the testing delivered for this feature is 4. We delivered all the automated testing we believe that covers the main path needed for this feature, as well as, the error scenarios. Most of the main testing needed for the MP Metrics features already have existing test coverage via TCKs and Liberty specific Liberty FAT buckets, which cover the basic functionality and error scenarios that may happen with the MpMetrics feature, that this new feature adds onto.

**Comment by ayoho** [comment]
LGTM 👍
