### ISSUE TITLE
Verify signature of id_token_hint in OAuth/OIDC logout

### ISSUE THREAD

**Issue by ayoho** [OpenLiberty/open-liberty#26562]
The https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.openidconnect.server/src/io/openliberty/security/openidconnect/backchannellogout/BackchannelLogoutService.java#L78 code should be updated to verify the signature of the `id_token_hint` request parameter that it receives. At the moment it passes the value as-is to the back-channel logout code. The BCL code verifies the claims within the token, but it does not validate the signature.

The method should be able to handle the case where the `userName` argument is missing and instead rely on the `"sub"` claim in the provided ID token. So the null/empty check on `userName` can be removed and the method refactored accordingly.

**Comment by ayoho** [comment]
For https://github.com/OpenLiberty/open-liberty/issues/18105

**Comment by jimmy1wu** [comment]
fixed in https://github.com/OpenLiberty/open-liberty/pull/27193/commits/59601dbd0118aa43778f548170918ef3c9f53231
