### ISSUE TITLE
Telemetry: Update to the latest versions of OSS before GA

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#26591]
Update to the latest versions of any Open Source software that we consume for MP Telemetry 1.1.

Can be done at any time but should be checked shortly before GA to ensure everything is up to date.

The MP Telemetry spec may define a specific version of the OTel API and SDK, but we should check on the versions of any other OSS we use.

**Comment by Yas-Franco** [comment]
Currently we have: 

- com.squareup.okhttp3:okhttp:4.12.0 (Latest)
- com.squareup.okio:okio-jvm:3.6.0 (Latest)
- io.zipkin.reporter2:zipkin-reporter:2.16.4 (Latest)
- io.zipkin.reporter2:zipkin-sender-okhttp3:2.16.4 (Latest)
- io.zipkin.zipkin2:zipkin:2.23.3 (Latest)

All are up to date.
