### ISSUE TITLE
Jakarta Bean Validation feature rename

### ISSUE THREAD

**Issue by mswatosh** [OpenLiberty/open-liberty#26604]
## Background
The Jakarta Bean Validation spec group has decided to go ahead with renaming the project from Jakarta Bean Validation to Jakarta Validation.

Liberty Bean Validation features use the naming scheme `beanValidation-x.y`

Changing the `symbolicName` would break the `ibm.tolerates` mechanism e.g.
`io.openliberty.beanValidation-3.0; ibm.tolerates:="3.1"`

## Proposed Solutions

1. Use `validation-3.1` for the upcoming Jakarta Validation feature.  Keep the symbolic name `io.openliberty.beanValidation-3.1` to allow `ibm.tolerates`. We can use `WLP-AlsoKnownAs: beanValidation-3.1` to notify users who try to use `beanValidation-3.1`. This would be the first time we had a feature with an `IBM-ShortName` which didn't match the `symbolicName`.  
2. Maintain the current naming system, so the upcoming feature would be `beanValidation-3.1`.
3. Create `validation-3.0` which supersedes `beanValidation-3.0` and update `beanValidation-3.0` to include `validation-3.0`.  `validation-3.1` feature would have `WLP-AlsoKnownAs: beanValidation-3.1` in it.  Customers would use io.openliberty.validation-3.0; ibm.tolerates:="3.1" going forward.

**Comment by mswatosh** [comment]
~Decided on option 3, with a new no-design Epic to deliver this prior to EE11~
See below comment on switching to Option 1

**Comment by mbroz2** [comment]
Option 3 gets my vote as well, as one of the [use-cases for supersedes](https://github.ibm.com/websphere/WS-CD-Open/wiki/Stabilized,-Superseded,-and-Discontinued-Features-and-Capabilities#superseded-features-and-capabilities) is for feature renames (with precedence via mdb)

**Comment by mswatosh** [comment]
After discussing with Alasdair, we've decided to switch to Option 1.
