### ISSUE TITLE
JAX-WS: @WebFault annotated Exceptions are not properly serialized as SOAPFaults on 22.0.0.8 and above.

### ISSUE THREAD

**Issue by neuwerk** [OpenLiberty/open-liberty#26636]
**Describe the bug**  

In 22.0.0.8 and above, Custom Exceptions annotated with `@WebFault` aren't properly marshalled when the exception does not override the `java.lang.Throwable.getMessage()` method. The result is an incorrect SOAP Message. Here's an example:

```
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <soap:Fault>
      <faultcode>soap:Server</faultcode>
      <faultstring>Expected all unequal numbers.</faultstring>
      <detail>
        <ns1:EqualNumbersException xmlns:ns1="http://provider.jaxws.ws.ibm.com/">
          <info xmlns:ns2="http://provider.jaxws.ws.ibm.com/">Numbers can't be equal</info>
        </ns1:EqualNumbersException>
      </detail>
    </soap:Fault>
  </soap:Body>
</soap:Envelope>

```

Prior to 22.0.0.8, the same exception generates this SOAP Fault: 

```
 <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <soap:Fault>
      <faultcode>soap:Server</faultcode>
      <faultstring>Expected all unequal numbers.</faultstring>
      <detail>
        <ns1:EqualNumbersException xmlns:ns1="http://provider.jaxws.ws.ibm.com/">
          <info xmlns:ns2="http://provider.jaxws.ws.ibm.com/">Numbers can't be equal</info>
          <message xmlns:ns2="http://provider.jaxws.ws.ibm.com/">Expected all unequal numbers.</message>
        </ns1:EqualNumbersException>
      </detail>
    </soap:Fault>
  </soap:Body>
</soap:Envelope>
```

By not marshalling the value of `Throwable.getMessage()` the JAX-WS features on Liberty are violating the JAX-WS Specification. Section 3.7 of the JAX-WS 2.2 spec that states states: 

> 
>     For each getter in the exception and its superclasses, a property of the same type and name is added
>     to the bean. The getCause, getLocalizedMessage and getStackTrace getters from 
>     java.lang.Throwable and the getClass getter from java.lang.Object are excluded from the list
>     of getters to be mapped

**Steps to Reproduce**  

Declare an Exception data type like the following:

```
@WebFault()
public class EqualNumbersException extends Exception {

    private static final long serialVersionUID = -2844570262814091172L;

    private String info;

    public EqualNumbersException() {

    }

    public EqualNumbersException(String message, String info) {
        super(message);
        this.info = info;
    }

    public String getInfo() {
        return info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

}
```

Throw an exception like this and the returned SOAP Fault will not be marshaled correctly on 22.0.0.8 and above. 

**Expected behavior**  
If the custom exception is throw, then the marshaled SOAP Fault should still contain the message element like the following: 

```
 <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <soap:Fault>
      <faultcode>soap:Server</faultcode>
      <faultstring>Expected all unequal numbers.</faultstring>
      <detail>
        <ns1:EqualNumbersException xmlns:ns1="http://provider.jaxws.ws.ibm.com/">
          <info xmlns:ns2="http://provider.jaxws.ws.ibm.com/">Numbers can't be equal</info>
          <message xmlns:ns2="http://provider.jaxws.ws.ibm.com/">Expected all unequal numbers.</message>
        </ns1:EqualNumbersException>
      </detail>
    </soap:Fault>
  </soap:Body>
</soap:Envelope>
```
**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.8 and above
 - Affected feature(s): jaxws-2.2
 - Java Version: Any

**Additional context**  
This violation of the JAX-WS spec, was introduced by a change in Liberty's JAX-WS implementation: Apache CXF. This JIRA  ticket, [CXF-4594](https://issues.apache.org/jira/browse/CXF-4594), introduced the breaking change.

**Comment by neuwerk** [comment]
#26600 address this issue.

**Comment by neuwerk** [comment]
Closing, as the fix was merged last week.

**Comment by covener** [comment]
> Closing, as the fix was merged last week.

@neuwerk promise breaker!  Please close.

**Comment by neuwerk** [comment]
Oooof, @covener I hit comment instead of close with comment.
