### ISSUE TITLE
JAX-RS 3.0 does not support sslConfig from webTarget

### ISSUE THREAD

**Issue by jonasrutishauser** [OpenLiberty/open-liberty#26649]
**Describe the bug**  
With the JAX-RS 3.0 client feature it is no longer possible to configure a `sslConfig` in the webTarget (https://openliberty.io/docs/latest/reference/config/webTarget.html).

**Steps to Reproduce**  
- Configure a `webTarget` with a sslConfig in the `server.xml`
  ```xml
  <webTarget sslConfig="otherSslSettings" uri="https://some.host/*"/>
  <ssl id="otherSslSettings" keyStoreRef="defaultKeyStore" trustStoreRef="otherTrustStore"/>
  <keyStore id="otherTrustStore" location="otherCaCerts" type="JKS" password="changeIt"/>
  ```
- Use a JAX-RS client with default configuration and call some endpoint on this host which requires a CA cert not in the default trust store
- An exception will be thrown which shows that the default trust store is used

**Expected behavior**  
Expected is that this works as with the javax version (< 3.0).

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.7
 - Affected feature(s): restfulWSClient-3.0
 - Java Version: doesn't matter but is 17
 - server.xml configuration (WITHOUT sensitive information like passwords): see in steps to reproduce

**Additional context**  
It does not help that the property of the `webTarget` is correctly mapped here https://github.com/OpenLiberty/open-liberty/pull/16290/files#diff-898e0e06fe0ec1cd06956e126d099e2fe596dc2d981b294d95f9270c2f36665fR59
The reason that it is not working is the following limitation of the implementation from https://github.com/OpenLiberty/open-liberty/issues/13476#issue-678114366
> One change between this 3.0 implementation and the 2.X implementations is that the property must be specified on the `ClientBuilder` - in 2.X, it was possible to specify this property on the `Client` or the `WebTarget`. While the option to specify the property on the `Client` or `WebTarget` is more flexible, it does not perform as well as it requires a filter to intercept the outbound request, check for the property and then apply the SSL settings. By setting it _only_ at the `ClientBuilder`, the builder can apply the SSLContext immediately and not need to do additional processing for each request.

**Comment by WhiteCat22** [comment]
Hi @jonasrutishauser 

As you've already found, we made the intentional decision to not support this in `restfulWS-3.0` and future `restfulWS` features. We do not plan to re-add this functionality as it would degrade request performance.

**Comment by jonasrutishauser** [comment]
In this case, there are the following questions to answer:
- Why is the `server.xml` property mapped when it is not supported?
- Why is in the documentation mentioned that this should work (see  https://openliberty.io/docs/latest/reference/feature/restfulWSClient-3.0.html#_modify_ssl_configuration_in_development)
- What will be the way to configure this as the [`outboundConnection`](https://openliberty.io/docs/latest/reference/config/ssl.html#outboundConnection) is not working either?

**Comment by jonasrutishauser** [comment]
@WhiteCat22 Can you answer the questions?
