### ISSUE TITLE
Kafka message acknowledgement is slow if messages are fed to a subscriber method

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#26692]
**Describe the bug**  
- A simple subscriber method with post-process acknowledgements will wait for an `ack()` to complete before accepting another message.
- The liberty kafka connector buffers acknowledgements to improve throughput.

These two behaviours mean that if messages from the kafka connector are routed to a simple subscriber method, either there's a delay between each message while the kafka connector waits to see if there are more messages to add to the batch, or the whole stream stalls because no more messages are requested, the kafka connector does not poll and the commit required to complete the `ack()` never occurs.

**Steps to Reproduce**  

Connect an incoming kafka channel to a method like this:

```java
@Incoming("myChannel")
public void myMethod(String data) {
}
```

**Expected behavior**  

Messages should be acknowledged quickly.

**Diagnostic information:**  
 - OpenLiberty Version: latest integration
 - Affected feature(s): `mpReactiveMessaging-1.0`

**Additional context**  

I raised a question about this behaviour previously in eclipse/microprofile-reactive-messaging#38. Despite the closed issue, I'm not sure what the resolution was supposed to be.

With the current behaviour, either:
- Connectors can't batch up acknowledgements
- Connectors have to lie and say that acknowledgement has been done when it hasn't

It doesn't look like smallrye reactive messaging has any option to change this behaviour.

This is a configuration which is demonstrated in the liberty reactive guide.

**Comment by Azquelt** [comment]
Opened #26691 with a test which demonstrates the issue. It passes slowly on RM 1.0 and fails on RM 3.0.

**Comment by Azquelt** [comment]
There's a further problem with the current approach:
- The RM container will [fail the stream if the message ack fails](https://github.com/smallrye/smallrye-reactive-messaging/blob/e59e7cff9962c0cdf4a7f6de859add786a2a6a23/smallrye-reactive-messaging-provider/src/main/java/io/smallrye/reactive/messaging/providers/SubscriberMediator.java#L197)
- It's quite possible for the Kafka container to fail to commit offsets for a partition if the partitions were rebalanced and the consumer no longer owns that partition.

Given this, propagating the failure to commit a partition offset back to the ack caller is not what we want to do, unless the user is doing their own acknowledgements and is expecting this behaviour.

I would suggest adding a new config option for the connector to complete acks immediately. We can default to `false` for RM 1.0 to keep the existing behaviour in case anyone is relying on it and default to `true` for RM 3.0.

**Comment by Azquelt** [comment]
We've added a new experimental option named `fast.ack`, but it's not documented yet and the name isn't final, so we can't consider this issue "fixed" yet.

**Comment by abutch3r** [comment]
Design has been approved with this name and will be included as part of the new connector documentation.
