### ISSUE TITLE
Investigate MP JWT TCK forked code

### ISSUE THREAD

**Issue by ayoho** [OpenLiberty/open-liberty#26827]
It looks like the [com.ibm.ws.security.mp.jwt_fat_tck](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.security.mp.jwt_fat_tck) bucket had the official MP JWT TCK code (https://github.com/eclipse/microprofile-jwt-auth/tree/main/tck/src/test) copied into it when the FAT was initially delivered. I suspect that means we're running with our own (unmaintained) fork of the official MP JWT TCK code. We should look at fixing that to be in line with other TCK buckets that define dependencies on the TCK test jars instead of having a copy of the code.

**Comment by c00crane** [comment]
Updates have been delivered
