### ISSUE TITLE
Server should be able to reclaim its recovery logs on startup

### ISSUE THREAD

**Issue by jonhawkes** [OpenLiberty/open-liberty#26832]
A restarting server should be able to reclaim its transaction recovery logs on startup even if they are being recovered by another member of its recovery group.

This is particularly important if the recovery group is deployed as a StatefulSet.

**Comment by ibmfjk** [comment]
@neilgsyoung  can you also deliver an ifix for liberty 23.0.0_09 ?

**Comment by torstenwilms** [comment]
Opened on request TS014711230 for backport to 23.0.0_09

**Comment by torstenwilms** [comment]
@neilgsyoung I opened on request TS014711230 for backport to 23.0.0_09 . If you need  more description in the Case, please let me know.

**Comment by ibmfjk** [comment]
@neilgsyoung May I know if the fix of #26843 will be included in 2023.12 or not?

**Comment by neilgsyoung** [comment]
Hi @ibmfjk - it turned out to be a significant piece of work. We took it through its final code review yesterday, it was approved and I have now merged the changes in PR #26843. I'm hoping that it should be in 24.0.0.1.
