### ISSUE TITLE
Servlet 6.1. : Clean up review for WLP-Server* in the bnd.bnd

### ISSUE THREAD

**Issue by pmd1nh** [OpenLiberty/open-liberty#26859]
Review and verify if these two WLP-Server* directives, in the bnd.bnd, can be removed in all of WebComponent bundles.

`WLP-ServerName: IBM WebSphere Application Server`

`WLP-ServerVersion: ${liberty.beta.version}`

see https://github.com/OpenLiberty/open-liberty/pull/26815/files/041c59bc13f5ff9fda15a7e30d5e0a37b48240a5#diff-cd5a5048af015cb90ab1adc2103c7fa7786c5b17d419311ba0235bf0584188a3

**Comment by pmd1nh** [comment]
Checked with Jared.  These 2 WLP-Server* can be removed.

**Comment by pmd1nh** [comment]
These 2 directives 

```
WLP-ServerName: IBM WebSphere Application Server
WLP-ServerVersion: ${liberty.beta.version}
```

need to stay in the base com.ibm.ws.webcontainer bnd.bnd since they are used from

https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/WebContainer.java#L1516

In the trace, this information shows up as:

`[2/7/24, 22:31:59:150 EST] 00000040 WebContainer  1   serverInfo -->IBM WebSphere Liberty/24.0.0.2`

Verified that these 2 are not presented in other `*.webcontainer.*` projects. 

JSP clean this up in https://github.com/OpenLiberty/open-liberty/issues/26903.

Issue can be closed.

**Comment by pnicolucci** [comment]
Looks good thanks @pmd1nh
