### ISSUE TITLE
MP Config 1.3: The AppPropertiesConfigSource is not properly dynamic

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#2687]
Anything change at runtime inside the `<application>` element will result in the application being restarted. Therefore, since the config will be re-read when the app restarts, it isn't properly dynamic.

Discussion ongoing how to fix but current best plan is to have special case code in the app manager to prevent the restart.

**Comment by tjwatson** [comment]
I think the application manager can have knowledge of the app properties to at least fill in the ApplicationInformation (com.ibm.wsspi.application.handler.ApplicationInformation<T>) with the app properties.  Perhaps have a method Map<String, String> getApplicationProperties.  But what else is needed is a callback to the ApplicationHandler when application properties change.  And the handler should return status indicating if the application must be restarted when the application properties change.

**Comment by Azquelt** [comment]
This is the only development work item left on the MP Config 1.3 Epic.

What was the conclusion on this item? Has it been fixed or is it still outstanding work that needs completed?

**Comment by neilgsyoung** [comment]
Hi @Azquelt - yes, this work is complete. I shall close the issue.
