### ISSUE TITLE
Remove WLP- entries from JSP Bundles

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#26903]
Are these WLP- entries necessary? I only see them in OL in some of the Pages/Faces/WebContainer/Session bnd.bnd files. Perhaps we can get an issue opened to investigate / remove if possible?

_Originally posted by @pnicolucci in https://github.com/OpenLiberty/open-liberty/pull/26346#discussion_r1382032386_
            
            
Remove the following ([example](https://github.com/OpenLiberty/open-liberty/blob/69c6eb9ad3f628762a5580808f95171e721c9685/dev/com.ibm.ws.jsf.jsp.shared/bnd.bnd#L19-L20))
```
WLP-ServerName: IBM WebSphere Application Server
WLP-ServerVersion: ${liberty.beta.version}
```

From the JSP bundles (Not all of them may contain the WLP entries) : 

- [x] com.ibm.websphere.appserver.spi.jsp
- [x] com.ibm.websphere.javaee.jsp.2.2
- [x] com.ibm.websphere.javaee.jsp.2.3
- [x] com.ibm.websphere.javaee.jsp.tld.2.2
- [ ] com.ibm.ws.jsf.jsp.shared
- [ ] com.ibm.ws.jsp
- [ ] com.ibm.ws.jsp.2.3
- [ ] com.ibm.ws.jsp.2.3_fat
- [ ] com.ibm.ws.jsp.factories
- [ ] com.ibm.ws.jsp.jasper
- [ ] com.ibm.ws.jsp.jstl.facade
- [x] io.openliberty.jakarta.servlet.jsp.jstl.2.0.internal
- [ ] io.openliberty.jakarta.servlet.jsp.tags.3.0.internal
- [ ] [io.openliberty.pages.3.1.internal.factories](https://github.com/OpenLiberty/open-liberty/tree/69c6eb9ad3f628762a5580808f95171e721c9685/dev/io.openliberty.pages.3.1.internal.factories)
- [ ] io.openliberty.jakarta.pages.3.0
- [ ] io.openliberty.jakarta.pages.tld.3.0
- [ ] io.openliberty.jakarta.pages.tld.3.1
- [x] io.openliberty.pages.3.1.internal.factories

Note: We do need to keep these in the com.ibm.ws.webcontainer base bundle as they are used here: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/WebContainer.java#L1502 (getServerInfoFromBundle()) which is then used for the ServletContext.getServerInfo for example: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.webcontainer.servlet.3.1/src/com/ibm/ws/webcontainer31/osgi/webapp/WebApp31.java#L466

**Comment by volosied** [comment]
Could also do webcontainer bundles too: 

https://github.com/search?q=repo%3AOpenLiberty%2Fopen-liberty%20%20WLP-ServerName&type=code

**Comment by chungngoops** [comment]
I'm working on this issue.

**Comment by volosied** [comment]
Thanks! Feel free to reach if you have any questions.
