### ISSUE TITLE
MP Telemetry 1.0 does not include query parameters in http.target attribute

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#26905]
`http.target` should include query parameters but since `TelemetryServletFilter` was added, it does not.

**Comment by jakub-pomykala** [comment]
We implemented the`testRouteWithSubResourceWithQueryParam` in `JaxRsRouteServlet` class where we wanted to test the `HTTP_TARGET` with the following:

```
.withAttribute(SemanticAttributes.HTTP_TARGET, getPath() + "/getSubResourceWithQueryParam/details?id=myIdForTesting"));
```

Currently the line is commented out.
