### ISSUE TITLE
Servlet 6.1: Check new Servlet 6.1 schema and see if there are any changes that are necessary

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#26902]
Background: Some initial changes were delivered: https://github.com/OpenLiberty/open-liberty/pull/26815 

1) Verify where the below is used and ensure additional changes are not necessary with the change to 61: 
`Service-Component: \
  com.ibm.ws.webcontainer.v61.dd; \
    implementation:=com.ibm.ws.javaee.version.ServletVersion; \
    provide:=com.ibm.ws.javaee.version.ServletVersion; \
    properties:="version:Integer=61", \`

2) Verify changes in `dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/container/config/WebAppConfiguratorHelper.java` are correct. If no new schema what should it be updated for Servlet 6.1?

3) Are there any additional changes necessary for a new 6.1 schema? Is there a new schema?

**Comment by pmd1nh** [comment]
Check back periodically for any new related schemas

https://jakarta.ee/xml/ns/jakartaee/#11

**Comment by pnicolucci** [comment]
@pmd1nh the new schemas are now available

**Comment by pmd1nh** [comment]
see https://github.com/OpenLiberty/open-liberty/issues/26964
