### ISSUE TITLE
Update tests for newer version of Telemetry Agent

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#26919]
Currently we're testing Telemetry Agent 1.19 with all versions of the mpTelemetry feature in `AgentTest`.

However, this means:
* We're not testing with the agent version which matches mpTelemetry-1.1
* None of the agent tests run on Java 21 which means they don't run in the personal or continuous builds so we don't find out if anything is broken until it hits the release branch and runs in the SOE or a build which uses a specific Java version.

**Comment by Azquelt** [comment]
Had a quick look at this. While repeating with the v1.29 agent is easy, it generates two spans for JAX-RS requests so all the test expectations need updating.

**Comment by jakub-pomykala** [comment]
We are experiencing an issue when withSpan annotation is used with Java EE7 and Java EE8 using Javaagent 1.29.

With Javaagent 1.19 up to 1.24:
- Javaagent creates 1 Jax-rs SERVER span.

With Javaagent 1.25 up to/ and 1.29 with NOT Java EE 7 or Java EE 8: 
- Javaagent creates 2 Jax-rs spans: 
-  1. Expected SERVER span
-  2. an extra INTERNAL span for the Jax-rs method

With Javaagent 1.25 up to/ and 1.29 with Java EE 7 or Java EE 8: 
- Javaagent ony creates 2 Jax-rs span: 
-  1. Expected SERVER span
-  2. an extra INTERNAL span for the Jax-rs method


With Javaagent 1.19 up to 1.24 annotated with withSpan:
- Javaagent creates 1 INTERNAL span.

With Javaagent 1.25 up to/ and 1.29 with NOT Java EE 7 or Java EE 8 annotated with withSpan:
- Javaagent creates 1 INTERNAL span.

With Javaagent 1.25 up to/ and 1.29 with Java EE 7 or Java EE 8 annotated with withSpan: 
- Javaagent creates no spans.

Whilst comparing versions 1.24 and 1.25 I found [this](https://github.com/open-telemetry/opentelemetry-java-instrumentation/commit/07335c807c6a0fd5a8898ded0fba87bde95db3e9) change in the javaagent which made changes to the WithSpanInstrumentation classes.

The change for the extra span to be created happened in the 1.24 release of javaagent. There has been a fix implemented to the [jax-rs annotation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/commit/64eb58633f4d12a1bc5da6a17d93c39f504de631). This fix is for [Missing jaxrs span in Open Liberty](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7870)

**Comment by jakub-pomykala** [comment]
Created an app that uses javaagent 1.29, Java EE 8 and MicoProfile 4.1 to check if this error will occur like in the tests if MPTelemetry is not enabled/installed. 

I created a simple application with the following two methods:

```
    @GET
    @Path("/withspannonbean")
    public String callNonBeanWithSpan() throws Exception {
        Method m = RestApplication.class.getDeclaredMethod("withSpanNonBeanMethod");
        System.out.println("ANNOTATIONS callNonBeanWithSpan: " + Arrays.asList(m.getAnnotations()));
        Span span = Span.current();
        withSpanNonBeanMethod();
        return span.getSpanContext().getTraceId();
    }

```

And 

```
    @WithSpan()
    public static String withSpanNonBeanMethod() {
        return Span.current().getSpanContext().getSpanId();
    }

```

Also used the following `jvm` options:

```
-javaagent:/path/to/opentelemetry-javaagent.jar
-Dotel.javaagent.debug=true
-Dotel.sdk.disabled=false
-Dotel.traces.exporter=logging
-Dotel.metrics.exporter=none
-Dotel.logs.exporter=none

```

The expected output for this scenario was:
- Javaagent creates no spans for `withSpanNonBeanMethod()`

The actual output was:
- Javaagent created a span for `withSpanNonBeanMethod()` which can be seen in the `message.logs` from `otel.javaagent.debug`

**Comment by jakub-pomykala** [comment]
Issue opened [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10159)
