### ISSUE TITLE
Add InstantonTest for mpOpenAPI endpoint configuration

### ISSUE THREAD

**Issue by abutch3r** [OpenLiberty/open-liberty#26966]
With the ability to set the endpoints on mpOpenAPI UI and Document endpoints dynamically, we need to test that this works in InstantOn scenarios.

The scenario we expect to see is that when the image is built the values for the endpoints will be the default or need to change in a container environment like k8s.

server.xml snippet:
```
  <featureManager>
    <feature>mpOpenAPI-3.1</feature>
  </featureManager>

<mpOpenApi docPath="/docs/openapi" uiPath="/docs" />
```

Our primary postivie test class for endpoint configuration:
https://github.com/OpenLiberty/open-liberty/blob/0cf80ac6cae2168982de954bf64fd3ea38846591/dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/config/OpenAPIConfigTest.java#L327

This includes a backbone of asserting against requests to the available endpoints

The test should package a simple REST app that will generate an OpenAPI document that can be shown in the UI. example: https://github.com/OpenLiberty/open-liberty/blob/d40a8c3fff555e9eeecbd65cc0692ba86ff5ec71/dev/com.ibm.ws.microprofile.openapi_fat/fat/src/com/ibm/ws/microprofile/openapi/fat/config/OpenAPIConfigTestResource.java

Steps for the test.
- Build an image without setting the paths in the images server.xml
- Deploy the image with an updated server.xml which changes both paths to the non-default values of `/openapi` and `/openapi/ui`
- check the logs for messages that show endpoints are available at the expected endpoints
- Invoke the endpoints to make sure we get a positive response back with some expected values in its contents

**Comment by tjwatson** [comment]
For the InstantOn test the configuration URL for checkpoint should probably be parameterized like the following such that we can mimic environment configuration of k8s with a `server.env` file on restore that sets the environment vars `OPEN_API_DOC_PATH` and `OPEN_API_UI_PATH` variables to the values for restore.

```xml
  <featureManager>
    <feature>mpOpenAPI-3.1</feature>
  </featureManager>

  <variable name="open_api_doc_path" defaultValue="/docs/openapi" />
  <variable name="open_api_ui_path" defaultValue="/docs" />
  <mpOpenApi docPath="${open_api_doc_path}" uiPath="${open_api_ui_path}" />
```

Then on restore we verify the endpoints are at the expected locations according to the environment on restore.

@anjumfatima90 could you take a look at adding this test?
