### ISSUE TITLE
Question : how to add key files for SSL config

### ISSUE THREAD

**Issue by borgogelli** [OpenLiberty/open-liberty#26978]
Hi guys
I would like to configure the SSL connection on the port 9443. 
Is there any easy configuration step to link the private and public key ?
In Apache I just use
```
             SSLCertificateFile "/etc/ssl/ssl.crt/iubar_it.crt"
             SSLCertificateKeyFile "/etc/ssl/ssl.key/iubar_it.key"
```
Do I have to use a PKCS#12 keystore ? How can I import both keys from files?

**Comment by borgogelli** [comment]
I can merge both files with : 
`openssl pkcs12 -in a.crt -inkey a.key -export -out cert.p12`

And then should I overwrite the p12 file with the following command ? 
`cp cert.p12 ./wlp/usr/servers/myserver/resources/security/key.p12`

**Comment by borgogelli** [comment]
Ok it works

**Comment by una-tapa** [comment]
@borgogelli  Apologies for the delay!  I was assigned to work with you on this issue, then got mixed up with another issue. 
Now I see your post above. Did you get it working?  If so, may I close this issue?  Also kindly share the solutions with us if you remember.  Thank you.

**Comment by una-tapa** [comment]
@borgogelli - We are closing this case.  Please reopen as needed.  Thanks for the report!
