### ISSUE TITLE
Feature Test Summary for Podman support in Liberty Maven/Gradle plugins

### ISSUE THREAD

**Issue by cherylking** [OpenLiberty/open-liberty#27063]
## Test Strategy

The Liberty Maven/Gradle plugins provide dev mode for containers, which up until now only supported running with Docker. The [1278](https://github.com/OpenLiberty/ci.maven/issues/1278#top) epic added support to run with Podman instead. The design of this feature looks for and uses Docker if it is installed. If Docker is not found, then the plugins will look for Podman and use it if it is a valid version. The tests are not currently automated because GHA does not support installing the version of Podman needed (4.4 or later). I have issue [1764](https://github.com/OpenLiberty/ci.maven/issues/1764) open to address this at a future date. In the meantime, we ran multiple manual tests (documented below) before delivering the feature. We also had a SVT cycle that tested the feature (and some defects were opened and resolved subsequently).

### List of FAT projects affected

* N/A

### Test strategy

* What functionality is new or modified by this feature?
** If Docker is not installed (or version is not valid), `dev mode for containers` will look for and use Podman instead if a valid version found.
* What are the positive and negative tests for that functionality? 
** Positive test scenarios:
-  Run devc goal/task successfully on Windows when Podman 4.4 is installed and Docker is not installed.
-  Run devc goal/task successfully on Linux when Podman 4.4 is installed and Docker is not installed.
-  Run devc goal/task successfully on Mac when Podman 4.4 is installed and Docker is not installed.

** Negative test scenarios:
-  Run devc goal/task when a Podman version < 4.4 is installed and Docker is not installed. Get error stating that the version of Podman is less than the minimum required version.
-  Run devc goal/task when Podman and Docker is not installed. Get error stating that no valid installation of Docker or Podman was found.

* What manual tests are there (if any)? The test scenarios described above were done as manual tests given the restriction of being able to install the necessary version of Podman in GHA.

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

How do we answer this when the only option given is a `0` based on the fact that we could not deliver any automated tests??? Our confidence in the manual testing that our team did, in combination with a SVT cycle of testing, is a `5`. We tested all positive and negative scenarios that are reasonable to predict a user would do.

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by dave-waddling** [comment]
Hi @cherylking, many thanks for filling out this FTS.

You're actually the second person in as many days to point out that the phrasing of the confidence question only relates to newly delivered automated testing. I'll have a chat with @ayoho as perhaps it would be more correct to ask for a confidence in new automated testing and, if not applicable, confidence in the manual testing that's been performed (as you have indeed done in your answer). 

I'm happy with approving this feature, particularly as there is a follow on issue for introducing automated testing when possible.
