### ISSUE TITLE
Feature Test Summary for Liberty z/OS support for Java 17

### ISSUE THREAD

**Issue by follis** [OpenLiberty/open-liberty#27074]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

There is no new product code for this feature, we're just trying to get existing Liberty tests to run with Java 17 on z/OS.  We did have to make a few java9.options updates and some changes to tests to get them to run.  But no new tests or new function in the product.   

A decision was made by Preston/Alasdair/Dave F. that as of 23.0.0.12 the test state was good enough to declare support.  So we're trying to close out this feature.  This is GHE feature 27479.

### List of FAT projects affected

* 

### Test strategy

* What functionality is new or modified by this feature?

No new function, just running under Java 17

* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)

We ran the existing Liberty tests

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

None

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

The goal was to have existing tests run.  No new tests were needed.

**Comment by dave-waddling** [comment]
Hi @follis, this FTS is a bit of a blast from the past! Now that we have Java 17 on z/OS into the SOE and it's running acceptably I'm happy to approve this feature. The test coverage makes sense, we're using our existing test corpus so I understand your confidence of 0 for the testing delivered (though most developers include existing automated testing in their assessment). Hopefully, we can continue to work our way through the test bugs going forward.
