### ISSUE TITLE
Design issue : Update in the webservices-bnd config after the checkpoint causes the application to restart.

### ISSUE THREAD

**Issue by anjumfatima90** [OpenLiberty/open-liberty#27089]
For epic #26840

**Issue:**

Updating the webservices-bnd config like ${TEST_HOST} variable in the below server.xml after the checkpoint is causing the application to restart.

server.xml

```
<webApplication id="" name="example" cotext-root="example" location="example.war">
                <webservices-bnd>
                        <service-ref name="services/ExampleImplService"
                                port-address="https://${TEST_HOST}:${bvt.prop.HTTP_default.secure}/example/ExampleImplService"
                                wsdl-location="https://${TEST_HOST}:${bvt.prop.HTTP_default.secure}/example/ExampleImplService?wsdl" />
                </webservices-bnd>
</webApplication>
```

logs

```
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://li-94c530cc-22ff-11b2-a85c-ed692b56e945.austin.ibm.com:8010/example/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://li-94c530cc-22ff-11b2-a85c-ed692b56e945.austin.ibm.com:8010/example/
[AUDIT   ] CWWKC0452I: The Liberty server process resumed operation from a checkpoint in 0.266 seconds.
[AUDIT   ] CWWKZ0009I: The application example has stopped successfully.
[AUDIT   ] CWWKG0017I: The server configuration was successfully updated in 0.175 seconds.
[AUDIT   ] CWWKZ0001I: Application example started in 0.268 seconds.
[AUDIT   ] CWWKF0012I: The server installed the following features: [appSecurity-2.0, componenttest-1.0, distributedMap-1.0, jaxb-2.2, jaxws-2.2, jndi-1.0, servlet-4.0, ssl-1.0, timedexit-1.0, wsSecurity-1.1].
[AUDIT   ] CWWKF0011I: The ExampleTestServer server is ready to run a smarter planet. The ExampleTestServer server started in 0.337 seconds.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://li-94c530cc-22ff-11b2-a85c-ed692b56e945.austin.ibm.com:8010/example/
[AUDIT   ] CWWKZ0003I: The application example updated in 0.232 seconds.
```

**Current scenario:**

- Updating the webservices-bnd config while the server is running (regular scenario and not checkpoint/restore) would cause the application to restart.

- webservices-bnd config is used to customize the web services endpoints for server provider and client within the application. It is a child config under the super type config `webApplication`

- Whenever `webservices-bnd` config is updated it fires a configuration update event for the super type config `webApplication` which causes the app manager to perform a state change operation that stops the application and performs a restart of the application.

**Suggested Solution:**

1. Keep as is, that is, restart the application on restore whenever there is a `webservices-bnd` config change.

2. Enhance the `webApplication` to allow its child elements to set a property as an indication to not restart the application. Although restarting the application on config change could be the default behavior.
 `com.ibm.ws.app.manager.internal.ApplicationConfigurator.updated(String, Dictionary<String, ?>)`
 
 The child element component would need to dynamically detect the updated config.

3. Disassociate the child element `webservices-bnd` with the super element `webApplication`.

**More info on webservices-bnd element:**

**Element hierarchy of webservices-bnd**
```
<webservices-bnd>
   - <webservice-endpoint-properties>
   - <webservice-endpoint>
      - <properties>
   - <http-publishing>
   - <webservice-security>
   - <service-ref>
      - <properties>
      - <port>
         - <properties>
```
**Attributes of above elements**

**webservice-endpoint-properties:** `enableLoggingInOutInterceptor`
**webservice-endpoint:** `port-component-name and address`
**http-publishing:** `context-root`
**webservice-security:** `security-constraint. security-role and login-config`
**service-ref:** `name, component-name, port-address and wsdl-location`
**port:** `name, namespace, address, username, password, ssl-ref, key-alias`

Reference: https://www.ibm.com/docs/en/was-liberty/base?topic=liberty-ws-bndxml-file

**Comment by neuwerk** [comment]
Potentially a 4th option could be to leverage the Web Services configuration, that's currently being worked on, to add configuration to support what's configurable in `webservices-bnd`. That could allow a user to move their existing `webservices-bnd` configuration to work with checkpoint restore.

**Comment by tjwatson** [comment]
> Potentially a 4th option could be to leverage the Web Services configuration, that's currently being worked on, to add configuration to support what's configurable in `webservices-bnd`. That could allow a user to move their existing `webservices-bnd` configuration to work with checkpoint restore.

My preference is to go with option 1 for an initial release of InstantOn support for XML Web Services and then bring in this option 4 later as time permits and we have experience that this is needed.

**Comment by cbridgha** [comment]
How is this different from changes to any of the other` <webApplication> `child elements (`<web-bnd>, <ejb-bnd>` etc...)?  Is solution 2, an enhancement any other child element could take advantage of?

**Comment by tjwatson** [comment]
> How is this different from changes to any of the other`<webApplication>`child elements (`<web-bnd>, <ejb-bnd>` etc...)? Is solution 2, an enhancement any other child element could take advantage of?

Option 2 is a design change to how application manager processes its configuration changes.  Currently any configuration change that is a child of the application element `<Application/>` or any others the inherit from that  (e.g. `<webApplication/>`) cause the application manager to restart the application.  The receiver of the child configuration (e.g. `<webservices-bnd>`) does not need to worry about forcing the app to restart.  It just happens and then all the config under it can take effect on the restart of the application.  To me adding a concept where a child element change under application can optionally not cause an application restart is a pretty big change to consider.

Option 4 is taking advantage of the fact that Thomas is adding new configuration element for XML web services that is removed from the application element configuration.  So it would not require a design change to the application manager configuration story.

**Comment by anjumfatima90** [comment]
Following our discussion, we reached a decision to opt for option 1 in the initial release of InstantOn support for XML Web Services. Option 2 is impractical because updating other child elements of `webApplication`, such as classloading, would necessitate restarting the application. Therefore, making a substantial change to Application Manager is not the appropriate course of action. Option 4 #25265 may be considered in the future; additional exploration is required, including research on the extent to which customers are utilizing the 'webservices-bnd' config, with a focus on ensuring zero migration for customers.
