### ISSUE TITLE
Create MP 6.1 TCK Results pages

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#27091]
Draft is here:
https://certifications-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/certifications/microprofile/6.1/23.0.0.12-TCKResults.html

**Comment by tevans78** [comment]
We have done everything we need to for now.
Results are live: https://openliberty.io/certifications/microprofile/6.1/23.0.0.12-TCKResults.html
