### ISSUE TITLE
DatabaseStoreImpl will NPE on createOrmFile when entityClassEntries is null

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#27181]
See https://github.com/OpenLiberty/open-liberty/blob/7ab9235847091f523b8a8b4282c6241b3a4763f0/dev/com.ibm.ws.persistence/src/com/ibm/wsspi/persistence/internal/DatabaseStoreImpl.java#L649C48-L649C48

The condition:
`(entityClassNames == null || entityClassNames.length == 0) && (entityClassEntries == null && entityClassEntries.length == 0)`

This will NPE if `entityClassEntries` is null on the access to `entityClassEntries.length`.  It seems that last `&&` should be `||`:
`(entityClassNames == null || entityClassNames.length == 0) && (entityClassEntries == null || entityClassEntries.length == 0)`

**Comment by njr-11** [comment]
@Riva-Tholoor-Philip @anija-anil @ajaypaul-ibm - this should be an easy bug fix in the JPA persistence service. Tom posted the correction to make in the issue writeup. One of you can pick it up for practice.

**Comment by tkburroughs** [comment]
I changed `release bug` to just `bug` as code in error may only be reached for the Jakarta Data feature that is in beta... so no GA level features could experience the issue.
