### ISSUE TITLE
On z/OS server start from the bin directory fails.

### ISSUE THREAD

**Issue by tspewak** [OpenLiberty/open-liberty#27191]
**Describe the bug**  
On z/OS when server start --clean is issued from the bin directory it fails with the following:
Error: Unable to access jarfile ./../bin/tools/ws-server.jar

**Steps to Reproduce**  
cd to the wlp/bin directory and issue
server start --clean

**Expected behavior**  
Server should start.

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.12
 
**Additional context**  
A fully qualified path to bin like below works.
/u/MSTONE1/wlpifix/test/wlp_230012/wlp/bin/server start --clean

**Comment by jimblye** [comment]
#regression

**Comment by jimblye** [comment]
#regression
