### ISSUE TITLE
Test Summary: Instant on testing for jaxws/xmlws features

### ISSUE THREAD

**Issue by anjumfatima90** [OpenLiberty/open-liberty#27214]
This the test summary for Open Liberty InstantOn Epic #26840.

For buckets that require a fully supported CRIU host environment we need an annotation called `componenttest.annotation.CheckpointTest` previously known as `componenttest.annotation.SkipIfCheckpointNotSupported` . Tests with this annotation will be skipped if the host environment does not have the necessary prerequisites to support Open Liberty InstantOn.

### List of FAT projects affected
* io.openliberty.checkpoint_fat
* io.openliberty.checkpoint_fat_xmlws

### Test strategy

* What functionality is new or modified by this feature?
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

 confidence level - 3.5
> The FATs attempt to cover as much as possible such that we can release the initial support for InstantOn for jaxws/xmlws features.

**Comment by anjumfatima90** [comment]
**General test behavior**

The tests encompasses testing checkpoint/restore for the jaxws/xmlws application. The tests mainly focus on testing AFTER_APP_START phase of checkpoint.

The positive tests aim is to verify the successful completion of each step (checkpoint/restore) as expected. This involves ensuring that the expected page, response, and response status are received, both with and without configuration updates.

The tests are repeated to test EE8, EE9 and EE10 features.

List of FAT projects affected:
**1. io.openliberty.checkpoint_fat:**

**JaxWSVirtualHostTest:**
Features tested: jaxws-2.2, xmlWS-3.0, xmlWS-4.0

The tests verify that the appropriate response page can be accessed when the server performs checkpoint/restore.

**2. io.openliberty.checkpoint_fat_xmlws**
Features tested: jaxws-2.2, xmlWS-3.0, xmlWS-4.0

All the following tests verifies that the appropriate response page can be accessed when the server performs checkpoint/restore.

**EJBWSBasicTest :** Tests ejb with jaxws/xmlws. 
**LibertyCXFPositivePropertiesTest:** Tests properties cxf.multipart.attachment and cxf.ignore.unsupported.policy. Also tests if the server restores properly on updating the `webservices-bnd` config after the checkpoint.  We do see an application restart on restore because of the config update. We decided to maintain that behavior. For ref: #27089.
**WebServiceRefTest:** Tests @WebServiceRef annotation in the JAX-WS client

**Comment by ayoho** [comment]
LGTM 👍
