### ISSUE TITLE
ConfigProviderResolver holds weak references to Config

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#2724]
`AbstractProviderResolver` (part of our implementation of `ConfigProviderResolver`) stores `Config` instances that it knows about in `WeakReference`s.

This means that if a user of the SPI calls `ConfigProviderResolver.registerConfig()` to register their `Config` and doesn't keep their own reference to it, it can be garbage collected at any time.

If it is garbage collected, calls to `ConfigProvider.getConfig()` will return a newly created `Config` with all the default sources, not the one that the user configured and registered.

I suspect this is the cause of https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=252669

We think the current implementation was put in place to avoid causing memory leaks by maintaining a strong reference to the Classloader. In particular `Config` stores the `ConversionManager` which in turn stores the `Classloader`. We think it should be safe to carefully change the `ConversionManager` to only store a `WeakReference` to the `ClassLoader`.

We also need a test to ensure we haven't missed anything and don't leak memory if lots of apps are stopped and started. It should be sufficient to start an app, request a page that will cause config to initialize, remove the app, repeat several times and then inspect the `AbstractProviderResolver` to see how many `Classloader`s and `Config`s it still has.

**Comment by tevans78** [comment]
This issue should also be used to improve the error reporting from the the StressTest that we think revealed the problem

**Comment by benjamin-confino** [comment]
Resolved in e408bb5f9ae240e90a7f1c4018e8a345947dbab2
