### ISSUE TITLE
ConfigBean closes config when it's destroyed

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#2725]
ConfigBean is a request scoped bean, but it actually produces a `Config` object with the lifetime of the application.

When the ConfigBean is destroyed, it's calling `releaseConfig()` which in turn calls `Config.close()`. If there are two requests running which have the same `Config` injected, when one of them finishes and the request scope is destroyed, the other will find that its `Config` instance starts throwing `ConfigClosedException`s.

Write a test to provoke this scenario, then fix the issue.

**Comment by tevans78** [comment]
ConfigBean should not call releaseConfig since the Config is longer lived than the bean.

**Comment by benjamin-confino** [comment]
I have a test that creates two requests and ensures that the second finishes first with a bit of time to spare. However this has not reproduced the issue, I may have to go back to the drawing board.
