### ISSUE TITLE
FTS - Enable verbose garbage collection by default on IBM Java/Semeru

### ISSUE THREAD

**Issue by rsherget** [OpenLiberty/open-liberty#27254]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

The change creates a verbosegc log file by default when using IBM Java/Semeru. The tests created to verify the function delivered by this feature test the following:

- the verbosegc log file gets created by default
- the verbosegc default can be turned off
- the verbosegc default can be changed and the verbosegc command that the user entered takes precedence
- if a JVM is used that isn't IBM Java/Semeru, no verbosegc log file is created

### List of FAT projects affected

* com.ibm.ws.kernel.boot_fat

### Test strategy

* What functionality is new or modified by this feature?

On server startup, if the user is using IBM Java/Semeru, a verbose garbage collection log file is created. This is done in our server scripts using `-Xverbosegclog`.

* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)

With IBM Java/Semeru:
- Test a normal server start creates a verbosegc log file. Verify the verbosegc log file is created.
- Test a server start with a jvm.options that turns off verbosegc. Verify verbosegc log file is not created.
- Test a server start with a server.env that turns off verbosegc. Verify verbosegc log file is not created.
- Test a server start with a server.env that keeps our verbosegc default. Verify the verbosegc log file is created.
- Test a server start with a jvm.options that specifies a new verbosegc command. Verify the user specified verbosegc log is created and the default verbosegc log is not created.
- Test a server start with an option to change the verbosegc command. Verify the user specified verbosegc log is created and the default verbosegc log is not created.

Without IBM Java/Semeru:
- Test a normal server does not create a verbosegc log file.

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

Has been manually tested on Mac and Windows with all the same scenarios as above.

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values: 4

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by dave-waddling** [comment]
Hi @rsherget, thanks for filling out this FTS - looking good. I have a couple of brief questions:

- Do any of the test cases involve starting the server with verbosegc enabled, stopping the server and disabling verbosegc, then restarting the server? (It's mentioned initially but not called out as a definitive test case).
- Are the different scenarios for how Liberty started on z/OS tested?
- Have you spoken to anyone in the CSD team to assess impact on the SOE?

**Comment by rsherget** [comment]
Do any of the test cases involve starting the server with verbosegc enabled, stopping the server and disabling verbosegc, then restarting the server? (It's mentioned initially but not called out as a definitive test case).

- This scenario is tested indirectly by the FAT tests. Each Fat test is running the same server with a different configuration (enabling, disabling, changing the verbosegc configuration) before stopping the server and moving to the next test. This was also tested manually.

Are the different scenarios for how Liberty started on z/OS tested?

- Yes, the changes work and were tested on z/OS as well.

Have you spoken to anyone in the CSD team to assess impact on the SOE?

- I spoke to Ethan Fritz a bit ago, he actually just pinged me about this and were working through getting an SOE build going to test the impact of the change

**Comment by dave-waddling** [comment]
Hi again @rsherget, many thanks for the clarifications - very reassuring and I'm happy to close this FTS out.

As per our Slack DMs, the impact on the SOE remains to be seen but if there are issues there they'll likely be for my team to solve; we'll cross that bridge if and when we come to it.
