### ISSUE TITLE
prototype - expose JVM metrics from Open Liberty using OTel standalone library instrumentation

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#27277]
use the "java platform" with standalone library instrumentation as mentioned at https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md . see if we're able to generate the required JVM metrics.

try with OpenJ9 (Semeru) and OpenJDK (Eclipse Temurin)

questions to answer -
- are we able to generate the metrics as described at https://github.com/open-telemetry/semantic-conventions/blob/main/docs/runtime/jvm-metrics.md ?
- how large is the standalone library (would we want to create a smaller package for just what we need)?

**Comment by fmhwong** [comment]
OpenJ9 Java 17 does not support Java Flight Recorder which is required by [runtime-telemetry-java17](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/runtime-telemetry/runtime-telemetry-java17).

**Comment by fmhwong** [comment]
Test results of using [runtime-telemetry-java8](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/runtime-telemetry/runtime-telemetry-java8) has been posted to https://github.com/eclipse-openj9/openj9/issues/18952
