### ISSUE TITLE
BETA BLOG - Back-channel logout support for OpenID Connect clients and servers

### ISSUE THREAD

**Issue by jimmy1wu** [OpenLiberty/open-liberty#27362]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty. For this post to be included in the beta issue please make sure that this is completed by the end of Friday following the GM (Tuesday). The beta and release blogs are created using automation and rely on you following the template's structure. **DO NOT REMOVE/ALTER THE `<GHA>` TAGS THROUGHOUT THIS TEMPLATE.**

Please provide the following information:
&#8203;<GHA-BLOG-RELATED-FEATURES>
1. Which Liberty feature(s) does your update relate to? 
    
    Human-readable name (eg WebSockets feature): OpenID Connect Client 1.0, Social Media Login 1.0, OpenID Connect Server 1.0 
   
    Short feature name (eg websockets-1.0):  openidConnectClient-1.0, socialLogin-1.0, openidConnectServer-1.0
   
   
    </GHA-BLOG-RELATED-FEATURES>

    <GHA-BLOG-TARGET-PERSONA>
2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.  
    Server admins
    
    </GHA-BLOG-TARGET-PERSONA>
   
    <GHA-BLOG-SUMMARY>
3. Provide a summary of the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.

   - What was the problem before and how does your update make their life better? (Why should they care?)
   
   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.
   
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?  
    
OpenID Connect clients and servers in Open Liberty now support back-channel logout. Back-channel logout allows OpenID Connect servers to directly notify OpenID Connect clients of a user logout so a local logout can also be performed for that user in each OpenID Connect client. Previously, OpenID Connect servers were only able to notify OpenID Connect clients that a user logged out by using iframes embedded in the OpenID Connect client's web page. This meant that a web page must be active for this communication to occur or else the OpenID Connect client would not be notified of the logout that occurred at the OpenID Connect server. Back-channel logout solves this problem through direct communication between the OpenID Connect server and clients.

With this release, back-channel logout is enabled by default when the OpenID Connect Client and Social Media Login features are used. The back-channel logout endpoints can be found at `/oidcclient/backchannel_logout/{clientId}` and `/ibm/api/social-login/backchannel_logout/{clientId}` for those features respectively.

To enable back-channel logout for OpenID Connect servers, the OpenID Connect client's back-channel logout URI must be specified when dynamically registering the OAuth client by using the `backchannel_logout_uri` metadata value, or by using the `backchannelLogoutUri` attribute for OAuth clients defined in a `localStore`. Additionally, the OpenID Connect server will wait a default of 180 seconds before the back-channel logout request times out, but this duration can also be specified using the `backchannelLogoutRequestTimeout` attribute. An example `server.xml` is shown here demonstrating how to specify the back-channel logout URI that an OpenID Connect server should use to make back-channel logout requests with a timeout of 60 seconds.

```
<featureManager>
    <feature>openidConnectServer-1.0</feature>
</featureManager>

...

<openidConnectProvider 
    id="OidcConfigSample" 
    backchannelLogoutRequestTimeout="60s"
    oauthProviderRef="OAuthConfigSample" ... />

<oauthProvider id="OAuthConfigSample" ... >
    <localStore>
        <client 
            name="client01"
            backchannelLogoutUri="http://localhost:9080/oidcclient/backchannel_logout/client01" 
            ... />
    </localStore>
</oauthProvider>
```

Now, when the OpenID Connect server's logout or end_session endpoint is invoked, the OpenID Connect server will also send back-channel logout requests to log the user out at the OpenID Connect clients as well. The OpenID Connect server's logout endpoint can be found at `/oidc/endpoint/{oidcProviderId}/logout` and the end_session endpoint can be found at `/oidc/endpoint/{oidcProviderId}/end_session`. Optionally, an `id_token_hint` containing an ID Token issued by that OpenID Connect server can be added to the endpoint request as a query parameter to help determine the user to log out. This is useful in scenarios where the logout or end_session request is made without the user's OpenID Connect server SSO cookie. Additionally, if the OpenID Connect server is configured with a SAML Identity Provider, a logout at the SAML Identity Provider will also trigger the OpenID Connect server to send back-channel logout requests to the OpenID Connect clients.

For more information about the Open Liberty configuration options, see:
- [openidConnectClient](https://openliberty.io/docs/latest/reference/config/openidConnectClient.html)
- [oidcLogin](https://openliberty.io/docs/latest/reference/config/oidcLogin.html)
- [openidConnectProvider](https://openliberty.io/docs/latest/reference/config/openidConnectProvider.html#oauthProvider)

For more information about the back-channel logout specification, see [OpenID Connect Back-Channel Logout 1.0](https://openid.net/specs/openid-connect-backchannel-1_0.html).
    
    </GHA-BLOG-SUMMARY>

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
    - Once you've approved the code review, close this issue. 
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by ayoho** [comment]
> Previously, OpenID Connect servers were only able to communicate to OpenID Connect clients of a user logout using iframes embedded in the OpenID Connect client's web page. This meant that a web page must be active for this communication to occur or else the OpenID Connect client will not be notified of the logout occurred at the OpenID Connect server.

Previously, OpenID Connect servers were only able to **notify OpenID Connect clients that a user logged out by** using iframes embedded in the OpenID Connect client's web page. This meant that a web page must be active for this communication to occur or else the OpenID Connect client **would** not be notified of the logout **that** occurred at the OpenID Connect server.

> To enable back-channel logout for OpenID Connect servers, the OpenID Connect client's back-channel logout URI must be specified using the backchannelLogoutUri attribute.

To enable back-channel logout for OpenID Connect servers, the OpenID Connect client's back-channel logout URI must be specified **when dynamically registering the OAuth client by using the `backchannel_logout_uri` metadata value, or by using the `backchannelLogoutUri` attribute for OAuth clients defined in a `localStore`**.

> Additionally, the OpenID Connect server will wait a default of 180s before the back-channel logout request times out, but this duration can also be specified using the backchannelLogoutRequestTimeout attribute. Here is an example server.xml demonstrating how to specify the back-channel logout URI an OpenID Connect server should use to make back-channel logout requests with a timeout of 60s.

Additionally, the OpenID Connect server will wait a default of **180 seconds** before the back-channel logout request times out, but this duration can also be specified using the `backchannelLogoutRequestTimeout` attribute. **An example `server.xml` is shown here** demonstrating how to specify the back-channel logout URI **that** an OpenID Connect server should use to make back-channel logout requests with a timeout of **60 seconds**.

> Optionally, an id_token_hint containing an ID Token issued by that OpenID Connect server can be added to the endpoint request as a query parameter to help determine the user to logout.

Optionally, an id_token_hint containing an ID Token issued by that OpenID Connect server can be added to the endpoint request as a query parameter to help determine the user to **log out**.

**Comment by jimmy1wu** [comment]
beta blog published: https://openliberty.io/blog/2024/02/13/24.0.0.2-beta.html
