### ISSUE TITLE
InstantOn jdbc-4.1 and jdbc-4.3 Feature Test Summary

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#27381]
## Test Strategy

This is the test summary for Open Liberty InstantOn Epic #27328

With the initial InstantOn support Epic #16384 the feature jdbc-4.2 was enabled for InstantOn and was included in the original test summary for that feature with #25294.  Test of the other versions of the jdbc feature involved enhancing the existing InstantOn tests for `jdbc-4.2` to repeat them for `jdbc-4.1` and `jdbc-4.2` features.

### List of FAT projects affected

* io.openliberty.checkpoint_fat_persistence

### Test strategy

* What functionality is new or modified by this feature?  The `jdbc-4.1` and `jdbc-4.3` features have been enabled for InstantOn checkpoints.
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

DB2Test:
Features tested: jdbc-4.1, jdbc-4.2, jdbc-4.3

The tests verify that the properties that configure the jdbc driver are set properly on the data source for restore.  Also, verify that
WAS JDBC statement wrappers can properly handle the NULL result set. They also ensure that the proper implementation
classes are used for the various data sources configured. Additionally checks that the locks are not shared between
transaction branches that are loosely coupled.

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

We rate our confidence level at 3.5:

The InstantOn feature covers a very large set of Open Liberty features for a new piece of functionality. The FATs attempt to cover as much as possible such that we can release the initial support for InstantOn in a reasonable amount of time. We ensured that we have tests that enable each supported feature for InstantOn and developed a set of applications that exercise the various features. We also have a set of configuration tests for the various features but we do not have as large of coverage on the configuration updates as there could be. Test improvements for InstantOn will be a continuous effort as we gain more user experience with the functionality. One such area that needs attention is in-container testing. Right now we are depending on SVT to do the bulk of our automated container testing. We need to pull this testing into development tests to catch issues earlier. Other areas include expanding our coverage against supported Databases, making sure Server wide MP configuration changes work.

**Comment by ayoho** [comment]
LGTM 👍
