### ISSUE TITLE
InstantOn appSecurity-1.0 javaMail-1.6 mail-2.0 mail-2.1 and passwordUtilities-1.0 Feature Test Summary

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#27391]
## Test Strategy

This is the test summary for Open Liberty InstantOn Epic #27329

With the initial InstantOn support Epic #16384 the feature `passwordUtilities` version 1.1 was enabled for InstantOn was included in the original test summary for that feature with #25294.  Testing of the `passwordUtilities-1.0` feature involved enhancing the existing InstantOn tests for `passwordUtilities-1.1` to repeat for `passwordUtilities-1.0`.

With the initial InstantOn support Epic #16384 the feature `appSecurity` versions 2.0, 3.0, 4.0, 5.0 were enabled for InstantOn was included in the original test summary for that feature with #25294.  In order to provide support for `passworkdUtilities-1.0` the InstantOn support had to be added also to `appSecurity` version 1.0.  The `appSecurity-1.0` feature includes `appSecurity-2.0` but also enables `servlet` and `ldapRegistry-3.0` features.  All tests of `appSecurity-2.0` cover the functionality of `appSecurty-1.0` already.  And the tests for `passwordUtilities-1.0` add additional usage of `appSecurity-1.0` during the FATs for `passwordUtilities` features.

The mail features were not supported as part of Epic #16384.  For the mail testing, the tests encompasses testing checkpoint phase AFTER_APP_START. The aim is to verify the successful completion of each step (checkpoint/restore) as expected after doing configuration changes before restore.  These tests are repeated for all versions of mail that support InstantOn.

### List of FAT projects affected

* io.openliberty.checkpoint_fat
* io.openliberty.checkpoint_fat_mail

### Test strategy

* What functionality is new or modified by this feature?
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

#### Mail tests
IMAPTest: The tests verifies successful reading of mail (inbox folder) sent from mail servers using the IMAP protocol. The tests updates the mail session config after the checkpoint before doing the restore and verifies that the updated mail session config is used when connecting to mail server.
MailSessionInjectionTest: The tests verifies successful creation of mail session using the deployment descriptor config and annotation during restore.

#### passwordUtilites-1.0 and appSecurity-1.0
PasswordUtilsTest:

The tests cover the verification of programmatic login with default principal mapping, as well as the authentication data
username and password verification after the server is restored.

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

We rate our confidence level at 3.5:

The InstantOn feature covers a very large set of Open Liberty features for a new piece of functionality. The FATs attempt to cover as much as possible such that we can release the initial support for InstantOn in a reasonable amount of time. We ensured that we have tests that enable each supported feature for InstantOn and developed a set of applications that exercise the various features. We also have a set of configuration tests for the various features but we do not have as large of coverage on the configuration updates as there could be. Test improvements for InstantOn will be a continuous effort as we gain more user experience with the functionality. One such area that needs attention is in-container testing. Right now we are depending on SVT to do the bulk of our automated container testing. We need to pull this testing into development tests to catch issues earlier. Other areas include expanding our coverage against supported Databases, making sure Server wide MP configuration changes work.

**Comment by ayoho** [comment]
LGTM 👍
