### ISSUE TITLE
Default charset encoding for OpenLiberty?

### ISSUE THREAD

**Issue by mdk8414** [OpenLiberty/open-liberty#27402]
Hi, my team recently switched our Java 17 Springboot 3 application webserver from Tomcat to OpenLiberty and since then we've been experiencing a couple encoding issues. The default encoding for Tomcat was ISO-8859-1 so much of our code revolved around using that encoding or converting it to UTF-8. What is the default encoding for OpenLiberty? Is there a way to switch it so that it defaults to ISO-8859-1? Thank you

**Comment by pmd1nh** [comment]
Hi,
The default encoding for parsing any request POST or parameters is ISO-8859-1 in Liberty.

You can change the default encoding by add the following line to the server's jvm.options file:

`-Ddefault.client.encoding=UTF-8`

**Comment by pnicolucci** [comment]
@mdk8414 can this issue be closed given the response from @pmd1nh ?

**Comment by mdk8414** [comment]
> Hi, The default encoding for parsing any request POST or parameters is ISO-8859-1 in Liberty.
> 
> You can change the default encoding by add the following line to the server's jvm.options file:
> 
> `-Ddefault.client.encoding=UTF-8`

Yes, thanks
