### ISSUE TITLE
InstantOn localConnector-1.0 Feature Test Summary

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#27407]
## Test Strategy

This is the test summary for Open Liberty InstantOn Epic #26851

The localConnector-1.0 feature  was not supported as part of Epic #16384.  For the local connector testing we used a subset of a modified version of the com.ibm.ws.jmx_fat test bucket which has the tests of the local connector functionality. The tests verify that the localConnector-1.0 feature can be configured when doing a checkpoint and is functional on the restore side.

### List of FAT projects affected

* io.openliberty.checkpoint_fat

### Test strategy

LocalConnectorTest - Tests that a server configuration with the `localConnector-1.0` feature enabled is able to make a successful checkpoint of the server process.  The test then verifies the server process can be restored successfully.  Once restored the test verifies that a connection to the MBean server can be made successfully using a local connector and that the expected results are found when doing various MBean calls.

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

We rate our confidence level at 3.5:

The InstantOn feature covers a very large set of Open Liberty features for a new piece of functionality. The FATs attempt to cover as much as possible such that we can release the initial support for InstantOn in a reasonable amount of time. We ensured that we have tests that enable each supported feature for InstantOn and developed a set of applications that exercise the various features. We also have a set of configuration tests for the various features but we do not have as large of coverage on the configuration updates as there could be. Test improvements for InstantOn will be a continuous effort as we gain more user experience with the functionality. One such area that needs attention is in-container testing. Right now we are depending on SVT to do the bulk of our automated container testing. We need to pull this testing into development tests to catch issues earlier. Other areas include expanding our coverage against supported Databases, making sure Server wide MP configuration changes work.

**Comment by ayoho** [comment]
LGTM 👍
