### ISSUE TITLE
Jakarta Persistence 3.2 : Deliver repeats of JPA FAT with Jakarta EE 11

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#27445]
Delivery of the M1 API build also repeated many of the JPA FATs for JPA 3.2.  Most of the remaining FATs should also be repeated with all Jakarta EE 11 features.  Primarily, this includes all JPA FAT that use the EE repeat actions rather than a common project with sub-projects per JPA level (i.e. those were handled by the M1 delivery, #27273).

Specifically, the repeat actions in the following FATs should be updated to include EE11_FEATURES:

- [x] com.ibm.ws.jpa.tests.container.client_fat
- [x] com.ibm.ws.jpa.tests.jpa_22_fat
- [x] com.ibm.ws.jpa.tests.jpa_30_fat
- [x] com.ibm.ws.jpa.tests.jpa_31_fat
- [x] com.ibm.ws.jpa.tests.jpa_fat
- [x] com.ibm.ws.jpa.tests.spec10.injection.defaultPersistenceUnit_fat
- [x] com.ibm.ws.jpa.tests.spec10.injection.dfi_fat
- [x] com.ibm.ws.jpa.tests.spec10.injection.dmi_fat
- [x] com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat
- [x] com.ibm.ws.jpa.tests.spec10.injection.jarfile_fat
- [x] com.ibm.ws.jpa.tests.spec10.injection.jndi_fat
- [x] com.ibm.ws.jpa.tests.spec10.injection.mdb_fat
- [x] com.ibm.ws.jpa.tests.spec10.issues_fat
- [x] com.ibm.ws.jpa.tests.spec21.cdi_fat
- [x] com.ibm.ws.jpa.tests.spec21.issues_fat
- [x] com.ibm.ws.jpa.tests.spec21.txsynchronization_fat

Note that adding another repeat will increase the time it takes to run the FAT. Before delivering, the FAT should be run locally and verified to 
- take <= 30 minutes in LITE mode
- take <= 60 minutes in FULL mode

If LITE mode is too long, some repeats can be moved to FULL by adding `.fullfatonly()` to the repeat.
If FULL mode is too long, then the bucket may need to be split into multiple smaller buckets, or switch to using a common project with sub-projects that repeat per JPA level.

for #25091

**Comment by ajaypaul-ibm** [comment]
Closing this issue as the [PR](https://github.com/OpenLiberty/open-liberty/pull/27452) is merged
