### ISSUE TITLE
Zos ASCII scripts can't be run 

### ISSUE THREAD

**Issue by travatine** [OpenLiberty/open-liberty#2745]
After unzipping the zos zip using the pax command the resulting scripts are in ASCII.
These can not be run without first converting the scripts to EBCDIC , using iconv or similar tools.

Please am I missing something?

Could the zos build scripts please be open sourced?

Thanks.
Travis.

**Comment by follis** [comment]
There isn't an z/OS .pax version of Open Liberty, so this isn't the place to raise this issue.  That said, the .pax should have tagged the scripts as being in ASCII (ls -T should show you).  To get the shell to honor the tags you need to export _BPXK_AUTOCVT=ON.
