### ISSUE TITLE
Configuring a variable with no value or defaultValue prevents config overrides being processed

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#27467]
**Describe the bug**  
Due to an error a server.xml had a variable defined like this:

```
<variable name="myVar" />
```

as a consequence of this the config snippets in `configDropins/overrides` were not processed. This was confirmed by updating the variable to provide a defaultValue. The variable value was defined outside of server.xml so references to `${myVar}` resolved.

**Steps to Reproduce**  
Place some configuration in `configDropins/overrides` add into `server.xml` a `variable` with no `value` or `defaultValue`.

**Expected behavior**  
Config overrides is loaded

**Diagnostic information:**  
 - OpenLiberty Version: [e.g. 21.0.0.8 - 21.0.0.10] 23.0.0.12
 - Affected feature(s) [e.g. mpHealth-3.0] kernel
 - Java Version: [i.e. full output of `java -version`] Eclipse OpenJ9 VM, version 17.0.9+9
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`
Message that drew my attention to this was:

```[01/25/2024 22:38:54.235 EDT] E CWWKG0092E: A value attribute or defaultValue attribute must be specified for the variable on line 56 of resource file:/opt/ol/wlp/usr/servers/defa
ultServer/server.xml```

It would be nice if this message also provided the variable name, it would have made it easier to spot the error.

**Comment by jgawor** [comment]
I don't know if that makes any difference, but the value for the variable was actually provided. In this case via a file the in `${server.config.dir}/variables` directory.

**Comment by rsherget** [comment]
PR #27707 should fix this issue
