### ISSUE TITLE
Faces 4.1: Missing "if" attribute of <f:viewAction>

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#27559]
`https://github.com/jakartaee/faces/issues/1811`

**Comment by volosied** [comment]
This is a javadoc / vlddoc change, but I'm seeing we still use `rendered`, not `if`. 

![Screenshot 2024-02-22 at 11 51 13 AM](https://github.com/OpenLiberty/open-liberty/assets/5934310/0ea0ea66-1d74-44de-88f2-15b143a8ea99)

Class: https://github.com/apache/myfaces/blame/4.1.x/api/src/main/java/jakarta/faces/component/UIViewAction.java

Description taken from UIComponentBase: https://github.com/apache/myfaces/blob/4.1.x/api/src/main/java/jakarta/faces/component/UIComponentBase.java#L1130

**Comment by volosied** [comment]
Changing upstream via `https://github.com/apache/myfaces/pull/678`

**Comment by volosied** [comment]
[myfaces-impl-4.1.0-RC2-facelets-tlddoc.jar](https://repo1.maven.org/maven2/org/apache/myfaces/core/myfaces-impl/4.1.0-RC2/myfaces-impl-4.1.0-RC2-facelets-tlddoc.jar) show shows the correct output:

![image](https://github.com/OpenLiberty/open-liberty/assets/5934310/a295e1a9-886a-4fa6-b3eb-2679bb9426ec)
