### ISSUE TITLE
Faces 4.1: Remove mentions in javadoc wrt backwards compatibility of facelets.* context params

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#27555]
`https://github.com/jakartaee/faces/issues/1828`

**Comment by volosied** [comment]
`facelets.REFRESH_PERIOD` looks to have been a mojarra specific context parameter and standardized into the spec via `jakarta.faces.FACELETS_BUFFER_SIZE`

Looks like a no-op for us. Safe to close out, @pnicolucci?

**Comment by pnicolucci** [comment]
I don't think this is a no-op:

1) https://github.com/apache/myfaces/blob/45c8d2c36725970f83e10a47410f0fa1a75415f4/api/src/main/java/jakarta/faces/application/ViewHandler.java#L130
2) https://github.com/apache/myfaces/blob/45c8d2c36725970f83e10a47410f0fa1a75415f4/api/src/main/java/jakarta/faces/application/ViewHandler.java#L99
3) https://github.com/apache/myfaces/blob/45c8d2c36725970f83e10a47410f0fa1a75415f4/api/src/main/java/jakarta/faces/application/ViewHandler.java#L123
4) https://github.com/apache/myfaces/blob/45c8d2c36725970f83e10a47410f0fa1a75415f4/api/src/main/java/jakarta/faces/application/ViewHandler.java#L117
5) https://github.com/apache/myfaces/blob/45c8d2c36725970f83e10a47410f0fa1a75415f4/api/src/main/java/jakarta/faces/application/ViewHandler.java#L109

**Comment by volosied** [comment]
Thanks for catching that -- work is done via `https://issues.apache.org/jira/browse/MYFACES-4651`

**Comment by volosied** [comment]
The 4.1 Page does not contain these context parameter aliases: https://myfaces.apache.org/#/core41

The removals were included in 4.1.0-RC2, so I'll close this issue out?
