### ISSUE TITLE
Faces 4.1: Faces 4.1: Deprecate full state saving (FSS)

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#27554]
`https://github.com/jakartaee/faces/issues/1829`

**Comment by volosied** [comment]
Tests In Progress

**Comment by volosied** [comment]
I added logging for `jakarta.faces.PARTIAL_STATE_SAVING` in RC1 , but nothing for `jakarta.faces.FULL_STATE_SAVING_VIEW_IDS`.   MyFaces has since been updated. 

Just need to enable the `verifyFullStateSavingViewIdsIsDeprecated` test once RC2 is released.  This issue will be kept open until then.
