### ISSUE TITLE
Faces 4.1: id attribute is missing in vdl of h:head and h:body

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#27562]
`https://github.com/jakartaee/faces/issues/1760`

**Comment by volosied** [comment]
This one might need some more work in the MF community. I'm not seeing myfaces write an id on the head element.

**Comment by volosied** [comment]
Saving my test app so I don't need to recreate it... [RenderId_Spec1760.war.zip](https://github.com/OpenLiberty/open-liberty/files/14365237/RenderId_Spec1760.war.zip)

**Comment by volosied** [comment]
I created a test, but it's not enabled.  This issue will be kept open until the behavior is fixed and test is enabled.
