### ISSUE TITLE
Faces 4.1: Deprecate unused PreDestroyCustomScopeEvent and PostConstructCustomScopeEvent

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#27568]
`https://github.com/jakartaee/faces/issues/1707`

**Comment by volosied** [comment]
Marked deprecated here:
- https://github.com/apache/myfaces/blob/4.1.x/api/src/main/java/jakarta/faces/event/PreDestroyCustomScopeEvent.java#L26
- https://github.com/apache/myfaces/blob/4.1.x/api/src/main/java/jakarta/faces/event/PostConstructCustomScopeEvent.java#L29

I don't believe there's a way to test these without Managed Beans. Safe to close out, @pnicolucci?

**Comment by pnicolucci** [comment]
@volosied  yea I agree. The TCK signature tests will catch stuff like this if it were not correct.
