### ISSUE TITLE
Faces 4.1: Remove UIComponent.bindings field

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#27565]
`https://github.com/jakartaee/faces/issues/1725`

**Comment by volosied** [comment]
MyFaces: Deprecated as of now: https://github.com/apache/myfaces/blob/4.1.x/api/src/main/java/jakarta/faces/component/UIComponent.java#L144-L145

Mojarra Removed it: https://github.com/eclipse-ee4j/mojarra/commit/d3aed2499c582c461676cece1a9f845fde77fe1b

**Comment by pnicolucci** [comment]
Since we are only doing a Faces 4.1 (minor version update) for Jakarta EE11, we can not remove the field. This will have to wait until the next major version update for the Faces specification.

**Comment by pnicolucci** [comment]
This is also no longer in the changelog for Faces 4.1

**Comment by pnicolucci** [comment]
Closing as there is no work to be done for Faces 4.1.
