### ISSUE TITLE
Faces 4.1: Require firing events for @Initialized, @BeforeDestroyed, @Destroyed for build-in scopes.

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#27564]
`https://github.com/jakartaee/faces/issues/1739`

**Comment by volosied** [comment]
Test in progress. However, MyFaces and Mojarra fail to work with the `@BeforeDestroyed` annotation, but the others work fine.

**Comment by pnicolucci** [comment]
> Test in progress. However, MyFaces and Mojarra fail to work with the `@BeforeDestroyed` annotation, but the others work fine.

@volosied something we need to bring up in the spec community?

**Comment by volosied** [comment]
@pnicolucci  No need, I believe.  It's just an implementation issue.  I'll create issues in MyFaces and Mojarra. 

Keeping this issue open until `@BeforeDestroyed` behavior is fixed. Otherwise a test was created via 27713 for the other two annotations.

**Comment by pnicolucci** [comment]
@volosied  do we have an issue opened with the communities for this one?

**Comment by volosied** [comment]
Linking to JIRA: https://issues.apache.org/jira/browse/MYFACES-4665
