### ISSUE TITLE
Faces 4.1: Javadoc for Application.subscribeToEvent methods has a reference to context that is incorrect

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#27566]
`https://github.com/jakartaee/faces/issues/1712`

**Comment by volosied** [comment]
From the issue:

> There is no context parameter for either of these methods. The reference to context should be removed.

This was only a javadoc change, so I don't see anything to do here.

Our class for reference: https://github.com/apache/myfaces/blob/94f6d9caa31ecea50d0be77b20c4b689521629e8/api/src/main/java/jakarta/faces/application/Application.java#L1099-L1135

**Comment by pnicolucci** [comment]
@volosied  this looks good. I'm ok with you closing this.
