### ISSUE TITLE
Faces 4.1: This release now requires Java SE 17 or newer (aligned with Jakarta EE 11).

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#27574]
This should be a no-op as we already require a min of Java 17 for all of our EE11 features including Faces 4.1.

Creating an issue so we can have one issue for each issue in the Faces 4.1 changelog to ensure we don't miss any testing.

**Comment by volosied** [comment]
The Java 17 PR: `https://github.com/apache/myfaces/pull/675` 

@pnicolucci  Safe to close out?
