### ISSUE TITLE
Faces 4.1: Add rowStatePreserved property to UIRepeat, exactly the same as UIData

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#27572]
`https://github.com/jakartaee/faces/issues/1263`

**Comment by volosied** [comment]
I found this blog useful for the rowStatePreserved property -  `http://lu4242.blogspot.com/2011/06/jsf-component-state-per-row-for.html`

Test could be created from https://github.com/apache/myfaces/pull/629/files#diff-aa1d2ba3983b50176eac59af8e408930680a18eab37b9fda73ed77f1c8a8594c
