### ISSUE TITLE
Faces 4.1: Deprecate unused composite:extension

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#27570]
`https://github.com/jakartaee/faces/issues/1549`

**Comment by volosied** [comment]
Test in progress

**Comment by volosied** [comment]
Facelet Doc: 
![image](https://github.com/OpenLiberty/open-liberty/assets/5934310/5e1d3865-a4df-4613-b54b-ca80db63a9bf)

**Comment by volosied** [comment]
Implemented in 4.1 and Test added via ` #27713`
