### ISSUE TITLE
Faces 4.1: dataTable rowStatePreserved attribute is missing in vdl

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#27573]
`https://github.com/jakartaee/faces/issues/1864`

**Comment by volosied** [comment]
MyFaces `JSF HTML Facelets Tag Library Tag dataTable`  Pages show: 
<img width="1365" alt="image" src="https://github.com/OpenLiberty/open-liberty/assets/5934310/aabb2dae-1e92-47c4-8d37-9aa68a7878de">

Downloaded from [myfaces-impl-4.1.0-RC1-facelets-tlddoc.jar](https://repo1.maven.org/maven2/org/apache/myfaces/core/myfaces-impl/4.1.0-RC1/)

**Comment by volosied** [comment]
Side note: [myfaces-impl-4.1.0-RC1-tlddoc.jar](https://repo1.maven.org/maven2/org/apache/myfaces/core/myfaces-impl/4.1.0-RC1/) is empty of any information? 

<img width="1686" alt="image" src="https://github.com/OpenLiberty/open-liberty/assets/5934310/6b77860a-f237-4782-bfeb-2ef96bb08cd4">


Created [MYFACES-4652](https://issues.apache.org/jira/browse/MYFACES-4652) to fix later on.

**Comment by pnicolucci** [comment]
Closing this one out as there is no work remaining, this was just a doc update and MyFaces looks good!
