### ISSUE TITLE
@Retry cannot be used with CDI's @PostConstruct annotation

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#276]
While working on the MP Conference demo app, I was attempting to add FT annotations to one of the classes like this:

```java
@ApplicationScoped
@Persistent
@Timeout(1000)
public class CouchAttendeeDAO implements AttendeeDAO {

    private int numRetries = 0;

    @PostConstruct
    @Retry(maxRetries = 5) // <-- annotation here causes issue
    public void connect() {
        if(numRetries++ < 2) {
          // blow up on purpose
          throw new RuntimeException("Connection attempt failed!");
        }
        // do normal connection code
    }
}
```

If I use `@Retry` in a different method not annotated with `@PostConstruct` then it works fine.

See attached logs for failure info:
[messages.log](https://github.com/OpenLiberty/open-liberty/files/1335823/messages.log)

**Comment by Azquelt** [comment]
You can't use Fault Tolerance annotations on lifecycle callbacks (`@PostConstruct`, `@PreDestroy` etc.) 

This is as defined in the Fault Tolerance spec [here][1]:
> invocation must be business method invocation as defined in CDI specification.

[1]: https://github.com/eclipse/microprofile-fault-tolerance/blob/master/spec/src/main/asciidoc/relationship.asciidoc
