### ISSUE TITLE
Invalid encoded request URI should return 400 instead of 500

### ISSUE THREAD

**Issue by pmd1nh** [OpenLiberty/open-liberty#27620]
**Describe the bug**  
500 status code returns for an invalid encoded URI.  It also creates a FFDC log.  It can cause a false alarm for the server administrator.  A `400 Bad Request` should be returned.

**Steps to Reproduce**  
Send a bad encoded URI to an existing application (i.e context root).  For example:

`http://host:port/%5%20C..`

**Expected behavior**  
Return `400 Bad Request` response without any FFDC.

**Diagnostic information:**  
 - OpenLiberty Version: all version until this is fixed.
 - Affected feature(s) [servlet]
 - Java Version: [11]
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**  
None

**Comment by pmd1nh** [comment]
**Describe the bug**  
500 status code returns for an invalid encoded URI.  It also creates a FFDC log.  It can cause a false alarm for the server administrator.  A `400 Bad Request` should be returned.


**Steps to Reproduce**  
Send a bad encoded URI to an existing application (i.e context root).  For example:

`http://host:port/%5%20C..`

**Expected behavior**  
Return `400 Bad Request` response without any FFDC.

**Diagnostic information:**  
 - OpenLiberty Version: all version until this is fixed.
 - Affected feature(s) [servlet]
 - Java Version: [11]
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**  
None

**Comment by pnicolucci** [comment]
I'm adding the original description of this bug as a comment and updated the top-level comment with the `release bug` template:

> The server returns a 500 and logs a FFDC for  a request that contains invalid encoded character.  It should return a 400 Bad Request instead.
> 
> Example: `http://host:port/%5%20C..`
> 
> Note: Most of the front-servers (i.e load balancer, web server...) may have filtered out these requests prior to the application server.

**Comment by pmd1nh** [comment]
Update tests to accommodate this change

https://github.ibm.com/websphere/WS-CD-Open/pull/31571

To avoid combined builds, the lWAS tests are disabled temporary until this PR is merged then reactive.
