### ISSUE TITLE
Faces 4.1: Remove noShip-1.0 from Faces FATs once faces-4.1 is beta'ed

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#27639]
Remove noShip-1.0 from Faces FATs once we beta.

_Originally posted by @volosied in https://github.com/OpenLiberty/open-liberty/pull/27485#discussion_r1487959067_

**Comment by pnicolucci** [comment]
We have tests that enable websockets so we can't quite do this yet.
