### ISSUE TITLE
build/export problem with io.openliberty.io.netty

### ISSUE THREAD

**Issue by epj** [OpenLiberty/open-liberty#27640]
**Describe the bug**  
There is a problem with how the project io.openliberty.io.netty is built or exported because it is not picked up automatically in WebSphere Liberty.

**Steps to Reproduce**  
After fresh and clean builds, io.openliberty.io.netty.jar is missing from /prereq.published/lib on the WL side.

**Expected behavior**  
/prereq.published/lib/io.openliberty.io.netty.jar needs to exist in WL.

**Comment by jhanders34** [comment]
Removed the `release bug` label since a customer would never run into this problem.
