### ISSUE TITLE
Minify issues warning about missing packages

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/open-liberty#277]
Using build openliberty-17.0.0.3-201709270743

PS C:\Users\charters\Development\Liberty\openliberty-17.0.0.3-201709270743\wlp> bin\server package defaultServer --include=minify
Packaging server defaultServer.
Querying server defaultServer for content.
Launching defaultServer (Open Liberty 17.0.0.3/wlp-1.0.18.201709270718) on IBM J9 VM, version pwa6480sr4fp5-20170421_01
(SR4 FP5) (en_GB)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[WARNING ] CWWKF0024W: The feature com.ibm.websphere.appserver.kernel-1.0 referenced a resource com.ibm.ws.repository/[1
.0.0,1.0.100) that was unable to be located during a packaging query.
[WARNING ] CWWKF0024W: The feature com.ibm.websphere.appserver.kernel-1.0 referenced a resource com.ibm.ws.repository.li
berty/[1.0.0,1.0.100) that was unable to be located during a packaging query.
[WARNING ] CWWKF0024W: The feature com.ibm.websphere.appserver.kernel-1.0 referenced a resource com.ibm.ws.install/[1.0.
0,1.0.100) that was unable to be located during a packaging query.
[WARNING ] CWWKF0024W: The feature com.ibm.websphere.appserver.kernel-1.0 referenced a resource com.ibm.ws.config.utilit
y/[1.0.0,1.0.100) that was unable to be located during a packaging query.
[WARNING ] CWWKF0024W: The feature com.ibm.websphere.appserver.kernel-1.0 referenced a resource com.ibm.ws.repository.re
solver/[1.0.0,1.0.100) that was unable to be located during a packaging query.
[AUDIT   ] CWWKF0026I: The server defaultServer is ready to build a smaller package.
[AUDIT   ] CWWKE0036I: The server defaultServer stopped after 2.37 seconds.
Building archive for server defaultServer.
Server defaultServer package complete in C:\Users\charters\Development\Liberty\openliberty-17.0.0.3-201709270743\wlp\usr
\servers\defaultServer\defaultServer.zip.

**Comment by hlhoots** [comment]
This should remain on hold until 18002 as portions of it will be fixed by changes planned in that release.

**Comment by hlhoots** [comment]
After the 18002 changes, it looks like we just have this one error remaining:
[WARNING ] CWWKF0024W: The feature com.ibm.websphere.appserver.kernel-1.0 referenced a resource com.ibm.ws.config.utility/[1.0.0,1.0.100) that was unable to be located during a packaging query.

**Comment by hlhoots** [comment]
The last warning for kernel-1.0 should be resolved with #10201
