### ISSUE TITLE
Job can not be purged when using the Java batch In-Memory Persistence  

### ISSUE THREAD

**Issue by Arunkumar-Kallyodan** [OpenLiberty/open-liberty#27715]
**Describe the bug**  
When using memory persistence with java batch, jobs cannot be removed from the in-memory repository

**Steps to Reproduce**  
Define a batch server with no batchPersistence defined so that it uses in-memory . Submit a jon and purge the job with the REST interface or batch Manager. A 500 error will occur and the job will not be removed from the in-memory repository. But the job logs will be deleted.

**Expected behavior**  
When using the purge using the REST interface or batchManager, the job should be removed from the backing repository either using in-memory or database

**Additional context**  
The limitation of using memory persistence is that if the server is stopped then the persistence is lost. However , a user should still be able to remove the data from the in-memory repository with a purge after this fix

**Comment by LifeIsGood524** [comment]
The PR is merged and is in a release build. Can this issue be closed? @dmbelina
