### ISSUE TITLE
General testing of jcacheContainer-1.1 feature

### ISSUE THREAD

**Issue by alexsm82** [OpenLiberty/open-liberty#2773]
User story:
"As a user of jCache in Liberty, I want Liberty to have good automated test coverage of the  jcacheContainer-1.1 feature."

Although the jcacheContainer functionality is tested in the session caching tests, there should be a test bucket for testing the jcacheContainer feature in the absence of the sessionCache feature.

**Comment by mswatosh** [comment]
Since jcacheContainer-1.1 will not be releasing with sessionCache, these tests will be enabled in the future with the jcacheContainer-1.1 feature.
