### ISSUE TITLE
Java version compatibility with Liberty 23.0.12

### ISSUE THREAD

**Issue by nagzeal** [OpenLiberty/open-liberty#27745]
Hi Team - I would like to know if there is any limitation of Java version of applications that can be deployed in Liberty.
Our application is on Java 8 (Spring Boot + React JS).
Could you please confirm we will be able to deploy this application in Liberty 23.0.12

Thanks

**Comment by NottyCode** [comment]
You can run Liberty on Java SE 8 as covered in our documentation [here](https://openliberty.io/docs/latest/java-se.html). Spring Boot is also supported as covered in our documentation [here](https://openliberty.io/docs/latest/deploy-spring-boot.html). React JS runs in the browser so Liberty support for it is not relevant to whether it would work or not.

**Comment by nagzeal** [comment]
How about Maven version, can you please comment on the compatibility of that?
