### ISSUE TITLE
Runnable package creation fails due to missing lafiles

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/open-liberty#278]
Using build openliberty-17.0.0.3-201709270743

PS C:\Users\charters\Development\Liberty\openliberty-17.0.0.3-201709270743\wlp> bin\server package --archive=defaultServer.jar --include=minify,runnable
Packaging server defaultServer.
Querying server defaultServer for content.
Launching defaultServer (Open Liberty 17.0.0.3/wlp-1.0.18.201709270718) on IBM J9 VM, version pwa6480sr4fp5-20170421_01
(SR4 FP5) (en_GB)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[WARNING ] CWWKF0024W: The feature com.ibm.websphere.appserver.kernel-1.0 referenced a resource com.ibm.ws.repository/[1
.0.0,1.0.100) that was unable to be located during a packaging query.
[WARNING ] CWWKF0024W: The feature com.ibm.websphere.appserver.kernel-1.0 referenced a resource com.ibm.ws.repository.li
berty/[1.0.0,1.0.100) that was unable to be located during a packaging query.
[WARNING ] CWWKF0024W: The feature com.ibm.websphere.appserver.kernel-1.0 referenced a resource com.ibm.ws.install/[1.0.
0,1.0.100) that was unable to be located during a packaging query.
[WARNING ] CWWKF0024W: The feature com.ibm.websphere.appserver.kernel-1.0 referenced a resource com.ibm.ws.config.utilit
y/[1.0.0,1.0.100) that was unable to be located during a packaging query.
[WARNING ] CWWKF0024W: The feature com.ibm.websphere.appserver.kernel-1.0 referenced a resource com.ibm.ws.repository.re
solver/[1.0.0,1.0.100) that was unable to be located during a packaging query.
[AUDIT   ] CWWKF0026I: The server defaultServer is ready to build a smaller package.
[AUDIT   ] CWWKE0036I: The server defaultServer stopped after 2.178 seconds.
Building archive for server defaultServer.
CWWKE0056E: Unable to zip up directory due to an IO exception java.io.FileNotFoundException: C:\Users\charters\Developme
nt\Liberty\openliberty-17.0.0.3-201709270743\wlp\lafiles.
Server defaultServer package failed. Check server logs for details.

**Comment by aguibert** [comment]
Stack trace for the CWWKE0056E is:
```
java.io.FileNotFoundException: C:\atemp\wlp-17003\lafiles
	at com.ibm.ws.kernel.boot.internal.commands.PackageProcessor.createMinifyConfigs(PackageProcessor.java:378)
	at com.ibm.ws.kernel.boot.internal.commands.PackageProcessor.execute(PackageProcessor.java:235)
	at com.ibm.ws.kernel.boot.internal.commands.PackageCommand.packageServerRuntime(PackageCommand.java:241)
	at com.ibm.ws.kernel.boot.internal.commands.PackageCommand.doPackage(PackageCommand.java:107)
	at com.ibm.ws.kernel.boot.Launcher.handleActions(Launcher.java:275)
	at com.ibm.ws.kernel.boot.Launcher.createPlatform(Launcher.java:119)
	at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:59)
	at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:35)
```

**Comment by aguibert** [comment]
closing out this issue since the fix has been delivered for a while and I have verified it fixes the issue locally

**Comment by gcharters** [comment]
Thanks @aguibert :)
