### ISSUE TITLE
Update Faces 4.1 Tests to use New Schemas once Released

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/open-liberty#27801]
new version of the schema? If not perhaps open an issue so we refresh these once available?

_Originally posted by @pnicolucci in https://github.com/OpenLiberty/open-liberty/pull/27713#discussion_r1507782384_

Schema Location: https://jakarta.ee/xml/ns/jakartaee/

**Comment by pnicolucci** [comment]
@volosied  there are new schemas available now here: https://jakarta.ee/xml/ns/jakartaee/#11 Do we need any changes in MyFaces or Open Liberty?  You should talk with Thomas Bitonti as well to ensure he is aware of the Faces 4.1 schemas.

**Comment by pnicolucci** [comment]
@volosied  I've messaged @tbitonti about schema updates for Servlet 6.1 and Faces 4.1. I've created a test case (trace is necessary to see the error output with the new version), once we have the schemas updated and this test passes we should be able to close this one out!

**Comment by pnicolucci** [comment]
schema issue: https://github.com/OpenLiberty/open-liberty/issues/29070
