### ISSUE TITLE
Jakarta Persistence 3.2 - Update to the API M2 build

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#27846]
Add support for Jakarta Persistence API 3.2 M2 build in Open Liberty for persistence-3.2 and persistenceContainer-3.2.
- [x] EclipseLink implementation will still only support 3.1 level of APIs.
- [x] If a new version of the persistence.xml schema has been published, then provide updates to parse the new schema
- [x] If available, add a new FAT for new persistence.xml

M2 build is documented as published here :
- https://central.sonatype.com/artifact/jakarta.persistence/jakarta.persistence-api/versions

M2 build is published on maven here:
- https://repo1.maven.org/maven2/jakarta/persistence/jakarta.persistence-api/3.2.0-M2/

for #25091

**Comment by Riva-Tholoor-Philip** [comment]
The PR [27895](https://github.com/OpenLiberty/open-liberty/pull/27895) is merged

**Comment by Riva-Tholoor-Philip** [comment]
Both the PRs -- [27895](https://github.com/OpenLiberty/open-liberty/pull/27895) and [27991](https://github.com/OpenLiberty/open-liberty/pull/27991)  are merged. Hence closing the issue.
