### ISSUE TITLE
Feature Test Summary for supporting Java 22 in Open Liberty

### ISSUE THREAD

**Issue by gjwatts** [OpenLiberty/open-liberty#27857]
## Test Strategy

This Feature Test Summary is provided for the epic [Support Java 22 in Open Liberty](https://github.com/OpenLiberty/open-liberty/issues/26461) to add a new Java 22 specific FAT https://github.com/OpenLiberty/open-liberty/pull/27515 and not to introduce any new or modified Open Liberty functionality.

Normally FAT testing is designed to validate the functionality of a new or changed feature in Open Liberty. Since there is no new OL functionality to test, the associated FAT test is a validation check to make sure we are running on Java 22. To accomplish that, this FAT uses a WAR file for testing that has been compiled at Java 22 using functionality that is specific to Java 22.

The main testing to validate Java 22 is done via our entire suite of Open Liberty and WebSphere Liberty FAT buckets.

### List of FAT projects affected

* io.openliberty.java.internal_fat - https://github.com/OpenLiberty/open-liberty/pull/27515

### Test strategy

* What functionality is new or modified by this feature?
  * No new Liberty functionality is added or changed by this feature
* What are the positive and negative tests for that functionality?
  * This FAT adds one simple test to ensure we are running on Java 22 by using functionality that is specific to Java 22 ([Unnamed variables & Patterns](https://openjdk.org/jeps/456))
* What manual tests are there (if any)? None.

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

**Comment by gjwatts** [comment]
Team confidence level landed on a 4.

**Comment by ayoho** [comment]
LGTM 👍
