### ISSUE TITLE
Handling Redundant TX Peer Recovery Leases: Filesystem Case

### ISSUE THREAD

**Issue by neilgsyoung** [OpenLiberty/open-liberty#27911]
Where a Peer Recovery Liberty environment has been configured to store recovery logs in a filesystem, the handling of redundant leases needs to be fixed.

If, for some reason, there is a redundant lease in the lease table, then a peer will attempt to recover the logs for that lease. If the peer cannot find those logs, it will attempt to create them. The behaviour should be that the absence of any logs should be reported and the lease should be deleted.

The behaviour can be readily reproduced by creating a "dummy" stale lease.

**Comment by Amitbh153** [comment]
@neilgsyoung  @jonhawkes  , If you can share any tentative date for fixing. Related issue 27211 is pending from long time.
