### ISSUE TITLE
management security authorization requires a configured user registry 

### ISSUE THREAD

**Issue by chunlongliang-ibm** [OpenLiberty/open-liberty#2793]
Management security authorization always require user registry be configured, and user is in the user registry. In SSO scenario, for example SAML or OIDC or JWT login,  user registry is not required. With current management security limitation, user can not login to managed application with SSO. We have seen those failing scenarios in micro profiles where client can not authenticate to managed API (like health check, metrics) with JWT.

Code analysis shows the main problem is in ManagementSecurityAuthorizationTable.java, which forces each role mapping to retrieve access_id from user registry.  If this table service honor the existing role to access_id mapping like application security, the problem should be resolved

**Comment by chunlongliang-ibm** [comment]
This issue need to be resolved soon, it has blocked many microprofile  samples.

**Comment by utle** [comment]
Fixed with these two PR#
https://github.com/OpenLiberty/open-liberty/pull/3627
https://github.com/OpenLiberty/open-liberty/pull/3672/checks

**Comment by utle** [comment]
Fixed in these PRs
#3672 
#3627

**Comment by radzikp** [comment]
Could you tell me if you release a new versin of this bug in one of the feature ? I am looking at this topic: https://stackoverflow.com/questions/49762236/securing-liberty-microprofile-metrics-endpoint-in-a-mpjwt-environment
