### ISSUE TITLE
BETA BLOG - Jakarta EE11 Servlet 6.1

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#27962]
The information you provide here will be included in the Open Liberty beta blog post ([example](https://openliberty.io/blog/2020/08/05/jakarta-grpc-beta-20009.html)), which will be published on [openliberty.io/blog/](https://www.openliberty.io/blog/), and potentially elsewhere, to promote this beta feature/function of Open Liberty. For this post to be included in the beta issue please make sure that this is completed by the end of Friday following the GM (Tuesday). The beta and release blogs are created using automation and rely on you following the template's structure. **DO NOT REMOVE/ALTER THE `<GHA>` TAGS THROUGHOUT THIS TEMPLATE.**

Please provide the following information:
&#8203;<GHA-BLOG-RELATED-FEATURES>
1. Which Liberty feature(s) does your update relate to? 
    
    Human-readable name (eg WebSockets feature): `Jakarta EE 11 Servlet 6.1`

    Short feature name (eg websockets-1.0):  `servlet-6.1`

    </GHA-BLOG-RELATED-FEATURES>

    <GHA-BLOG-TARGET-PERSONA>
2. Who is the target persona? Who do you expect to use the update? eg application developer, operations.  `Developers of Jakarta Enterprise Edition (EE) applications.`
    </GHA-BLOG-TARGET-PERSONA>
   
    <GHA-BLOG-SUMMARY>
3. Provide a summary of the update, including the following points:
   
   - A sentence or two that introduces the update to someone new to the general technology/concept.

`The Open Liberty servlet-6.1 feature is an implementation of the Jakarta EE 11 Servlet 6.1 Specification. It includes a number of new features, specification clarifications as well as deprecates some existing Servlet features.`

   - What was the problem before and how does your update make their life better? (Why should they care?)

`Prior to Servlet 6.1, there was not a way for an application to control the response data when doing a send redirect, as well as the response status code which always set to 302.  An application could not easily retrieve the initial request's query string or request HTTP method during an error handling dispatch.  It also could not set the character encoding for a request or a response using the java.nio.charset.Charset; the only available option was using a String.  During the read or write of a servlet data, the jakarta.servlet.ServletInputStream or jakarta.servlet.ServletOutputStream only supports a byte array.`

`Servlet 6.1 was updated to provide additional servlet APIs that allow the send redirect to include an optional response data and/or set a compliant status code, instead of the default 302.  Additional request attributes are available during the error handling process to easily retrieve the initial request’s query string or method.  Further more, international application can now set the character encoding using a Charset instead of a String.  The ServletInputStream or ServletOutputStream can use java.nio.ByteBuffer to read or write the data.`

`Several clarifications are added to clarify the behavior of the existing servlet APIs. For example, the getParameter family from the jakar.servlet.ServletRequest is now throwing the runtime java.lang.IllegalStateException when an error occurs during the parsing of the request’s parameters.  While processing an error handling dispatch, the HTTP GET method is always used instead of the original request’s HTTP method.`

   - Briefly explain how to make your update work. Include screenshots, diagrams, and/or code snippets, and provide a `server.xml` snippet.
`<featureManager>
      <feature>servlet-6.1</feature>
   </featureManager>`
   - Where can they find out more about this specific update (eg Open Liberty docs, Javadoc) and/or the wider technology?  
    ` The Jakarta Servlet 6.1 information can be found at https://jakarta.ee/specifications/servlet/6.1/`
    </GHA-BLOG-SUMMARY>

## What happens next?
- Add the label for the beta you're targeting: `target:YY00X-beta`.
- Make sure this blog post is linked back to the Epic for this feature/function.
- Your paragraph will be included in the beta blog post. It might be edited for style and consistency.
- You will be asked to review a draft before publication.
    - Once you've approved the code review, close this issue. 
- If you would _also_ like to write a standalone blog post about your update (highly recommended), raise an issue on the [Open Liberty blogs repo](https://github.com/OpenLiberty/blogs/issues/new/choose). State in the issue that the blog post relates to a specific release so that we can ensure it is published on an appropriate date (it won't be the same day as the beta blog post).

**Comment by pmd1nh** [comment]
`https://github.com/OpenLiberty/blogs/pull/3742` is merged

**Comment by pnicolucci** [comment]
https://github.com/OpenLiberty/blogs/pull/3742
