### ISSUE TITLE
context root is not working when deploying as war in a container

### ISSUE THREAD

**Issue by mehmandarov** [OpenLiberty/open-liberty#27961]
**Describe the bug**  
Setting contextRoot in settings.xml lets you define root, as for example:
```
    <webApplication contextRoot="/" location="${project.name}.war" />
```

This works while building fat jars, but not when deploying as a war in a container.

**Steps to Reproduce**  
1. Create a sample application. Update settings.xml to: `<webApplication contextRoot="/" location="${project.name}.war" />`
2. Set the application path in ApplicationEntryPoint with: `@ApplicationPath("/api")`
3. Build with `mvn clean package` and run the jar using `java -jar target/randomstrings.jar`
4. Verify you have the updated the context root in the logs: `Web application available (default_host): http://localhost:8080/`
5. Verify you have can access: `Web application available (default_host): http://localhost:8080/api`
6. Now, deploy the same app into a container using something similar to a file described here: https://openliberty.io/guides/docker.html#creating-the-dockerfile
7. See if you can access your application: <docker-container-address>:8080/api
8. You should get an error: "Context Root Not Found"
9. Also <docker-container-address>:8080/openapi returns this:
```
---
openapi: 3.0.3
info:
  title: Generated API
  version: "1.0"
servers:
- url: https://<myurl>
paths: {}
```

**Note:** I have changed default port to 8080 in settings.xml:
```
    <httpEndpoint id="defaultHttpEndpoint"
                  httpPort="8080"
                  httpsPort="9443"/>
```

**Expected behavior**  
I should be able to access the same urls as running with `java -jar target/randomstrings.jar`.

**Diagnostic information:**  
 - OpenLiberty Version: 24.0.0.2
 - Affected feature(s): Following features are on -> jakartaee-10.0, microProfile-6.1</feature> 
 - Java Version: OpenJ9 21 -> Docker image `FROM icr.io/appcafe/open-liberty:kernel-slim-java21-openj9-ubi-minimal`
 - server.xml configuration (WITHOUT sensitive information like passwords)

```
<?xml version="1.0" encoding="UTF-8"?>
<server description="${project.name}">

    <featureManager>
        <feature>jakartaee-10.0</feature>
        <feature>microProfile-6.1</feature>
    </featureManager>

    <basicRegistry id="basic" realm="BasicRealm">
        <!--
        <user name="yourUserName" password="" />
        -->
    </basicRegistry>

    <httpEndpoint id="defaultHttpEndpoint"
                  httpPort="8080"
                  httpsPort="9443"/>

    <!-- Automatically expand WAR files and EAR files -->
    <applicationManager autoExpand="true"/>

    <webApplication contextRoot="/" location="${project.name}.war" />

    <!-- Default SSL configuration enables trust for default certificates from the Java runtime -->
    <ssl id="defaultSSLConfig" trustDefaultCerts="true" />

</server>

```

**Additional context**  
I might be missing something here. This behaviour makes no sense to me right now. :-)

**Comment by scottkurz** [comment]
Hi, it might help if you could share a simple recreate, including enough of your **server.xml**, **pom.xml** and **Dockerfile** to illustrate the issue.  I would think it'd be easy to avoid including anything sensitive to do this.

It's a bit confusing because it looks like you pasted the **server.xml** showing a '/' context root

```xml
  <webApplication contextRoot="/" location="${project.name}.war" />
```

though you described the problem as not being able to configure an '/api' context root.  It's also confusing that you mentioned using `@ApplicationPath("/api")`, which makes me wonder if the context root and application path might be getting confused somehow.

At a high level, one mistake in this area that users sometimes make is to deploy their application in a way that doesn't align with the server.xml app configuration, so the context root configured there isn't applied (but rather Open Liberty calculates a default).

**Comment by mehmandarov** [comment]
Thanks for the reply, @scottkurz! Here is a simple demo app that illustrates the issue:

Whole repo: https://github.com/mehmandarov/microprofile-randomstrings/
Specifically:
- Dockerfile: https://github.com/mehmandarov/microprofile-randomstrings/blob/master/src/main/docker/liberty/Dockerfile.jvm
- settings.xml: https://github.com/mehmandarov/microprofile-randomstrings/blob/master/src/main/liberty/config/server.xml
- pom.xml: https://github.com/mehmandarov/microprofile-randomstrings/blob/master/pom-liberty.xml

**Comment by tjwatson** [comment]
Could it be the use of `<webApplication contextRoot="/" location="${project.name}.war" />` in the `server.xml` where in the container it knows nothing about the `project.name` variable?  Could you try setting that to the final WAR name directly?

**Comment by mehmandarov** [comment]
Could be. Let me try that! Thanks!

**Comment by scottkurz** [comment]
Thank you for sharing your project repository.

So, let me just start by focusing on this one point I mentioned in my last comment.  

You have in **server.xml**
```xml
   <webApplication contextRoot="/" location="${project.name}.war" />
```

So why are you expecting to use '/api' as your context root?

**Comment by mehmandarov** [comment]
You were absolutely right, @tjwatson! That was the issue. Changing it to the actual application name fixed the issue. Thanks!

**Comment by scottkurz** [comment]
> You were absolutely right, @tjwatson! That was the issue. Changing it to the actual application name fixed the issue. Thanks!

OK, glad it's working for you.  Though maybe some portion of the problem didn't get captured, it may not matter now.

Since this worked the problem must have been that by copying this in your docker build:

```
COPY --chown=1001:0 --from=maven /liberty/src/main/liberty/config /config
RUN features.sh

COPY --chown=1001:0 --from=maven /liberty/target/*.war /config/apps
RUN configure.sh
```

you were not copying the bootstrap.properties which was generated during deployment by liberty-maven-plugin (at path **target/liberty/wlp/usr/servers/randomstrings/bootstrap.properties**) in your build.

Rougly speaking, you'd have to copy both "source" config and plugin-generated config to have the full configuration in your Docker container image.

**Comment by mehmandarov** [comment]
Thanks for your reply, @scottkurz! No, I dit not expect it to be the context root, but I did expect it to be accessible since it is defined [here](https://github.com/mehmandarov/microprofile-randomstrings/blob/81d727b9c59ee5f1105030d63ceec7d29062e5d0/src/main/java/com/mehmandarov/randomstrings/RandomStringsController.java#L16). The issue was that I was using `${project.name}` in the `location` and that resulted in `Context Root Not Found` error.

**Comment by mehmandarov** [comment]
> you were not copying the bootstrap.properties which was generated during deployment by liberty-maven-plugin (at path **target/liberty/wlp/usr/servers/randomstrings/bootstrap.properties**) in your build.

Oh, that's a good point, @scottkurz. Let me try that out too a little bit later today. 

In that case, may I suggest a change to the Dockerfile sample in the tutorial here: https://openliberty.io/guides/docker.html#creating-the-dockerfile? I will be happy to submit a pull request if it is an open repo.

**Comment by mehmandarov** [comment]
On a slightly unrelated matter: I have also noticed a different behaviour for jar vs war deploys:

* For jar deploys, like `java -jar target/randomstrings.jar` my root app folder is set to `webapp` folder and `index.html`
* For war deploy on Cloud Run, I am redirected to a standard OpenLiberty landing page.

Could that be something with `bootstrap.properties` as well?  I will investigate and get back to you. Thanks again!

**Comment by scottkurz** [comment]
> In that case, may I suggest a change to the Dockerfile sample in the tutorial here: https://openliberty.io/guides/docker.html#creating-the-dockerfile? I will be happy to submit a pull request if it is an open repo.

Appreciate your point, we could use some more examples.  Not sure that's the best place to address this but thanks for the suggestion.  I will pass it along.
