### ISSUE TITLE
Error 500 using sessionCache-1.0 with a Hazelcast cluster on failover

### ISSUE THREAD

**Issue by dacleyra** [OpenLiberty/open-liberty#2798]
Using sessionCache-1.0 with a Hazelcast cluster for the provider.

When a single Hazelcast cluster member is killed, the appserver produces an Error 500

Error 500: com.hazelcast.spi.exception.TargetDisconnectedException: Exception in ClientConnection{alive=true, connectionId=2, channel=NioChannel{/10.1.71.133:40654-&gt;/10.1.2.75:5701}, remoteEndpoint=[10.1.2.75]:5701, lastReadTime=2018-03-22 15:19:14.721, lastWriteTime=2018-03-22 15:19:14.718, closedTime=never, lastHeartbeatRequested=2018-03-22 13:34:38.772, lastHeartbeatReceived=2018-03-22 13:34:38.772, connected server version=3.9.3}, thread=hz.file:/opt/ibm/wlp/usr/shared/config//hazelcast/hazelcast-client.xml.IO.thread-in-0

**Comment by dacleyra** [comment]
[messages.log](https://github.com/OpenLiberty/open-liberty/files/1838429/messages.log)

**Comment by alexsm82** [comment]
Hi @dacleyra.  That error seems to be coming entirely out of Hazelcast.  If you can give me a little more detail about this test I can talk with the Hazelcast developers about whether this is expected behavior and if there is any configuration options that could work around this.  The main question I have is how you are killing the the Hazelcast cluster member?

**Comment by dacleyra** [comment]
The environment is deployed in IBM Cloud Private.
A Hazelcast cluster member is killed by running `kubectl delete pod podname`
I have run this same test with hazelcast's session filter, hazelcast-wm, and can't recall seeing a 500 surface from the appserver as a result of a cluster member being killed.

The test artifacts I'm using for this test are here
https://github.ibm.com/dacleyra/microwebapp-249348

The test artifacts for the hazelcast-wm test are here
https://github.ibm.com/dacleyra/microwebapp-hz

**Comment by alexsm82** [comment]
Hey @dacleyra, can you try testing with Hazelcast retry enabled: http://docs.hazelcast.org/docs/3.9.2/manual/html-single/index.html#enabling-redo-operation?  I'm not positive that is necessarily what the final solution to this issue will be, but I wanted to see if it at least resolved the issue.

**Comment by dacleyra** [comment]
retry-enabled appears to prevent any 500s from occurring.

That said, I believe it a problem that the 500 is exposing that much backend information to the client

**Comment by alexsm82** [comment]
Thanks for testing that.  I'm still going to look into whether we should maybe doing some retry on the Liberty side/at least catching the exception, but wanted to see what the behavior was with Hazelcast retry enabled.

**Comment by alexsm82** [comment]
We're still discussing exactly what behavior we want to have, but we do agree that the current 500 message is exposing to much information.
