### ISSUE TITLE
Pages 4.0: Pull in final 4.0 API

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#28034]
https://repo1.maven.org/maven2/jakarta/servlet/jsp/jakarta.servlet.jsp-api/4.0.0/

**Comment by CassTucker** [comment]
@pnicolucci thanks for the heads up, is this going in ol 24.0.0.7? I ask because I looked in Mend  open-liberty-latest and I'm not seeing it.  It could just be a timing issue.

**Comment by pnicolucci** [comment]
> @pnicolucci thanks for the heads up, is this going in ol 24.0.0.7? I ask because I looked in Mend open-liberty-latest and I'm not seeing it. It could just be a timing issue.

@CassTucker the pages-4.0 feature is currently in beta and will remain that way for some time. It was just merged a few hours ago so depending on what the tooling is looking at it could take a day or two to get to the release branch if that's what you're looking at.
