### ISSUE TITLE
Server Won't Start with Space in File Path

### ISSUE THREAD

**Issue by rsherget** [OpenLiberty/open-liberty#28083]
**Describe the bug**  
If there is a space in the file path of a server's log directory, there will be an error with the verbose garbage collection option that will keep the server from starting. Trying to start the server via a terminal gives the message `Server defaultServer start failed. Check server logs for details.`

Console.log contains:
```
JVMJ9VM007E Command-line option unrecognised: Files\IBM\WebSphere\Liberty\usr\servers\defaultServer\logs\verbosegc.%seq.log,10,1024
```

The full file path for the verbosegc option in this case was `C:\\Program Files\IBM\WebSphere\Liberty\usr\servers\defaultServer\logs\verbosegc.%seq.log,10,1024`. The space in `Program Files` causes the option to get split and then causes an error.

**Steps to Reproduce**  
With Open Liberty version 24.0.0.3, add a space to a directory in the file path of the server's log directory.

**Expected behavior**  
The server should start as normal, regardless of there being a space within the file path.

**Diagnostic information:**  
 - OpenLiberty Version: 24.0.0.3
 - Affected feature(s) N/A
 - Java Version: IBM Java
 - server.xml configuration N/A

**Additional Context**
A workaround is to either specify some verbosegc configuration via jvm.options or the command line, or to add `VERBOSEGC=false` to the server.env of a server.

**Comment by yafred** [comment]
_A workaround is to either specify some verbosegc configuration via jvm.options_

What should I write in jvm.options ?
