### ISSUE TITLE
FeatureUtility custom repository connection issue

### ISSUE THREAD

**Issue by jjiwooLim** [OpenLiberty/open-liberty#28152]
**Describe the bug**  
In some scenarios, FeatureUtility connection test to custom repo (base url) returns response code 400 and fails to recognize it as working repository. It's not good to fail fast because there are cases where users do not have appropriate access to the whole repository, but they have access to certain artifacts in the repository. In this case response code can return 400, 403, etc. 

**Diagnostic information:**  
 - OpenLiberty Version: 24.0.0.3

**Comment by bmarwell** [comment]
@jjiwooLim please add diagnostic output (especially the response  body!!) to the featureUtility! Thanks!

**Comment by jjiwooLim** [comment]
@bmarwell thanks for the input. We will create a separate issue for this.

**Comment by bmarwell** [comment]
> @bmarwell thanks for the input. We will create a separate issue for this.

I actually found it: https://github.com/OpenLiberty/open-liberty/issues/25990

HTH
