### ISSUE TITLE
[JPA 3.0] EclipseLink: Deliver Oracle 23 support

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#28155]
[Update JPA 3.0 to support Oracle 23](https://github.com/eclipse-ee4j/eclipselink/issues/2109)

This is a backport of EclipseLink

- [[master] Oracle 23 platform](https://github.com/eclipse-ee4j/eclipselink/pull/1876)
- [[4.0] Oracle 23 platform - backport from master](https://github.com/eclipse-ee4j/eclipselink/pull/1889)

And similar to this backport back to 2.7

- [[2.7] Oracle 23C platform - backport from master](https://github.com/eclipse-ee4j/eclipselink/pull/2000)

Provide an overlay of these changes to io.openliberty.persistence.3.0.thirdparty.

**Comment by covener** [comment]
FYI not fully linked to the merged PR so still open.  If the release-bug is resolved, please close.

**Comment by tkburroughs** [comment]
Just verified that the test is now passing with Oracle 23; issue is complete.
