### ISSUE TITLE
InstantOn support for Jakarta Messaging Feature Test Summary

### ISSUE THREAD

**Issue by dazavala** [OpenLiberty/open-liberty#28272]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

New checkpoint tests have been introduced into the Liberty continuous delivery pipeline to verify the {[Jakarta Messaging](https://openliberty.io/docs/latest/reference/feature/messaging-3.1.html), [Jakarta Connectors](https://openliberty.io/docs/latest/reference/feature/connectors-2.1.html), [Jakarta Enterprise Beans Message-Drive Beans](https://openliberty.io/docs/latest/reference/feature/mdb-4.0.html)} features function as designed over server checkpoint/restore at phases {`beforeAppStart`, `afterAppStart`} for applications that may use the Jakarta Connectors or Messaging APIs to access external resources, require a Connectors resource adapter to enable connections to external resources, and deliver messages to Message-Driven Bean endpoints.

In addition to verifying feature function over the EE 8..10 platforms, these checkpoint tests verify restored servers dynamically update the Connectors and Messaging feature configurations to access external resources provided by any environment in which a server is restored from checkpoint.

### List of FAT projects affected

* io.openliberty.ejbcontainer.mdb.checkpoint_fat provided by [Enable MDB features and EjbCtnr MDB RA FAT for InstantOn](https://github.com/OpenLiberty/open-liberty/pull/27224)
* com.ibm.ws.messaging.jms20.wmq_fat_java7 provided by [Verify Messaging features support MQ client function for InstantOn](https://github.ibm.com/websphere/WS-CD-Open/pull/31450)

### Test strategy

* What functionality is new or modified by this feature?

   * The Messaging, Connectors, and MDB features are enabled for server checkpoint.
   * The Connectors feature runtime required modification to 1) install resource adapters during server checkpoint, and to 2) prohibit timer creation and work submissions (scheduling) during application startup within a checkpoint request.

* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)

   * FAT project `io.openliberty.ejbcontainer.mdb.checkpoint_fat` provides two test classes: `MsgCheckpointTest` verifies POJO and MDB message endpoint behaviors, including timed operations, transactional delivery (ContainerManagedTrans), and non-transactional delivery (BeanManagedTrans); this is a bringup test that exercises both Connectors and Messaging message endpoint deployments along with a test resource adapter to simulate inbound and outbound connection to an external resource.  `ConfigChangeTest` verifies message endpoint activation defers until server startup (i.e. inbound work does not start until the server is started during restore) over all endpoint AutoStart configurations. The test also verifies dynamic updates to resource authentication data referenced by Connectors and Messaging configurations apply at restore, before message endpoints are activated, enabling connectivity to external resources provided in different server environments. Note that authData referenced by activationSpec and jmsActivationSpec are the only configuration attributes that require dynamic update verification.

   * FAT project `com.ibm.ws.jca_fat_derbyra` provides two test classes: `DerbyRACheckpointLimitationsTest` verifies usage limitations for resource adapters (RAs) introduced by InstantOn support. These tests ensure the RA prohibits timer creation and work submissions (scheduling) during application startup within a checkpoint request, and that Connectors support functions as expected when a checkpoint is taken before application startup. Also, these tests verify RA lifecycle events within checkpoints taken before and after application startup.  `DerbyRACheckpointTest` verifies multiple Connectors behaviors over a test RA that accesses a Derby database (resource) within checkpoint-restore, including RA timer creation, RA work management (work submission), connection management, message delivery to MDBs, container managed authentication, XA recovery, RA java beans and annotations, resource injection, dynamic config of connection auth data at restore, and all configuration types (resourceAdapter, connectionManager, connectionFactory, activationSpec, adminObject). 

   * FAT project `com.ibm.ws.messaging.jms20.wmq_fat_java7` provides test class `MQCheckpointFATTest`, which verifies a Jakarta Messaging, Connectors and MDB feature function for Messaging applications that use external Messaging resources -- specifically, IBM MQ -- via a Connectors resource adapter.  Checkpoint scenarios exercise MQ server host and port updates (i.e. resource connectivity configuration updates) at restore. Outbound resource connectivity is verified over both the Connectors and Messaging configuration types (e.g. connectionFactory, jmsConnectionFactory, jmsQueueConnectionFactory, jmsTopicConnectionFactory, jmsQueue, jmsTopic); and Inbound resource connectivity is verified over the Messaging endpoint configuration types (jmsActivationSpec, adminObject, authData). This test also exercises support for Connectors MetaData annotations and Connectors+Messaging resource injection. 

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

   * There are no manual tests.

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

   * Vote: 4 - We've tested all golden paths crucial to InstantOn support for the Jakarta Messaging, Connectors and MDB features. InstantOn testing does not cover all feature function, so I cannot vote 5 as there's always a slight risk of an outlying use-case that fails InstantOn.  

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by dave-waddling** [comment]
Hi @dazavala, thanks for completing this FTS! Regarding your confidence level of 3, please can you give me a brief assessment of risk/justification for not adding further testing - I'm just looking to understand a little more. Otherwise, all looks good.

**Comment by dazavala** [comment]
FYI @dave-waddling: **We bumped the #26039 GA target to 24006.** The 3 confidence rating was my own assessment based on coverage concerns for Jakarta Connectors (*) feature function. NathanR, TomW and I discussed these concerns and determined we will deliver a couple functional restrictions and additional test coverage before GA. Going forward you'll see FTS updates w.r.t. new Connectors FAT coverage before I request another approval review.

(*) Jakarta Connectors was formerly known as "JCA", which you will see in FAT artifact names. Similar to Jakarta Messaging and "JMS".

**Comment by dave-waddling** [comment]
Hi @dazavala, many thanks for the update - I'll keep this feature on our radar for 24.0.0.6. When the FTS is ready for re-review, please can I ask that your team revisits the confidence level (for the entire feature).

**Comment by dazavala** [comment]
@ayoho Can you handle this approval for @dave-waddling while he's away?  Since last talking with Dave, I posted the [new test coverage for the Connectors feature](https://github.com/OpenLiberty/open-liberty/pull/28485) and revised the confidence level to 4 w/ explanation.

**Comment by ayoho** [comment]
LGTM 👍
