### ISSUE TITLE
If an application fails to start when doing a checkpoint the checkpoint still succeeds

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#28280]
**Describe the bug**  
If an application fails to start while doing a checkpoint `afterAppStart` the the checkpoint is still allowed to succeed and we are left with a application process checkpoint that will restore always with a failed application start.  It would be better to fail the checkpoint in this case so that container image builds can reliably fail to build if the application fails to start when we are doing a container image build with InstantOn

**Steps to Reproduce**  
Configure any application that fails to start and do a checkpoint with `afterAppStart`

**Expected behavior**

**Comment by covener** [comment]
@anjumfatima90 I'm not sure why this didn't close automatically, maybe the association to the PR happened after the merge. Do you know if this issue is really resolved by #28297 and 28297 is not reverted? Can you close if confident?

**Comment by anjumfatima90** [comment]
I think we can safely close this.
