### ISSUE TITLE
UUIDs fail with EclipseLink and Postgres

### ISSUE THREAD

**Issue by mswatosh** [OpenLiberty/open-liberty#28368]
When creating a query with a UUID, the parameter is set as a VARCHAR instead of a UUID, and is rejected by Postgres. 

Here is an example of the failing query:
```java
UUID uuid = p1.id;
List<?> result = em.createQuery("SELECT p FROM PurchaseOrder p WHERE p.id=?1")
                   .setParameter(1, uuid).getResultList();
```

There is some discussion on how to convert to a UUID in postgres here:
https://stackoverflow.com/questions/12771737/conversion-string-to-uuid-in-postgres-and-java/34652560#34652560

There is a recreate here (see the `/uuid` endpoint):
https://github.com/mswatosh/persistence-recreates

**Comment by Riva-Tholoor-Philip** [comment]
See EclipseLink Issue : [2190](https://github.com/eclipse-ee4j/eclipselink/issues/2190)
