### ISSUE TITLE
EclipseLink not returning jakarta.persistence.EntityExistsException with Postgres

### ISSUE THREAD

**Issue by mswatosh** [OpenLiberty/open-liberty#28380]
When inserting two Entities with the same Id using Postgres, EclipseLink returns a `jakarta.persistence.PersistenceException` instead of a`jakarta.persistence.EntityExistsException` 

There is a recreate here (see the `/entityExists` endpoint):
https://github.com/mswatosh/persistence-recreates

**Comment by njr-11** [comment]
Closing as duplicate of #28737
