### ISSUE TITLE
Feature Test Summary: Audit-2.0

### ISSUE THREAD

**Issue by wrodrig** [OpenLiberty/open-liberty#28396]
## Test Strategy for #27475

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

New test cases have been introduced into Liberty Continous delivery pipeline to verify the [audit-2.0](https://github.com/OpenLiberty/open-liberty/issues/27475) feature. Additionally some existing cases that use audit-1.0 have been updated to re-run using the audit-2.0 feature.

### List of FAT projects affected

* com.ibm.ws.ejbcontainer.security.jacc_fat.2.1
*com.ibm.ws.ejbcontainer.security.jacc_fat
* com.ibm.ws.logstash.collector_fat
* com.ibm.ws.rest.handler.config_fat
* com.ibm.ws.security.jaspic_fat
* com.ibm.ws.webcontainer.security.jacc.1.5_fat
* io.openliberty.checkpoint_fat
* io.openliberty.jakartaee9.internal_fat
* io.openliberty.jakartaee10.internal_fat
* io.openliberty.jakartaee11.internal_fat
* com.ibm.ws.security.wim.audit_fat

### Test strategy

* What functionality is new or modified by this feature?
  * When `audit-2.0` is enabled, the Rest API is not invoked.  
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
  * In the FAT project  `com.ibm.ws.rest.handler.config_fat` test were added to make sure that when `audit-2.0` is used, the Rest API is not invoked. It also included a test where the `audit-2.0` and `restConnector-2.0` were used to make sure that the RestHandlerEvents are still invoked. 
  * FAT projects that have test cases for audit-1.0: `com.ibm.ws.ejbcontainer.security.jacc_fat.2.1`, `com.ibm.ws.ejbcontainer.security.jacc_fat`, `com.ibm.ws.logstash.collector_fat`, `com.ibm.ws.security.jaspic_fat`,`com.ibm.ws.webcontainer.security.jacc.1.5_fat`, 
  `io.openliberty.checkpoint_fat`, `io.openliberty.jakartaee9.internal_fat`, `io.openliberty.jakartaee10.internal_fat`, `io.openliberty.jakartaee11.internal_fat`,`com.ibm.ws.security.wim.audit_fat` were updated to re-run those test cases with the `audit-2.0` feature. 

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)
  * There are no manual test cases.

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

 * **Vote 4** we have a very similar test coverage as the existing audit-1.0 feature as well as specific test cases for audit-2.0. Additional test cases to cover MemberManagement Events can be considered in the future. 

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by ayoho** [comment]
LGTM 👍
