### ISSUE TITLE
Feature Test Summary

### ISSUE THREAD

**Issue by tonyreigns** [OpenLiberty/open-liberty#28422]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

The upcoming MicroProfile Metrics 3.0/4.0 feature updates are backported changes from MicroProfile Metrics 5.1, which includes new MicroProfile Config properties used for configuring the statistics that are tracked and outputted by the Histogram and Timer metrics.

The new properties introduced in MicroProfile Metrics 3.0/4.0 will allow users to define a custom set of percentiles as well as custom set of histogram buckets for the Histogram and Timer metrics. There are also additional configuration properties for enabling a default set of histogram buckets including properties for defining and upper and lower bound for the bucket set.

The TCK and optional FATs were ported over from 5.1 to 3.0 and 4.0. 4.0 is the Jakartafied version of 3.0. The majority of this Feature Test summary was taken from the 5.1 issue: https://github.com/OpenLiberty/open-liberty/issues/26520

### io.openliberty.microprofile.metrics.internal.3.0_fat

The `io.openliberty.microprofile.metrics.internal.3.0_fat` runs the MicroProfile Metrics 5.1 TCK test suite but was altered to support Metrics 3.0 and 4.0.
The TCK was developed/updated along with API and specification changes to the MicroProfile Metrics 5.1 specification.

The changes to the MP Metrics 3.0/4.0 specification brings in new MP config values that allow for the configuration of how the _Histogram_ and _Timer_ metric behave in terms of the data it records and reports (in the Prometheus formatted output on the `/metrics` REST endpoint). These configurations include customizing the set of percentiles that both metrics can track and report, 
 and customizing the histogram buckets that both metrics can track and report. The TCK had been updated to include tests that tests the configuration in the `API` and `REST` modules. The former tests that the percentiles and buckets retrieved as configured. The latter testing the output in `/metrics` and verifies it is as expected. For the API tests, there are configurations/tests for a valid configuration, invalid configurations and configurations with both valid and invalid configurations. For the REST test, we test mainly valid configurations and concentrate on the validity/adherence of the expected Prometheus format. There is a mix of injected metrics and programmatically created metrics. Tests also tested against the use of a wild card  (i.e. *) in the configuration, which is supported.
 
### io.openliberty.microprofile.metrics.internal.3.0_fat

The same FAT bucket includes optional tests taken from `io.openliberty.microprofile.metrics.internal.5.1_fat`
This FAT bucket includes new tests that test some optional MP Config configurations that were not included in the TCK. These configurations enable default histogram-buckets for the _Timer_ and _Histogram_ metrics as well as setting a max and min value on those buckets. Tests include a valid configurations, invalid configurations and configurations with both valid and invalid values. The test tests that the output on `/metrics` is as expected. Tests also tested against the use of a wild card  (i.e. *) in the configuration, which is supported.

### List of FAT projects affected

- io.openliberty.microprofile.metrics.internal.3.0_fat  **(new)**

### Test strategy

* What functionality is new or modified by this feature?
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

4

**Comment by ayoho** [comment]
@tonyreigns The information in here is very helpful, thank you. When you mention there are tests for "valid configuration, invalid configurations and configurations with both valid and invalid configurations", can you provide some examples of those tests? Having to write out some of the specifics sometimes points out holes or combinations that were missed in testing.

**Comment by tonyreigns** [comment]
Hi @ayoho ,this [entire FAT bucket](https://github.com/openliberty/open-liberty/tree/integration/dev/io.openliberty.microprofile.metrics.internal.3.0_fat) is made up of all the new tests.

Invalid configurations: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.microprofile.metrics.internal.3.0_fat/fat/src/io/openliberty/microprofile/metrics/internal/fat/BadHistogramTimerConfigTest.java

This class has several tests with invalid configuration inputs that a user can enter and ensures that no unexpected buckets are created. For example, checkBadHistogramBuckets() passes through a mix of valid and invalid values, and the invalid config is filtered out along with a warning thrown. 
The input for this test was: 
`mp.metrics.distribution.percentiles=badHistogramPercentiles=0.1,adf,fd.ks,0.3,%0.4,()*&$(,0.4,/0.1;badTimerPercentiles=()sdf,0.34fdsf,0.1,(//2,f0.3,33,1.1,><`

Only integer/decimals are valid for Histograms.

The other tests in this class are the same.


In this class: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.microprofile.metrics.internal.3.0_fat/fat/src/io/openliberty/microprofile/metrics/internal/fat/HistogramConfigFieldTest.java

Valid configuration is used and tested to confirm successful bucket creation. For example, checkHistogramCustomBucketsCustomPercentiles() tests to make sure both custom buckets and custom percentiles are configured correctly.

Each of the 4 classes [found here](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.microprofile.metrics.internal.3.0_fat/fat/src/io/openliberty/microprofile/metrics/internal/fat) have several either testing combinations of invalid configuration(BadHistogramTimerConfigTest), valid configuration(HistogramConfigFieldTest and TimerConfigFieldTest), and testing the default histogram bucket configuration(DefaultHistogramBucketsTest)

**Comment by ayoho** [comment]
Thank you! Coverage sounds fine to me 👍
