### ISSUE TITLE
Feature Test Summary:Instant on testing for sessionCache

### ISSUE THREAD

**Issue by anjumfatima90** [OpenLiberty/open-liberty#28448]
This the test summary for Open Liberty InstantOn Epic #26845

The FAT tests are testing Instant On support for the feature sessionCache-1.0. For buckets that require a fully supported CRIU host environment we need an annotation called componenttest.annotation.CheckpointTest. Tests with this annotation will be skipped if the host environment does not have the necessary prerequisites to support Open Liberty InstantOn.

### List of FAT projects affected
* io.openliberty.checkpoint_fat_session_cache_infinispan
* io.openliberty.checkpoint_fat_session_cache_infinispan_container

### Test strategy

* What functionality is new or modified by this feature?
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

 confidence level - 4.0
> The FATs attempt to cover as much as possible such that we can release the initial support for InstantOn for sessionCache-1.0 feature.

**Comment by anjumfatima90** [comment]
**General test behavior**

The tests encompasses testing checkpoint/restore for the sessionCache application. The tests mainly focus on testing AFTER_APP_START phase of checkpoint.

The positive tests aim is to verify the successful completion of each step (checkpoint/restore) as expected. This involves ensuring that the expected page, response, response status and session data are received.

The tests are repeated to test EE8, EE9 and EE10 features with jcache provider specified using `libraryRef` and `cacheManagerRef`.

List of FAT projects affected:
**1. io.openliberty.checkpoint_fat_session_cache_infinispan:**
Features tested: sessionCache-1.0

All the following tests verifies that the appropriate response page and session data can be accessed when the server performs checkpoint/restore for `peer to peer` distributed session caching.

**CheckpointSessionCacheOneServerTest:**
The tests involves submitting concurrent requests to manage session attributes, ensuring correct addition, replacement, and existence of attributes, and verifying session creation and last accessed times. It includes testing concurrent operations for adding, getting, and removing attributes, and ensuring HttpSessionListener events are triggered correctly. Additionally, it verifies that various object types can be stored, serialized when the session is evicted from memory, and deserialized upon session access, maintaining data integrity across different operations and states of the session lifecycle.

**CheckpointSessionCacheTwoServerTest:**
The tests ensure that various types of objects can be stored in a session, serialized when the session is evicted from memory, and deserialized when the session is accessed again. They test that calling session.invalidate() on one server will propagate the invalidation to the other server. Verifies httpSessionCache's writeContents configuration. Confirms that a SessionScoped CDI bean preserves its state across session calls. Also ensures that calling setMaxInactiveInterval(int interval) on a session overrides the invalidation time configured in server.xml for that session. Finally, tests the lifecycle of the session cache by putting data into a server, shutting down that server, and verifying the data fails over to the other server.

**CheckpointSessionCacheTwoServerTimeoutTest:**
The tests verifies that a session created on one server is not accessible on another server after it is invalidated on the first server, and ensures that a session invalidated during a servlet call on a second server is inaccessible if not cached locally, but accessible if cached locally. Also ensures that a session created on Server A is removed from the session cache once it times out on Server B, even if locally cached, and that after a session is invalidated, it is removed from both caches.

**CheckpointSessionCacheConfigUpdateTest:**
The tests verifies a warning message `SESN0312W` is logged when the attributes values of writeContents, writeFrequency, writeInterval, scheduleInvalidationFirstHour, scheduleInvalidationSecondHour are changed after the server is checkpointed before doing the restore stating that the new value will not be used on restore.


**2. io.openliberty.checkpoint_fat_session_cache_infinispan_container**
Features tested: sessionCache-1.0

All the following tests verifies that the appropriate response page and session data can be accessed when the server performs checkpoint/restore for `client-server` distributed session caching.

**CheckpointSessionCacheOneServerTest :**
The tests involves submitting concurrent requests to manage session attributes, ensuring correct addition, replacement, and existence of attributes, and verifying session creation and last accessed times. It includes testing concurrent operations for adding, getting, and removing attributes, and ensuring HttpSessionListener events are triggered correctly. Additionally, it verifies that various object types can be stored, serialized when the session is evicted from memory, and deserialized upon session access, maintaining data integrity across different operations and states of the session lifecycle.

**CheckpointSessionCacheTwoServerTest:** 
The tests ensure that various types of objects can be stored in a session, serialized when the session is evicted from memory, and deserialized when the session is accessed again. They test that calling session.invalidate() on one server will propagate the invalidation to the other server. Verifies httpSessionCache's writeContents configuration. Confirms that a SessionScoped CDI bean preserves its state across session calls. Also ensures that calling setMaxInactiveInterval(int interval) on a session overrides the invalidation time configured in server.xml for that session. Finally, tests the lifecycle of the session cache by putting data into a server, shutting down that server, and verifying the data fails over to the other server.

**CheckpointSessionCacheTwoServerTimeoutTest:**
The tests verifies that a session created on one server is not accessible on another server after it is invalidated on the first server, and ensures that a session invalidated during a servlet call on a second server is inaccessible if not cached locally, but accessible if cached locally. Also ensures that a session created on Server A is removed from the session cache once it times out on Server B, even if locally cached, and that after a session is invalidated, it is removed from both caches.

**Comment by dave-waddling** [comment]
Hi @anjumfatima90, thanks for completing this FTS, it's very comprehensive and the test coverage and scenarios seem sufficient.
