### ISSUE TITLE
Sort out MP 7.0 repeats

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#28464]
Update `MicroProfileActions`
- Ensure the MP70 FeatureSet is correct
  - Should have at least `mpFaultTolerance-4.1` and `mpTelemetry-2.0` updated, check for any others
- Add `MP70` to the "ALL" list

Update `EE*CompatibilityTest`
- These tests currently ignore `mpFaultTolerance-4.1` and `mpTelemetry-2.0` because they weren't listed in an MP `FeatureSet`. We should be able to remove those exceptions.

**Comment by Yas-Franco** [comment]
Most of this work is done now. We still need to update these: 

https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.jakartaee9.internal_fat/fat/src/io/openliberty/jakartaee9/internal/tests/EE9Features.java#L297
