### ISSUE TITLE
Update Fault Tolerance 4.1 feature file

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#28463]
The Fault Tolerance 4.1 feature file needs to depend on the correct versions of other features. We noted when reviewing #28188 that it didn't, but wanted to get that PR merged in.

**Comment by Azquelt** [comment]
@tevans78 also recommended that the autofeature name be changed to ` io.openliberty.mpFaultTolerance4.1-mpTelemetry2.0`

**Comment by Yas-Franco** [comment]
The feature file has been changed already: 
https://github.com/benjamin-confino/open-liberty/blob/integration/dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpFaultTolerance4.1-mpTelemetry2.0.feature

**Comment by Yas-Franco** [comment]
These are up to date with the latest feature versions now: 

https://github.com/benjamin-confino/open-liberty/blob/integration/dev/com.ibm.websphere.appserver.features/visibility/public/mpFaultTolerance-4.1/io.openliberty.mpFaultTolerance-4.1.feature#L11-L14
