### ISSUE TITLE
Feature Test Summary - SpringBoot 3.0: InstantOn support - Epic #25594

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#28466]
## Test Strategy

This the test summary for Open Liberty SpringBoot 3.0: InstantOn support - Epic #25594

The test strategy involves running FAT on test machines that are enabled for InstantOn (checkpoint) testing.  Both SOE and the orchestrater builds invoked by PR `#build` run the `checkpoint` test buckets on machines/environments that support Liberty InstantOn.  We also still maintain a continuous `InstantOn` build that runs daily using the Open Liberty `integration` branch with the `checkpoint` tests running in FULL mode.  The `checkpoint` tests are run across Java 11, 17 and 21 in the continuous `InstantOn` build as well as in SOE runs.  The InstantOn `checkpoint` FAT tests are identified using the `@CheckpointTest` annotation.  This ensures the test is only executed on host systems that support `checkpoint` (i.e. Linux systems with the right kernel version and `criu` installed and running OpenJ9).

Epic #25594 has two main parts that need testing:

1. The `crac-1.4` feature.  This feature adds the `org.crac` API which applications may use to hook into the Liberty InstantOn checkpoint/restore process.
2. Enabling `springBoot-3.0` to work with Liberty InstantOn.  Spring Boot 3 now offers support for checkpoint/restore by hooking into the process using the `org.crac` package.  Older Spring Boot feature versions did not get enhanced to support Liberty InstantOn because only Spring Boot 3 added support to hook into `org.crac`.

### List of FAT projects affected

For InstantOn a strategy was taken to develop new FAT buckets instead of enhancing existing buckets. This was to make it easier to reason about the FATs that require full `checkpoint` supporting hosts. The following buckets are the current set that require full `checkpoint` supporting hosts:

* io.openliberty.checkpoint_fat_springboot
* io.openliberty.checkpoint_fat_springboot_data
* io.openliberty.checkpoint_fat_crac

### Test strategy

* What functionality is new or modified by this feature?

The `springBoot-3.0` feature has been enabled for Liberty InstantOn by adding the `WLP-InstantOn-Enabled: true` feature manifest header.  This allows the feature to be enabled when doing a Liberty InstantOn `checkpoint` action.  Without this the `checkpoint` action would fail when the `springBoot-3.0` feature is enabled.

A new feature `crac-1.4` is introduced that supports Liberty InstantOn.  This feature offers the `org.crac` APIs at version 1.4 as `stable` APIs for applications to use.  The `org.crac` package allows applications to hook into the checkpoint/restore process.  The Spring Framework 6 and Spring Boot 3 projects both use `org.crac` too manage spring components when doing a checkpoint and restore.  The Liberty implementation of `org.crac` is implemented on top of the Liberty InstantOn functionality.  With the `crac-1.4` feature a Spring based application is able to hook into Liberty InstantOn checkpoint/restore process and take full advantage of the rapid startup Liberty InstantOn offers.

* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)

### CRaC Tests
1. Register a list of CRaC resource hooks that should get notifications when a checkpoint and restore happens.
    1. Verify the list of resource hooks are notified of a `checkpoint` action and that the order the resource hooks are notified of a checkpoint is the reverse order they are registered with the `org.crac` APIs
    1. Verify the list of resource hooks are notified when the checkpointed process is restored and that the order the resource hooks are notified of the restore is the order they are registered with the `org.crac` APIs (note that this is opposite the order resources are notified during the `checkpoint` action.
    1. After restore, verify the application endpoints are functional
1. Perform a `checkpoint` action with `afterAppStart` on a server configuration with multiple applications that register multiple CRaC resource hooks.
    1. Verify the expected order of the application hook notifications for both applications on checkpoint and restore.
    1. After restore verify both applications endpoints are functional
1. Perform a `checkpoint` action with an application that uses the new `org.crac.management.CRaCMXBean`
    1. Verify the `getRestoreTime` and `getUptimeSinceRestore` are both `-1` before the checkpoint
    1. Verify the both `getRestoreTime` and `getUptimeSinceRestore` are > `0`
    1. Verify `getRestoreTime` is < current time
    1. Verify `getUptimeSinceRestore` < (currentTime - `getRestoreTime`)
    1. Verify `getRestoreTime` remains constant after the process has been restored
    1. Verify `getUptimeSinceRestore` increases as time goes by after the process has been restored

### Spring Boot Tests
1. Basic test using a Spring Boot 3.2 application that uses the `spring-boot-starter-web` dependency.
    1. Verify a checkpoint is successful with `springBoot-3.0` feature enabled and application configured
    1. Verify restoring the checkpointed application process succeeds
    1. Verify the basic endpoints of the web test application are functional after restore
    1. Verify the Spring Framework lifecycle bean management reacts properly to the checkpoint/restore notifications
1. Basic test using a Spring Boot 3.2 application that uses the `spring-boot-starter-webflux` dependency.
    1. Verify a checkpoint is successful with `springBoot-3.0` feature enabled and application configured
    1. Verify restoring the checkpointed application process succeeds
    1. Verify the basic endpoints of the webflux test application are functional after restore
    1. Verify the Spring Framework lifecycle bean management reacts properly to the checkpoint/restore notifications
1. Spring Boot Data tests deployed as a `<springBootApplication/>`
    1. Verify spring boot data application can successful checkpoint and restore
    1. After checkpoint and before restore: configure the remote data source location (URL) and credentials (username, password)
    1. On restore verify the remote spring data source can be accessed by the application
1. Spring Boot Data tests deployed as a `<WebApplication/>` WAR
    1. Verify spring boot data application can successful checkpoint and restore
    1. After checkpoint and before restore: configure the remote data source location (URL) and credentials (username, password)
    1. On restore verify the remote spring data source can be accessed by the application

### CRaC Tests
1. Do a `checkpoint` action `afterAppStart` with multiple resources that throw errors on `beforeCheckpoint` notification
    1. Verify that all resources get notified of the `checkpoint` action, even when a resource notified before them throws an error on the `beforeCheckpoint` notification
    1. Verify that the `checkpoint` action fails with the expected error code and messages.
1. Do a `checkpoint` action `afterAppStart` and then restore the process with a multiple resources that throw errors on `afterRestore` notification
    1. Verify that all resources get notified of the restore, even when a resource notified before them throws an error on `afterRestore` notification
    1. Verify that the restore fails with the expected error code and messages.
1. Start a Liberty server with an application that attempts to perform an application initiated checkpoint using the CRaC `Core.checkpointRestore` API.  Note this test is not performing a `checkpoint` action at all.
    1. Verify that the `Core.checkpointRestore` method throws the appropriate `java.lang.UnsupportedOperationException` exception.
1. Perform a `checkpoint` action using `afterAppStart` on a server with an application that attempts to perform an application initiated checkpoint using the CRaC `Core.checkpointRestore` API.
    1. Verify that the `Core.checkpointRestore` method throws the appropriate `org.crac.CheckpointException` exception.
1. Perform a `checkpoint` action using `beforeAppStart` on a server with an application that attempts to perform an application initiated checkpoint using the CRaC `Core.checkpointRestore` API.
    1. Verify that the `Core.checkpointRestore` method throws the appropriate `org.crac.CheckpointException` exception if called by the application after the server process has been restored.

### Spring Boot Tests
1. Do a `checkpoint` action with a Spring Boot application that fails to start
    1. Verify the `checkpoint` action fails with the expected error code and messages

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

We rate our confidence level at 4:

**Comment by ayoho** [comment]
Coverage sounds ample and good to me 👍
