### ISSUE TITLE
Use `AttributeKey` in telemetry `MetricRecorderImpl`

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#28481]
When building an `Attributes` object, we should use predeclared `AttributeKey` instances as the key, rather than plain strings.

**Comment by Yas-Franco** [comment]
Completed[ here](https://github.com/benjamin-confino/open-liberty/commit/a1d279b7b5a5ed358f03d6c51f5566abd459c4a1)
