### ISSUE TITLE
DB2 for z/OS: transaction log manager should provide an option to change the default database

### ISSUE THREAD

**Issue by tuomin35** [OpenLiberty/open-liberty#28507]
**Describe the use case that you want to enable:**
An option to change the default database when creating tables.
`CREATE TABLE (...) IN DATABASE database-name`

**Describe why this is important to you:**
Transaction log manager does not work with DB2 for z/OS if the default database, which is used for the JDBC driver, could not be used for the leases, partner and tranlog tables.

**Additional context**
The `databaseName` for "JDBC driver property" and `database-name` for "CREATE TABLE" are not the same.
- https://openliberty.io/docs/latest/reference/config/dataSource.html#properties
- https://www.ibm.com/docs/en/db2-for-zos/12?topic=statements-create-table

I am not a DBA, but I have understood this is a DB2 for z/OS related problem.

**Comment by jonhawkes** [comment]
The intention is that the transaction service should use its own non transactional datasource to access the database used for recovery logs. That datasource should have the databaseName attribute set appropriately. Are you saying that does not work?

**Comment by tuomin35** [comment]
I have two separate datasources: XA datasource for application and non-XA for transaction manager.

According to DBA the _default_ database can not be used when creating tables.

> Whenever a table space is created, it is explicitly or implicitly assigned to an existing database. If you create a table space and do not specify a database name, the table space is created in the default database, DSNDB04.
https://www.ibm.com/docs/en/zos-basic-skills?topic=structures-db2-databases

Error message in OpenLiberty:
`com.ibm.db2.jcc.am.SqlSyntaxErrorException: TUOMIN35.WAS_PARTNER_LOGTUOMIN35 IS AN UNDEFINED NAME. SQLCODE=-204, SQLSTATE=42704`

Error message in DB2:
`TUOMIN35 DOES NOT HAVE THE PRIVILEGE TO PERFORM OPERATION CREATE TABLE ON OBJECT DSNDB04`

...where `TUOMIN35` is a placeholder for database schema name, client hostname and client username, respectively.
