### ISSUE TITLE
`OpenTelemetryConstants` package not exported but used by other bundles

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#28510]
The package containing `OpenTelemetryConstants` is not exported, but the class is used in other bundles. I think we're getting away with it because the constants are being inlined at compile time but it creates warnings everywhere and if the class is intended to be used outside of its bundle then it should be exported.

**Comment by Yas-Franco** [comment]
The package is exported here: 
https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.microprofile.telemetry.internal.common/original.bnd#L18-L25
