### ISSUE TITLE
Verify all messages are translated for Servlet 6.1

### ISSUE THREAD

**Issue by pmd1nh** [OpenLiberty/open-liberty#28626]
Verify the following nlsprops files for their translated messages.

1. ~~com.ibm.ws.transport.http/resources/com/ibm/ws/http/channel/internal/resources/httpchannelmessages.nlsprops~~ `<VERIFIED>`
2. ~~com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops~~ `<VERIFIED>`
3. ~~io.openliberty.session.6.0.internal/resources/io/openliberty/session/resources/SessionMessages.nlsprops~~ `<VERIFIED>`

**Comment by pmd1nh** [comment]
Verified SessionMessages.nlsprops

```
# Servlet 6.1
session.id.is.invalid=SESN8603E: El ID de sesi\u00f3n no es v\u00e1lido.
session.id.is.invalid.explanation=El ID de sesi\u00f3n ha cambiado desde el \u00faltimo acceso.
session.id.is.invalid.useraction=El ID de sesi\u00f3n ha cambiado desde el \u00faltimo acceso. Intente iniciar la sesi\u00f3n de nuevo.
```

**Comment by pmd1nh** [comment]
Verified webcontainer Messages_es.nlsprops

```
read.write.bytebuffer.null=CWWWC0010E: Un intento de leer de una operaci\u00f3n InputStream o escribir en una operaci\u00f3n OutputStream ha fallado porque un argumento de variable ByteBuffer era nulo.
read.write.bytebuffer.null.explanation=La instancia del argumento de variable ByteBuffer que se pasa a la API de lectura o grabaci\u00f3n no debe ser nula.
read.write.bytebuffer.null.useraction=Modifique el c\u00f3digo de aplicaci\u00f3n para crear una instancia de ByteBuffer no nula para pasar a la operaci\u00f3n InputStream o OutputStream .

```

**Comment by pnicolucci** [comment]
Verified: com.ibm.ws.transport.http/resources/com/ibm/ws/http/channel/internal/resources/httpchannelmessages.nlsprops  ->  https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.transport.http/resources/com/ibm/ws/http/channel/internal/resources/httpchannelmessages.nlsprops

 `cookie.attribute.name.invalid` is translated: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.transport.http/resources/com/ibm/ws/http/channel/internal/resources/httpchannelmessages_cs.nlsprops#L212
