### ISSUE TITLE
Implement ProvisioningFeatureDefinition APIs

### ISSUE THREAD

**Issue by jimblye** [OpenLiberty/open-liberty#28639]
/**
     * Answer the platform of this feature.
     *
     * The feature platform is stored as a header attribute.
     *
     * @return The platform of this feature.
     */
    List<String> getPlatformNames();

    /**
     * Tell if this is a versionless feature.
     *
     * @return
     */
    boolean isVersionless();

    /**
     * Tell if this is a convenience feature.
     *
     * @return
     */
    boolean isConvenience();

    /**
     * Tell if the feature is a compatibility feature.
     * This is determined by two things. If the feature is private and it
     * has a WLP-Platform, then it is a compatibility feature.
     *
     * @return
     */
    boolean isCompatibility();

    /**
     * Tell the platform, when the feature is a compatibility feature.
     *
     * Always returns the first platform the WLP_Platform: list. See { {@see #getPlatforms()}
     *
     * @return The platform value of this compatibility feature
     */
    String getPlatformName();.

**Comment by tbitonti** [comment]
Delivered by #28641.
