### ISSUE TITLE
Versionless: Complete test checking for new feature versionless requirements

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/open-liberty#28676]
1) - Checking all public features if they belong in a platform...  they now require a WLP-Platform header....
2) - Require private versionless feature creation (Already done)
3) - Any new feature being added to a platform - possibly require a new "public" versionless feature.

**Comment by rsherget** [comment]
All of these are already implemented in `VersionlessTest` within `com.ibm.websphere.appserver.features` 

1. Starting at line 310, checks if feature is supposed to have a WLP-Platform value and then if it has a WLP-Platform with `getPlatforms()`
```
if (!skipFeatures.contains(featureTitle) && depInfo.getPlatforms().isEmpty()) {
    errorMessage.append(depInfo.getName()).append('\n');
}
```

2 and 3. A test already goes through all the features, both public and private, and creates the missing versionless features.
