### ISSUE TITLE
add JVM metrics to MP Telemetry 2.0

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#28689]
As described in the MP Telemetry 2.0 spec, we are required to have a specific set of JVM metrics.

we should be able to use the JVM metrics from [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/runtime-telemetry/runtime-telemetry-java8/library).  @fmhwong did some [investigation](https://github.com/eclipse-openj9/openj9/issues/18952) to show that that implementation satisfies the requirements of the semantic conventions for JVM metrics and works on OpenJ9 (I believe it's also been tested with HotSpot).

**Comment by benjamin-confino** [comment]
I've created a PR here https://github.com/tonyreigns/open-liberty/pull/222 - it goes directly into Tony's branch to avoid a merge conflict down the line.

**Comment by fmhwong** [comment]
From this [code](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/687cffe01fc5835ba008291c03be83496b434894/instrumentation/runtime-telemetry/runtime-telemetry-java8/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics/java8/internal/CpuMethods.java#L35), it looks like the library supports both J9 and Hotspot JVM.  All tests I performed were on J9 only.

**Comment by donbourne** [comment]
function provided in #28809
