### ISSUE TITLE
Jakarta Persistence 3.2 Beta

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#28723]
Move the Jakarta Persistence 3.2 features to "beta".

This will include at least the following features:
- com.ibm.websphere.appserver.org.eclipse.persistence-3.2
- io.openliberty.persistence-3.2
- io.openliberty.persistenceContainer-3.2

And may also include features such as:
- io.openliberty.batch2.1.internal.ee-11.0
- io.openliberty.jakartaeeClient-11.0

Primarily, this is done by updating the following in the `.feature` files:

```
kind=noship   -> beta
edition=full   -> [same as older feature level, such as jpa 3.1]
```

for #25091

**Comment by Riva-Tholoor-Philip** [comment]
The PR is merged and hence closing this issue
