### ISSUE TITLE
jaxb regression in 24.0.0.2 ?

### ISSUE THREAD

**Issue by krismarc** [OpenLiberty/open-liberty#28745]
Accordingly to issues and commits I've found. There were some changes around jaxb and seems like @neuwerk might know details :)

I've found some commits with some reverts already done. So I'd like to know if we are not hunting a bug which is already known and might be already fixed or it's under investigation.

**Describe the bug**  
we have attempted to switch from 23.0.0.12 to 24.0.0.4 with spring boot based application (without any changes to the app itself). and this resulted in:

```
Unable to start web server; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration': Unsatisfied dependency expressed through method 'setWebSecurityCustomizers' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ignoreCloudFoundryPathsWebSecurityCustomizer' defined in class path resource [org/springframework/boot/actuate/autoconfigure/cloudfoundry/servlet/CloudFoundryActuatorAutoConfiguration$IgnoredCloudFoundryPathsWebSecurityConfiguration.class]: Unsatisfied dependency expressed through method 'ignoreCloudFoundryPathsWebSecurityCustomizer' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cloudFoundryWebEndpointServletHandlerMapping' defined in class path resource [org/springframework/boot/actuate/autoconfigure/cloudfoundry/servlet/CloudFoundryActuatorAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.autoconfigure.cloudfoundry.servlet.CloudFoundryWebEndpointServletHandlerMapping]: Factory method 'cloudFoundryWebEndpointServletHandlerMapping' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cachesEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/cache/CachesEndpointAutoConfiguration.class]: Unsatisfied dependency expressed through method 'cachesEndpoint' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cacheManager' defined in class path resource [org/springframework/boot/autoconfigure/cache/JCacheCacheConfiguration.class]: Unsatisfied dependency expressed through method 'cacheManager' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jCacheCacheManager' defined in class path resource [org/springframework/boot/autoconfigure/cache/JCacheCacheConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.cache.CacheManager]: Factory method 'jCacheCacheManager' threw exception; nested exception is javax.cache.CacheException: org.ehcache.xml.exceptions.XmlConfigurationException: Error parsing XML configuration at file:/home/vcap/app/wlp/usr/servers/defaultServer/apps/app.war/WEB-INF/classes/ehcache.xml
```

```
Failed to instantiate [javax.cache.CacheManager]: Factory method 'jCacheCacheManager' threw exception; nested exception is javax.cache.CacheException: org.ehcache.xml.exceptions.XmlConfigurationException: Error parsing XML configuration
```

later on, we gave it a try with all other versions in between and this starts to happen in 24.0.0.2. 24.0.0.1 is yet fine.

**Comment by neuwerk** [comment]
For admin purpose going to comment based on the discussion in #28019 , @krismarc is going to run against the nightly build that includes the fix for #28019 - if the problem is resolve then we can close this out, if not then we will dig into this as its own separate issue.

**Comment by krismarc** [comment]
@neuwerk, we have tested and it works again with the latest nightly build of 24.0.0.7 -> https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2024-06-13_2055/openliberty-24.0.0.7-cl240720240613-2055.zip
..even with beta of 24.0.0.6 it doesn't yet.

Therefore, three questions comes to my mind. 
1) is there any chance we could still see this little change in June release?
2) would you assume safe to build 24.0.0.5 myself with changes you have done in https://github.com/OpenLiberty/open-liberty/pull/28642/files
3) do you know what's the potential impact scope of this? I'm handling 700 prod apps, around 50 already started using 24.0.0.4 and only 1 faced an issue so far. I don't believe this impacts entire jaxb scope - this would be rather a mess. It's not clear to me when application exactly might encounter an issue.

**Comment by BerksanAtes** [comment]
@krismarc @neuwerk won't be available till the middle of next week. I'll try to help you meanwhile. 
1. The window for us to put our changes for 24.0.0.6 is already closed. Unfortunately fix will go to next months release.
2. In general it's not advisable to apply a fix designed and build for a release to another release. We always recommend to use the latest release anyway. 
3. It is really hard to tell potential impact scope. There are so many factors that might affect it.

**Comment by neuwerk** [comment]
@krismarc unfortunately @BerksanAtes is correct, but I just wanted to add that the next 24.0.0.7 beta will also have it included. If its show-stopper to wait for the next release and your organization is entitled to IBM support, you could open a [support case](https://www.ibm.com/mysupport/s/?language=en_US).
