### ISSUE TITLE
Converting arrays in configuration may not honor escape character

### ISSUE THREAD

**Issue by ljnelson** [OpenLiberty/open-liberty#2879]
Hello; thanks for a great product.

I noticed here (https://github.com/OpenLiberty/open-liberty/blob/e5245dcc553527fdc8e128bdff64ffd8f48c0946/dev/com.ibm.ws.microprofile.config/src/com/ibm/ws/microprofile/config/impl/ConversionManager.java#L233) while investigating your code for ideas on how to implement MicroProfile Config that the specification-mandated escape character (`\`) does not seem to be honored when converting an array.  I just wanted to make sure I captured this so it didn't get lost; it's possible, too, that I've misinterpreted something.  Thanks!

**Comment by tevans78** [comment]
Hi @ljnelson, thanks for raising the issue.

I think the link you pasted in above is to the Config 1.1 version of the file. We have already fixed the problem in 1.2. See here, in master;

https://github.com/OpenLiberty/open-liberty/blob/71753e5e25737b2fddb702948a9c88e2b5344a4e/dev/com.ibm.ws.microprofile.config/src/com/ibm/ws/microprofile/config/impl/ConversionManager.java#L288
