### ISSUE TITLE
Allow MP OpenAPI server.xml info section to be set with server.xml (2.0+)

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#28858]
## New server.xml element

```xml
<mpOpenAPI>​
  <info title=""​
    description=""​
    termsOfService=""​
    contactName=""​
    contactUrl=""​
    contactEmail=""​
    licenseName=""​
    licenseUrl=""​
    licenseIdentifier=""​
    summary=""​
    version=""​
  />​
</mpOpenAPI>​
```

If `<info>` is present
- The [`info` section of the OpenAPI document][info-section] is replaced with one generated from this config
- The [`mp.openapi.extensions.liberty.merged.info` property](https://openliberty.io/docs/latest/documentation-openapi.html#multi-module) is ignored

Note that `info` and `version` are required, in the OpenAPI spec - the document will not validate if they're not present and a warning will be logged. Not sure if we can indicate in the metatype that these attributes are "required" for the purposes of any UI that might be using it.

[info-section]: https://spec.openapis.org/oas/v3.1.0.html#info-object

**Comment by Azquelt** [comment]
Tasks:
- [x] Update the metatype, use `ibm:beta` on the new elements/attributes
- [x] Have a component which receives the config, currently this is `OpenAPIEndpointManager` since we only have endpoint config, so some refactoring will be needed here
- [ ] Update `OpenAPIUtils.getConfiguredInfo` to consider the new config from server.xml
  - Ensure this processing is gated behind the beta flag
- [ ] Test that the new config is ignored unless the beta flag is set (to be removed when feature is done)
- [ ] Test that the info object can be set with server.xml
  - We have existing tests in `MergeConfigTest` which can be adapted
- [ ] Test that the MP config properties are ignored if the new server.xml element is used
- [ ] Test that changes to the server.xml config are reflected immediately

**Comment by Yas-Franco** [comment]
The small start I made before handing back overr to Ben is here: https://github.com/OpenLiberty/open-liberty/pull/29792
