### ISSUE TITLE
OpenTelemetry does not filter out arquillian-liberty-support

### ISSUE THREAD

**Issue by benjamin-confino** [OpenLiberty/open-liberty#28855]
Because arquillian-liberty-support is not an application OpenTelemetryInfoFactory is not supposed to, and cannot, create an OpenTelemetrySDK for it.

However in failing to do so it currently throws an FFDC.

**Comment by Azquelt** [comment]
Looking at the code, there's a hard-coded list of applications we choose to ignore because they're actually liberty features?

We should check if there's some way we can generically tell if the "current application" is actually a feature.
