### ISSUE TITLE
Versionless: Ensure Result class from resolver covers all failing scenarios

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/open-liberty#28969]
The Result class needs to capture the error scenarios with versionless / platforms

Additional information captured for the "target platforms" as well.

This is required to display error cases on the install / repo side - differing from any logging the kernel resolver may display.

**Comment by rsherget** [comment]
implementation in https://github.com/OpenLiberty/open-liberty/pull/29054 and https://github.com/OpenLiberty/open-liberty/pull/29014
