### ISSUE TITLE
Feature Test Summary for Versionless features

### ISSUE THREAD

**Issue by hlhoots** [OpenLiberty/open-liberty#29017]
For epic #25704 : Support versionless Jakarta EE/MicroProfile features

## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

Several categories of tests are performed:

* Feature definitions are examined to determine if necessary updates have been made relative to versionless feature functionality.
  * Tests were added to ensure that all features which are associated with a platform, with exceptions, must have associated versionless features.
  * Tests were added to ensure that all versionless features both a public feature definition and private, internal, linking features, which create an association with a platform version.
  * Tests were added to ensure that all versionless features are marked as enabled for InstantOn.
  * The tests detect missing feature data, and emit suggested feature definitions for any which are missing.
  * The Feature definition, and "ESA" artifacts on the liberty repo component were also enhanced to understand feature "platforms" - tests added to load and save these artifacts that are now part of our shipped ESA's and respository metadata.
  * Install testing for "featureUtility installServerFeatures"

* A large number of feature resolution tests are performed.
  * All resolution tests validate that expected feature resolution results are obtained.
  * Server based tests also validate that the expected feature resolution messages are obtained.
  * Feature resolution tests are performed using a test feature repository (outside of a running server).
    * Using a test repository is much faster than server based test, enabling many more resolution tests to be performed.
    * Such tests require feature data stored in the server image, and must be run as FAT tests.
  * Feature resolution tests are performed using a running server.
    * Server based resolution tests use a more complete code stack, providing more robust test results.
    * However, server based testing is much slower than resolution relative to a test repository, limiting how many tests may be run in this mode.

* Feature resolution tests are parameterized:
  * Input platforms:
    * Specified as platform elements.
    * Specified indirectly using versioned features.
    * Specified using an environment variable.
  * Input features:
    * These may be versioned features.
    * These may be versionless features.
  * Additional parameters:
    * For server startup or for installation/packaging.
  * Output resolved features.
  * Output special case results:
    * Platform errors.
    * Feature errors.
    * The specific resolution of each versionless feature.

* Several categories of tests were performed:
  * Baseline: Versioned Public Feature Singleton.  These tests compare the resolution results of **all single public features**.  Results are compared with results obtained before adding versionless feature functionality.  
    * This is a baseline / regression test.
  * Baseline: Versioned Servlet Plus Versionless feature.  These tests compare the resolution of the pair of **all versioned servlet features with all versionless features**.
    * This is a core function test for versionless features.
  * Baseline: Versionless Feature Plus Platform.  These tests convert **all public feature singletons into a combination of a versionless feature plus a versioned platform**.  The combination is selected to be as close, in effect, to the original versioned feature.  Results of the versionless resolution are compared, with adjustments, with the original versioned resolution.
    * This is a core function test for versionless features, testing the equivalence of the new versionless feature resolution with similar, versioned feature cases.
  * Specific: JavaEE to MicroProfile: These tests cross **a versioned JavaEE feature with a versionless MicroProfile feature**.  The detailed results are verified to be correct.  The tests vary platform preference so to verify that the correct resolution is performed relative to the specified platform preference.
    * This is a core function test for versionless features, specifically, for cases which cross between JavaEE and MicroProfile.
  * Specific: MicroProfile to JavaEE: These tests cross **a versioned MicroProfile feature with a versionless JavaEE feature**.  The detailed results are verified to be correct.  The tests vary platform preference so to verify that the correct resolution is performed relative to the specified platform preference.
    * This is a core function test for versionless features, specifically, for cases which cross between JavaEE and MicroProfile.
  * Specific: Platform Handling: These tests verify that platform values are handled correctly for all of the cases of where the platform is specified, and that platform values are used correctly for different combinations of versionless features.  The test plan has a cross of (platform element, versioned feature, environment variable) as one dimension of test parameters with (no platforms, one platform, two platforms of the same type, two platforms of different types) as a second dimension, and with (one associated feature, two associated features) as a third dimension.
    * This is a core function test for versionless features, specifically, for variations on how the platform is specified.
    * These tests are run both using a test feature repository and using running servers.  A distinguished subset of all test combinations was selected to run on servers.
  * Specific: Feature messaging.  Feature resolutions were selected that generate all possible result messages.  This includes several categories of results:
    * Normal resolution of versioned features;
    * Normal resolution of versionless features with platforms;
    * Normal resolution of versionless features with env var;
    * Normal resolution of versionless features with versioned features;
    * Versionless feature resolution with no platforms;
    * Versionless feature resolution with incompatible platforms;
    * Versionless feature resolution with no valid version;
    * Feature resolution feature errors
    * This is a core function test for versionless features, specifically, verifying base cases of all feature resolution messages.
  * Specific: Caching.  Feature resolution provides a cache to speed up resolution between server restarts, when the restart is performed and the feature configuration did not change.  FAT tests are being written that verify that the feature resolution cache is functioning correctly.
    * This is a core function test for versionless features, specifically, relating to feature resolution caching.
  * Specific: Feature update.  This is a variation of feature caching.  A running server tracks what features are configured, and re-resolved features when the feature configuration is updated.  FAT tests are being written to verify that feature resolution is updated correct when the feature configuration is updated for a running server.
    * This is a core function test for versionless features, specifically, relating to feature update handling.

### List of FAT projects affected

* com.ibm.websphere.appserver.features - Versionless feature file tests
  * Validate that all versionless features exist that are supposed to exist as well as verify their contents are correct
  * Create new feature files for missing/incorrect features
* com.ibm.ws.kernel.boot_fat - Versionless feature packaging tests
  * Tests basic packaging formats and strategies - normal package, minify, runnable, etc.
  * Tests basic packing of versionless platforms with versionless features both configured in the server.xml and in the PREFERRED_PLATFORM_VERSIONS environment variable.
* com.ibm.ws.kernel.feature
   * Unchanged  
   * 5 test classes with about 105 tests
   * Low level feature unit tests
* com.ibm.ws.kernel.feature.resolver_fat - Versionless feature resolution tests
  * BaselineResolutionMicroProfileUnitTest
    * Parameterized: 2 cases
  * BaselineResolutionServletUnitTest
    * Parameterized: About 300 cases
  * BaselineResolutionSingletonUnitTest
    * Parameterized: About 310 cases
  * BaselineVersionlessSingletonUnitTest
    * Parameterized: About 310 cases
  * VersionlessJavaEEToMicroProfileTest
    * Parameterized: 8 cases
  * VersionlessServletToMicroProfileTest
    * Parameterized: 16 cases
  * VersionlessMessageTest
    * 6 cases (1 per message)
  * VersionlessCachingTest
    * 6 cases
    * Testing feature resolution cache between server restarts
    * Varying features and platforms
  * VersionlessPlatformTest.java
    * 11 cases
    * varies platform setting by platform element, environment variable, versioned feature
    * includes EE, MicroProfile, and mixed tests

* Install/Packaging (in com.ibm.ws.install.featureUtility_fat):
  * InstallVersionlessServerTest
    * testVersionlessWithPlatformFeatures - test use of versionless features for installation
    * testVersionlessWithBadPlatformFeatures - test use of bad platform values for installation
    * testVersionlessWithNoPlatformFeatures - test missing platform when using versionless for installation

 * Feature repository tests (com.ibm.websphere.appserver.features):
   * SymbolicNameTest.java (3 tests; unchanged)
   * VersionlessTest.java (6 tests; all new)
     * Validate platform settings;
     * Ensure that versionless features exist for platform associated public features.
   * VisibilityTest.java (22 tests; 1 new)
     * Verify that versionless features have the correct visibility
    
 * com.ibm.ws.repository_fat_shared
   * EsaResourceTest.java
     * 19 tests (unchanged)
     * validates that ESA data for features, which includes new versionless feature metadata, can be persisted

 * Minified Packaging(in com.ibm.ws.kernel.feature_fat)
    * SimpleVersionlessMinifiedServerTest.java
    * 1 test for minifying server with versionless and bringup of minified package.

### Test strategy

* What functionality is new or modified by this feature?

This feature impacts feature resolution -- which determines what features are run by a particular server -- and which determines what features are put into a server package.

* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)

Extensive FAT tests were created for a representative subset of resolution cases, including variations of what features are to be resolved, and including error cases and cases which produce all feature resolution messages.  See the prior sections for a detailed listing of the test strategy and for particular tests which were run.

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

The current confidence level is 4, working towards 5.

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by ayoho** [comment]
Coverage looks pretty comprehensive; I trust that the team has considered any edge case (and more) that I'd be able to conjure up. 👍
