### ISSUE TITLE
jaxrs: Regression by #27782

### ISSUE THREAD

**Issue by mkoegler** [OpenLiberty/open-liberty#29124]
18857ba42fb853efe3fcdc1c6b6960e82ea7a504  changed jaxrs client to call
`                        return jsseHelper.getSSLContext(null, null, null);`
if no sslAlias is explicitly set. It does not honor eg. any ssl Config Statement, which would match a host.

The old behavoiur would be passing the connectionInfo:
`                        return jsseHelper.getSSLContext(null, connectionInfo, null);`

So for eg. jax-ws, OL still honors
```
<ssl id="x" keyStoreRef="test">
          <outboundConnection host="test.com" port="443"/>
</ssl>
```
For jax-rs. it is not honored and uses only the default SSL statement.

Tested with 24.0.0.6 - the code is still unchanged in master.

**Comment by mkoegler** [comment]
Change introduced by @WhiteCat22  #27782

**Comment by dougbreaux** [comment]
Following, possibly related? https://stackoverflow.com/q/78742044/796761

**Comment by WhiteCat22** [comment]
It looks like when I refactored SSL code I inadvertently broke dynamic outbound for JAX-RS Clients in the fallback case where no `sslRef` is supplied. The logic makes sense to get the default SSL config, however, it looks like I missed the dynamic outbound case.

**Comment by WhiteCat22** [comment]
@mkoegler Do you have a sample application that you could share with your use case?

**Comment by WhiteCat22** [comment]
https://github.com/OpenLiberty/open-liberty/issues/27782

**Comment by mkoegler** [comment]
No. You can use even the simples jaxrs client demo. Call an endpoint protected by client certificates  and provide them only via hostname matching via a second ssl setting:
```
<ssl id="x" keyStoreRef="test">
          <outboundConnection host="test.com" port="443"/>
</ssl>
```

**Comment by dougbreaux** [comment]
Well... my problem still seems to be happening with 24.0.0.9. Ahh, and I see a comment on my SO question that this won't address HttpClient dynamic outbound ☹️ .

**Comment by dougbreaux** [comment]
Ok, it still seems to me that this should be able to work for just HttpClient, but I did find a way to use JSSEHelper to use the server configured objects instead of having to explicitly reference them in Java source
