### ISSUE TITLE
Versionless: Feature manifest corrections

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#29168]
Per the externals review:

jakartaee-11.0 tolerates were removed, and need to be added back.

For example (one of several feature manifests):

### build.image/wlp/lib/features/io.openliberty.versionless.faces.mf

Manifest Headers with Changes
Subsystem-Content
Old Value
io.openliberty.internal.versionless.jsf-2.0;ibm.tolerates:="2.2,2.3,3.0,4.0,4.1";type="osgi.subsystem.feature"
New Value
io.openliberty.internal.versionless.jsf-2.0;ibm.tolerates:="2.2,2.3,3.0,4.0";type="osgi.subsystem.feature"

jsp and pages versionless features need to have jsp-2.2 set back as the preferred version:

### build.image/wlp/lib/features/io.openliberty.versionless.jsp.mf

Manifest Headers with Changes
Subsystem-Content
Added content
io.openliberty.internal.versionless.jsp-2.3;ibm.tolerates:="3.0,3.1";type="osgi.subsystem.feature"
Removed content
io.openliberty.internal.versionless.jsp-2.2;ibm.tolerates:="2.3,3.0,3.1,4.0";type="osgi.subsystem.feature"

### build.image/wlp/lib/features/io.openliberty.versionless.pages.mf

Manifest Headers with Changes
Subsystem-Content
Added content
io.openliberty.internal.versionless.jsp-2.3;ibm.tolerates:="3.0,3.1";type="osgi.subsystem.feature"
Removed content
io.openliberty.internal.versionless.jsp-2.2;ibm.tolerates:="2.3,3.0,3.1,4.0";type="osgi.subsystem.feature"

**Comment by rsherget** [comment]
Fixed with https://github.com/OpenLiberty/open-liberty/pull/29142
