### ISSUE TITLE
Open Liberty Release 24.0.0.7

### ISSUE THREAD

**Issue by krismarc** [OpenLiberty/open-liberty#29218]
Hey, a release note is not updated in github for this release.
https://github.com/OpenLiberty/open-liberty/releases/tag/gm-24.0.0.7

..while it's already available since Jul 16
https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/24.0.0.7/

**Comment by ayoho** [comment]
Thank you for bringing it to our attention, @krismarc. All links should be there now.
