### ISSUE TITLE
Out-of-the-box OpenLiberty support for letsencrypt.org TLS certificates?

### ISSUE THREAD

**Issue by hrstoyanov** [OpenLiberty/open-liberty#2930]
The very popular [letsencrypt.org](https://letsencrypt.org) offers free (relatively short-lived) SSL certificates. It implements [ACME](https://tools.ietf.org/html/draft-ietf-acme-acme-10) (see also [ACME4J](https://github.com/shred/acme4j)) protocol to obtain/renew certificates, which would need to be implemented by OL, but is not compatible with the clunky keystore file approach. Any plans to seamlessly integrate with letsencrypt/ACME?

**Comment by NottyCode** [comment]
I'm not going to go as far as say plans, but I agree it would be a cool thing to do. I think one reason it hasn't been done in the past is because app servers are often deployed with the SSL being terminated ahead of the application server at which point it wouldn't be useful.

**Comment by hrstoyanov** [comment]
So what is the status of this? This month (July 2018) Chrome starts warning users whe visiting sites [that use HTTP](https://www.theregister.co.uk/2018/02/08/google_chrome_http_shame/). Therefore, if one ones to use OL and the free and awesome [letsencrypt.org](https://letsencrypt.org), she will have to put a letsencrypt-friendly proxy (Apache/NGINX), which is pretty ugly and redundant.

**Comment by hrstoyanov** [comment]
@aguibert , @acdemyers
Any hope for this feature? As you know, Google Chrome will mark all HTTP connections as unsafe with the next Chrome release. letsencrypt.org offers a free way to secure web app. 

Without built-in support in OL, one has to:
1. Frontend his/her OL-based  web app with Apache or NGINX (which already integrate smoothly with letsencrypt) or even Istio.

2. Switch back to the old way of purchasing certificates, building key stores, etc.

**Comment by acdemyers** [comment]
@hrstoyanov  This is still under consideration.

**Comment by acdemyers** [comment]
This is still be investigated.

**Comment by tevans78** [comment]
Ongoing

**Comment by jtmulvey** [comment]
Most of the design work on this item is completed and we're starting to evolve the prototype to real implementation.  It should be delivered soon (two or three months).

**Comment by acdemyers** [comment]
Being worked under #9017

**Comment by jtmulvey** [comment]
@hrstoyanov We are very close to delivering this support. Any interest in trying this support out pre-GA?

**Comment by hrstoyanov** [comment]
Will try depending on my time, thank you very much!


/Hristo Stoyanov

**Comment by inad9300** [comment]
Has this been completed? Is [Automatic certificate management with ACME
](https://openliberty.io/docs/latest/acme-cert-management.html) the result of this work, or is what you want to accomplish here something else?

**Comment by NottyCode** [comment]
As observed by @inad9300 this was delivered with the ACME support, but closing this was missed.
