### ISSUE TITLE
JWT configuration can be simpler?

### ISSUE THREAD

**Issue by hrstoyanov** [OpenLiberty/open-liberty#2932]
Looking at the [JWT OL tutorial](https://openliberty.io/guides/microprofile-jwt.html#creating-the-server-configuration-file) I find the JWT implementation unnecessarily convoluted:

1. Why do one need to store the public key used for JWT signing in a keystore file? This is just a public key, so it could be just another configuration attribute (for example __publicKey__):

```
<server >
    ...
    <mpJwt id="jwtUserConsumer" 
                  publicKey="ABCDEFJX1234546" 
                  audiences="simpleapp" 
                  issuer="${jwt.issuer}"/>
</server>
```
2. Can we be more flexible and avoid using the java keystore files?
 - This complicates the automation configuration for OL pipelines (especially for Gradle projets, where no good plug-in exists)
 - Modern (and very popular!) free SSL CAs such as [letsencrypt.org](http://letsencrypt.org) use network protocol ([ACME](https://letsencrypt.org/docs/client-options/)) to create/renew certificates. See issue #2930

**Comment by hrstoyanov** [comment]
Looking at the [discussion around upcoming changes to MP JWT 1.1](https://groups.google.com/forum/#!topic/microprofile/-DzmIoJ58ak), this is about to change for the better - JWT machinery will be configurable via MP Config!

Fell free to close this issue.

**Comment by hrstoyanov** [comment]
Further, reading this [document](https://www.ibm.com/support/knowledgecenter/en/was_beta_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_sec_json.html) suggests that I can use the _jwksUri_ configuration attribute:
```xml
<mpJwt     
     jwksUri="https://example.com/api/jwk"   
</mpJwt>
```
to mitigate this issue. However jwksUri is ignored. See  Issue #3117

**Comment by chunlongliang-ibm** [comment]
1. The preferred key exchange method is JWK.  Note that public key can be easily translated to a jwk document.
2. If JWK is not supported by token issuer, and key exchange is out-of-band, the signing certificate. It is expected that signed's certificate is imported to trust store, and alias is configured in mpJwt to locate the certificate.
3. Liberty does not allow public key itself as a configuration attribute

**Comment by hrstoyanov** [comment]
For using JDK's default cacert, see explanation by @acdemyers in issue #4377
