### ISSUE TITLE
Feature Test Summary for Provide a way to send Liberty logs to OpenTelemetry

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/open-liberty#29355]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

### List of FAT projects affected

* io.openliberty.microprofile.telemetry.2.0.logging.internal_fat (NEW)
* io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat (NEW)

### Test strategy

This Feature Test Summary only covers the bridging of the Liberty and application logs to OpenTelemetry via the mpTelemetry-2.0 feature. The overall tests for the mpTelemetry-2.0 feature is covered under https://github.com/OpenLiberty/open-liberty/issues/28986

The following tests have been added:

**Test Scenario:** 
**OpenTelemetry SDK instances that needs to be tested for different logging scenarios for runtime and application instances.**
- **testTelemetryApplicationMessages :** Ensure that application logs are configured correctly with an application SDK, Test if only the app logs are routed and no Runtime logs are routed, to the configured exporter, when the App OTel SDK instance is used.
- **testTelemetryDropinAppSDK :** Test an application exported to dropins dynamically with an application SDK and ensure only application logs are bridged.
- **testTelemetryDropinRuntimeSDK :** Test an application exported to dropins dynamically with a Runtime SDK and ensure both application and runtime logs are bridged.

**Test Scenario:** 
**Test for verification if all Liberty log events are routed to OpenTelemetry log exporter, with different source configurations.**
- **testTelemetryMessages :** Ensures all Liberty messages are correctly bridged and all attributes are present.
- **testTelemetryApplicationMessages :** Ensures application messages are bridged.
- testTelemetryTrace : Ensures trace logs are bridged and all attributes are present. Also ensures that both runtime and app trace logs are routed when the runtime OpenTelemetry SDK instance is used.
- **testTelemetryFFDCMessages :** Ensures FFDCs are correctly bridged and all attributes are present.
- **testTelemetryApplicationMessages :** Ensures application messages are bridged.
-  **testTelemetryLogLevels :** Ensures all log types have the correct mapped log levels.
- **testTelemetryAllSources :** Test a server with all MPTelemetry sources enabled and ensure message, trace and ffdc logs are bridged.
- **testTelemetryNoSource :** Test a server with no MPTelemetry source attribute and ensure message logs are bridged by default.
- **testTelemetryNoTelemetryAttribute :** Test a server with no MPTelemetry attribute and ensure message logs are bridged by default.
- **testTelemetryEmptySource :** Test a server with an empty MPTelemetry sources attribute and ensure no logs are bridged.
- **testTelemetryInvalidSource :** Test a server with an invalid MPTelemetry source attribute and a warning is logged.
- **testTelemetryInvalidAndValidSource :** Test a server with both invalid and valid MPTelemetry source attributes and ensure a warning is logged along with the messages being bridged.
- **testTelemetryDynamicUpdateAllSources :** Test a server with only the message sources enabled and only ensure message logs are bridged, and then dynamically update the configuration to include all sources, and ensure all sources are bridged.
- **testTelemetryDynamicUpdateEmptySource :** Test a server with only the message sources enabled and only ensure message logs are bridged, and then dynamically update the configuration to exclude all log sources and ensure no messages are bridged.
- **testTelemetryLogRecordContext :** Ensure that the LogRecordContext extensions configured by an application are correctly mapped.
- **testTelemetryTraceSpanID :** Checks for populated span and trace ID for application logs

**Test Scenario:** 
**Test for InstantOn/Checkpoint scenarios for each source, where the old logs should not be bridged during restore phase.**
-  **testTelemetryMessagesCheckpoint :** Verifies that messages from the checkpoint phase do not get bridged over during restore phase.
- **testTelemetryTraceCheckpoint :** Verifies that traces from the checkpoint phase do not get bridged over during restore phase.
- **testTelemetryFFDCMessagesCheckpoint :** Verifies that FFDC from the checkpoint phase do not get bridged over during restore phase.

**Test Scenario:** 
**Test with OpenTelemetry Collector with the OTLP exporter for all logs**
- **testBridgedLogs :** Ensures all messages printed in the messages.log are bridged over to the OTLP container.
- **testMessageLogs :** Ensures that an info message from a Liberty application are bridged over to the OTLP container.
- **testTraceLogs :** Ensures that a trace message from a Liberty application are bridged over to the OTLP container.
- **testFFDCLogs :** Ensures that an FFDC message from a Liberty application are bridged over to the OTLP container.

**Test Scenario:** 
**Test for OpenTelemetry Java Agent scenarios with logging.**
- **testNoDuplicateJULMessageLogsWithOpenTelemetryAgent :** Ensure JUL message/trace logs are not duplicated when the OpenTelemetry Java agent is active with mpTelemetry-2.0.
- **testMatchingJULMessageLogsWithContainerViaOpenTelemetryAgent :** Ensures all Liberty Runtime messages are bridged over to OpenTelemetry, with the Java agent present.

In addition to the above test cases, we have also manually tested using the OpenTelemetry Collector to bridge Liberty and application logs to it and visualize them in Loki, from the Grafana stack.

The above test cases are also repeated for different MP and EE versions. The tests are repeated for the following versions:
```
MicroProfileActions.MP70_EE11,
TelemetryActions.MP14_MPTEL20,
TelemetryActions.MP41_MPTEL20,
TelemetryActions.MP50_MPTEL20_JAVA8,
MicroProfileActions.MP70_EE10
```

## Confidence Level

Our confidence level for the testing delivered for this feature is 4. We delivered all the automated testing we believe that covers the main path needed for this feature, as well as, the error scenarios. Most of the main testing needed for the MP Telemetry 2.0 feature already have existing test coverage via TCKs and Liberty specific MpTelemetry 1.0/1.1 FAT buckets that are repeated for MP Telemetry 2.0, which cover the basic functionality and error scenarios that may happen with the MPTelemetry feature, that this new feature adds onto.

**Comment by dave-waddling** [comment]
Hi @pgunapal, thank you for completing this FTS, I appreciate how comprehensive it is. Test coverage makes sense and there are no obvious gaps, so looking good.
