### ISSUE TITLE
Feature Test Summary for `Add HTTP metrics to monitor-1.0, mpMetrics and OpenTelemetry`

### ISSUE THREAD

**Issue by Channyboy** [OpenLiberty/open-liberty#29385]
Epic link: https://github.com/OpenLiberty/open-liberty/issues/20985

## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

### List of FAT projects affected

- `io.openliberty.http.monitor_fat`

### Test strategy

* What functionality is new or modified by this feature?

This feature introduces the support for Open Liberty's monitoring/observability capabilities to  capture HTTP requests made to the server and report them as an MBeans (following the monitor-1.0 model as this feature relies on monitor-1.0) and metrics through mpMetrics-5.x (JEE10+)  and mpTelemetry-2.0 (JEE7+).

The crux of this feature is to abide by the Open Telemetry semantic convention for HTTP metrics. We capture the metadata that is indicated by the attributes list from their [ semantic convention specification](https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration). The data we record is the count and duration of the requests.
 
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)

The tests in `io.openliberty.http.monitor_fat` test the MBean (repeats from JEE7 to 11), output for mpMetrics-5.x (repeats for EE10 and EE11) and the output from mpTelemetry-2.0 (repeats from EE7 to 11) with a configured Otel collector. The metric tests  test that the metric exists and the expected tags/labels are present as well as a value from the metric. The Mbean test tests for the presence of the expected object name.

Servlets:
- Tested servlets with regular paths
- Tested servlets with wild cards
- Tested servlets with query params (query params should not affect the http route)
- Tested servlets with application thrown exceptions, custom HTTP response status, non existent paths. 

Servlets:
- Tested REST resource with regular paths
- Tested REST resource with path params
- Tested REST resource with query params (with and without path params) (query params should not affect the http route)
- Tested REST resource with path application thrown exceptions, non existent paths. 

JSPs + other:
- Tested web.xml configured JSPs 
- Tested unconfigured JSPs
- Tested html file 
- Tested splash page for OpenLiberty

MBean
- Uses the same test apps above (Servlet, REST, jsp, html files ) and the same test servlet/resource hits.

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

N/A

## Confidence Level

4

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by dave-waddling** [comment]
Hi @Channyboy, thanks for completing this FTS - all looks good to me.
