### ISSUE TITLE
Unexpected transaction timeout of 180 seconds (or other unexpected value) after running Batch job previously in the server.  

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/open-liberty#2940]
Batch job with chunk step can cause side effect of "dirty" Transaction timeout for other threads.

**Comment by scottkurz** [comment]
In a batch job with a chunk step, the batch container will call **UserTransaction.setTransactionTimeout(seconds)** to set the transaction timeout for the next transaction started on the thread.   But since OpenLiberty doesn't perform a general cleanup upon obtaining a thread from the thread pool or returning a thread to the thread pool , this "thread-local"-like behavior can cause side effects when another piece of work runs on this same thread.

The fact that the behavior is unpredictable, depending on which piece of work exactly gets a given "dirty" thread from the thread pool, makes this a problem.

This is made more noticable by the fact that batch has its own default chunk timeout value of 180 seconds (though the value of '0' can be explicitly specified in JSL to default to the server default timeout, this is not the default from the batch/JSL perspective).

So we want to ensure that batch work begins with a "clean" transaction timeout value, a value of '0'.   

The options under consideration are:

1. cleanup for every piece of work in OpenLiberty
2. cleanup before/after each batch thread (job, partition, split-flow)
3. cleanup before/after each batch step (or after every chunk step).

By "cleanup" we mean set transaction to '0', most likely, (though also conceivable would be to store/restore previously-set value).

**Comment by kalidassn** [comment]
I'm facing dirty transaction timeout. Like when the transaction timeout happened for one thread on partition step. the next thread which is having transaction timeout hanging for a while. And its causing the batch job to run for long time. Basically how do we clean the thread as you mentioned the option 2 which is "cleanup before/after each batch thread".

**Comment by kalidassn** [comment]
And how to set the transaction back to '0'

**Comment by scottkurz** [comment]
Hi @kalidassn ... what version of Open Liberty or WebSphere Liberty are you running?   It's interesting that you say the problem happens when a second thread runs **after a transaction timeout**.   The original problem applied more generally when an earlier transaction had run with a non-zero timeout on this thread (not specifically or only when an earlier transaction had timed out on this thread).

**Comment by scottkurz** [comment]
Fixed by #3033
