### ISSUE TITLE
Feature Test Summary for MicroProfile Fault Tolerance 4.1

### ISSUE THREAD

**Issue by benjamin-confino** [OpenLiberty/open-liberty#29427]
### List of FAT projects affected

* com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics
* io.openliberty.microprofile.faulttolerance.4.1.internal_fat_tck (new)

### Test strategy

Microprofile Telemetry 2.0 introduced the ability to accept metrics and export them in various formats. To support this new glue code was written to allow Fault Tolerance to export its metrics to telemetry. 

This test strategy covers this glue code.

Most of the testing is done by `io.openliberty.microprofile.faulttolerance.4.1.internal_fat_tck` which tests we are able to correctly export every single metric listed in the specification.

Two new tests were created within `com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics` to cover areas outside the TCK. 

- `TelemetryMetricIsolationTest` tests that the glue code handles multiple applications correctly and does not leak metrics from one application to another. It also verifies we do not leak metrics across application restarts. 
- `TelemetryMetricCombinationTest` tests that Fault Tolerence can correctly export to Telemetry and Microprofile Metrics at the same time. 

Because MPTelemetry only supports metrics in version 2.0 or above, the fat repeats are:
- MicroProfileActions.MP70_EE11
- MicroProfileActions.MP70_EE10

## Confidence Level
4

**Comment by dave-waddling** [comment]
@benjamin-confino Thanks for completing this FTS, the test strategy and coverage make sense. All testing is passing cleanly in the latest SOE and there's nothing else which needs attention. I'll add the approval to the feature issue now.
