### ISSUE TITLE
Simplify configuration of classloader apiTypeVisibility

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#2944]
## Problem 
Currently if a user wants to override the default apiTypeVisibility (normally just adding third-party), they must know all of the existing values provided by default:

```xml
<application ...>
  <classloader apiTypeVisibility="spec, stable, ibm-api, api, third-party"/>
</application>
```

Also, before the `stable` type was introduced, many users probably have this hard-coded in their server.xml:
```xml
<application ...>
  <classloader apiTypeVisibility="spec, ibm-api, api, third-party"/>
</application>
```
which will confuse customers if they ever try to update their application to use MP APIs

## Proposal A
It would be easier if the user could simply specify what options they want to change from the default values (e.g. "add third-party visibility").  We could look to `chmod`-style syntax such as +/- `<api-type>`:
```xml
<application ...>
  <classloader apiTypeVisibility="+third-party"/>
</application>
```

This becomes more relevant now that we have added `stable` API type, which means customers that have hard-coded all of the api-types before we introduced the `stable` type will need to update their classloader configuration in order to use any microprofile features.

## Proposal B

Another thought is to think of API type visibility as a consecutively larger set of APIs.  For example, no one would ever want to configure `apiTypeVisibility="third-party"` (only see third-party, but no spec).  In my mind, the priority is as follows:
1. spec
2. stable
3. ibm-api
4. api
5. third-party

For this situation, we could look for the most general (highest number) configured API type, and assume the lower numbers are implied.  So if someone configured `apiTypeVisibility="third-party"`, they would get all api types.

**Comment by NottyCode** [comment]
Go with Proposal A.

**Comment by aguibert** [comment]
Opened epic #3044 for implementation of proposal A
