### ISSUE TITLE
Introduce versionless features for standalone MicroProfile specifications

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/open-liberty#29545]
Similar to MicroProfile liberty features that represent component specifications that are part of the MicroProfile release, standalone MicroProfile liberty features can also benefit from versionless features in order to make it easier for users to not need to know which version of the feature to use for different MicroProfile releases.  Unlike component specifications though, the standalone MicroProfile specifications are not initially tied to a particular MicroProfile release until MicroProfile 5 when the transition to Jakarta 9 happens due to the package rename requiring all MicroProfile specifications to have a version update.

With this all in mind I propose that for versionless features for the standalone specifications, we simply include the MicroProfile platform versions that work in liberty for those standalone specifications.  The list is below.

**mpContextPropagation**
- 1.0 microProfile-1.0 to 3.3
- 1.2 microProfile-4.0 to 4.1
- 1.3 microProfile-5.0 to 7.0

**mpGraphQL**
- 1.0 microProfile-3.3 to 4.1
- 2.0 microProfile-5.0 to 7.0

**mpReactiveMessaging**
- 1.0 microProfile-1.4 to 3.3
- 3.0 microProfile-5.0 to 7.0

**mpReactiveStreams**
- 1.0 microProfile-1.0 to 3.3
- 3.0 microProfile-5.0 to 7.0

#29749 is the GA blog issue for this change
https://github.com/OpenLiberty/docs/issues/7600 is the doc issue for this change

**Comment by cbridgha** [comment]
Thanks for creating this issue - yes this makes sense to me...

**Comment by dmuelle** [comment]
Please open an issue in the docs repo if we are still manually maintaining a list of features by platform when these are targeted for release
