### ISSUE TITLE
MicroProfile LRA (Long Running Actions) fearutes align to MicroProfile 6.1/7.0

### ISSUE THREAD

**Issue by yakebao** [OpenLiberty/open-liberty#29655]
MicroProfile LRA (Long Running Actions) specification
https://github.com/eclipse/microprofile-lra/
MicroProfile LRA 2.0 released at Mar 7, 2023

As now, OpenLiberty provides feature MicroProfile 6.1 aligns with Jakarta EE 10 spec,
but MicroProfile LRA (Long Running Actions) features was not found .
Do we have a roadmap to provide MicroProfile LRA features to work with  MicroProfile 6.1 ,
or an alternative solution to MicroProfile LRA on OpenLiberty with MicroProfile 6.1.

**Comment by Emily-Jiang** [comment]
Thank you @yakebao for reporting this! Open Liberty does not support MicroProfile LRA, which is why the feature was not found. However, MicroProfile LRA feature can be found in Open Liberty beta release if you want to do some experiment.

**Comment by yakebao** [comment]
Got it . Thank you @Emily-Jiang
