### ISSUE TITLE
Revise autogenerated platform pages 

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/open-liberty#29767]
I did some work on the new autogenerated platform pages to align them with IBM Style and accessibility requirements. I'm hoping we can get these changes added to the generation process in future releases so we dont have to make them manually.

- add H1 heading to start of page
- add intro description to each page
- add headings for each table, with an anchor list at top of page
- provide the platform short name before each table
- remove monospace formatting from feature names in column 1 
- Reverse table order so that on each page, the newest table shows first. Eg MicroProfile 1.2 should be at end of page instead of start.

Here is a draft of the updates

- [MicroProfile platforms](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/platform/MicroProfile.html)
- [Java EE platforms](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/platform/JavaEE.html)
- [Jakarta EE platforms](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/platform/JakartaEE.html)

The updated source files in this folder demonstrate the proper syntax:
https://github.com/OpenLiberty/docs-generated/tree/draft/modules/reference/pages/platform

**Comment by hlhoots** [comment]
Changes merged to tooling docgen generation after review from @dmuelle .  Closing for now.
