### ISSUE TITLE
Feature Test Summary - InstantOn support for Jakarta Embedded Messaging

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#29798]
## Test Strategy

This the test summary for epic [InstantOn support for Jakarta Embedded Messaging
#28238](https://github.com/OpenLiberty/open-liberty/issues/28238)

The test strategy involves running FATs on test machines that are enabled for InstantOn (checkpoint) testing. Both SOE and the orchestrater builds invoked by PR #build run the checkpoint test buckets on machines/environments that support Liberty InstantOn. We also still maintain a continuous InstantOn build that runs daily using the Open Liberty integration branch with the checkpoint tests running in FULL mode. The checkpoint tests are run across Java 11, 17 and 21 in the continuous InstantOn build as well as in SOE runs. The InstantOn checkpoint FAT tests are identified using the @CheckpointTest annotation. This ensures the test is only executed on host systems that support checkpoint (i.e. Linux systems with the right kernel version and criu installed and running OpenJ9).

### List of FAT projects affected
For InstantOn embedded messaging support, a strategy was taken to develop a new FAT bucket instead of enhancing existing buckets. This was to make it easier to reason about the FATs that require full checkpoint supporting hosts. The following buckets are the current set that require full checkpoint supporting hosts:

* io.openliberty.checkpoint_fat_jms

### Test strategy

* What functionality is new or modified by this feature?

The following features have been enabled for Liberty InstantOn by adding the `WLP-InstantOn-Enabled: true` feature manifest header.  This allows the features to be enabled when doing a Liberty InstantOn `checkpoint` action.  Without this the `checkpoint` action would fail when one or more of the following features are enabled.

1. messagingClient-3.0
1. messagingSecurity-3.0
1. messagingServer-3.0
1. wasJmsClient-2.0
1. wasJmsSecurity-1.0
1. wasJmsServer-1.0

* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)

To test this feature we used  existing FAT buckets that tested a wide range of functionality of the embedded messaging features and repurposed them to test InstantOn support.   The test goal was to get a good base of existing tests but to run them in the context of a restored application process where we have applied configuration updates that impact the communication between the messaging client and the messaging server.  The following buckets were repurposed (copied) into the `io.openliberty.checkpoint_fat_jms` FAT:

1. com.ibm.ws.messaging.open_jms20_fat
1. com.ibm.ws.messaging.open_jms20contextSecurity2_fat

The following tests run two sets of tests and repeats them such that one run does a checkpoint/restore of the messaging client which is connecting to a messaging server which starts with out InstantOn, the second run starts the message client without using InstantOn which is connecting to a messaging server which does a checkpoint/restore.  The tests are then repeated against all the EE levels that are supported (EE8 though EE11) for InstantOn.

1. io.openliberty.checkpoint_fat_jms/fat/src/io/openliberty/checkpoint/messaging/JMS20/fat/BucketSet1CpClientTest.java
1. /io.openliberty.checkpoint_fat_jms/fat/src/io/openliberty/checkpoint/messaging/JMS20/fat/BucketSet1CpEngineTest.java
1. /io.openliberty.checkpoint_fat_jms/fat/src/io/openliberty/checkpoint/messaging/JMS20/fat/BucketSet2CpClientTest.java
1. /io.openliberty.checkpoint_fat_jms/fat/src/io/openliberty/checkpoint/messaging/JMS20/fat/BucketSet2CpEngineTest.java

In the test each time the process is restored it is configured with the right port for the messaging client/server to communicate properly.

In order to test messaging security the `/io.openliberty.checkpoint_fat_jms/fat/src/io/openliberty/checkpoint/messaging/JMS20/fat/JMSMDBTest.java` test was derived from the `/com.ibm.ws.messaging.open_jms20contextSecurity2_fat/fat/src/com/ibm/ws/messaging/JMS20/fat/ContextInject/JMSContextInjectTest.java` into the `/io.openliberty.checkpoint_fat_jms/fat/src/io/openliberty/checkpoint/messaging/JMS20/fat/JMSMDBTest.java` test. This test uses an MDB and a test servlet that acts as the messaging client to the MDB.

The test servlet `/io.openliberty.checkpoint_fat_jms/test-applications/MDBTestWeb/src/mdb/test/web/JMSContextInjectServlet.java` is injected with different `JMSContext` objects which have their security credentials configured in the `server.xml`.

The test MDB `/io.openliberty.checkpoint_fat_jms/test-applications/MDBTestApp/src/mdb/test/app/EJBAnnotatedMessageDrivenBean.java` uses the `@MessageDriven` annotation with various `@ActivationConfigProperty` to properly config the messaging queue for the MDB.  The security credentials are configured in the `server.xml`.

For both the messaging client and messaging servers the security credentials in the `server.xml` are parameterized such that they are not available when the application process is checkpointed.  The credentials are then set in the `server.env` before restoring the server process.  The tests confirm that the security credentials are properly read at restore time and the application functions properly.

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

None

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

We rate our confidence level at 3.

**Comment by dave-waddling** [comment]
Hi @tjwatson, thanks for the comprehensive FTS. Please can you give a brief explanation as to why you rate your confidence at 3 and what would be needed to bring it up to a 4? A confidence of 3 is acceptable but it would be helpful to understand where you think testing might be improved/added.

**Comment by tjwatson** [comment]
> A confidence of 3 is acceptable but it would be helpful to understand where you think testing might be improved/added.

Mainly a 3 because of my lack of experience with messaging in general.  I did a best effort to select subset of tests that I thought did adequate coverage of the functionality.  I did have others review the tests and confirm my thinking was sound.  So it is likely just my lack of experience in the area that gives me pause.

**Comment by dave-waddling** [comment]
Thanks, I appreciate the honesty in your assessment and the extra context you provide is reassuring; I'm happy to approve at this time.
