### ISSUE TITLE
[Question] Configure jwtBuilder/jwtConsumer with JWE enabled

### ISSUE THREAD

**Issue by c-koell** [OpenLiberty/open-liberty#29809]
First i tried to configure a jwtBuilder without JWE.

Example server.xml
```
<jwtBuilder issuer="TokenService" id="TokenBuilder" keyStoreRef="jwtKeyStore" keyAlias="authtokenservice" expiresInSeconds="45000" />
<keyStore id="jwtKeyStore" location="${server.config.dir}\jwkkey.p12" password="xxx" />
```
The JWK Endpoint looks like this.
```
{"keys":[{"kty":"RSA","e":"AQAB","use":"sig","kid":"GZiHj9ku9Zq5zb7ynBgiAuOXb4rsrxQcaUSn7HbTZ6o","alg":"RS256","n":"zbQK1TuItx3Bf3nJHEljZDFxAe_a5bMZBwcMRB_2IUV61yxJl9Eh4EeBSWCxTUCrElfHvQB1eEoxTEsFj_R-azakcan0-i8TeXPonCOOgSrJAelzsIamIry_1jBUgJEE4IXyXA1lWvTVo0A_vXUjgkVOAmkNbUJ44d2WMCpijT1iGkY89oF-vddVrCu_NsjuX96DnkZ8mtNln5cjwMNPtIavCfCaLErkEoCjC9ps0xuoWUAldOChX_Zyg-GFh2PA1EDK0eOCdrITgGggKlz5Gd35eknohyG-ZTKIKYUgQh6YKTqMt5e76kBj6bH2lHBu1bA2kNptXE9VlWws0JW85w"}]}
```
The jwtConsumer is configured like this
```
<jwtConsumer id="TokenConsumer" issuer="TokenService" jwkEnabled="true" jwkEndpointUrl="http://localhost:9084/jwt/ibm/api/TokenBuilder/jwk"/>
```
Everythinmg works fine.

Now i changed the jwtBuilder to
```
<jwtBuilder issuer="TokenService" id="TokenBuilder" trustStoreRef="jwtKeyStore" keyManagementKeyAlias="authtokenservice-jwe" 
 keyStoreRef="jwtKeyStore" keyAlias="authtokenservice" expiresInSeconds="45000" />
```
The jwtBuilder creates now a encrypted token.

The jwtConsumer is now unable to read the encrypted token. Maybe someone can give me some hint how i configure the jwtBuilder/jwtConsumer to work fine with encrypted tokens... thanks much !

**Comment by ayoho** [comment]
Hi, @c-koell. The JWT consumer needs to know what key to use to decrypt the data in the JWE. You do that by configuring the `sslRef` and `keyManagementKeyAlias` attributes in the `<jwtConsumer>` element. Note that the JWT builder uses a public key to encrypt the Content Encryption Key of the JWE. The JWT consumer needs the corresponding _private_ key to decrypt the Content Encryption Key. That means you'll need to configure a keystore that contains that private key and point the jwtConsumer to that keystore.

For example, if the private key associated with the public key the jwtBuilder is using is stored in a keystore called `jwtKeyStore` under the alias `authtokenservice-jwe`, your jwtConsumer configuration would need to look something like this:

```XML
<ssl id="mySslConfig" keyStoreRef="jwtKeyStore" ... />
<keyStore id="jwtKeyStore" location="..." />
<jwtConsumer id="TokenConsumer" issuer="TokenService" jwkEnabled="true" jwkEndpointUrl="http://localhost:9084/jwt/ibm/api/TokenBuilder/jwk"
             sslRef="mySslConfig" keyManagementKeyAlias="authtokenservice-jwe"/>
```

Note the addition of the `sslRef` and `keyManagementKeyAlias` attributes in the `<jwtConsumer>` element, as well as the `<ssl>` and `<keyStore>` elements.

**Comment by c-koell** [comment]
@ayoho thank you very much for the clarification !

It works fine now. 
The hint with the sslRef was the game changer :-) 

The documentation for the jwtConsumer is not clearly here...
[Specifies an ID of the SSL configuration that is used to connect to the OpenID Connect provider.]
https://openliberty.io/docs/latest/reference/config/jwtConsumer.html

For the jwtBuilder is the documentation more clear.
https://openliberty.io/docs/latest/reference/config/jwtBuilder.html

Maybe you extend the documentaion for the jwtConsumer a little bit.

**Comment by ayoho** [comment]
Great! I'm glad all is well.

Indeed, it looks like the documentation for the jwtConsumer should be improved. I've opened https://github.com/OpenLiberty/open-liberty/issues/29823 to track getting our docs updated to help more.
