### ISSUE TITLE
A custom error page for a WebContainer exception to avoid possible data disclosure

### ISSUE THREAD

**Issue by andreaminutoibm** [OpenLiberty/open-liberty#29818]
**Describe the use case that you want to enable:**
When the WebContainer throws an exception before the request is dispatched - e.g. an invalid URL-, no application can catch and manage it.
That behavior leads to data disclosure because the exception reports the impacted class and method, revealing that the application runtime is an IBM application server.
What I need is an attribute for the entry <webContainer> where I can configure a custom error page that shows only a generic error.

**Describe why this is important to you:**
This data disclosure kind of problem is reported by all the current pentest tools and I need a solution to help my customer to pass a pentest.

**Additional context**
For example, an attribute like: <webContainer **errorPage**="/errors/invalidurl.html" ... />

**Comment by pmd1nh** [comment]
There is a configurable message for missing context root using `<httpDispatcher>` in the server.xml.

https://www.ibm.com/docs/en/was-liberty/core?topic=configuration-httpdispatcher

`<httpDispatcher appOrContextRootMissingMessage="I am a default Error Message for missing context root"/>`

**Comment by pmd1nh** [comment]
If the context root is valid but there is no error-page from the application, you can use the webContainer property to set a simple text response.

   `<webContainer com.ibm.ws.webcontainer.displaytextwhennoerrorpagedefined="I am a default Error Page"/>  `

**Comment by amasson88** [comment]
That would be nice to have it safe by default.

**Comment by andreaminutoibm** [comment]
Thank you all. I tried what you suggested and they worked very well. I'll close the issue.

**Comment by andreaminutoibm** [comment]
There is no need to a new feature because what I need is already implemented though not well documented.
