### ISSUE TITLE
Incorrect substitution values in OpenAPI message

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#29876]
Need to check whether the `OPENAPI_MERGE_INVALID_NAME_CWWKO1666W` can be used for both MP Config properties and server.xml element names.

The message is only written to accept an MP Config property name.

**Comment by benjamin-confino** [comment]
Are you asking if `OPEN_API_SLASH_IN_APPLICATION_CWWKO1678W` and `OPEN_API_SLASH_IN_MODULE_CWWKO1679W` can be removed and `OPENAPI_MERGE_INVALID_NAME_CWWKO1666W` used in their place?

**Comment by Azquelt** [comment]
No, I'm asking if `OPENAPI_MERGE_INVALID_NAME_CWWKO1666W` is the correct message in each code path where it's used.

I guess there are two questions to answer

1. Is the message specific to MP Config?
2. Is there a code path where we emit this message due to a problem with config from the server.xml?

If the answer to both is "yes" then we may need to reword the message, or create a new message for the server.xml path.

**Comment by benjamin-confino** [comment]
The answer is that we do put app/module names from server.xml into the code that emits `OPENAPI_MERGE_INVALID_NAME_CWWKO1666W` but as written the regex will accept literally any string except an empty one. 

After discussion on slack we're going to only make a minimal change to ensure we don't break any old apps.
