### ISSUE TITLE
Feature Test Summary for MP Rest Client-4.0

### ISSUE THREAD

**Issue by jim-krueger** [OpenLiberty/open-liberty#29871]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

Existing MP Rest Client tests from previous EE versions were updated to repeat with MP Rest Client 4.0 and other EE 10 features. 

### New FAT projects added

* io.openliberty.jakarta.rest.4.0.internal_fat_tck   

### List of FAT projects affected

* com.ibm.ws.microprofile.rest.client_fat

### Test strategy

* What functionality is new or modified by this feature?

- mpRestClient-4.0 will no be compatible with EE10 and tolerate EE11
- Users do not need create a URI themselves to create a Client instance, instead they can pass a String
```
RestClientBuilder.newBuilder()
                             .baseUri("http://example.com")
                             .build(SomeClient.class);
```
- Users can set HTTP Headers on a per instance basis by calling the
`RestClientBuilder.header(String,Object)` method.
```
RestClientBuilder.newBuilder()
                             .baseUri(someUri or String)
                             .header("Some-Header", headerValueObj)
                             .build(SomeClient.class);
```

* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)

All existing positive and negative tests from previous versions of MP Rest Cleint were left unchanged.  All new functionality added in MP Rest Client 4.0 is fully tested within the internal TCK FAT that was added.

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

None

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

**Answer:  4**

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by ayoho** [comment]
LGTM 👍
