### ISSUE TITLE
SQLException handling/reporting in Jakarta Data

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#29934]
RepositoryImpl has a TODO comment,
```
                // TODO If this ever becomes real code, it should be delegated to the JDBC integration layer
                // where there is more thorough logic that takes into account configuration and database differences
```
around some approximate/incomplete code for identifying what SQLExceptions mean.  We should figure out what best to do here and remove the TODO comment after updating it.

**Comment by mswatosh** [comment]
fixed in #30038
