### ISSUE TITLE
Feature Test Summary `mpOpenAPI-4.0`

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#29962]
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

### List of FAT projects affected

* `com.ibm.ws.microprofile.openapi_fat`
* `io.openliberty.microprofile.openapi.2.0.internal_fat`
* `io.openliberty.microprofile.openapi.4.0.internal_fat`
* `io.openliberty.microprofile.openapi.4.0.internal_fat_tck`

### Test strategy

* What functionality is new or modified by this feature?
* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)
* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

#### Support OpenAPI 3.1 and 3.0

OpenAPI documentation can be produced in OpenAPI 3.1 (new) or 3.0 format. Server.xml configuration used to select which version is produced.

* SmallRye OpenAPI tests
  * the functionality to produce either output is provided by SmallRye OpenAPI
  * they have fairly rigorous tests for what's output in the places where the spec versions differ smallrye/smallrye-open-api#1918
* TCK tests
  * the spec only requires 3.1 format so the TCK tests have all been updated to expect 3.1
* FAT tests
  * Almost all existing FAT tests do not assert the OpenAPI version directly and are repeated against the new feature with 3.1 output
  * New FAT test added for configuration: [OpenAPIVersionTest](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/version/OpenAPIVersionTest.java#L48)
    * configuration attribute changes the OpenAPI version of the output
    * spot check parts of the document that should change between 3.0 and 3.1 are correct for each version
    * configuration can be updated dynamically
    * invalid values result in warning log messages

#### All applications documented by default

* New FAT test for default inclusion behaviour with no configuration [MergeConfigServerXMLTest.testDefaultInclusion](https://github.com/OpenLiberty/open-liberty/pull/29957/files#diff-b8bacb837976659f33b88f5e8b5047f32474cde9fd4600df7e1d8833e76d3abcR98)
  * Some existing tests relying on the old default behaviour updated to provide explicit config so they can be repeated against `mpOpenAPI-4.0`

#### New server.xml configuration to select which applications are documented

mpOpenAPI-2.0+ has had MP Config-based configuration for this for a while, so the new server.xml based options are be backported to mpOpenAPI-2.0+ to reduce confusion.

* Existing inclusion/exclusion tests ported to the new configuration format `MergeConfigServerXMLTest`
* New FAT tests for application and module inclusion configuration
  * test configuration can be updated dynamically
  * test invalid configuration results in appropriate warnings messages

#### New server.xml configuration to override `info` section of OpenAPI document

mpOpenAPI-2.0+ has had MP Config-based configuration for this for a while, so the new server.xml based options are be backported to mpOpenAPI-2.0+ to reduce confusion.

* Existing FAT tests for overriding info ported to the new configuration format `MergeConfigServerXMLTest` (`testInfo*` methods)
* Test new warning messages for invalid configuration

#### Updated validation for OpenAPI 3.1

Some of the validation rules are different between OpenAPI 3.0 and OpenAPI 3.1

* Add unit tests for new validation rules
* Add new FAT test for each new validation case
* Repeat existing validation tests for cases where validation rules have not changed

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

**Comment by dave-waddling** [comment]
Hi @Azquelt, thanks for completing this FTS and for the quick chat via DM. The testing seems thorough, the coverage is appropriate, and so the only things gating approval are a bit of defect work (as per Slack) and the results of this weekend's SOE.
