### ISSUE TITLE
For clarity modify text related to attach api in the Liberty server command

### ISSUE THREAD

**Issue by ajaybhalodia** [OpenLiberty/open-liberty#30045]
This is in reference to github item to make documentation changes:
https://github.ibm.com/websphere/liberty-docs/issues/4098

The comment in server command in wlp/bin folder contains information for java attach API where it states:
"# Add -Dcom.ibm.tools.attach.enable=yes to allow self-attach on z/OS"

Suggesting document change to remove the above and add:
# Support for the Attach API is enabled by default on all platforms except z/OS®
# To enable Attach API on z/OS add "-Dcom.ibm.tools.attach.enable=yes" as a JVM argument.

**Comment by dmuelle** [comment]
Changes to be made in `~/open-liberty/dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server` file

**Comment by ajaybhalodia** [comment]
Yes that is correct the document changes are to be made in
`~/open-liberty/dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server file`

**Comment by NottyCode** [comment]
Open Liberty doesn't support z/OS so making a change to the server script to document z/OS specific behaviour would not be appropriate.

**Comment by NottyCode** [comment]
Reopening because after re-reading the suggestion was to effectively remove bleeding for z/OS behaviour for commercial upstream to Open Liberty.
