### ISSUE TITLE
FT 1.1 Add getFailure() method to ExecutionContext

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#3017]
The `ExecutionContext` is only available to user code in the `FallbackHandler`. This new method should return the exception which caused the failure.

eclipse/microprofile-fault-tolerance#224

**Comment by hutchig** [comment]
The TCK testcase that fails when the implementation is not there is: 
org.eclipse.microprofile.fault.tolerance.tck.testClassLevelFallbackSuccess
With the following:
dev/com.ibm.ws.microprofile.faulttolerance_fat_tck/build/libs/autoFVT/results/mvnOutput_TCK
ests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.57 sec <<< FAILURE! - in TestSuite                                                                                                                          testClassLevelFallbackSuccess(org.eclipse.microprofile.fault.tolerance.tck.FallbackTest)  Time elapsed: 1.731 sec  <<< FAILURE!                                                                                               java.lang.NoSuchMethodError: org.eclipse.microprofile.faulttolerance.ExecutionContext.getFailure()Ljava/lang/Throwable;                                                                                                               at org.eclipse.microprofile.fault.tolerance.tck.fallback.clientserver.SecondStringFallbackHandler.handle(SecondStringFallbackHandler.java:39)                                                                                 at org.eclipse.microprofile.fault.tolerance.tck.fallback.clientserver.SecondStringFallbackHandler.handle(SecondStringFallbackHandler.java:34)                                                                                 at com.ibm.ws.microprofile.faulttolerance.impl.policy.FallbackPolicyImpl.lambda$getFallbackFunction$0(FallbackPolicyImpl.java:33)                                                                                             at com.ibm.ws.microprofile.faulttolerance.impl.sync.SynchronousExecutorImpl.lambda$execute$2(SynchronousExecutorImpl.java:137)                                                                                                at net.jodah.failsafe.Functions$13.apply(Functions.java:284)                                                                                                                                                                  at net.jodah.failsafe.SyncFailsafe.fallbackFor(SyncFailsafe.java:176)                                                                                                                                                         at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:158)                                                                                                                                                                at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56)                                                                                                                                                                  at com.ibm.ws.microprofile.faulttolerance.impl.sync.SynchronousExecutorImpl.execute(SynchronousExecutorImpl.java:147)                                                                                                         at com.ibm.ws.microprofile.faulttolerance.cdi.FaultToleranceInterceptor.execute(FaultToleranceInterceptor.java:239)                                                                                                           at com.ibm.ws.microprofile.faulttolerance.cdi.FaultToleranceInterceptor.executeFT(FaultToleranceInterceptor.java:75)                                                                                                          at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                                                                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                                                                              at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:85)
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:73)
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:57)
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
