### ISSUE TITLE
A client request which sends `tracestate` header to JAX-RS API does not result in `tracestate` being propagated with TextMapPropagator

### ISSUE THREAD

**Issue by JDUNNIN** [OpenLiberty/open-liberty#30271]
**Describe the bug**  

If there is a stack trace, please include the FULL stack trace (without any `[internal classes]` lines in it). To find the full stack trace, you may need to check in `$WLP_OUTPUT_DIR/messages.log`

Related to issue #30260 

Calling a JAX-RS API with headers `baggage=userId=alice,serverNode=DF%2028,isProduction=false` and `tracestate=rojo=00f067aa0ba902b7,congo=t61rcWkgMzE` (doc examples), I can see the headers on the inbound request to the server, but when `TextMapPropagator` is called, only `baggage` and the created `traceparent` are provided. 

Some trace entries in server to support this:
```
Request headers:
{accept-encoding=[gzip], baggage=[userId=alice,serverNode=DF%2028,isProduction=false], connection=[Keep-Alive], content-type=[application/json], Host=[localhost:33957], tracestate=[rojo=00f067aa0ba902b7,congo=t61rcWkgMzE], User-Agent=[okhttp/4.7.2]}
...
OTEL: InvocationBuilderSetter.set called for key traceparent
OTEL: Adding header traceparent with value 00-857639bc42c761bd3527bb40961b68ef-a0b00a20de2b8e06-01
OTEL: InvocationBuilderSetter.set called for key baggage
OTEL: Adding header baggage with value isProduction=false,serverNode=DF%2028,userId=Alice
// debug
OTEL: Span.current().getSpanContext().getTraceState(): ArrayBasedTraceState{entries=[]}
```
The Java code in use within the JAX-RS API:
```

import io.openliberty.microprofile.telemetry.spi.OpenTelemetryAccessor;
import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.SpanKind;
import io.opentelemetry.context.Context;
import io.opentelemetry.context.propagation.TextMapPropagator;
import io.opentelemetry.context.propagation.TextMapSetter;

...

            TextMapPropagator textMapPropagator = OpenTelemetryAccessor.getOpenTelemetryInfo().getOpenTelemetry().getPropagators().getTextMapPropagator();
            textMapPropagator.inject(Context.current(), builder, TEXT_MAP_SETTER);

            builder.post(payload)

...
    private static class InvocationBuilderSetter implements TextMapSetter<Builder> {
        @SuppressWarnings("null")
        @Override
        public void set(Builder carrier, String key, String value) {
            Tr.debug(tc, "OTEL: InvocationBuilderSetter.set called for key {0}", key);
            if (carrier == null) {
                return;
            }
            carrier.header(key, value);
            Tr.debug(tc, "OTEL: Adding header {0} with value {1}", key, value);
        }
    }
```
If it is of use, we create our spans using:
```
            this.span = openTelemetry.getTracer(PRODUCT_SCOPE_NAME)
                    .spanBuilder(this.name)
                    .setSpanKind(this.spanKind).startSpan();
            this.scope = this.span.makeCurrent();
```

**Steps to Reproduce**  
Steps to reproduce the bug
- Deploy a JAX-RS API and have it use a `TextMapPropagator` to call `.inject(...)`.
- Send a request with described headers
- See in trace `tracestate` is not called as part of `inject` as expected.

**Expected behavior**  

When a client request includes `tracestate`  header, this should be set in the context for spans

**Diagnostic information:**  
 - OpenLiberty Version: WebSphere Application Server 24.0.0.9 (with temp iFix OLGH28891 related to OTEL accessor methods)
 - Affected feature(s) [mpTelemetry-2.0]
 - Java Version: IBM Semeru Runtime Open Edition (17.0.12+7)
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**

**Comment by Azquelt** [comment]
Here's how I believe it should work whenever the w3c trace propagator is enabled:

- When receiving the request via servlet or Jakarta REST, the `tracestate` header should be parsed and stored as a `TraceState` object in the `SpanContext`
  - use `Span.current().getSpanContext().getTraceState()` to check that this happens
- When creating a new span, the `TraceState` should be copied from the parent context
  - after creating a new span, `Span.current().getSpanContext().getTraceState()` should still contain the data
  - can't find where in the spec this is explicitly stated, but the Java implementation [does appear to be doing this](https://github.com/open-telemetry/opentelemetry-java/blob/v1.41.0/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpanBuilder.java#L212-L221)
- When making a request, the `TraceState` object should be serialized into a `tracestate` header
  - if the request is made via MP Rest Client or Jakarta REST Client, then liberty should do this automatically and the header should be seen on the outgoing request
  - if the user is manually calling the `TextMapPropagator` as Jack is here, their `TextMapSetter` should be called with `key="tracestate"` and `value` = the serialized `TraceState` object.

**Comment by JDUNNIN** [comment]
Confirmed that at the earliest point in our code,  before we do anything with Spans etc, calling `Span.current().getSpanContext().getTraceState()` still shows an empty array for entries.

**Comment by Yas-Franco** [comment]
@JDUNNIN 

Here is the pr with the tests for this: https://github.com/OpenLiberty/open-liberty/pull/30356

I have found that the tracestate is propagated on an outgoing request. This is when the tracestate is sent through a request header (see `testTraceStateFromHeaders`) or when it is manually added to the span context (see `testTraceState`).  
However, I did find:
- The `tracestate` is not sent through the request headers if the span's `tracestate` is an empty entry
- The `tracestate` is not set if `traceparent` is missing

We can look through your application set up together to compare these results if that would be helpful

**Comment by JDUNNIN** [comment]
Thanks @yasmin-aumeeruddy I'll take a look soon, likely next week, possible the caveats are the cause. Will be in touch.

**Comment by JDUNNIN** [comment]
@yasmin-aumeeruddy can now confirm it would have been caused by "The tracestate is not set if traceparent is missing" as we wouldn't have had our client generating a traceparent at the time. Now we do have that, it works as expected. Happy for this to be closed as it matches the W3C Trace Context spec.
