### ISSUE TITLE
Failed to install versionless features with JEE10 and MP7 plafforms

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/open-liberty#30363]
**Describe the bug**  

Failed to install features by server.xml with versionless features

```
[INFO] Launching defaultServer (Open Liberty 24.0.0.12/wlp-1.0.96.cl241220241119-0657) on Eclipse OpenJ9 VM, version 11.0.18+10 (en_CA)
[INFO] [AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[INFO] [AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /Users/gkwan/tasks/CNAI/guides/working/getting-started/versionless/guide-getting-started/finish/target/liberty/wlp/usr/servers/defaultServer/configDropins/overrides/liberty-plugin-variable-config.xml
[INFO] [ERROR   ] CWWKF0001E: A feature definition could not be found for mphealth
[INFO] [ERROR   ] CWWKF0001E: A feature definition could not be found for jsonb
[INFO] [ERROR   ] CWWKF0001E: A feature definition could not be found for jsonp
[INFO] [ERROR   ] CWWKF0001E: A feature definition could not be found for restfulws
[INFO] [ERROR   ] CWWKF0001E: A feature definition could not be found for cdi
[INFO] [ERROR   ] CWWKF0001E: A feature definition could not be found for mpconfig
[INFO] [ERROR   ] CWWKF0001E: A feature definition could not be found for mpmetrics
[INFO] [AUDIT   ] CWWKF0012I: The server installed the following features: [].
```

**Steps to Reproduce**  
- use Java 11+
- `git clone https://github.com/OpenLiberty/guide-getting-started.git -b versionless`
- `cd guide-getting-started/finish`
- `mvn liberty:run`
- got above errors

**Expected behavior**  
Liberty runtime should be started successfully with the required features from server.xml

**Diagnostic information:**  
 - OpenLiberty Version: 24.0.0.12
 - Affected feature(s): MP7
 - Java Version: Java 11, 17, 21
 - server.xml configuration (WITHOUT sensitive information like passwords)
   - https://github.com/OpenLiberty/guide-getting-started/blob/versionless/finish/src/main/liberty/config/server.xml 
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`
   - the messages.log has no exception stack traces 

**Additional context**  
- there is no problem if switch to use MP 6.1

**Comment by gkwan-ibm** [comment]
hi @rsherget, I assigned to you because you addressed probably the related issue #29868

**Comment by rsherget** [comment]
Main problem here is featureUtility installServerFeatures with this configuration does not install any features, looking into it

**Comment by rsherget** [comment]
The reason this didn't work was that the mpMetrics feature file was not properly configured to allow resolution with microprofile-7.0. The PR fixes that so that mpMetrics can resolve.
