### ISSUE TITLE
Improve Performance of Microprofile Metrics in RequestScoped Beans

### ISSUE THREAD

**Issue by jdmcclur** [OpenLiberty/open-liberty#304]
There is a small overhead when enabling the metrics feature in RequestScoped classes. It would be nice to improve this performance.

**Comment by donbourne** [comment]
First improvement - looking to improve minor performance issue on Metadata construction.

![image](https://user-images.githubusercontent.com/17110503/31587302-6810ab3e-b1ad-11e7-885a-2aa5e4daf9c7.png)

**Comment by donbourne** [comment]
After Metadata construction improvement...

![image](https://user-images.githubusercontent.com/17110503/31634577-09092d42-b292-11e7-9d65-7898029b2541.png)

**Comment by donbourne** [comment]
Metadata constructor issue fixed by #627

**Comment by donbourne** [comment]
Second improvement -     

Redundant metrics registration - (affects @RequestScoped requests) 

Every construction of MetricsInterceptor results in all of the constructors and methods of the class being checked for metrics annotations.  Those annotation definitions, together with class/method name, are then used to compute metric names.  Those metric names are used to register the corresponding metrics in the MetricsRegistry.  This happens on every request for metrics-annotated @RequestScoped services.

- In MetricsInterceptor.metrics method, after registering all metrics for a class, store the FQ classname of the target bean in a static Set associated with the MetricsInterceptor.  On subsequent hits to MetricsInterceptor.metrics method check to see if FQ classname has already been processed before wasting any time on metric registration steps. 
- would we need to clear this cache ever?  If you don't clear it any new metrics added to elements after initial call to MetricsInterceptor.metrics won't be put into the MetricsRegistry so won't appear in /metrics calls.  Ideally you'd want to clear a classname from the cache when that class' bytecode is changed (eg. via WDT changing a method, for example).
- note that MetricsInterceptor.metrics calls proceed method...which eventually calls MeteredInterceptor.meteredConstructor -- which marks the metric for that... which still has to happen... So -- jump past registerMetrics calls, but don't skip the proceed call. 

![image](https://user-images.githubusercontent.com/17110503/31965847-995d1d14-b8d6-11e7-8ae4-2a1022437c29.png)

**Comment by jdmcclur** [comment]
I think perf is looking good here, so closing.
