### ISSUE TITLE
Allow MP Config to access server.xml variables and appProperties elements without restart

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#3047]
There are two parts to this issue;

1. Make `server.xml` variables available by (partially) exposing the contents of ConfigVariableRegistry to MP Config through a new internal DS.

2. Since the proposed `<appProperties>` element is inside `<application>`, any changes result in a full application restart. What we want is for the app manager to (some how) know not to restart the app for changes to `<appProperties>`.

**Comment by ibmfjk** [comment]
How to check if the solution is included in Liberty 18002 ?
Does it support update action to variables in server.xml

**Comment by tevans78** [comment]
@ibmfjk this was not included in Liberty 18.0.0.2. When it is, dynamic updates to variables should be supported.

**Comment by ibmfjk** [comment]
@tevans78 Thanks! is there plan to include it in 18003 or 18004?

**Comment by tevans78** [comment]
@ibmfjk it should be in 18003 ... are you an IBMer?

**Comment by ibmfjk** [comment]
@tevans78 yes, I am IBMer, want to leverage this feature once it is in.
