### ISSUE TITLE
Chkpii error in com.ibm.ws.anno project

### ISSUE THREAD

**Issue by pnickoll** [OpenLiberty/open-liberty#3064]
Chkpii error in \com.ibm.ws.anno\resources\com\ibm\ws\anno\resources\internal\AnnoMessages.nlsprops

  ANNOMESSAGES.NLSPROPS        PORTAL-PRB  128   (W) UNIX file (newline=x'0A') should be converted to PC-DOS (newline=x'0D0A') format in order to be translated.
                                           921   Message ID must be 'aaaaannnns: ' (a=letter,n=number,s=A,E,I,W).  Found: 'CWWKC00075W: '.  Line: 503

It looks like that message number has one too many 0's in.

**Comment by jimblye** [comment]
Fixed in Pull Request #4333
