### ISSUE TITLE
mpOpenTracing-1.0 prevents @Provider from executing properly

### ISSUE THREAD

**Issue by bpaskin** [OpenLiberty/open-liberty#3069]
When using MP in 18.0.0.1 and having JAX-RS registered with `@RequestScoped` with a `@Provider` that overrides the `ExceptionMapper` the overridden method is never called.  The class itself is instantiate, but the method is never called.  Once mpOpenTracing-1.0 is removed the `ExceptionMapper` works correctly.
```
@Provider
public class ErrorResponseMapper implements ExceptionMapper<WebApplicationException> {
	@Override
	public Response toResponse(WebApplicationException ex) {
		Error error = new Error();
		error.setStatus(ex.getResponse().getStatus());
		error.setMessage("Error processing your request: " + ex.getMessage());
		return Response.serverError().type(MediaType.APPLICATION_JSON).entity(error).build();
	}
}
```
```
@RequestScoped
@Path("v1") 
public class CompactDiscs {...}
```
Brian
[SimpleRSError.zip](https://github.com/OpenLiberty/open-liberty/files/1899703/SimpleRSError.zip)

**Comment by andymc12** [comment]
This should be fixed by issue #9293 / PR #9585 which went into 19.0.0.12.
