### ISSUE TITLE
permissions.xml in standalone RAR

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#3070]
"As a user of JCA in Liberty, I want permissions.xml to be honored for standalone RARs, so that the application server can grant the Java 2 security permissions that are needed by the resource adapter code."

Need to obtain and set the ProtectionDomain on the ClassLoaderConfiguration in
com.ibm.ws.jca.internal.ResourceAdapterService.createRarClassLoader()

Some notes from Teddy on this:
_What needs to happen is that we need to obtain the adaptable Container object and call the adapt method to obtain the PermissionsConfig object from the archive.  Then do like DeployedAppInfoBase does in getProtectionDomain and use that answer to set the protection domain in the ClassLoaderConfiguration object used for the rar classloader._

_We need confirmation that these RAR classloaders are for RARs that are not part of an application.  If the RARs are inside an app, then the RARDeployedAppInfo should take care of that path and merge the right permissions already from the app's permissions.xml.  This distinction matters because it affects what permissions are granted to the RAR._

**Comment by nmittles** [comment]
#build
