### ISSUE TITLE
what's releaseNeeded do?

### ISSUE THREAD

**Issue by brutif** [OpenLiberty/open-liberty#31]
In the instructions at 
https://github.com/OpenLiberty/open-liberty, 
what does step 4, 

Perform a local release

./gradlew releaseNeeded

achieve?    (perhaps an update to this page to add explanation would be helpful)

**Comment by cbridgha** [comment]
opened https://github.com/OpenLiberty/open-liberty/pull/88

**Comment by cbridgha** [comment]
Merged fix  thanks!
