### ISSUE TITLE
Fault Tolerance 1.1 TCK Clean Run Status

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#3100]
com.ibm.ws.microprofile.faulttolerance_git_fat_tck:buildandrun -Dfat.test.mode=experimental

Once a tag is available this will become

com.ibm.ws.microprofile.faulttolerance_git_fat_tck:buildandrun -Dfat.test.mode=experimental -Dbranch=1.1

Once https://github.ibm.com/APTribe/CSI-Squad-Backlog/issues/372 (current outlook Monday 16th)
we can run this in batch. 

   Currently 28 failing tests as of todays date:

AsyncTimeoutTest testAsyncClassLevelTimeout
AsyncTimeoutTest testAsyncNoTimeout
AsyncTimeoutTest testAsyncTimeout
AsynchronousTest testClassLevelAsyncIsFinished
AsynchronousTest testAsyncIsNotFinished
AsynchronousTest testClassLevelAsyncIsNotFinished
AsynchronousTest testAsyncIsFinished
CircuitBreakerRetryTest testClassLevelCircuitOpenWithFewRetries
CircuitBreakerRetryTest testCircuitOpenWithMultiTimeouts
CircuitBreakerRetryTest testCircuitOpenWithFewRetries
CircuitBreakerRetryTest testClassLevelCircuitOpenWithMoreRetries
CircuitBreakerRetryTest testCircuitOpenWithMoreRetries
FallbackTest testClassLevelFallbackSuccess
TimeoutMethodConfigTest testTimeout
BulkheadSynchTest testBulkheadClassSemaphore10
BulkheadSynchTest testBulkheadClassSemaphore3
BulkheadSynchTest testBulkheadMethodSemaphoreDefault
BulkheadSynchTest testBulkheadMethodSemaphore3
BulkheadSynchTest testBulkheadClassSemaphoreDefault
BulkheadSynchTest testBulkheadMethodSemaphore10
CircuitBreakerConfigGlobalTest testCircuitDefaultSuccessThreshold
CircuitBreakerConfigOnMethodTest testCircuitDefaultSuccessThreshold
IncompatibleFallbackMethodWithArgsTest test
InvalidCircuitBreakerDelayTest test
InvalidCircuitBreakerFailureReqVol0Test test
InvalidCircuitBreakerFailureReqVolNegTest test
InvalidRetryMaxRetriesTest test

**Comment by hutchig** [comment]
New error in log from FT 1.0:
public class FaultToleranceGitTckLauncher {
+                          "CWMFT5019W", // The Retry policy jitter delay of 200 Millis is not valid because
+                          // the jitter delay must be less than the delay duration of 1 Micros
making PR now...

**Comment by hutchig** [comment]
1.3.0 had same errors - so I need to investigate further.

**Comment by hutchig** [comment]
Retesting with:
<groupId>com.ibm.ws.org.jboss.arquillian.container</groupId>
  <artifactId>arquillian-liberty-managed</artifactId>
  <version>999.0.20180329212918</version> 
  <name>Arquillian Container Liberty Managed</name>
  <description>Liberty Managed Container integration for the Arquillian Project</description>

**Comment by hutchig** [comment]
With the ideal settings:
$ git diff . | grep "^+"
+++ b/dev/com.ibm.ws.microprofile.faulttolerance_git_fat_tck/publish/tckRunner/pom.xml
+        <arquillian.version>1.4.0.Final</arquillian.version> 
+++ b/dev/com.ibm.ws.microprofile.faulttolerance_git_fat_tck/publish/tckRunner/tck/pom.xml
+        <default.arquillian.version>1.4.0.Final</default.arquillian.version>
+            <version>1.4.0.Final</version>
+        <dependency>
+            <groupId>io.openliberty.arquillian</groupId>
+            <artifactId>arquillian-liberty-managed</artifactId>
+            <version>1.0.0-SNAPSHOT</version> 
+            <scope>test</scope>
+        </dependency>
+
All the tests fail! So backing off from that...

**Comment by hutchig** [comment]
testBulkheadClassSemaphore3 seems to suceed fine when run on its own.

**Comment by hutchig** [comment]
[messages.log](https://github.com/OpenLiberty/open-liberty/files/1989517/messages.log)
Search the file above for "[09/05/18 17:49:13:890 BST] 000001ad SystemOut                                                    O 429 17:49:13:89: java.util.concurrent.ExecutionException: java.lang.AssertionError: Unexpected exceptionA metric named ft.org.eclipse.microprofile.fault.tolerance.tck.bulkhead.clientserver.Bulkhead3ClassSemaphoreBean.test.bulkhead.concurrentExecutions already exists
"  This is the bean used in the failing test and the exception may be occurring at the correct time to scupper @Azquelt ?? Coincidentally there are two tests called testBulkheadClassSemaphore3
in two packages.

**Comment by hutchig** [comment]
[ffdc_18.05.09_17.47.51.0.log](https://github.com/OpenLiberty/open-liberty/files/1989530/ffdc_18.05.09_17.47.51.0.log)
Has Stack Dump = java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.ibm.ws.threading.internal.PolicyTaskFutureImpl.get(PolicyTaskFutureImpl.java:559)
	at com.ibm.ws.microprofile.faulttolerance.impl.async.QueuedFuture.get(QueuedFuture.java:153)
	at org.eclipse.microprofile.fault.tolerance.tck.bulkhead.Utils.handleResults(Utils.java:55)
	at org.eclipse.microprofile.fault.tolerance.tck.bulkhead.BulkheadAsynchTest.loop(BulkheadAsynchTest.java:224)

**Comment by Azquelt** [comment]
> Unexpected exceptionA metric named ft.org.eclipse.microprofile.fault.tolerance.tck.bulkhead.clientserver.Bulkhead3ClassSemaphoreBean.test.bulkhead.concurrentExecutions already exists

Yeah, that bit is my fault. I realised the metrics code doesn't clean up metrics properly, or tolerate he same metric being added twice.

**Comment by hutchig** [comment]
With the latest PRs from Andrew, Ben and myself plus the removal of testable=true from the ShouldThrowExceptions I get a clean run of 177 tests.
