### ISSUE TITLE
In 18.0.0.1, the minify option is not making the runnable JAR package any smaller

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/open-liberty#3102]
When I run `package` with the `--include=minify,runnable` option, 18.0.0.1 doesn't actually make the package any smaller than when I run it without the `minify` option.

In 17.0.0.4, it works as expected: My package is reduced from 97MB to 36MB.

To reproduce:

1. Create an app with just (for example) MicroProfile-1.3 in the `server.xml`.
2. Run the app on a full installation of 18.0.0.1 (I was using Maven so I have the full Open Liberty package): `bin/server package sampleAppServer --archive=test.jar --include=minify,runnable`
3. Check the file size of the `test.jar` file.
3. Run the same app on 17.0.0.4 then check the file size of the `test.jar` file again.

**Comment by hlhoots** [comment]
Chuck and Brent: I think I had a quick look at this the other day (randomly saw the post in slack about it).  I believe that if you just do a --include=minify it shrinks the server size as expected, however if you include minify and runnable, then the server size does not go down.  So you may need to look at the path for runnable in the code to troubleshoot further.
