### ISSUE TITLE
Connect JPA 2.2 Features with Java EE 8 Features

### ISSUE THREAD

**Issue by jgrassel** [OpenLiberty/open-liberty#313]
When the JavaEE 8 features become available (javaeeClient-8.0, javaeeCompatible-8.0, javaeePlatform-8.0), properly connect the JPA 2.2 features with them, as the initial delivery of the JPA 2.2 features have them connected to the 7.0 versions of those features.

**Comment by aguibert** [comment]
javaeeCompatible-8.0 was addressed in PR #659 

javaeeClient-8.0 will be addressed in PR #812

javaee-8.0 will be addressed under story #811
