### ISSUE TITLE
Connect JPA 2.2 Feature with CDI 2.0 Feature

### ISSUE THREAD

**Issue by jgrassel** [OpenLiberty/open-liberty#315]
Work item to track the progress for creating com.ibm.websphere.appserver.jpaContainer2.2-cdi2.0 and com.ibm.ws.jpa.container.v22.cdi - the linkage between the JPA 2.2 feature and CDI 2.0.

This issue should provide FAT testing for CDI Injection in AttributeConverters

**Comment by tevans78** [comment]
@jgrassel do you want me to create a jpaContainer2.2-cdi2.0 auto-feature under #250 ?

**Comment by jgrassel** [comment]
@tevans78 Yeah, that would be great!

**Comment by jgrassel** [comment]
Closing, the CDI-2.0 and JPA 2.2 features are now working with eachother.

**Comment by tevans78** [comment]
I think that PR #659 from @aguibert is enough to resolve this issue. Will close once it's all in the master branches.
