### ISSUE TITLE
Daily builds should include all content

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/open-liberty#317]
The daily builds published on openliberty.io only include GA features, not features still under development.  They should include all content for people to try.   The build produces an -all zip that's currently 84MB vs the 76MB GA zip.  We need to publish the -all zip. 

Related to this, the size on the download button on the landing page says 84MB, which I presume corresponds to an 'all' size, when it should only have the GA content.

**Comment by cbridgha** [comment]
This is a good point, and we just switched to creating two versions a couple days ago.

@fritze2 can we make this switch?  Our "Release" drivers that we'll be manually pushing will use the filtered copy - but the Nightly release should push the *-all" versions

**Comment by fritze2** [comment]
Nightly builds will start publishing the image with all features when https://github.com/OpenLiberty/open-liberty/pull/450 is promoted to master.
