### ISSUE TITLE
[spring boot feature] understand how spring logging and liberty logging interact

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#3179]
There may be no issues here, but we need to investigate how spring logging works with our own Liberty logging.

See
https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html

**Comment by tjwatson** [comment]
Removing from Epic.  I don't think there is anything to do here.  Anjum will update with comments on her findings.

**Comment by anjumfatima90** [comment]
Used spring-boot-starter-log4j2 in the application and logged some stuff on the console from the application. It did not require any changes to be done to liberty runtime and worked perfectly with all the other liberty logging.
