### ISSUE TITLE
Move all EE8 features from noship/beta to ga

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#323]
All EE8 features are being developed under their respective individual features, and can be considered "complete" once they have been released in OpenLiberty nightly dev builds and their corresponding feature is closed.

Once all EE8 features are complete, we can do a bulk update of the following features from `kind=beta` to `kind=ga`:
- jsf-2.3
- security-1.0
- jsonb-1.0
- jsonp-1.1
- jaxrs-2.1
- bval-2.0
- cdi-2.0
- servlet-4.0
- jpa-2.2
- javamail-1.6

**Comment by kwsutter** [comment]
Java EE features are not complete, complete until they pass the CTS or TCK.  So, we need to be aware of that effort before marking anything "ga".

**Comment by aguibert** [comment]
Based on discussion with @kwsutter we are going to start the effort of moving EE8 features to GA now
