### ISSUE TITLE
Features' AppliesTo should use "Open" edition instead of "OPEN"

### ISSUE THREAD

**Issue by ericglau** [OpenLiberty/open-liberty#3235]
#3215 refers to "OPEN" and "OPEN_WEB" editions.  However, the correct editions should be "Open" and "Open_Web" (case sensitive) to match with the editions in lib/versions/openliberty.properties

**Comment by ericglau** [comment]
#3246 reverted PR #3215.  Affected features would fail to install on WebSphere Liberty which extends the "Open" edition.

**Comment by idlewis** [comment]
This was fixed by #3258
