### ISSUE TITLE
JWT SSO: Re-accessing resource with LTPA cookie allows access when it shouldn't

### ISSUE THREAD

**Issue by ayoho** [OpenLiberty/open-liberty#3275]
Test scenario:
- Log into the protected resource _without_ the JWT SSO feature, obtaining an LTPA token/cookie
- Reconfigure the server to enable the JWT SSO feature
- Re-access the protected resource with the LTPA cookie that was just obtained

Re-accessing the resource should produce a login prompt, however I'm reaching the protected resource and a new JWT principal is put into the subject in addition to the WSPrincipal.

[server_noFeature.txt](https://github.com/OpenLiberty/open-liberty/files/1944363/server_noFeature.txt)
[server_withFeature.txt](https://github.com/OpenLiberty/open-liberty/files/1944365/server_withFeature.txt)
[trace.log](https://github.com/OpenLiberty/open-liberty/files/1944366/trace.log)

**Comment by ayoho** [comment]
This is actually functioning as expected, so I'm closing this issue.

**Comment by brutif** [comment]
Should get fixed by #3268
