### ISSUE TITLE
Followup: Eclipselink bundle version dependencies cleanup

### ISSUE THREAD

**Issue by jgrassel** [OpenLiberty/open-liberty#331]
Followup with updating the Eclipselink bundles generated by the 2.6_WAS and 2.7_WAS branches to provide a more uniform version information, as the current bnd.bnd configuration for the Include-Resources for Eclipselink 2.6 and Eclipselink 2.7 is gross:

Include-Resource: \
  @${repo;org.eclipse.persistence.antlr;3.2.0.v201302191141;EXACT}!/!META-INF/maven/*,\
  @${repo;org.eclipse.persistence.asm;5.0.1.v201405080102;EXACT}!/!META-INF/maven/*,\
  @${repo;org.eclipse.persistence.core;2.6.4.WAS;EXACT}!/!META-INF/maven/*,\
  @${repo;org.eclipse.persistence.jpa.jpql;2.6.4.WAS;EXACT}!/!META-INF/maven/*,\
  @${repo;org.eclipse.persistence.jpa.modelgen;2.6.4.WAS-v20170831-8e605f1;EXACT}!/!META-INF/maven/*,\
  @${repo;org.eclipse.persistence.jpa;2.6.4.WAS;EXACT}!/!META-INF/maven/*

**Comment by dazey3** [comment]
Dup of #826
