### ISSUE TITLE
Delete extracted server (minus logs) on JVM exit

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#338]
Implement the solution discussed in design issue #260 

> When a server is launched with `java -jar myServer.jar`, delete server on exit, but leave the content of the logs folder, unless WLP_JAR_EXTRACT_DIR is set at which point don't delete.

**Comment by brenthdaniel** [comment]
@aguibert can this be closed?

**Comment by aguibert** [comment]
I don't think so. AFAIK it has not been implemented yet (unassigned owner)

**Comment by cbridgha** [comment]
Malcolm - take a look - read-up on the referencing issue where this originated.
This is mainly around detecting a JVM exit, and doing some cleanup of the server directories.

**Comment by atosak** [comment]
This was treated as a defect.
