### ISSUE TITLE
Config 1.3: ID

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#3380]
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemName/com.ibm.team.workitem.WorkItem/254171

We will need some updates to this page:

https://www.ibm.com/support/knowledgecenter/en/SSD28V_9.0.0/com.ibm.websphere.wlp.core.doc/ae/twlp_microprofile_appconfig.html

Something describing the new features in 1.3, including the ability to use server.xml as a config source

**Comment by tevans78** [comment]
Might also want to update the config guide?

**Comment by neilgsyoung** [comment]
ID is complete.
