### ISSUE TITLE
A NullPointerException occurs when starting a spring boot application if cdi-1.2 feature is enabled

### ISSUE THREAD

**Issue by anjumfatima90** [OpenLiberty/open-liberty#3394]
[ERROR   ] CWWKZ0002E: An exception occurred while starting the application test. The exception message was: com.ibm.ws.container.service.state.StateChangeException: java.lang.NullPointerException

Figure out why this exception occurs when cdi-1.2 feature is enabled while starting a spring boot application and provide a solution to this problem.

**Comment by tjwatson** [comment]
Fix is in master now.
