### ISSUE TITLE
Jwt feature needs a more granular attribute to set token expiration time

### ISSUE THREAD

**Issue by brutif** [OpenLiberty/open-liberty#3399]
The current jwt builder "expiry" attribute uses hours as the default units.  Inputting values in less than one hour increments is not possible.  For example, expiry="30m" gets rounded down to zero. 

We probably need a new attribute "expiresInSeconds" to allow more granular setting while preserving existing behavior.  
If the new attribute is present, it would take precedence.  

The old attribute should be marked as deprecated. 

Internals like JwtCreator and JwtSsoBuilderComponent will need to be updated to work with seconds instead of hours.

**Comment by brutif** [comment]
jwtssotokenimpl will also need updating

**Comment by ayoho** [comment]
Same as #3390
