### ISSUE TITLE
Custom feature installation tooling is missing

### ISSUE THREAD

**Issue by mvlazar** [OpenLiberty/open-liberty#340]
When deploying a server with a custom feature, the following message is displayed:

com.ibm.ws.kernel.feature.internal.FeatureManager   E CWWKF0042E: A feature definition cannot  be found for the  libertysecurityfeature-1.0 feature.  Try running the command, bin/installUtility install libertysecurityfeature-1.0,  to install the feature. Alternatively, you can run the command, bin/installUtility install [..........],  to install all features that are referenced by this configuration.

Both installUtility and featureManager are missing in openliberty (but present in IBM WAS Liberty bundle).

Environment:
product = Open Liberty 2017.9.0.0 (wlp-1.0.18.201709162138)
java.version = 1.8.0
java.runtime = Java(TM) SE Runtime Environment (pwa6480sr4fp5-20170421_01 (SR4 FP5))
os = Windows 10 (10.0; amd64) (en_US)

**Comment by NottyCode** [comment]
Thank you for the bug report. This issue has already been raised in issue #154 essentially the message needs to be updated since installUtility and featureManager do not exist.

**Comment by mvlazar** [comment]
So what would be the approach to install a custom feature? I can copy manually the required file and manifest into /usr but the feature is not loading from server.xml
