### ISSUE TITLE
update jwtsso feature - specify servlet-3.1

### ISSUE THREAD

**Issue by arunavemulapalli** [OpenLiberty/open-liberty#3420]
We need to specify a specific version to fix an error that we encounter during the server startup with jwtsso feature. 

E CWWKF0001E: A feature definition could not be found for com.ibm.websphere.appserver.servlet-3.0

Right now we have specified 4.0 but this causes conflicts with the other features (such as older jaxrs and cdi features that depend on 3.1). Since there is no requirement for 4.0, I am updating the feature to use 3.1 and tolerate 4.0

**Comment by ayoho** [comment]
Should be fixed by #3421
