### ISSUE TITLE
Create an Arquillian Container Adapter To Run a TCK as a FAT

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#343]
Liberty has an existing framework for running "FAT" tests.
Various components (CDI, Microprofile Config and Fault Tolerance etc) have TCKs that
are written to use Arquillian. 
This issue is to write some code to act as a shim between the existing ./dev/fattest.simplicity FAT framework and tests written to plug into Arquillian such as https://github.com/eclipse/microprofile-config/tree/master/tck

**Comment by hutchig** [comment]
Needs a fix to #1130

**Comment by fmhwong** [comment]
@hutchig  I have an open issue on automating mpMetrics TCK so I would like to know your plan on this so I can plan my work accordingly.

**Comment by hutchig** [comment]
@fmhwong Hi Felix, If you were to base your work on PR #1400 or #1331 and https://github.ibm.com/was-liberty/WS-CD-Open/wiki/How-to-Create-a-FAT-Project-That-Runs-a-Maven-Based-TCK-Using-Surefire-and-Arquillian the mvn support is in the build now. I am in the last stages of debugging but the 'common' bits are there.
