### ISSUE TITLE
default jwtsso token issuer is not correct

### ISSUE THREAD

**Issue by arunavemulapalli** [OpenLiberty/open-liberty#3491]
Update default issuer logic to make sure that we use correct schema and port.

**Comment by ayoho** [comment]
Ditto - check Ut's changes to see if this was included.

**Comment by ayoho** [comment]
I will go back through our tests to see whether our issuer checking is accurate. The scheme and port should depend on initial request (i.e. http vs. https) and the server configuration (e.g. no SSL port).
