### ISSUE TITLE
NLS messages for JwtSSOTokenImpl

### ISSUE THREAD

**Issue by ayoho** [OpenLiberty/open-liberty#3547]
The `JwtSSOTokenImpl` class has a TODO for a spot that could use a useful error message of some kind:

```Java
@Override
public String getJwtSSOToken(Subject subject) {
    String encodedjwtprincipal = null;
    Set<JsonWebToken> jsonWebTokenPrincipalSet = getJwtPrincipals(subject);
    if (!jsonWebTokenPrincipalSet.isEmpty()) {
        if (hasMultiplePrincipals(jsonWebTokenPrincipalSet)) {
            // TODO error
        } else {
```

**Comment by brutif** [comment]
I agree with the need to NLS some of the strings, but in the case where we are merely wrapping exceptions that are already nls'd in a WSSecurityException, I'm not sure a new message is helpful.
