### ISSUE TITLE
JWT SSO: 500 Internal Server Error for cookie name with invalid characters

### ISSUE THREAD

**Issue by ayoho** [OpenLiberty/open-liberty#3556]
I have tests that set the `cookieName` attribute to:

- `"cookie name with white space"`
- `"not;a, very;good=cookie;name"`
- `"CR&#x000D;LF&#x000A;"` (includes carriage return and line feed unicode characters)

Each of these contains invalid characters (whitespace, `;`, `=`, CR, LF). In each case I'm getting a 500 Internal Server Error with the following FFDC when I submit the user credentials on the login page:

```
------Start of DE processing------ = [5/14/18 9:52:33:166 CDT]
Exception = java.lang.IllegalArgumentException
Source = com.ibm.ws.webcontainer.webapp.WebApp.handleRequest
probeid = 985
Stack Dump = java.lang.IllegalArgumentException: Cookie name "cookie name with white space" is a reserved token
	at javax.servlet.http.Cookie.<init>(Cookie.java:192)
	at com.ibm.ws.webcontainer.security.SSOCookieHelperImpl.createCookie(SSOCookieHelperImpl.java:176)
	at com.ibm.ws.webcontainer.security.SSOCookieHelperImpl.addJwtCookies(SSOCookieHelperImpl.java:146)
	at com.ibm.ws.webcontainer.security.SSOCookieHelperImpl.addJwtSsoCookiesToResponse(SSOCookieHelperImpl.java:119)
	at com.ibm.ws.webcontainer.security.SSOCookieHelperImpl.addSSOCookiesToResponse(SSOCookieHelperImpl.java:78)
	at com.ibm.ws.webcontainer.security.internal.FormLoginExtensionProcessor.postFormLoginProcess(FormLoginExtensionProcessor.java:221)
```

The `cookieName` attribute should be validating to ensure it does not contain any invalid cookie characters before it is processed. I think a warning message should be emitted and the default cookie name should be used if the `cookieName` value is found to be invalid.

**Comment by brutif** [comment]
While tradition used to be we don't ask users to read ffdc's, this one's actually pretty easy to troubleshoot from the ffdc, so I don't think it's urgent.

**Comment by ayoho** [comment]
The error message looks fine to me (shown below.)
```
COOKIE_NAME_INVALID=CWWKS6303E: The value of the jwtSso cookieName attribute  [{0}] contains an invalid character [{1}]. The default cookieName value will be used instead.
COOKIE_NAME_INVALID.explanation=The cookieName attribute needs to be valid cookie name.
COOKIE_NAME_INVALID.useraction=Remove the cookieName attribute, or correct the value.
```

I'd suggest some minor updates, such as:
- Make it a warning message instead of an error message
- Delete an extra space before the first insert: `The value of the jwtSso cookieName attribute (remove extra space) [{0}]`
- Add some help for what we consider to be a "valid" cookie name

**Comment by ayoho** [comment]
The 500 error has been addressed with the latest code. Closing accordingly.
