### ISSUE TITLE
com.ibm.ws.security.mp.jwt.cdi.ClaimProducer using deprecated CDI API

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#3568]
Whenever I start an application that uses MP-JWT, I get this error in logs:

> [5/14/18 17:01:44:814 CDT] 00000030 org.jboss.weld.Bootstrap                                     W WELD-000146: BeforeBeanDiscovery.addAnnotatedType(AnnotatedType<?>) used for class com.ibm.ws.security.mp.jwt.cdi.ClaimProducer is deprecated from CDI 1.1!

**Comment by ayoho** [comment]
Looks like the change for this would be in the `com.ibm.ws.security.mp.jwt.cdi/JwtCDIExtension.java` class as follows:

Change:
```Java
public void beforeBeanDiscovery(@Observes BeforeBeanDiscovery bbd, BeanManager bm) {
    AnnotatedType<ClaimProducer> producer = bm.createAnnotatedType(ClaimProducer.class);
    bbd.addAnnotatedType(producer);
}
```

To something like:
```Java
public void beforeBeanDiscovery(@Observes BeforeBeanDiscovery bbd, BeanManager bm) {
    AnnotatedType<ClaimProducer> producer = bm.createAnnotatedType(ClaimProducer.class);
    bbd.addAnnotatedType(producer, ClaimProducer.class.getName() + getClass().getClassLoader().hashCode());
}
```

An ID needed to be added to the `addAnotatedType()` method that is the ID of the annotated type class (`ClaimProducer`). The class loader's hash code is added to the end for the rare case that another class with the same name might have been loaded elsewhere. Adding the class loader's hash code should uniquely identify the actually annotated type class in that case.

**Comment by tevans78** [comment]
i just found the one other place we already create this id and we used the class’ own hashcode…
```clazz.getName() + ": " + clazz.hashCode()```
in theory the class’ hashcode should be different if it is loaded by a different classloader … or re-loaded by the same one
