### ISSUE TITLE
MicroProfile Config feature needs the spec version in its name

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/open-liberty#361]
When reading the human readable feature name for MicroProfile Config, it's not clear if the feature is the 1.0 or 1.1 level (see https://developer.ibm.com/wasdev/downloads/#filter/sortby=relevance;q=%22MicroProfile%20Config%22 ).  We need to add the version number to the name (e.g. MicroProfile Config 1.1).

**Comment by Emily-Jiang** [comment]
This issue is fixed by my pr #361.
