### ISSUE TITLE
support openid connect and social media login in Open Liberty

### ISSUE THREAD

**Issue by chunlongliang-ibm** [OpenLiberty/open-liberty#3690]
This feature is to refactor and enhance the socialLogin-1.0 feature, then move socialLogin-1.0 feature to open liberty from WAS liberty. This effort includes
1. remove redundant codes and outdated java 6 code path from openidConnectClient-1.0, oauth-2.0, and openidConnectProvider-1.0 feature
2. create a common OIDC client component to be shared by both oidcLogin in socialLogin-1.0 and openidConnectClient-1.0, and remove duplicated oidc client codes
3. enhance oidcLogin in socialLogin-1.0 feature to be openidConnect RP spec compatible, and can be certified 
4. move socialLogin-1.0 to Open Liberty

**Comment by chunlongliang-ibm** [comment]
#link 3691

**Comment by dave-waddling** [comment]
**FAT Focal Approval**: Please can you complete the Feature Test Summary issue (#4720) that has been added to your Epic. This issue is what is used to review the FAT testing and obtain the FAT focal approval. Many thanks.

**Comment by dave-waddling** [comment]
**FAT Focal Approval:** Feature test summary looks good and the SOE results are good - approval granted.

**Comment by bsbyrd1** [comment]
No ID is required for this feature.
