### ISSUE TITLE
Issue a warning if compression is configured for Spring Boot applications

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#3706]
Spring boot has the following settings which are related to compression support:

    server.compression.enabled
    server.compression.excluded-user-agents
    server.compression.mime-types
    server.compression.min-response-size

For now we will issue a warning if these settings are used.  A separate issue #3705 is open to investigate how to enable compression.

**Comment by sebratton** [comment]
As described above there are many different configuration settings.  A warning message will only be issued if compression is actually enabled

**Comment by tjwatson** [comment]
Fixed in master
