### ISSUE TITLE
MicroProfile OpenAPI implementation

### ISSUE THREAD

**Issue by arthurdm** [OpenLiberty/open-liberty#373]
Work required to implement the new MicroProfile OpenAPI specification (https://github.com/eclipse/microprofile-open-api) and the value-add in Open Liberty (validation and customizable UI and document) as part of the mpOpenAPI-1.0.

- [x] GA the mpOpenAPI-1.0 feature #1695 

- [x] MicroProfile OpenAPI 1.0 Feature Test Summary #2277

- [x] - Serviceability Summary - #2292

**Comment by leochr** [comment]
Completed.
