### ISSUE TITLE
Failure to load JPA PersistenceServiceUnit used by Batch feature using V2 version of JobInstance entity.

### ISSUE THREAD

**Issue by ajm01** [OpenLiberty/open-liberty#3739]
We are interpreting the sql exceptions that are returned when determining the runtime version of our Entity objects. This is based on the presence or lack thereof of certain tables and columns when we execute JPA test queries. In some instances we are not checking for all possibilities when we execute certain jpa queries and the runtime erroneously gives up and fails to load the JPA PersistenceServiceUnit.

Need to fix the runtime to check for all possibilities so that the JPA PersistenceServiceUnit is created correctly for the given Entity version.

**Comment by scottkurz** [comment]
Resolved by PR #3740
