### ISSUE TITLE
Complete MicroProfile OpenAPI annotation implementation

### ISSUE THREAD

**Issue by arthurdm** [OpenLiberty/open-liberty#376]
Complete the support for the annotations in the MicroProfile OpenAPI spec (e.g. components). Also handle scenarios involving annotations precedence/overrides.

**Comment by navidsh** [comment]
Annotation list:

[ ] Callback
[ ] Callbacks
[ ] Components
[ ] Explode
[ ] ParameterIn
[ ] ParameterStyle
[ ] SecuritySchemeIn
[ ] SecuritySchemeType
[ ] Extension
[ ] Extensions
[ ] ExternalDocumentation
[ ] Header
[ ] Contact
[ ] Info
[ ] License
[ ] Link
[ ] LinkParameter
[ ] ArraySchema
[ ] Content
[ ] DiscriminatorMapping
[ ] Encoding
[ ] ExampleObject
[ ] Schema
[ ] OpenAPIDefinition
[ ] Operation
[ ] Parameter
[ ] Parameters
[ ] RequestBody
[ ] APIResponse
[ ] APIResponses
[ ] OAuthFlow
[ ] OAuthFlows
[ ] OAuthScope
[ ] SecurityRequirement
[ ] SecurityRequirements
[ ] SecurityScheme
[ ] SecuritySchemes
[ ] Server
[ ] Servers
[ ] ServerVariable
[ ] Tag
[ ] Tags

**Comment by navidsh** [comment]
I'm working on the following annotations:
- Header

**Comment by leochr** [comment]
I'm working on 'Components' annotation

**Comment by janamanoharan** [comment]
I'll work on:
- [] Parameter

**Comment by janamanoharan** [comment]
Working on Content now

**Comment by leochr** [comment]
We have separate issues to handle the rest of the items from the list, so closing this one.
