### ISSUE TITLE
CDI [1.2, 2.0] Holding on to application in memory after being unloaded

### ISSUE THREAD

**Issue by Channyboy** [OpenLiberty/open-liberty#3782]
When unloading an application from server.xml (i.e removing the application entry or commenting it out) the classloader (and application) is still held in memory. The Application is placed in `/apps`

This was encountered in a  new fat test being developed to check if an application has been properly unloaded from memory after unloading the application.

The original purpose to check if an MpMetrics enabled application is properly unloaded, but over-time the test was whittled down to just a simple Servlet.  Without CDI enabled as a feature, the test passes. But when CDI is enabled, the classloader is not properly unloaded.

The Fat test consists of two web apps  consisting of a single Servlet each. One of the web-apps is the app to be tested to see if the app is properly unloaded and the other web-app is the checker-app to evaluate it.
It does so by using a Shared Library which has a singleton that holds a Weak Reference to the ClassLoader of the 'test-app'.

Summary of Fat Test's flow:
1. 'Test App' stores WeakReference of it's classloader into Shared library
2. 'Checker App' checks that a classloader is stored into Shared Library
3. 'Test App' is unloaded through server.xml
4. 'Checker App' checks that the resolved weakreference (from Shared Library) should be null. Will check each second for 4 minutes and create large objects, additional weak references and request system.gcs() in an attempt for a GC to occur. If the wait-time expires, it will fail.

**Comment by jimblye** [comment]
Current plan is to revert pull request ( Enable jandex for cdi extension archives #3049 ).   This will cause Liberty to not use Jandex indexes for CDI extension archives.   I am told CDI extension archives are Liberty archives, and are not (usually?) part of an application.   If that is the case, we could open a new issue to turn on Jandex for these archives by default.  That means we will also need to generate indexes for those archives and keep the indexes up-to-date when the archives are modified.

**Comment by jimblye** [comment]
Steps to enable Jandex for CDI extension archives:  
1) Identify extension archives
2) Generate Jandex indexes for all of archives
3) Maintain those indexes
4) Enable Jandex by default for Extension Archives 

Is this worth doing?  How many archives are there?  How big are they?

**Comment by benjamin-confino** [comment]
Fixed by https://github.com/OpenLiberty/open-liberty/pull/3807
