### ISSUE TITLE
provide option to run mpMetrics-1.1 without TLS/auth

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#3835]

**Comment by rachel-orti** [comment]
+ 1. It would be clearly great to consume the metrics more easily with Prometheus :-)

**Comment by lgrateau** [comment]
+1

**Comment by rachel-orti** [comment]
Is there any chance that this issue is fixed soon?

**Comment by navidsh** [comment]
This functionality is delivered by https://github.com/OpenLiberty/open-liberty/issues/4406.
Closing this issue.
