### ISSUE TITLE
Create centralized JWK service

### ISSUE THREAD

**Issue by ayoho** [OpenLiberty/open-liberty#3843]
At the moment, the Liberty runtime has a couple JWK services. These should be consolidated into a single place so we don't have to maintain different sets of code and ideally rely exclusively on the Jose4j implementation.

**Comment by ayoho** [comment]
@arunavemulapalli Does this encapsulate the JWK work that you completed in 3Q? And can this therefore be closed?

**Comment by arunavemulapalli** [comment]
Yes. This work is complete. OIDC and Social and JWT/MPJWT/JWTSSO - all use same jwk function.
