### ISSUE TITLE
com.ibm.ws.cdi.beansxml_fat takes a little too long

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#3912]
Given thet `com.ibm.ws.cdi.beansxml_fat` is essentially run twice, once for cdi-1.2 and then again for cdi-2.0, overall it takes around 15 mins which is a bit long.

The implicit bean archive tests can be split out into a separate bucket.

**Comment by benjamin-confino** [comment]
The buckets have been split.
