### ISSUE TITLE
Support MetadataBuilder for MP Metrics 2.0

### ISSUE THREAD

**Issue by raymondlam** [OpenLiberty/open-liberty#3916]
MicroProfile 2.0 introduces the builder design pattern for Metadata to make it immutable.

We need to update the MetricRegistryImpl and the metric's CDI project to make it work with MetadataBuilder.

- [ ] Create a new mpMetrics-2.0 beta feature
- [ ] Add latest microprofile snapshot jar to the 2.0 projects
- [ ] Update any places that creates Metadata previously to uses MetadataBuilder without affecting mpMetrics-1.0 or mpMetrics-1.1.

**Comment by Channyboy** [comment]
See #6178
