### ISSUE TITLE
Investigation of differences between Mongo DB java driver versions

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#3938]
User story:
"As the WAS development team, we need to be aware of the differences between Mongo DB java driver versions, so that we can come up with an intelligent design for supporting the latest version."

Determine which configuration has been removed/added and when, and how any new configuration that is possible is achieved. Also, investigate the multiple Java drivers that are available now, and when they became available and how similar they are to the old one.

**Comment by alexsm82** [comment]
Changes identified which affect Liberty:

- autoConnectRetry and maxAutoConnectionRetryTime (in metatype) were removed in 3.0
- The code used the MAJOR_VERSION and MINOR_VERSION fields (for older drivers) or getMajorVersion()/getMinorVersion() in com.mongodb.Mongo to get the driver version.  Both of those mechanisms have been removed in the 3.0 driver. 
- The MongoClient (List<ServerAddress> seeds, List<MongoCredential> credentialsList, MongoClientOptions options) constructor, which is now deprecated, is used.
- The Mongo.getDB method is now deprecated: getDB(String dbname)
- Several WriteConcern values (which are in metatype) were added/deprecated/removed
- socketKeepAlive in metatype is now deprecated
- authenticate(String, char) and isAuthenticated methods on com.mongodb.DB have been removed
- Config options added to the MongoClientOptions.Builder method (which may want to be added as new config options): addClusterListener (ClusterListener clusterListener), addCommandListener (CommandListener commandListener), addConnectionPoolListener (ConnectionPoolListener connectionPoolListener), addServerListener (ServerListener serverListener), addServerMonitorListener (ServerMonitorListener serverMonitorListener), applicationName (String applicationName), codecRegistry (CodecRegistry codecRegistry), compressorList (List<MongoCompressor> compressorList), readConcern (ReadConcern readConcern), retryWrites (boolean retryWrites), serverSelectionTimeout (int serverSelectionTimeout), serverSelector (ServerSelector serverSelector), sslContext (SSLContext sslContext), sslEnabled (boolean sslEnabled), sslInvalidHostNameAllowed (boolean sslInvalidHostNameAllowed)

**Comment by alexsm82** [comment]
Raw data of all changes made to Mongo classes used by Liberty:
Updates to Mongo classes used by Liberty:

Methods/constructors added to com.mongodb.MongoClient:
MongoClient (MongoClientURI uri, MongoDriverInformation mongoDriverInformation) 
MongoClient (ServerAddress addr, MongoCredential credential, MongoClientOptions options)
MongoClient(ServerAddress addr, MongoCredential credential, MongoClientOptions options,MongoDriverInformation mongoDriverInformation)
MongoClient(ServerAddress addr, List<MongoCredential> credentialsList, MongoClientOptions options,MongoDriverInformation mongoDriverInformation)
MongoClient (List<ServerAddress> seeds, MongoCredential credential, MongoClientOptions options)
MongoClient(List<ServerAddress> seeds, MongoCredential credential, MongoClientOptions options,MongoDriverInformation mongoDriverInformation)
MongoClient(List<ServerAddress> seeds, List<MongoCredential> credentialsList, MongoClientOptions options,MongoDriverInformation mongoDriverInformation)
MongoClient now implements Closeable (so the close method was added)
getDatabase (String databaseName)
getDefaultCodecRegistry ()
listDatabaseNames ()
listDatabaseNames (ClientSession clientSession)
listDatabases ()
listDatabases (ClientSession clientSession)
listDatabases (ClientSession clientSession,  Class<T> clazz)
listDatabases (Class<T> clazz)
startSession (ClientSessionOptions options)

Methods removed (or now deprecated) in com.mongodb.MongoClient:
MongoClient (ServerAddress addr, List<MongoCredential> credentialsList) - now deprecated
MongoClient (ServerAddress addr, List<MongoCredential> credentialsList, MongoClientOptions options) - now deprecated
MongoClient(ServerAddress addr, List<MongoCredential> credentialsList, MongoClientOptions options,MongoDriverInformation mongoDriverInformation) - now deprecated
MongoClient (List<ServerAddress> seeds, List<MongoCredential> credentialsList) - now deprecated
MongoClient (List<ServerAddress> seeds, List<MongoCredential> credentialsList, MongoClientOptions options) - now deprecated
MongoClient(List<ServerAddress> seeds, List<MongoCredential> credentialsList, MongoClientOptions options,MongoDriverInformation mongoDriverInformation) - now deprecated 

Methods/constructors added to com.mongodb.Mongo (Mongo is extended by MongoClient):
Mongo is now marked as thread safe
All constructors are still deprecated
getReadConcern ()

Methods/fields removed (or now deprecated) in com.mongodb.Mongo (Mongo is extended by MongoClient):
addOption (int option) - now Deprecated
connect(DBAddress addr)
debugString()
getConnector()
getDatabaseNames() - now Deprecated
getDB(String dbname) - now Deprecated
getMajorVersion()
getMinorVersion()
getMongoOptions() - still deprecated
getOptions() - now deprecated
getVersion()
resetOptions () - now deprecated
setOptions (int options) - now deprecated
setReadPreference (ReadPreference readPreference) - now deprecated
setWriteConcern (WriteConcern writeConcern) - now deprecated
slaveOk () - still deprecated
MAJOR_VERSION
MINOR_VERSION

Methods/constructors added to com.mongodb.MongoClientOptions:
builder (MongoClientOptions options)
getApplicationName ()
getClusterListeners ()
getCodecRegistry ()
getCommandListeners ()
getCompressorList ()
getConnectionPoolListeners ()
getReadConcern ()
getRetryWrites ()
getServerListeners ()
getServerMonitorListeners ()
getServerSelectionTimeout ()
getServerSelector ()
getSslContext ()
isSslEnabled ()
isSslInvalidHostNameAllowed ()
 
Methods/constructors removed (or now deprecated) from com.mongodb.MongoClientOptions:
getAcceptableLatencyDifference()
getHeartbeatConnectRetryFrequency()
getHeartbeatThreadCount()
getMaxAutoConnectRetryTime()
isAutoConnectRetry()
isSocketKeepAlive () - now deprecated

com.mongodb.MongoClientURI
Now mentions an alternative format, using the mongodb+srv protocol, is: mongodb+srv://[username:password@]host[/[database][?options]] in doc, but API is the same

Fields added to com.mongodb.MongoCredential:
CANONICALIZE_HOST_NAME_KEY
JAVA_SASL_CLIENT_PROPERTIES_KEY
JAVA_SUBJECT_KEY
SERVICE_NAME_KEY

Methods added to com.mongodb.MongoCredential:
createMongoX509Credential ()
getAuthenticationMechanism ()

Methods/constructors removed (or now deprecated) from com.mongodb.MongoCredential:
createMongoCRCredential (String userName,String database, char[] password) - now deprecated

Fields and Methods/constructors added to com.mongodb.WriteConcern:
W1
W2
W3
asDocument ()
getJournal ()
getWTimeout (TimeUnit timeUnit)
isAcknowledged ()
isServerDefault ()
withFsync (boolean fsync) - also deprecated now
withJ (boolean journal) - also deprecated now
withJournal (Boolean journal)
withW (int w)
withW (String w)
withWTimeout (long wTimeout, TimeUnit timeUnit)

Fields and Methods/constructors removed (or now deprecated) from com.mongodb.WriteConcern:
WriteConcern.Majority - now deprecated
ERRORS_IGNORED
FSYNC_SAFE - now deprecated
FSYNCED - now deprecated
JOURNAL_SAFE - now deprecated
NONE 
NORMAL - now deprecated
REPLICA_ACKNOWLEDGED - now deprecated
REPLICAS_SAFE - now deprecated
SAFE - now deprecated
WriteConcern () - now deprecated
WriteConcern (boolean fsync) - now deprecated
WriteConcern (int w, int wTimeoutMS, boolean fsync) - now deprecated
WriteConcern (int w, int wTimeoutMS, boolean fsync, boolean journal) - now deprecated
WriteConcern(int w, int wtimeout, boolean fsync, boolean j, boolean continueOnError)
WriteConcern(String w, int wtimeout, boolean fsync, boolean j) -  now deprecated
WriteConcern(String w, int wtimeout, boolean fsync, boolean j, boolean continueOnError)
callGetLastError () -  now deprecated
continueOnError(boolean continueOnError)
continueOnErrorForInsert(boolean continueOnErrorForInsert)
fsync () -  now deprecated
getCommand()
getContinueOnError()
getContinueOnErrorForInsert()
getFsync () - now deprecated
getJ () - now deprecated
getWtimeout ()  - now deprecated
majorityWriteConcern (int wtimeout, boolean fsync, boolean j) - now deprecated
raiseNetworkErrors()
setWObject(Object w)

Fields and Methods/constructors added to com.mongodb.ReadPreference:
ReadPreference is now immutable
choose (ClusterDescription clusterDescription)
chooseForNonReplicaSet (ClusterDescription clusterDescription)
chooseForReplicaSet (ClusterDescription clusterDescription)
nearest (long maxStaleness, TimeUnit timeUnit)
nearest (TagSet tagSet, long maxStaleness,TimeUnit timeUnit)
nearest (List<TagSet> tagSetList, long maxStaleness,TimeUnit timeUnit)
primaryPreferred (long maxStaleness, TimeUnit timeUnit)
primaryPreferred (TagSet tagSet, long maxStaleness,TimeUnit timeUnit)
primaryPreferred (List<TagSet> tagSetList, long maxStaleness, TimeUnit timeUnit)
secondary (long maxStaleness, TimeUnit timeUnit)
secondary (TagSet tagSet, long maxStaleness,TimeUnit timeUnit)
secondary (List<TagSet> tagSetList, long maxStaleness,TimeUnit timeUnit)
secondaryPreferred (long maxStaleness,TimeUnit timeUnit)
secondaryPreferred (TagSet tagSet, long maxStaleness,TimeUnit timeUnit)
secondaryPreferred (List<TagSet> tagSetList, long maxStaleness, TimeUnit timeUnit)
toDocument ()
valueOf (String name, List<TagSet> tagSetList, long maxStaleness, TimeUnit timeUnit)

Fields and Methods/constructors removed (or now deprecated) from com.mongodb.ReadPreference:
ReadPreference.TaggedReadPreference
PRIMARY
SECONDARY
nearest(DBObject firstTagSet, DBObject... remainingTagSets)
primaryPreferred(DBObject firstTagSet, DBObject... remainingTagSets)
secondary(DBObject firstTagSet, DBObject... remainingTagSets)
secondaryPreferred(DBObject firstTagSet, DBObject... remainingTagSets)
toDBObject()
valueOf(String name, DBObject firstTagSet, DBObject... remainingTagSets)
withTags(DBObject tags)
withTags(Map<String,String> tags)

Fields and Methods/constructors added to com.mongodb.MongoClientOptions.Builder:
Builder (MongoClientOptions options)
addClusterListener (ClusterListener clusterListener)
addCommandListener (CommandListener commandListener)
addConnectionPoolListener (ConnectionPoolListener connectionPoolListener)
addServerListener (ServerListener serverListener)
addServerMonitorListener (ServerMonitorListener serverMonitorListener)
applicationName (String applicationName)
codecRegistry (CodecRegistry codecRegistry)
compressorList (List<MongoCompressor> compressorList)
readConcern (ReadConcern readConcern)
retryWrites (boolean retryWrites)
serverSelectionTimeout (int serverSelectionTimeout)
serverSelector (ServerSelector serverSelector)
sslContext (SSLContext sslContext)
sslEnabled (boolean sslEnabled)
sslInvalidHostNameAllowed (boolean sslInvalidHostNameAllowed)

Fields and Methods/constructors removed (or now deprecated) from com.mongodb.MongoClientOptions.Builder:
acceptableLatencyDifference(int acceptableLatencyDifference)
autoConnectRetry(boolean autoConnectRetry)
heartbeatConnectRetryFrequency(int minHeartbeatFrequency)
heartbeatThreadCount(int heartbeatThreadCount)
maxAutoConnectRetryTime(long maxAutoConnectRetryTime)
socketKeepAlive (boolean socketKeepAlive) - now deprecated

Fields and Methods/constructors added to com.mongodb.DB:
DB class is now annotated as threadsafe
createView (String viewName, String viewOn, List<? extends DBObject> pipeline)
createView (String viewName, String viewOn, List<? extends DBObject> pipeline,DBCreateViewOptions options)
getReadConcern ()


Fields and Methods/constructors removed (or now deprecated) from com.mongodb.DB:
_readOnly
addUser(String username, char[] passwd) - still deprecated
addUser(String username, char[] passwd, boolean readOnly) - still deprecated
authenticate(String username, char[] password)
authenticateCommand(String username, char[] password)
cleanCursors(boolean force)
command(DBObject cmd, int options)
command(DBObject cmd, int options, DBEncoder encoder)
command(DBObject cmd, int options, ReadPreference readPreference)
command(DBObject cmd, int options, ReadPreference readPreference, DBEncoder encoder)
command(String cmd, int options)
forceError()
getLastError()
getLastError(int w, int wtimeout, boolean fsync)
getLastError(WriteConcern concern)
getPreviousError()
isAuthenticated()
removeUser(String username) - still deprecated
requestDone()
requestEnsureConnection()
requestStart()
resetError()
setReadOnly(Boolean b)
slaveOk() - still deprecated

Fields and Methods/constructors added to com.mongodb.ServerAddress:
Class is now serializable

Fields and Methods/constructors removed (or now deprecated) from com.mongodb.ServerAddress:
sameHost (String hostName) - now deprecated

**Comment by alexsm82** [comment]
Raw data of all changes to Mongo classes used by Liberty:
Added to com.mongodb.MongoClient:
MongoClient (MongoClientURI uri, MongoDriverInformation mongoDriverInformation) 
MongoClient (ServerAddress addr, MongoCredential credential, MongoClientOptions options)
MongoClient(ServerAddress addr, MongoCredential credential, MongoClientOptions options,MongoDriverInformation mongoDriverInformation)
MongoClient(ServerAddress addr, List<MongoCredential> credentialsList, MongoClientOptions options,MongoDriverInformation mongoDriverInformation)
MongoClient (List<ServerAddress> seeds, MongoCredential credential, MongoClientOptions options)
MongoClient(List<ServerAddress> seeds, MongoCredential credential, MongoClientOptions options,MongoDriverInformation mongoDriverInformation)
MongoClient(List<ServerAddress> seeds, List<MongoCredential> credentialsList, MongoClientOptions options,MongoDriverInformation mongoDriverInformation)
MongoClient now implements Closeable (so the close method was added)
getDatabase (String databaseName)
getDefaultCodecRegistry ()
listDatabaseNames ()
listDatabaseNames (ClientSession clientSession)
listDatabases ()
listDatabases (ClientSession clientSession)
listDatabases (ClientSession clientSession,  Class<T> clazz)
listDatabases (Class<T> clazz)
startSession (ClientSessionOptions options)

Removed (or now deprecated) in com.mongodb.MongoClient:
MongoClient (ServerAddress addr, List<MongoCredential> credentialsList) - now deprecated
MongoClient (ServerAddress addr, List<MongoCredential> credentialsList, MongoClientOptions options) - now deprecated
MongoClient(ServerAddress addr, List<MongoCredential> credentialsList, MongoClientOptions options,MongoDriverInformation mongoDriverInformation) - now deprecated
MongoClient (List<ServerAddress> seeds, List<MongoCredential> credentialsList) - now deprecated
MongoClient (List<ServerAddress> seeds, List<MongoCredential> credentialsList, MongoClientOptions options) - now deprecated
MongoClient(List<ServerAddress> seeds, List<MongoCredential> credentialsList, MongoClientOptions options,MongoDriverInformation mongoDriverInformation) - now deprecated 

Added to com.mongodb.Mongo (Mongo is extended by MongoClient):
Mongo is now marked as thread safe
All constructors are still deprecated
getReadConcern ()

Removed (or now deprecated) in com.mongodb.Mongo (Mongo is extended by MongoClient):
addOption (int option) - now Deprecated
connect(DBAddress addr)
debugString()
getConnector()
getDatabaseNames() - now Deprecated
getDB(String dbname) - now Deprecated
getMajorVersion()
getMinorVersion()
getMongoOptions() - still deprecated
getOptions() - now deprecated
getVersion()
resetOptions () - now deprecated
setOptions (int options) - now deprecated
setReadPreference (ReadPreference readPreference) - now deprecated
setWriteConcern (WriteConcern writeConcern) - now deprecated
slaveOk () - still deprecated
MAJOR_VERSION
MINOR_VERSION

Added to com.mongodb.MongoClientOptions:
builder (MongoClientOptions options)
getApplicationName ()
getClusterListeners ()
getCodecRegistry ()
getCommandListeners ()
getCompressorList ()
getConnectionPoolListeners ()
getReadConcern ()
getRetryWrites ()
getServerListeners ()
getServerMonitorListeners ()
getServerSelectionTimeout ()
getServerSelector ()
getSslContext ()
isSslEnabled ()
isSslInvalidHostNameAllowed ()
 
Removed (or now deprecated) from com.mongodb.MongoClientOptions:
getAcceptableLatencyDifference()
getHeartbeatConnectRetryFrequency()
getHeartbeatThreadCount()
getMaxAutoConnectRetryTime()
isAutoConnectRetry()
isSocketKeepAlive () - now deprecated

com.mongodb.MongoClientURI
Now mentions an alternative format, using the mongodb+srv protocol, is: mongodb+srv://[username:password@]host[/[database][?options]] in doc, but API is the same

Added to com.mongodb.MongoCredential:
CANONICALIZE_HOST_NAME_KEY
JAVA_SASL_CLIENT_PROPERTIES_KEY
JAVA_SUBJECT_KEY
SERVICE_NAME_KEY
createMongoX509Credential ()
getAuthenticationMechanism ()

Removed (or now deprecated) from com.mongodb.MongoCredential:
createMongoCRCredential (String userName,String database, char[] password) - now deprecated

Added to com.mongodb.WriteConcern:
W1
W2
W3
asDocument ()
getJournal ()
getWTimeout (TimeUnit timeUnit)
isAcknowledged ()
isServerDefault ()
withFsync (boolean fsync) - also deprecated now
withJ (boolean journal) - also deprecated now
withJournal (Boolean journal)
withW (int w)
withW (String w)
withWTimeout (long wTimeout, TimeUnit timeUnit)

Removed (or now deprecated) from com.mongodb.WriteConcern:
WriteConcern.Majority - now deprecated
ERRORS_IGNORED
FSYNC_SAFE - now deprecated
FSYNCED - now deprecated
JOURNAL_SAFE - now deprecated
NONE 
NORMAL - now deprecated
REPLICA_ACKNOWLEDGED - now deprecated
REPLICAS_SAFE - now deprecated
SAFE - now deprecated
WriteConcern () - now deprecated
WriteConcern (boolean fsync) - now deprecated
WriteConcern (int w, int wTimeoutMS, boolean fsync) - now deprecated
WriteConcern (int w, int wTimeoutMS, boolean fsync, boolean journal) - now deprecated
WriteConcern(int w, int wtimeout, boolean fsync, boolean j, boolean continueOnError)
WriteConcern(String w, int wtimeout, boolean fsync, boolean j) -  now deprecated
WriteConcern(String w, int wtimeout, boolean fsync, boolean j, boolean continueOnError)
callGetLastError () -  now deprecated
continueOnError(boolean continueOnError)
continueOnErrorForInsert(boolean continueOnErrorForInsert)
fsync () -  now deprecated
getCommand()
getContinueOnError()
getContinueOnErrorForInsert()
getFsync () - now deprecated
getJ () - now deprecated
getWtimeout ()  - now deprecated
majorityWriteConcern (int wtimeout, boolean fsync, boolean j) - now deprecated
raiseNetworkErrors()
setWObject(Object w)

Added to com.mongodb.ReadPreference:
ReadPreference is now immutable
choose (ClusterDescription clusterDescription)
chooseForNonReplicaSet (ClusterDescription clusterDescription)
chooseForReplicaSet (ClusterDescription clusterDescription)
nearest (long maxStaleness, TimeUnit timeUnit)
nearest (TagSet tagSet, long maxStaleness,TimeUnit timeUnit)
nearest (List<TagSet> tagSetList, long maxStaleness,TimeUnit timeUnit)
primaryPreferred (long maxStaleness, TimeUnit timeUnit)
primaryPreferred (TagSet tagSet, long maxStaleness,TimeUnit timeUnit)
primaryPreferred (List<TagSet> tagSetList, long maxStaleness, TimeUnit timeUnit)
secondary (long maxStaleness, TimeUnit timeUnit)
secondary (TagSet tagSet, long maxStaleness,TimeUnit timeUnit)
secondary (List<TagSet> tagSetList, long maxStaleness,TimeUnit timeUnit)
secondaryPreferred (long maxStaleness,TimeUnit timeUnit)
secondaryPreferred (TagSet tagSet, long maxStaleness,TimeUnit timeUnit)
secondaryPreferred (List<TagSet> tagSetList, long maxStaleness, TimeUnit timeUnit)
toDocument ()
valueOf (String name, List<TagSet> tagSetList, long maxStaleness, TimeUnit timeUnit)

Removed (or now deprecated) from com.mongodb.ReadPreference:
ReadPreference.TaggedReadPreference
PRIMARY
SECONDARY
nearest(DBObject firstTagSet, DBObject... remainingTagSets)
primaryPreferred(DBObject firstTagSet, DBObject... remainingTagSets)
secondary(DBObject firstTagSet, DBObject... remainingTagSets)
secondaryPreferred(DBObject firstTagSet, DBObject... remainingTagSets)
toDBObject()
valueOf(String name, DBObject firstTagSet, DBObject... remainingTagSets)
withTags(DBObject tags)
withTags(Map<String,String> tags)

Added to com.mongodb.MongoClientOptions.Builder:
Builder (MongoClientOptions options)
addClusterListener (ClusterListener clusterListener)
addCommandListener (CommandListener commandListener)
addConnectionPoolListener (ConnectionPoolListener connectionPoolListener)
addServerListener (ServerListener serverListener)
addServerMonitorListener (ServerMonitorListener serverMonitorListener)
applicationName (String applicationName)
codecRegistry (CodecRegistry codecRegistry)
compressorList (List<MongoCompressor> compressorList)
readConcern (ReadConcern readConcern)
retryWrites (boolean retryWrites)
serverSelectionTimeout (int serverSelectionTimeout)
serverSelector (ServerSelector serverSelector)
sslContext (SSLContext sslContext)
sslEnabled (boolean sslEnabled)
sslInvalidHostNameAllowed (boolean sslInvalidHostNameAllowed)

Removed (or now deprecated) from com.mongodb.MongoClientOptions.Builder:
acceptableLatencyDifference(int acceptableLatencyDifference)
autoConnectRetry(boolean autoConnectRetry)
heartbeatConnectRetryFrequency(int minHeartbeatFrequency)
heartbeatThreadCount(int heartbeatThreadCount)
maxAutoConnectRetryTime(long maxAutoConnectRetryTime)
socketKeepAlive (boolean socketKeepAlive) - now deprecated

Added to com.mongodb.DB:
DB class is now annotated as threadsafe
createView (String viewName, String viewOn, List<? extends DBObject> pipeline)
createView (String viewName, String viewOn, List<? extends DBObject> pipeline,DBCreateViewOptions options)
getReadConcern ()


Removed (or now deprecated) from com.mongodb.DB:
_readOnly
addUser(String username, char[] passwd) - still deprecated
addUser(String username, char[] passwd, boolean readOnly) - still deprecated
authenticate(String username, char[] password)
authenticateCommand(String username, char[] password)
cleanCursors(boolean force)
command(DBObject cmd, int options)
command(DBObject cmd, int options, DBEncoder encoder)
command(DBObject cmd, int options, ReadPreference readPreference)
command(DBObject cmd, int options, ReadPreference readPreference, DBEncoder encoder)
command(String cmd, int options)
forceError()
getLastError()
getLastError(int w, int wtimeout, boolean fsync)
getLastError(WriteConcern concern)
getPreviousError()
isAuthenticated()
removeUser(String username) - still deprecated
requestDone()
requestEnsureConnection()
requestStart()
resetError()
setReadOnly(Boolean b)
slaveOk() - still deprecated

Added to com.mongodb.ServerAddress:
Class is now serializable

Removed (or now deprecated) from com.mongodb.ServerAddress:
sameHost (String hostName) - now deprecated
