### ISSUE TITLE
Figure out how to create common FAT applications

### ISSUE THREAD

**Issue by ayoho** [OpenLiberty/open-liberty#3944]
I had to deliver a duplicate of our `testmarker` and `formlogin` applications into the `com.ibm.ws.security.jwtsso_fat` project in order to use them during testing. Having to duplicate common applications should be completely unnecessary, so we need to find out how to package these applications in one place and be able to use them across disparate FAT projects.

**Comment by c00crane** [comment]
I'm adding code in the common FAT to generate and externalize the war files.
In the jwtsso project, I'm adding code to copy the war's into the dropins and apps directories as approriate.
I'll also delete the app source from jwtsso.
