### ISSUE TITLE
Support variable substitution in deployment descriptors and annotations

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#3963]
Glassfish and payara allow for variables to be specified in deployment descriptors and annotation equivilents. This is documented [here](https://docs.payara.fish/documentation/payara-server/server-configuration/var-substitution/usage-of-variables.html)

This is non-portable if used, but it does mean that you can override the configuration at deployment time. In Liberty this is done by doing an override of the deployment descriptor in server.xml, but allowing variable substitution would be an alternative that might be simpler, especially in fat jar or docker deployment scenarios.

**Comment by NottyCode** [comment]
On a call this was discussed and it was agreed this seemed like a good idea with the following observations:

* We should look at how we can optionally integrate this with MP config. This shouldn't be a hard requirement, but an optional one.
* We should look at providing default values for the variable substitution
* We should ensure that if we can't resolve a variable something sensible happens at app startup time.
* We need to look at dynamic configuration to ensure that variable changing works correctly. Ideally it wouldn't force an app restart.

**Comment by maroschutte** [comment]
I solved this using the configDropins/overrides folder [1] where I use the id attribute of my enterpriseapplication to add to its configuration.

[1] https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_setup_dropins.html
