### ISSUE TITLE
testClashingName failes in fault tolerence 1.1 tck

### ISSUE THREAD

**Issue by benjamin-confino** [OpenLiberty/open-liberty#3982]
We have seen a failure in testClashingName in the fault tolerance 1.1 tck; a build can be found here. 

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_5sA1YG__EeiEs4pc7_B0gQ&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage

**Comment by Azquelt** [comment]
It looks like I messed up the TCK test here.

The test runs two methods annotated with `@Asynchronous` and expects the invocation counter to have been incremented immediately afterwards.

The test should wait for both methods to finish executing before checking the counter.

**Comment by Azquelt** [comment]
TCK fix submitted: eclipse/microprofile-fault-tolerance#290
