### ISSUE TITLE
Test that reactive extensions will work in `jaxrs-2.1`'s reactive client

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#4004]
Section 5.7.1 of the JAX-RS 2.1 spec states that JAX-RS 2.1 implementations MUST support the `CompletionStage` return type for reactive clients and MAY support other reactive extensions.  Here is an example of how this could work with RxJava 2.0:

```
Client client = ClientBuilder.newClient().register(ObservableRxInvokerProvider.class);
Observable<String> o = client.target(someUri)
                             .request()
                             .rx(ObservableRxInvoker.class)    // non-default invoker
                             .get(String.class);
o.subscribe(System.out::println);
```

Ideally, we could also provide support for Java 9's `Flow` API which, IIUC, is based on RxJava 2.

Since users may want to bring their own version of RxJava, I would suggest that Liberty _not_ package it, but be able to use it if a user application packages it.  

We'll want tests for apps that package their own version of RxJava 2 (and ideally Java 9's Flow).  This might require that we pull in new CXF modules such as `cxf-rt-rs-extension-rx2` and `cxf-rt-rs-extension-reactivestreams` and add them to the `jaxrsClient-2.1` feature.

**Comment by jkoehler22** [comment]
PR: https://github.com/OpenLiberty/open-liberty/pull/4229
