### ISSUE TITLE
Add common annotations 1.3 feature

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#401]

**Comment by tbitonti** [comment]
Question of whether to use the 1.3 or 1.3.1 version of the API jar.  See:
https://mvnrepository.com/artifact/javax.annotation/javax.annotation-api/1.3
https://mvnrepository.com/artifact/javax.annotation/javax.annotation-api/1.3.1

Initial upload to artifactory:
https://na.artifactory.swg-devops.com/artifactory/webapp/#/artifacts/browse/tree/General/wasliberty-open-liberty/javax/annotation/javax.annotation-api/1.3.1/javax.annotation-api-1.3.1.jar

Coordinates (G:A:V): javax.annotation:javax.annotation-api:1.3.1

**Comment by Emily-Jiang** [comment]
@tbitonti have you solved this issue?
