### ISSUE TITLE
OpenLiberty server splash page incorrectly indicating new avaliable version

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/open-liberty#4029]
# Problem
The latest version of OpenLiberty (18.0.0.1) is indicating there is a new OL version avaliable.  This is incorrect since 18.0.0.1 is the latest build at the time of this issue creation.

# Recreation Steps
1. Download 18.0.0.1 release build from https://openliberty.io/downloads/
2. Unzip the build
3. Run command in the `wlp/bin` folder: `./server create defaultServer`
4. Run command in the `wlp/bin` folder: `./server start defaultServer`
5. Go to http://localhost:9080/
6. Notice the top banner indicating a new version is available 

# Snapshot of the 18.0.0.1 splash page
![image](https://user-images.githubusercontent.com/31117513/41666389-09c39bf0-7470-11e8-9e5d-30fc2a02ed2d.png)

# Code
I suspect the logic that controls the banner is in this area of code
https://github.com/OpenLiberty/open-liberty/blob/9ea1070737696c2ad90bf9cf8b66ab11793696aa/dev/com.ibm.ws.transport.http/resources/OSGI-INF/welcome/index.html#L372

**Comment by mbroz2** [comment]
Closing as per current implementation this needs to be addressed in openliberty.io's latestVersion.js.
