### ISSUE TITLE
MP Reactive Streams Operators 1.0: Documentation

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#4088]
Create doc on why, what and how on mp reactive

**Comment by hutchig** [comment]
@rhpeters Please could you link me up with an ID contact to help resolve how I can deliver the ID requirements as described in the WAD?

The WAD page on "communication" currently has:
```
This material is suitable for Open Liberty blog articles for the audience of ‘settler’ type developers.
As well as Beta and GA release blog post inclusion:

(Any security related material (e.g. regarding Principle context propogation) should be considered for the Knowledge Centre. )

An article showing the simple wiring together of two different Java EE technologies with very little application code using the fluent, functional composition that reactive streams enables along with simple operator use. The aim is to introduce streams, operators and show the expressive power/productivity of stream use.

A second article where the text and code’s aim is to jump start a developer in writing their own reactive stream Publisher and Subscriber. This article can show mixing with RxJava (and maybe) Reactor sourced stream elements and operators – showing that it is not a “choose one” scenario – where users might feel inclined to ignore new entrants.

Later on, a ‘Guide’ that shows how to use the MicroProfile Messaging Annotations to subscribe and write to a persisted Kafka topic as might be used in inter-service, Event Driven, flows.
```
So the KC requirements described in the WAD relate to no more than:

"(Any security related material (e.g. regarding Principle context propogation) should be considered for the Knowledge Centre. )"

So what I would propose is that we need something similar to:
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_microprofile_fault_tolerance.html
and I will cover the above requirement.

Can I supply a draft for this?

Please would you inform me of the format and elivery process needed?
thanks!

I suggest we handle further discussion here and not in the epic.

**Comment by helyarp** [comment]
From Karen Deen, who is the ID focal for Open Liberty:
- For an OL blog post, go to https://openliberty.io/blog/. Karen left a slack message on the OL site to see who your Ol contact would be.
- For an OL guide, contact Eveline Cai.
- For KC, I can be your ID contact. KC is for commercial Liberty doc.

**Comment by hutchig** [comment]
Dear @helyarp, here is the text I suggest in the KC similar to what we have done for other MP specs:
<start>

You can use the MicroProfile Reactive Streams Operators feature to 
create and manipulate reactive streams of data. This feature is an implementation of the Eclipse MicroProfile Reactive Streams Operators feature version 1.0

It provides an interface for creating a publish-subscribe relationship between a producer and consumer of data with the ability add intermediate processors and use a set of generic operators. As well as a mechanism for passing data down the stream, it provides an elegant mechanism for handling errors and controlling data flow rates within the stream.

#Before you begin

For more information about the open source MicroProfile specification that is implemented by the MicroProfile Reactive Streams Operators feature, see the Eclipse MicroProfile Reactive Streams Operators Specification 1.0 [here:]( https://download.eclipse.org/microprofile/microprofile-reactive-streams-operators-1.0/microprofile-reactive-streams-operators-spec.pdf)

#Procedure

##Add the mpReactiveStreams-1.0 to a featureManager element in your server.xml file.
```
    <featureManager>
       <feature>mpReactiveStreams-1.0</feature>
    </featureManager>
```

#Example

The `ReactiveStreams` class is the starting class for building most MicroProfile reactive streams.  It has methods that can be used to create the source of a reactive stream’s data that are easier to use that writing a full implementation of the reactive streams Publisher interface.

For example, below is a simple example that sums the even numbers in the first 10 integers:

```
CompletionStage<Optional<Integer>> result = 
ReactiveStreams.of( 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 )
                .filter(i -> (i % 2) == 0)                                // evens
                .collect(Collectors.reducing((i, j) -> i + j)) // sum
                .run();
// Wait for stream to complete and get result
Optional<Integer> total = result.toCompletableFuture().get();
```

In the above example the ReactiveStreams::of method creates a underlying reactive streams ‘Publisher’ that emits its parameters when the stream is run. The generic `filter()` and `collect()` operators are used to pick particular data items from the stream and sum them together.  The full set of operators available are described, for example,  [here:]( https://download.eclipse.org/microprofile/microprofile-reactive-streams-operators-1.0/apidocs/org/eclipse/microprofile/reactive/streams/operators/PublisherBuilder.html)

The ReactiveStreams class can initiate a stream from many sources, including from an ‘Iterable’, from a `CompletionStage`, from a `Supplier`, from repeatably calling a given function, from one a reactive streams Publisher and so on.

Other significant classes are the `PublisherBuilder`, `ProcessorBuilder` and `SubscriberBuilder` classes. They provide a mechanism, via the `via()` and `to()` methods or connecting together data processing elements in the stream. 

Once a stream is completed with a Subscriber or other terminating contruct the result is a 'CompletionRunner' which offers a 'run()' method to set the stream into operation and, when 
finished, collect the result of the stream. The stream is run asynchronously as a result of calling the run() method on a thread from the server's managed thread pool. 
Standard Liberty ManagedExecuter context propogation is done from the initiating thread to the thread used to run the stream. Each functional element of the stream will typically run in the context of the same thread and thus share any changes made to the thread contexts.
 
The full set of classes and operators that are available in the Eclipse MicroProfile Reactive Streams Operators Specification 1.0 are described [here:](https://download.eclipse.org/microprofile/microprofile-reactive-streams-operators-1.0/apidocs/index.html?org/eclipse/microprofile/reactive/streams/operators/package-summary.html)

**Comment by hutchig** [comment]
Dear @helyarp please can you process the comment above as my draft input the the KC thank you (feel free to edit it - clicking on the "edited" word in the blue bar of the issue comment provides means to access older versions)

**Comment by helyarp** [comment]
@hutchig Hi, I've put info from your comment into the Liberty 19003 beta doc and tagged it for 19004 eGA with issue #1139. Please suggest revisions to the doc in issue 1139. The draft has:

## Manipulating reactive streams of data in Liberty

You can use the MicroProfile Reactive Streams Operators feature to create and manipulate reactive streams of data. This feature is an implementation of the Eclipse MicroProfile Reactive Streams Operators Specification 1.0.

The `mpReactiveStreams-1.0` feature provides an interface for creating a publish-subscribe relationship between a producer and consumer of data. It supports intermediate processors and uses a set of generic operators. As well as a mechanism for passing data down the stream, it provides an elegant mechanism for handling errors and controlling data flow rates within the stream.

For more information about the open source MicroProfile specification that is implemented by the MicroProfile Reactive Streams Operators feature, see Eclipse MicroProfile Reactive Streams Operators Specification 1.0.

### Procedure
1.  Add the `mpReactiveStreams-1.0` feature to a `featureManager` element in your `server.xml` file.
```
    <featureManager>
       <feature>mpReactiveStreams-1.0</feature>
    </featureManager>
```
2. Use methods in the `ReactiveStreams` class to create a reactive stream of data. Then use methods in MicroProfile Reactive Streams Operators classes to manipulate that stream.

### Example

The ReactiveStreams class is the starting class for building most MicroProfile reactive streams. Its methods that create the source of a reactive stream of data are easier to use than writing a full implementation of the reactive streams Publisher interface.

For example, the following code adds the even numbers in the first 10 integers:
```
CompletionStage<Optional<Integer>> result = 
ReactiveStreams.of( 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 )
                .filter(i -> (i % 2) == 0)                     // evens
                .collect(Collectors.reducing((i, j) -> i + j)) // sum
                .run();
// Wait for stream to complete and get result
Optional<Integer> total = result.toCompletableFuture().get();
```

In this example, the `ReactiveStreams::of` method creates an underlying reactive streams _Publisher_ that emits its parameters when the stream is run. The generic `filter()` and `collect()` operators select specific data items from the stream and sum them. The full set of operators available is described in the `PublisherBuilder` interface of the Eclipse MicroProfile Reactive Streams Operators API documentation.

The `ReactiveStreams` class can initiate a stream from many sources, including from an `Iterable`, from a `CompletionStage`, from a `Supplier`, from repeatedly calling a specific function, from a reactive streams Publisher, and so on.

Other significant classes are the `PublisherBuilder`, `ProcessorBuilder`, and `SubscriberBuilder `classes. They provide a mechanism, through `via()` and `to()` methods, for connecting data processing elements in the stream.

After a stream is completed with a _Subscriber_ or other terminating construct, the result is a _CompletionRunner_. It offers a `run()` method to set the stream into operation and, when finished, collect the result of the stream. The stream is run asynchronously by calling the `run()` method on a thread from the managed thread pool of the server.

Standard Liberty `ManagedExecuter`  context propagation is done from the initiating thread to the thread that runs the stream. Each functional element of the stream typically runs in the context of the same thread and thus shares any changes that are made to the thread contexts. **[Please improve the wording in this paragraph]**

The full set of classes and operators are described in the Eclipse MicroProfile Reactive Streams Operators Specification 1.0 documentation.

**Comment by hutchig** [comment]
This has been delivered and reviewed at: https://github.ibm.com/was-liberty/liberty-docs/issues/1139
