### ISSUE TITLE
Support MicroProfile JWT 1.1 spec

### ISSUE THREAD

**Issue by chunlongliang-ibm** [OpenLiberty/open-liberty#4113]
This epic is opened to support MP-JWT 1.1 spec, https://github.com/eclipse/microprofile-jwt-auth/releases/download/1.1/microprofile-jwt-auth-spec-1.1.pdf.

The MP-JWT 1.1 is an update to MP-JWT 1.0. The major updates include
1. Define vendor neutral MP-Config for JWT validation
2. Define interoperable JWT validation key format

**Comment by ayoho** [comment]
This looks like a duplicate of #3844
