### ISSUE TITLE
Enable CDI when @Inject is detected

### ISSUE THREAD

**Issue by benjamin-confino** [OpenLiberty/open-liberty#4116]
When creating the test for #2725 I needed to add an empty bean with a bean defining annotation otherwise `@Inject Config config` would not work. I think that CDI should be enabled for an application if we detect `@Inject`

**Comment by Azquelt** [comment]
This caught someone else out trying to set up a small metrics sample.

Unfortunately, it's very likely to come up when people are doing small experiments with microprofile as lots things rely on `@Inject` and in a small sample, you might do everything in the JAX-RS endpoint.

**Comment by Emily-Jiang** [comment]
@benjamin-confino this issue is invalid though and it is against the CDI spec. @Inject should not work in the classes that are not CDI beans nor JavaEE component classes.

**Comment by iainduncani** [comment]
I think it is worth adding this to the "CDI tips" section at the bottom of this page then:

https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/cwlp_mp_metrics_api.html

**Comment by tevans78** [comment]
@benjamin-confino What do you want to do with this issue? A Doc update?
