### ISSUE TITLE
Add @HitCounted and @ParallelCounted for MP Metrics 2.0

### ISSUE THREAD

**Issue by raymondlam** [OpenLiberty/open-liberty#4152]
We are planning to deprecate `@Counted` in favour of `@HitCounted` and `@ParallelCounted`.

`@HitCounted` is equivalent to a `@Counted` with `monotonic=true`
`@ParallelCounted` is equivalent to a `@Counted` with `monotonic=false`

We need the appropriate CDI interceptors to handle `@HitCounted` and `@ParallelCounted`

- [ ] Add implementation for HitCounted/ParallelCounted
- [ ] Add interceptor support for `@HitCounted` and `@ParallelCounted`
- [ ] Deprecate `MetricRegistry.remove`
- [ ] Support `MetricRegistry.unregister()` with filtering by type

Note: currently the Metrics PRs are still in progress and not merged in.
See MicroProfile Metrics PR 247, 270, 272.

**Comment by fmhwong** [comment]
@Channyboy Do we still need this?

**Comment by Channyboy** [comment]
See #6178
