### ISSUE TITLE
AccessControlException from MetricRegistry11Impl

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#4155]
MetricRegistry11Impl gets the thread context classloader without using a doPrivileged block, resulting in an AccessControlException when registering a metric with java 2 security enabled.

The offending call is here: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.metrics.1.1/src/com/ibm/ws/microprofile/metrics11/impl/MetricRegistry11Impl.java#L67

Should be using `SecureAction.getContextClassLoader()` instead.

**Comment by fmhwong** [comment]
Resolved by https://github.com/OpenLiberty/open-liberty/pull/7557
