### ISSUE TITLE
JSF 2.3 not supported in eclipse photon (4.8.3)

### ISSUE THREAD

**Issue by ghostidentity** [OpenLiberty/open-liberty#4205]
Hi guys!

Greetings! do you have workaround  on how to solve the issue ? 

Thanks,
Mark

**Comment by aguibert** [comment]
@ghostidentity can you elaborate on what is not supported with Eclipse Photon and how that involves OpenLiberty?  

If I remember correctly, Eclipse did not implement a project facet for JSF 2.3 -- is that what you are referring to?  If so, it would be better to open an issue on the Eclipse IDE issue tracker.

**Comment by ghostidentity** [comment]
Yeah, the project facets for jsf 2.3 spec not supported in eclipse. Therefore, when I run the web project using openliberty server utilizing java ee 8 spec would throw an error. Eclipse wont read new jsf tags like <f: websocket>. I shall open an issue on eclipse.

**Comment by johnmcollier** [comment]
Hi, I worked on the Eclipse tooling for Java EE 8 in Eclipse WTP. Oracle implements the support for JPA and JSF facets in WTP, and whereas IBM tends to implement the other facets. For Java EE 8, Oracle was not able to devote enough resources to adding support for JPA 2.2 and JSF 2.3, as a result, Eclipse WTP does not have proper support for those project facets.

**Comment by aguibert** [comment]
Closing out this issue since it is better suited for the Eclipse tooling issue tracker

**Comment by johnmcollier** [comment]
JSF 2.3 has been implemented by an outside contributor to WTP in http://git.eclipse.org/c/jsf/webtools.jsf.git/commit/?id=49060e54a5b1124c21b105d32d2408b7c5233a94
