### ISSUE TITLE
Move first raft of transactions tests into open-liberty

### ISSUE THREAD

**Issue by jonhawkes** [OpenLiberty/open-liberty#4208]
Move transactions tests into open-liberty. Suites to move are:

- com.ibm.ws.transaction_bvt
- com.ibm.ws.transaction_fat_java7
- com.ibm.ws.transaction.cloud_fat

Consider whether com.ibm.ws.transaction_fat can be removed if java7 version is a superset. Otherwise either move that as well or merge with java7 suite.

**Comment by neilgsyoung** [comment]
Completed.
