### ISSUE TITLE
Timing issue in config dropins test

### ISSUE THREAD

**Issue by brenthdaniel** [OpenLiberty/open-liberty#4214]
It's possible for testBrokenDropin() in test.server.config.DropinsTest to exit early, which could lead to a failure in cleanup of testSimpleDefaults(). 

The test currently copies three files to config dropins and then waits for an update message, but it's possible that the file notification for the first update can occur before the others, which would result in two config updates. We only wait for one update, so the test could exit early. We can avoid this by waiting for an update after each individual file copy.

**Comment by hutchig** [comment]
We are also seeing lots of 'new' errors in Arquillian deployment driven tests where something has 'changed' to do with deployment action occurring 'too' quickly. e.g. ShrinkWrap un zip to file at dropins directory has Liberty struggling with incomplete wars which did not used to happen. @Azquelt think he might have spotted a related code change but we are still clarifying the picture.
