### ISSUE TITLE
Metric Arquillian Container Level Stuck at older impl.

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#4219]
I was unable to update 
 dev/com.ibm.ws.microprofile.metrics_fat_tck/publish/tckRunner/tck/pom.xml
as part of 
https://github.com/OpenLiberty/open-liberty/pull/4170/commits/3457256e015346771e7e4b7e4ee4ad1dcf5a2829

to use:
      <dependency>
             <groupId>io.openliberty.arquillian</groupId>
             <artifactId>arquillian-liberty-managed</artifactId>
             <version>1.0.1</version> 
             <scope>test</scope>
         </dependency>

due to 
Caused by: java.lang.IllegalStateException: Multiple service implementations found for interface org.jboss.arquillian.container.spi.client.container.DeployableContainer. org.jboss.arquillian.container.was.wlp_managed_8_5.WLPManagedContainer, io.openliberty.arquillian.managed.WLPManagedContainer
at org.jboss.arquillian.core.impl.loadable.ServiceRegistryLoader.onlyOne(ServiceRegistryLoader.java:74)

Not sure why this is?

**Comment by hutchig** [comment]
I do not plan to progress this myself at the moment.

**Comment by hutchig** [comment]
so my hunch is that something in io.astefanutti material has a java-service-loader file called org.jboss.arquillian.container.spi.client.container.DeployableContainer with the contents of “org.jboss.arquillian.container.was.wlp_managed_8_5.WLPManagedContainer”. It it works if you have two of these files with the same contents but not two of these files with different fully qualified class names.

So our internal slightly older Container was also called “org.jboss.arquillian.container.was.wlp_managed_8_5.WLPManagedContainer”
but not now.

**Comment by hutchig** [comment]
org.jboss.arquillian.core.spi.LoadableExtension is service loadable, it contains: 
   io.openliberty.arquillian.managed.WebSphereExtension
That then gets service loaded and the register method called: 
```
public class WebSphereExtension implements LoadableExtension
{
   @Override
   public void register(ExtensionBuilder builder)
   {
      builder.service(DeployableContainer.class, WLPManagedContainer.class);
   }
}
```

**Comment by fmhwong** [comment]
Fixed using https://github.com/OpenLiberty/open-liberty/pull/5975
