### ISSUE TITLE
Enable auth filter for mpjwt flow

### ISSUE THREAD

**Issue by arunavemulapalli** [OpenLiberty/open-liberty#4254]
Enable this support for mpJwt. 
With this, users will have choice of securing resources with not just mpjwt (right now, if the mpJwt feature is added to the server then it enforces the runtime to protect the secured resources with only mpjwt) but other types such as basic auth or ceritificate mapping etc..

**Comment by ayoho** [comment]
@arunavemulapalli Sounds like this should be closed.

**Comment by arunavemulapalli** [comment]
This work is completed. Closing the issue
