### ISSUE TITLE
java.lang.IllegalStateException: Null zip file thrown from ZipFileData

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#4274]
An IllegalStateException can be thrown from ZipFileData if it gets its internal state in a muddle.

This can happen if it encounters an exception while reopening the zip file as part of a `reacquireZipFile` operation.

`reaquireZipFile` closes the zip file, then opens it, then updates the state of ZipFileData. If opening the zip file throws an exception, the state doesn't get updated and ZipFileData is left in a state where it thinks it has the zip file open (Pending state), but actually the `zipFile` field is `null`.

At this point, any attempt to use the ZipFileData will result in an attempt to reacquire the zip file again and the close operation will fail because the `zipFile` field is `null`, resulting in this IllegalStateException.

This means that once this problem has occurred, for as long as the ZipFileData remains cached, any application deployed at that location will fail to start.

**Comment by tbitonti** [comment]
Looking over the code, I concur: ZipFileData is not handling the failure to reacquire the ZIP file.
Two methods are in play:
ZipFileReaper :: ZipFile open(String, long) throws IOException, ZipException;
ZipFileData :: ZipFile reacquireZipFile() throws IOException, ZipException;
No only must the ZipFileData be put into a correct state.  The reaper must correct its placement of the zip file data.
I'm thinking the correct behavior here is to throw an exception while leaving the zip file data in the pendingClose state.  The close, when it eventually occurs, should not require that the zip file still exist.  And, any subsequent attempt to reacquire the zip file will succeed or fail according to the state of the zip file when the attempt was made.

**Comment by tbitonti** [comment]
The failure occurs in ZipFileData.reacquireZipFile; there are two calls from ZipFileReaper.open,
one for an open on top of an open, the other for an open on top of a pending close.
Need to correct the data state and the reaper state correctly when reaquire throws an exception.

The third case in ZFR.open is an open on top of a full close; that case operates through a call to open, which will fail with an exception and works out, although, mostly by accident.

Tn ZFR.open, the eventual call to data.enactOpen is incorrect to do when the reacquire fails.

Teacquire clears out the zip file reference before trying the new open.  That leaves the state of the ZipFileData correct in the case of a failure.

The eventual call to enactOpen can be changed to enactClose(CLOSE_ALL) then enactFullClose() -- when the data in an open state, or to just enactFullClose() -- when the data is in a pending state.  Calling enactFullClose on data which is in a pending state is not valid.

**Comment by jimblye** [comment]
Fixed by pull request: #4967

**Comment by hlhoots** [comment]
Hey @jimblye  @tbitonti 

Can this one be closed out?  Looks like its resolved by #4967 ?
