### ISSUE TITLE
Need to fix first line of output from Liberty JSON log format to actually be JSON

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#4332]
Header line of output in logs, when console logs are in JSON format, isn't in JSON format.  This is problematic when you want to pipe output into something like jq:

```
Launching defaultServer (WebSphere Application Server 18.0.0.2/wlp-1.0.21.cl180220180619-0403) on IBM J9 VM, version 8.0.5.17 - pxa6480sr5fp17-20180627_01(SR5 FP17) (en_US)
{"type":"liberty_message","host":"test0719-ibm-websphere-l-595845f45c-8mms5","ibm_userDir":"\/opt\/ibm\/wlp\/usr\/","ibm_serverName":"defaultServer","message":"CWWKE0001I: The server defaultServer has been launched.","ibm_threadId":"00000001","ibm_datetime":"2018-07-19T14:41:47.929+0000","ibm_messageId":"CWWKE0001I","module":"com.ibm.ws.kernel.launch.internal.FrameworkManager","loglevel":"AUDIT","ibm_sequence":"1532011307929_0000000000001"}
```

Need the header line to also be in JSON format.

**Comment by jwalcorn** [comment]
This is still an issue with 18.0.0.3 that shipped at the end of September.  Any outlook on this?  Thanks!

**Comment by donbourne** [comment]
fields to include in Liberty header record:

- type - "liberty_message"
- host
- ibm_userDir
- ibm_serverName
- message
- ibm_datetime
- ibm_sequence

**Comment by donbourne** [comment]
also, please order the fields in the JSON header in the same order as the rest of the Liberty messages (for consistency and simple scripting).

**Comment by fmhwong** [comment]
PR merged
