### ISSUE TITLE
MP Fault Tolerance 1.1: Create Metrics blog article

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#4336]
MP Fault Tolerance brings new metrics. We need an article (or a guide) about using and graphing these metrics as they're not terribly intuitive (but they are terribly useful).

**Comment by tevans78** [comment]
Blog post was published.

**Comment by Azquelt** [comment]
Blog post published here: https://openliberty.io/blog/2018/10/05/microprofile-faulttolerance-1.1-metrics.html
