### ISSUE TITLE
Format problem with logs when traceFileName is stdout

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#4356]
steps to recreate
1. ./server create server1
2. edit server.xml - add
  -   `<logging traceSpecification="blah=fine" traceFileName="stdout" traceFormat="ADVANCED" />`
3. ./server run server1

notice that the output is missing a space between the log level and the "UOW" label:
```
[24/07/18 16:28:48:699 EDT] 00000001 IUOW= source=com.ibm.ws.kernel.launch.internal.FrameworkManager org= prod= component=
          CWWKE0002I: The kernel started after 1.487 seconds
```

format should match what you would see in trace.log when traceFileName attribute is not set in above configuration.

This also affects `ENHANCED` format as well.

--------------------

Additionally, when enabling trace with Liberty and the option to write to stdout is selected and the default/basic formatting mode is chosen for console, the trace that comes out to console is formatted in JSON instead of basic.

**Comment by Channyboy** [comment]
See #4402
