### ISSUE TITLE
Reducing Kernel compressed image size

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/open-liberty#4358]
Currently our minified (compressed) image for a simple jsp/servlet application is ~28MB.

The Kernel contains ~10MB of this image.

We need to investigate the specific components that take up this space, and investigate different strategies for creating a reduced image either by refactoring or creating alternative images for different environments (Fat jar / Docker).

**Comment by cbridgha** [comment]
Possible flags for invoking this option:

--include=minify,reduce or --include=minify AND --reduce

Can also offer to include single nl language like we do for --os option
--lang=fr and just remove all other translations.  Default to english if nothing specified

**Comment by marikaj123** [comment]
@cbridgha - Hi Chuck, Are you going to deliver the AHA Feature https://bigblue.aha.io/features/APSFOUND-28 in 4Q18?  If yes, then please add the tag 'Target:4Q18' by October 29.  Thank you.

**Comment by tbitonti** [comment]
Obsolete.
