### ISSUE TITLE
Liberty logs were generated in JSON format by default

### ISSUE THREAD

**Issue by patrickyau** [OpenLiberty/open-liberty#4369]
We used Liberty 18.0.0.1 previously. This is a new problem from 18.0.0.2.

When the following logging.xml is used, we observed the Liberty messages were logged in JSON format while the application trace was in regular advanced format:
```
<server>
  <logging suppressSensitiveTrace="true" traceFormat="ADVANCED" traceSpecification="*=warning:com.ibm.ws.security.*=all" traceFileName="stdout" hideMessage="SRVE9967W">
  </logging>
</server>
```

**Comment by Channyboy** [comment]
Issue addressed and resolved through #4402
