### ISSUE TITLE
Investigate which changes from swagger-core rc2 to include in MicroProfile

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty#439]
Investigate the rc2 changes from swagger-core (https://github.com/swagger-api/swagger-core/releases/tag/v2.0.0-rc2) and check which ones we want to push into our MicroProfile proposal?  For example, they removed `RequestBody` from the `Operation` annotation.

**Comment by leochr** [comment]
Annotation and models only (not jaxrs).

**Comment by arturdzm** [comment]
Changes:
1. Added scanning of `@ApplicationPath` annotation (and keeps track of the JAXRS app class)
2. Made annotations repeatable (eg SecurityScheme now can be supplied more then once on a single method)
3. General improvements for annotation (fixed targets, javadoc)
4. Added enums for some annotation like Parameter and SecuritySchema
5 Changes to Parameter annotation (now only works on method and fields
6. Support for hiding operations (hidden boolean on annotation)
7. Added default info to OpenAPIDefinition annotation

**Comment by leochr** [comment]
@arturdzm can this be closed? is there any pending work?

**Comment by arturdzm** [comment]
Yeah, we can close this.
