### ISSUE TITLE
Support JWT public key location other than HTTP URL schema

### ISSUE THREAD

**Issue by chunlongliang-ibm** [OpenLiberty/open-liberty#4395]
Liberty supports token verification key location in HTTP(S) URL schema. This PR is to support other key location, including

1. Relative or non-URL paths supplied as the location are resolved in the following order:

    new File(location)

    Thread.currentThread().getContextClassLoader().getResource(location)
file: URL Scheme

2. File URL paths supplied as the location allow for explicit externalization of the file via full url.
       java -jar movieservice.jar -Dmp.jwt.verify.publickey.location=file:///opt/keys/orange.pem

The resolved key format can be PKCS#8 PEM, JWK, or JWKS.

I think we could update the method "protected PublicKey getJwkLocal(String kid, String x5t)" in class "/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java" to accomplish this.

The key location is resolved by mp-config's mp.jwt.verify.publickey.location. If instead the public key is supplied directly using mp.jwt.verify.publickey, key should be resolved without using   mp.jwt.verify.publickey.location.

See spec for detail: https://github.com/eclipse/microprofile-jwt-auth/blob/master/spec/src/main/asciidoc/configuration.asciidoc

**Comment by ayoho** [comment]
@brutif Can you check and verify that this is done?

**Comment by brutif** [comment]
this is done, it's much of what the tck checks for
