### ISSUE TITLE
CLA Label changes proposed

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/open-liberty#44]
Existing IBM Org members are getting the "CLA Not Needed" label applied, but should be made more specific like "CLA covered under Corporate Agreement" - but obviously too long.

In general - it should be clear why the CLA signature is not needed in this case, as IBM employees are automatically covered.

Will consider options.

**Comment by cbridgha** [comment]
OK After looking at a few public projects...  we should just change "CLA Not Needed" to "CLA Signed"

All IBMers have implicitly "signed" the CLA

**Comment by wraschke** [comment]
https://github.ibm.com/was-liberty/infrastructure/pull/58 is merged and the fix is on the crazytown Rosie server. I can see in open-liberty PRs opened after I updated the server that the "CLA Signed" label is now being added instead of "CLA Not Needed." So I am closing this.
