### ISSUE TITLE
Refactor productUtility script to not use JAX-B

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#4455]
In Java 11 JAX-B is being removed from the JDK, and so Liberty must provide its own copy of JAX-B going forward.  Since the `productUtility` script is required by the kernel, we want to avoid adding the 3.4MB JAX-B dependency to the Liberty kernel.

**Comment by mswatosh** [comment]
We're using JAXB to bind iFix and Liberty metadata xml files to IFixInfo and LibertyProfileMetadataFile objects in com.ibm.ws.product.utility.extension.IFixUtils

The least invasive way to handle this should be using JAXP to parse the xml files and assemble the IFixInfo and LibertyProfileMetadataFile objects.
