### ISSUE TITLE
Allow user to specify server root in package archive

### ISSUE THREAD

**Issue by hlhoots** [OpenLiberty/open-liberty#4480]
Users need to be allowed to specify the root folder name within the output archive whenever the server package command is executed.

New --server-root option will be added.  The user can specify --server-root=myroot and the archive will use /myroot as the base folder.

Additionally, if the user specifies --include=usr AND the --server-root option, then the default of /wlp/usr will be replaced with just the --server-root value.  Example,

--include=usr --server-root=myroot
Archive will have /myroot/servers/... (ie, no /usr)

**Comment by hlhoots** [comment]
@gkwan-ibm 

1. No WAD required.
2. Not yet. Will most likely demo this on EOI to show the team the new option being added to the server package command.
3. Spoke to Brian H, and we agreed that FVT / FAT should cover this and SVT is not needed.
4. LL3KRN would be the L3 queue and our team is aware of this new feature.  The L2 queue would be WASADM.  They have not yet been notified yet, but I will reach out to them today.

**Comment by bsbyrd1** [comment]
My approval is based on the sizing of the ID work, and the expectation that the ID work can be completed before the last ID translation drop.

**Comment by dave-waddling** [comment]
**FAT Focal Approval:** Feature Test Summary looks good and the new testing is passing perfectly in the SOE. Approval granted.

**Comment by marikaj123** [comment]
Approving on behalf of Swati. No STE is needed

**Comment by marikaj123** [comment]
Blog GA Info:  https://github.ibm.com/was-liberty/WS-CD-Open/issues/13153

**Comment by hlhoots** [comment]
Completed
