### ISSUE TITLE
Add new test cases for mpMetrics's authentication config

### ISSUE THREAD

**Issue by navidsh** [OpenLiberty/open-liberty#4504]
Add FAT tests for the MicroProfile Metrics.

For more info about the actual changes made, see https://github.com/OpenLiberty/open-liberty/issues/4406

Scenarios to be tested:
- Setting `authentication` to `true` or `false`.
- Removing `<mpMetrics ... />` and ensuring default is the secure endpoint.
- Switching between `mpMetrics-1.0` and `mpMetrics-1.1`

I would suggest you add a configuration element to the FAT framework to make your life easier when switching `mpMetrics` configuration. See [com.ibm.websphere.simplicity.config.OpenAPIElement](https://github.ibm.com/was-liberty/WS-CD-Open/blob/integration/dev/fattest.simplicity/src/com/ibm/websphere/simplicity/config/OpenAPIElement.java) for an example of how you could do it.

**Comment by tkburroughs** [comment]
Is this issue ready to be closed?

**Comment by navidsh** [comment]
Delivered. Closing.
