### ISSUE TITLE
Issue(s) with loose applications getting updated (or not) by application monitor.

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/open-liberty#4548]
For a "loose" application, in this case developed via the **liberty-maven-plugin**, the application doesn't update on a running server predictably after a compile.   It may not update, or two update messages may appear.  Not updating at all is worse.

### Recreate instructions

1. Do:
> clone https://github.com/scottkurz/sample-getting-started

2. Do:
> mvn clean package 

3. Start server
> mvn liberty:run-server

4. Make app change (in another window) 
* E.g. update **src/main/java/io/openliberty/sample/system/SystemConfig.java**

5. compile
> mvn compile

#### Expected
```
[INFO] [AUDIT   ] CWWKT0017I: Web application removed (default_host): http://desktop-rm5ausp.pok.ibm.com:9080/
[INFO] [AUDIT   ] CWWKZ0009I: The application io.openliberty.sample.getting.started has stopped successfully.
[INFO] [AUDIT   ] CWWKT0016I: Web application available (default_host): http://desktop-rm5ausp.pok.ibm.com:9080/
[INFO] [AUDIT   ] CWWKZ0003I: The application io.openliberty.sample.getting.started updated in 0.315 seconds.
```

#### Actual
The worst case is that nothing happens (no msg;  no loading of the updated classes as seen by the fact that the updates don't appear on execution).  I've only seen this on Windows.

Sometimes the sequence is repeated twice.  This seems to happen most (all?) the time on Linuz and Mac.   

Not sure how "bad" the double update would be considered, but not updating at all is clearly a problem.

#### Config adjustments

This sample uses:
```
<applicationManager autoExpand="true" />
```
and the default **applicationMonitor**.

I've tried tweaking the monitor polling time, and removing autoExpand a bit, informally.  I'll note it hasn't seem to have made a difference, but don't take my word for it, as I wasn't very methodical about testing these permutations.

**Comment by yangcao77** [comment]
It’s not only an issue with OL, ibmliberty also has the same issue.  As the first time I met this issue was with `websphere-liberty:webProfile7` images.

Did not see this issue in WDT (WDT use Eclipse build, not Maven build), only see this issue with Liberty& Maven & loose config.

**Comment by yangcao77** [comment]
This should be liberty-maven-plugin issue, manually updated a single java class( copy to target folder) only see one single update.

**Comment by yangcao77** [comment]
@scottkurz Please confirm that it's an issue with maven plugin, and move the issue to the correct repo.

**Comment by scottkurz** [comment]
Now I can't recreate even when `autoExpand="true"` on Windows.  Since I opened it, I'm going to close it to avoid anyone wasting their time on it.

@yangcao77 please reopen if you think there's still an issue here.

**Comment by yangcao77** [comment]
@scottkurz Confirmed that, increasing the pollingRate does help for the double update issue. 
But autoExpand = "false" still does not trigger the update on "mvn compile" 


We wants to know why the default pollingRate mostly not works well on looseConfig. And we are not suppose to change user's server.xml, so user would still see the wired behavior upon update.

**Comment by scottkurz** [comment]
Do you have another test that can predictably recreate the "app doesn't update" issue?  I opened this issue thinking this was happening consistently (on Windows), but it stopped occurring for me and so I don't know how to carry that forwards for now.

As far as the double update, I don't have any knowledge to indicate this isn't working as designed.    Perhaps the liberty-maven-plugin doc could warn about such a scenario, but this plugin isn't writing the classes into place upon compile (the compiler plugin is).    I could be wrong or missing information, but if there is something for the Open Liberty runtime to look at here, it would be a very different issue than the "app doesn't update" issue.  So I still think this issue maybe should be closed.
