### ISSUE TITLE
JPA ORM Analyzer: Support EclipseLink/OpenJPA ORM extensions

### ISSUE THREAD

**Issue by dazey3** [OpenLiberty/open-liberty#4555]
EclipseLink and OpenJPA both have their own ORM extension files. We should be able to read those files in and parse the ORM information.

Will need to use JAXB to read the ORM extension file schemas

**Comment by jgrassel** [comment]
I think this one can be prioritized as low, since we collect the entirety of the ORM XML file, without processing, so it would include any vendor-specific extensions to the ORM XML schema.

Processing of such extensions becomes more important in any analyzer tool we create that consumes this data.

**Comment by jgrassel** [comment]
Since the ORM Diagnostic has been updated to collect the entirety of the orm xml file contents, this issue becomes more important for any analyzer tool we might create in the future, rather than in the diagnostic collector itself.
