### ISSUE TITLE
Spans are getting grouped up under same span for OpenTracing.1.1

### ISSUE THREAD

**Issue by tonyreigns** [OpenLiberty/open-liberty#4578]
There was a case found where hundreds of spans were getting grouped up with the same parent. Span isn't closing properly or something is picking up the wrong parent for certain spans.

**Comment by tonyreigns** [comment]
@dacleyra

**Comment by atosak** [comment]
@hanczaryk , is this SVT blocking issue for 3Q?

**Comment by atosak** [comment]
closed by accident. Reopened.

**Comment by dacleyra** [comment]
Yes, blocking SVT

**Comment by tonyreigns** [comment]
Issue has been solved. See https://github.ibm.com/was-liberty/WS-CD-Open/issues/12876
