### ISSUE TITLE
Upgrade CXF to 3.1.16 for JAX-RS 2.0

### ISSUE THREAD

**Issue by WhiteCat22** [OpenLiberty/open-liberty#4647]
We need to upgrade out CXF implementation for JAX-RS 2.0 to 3.1.16 for 18.0.0.3.

**Comment by jkoehler22** [comment]
https://github.com/OpenLiberty/open-liberty/pull/4675/

**Comment by marikaj123** [comment]
PB running now.

**Comment by jkoehler22** [comment]
reopen to wait for it to be push to master

**Comment by WhiteCat22** [comment]
changes made it to master
