### ISSUE TITLE
Remove dependency on jaxb from Spring Boot features

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#4681]
jaxb is used to manipulate some relatively small and simple XML files for configuration in the Spring Boot support.  Since jaxb is being removed from the base Java in Java 11 we should try to eliminate our dependency on jaxb.

**Comment by aguibert** [comment]
JAX-B dependency introduced into springBoot-1.5 and 2.0 features in issue #4679

**Comment by dazavala** [comment]
Given the simplicity of the XML files, a straightforward StAX solution seems most appropriate here.

**Comment by dazavala** [comment]
Changes have merged into master.
