### ISSUE TITLE
Ensure com.ibm.ws.metadata.ejb.AutomaticTimerBean.DateHelper.parse() works in JDK 9+

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#4725]
In JDK 9 JAX-B is being taken off the bootclasspath (and fully removed in JDK 11).  The EJB Container code only had a single dependency on JAX-B, so instead of adding the 3.4MB JAX-B dependency to the EJB features, I branched the code to use java.time APIs if the Java version is >=9.

https://github.com/OpenLiberty/open-liberty/pull/4683/files#diff-7dc460d94709f1814108a5e0c9d037e5

We should add unit-tests to the EJB Container code to verify that this datetime parsing pattern works consistently across the JDK 8- and JDK 9+.

**Comment by tkburroughs** [comment]
open-liberty change merged; closing.
