### ISSUE TITLE
Make type=xa default for dataSource

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#4738]
User story:
"As a user of Liberty, I want type=javax.sql.XADataSource to be the default for dataSource so that I get the most functionality by default."

This is not a requirement of JDBC 4.3.  However, introduction of the jdbc-4.3 OpenLiberty feature gives us the opportunity to introduce this requested change in behavior.  The existing jdbc-4.2 (and earlier) features will preserve existing behavior.

**Comment by bpaskin-ibm** [comment]
I would recommend not changing the behavior, but maybe adding an element, maybe to the applicationManager, to determine the default type.  There are too many users that would enable the latest feature and may not realize the change in behavior.   -Brian

**Comment by njr-11** [comment]
@bpaskin-ibm Liberty already has a configuration attribute (it's on the dataSource element) to determine the default type.  It should also be noted that typically implementations of XADataSource are a superset of the capability you get from ConnectionPoolDataSource/DataSource, and so typically this change will just mean allowing applications to enlist multiple resources in a transaction where they previously would have gotten an error for it.  If the JDBC vendor doesn't provide an XADataSource, then change in order doesn't make any difference at all.  There still remains, however, the possibility that a JDBC vendor might have either chosen to or inadvertently coded a behavior difference between their XADataSource and ConnectionPoolDataSource implementations, which is why this was deferred to a feature boundary rather than implemented within the existing jdbc-4.2 feature.  We were trying to be extra cautious about it.  Does this change your opinion on the matter, or are you still of the position that this change should not be made at all?

**Comment by bpaskin-ibm** [comment]
Yes, it is on the DS, but it is not global to all DSes.  As long as the change does not affect performance, then it should be fine, IMO.  Thx for the response.

**Comment by njr-11** [comment]
The other reason for the change which I neglected to mention above is that with the current behavior of selecting ConnectionPoolDataSource by default, customers end up unknowingly  accepting heuristic hazard (it's enabled by default) when enlisting the one-phase capable resource created by ConnectionPoolDataSource into two-phase commit transactions.  Defaulting to XADataSource corrects this by ensuring that enlisted resources are two-phase commit capable.

**Comment by bsbyrd1** [comment]
@njr-11 @atosak What Aha feature is associated with this Epic? Is it for 4Q?
