### ISSUE TITLE
Update automated tests/infrastructure to run with latest Derby

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#4744]
User story:
"As the development team, we need automated tests to be able to run with a newer version of Derby that supports JDBC 4.3."

Might need to choose the Derby level based on Java version that the tests are running against.

**Comment by mswatosh** [comment]
At this point, since Derby doesn't appear to be planning on anything but no-ops for JDBC 4.3, it's not worth including an additional Derby version.
