### ISSUE TITLE
Stop creating / pushing git tags on nightly builds

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/open-liberty#475]
Currently, we have a routine in our "integration" builds that create a git tag, and also uses the "latest" tag to determine the commit log between builds.

The tag's that are pushed show up as GitHub "releases", which isn't desired - and we need to clean out the existing tags as well, so we only leave behind real "releases".

**Comment by cbridgha** [comment]
@fritze2 Can you take a look?  we'll need to tweak the logic in our any scripts around git tag usage.
We can use the git commit sha instead (tagging the RTC build instance) and always compare the HEAD to the master/HEAD commit.

**Comment by ewhoch** [comment]
I'm going to try to finish this one up this week, at least for the i-type tags.

**Comment by ewhoch** [comment]
Cleaned this up in our push code, i-type tags no longer created.
