### ISSUE TITLE
MP FT 1.1 changes leaks to MP FT1.0

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#4753]
I discovered there is unintended changes required by MP FT 1.1, made to MP FT1.0, which breaks our zero migration principle. We need to fix this before the 18.0.0.3 release.

**Comment by tevans78** [comment]
@marikaj123 The first PR for this issue is now in master. The second is now in integration.

**Comment by tevans78** [comment]
All now in stabilisation. Closing.
