### ISSUE TITLE
consider enhancing key file detection for mp-jwt-1.1

### ISSUE THREAD

**Issue by brutif** [OpenLiberty/open-liberty#4783]
Currently when looking at public keys supplied in a file or environment variable, we detect json key information or a pkcs 1 or 8 key beginning with "--- BEGIN ....".  We might want to be able to correctly detect the keys in a couple of other formats: 
1) a pkcs1 or 8 key without the begin and end headers
2) a base64 encoded json key
Both of these are outside the scope of the spec.

**Comment by c00crane** [comment]
Enable FAT tests MPJwtMPConfigInApp_NoMPJwtConfigInServerXml_GoodSimplePublicKeyInMPConfigInMetaInf and MPJwtMPConfigInApp_NoMPJwtConfigInServerXml_GoodSimplePublicKeyInMPConfigUnderWebInf  in MPJwtMPConfigInApp_NoMPJwtConfigInServerXml_Tests  when done

**Comment by ayoho** [comment]
@chunlongliang-ibm has said that this scenario is not one that we need to worry about, so I'm going to go ahead and close this.
