### ISSUE TITLE
Springboot apps start on port 8080 when WebServer factory bean is called from child context

### ISSUE THREAD

**Issue by bpaskin-ibm** [OpenLiberty/open-liberty#4806]
When creating a SpringBoot application in Liberty it is possible that the application will not start on the defined port for the httpEndpoint, but on port 8080.  
```
<httpEndpoint id="defaultHttpEndpoint" httpPort="9080" httpsPort="9443" host="*"/>
<springBootApplication location="mySpringBoot.jar" id="myApp" type="spring" name="myApp"/>

```
This is happening when the WebServer factory bean is being called by a child of the ApplicationContext and not the root ApplicationContext.  Liberty should handle both cases.

A small workaround is to define a virtual host for the springBootVirtualHost to override the behavior.
```
<virtualHost id="springBootVirtualHost-8080">
   <hostAlias>*:9443</hostAlias>
</virtualHost>
```

Brian

**Comment by tjwatson** [comment]
The fix for this has been merged for the next release 18.0.0.3 as well as for integration to master.
