### ISSUE TITLE
Remove internal designation/updates for servletPathForDefaultMapping/make servlet-4.0 default / tests 

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#4809]
The initial work marked it internal as translations are required: https://github.com/OpenLiberty/open-liberty/issues/4666 Lets also use this work item to add a couple of test cases for this functionality.

**Comment by marikaj123** [comment]
PR: https://github.com/OpenLiberty/open-liberty/pull/4852

**Comment by pnicolucci** [comment]
Code is integrated into 18.0.0.4 and integration branches so this can be closed now.
