### ISSUE TITLE
JWT builder need convert public key to JWK even keystore is not explictly configured

### ISSUE THREAD

**Issue by chunlongliang-ibm** [OpenLiberty/open-liberty#4827]
The JWT builder auto converts public key to JWT. However, the implementation requires keystore reference be configured explicitly. We should simply fetch the public key from default server certificate if keystore is not configured.. 
The fix can be done here:
/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/utils/JwtUtils.java
    public static PublicKey getPublicKey(String keyAlias, String trustStoreRef, KeyStoreService kss)
            throws KeyStoreException, CertificateException, InvalidTokenException

**Comment by arunavemulapalli** [comment]
Chunlong and I took a look at the code and I believe that we already have the function supported. 
Chunlong will test this to confirm.

**Comment by ayoho** [comment]
@arunavemulapalli and @chunlongliang-ibm will check to see if this has been resolved.
