### ISSUE TITLE
Provision compatible javax.annotations API for SpringBoot applications

### ISSUE THREAD

**Issue by dazavala** [OpenLiberty/open-liberty#4853]
A server configured from the springBoot1 (2) template on Liberty 18.0.0.2 will emit a ClassDefNotFoundError and fail to start a dropped-in Spring Boot application that depends on v1.2+ of the javax.annotation API. The problem occurs because the server provisions v1.1 of the javax.annotation API, which lacks classes supplied in later versions -- or more generally, a class loading problem will likely occur whenever the server provisions an incompatible version of a javax API on which a Spring Boot application depends.  

Note that the Spring Boot thinning support will remove, for example, the javax.annotation dependency jar from the application deployment whenever the jar is a transient dependency of a Spring Boot embedded server starter dependency. This behavior is not the root cause of the problem, but may confuse problem determination when the server indicates a class loading failure. 

This problem was discovered by a developer who attempted to deploy a JAX-RS(Jersey) SpringBoot app over a websphere-liberty 18.0.0.2 springBoot2 docker tag  [issue 182](https://github.com/WASdev/ci.docker/issues/182).

**Comment by tevans78** [comment]
We will at least update servlet-4.0 to pull in annotations-1.3. The rest will be left for now in case they break existing configurations. @dazavala please close if you are happy with this.

**Comment by dazavala** [comment]
@tevans78 We updated both the servlet-3.1 and 4.0 javax anno api provision. @benjamin-confino, note that cdi-1.0 was not modified to tolerate javax.anno-1.2. Details are in #5328.

**Comment by tevans78** [comment]
Assuming that @benjamin-confino is happy too then this issue can be closed.

**Comment by benjamin-confino** [comment]
I'm happy with this solution.
