### ISSUE TITLE
Fix intermittent failure in ejbcontainer.session.passivation_fat

### ISSUE THREAD

**Issue by brideck** [OpenLiberty/open-liberty#4888]
StatefulTimeoutTest.testXMLOnly can sometimes fail with:
javax.ejb.NoSuchEJBException: Stateful bean CMStatefulBeanO timed out

This can happen when the amount of time it takes for recovery log processing to occur exceeds the 15 sec stateful timeout that is configured by the test.

**Comment by tkburroughs** [comment]
merged
