### ISSUE TITLE
ldapRegistry-3.0 uses infinite read timeout

### ISSUE THREAD

**Issue by jvanhill** [OpenLiberty/open-liberty#4949]
The LDAP registry in both Liberty and tWAS defaults to an infinite read timeout. In tWAS, you can set the read timeout by setting the connect timeout. In Liberty, there was no way to set the read timeout on the registry outside of setting the JNDI system property which effects all JNDI connections until we added a configuration attribute in issue #3383.

Customers have hit issues where LDAP server did not respond and the LDAP registry has sat for 30+ minutes until the connection was closed remotely (firewall connection timeout). This consumes contexts from the JNDI context pool in the LDAP registry as well as consuming service threads until the connection is closed remotely.

After talking it over with Alasdair, I would like to discuss if it might be better to change Liberty's default behavior and include a default read timeout that is not infinite. Currently we have the following defaults in Liberty:

- connect timeout = 1m   [time JNDI will wait for a connection attempt before aborting]
- read timeout = infinite   [time JNDI will wait for a request to return before aborting the request]
- search timeout = 1m     [the allotted time a server is allowed to take before the server should abort the request]

**Comment by tevans78** [comment]
@jvanhill can this issue be closed? I think the suggested resolution was a 1m timeout?

**Comment by jvanhill** [comment]
@tevans78 - As you mentioned, the resolution was a 1m timeout.

I will open up a new issue to make the change and then close this issue.

**Comment by jvanhill** [comment]
Closing this issue per my comment above.
