### ISSUE TITLE
JCA connections used across suspend/resume of global transactions

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#4974]
User story:
"As a user of global transactions in Liberty, I want operations performed on connections to run under the transaction that is active on the thread, so that they can commit or roll back along with that same transaction."

There are a variety of ways to accomplish suspend/resume, including the transaction manager API, context service, EJBs, and `@Transactional`

Refer to TODOs in the following test cases which demonstrate the lack of this capability:
jdbc.fat.v43.web.JDBC43TestServlet.testSuspendRunGlobalTranAndResumeSharable()
jdbc.fat.v43.web.JDBC43TestServlet.testSuspendRunGlobalTranAndResumeUnsharable()
jdbc.fat.v43.web.JDBC43TestServlet.testSuspendRunLTCAndResumeSharable()
jdbc.fat.v43.web.JDBC43TestServlet.testSuspendRunLTCAndResumeUnsharable()

Upon investigation by Mark, this error is broader that just JDBC and applies to all of JCA, thus is it not appropriate to fix only within the JDBC layer.

**Comment by mswatosh** [comment]
This is currently blocked by Issue #6013
