### ISSUE TITLE
Support for Oracle Universal Connection Pool (UCP)

### ISSUE THREAD

**Issue by janfonas** [OpenLiberty/open-liberty#4985]
WebSphere "traditional" has supported Oracle UCP for some time now, Could we please have support for UCP in OpenLiberty?

**Comment by frowe** [comment]
Great suggestion, we've got other users interested in the same support (see [this dewWorks RFE](http://www.ibm.com/developerworks/rfe/execute?use_case=viewChangeRequest&CR_ID=88268)).  I'll add this request to our backlog.

**Comment by tevans78** [comment]
This issue is still being worked on.

**Comment by alexsm82** [comment]
Oracle UCP is now supported in Open Liberty as of version 19.0.0.4.  See this blog post for more details: https://openliberty.io/blog/2019/04/26/reactive-microservices-microprofile-19004.html#oracle.
