### ISSUE TITLE
Configuration element properties.postgresql

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#4997]
User story:
"As a user of server administrator, I want Liberty to have built-in knowledge of PostgreSQL data source properties and values, so that it is easier for me to configure data sources for it."

Add a properties.postgreSQL configuration element similar to properties elements we have for other JDBC vendors.

Include example configuration alongside other data source config examples.

**Comment by aguibert** [comment]
PostgreSQL has the following properties for the various DS types:

- BaseDataSource (common to all)
  - setAllowEncodingChanges(boolean)
  - setApplicationName(String)
  - setAssumeMinServerVersion(String)
  - setAutosave(AutoSave)
  - setBinaryTransfer(boolean)
  - setBinaryTransferDisable(String)
  - setBinaryTransferEnable(String)
  - setCancelSignalTimeout(int)
  - setConnectTimeout(int)
  - setCurrentSchema(String)
  - setDatabaseMetadataCacheFields(int)
  - setDatabaseMetadataCacheFieldsMiB(int)
  - setDatabaseName(String)
  - setDefaultRowFetchSize(int)
  - setDisableColumnSanitiser(boolean)
  - setFromReference(Reference)
  - setGssLib(String)
  - setHostRecheckSeconds(int)
  - setJaasApplicationName(String)
  - setJaasLogin(boolean)
  - setKerberosServerName(String)
  - setLoadBalanceHosts(boolean)
  - setLoggerFile(String)
  - setLoggerLevel(String)
  - setLoginTimeout(int)
  - setLogUnclosedConnections(boolean)
  - setLogWriter(PrintWriter)
  - setPassword(String)
  - setPortNumber(int)
  - setPreferQueryMode(PreferQueryMode)
  - setPreparedStatementCacheQueries(int)
  - setPreparedStatementCacheSizeMiB(int)
  - setPrepareThreshold(int)
  - setProperty(String, String)
  - setProperty(PGProperty, String)
  - setProtocolVersion(int)
  - setReadOnly(boolean)
  - setReceiveBufferSize(int)
  - setReplication(String)
  - setReWriteBatchedInserts(boolean)
  - setSendBufferSize(int)
  - setServerName(String)
  - setSocketFactory(String)
  - setSocketFactoryArg(String)
  - setSocketTimeout(int)
  - setSsl(boolean)
  - setSslCert(String)
  - setSslfactory(String)
  - setSslFactoryArg(String)
  - setSslHostnameVerifier(String)
  - setSslKey(String)
  - setSslMode(String)
  - setSslPassword(String)
  - setSslPasswordCallback(String)
  - setSslRootCert(String)
  - setSspiServiceClass(String)
  - setStringType(String)
  - setTargetServerType(String)
  - setTcpKeepAlive(boolean)
  - setUnknownLength(int)
  - setUrl(String)
  - setURL(String)
  - setUser(String)
  - setUseSpNego(boolean)

- PGSimpleDataSource (javax.sql.DataSource)
<no added bean properties>

- PGConnectionPoolDataSource (javax.sql.ConnectionPoolDataSource)
  - setDefaultAutoCommit(boolean)

- PGXADataSource (javax.sql.XADataSource)
<no added bean properties>
