### ISSUE TITLE
Test jdbc-4.3 feature with older JDBC drivers

### ISSUE THREAD

**Issue by alexsm82** [OpenLiberty/open-liberty#5004]
As a user of the JDBC 4.3 feature in Open Liberty, I want to be able to use a less than JDBC 4.3 compliant driver (such as JDBC 4.0, 4.1, or 4.2) with the JDBC 4.3 feature.

**Comment by nmittles** [comment]
Manually configured testing of the JDBC 4.3 feature with older drivers for v4.2, v4.1, and v4.0. This testing included scenarios using SQL Server, DB2 and Derby.
