### ISSUE TITLE
Liberty 18.0.0.3 pb when activating the jaxb-2.2 and jaxws-2.2 features

### ISSUE THREAD

**Issue by hsajus** [OpenLiberty/open-liberty#5056]
We are experiencing an issue with Liberty 18.0.0.3.
Everything worked fine with Liberty 18.0.0.1
We first experienced the issue with Liberty 18.0.0.2 and were expecting a fix in 18.0.0.3.
 
There are seemingly related defects:
https://github.com/OpenLiberty/open-liberty/issues/4404  
https://github.com/OpenLiberty/open-liberty/issues/4399

But these issues are closed, while our problem remains!
Here is some context:
 
The problem occurs when we (or customers) activate the jaxb-2.2 and jaxws-2.2 features.
We get an JAXBException from our classes:

Caused by: javax.xml.bind.JAXBException
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]
at com.ibm.rules.res.xml.internal.JAXBContext.newInstance(JAXBContext.java:101)
at com.ibm.rules.res.model.rest.binding.internal.RESTServiceBindingBase.<init>(RESTServiceBindingBase.java:45)
... 11 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory
at com.ibm.ws.classloading.internal.AppClassLoader.findClassCommonLibraryClassLoaders(AppClassLoader.java:504)
at [internal classes]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at com.ibm.rules.res.xml.internal.JAXBContext.newInstance(JAXBContext.java:84)

The  "com.sun.xml.bind.v2.ContextFactory" class is used with java reflection api in our application:
Class clazz = Class.forName("com.sun.xml.bind.v2.ContextFactory");

Here is the feature list in the server.xml of Liberty18.0.0.1:
    <featureManager>
                <feature>servlet-3.1</feature>
                <feature>jsp-2.3</feature>
                <feature>jdbc-4.1</feature>
                <feature>appSecurity-2.0</feature>
                <feature>jaxrs-2.0</feature>
                <feature>concurrent-1.0</feature>
                <feature>jaxb-2.2</feature>
                <feature>jaxws-2.2</feature>
    </featureManager>

The feature list in the server.xml of Liberty18.0.0.3:
    <featureManager>
           <feature>servlet-4.0</feature>
          <feature>jsp-2.3</feature>
          <feature>jdbc-4.2</feature>
         <feature>appSecurity-2.0</feature>
         <feature>jaxrs-2.1</feature>
         <feature>concurrent-1.0</feature>
        <feature>jaxb-2.2</feature>
        <feature>jaxws-2.2</feature>
  </featureManager> 

Both use Sun Java 8 version.

**Comment by aguibert** [comment]
hi @hsajus, does the problem also occur when you use the exact same feature list as in 18.0.0.1?  Also, can you please post the entire stack trace?  (check in messages.log)

**Comment by barecode** [comment]
I am not sure if this is related, but using a server.xml configured as:
```
    <featureManager>
        <feature>jaxrs-2.1</feature>
        <feature>jsonp-1.1</feature>
        <feature>cdi-2.0</feature>
        <feature>transportSecurity-1.0</feature>
        <feature>appSecurity-2.0</feature>
    </featureManager>
```

I was hitting the following exception:
[9/12/18 20:10:38:880 CDT] 00000121 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.lang.ClassNotFoundException: com.ibm.ws.jaxrs20.appsecurity.security.JaxRsSSLManager cannot be found by com.ibm.ws.jaxrs.2.0.client_1.0.21.cl180220180619-0403 com.ibm.ws.jaxrs20.client.security.LibertyJaxRsClientSSLOutInterceptor 152" at ffdc_18.09.12_20.10.38.0.log

The error was clearly driven by the instantiation of a REST Client in my application (actually the openliberty.io website backend). I am not sure if this is related to the issue described here or not, but I could open a new issue if not. I discussed this briefly with @acdemyers and at the time there was some weird stuff going on... things like the server config updated in **156.537 seconds**. I never got to the bottom of it, because of course it started working (magically), but I still have the FFDC in slack if that's useful.

**Comment by hsajus** [comment]
Hi @aguibert, 
I did some tests, and I confirm that: 

in Liberty 18.0.0.1 with the above feature list.
The application works with  
Class.forName("com.sun.xml.internal.bind.v2.ContextFactory")
and
Class.forName("com.sun.xml.bind.v2.ContextFactory") doesn't work

I also tried to use the same features in Liberty 18.0.0.1 as 18.0.0.3
<featureManager>
	<feature>servlet-4.0</feature>
	<feature>jsp-2.3</feature>
	<feature>jdbc-4.1</feature>
	<feature>appSecurity-2.0</feature>
	<feature>jaxrs-2.0</feature>
	<feature>concurrent-1.0</feature>
	<feature>jaxb-2.2</feature>
	<feature>jaxws-2.2</feature>
</featureManager>

The application works. 
The Liberty version is :
WebSphere Application Server 18.0.0.1 (1.0.20.cl180120180309-2209) on Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_144-b01 (en_US)

**Comment by hsajus** [comment]
Hi @aguibert,

Thanks for your insights, they set us on the right track.
Here are the results of my tests.

When the jaxws+Jaxb feature is activated in the Liberty server, these Jaxb libs are loaded first.
Because these Jaxb libs are not the same as the Jaxb libs from the Java 8 that our application uses, we get an exception. 
If Liberty took the Java 8 libs first the application would work fine. 

(My tests also allowed me to verify that we see the same issue with Liberty 18.0.0.1 when jaxws is installed.)

The good news is that we have found a workaround to fix the problem in our application.
We're happy for you to close this issue now. 

Thanks again for your help.

**Comment by aguibert** [comment]
glad you got the issue sorted out!  Closing this item

**Comment by barecode** [comment]
@hsajus what was the workaround?
