### ISSUE TITLE
FAT test for a User Replacing the ReactiveStreams Engine with their own ServiceLoadable one (as per spec)

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#5156]
The spec hints at the ReactiveStreams Engine being service loadable (i.e. replacable by
a user) - we do service load it but have not currently got a FAT test that tests a user plugging
in their own.

**Comment by hutchig** [comment]
I chatted with James Roper in the hangout about whether CDI Inject and ServiceLoad should always see the same 'winner' and that this should be in the spec. He did not express the desire to specify this as a fixed requitement.

**Comment by tevans78** [comment]
The spec does not support or require this. It isn't possible.
