### ISSUE TITLE
clean intermediate cookie created by socialLogin-1.0 feature

### ISSUE THREAD

**Issue by chunlongliang-ibm** [OpenLiberty/open-liberty#5158]
Some intermediate cookies created by socialLogin-1.0 feature are not removed/invalidated, which prevents user to relogin if browser is not closed.
For example, after login to OIDC server with socialLogin-1.0, if you call  request.logout() then login, you can see  WASOidcNonce cookie, and get “Error 500: com.ibm.websphere.servlet.session.UnauthorizedSessionRequestException: SESN0008E”.

**Comment by ayoho** [comment]
Related to https://github.com/openliberty/open-liberty/issues/9909. I have an ongoing TODO to verify that SSO cookies are truly being deleted once they are no longer needed.

**Comment by ayoho** [comment]
Resolved and verified in https://github.com/OpenLiberty/open-liberty/pull/19775 and https://github.com/OpenLiberty/open-liberty/pull/19902
