### ISSUE TITLE
WSOC: Port websocket fvt test cases to OpenLiberty

### ISSUE THREAD

**Issue by billw1024** [OpenLiberty/open-liberty#5207]
WSOC: Port websocket fvt  test cases to OpenLiberty.

**Comment by isaacrivriv** [comment]
We decided to port the tests piece by piece to get some core test functionality for the jakarta websocket 2 feature in parallel

**Comment by isaacrivriv** [comment]
Issue to investigate which tests can still be ported over from CL and port them to OL is #12870
