### ISSUE TITLE
Notify webTarget properties change to customized service

### ISSUE THREAD

**Issue by akinlong** [OpenLiberty/open-liberty#5212]
We have a case that we want to re-use the 'javax.ws.rs.client.WebTarget' object in out rest call instance due to the huge time and resource cost on creating webTarget everytime, also, the webTarget properties will not change frequently, basically, we only need to maintained one webTarget for one URI.
 
But when we maintained one WebTarget object for each rest client, the newly updated properties in server.xml <webTarget> will not be reflected in our maintained WebTarget object. After consulting the sepcialist of the Liberty team, I finally get the udpated properties by implementing a service with configurationPid = "com.ibm.ws.jaxrs20.common.clientConfig". But the properties change involves some Liberty properties management logic, so, can you have a new feature that support we maintain one webTarget for the Rest client and got notify after the webTarget properties change?

Paste the response from the Liberty team here:
**"Unfortunately there is currently no way to automatically update existing WebTarget instances after the webTarget configuration changes.  If you use a user feature (or product extension), then you should be able to access the configuration similar to how we access it in:
https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/clientconfig/JAXRSClientConfigImpl.java
 
If it makes more sense, possibly we could add a new feature that would notify interested subscribers when the webTarget configuration changes. "**

**Comment by andymc12** [comment]
@akinlong 
Thanks for the feature request.  The Liberty JAX-RS development team has considered the issue, but we feel that the work necessary to complete the feature is greater than the benefit that it would provide to most customers - considering other development efforts that we feel would have more benefit to end-users.  We can leave this issue open, but we will not likely get to it for some time.  In the mean time, please consider writing the code to complete this feature and submit it as a pull request to Open Liberty.  Thanks again!

**Comment by tevans78** [comment]
Closing this issue.
