### ISSUE TITLE
 Support MP Config value customizationPolling (for performance)

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty#530]
The customization definition file can be dropped to a specific location and it'll be automatically picked. This means that the file will need to be continuously monitored. For performance reasons, support a MP Config key called 'customizationPolling' to control how frequently the files are checked/monitored.

Something to consider for performance : 
- a special value that'll turn off file monitoring altogether. For customers who doesn't want to modify the UI.
- a special value that'll pick up the file from the default location only once at start up - for customers whose customization doesn't change dynamically.

**Comment by leochr** [comment]
@mrglavas this is the customization polling item we discussed yesterday. can I assign this to you?

**Comment by mrglavas** [comment]
@leochr: Introducing a property called **mp.openapi.extensions.liberty.file.polling.interval** for customizing the polling interval for files monitored by the mpOpenAPI-1.0 feature. The value of this property is a non-negative integer. The unit for the interval is seconds. The default value is 2 (two seconds). Setting the value to 0 will disable file monitoring.

**Comment by mrglavas** [comment]
If file monitoring is disabled a file that would be monitored is only read once when the feature is enabled.

**Comment by mrglavas** [comment]
Merged with the team's collaboration branch.
