### ISSUE TITLE
Customizing OpenAPI UI

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty#531]
The OpenAPI UI should be customizable in Open Liberty (logo and header). The customization definition can be dropped to a specific location within the server (e.g. mpopenapi or openapi) and will be automatically picked up. 

Include automated tests to ensure the functionality of customization is working as expected (initial pickup of customization files, file monitoring, restoring to default, etc).

Ensure there is no caching issues (UI is customized --> server is stopped and customization file is removed --> start server --> UI should be default). 

Note: The OpenAPI definition wouldn't have to be customizable since only one application is supported at a time, so it's definition can be used as is.

The underlying logic to update the UI will be similar to the existing code from commercial Liberty (openapi-3.0 feature), so try to port/share the code if possible.

**Comment by leochr** [comment]
Opened #2134 for the automated tests portion.

**Comment by mrglavas** [comment]
Support for customizing the OpenAPI UI was delivered in: https://github.com/arturdzm/open-liberty/pull/46 to the team's collaboration branch.

**Comment by inad9300** [comment]
@leochr could you please explain how to make use of this feature? I've checked https://www.ibm.com/docs/en/was-liberty/core?topic=openapi-customizing-user-interface, which suggests placing a file inside `$server.config.dir`, but this directory is autogenerated and not committed to version control (I'm using `liberty-maven-plugin`).

**Comment by inad9300** [comment]
In case anyone arriving here is interested, I finally managed by simply placing the file `customization.css` under `src/main/liberty/config/mpopenapi`.
