### ISSUE TITLE
Modify default ldapRegistry-3.0 read timeout to be 1 minute

### ISSUE THREAD

**Issue by jvanhill** [OpenLiberty/open-liberty#5341]
The ldapRegistry-3.0 uses an infinite read timeout. This can lead to user requests hanging for long periods of time. This consumes worker threads and contexts from the LDAP registry's context pool, both resulting in poor performance.

Issue #3383 was completed to allow the customer to specify their own timeout.

Modify the default read timeout to be 1 minute to match both the JNDI search timeout and the connect timeout.

See issue #4949 for more details on the decision to make this change.

**Comment by jvanhill** [comment]
@NottyCode - I marked this as a 'release bug' since customers have seen this occur out in the wild and (although extremely unlikely) there is a chance that a customer may see requests that take over a minute now aborted. In the latter case, it might be helpful for them to find this issue on their own. Let me know if you disagree.

**Comment by agiridharan** [comment]
fixed in #5513
