### ISSUE TITLE
Make all openid, jwt and social components proxy aware

### ISSUE THREAD

**Issue by barbj** [OpenLiberty/open-liberty#5409]
Make all openid, jwt, jwk and social components use of the HTTP client proxy aware.  We need to default to not using system properties and give the user the option to use system properties.  When they want to use system properties, do the following:

HttpClientBuilder builder = HttpClientBuilder.create();
builder.useSystemProperties();
...

**Comment by brutif** [comment]
resolved by #5484 , #5715
