### ISSUE TITLE
Update Weld to 3.1.0 and move weld 3 to a 2 digit versoning scheme

### ISSUE THREAD

**Issue by benjamin-confino** [OpenLiberty/open-liberty#5435]
Every time weld releases a new update we have to manually go through and update the version number in many different files. We should move the weld osgi bundle to a 2 digit version scheme to prevent having to do this all the time. 

(From what weld said last time I spoke 2.4.8 might be the last 2.4 bundle, but we should do this for weld 3)

**Comment by tevans78** [comment]
https://github.com/OpenLiberty/open-liberty/pull/5434 is an example of how having the third digit in there makes an update much harder. @Emily-Jiang what do you think?

**Comment by tevans78** [comment]
Complete
