### ISSUE TITLE
JMSContextInjectionBean uses deprecated CDI method

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#5441]
Running JMS and CDI 2.0 together gets this warning:

[WARNING ] WELD-000146: BeforeBeanDiscovery.addAnnotatedType(AnnotatedType<?>) used for class com.ibm.ws.cdi.jms.JMSContextInjectionBean is deprecated from CDI 1.1!

while this still works and the code is common between CDI 1.0 and the newer CDI versions we should fix it so we aren't producing this kind of warning.

**Comment by benjamin-confino** [comment]
I've merged in a fix, we now have a new util method to generate IDs in a standard way for the addAnnotatedType method and I've ensured all calls to that method use it.
