### ISSUE TITLE
Servlet4.0 should only work with CDI 2.0

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#547]
Servlet 4.0 should only work with CDI 2.0 feature not CDI 1.2.

**Comment by Emily-Jiang** [comment]
@mmulholl , @tevans78 spotted that the Servlet 4.0 has not implemented the interfaces under com.ibm.ws.webcontainer31.osgi.listener.*. I understand that the feature Servlet 4.0  is not complete as yet. Can you ensure the interfaces were implemented in Servlet 4.0 as part of this issue?

**Comment by tevans78** [comment]
I think Martin confirmed that the listener interfaces under webcontainer31 are reused for 40. Therefore, I think this issue can be closed.
