### ISSUE TITLE
Feature Test Summary for Policy executor for Microprofile and Managed Executors

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#552]
# _1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule._

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the [CSI Team](https://github.com/OpenLiberty/open-liberty/wiki/OpenLiberty-Teams) who can provide advice and verify if results are being received)?_

### com.ibm.ws.concurrent_fat_policy: ConcurrentPolicyExecutorTest

testAbortWhenQueueFull - Submit a task when the queue is at capacity. Expect the submit to be aborted, with the proper exception raised and ManagedTaskListener taskAborted signal sent.

testAbortWhenQueueWaitInterrupted - Submit a task when the queue is at capacity. Interrupt it before maxWaitForEnqueue is exceeded. Expect the submit to be aborted, with the proper exception raised and ManagedTaskListener taskAborted signal sent.

testAllResourcesInjected - Tests injection of managed executors and other resources used by the tests. If this doesn't work, expect many (possibly all) other tests to fail.

testFailInvokeAllOnSecondSubmit - Attempt to submit 2 tasks via invokeAll where the second task's ManagedTaskListener fails during taskSubmitted (force a NamingException by looking up an invalid name). Expect the first task, although submitted, to be canceled when invokeAll is rejected.

testInvokeAllListenersWithLookups - Use untimed invokeAll to submit 3 tasks with ManagedTaskListeners that perform JNDI lookups on taskSubmitted, taskStarting, and taskDone.

testInvokeAllMixedPoliciesTimed - Submit normal and long-running tasks in a single request to timed invokeAll.

testInvokeAllMixedPoliciesUntimed - Submit normal and long-running tasks in a single request via untimed invokeAll. Untimed invokeAll can run normal tasks on the current thread in excess of max concurrency per the maxPolicy=loose configuration.

testInvokeAnyMixedPoliciesRunLongRunning - Submit a normal task and a long running task via invokeAny, where the normal policy has max concurrency used up. The long running task must run and return its result from invokeAny.

testInvokeAnyMixedPoliciesRunNormal - Submit a normal task and a long running task via invokeAny, where the long-running policy has max concurrency used up. The normal task must run and return its result from invokeAny.

testStartTimeoutFutureGet - Submit a task that exceeds its start timeout.  Verify that Future.get returns an AbortedException after the timeout elapses.

testStartTimeoutFutureStatusMethods - Submit a task that exceeds its start timeout. Verify that status methods on Future such as isDone are consistent with an aborted task once the start timeout elapses.

testStartTimeoutInvokeAll - Submit a group of tasks to timed invokeAll, where all tasks exceed the startTimeout. Verify that invokeAll returns once the tasks time out, rather than after the larger timeout that was supplied to invokeAll.

testStartTimeoutInvokeAny - Submit a group of tasks to timed invokeAny, where all tasks exceed the startTimeout. Verify that invokeAny raises TimeoutException.

### com.ibm.ws.concurrent_fat_config: EEConcurrencyConfigTest

testLongRunningPolicyRef - Should be possible to make modifications to which concurrency policy a managed executor points at via its longRunningPolicyRef without interfering with tasks that are in-progress or queued. For this test, we set max concurrency to 1 and submit two long running tasks, where the first depends on the second, such that the first is blocked while running and the second is stuck in the queue - a temporary deadlock of the executor. Then, we switch which concurrency policy the managed executor's longRunningPolicyRef points to and verify that we can submit and run tasks per the new policy. Then, we increase max concurrency of the old policy 2 and expect both of the previous tasks to complete successfully.

testNestedConcurrencyPolicy - Should be possible to make modifications to a concurrencyPolicy that is nested under a managed executor without interfering with tasks that are in-progress or queued. For this test, we set max concurrency to 1 and submit two tasks, where the first depends on the second, such that the first is blocked while running and the second is stuck in the queue - a temporary deadlock of the executor. Then, we increase max concurrency to 2 and expect both tasks to complete successfully.

testNestedLongRunningPolicy - Should be possible to make modifications to a longRunningPolicy that is nested under a managed executor without interfering with tasks that are in-progress or queued. For this test, we set max concurrency to 1 and submit two tasks, where the first depends on the second, such that the first is blocked while running and the second is stuck in the queue - a temporary deadlock of the executor. At this point, we can still submit normal tasks (not long running) per the normal concurrencyPolicy. Then, we increase the long running policy's max concurrency to 2 and expect both long running tasks to complete successfully.

testPolicyRef - Should be possible to make modifications to which concurrency policy a managed executor points at without interfering with tasks that are in-progress or queued. For this test, we set max concurrency to 1 and submit two tasks, where the first depends on the second, such that the first is blocked while running and the second is stuck in the queue - a temporary deadlock of the executor. Then, we switch which concurrency policy the managed executor points to and verify that we can submit and run tasks per the new policy. Then, we increase max concurrency of the old policy 2 and expect both of the previous tasks to complete successfully.

testTasksCanceledOnDeactivate - Verify that both long running as well as normal tasks submitted by a managed executor are canceled when the managed executor deactivates. We test this by submitting 2 normal tasks and 2 long running tasks to a managed executor with concurrency policies that only allow 1 to run at time, and where the first task blocks when it runs, leaving the other tasks stuck in the queue. Then we remove the configuration of the managed executor to make it deactivate and verify that all of the task Futures are canceled.

Added the following tests to this bucket,

### com.ibm.ws.threading.policy_fat: PolicyExecutorTest

Added the following tests to this bucket,

testCallbacksForAbortedTasks - Verify that the onEnd(aborted) callback is sent for tasks that abort after they are submitted but before they start to run. This test covers a task that is aborted to due to exceeding the maximum queue size and a task that is aborted due to being interrupted while waiting for a queue position.

testCancelOnStart - Cancel tasks during the onStart callback. Verify that tasks are canceled and do not run, implying that the onStart callback is being invoked.

testCancelOnStartWithInterrupt - Cancel tasks during the onStart callback, where cancel interrupts the thread of execution. Verify that tasks are canceled and do not run, implying that the onStart callback is being invoked.

testCancelOnSubmit - Cancel tasks during the onSubmit callback. Verify that tasks are canceled and do not run, implying that the onSubmit callback is being invoked.

testConcurrencyCallback - Register concurrency callbacks with a policy executor. Verify that at most one can be registered, that the most recently registered replaces any previous ones, and that the concurrency callback can be unregistered by supplying null. Verify that the concurrency callback is notified when the number of running tasks exceeds the threshold.

testConcurrentAwaitTerminationAfterShutdownNow - updated to add coreConcurrency set to 0

testFailOnSubmit - Submit a task that fails during onSubmit by raising a RuntimeException subclass. The task submission must be aborted and elapsed queue/run times must be 0.

testIdentifiers - updated to add coreConcurrency with a value less than maxConcurrency, where the identifier is later reused with a maxConcurrency value that is less than the previous executor's coreConcurrency. This is valid because the identifier is being reused for a new instance.

testInvokeAll - Use invokeAll to run a group of tasks. Some might run on pooled threads. Some might run on the current thread. The last task in the list will always run on the current thread (implementation detail).

testInvokeAllAbortIgnoredWhenConcurrencyUnlimited - Use invokeAll where maxQueueSize is constrained to 1 and queueFullAction is Abort and maxConcurrency is unlimited. Normally, the queue size of 1 would risk having task submissions aborted when tasks are not pulled from the queue for execution quickly enough. However, the fact that the user has specified the untimed invokeAll operation to wait for all tasks to be completed means that the current thread can be used to help complete the tasks in the  even that they cannot be queued, so it is not necessary to resort to the queueFullAction.

testInvokeAllAfterShutdown - Attempts the timed and untimed invokeAll operations on a policy executor instance that has been shut down, expecting it to be rejected.

testInvokeAllCallerRunsWhenQueueFull - Use invokeAll where one or more tasks must run on the current thread due to the queue being full. To achieve this, we constrain maxConcurrency and maxQueueSize to 1 and supply 4 tasks to invokeAll, where the first task blocks until all others start. This maxConcurrency to be exceeded, which is only possible due to the CallerRuns queueFullAction.

testInvokeAllInterruptedWhileRunningTaskAfterOtherTasksSubmitted - Test the code path where untimed invokeAll is interrupted while it is running a task on the current thread after the other tasks have been successfully submitted. Once interrupted, invokeAll must immediately cancel all of its tasks which have not already completed and return.

testInvokeAllInterruptedWhileRunningTaskThatCannotBeSubmitted - Test the code path where untimed invokeAll is interrupted while it is running a task on the current thread because the queue has reached capacity. Once interrupted, invokeAll must immediately cancel all of its tasks which have not already completed and return.

testInvokeAllOfOneAndNone - Use invokeAll where the group of tasks to invoke is a single task and where it is no tasks at all. When a single task is invoked, it runs on the current thread if a permit is available, and otherwise on a separate thread. However, if using CallerRuns, then it always runs on the current thread regardless of whether a permit is available.

testInvokeAllOnCurrentThread - Use invokeAll where all tasks run on the current thread because there is only 1 maxConcurrency permit available.

testInvokeAllOnCurrentThreadCallerRunsWithoutPermit - Use invokeAll where all tasks run on the current thread even without a maxConcurrency permit due to the CallerRuns action.

testInvokeAllInvalidParameters - Test invalid parameters for invokeAll. This includes a null task list, null as the only element in the task list and null within a list of otherwise valid tasks.

testInvokeAllTasksThatRaiseExceptions - Invoke a group of tasks where some of the tasks raise exceptions during execution. This should not cause invokeAll to return prematurely and all other tasks must be allowed to continue to completion.

testInvokeAllTimed - Submit and wait for groups of tasks via the timed invokeAll method. Includes coverage of scenarios where core/max concurrency is insufficient to run all of the tasks at once, and where the maximum queue size is insufficient to allow all of the tasks to be queued and requires waiting.

testInvokeAllTimedInterruptWaitForCompletion - Interrupt timed invokeAll while that tasks that it submitted are in progress. All of the tasks should be canceled when invokeAll returns and finish stopping in a timely manner.

testInvokeAllTimedInterruptWaitForEnqueue - Interrupt timed invokeAll while it is waiting for a queue position in order to submit one of the tasks. All of the tasks that previously started should be canceled when invokeAll returns and finish stopping in a timely manner.

testInvokeAllTimedInvalidParameters - Test invalid parameters for invokeAll with timeout. This includes a null task list, null as the only element in the task list, null within a list of otherwise valid tasks, null time unit, and negative timeout.

testInvokeAllTimedTimeoutWaitForCompletion - Using timed invokeAll submit a group of tasks where some block, such that invokeAll times out before all of the tasks complete. Verify that the blocking tasks are canceled such that invokeAll can return in a timely manner, and that any non-blocking tasks completed, either successfully or exceptionally.

testInvokeAllTimedTimeoutWaitForEnqueue - Using timed invokeAll where the timeout is much longer than the maxWaitForEnqueue and maxConcurrency is less than the number of tasks submitted, submit several tasks that start and block. Should be rejected waiting for a queue position and all in-progress tasks should cancel before returning from invokeAll. Rejection should occur even if QueueFullAction is CallerRuns because timed invokeAll disallows having the caller run tasks such that the timing can be honored.

testInvokeAllTimeoutWaitForEnqueue - Using the untimed invokeAll where maxConcurrency is less than the number of tasks submitted, submit several tasks that start and block. Should be rejected waiting for a queue position and all in-progress tasks should cancel before returning from invokeAll.

testInvokeAny1Successful - Basic test of untimed invokeAny. Submit a group of tasks, of which one raises an exception, another runs for a long time, and another completes successfully within a short time. The result of the one that completed successfully should be returned, and the duration of the invokeAny method should show that it only waited for the first successful task.

testInvokeAnyAllFail - Submit a group of tasks to untimed invokeAny, where all fail during execution. Verify that an ExecutionException is raised which chains one of the failures.

testInvokeAnyAllSuccessful - Submit a group of tasks via untimed invokeAny, where all are able to complete successfully. Verify that invokeAny returns the result of one of the successful tasks.

testInvokeAnyExceedMaxWaitForEnqueue - Verify that untimed invokeAny stops trying to submit tasks after reaching the maxWaitForEnqueue. It should not keep applying the maxWaitForEnqueue in attempting to submit every task in the list.

testInvokeAnyInterruptRunningTask - Submit tasks via timed and untimed invokeAny that interrupts itself in order to test appropriate handling of InterruptedException during execution.  ExecutionException with chained InterruptedException must be raised when running on a different thread, which is consistent with an asynchronous task failing. When running on the same thread (untimed invokeAny with single task), InterruptedException should be raised directly to the caller, which indicates an interruption of thread of execution of invokeAny.

testInvokeAnyInterruptWaitForCompletion - Submit a group of tasks to untimed invokeAny, one of which raises an exception and another of which blocks. Interrupt the invokeAny operation before it completes. Expect InterruptedException.

testInvokeAnyInterruptWaitForEnqueue - Submit a group of tasks to untimed invokeAny, one of which raises an exception, another of which blocks all others from starting, another of which it stuck in the queue, and another of which is blocked attempting to get a queue position. Interrupt the invokeAny operation before it completes. Expect InterruptedException.

testInvokeAnyInvalidParameters - Test invalid parameters for invokeAny. This includes a null task list, an empty task list, null as the only element in the task list and null within a list of otherwise valid tasks.

testInvokeAnyNullSuccessfulResult - Submit a group of tasks via untimed invokeAny, where one of the tasks promptly returns a null result, and another returns a non-null result after a delay. Verify that the result of invokeAny is null. This test verifies that the implementation is not limited to awaiting non-null results, and handles null properly. Also verifies that the other task ends before it otherwise would have due to the implicit cancel/interrupt upon return of invokeAny.

testInvokeAnyOfOne - Submit a single task via untimed invokeAny. If a permit is available or a permit isn't required to run tasks, then it should run on the caller's thread. Otherwise, it should run on a separate thread.

testInvokeAnyTimed1Successful - Basic test of timed invokeAny. Submit a group of tasks, of which one raises an exception, another runs for longer than the timeout, and another completes successfully. The result of the one that completed successfully should be returned, and the duration of the invokeAny method should not exceed the timeout.

testInvokeAnyTimed1TimesOut1Fails - Submit a group of tasks to invokeAny, of which one raises an exception and another runs for longer than the timeout. TimeoutException should occur.

testInvokeAnyTimedAllFail - Submit a group of tasks to timed invokeAny, where all fail during execution. Verify that an ExecutionException is raised which chains one of the failures.

testInvokeAnyTimedAllSuccessful - Submit a group of tasks to timed invokeAny, where all are able to complete successfully. Verify that invokeAny returns the result of one of the successful tasks.

testInvokeAnyTimedAllTimeout - Submit a group of tasks to timed invokeAny, where all tasks block and exceed the timeout. Verify that invokeAny raises TimeoutException.

testInvokeAnyTimedInterruptWaitForCompletion - Submit a group of tasks to timed invokeAny, one of which raises an exception and another of which blocks. Interrupt the invokeAny operation before it completes. Expect InterruptedException.

testInvokeAnyTimedInterruptWaitForEnqueue - Submit a group of tasks to timed invokeAny, one of which raises an exception, another of which blocks all others from starting, another of which it stuck in the queue, and another of which is blocked attempting to get a queue position. Interrupt the invokeAny operation before it completes. Expect InterruptedException.

testInvokeAnyTimedNullSuccessfulResult - Submit a group of tasks to timed invokeAny, where one of the tasks promptly returns a null result, and another returns a non-null result after a delay.  Verify that the result of invokeAny is null. This test verifies that the implementation is not limited to awaiting non-null results, and handles null properly. Also verifies that the other task ends before it otherwise would have due to the implicit cancel/interrupt upon return of invokeAny.

testInvokeAnyTimedShutdownNowWhileEnqueued - Submit a group of tasks via timed invokeAny. Allow the tasks to be enqueued, but blocked from starting because another thread holds the only permit against maxConcurrency. Then invoke shutdownNow on the executor, all of the queued tasks should be canceled without starting, allowing invokeAny to raise a CancellationException before reaching the timeout.

testInvokeAnyTimedShutdownNowWhileRunning - Submit a group of tasks via timed invokeAny. Have all of the tasks block and then invoke shutdownNow on the executor. All of the tasks should be canceled and interrupted, allowing invokeAny to raise a CancellationException before reaching the timeout.

testInvokeAnyTimedTimeoutDuringWaitForEnqueue - Submit a group of tasks to timed invokeAny, where there are insufficient queue positions to enqueue the tasks and the timeout occurs while waiting or a queue position to become available rather than while running the task.

testLateStartCallback - Register late start callbacks with a policy executor. Verify that at most one can be registered, that the most recently registered replaces any previous ones, and that the late start callback can be unregistered by supplying null. Verify that the late start callback is notified when a task starts after the designated threshold.

testMultipleLayersOfInvokeAll - Invoke groups of tasks on the policy executor that break themselves into multiple tasks that also invoke groups of tasks on the policy executor, which in turn break themselves down and invoke more groups of tasks, and so forth.

testMultipleLayersOfSubmits - updated to add coreConcurrency with a value equal to maxConcurrency, in a test where the full amount of the coreConcurrency is required in order for the tasks submitted by the test to complete successfully.

testQueueSizeCallback - Register queue size callbacks with a policy executor. Verify that at most one can be registered, that the most recently registered replaces any previous ones, and that the queue size callback can be unregistered by supplying null. Verify that the queue size callback is notified when the queue capacity drops below the threshold, either by using up queue positions, or by decreasing the size of the queue.

testRecursiveTasks - updated to add coreConcurrency with a value less than maxConcurrency

testRunIfQueueFull - Verify that tasks submitted via the execute and submit methods run on the caller thread when the queue is full if runIfQueueFull is set to true, unless maxConcurrencyAppliesToCallerThread is true and maxConcurrency is used up.

testShutdownDuringTimedInvokeAll - Tests behavior when shutdown occurs while timed invokeAll is submitting and running tasks. Supply a group of 5 tasks to invokeAll. The first task should complete successfully. The second task shuts down the executor. When the executor shuts down, the third and fourth tasks might or might not have been enqueued, depending on timing. However, the fifth task will not have been enqueued yet due to a maximum concurrency of 1 and maximum queue size of 2. The shutdown should prevent further enqueuing of tasks which causes the invokeAll operation to be rejected.

testShutdownNowDuringInvokeAll - Tests behavior when shutdownNow occurs while invokeAll is submitting and running tasks. Supply a group of 3 tasks to invokeAll. The first task should complete successfully. The second task waits for the third to start and then shuts down the executor. Relying on behavior of policy executor that runs invokeAll tasks in reverse order on the current thread if the global executor hasn't been able to start them, the third (last) task should start on the current thread and block until canceled by shutdownNow.

testStartTimeout - Submit a task that gets queued but times out (due to startTimeout) before it can run.

testStartTimeoutFromQueue - Submit tasks that get queued, but time out (due to startTimeout) while in the queue due to other submits needing their queue positions.

testStartTimeoutWhenAnotherTaskWaitsForEnqueue - Submit a task that gets queued but times out (due to startTimeout) while in the queue due to another submit that is waiting for enqueue.

testGetRunningTaskCount - Test the getRunningTaskCount method

testQueueCapacityRemaining - Test that testqueueCapacityRemaining is correct as tasks are queued, run, and the maxQueueSize value is changed.

### com.ibm.ws.threading.internal.PolicyExecutorTest

Added the following tests,

testExpedite - Verify that tasks expedited by policy executors are executed ahead of normal tasks.  To accomplish this, we are constructing a special copy of the Liberty global thread pool implementation with only 1 thread, then creating 2 policy executors against it, one of which can expedite and the other of which cannot.  We first submit tasks from the non-expediting policy executor (the first one blocking so that tasks can queue up), and then submit tasks from the expediting policy executor, and then verify the order in which tasks runs has the expedited tasks running first (after the started one) followed by the others.

testExpediteConfiguration  - Verify that the configured number of expedites can be -1 (unlimited) but otherwise not negative or greater than maximum concurrency, except where maximum concurrency is -1 (unlimited).

testIntrospector - Test introspector output for policy executors.

testScheduledTasksAreExpedited - Test that scheduled tasks (both runnable and callable) are expedited.

## Queue Implementation

We tested five different queue implementations for performance and choose the improved version of the BoundedBuffer, since it scaled to 100% CPU usage better than the other implementations, allowing for higher throughput.

# _2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole._

_Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:_

_0 - No automated testing delivered_

_1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature._

_2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths_

_3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level._

_4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide._

_5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature._

5

_Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)_

**Comment by sabolo** [comment]
Many thanks for completing the test summary.  All looks good so approved.
