### ISSUE TITLE
Orb's yoko implementation performance is too bad

### ISSUE THREAD

**Issue by wuleixy** [OpenLiberty/open-liberty#5635]
Orb's yoko implementation performance is too bad, 10 times slower than weblogic.
Why not use the same implementation as WAS.

**Comment by ngmr** [comment]
The Yoko ORB was chosen to be used so that Liberty could remain Java SDK / JRE implementation agnostic.

**Comment by tevans78** [comment]
I'm sorry but we currently have no plans for any yoko performance improvments.
