### ISSUE TITLE
Fix --include default to have /usr for server and shared folder

### ISSUE THREAD

**Issue by hlhoots** [OpenLiberty/open-liberty#5647]

**Comment by hlhoots** [comment]
fixing bug in #4480

**Comment by hlhoots** [comment]
#build 

Added message and code to ignore --server-root=XYZ and --include=runnable.  Default of /wlp for server root will be used.

**Comment by marikaj123** [comment]
Translation is required

**Comment by hlhoots** [comment]
merged to master. closing.
