### ISSUE TITLE
MP Context Propagation guide

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#5690]
User story:
"As a user of Liberty, I would like to see examples of how to use MicroProfile Context Propagation so that it will be easier and quicker to write applications."

corresponds to:
https://github.com/OpenLiberty/guides-common/issues/219

When someone picks this up, please work with Michael Broz on the above issue.

The following is good candidate for an existing guide to update to use MP Context Propagation,
https://openliberty.io/guides/bulkhead.html
Specifically, replacing the following sort of code was one of the main drivers for MP Context Propagation,
```
return CompletableFuture.completedFuture( chatService );
```
when the customer adds dependent stages to the resulting CompletableFuture, they neither run on the Liberty thread pool (if Async) nor do they have deterministic thread context.  MP Context Propagation solves this problem.  So it could be a natural place to include it in the guide.

Depends on the MicroProfile Context Propagation Epic #5301

**Comment by mswatosh** [comment]
Updates are in this pull:
https://github.com/OpenLiberty/iguide-bulkhead/pull/177
Waiting on mpContextPropagation-1.0 GA

**Comment by mswatosh** [comment]
Changes are merged.
