### ISSUE TITLE
Expose ConnectionManagerMBean as API

### ISSUE THREAD

**Issue by alexsm82** [OpenLiberty/open-liberty#5751]
The ConnectionManagerMBean is correctly registered and exposed as an MBean but it is not exposed as API.  The MBean should be properly exposed as API so it is easier to use programmatically and the interfaces are javadoc'd.

I also noticed the Javadoc appears incorrect for purgePoolContents as it doesn't mention the abort option.

**Comment by alexsm82** [comment]
Yes @frowe , it does appears to be a dup, I didn't know #1979 existed when I opened this issue.  The only thing mentioned in this issue that isn't mentioned in the other is fixing the javadoc for purgePoolContents.

**Comment by frowe** [comment]
I've added the update to #1979, if you'd like to code this issue.
