### ISSUE TITLE
Include location doe's not work with a Bootstrap Property

### ISSUE THREAD

**Issue by c-koell** [OpenLiberty/open-liberty#5777]
If i try to include a configuration file based on a Bootstrap Property i do always get the error that the file ${variable_name} could not be found.

Example:
`<server description="new server">
    ...
    <include location="${configPath}" />
</server>`

and in my bootstrap.properties file i have following entry:
`configPath=C:/.../config.xml`

Should this work ?

**Comment by hlhoots** [comment]
Hi.

It should work.  I just verified it on my Windows machine on the latest Open Liberty release.  You do need to have quotes around the entry in bootstrap.properties:

configPath="c:/temp/config.xml"

Some more details on the topic are here:
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_setup_vars.html
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_setup_includes.html

**Comment by c-koell** [comment]
Thanks for the hint regarding quotes ! That solved the problem.

Sorry for the noise ...
