### ISSUE TITLE
CWWKS9582E: The [defaultSSLConfig] sslRef attributes required by the orb element with the defaultOrb id have not been resolved within 10 seconds.

### ISSUE THREAD

**Issue by dburdine** [OpenLiberty/open-liberty#5785]
During Server initialization the following error is seen:
CWWKS9582E: The [defaultSSLConfig] sslRef attributes required by the orb element with the defaultOrb id have not been resolved within 10 seconds.

**Comment by dburdine** [comment]
The fix will be to enable the timeout value to be configurable. Currently it is hardcoded at 10 seconds.

**Comment by dburdine** [comment]
PR#5788

**Comment by dburdine** [comment]
Property orbSSLInitTimeout has been added. Here is an example setting the timeout to 33 seconds:
    <orb id="defaultOrb" orbSSLInitTimeout="33">
        <serverPolicy.csiv2>
            <layers>
                <attributeLayer identityAssertionEnabled="false"/>
                <authenticationLayer mechanisms="LTPA" establishTrustInClient="Never"/>
                <transportLayer sslRef="requiredClientAuthenticationSSLConfig" />
            </layers>
        </serverPolicy.csiv2>
    </orb>

**Comment by toshiyamamoto** [comment]
The original fix was reverted, so this issue is reopened.

**Comment by dburdine** [comment]
Resolved by PR 5983
