### ISSUE TITLE
SCIM create fails with DefaultParentNotFoundException when multiple repositories are federated

### ISSUE THREAD

**Issue by jvanhill** [OpenLiberty/open-liberty#5832]
When multiple repositories are federated, SCIM create operations may fail with DefaultParentNotFoundExceptions, like the following:

```
com.ibm.wsspi.security.wim.exception.DefaultParentNotFoundException: CWIML0516E: The default parent for Group cannot be determined. Verify that the configuration for the FederatedRealm realm is correct.
	at com.ibm.ws.security.wim.ProfileManager.createImpl(ProfileManager.java:2882)
	at com.ibm.ws.security.wim.ProfileManager.genericProfileManagerMethod(ProfileManager.java:247)
	at com.ibm.ws.security.wim.ProfileManager.create(ProfileManager.java:2752)
	at com.ibm.ws.security.wim.VMMService.create(VMMService.java:330)
```

This occurs since SCIM does not specify a parent, and WIM does not make a best effort to determine where the new entry should go. Either:

1. SCIM should be updated to set a parent on the request
2. WIM should be updated to check the base entry on the unique name and match it with a repository
3. or both options should be performed.

To work around the issue if you only want to write to one repository, the following configuration can be added, where 'dc=ibm,dc=com' is the base entry of the repository to write to.

```
 <federatedRepository>
      <supportedEntityType>
	<name>Group</name>
	<defaultParent>dc=ibm,dc=com</defaultParent>
      </supportedEntityType>
      <supportedEntityType>
	<name>PersonAccount</name>
	<defaultParent>dc=ibm,dc=com</defaultParent>
      </supportedEntityType>
</federatedRepository>
```

There is no work-around to write to multiple repositories.

**Comment by ryanesch** [comment]
Resolved https://github.com/OpenLiberty/open-liberty/pull/6281
