### ISSUE TITLE
OpenAPI support for multiple modules

### ISSUE THREAD

**Issue by igbluz** [OpenLiberty/open-liberty#5839]
As a developer I would like to have the flexibility in design my Application which can consist of several modules packed into one EAR. Each module can be a WAR which does implement a REST-Service by an OpenAPI contract. Now when deploying the EAR to the OpenLiberty Server I would like to see the aggregated OpenAPI documents like it is existing on IBM Liberty Server using the feature `openapi-3.1`.

**Comment by arthurdm** [comment]
For background purposes, @igbluz and I exchanged notes on [this](https://stackoverflow.com/questions/53388213/openapi-multimodule-ear-deployment) stackoverflow issue, and I suggested a feature request be opened here for future consideration.

**Comment by Warkdev** [comment]
Hello,

Is this something you're planning to implement at some point ?

I've seen that Openapi3.1 seems to be available in OpenLiberty 20.0.0.9 (https://openliberty.io/docs/20.0.0.9/reference/feature/openapi-3.1.html) but I can't find anyway to load it properly. I'm on OL20.0.0.11.

Thanks.

**Comment by Azquelt** [comment]
This has been implemented for `mpOpenApi-2.0` in #16628 which is available now in the [21.0.0.12 beta][beta-blog].

[beta-blog]: https://openliberty.io/blog/2021/11/02/microprofile-jakarta-210012-beta.html#mpOpenApi_multiple_apps

**Comment by Azquelt** [comment]
Released in 22.0.0.1
