### ISSUE TITLE
Make mpJwt audiences property configurable via mpConfig

### ISSUE THREAD

**Issue by tnsasse** [OpenLiberty/open-liberty#5840]
Using MP-JWT we can specify `mp.jwt.verify.issuer` and `mp.jwt.verify.publickey` via MP-Config, which is nice. However I found myself having to also specify the trusted audiences property, which to my knowledge is only possible via a server.xml entry like this:

`<mpJwt id="defaultMpJwt" audiences="MYTRUSTEDAUDIENCE" />`

This forces me to distribute my configuration parameters to several places. I'd like to suggest the improvement of specifying the audiences property via mpConfig, as we already have for the issuer and publickey properties. Maybe something like this:

```
mp.jwt.verify.publickey=abc
mp.jwt.verify.issuer=abc
mp.jwt.verify.audiences=abc
```

**Comment by chunlongliang-ibm** [comment]
The "audience" requirement and verification have not been discussed and defined in Microprofile JWT working group yet. I will bring this to the working group for discussion.

**Comment by tevans78** [comment]
I think this issue should be tracked in the eclipse/microprofile-jwt-auth repo. Closing this issue.
