### ISSUE TITLE
Liberty excessive tracing

### ISSUE THREAD

**Issue by IvanHargreaves** [OpenLiberty/open-liberty#5895]
RELEASE BUG

product = wlp-1.0.21.cl180220180619-0403
java.home = /java/J8.0_64
java.version = 1.8.0_181
java.runtime = Java(TM) SE Runtime Environment (8.0.5.20 - pmz6480sr5fp20-20180802_01(SR5 FP20))
os = z/OS (02.02.00; s390x) (en_US)

Using the following trace specification causes excessive trace instrumentation, megabytes of trace data, and massive server slow-down compared to earlier releases of Liberty.

trace.specification = `*=info:com.ibm.*=finer`

Additionally, with the following trace specification the tracing appears to be tracing itself resulting in even more trace-entries and large quantities of data produced, particular under the x.<package> BufferManager.

trace.specification = `*=info:com.ibm.*=all`

I appreciate tracing at these levels is not recommended, however, it is a regression compared to earlier releases.

*Recreate:* Start and then later stop a Liberty server with the trace specification.

Sample server.xml is:

    <featureManager>
        <feature>jsp-2.3</feature>
        <feature>jdbc-4.1</feature>
        <feature>transportSecurity-1.0</feature>
        <feature>jsf-2.2</feature>
        <feature>jndi-1.0</feature>
        <feature>wab-1.0</feature>
        <feature>ssl-1.0</feature>
        <feature>jsf-2.2</feature>
    </featureManager>

    <httpEndpoint host="*" httpPort="27258" httpsPort="27257" id="defaultHttpEndpoint"/>
    <config monitorInterval="5s" updateTrigger="polled"/>
    <applicationMonitor dropins="dropins" dropinsEnabled="false" pollingRate="5s" updateTrigger="disabled"/>

    <cdi12 enableImplicitBeanArchives="false"/>
    <ssl id="defaultSSLConfig" keyStoreRef="defaultKeyStore" sslProtocol="TLSv1.2"/>
    <keyStore id="defaultKeyStore" password="defaultPassword"/>
    <safRegistry enableFailover="false" id="saf"/>
    <executor maxThreads="15"/>
</server>

**Comment by donbourne** [comment]
discussed on Slack that the problem is largely BufferManager trace, which, while restricted to `x.` logger name, still gets instrumented by BCI trace injection when trace.specification = `*=info:com.ibm.*=all`

**Comment by donbourne** [comment]
I think there are multiple issues mentioned in this issue.  I would suggest we just focus on...

> Additionally, with the following trace specification the tracing appears to be tracing itself resulting in even more trace-entries and large quantities of data produced, particular under the x. BufferManager.

> `trace.specification = *=info:com.ibm.*=all`

...in this issue

**Comment by kbaillie** [comment]
@IvanHargreaves we have been unable to reproduce the problem on z/OS using the trace.specification = *=info:com.ibm.*=all or trace.specification = *=info:com.ibm.*=finer . Any suggestions on how to reproduce this problem?
