### ISSUE TITLE
ContextResolver not working

### ISSUE THREAD

**Issue by felipe-alves-moraes** [OpenLiberty/open-liberty#5903]
Hi, I'm trying to test my project in openliberty, but I'm having some trouble with my ContextResolver, it simply doesn't work.

Here is the Resolver: 
```
@Provider
public class JsonConfiguration implements ContextResolver<Jsonb> {

    @Override
    public Jsonb getContext(Class<?> aClass) {
        return JsonbBuilder.newBuilder()
                .withConfig(new JsonbConfig()
                        .withPropertyVisibilityStrategy(new PrivateVisibilityJsonbStrategy()))
                .build();
    }

}
```

When I use the same code in Payara it works the way it should. Any hints of what could be wrong??

Tested using OpenLibery 18.0.0.3

**Comment by WhiteCat22** [comment]
Are you overriding `getClasses()` in your Application class?

**Comment by WhiteCat22** [comment]
> > Can you also describe how it is not working?
> 
> I'm trying to serialize my payload, using my private attributes instead of only serialize the public attributes of my class

Can you explain how you expect `JsonConfiguration` to behave and how you know that it isn't working?

**Comment by felipe-alves-moraes** [comment]
> > > Can you also describe how it is not working?
> > 
> > 
> > I'm trying to serialize my payload, using my private attributes instead of only serialize the public attributes of my class
> 
> Can you explain how you expect `JsonConfiguration` to behave and how you know that it isn't working?

Ok, I have this class:
```
@Entity
@JsonbVisibility(PrivateVisibilityJsonbStrategy.class)
public class Event {

    @Id
    @GeneratedValue
    private Long id;
    @NotNull
    private Category category;
    @NotBlank
    private String name;

    protected Event() {}

    public Event(Category category, String name) {
        this.category = category;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public Category getCategory() {
        return category;
    }
}
```
and this endpoint `localhost:9080/app/resources/events`
When I post this:
```
{
	"category": "MEETUP",
	"name": "test"
}
```
I expect it to be serialized into my class out of the box. And when I call the endpoint using GET, I expect to receive the same payload I sent.

**Comment by WhiteCat22** [comment]
Thanks, have you tried adding a `System.out.println()` message to your `getContext()` method to see if it's being called? What about your `isVisible()` methods?

**Comment by felipe-alves-moraes** [comment]
> Thanks, have you tried adding a `System.out.println()` message to your `getContext()` method to see if it's being called? What about your `isVisible()` methods?

I did this, also put some break points, nothing is called

**Comment by WhiteCat22** [comment]
> > Thanks, have you tried adding a `System.out.println()` message to your `getContext()` method to see if it's being called? What about your `isVisible()` methods?
> 
> I did this, also put some break points, nothing is called

good to know, thank you

I'll look into this and attempt to recreate. I'll update Monday afternoon.

**Comment by felipe-alves-moraes** [comment]
> > > Thanks, have you tried adding a `System.out.println()` message to your `getContext()` method to see if it's being called? What about your `isVisible()` methods?
> > 
> > 
> > I did this, also put some break points, nothing is called
> 
> good to know, thank you
> 
> I'll look into this and attempt to recreate. I'll update Monday afternoon.

Thanks, if you need some help just ping me

**Comment by scottkurz** [comment]
What features are you using?  Can you share this as a snippet from your server.xml?

**Comment by felipe-alves-moraes** [comment]
> What features are you using? Can you share this as a snippet from your server.xml?

Sure, here it is:
```
<cdi2 enableImplicitBeanArchives="false"/>
    
    <!-- Enable features -->
    <featureManager>
        <feature>javaee-8.0</feature>
        <feature>microProfile-2.0</feature>
    </featureManager>
```

**Comment by WhiteCat22** [comment]
I think what is going on is that you aren't serializing your payload yourself with the `javax.json.bind.Jsonb` object from your `ContextResolver` in your resource method. If you let Liberty serialize to `String` and then serialize yourself with your custom `javax.json.bind.Jsonb` object you will get your desired results.

I have the following code working:
```
    @GET
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @Path("events")
    public Response getEvent() {
		ContextResolver<Jsonb> resolver = providers.getContextResolver(Jsonb.class, MediaType.APPLICATION_JSON_TYPE);
		Jsonb jsonb = resolver.getContext(Jsonb.class);
    	return Response.ok(jsonb.toJson(this.event)).build();
    }
    
    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @Path("events")
    public Response newEvent(String event) {
    	ContextResolver<Jsonb> resolver = providers.getContextResolver(Jsonb.class, MediaType.APPLICATION_JSON_TYPE);
		Jsonb jsonb = resolver.getContext(Jsonb.class);
    	this.event = jsonb.fromJson(event, Event.class);
    	return Response.ok(event).build();
    }
```

**Comment by felipe-alves-moraes** [comment]
> I think what is going on is that you aren't serializing your payload yourself with the `javax.json.bind.Jsonb` object from your `ContextResolver` in your resource method. If you let Liberty serialize to `String` and then serialize yourself with your custom `javax.json.bind.Jsonb` object you will get your desired results.
> 
> I have the following code working:
> 
> ```
>     @GET
>     @Consumes(MediaType.APPLICATION_JSON)
>     @Produces(MediaType.APPLICATION_JSON)
>     @Path("events")
>     public Response getEvent() {
> 		ContextResolver<Jsonb> resolver = providers.getContextResolver(Jsonb.class, MediaType.APPLICATION_JSON_TYPE);
> 		Jsonb jsonb = resolver.getContext(Jsonb.class);
>     	return Response.ok(jsonb.toJson(this.event)).build();
>     }
>     
>     @POST
>     @Consumes(MediaType.APPLICATION_JSON)
>     @Produces(MediaType.APPLICATION_JSON)
>     @Path("events")
>     public Response newEvent(String event) {
>     	ContextResolver<Jsonb> resolver = providers.getContextResolver(Jsonb.class, MediaType.APPLICATION_JSON_TYPE);
> 		Jsonb jsonb = resolver.getContext(Jsonb.class);
>     	this.event = jsonb.fromJson(event, Event.class);
>     	return Response.ok(event).build();
>     }
> ```

I have the project on my repository [here](https://github.com/felipe-alves-moraes/events), and my class 
[JsonConfiguration](https://github.com/felipe-alves-moraes/events/blob/master/src/main/java/com/fmoraes/events/JsonConfiguration.java) should handle this automatically

**Comment by felipe-alves-moraes** [comment]
Thanks @WhiteCat22, I'll take a look in this class and see if I'm able to submit a PR. If I can understand and add this lookup, I do it.

**Comment by felipe-alves-moraes** [comment]
@WhiteCat22 while trying to implement this feature, I end up finding this [Apache-CXF doc](https://cwiki.apache.org/confluence/display/CXF20DOC/JAX-RS+Basics), saying that the don't support automatic registration of `@Provider` classes. So the problem is not with the server lacking a feature I guess, it's CXF framework that don't support this feature. 

Now I'm not sure what should be done.

**Comment by felipe-alves-moraes** [comment]
> Hi Felipe, I'm not sure if that is bad doc, or if it is something that we do that CXF does not, but Liberty definitely supports automatic registration for `@Provider` annotated classes.
> 
> Regardless, we do not currently support modifying our provided JSON MessageBodyReader/MessageBodyWriter with a ContextResolver as per my previous update.

Got it @WhiteCat22, I was trying to check if I was able to change this behaviour, but I couldn't, I don't have experience with the OSGI, and don't know how to look into the context before assign the Liberty JsonbProvider. 😅

**Comment by jkoehler22** [comment]
A second customer is requesting this new enhancement.

**Comment by bmhm** [comment]
Just found this from this thread:

> I am going to mark this issue as a request for enhancement. The spec does not _require_ the built-in JSON-B provider to use a context resolver, but it is not a bad idea. I am going to mark this issue as a request for enhancement. The spec does not _require_ the built-in JSON-B provider to use a context resolver, but it is not a bad idea.

Can you please provide a link? I was unable to find a spec.

While I surely believe you, I found some interesting places where ppl use it as granted:
* This is the reference implementation (glassfish):
  https://github.com/jersey/jersey/blob/master/media/json-binding/src/main/java/org/glassfish/jersey/jsonb/JsonBindingFeature.java#L59-L70
* The eclipse foundation seems to take it as granted:
  https://github.com/eclipse-ee4j/jsonb-api/issues/75#issuecomment-441330868
* The last link is Adam Bien's blog, and it is very high ranked on Google:
 http://www.adam-bien.com/roller/abien/entry/private_fields_serialization_with_json

So far I found these app servers to support this feature  (just for reference for those who stumble over this):
* Glassfish  :heavy_check_mark:
* Payara  :heavy_check_mark:
* (Open) Liberty  :heavy_multiplication_x:
* Wildfly 14  :heavy_multiplication_x:

HTH.

**Comment by WhiteCat22** [comment]
> Just found this from this thread:
> 
> > I am going to mark this issue as a request for enhancement. The spec does not _require_ the built-in JSON-B provider to use a context resolver, but it is not a bad idea. I am going to mark this issue as a request for enhancement. The spec does not _require_ the built-in JSON-B provider to use a context resolver, but it is not a bad idea.
> 
> Can you please provide a link? I was unable to find a spec.
> 
> While I surely believe you, I found some interesting places where ppl use it as granted:
> 
> * This is the reference implementation (glassfish):
>   https://github.com/jersey/jersey/blob/master/media/json-binding/src/main/java/org/glassfish/jersey/jsonb/JsonBindingFeature.java#L59-L70
> * The eclipse foundation seems to take it as granted:
>   [eclipse-ee4j/jsonb-api#75 (comment)](https://github.com/eclipse-ee4j/jsonb-api/issues/75#issuecomment-441330868)
> * The last link is Adam Bien's blog, and it is very high ranked on Google:
>   http://www.adam-bien.com/roller/abien/entry/private_fields_serialization_with_json
> 
> So far I found these app servers to support this feature (just for reference for those who stumble over this):
> 
> * Glassfish  ✔️
> * Payara  ✔️
> * (Open) Liberty  ✖️
> * Wildfly 14  ✖️
> 
> HTH.

Here is the Jaxrs 2.1 spec: https://download.oracle.com/otn-pub/jcp/jaxrs-2_1-pfd-spec/jaxrs-2_1-pfd-spec.pdf

Section 4.2.4 details standard entity providers and specifically states that JAXB providers must use application supplied context resolvers:
_The implementation-supplied entity provider(s) for javax.xml.bind.JAXBElement and applicationsupplied JAXB classes MUST use JAXBContext instances provided by application-supplied context resolvers, see Section 4.3. If an application does not supply a JAXBContext for a particular type, the
implementation-supplied entity provider MUST use its own default context instead._
There is nothing about JSON providers.

Section 11.2.6 details the Java API for JSON Processing and doesn't say anything about context resolvers.
Section 11.2.7 details the Java API for JSON Binding and doesn't say anything about context resolvers.

That being said, we believe that this is a nice feature and we are investigating how difficult it would be to add this functionality.

**Comment by bmhm** [comment]
@andymc12 thanks for working on this!

However, I absolutely agree with @WhiteCat22. This behaviour is not specified in the standard. It should therefore be documented and possibly even highlighted.

I think, the primary goal should be interoperability between the application servers. In this regard, not specifying that the Jsonb instance can be supplied via ContextResolver might just be an oversight in the spec, who knows.

My suggestion is: If you do accept @andymc12's PR, please also make sure that this goes into the spec and/or someone alert the wildfly and TomEE teams. Reasonable: l don't want to create more incompatiblity between the application servers.
