### ISSUE TITLE
Server package to store app in extracted form

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#5914]
When we generate a server package if the app is a 'loose' app specified using an xml file the server package converts it to a .war or .ear archive. Instead it should be put in the server package in exploded form. This means that when the server is deployed the app will already be in exploded form for faster startup. 

(We discussed but didn't implement this part).
In addition it might be worth discussing always extracting during server package even if an archive has been deployed. Also should this only happen if extract on startup is set?

**Comment by shighbar** [comment]
I've started looking into this issue a bit. You mentioned above should all archives be extracted when doing a server package - I think one question is if it ever makes sense to not have an application in expanded format? Given that we have extract on startup as an option I think there is a case to be made that there may be scenario where you would not want an app expanded no? Using the extract on startup to drive this is an option but if that was set any apps being packaged other than loose ones should already be extracted.
  Seems to me given that what makes the most sense for the scope here then is to just pull loose applications into the package in an expanded form.

**Comment by canterburymalcolm** [comment]
## Test Coverage:

- ### Parameterized (run against a set of loose configurations)
  - **Loose Configs**
    - `DefaultArchive.war.xml` The original config used by com.ibm.ws.kernel.boot.root.fat to test the majority of package commands, contains a variety of elements
    - `SimpleElements.war.xml` Tests that individual elements all work with both simple and nested targetInArchive attributes
    - `ArchivedElements.war.xml` Tests that every element can be nested under an <archive> element
    - `SkipInvalidEntries.war.xml` Contains several types of invalid elements alongside valid ones to test that the archive is still created with only the valid elements
  - **Tests**
    - `testIncludeUsr()` Packages with `--include=usr` then verifies that entries for the server, the archive, and the expanded folder were all added to the package correctly
    - `testArchiveContentsMatchExpandedFolder()` Packages with `--include=usr` then extracts the created .war and ensures that the content and order of its entries match those in the expanded folder
- ### Regular
  - **Tests** (all run with `DefaultArchive.war.xml`)
    - `testIncludeAll()` Packages with `--include=all` and verifies that the correct entries are created in the .zip
    - `testIncludeRunnable()` Packages with `include=runnable` and and verifies that the correct entries are created in the .jar
    - `testCreateAndStartRunnableJar()` Packages with `include=runnable` then runs the jar in a separate process with `java -jar packageName.jar` to check that it starts up correctly

**Comment by cbridgha** [comment]
There are no external behavior change for users, so no ID/Docs need any changes.

**Comment by chirp1** [comment]
Approving as Chuck indicated that there are no doc changes, and that the feature is a "No WAD Approval" feature.

**Comment by skasund** [comment]
No STE required for L2

**Comment by marikaj123** [comment]
Does the feature require translation?

**Comment by sabolo** [comment]
Please can you complete the feature test summary for this feature.  I have added a child issue and put in the template for you.  I see you have some test information in the comments above however they have no reference to where the tests are (which bucket etc) and also you need to complete part 2 of the feature test summary.  You may wish to copy the contents from the comment above into the feature test summary and expand on it from there.

**Comment by NottyCode** [comment]
@cbridgha I've added the no design approved tab, but in future can you make sure you put in the request well ahead of time? It shouldn't be requested weeks after it is targeted for a release.

**Comment by cbridgha** [comment]
@marikaj123 no message or OD changes - so no translation review needed.
