### ISSUE TITLE
Performance test is required for the serial filter function.

### ISSUE THREAD

**Issue by toshiyamamoto** [OpenLiberty/open-liberty#5933]
In order to make sure that the serial filter function (epic #5924) won't degrade performance of the runtime code significantly, some performance measurements are required.

**Comment by toshiyamamoto** [comment]
The Epic #5924

**Comment by jhanders34** [comment]
This function was changed to depend on the builtin Java support, so there isn't a need any longer to test a liberty specific function for this support.  As such I am closing out this issue.
