### ISSUE TITLE
Missing OpenAPI entries when @Path entries overlap

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/open-liberty#5954]
If you have `@Path` entries that result in a parent-child resource hierarchy (for want of a better term), then OpenAPI does not show all the available resource APIs. For example:
`@ApplicationPath("system")` with resources with paths of `@Path("/")` and `@Path("/properties")` should result in OpenAPI describing resources APIs available at `/system/` and `/system/properties` but it actually only shows `/system/properties`.

**Comment by leochr** [comment]
@arturdzm, could you please look into this?

**Comment by arturdzm** [comment]
Looks like the issue is not with overlapping paths:

eg:
/system/abc/properties and /system/abc works

It seems failing to scan in specific case:
ApplicationPath("anything") and Path("/")

Regardless of the existence of any other paths

**Comment by Azquelt** [comment]
This issue is not present in `mpOpenApi-2.0` but still exists in `mpOpenApi-1.1` and `mpOpenApi-1.0`

**Comment by Emily-Jiang** [comment]
I chatted with @gcharters and he thinks it is best to move up and use the latest version considering how old this issue is. Close this issue for now.
