### ISSUE TITLE
Fix timing issue in testTrustedForwardedWithMultipleServerConfigurations and testTrustedXForwardedWithMultipleServerConfigurations

### ISSUE THREAD

**Issue by ebreijo** [OpenLiberty/open-liberty#5990]
The testTrustedForwardedWithMultipleServerConfigurations and testTrustedXForwardedWithMultipleServerConfigurations could experience a timing issue at the time of reconfiguring the server.xml and driving a request right after reconfiguration. To fix this issue, we need to wait for regex "CWWKT0016I:.EndpointInformation." which ensure that the application is available.

**Comment by ebreijo** [comment]
The testTrustedForwardedWithMultipleServerConfigurations and testTrustedXForwardedWithMultipleServerConfigurations could experience a timing issue at the time of reconfiguring the server.xml and driving a request right after reconfiguration. To fix this issue, we need to wait for regex "CWWKT0016I:.*EndpointInformation.*" which ensure that the application is available.

**Comment by pnicolucci** [comment]
merged to master closing issue.
