### ISSUE TITLE
Resources not being delisted during a transaction suspend

### ISSUE THREAD

**Issue by mswatosh** [OpenLiberty/open-liberty#6013]
From Section 3.2.3 of the JTA Specification:

> The application server is responsible for ensuring that the resources in use by the application are properly delisted from the suspended transaction. A resource delist operation triggers the transaction manager to inform the resource manager to disassociate the transaction from the specified resource object (XAResource.end(TMSUSPEND)).

>When the application’s transaction context is resumed, the application server ensures that the resource in use by the application is again enlisted with the transaction. Enlisting a resource as a result of resuming a transaction triggers the transaction manager to inform the resource manager to re-associate the resource object with the resumed transaction (XAResource.start(TMRESUME)). Refer to Section 3.3.1, “Resource Enlistment.” and Section 3.4.4, “Transaction Association,” for more details on resource enlistment and transaction association.

Currently when a transaction is suspended, resources are not delisted, and the TMSUSPEND flag is not being passed to the resource.

This is blocking Issue #4974

**Comment by jonhawkes** [comment]
The application server was designed so that delisting/enlisting across suspend/resume is never necessary. Can you explain what design change you are proposing that necessitates this behavior now?

**Comment by mswatosh** [comment]
This isn't a design change, it's possible to encounter issues due to resources not being delisted:

https://github.com/OpenLiberty/open-liberty/blob/c3e13171e6b4042c2c43caaca7d4e0334771e8e2/dev/com.ibm.ws.jdbc_fat_v43/test-applications/app43/src/jdbc/fat/v43/web/JDBC43TestServlet.java#L2088

In that example, the same connection is used over the transaction boundary. To fix this correctly from the JCA side, we need to receive the TMSUSPEND/TMRESUME flags so we can properly switch to a new physical connection.
