### ISSUE TITLE
mpOpenTracing v1.3 - Spec/API/TCK

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#6098]
https://bigblue.aha.io/features/LG-47

**Comment by fmhwong** [comment]
Tested MicroProfile OpenTracing 1.3 RC1 with Open Liberty and found `https://github.com/eclipse/microprofile-opentracing/issues/142`.  MicroProfile OpenTracing 1.3 has this fixed.

**Comment by atosak** [comment]
Per Don's comment:
https://github.com/OpenLiberty/open-liberty/issues/6098 is just the git issue we were using for the spec/api/tck work necessary for the microprofile opentracing release to go out (not the Liberty impl of it).  As mpOT-1.3 has been released by MP, we should probably mark 6098 as shipped.

**Comment by fmhwong** [comment]
Closing this as MicroProfile Open Tracing 1.3 was released on Jan 18, 2019
