### ISSUE TITLE
Trace Specification logging level "off" doesn't work

### ISSUE THREAD

**Issue by kbaillie** [OpenLiberty/open-liberty#6123]
When setting the trace specification with the `off` logging level, for example: `<logging traceSpecification="com.ibm.ws.*=all:com.ibm.ws.kernel.*=off"/>` the relevant code does not turn off logging.

**Comment by fwji** [comment]
In TraceComponent.updateTraceSpec(), when we are looping through log levels to enable all log levels and up, we didn't include TraceLevel.off.
