### ISSUE TITLE
Some recent OL builds have the wrong version number 

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/open-liberty#6168]
The guide's continuous tests are testing every OL builds found on ol.io site. Lately lots of them are failing. After some investigation, it's found that some of the OL builds have the wrong version number. 

For example:
http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2019-01-10_2312/ 
has openliberty-all-**18.0.0.4**-cl180420190110-2141.zip. 
Here's a correct one: http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2019-01-10_2056/
has openliberty-all-**19.0.0.1**-cl190120190110-1900.zip.

**Comment by cbridgha** [comment]
@naumanna figured it out..  those were i-fix builds that were moved from the last release, but never turned off the build publishing - I think we have it fixed and shouldn't see more of these after today.

**Comment by cbridgha** [comment]
I'm going to close this one out - let us know if you see this again

**Comment by evelinec** [comment]
Two of yesterday's builds still have this problem: 

1. http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2019-01-14_1607/
2. http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2019-01-14_2358/

**Comment by naumanna** [comment]
Those builds had started before we made the change yesterday to disable publishing to DHE from the 18.0.0.4 ifix builds.  From now on we shouldn't see any more 18.0.0.4 builds publishing in the nightly directory.

**Comment by evelinec** [comment]
These are the builds we found for yesterday, 1/15, two of them are named incorrectly: 

openliberty-all-19.0.0.1-cl190120190115-0300.zip
openliberty-all-19.0.0.1-cl190120190115-0610.zip
openliberty-all-19.0.0.1-cl190120190115-0631.zip
**openliberty-all-18.0.0.4-cl180420190115-1355.zip** in http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2019-01-15_1520/
**openliberty-all-19.0.0.1-20190115-1801.zip** in http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2019-01-15_1943/
openliberty-all-19.0.0.1-cl190120190115-1900.zip

**Comment by yeekangc** [comment]
@cbridgha @naumanna, can you please take another look?

@evelinec can provide further details if necessary.

**Comment by cbridgha** [comment]
openliberty-all-18.0.0.4-cl180420190115-1355.zip was base on Ifix build:  (cl180420190115-1355) where the property is.public.publishing = true.  All other after that are false so should be ok on that definition.    Still looking for the build that doesn't use the "cl" prefix  @naumanna have you seen that?

**Comment by naumanna** [comment]
The 20190115-1801 build was a test build related to the publish to DHE function, so it is valid that the build would have published to DHE.  By default though, test builds will not publish out to that location.

**Comment by wraschke** [comment]
The purpose of that test release build is for testing--the organization doesn't like me testing with official release build definitions. I have to be sure I am not regressing things with my changes (in this case, RTC work item 260265).

If there is a channel or medium where I can go to give testers advance notice that I will be testing with "Liberty Test Definition Release Build - Static" definitions, please point me to those channels or names.

**Comment by evelinec** [comment]
FYI, we didn't get any builds with bad names yesterday. Just checked that there's one "test build" for today: http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2019-01-17_0154/openliberty-all-19.0.0.1-20190116-2145.zip

**Comment by evelinec** [comment]
I haven’t been seeing any more wrong naming build symptoms lately, since my last report on this issue.

**Comment by evelinec** [comment]
I don't see this problem anymore. Closed.
