### ISSUE TITLE
Provide a way to define fallback values for env variables in server.xml

### ISSUE THREAD

**Issue by navidsh** [OpenLiberty/open-liberty#6186]
Currently, Liberty does not support defining fallback values for environment variables in server.xml. So if an env variable is not defined, its fallback value (if defined) be used.

Example server configuration in a container:
```xml
<iiopEndpoint id="defaultIiopEndpoint" host="${env.POD_IP}" iiopPort="${env.IIOPENDPOINT_IIOPPORT}">
  <iiopsOptions iiopsPort="${env.IIOPENDPOINT_IIOPSPORT}" sslRef="defaultSSLConfig" />
</iiopEndpoint>
```

If `env.POD_IP` is not defined in the container,  Liberty can fallback to a value such as `localhost`.

**Comment by scottkurz** [comment]
A couple comments:

1. I'd assume the `default` attribute value can itself be defined using a normal variable substitution.   I don't think that adds any new recursion scenarios to worry about but haven't thought it through much.

2. Maybe this is obvious, but the issue's title is a bit misleading... this isn't a "fallback for an env variable" it's just another way to resolve a config variable substitution.   (It's not like an env var is going to be set, the env var just happens to be the last in precedence today).    It should just be "provide default value for server config variables for server.xml"

**Comment by tevans78** [comment]
Default values will be made available (to MP Config) via a separate interface to the variables themselves. Closing.
