### ISSUE TITLE
Ensure multi-dimensional JSON metrics runs properly with collectd/graphite/grafana

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#6187]
Ensure multi-dimensional JSON metrics runs properly with collectd / graphite / grafana following https://developer.ibm.com/wasdev/docs/collect-metrics-from-liberty-apps-and-display-in-grafana/

**Comment by Erikkre** [comment]
Collectd issue opened to help diagnose the issue: https://github.com/collectd/collectd/issues/3068

**Comment by Erikkre** [comment]
Documentation on proper method of implementation:

https://github.ibm.com/was-lumberjack/lumberjack-docs/tree/master/projects/displayingMpMetricsCollectd-Graphite-Grafana
