### ISSUE TITLE
Ensure multi-dimensional Prometheus metrics runs properly with Prometheus/Grafana

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#6188]
Ensure multi-dimensional Prometheus metrics runs properly with Prometheus/Grafana

**Comment by donbourne** [comment]
Verified that this runs properly.  One change needed in the dashboards in prep for mpMetrics-2.0 is to change names:
`base:` to `base_`
`vendor:` to `vendor_`
`application:` to `application_`

Tags/Labels appear as expected in Prometheus/Grafana query output.
