### ISSUE TITLE
build broken (again)

### ISSUE THREAD

**Issue by kundel** [OpenLiberty/open-liberty#620]
2: Task failed with an exception.
-----------
* Where:
Build file '/data/dev/os/ibm/liberty/dev/com.ibm.websphere.javaee.jsf.2.3/build.gradle' line: 31

* What went wrong:
Execution failed for task ':com.ibm.websphere.javaee.jsf.2.3:copySource'.
> Could not resolve all files for configuration ':com.ibm.websphere.javaee.jsf.2.3:sourceJar'.
   > Could not find com.ibm.ws.org.apache.myfaces.core:myfaces-api:2.3.0-20171016-074050-275.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/ibm/ws/org/apache/myfaces/core/myfaces-api/2.3.0-20171016-074050-275/myfaces-api-2.3.0-20171016-074050-275.pom
         https://repo1.maven.org/maven2/com/ibm/ws/org/apache/myfaces/core/myfaces-api/2.3.0-20171016-074050-275/myfaces-api-2.3.0-20171016-074050-275-sources.jar
         http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/wasliberty-open-liberty/com/ibm/ws/org/apache/myfaces/core/myfaces-api/2.3.0-20171016-074050-275/myfaces-api-2.3.0-20171016-074050-275.pom
         http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/wasliberty-open-liberty/com/ibm/ws/org/apache/myfaces/core/myfaces-api/2.3.0-20171016-074050-275/myfaces-api-2.3.0-20171016-074050-275-sources.jar
     Required by:
         project :com.ibm.websphere.javaee.jsf.2.3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

3: Task failed with an exception.
-----------
* Where:
Build file '/data/dev/os/ibm/liberty/dev/com.ibm.ws.org.apache.myfaces.2.3/build.gradle' line: 27

* What went wrong:
Execution failed for task ':com.ibm.ws.org.apache.myfaces.2.3:copySource'.
> Could not resolve all files for configuration ':com.ibm.ws.org.apache.myfaces.2.3:sourceJar'.
   > Could not find com.ibm.ws.org.apache.myfaces.core:myfaces-impl:2.3.0-20171016-074423-270.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/ibm/ws/org/apache/myfaces/core/myfaces-impl/2.3.0-20171016-074423-270/myfaces-impl-2.3.0-20171016-074423-270.pom
         https://repo1.maven.org/maven2/com/ibm/ws/org/apache/myfaces/core/myfaces-impl/2.3.0-20171016-074423-270/myfaces-impl-2.3.0-20171016-074423-270-sources.jar
         http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/wasliberty-open-liberty/com/ibm/ws/org/apache/myfaces/core/myfaces-impl/2.3.0-20171016-074423-270/myfaces-impl-2.3.0-20171016-074423-270.pom
         http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/wasliberty-open-liberty/com/ibm/ws/org/apache/myfaces/core/myfaces-impl/2.3.0-20171016-074423-270/myfaces-impl-2.3.0-20171016-074423-270-sources.jar
     Required by:
         project :com.ibm.ws.org.apache.myfaces.2.3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

**Comment by takakiyo** [comment]
https://github.com/OpenLiberty/open-liberty/commit/1b39a4cd976a669146d9cf03c9f0f03eb2770dad

http://public.dhe.ibm.com does not have latest snapshot yet.

**Comment by pnicolucci** [comment]
@jsartoris can you see what might be happening here?

**Comment by jsartoris** [comment]
There was an issue in the past few days with files uploaded to the DHE staging server were not being promoted to the public server.  I reached out to the DHE admins and they were able to resolve the issue.  I now see the MyFaces jar files on the public server.  
I am closing this issue as there is no code change required here.
