### ISSUE TITLE
Consider support of resolution of Liberty server.xml config variables by env var using MPConfig-style resolution

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#6209]
## PROBLEM

In the Liberty Boost plugin we intend to generate server config for a Maven/Gradle project, with certain properties like URLs configurable  outside the application, and so represented in server config with variable substitutions.

One hurdle introducing some ugliness is the separate syntax for resolving Java property vs. env variable substitutions.

So for a config variable substitution like:

    <properties.db2.jcc serverName="${jdbc.host}" ... />

it is more typical to expect the substitution to come from a Java property during development (e.g. `mvn boost:run -Djdbc.host=127.0.0.1`).  But, when the app is containerized and deployed to k8s/ICP, this config is more likely to come from an environment variable.

This would require us to generate a separate config flavor for a Dockerized deploy:

    <properties.db2.jcc serverName="${env.JDBC_HOST}" ... />

Of course, one can step back and broaden the focus from generating config to more generally writing and working with config, and I think immediately see the value of being able to use one syntax with the entire precedence chain.

I have no idea of the gotchas, or the answer to the question:  "_why don't we already do something like this?"_

**Note:** Alasdair already weighed in in suggesting this was a worthy issue to discuss further.)

## SOLUTION (a proposal):

Resolve server config var substitutions like `${jdbc.host}` with the existing methods and precedence, **BUT** with a change in case we get to the last step of using a process environment variable to resolve this.

If the variable is still unresolved by the time we check env vars we will follow the lead of MP Config and look at env var:  **JDBC_HOST**  

So like in MP Config, we uppercase alpha chars and convert dot to underscore:  ( '.' => '_').

## REFERENCES:

1) Existing variable substitution precedence:
https://www.ibm.com/support/knowledgecenter/en/SS7K4U_liberty/com.ibm.websphere.wlp.zseries.doc/ae/twlp_setup_vars.html

> If the same variable is specified in multiple places, the precedence is as follows:
> • variables in bootstrap.properties override the process environment variables
> • variables in server.xml, or included XML files, override the variables in bootstrap.properties and process environment variables
> 

2) Original MP Config thread:
https://github.com/eclipse/microprofile-config/issues/264

**Comment by NottyCode** [comment]
Decided that when we get to looking at environment variables when resolving variables we should try the following variables:

1. the original variable as a literal
2. convert non-alphanumeric characters to _
3. convert non-alphanumeric characters to _ and upper case

that would mean jdbc.host in the description would match:

jdbc.host - invalid
jdbc_host - valid but unusual in the environment
JDBC_HOST - valid and usual in the environment

**Comment by tevans78** [comment]
Feature is in progress. Closing
