### ISSUE TITLE
Server for com.ibm.ws.jaxrs.2.1.sse_fat fails to shutdown normally

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#623]
The jaxrs.2.1.sse_fat does not shutdown normally, and waits 30s and eventually emits a `CWWKE1102W` message which indicates that the server failed to quiesce in 30s and will be forcibly shut down.

We should investigate why this FAT server does not shutdown normally, and confirm that this is not caused by product code.

**Comment by andymc12** [comment]
Verified with new test changes.  Talked with Andy G, and he agrees this can be closed.
