### ISSUE TITLE
jwtsso feature should expose MP JWT and AUTH packages as an api

### ISSUE THREAD

**Issue by arunavemulapalli** [OpenLiberty/open-liberty#6241]
Add the following to the jwtsso feature definition.
IBM-API-Package: \
  org.eclipse.microprofile.jwt; type="stable", \
  org.eclipse.microprofile.auth; type="stable"

So application developers can have access to the JsonWebToken

**Comment by ayoho** [comment]
Confirmed that commit f9d5ca9 is included in the master branch, so I'm closing this issue.
