### ISSUE TITLE
JWT SSO cookie emits too many error messages

### ISSUE THREAD

**Issue by chunlongliang-ibm** [OpenLiberty/open-liberty#6248]
If JWT SSO cookie is expired or invalid, Liberty emits error messages. An invalid token is an expected error, we can log (or FFDC it), but we should not emit it as error, which can fill message/console logs quickly.  

We should handle JWT sso cookie error logging like LTPA cookie.

See the following JWT sso cookie error messages:

[ERROR   ] CWWKS5524E: The MicroProfile JWT feature encountered an error while creating a JWT by 
 using the [myMpJwt] configuration and the token included in the request.
 CWWKS6031E: The JSON Web Token (JWT) consumer [myMpJwt] cannot process the token string. 
 CWWKS6025E: The JSON Web Token (JWT) is not valid because its expiration ('exp') claim is either missing or the token expired. 
 The expiration claim is [2019-01-10T14:47:51+0000]. The current time minus the clock skew is [2019-01-15T06:09:23+0000]. 
 The configured clock skew is [300] seconds.

 [ERROR   ] CWWKS5523E: The MicroProfile JWT feature cannot authenticate the request because a valid JWT 
 cannot be created from the token included in the request. CWWKS5524E: The MicroProfile JWT feature encountered 
 an error while creating a JWT by using the [myMpJwt] configuration and the token included in the request. 
 CWWKS6031E: The JSON Web Token (JWT) consumer [myMpJwt] cannot process the token string. 
 CWWKS6025E: The JSON Web Token (JWT) is not valid because its expiration ('exp') claim is either missing or the token expired. 
 The expiration claim is [2019-01-10T14:47:51+0000]. The current time minus the clock skew is [2019-01-15T06:09:23+0000]. 
 The configured clock skew is [300] seconds.

**Comment by brutif** [comment]
As a workaround, these messages can be suppressed by specifying "hidemessage" attribute in trace settings in server.xml.   https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_logging.html

**Comment by brutif** [comment]
recent versions of liberty roll the logs by default (maxFiles and maxFileSize attributes of above topic), so this isn't going to overflow the file system.

**Comment by brutif** [comment]
fixing on #6261

**Comment by ayoho** [comment]
@brutif @c00crane Can this be closed since the associated PR has been merged?
