### ISSUE TITLE
jsonp-1.1 api dependencies incorrect

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/open-liberty#6255]
Note, this issue may also apply to jsonp-1.0.

I should be able to depend on the jsonp-1.1 feature like this:

```
        <dependency>
            <groupId>io.openliberty.features</groupId>
            <artifactId>jsonp-1.1</artifactId>
            <type>esa</type>
            <scope>provided</scope>
        </dependency>
```

And have it pull in the javax.json API automatically for me.  Unfortunately, the jsonp-1.1 feature depends on version 1.0 of the API artifact which is from 2013 and does not contain the correct level of the jsonp APIs (e.g. I can't use `javax.json.stream.JsonCollectors` because that came in a later version.).

To work around this issue, I have to add this dependency.

```
        <dependency>
            <groupId>javax.json</groupId>
            <artifactId>javax.json-api</artifactId>
            <version>1.1.4</version>
            <scope>provided</scope>
        </dependency>
```

**Comment by ericglau** [comment]
jsonp-1.0 feature depends on `javax.json:javax.json-api:jar:1.0` as seen in the following dependency tree:
```
[INFO] \- io.openliberty.features:jsonp-1.0:esa:19.0.0.1:provided
[INFO]    \- javax.json:javax.json-api:jar:1.0:provided
```

jsonp-1.1 feature depends on `javax.json:javax.json-api:jar:1.1.2` as seen in the following dependency tree:
```
[INFO] \- io.openliberty.features:jsonp-1.1:esa:19.0.0.1:provided
[INFO]    \- io.openliberty.features:com.ibm.websphere.appserver.jsonpInternal-1.1:esa:19.0.0.1:provided
[INFO]       \- io.openliberty.features:com.ibm.websphere.appserver.jsonpImpl-1.1.1:esa:19.0.0.1:provided
[INFO]          +- io.openliberty.features:com.ibm.websphere.appserver.javaeeCompatible-8.0:esa:19.0.0.1:provided
[INFO]          \- javax.json:javax.json-api:jar:1.1.2:provided
```

**Comment by ericglau** [comment]
jsonp-1.1 should depend on json-api 1.1.3 to match #5629 which is the same version as what is currently [here](https://github.com/aguibert/open-liberty/blob/master/dev/com.ibm.websphere.javaee.jsonp.1.1/bnd.bnd)
