### ISSUE TITLE
Upgrade of Liberty buildpack from liberty-for-java_v3_26-20181023-1545 to liberty-for-java_v3_27-20181130-1702 breaks application authentication

### ISSUE THREAD

**Issue by eugenerr** [OpenLiberty/open-liberty#6280]
From discussion on was-liberty channel its Liberty 18.0.0.3 in V3.26 and 18.0.0.4 in v3.27.

We use openid as authentication mechanism, openid client is configured.
Application logic examines WSSubject and creates instance of w3User object which is declared as

@xmlrootelement(name = "W3User")
@xmlaccessortype(XmlAccessType.FIELD)
@xmltype(propOrder = { "w3Id", "fullName", "blueGroups", "emailAddresses", "credentials",
"userEnvironment", "state", "effectiveDate" })
@jsonignoreproperties(value = { "isAuthenticated" })
public class W3User implements Serializable

The instance is then cached in javax.servlet.http.HttpSession

`session.setAttribute( W3User.sessionKey, user );`

Client sends request and its handler looks for cached W3User in HttpSession

`W3User user = (W3User)session.getAttribute( W3User.sessionKey );`

If found handler sends response to client as

`javax.ws.rs.core.Response jaxRsResponse = Response.status( Response.Status.OK ).entity( user )
.type( MediaType.APPLICATION_JSON ).build();`

`return jaxRsResponse;`

This is Cloud Foundry application deployed in IBM Cloud in more than one instances. We use table in db2 to store shared session. http session is configured as

`<httpSessionDatabase id="session_db" dataSourceRef="session_ds" />`
`<httpSession storageRef="session_db" cookieName="IBM-MY-NOTIFICATIONS-SESSIONID" securityIntegrationEnabled="false" />`

when using liberty-for-java_v3_26-20181023-1545 request returns response as expected, i.e. client gets user json but when using
liberty-for-java_v3_27-20181130-1702 response returns 500

`Error 500: org.jboss.weld.exceptions.IllegalStateException: WELD-000227: Bean identifier index inconsistency detected - the distributed container probably does not work with identical applications
Expected hash: -1893558545
Current index: BeanIdentifierIndex [hash=-102003167, indexed=2]
0: WELD%ManagedBean%EAR_MyN_Core|EAR_MyN_Core#com.ibm.ws.jsf.2.2_1.additionalClasses|org.apache.myfaces.cdi.view.ViewScopeBeanHolder|org.apache.myfaces.cdi.view.ViewScopeBeanHolder#java.lang.Class#-558632038|false
1: WELD%ManagedBean%EAR_MyN_Core|EAR_MyN_Core#com.ibm.ws.jsf.2.2_1.additionalClasses|org.apache.myfaces.flow.cdi.FlowScopeBeanHolder|org.apache.myfaces.flow.cdi.FlowScopeBeanHolder[@javax.enterprise.context.SessionScoped()]{org.apache.myfaces.flow.cdi.FlowScopeBeanHolder.applicationContextBean[@javax.inject.Inject()];org.apache.myfaces.flow.cdi.FlowScopeBeanHolder.destroyBeansOnPreDestroy[@javax.annotation.PreDestroy()]();org.apache.myfaces.flow.cdi.FlowScopeBeanHolder.init[@javax.annotation.PostConstruct()]();}|false` 

Given that request handler defined as 
` @Path("authenticated")
  @Produces("application/json, text/plain")
  @GET
  public Response getAuthenticatedUser()
  {
       ....
  }`
is not called I think that failure occurs during injection

`@Context
    private HttpServletRequest servletRequest;`

**Comment by benjamin-confino** [comment]
Already on it Emily :) 

As I said on Slack @eugenerr the first step for debugging WELD-000227 is to get the CDI mustgather trace from all the servers that are capable of failing over to each other. You need to stick

`    <logging traceSpecification="*=info:JCDI=all:com.ibm.ws.webbeans*=all:org.apache.webbeans*=all:org.jboss.weld*=all:com.ibm.ws.cdi*=all"></logging>` into your server.xml - or at least, that's how I do it. I don't know if it works differently from buildpacks. 

Once you have that each trace.log should have a `WELD-000145` message in it, which will include an BeanIdentifierIndex like the one in the error message. To resolve this issue you need to find any diffs in those indexes and make them identical.

**Comment by kevin-ortega** [comment]
@eugenerr 
We document how to set tracing on the liberty server running on IBM Cloud here:
https://console.bluemix.net/docs/runtimes/liberty/loggingAndTracing.html#changing-trace-configuration-via-ssh

I suggest using the ssh method and log into the app and manually change update the server.xml with the requested trace spec.   You will need to wait 1 minute for the trace spec change to take effect.

**Comment by eugenerr** [comment]
I can confirm that when application is deployed in a single instance it works as designed and when it is deployed in two instances it fails.

Attaching trace files from both instances.
[inst0trace.txt](https://github.com/OpenLiberty/open-liberty/files/2797650/inst0trace.txt)
[inst1trace.txt](https://github.com/OpenLiberty/open-liberty/files/2797652/inst1trace.txt)

@benjamin-confino you wrote "To resolve this issue you need to find any diffs in those indexes and make them identical".
In inst 0 BeanIdentifierIndex [hash=-52127035, indexed=2] 
In inst 1 BeanIdentifierIndex [hash=-307914119, indexed=2]
Unfortunately trace doesn't provide recognizable identification for a bean in question. I'm assuming that this is a bean that is stored in shared session. Attaching its definition for review as well

[W3User.txt](https://github.com/OpenLiberty/open-liberty/files/2797694/W3User.txt)

How these hashes are built?
I was assuming that hash would be a derivative of serialVersionUID. Or algorithm takes into account bean's properties values?
Those don't mutate until after injecting
    @Context
    private HttpServletRequest servletRequest;

The sequence is: filter looks at WSSubject and creates bean, then caches it in session. Client sends request and handler injects context. Then specific @GET gets called which gets bean reference from session and then some properties of bean instance get modified.
I'm thinking maybe this modification causes a problem. On the other hand this issue is new and injection started failing only in v27.
In addition I'm reading this article https://issues.jboss.org/browse/WELD-1887

**Comment by benjamin-confino** [comment]
I tracked down the issue to https://github.com/OpenLiberty/open-liberty/pull/5553

It appears that addAnnotatedType(class, id) ends up in the bean identifier index. However the javadoc says `This method allows multiple annotated types, based on the same underlying type, to be defined.` which suggests you are supposed to have a unique value for id. However the bean identifier index must be the same across multiple applications. 

This might be a bug in weld, but one we could easily workaround. I will discuss this with the rest of the team during our next scrum.

**Comment by kevin-ortega** [comment]
@benjamin-confino Is the fix #5553 in 19.0.0.1?

**Comment by benjamin-confino** [comment]
Alas no, the deadline closed a while back.

**Comment by benjamin-confino** [comment]
This should be closed. #6327 was delivered a while ago.
