### ISSUE TITLE
Clear up confusing about CF push of Spring Boot executable WAR/JAR

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/open-liberty#6355]
When pushing a stand-alone application in an executable jar/war the liberty build pack will cause the archive to be launched with "java -jar". When the archive is a spring boot app we would ideally default (or provide an easy way) to have that archive be deployed to a websphere liberty server using the springBoot-n. feature. The springBoot feature to use can likely be determined by analyzing the archive. Other features can be specified via the standard JBP_CONFIG_LIBERTY mechanism.

**Comment by sebratton** [comment]
When pushing a stand-alone application in an executable jar/war the liberty build pack will cause the archive to be launched with "java -jar". When the archive is a spring boot app we would ideally default (or provide an easy way) to have that archive be deployed to a websphere liberty server using the springBoot-n. feature. The springBoot feature to use can likely be determined by analyzing the archive. Other features can be specified via the standard JBP_CONFIG_LIBERTY mechanism.

**Comment by jgawor** [comment]
Would like to iron out some details before we decide to go with this or not:
  * How do we determine the app is a spring boot app? (Java buildpack has some code for it I believe)
  * What if the spring boot app has Liberty runtime packaged? Do we run with it or the buildpack's version?
  * What if the spring boot app has non-Liberty runtime? That's when I assume we would use this. What are the exact steps to configure the Liberty runtime with spring boot app
  * What if the spring boot app has no runtime? Treat it same as above?
  * Are there any known issues with running spring boot app on Liberty vs. Tomcat? That is, do we need a mechanism to disable this feature in case of a problem or do we make the user to explicitly enable it instead?

**Comment by sebratton** [comment]
> Would like to iron out some details before we decide to go with this or not:
> 
> * How do we determine the app is a spring boot app? (Java buildpack has some code for it I believe)
> * What if the spring boot app has Liberty runtime packaged? Do we run with it or the buildpack's version?
> * What if the spring boot app has non-Liberty runtime? That's when I assume we would use this. What are the exact steps to configure the Liberty runtime with spring boot app
> * What if the spring boot app has no runtime? Treat it same as above?
> * Are there any known issues with running spring boot app on Liberty vs. Tomcat? That is, do we need a mechanism to disable this feature in case of a problem or do we make the user to explicitly enable it instead?

The liberty dev and liberty build pack teams had a brief meeting to discuss this on Feb 12th attended by: Heather L Duschl/Durham/IBM, Jaroslaw Gawor/Durham/IBM, Kevin Ortega/Raleigh/IBM, Thomas Watson/Austin/IBM@IBMUS, Samuel E Bratton/Austin/IBM

An Aha! issue was opened by build pack to get this work sized and prioritized:
https://bigblue.aha.io/features/BPACKS-62

The questions above were discussed:
* How do we determine the app is a spring boot app? (Java buildpack has some code for it I believe)

Probably some refinement of checking for executable war/jar + manifest.mf has 
Main-Class: org.springframework.boot.loader.{WarLauncher|Jarlauncher}
and a Start-Class is specified

* What if the spring boot app has Liberty runtime packaged? Do we run with it or the buildpack's version?

Boost jars are like this. They are not spring-specific, probably will not meet the above checks and should be executed
as plain executable archives. There is a non-supported variant, liberty-boot (released as an alpha) which we don't expect to see and will not do any special processing for.

* What if the spring boot app has non-Liberty runtime? That's when I assume we would use this. What are the exact steps to configure the 

Liberty osgi squad may need to provide more details to buildpack team. It might be possible to determine the version of spring and detect the correct liberty spring-boot feature (by inspecting an embedded pom). If this proves unreliable then we might need to default to springBoot-2.1 and possibly some default set of features. Overrides can be applied by the deployer using existing liberty buildpack techniques.

* What if the spring boot app has no runtime? Treat it same as above?

 Treat as above.
 
* Are there any known issues with running spring boot app on Liberty vs. Tomcat? That is, do we need a mechanism to disable this feature in case of a problem or do we make the user to explicitly enable it instead?

No issues come to mind at time of meeting. Support continues. 
It's undecided weather this new behavior will be default or enabled with a switch. At the time of the meeting the consensus was to make the behavior enabled by a switch and not default. In any event there must be a way to turn off the new behavior.
This still need to be hashed out as the feature is socialized via WAD.

**Comment by sebratton** [comment]
See
https://github.ibm.com/was-buildpacks/bluemix-runtimes-issues/issues/605
https://bigblue.aha.io/features/BPACKS-62
