### ISSUE TITLE
Move Remaining Database logging Tests in the Transaction Cloud Test Suite from Commercial Liberty to Open Liberty

### ISSUE THREAD

**Issue by neilgsyoung** [OpenLiberty/open-liberty#6361]
Move the remaining tests that use Database Transaction logging in the com.ibm.ws.transaction.cloud_fat suite in Commercial Liberty to Open Liberty.

The Database Tests in DualServerDynamicTest and DualServerDynamicTest need to be migrated from Commercial Liberty to Open Liberty.

**Comment by tevans78** [comment]
Complete
