### ISSUE TITLE
try to boost ulimit -n by default?

### ISSUE THREAD

**Issue by covener** [OpenLiberty/open-liberty#6379]
Many platforms set the soft limit for file descriptors / open files to a relatively low value with a much  higher hard limit (unprivileged processes can raise their soft limits up to the hard limit)

Some sample combos spot-checking interactive shells on different systems:

OS | Soft Limit | Hard Limit
----|----|----
Ubuntu 18.04 |  1024 | 1048576
RHEL 7 | 1024 | 4096
Solaris 11 | 256|  65535
AIX 7 |  2000 | unlimited

1024 is a little low for a multi-threaded server, especially one that holds so many files open after startup before counting inbound or outbound TCP connections. On my workstation, an idle server already has a couple hundred open file descriptors.  That leaves 600 to be shared amongst frontend HTTP connections (even those in keepalive not using a thread), outbound HTTP connections (even those in connection pools), LDAP/Database/??? connections.

Would it be reasonable to try to boost the soft limit up to 4096 in bin/server:
 - if we see it lower
 - ignoring failures

**Comment by NottyCode** [comment]
Update shell script to set the soft file limit to 4096 by default. Allow this number to be set via an env var:

WLP_FILE_SOFT_LIMIT

**Comment by jhanders34** [comment]
PR #7687 is causing a regression on a system where the ulimit is configured different than the low defaults mentioned above.  I thought we discussed on the design issues call that we would only set the 4096 default if the current ulimit setting was less than that, and leave it alone if the ulimit was already configured in a smart fashion by a customer.  As such I believe that the aforementioned PR associated with this issue has caused a breaking change that affect zero migration.

**Comment by garypicher** [comment]
When this gets re-done, I think we should consider eliminating the WLP_FILE_SOFT_LIMIT variable.  There's already a way to set this in the OS environment - the purpose of this support is just to raise the value to 4096 if it's set below that.  Making that configurable seems odd...  if the customer was aware that their setting is low and wanted to raise it, they already have a way to do that.

**Comment by hlhoots** [comment]
@jhanders34 I didn't catch that from the design discussion, and was just going off of the outcome from the mtg in the comment above that said 'default it to 4096'.  I dont think it should be to hard to add some logic that checks to see if its set higher than 4096 and thus make no changes.

@garypicher I think the reason for the env variable was so that it could be overridden and/or set for Docker containers.  We can discuss more on your thoughts on removal.

**Comment by NottyCode** [comment]
Most recent versions of Java on Hotspot, and OpenJ9 set the soft limit to match the hard limit when the JVM starts as a result there is nothing we can do. Perhaps the tuning doc could advocate setting the hard limit, but that is all.
