### ISSUE TITLE
WLP 18.0.0.4 fails to rotate trace log on Windows 

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/open-liberty#6381]
When Liberty 18.0.0.4 on Windows is configured for log rotation, the trace.log cannot be deleted and the historical trace_xxx.log and trace.log files are increasing in size.

Example server.xml:
\<?xml version="1.0" encoding="UTF-8"?>
\<server description="new server">
\
\<featureManager>
\<feature>webProfile-8.0</feature>
\<feature>distributedMap-1.0</feature>
\</featureManager>
\
\<httpEndpoint id="defaultHttpEndpoint"
httpPort="9080"
httpsPort="9443" />
\
\<applicationManager autoExpand="true"/>
\<logging traceSpecification="*=finer" maxFiles="5" maxFileSize="5" />
\</server>

After running for some minutes, we have these trace files:

15.01.2019 12:57 8.202 console.log
15.01.2019 12:56 \<DIR> ffdc
15.01.2019 12:57 8.184 messages.log
15.01.2019 12:57 \<DIR> state
15.01.2019 12:57 376.864.301 trace.log
15.01.2019 12:57 360.062.683 trace_19.01.15_12.57.34.0.log
15.01.2019 12:57 365.305.412 trace_19.01.15_12.57.34.1.log
15.01.2019 12:57 370.547.770 trace_19.01.15_12.57.37.0.log
15.01.2019 12:57 375.790.457 trace_19.01.15_12.57.43.0.log

All trace log files begin at the same time, they are only appended instead of rotated, because the original trace.log cannot be deleted -
which is also shown in console.log:
TRAS0038E: The system could not delete file D:\wlp18004\usr\servers\server1\logs\trace.log
This problem did not happen with earlier WLP 18.0.0.x releases.

**Comment by kgibm** [comment]
I'm sorry, this was my fault, as part of refactoring for #4389. The fix is to move the log file creation within the right security context. A workaround is to set `maxFileSize="0"` to disable rotation although then sufficient disk space must be provisioned.
