### ISSUE TITLE
BETA BLOG API-22 - Fault Tolerance 2.0

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#6448]
a. Which Liberty feature does it relate to?

   i. Human-readable name: MicroProfile Fault Tolerance 2.0

   ii. Feature name: mpFaultTolerance-2.0

   iii. Is this a new feature or is it an update to an existing feature for this release? New feature

   iv. Provide the qualified name of all changed feature deliveries to this release? 
    - com.ibm.websphere.appserver.mpFaultTolerance-2.0.esa
    - com.ibm.websphere.appserver.org.eclipse.microprofile.faulttolerance-2.0.esa
    - com.ibm.websphere.appserver.mpFaultTolerance2.0-cdi2.0

b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc
 - application developers

c. Write a sentence or two that introduces it to someone new to the general technology/concept.

MicroProfile Fault Tolerance allows developers to easily apply strategies for mitigating failure to their code. It provides annotations which developers can add to methods to use bulkhead, circuit breaker, retry, timeout and fallback strategies. In addition, it provides an annotation which causes a method to  be run asynchronously.

d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)

Version 2.0 adds several new features:
 - Asynchronous methods can now return a `CompletionStage`, making it easier to compose asynchronous operations and use fault tolerance with existing asynchronous technologies.
 - The user can now configure the priority of the CDI interceptors added by Fault Tolerance, giving them control over how Fault Tolerance interacts with any other interceptors which have been applied.
 
e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.

  1. Enable Fault Tolerance and CDI in the server.xml, along with any other features you're using.
  ```
  <featureManager>
    <feature>mpFaultTolerance-2.0</feature>
    <feature>cdi-2.0</feature>
    <feature>jaxrs-2.1</feature>
  </featureManager>
```
  2. Add any of the Fault Tolerance annotations to a business method of a CDI bean.
  ```
  @Retry(5)
  public User lookupUserFromRegistry(String name) {
    return registry.getUser(name);
  }
```
  3. When that method is called as a a CDI business method, the fault tolerance strategy will be used. In this example, if `lookupUserFromRegistry()` would throw an exception, it will instead be retried up to five times.

f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

 - Specification release: https://github.com/eclipse/microprofile-fault-tolerance/releases/tag/2.0

g. Attach any images to this work item as .png files.

**Comment by lauracowen** [comment]
Also mention the behaviour changes from here: https://github.com/OpenLiberty/docs/issues/136#issuecomment-471654257

**Comment by marikaj123** [comment]
Blog post going into the feature GAed for release 19003. 
Epic:  https://github.com/OpenLiberty/open-liberty/issues/4080

**Comment by lauracowen** [comment]
Thanks
