### ISSUE TITLE
typo in javax.xml.bind:jaxb-api:2.2.12.b140109_1041;EXACT maven dependency

### ISSUE THREAD

**Issue by gdelvallez** [OpenLiberty/open-liberty#6461]
Hi, 
I am trying to move to liberty 19.0.0.1, using com.ibm.websphere.appserver.features:baseBundle:19.0.0.1 maven dependency in eclipse. Eclipse show me an error because jaxb-api-2.2.12.b140109_1041;EXACT.jar in nor found in repository.
Looking into internet, I found that https://github.com/OpenLiberty/open-liberty/pull/4877/files#diff-8a85fcc6392b0a9792dad153100abb47 is referencing an update 
adding .   mavenCoordinates="javax.xml.bind:jaxb-api:2.2.12.b140109_1041;EXACT",

but maven repository does not include javax.xml.bind:jaxb-api:2.2.12.b140109_1041;EXACT
but javax.xml.bind:jaxb-api:2.2.12.b140109_1041

May be it is a typo.
I hope is could be quickly fixed.
Regards.

**Comment by aguibert** [comment]
hi @gdelvallez, thanks for raising this issue! It is indeed a typo, we'll get it fixed in 19.0.0.2 which will be available in a few weeks.
