### ISSUE TITLE
RemoteException thrown when sending objects over IIOP on Java 11

### ISSUE THREAD

**Issue by chackoj** [OpenLiberty/open-liberty#6473]
When using Liberty with Java 11, if there is a serialization-compatible change between the classes on the server and those on the client, objects of that class may not be transmitted correctly, and a `java.rmi.RemoteException` may be received instead.

**Comment by marlowa** [comment]
According to https://openjdk.java.net/jeps/320 RMI-IIOP is now optional in Java 11 as part of getting rid of CORBA.

**Comment by chackoj** [comment]
Thank you, @marlowa.
The removal of RMI-IIOP from Java 11 changed the codepath the tests were executing, and exercised function that has yet to be implemented in Yoko. Therefore this issue is not a regression from behaviour in a previous release as I originally indicated.
