### ISSUE TITLE
BETA BLOG 19003 and GA 19004 - MicroProfile Reactive Streams Operators 1.0

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#6523]
https://github.ibm.com/was-liberty/WS-CD-Open/wiki/Creating-Stories-and-Features#moving-a-feature-into-a-beta

Moving a feature into a beta

If your feature has function that you want to be available in a beta, you need to provide text for a paragraph in the beta announcement blog post.

    For Epics containing beta content, apply the label 'beta:1900#' where #=1,2,3,... to the epic.
    Create a child task of the epic with a description that starts with "BETA BLOG 1900#", where #=1,2,3, ...
    Provide the appropriate text (see questionnaire) in the child task.
    When the text has been provided, assign the task to Laura Cowen and the Epic feature owner.

https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/Wde4b45b770c2_47cd_9d6d_7061f359add9/page/Blog%20Questionnairs

**Comment by hutchig** [comment]
a. Which Liberty feature does it relate to?

i. Human-readable name: MicroProfile Reactive Stream Operators 1.0

ii. Feature name: mpReactiveStreams-1.0

iii. Is this a new feature or is it an update to an existing feature for this release? 
New feature

iv. Provide the qualified name of all changed feature deliveries to this release?
Private:
com.ibm.websphere.appserver.org.eclipse.microprofile.reactive.streams.operators-1.0.feature
com.ibm.websphere.appserver.org.reactivestreams-1.0.feature
Public:
com.ibm.websphere.appserver.mpReactiveStreams-1.0.feature ("mpReactiveStreams-1.0
")
This will expose the following packages:
IBM-API-Package: \
  org.eclipse.microprofile.reactive.streams.operators; type="stable", \
  org.eclipse.microprofile.reactive.streams.operators.spi; type="stable", \
  org.eclipse.microprofile.reactive.streams.operators.core; type="stable", \
  org.reactivestreams; type="stable";

b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc

    * application developers

c. Write a sentence or two that introduces it to someone new to the general technology/concept.

Reactive streams provide a method to implement publish subscribe ('pub-sub') pipelines that handle flow-control and error handling in an elegant manner. The MicroProfile Reactive Streams Operators specification bundles a reactive streams API together with a set of standard operators that can be applied to streams. 

d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)

Reactive streams provide for a powerful abstraction that can handle, perhaps infinite, 
streams of events in a manner that prevents downstream clients being overwhelmed. Provided operators can filter, combine or map events, handle errors and so on all without breaking the stream processing pipeline. Additionally, streams are generic over application domain types and allow developers to compose multiple technologies using a common succinct approach enabling them to concentrate more on application domain problems.

e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.

1. This feature can be enabled with a server xml snippet of:
```xml

<featureManager>
        <feature>mpReactiveStreams-1.0</feature>
</featureManager>

```
2. It is then possible to use code like the below in your Liberty application.

```java
import org.eclipse.microprofile.reactive.streams.operators.ReactiveStreams;
...
assertEquals(
                ReactiveStreams.of("1", "2", "3")
                        .collect(Collectors.joining(", ")).run().toCompletableFuture().get(),
                "1, 2, 3");
```


f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

    * Specification release: https://github.com/eclipse/microprofile-reactive-streams-operators/releases/download/1.0/microprofile-reactive-streams-operators-spec-1.0.pdf

g. Attach any images to this work item as .png files.

**Comment by hutchig** [comment]
Laura @lauracowen  please could you review the above. 
I modelled it on https://github.com/OpenLiberty/open-liberty/issues/6448
I expect there will be other texts to come on Reactive Streams feature
so this is just trying to fullfil:
```

```


https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/Wde4b45b770c2_47cd_9d6d_7061f359add9/page/Blog%20Questionnairs

**Comment by lauracowen** [comment]
Could you add to the intro a real-life example of why reactive streams are awesome? What do they let you, as developer, do that you can't do with non-reactive approaches to development? Why should a developer bother to learn the concepts and how to develop in a reactive way?

Otherwise looks okay, thanks.

**Comment by hutchig** [comment]
# Could you add to the intro a real-life example of why reactive streams are awesome? 

The intro could become: 
```
Reactive streams provide a method to implement publish subscribe ('pub-sub') pipelines that handle flow-control and error handling in an elegant manner. The MicroProfile Reactive Streams Operators specification bundles a reactive streams API together with a set of standard operators that can be applied to streams. For example, you could write a reactive streams Publisher that sent events capturing sensor data from an 'internet of things' (IOT) device such as temperature or pressure and then subscribe to these events in a way that enabled the client to control how frequently the events were being sent without have to 'block' on the event processing to slow things down. Additionally, it would be easy to apply reactive streams operators such as filters or mappings to the events that were received by the subscribing client.
```

# What do they let you, as developer, do that you can't do with non-reactive approaches to development? 

Non reactive approaches often control the flow of data inadvertantly by simply getting slower at processing it, thus blocking the thread of control from being used to send further work while doing so. If we attempt to improve on this approach, by using asynchronous techniques to free up the thread, it can often lead to a problem where the rate of data arriving at a component exceeds the rate that it can be processed. Buffering can help to smooth arrival rates but, long term, it will not help throttle the incoming work to an rate that is sustainable. The reactive approach uses a system of ticketing whereby the sender reacts to requests for data. This ticketing approach creates 'back pressure' between the publisher and subscriber which limits the amount of data that can be sent to levels that can be handled successfully and contributes towards protecting the system from overload.

# Why should a developer bother to learn the concepts and how to develop in a reactive way?

**Comment by hutchig** [comment]
I have raised https://github.ibm.com/dev-engage/blog-posts/issues/73 to cover a draft article like 
https://openliberty.io/blog/2019/04/10/jaxrs-reactive-extensions.html

**Comment by lauracowen** [comment]
Thanks, that's great. Let me know when you've done the standalone blog post and I'll review it. When it's published I'll also update this release blog post to link to it.
