### ISSUE TITLE
[Windows 10] Console log is empty after server start

### ISSUE THREAD

**Issue by kristip17** [OpenLiberty/open-liberty#6525]
On my Windows 10 machine, the console.log (or FAT test console log) is being created, but not populated with any messages.

This causes FAT tests to fail because it cannot find the `CWWKF0011I` message in the console log. If I add `com.ibm.ws.logging.console.log.level=OFF` then it works around it for FAT tests.

This seems to be a machine wide problem though. If I just do a simple "server start server1", a console.log appears, but it is empty. Even outside of my open-liberty workspace.

I found an older wlp (early December) that had server1 with a correct/populated console.log (from when I last used it) and started that server -- but now it creates an empty console.log.

This definitely started happening on Monday (2/11). It may have been occurring on Friday as I was having some FAT test problems, but I was working on a messy change so I'm not sure if it was the same problem or not. I did get a big Windows update pushed Monday morning.

@brideck  also is seeing this (in CL, I think) on Windows.

I have tried running as administrator, but see the same problems.

@aguibert was troubleshooting with me in a was liberty slack thread.

Example of the failure you see running a FAT test -- the key being the "Message was not found in" and the then the name of the console log supplied by the test.

```
[02/13/2019 15:33:47:982 CST] 001 LibertyServer                  validateServerStarted          S Server failed to start.   Command used to start server was: C:/libertygit2/open-liberty/dev/build.image/wlp/bin/server
componenttest.exception.TopologyException: Start Server error: The server did not show kernel had started. The server did not show kernel had started. The standard error was: .
 Standard out was: Starting server com.ibm.ws.security.wim.adapter.ldap.fat.search.paging.
Server com.ibm.ws.security.wim.adapter.ldap.fat.search.paging started.
.
 Return code was: 0.
 Message was not found in C:/libertygit2/open-liberty/dev/build.image/wlp/usr/servers/com.ibm.ws.security.wim.adapter.ldap.fat.search.paging/logs/com.ibm.ws.security.wim.adapter.ldap.fat.SearchPagingTest.log
    at componenttest.topology.impl.LibertyServer.validateServerStarted(LibertyServer.java:2102)
    at componenttest.topology.impl.LibertyServer.startServerWithArgs(LibertyServer.java:1418)
    at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:1041)
    at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:1023)
    at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:1010)
    at componenttest.topology.impl.LibertyServer.startServer(LibertyServer.java:873)
    at com.ibm.ws.security.wim.adapter.ldap.fat.SearchPagingTest.setupLibertyServer(SearchPagingTest.java:118)
    at com.ibm.ws.security.wim.adapter.ldap.fat.SearchPagingTest.setupClass(SearchPagingTest.java:73)
```

**Comment by kristip17** [comment]
Running 

```java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 8.0.5.20 - pwa6480sr5fp20-20180802_01(SR5 FP20))
IBM J9 VM (build 2.9, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20180731_393394 (JIT enabled, AOT enabled)
OpenJ9   - bd23af8
OMR      - ca1411c
IBM      - 98805ca)
JCL - 20180719_01 based on Oracle jdk8u181-b12```

 @loriadi  is also seeing this problem.

**Comment by kristip17** [comment]
Currently, we suspect that this is related to a recent windows update -- Feature update to Windows 10, version 1809.

**Comment by brenthdaniel** [comment]
It looks like something is broken in windows patch 1809 with output redirection from the javaw command. A workaround is to use java rather than javaw (around line 291 of server.bat, change `!JAVA_CMD_QUOTED!w` to `!JAVA_CMD_QUOTED!` )

**Comment by brenthdaniel** [comment]
https://github.com/Microsoft/console/issues/271  seems to be the culprit. The workaround listed there (running `start` with `/min`) seems to work.

**Comment by hlhoots** [comment]
I believe this is resolved.  Closing for now.  Please reopen if issues still exist.
