### ISSUE TITLE
Can't use mpRestClient from EJB

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#6534]
@jwalcorn commented on [Thu Feb 14 2019](https://github.com/OpenLiberty/openliberty.io/issues/994)

I've been using mpRestClient-1.1 from my JAX-RS classes, packaged in a war, without any problems.  In fact, mpRestClient is my favorite MicroProfile technology.  But now I'm trying to use it from an EJB (specifically, an MDB that is pulling messages from MQ), and it's failing to inject the RestClient.  It's saying it can't determine the base URL (even though I see it, when I log the results of System.getProperty("com.ibm.hybrid.cloud.sample.stocktrader.messaging.client.NotificationClient/mp-rest/url") in a static initializer block I just added for debugging.  I'm setting that via a jvm.options entry (just like I do from my JAX-RS classes, which works).  I gathered a com.ibm.ws.microprofile.rest.client.cdi=all trace.  It, and my server.xml, jvm.options, and my ear file (containing the EJB jar) are zipped up and attached here.  Let me know if anything else is needed.  Thanks!
[mpRestClientFromEJB.zip](https://github.com/OpenLiberty/openliberty.io/files/2867216/mpRestClientFromEJB.zip)

---

@jwalcorn commented on [Thu Feb 14 2019](https://github.com/OpenLiberty/openliberty.io/issues/994#issuecomment-463859409)

I forgot to mention, this is all in GitHub, at https://github.com/IBMStockTrader/messaging.  The built image is in DockerHub, at https://hub.docker.com/r/ibmstocktrader/messaging.  I can provide access to the Kubernetes environment hosting that Docker image if needed.  oh, and I'm running on Liberty 19.0.0.1

**Comment by aguibert** [comment]
CC @andymc12

**Comment by jwalcorn** [comment]
Sorry - guess I opened that in the wrong place.  Thanks for moving.  I had also attached the requested trace to the original issue.

**Comment by aguibert** [comment]
no worries, everything from the initial issue (including attached trace) got carried over automatically

**Comment by jwalcorn** [comment]
My bad - forgot to include `mpConfig-1.3` in my feature list.  Just added it, per suggestion from @andymc12, and all started working perfectly.  Thanks.  You can close this (I don't have the Close button, I guess because it was cloned here from another repo by someone else).

**Comment by jwalcorn** [comment]
btw, I see this in my log.  but it doesn't seem to keep anything from working:
`[WARNING ] Could not load provider, , configured for Rest Client interface, com.ibm.hybrid.cloud.sample.stocktrader.messaging.client.NotificationClient`

**Comment by andymc12** [comment]
I delivered PR #6579 to verify that MP Rest Client can be invoked from EJBs - still good to test that scenario.  As for the warning message, that was an issue in 19.0.0.1 that is addressed with issue #6428.
