### ISSUE TITLE
REST API to test CouchDB

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#6563]
User story:
"As a user of Couch DB, I want to invoke a REST API to validate that my couchDB configuration is valid."

**Comment by alexsm82** [comment]
There is currently discussion over whether the couchDb feature should be stabilized. Whether this story gets implemented will depend on that decision.

**Comment by njr-11** [comment]
CouchDB feature has been stabilized and therefore we will not add integration with the validation REST endpoint for it.
