### ISSUE TITLE
Blog SEC-28: Add hash encoding support to QuickStartSecurity #6479

### ISSUE THREAD

**Issue by marikaj123** [OpenLiberty/open-liberty#6569]
Epic: https://github.com/OpenLiberty/open-liberty/issues/6479

**Comment by marikaj123** [comment]
GA

This information will be published in the blog post and used in Alasdair's webcast to announce what’s new in this release.

If the exact information you want give is already in a previous blog post:
a. Provide a link to the post(s), specify exactly which sections are relevant, and any updates required or to make it more interesting.
b. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.
 

---

If not previously published in a blog post, please answer the following questions:

a. Which Liberty feature does it relate to?

   i. Human-readable name (eg WebSockets feature)

   ii. Feature name (eg websockets-1.0)

   iii. Is this a new feature or is it an update to an existing feature for this release?

   iv. Provide the qualified name of all changed feature deliveries to this release? (eg: com.ibm.websphere.appserver.transportSecurity-1.0.esa)

b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc
c. Write a sentence or two that introduces it to someone new to the general technology/concept.
 
d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)
 
e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.
 
f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

g. Attach any images to this work item as .png files.

**Comment by jvanhill** [comment]
I have completed filling out the required information above.
