### ISSUE TITLE
Need to rename CXF JAX-RS projects 3.2 -> 3.4

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#6578]
In Issue #6313 and PR #6392, we upgraded CXF from 3.2.6 to 3.3.0.  The project names for the CXF projects still have the "3.2" version number - i.e. `com.ibm.ws.org.apache.cxf.cxf.rt.frontent.jaxrs.3.2`.  These should be renamed to end with "3.3" instead (with the exception of `com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.2` - that project needs to remain at 3.2 for MP Rest Client 1.0 and 1.1 compatibility - there is already a `com.ibm.ws.org.apache.cxf.cxf.rt.rs.mp.client.3.3` project for MP Rest Client 1.2).

This is part of the MP Rest Client 1.2 epic ( #5941 ), and is not a release bug.

**Comment by neuwerk** [comment]
@andymc12 I just noticed this issue but the same applies for the JAX-WS side of CXF. Can we combine the efforts and do all of them at once?

**Comment by andymc12** [comment]
Consensus is that we should probably just leave these alone.  Yes, the version has changed since we started development, but there is a lot of churn to perform a rename.  In general, I think it makes sense for liberty projects to use version numbers associated with the feature version rather than the version of the artifact... it's not a perfect solution, but better than the alternative.
