### ISSUE TITLE
Java 12: javac does not support source 1.6 compilation

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#6586]
In OpenLiberty we have a few components that require the lowest possible source compatibility, mainly so that when a user tries to start on a super old JDK we can at least boot the JVM and output a nice error message, as opposed to the more cryptic unsupported class version errors.

Right now, we have 2 components that try to compile down to Java 6, which causes OpenLiberty to fail to build with JDK 12.
```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':com.ibm.ws.kernel.instrument.check:compileJava'.
> error: release version 6 not supported

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':wlp.lib.extract:compileJava'.
> error: release version 6 not supported

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
```

So far the options I see are:
A) Update boot components to compile w/ target 1.7
B) Since boot components don't change often, we could manually compile them and check in the compiled binaries
C) Add conditional logic to compile as low as possible on the current build JDK. For example Java 11 build compiles at 1.6, Java 12 build compiles to 1.7.

Currently I have a question out on SO to see if any more elegant solutions are available: 
https://stackoverflow.com/questions/54752393/compile-to-lower-java-level-than-allowed-by-javac-using-gradle

**Comment by aguibert** [comment]
I raised this issue on the jdk-dev mailing list and was notified of this JEP which defines a policy for removing old options:
http://openjdk.java.net/jeps/182

To sum it up:
>  In JDK 9 and going forward, javac will use a "one + three back" policy of supported source and target options.

However, it appears they are just "reserving the right" to use the "one + three back" policy, but are really allowing "one + five back" for JDK 12.

**Comment by tevans78** [comment]
Look into setting a build property to control the compilation version. Keep version 1.6 for everything except Java 12 build.... at least until Java 7 goes out of support.

In general. push back via the Runtimes team, ask to support any version still in extended support.
