### ISSUE TITLE
RSO FAT Test Stream Completions CompletableFuture

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#6650]

**Comment by Azquelt** [comment]
Looking at the feature test summary, I will add tests to ensure that the thread context is set correctly both in the stream (in a map operation) and in the execution of synchronous actions attached to the stream completion CompletionStage object.

**Comment by hutchig** [comment]
Re comment above see https://github.com/OpenLiberty/open-liberty/pull/7191/commits/7db7eac359e1b4595a5cf92cbb8e82158fc6933b and https://github.com/OpenLiberty/open-liberty/pull/7191/commits/dcd2941d8c5a29ef2e9293c75830b82e318f9f10 which were cherry picked into the pull request for the function they were testing. Thank you Andrew!

**Comment by Azquelt** [comment]
Tests merged in #7191
