### ISSUE TITLE
Get open source approval for mpOpenTracing-1.3

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#6667]
Get open source approval for mpOpenTracing-1.3

**Comment by fmhwong** [comment]
@CassTucker 

I'd like to get OSS approval for shipping MicroProfile OpenTracing API 1.3 in Open Liberty 19.0.0.3.

Link to MP OT 1.3: https://github.com/eclipse/microprofile-opentracing/releases/tag/1.3
Link to Maven Repo: https://mvnrepository.com/artifact/org.eclipse.microprofile.opentracing/microprofile-opentracing-api/1.3

**Comment by CassTucker** [comment]
legal approves..
