### ISSUE TITLE
'pattern' restriction in schema is swallowed

### ISSUE THREAD

**Issue by sithmein** [OpenLiberty/open-liberty#6677]
If you have a `pattern` restriction on a string field in your OpenAPI schema definition, this is silently swallowed and not delivered by the `/openapi` resource.
Steps to reproduce:

1. `git clone https://github.com/openliberty/guide-microprofile-openapi.git`
2. `cd guide-microprofile-openapi/finish`
3. Modify `src/main/webapp/META-INF/openapi.yaml` so that a string field in the schema section (e.g. `hostname`) contains a pattern, e.g. `pattern: .+`
4. `mvn install liberty:start-server`
5. Open http://127.0.0.1:9080/openapi. You will see that the pattern restriction you just added is gone.

**Comment by yeekangc** [comment]
@arturdzm @leochr @arthurdm

**Comment by arturdzm** [comment]
This was fixed and should be included in 19.0.0.3
