### ISSUE TITLE
create config source for the variables with defaultValue specified

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#6678]
After introducing the following default value support in server.xml, we need to create a corresponding config source for the variables for them to be overridden and then injected correctly.

<variable name="host" defaultValue="localhost"/>

These variables need to be mapped to a config source with a lowest priority (1). It should be overridden by any other config sources but its value should be used if no config source override it.

`@Inject @ConfigProperty(name="host" defaultValue="129.1.1.1") String host;`
The value of host should be `localhost`, as specified in server.xml when no other config source specifies this property.

**Comment by tevans78** [comment]
Since I merged the PR before going on vacation, this is probably complete ... but I will double check before closing this issue.

**Comment by tevans78** [comment]
This is done
