### ISSUE TITLE
Plug in Kafaka Client to Liberty

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#6679]
Investigate how to get Liberty to consume Kafka including
Set up Kafka client, config Kafka etc. Kate Stanley has done some prototype before. reach out to her for help if needed. Follow instructions from https://console.bluemix.net/docs/services/EventStreams/eventstreams104.html#kafka_using
https://github.com/ibm-messaging/event-streams-samples/tree/master/kafka-java-liberty-sample

**Comment by tevans78** [comment]
As this was just an investigation, it is now complete. Andrew has understood how to run Kafka within Liberty.
