### ISSUE TITLE
RM: ID for Reactive Messaging

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#6683]
Documentation required:

* An introduction to Reactive Messaging
  * explain the structure of an RM application
  * introduce the concept of connectors
* Connecting to Kafka
  * explain how to use the included Kafka connector for ingress and egress of messages
  * document the configurable properties of the connector (include that all other properties as passed directly to the KafkaConsumer or KafkaProducer)

Laura suggested that we should produce this information as a blog post (as that will be needed anyway) and then the docs team will convert that into reference documentation to be included on openliberty.io/docs

**Comment by tevans78** [comment]
The blog post falls under issue #6682. It may be that is all we need before GA so this might become a no-op or get carried over to a later release.

**Comment by tevans78** [comment]
Confirmed that the only ID required for GA is the blog post. Closing this issue.
