### ISSUE TITLE
RM: Feature Test Summary

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#6686]
**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

This feature has two main parts - the core reactive messaging implementation, and an Apache Kafka connector, which allows messages to be sourced from and delivered to kafka topics by providing a reactive streams Publisher and Subscriber.

* Reactive Messaging Implementation
  * Note: We are consuming the smallrye reactive messaging provider which needs minimal integration
  * FAT test to run TCK
* Kafka connector
  * Note: We will use testcontainers to obtain a Kafka broker where one is required by the test
  * Run reactivestreams.org TCK test against the publisher and subscriber provided by the kafka connector to verify conformance to the reactive streams specification - #8204
    * This just verifies that the Publisher and Subscriber obey the rules set out in the interfaces they implement. It's a bit complicated and and easy to get wrong.
  * FAT tests for delivery of messages - #7741 
    * check message is delivered
    * check Message object is acknowledged on successful delivery
  * FAT tests for reception of messages - #8228 
    * check messages are received from the topic
    * check partition offset is committed after the message is acknowledged
    * check partition offset is only committed up to the first unacknowledged message if messages are acknowledged out of order
  * FAT tests for Kafka converters - #8230
    * test that several Kafka provided converters work
    * test that a custom converter packaged in the app works
    * test the behaviour when the type produced by a converter is not the type expected by the connected processor
  * FAT tests for handling of partition assignment - #8229 
    * check that we can add new readers with the same group id and that the connector handles having partitions removed
    * check that we can remove a second reader the same group id and that the connector handles having partitions assigned
    * check that partition offsets are committed correctly when reading from multiple partitions
  * FAT tests for using TLS 1.2 encryption for the broker connection - #7751 
  * FAT tests for using SASL PLAIN authentication for the broker connection - #7760 
  * FAT tests for using the LibertyLoginModule - #8207 
    * aes and xor encoded passwords
    * badly encoded passwords
    * unencoded passwords
  * FAT tests for loading a user-supplied Kafka client - #7752 
    * packaged within the app
    * packaged in a shared library
 * FAT tests for bad or missing configuration - #8471 
   * missing group.id
   * missing topic name (now defaults to channel name) - #8604 
   * bad connector id - #8575 
* Liberty / Cloud integration
  * FAT tests for allowing auth credentials to be encoded with `securityUtility` - #8207 
  * ~~FAT tests reading IBM Event Streams config from `VCAP_SERVICES` - #8208~~ (functionality removed from scope)

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

**4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.**

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by ayoho** [comment]
@Emily-Jiang @Azquelt @tevans78 What I've seen so far for PRs for test deliveries has been good. I did have a couple questions about some specific testing based on what I had read in the WAD, though.
1. The WAD mentions leveraging the MP Config feature to obtain and use various values. What, if any, "interesting" scenarios are there to test in that regard as it pertains to this feature? And are those scenarios being tested?
1. The WAD also mentions ensuring that the Kafka LoginModule callback works for AES-encrypted values. Is that something that we have the power to test, and if so, is there any testing in place for those scenarios? Are there any other encoded/encrypted value scenarios that make sense to test?

The answers to these may very well be in the PRs that have already been linked, but I'd appreciate any clarification you might be able to provide.

**Comment by tevans78** [comment]
@ayoho Good questions ... we have done these tests but they don't appear to be linked here. I will update today.

**Comment by tevans78** [comment]
@ayoho I added these above...
FAT tests for using the LibertyLoginModule - #8207
    aes and xor encoded passwords
    badly encoded passwords
    unencoded passwords
FAT tests for bad or missing configuration - #8471
    missing group.id
    missing topic name (now defaults to channel name) - #8604
    bad connector id - #8575

**Comment by ayoho** [comment]
I'm satisfied with the details here. Now just have to wait for this weekend's SOE results to see how this functionality fared before I approve.
