### ISSUE TITLE
Support JDK 12 in OpenLiberty

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#6736]
See JDK 12 page for details on what's new: https://openjdk.java.net/projects/jdk/12/

Primary challenges posed with this effort:
- javac target 1.6 is dropped
- class file format gets incremented (requires updates in ASM and Gradle)

**Comment by aguibert** [comment]
Support for JDK 12 was delivered in 19.0.0.4, and announced here:
https://openliberty.io/blog/2019/04/26/reactive-microservices-microprofile-19004.html#java12

**Comment by samwatibm** [comment]
Closed already; remove target:ga
