### ISSUE TITLE
Override sessioncache/jcache url encoded automatic cache names

### ISSUE THREAD

**Issue by dacleyra** [OpenLiberty/open-liberty#6762]
cache names created by sessionCache-1.0 feature are named and encoded such as:

com.ibm.ws.session.attr.default_host%2Fmicrowebapp

Some jcache providers have issues with the url encoded cache name
- The Hazelcast management center can not correctly display statistics for a cache with url encoded names
- Using the Hazelcast REST API would require double url encoding the cache name, which is not allowed for security reasons

**Comment by zhang-ca** [comment]
JCache spec does not allow slash "/", we need to encoded with something.

**Comment by zhang-ca** [comment]
@dacleyra any suggestion for replacing the slash ?
Will the dot ok ?  com.ibm.ws.session.attr.default_host.microwebapp
