### ISSUE TITLE
AccessController.doPrivileged() needs to wrap JMX service registration.

### ISSUE THREAD

**Issue by mrglavas** [OpenLiberty/open-liberty#677]
The registration of the MBeanServerPipeline needs to be wrapped in an AccessController.doPrivileged() otherwise it might fail if an application thread happens to be the first one to access the MBeanServer.

**Comment by ewhoch** [comment]
@mcglavas is this ready to close? did you verify it?

**Comment by mrglavas** [comment]
Thanks for the reminder. Verified a long time ago. I forgot to close it.
