### ISSUE TITLE
OOM Problems in InjectionEngine Cache

### ISSUE THREAD

**Issue by olendvcook** [OpenLiberty/open-liberty#6771]
The InjectionEngine stores a cache of processed classes in ReferenceContextImpl.ivProcessedInjectionClasses in a Set. After processing a class it is put in the cache so it is not processed again. The cache can grow too big and cause memory problems when the injection engine has to keep processing dynamic JSP classes that are regenerated.

**Comment by olendvcook** [comment]
Our current solution is to cap the size of the cache when doing dynamic processing. By the time we hit the cap we should have already stored all the regular classes and are only capping the regenerated JSP classes.

**Comment by tkburroughs** [comment]
PR merged; closing
