### ISSUE TITLE
Manual testing with zipkin tracer user feature

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#6789]
Manual test with Zipkin tracer sample https://github.com/WASdev/sample.opentracing.zipkintracer

**Comment by tonyreigns** [comment]
To test OpenTracing.1.3 and mpRestClient.1.2, I made it so the Zipkin user feature used Opentracing.1.3 and created two Liberty servers using the same applications found in the Openliberty.io OpenTracing guide found here: https://openliberty.io/guides/microprofile-opentracing.html 

I checked to make sure that we could reach all the endpoints without any issues and that all the spans were being picked up by Zipkin. With the new version of OpenTracing and mpRestClient, I ensured that when calling the /inventory/systems/localhost endpoint that the spans were grouped together as expected which is one of the fixes made in the newer version of OpenTracing. I was able to complete the guide successfully with the new changes.

**Comment by tonyreigns** [comment]
These tests were repeated using an official development offering(wlp-cl190320190314-0300.zip) found here: https://libertyfs.hursley.ibm.com/liberty/dev/Xo/release/cl190320190314-0300-_6N6gEEX8Eemzxv6qGNuYMg/

The tests resulted in the same way as the tests performed on the personal build offering. When accessing the http://localhost:9081/inventory/systems/localhost endpoint from the [OpenLiberty OpenTracing Guide](https://openliberty.io/guides/microprofile-opentracing.html), the following trace was found:

<img width="1438" alt="Trace" src="https://user-images.githubusercontent.com/5152406/54380415-bf7e2c80-4661-11e9-9cce-60e8bee23925.png">

Closer looks at each span in order:
<img width="732" alt="Span1" src="https://user-images.githubusercontent.com/5152406/54380471-f18f8e80-4661-11e9-8808-22ddf93aad9b.png">
<img width="633" alt="Span2" src="https://user-images.githubusercontent.com/5152406/54380489-f94f3300-4661-11e9-9876-6bab91be29a9.png">
<img width="615" alt="Span3" src="https://user-images.githubusercontent.com/5152406/54380488-f94f3300-4661-11e9-9a29-125380dcce75.png">

The trace JSON: 
`[
  {
    "traceId": "9ddc43e485aa1367",
    "parentId": "9ddc43e485aa1367",
    "id": "eadc5aa81c55eb3a",
    "kind": "CLIENT",
    "name": "get",
    "timestamp": 1552586144737449,
    "duration": 1241999,
    "localEndpoint": {
      "serviceName": "inventory-service"
    },
    "tags": {
      "component": "jaxrs",
      "http.method": "GET",
      "http.status_code": "200",
      "http.url": "http://localhost:9080/system/properties"
    }
  },
  {
    "traceId": "9ddc43e485aa1367",
    "parentId": "9ddc43e485aa1367",
    "id": "121871daebcf709a",
    "name": "add() span",
    "timestamp": 1552586146113125,
    "duration": 47,
    "localEndpoint": {
      "serviceName": "inventory-service"
    }
  },
  {
    "traceId": "9ddc43e485aa1367",
    "id": "9ddc43e485aa1367",
    "kind": "SERVER",
    "name": "get:io.openliberty.guides.inventory.inventoryresource.getpropertiesforhost",
    "timestamp": 1552586144388426,
    "duration": 1730592,
    "localEndpoint": {
      "serviceName": "inventory-service"
    },
    "tags": {
      "component": "jaxrs",
      "http.method": "GET",
      "http.status_code": "200",
      "http.url": "http://localhost:9081/inventory/systems/localhost"
    }
  },
  {
    "traceId": "9ddc43e485aa1367",
    "parentId": "9ddc43e485aa1367",
    "id": "eadc5aa81c55eb3a",
    "kind": "SERVER",
    "name": "get:io.openliberty.guides.system.systemresource.getproperties",
    "timestamp": 1552586145770462,
    "duration": 60472,
    "localEndpoint": {
      "serviceName": "system-service"
    },
    "tags": {
      "component": "jaxrs",
      "http.method": "GET",
      "http.status_code": "200",
      "http.url": "http://localhost:9080/system/properties"
    },
    "shared": true
  }
]`
