### ISSUE TITLE
Port com.ibm.ws.jaxws.ejb_fat bucket to open-liberty

### ISSUE THREAD

**Issue by BerksanAtes** [OpenLiberty/open-liberty#6793]
Ported com.ibm.ws.jaxws.ejb_fat_lWAS bucket from WS-CD-Open to com.ibm.ws.jaxws.ejb_fat bucket in open-liberty. Way of creating new jar, war and ear packages in test classes changed besides the addition of few javaPermissions in server.xml files. 

Steps to port:

- [x] Move com.ibm.ws.jaxws.ejb_fat_lWAS to OL
- [x] Update references and copy-write headers
- [x] Update FAT test apps to be built with the OL test framework
- [ ] After delivering the OL com.ibm.ws.jaxws.ejb_fat remove com.ibm.ws.jaxws.ejb_fat from CL

**Comment by jhanders34** [comment]
#run-libby

**Comment by jhanders34** [comment]
#libby

**Comment by jhanders34** [comment]
#libbybot
