### ISSUE TITLE
HTTP request header "If-Modified-Since" parsing fails with IllegalArgumentException if default Locale isn't US

### ISSUE THREAD

**Issue by avojenk** [OpenLiberty/open-liberty#6812]
jhanders34@9dd7e423d51ae5de8b41647b1c1f9855716d394f
The refactoring of CachedTime in HttpLocalFormat no longer sets the Locale for myParse SimpleDateFormat, thus using the default locale:
`this.myParse = new SimpleDateFormat(pattern);`

Probably applies to other HTTP request headers in HTTP-date format as well.

'com.ibm.ws.webcontainer.osgi.request.IRequestImpl.getDateHeader:264'
java.lang.IllegalArgumentException: Fri, 01 Feb 2019 10:39:48 GMT
	at com.ibm.ws.webcontainer.osgi.request.IRequestImpl.getDateHeader(IRequestImpl.java:264)
...
Caused by: java.text.ParseException: Unparseable [Fri, 01 Feb 2019 10:39:48 GMT]
	at com.ibm.ws.http.internal.HttpDateFormatImpl.parseTime(HttpDateFormatImpl.java:391)
	at com.ibm.ws.webcontainer.osgi.request.IRequestImpl.getDateHeader(IRequestImpl.java:257)
...

**Comment by jhanders34** [comment]
Looking at the change I see I missed passing the Locale to the new SimpleDateFormat to match what was done previously.  I will make a PR to fix that.

**Comment by jhanders34** [comment]
To include references, this issue was caused by the changes I made in PR #5808.  In that change I changed to lazily initialize the different parsers in order to avoid extra memory in the heap that may never be needed.  I missed passing the Locale to the SimpleDateFormat for the parse SimpleDateFormat as the reporter points out.

**Comment by jhanders34** [comment]
The pull request has been merged and will be available in the next open liberty and commercial liberty release.  Thank you for reporting this problem.
