### ISSUE TITLE
Endpoint domain for OpenLiberty provided REST APIs

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#6825]
In WebSphere Liberty, there is a mechanism where server-provided REST endpoints can implement `RestHandler` and end up under the `ibm/api` domain, for example:
http://localhost:8080/ibm/api/whatever

This is useful because the `ibm/api` domain can be automatically aggregated for built-in API discovery tools like OpenAPI.

In OpenLiberty, we do have the `RestHandler` interface, but we may want to re-think whether or not OpenLiberty endpoints should still be provided under the `ibm/api` domain.

Some potential options:
1. `/ibm/api` (existing endpoint, continue putting OpenLiberty endpoints here)
2. `/liberty/api`
3. `/platform/api`
4. `/openliberty/api`
5. `/wlp/api`

Whatever we decide to go with, we will want to choose a name that has a low probability of conflicting with existing user's application endpoints.

The immediate use case for this is we are working on moving the `validator-1.0` feature to OpenLiberty, and want an appropriate path for the new `.../validator` and `.../config` endpoints

**Comment by arthurdm** [comment]
Thanks @aguibert - my vote is for `/liberty/api`, so that this can be the REST Handler endpoint going forward for both WebSphere Liberty and Open Liberty.

**Comment by tevans78** [comment]
`/ibm/api` < existing endpoint but has `ibm` in
`/liberty/api` < possible security implications by exposing liberty as the platform
`/platform/api` < ok ... `/system/api` might be an alternative (product name neutral)
`/openliberty/api` < will look wrong when running WebSphere Liberty
`/wlp/api` < contains wlp so same problem as `ibm`

Will stick with `/ibm/api` for now to maintain consistency but will consider an additional endpoint in the future.

**Comment by frowe** [comment]
Since we had a resolution, can this DI be closed?

**Comment by aguibert** [comment]
We had an immediate resolution for the validator feature (keep using `/ibm/api`), but I believe we were going to further discuss a more general solution that we could apply in the future.

**Comment by frowe** [comment]
I don't recall that.  If that were the case wouldn't we have just discussed it during the DI call?

**Comment by frowe** [comment]
Closing, implemented /platform.
