### ISSUE TITLE
Improvements for com.ibm.ws.mongo_fat

### ISSUE THREAD

**Issue by brideck** [OpenLiberty/open-liberty#6887]
This issue is to address a handful of intermittent problems with the com.ibm.ws.mongo_fat bucket.

- In error test cases, expected errors/FFDC can sometimes leak from one test into another causing spurious failures.  I'll add extra log checking to ensure that the mongo thread has thrown all expected errors before proceeding to the next test.
- Likewise, the testCertAuthInvalidTrust method in the SSL tests causes a recurring FFDC to be thrown that can sometimes interfere with tests that run after it.  I'll move this test to a separate class/server instance to eliminate that potential for interference.
- The tests currently allow a whole slew of errors/FFDC that are unrelated to the proper execution of the tests.  I'll seek to clean that up as much as possible here.
- Tests can fail for non-obvious reasons when the wrong exception is received.  I'll add a check to verify that the exception is actually expected.

**Comment by tkburroughs** [comment]
PR was merged; closing.
