### ISSUE TITLE
server.xml: using include to set keystore password AES encoding key property fails

### ISSUE THREAD

**Issue by johnarwe** [OpenLiberty/open-liberty#6900]
Released bug in product = WebSphere Application Server 18.0.0.4 (wlp-1.0.23.cl180420181121-0300).

Per the recommendation in https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/cwlp_pwd_encrypt.html 

>... by setting the wlp.password.encryption.key property. This property must not be set in the server.xml file that stores the password, but in a separate configuration file that is included by the server.xml file. This separate configuration file must contain only a single property declaration, and must be stored outside the normal configuration directory for the server.

I found that **using a server.xml include fails, but using bootstrap properties instead works, with identical value for the secret**.  I have reproduced this on both systems I tried (RHEL 7.6 IBM Java 8 20180502_01(SR5 FP15) and OpenSSL 1.0.2k-fips  26 Jan 2017, SLES 11.3 IBM Java 7.0 and 2009-vintage openssl), using the same Liberty code (18.004, as above)

Server.xml steps
- I  started with a existing and working server.xml file that included a known `{xor}` encoded keystore password, 
- added an `<include` element to another file whose `<property...>` content set the `wlp.password.encryption.key` property value, 
- used `securityUtility encode --encoding=aes --key=[secret] ...new-password-value...` to encode the new password
- put the encoded output in server.xml, and the secret in the file that server.xml includes as the value of the `wlp.password.encryption.key` 
- started Liberty

Example of file contents:
```
/usr/wave/websphere/wlp/bin/securityUtility encode --encoding=aes --key=A5875CBF0ABDD109592987BE414994B3 tpns2013
{aes}ABAxLijxnT2M6H9qViKyDwqR7+Aps+rsN9vZLPdc2EAs
egrep -e "pass|include" /usr/wave/websphere/wlp/usr/servers/defaultServer/server.xml
        <keyStore id="defaultKeyStore" password="{aes}ABAxLijxnT2M6H9qViKyDwqR7+Aps+rsN9vZLPdc2EAs"/>
        <include location="/usr/wave/install/liberty-properties01.xml"/>
cat /usr/wave/install/liberty-properties01.xml
<variable name="wlp.password.encryption.key" value="A5875CBF0ABDD109592987BE414994B3" />
```
Related messages.log content
```
egrep " E |/usr/wave" $liblog
wlp.install.dir = /usr/wave/websphere/wlp/
[3/13/19 7:36:37:876 EDT] 00000014 com.ibm.ws.config.xml.internal.XMLConfigParser               A CWWKG0028A: Processing included configuration resource: /usr/wave/install/liberty-properties01.xml
[3/13/19 7:36:40:318 EDT] 00000018 com.ibm.websphere.crypto.PasswordUtil                        E CWWKS1856E: The password was not processed because an unknown password algorithm exception was reported.
[3/13/19 7:36:40:345 EDT] 00000018 com.ibm.ws.ssl.config.WSKeyStore                             E CWPKI0033E: The keystore located at /usr/wave/websphere/wlp/usr/servers/defaultServer/resources/security/key.jks did not load because of the following error: Keystore was tampered with, or password was incorrect
```
Stack trace from messages.log with the include
```
 24 [3/13/19 10:02:08:377 EDT] 00000020 com.ibm.websphere.crypto.PasswordUtil                        E CWWKS1856E: The password was not processed b    ecause an unknown password algorithm exception was reported.
 25 com.ibm.websphere.crypto.UnsupportedCryptoAlgorithmException
 26     at com.ibm.ws.crypto.util.PasswordCipherUtil.aesDecipher(PasswordCipherUtil.java:264)
 27     at com.ibm.ws.crypto.util.PasswordCipherUtil.decipher(PasswordCipherUtil.java:197)
 28     at com.ibm.websphere.crypto.PasswordUtil.decode_password(PasswordUtil.java:624)
 29     at com.ibm.websphere.crypto.PasswordUtil.decode(PasswordUtil.java:135)
 30     at com.ibm.ws.ssl.config.WSKeyStore.decodePassword(WSKeyStore.java:1035)
 31     at com.ibm.ws.ssl.config.WSKeyStore$1.run(WSKeyStore.java:687)
 32     at com.ibm.ws.ssl.config.WSKeyStore$1.run(WSKeyStore.java:676)
 33     at java.security.AccessController.doPrivileged(AccessController.java:696)
 34     at com.ibm.ws.ssl.config.WSKeyStore.obtainKeyStore(WSKeyStore.java:676)
 35     at com.ibm.ws.ssl.config.WSKeyStore.do_getKeyStore(WSKeyStore.java:647)
 36     at com.ibm.ws.ssl.config.WSKeyStore.getKeyStore(WSKeyStore.java:849)
 37     at com.ibm.ws.ssl.config.WSKeyStore.initializeKeyStore(WSKeyStore.java:936)
 38     at com.ibm.ws.ssl.config.WSKeyStore.<init>(WSKeyStore.java:243)
 39     at com.ibm.ws.ssl.internal.KeystoreConfig.updateKeystoreConfig(KeystoreConfig.java:93)
 40     at com.ibm.ws.ssl.internal.KeystoreConfigurationFactory.updated(KeystoreConfigurationFactory.java:100)
 41     at com.ibm.ws.config.admin.internal.ManagedServiceFactoryTracker$2.run(ManagedServiceFactoryTracker.java:267)
 42     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
 43     at java.util.concurrent.FutureTask.run(FutureTask.java:277)
 44     at com.ibm.ws.config.admin.internal.UpdateQueue$Queue.run(UpdateQueue.java:67)
 45     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
 46     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 47     at java.lang.Thread.run(Thread.java:811)
 48 Caused by: javax.crypto.BadPaddingException: Given final block not properly padded
 49     at com.ibm.crypto.provider.AbstractBufferingCipher.a(Unknown Source)
 50     at com.ibm.crypto.provider.AbstractBufferingCipher.engineDoFinal(Unknown Source)
 51     at javax.crypto.Cipher.doFinal(Unknown Source)
 52     at com.ibm.ws.crypto.util.PasswordCipherUtil.aesDecipher(PasswordCipherUtil.java:250)
 53     ... 21 more
```

**Comment by emilytee** [comment]
@johnarwe , in your server.xml file, do you specify a location for the defaultKeyStore?   If not, can you specify the location, and make sure to reference the keystore with .p12 filetype.     Retry and update if that resolved the issue.    As of 18.0.0.4, if a location is not specified for the defaultKeyStore in server.xml, we default to use PKCS12 keystore types.

**Comment by emilytee** [comment]
@johnarwe, any updates?

**Comment by johnarwe** [comment]
Thanks for the poke, I don't recall seeing any GH notification from 12 days ago.  No location (if you squint hard at the original, it's just `<keyStore id=... password=... />`, and that was a paste.

In the interim, we've had to GA the code using bootstrap properties so there is no appetite on our product's part to fool around with the property-based alternative at this point.  I can tell you though, having done "more than a few" fresh-install tests, that I'm "skeptical" that 18.004 changed the default to p12.  We did ship (and test) with 18.004, we do not lay down our own keystore, our `<keyStore` tag is unchanged (no location=), and we get JKS keystores created when Liberty first starts.  I wonder if that change slipped to 19.001; it almost certainly breaks code we just shipped.

**Comment by emilytee** [comment]
Typo on my part.   It was 19.0.0.3+ where this was introduced.    The security utility tool is being updated to add an option to create the JKS file under resource/security.

**Comment by emilytee** [comment]
https://github.com/OpenLiberty/open-liberty/pull/7501 provides an option, --keyType, to specify the expected keystore type.  By default, a PKCS12 keystore will be generated if that option is not specified.  Hence, specifying the option as, --keyType=PKCS12, is not necessary.  If AJKS keyfile is expected,  specify --keyType=JKS.
