### ISSUE TITLE
Open Source Approval for LG-37: Jaeger support in MicroProfile Open Tracing

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#6908]
This feature will not ship any Jaeger client library but it will depend on jaeger-core version 0.34.0 for compilation purpose.  https://mvnrepository.com/artifact/io.jaegertracing/jaeger-core/0.34.0

**Comment by fmhwong** [comment]
@CassTucker May I get your approval?

**Comment by CassTucker** [comment]
This is using Apache V2 license and update to Open Tracing, yes?

**Comment by fmhwong** [comment]
Yes, this is using Apache V2 license https://github.com/jaegertracing/jaeger-client-java/blob/master/LICENSE.  

This is a new file for approval.  This is used for compilation but NOT included in the product.

**Comment by CassTucker** [comment]
Approve to include

**Comment by jennifer-c** [comment]
The Jaeger FAT test will require the following jars for compilation:

https://mvnrepository.com/artifact/com.google.code.gson/gson/2.8.2
https://mvnrepository.com/artifact/io.jaegertracing/jaeger-thrift/0.34.0
https://mvnrepository.com/artifact/io.jaegertracing/jaeger-client/0.34.0
https://mvnrepository.com/artifact/org.slf4j/slf4j-simple/1.7.26
https://mvnrepository.com/artifact/org.slf4j/slf4j-api/1.7.26
https://mvnrepository.com/artifact/org.apache.thrift/libthrift/0.11.0

They will not be shipped with the product, but are required to run the tests.

@CassTucker Could I get your approval?

**Comment by CassTucker** [comment]
Approved!
