### ISSUE TITLE
Feature test summary for LG-37: Jaeger support in MicroProfile Open Tracing

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#6909]
**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature.

If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by jennifer-c** [comment]
1)
The FAT contains the following tests:
- testTraceCreated
    - Tests that a trace is being created when Jaeger is configured properly.
- testImproperConfig
    - Tests that the appropriate error, CWMOT0008E, is sent if the user enables Jaeger but does not have the appropriate libraries.
- testJaegerNotEnabled
    - Tests that the appropriate error, CWMOT0008E, is sent if the user does not have Jaeger enabled (no tracer provided)
- testMultiSpans
    - Tests that spans are created on multiple servers when hitting one endpoint (this test uses two servers)

Manual testing was also done as an extra level of verification already tested by `com.ibm.ws.microprofile.opentracing.jaeger_fat`. Jaeger also provides a UI, so manual testing was done to ensure that the spans were being sent from the Liberty server to the UI.

2)
4 - The current automated testing adequately tests the Jaeger feature.

**Comment by fmhwong** [comment]
@sabolo Please review

**Comment by sabolo** [comment]
Hi... I am concerned there is very sparse testing here... please could you address the following comments?

1:  There are only 3 tests delivered.  This seems extremely sparse to verify everything that could be traced.  Surely there should be more in depth testing to ensure we handle incorrect values, any load tests, responsiveness etc
2:  What if ZipKin and Jaeger are both configured… what happens… does it work as expected?
3:  There are at least 2 ways to configure Jaeger (in server XML or in the WAR) however I don’t see any reference to both being tested
4:  I see no testing using encrypted and none encrypted passwords or certificates
5:  How have you verified Jaeger when its on a different host?
6:  Have you matched the same level of testing you did for ZipKin?  Did that only involve 3 tests?
7:  What about issues like if the collector is offline or returning errors or the Jaeger agent is unresponsive, slow, returning failures etc.

**Comment by sabolo** [comment]
Answers to the above were received via email and slack.  The net outcome having looked through all that is delivered was that extra testing was needed to confirm that configuration of Jaeger in a WAD works.  This has been tested manually and by SVT but needs to be in the FAT framework.  The risk is considered minimal and I have agreed that this will be delivered as a priority but is not a blocker for the GM.
