### ISSUE TITLE
ID for mpOpenAPI-1.1

### ISSUE THREAD

**Issue by arturdzm** [OpenLiberty/open-liberty#6912]
All the documentation for mpOpenAPI-1.0 feature is still relevant for mpOpenAPI-1.1 
We need to just add basic feature information to KC

**Comment by arturdzm** [comment]
Wer are looking to update mentions of 1.0 to 1.1 here
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_mpopenapi.html

**Comment by chirp1** [comment]
Jeff will update twlp_mpopenapi.html. Artur will handle updates to the autogen topic.

**Comment by jantley-ibm** [comment]
@arturdzm Is it correct to say "Starting with 19.0.0.3, support for mpOpenAPI-1.1 is added. Through 19.0.0.2, use mpOpenAPI-1.0." ?

**Comment by arturdzm** [comment]
Yes, starting with 19.0.0.3 we want people to use mpOpenAPI-1.1 feature,
Also there is a link  `MicroProfile OpenAPI 1.0 specification`

that should be updated to use 1.1.2 link
 https://download.eclipse.org/microprofile/microprofile-open-api-1.1.2/microprofile-openapi-spec.html

**Comment by jantley-ibm** [comment]
Here is the pull request: https://github.ibm.com/was-liberty/liberty-docs/pull/1154

**Comment by arturdzm** [comment]
@jantley-ibm Thanks
