### ISSUE TITLE
bootstrap.properties documentation omits include syntax

### ISSUE THREAD

**Issue by johnarwe** [OpenLiberty/open-liberty#6922]
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/cwlp_pwd_encrypt.html says  `put the encryption key in a separate properties file that is included in the server bootstrap.properties file.` but I'm not finding the syntax for inclusion there.  

E.g. searching for `include` in https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_inst_bootstrap.html yields no interesting hits (and that page is the best match I've found from sampling the search engine's results).  

The bottom of https://stackoverflow.com/questions/46251965/liberty-server-properties-file-setup?rq=1 says `you can include additional files by specifying bootstrap.include` but a search on `bootstrap.include` yields nothing in the pubs.

Experimentally I have confirmed that 18.004 works with the simple-minded approach below, but this still need to be documented:
```
cat bootstrap.properties
bootstrap.include=/usr/wave/install/liberty-bootstrap.properties
# A comment
cat /usr/wave/install/liberty-bootstrap.properties
wlp.password.encryption.key=mysecret
```
I also experimentally confirmed that multiple bootstrap.include "statements" are processed, if present.  Since include is non-standard behavior compared to property files in general, I think it's important to include the "multiple includes work" behavior, either implicitly or explicitly.

**Comment by NottyCode** [comment]
@johnarwe this is documented on [this page](
https://www.openliberty.io/docs/ref/config/#serverConfiguration.html) in the OpenLiberty docs. It says:

The bootstrap.properties file supports a special property, bootstrap.include, which optionally specifies another properties file to also be read during the bootstrap stage. This include file could, for example, contain a common set of bootstrap properties to be used by multiple servers. Set the bootstrap.include to an absolute or relative file path.

**Comment by johnarwe** [comment]
@NottyCode the implication being that each user (embedder) of WebSphere Liberty is expected to know which implementation components come from elsewhere (OpenLiberty being but one example of ... what, hundreds?), and search the transitive closure of those docs?

The OpenLiberty doc page you refer to has its own ambiguties wrt bootstrap.include.  It leaves open whether or not multiple include files can be used, and whether or not the includes are recursive (an include-d file1 contains bootstrap.include=file2), for example.  A -narrow- reading would say that multiple includes from a single are not allowed, based on the use of singular "file" in 2 places, but (speaking as a former W3C spec editor) that's a bit much to expect from most readers.
