### ISSUE TITLE
[19.0.0.2] Eclipselink Issues when compiling with Java 11

### ISSUE THREAD

**Issue by lostiniceland** [OpenLiberty/open-liberty#6948]
As mentioned in API-9 (the Java 11 issue for Openliberty) I came accross weird issues when using Java 11 with regards to Java Enums.

There are currently 3 issues related to enums and Java 11

- inner-class enums cannot be resolved in JPQL
- JpaConverters run into an Postgres-Error using the != operator in JPQL
- an enum with a instance-method fails the creation of the persistence-context

I've attached a Gradle build which contains separate samples for each. Details on how to use the sample are at the end.

[test.tar.gz](https://github.com/OpenLiberty/open-liberty/files/2980123/test.tar.gz)

### Error Description

My observation showed that the problems are not simply caused when running OL with Java 11 (OpenJDK or OpenJ9). **The errors occur when the deployed artefact is compiled with Java 11**. So running the same code compiled with Java 1.8 on Java 11 works.

I've provided console-output for the each szenario with working and error case.
All errors seem to occur in Eclipselink, so they might have to be fixed there.

## Provided Sample
The sample is using Gradle 5.2.1 (provided via wrapper) and uses PostgreSQL 11 (via docker-compose) to simulate the environment where the errors first occured.

The project is currently configured with Java 11 compilation/target. To change to Java 1.8 just change the lines 28-31 in `build.gradle.kts`.

### Modules
The actual samples are located in their own module `sample-xyz`
Each module contains a `README.txt` which has a desciption of the working use-case as well as the error-stack-trace

The only additional dependency added is Flyway to quickly setup the database for each module.

### Server Setup
For ease of use, I've provided several Gradle tasks which do the following
- Download OL 19.0.0.2 and extract it to <project>/server/wlp
- Download PostgreSQL-JDBC and add it as a library-folder
- Copy a preconfigured server.xml to the created default-server

To use the server just run `./gradlew updateServer`

### Run PostgreSQL
To start the necessary PostgreSQL run `docker-compose -f postgres.yml up` in the docker-compose folder. This uses an provided init-script to create a user and schema for module in order to not run into any side-effects.

**Comment by aguibert** [comment]
hi @lostiniceland, thanks for providing the detailed sample and issue writeup. 

I see you are downloading and unzipping Liberty with custom gradle tasks, and I just wanted to make sure you're aware of the Liberty Gradle plugin:
https://openliberty.io/guides/gradle-intro.html
I use gradle for all of my projects, and this plugin is provided/maintained by OpenLiberty so it is quite reliable.

**Comment by lostiniceland** [comment]
Nope, I havent seen this plugin. Looks very promising.
We use the approach at work (via Maven) to extract and configure a reproducible developer-server (wildfly, liberty, tomcat) for every teammember which is then integrated in the IDE. Turned out very usefull.

**Comment by dazey3** [comment]
I was able to reproduce the "Problem compiling" failure in a simple JSE test harness, outside Liberty and PostgreSQL (which I thought might be involved), by using EclipseLink 2.7.3. However, after updating to EclipseLink 2.7.4, the failure goes away and the test passes.

**Comment by lostiniceland** [comment]
I've run the tests again with the latest 19.0.0.3 release and can confirm that the Eclipselink errors are gone. I've also tested against another project and so far it is looking good.
