### ISSUE TITLE
Blog: LG-51: mpOpenTracing v1.3

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#6952]
GA

This information will be published in the blog post and used in Alasdair's webcast to announce what’s new in this release.

If the exact information you want give is already in a previous blog post:
a. Provide a link to the post(s), specify exactly which sections are relevant, and any updates required or to make it more interesting.
b. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

If not previously published in a blog post, please answer the following questions:

a. Which Liberty feature does it relate to?

i. Human-readable name (eg WebSockets feature)

    MicroProfile Open Tracing 1.3

ii. Feature name (eg websockets-1.0)

    mpOpenTracing-1.3
 
iii. Is this a new feature or is it an update to an existing feature for this release?

    This is an update to add support tracing with MicroProfile REST clients.

iv. Provide the qualified name of all changed feature deliveries to this release? (eg: com.ibm.websphere.appserver.transportSecurity-1.0.esa)

    com.ibm.websphere.appserver.mpOpenTracing-1.3.esa

b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc

    Developers and administrators

c. Write a sentence or two that introduces it to someone new to the general technology/concept.

    Introduced the support of tracing with MicroProfile REST clients.

d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)

    In the previous version of MicroProfile Open Tracing, tracing of client/server calls 
    can be done with JAX-RS clients only.  MicroProfile REST client calls 
    will be broken down into 2 separate traces.  One trace is created for 
    the first service (i.e. caller) and another trace is created for the 
    second service.

    In MicroProfile Open Tracing 1.3, tracing of client/server calls can be done with 
    JAX-RS clients and MicroProfile REST clients.  Client/server calls will become 
    a single trace with multiple spans.

e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.

    Include the following in the server.xml:
    <feature>mpOpenTracing-1.3</feature>
    <feature>mpRestClient-1.2</feature>

    No other configuration is required.

    Tracing for MicroProfile REST clients are enabled globally by default if the features 
    are specified in the server configuration. You may individually turn tracing off 
    by specifying @Traced(false) on the REST client interface class level or method level. 

f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

    https://github.com/eclipse/microprofile-opentracing/releases/tag/1.3

g. Attach any images to this work item as .png files.

    N/A

**Comment by marikaj123** [comment]
Epic: https://github.com/OpenLiberty/open-liberty/issues/6338

**Comment by lauracowen** [comment]
Thanks
