### ISSUE TITLE
Blog Post  API-35 - mpRestClient-1.2 for 19003

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#6959]
GA

This information will be published in the blog post and used in Alasdair's webcast to announce what’s new in this release.

If the exact information you want give is already in a previous blog post:
a. Provide a link to the post(s), specify exactly which sections are relevant, and any updates required or to make it more interesting.
b. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

If not previously published in a blog post, please answer the following questions:

a. Which Liberty feature does it relate to?

i. Human-readable name (eg WebSockets feature)

    MicroProfile Rest Client 1.2

ii. Feature name (eg websockets-1.0)

    mpRestClient-1.2
 
iii. Is this a new feature or is it an update to an existing feature for this release?

    This is a new feature version - it is the third version of the MicroProfile Rest Client implementation provided by Liberty.

iv. Provide the qualified name of all changed feature deliveries to this release? (eg: com.ibm.websphere.appserver.transportSecurity-1.0.esa)

    com.ibm.websphere.appserver.mpRestClient-1.2.esa

b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc

    Primarily developers, but also devops pipeline devs.

c. Write a sentence or two that introduces it to someone new to the general technology/concept.

    MicroProfile Rest Client is a type-safe client API for invoking RESTful services.  Version 1.2 improves developer experience and enhances integration with other MicroProfile technologies such as CDI, Fault Tolerance, OpenTracing, etc.

d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)

    Previous releases of the Rest Client lacked integration with CDI, Fault Tolerance, OpenTracing, etc. making it difficult to add things like timeouts, retries, circuit breakers, etc. to client interfaces.  In addition to improving the integration with other MicroProfile technologies, MicroProfile Rest Client 1.2 has improved developer experience by allowing users to specify the base URL directly in the `@RegisterRestClient` annotation in the interface - and allowing users to specify connect and read timeouts in a portable fashion.

    Sending HTTP headers or propagating them from a JAX-RS request has been a complicated problem with prior releases, but not anymore.  Now users can specify HTTP headers to send or propagate using the new `@ClientHeaderParam` annotation, MicroProfile Config properties, or by implementing a new `ClientHeadersFactory` interface.

e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.

Add `<feature>mpRestClient-1.2</feature>` to the server.xml to enable the feature.

---

Here is an example of specifying the URI in the annotation on the interface:
```
package io.openliberty.rest.client;
...
@RegisterRestClient(baseUri="http://localhost:9080/myBaseUri")
public interface ClientWithURI {
...
```
Note that this can still be overridden by specifying a MicroProfile Config property like this:
`io.openliberty.rest.client.ClientWithURI/mp-rest/uri=http://localhost:9080/myOverriddenBaseUri`

---

If the MicroProfile Rest Client interface is invoked from within a JAX-RS resource class, then it is possible to propagate HTTP headers from the incoming request to the outgoing Rest Client request by specifying the headers to propagate using this MP Config property:
`org.eclipse.microprofile.rest.client.propagateHeaders=Authorization,MyCustomHeader`

It is also possible to specify or generate a header value using annotations like this:
```
@ClientHeaderParam(name="HeaderOrigin", value="MPRestClientInOpenLiberty")
@ClientHeaderParam(name="MyHeader", value="value1")
@Path("/somePath")
public interface MyClient {

    @GET
    @ClientHeaderParam(name="MyHeader", value="{computeValue}")
    MyResponse getSomeResponse();

    default String computeValue() {
        return "value2";
    }
...
```

In this example, the client would send two newly-created HTTP headers when the `getSomeResponse()` method is invoked: 
1)  HeaderOrigin: MPRestClientInOpenLiberty
2) MyHeader: value2

Header values can be computed by surrounding the method name in curly-braces.  The only methods that can be specified to compute a header value are default interface methods in the same client interface or public static methods (which must be fully-qualified).

In the case where the same header is specified at the interface level and the method level, the value specified at the method level is used.  Thus "MyHeader" is set to "value2" rather than "value1".

---

If the `mpFaultTolerance-2.0` feature has been specified, then the functionality of the Rest Client interfaces can be augmented with handy Fault Tolerance APIs, for example:
```
public interface MyFaultTolerantClient {

    @GET
    @Retry(retryOn={WebApplicationException.class}, maxRetries = 3)
    String method1();

    @PUT
    @Timeout(value=3, unit=ChronoUnit.SECONDS)
    boolean method2(MyEntity entity);

    @POST
    @Fallback(fallbackMethod="queueForLater")
    boolean method3(MyEntity entity); 

    default boolean queueForLater(MyEntity entity) {
        return addToRetryQueue(entity);
    }
}
```

In this example, `method1` will retry the request up to three times in the event that a `WebApplicationException` occurs.  The `@Timeout` annotation on `method2` will automatically set the connect and read timeouts for the request to 3 seconds, and if the request takes longer than 3 seconds, the Fault Tolerance implementation will interrupt the request.  Last, if an exception occurs when invoking `method3`, the Fault Tolerance implementation will invoke the `queueForLater` method. 

f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

* [MicroProfile Rest Client 1.2.1 Release Page](https://github.com/eclipse/microprofile-rest-client/releases/tag/1.2.1)
* [Javadocs](
http://download.eclipse.org/microprofile/microprofile-rest-client-1.2.1/apidocs/)
* [Specification document](
http://download.eclipse.org/microprofile/microprofile-rest-client-1.2.1/microprofile-rest-client-1.2.1.html) 
  

g. Attach any images to this work item as .png files.

    N/A

**Comment by andymc12** [comment]
Part of Epic #5941

**Comment by lauracowen** [comment]
Thanks
