### ISSUE TITLE
apiDiscovery-1.0 for open-liberty 

### ISSUE THREAD

**Issue by travatine** [OpenLiberty/open-liberty#6966]
Hi,

Are there plans to provide apiDiscovery-1.0 or openapi-3.0 on z/OS?

If not, is there an alternative method for API discovery?

Thanks

**Comment by NottyCode** [comment]
Open Liberty doesn’t have a z/OS distribution and apiDiscovery-1.0 isn’t a feature in Open Liberty anyway. I think you are asking about WebSphere Liberty which has those feature in the z/OS distribution. Please ask questions about WebSphere Liberty via one of the IBM commercial support channels.

**Comment by travatine** [comment]
"Thanks for your reply. To rephrase my question, with Open Liberty (running on z/OS), how can I do API discovery (i.e. see Swagger annotated REST APIs) if apiDiscovery-1.0 is not available?"
