### ISSUE TITLE
Redirect Scheme and Port Mismatch

### ISSUE THREAD

**Issue by mrsaldana** [OpenLiberty/open-liberty#6987]
There is a possibility of Web Container sending a redirect to a context root with mismatching scheme and ports. For instance, the scheme could read "https" for a default 80 port.

**Comment by c-koell** [comment]
Hi, We are facing the same issue .. thanks for fixing that bug

**Comment by stevekinder-ibm** [comment]
In case someone hits that using Kubernetes, search string:  "Port 80 redirect on https: port".   You can work around this issue in your Ingress, by using regex workaround in your ingress document:

>     ingress.kubernetes.io/proxy-redirect-from: ~*^https?://<<$INGRESS_IP>>(:\d+)?/(.*)$
>     ingress.kubernetes.io/proxy-redirect-to: $scheme://$http_host/$2

replacing "<<$INGRESS_IP>>" string with the dns or IP address of your ingress.
