### ISSUE TITLE
Blog WC-22 MicroProfile OpenAPI 1.1

### ISSUE THREAD

**Issue by arturdzm** [OpenLiberty/open-liberty#7003]
GA

This information will be published in the blog post and used in Alasdair's webcast to announce what’s new in this release.

If the exact information you want give is already in a previous blog post:
a. Provide a link to the post(s), specify exactly which sections are relevant, and any updates required or to make it more interesting.

`https://openliberty.io/blog/2018/05/22/microprofile-openapi-intro.html`

b. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

If not previously published in a blog post, please answer the following questions:

a. Which Liberty feature does it relate to?

i. Human-readable name (eg WebSockets feature)

`MicroProfile OpenAPI 1.1`

ii. Feature name (eg websockets-1.0)

`mpOpenAPI-1.1`

iii. Is this a new feature or is it an update to an existing feature for this release?

`This is a new feature to support MicroProfile OpenAPI 1.1 specification`

iv. Provide the qualified name of all changed feature deliveries to this release? (eg: com.ibm.websphere.appserver.transportSecurity-1.0.esa)

`com.ibm.websphere.appserver.mpOpenAPI-1.1.esa`

b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc

`Developers and administrators`

c. Write a sentence or two that introduces it to someone new to the general technology/concept.

`Enables generation of OpenAPI 3.0 documentation from Java annotations in your JAX-RS REST applications.`

d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)

```The MicroProfile OpenAPI 1.1 specification improves the OpenAPI model interfaces by adding convenience setters, add and remove methods, which make it easier to use to generate documentation or filter the generated document.```

e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.
```
Include the following in the server.xml:
<feature>mpOpenAPI-1.1</feature>

No other configuration is required.
The application documentation will be available at /openapi endpoint
The UI to render and try out REST APIs is available at  openapi/ui endpoint
```
f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

`https://github.com/eclipse/microprofile-open-api/releases/tag/1.1.2`
g. Attach any images to this work item as .png files.

N/A

**Comment by lauracowen** [comment]
Thanks
