### ISSUE TITLE
EclipseLink: Update ASM to 7.0.0 for 2.6_WAS

### ISSUE THREAD

**Issue by dazey3** [OpenLiberty/open-liberty#7004]
This issue will be used to track updating EclipseLink in OpenLiberty for this issue: https://github.com/eclipse-ee4j/eclipselink/pull/398

**Comment by aguibert** [comment]
Note that I'm in the process of upgrading us to ASM 7.1 in this PR: https://github.com/OpenLiberty/open-liberty/pull/7012

May be best to hold off on this for a day or two so we can hop straight to ASM 7.1
