### ISSUE TITLE
JAX-RS resources as a CDI bean needs to support Constructor injection

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#7010]
Apparently, JAX-RS resources with the following code snippet failed to do any constructor injection:
```
@Path("/a")
@RequestScoped
public class ServiceAEndpoint {
	
	
	
	@Inject
	@RestClient
	ServiceBClient serviceB;
	MyBean myBean;
	
	@Inject
	public ServiceAEndpoint(MyBean myBean) {
		this.myBean = myBean;
	}
	@Inject
	@ConfigProperty(name="userName") String username;
	
	@GET
	@Operation(summary="Display the return from calling serviceB", description="calling service B")
	@Retry
	@Metered
	public String callServiceB() {
		//call service b
		return  "hello ccc " + username + "Voxxed Bucharest" + serviceB.hello();
		
	}
	
}
@ApplicationScoped
public class MyBean {
	
	public String sayHello() {
		return "hello";
	}

}

The application stopped working with the instance creation failure. 
```

**Comment by jkoehler22** [comment]
In our testing we may of found a work around.  Add a default ctor:

    public ServiceAEndpoint() {
        // default constructor - should not be used
        this.myBean = null;
    }

**Comment by Emily-Jiang** [comment]
@jkoehler22 you were right. Since this bean is RequestScoped, it needs to be proxied. Hence a non-private no-arg constructor is required. I did not pay much attention to the scope when I was briefed with the problem. I will cancel this defect. Thanks for your investigation!
