### ISSUE TITLE
Java 11 warning about Illegal reflective access by serialFilter

### ISSUE THREAD

**Issue by frowe** [OpenLiberty/open-liberty#7011]
On beta 2019.2.0.0 (wlp-1.0.25.cl190220190222-1311), when started from cmdline with Java 11 (JDK or JRE), I'm seeing:

> WARNING: An illegal reflective access operation has occurred
> 
> WARNING: Illegal reflective access by com.ibm.ws.kernel.instrument.serialfilter.agent.PreMain (file:/Users/frowe/Dev/runtimes/v2019200/bin/tools/ws-serialfilteragent.jar) to field java.lang.reflect.Field.modifiers
> WARNING: Please consider reporting this to the maintainers of com.ibm.ws.kernel.instrument.serialfilter.agent.PreMain
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> WebSphere Application Server Serial Filter Agent is loaded.
> This message appears in neither console or message log.
> 

This warning occurs even with no features enabled.

**Comment by toshiyamamoto** [comment]
This issue has been resolved by PR #7059.

**Comment by toshiyamamoto** [comment]
I confirmed that the issue was resolved. I tested with openjdk full version "11.0.2+9".
