### ISSUE TITLE
Re-enable ignored tests in in com.ibm.ws.logging_test

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#7020]
RTC #252760

Re-enable ignored tests in https://github.com/OpenLiberty/open-liberty/issues/2733

**Comment by ismartspace** [comment]
Re-enabling ignored tests from this PR:
https://github.com/OpenLiberty/open-liberty/commit/db39b6a21d30d0b9131e30d06306bb41f62495bc#diff-d5b5fccc67f3461f7f0d441884265453

https://github.com/OpenLiberty/open-liberty/commit/fb9711691e202320f771a8e51612c0eb90db93b5#diff-5941a4b7aa58e746521b85caab3275c7
