### ISSUE TITLE
Port com.ibm.ws.jaxws.webcontainer_fat to Open-Liberty

### ISSUE THREAD

**Issue by neuwerk** [OpenLiberty/open-liberty#7021]
Currently the jaxws-2.2 fat bucket that tests the Web Container component of the feature is not in Open-Liberty. The com.ibm.ws.jaxws.webcontainer_fat needs to moved over. 

- [x] Move com.ibm.ws.jaxws.webcontainer_fat_lWAS to OL
- [x] Update references and copy-write headers
- [x] Update FAT test apps to be built with the OL test framework
- [x] After delivering the OL com.ibm.ws.jaxws.webcontianer_fat remove com.ibm.ws.jaxws.webcontainer_fat_lWAS from CL

**Comment by WhiteCat22** [comment]
finished deleting from CL
