### ISSUE TITLE
Port com.ibm.ws.jaxws.clientcontainer_fat_lwas into Open-Liberty

### ISSUE THREAD

**Issue by neuwerk** [OpenLiberty/open-liberty#7023]
Currently the jaxws-2.2 fat bucket that tests the Client Container component of the feature is not in Open-Liberty. The com.ibm.ws.jaxws.client_fat needs to moved over. 

Steps to port:

- [ ] Move com.ibm.ws.jaxws.clientcontainer_fat to OL
- [ ] Update references and copy-write headers
- [] Update FAT test apps to be built with the OL test framework
- [ ] After delivering the OL com.ibm.ws.jaxws.ejb_fat remove com.ibm.ws.jaxws.ejb_fat from CL

**Comment by BerksanAtes** [comment]
Duplicate of #7429
