### ISSUE TITLE
trackLoggedOutSSOCookies setting ignored for JWT SSO

### ISSUE THREAD

**Issue by blindenvy** [OpenLiberty/open-liberty#7037]
While using the `jwtSso-1.0` feature with Liberty my team has run into the following error when  doing a lot of testing between browsers:
```
000699fd com.ibm.ws.webcontainer.security.internal.SSOAuthenticator   A CWWKS9126A: Authentication using a JSON Web Token did not succeed because the token was previously logged out.
```
Steps to reproduce:
1) Login to the web application sending the same credentials in two separate browsers (IE. Chrome and Firefox)
2) Logout of the web application in one of the browsers (IE. Chrome)
3) Try and access a protected resource in the non-logged out browser (IE. Firefox)

You will be met with a 401 because the JWT you sent with the request was in the LoggedOutTokenCache. Authentication is denied in this instance (rightfully so) but the offending JWT cookie is not being requested to be cleared in the response from the server.

In reviewing the code for `SSOAuthenticator.java` I've come to the determination that it does NOT take into consideration the `trackLoggedOutSSOCookies` property under the `webAppSecurity` configuration element. I believe that this setting should not only work with LTPA SSO but also JWT SSO.

**Comment by blindenvy** [comment]
Hey @utle I tested the change you provided. It doesn't seem as any changes were made to honor the `trackLoggedOutSSOCookies` property. It also doesn't appear that the cookie is being cleared when a 401 response is returned under the scenario I outlined above.

**Comment by utle** [comment]
@blindenvy The designed is not to let customer disable the trackLoggedOutSSOcookies for JWT.

**Comment by utle** [comment]
Hi @blindenvy - #7453 is done. Can we close this issue? Thanks.
