### ISSUE TITLE
securityUtility in 19.0.0.3 has no option to create JKS keystore

### ISSUE THREAD

**Issue by ibmssou** [OpenLiberty/open-liberty#7041]
We use the securityUtility tool in our product to create the initial keystore during install time. We use the following command to create the keystore: 

securityUtility createSSLCertificate --server=myServer --password=foobar --validity=3650

In 19.0.0.2, this resulted in a JKS file:
```
./securityUtility createSSLCertificate --server=myServer --password=foobar --validity=3650
	Creating keystore /tmp/WLP19002/wlp/usr/servers/myServer/resources/security/key.jks
```

However, in 19.0.0.3, this results in a .p12 file:
```
./securityUtility createSSLCertificate --server=myServer --password=foobar --validity=3650
	Creating keystore /tmp/WLP19003/wlp/usr/servers/myServer/resources/security/key.p12
```

In talking with our contacts in Liberty development, we were told that while Liberty still supports JKS and PKCS keystore files, the securityUtility will only create .p12 files in 19.0.0.3+, with no option/flag/parameter to specify a JKS format keystore file.

We have tried setting various values in our server.xml to try and force a JKS keystore.  For example, we tried:
```
<keyStore id="defaultKeyStore" password="{xor}Ozo5PiozKw==" type="JKS" location="keyfoo.jks" />
  <sslDefault sslRef="defaultSSLSettings" />
  <ssl id="defaultSSLSettings" keyStoreRef="defaultKeyStore" sslProtocol="SSL_TLSv2" />
```

But this still results in a key.p12 file created.

This causes several problems in our product as parts of our code interact with the keystore file and expect a JKS format.  In addition, it will cause upgrade issues as older versions of our product out in the field are on Liberty versions 17.x, 18.x, and older versions of 19.x.

We think the securityUtility should provide the option to set the keystore type (JKS or PKCS).   This will allow us to use the latest 19.0.0.3+ with relevant security fixes, while giving us time to plan for the appropriate changes in our product to transition to PKCS keystores.

**Comment by emilytee** [comment]
Starting with 19.0.0.5, the securityUtility tool has been enhanced to include the following, allowing for the option of creating a JKS file:

--keyType=keystore type
    [19.0.0.5 and later]Specifies the keystore type to generate. To generate a JKS keystore, specify the --keyType option with the value of JKS. By default, a PKCS12 keystore is generated. However, to explicitly specify the generation of a PKCS12 keystore, specify the --keyType option with the value of PKCS12.

    A PKCS12 keystore has a number of advantages over a JKS keystore. The PKCS12 keystore is more extensible, supports stronger cryptographic algorithms, and is widely adopted. The PKCS12 format is frequently the format that certificate authorities provide when they issue certificates.
