### ISSUE TITLE
WebAuthn support

### ISSUE THREAD

**Issue by giamma** [OpenLiberty/open-liberty#7060]
This is a feature request.

Now that WebAuthn has been released as a w3c standard, OpenLiberty should support WebAuthn-based container-managed authentication.

**Comment by arkarkala** [comment]
We will investigate this and get back when we have an answer.

**Comment by arkarkala** [comment]
We will continue looking at this. It will be a while before a decision is made.

**Comment by jtmulvey** [comment]
This is now in our backlog and being worked under this issue:
https://github.com/OpenLiberty/open-liberty/issues/10104
