### ISSUE TITLE
Wrong server info string

### ISSUE THREAD

**Issue by sebasbaumh** [OpenLiberty/open-liberty#708]
I downloaded the latest [OpenLiberty Runtime](https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2017-09-27_1951/openliberty-17.0.0.3.zip) (version 17.0.0.3)

When I query the server info using [getServerInfo()](https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContext.html#getServerInfo--) in a Servlets doGet method:
```
	OutputStream out = response.getOutputStream();
	ServletContext context = getServletContext();
	out.println("ServerInfo: " + context.getServerInfo());
```
It prints this server info:
`ServerInfo: IBM WebSphere Liberty/${liberty.service.version}`

As you can see the version string is not replaced by the actual version when calling .

**Comment by ewhoch** [comment]
Correct, this should be displaying as OpenLiberty,  similar to the bin\server version command output of "Open Liberty 17.0.0.3 (1.0.18.cl170320171005-2054)..."

**Comment by fritze2** [comment]
There are several occurrences of WLP-ServerName and WLP-ServerVersion headers containing the wrong information. For WLP-ServerName, there are occurrences of "IBM WebSphere Application Server" and "IBM WebSphere Liberty". For WLP-ServerVersion, ${liberty.beta.version} should now be ${libertyBetaVersion}.
