### ISSUE TITLE
Tracing Solution (That Works) Needed For Bundled JARs

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#7131]
In com.ibm.ws.io.smallrye.reactive.streams.operators.1.0
I bundle 
  @${repo;io.smallrye.reactive:smallrye-reactive-streams-operators;1.0.0}

1) This jar's code has inbuilt support for log4j2.
2) I had expected to be able to get the Websphere trace bytecode weaving
to work on bundled .class files as I thought this was done at the bytecode level.
I can find not other example of where this is done to bundled jars. 

Although liberty has many other jars at it's core that we cannot currently
trace ( Weld, Failsafe, (CXF??) etc.) I think going forward, if we are to make increasing use
of shared smallrye jars we should solve this problem. 

My investigation have led me to believe that enabling the ability for a customer
to somehow get a log4j2 file onto the bundles classpath under the guidance of a L2/3
engineer is likely to give a better trace that LIberty bytecode weaving (as this may
produce a ffdc for every exception caught?? and would only trace method entry exit as there is no 'Trivial' support and no
explicit tracing that is in the code). Of course it may be possible to switch both 'on'
at the same time.  

The solutions on the web relate to log4j working for application classes
not for bundled jars. Joe Chacko has mentioned a solution that "Take a look at this to see how the Bundle-Classpath stuff could work: https://osgi.org/specification/osgi.core/7.0.0/framework.module.html#framework.module.bundleclasspath
The downside is that to override what is in the log4j bundle already, the config file needs to be in a jar in a fragment bundle"  but also Take a look at this to see how the Bundle-Classpath stuff could work: https://osgi.org/specification/osgi.core/7.0.0/framework.module.html#framework.module.bundleclasspath
The downside is that to override what is in the log4j bundle already, the config file needs to be in a jar in a fragment bundle.

Perhaps I just need to locate a working example/wiki page. 

Additionally I have an unresolved problem (that I need to resolve first to remove the FUD)
in XML parsing of (any) working log4j2 file I put on the classpath as descibed here:
https://github.com/OpenLiberty/open-liberty/pull/7130/files#r272093065

**Comment by jhanders34** [comment]
I noticed in your bnd.bnd that you had `instrument.disabled: true` specified.  With that not being set, do you get the instrumentation of the byte code to do the logging that you want?  Or are you trying to get integration of existing trace from the com.ibm.ws.io.smallrye.reactive.streams.operators.1.0 classes?

**Comment by hutchig** [comment]
Agh - yes I had spotted that too and had not pushed up the change. Sorry.

**Comment by hutchig** [comment]
With that line deleted and the other code changes in the PR I DO NOT get any tracing of classes in io.smallrye.

**Comment by NottyCode** [comment]
Current expectation is if you integrate things like slf4j with java util logging then you can use Liberty trace config to get trace e.g.:

```
<logging traceSpecification="package.using.slf4j.*=all"/>
```

**Comment by hutchig** [comment]
Understood. Closing.
