### ISSUE TITLE
Document that Message Endpoints are Pauseable Components 

### ISSUE THREAD

**Issue by alexsm82** [OpenLiberty/open-liberty#715]
With the work for this story, MDB message endpoints will be added as components that can be paused.  The associated documentation should be updated to include MDB message endpoints.

Add doc to describe the expected experience of messaging clients and MDBs when a messaging endpoint is paused. A similar page exists for WebSphere traditional here: https://www.ibm.com/support/knowledgecenter/en/SSAW57_8.5.5/com.ibm.websphere.nd.doc/ae/tdat_msgendpoint.html

**Comment by bcpswope** [comment]
ID does not have documentation on Open Liberty at this time. We are using the ID required currently for guide reviews. Can you tell me what ID is required here?
