### ISSUE TITLE
Kafka Library Jar Packaging: Vanilla Bundlize or MongoDB pattern or JSF pattern or client supplied etc.

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#7177]
There is a question of a Kafka client API jar being updated reasonably often
and also users may wish to 'mix' native client API use and use of the 
MicroProfile reactive messaging feature.

In discussion as part of the cross language/framework IBM Event Model working group Chris Bailey raised the topic of 'mixing' applications:

1 -  'Traditional' Kafka client applications running in Liberty
2 - MP Reactive Messaging applications running in Liberty
3 - 'Traditional' Kafka client applications running natively as JBM processes.

a - in the same server process
b - in the same consumer group
c - sharing the same 'at least once' delivery fulfillment.

By default we do not expose any API's used on implementation classes (for example the RxJava API's are used in implementation and can ve used in Unit Tests but are not exposed or usable by FATS). 

The issue is related to the implementation technology (i.e. should we use an intermediate dependancy that itself consumes the Confluent Kafka client JAR), the packaging format, and what is left on the classpath.

**Comment by Emily-Jiang** [comment]
I don't think we should expose Kafka APIs. One of the benefit of introducing MP Reactive Messaging is to hide the low-level Kafka APIs or other messaging provider APIs.

**Comment by hutchig** [comment]
This was discussed on a design issues call.
The approaches discussed were: 

1. 'standard' bundlization of the Confluent client jar (no classes left on application classpath)
2. the mongodb approach (more details below)
3. the JSF approach (more details below)
4. mandatory provision of the client jar by the user (in their app or as a lib)

Alasdair recommendation was to have a good look at how JSF do it. 

Action - investigate and understand the above approaches and recommend one
(if not recommending same approach as JSK - construct a well reasoned arguement why not)

**Comment by hutchig** [comment]
https://www.ibm.com/support/knowledgecenter/en/SSAW57_8.5.5/com.ibm.websphere.nd.multiplatform.doc/ae/tweb_jsf.html
"Use this task to specify which JavaServer Faces implementation to use. You can use Apache MyFaces 2.0 or the Sun Reference Implementation 1.2 of JSF, **or your own implementation.**

**Comment by hutchig** [comment]
(Liberty) https://www.ibm.com/developerworks/community/blogs/devTips/entry/Using_a_Custom_JSF_implementation_with_WebSphere_Liberty_Profile?lang=en
"how to use custom JSF implementation with IBM WebSphere(WAS) Liberty Profile "

**Comment by hutchig** [comment]
So the default strawman would be to bundle a Confluent client API (perhaps as a dependancy to a Reactive third party layer (Vertex/Lightbend/Reactor) to be considered alongside implementing/forking our own reactive layer (probably look at putting that into smallrye project). With the ability for a user to refresh/replace the Kafka client library (with the hope the server implementation can use the replacement) whence they would have access to that libraries classes
on their app classpath.

**Comment by Emily-Jiang** [comment]
Two possible options:
1. Not to package Kafka client, customers bring their own Kafka client
2. Liberty package a version of Kafka client, customers can override it with their packaged version of Kafka client

**Comment by hutchig** [comment]
Here is a transcript of a further conversation I had with Alasdair (@tevans78 @Azquelt FYI) on Friday

Alasdair Nottingham [4:59 PM]
hi

Gordon Hutchison [4:59 PM]
Hi

Alasdair Nottingham [5:00 PM]
so if you can pick up the kafka library from the application I think for 90% of people that will be easier than a booster

Gordon Hutchison [5:00 PM]
I am just researching DEVEXP-15 part for Cloudant as that allows that.
I agree.
so we will aim for that on our side.

Alasdair Nottingham [5:01 PM]
cool, so the reason I was erring away from doing this booster one is if you can make that happen I’d probably put this quite low.
If you can’t get that to work then it would go higher
but I have a strong desire this be very low because I think app packaging is a better approach for your use case

Gordon Hutchison [5:02 PM]
‘investigating’ as we don’t have a separate interface from the impl classes for the Kafka client but need to perform OK.
If we get to fairly vanilla app packaging - the need for a boost help is very low - we just need to work out how to make use of the jar’s classes from the server in a performing way that has simple config.

Alasdair Nottingham [5:07 PM]
You could look at what the JSFContainer feature does

Gordon Hutchison [5:08 PM]
Yeagh - you gave me that link before and I am and also https://github.ibm.com/was-liberty/ws-cd-open/issues/6256
(just about to chat to Nathan)

Alasdair Nottingham [5:08 PM]
I don’t know how Cloudant works, but it may be similar.

Gordon Hutchison [5:09 PM]
Andy G. mentioned:  - jsfContainer
- jpaContianer
- jsonbContainer
- jsonpContainer

Alasdair Nottingham [5:09 PM]
Jsf container has to see app classes and runtime classes that aren’t external

Gordon Hutchison [5:10 PM]
‘external’ meaning things they could have pre-knowledge of?

Alasdair Nottingham [5:10 PM]
So we have a jar that makes static calls to Kafka, and instead of it being bundle loaded we create a classloader that has the app classloader as a parent and side peeks into the message streams runtime so it can see both and this integration jar.

Gordon Hutchison [5:11 PM]
Yes - we plan to hack up this chain of possible approaches….:  #7812 - #7816
from MVP to better and better…

Alasdair Nottingham [5:12 PM]
the custom classloader means if this special integration jar we create needs to see stuff internal to Liberty we don’t have to expose that into the application classspace.

Gordon Hutchison [5:12 PM]
#agile

Alasdair Nottingham [5:12 PM]
which is really important

Gordon Hutchison [5:13 PM]
OK - noted

Alasdair Nottingham [5:14 PM]
so are you happy that we can defer prioritization on that feature and you have a path forward that can potentially do what you and Mr Schofield agreed was vital?

Gordon Hutchison [5:15 PM]
Yes.

Alasdair Nottingham [5:15 PM]
good
I was worried you might think I was uncaring about the problem you are trying to solve

Gordon Hutchison [5:16 PM]
Schofield was a ‘nice to have’. I said we got a lot of revenue by being a site for MQ apps and how could we be the best place for EventStreams apps - it only moves the ‘easiness’ needle a bit and we can do the same thing with docs.
No fine.  You care. I know.

Gordon Hutchison [5:39 PM]
Do you know if anyone has used techniques like these: https://dzone.com/articles/java-reflection-but-faster ?
dzone.com
Java Reflection, but Faster - DZone Java
In this post, we explore a faster way to read a getter from a Java class without knowing the class at compilation time, using Reflection and MethodHandles.
(no need to answer - thanks for you time o&o)

Alasdair Nottingham [5:42 PM]
do you mean in Liberty, or in general?
I know method handles are slow
sadly OpenJ9 is even slower than Hotspot
the interesting thing is that Java Reflection (despite being a significant component during startup) does not factor in as significant in our startup profiles

Gordon Hutchison [5:55 PM]
I meant going faster than reflecting and in the Liberty server. I just spoke to Nathan re the DEVEXP-15 work and he did a) have an interface and b) used reflection but a lot of the calls go straight from the app to the client jar so no performance issue in jdbc/Cloudant libs being accessed using reflection from server code (edited) 


Alasdair Nottingham [5:56 PM]
So I have raised reflection questions with the perf team quite a bit, but static compiling for our use case appears expensive for not much benefit (at least as far as server startup).
although the LambdaMetafactory “hack” looks interesting. (edited) 
I don’t think you need to have a reflection hit in your case even if the calls are mediated by you
and you don’t need to do bytecode generation either
dump an interface in your jar file. Have your code call kafka via that interface. Provide a direct, non reflection implementation but put it in a jar file.

Gordon Hutchison [5:58 PM]
Well it might be 6th in our MVP to ideal staircase :-)

Alasdair Nottingham [5:58 PM]
then create a classloader that has the app classloader as a parent, and your bundle classloader as a side lookup
and then it works with no reflection other than the initial bootstrap into the static jar which is a 1 time cost to load the class

Gordon Hutchison [5:59 PM]
Ok I will write that approach up as an issue and we will attack it - thanks and have a good weekend

Alasdair Nottingham [6:00 PM]
you too

**Comment by hutchig** [comment]
I think our direction is clear now (aiming for 7828 with chunks on the way) so this can be closed.
We will reopen some subset of it if we get stuck or need guidance. Thank you Alasdair
