### ISSUE TITLE
Should we reduce the potential for behavior changes from env var lookups

### ISSUE THREAD

**Issue by brenthdaniel** [OpenLiberty/open-liberty#7233]
Performance testing ran into an issue because they have a couple of systems that specify an environment variable named ID. Prior to 19.0.0.3, the variable ${id} in a metatype default value would resolve to the ID value from the configuration, but now it will resolve to the environment variable. In this particular case, it prevented the messaging engine from starting. 

We accepted that there could be potential behavior changes as a result of the changes around environment variables, but I'm wondering if we can reduce the likelihood of problems. 

One option would be to handle this specific case by changing ${id} variables in metatype defaults to something else. eg, something like:
`default="(|(service.pid=${sslOptionsRef})(&amp;(service.factoryPid=com.ibm.ws.sslchannel.options)(|(id=com.ibm.ws.messaging.comms.server-${id}/*)(id=defaultSSLOptions))))"` could be changed to use something like `${attribute.ID}` which would indicate that we are only looking for values from the configuration element and not from the environment or other variables. If there are other cases where we're only looking for a config attribute value we could do the same for them.

**Comment by jhanders34** [comment]
The other thing we discussed is to only honor the environment variable if it is a variable that is specified in the server.xml or its imported configuration and not to use environment variables to default configuration information.  With that we would be saying that customers should not be able to override internal config with an environment variable.

**Comment by jhanders34** [comment]
Brent it sounds like you are saying id is specified somehow that possibly should take precedence over an environment variable?  You mentioned looking for values in the configuration element.  Wouldn't those take precedence over an environment variable?

**Comment by brenthdaniel** [comment]
1) I don't think a solution that changes the order of resolution specifically for metatype default values is workable. At a minimum it would require a lot of work to the config runtime. I'm not sure I would agree with it in principle even if it were easy, though -- I think it would be weird to treat default values and configured values differently.  

2) I don't think we should change the order of resolution in general, though that is a possibility to consider. I think we would be less likely to run into unintended collisions that way, but we would be introducing another potential breaking change. Historically,defined variables have always taken precedence over config attributes. As part of this feature work we agreed the new order would be Defined variables, environment variables, config attributes, and the variable default values.

**Comment by NottyCode** [comment]
In 19.0.0.3 this xml snippet:

    <dataSource id="DS" jndiName="jdbc/${id}" />

resolves a jndiName to jdbc/DS if no env var is defined and jdbc/<value of id from env> if it is set in env. This is an issue since the application is likely using jdbc/DS as its value without config variable substitution which doesn't work in DD or `@Resource(lookup="jdbc/DS")`.

In addition metatype often makes use of ${id} syntax referencing a variable so if you have an env var of id it can break in other non-obvious ways.

Proposal is to resolve config attributes before the environment variables thus restoring the old compatible behaviour. So order now becomes:

Defined variables, config attributes, environment variables, and the variable default values.
