### ISSUE TITLE
GA BLOG: Support for Oracle UCP

### ISSUE THREAD

**Issue by alexsm82** [OpenLiberty/open-liberty#7261]

**Comment by lauracowen** [comment]
@alexsm82 Instead of completing the questionnaire from here: https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/Wde4b45b770c2_47cd_9d6d_7061f359add9/page/Blog%20Questionnairs , I can use the info from the docs issue here: https://app.zenhub.com/workspaces/docs-5c7031f61d4580192beb4070/issues/openliberty/docs/192

**Comment by alexsm82** [comment]
Link to the beta blog: https://openliberty.io/blog/2019/03/01/sharding-keys-jdbc43-19002.html, Section: Support for Oracle Universal Connection Pool (UCP) (JDBC 4.x)
Updates:
The first sentence of the second paragraph should be changed to: Using Oracle UCP is now supported with Liberty in the 19.0.0.4. 
The code following “And add a datasource using the new properties.oracle.ucp element:” should be changed to:
<dataSource id="DefaultDataSource" jndiName="jdbc/oracleUCP">
    <jdbcDriver libraryRef="OracleUCPLib" />
    <properties.oracle.ucp URL="jdbc:oracle:thin:@//localhost:1521/SAMPLEDB" user="user" password="pwd"/>
</dataSource>

Change the final paragraph to something more along the lines of (starting with “Add any desired config”) to:
Since the Liberty connection pool is disabled, some of the Open Liberty datasource and connection manager configuration values are ignored and overridden. The following connection manager properties cannot be used with Oracle UCP: agedTimeout, connectionTimeout, maxIdleTime, maxPoolSize, minPoolSize, purgePolicy, reapTime, maxConnectionsPerThread, 
 and maxConnectionsPerThreadLocal.

Additionally, the datasource properties statementCacheSize and validationTimeout cannot be used when using UCP with Open Liberty, as Open Liberty's statement caching and connection validation are disabled.

For most of those datasource and connection manager properties, Oracle UCP provides equivalent functionality. See Oracle's documentation for more details and note that some default property values differ between Open Liberty's connection manager and Oracle UCP. The Oracle UCP properties (such as maxPoolSize or fastConnectionFailoverEnabled) can be applied to the properties.oracle.ucp properties element. Some versions of Oracle UCP require that a username and password are supplied as datasource properties.
