### ISSUE TITLE
Clarifications on "optionalMetrics" attribute

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/open-liberty#7272]
This new attribute should really use an "ENUM" specified in metatype to express the valid values shown in the description - because multiple values are allowed - can be specified as multiple ENUM. - Also add this as an "option" in metatype - and also specify the "default" value "ALL" in the metatype too.  

<usageMetering>
  <optionalMetric>JVM_BLAH</optionalMetric>
</usageMetering>

**Comment by tkburroughs** [comment]
ENUM was not used because stack products may add their own values.  We will not know what the stack product values are, thus cannot provide a complete list.

**Comment by tkburroughs** [comment]
The function and config containing "optionalMetrics" that this issue refers to does not exist in open-liberty.
Moving the issue to internal tracking for WebSphere Liberty only features : GHE 17607
