### ISSUE TITLE
Support JaegerTracer 

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#7317]
Prototype different implementation approaches on how to integrate Jaeger into OpenLiberty.

**Comment by fmhwong** [comment]
We have a working prototype on using trace resolver to resolve Jaeger Tracer.  Users just need to define a shared library with the Jaeger jars in server.xml.  Set the required environment variables to point to the Jaeger backend.  mpOT 1.3 will be able to send traces to Jaeger backend and see them in the UI.

@tonyreigns is going to investigate how to integrate the logging (SLF4J) into JUL so that we can see Jaeger log messages.

**Comment by tonyreigns** [comment]
After investigating the Jaeger implementation, I've found that aside from logging the spanID's, there are no additional logs that Jaeger can provide through SLF4J. No configuration is required to log the spanID's from our implementation's side however users will have to add the following to their system environment variables: `JAEGER_REPORTER_LOG_SPANS=true`.

**Comment by fmhwong** [comment]
Moved from tracerresolver approach to creating an adapter.  The adapter gives us more control of the configuration parameters.
