### ISSUE TITLE
Reduce mpOpenTracing Overhead

### ISSUE THREAD

**Issue by jdmcclur** [OpenLiberty/open-liberty#7326]
I see a couple issues where we can reduce the overhead of opentracing.

Case 1: The microprofile-2.x convenience feature is enabled (so mpOpentracing is enabled), but zipkin is NOT installed. Open Liberty attempts to find a tracer on every request.

It looks like JAXRSUtils calls an opentracing filter, that eventually does a initial context lookup (on every request...). It seems like there should be a way to make this faster, or in my case where I have no Tracer, to disable it.
[4/22/19 14:43:49:045 CDT] 0000003a com.ibm.ws.opentracing.OpentracingUserFeatureAccessService   E CWMOT0008E: OpenTracing cannot track JAX-RS requests because an OpentracingTracerFactory class was not provided.
 
It takes 26% of the time looking for a tracer that does not exist.
```
26.92            J:org/apache/cxf/jaxrs/utils/JAXRSUtils.runContainerRequestFilters(Lorg/apache/cxf/jaxrs/provider/ServerProviderFactory;Lorg/apache/cxf/message/Message;ZLjava/util/Set;)Z
26.92            J:com/ibm/ws/opentracing/OpentracingContainerFilter.filter(Ljavax/ws/rs/container/ContainerRequestContext;)V
26.85            J:com/ibm/ws/opentracing/OpentracingTracerManager.getTracer()Lio/opentracing/Tracer;
26.61            J:com/ibm/ws/opentracing/OpentracingUtils.lookupAppName()Ljava/lang/String;
26.10            J:javax/naming/InitialContext.lookup(Ljava/lang/String;)Ljava/lang/Object;
```

Case 2: Zipkin is enabled, but the JAX-RS endpoint has Trace(false) 

I see 9.42% overhead.

``` 
  Parent      0   0.07   9.42           4         574    J:org/apache/cxf/jaxrs/utils/JAXRSUtils.runContainerRequestFilters(Lorg/apache/cxf/jaxrs/provider/ServerProviderFactory;Lorg/apache/cxf/message/Message;ZLjava/util/Set;)Z
 
    Self      0   0.07   9.42           4         574    J:com/ibm/ws/opentracing/OpentracingContainerFilter.filter(Ljavax/ws/rs/container/ContainerRequestContext;)V
 
   Child      0   0.00   3.82           0         233    J:org/apache/cxf/jaxrs/impl/UriInfoImpl.getRequestUri()Ljava/net/URI;
   Child      0   0.00   1.56           0          95    J:com/ibm/ws/opentracing/zipkin/OpentracingZipkinTracer.extract(Lio/opentracing/propagation/Format;Ljava/lang/Object;)Lio/opentracing/SpanContext;
   Child      0   0.05   1.56           3          95    J:com/ibm/ws/opentracing/OpentracingService.process(Ljava/net/URI;Ljava/lang/String;Lcom/ibm/ws/opentracing/filters/SpanFilterType;)Z
   Child      0   0.00   0.75           0          46    J:java/net/URI.toURL()Ljava/net/URL;
   Child      0   0.00   0.49           0          30    J:org/apache/cxf/jaxrs/impl/ContainerRequestContextImpl.getHeaders()Ljavax/ws/rs/core/MultivaluedMap;
   Child      0   0.00   0.38           0          23    J:com/ibm/ws/microprofile/opentracing/OpenTracingFilterHelper.getBuildSpanName(Ljavax/ws/rs/container/ContainerRequestContext;Ljavax/ws/rs/container/ResourceInfo;)Ljava/lang/String;
   Child      0   0.00   0.25           0          15    J:org/apache/cxf/jaxrs/impl/AbstractPropertiesImpl.setProperty(Ljava/lang/String;Ljava/lang/Object;)V
   Child      0   0.00   0.21           0          13    J:java/net/URL.toString()Ljava/lang/String;
   Child      0   0.02   0.16           1          10    J:org/apache/cxf/jaxrs/impl/ContainerRequestContextImpl.getUriInfo()Ljavax/ws/rs/core/UriInfo;
   Child      0   0.11   0.11           7           7    J:com/ibm/ws/opentracing/OpentracingTracerManager.getTracer()Lio/opentracing/Tracer;
   Child      0   0.00   0.05           0           3    J:org/apache/cxf/jaxrs/impl/UriInfoImpl.getPath()Ljava/lang/String;
```

**Comment by fmhwong** [comment]
PR https://github.com/OpenLiberty/open-liberty/pull/7348 has been opened to address case 1.

**Comment by fmhwong** [comment]
PR #7348 has been merged.

**Comment by fmhwong** [comment]
@jdmcclur Do you have suggestions on case 2?

The biggest one in the stack is `UriInfoImpl.getRequestUri()` which used 3.82%.  However, this is in CXF.

**Comment by jdmcclur** [comment]
Felix, I did look at this briefly, but I did not see any easy fixes, as I had hoped. It seems like you have to go down this path regardless if Traced is true or false, but I don't yet have a great understanding of the code. Improving things here would probably improve both cases (true/false). It does seem like the getRequestUri is taking a long time.

**Comment by fmhwong** [comment]
@jdmcclur Is there anything else you'd like me to try?

**Comment by jdmcclur** [comment]
Felix, no, I think I'll close this issue as we made improvements for case 1, and case 2 does not seem trivial and not high priority. I'll continue to look at it as I have time.
