### ISSUE TITLE
Health Center is not found when using IBM JDK 8.0.5.31

### ISSUE THREAD

**Issue by bpaskin-ibm** [OpenLiberty/open-liberty#7344]
When using the IBM JDK 8.0.5.31 with Liberty 19.0.0.3 the health center agent cannot be found (-Xhealthcenter).  The following message is produced:

`[25/04/19 11:37:05:781 EDT] 0001d36d com.ibm.ws.health.center.classloader.HCClassLoader           W TRAS4352W: Health Center agent was not found, so JVM monitoring and diagnostic information will not be available`

Brian

**Comment by NottyCode** [comment]
This message does not exist in Open Liberty
