### ISSUE TITLE
Open Liberty server debug issue

### ISSUE THREAD

**Issue by ikos23** [OpenLiberty/open-liberty#7346]
**Prerequisites:**
This is what I am trying to run in Docker container:
```
Launching defaultServer (Open Liberty 19.0.0.2/wlp-1.0.25.cl190220190222-1311) on Eclipse OpenJ9 VM, version 11.0.2+9 (en_US)
```
I want to run the server in debug mode and when I can see this line in logs
`Listening for transport dt_socket at address: 7777` I try to connect from my IDEA but getting error:
> Error running 'DEBUG': Unable to open debugger port (sand025:7777): java.net.ConnectException "Connection refused: connect"

`sand025` is a host where my Docker lives.  

**I managed to fix this issue by adding env variable to my docker container: `WLP_DEBUG_ADDRESS=0.0.0.0:7777`.**

I did that after I found this  code snipped on [GitHub](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server):
```
if [ "${ACTION}" = "debug" ]
      then
        if [ -z "${WLP_DEBUG_ADDRESS}" ]
        then
          WLP_DEBUG_ADDRESS=7777
        fi
        if [ -z "${WLP_DEBUG_SUSPEND}" ]
        then
          WLP_DEBUG_SUSPEND=y
        fi
        JAVA_DEBUG="-Dwas.debug.mode=true -Dcom.ibm.websphere.ras.inject.at.transform=true -Dsun.reflect.noInflation=true -agentlib:jdwp=transport=dt_socket,server=y,suspend=${WLP_DEBUG_SUSPEND},address=${WLP_DEBUG_ADDRESS}"
      fi

....
```
It looks weird for me that `address=${WLP_DEBUG_ADDRESS}"` will contain only port 7777 because of a few lines above.

If you only set the port to that variable, shouldn't it be `address*=${WLP_DEBUG_ADDRESS}"` or something like that?

There is a chance all this stuff does not make any sense (I am not that smart :) ), then just close the issue or update documentation please to make it more clear what is needed to be able to debug :)

**Comment by covener** [comment]
address=7777 is valid but on my linux system it results in listening on localhost:7777 only which conflicts with oracle docs AFAICT.

https://docs.oracle.com/javase/8/docs/technotes/guides/jpda/conninv.html

**Comment by ikos23** [comment]
If this helps me `WLP_DEBUG_ADDRESS=0.0.0.0:7777`, does it mean there is a chance it doesn't result in localhost:7777, because telnet also fails for me for that port (7777) without my fix.

**Comment by arthurdm** [comment]
HI @ikos23 - thanks for reporting this.

Things worked fine for us when we started the container like this:  `docker run --name wlpDebug -p 7777:7777 -d open-liberty server debug defaultServer`

Here's the output of `docker ps`:
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                        NAMES
1b64869a4ccc        open-liberty        "/opt/ol/helpers/run…"   9 seconds ago       Up 8 seconds        9080/tcp, 0.0.0.0:7777->7777/tcp, 9443/tcp   wlpDebug
```

As you can see we didn't have to override the `WLP_DEBUG_ADDRESS` environment variable, so we got the default `0.0.0.0:7777` mapping.

**Comment by ikos23** [comment]
I guess this issue can be closed. There must be something wrong in my setup, something I am missing :) 
Anyway the weird hack works (even though I can't explain why) so I am able to debug.

**Comment by tevans78** [comment]
@ikos23 Sounds like you at least have a workaround so I am closing this issue. If you encounter any further problems or you just have some enhancement suggestions, please feel free to open further issues. Thank you.
