### ISSUE TITLE
Unable to login to /IBMJMXConnectorREST/api if a HttpAuthenticationMechanism is used

### ISSUE THREAD

**Issue by c-koell** [OpenLiberty/open-liberty#7424]
We are using a HttpAuthenticationMechanism.
There we axtract some custom headers an create a valid UserPrincipal with some specific groups in it. We have tried to enable the restConnector-2.0 Feature to be able to connect via JMX.

A valid username created by the HttpAuthenticationMechanism is as example u0123456@domain.local
I have configured in the server.xml following snippet
`<administrator-role>
		<user>u0123456@domain.local</user>
	</administrator-role>`
I'm unable to connect to https://myhost:9443/IBMJMXConnectorREST/api

I always get Error 403: AuthorizationFailed with following log entry
[AUDIT   ] CWWKS9104A: Die Berechtigung f�r den Benutzer u0123456@domain.local ist beim Aufruf von com.ibm.ws.management.security.resource in /api fehlgeschlagen. Dem Benutzer wurde kein Zugriff auf die erforderlichen Rollen erteilt: [Administrator, Viewer]

If i try with a quickStartSecurity i'm able to login (bob/bobpassword).
`<quickStartSecurity userName="bob" userPassword="bobpassword" />`

Do i have something misconfigured or is it a bug ?

greets
claus

**Comment by c-koell** [comment]
Hi !

Could someone verify that?

Greets

**Comment by c-koell** [comment]
Is it a must to have a userregistry configured to login to the ibm api / restConnector ?
It would be great to get some feedback here .... thanks

**Comment by teddyjtorres** [comment]
Per the JSR-375 specification, the HttpAuthenticationMechanism is used by the application that contains it. The mechanisms in one app cannot be used for another. That means that they cannot be used for the rest connector endpoint.

**Comment by teddyjtorres** [comment]
At the moment, this is working as designed per the specification.
