### ISSUE TITLE
Open liberty should support other logging framework

### ISSUE THREAD

**Issue by argenstijn** [OpenLiberty/open-liberty#7439]
Could you please add support for open liberty to support another logging framework than JUL. For example slf4j.

**Comment by donbourne** [comment]
People do use SLF4J with Liberty today (with the JUL bridge), but are you asking for ability for Liberty traceSpecification to control SLF4J loggers, or did you have something else in mind?

**Comment by tevans78** [comment]
There isn't really enough detail here for us to actually do anything. Closing for now.
