### ISSUE TITLE
CDI 2.0: Ensure all appropriate cdi 2.0 packages are exposed in OpenLiberty

### ISSUE THREAD

**Issue by neilgsyoung** [OpenLiberty/open-liberty#744]
List all the packages in the cdi 2.0 jar and ensure that they are exposed in OL. N.B. Not .se
During testing I found that javax.enterprise.inject.literal and javax.enterprise.inject.spi.configurator were not fully exposed (missing from the com.ibm.websphere.appserver.cdi-2.0.feature file)

**Comment by tevans78** [comment]
I re-checked the CDI 2.0 API and the new packages are:
```
javax.enterprise.context.control
javax.enterprise.inject.literal
javax.enterprise.inject.se
javax.enterprise.inject.spi.configurator
```
We are not going to expose `javax.enterprise.inject.se` but the other three should be

**Comment by tevans78** [comment]
This is done
