### ISSUE TITLE
[19.0.0.7] Test mpOpenTracing with MicroProfile 3.0

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#7480]
MicroProfile 3.0 has mpRestClient version bumped to 1.3.  We need to test and see if mpOpenTracing 1.3 is able to tolerate mpRestClient 1.3.

DCUT for 19.0.0.7 is 6/26/2019.

**Comment by tonyreigns** [comment]
We've tested out the compatibility between mpRestClient.1.3 and OT.1.3 by following the Openliberty.io guide and ensuring that all spans were created properly. We also had to make a minor change to the auto feature to ensure that the osgi bundle was being started.
