### ISSUE TITLE
Update com.ibm.ws.org.osgi.annotation.versioning to use 1.1

### ISSUE THREAD

**Issue by Channyboy** [OpenLiberty/open-liberty#7523]
Currently, `com.ibm.ws.org.osgi.annotation.versioning` sources `org.osgi.annotation.versioning` 1.0.
This should be updated to `org.osgi.annotation.versioning` 1.1.

For example:
Microprofile projects leverage the use of the `@ProviderType` annotation on packages.
An annotation target that is not provided in 1.0 but rather 1.1

**Comment by dazavala** [comment]
Verified merged into master.
