### ISSUE TITLE
Merge config enterpriseApplication element in server.xml

### ISSUE THREAD

**Issue by 2ppisaHcl** [OpenLiberty/open-liberty#7535]
I'm trying with no success to merge an **enterpriseApplication** configured in server.xml with the one xml file in configDropins/overrides, such that:

```
<!-- server.xml -->
<server>	
   <enterpriseApplication id="A" location="A.ear" name="A">
            <classloader ...../>
            <ejb-jar-bnd..../>
            <web-bnd..../> 
     </enterpriseApplication> 
 </server>
```

```
<!-- configDropins/overrides/roles.xml -->
<server>	
   <enterpriseApplication id="A">
       <application-bnd>
        	<security-role name="R1">
        		<special-subject type="ALL_AUTHENTICATED_USERS"/>
                 </security-role>
 	          <security-role name="R2">
        		<group name="groupR2">
                 </security-role>
        </application-bnd>
    </enterpriseApplication>
 </server>
```

expecting as merged result an element like this one:

```
<server>	
   <enterpriseApplication id="A" location="A.ear" name="A">
          <!-- from server.xml -->  
          <classloader ...../>
            <ejb-jar-bnd..../>
            <web-bnd..../> 
      <!-- from roles.xml -->
       <application-bnd>
        	<security-role name="R1">
        		<special-subject type="ALL_AUTHENTICATED_USERS"/>
                 </security-role>
 	          <security-role name="R2">
        		<group name="groupR2">
                 </security-role>
        </application-bnd>
   </enterpriseApplication> 
 </server>
```

Is some limitation about this kind merge operation? Are there other ways to meet the same goal?

**Comment by jhanders34** [comment]
I notice that you reference configDroppins.  Shouldn't the directory name be configDropins?

https://www.ibm.com/support/knowledgecenter/SSD28V_9.0.0/com.ibm.websphere.wlp.core.doc/ae/twlp_setup_dropins.html

**Comment by 2ppisaHcl** [comment]
sorry it is a  typo.  configDropins/overrides

**Comment by brenthdaniel** [comment]
Hi, 

The two configurations you listed would be merged together into exactly the result that you specified. What is the actual problem that you're seeing?

**Comment by 2ppisaHcl** [comment]
Thanks, actually it works. Just the Eclipse's plugin feature seems to be give a wrong view about the merged server.xml version. Is there some logs on server to enable so I could see the in-memory server.xml merged version?

**Comment by brenthdaniel** [comment]
@2ppisaHcl No, unfortunately there isn't a way to get a representation of the merged XML. The closest thing would be the ConfigAdminIntrospection that is produce when running `server dump`, but that is a representation of transformed configuration rather than XML elements. I believe there is a way in the Liberty development tools to see a combined view, but I'm not sure about that.
