### ISSUE TITLE
Beta blog content for PostgreSQL support in 19005

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#7545]
## Support for PostgreSQL

[PostgreSQL](https://www.postgresql.org/) is a very popular open source relational database that has a wide amount of adoption in the community. Now there is a first-class configuration support for using it with Open Liberty.

To use PostgreSQL with Open Liberty, first make sure one of the JDBC features is enabled:
```xml
<featureManager>
    <feature>jdbc-4.2</feature>
    <feature>jndi-1.0</feature> <!-- Required only if JNDI is desired to look up resources -->
</featureManager>
```

Then, configure a DataSource as follows:
```xml
<dataSource jndiName="jdbc/postgresql">
  <jdbcDriver libraryRef="PostgresLib" />
  <properties.postgresql serverName="localhost" portNumber="5432" databaseName="SAMPLEDB" 
                         user="bob" password="secret"/>
</dataSource>

<library id="PostgresLib">
    <fileset dir="${server.config.dir}/jdbc"/>
</library>
```

The JDBC driver for PostgreSQL can be obtained on Maven Central here: https://mvnrepository.com/artifact/org.postgresql/postgresql
The Postgres Docker images can be found here: https://hub.docker.com/_/postgres
More information about PostgreSQL can be found at https://www.postgresql.org/

**Comment by lauracowen** [comment]
Thanks, Andy!
