### ISSUE TITLE
Beta blog content for REST-based test connection service 

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/open-liberty#7546]
Please complete the questionnaire (see https://github.ibm.com/was-liberty/WS-CD-Open/wiki/Creating-Stories-and-Features).

**Comment by lauracowen** [comment]
@nmittles Are you also planning on updating this old WASdev article too (you mention it in #6509 now not being complete?): https://developer.ibm.com/wasdev/blog/2017/04/19/testing-database-connections/ If so, can you make sure it's suitable for Open Liberty (not WebSphere Liberty) and we can republish it as a new post on the OL.io blog (and redirect the old WASdev one to the new OL one)?

The questionnaire info will go in the 19005 release blog post as a summary and then we can link from there to the fuller standalone blog post. Thanks

**Comment by nmittles** [comment]
Summary for 19005 release blog post:


## Testing database connections

How many times have you had to write a server-side test that gets a connection just to check if your configuration is valid and your app can connect to your database? Now by utilizing the REST API provided by the configValidator-1.0 beta feature, you can validate supported elements of your configuration via REST endpoints.

To enable these REST endpoints, add the `configValidator-1.0` beta feature to any server using JDBC, JCA, or JMS technologies.

**Comment by nmittles** [comment]
The old WASdev article is was complete for the beta function we had delivered at the time (~2 years ago).  No updates describing additional function are needed for the WASdev article, but we should update it to link to the new Open Liberty configValidator-1.0 blog post.  As well as stating the validator-1.0 beta feature is being replaced by the configValidator-1.0 beta feature.

**Comment by lauracowen** [comment]
I'll just redirect the WASdev article to the new OL blog post because we're shutting WASdev down anyway and the old beta for WL is no longer available.

**Comment by sercheo87** [comment]
When open url `https://localhost:9443/ibm/api/validation/dataSource/DefaultDataSource` required credentials.

What type credentials is?

**Comment by nmittles** [comment]
@sercheo87 the `ibm/api/validation/*'` endpoints require a user with the `Administrator` authorization role.  See the following Open Liberty test servers for simple examples:
https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.rest.handler.validator_fat/publish/servers/com.ibm.ws.rest.handler.validator.jdbc.fat/server.xml
https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.rest.handler.validator_fat/publish/servers/com.ibm.ws.rest.handler.validator.jca.fat/server.xml
