### ISSUE TITLE
"writeInterval" in httpSessionDatabase configuration is not honored

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/open-liberty#7634]
I tested following configuration with writeInterval set to 1s, 5s and 30s. 
The trace shows the actual writeInterval is 10 secs regardless of the configured value. 

```
    <httpSessionDatabase dataSourceRef="sessionDS"
        useMultiRowSchema="true" writeContents="ONLY_UPDATED_ATTRIBUTES"
        writeFrequency="TIME_BASED_WRITE" writeInterval="1s"/>
```

Following repo has a Docker file and recreation steps 
https://github.com/una-tapa/LibertySessionDBTest

trace
https://github.com/una-tapa/LibertySessionDBTest/blob/master/trace.log

**Comment by zhang-ca** [comment]
This was due to minimum timer is set to 10 secs. 
For less than 10s session writeInterval, we always recommended writeFrequency="End of servlet service".
That is, optimize for failover. For details, please see:
https://www.ibm.com/support/knowledgecenter/SSAW57_8.5.5/com.ibm.websphere.nd.multiplatform.doc/ae/uprs_rtuning_parameters.html

**Comment by zhang-ca** [comment]
"END_OF_SERVLET_SERVICE" writes are more reliable and significant than "TIME_BASED_WRITE" even with write interval is 1 sec.

**Comment by una-tapa** [comment]
@zhang-ca  
Thanks for looking so promptly.  We actually recommended "END_OF_SERVLET_SERVICE" of course.   It did not work for them because the end of servlet performance was not acceptable.  They would like to keep saving whatever is updated, to keep the performance stable.

**Comment by una-tapa** [comment]
- The doc says "positive integer" for the writeInterval, that means 1s.  It is misleading if we know the minimum timer interval is 10 secs. 
- Whatever the value I set for the writeInterva,  (30 sec for example)  the write timer in the trace looks 10 sec still ..

**Comment by zhang-ca** [comment]
The write timer is not the same as session writeInterval. The timer always run every 10 sec. Session write based on writeInterval but can not be less time than the timer (10 sec.)

**Comment by zhang-ca** [comment]
com.ibm.ws.session.SessionContext.createStorer() : 

        if (smc.getEnableTimeBasedWrite()) {
            storer = new TBWSessionStorer(store, 10); // 10 seconds is fixed - not configurable

The write timer is not configurable at this time, setting to 1 sec would definitely affect the server performance.

**Comment by una-tapa** [comment]
How are  "write timer" and "writeInterval" are different.  ?  
If writeInterval=600s (5 mins),  will Liberty still write every 10 seconds because write time runs on fixed value?  If so, it would be performance concern.  

I had a chance to check with WAS performance expert.  He said 1 sec is OK if machine spec is good and database performance is good too. 

Following KC doc says writeInterval supports positive integer (Bold)  Is this a doc defect? 

https://www.ibm.com/support/knowledgecenter/en/SSAW57_liberty/com.ibm.websphere.liberty.autogen.nd.doc/ae/rwlp_config_httpSessionDatabase.html

writeInterval | A period of time with second precision | 2m | Number of seconds that should pass before writing session data to the persistent store. The default is 120 seconds. This value is only used when a time based write frequency is enabled. **Specify a positive integer followed by a unit of time,** which can be hours (h), minutes (m), or seconds (s). For example, specify 30 seconds as 30s. You can include multiple values in a single entry. For example, 1m30s is equivalent to 90 seconds

**Comment by zhang-ca** [comment]
The "write timer" doesn't do any write, it schedule the server to **check** every 10 second.
The actual session write is done by "writeInterval".
