### ISSUE TITLE
JPA Container feature description needs improvements

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#7683]
Someone in IBM emailed me to observe that the description for the JPA Container feature has some issues. It is currently:

    This feature enables support for applications that use application-managedand 
    container-managed JPA written to the Java Persistence API 2.2 specification. This 
    only includes Java Persistence API 2.2 specification interfaces, and 
    container-managedJPA integration. This feature does not include any JPA implementation.

If you look carefully you'll notice that the 1st line ends with two words running together without space, and the last sentence starts in the same way.

They also suggested not ending sentence 1 with `Java Persistence API 2.2 specification` given it is at the start of the next sentence, so they suggest this:

    This feature enables support for applications that use application-managed and 
    container-managed JPA. This only includes Java Persistence API 2.2 specification 
    interfaces, and container-managed JPA integration. This feature does not include 
    any JPA implementation.

They also suggest it should be JPA implementations (plural) rather than JPA implementation. I'm not sure about that though.

**Comment by tkburroughs** [comment]
Merged.. closing
