### ISSUE TITLE
FAT Approval Test Summary for SEC-17 (7496)

### ISSUE THREAD

**Issue by acdemyers** [OpenLiberty/open-liberty#7702]
**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule**.

For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature.

If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

-------------------
SEC-17, https://github.com/OpenLiberty/open-liberty/issues/7496, feature to be able to configure hostname verification on SSL configurations.  Hostname verification is a server identity check performed on they client side of the connection during a SSL handshake.   The client tries to match the hostname used in the URL with a hostname in the server certificate.   The hostname may be found in the Subject Alternative Name(SAN) extension if not there then the SubjectDN of the certificate.

Along with this feature the command line tool createSSLCertificte was updated to create the default certificate with the Subject Alternative Name extension. And a flag was added to allow users to add a custom Subject Alternative Name if desired.

The tests added/modified are in the following projects -

1) HostnameVerificationTest.java in the com.ibm.ws.ssl_fat project.     This contains new tests around hostname verification testing.

2) OutboundSSLLDAPTest.java in com.ibm.ws.security.wim.adapter.ldap_fat.  FAT update do to change in code.

3) MongoSSLInvalidTrustTest.java in com.ibm.ws.mongo_fat. FAT update due to change in code 

4) KeytoolSSLCertificateCreatorTest.java updates to the securityUtility createSSLCertificate option.

_Description of the tests:_

- Configure a ssl configuration to enable hostname verification access a server with a cert containing the proper hostname information and make sure the connection succeeds.

- Configure a client ssl configuration to disable hostname verification and configure server with a certificate without the hostname in the SAN or subjectDN .   Make sure the connection succeeds.  Then flip the client side to enable hostname verification.  Make sure the connections fails and the error shows up in the clients messages log.

- Configure a client ssl configuration to enable hostname verification and configure server with a certificate with the hostname in the SAN extension.   The client accesses the server with the hostname, make sure the connection succeeds.  Then the client access the server using an IP address.  Make sure the connections fails and the error shows up in the clients messages log.

- Configure a client ssl configuration to enable hostname verification and configure server with a certificate with the hostname in the SubjectDN.   Client access the server with the hostname, make sure the connection succeeds.  Then the client access the server using an IP address.  Make sure the connections fails and the error shows up in the clients messages log.

- Configure a client ssl configuration to enable hostname verification and configure server with a certificate with an IP address in the SAN extension.   The client accesses the server with the IP address, make sure the connection succeeds.  Then the client access the server using a hostname.  Make sure the connections fails and the error shows up in the clients messages log.

- Configure a client ssl configuration to enable hostname verification and configure server with a certificate with an IP address in the SubjectDN.   The client accesses the server with the IP address, make sure the connection succeeds.  Then the client access the server using a hostname.  Make sure the connections fails and the error shows up in the clients messages log.

- Test added to verify SAN information is in the certificate by default with out any flag.

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:  4

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

--------------
4) The tests that were added in this feature cover all the golden path and all of the error/outlying scenarios that make sense. Cannot think of any gaps and no manual testing is required.

**Comment by acdemyers** [comment]
Along with this feature the command line tool createSSLCertificte was updated to create the default certificate with the Subject Alternative Name extension.    And a flag was added to allow users to add a custom Subject Alternative Name if desired.


- Test added to verify SAN information is in the certificate by default with out any flag.

- Test added to specify the -ext flag and providing SAN information and make sure the certificate contains it.

**Comment by acdemyers** [comment]
#7496

**Comment by sabolo** [comment]
@acdemyers :  Could you please clarify "KeytoolCommandTest.java, KeytoolSSLCertificateCreatorTest.java, CreateSSLCertificateTask.java in com.ibm.ws.crypto.certificateutil ---> for SecurityUtility code changes.".  com.ibm.ws.crypto.certificateutil  does not seem to exist in the FAT runs so I am hoping its just a miss type.  I checked for the word crypto just in case but still no matches.

**Comment by acdemyers** [comment]
@sabolo The SecurityUtilitiy testing has always been done in com.ibm.ws.crypto.certificateutil_bvt and com.ibm.ws.security.utility_bvt

**Comment by arkarkala** [comment]
The list of tests have been corrected in the summary above.

**Comment by arkarkala** [comment]
@sabolo Can this be verified now - assuming SOE builds are done and no issues wrt to this feature?

**Comment by sabolo** [comment]
We will be getting features checked first thing tomorrow morning.  It’s not ideal as we should have fine today but the entire staging process for the release is broken and that is needing all hands on deck or there will be no release.   Marika has been informed. 

Sent from my iPhone

> On 19 Jun 2019, at 11:11, Ajay Karkala <notifications@github.com> wrote:
> 
> @sabolo Can this be verified now - assuming SOE builds are done and no issues wrt to this feature?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
Unless stated otherwise above:
IBM United Kingdom Limited - Registered in England and Wales with number 741598. 
Registered office: PO Box 41, North Harbour, Portsmouth, Hampshire PO6 3AU

**Comment by dave-waddling** [comment]
**FAT Focal Approval comment:** Apologies for getting to this review, as @sabolo described above we had some issues getting 19.0.0.6 staged for release and our squad was focused on that issue. Now that things have calmed down I've had a chance to fully review this Feature Test Summary and all of the new testing is passing nicely so I've granted the FAT Focal Approval.

**Comment by acdemyers** [comment]
Fat has been approve so closing the summary issue out.
