### ISSUE TITLE
Experiment to identify whether -noverify can be removed

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#7725]
Currently, when starting test servers on Hotspot Java 8, we set the `-noverify` option.

We're not sure if this is needed any more and we suspect it's the cause of some intermittent JVM crashes that we're occasionally seeing in testing.

Investigate whether this option can be removed. It's set in https://github.com/OpenLiberty/open-liberty/blob/bed04c15872424e51c27a7de6513a8d342a7f3d5/dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java#L1218

**Comment by tevans78** [comment]
Removing noverify appears to have been sucessful. Closing this issue.
