### ISSUE TITLE
SVT MicroProfile Reactive Messaging to IBM Cloud Private Event Streams.

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#7739]
This may be able to make use to the test material that the development
team are going to write to test with plain old Apache Kafka.
 
The client jar is supposed to be the same but is provided by the
Event Streams UI:
https://ibm.github.io/event-streams/getting-started/client/

The ideal SVT would be to follow the process as documented
in IBM Event Streams to obtain the client JAR then use the
recommended WAS approach to 'replace' the client jar in the Liberty feature
and check it still works!

**Comment by hutchig** [comment]
https://cloud.ibm.com/docs/services/EventStreams?topic=eventstreams-kafka_using_classic
"Additionally, if you're using the Enterprise plan, you'll also need to use the Server Name Indication (SNI) extension to the TLSv1.2 protocol."
Note *_Server Name Indication_*

**Comment by hutchig** [comment]
This has to include the use of API Keys.

See 
https://www.ibm.com/support/knowledgecenter/en/SSYHZ8_18.0.x/com.ibm.dba.install/topics/tsk_preparing_bai_using_event_streams.html

**Comment by hanczaryk** [comment]
I was able to successfully execute a 3 day stress run where I observed no significant memory growth or exceptions.
