### ISSUE TITLE
Develop Code to Enable Liberty Programmatic/Secret MP Reactive Messaging Kafka Security (not AuthenticateCallbackHandler related)

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#7745]
AuthenticateCallbackHandler - will be done in an other issue.

**Comment by Azquelt** [comment]
#8207 covers enabling a mechanism to provide passwords which have been encoded using `securityUtility`. We're not doing anything further to provide secrets to the connector.
