### ISSUE TITLE
MP Reactive Messaging Kafka Connector TLS 1.2 Support

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#7750]
https://cloud.ibm.com/docs/services/EventStreams?topic=eventstreams-data_security

Cryptographic protocols

    Connections to the Kafka native and REST interfaces must be made using TLS 1.2.

    Connections are restricted to the following strong cipher suites:
        ECDHE-RSA-AES128-GCM-SHA256
        ECDHE-RSA-AES256-GCM-SHA384
        DHE-RSA-AES128-GCM-SHA256
        kEDH+AESGCM
        ECDHE-RSA-AES128-SHA256
        ECDHE-RSA-AES256-SHA384
        DHE-RSA-AES128-SHA256
        DHE-RSA-AES256-SHA256

    To access the Event Streams dashboard, you must use a browser that supports TLS 1.2.

**Comment by hutchig** [comment]
https://cloud.ibm.com/docs/services/EventStreams?topic=eventstreams-kafka_using_classic
"Additionally, if you're using the Enterprise plan, you'll also need to use the Server Name Indication (SNI) extension to the TLSv1.2 protocol."

**Comment by Azquelt** [comment]
I don't think that there's anything that our connector needs to do here. I think these options should be supported by the kafka client out of the box, if it's configured to use TLS.

We have #7751 to write FATs to ensure this scenario works so I'm going to close this issue as there's nothing to do here.
