### ISSUE TITLE
FaultTolerance 2.0 Blog Post

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#7753]
The WAD says there should be a blog post

New stuff in FT 2.0 includes
- Async with CompletionStage
- Execution sequence is more clearly defined

**Comment by Azquelt** [comment]
Joe was working on turning the material I had started into a blog post for this here: https://github.com/Joseph-Cass/blogs/blob/MP-FT-Asynchronous/drafts/Asynchronous-programming-made-resilient-with-MPFT.adoc

**Comment by tevans78** [comment]
Done
