### ISSUE TITLE
SVT MicroProfile Reactive Messaging to Apache Kafka

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#7762]
We plan to test to this as part of our development produced FAT bucket - if we can get the provisioning/binding to Kafka issue sorted out - perhaps using test containers.
See #7741 
...but we can't do the sort of scaling and memory leak testing that SVT can do so
we still need SVT air cover.

**Comment by hanczaryk** [comment]
SVT encountered memory leak issue detailed at https://github.ibm.com/was-liberty/WS-CD-Open/issues/18065

**Comment by hanczaryk** [comment]
I was able to successfully execute a 3 day stress run where I observed no significant memory growth or exceptions.
