### ISSUE TITLE
MicroProfile Reactive Messaging: Kafka IAM {cluster, topic, group, txnid} x {Reader, Writer, Manager}

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#7779]
We want to be able to map from Liberty user/principle management to feed into
Kafka IAM. 

For each cell in the
                      Cluster     Topic      Group
Reader           
Writer
(Manager?) 

We need to suport and test that Liberty ID management can be used to get
the access to a IAM'ed Kafka (and Event Streams) service.

**Comment by hutchig** [comment]
See https://cloud.ibm.com/docs/services/EventStreams?topic=eventstreams-security

**Comment by Azquelt** [comment]
We're not doing any mapping between liberty principles and IBM Cloud IAM roles.

If the user sets up an IAM role, this will create a credential which can be used to access Kafka with the appropriate permissions. This credential can be provided to the RM Kafka connector as a standard username and password.
