### ISSUE TITLE
Packaging prototype 1 - release connector separately

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#7812]
Release the Kafka connector as a separate library that users can include in their app as a dependency

Advantages:
* Fairly easy for the user to include it
* Does not involve shipping a Kafka client jar
* User can use maven dependency management to include a different version of the Kafka client jar which has a compatible API

Disadvantages:
* Connector isn't actually included in the product

**Comment by hutchig** [comment]
Also feeds well into the connector eventually coming from smallrye.

**Comment by Azquelt** [comment]
We no longer plan to do this. Closing the issue.
