### ISSUE TITLE
Packaging prototype 2 - ship kafka client jar in a feature

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#7813]
Ship the kafka connector and the kafka client jar and all dependencies in a feature

This follows on naturally from prototype 1 #7812

Advantages:
* Connecting to kafka works out of the box if the user includes the feature

Disadvantages
* Need to either expose Kafka APIs, or invent our own API to communicate messages to the user's app
* We ship a specific version of the kafka client with liberty which the user can't update

**Comment by tevans78** [comment]
We're not going to do this right now. Closing.
