### ISSUE TITLE
Packaging prototype 3 - Access kafka client reflectively

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#7814]
Ship the kafka connector as part of a liberty feature but modify it to access the kafka client classes reflectively

The kafka client could be included in the user's app or in a shared library

This is similar to the approach taken by the mongodb feature

As part of this, we would need to determine whether a connector can create a publisher of messages without knowing the type of the payload of the message.

I.e. can we declare `PublisherBuilder<? extends Message> getPublisherBuilder(Config config);` in our connector and return a stream of `Message<ConsumerRecord<String, String>>` and have those messages fed into a method declared by the user `void processRecord(ConsumerRecord<String, String>)`?

If we can't do this, then we will need to create our own API interfaces to communicate the information included in a `ConsumerRecord`.

This task follows on from (1) #7812 and has some overlap with (2) #7813

Advantages:
* Allows us to include the kafka connector in the product but have the user provide the kafka client jar and dependencies

Disadvantages:
* All access to the kafka client is done through reflection which may have a performance impact
* We would need to write reflection or dynamic proxy code to access the kafka client classes

**Comment by tevans78** [comment]
Not going to do this, closing.
