### ISSUE TITLE
Packaging prototype 4 - ship the kafka connector but avoid reflection with classloader magic

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#7815]
Include the kafka connector in a liberty feature but have the kafka client jar included in the user's app or in a shared library.

Do some magic to load the connector classes through a classloader which can see the kafka client classes and have them picked up as CDI beans which are visible to the reactive streams implementation.

This follows on from (1) #7812 and has some overlap with (2) #7813.

Advantages:
* Allows us to include the kafka connector in the product without including the kafka client jar
* Avoids using reflection

Disadvantages:
* Requires classloader magic which may be impossible or merely very complex

**Comment by tevans78** [comment]
Not going to do this. Closing.
