### ISSUE TITLE
Packaging prototype 5 - shade some interfaces and data classes from the kafka client jar

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#7816]
Include the kafka connectors in a liberty feature, along with a select set of interfaces and small data classes from the kafka client jar. Expose the kafka client interfaces as API, so that they're shared between the kafka connector and the application code.

Have the kafka client jar included in the user's app or in a shared library.

Modify the kafka connectors to use only the included kafka client interfaces and data classes and to load the main kafka classes using reflection.

This follows on from prototype (1) #7812 and has some overlap with (2) #7813

Advantages:
* Allows us to include the kafka connectors in liberty without including the kafka client jar
* Avoids reflection on main code paths

Disadvantages:
* Requires us to pull apart the kafka client jar and to expose some of it as API to applications
* Risk of breakage if newer versions of the Kafka client add new methods to those interfaces and the user's code expects to be able to call them
* Will break horribly if parentLast classloading is used

**Comment by hutchig** [comment]
There is an additional defect in this set: https://github.com/OpenLiberty/open-liberty/issues/7828
based on discussion with Alasdair.

**Comment by tevans78** [comment]
Not going to do this
