### ISSUE TITLE
Packaging prototype 6 (AN)  - Provide a shim implementation in a jar/classpath

### ISSUE THREAD

**Issue by hutchig** [OpenLiberty/open-liberty#7828]
This issue is a recording of an approach discussed with Alasdair
(as best as I can - I may have miscaught some of his vision - in
which case he can correct me.)

Here are all the relevant snippets from the conversation with Alasdair:
```
"pick up the kafka library from the application"
"app packaging is a better approach for your use case"

"a jar that makes static calls to Kafka, and instead of it being bundle loaded we create a classloader that has the app classloader as a parent and side peeks into the message streams runtime so it can see both and this integration jar."

"the custom classloader means if this special integration jar we create needs to see stuff internal to Liberty we don’t have to expose that into the application classspace."

"which is really important"

"dump an interface in your jar file. Have your code call kafka via that interface. Provide a direct, non reflection implementation but put it in a jar file."
```

The shim interface and implementation will be done under this issue. The classloader work will be done under issue #7843

**Comment by hutchig** [comment]
@tevans78 @Azquelt drawing your attention to this issue.
We need to discuss the correct place to 'insert' this into
the order of packaging prototypes.

**Comment by Azquelt** [comment]
@hutchig I'm not sure that the subject line of this issue matches what I understand from your conversation snippets.

The headline suggests to me that we would create a shim interface and require the user to include an implementation of it in their application.

However, I think the conversation is suggesting that we create:
* a shim interface in a bundle
* a shim implementation which is in a separate non-bundle jar
* a classloader which can see see the app classes, the shim implementation jar and the shim interface classes

We then use the classloader to load the shim implementation class which we can then call from our bundle code via the shim interface.

**Comment by hutchig** [comment]
So the shim interface can be shipped in Liberty.
The shim implementation can 'see' the users bundled Kafka client jar
because its classloader delegates to the app classloader.
