### ISSUE TITLE
Remote debugging does not work with Java 11+

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#7833]
Previously to attach a remote debugger, we could specify JVM arguments such as this:
```
-agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n
```

However, this does not allow connecting to the VM with a remote debugger. To allow this, we need to slightly adjust the `address` property to be this:
```
-agentlib:jdwp=transport=dt_socket,address=*:8787,server=y,suspend=n
```
(Note the extra `*:`)

Unfortunately, the `*:` syntax is not backwards compatible to Java 7/8, but if we specify the hostname instead of `*` then it does work on all JDKs.

**Comment by FuzzyAzurik** [comment]
Can confirm I had a similar issue, I was unable to attach a remote debugger to the JVM when running JDK 11. I able to resolve it by creating the following file "${WLP_HOME}/usr/servers/server1/jvm.options" and adding 
```text
-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:7777
```

**Comment by tjwatson** [comment]
Was the host name for the address added for security reasons?  Do we need to be careful when defaulting to specifying `*:7777` for the debug address?  I assume if not specified it defaults to `localhost` only.

**Comment by aguibert** [comment]
You are correct Tom, currently remote debugging is not allowed by default in Java 11+. Allowing it all the time would be a security concern, which Alasdair also raised on PR #7834.

Right now I've gone with a solution that leaves the default behavior as is, and if the user wants to enable remote debugging on their server they will be able to set the `WLP_DEBUG_REMOTE=y` env var.
