### ISSUE TITLE
Introspector for Zip Reaper

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#7868]
A zip file reaper dump will includes a history (up to a threshold) of zip file activity, including information for recently accessed and currently opened archives

The reaper dump can be used to diagnose stubborn file lock problems.  That is, when application archives cannot be deleted, renamed, or overwritten, because the file is locked by the liberty process.  The dump would show whether the reaper subsystem was holding a problem archive open.

The reaper introspector will be implemented using the liberty introspector framework, replicating the pattern which is in use for other introspector implementations.

**Comment by tbitonti** [comment]
A prototype implementation is available in branch "zip-dump-handler" of open-liberty repository "tbitonti":
https://github.com/tbitonti/open-liberty/tree/zip-dump-handler

Sample output from the prototype implementation:
[ZipCachingIntrospector.txt](https://github.com/OpenLiberty/open-liberty/files/3282606/ZipCachingIntrospector.txt)

**Comment by NottyCode** [comment]
Agreed to include this since the information is useful.

**Comment by bberry1675** [comment]
Current Latest Code Available Here:https://github.com/bberry1675/open-liberty/tree/zip-introspector

**Comment by bberry1675** [comment]
[here](https://github.com/bberry1675/open-liberty/tree/zip-introspector)

**Comment by bberry1675** [comment]
Sample output will be available here soon.

**Comment by bberry1675** [comment]
[ZipCachingIntrospector.txt](https://github.com/OpenLiberty/open-liberty/files/3398678/ZipCachingIntrospector.txt)

**Comment by bberry1675** [comment]
Second Version of the sample output: [ZipCachingIntrospector.txt](https://github.com/OpenLiberty/open-liberty/files/3403743/ZipCachingIntrospector.txt)
