### ISSUE TITLE
Introspector for Overlay Containers

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#7869]
Add an introspector which will show currently active root overlay containers, including the URLs of the base container and the URLs of the directory overlay container, and including a listing of data stored in the non-persistent cache of the overlay container.  (Adaptable containers implement a non-persistent cache on overlay containers.)

The listing of active overlay containers provides a top-level view of root application containers.

The listing of data from the non-persistent cache shows key application data which has been generated for applications, since each application has a root adaptable container, which has a root overlay container and a non-persistent cache within the overlay container.

**Comment by tbitonti** [comment]
A prototype implementation is available in branch "zip-dump-handler" of open-liberty repository "tbitonti":
https://github.com/tbitonti/open-liberty/tree/zip-dump-handler

Sample output from the prototype implementation:
[OverlayContainerIntrospector.txt](https://github.com/OpenLiberty/open-liberty/files/3282633/OverlayContainerIntrospector.txt)

**Comment by NottyCode** [comment]
Agreed to include this, but there is too much data being tracked so we need to reduce the overhead before delivery.

**Comment by tbitonti** [comment]
Refs:
Design Issue: "Introspector for Overlay Containers"
https://github.com/OpenLiberty/open-liberty/issues/7869

Story: "Implement Introspector for Overlay Container"
https://github.com/OpenLiberty/open-liberty/issues/8478

Pull Request: "Overlay Container Introspector"
https://github.com/OpenLiberty/open-liberty/pull/8416

ID: "GA BLOG: Introspector for Overlay Containers"
https://github.com/OpenLiberty/open-liberty/issues/8479
