### ISSUE TITLE
Tr.audit overhead during Liberty startup

### ISSUE THREAD

**Issue by vijaysun-omr** [OpenLiberty/open-liberty#7878]
Tr.audit takes almost 10 ms during OpenLiberty startup. 

Most of the time goes under the class initializer (<clinit>) and formatTime methods in the class com/ibm/ws/logging/collector/DateFormatHelper which in turn gets into the java/text/DateFormat apis such as getDateTimeInstance. 

I'm raising this issue to see if this code can be improved but there is a risk that even if we avoid initializing these expensive apis in the Tr.audit code paths, they are still encountered on some other subsequent code path executed during OpenLiberty startup (but I thought I'd ask about this in any case).

**Comment by kabicin** [comment]
Modifications were made to com.ibm.ws.logging/src/com/ibm/ws/logging/collector/DateFormatHelper.java and merged into the OpenLiberty:integration. The pull request can be viewed here: https://github.com/OpenLiberty/open-liberty/pull/8263/
