### ISSUE TITLE
Improve error message when configured apps in dropins

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/open-liberty#7921]
We have this age old issue that if someone drops an application into dropins and configures it in server.xml we tell them not to install an application twice. This makes a lot of sense to us, but is consistently confusing to people. The issue is we have historically not been able to get rid of this problem scenario.

Some possible options:

* Check location in apps and report if it is relative to dropins, do not start the configured app.
* See if dropins processing can check to ensure that app isn't configured in server.xml and uninstall. I think in the past this was slightly problematic in some cases, but I can't recall. I know right now the dropins processing has no reference to what is in config. If we could see this we could ignore the app in dropins.

current message:
>ERROR   ] CWWKZ0013E: It is not possible to start two applications called

**Comment by brenthdaniel** [comment]
I think the best way to go is to silently handle this. 

We can handle this pretty easily at the point where we currently issue the error message. If the configured application starts first, we will block the dropins application from starting and proceed without a warning message. If the dropins app starts first, we will stop it, block it, and start the configured app without a warning. Blocking the dropins app means that it will automatically start if the configured app is removed. 

The only real downside to this approach is that, depending on startup order, we could waste time stopping the dropins version. In practice, the configured app is likely to be available before the dropins version, so this probably isn't a big deal.

**Comment by brenthdaniel** [comment]
We talked about this again and there was some reluctance to the proposed solution. Several people felt it would be better to just improve the error message because it would be more straightforward. They also thought it might be confusing to have the dropins application automatically start if you removed the app from server.xml.  The downside to that approach is that it would still be random as to which version of the application gets started.

**Comment by NottyCode** [comment]
Proposal is to have dropins monitor not create a new application if it is already defined.  Add a message if the app manager starts a configured app that is in dropins because things could behave unusually. If the configured application is removed we should restart from dropins because that is what would happen on a server restart so it should be consistent with that or someone will be surprised when the application is running after a server bounce.
