### ISSUE TITLE
Allow use of DataSource with container auth with custom login module 

### ISSUE THREAD

**Issue by KyleAure** [OpenLiberty/open-liberty#7938]
As of PR: https://github.com/OpenLiberty/open-liberty/pull/7930
The Validation endpoint will be restricted to GET requests only.
As a result, the ability to use a custom login module is no longer supported.  

Currently, access to a custom login module is done by supplying authentication data in a HTTP request body.  During testing, it was discovered that at the JDK layer a connection calling the method, `con.getOutputStream();` to write data to the request body, will be changed from a GET request to a POST request.  Since this command also opens the connect, there is no way to revert back it to a GET request.

**Comment by njr-11** [comment]
Custom login module properties have been moved from the request body to the header.  Test cases have been re-enabled.
