### ISSUE TITLE
GA BLOG: Hostname verification 

### ISSUE THREAD

**Issue by acdemyers** [OpenLiberty/open-liberty#7957]
a. Which Liberty feature does it relate to?
   i. Human-readable name:   **SSL feature** 
   ii. Feature name:   **transportSecurity-1.0**
   iii. Is this a new feature or is it an update to an existing feature for this release?   **Hostname verification on SSL configuration is new function in the transportSecurity-1.0 feature.**
   iv. Provide the qualified name of all changed feature deliveries to this release? (eg: com.ibm.websphere.appserver.transportSecurity-1.0.esa)
b. Who is the target audience?  **appserver administrators**
c. Write a sentence or two that introduces it to someone new to the general technology/concept.

**Hostname verification is server identity check used to ensure a client is talking to the correct server.   The check is performed on the client side of an SSL communication and  involves looking at the server’s certificate Subject Alternative Name or SubjectDN to see if it matches   the  host part of the URL used to make the outbound request.**   
 
d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)

**Hostname verification is a feature that is recommended to help protect again man-in-the-middle security vulnerability attacks.  Liberty is allowing uses to enable this on a SSL configuration.**
 
e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.

Hostname verification can be enabled on a SSL configuration by adding the "verifyHostname" attribute to a SSL configuration.  

```
<ssl id="defaultSSLConfig" keyStoreRef="keyStore" verifyHostname="true" />
<keyStore id="keyStore" location="${server.config.dir}/key.p12" type="PKCS12" password="liberty" />
```

With this configuration any outbound SSL connection using "defaultSSLConfig" will undergo a hostname verification check by the JDK.   The check takes place in the trust manager by looking at the server certificate's Subject Alternative Name information to get valid hostnames and look for a match to the hostname in the URL used to make the outbound connection.  If there is no hostname match the SSL handshake will fail.   The hostname may be acquired from the server certificate's SubjectDN if the Subject Alternative Name is missing.
 
f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.
g. Attach any images to this work item as .png files.

**Comment by acdemyers** [comment]
#7496

**Comment by lauracowen** [comment]
That's great, thanks @acdemyers
