### ISSUE TITLE
jdbc-4.3 feature is not giving a warning that it requires Java 11+

### ISSUE THREAD

**Issue by bpaskin-ibm** [OpenLiberty/open-liberty#8002]
The Liberty feature `jdbc-4.3` is not giving a warning that Java 11 is required.  Instead it is just throwing an error similar to this when not using Java 11:

```Caused by: java.lang.UnsupportedClassVersionError: com/ibm/ws/jdbc/osgi/v43/JDBC43Runtime has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0```

The documentation also needs an update, as it states Java SE 8.  
https://developer.ibm.com/wasdev/downloads/#asset/features-com.ibm.websphere.appserver.jdbc-4.3

It should also be noted in the general documentation too.

Brian

**Comment by aguibert** [comment]
Confirmed this is issue is resolved in 19.0.0.7
