### ISSUE TITLE
Feature Test Summary - Support Custom JNDI names for EJBs

### ISSUE THREAD

**Issue by tkburroughs** [OpenLiberty/open-liberty#8043]
**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

The Feature that this is a feature test summary for is to bring over support for custom bindings for EJB from WebSphere Application Server to Open Liberty, mostly to make migration easier. Before the java namespace lookups existed WebSphere used what we call "custom JNDI names". There were default ones (for 3.X beans) or the customer could specify bindings through various `ejb-jar-bnd.xml` (and `ejb-jar-bnd.xmi`) fields.

Our testing strategy consisted of 2 approaches. Moving tests from WAS or Liberty to Open Liberty, and writing new tests for new implementations or edge case areas we discovered while delivering this feature. There are 2 Comments under this one listing the new tests with links to their issues.

**1. FATs moving to open-liberty**

- As this is a feature to implement something already working in WAS, there were a good number of tests for it already in WAS. Specific suites like `bnd`, `defbnd`, and `bnderr` in `suite.r70.base.ejb3misc`, `suite.r80.base.misc.bndmod`, and `suite.r80.base.noInterface.bnd` were created to directly test custom bindings in WAS. We have moved all of these.

- In addition, we scoured the source apps for test applications using custom bindings in the ejb-jar-bnd.xml (and xmi) and found a good number to also bring over to provide more coveraged, such as `suite.r70.base.injection.xml` which deals with injection with custom bindings.

- Some of these were already ported to Liberty, but with the custom bindings removed and replaced with the java namespace lookups, we have moved them to Open Liberty and restored the custom bindings.

We have brought over enough to test every different kind of custom binding lookup, and the `suite.r70.base.ejb3misc.bnderr` bucket covers the various invalid scenarios such as combining certain custom bindings and leaving them blank.

**2. New Tests for added Feature**

These are new tests we have come up with to improve test coverage or cover certain scenarios discovered while implementing this feature.

- There are tests for every new config element for EJBContainer implemented for this feature.

- Tests for having the custom bindings specified in `ejb-jar-bnd.xml` being specified in `server.xml` instead, as that is a new feature in Liberty.

- In WAS, during application install, if you did not have custom bindings specified for 1.X or 2.X beans, we would write default bindings in the `ejb-jar-bnd.xmi` automatically, and it would never be blank during runtime. Open Liberty does not have an application install step so we had to provide default bindings during runtime for 1.X and 2.X beans if they were missing in the bnd file. So we added new tests for this.

- A wide swath of tests called "The Namespace Tests". Since the bindings in the `ejb-jar-bnd.xml` or ``ejb-jar-bnd.xmi` values are strings, we took some exploratory time to manually try weird values in WAS. It was discovered if you stick a namespace in the values (e.g. `java:` `ejblocal:` `local:` etc) you can get some weird behavior of circumventing how the bindings bound. We decided to not allow this and throw an error if your binding value has a namespace in it. We updated our error scenario test suite (`com.ibm.ws.ejbcontainer.bindings_fat : BndErrorTest`) to cover these. The second part of providing lookup bindings is the act of looking them up. On WAS you can also do some weird lockups by chaining namespaces in the lookup, even for normal bindings. The other namespace tests are asserting these chaining namespace lookups work correctly.

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

~~0 - No automated testing delivered~~

~~1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.~~

~~2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths~~

~~3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.~~

**4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.**

~~5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.~~

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by tkburroughs** [comment]
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## FATs moving to open-liberty
- [ ] r70-ejb3misc.defbnd  -> com.ibm.ws.ejbcontainer.binding_fat

**Comment by olendvcook** [comment]
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ## New Tests for added Feature

| Created | Passing | open-liberty test | Status |
| :---: | :---: | :--- | :--- |
| | | server.xml tests | Opened #8231 |
| | | ejb config | Opened  #8232 |
| | | customBindings.onError | Opened #8262 |

**Comment by ayoho** [comment]
Coverage sounds great to me - I'm happy to approve.
