### ISSUE TITLE
NullPointerException at SSLConfigManager.getCipherList

### ISSUE THREAD

**Issue by cassiel13** [OpenLiberty/open-liberty#8071]
Hello. I'm getting this NPE trying to use a REST service with Spring MVC / Security in Liberty 19.0.0.6 and IBM 1.8.0_sr5fp36 (Liberty for Java in IBM Cloud). It works fine in 19.0.0.3.

Here is the ffdc:
[ffdc_19.06.27_05.31.19.0.log](https://github.com/OpenLiberty/open-liberty/files/3336965/ffdc_19.06.27_05.31.19.0.log)

**Comment by ayoho** [comment]
Looks like there were some NPE protections that were removed in https://github.com/OpenLiberty/open-liberty/pull/7469. @acdemyers Would you be able to take a look?

**Comment by acdemyers** [comment]
This should be fixed by PR https://github.com/OpenLiberty/open-liberty/pull/7929.  The tack in the logs attached suggest this change is not included.
