### ISSUE TITLE
security credential needs to have time of authentication available

### ISSUE THREAD

**Issue by brutif** [OpenLiberty/open-liberty#8083]
In the openid connect core spec, sec 3.1.2.1 specifies a max_age parameter which should cause the provider to reauthenticate the user:
```
max_age
    OPTIONAL. Maximum Authentication Age. Specifies the allowable elapsed time in seconds since the last time the End-User was actively authenticated by the OP. If the elapsed time is greater than this value, the OP MUST attempt to actively re-authenticate the End-User. 
```

While marked optional in the spec, to obtain provider certification from openid.net
(https://openid.net/certification/) this function must work.  In order for it to be able to work we need to be able to obtain the authentication time from the WSCredential.  Presently we can only obtain the expiration time.

**Comment by brutif** [comment]
@chunlongliang-ibm fyi.

**Comment by ayoho** [comment]
The prereq for this request is no longer needed, so I'm going to go ahead and close this issue.
