### ISSUE TITLE
HttpServletMapping.getPattern is not correct for /* mapping

### ISSUE THREAD

**Issue by pmd1nh** [OpenLiberty/open-liberty#8085]
For a servlet mapping of `/*`, HttpServletMapping.getPattern() should have returned `/*` (instead of just `/` ).  Also, the HttpServletMapping.getMappingMatch() should have returned "PATH" (instead of "DEFAULT").

**Comment by pmd1nh** [comment]
https://github.com/OpenLiberty/open-liberty/pull/8090

**Comment by pmd1nh** [comment]
Example output for HttpServletMappingServlet servlet which has /* mapping.
Request URL: http://localhost:9080/contextRoot/testPath/myPath 

Old:
getPattern: /
getMappingMatch: DEFAULT
getMatchValue: 
getServletName: HttpServletMappingServlet

New:
getPattern: /*
getMappingMatch: PATH
getMatchValue: testPath/myPath
getServletName: HttpServletMappingServlet

**Comment by pnicolucci** [comment]
Merged to master closing.
