### ISSUE TITLE
Issues with CPU and Heap size metrics on Grafana dashboard

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#8086]
As reported by Monica Tamboli, there are two things that need to be looked at and potentially fixed for our metrics.  Monica was viewing our Liberty Grafana dashboard and made the following observations:

1.  CPU System Load Average - value doesn't match what the pod overview in ICP dashboard says
2.  Maximum heap size - value seems to match container size rather than the JVM max heap size

**Comment by mtamboli** [comment]
Hi Don, as we discussed on the slack, I looked into the CPU comparison of 2 dashboards for same pod:

I am trying to remember what I meant then. But what is liberty dashboard representing int terms of CPU core used.

https://9.42.98.50:8443/grafana/d/kube-system-kubernetes-pod-overview/kubernetes-pod-overview?refresh=10s&orgId=1&var-namespace=mtamboli&var-pod=qs-ol-ubi1-ibm-open-libe-0&var-container=All
![image](https://user-images.githubusercontent.com/29490950/63062672-c090df80-bec7-11e9-8542-527cf0da5c8b.png)

https://9.42.98.50:8443/grafana/d/websphere-liberty/liberty-metrics-g5-20190521?orgId=11&refresh=10s&var-app=qs-ol-ubi1-ibm-open-libe&var-servlet=com_ibm_ws_microprofile_health_health_check_servlet&var-dur=%5B10m%5D&from=now-30m&to=now
![image](https://user-images.githubusercontent.com/29490950/63062766-0352b780-bec8-11e9-8c2c-873d0100c0bc.png)
![image](https://user-images.githubusercontent.com/29490950/63062848-588ec900-bec8-11e9-9732-85591e745a2b.png)

**Comment by jennifer-c** [comment]
Hi Monica,

Seems that the CPU System Load Average is the "sum of the number of runnable entities queued to the available processors and the number of runnable entities running on the available processors averaged over a period of time" (from the Metrics spec). On the dashboard, it shows the average over one minute.

**Comment by jennifer-c** [comment]
I also investigated the CPU load percentage, and it seems to be working as intended. 

When restricted to 4 cores, CPU load percent would plateau at 12.5%. When unrestricted, the CPU load percent could go beyond 12.5% (I got to ~17% with my app that is moderately weak in terms of CPU usage). There are 32 cores available per pod, which is the default when choosing not to enable constraints. So, the CPU load percentage is based off of how much of the 32 cores are being used.

**Comment by donbourne** [comment]
As proposed by @jennifer-c , we're looking to use OperatingSystemMXBean's getProcessCpuTime as that will give us a number, which when divided by the number of available CPUs will be a representation of the % of available CPUs used.

This would be a vendor metric, possibly called `cpu_process_cpu_time`.  We propose adding that to mpMetrics and possibly to monitor-1.0 metrics.

**Comment by donbourne** [comment]
This new metric (cpu_process_cpu_time) might be best positioned to be added as a new base metric as part of the MicroProfile Metrics spec rather than just including it in Liberty.

**Comment by jennifer-c** [comment]
The new `processCpuTime` metric has been added to Open Liberty 20.0.0.1 (#9384 #9945)

Manually verified that the metric works on OpenJ9 and HotSpot JVMs.

Attached is the results of testing the metric on z/OS, as well.
[Metrics.txt](https://github.com/OpenLiberty/open-liberty/files/4119018/Metrics.txt)

**Comment by jennifer-c** [comment]
PR for updated dashboards is here: https://github.com/OpenLiberty/open-liberty-operator/pull/97
