### ISSUE TITLE
BETA BLOG 19700: Reactive Messaging Beta blog post content

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#8104]
BETA BLOG 19700
We should write a paragraph or two on how to use the beta mpReactiveMessaging-1.0 feature

**Comment by hutchig** [comment]
I will follow the process here: https://github.ibm.com/was-liberty/WS-CD-Open/wiki/Creating-Stories-and-Features#moving-a-feature-into-a-beta
and chat to @lauracowen

**Comment by hutchig** [comment]
~~1 - Create a child task of the epic~~
~~2 - with a description that starts with "BETA BLOG 19#00", where #=1,2,3, ~~
Add to the child task the labels: 
~~3 'Blog' ~~
~~ 4 and 'release:19#00', where #=1,2,3, ... ~

Provide the appropriate text (see questionnaire) in the child task.
When the text has been provided, assign the task to Laura Cowen, Dave Barfield and the Epic feature owner.

**Comment by hutchig** [comment]
Beta (no betas in Open Liberty so blog posts are just updates on what's in progress but not yet in the stable/GA release; eg https://openliberty.io/blog/2018/11/23/distributed-tracing-microservices.html)
Development progress update

a. Which Liberty feature does it relate to?

   i. Human-readable name (eg WebSockets feature)

   ii. Feature name (eg websockets-1.0)

   iii. Is this a new feature or is it an update to an existing feature for this release?

   iv. Provide the qualified name of all changed feature deliveries to this release? (eg: com.ibm.websphere.appserver.transportSecurity-1.0.esa)

b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc
c. Write a sentence or two that introduces it to someone new to the general technology/concept.
 
d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)
 
e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.
 
f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

g. Attach any images to this work item as .png files.

**Comment by lauracowen** [comment]
Thanks!
