### ISSUE TITLE
Feature Test Summary: Liberty integration with PostgreSQL

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/open-liberty#8118]
Please complete the following Feature Test Summary when you have completed all your testing.  This will be used as part of the FAT Complete Review.

# Part 1:
Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.

> For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature.

> If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

### New Testcontainers support added to test framework
 - Added usage of Testcontainers to the FAT framework which will allow FATs to spin up an arbitrary Docker container and expose it on a random port to be used per FAT run instance

### Automated FAT tests in a new `com.ibm.ws.jdbc_fat_postgresql` bucket:
- Uses Testcontainers to spin up 1 unsecured PostgreSQL instance per run, and 1 additional secured PostgreSQL instance in FULL mode.
- Verify existing (as-is) behavior of using PostgreSQL with generic `<properties>` element continues to work by;
    - auto-detecting driver type from JDBC driver jar name
    - auto-detecting driver type from looking at META-INF/services/
- Verify minimal configuration for the new `<properties.postgresql>` element
- Verify it is possible to configure a DataSource using only a URL with `<properties.postgresql URL="..."/>`
- Verify basic DataSource unwrap pattern works for PostgreSQL driver. There are no vendor-specific methods on DataSource to test though.
- Verify basic Connection unwrap pattern works for PostgreSQL vendor-specific methods, such as:
   - PGConnection.getBackendPID()
   - PGConnection.createArrayOf(String, Object)
- Test that a basic PostgreSQL-only bean property (defaultFetchSize) gets set on a DataSource when configured in server.xml
- Verify behavior of the defaultReadOnly setting on <properties.postgresql>
- Verify that the defaultAutoCommit setting defaults to true, and when it is set to false connections obtained from these DataSources have autoCommit=false when initially obtained
- Ensure defaultAutoCommit=false behaves properly across global transaction boundaries. Insert/read data with two different DataSources, expect writes to auto-commit
- Verify autoCommit can be set and is reset on new connection
- Verify transaction isolation level can be set and is reset on new connection
- Verify ResultSet holdability can be set and is reset on new connection
- Verify network timeout can be set and is reset on new connection
- Verify schema can be set and is reset on new connection
- Verify PostgreSQL vendor-specific Connection property defaultFetchSize can be set and is reset properly
- Verify PostgreSQL vendor-specific Connection property prepareThreshold can be set and is reset properly
- Verify the PostgreSQL vendor-specific CopyAPI is allowed
- Verify the PostgreSQL vendor-specific LargeObjectAPI is not allowed because it has operations that can commit transactions on the underlying PG connection
- Copied some tests from the jdbc_fat_v41 bucket to verify statement caching behavior
- FULL mode only tests:
   - Verify PostgreSQL vendor-specific SSL configuration can be used with a security-enabled PostgreSQL DB
   - Verify Liberty standard SSL configuration can be used with a security-enabled PostgreSQL DB

# Part 2:
Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.

> Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:
> 0 - No automated testing delivered
> 1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.
> 2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths
> 3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.
> 4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.
> 5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

> Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

Confidence: 5
Comments:

**Comment by dave-waddling** [comment]
**FAT Focal Approval comment:** Hi @aguibert, thanks for completing the Feature Test Summary. 

I'm aware there's still at least one functional PR which is not yet merged (#8027 

There are also a pair of defects open against the new com.ibm.ws.jdbc_fat_postgresql bucket which will need to be triaged to ensure they are not product issues: [265044](https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=265044) and [262480](https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=262480).

Obviously I can't approve until the above are addressed and until all of the functional changes have gone through an SOE run.

**Comment by aguibert** [comment]
@dave-waddling #8027 is unrelated to this feature, did you mean a different issue/PR?

I was aware of defect 262480 -- it is an issue with Testcontainers setup (before product code is even in play) and shouldn't need to block this feature from GAing. I've labeled it `test_bug` to make that more clear.

Looks like 265044 was opened after I requested FAT Focal Approval. This one appears to be a test bug as well, but I will do some investigation today and confirm.

**Comment by tevans78** [comment]
I think Dave probably meant #8095 which is now closed.

**Comment by aguibert** [comment]
Identified the issue in 265044 and confirmed it is indeed a test bug. I have a proposed fix in PR #8153 

@dave-waddling all blockers identified earlier have now been removed, so this feature test summary should be ready for approval now

**Comment by dave-waddling** [comment]
**FAT Focal Approval comment:** I've reviewed this feature and in discussion with @aguibert I'm happy to grant a FAT Focal Approval once 265044 is demonstrated to be fixed when running on IBM JDK 8.

**Comment by aguibert** [comment]
The personal build in this PR https://github.com/OpenLiberty/open-liberty/pull/8163 addresses Dave's remaining concern and will resolve 265044.

Proceeding with closing out this issue

**Comment by dave-waddling** [comment]
**FAT Focal Approval comment:** Hi @aguibert, I've taken a look at your builds this morning and the fix looks good. Based on our prior discussions and the nature of the now fixed issue I've granted the FAT Focal Approval to the parent Epic.
