### ISSUE TITLE
server.bat on Windows doesn't "propagate" WLP_DEBUG_SUSPEND read from server.env

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/open-liberty#8122]
When using the Unix-style **bin/server** script, the `server debug <serverName>` command will read **server.env** and use the value of WLP_DEBUG_SUSPEND to build the debugger-related JVM args.

When using server.bat on Win 10 (from cmd.exe, or Git Bash), a value of `WLP_DEBUG_SUSPEND=n` in server.env is ignored, and I get the behavior where the JVM is launched suspended, waiting for the debugger.

This happened for me on 19.0.0.4 and 19.0.0.6

**Comment by NottyCode** [comment]
does setting WLP_DEBUG_ADDRESS also fail in the same way?

**Comment by scottkurz** [comment]
Yes, same issue with:  WLP_DEBUG_ADDRESS.

**Comment by scottkurz** [comment]
@hlhoots would you happen to have any suggestions on this?  E.g. if we needed to add a Windows-only FAT test, what FAT bucket might that go in?   (Thanks).

**Comment by scottkurz** [comment]
Maybe com.ibm.ws.kernel.boot_fat

**Comment by scottkurz** [comment]
Crap.. never actually merged this..now it needs to be merged with https://github.com/OpenLiberty/open-liberty/pull/8765 which is trivial but maybe could use another quick manual test and a build+FAT too.   Will rebase today.

**Comment by hlhoots** [comment]
Think this was resolved by PR #8140. Closing out.
