### ISSUE TITLE
Port servlet-3.1 FATs to open-liberty

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/open-liberty#8127]
Port the following FATs to open-liberty:
1) com.ibm.ws.webcontainer_fat_servlet31 - runs the 3.1 specific tests
2) com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.1 - runs the 3.1 tests with the servlet-4.0 feature

**Comment by isaacrivriv** [comment]
We ported the com.ibm.ws.webcontainer_fat_servlet31 bucket from Websphere Liberty as com.ibm.ws.webcontainer.servlet.3.1_fat on Open Liberty. Added the tests of the com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.1 bucket as a repeat test inside the new Open Liberty bucket.
