### ISSUE TITLE
Adding mpConfig-1.3 feature while the server is running doesn't install the configuration feature properly

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/open-liberty#8141]
Running `mvn liberty:run-server`, then adding `mpConfig-1.3` in the target server.xml and running `mvn compile` in another terminal, the following error is displayed:

```
[ERROR   ] CWWKZ0004E: An exception occurred while starting the application japan-tour. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type String with qualifiers @ConfigProperty
[INFO]   at injection point [BackedAnnotatedField] @Inject @ConfigProperty com.sebastian_daschner.japan_tour.MascotsResource.homeDir
[INFO]   at com.sebastian_daschner.japan_tour.MascotsResource.homeDir(MascotsResource.java:0)
```
If you stop the server and restart it the error no longer appears.  Is this expected behaviour? 

See https://github.com/WASdev/ci.maven/issues/467

**Comment by tevans78** [comment]
My first attempt at recreating this issue (as a FAT test, without maven) failed ... or rather the new test I wrote passed. It was using variables from server.env ... next I will try just using `home` from my system environment. But that will have to wait until next week.

**Comment by tevans78** [comment]
Note that I just wanted to rule out it being a general problem with hot adding the feature. Will also try using `mvn liberty:dev`

**Comment by tevans78** [comment]
I have recreated this properly now. The bug is really in CDI. CDI was caching the runtime extensions such that when mpConfig was added, CDI never saw the extra extension.
