### ISSUE TITLE
Json Error Logs since 19.0.0.6

### ISSUE THREAD

**Issue by c-koell** [OpenLiberty/open-liberty#8171]
After upgrading to 19.0.0.6 from 19.0.0.5 we see some Error Messages in the System.err log.
We have some code that tries to convert a String Value into a Type.

```java
Jsonb jsonb = JsonbBuilder.create();
  try {
    return jsonb.fromJson(json, OutboundEndpoint.class);
  } catch (Exception e) {
    // Nothing to log ..
    return null;
}
```

It could happen that a non valid json String will be given to that Method. In the new Liberty Version that generates a Log Entry like this

`[ERROR   ] Error deserialize JSON value into type: class org.some.Type`

**Comment by aguibert** [comment]
hi @c-koell, it looks like this error may have always been occurring with your application, but previously Yasson did not log an ERROR message and now it does.

The extra logging statement was likely introduced by this change:
https://github.com/eclipse-ee4j/yasson/commit/62dc006ac312fc8b1543892b82a14ef6485d6fa3#diff-44d72b506105258cffab226412abc88b

In order to investigate further can you please do the following:
1. Clarify that your app still works the same as before -- the only difference is the extra log message
1. add some logging to the `catch (Exception e)` block so we can determine the full stack trace
1. when the exception is encountered, can you provide the incoming JSON data
1. include the `OutboundEndpoint` class and related sub-fields/classes

**Comment by c-koell** [comment]
Hi @aguibert 

1. yes the app works as before .. 
2. i will attach the stack trace tomorrow
3. we give different strings to that method .. so it is a method to test if it is a valid json string .. if a string like "abc" comes i the log occurs
4. i think you do not need any class because "abc" can not be converted to any class type

**Comment by c-koell** [comment]
This ist the Stacktrace 
`[ERROR   ] Error deserialize JSON value into type: class at.gv.tirol.csb.client.jaxrs.config.OutboundEndpoint.
[err] javax.json.bind.JsonbException: Error deserialize JSON value into type: class at.gv.tirol.csb.client.jaxrs.config.OutboundEndpoint.
[err] 	at org.eclipse.yasson.internal.serializer.DeserializerBuilder.build(DeserializerBuilder.java:134)
[err] 	at [internal classes]
[err] 	at at.gv.tirol.csb.client.jaxrs.config.OutboundEndpoint.fromJson(OutboundEndpoint.java:129)
[err] 	at at.gv.tirol.csb.client.jaxrs.mpconfig.OutboundEndpointConverter.convert(OutboundEndpointConverter.java:17)
[err] 	at at.gv.tirol.csb.client.jaxrs.mpconfig.OutboundEndpointConverter.convert(OutboundEndpointConverter.java:10)
[err] 	at com.ibm.ws.microprofile.config.converters.UserConverter.convert(UserConverter.java:76)
[err] 	at [internal classes]
[err] 	at at.gv.tirol.csb.client.jaxrs.mpconfig.ConfigManager.getOutboundEndpoint(ConfigManager.java:34)
[err] 	at at.gv.tirol.csb.client.jaxrs.mpconfig.ConfigManager.getOutboundEndpoints(ConfigManager.java:45)
[err] 	at at.gv.tirol.csb.client.jaxrs.CSBManager.getOutboundEndpointsForJMX(CSBManager.java:227)
[err] 	at at.gv.tirol.csb.client.CSBManager.getOutboundEndpointsForJMX(CSBManager.java:121)
[err] 	at at.gv.tirol.csb.client.jaxrs.statistic.OutboundEndpointStatisticManager.startup(OutboundEndpointStatisticManager.java:67)
[err] 	at at.gv.tirol.common.global.PluginRegistry.startupPlugin(PluginRegistry.java:149)
[err] 	at at.gv.tirol.common.global.PluginRegistry.newPlugin(PluginRegistry.java:128)
[err] 	at at.gv.tirol.common.global.PluginRegistry.getPlugin(PluginRegistry.java:81)
[err] 	at at.gv.tirol.common.global.PluginRegistry.getPlugin(PluginRegistry.java:50)
[err] 	at at.gv.tirol.common.global.ApplicationContext.getPlugin(ApplicationContext.java:84)
[err] 	at at.gv.tirol.csb.client.jaxrs.invoker.AbstractServiceClient.<init>(AbstractServiceClient.java:28)
[err] 	at at.gv.tirol.csb.client.jaxrs.invoker.FailoverServiceClient.<init>(FailoverServiceClient.java:15)
[err] 	at at.gv.tirol.csb.client.jaxrs.invoker.Balance$$Lambda$321.000000001BF0FEE0.get(Unknown Source)
[err] 	at at.gv.tirol.csb.client.jaxrs.invoker.Balance.getServiceClient(Balance.java:29)
[err] 	at at.gv.tirol.csb.client.jaxrs.invoker.ExternalServiceClient.post(ExternalServiceClient.java:134)
[err] 	at at.gv.tirol.csb.client.jaxrs.invoker.ExternalServiceClient.post(ExternalServiceClient.java:111)
[err] 	at at.gv.tirol.csb.client.jaxrs.CSBClient.receiveRemoteBackbone(CSBClient.java:466)
[err] 	at at.gv.tirol.csb.client.jaxrs.CSBClient.receiveRemote(CSBClient.java:434)
[err] 	at at.gv.tirol.csb.client.jaxrs.CSBClient.receiveInternal(CSBClient.java:329)
[err] 	at at.gv.tirol.csb.client.jaxrs.CSBClient.receive(CSBClient.java:169)
[err] 	at at.gv.tirol.csb.client.jaxrs.CSBClient.receive(CSBClient.java:159)
[err] 	at at.gv.tirol.csb.client.jaxrs.CSBClient.receive(CSBClient.java:145)
[err] 	at at.gv.tirol.csb.client.jaxrs.CSBClient.receive(CSBClient.java:131)
[err] 	at at.gv.tirol.csb.client.CSBClient.receive(CSBClient.java:174)
[err] 	at at.gv.tirol.csb.client.listener.DurableChannelListenerImpl.subscribe(DurableChannelListenerImpl.java:53)
[err] 	at at.gv.tirol.csb.client.task.TaskChannelManager.subscribe(TaskChannelManager.java:171)
[err] 	at at.gv.tirol.csb.client.task.TaskChannelManager.subscribe(TaskChannelManager.java:145)
[err] 	at at.gv.tirol.csb.client.jaxrs.CSBInitHandler.init(CSBInitHandler.java:67)
[err] 	at sun.reflect.GeneratedMethodAccessor1076.invoke(Unknown Source)
[err] 	at java.lang.reflect.Method.invoke(Method.java:508)
[err] 	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
[err] 	at [internal classes]
[err] 	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
[err] 	at org.jboss.weld.util.Observers.notify(Observers.java:166)
[err] 	at [internal classes]
[err] 	at com.ibm.ws.webcontainer.osgi.WebContainer.access$000(WebContainer.java:111)
[err] 	at com.ibm.ws.webcontainer.osgi.WebContainer$3.run(WebContainer.java:956)
[err] 	at [internal classes]
[err] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
[err] 	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
[err] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
[err] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[err] 	at java.lang.Thread.run(Thread.java:812)
`

**Comment by aguibert** [comment]
This seems like OK behavior to me. Some invalid data is being passed to Yasson, and as a result an error is logged.

I would recommend tweaking your app so you don't attempt to deserialize invalid JSON data. Otherwise, you could disable logging for Yasson by setting `org.eclipse.yasson.internal.serializer=off` in your trace settings.

**Comment by c-koell** [comment]
Hi !

Thank you for clarifing... For me it's also a valid behaviour.

But I would still give some thoughts to concern

- There is no public method in the api to test a string. 
   So i think many people out there have a try catch strategy to test a string where now
   maybe many log entries will be created
- Logging Hell
   We are using in our application log4j2 and i have tried to route the java.util Log from yasson with the 
   jul-to-slf4j -> log4j-slf4j -> log4j2 construct. Maybe it was my mistake but i was not able to route the 
   error logs. I don't know why but the SLF4JBridgeHandler will not be called. Maybe because yasson is in 
   the liberty runtime and not in my application.

**Comment by aguibert** [comment]
- The only test that should be needed is if the JSON input string starts with `{` and ends with `}` and if so it likely represents JSON data. Another option is to write a custom `JsonbAdapter` or `JsonbDeserializer` to implement custom JSON->POJO logic according to your application's needs. See the [JSONB user guide](http://json-b.net/docs/user-guide.html#adapters) for code example.

- The logging spec would need to be configured as a Liberty trace setting, which can be done with the `<logging traceSpecification="*=info:org.eclipse.yasson.internal.serializer=off"/>` element in your server.xml see the [config doc](https://openliberty.io/docs/ref/config/#logging.html) for full details.
