### ISSUE TITLE
RM Kafka: Read IBM Cloud Event Streams config from VCAP_SERVICES if available

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#8208]
Needs some investigation to check the format of VCAP_SERVICES and see whether any additional information is required to be able to extract the required connection informatmion.

**Comment by hutchig** [comment]
Java code to fish properties like the api-key and the token needed, using Jackson from a System.getenv("VCAP_SERVICES"); can be found here:
https://github.com/ibm-messaging/event-streams-samples/blob/master/kafka-java-liberty-sample/src/main/java/com/eventstreams/samples/env/Environment.java

A good contact person is Adian Preston who has written such code in the past.

**Comment by hutchig** [comment]
If I use cloud.ibm to generate credentials now, an actual example looks like this (this was not VCAP_SERVICES but a single credential):

{
  "api_key": "xOSdtHUxGDVXeXHc7VGCh9kCOYfCzQWNZ155owIHkFgj",
  "apikey": "xOSdtHUxGDVXeXHc7VGCh9kCOYfCzQWNZ155owIHkFgj",
  "iam_apikey_description": "Auto-generated for key 765ef9f3-50ba-4798-9a43-e95bc6617c37",
  "iam_apikey_name": "Service credentials-2",
  "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Manager",
  "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/ff1092aaa74d4be8c036063e9200c9fc::serviceid:ServiceId-ccff927b-fa3f-44e2-9094-ab76f9755d6e",
  "instance_id": "0ac973e8-8d1f-447f-ba68-d67cd20db6c9",
  "kafka_admin_url": "https://mrvwmjj9p7f6nk4r.svc01.eu-gb.eventstreams.cloud.ibm.com",
  "kafka_brokers_sasl": [
    "broker-4-mrvwmjj9p7f6nk4r.kafka.svc01.eu-gb.eventstreams.cloud.ibm.com:9093",
    "broker-0-mrvwmjj9p7f6nk4r.kafka.svc01.eu-gb.eventstreams.cloud.ibm.com:9093",
    "broker-2-mrvwmjj9p7f6nk4r.kafka.svc01.eu-gb.eventstreams.cloud.ibm.com:9093",
    "broker-1-mrvwmjj9p7f6nk4r.kafka.svc01.eu-gb.eventstreams.cloud.ibm.com:9093",
    "broker-3-mrvwmjj9p7f6nk4r.kafka.svc01.eu-gb.eventstreams.cloud.ibm.com:9093",
    "broker-5-mrvwmjj9p7f6nk4r.kafka.svc01.eu-gb.eventstreams.cloud.ibm.com:9093"
  ],
  "kafka_http_url": "https://mrvwmjj9p7f6nk4r.svc01.eu-gb.eventstreams.cloud.ibm.com",
  "password": "xOSdtHUxGDVXeXHc7VGCh9kCOYfCzQWNZ155owIHkFgj",
  "user": "token"
}

**Comment by Azquelt** [comment]
Be aware that the Jackson jar is somewhat large. In the repository, we were asked to avoid using it to avoid inflating the size of the kernel.

There is a jsonp jar in the kernel which we might consider using instead, though it is a more basic interface than jackson provides.

**Comment by hutchig** [comment]
A whole (real) credential section will look like this: (on cloud public):
note the "messagehub" from the old name for Event Streams on public cloud

{
  "messagehub": [
    {
      "label": "messagehub",
      "provider": null,
      "plan": "standard-v2",
      "name": "Event Streams-ex",
      "tags": [
        "web_and_app",
        "ibm_created",
        "ibm_dedicated_public",
        "ibmcloud-alias"
      ],
      "instance_name": "Event Streams-ex",
      "binding_name": null,
      "credentials": {
        "api_key": "af_uvOM-7SQZjyJWJMARPXg5VeP8gGeoX1gF4_tWSRwr",
        "apikey": "af_uvOM-7SQZjyJWJMARPXg5VeP8gGeoX1gF4_tWSRwr",
        "iam_apikey_description": "Auto-generated for binding 106e044f-7d89-4847-9fe9-d7a3d96cb685",
        "iam_apikey_name": "Event Streams-ex",
        "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Manager",
        "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/ff1092aaa74d4be8c036063e9200c9fc::serviceid:ServiceId-e2ff2550-e47b-4c1e-8a8a-6e8a8d77c064",
        "instance_id": "0ac973e8-8d1f-447f-ba68-d67cd20db6c9",
        "kafka_admin_url": "https://mrvwmjj9p7f6nk4r.svc01.eu-gb.eventstreams.cloud.ibm.com",
        "kafka_brokers_sasl": [
          "broker-3-mrvwmjj9p7f6nk4r.kafka.svc01.eu-gb.eventstreams.cloud.ibm.com:9093",
          "broker-1-mrvwmjj9p7f6nk4r.kafka.svc01.eu-gb.eventstreams.cloud.ibm.com:9093",
          "broker-0-mrvwmjj9p7f6nk4r.kafka.svc01.eu-gb.eventstreams.cloud.ibm.com:9093",
          "broker-2-mrvwmjj9p7f6nk4r.kafka.svc01.eu-gb.eventstreams.cloud.ibm.com:9093",
          "broker-4-mrvwmjj9p7f6nk4r.kafka.svc01.eu-gb.eventstreams.cloud.ibm.com:9093",
          "broker-5-mrvwmjj9p7f6nk4r.kafka.svc01.eu-gb.eventstreams.cloud.ibm.com:9093"
        ],
        "kafka_http_url": "https://mrvwmjj9p7f6nk4r.svc01.eu-gb.eventstreams.cloud.ibm.com",
        "password": "af_uvOM-7SQZjyJWJMARPXg5VeP8gGeoX1gF4_tWSRwr",
        "user": "token"
      },
      "syslog_drain_url": null,
      "volume_mounts": []
    }
  ]
}

**Comment by hutchig** [comment]
OK Andrew - sounds like wise advice on JSON decoding.
I have no technical opinion at the moment on the best way to decode
JSON as I have not looked into it.

**Comment by tevans78** [comment]
Reconsidering whether this issue should be included in the feature

**Comment by tevans78** [comment]
We agreed with @NottyCode that we should not implement this. Closing.
