### ISSUE TITLE
Create EJB Custom Bindings in server.xml tests

### ISSUE THREAD

**Issue by olendvcook** [OpenLiberty/open-liberty#8231]
Create new EJB Custom Bindings in server.xml tests.

Test ibm-ejb-jar-bnd.xml elements included directly in server.xml

Should go into bindings_fat

**Comment by olendvcook** [comment]
Test simple-binding-name, component-id, local-home-binding-name, remote-home-binding-name on session element

**Comment by tkburroughs** [comment]
Be sure to test override; server.xml overrides what is in app binding file.

**Comment by tkburroughs** [comment]
Is this possible for WAR modules with EJBs in them?

**Comment by olendvcook** [comment]
Done
