### ISSUE TITLE
[Question] What is the expected release schedule for OpenLiberty?

### ISSUE THREAD

**Issue by hrstoyanov** [OpenLiberty/open-liberty#825]
It's be nice if you can release monthly, like Wildfly Swarm ...

**Comment by aguibert** [comment]
OpenLiberty officially releases on a quarterly basis, which is built into the versioning scheme:  `YEAR.0.0.QUARTER` such as `17.0.0.3`

We also build/test developer builds on a continuous basis.

Both the official quarterly releases and the the developer builds can be found on https://openliberty.io/downloads/
