### ISSUE TITLE
Add a test case for HealthChecks defined using CDI Producers for mpHealth-2.0

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/open-liberty#8255]
Need to add a test case in our mpHealth-2.0, that tests the scenario, where the HealthCheck procedures are defined using CDI Producers.

```java
@ApplicationScoped
public class Checks {

    @Readiness
    @Produces
    HealthCheck databaseCheck() {
        return () -> HealthCheckResponse.named("random-check").up().build();
    }
}
```

**Comment by kabicin** [comment]
Merged the test cases with PR https://github.com/OpenLiberty/open-liberty/pull/8529
