### ISSUE TITLE
Update the EclipseLink Binaries and fix the gradle utility script

### ISSUE THREAD

**Issue by daliasheasha** [OpenLiberty/open-liberty#826]
The EclipseLink binaries in Liberty should be updated to the latest commit level to include version: 2.6.5.WAS-22b68cc

The utility scripts that update the EclipseLink versions in Liberty needs to be fixed to account for having EclipseLink 2.7 binaries in the repo as well as EclipseLink 2.6.

**Comment by tkburroughs** [comment]
Work complete... closing
