### ISSUE TITLE
Beta attribute under which to develop DB2 Trusted Context in OpenLiberty

### ISSUE THREAD

**Issue by frowe** [OpenLiberty/open-liberty#8295]
As a user of Liberty, I need a way to enable the DB2 Trusted Context beta function so that I can experiment with it without interfering with production usage.
When the function GA's, DB2 trusted context (TC) will be enabled by the presence of a specific login mapping module type in the app bindings (whether the bindings file or server.xml) and ultimately there will be no server config required to enable it.  This means that without a beta guard, while we're in code development, a user could deploy an application specifying that mapping module w/o knowing OL support isn't complete and get errors and unexpected behavior.  Because the new code for TC has to be added to existing connection management code and not under a new feature, an OL feature won't be required to enable it, so to prevent unintentional use of the new code, we're going to require the configuration of a dummy attribute on dataSource config element, **"trustedContext=true** to enable the function.  This attribute  will not be required when the function GA's.  The connection management code should look for the presence of this attribute before acting upon the presence of the TC information.

**Comment by njr-11** [comment]
Closing - will use general server mechanism for detecting beta instead
