### ISSUE TITLE
LTPA cookie created from JWT or OIDC can not be used on a downstream servers

### ISSUE THREAD

**Issue by barbj** [OpenLiberty/open-liberty#8302]
The case is as follows:

1) WLP is configured for OIDC/OAuth2 authentication using the mpjwt feature
2) Authentication is through an access token
3) Step 2) will implicitly create an LTPA token which inherits the custom cache key created after the access token was successfully validated and the subject got created
4) The custom cache key is set as attribute com.ibm.wsspi.security.cred.cachekey of the LTPA token
5) In a next step the LTPA token is extracted from the thread's security context using e.g. Cookie ltpaCookie = WebSecurityHelper.getSSOCookieFromSSOToken();
6) This cookie is sent to a downstream server which errors out with the following exception:  com.ibm.ws.security.authentication.AuthenticationException: Custom cache key missed authentication cache. Need to re-challenge the user to login again.

The proposed fix will work like this:

1. The 1st hop always validate access_token.The subject in the 1st hop is directly created from the received access_token. If there exists a cached subject with the same principal name, new subject will still be created unless the cached subject contains the exact same JWT. So the RunAs subject represents the access_token in the request.

2. The LTPA cookie API will create LTPA cookie from the RunAs subject directly without including custom cache key, so LTPA cookie can be used by another server. In other words, the following API will return an LTPA cookie that can be used by other servers (without containing a custom cache key)

**Comment by barbj** [comment]
Core security will provide an API to create a propagatable LTPA token.

**Comment by rbgigo** [comment]
Hi Ut

Just wondering, is the API being provided something different to _WebSecurityHelper.getSSOCookieFromSSOToken();_ ?

Regards
Ray

**Comment by utle** [comment]
Hi Ray,
We are not finalize the design yet. I will let you know as soon as we are agreed on the design.
Thanks,
Ut

**Comment by utle** [comment]
@rbgigo 
Merged the new API in the PR.
https://github.com/OpenLiberty/open-liberty/pull/9814

WebSecurityHelper.getSSOCookieFromSSOToken(AttributeNameConstants.WSCREDENTIAL_CACHE_KEY)
