### ISSUE TITLE
server skript line 1071:  missing ']'

### ISSUE THREAD

**Issue by igbluz** [OpenLiberty/open-liberty#8311]
With OL 19.0.0.7 when generating the runtime a server skript file is generated on the wlp/bin directory.
On line 1071 there is missing one space:
Error Line is:        if [ "${WLP_DEBUG_REMOTE}" = "y"]
Correct Line is:        if [ "${WLP_DEBUG_REMOTE}" = "y" ]

best regards,
Igor

**Comment by jhanders34** [comment]
This was recently fixed with PR #8218.
