### ISSUE TITLE
APSFOUND-267: Configure custom login modules for JCA and JMS connection factories

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#8330]
This feature is to enable the configuration of custom login modules for JCA and JMS connection factories in server configuration.

This applies to the following configuration elements:
connectionFactory
jmsConnectionFactory
jmsQueueConnectionFactory
jmsTopicConnectionFactory

**Comment by marikaj123** [comment]
Does the feature require translation?  If yes does the translated code exist in the stream?

**Comment by dave-waddling** [comment]
**FAT Focal Approval comment:** Hi, I've completed my review of the Feature Test Summary (#8706) and all is looking good. Therefore I'm adding the FAT Focal Approval at this time.

**Comment by marikaj123** [comment]
It is not WAD approved; therefore, it requires two approvals only: Globalization and FAT. Then you can move the feature to GA.

**Comment by lauracowen** [comment]
@njr-11 Should there be a release blog post issue for this? (appearing here: https://github.com/OpenLiberty/open-liberty/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3ABlog+label%3A%22release%3A190010%22+-label%3AEpic+-label%3Astory+-label%3AtWAS)

**Comment by njr-11** [comment]
@lauracowen yes, it can be included in the release blog post as a minor item, but I wouldn't go any further than that.  All that is done under this feature is adding the same attribute to connection factory configuration that was already available for dataSource configuration.

**Comment by lauracowen** [comment]
@njr-11 Okay, can you create a blog post issue briefly explaining that so that we can copy it into the release blog post, pls?

**Comment by marikaj123** [comment]
@njr-11 - Since all approvals were granted and the feature made it into the GM build, the feature can be closed after creating the blog.

**Comment by atosak** [comment]
@njr-11 Can we close this Epic?

**Comment by njr-11** [comment]
@atosak I had closed this Epic at one point.  However, I had to reopen it in order to add a GA blog issue as a child.  Until the child issue closes out, this Epic will need to remain open.

**Comment by lauracowen** [comment]
Sorry, I've closed the blog issue.

**Comment by njr-11** [comment]
That's nothing to be sorry about.  Having the blog issue is part of the process.  Now that it's closed, I'll go ahead and close out the Epic.
