### ISSUE TITLE
server with openidConnectClient-1.0 feature does not start

### ISSUE THREAD

**Issue by brutif** [OpenLiberty/open-liberty#8332]
There are bundle resolution errors when attempting to start a server containing this feature.
Tested with nightly build openliberty-all-19.0.0.8-cl190820190723-1900.zip
To recreate, add to server.xml: <feature>openidConnectClient-1.0</feature>
I tried the fix from openIdConnectServer but it did not resolve this one.

**Comment by naumanna** [comment]
Testing a potential fix now under #8359
