### ISSUE TITLE
Blog post for 19008 for Oracle ssl properties encryption support

### ISSUE THREAD

**Issue by frowe** [OpenLiberty/open-liberty#8334]
To help introduce the resolution of issue #7631, the following is a draft for a short blog entry for 19008 GA blog, on the newly added support for encryption of connectionProperties ssl passwords.

In this [Request for Enhancement (RFE)](https://www.ibm.com/developerworks/rfe/execute?use_case=viewChangeRequest&CR_ID=133168), you asked for OpenLiberty support for the use of encrypted ssl key and trust store passwords for Oracle datasources and we delivered it in #7631 !  Oracle users can set JDBC driver connection properties in the connectionProperties configuration element of server.xml.  Those connection properties include javax.net.sslKeyStorePassword and javax.net.sslTrustStorePassword whose values are passwords.  Until now, unlike many other config elements containing passwords, you could not encrypt these values, they had to be in clear text.  With the 19008 release, you can encrypt those values and OpenLiberty will decrypt them before sending them to the Oracle JDBC driver.  Passwords may be encrypted using the `encode` option of the OpenLiberty securityUtility script in the ${wlp.install.dir}/bin directory. See [here](https://www.ibm.com/support/knowledgecenter/en/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/rwlp_command_securityutil.html) for details on encrypting passwords for Liberty.  As an example:
Prior to 19008:
<dataSource id="oracleDS" jdbcDriverRef="OracleDriver" jndiName="jdbc/DictionaryDB">
     	<properties.oracle URL="jdbc:oracle:thin:@//...” connectionProperties="oracle.net.ssl_version=1.2;javax.net.ssl.keyStore=path-to-keystore/keystore.p12;**javax.net.ssl.keyStorePassword=WooHoo**; javax.net.ssl.trustStore= path-to-keystore/keystore.p12;**javax.net.ssl.trustStorePassword=password**”/>
    </dataSource>
After 19008:
<dataSource id="oracleDS" jdbcDriverRef="OracleDriver" jndiName="jdbc/DictionaryDB">
     	<properties.oracle URL="jdbc:oracle:thin:@//...” connectionProperties="oracle.net.ssl_version=1.2;javax.net.ssl.keyStore=path-to-keystore/keystore.p12;**javax.net.ssl.keyStorePassword={xor}CDAwFzAw**; javax.net.ssl.trustStore= path-to-keystore/keystore.p12;**javax.net.ssl.trustStorePassword={aes}AAbk9iEIjV06JSZMTpsW+6B+TjN+XjB2bs8hii2uZuMu**"/>
    </dataSource>

No more clear text ssl keystone passwords!

**Comment by lauracowen** [comment]
Thanks - will send you link to review when draft is ready
