### ISSUE TITLE
FAT for Jaeger support

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#8338]
Create a FAT to test a few JAX-RS calls and verify the traces are found in either STDOUT or a file using Jaeger.  We do not want to use the Jaeger backend in a build.

**Comment by tonyreigns** [comment]
The FAT has been created and will be transferred to Jennifer for later use.

**Comment by fmhwong** [comment]
@jennifer-c Please run the FAT code against this PR https://github.com/OpenLiberty/open-liberty/pull/8848
