### ISSUE TITLE
Password https://localhost:9443/ibm/api/

### ISSUE THREAD

**Issue by JCaymme** [OpenLiberty/open-liberty#8369]
Good afternoon
Guys I have not located the user and password to authenticate on https://localhost:9443/ibm/api/, does anyone know the user and password by kindness or somewhere in the documentation that I can locate?

**Comment by aguibert** [comment]
hi @JCaymme, if you haven't configured any registries in your server.xml, then there are no users/passwords defined for your server (you should see an error in the server logs about this).

The simplest way to get going with a basic user/password for your server is to use the `<quickStartSecurity>` element in your server.xml like this:
```xml
<server>

    <quickStartSecurity userName="admin" userPassword="admin"/>

    <!-- ... rest of server.xml -->
</server
```

**Comment by bpaskin-ibm** [comment]
Hi, you need to setup an administration id through quickStartSecurity or a repository.  This information can be found in the [Knowledge Center](https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_sec_mapadmin.html).  The link has examples that can used. Brian

**Comment by JCaymme** [comment]
I got access thank you very much.
Is another doubt normal to be blank?

![image](https://user-images.githubusercontent.com/12763879/61905199-e6e1e180-aefe-11e9-8b03-08cb04468290.png)

**Comment by aguibert** [comment]
the /ibm/api endpoint lists some of the available endpoints for the server -- such as `/metrics` as shown in your browser.

If you are trying to browse and interact with REST APIs in a web browser, I would recommend using MicroProifle OpenAPI. To use this feature, you can enable the `mpOpenApi-1.1` feature and go to http://localhost:9080/openapi/ui in your web browser. For full details on how to use MP OpenAPI, see this guide: https://openliberty.io/guides/microprofile-openapi.html#generating-the-openapi-document-for-the-inventory-service

**Comment by aguibert** [comment]
closing this issue because it's been inactive for a few weeks and I believe all of the OP's questions have been answered.

If there are still questions we can reopen or raise a new issue
