### ISSUE TITLE
GA BLOG: MicroProfile Context Propagation 1.0 in Open Liberty

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/open-liberty#8378]
_a. Which Liberty feature does it relate to?_

   _i. Human-readable name (eg WebSockets feature)_
MicroProfile Context Propagation 1.0

   _ii. Feature name (eg websockets-1.0)_
mpContextPropagation-1.0

   _iii. Is this a new feature or is it an update to an existing feature for this release?_
new

_b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc_
application developers

_c. Write a sentence or two that introduces it to someone new to the general technology/concept._
MicroProfile Context Propagation allows you to create pipelines of dependent stages that run with predictable thread context regardless of which thread the completion stage action ends up running on.

_d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)_
MicroProfile Context Propagation provides completion stages that run with predictable thread context and also benefit from being backed by the automatically-tuned Liberty global thread pool. Configuration of concurrency constraints and context propagation is possible programmatically with a fluent builder pattern where configuration defaults can be specified via MicroProfile Config.
 
_e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature._ 

Enablement in server.xml:
```
  <featureManager>
    <feature>mpContextPropagation-1.0</feature>
    <feature>cdi-2.0</feature> <!-- used in example -->
    <feature>jndi-1.0</feature> <!-- used in example -->
    ... other features
  </featureManager>
```

Example usage of programmatic builders:
```
import org.eclipse.microprofile.context.ManagedExecutor;
import org.eclipse.microprofile.context.ThreadContext;
...

ManagedExecutor executor = ManagedExecutor.builder()
    .maxAsync(5)
    .propagated(ThreadContext.APPLICATION, ThreadContext.SECURITY)
    .build();

CompletableFuture<Integer> stage1 = executor.newIncompleteFuture();
stage1.thenApply(function1).thenAccept(value -> {
    try {
        // access resource reference in application's java:comp namespace,
        DataSource ds = InitialContext.doLookup("java:comp/env/jdbc/ds1");
        ...
    } catch (Exception x) {
        throw new CompletionException(x);
    }
};
...
stage1.complete(result);

...
// Shut down managed executor once the application no longer needs it
executor.shutdown();
```

Example usage in a CDI bean:
```
// CDI qualifier which is used to identify the executor instance
@Qualifier
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.FIELD, ElementType.METHOD, ElementType.PARAMETER })
public @interface AppContext {}

// Example producer field, defined in a CDI bean,
@Produces @ApplicationScoped @AppContext
ManagedExecutor appContextExecutor = ManagedExecutor.builder()
    .propagated(ThreadContext.APPLICATION)
    .build();

// Example disposer method, also defined in the CDI bean,
void disposeExecutor(@Disposes @AppContext exec) {
    exec.shutdownNow();
}

// Example injection point, defined in a CDI bean,
@Inject @AppContext
ManagedExecutor executor;

...

CompletableFuture<Integer> stage = executor
    .supplyAsync(supplier1)
    .thenApply(function1)
    .thenApplyAsync(value -> {
        try {
            // access resource reference in application's java:comp namespace,
            DataSource ds = InitialContext.doLookup("java:comp/env/jdbc/ds1");
            ...
            return result;
        } catch (Exception x) {
            throw new CompletionException(x);
        }
    });
```

_f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology._

JavaDoc API can be found here:
https://openliberty.io/docs/ref/microprofile/3.0/#package=org/eclipse/microprofile/context/package-frame.html&class=org/eclipse/microprofile/context/package-summary.html

Spec binaries and Maven coordinates can be found here:
https://github.com/eclipse/microprofile-context-propagation/releases/tag/1.0

Context Propagation 1.0 specification:
http://download.eclipse.org/microprofile/microprofile-context-propagation-1.0/microprofile-context-propagation.html

_g. Attach any images to this work item as .png files._
no images attached

**Comment by lauracowen** [comment]
Thanks
