### ISSUE TITLE
NLS message inserts wrong in com.ibm.ws.security.common

### ISSUE THREAD

**Issue by pnickoll** [OpenLiberty/open-liberty#842]
We have the {0} insert twice in the following message. I have asked the translators to assume the second insert should be {1}, but this would need correcting in the English file too so raising this issue to cover fixing the English file.

Filename : com.ibm.ws.security.common\com\ibm\ws\security\common\internal\resources\SSOCommonMessages.nlsprops

CONFIG_REQUIRED_ATTRIBUTE_NULL_WITH_CONFIG_ID</TWBCTX>=CWWKS6105W: <TWBQ>The configuration attribute [{0}] that is required is missing or empty in the configuration [{0}] and a default value is not provided

**Comment by pnickoll** [comment]
Assigning this to you Adam as I believe you wrote the message and I'd like to check my assumptions above were correct.

**Comment by ayoho** [comment]
Indeed, looks like I missed that in https://github.com/OpenLiberty/open-liberty/pull/392. I'll get a change going to fix it.
