### ISSUE TITLE
Custom fields not logging when using LogRecordContext

### ISSUE THREAD

**Issue by jpfloresibm** [OpenLiberty/open-liberty#8422]
When json logging is configured and LogRecordContext is used to add custom fields to the debug logs using LogRecordContext, the custom fields are not showing up in the logs.

Steps to reproduce:
1. Enable json logging by configuring the following in the server's server.env
```
WLP_LOGGING_MESSAGE_FORMAT=json
WLP_LOGGING_MESSAGE_SOURCE=message,trace,accessLog,ffdc,audit
WLP_LOGGING_CONSOLE_FORMAT=json
WLP_LOGGING_CONSOLE_LOGLEVEL=info
WLP_LOGGING_CONSOLE_SOURCE=message,trace,accessLog,ffdc,audit
```
2. add the following in the application code:
```
 LogRecordContext.addExtension("userName","don");
 LogRecordContext.addExtension("isGoldCustomer_bool","true");
 logger.debug("This is a test...");
```

When the application code is run the following is seen in the messages output (notice custom fields `userName` and `isGoldCustomer_bool` not being logged):
```
{"type":"liberty_message","host":"localhost","ibm_userDir":"\/usr\/ibmpacks\/current\/mdmexpress\/wlp\/usr\/","ibm_serverName":"bigmatch-server","message":"This is a test...","ibm_threadId":"0000022f","ibm_datetime":"2019-07-30T19:46:29.030+0000","module":"com.ibm.entity.analytics.graph.api.rest.service.CollectionService","loglevel":"INFO","ibm_methodName":"getAllCollections","ibm_className":"com.ibm.entity.analytics.graph.api.rest.service.CollectionService","ibm_sequence":"1564515989030_00000000000D4"}
```

Attached is the sample application and server config used to reproduce the issue:
[loggingProject.zip](https://github.com/OpenLiberty/open-liberty/files/3452616/loggingProject.zip)

**Comment by donbourne** [comment]
@jpfloresibm , thanks very much for opening this.  We're investigating.  At first look it appears that the LogRecordContext content is properly used when logging with JUL, but for some reason we're seeing it not get used when logging with SLF4J.
