### ISSUE TITLE
GA BLOG: Introspector for Zip Cache

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#8445]
Refs: 
Design Issue: "Introspector for Zip Cache": https://github.com/OpenLiberty/open-liberty/issues/7868
Issue/Story: "Implement Introspctor for Zip Cache": https://github.com/OpenLiberty/open-liberty/issues/8441
Pull Request: https://github.com/OpenLiberty/open-liberty/pull/8148
Open-Liberty Doc Issue: "ID for Introspector for Zip Cache": https://github.com/OpenLiberty/docs/issues/477

Draft documentation (cross linked from the open-liberty doc issue): https://github.com/OpenLiberty/docs/files/3457598/zipCacheIntrospector.draft.01-Aug-2019.txt

**Comment by lauracowen** [comment]
Removed from blog post as its audience is more support. Will save content though.
