### ISSUE TITLE
GA BLOG for app-passwords/app-tokens 

### ISSUE THREAD

**Issue by brutif** [OpenLiberty/open-liberty#8453]
Here's the template:
if not previously published in a blog post, please answer the following questions:

a. Which Liberty feature does it relate to? **openidConnectServer-1.0**

   i. Human-readable name (eg WebSockets feature). **OpenID Connect Server**

   ii. Feature name (eg websockets-1.0) **openidConnectServer-1.0**

   iii. Is this a new feature or is it an update to an existing feature for this release? 
**Feature is new to open liberty as of 19007. These functions are an update to the feature.**

b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc.  **non-browser app developers and  appserver administrators**
c. Write a sentence or two that introduces it to someone new to the general technology/concept.

**OpenID Connect is a technology that allows delegation of user authentication to an external security provider.** 

d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)

**Liberty's OpenID Connect Server feature now includes support for long lived application passwords and application tokens, for use by non browser applications.  Users can acquire these and submit them to a non-browser application, which can then use them to access secured resources on servers configured to accept OAuth access tokens from the OpenID Connect server.  The user's password is never exposed to the non-browser app, and the tokens can be revoked independently if needed. App-passwords are exchanged repetitively by the non-browser app for short lived access tokens using a standard OAuth ROPC flow,  so if an access token is ever compromised, it is not valid for long.  App-tokens are long lived access tokens.**

**Web and REST interfaces for users and administrators are added to administer these tokens.
A new UI for managing client registration is also added.**
 
e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.

Create a new Liberty server and use this server.xml.   Comments in server.xml explain the new configuration attributes.  This server doesn't have a  backing database so is for demo purposes only. 
```xml
<server>
    <featureManager>      
      <feature>openidConnectServer-1.0</feature>     
    </featureManager>

    <openidConnectProvider id="OP" oauthProviderRef="OAuth" 
        signatureAlgorithm="RS256" keyStoreRef="defaultKeyStore" 
        jwkEnabled="true"
    >
    </openidConnectProvider>
    
    <!-- internalClientID and internalClientSecret match a defined 
         client and are used in creating app-passwords and app-tokens.
         passwordGrantRequiresAppPassword enables the ROPC flow to 
         exchange app-passwords for short-lived access tokens.
         appPasswordLifetime and appTokenLifetime set the lifetime of these tokens.
    --> 
    <oauthProvider id="OAuth" tokenFormat="mpjwt" 
      passwordGrantRequiresAppPassword="true" 
      internalClientId="RP" 
      internalClientSecret="thesecret" 
      appPasswordLifetime="30d"
      >
        <!-- 
         localStore for demo use, a backing database is used instead in production. 
         When localStore is used, all client data and token status is held
         in memory only. 
        --> 
        <localStore>
         
          <!-- appPasswordAllowed and appTokenAllowed allow 
          this client to create app-passwords and app-tokens -->
          <client displayname="RP" enabled="true"
                name="RP" secret="thesecret" 
                scope="openid profile email"
                preAuthorizedScope="openid profile email"
                appPasswordAllowed="true"
                appTokenAllowed="true"
          >                  
                <redirect>https://localhost:19443/oidcclient/redirect/RP</redirect>
          </client>    
        </localStore>
    </oauthProvider>
     
    <oauth-roles>
        <authenticated>
            <special-subject type="ALL_AUTHENTICATED_USERS" />  
        </authenticated> 
         <tokenManager>
           <!-- this user can manage the app-passwords and tokens of other users -->
            <user name="admin" />
        </tokenManager> 
    </oauth-roles>

    <!-- Basic registry for test / development use. -->   
    <basicRegistry id="basic" realm="customRealm">
        <user          
          name="admin"
          password="adminpwd" />
        <user
          name="demouser2"
          password="demopassword2" />
         <group name="users">
             <member name="admin"/>
             <member name="demouser2" />
        </group>
    </basicRegistry>

    <httpEndpoint id="defaultHttpEndpoint" host="*" httpPort="29080" httpsPort="29443" />
    <keyStore id="defaultKeyStore" password="keyspass" />  

</server>
```

Now users can request and manage their own tokens at 
`https://host:port/oidc/endpoint/(provider id)/personalTokenManagement`.   Token admins can administer the tokens of other users at `https://host:port/oidc/endpoint/(provider id)/usersTokenManagement`.  Servers using a database  (not this demo) can now manage client  registration at `https://host:port/oidc/endpoint/(provider id)/clientManagement`.

To try it out, start the server and log in as admin, adminpwd at 
`https://localhost:29443/oidc/endpoint/OP/personalTokenManagement`

Your app-passwords and tokens might look something like this:

![image](https://user-images.githubusercontent.com/26486297/63465347-a9517500-c426-11e9-8a4a-b7356072617d.png)

These  tokens can be submitted to non-browser applications, which can in turn use them when accessing secured resources on  servers configured to accept access tokens from the OpenID Connect server.  

**DO WE HAVE ROOM FOR 2 MORE SCREENSHOTS AS MICHAL SUGGESTS?**
 
f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

g. Attach any images to this work item as .png files.

**Comment by brutif** [comment]
@pnickoll @rickettmwork @dbarfield @lauracowen  Note recent edits, thanks.

**Comment by lauracowen** [comment]
Thanks. After this, can you make any other edits as comments instead of to the original description (so we can see what the changes are easily), pls.

**Comment by lauracowen** [comment]
Removed from 19008 release so I've relabelled this issue.

**Comment by mbroz2** [comment]
I would recommend cropping the /personalTokenManagement to just the content and not the entire browser.  
I would also recommend adding a screenshot for /clientManagement (and maybe /usersTokenManagement).

**Comment by brutif** [comment]
Thanks Michal, I cropped it and asked in the body if she thinks we have room for two more.

**Comment by lauracowen** [comment]
Add more screenshots if you like. :)

**Comment by brutif** [comment]
@mbroz2 would your team like to contribute the screenshots?   Or I can...

**Comment by mbroz2** [comment]
Sure, I'll upload them soon

**Comment by mbroz2** [comment]
/personalTokenManagement
![image](https://user-images.githubusercontent.com/3076261/63604671-00c02400-c592-11e9-82d5-7eaa8f784301.png)

/usersTokenManagement
![image](https://user-images.githubusercontent.com/3076261/63606367-85607180-c595-11e9-972d-325427bf25aa.png)

/clientManagement
![image](https://user-images.githubusercontent.com/3076261/63613976-8b5f4e00-c5a7-11e9-8bd2-62326f6f72d5.png)
