### ISSUE TITLE
GA BLOG: Introspector for Overlay Containers

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#8479]

**Comment by tbitonti** [comment]
[overlayIntrospector.draft.01-Aug-2019.txt](https://github.com/OpenLiberty/open-liberty/files/3468605/overlayIntrospector.draft.01-Aug-2019.txt)

**Comment by tbitonti** [comment]
Refs:
Design Issue: "Introspector for Overlay Containers"
https://github.com/OpenLiberty/open-liberty/issues/7869

Story: "Implement Introspector for Overlay Container"
https://github.com/OpenLiberty/open-liberty/issues/8478

Pull Request: "Overlay Container Introspector"
https://github.com/OpenLiberty/open-liberty/pull/8416

ID: "GA BLOG: Introspector for Overlay Containers"
https://github.com/OpenLiberty/open-liberty/issues/8479

**Comment by lauracowen** [comment]
Removed from blog post as its audience is more support. Will save content though.
