### ISSUE TITLE
server javadump can't produce core due to soft limit

### ISSUE THREAD

**Issue by davebachmann** [OpenLiberty/open-liberty#8485]
When we try to collect a system core on Linux with
server javadump runtime --include=system
it fails at first because the default softlimit for RLIMIT_CORE is 0
This stops data collection on a problem in its  tracks until you can change the ulimit and restart the jvm.

It would be very helpful if the RLIMIT_CORE was temporarily increased to whatever the hard limit is, before the child is forked and killed to create the core file.  Then it can be set back afterwards.

**Comment by aguibert** [comment]
hi @davebachmann, thanks for raising this issue. We've considered the possibility of raising the ulimit in the past, but ultimately have decided to let the JDK tune itself.

Can you include some additional information such as:
1. What the ulimit is currently set at
1. The full java version you are using

**Comment by aguibert** [comment]
related to the discussion we had on #6379

**Comment by covener** [comment]
@aguibert Re: #6379 my 4/2019 openjdk+openj9 on linux doesn't raise the soft corefile limit the way it does with file descriptor limit,  which makes some sense.  Raising the former automatically could inadvertently tie up lots of i/o and disk space in the event of a crash that requires more of an opt-in than file descriptors.

**Comment by davebachmann** [comment]
Hi @aguibert the core ulimit was originally not set in /etc/security/limits.conf or in any file under /etc/security/limits.d so it was defaulting to a soft limit of 0 and a hard limit of unlimited.  Once I added a line to /etc/security/limits.conf setting it to unlimited for both soft and hard, and then restarted the jvm to pick up the new ulimit, then I was able to get a core file to be created.

The jvm version is JRE 1.8.0 Linux amd64-64 (build 8.0.5.27 - pxa6480sr5fp27-20190104_01(SR5 FP27))
The linux kernel is Linux 3.10.0-862.14.4.el7_1.iss8_1.6.x86_64

My thought was that in the event that a system dump is being requested via
server javadump runtime --include=system
then the user clearly intends for a core file to be generated, so if the hard limit does allow for it, then it would be reasonable to temporarily increase the soft limit, if it is currently less than the hard limit, via a call to setrlimit(RLIMIT_CORE, &core_limit) and after creating the core restore the ulimit back to its previous value.

**Comment by gjdeval** [comment]
We see these problems all the time, where the customer needs to collect a core file for diagnosis and they trip over OS issues, on Linux specifically core file size limit and core file routing (target location is unusable for some reason, e.g. not writable by the JVM process owner). And when it happens we go back and forth with the customer trying to figure out the particular issue, and help them understand how to resolve it. 
It would be really nice if 'server javadump' could smooth that path ... ideally we would check the ulimit and the core path definition, alert the user to any issues, and offer modifications of these settings which the user could approve or decline.
Not sure how practical that is, but would be a really helpful diagnostic usability improvement.
@donbourne  probably has some thoughts on this.

**Comment by donbourne** [comment]
This might actually be something that the IBM JDK would be able to help with diagnostics for.  While I could see OpenLiberty trying to add some of this, the JVM may be in a better position to report on issues that require more direct access to the host OS.  So perhaps that could be a combination of the JVM reporting the exact problem (eg. file system full, file ownership issue, ulimit setting issue, etc.), and Liberty reporting what is unable to continue due to the underlying issue the JVM reported.

**Comment by kgibm** [comment]
J9 already implicitly increases the core limit from soft to hard when requested to take a core dump through `com.ibm.jvm.Dump.SystemDump`.

@davebachmann are you using IBM Java/OpenJ9 or HotSpot?

**Comment by gjdeval** [comment]
@kgibm  Dave's out on vacation this week, so I'll reply to this question - they are using J9 sr5-fp27.

**Comment by kgibm** [comment]
Oh, yeah, I see his Java version in another comment now. Interesting, in that case, my suspicions are:

1. The core hard ulimit wasn't actually unlimited.
2. Liberty uses some mechanism other than `Dump.SystemDump()` to create the core (not sure what that would be).
3. There's a bug in J9 or the kernel increasing the ulimit.

(1) is the easiest to verify - please provide the `1CIUSERLIMITS` section of the produced javacore.

I'll check on (2)...

**Comment by kgibm** [comment]
Confirmed for (2) that Liberty is using `com.ibm.jvm.Dump.systemDumpToFile`: https://github.com/OpenLiberty/open-liberty/blob/release-19.0.0.8/dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/internal/commands/JavaDumper.java#L30

Here's the call to `setrlimit` in OpenJ9 to use the core hard ulimit: https://github.com/eclipse/openj9-omr/blob/v0.15.0-release/port/unix/omrosdump.c#L307

**Comment by kgibm** [comment]
Note that J9 doesn't actually check the return value of `setrlimit` so there might be some error from the OS (also potentially on the `getrlimit` call). Assuming (1) reports in the javacore that the core hard ulimit was set to unlimited, then I think the next step would be to `strace` the process for `getrlimit` and `setrlimit` calls (let me know if you need help on that).

I've also opened a J9 issue: https://github.com/eclipse/openj9-omr/issues/35

**Comment by davebachmann** [comment]
Hi @kgibm here is the 1CIUSERLIMITS section from the produced javacore when server javadump would not produce a core.

1CIUSERLIMITS  User Limits (in bytes except for NOFILE and NPROC)
NULL           ------------------------------------------------------------------------
NULL           type                            soft limit           hard limit
2CIUSERLIMIT   RLIMIT_AS                        unlimited            unlimited
2CIUSERLIMIT   RLIMIT_CORE                              0            unlimited
2CIUSERLIMIT   RLIMIT_CPU                       unlimited            unlimited
2CIUSERLIMIT   RLIMIT_DATA                      unlimited            unlimited
2CIUSERLIMIT   RLIMIT_FSIZE                     unlimited            unlimited
2CIUSERLIMIT   RLIMIT_LOCKS                     unlimited            unlimited
2CIUSERLIMIT   RLIMIT_MEMLOCK                       65536                65536
2CIUSERLIMIT   RLIMIT_NOFILE                        16000                16000
2CIUSERLIMIT   RLIMIT_NPROC                         10240                10240
2CIUSERLIMIT   RLIMIT_RSS                       unlimited            unlimited
2CIUSERLIMIT   RLIMIT_STACK                       8388608            unlimited
2CIUSERLIMIT   RLIMIT_MSGQUEUE                     819200               819200
2CIUSERLIMIT   RLIMIT_NICE                              0                    0
2CIUSERLIMIT   RLIMIT_RTPRIO                            0                    0
2CIUSERLIMIT   RLIMIT_SIGPENDING                   128061               128061

**Comment by davebachmann** [comment]
I had to change /etc/security/limits.conf to set unlimited core before I could get a good core.  

`*               soft    core            unlimited
`

Once I did that then the 1CIUSERLIMITS section reflected the increased RLIMIT_CORE:

```
1CIUSERLIMITS  User Limits (in bytes except for NOFILE and NPROC)
NULL           -----------------------------------------------------------------
-------
NULL           type                            soft limit           hard limit
2CIUSERLIMIT   RLIMIT_AS                        unlimited            unlimited
2CIUSERLIMIT   RLIMIT_CORE                      unlimited            unlimited
2CIUSERLIMIT   RLIMIT_CPU                       unlimited            unlimited
2CIUSERLIMIT   RLIMIT_DATA                      unlimited            unlimited
2CIUSERLIMIT   RLIMIT_FSIZE                     unlimited            unlimited
2CIUSERLIMIT   RLIMIT_LOCKS                     unlimited            unlimited
2CIUSERLIMIT   RLIMIT_MEMLOCK                       65536                65536
2CIUSERLIMIT   RLIMIT_NOFILE                         1024                 4096
2CIUSERLIMIT   RLIMIT_NPROC                        128061               128061
2CIUSERLIMIT   RLIMIT_RSS                       unlimited            unlimited
2CIUSERLIMIT   RLIMIT_STACK                       8388608            unlimited
2CIUSERLIMIT   RLIMIT_MSGQUEUE                     819200               819200
2CIUSERLIMIT   RLIMIT_NICE                              0                    0
2CIUSERLIMIT   RLIMIT_RTPRIO                            0                    0
2CIUSERLIMIT   RLIMIT_SIGPENDING                   128061               128061

```

**Comment by kgibm** [comment]
> Hi @kgibm here is the 1CIUSERLIMITS section from the produced javacore when server javadump would not produce a core.

Interesting, so from that it seems that it should have increased the core ulimit to the hard limit of unlimited. Can you reproduce the problem with strace? Example command:

```
strace -f -tt -o outputfile.txt -p $PID
```

**Comment by davebachmann** [comment]
Thanks for the reminder @kgibm 
I've been collecting strace output with the default RLIMIT_CORE of 0 soft and unlimited hard, as well as when I change the soft RLIMIT_CORE to unlimited.
Of course, now that I have it under the microscope the core files are being created without problem.
I can see in both sets of straces the call to getrlimit and then setrlimit for RLIMIT_CORE.

Here are the calls on the process with soft limit 0:

2109  15:29:49.962099 getrlimit(RLIMIT_CORE, {rlim_cur=0, rlim_max=RLIM64_INFINITY}) = 0
2109  15:29:50.377654 setrlimit(RLIMIT_CORE, {rlim_cur=RLIM64_INFINITY, rlim_max=RLIM64_INFINITY}) = 0

So the behavior I was seeing before of core files not being creating seems to no longer reproduce.

A side issue is that server javadump still fails because the core is owned by root so the java process can't read it, but I think that's due to some ancestor of the java process having setuid before it was started.

Since my original problem of no core file being produced is not reproducible at this time, I'll go ahead and close the issue.
Thanks for your help.
