### ISSUE TITLE
RM: Check servicability requirements

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#8492]
Check that it's possible to get enough information out of RM and the Kafka connector to do problem determination.

Probably a good idea to take notes on what's possible and how to do it in preparation for #8226

**Comment by tevans78** [comment]
PR #8602 improves the exception handling so that it is slightly easier to determine the cause of a problem.

We also need to look into how easy it is to adjust the kafka client logging.

**Comment by tevans78** [comment]
For now, the kafka client logging section of this issue is documentation only. We're not going to make any more code changes.

**Comment by tevans78** [comment]
Documentation of trace options will be covered in the blog.
https://github.com/OpenLiberty/open-liberty/issues/6682#issuecomment-523988498
