### ISSUE TITLE
Cannot retrieve info on OAuth client having Self assigned client ID with blanks 

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/open-liberty#8516]
I created an OAuth client with a client ID and Name of `'la .           something'`.

When I query for all registered clients from the OIDC clientManagement application with
`https://localhost:29443/oidc/endpoint/OP/registration/`
the client is returned:

![image](https://user-images.githubusercontent.com/29490139/62581710-a031a700-b86f-11e9-8823-3adaa7e21ad5.png)

However, when I go to edit that client I query for its definition by issuing a GET
`https://localhost:29443/oidc/endpoint/OP/registration/la%20.%20%20%20%20%20%20%20%20%20%20%20something`
and it fails with "CWOAU0073E: An error was encountered while authenticating a user. Please try authenticating again, or contact the site administrator if the problem persists."
Status code is 404 (Not Found) (edited)

**Comment by dmorgant** [comment]
In further testing.....it turns out that when a space exists in the client ID (not name) then a delete operation will also fail.  The ID is not getting encoded to handle the space.

For example,  registering a client with a client ID and name of 'test a' will return  
"registration_client_uri":"https://localhost:29443/oidc/endpoint/OP/registration/test a".
So, I believe this space in the client id is what is preventing the API from working.

This fails using just regular postman too, so should be recreateable.

**Comment by mbroz2** [comment]
I just hit this as well.

**Comment by ayoho** [comment]
@dmorgant Can you confirm that this has been fixed? As I mentioned to you a couple weeks ago, client IDs with leading or trailing spaces still shouldn't work, but spaces within the ID should work now.

**Comment by dmorgant** [comment]
@ayoho I tested and it is now working.  Thank you
