### ISSUE TITLE
Need to complete oidc server certification 

### ISSUE THREAD

**Issue by frank870117** [OpenLiberty/open-liberty#8536]

**Comment by frank870117** [comment]
https://op.certification.openid.net:60000/ 
click on "List", then search + click on "https://oidcop.mybluemix.net:8080/oidc/endpoint/OP", then click on the "Intern" tag to see the results. 
If you want to change the configuration, then you click on the "Reconfigure" button. It will reset the test results. 
The application is currently being hosted on my cloud. After my internship ends, it might be deactivated. Therefore, you might need to host another simple application on IBM Cloud.

**Comment by ayoho** [comment]
This issue isn't strategic for us right now, so I'm going to close this.
