### ISSUE TITLE
RM: Review external names

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#8551]
We need to confirm
- The name of the connector (currently `io.openliberty.kafka`)
   Suggest `liberty-kafka`
- The name of the login module (currently `com.ibm.ws.kafka.security.LibertyLoginModule`)
- The property names for the outgoing connector
   `topic`
- The property names for the incoming connector
   `topics` - suggest this should just be `topic`
   `unacked.limit`

**Comment by tevans78** [comment]
For comparison, here is the SmallRye config: https://smallrye.io/smallrye-reactive-messaging/#_interacting_with_apache_kafka

**Comment by tevans78** [comment]
* Changed the connector ID to `liberty-kafka` - #8648
* login module name is fine, stays the same
* Changed to a single inbound topic - #8670
* `unacked.limit` stays the same but default in increased
