### ISSUE TITLE
Pull in MyFaces 2.3.6

### ISSUE THREAD

**Issue by wtlucy** [OpenLiberty/open-liberty#8563]
Current fixlist for MyFaces 2.3.5 (used for `jsf-2.3`):
https://issues.apache.org/jira/browse/MYFACES-4299?jql=project%20%3D%20MYFACES%20AND%20fixVersion%20%3D%202.3.5

We are going to pass on 2.3.5 due to https://issues.apache.org/jira/browse/MYFACES-4309

We will pull in MyFaces 2.3.6 when it is available in the coming weeks.

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsfContainer_fat_2.3,com.ibm.ws.jsf_fat,com.ibm.ws.jsf.2.2,com.ibm.ws.jsf_fat_lWAS_jsf2.3,com.ibm.ws.jsf_fat_jsf2.3
