### ISSUE TITLE
RM: Default logging from kafka client seems overly verbose

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#8564]

**Comment by Azquelt** [comment]
It looks like the Kafka client itself logs quite a bit on connection at the INFO level. By default this will go to the messages.log.

We should make sure we document how to alter the Kafka logging level as it will be common for users to want to either turn off this logging, or to get more detailed logging to diagnose problems, as Kafka tends to quietly retry for a while in the face of issues.

**Comment by tevans78** [comment]
I have verified that using SLF4J and JUL, the trace and logging can be controlled as expected; e.g.
```
com.ibm.ws.logging.trace.specification = org.apache.kafka.*=WARNING
```
This will be added to the blog post

**Comment by tevans78** [comment]
The logging is not verbose if you only make a single connection. If you connect and disconnect over and over then there is a lot of trace but this is an unusual usage scenario. If that really is what you want to do then the trace can be turned off as described abover.
