### ISSUE TITLE
Reduce code over-riding from CXF/RestEasy

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#8621]
The current process (for Liberty, and soon for tWAS) for pulling in Apache CXF and RESTEasy is to pull in the release binary, and then override (in GitHub/CMVC) some files to glue it into WAS. It would be preferable to avoid the overriding if possible - this might involve changing the CXF/RESTE code to be more flexible - so that it can accept its configuration from non-CXF/RESTEasy sources, etc.

 

The ultimate goal of this feature would be to avoid overriding any CXF/RESTEasy code - however, as part of this feature we should evaluate the code that we already override and perform a cost-benefit analysis of the effort.

**Comment by tevans78** [comment]
A design issue has also been opened: #13920

**Comment by neuwerk** [comment]
I'm currently working on an upgrade of CXF 3.4.3 to 3.5.5. Part of the update is to dentify what overrides could be dropped post update, what updates we should try to commit back to CXF, and just a general clean up of what changes we are making in the overrides. If we can keep up with this type of identification, we should minimize both the current overrides as well as future overriding.

**Comment by neuwerk** [comment]
I've gotten the CF upgrade merged (https://github.com/OpenLiberty/open-liberty/pull/25447). I think this goes a long way to help put in place a format for maintaining our CXF overrides. I've been able to drop the duplicates that I could verify. There's also plans in place to push a portion of our performance related overrides back to the Apache CXF repo, which once in place will allow us to drop those changes.

**Comment by cbridgha** [comment]
We are deciding to close this feature, as great progress has been made consuming the cxf libraries, reducing overrides where possible, and a good maintenance plan is in place.
  Any significant changes in this area will be handled by a separate issue, and prioritized appropriately.
