### ISSUE TITLE
Deliver MicroProfile 3.2

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#8622]

**Comment by jhanders34** [comment]
Even though it isn't marked ready for focal approvals I am going to mark it approved for perf since we have tested both of the sub features that are included in MP 3.1.

**Comment by marikaj123** [comment]
Approving as no translation is needed.

**Comment by skasund** [comment]
No STE required for this feature.  I've provided the STE approval.

**Comment by marikaj123** [comment]
Can we have the WAD or No WAD label added to the Epic, please.

**Comment by Emily-Jiang** [comment]
Since MicroProfile 3.1 was declared faulty and released MP 3.2, we will not support MicroProfile 3.1. Hence update this feature to MicroProfile 3.2.

**Comment by chirp1** [comment]
From discussions with Tom, doc updates would seem to be just javadoc, which the developer would address. The general topic on MP wouldn't need updating. Approving.

**Comment by marikaj123** [comment]
Emily, Thank you for confirming the feature did make the GM release 190012. When you can please close the feature.  Thank you.

**Comment by tevans78** [comment]
Closing, we already doubled checked that the microProfile3 package and microProfile-3.2 feature work.
