### ISSUE TITLE
Problem with jsonb serializationcontext when Jackson is in classpath

### ISSUE THREAD

**Issue by bmhm** [OpenLiberty/open-liberty#8623]
Hi everyone!

I have a jaxrs-2.1 webapp which also uses the features `jsonb-1.0` and `jsonp-1.1`.
I tested this issue on wlp18.0.0.4 through wlp19.0.0.7 and openliberty 18.0.0.4 through 19.0.0.1.

I got a couple of Serializers for a 3rd party package. As the classes can be stitched together dynamically, in those Serializers, I am invoking `ctx.serialize(object.someProperty(), generator)`. Where someProperty also has a `SomePropertySerializer` which is then invoked.

I recently added another jar (runtime only) to my webapp. It comes with a dependency on jackson (and jackson-databind).
Since then, the call to `ctx.serialize(object.someproperty(), generator)` on the top Jsonb Serializer will only output an empty object. The nested Jsonb Serializer is not being invoked anymore.

It seems, as soon as jackson is on the classpath, Liberty will use Jackson.
To prevent this I tried the following without success:
* adding `@Provider class JsonbProvider implements ContextResolver<Jsonb>`.
* Adding a `MessageBodyWriter<Object>` using `@Provider @Produces(MediaType.APPLICATION_JSON) class JsonbMessageBodyWriter`.

Both did not help.

Shading the other dependency is not an option, as shading means delivery without test (behaviour will probably change).

Can (Open) Liberty be forced to not discover Jackson from a jar inside the `.war` file?

**Comment by bmhm** [comment]
Oh hey, removing that jackson dependency did not help either.
I think it is related to https://github.com/eclipse-ee4j/yasson/issues/164. I think OpenLiberty does not ship a somewhat recent version of yasson. Is this a reasonable assumption?

**Comment by bmhm** [comment]
I tried to disable the features `jsonp` and `jsonb`, but with no luck. Because of jaxrs they are still activated and will override the `yasson` library contained inside the `.war` file.

My guess is that the yasson version shipped in liberty (which is 1.0.1 or 1.0.2) is outdated, yasson 1.0.3 fixes some related issues.

I just wonder: When I ship my own Jackson implementation, that is being used. If I ship my own yasson implementation, that is ignored.
The error message rendered in the stdout log (messages.log) is very odd: `javax.json.bind.spi.JsonbProvider: Provider org.eclipse.yasson.JsonBindingProvider not a subtype`.

That message does not seem to be emitted by the `jakarta.json.bind-api` binding. Maybe it is from the older `javax.json.bind-api:javax.json.bind` dependency (which might still be shipped in liberty).

**Comment by bmhm** [comment]
OK got the issue.
I implemented my own `MessageBodyWriter<Object>`. Removing it solved the issue.

Although I was using my own Instance of Jsonb, the Context somehow got messed up.

Is this supposed to happen?

**Comment by WhiteCat22** [comment]
Hi @bmhm, When you create your own MessagerBodyWriter it takes priority over our pre packaged MBWs if ```isWritable()``` returns true for the object you are trying to serialize.

The reason Jackson's MWB is being picked up is because we scan all classes in a customer's application for ```@Provider``` annotated classes by default. If you do not want ALL providers added to your application, you'll have to override the ```getClasses()``` method in your Application class to return just the classes you want your application to use.

Here is one of our test classes as an example:
https://github.com/OpenLiberty/open-liberty/blob/3a7577f471130f0c6e90f205f6d44b121399bf7b/dev/com.ibm.ws.jaxrs.2.0.client_fat/test-applications/jackson/src/com/ibm/ws/jaxrs20/client/fat/jackson/service/JacksonPOJOApplication.java

**Comment by bmhm** [comment]
Hi and thanks!
I just found out that there is or was also an issue with liberty profile / open liberty before 19.0.0.2 (at least) which confused me. Must have been fixed somewhere between .2 and .7.

I'll see on Monday of it works correctly and let you know. If it does (I believe so), I'm gonna close this issue.

You can tag this one as question of you like, because it seems I also stumbled over a fixed bug.

**Comment by WhiteCat22** [comment]
Cool, I recall the issue you are talking about but not the details. We've also recently added support for jsonb context with our prepackaged jsonb MBW.

**Comment by bmhm** [comment]
Thanks, this explains a lot. I did not figure out why - even on the same system sand same configuration - serializers stopped working or not being found.

**Comment by bmhm** [comment]
Hello @WhiteCat22.

The problem persists, but in a different way.
After removing the `@Provider` annotation from the library, it loaded well and the HTTP endpoints were  working again.

The library contains a `MessageBodyReader<JsonNode>` which is registered via `javax.ws.rs.core.Feature` using the default jaxrs client. The MBR only contains `return ObjectMapper.readTree(inputStream)`.

With this setup I get this exception:

```
Caused by: javax.json.bind.JsonbException: Can't create instance
        at org.eclipse.yasson.internal.ReflectionUtils.createNoArgConstructorInstance(ReflectionUtils.java:205)
        at org.eclipse.yasson.internal.serializer.ObjectDeserializer.getInstance(ObjectDeserializer.java:94)
        at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserialize(AbstractContainerDeserializer.java:61)
        at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:70)
        at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:56)
        at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:53)
        at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:93)
        at com.ibm.ws.jaxrs21.providers.json.JsonBProvider.readFrom(JsonBProvider.java:125)
        at org.apache.cxf.jaxrs.utils.JAXRSUtils$2.run(JAXRSUtils.java:1435)
        at java.security.AccessController.doPrivileged(AccessController.java:703)
        at org.apache.cxf.jaxrs.utils.JAXRSUtils.readFromMessageBodyReader(JAXRSUtils.java:1432)
        at org.apache.cxf.jaxrs.impl.ResponseImpl.doReadEntity(ResponseImpl.java:445)
        ... 56 more
Caused by: java.lang.InstantiationException
        at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.eclipse.yasson.internal.ReflectionUtils.createNoArgConstructorInstance(ReflectionUtils.java:203)
        ... 67 more
```

Now what I can read from it:
* Yasson is used somewhere, somehow.
* Yasson tries to instantiate Jackson's JsonNode

My guess is that creating a new client will still pick up the default MBR:
```java
Client client = ClientBuilder.newClient()
        .register(MarshallingFeatures.class)
```

I also checked the  Configuration of JAX-RS and couldn't find any other MBR besides the one that I defined. So I guess it is injected late in the process somehow.

Is this intended? If so, can I circumvent it or is there a better way to code the library?

Thanks!

**Comment by bmhm** [comment]
Nevermind, the last one was a wrongly implemented `isReadable()` method. Thanks for the hint about the MBR / MBW!

**Comment by WhiteCat22** [comment]
No problem, glad you figured it out.
