### ISSUE TITLE
Feature Test Summary: SEC-47: Support PKCE in liberty oidc server

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#8630]
Please complete the following Feature Test Summary when you have completed all your testing. This will be used as part of the FAT Complete Review.

Part 1:
Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.

    For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature.

    If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

Part 2:
Collectively as a team you need to assess your confidence in the testing delivered based on the values below. This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.

    Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:
    0 - No automated testing delivered
    1 - We have minimal automated coverage of the feature including golden paths. There is a relatively high risk that defects or issues could be found in this feature.
    2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here. Error/outlying scenarios are not really covered. There are likely risks that issues may exist in the golden paths
    3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios. There is a risk when the feature is used outside the golden paths however we are confident on the golden path. Note: This may still be a valid end state for a feature... things like Beta features may well suffice at this level.
    4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios. While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.
    5 - We have delivered all automated testing we believe is needed for this feature. The testing covers all golden path cases as well as all the error/outlying scenarios that make sense. We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

    Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer. Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above. We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5. We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc. Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

Confidence:
Comments:

**Comment by c00crane** [comment]
Part 1: 
PKCE supported added new parms to the authorization and token endpoints.  The authorization endpoint is passed the challenge and method - when the token endpoint is called, the verifier is passed to it and it calculates and compares the value against the challenge passed to the authorization endpoint.  We've tested all combinations of good/bad/mismatched values being passed to both the authorization and token endpoints.  We've done this specifying that PKCE is and is not required (via a new config setting).  We've run this with both pure oauth and with oidc - we also use public and private clients.
The following tests are run with both OAuth and with OIDC:
PKCETests_PKCENotSpecified_privateClient_challengePlain_methodPlain
PKCETests_PKCENotSpecified_privateClient_challengeS256_methodS256
PKCETests_PKCENotSpecified_publicClient_challengePlain_methodPlain
PKCETests_PKCENotSpecified_publicClient_challengeS256_methodS256
PKCETests_PKCERequired_challengeOmitted_methodOmitted
PKCETests_PKCERequired_challengeOmitted_methodPlain
PKCETests_PKCERequired_challengeOmitted_methodS256
PKCETests_PKCERequired_challengeOmitted_methodOther
PKCETests_PKCERequired_challengePlain_methodOmitted
PKCETests_PKCERequired_challengePlain_methodPlain
PKCETests_PKCERequired_challengePlain_methodS256
PKCETests_PKCERequired_challengePlain_methodOther
PKCETests_PKCERequired_challengePlainLessthan43_methodPlain
PKCETests_PKCERequired_challengePlainGreaterThan128_methodPlain
PKCETests_PKCERequired_challengeS256_methodOmitted
PKCETests_PKCERequired_challengeS256_methodPlain
PKCETests_PKCERequired_challengeS256_methodS256
PKCETests_PKCERequired_challengeS256_methodOther
PKCETests_PKCERequired_challengeS256LessThan43_methodS256
PKCETests_PKCERequired_challengeS256GreaterThan128_methodS256
PKCETests_PKCENotRequired_challengeOmitted_methodOmitted
PKCETests_PKCENotRequired_challengeOmitted_methodPlain
PKCETests_PKCENotRequired_challengeOmitted_methodS256
PKCETests_PKCENotRequired_challengeOmitted_methodOther
PKCETests_PKCENotRequired_challengePlain_methodOmitted
PKCETests_PKCENotRequired_challengePlain_methodPlain
PKCETests_PKCENotRequired_challengePlain_methodS256
PKCETests_PKCENotRequired_challengePlain_methodOther
PKCETests_PKCENotRequired_challengePlainLessThan43_methodPlain
PKCETests_PKCENotRequired_challengePlainGreaterThan128_methodPlain
PKCETests_PKCENotRequired_challengeS256_methodOmitted
PKCETests_PKCENotRequired_challengeS256_methodPlain
PKCETests_PKCENotRequired_challengeS256_methodS256
PKCETests_PKCENotRequired_challengeS256_methodOther
PKCETests_PKCENotRequired_challengeS256LessThan43_methodS256
PKCETests_PKCENotRequired_challengeS256GreaterThan128_methodS256
PKCETests_codeVerifierInvalidOnTokenEndpoint_badFormat_codeChallengeInsteadOfCodeVerifier
PKCETests_codeVerifierInvalidOnTokenEndpoint_invalidString_methodPlain
PKCETests_codeVerifierInvalidOnTokenEndpoint_invalidString_MethodS256
PKCETests_codeVerifierMissingOnTokenEndpoint_methodPlain
PKCETests_codeVerifierMissingOnTokenEndpoint_methodS256
PKCETests_codeVerifierOnTokenEndpoint_afterNoCodeChallengeOrMethodOnAuthorization
PKCETests_codeVerifierConstansInvalidCharacter_methodPlain
PKCETests_codeVerifierConstansInvalidCharacter_methodS256
PKCETests_codeChallengeUsedPastLifetime_methodPlain
PKCETests_codeChallengeUsedPastLifetime_methodS256
PKCETests_reuseCodeVerifier_methodPlain
PKCETests_reuseCodeVerifier_methodS256
PKCETests_reuseCodeVerifierAndChallenge_methodPlain
PKCETests_reuseCodeVerifierAndChallenge_methodS256
PKCETests_useSameCodeVerifierAndChallengeOnMultipleRequests_methodPlain
PKCETests_useSameCodeVerifierAndChallengeOnMultipleRequests_methodS256
PKCETests_createMultipleAuthCodes_useWrongCodeVerifierOnTokenEndpoint_methodPlain
PKCETests_createMultipleAuthCodes_useWrongCodeVerifierOnTokenEndpoint_methodS256

**Comment by c00crane** [comment]
Part 2:
Confidence: 4
Comments: The tests are very thorough, but, were developed in Closed Liberty as that is where the runtime was located when we started and this is also where all of our FAT tooling is located.  We need the tooling to do the token and response processing/verification.  This will need to be ported to open after our tools are ported.

**Comment by c00crane** [comment]
In addition to the normal personal builds, I've run Java 2 Security and a Java 7 builds - both ran the new tests successfully.

**Comment by dave-waddling** [comment]
**FAT Focal Approval comment:** Hi @c00crane, please can you a comment with a link to the PR in which you delivered the the testing for this feature? Issue #18009 (in Commercial Liberty) "FAT for PKCE" mentioned the Epic for this feature but it is still open and doesn't reference a PR.

**Comment by dave-waddling** [comment]
**FAT Focal Approval comment:** Just a quick comment to note that @c00crane and I discussed the PR as per my previous comment. I've since completed the review and added the FAT Focal Approval to the parent epic.
