### ISSUE TITLE
EJB Custom Bindings: Bind default short bindings

### ISSUE THREAD

**Issue by brideck** [OpenLiberty/open-liberty#8756]
- Implement remote default short bindings and bind them to the server root
- Implement local default short bindings and bind them to ejblocal: namespace
- Handle duplicates with AmbiguousEJBReferenceException (this can be split into a separate issue, as needed)
- Activate default bindings (short-form) tests in EJB3DefBndWeb.war and NoInterfaceBndWeb.war

For EJB 3.x modules, if a custom binding is not provided, then in addition to the specification defined JNDI names, the WebSphere traditional default long and short form JNDI names will be available for direct lookup and may be bound to EJB references:

`Remote short : <interface>`
`Local short : ejblocal:<interface>`

**Comment by olendvcook** [comment]
Note: local short should be working after delivering #8774
