### ISSUE TITLE
Port over com.ibm.ws.request.timing_fat to OL

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/open-liberty#8771]
The com.ibm.ws.request.timing project was ported over in PR #8185. Need to port over the associated FAT (com.ibm.ws.request.timing_fat) and dependent FAT projects over to OL.

FATs to port over:
com.ibm.ws.request.timing_fat
com.ibm.ws.request.probes_fat
com.ibm.ws.request.probes_fat_java7
com.ibm.ws.request.probe.jdbc_fat
com.ibm.ws.request.probe.servlet_fat

**Comment by lamkavan** [comment]
The FAT projects are removed in PR # 19117 from CL. Note: com.ibm.ws.request.probes_fat_java7 was merged into com.ibm.ws.request.probes_fat. So com.ibm.ws.request.probes_fat_java7 no longer exist.
