### ISSUE TITLE
EJB Custom Bindings: Bind local default bindings (ejblocal: namespace)

### ISSUE THREAD

**Issue by brideck** [OpenLiberty/open-liberty#8774]
- Support ejblocal: namespace
- Implement local default bindings and bind them to ejblocal:
- Activate local default bindings (long-form) tests in EJB3DefBndWeb.war and NoInterfaceBndWeb.war

For EJB 3.x modules, if a custom binding is not provided, then in addition to the specification defined JNDI names, the WebSphere traditional default long and short form JNDI names will be available for direct lookup and may be bound to EJB references:

`Local long : ejblocal:<app>/<module>.jar/<bean>#<interface>`

**Comment by olendvcook** [comment]
delivered
