### ISSUE TITLE
EJB Custom Bindings: Support simple-binding-name XML element

### ISSUE THREAD

**Issue by brideck** [OpenLiberty/open-liberty#8777]
- Implement support for simple-binding-name in ibm-ejb-jar-bnd.xml for both remote and ejblocal:
- Activate simple-binding-name tests in NoInterfaceBndWeb.war

Simple binding name (one name used for both local and remote) 
`<session name="AccountServiceBean" simple-binding-name="ejb/AccountService"/>`

**Comment by nkuzman** [comment]
Any news/ETA on this?

**Comment by olendvcook** [comment]
@nkuzman Hello, just saw your question. This should be working for **LOCAL EJBs** as of 20.0.0.2 (in a beta functionality fashion). Unfortunately, getting it to work for remote EJBs is taking a little longer, hopefully soon though.

Note that even if we get it to start working for the simple-binding-name for remote EJBs. the entire feature (#7918) Is still going to take a while and it would be considered beta until we're finished with that.

For now if you just need it for local EJBs and you have 20.0.0.2, you can enable the beta feature by adding `<ejbContainer bindToServerRoot="true"/>` to your server.xml and have the EJBHome feature added as well (`<feature>ejbHome-3.2</feature>`)

**Comment by nkuzman** [comment]
Hi @olendvcook , thank you for your answer.
I mostly use remote EJBs, so apparently I'll just have to wait for it a bit longer :)

**Comment by olendvcook** [comment]
@nkuzman I have delivered support for the remote simple-binding-name and it should be in the 2.0.0.5 beta.
