### ISSUE TITLE
EJB Custom Bindings: Support Remote interface and binding-name XML elements

### ISSUE THREAD

**Issue by brideck** [OpenLiberty/open-liberty#8783]
- Implement support for \<interface\> and binding-name in ibm-ejb-jar-bnd.xml remote.
- Activate binding-name tests in EJB3BndWeb.war and NoInterfaceBndWeb.war

Binding per interface:
```
<session name="NoInterceptorBasicStateless">
     <interface class="com.ejbs.InventoryService" binding-name="ejb/Inventory"/>
</session>
```

**Comment by olendvcook** [comment]
Complete
