### ISSUE TITLE
EJB Custom Bindings: Bind local XMI bindings (local: namespace)

### ISSUE THREAD

**Issue by brideck** [OpenLiberty/open-liberty#8785]
- Support local: namespace
- Implement support for \<ejbBindings\> and jndiName in ibm-ejb-jar-bnd.xmi for local:
- Activate local XMI bindings tests in legacy_fat

EJB 1.x and 2.x provide a single JNDI name that applies to both the remote and local home:
```
<ejbBindings xmi:id="EnterpriseBeanBinding_8" jndiName="suite/r6x/base/misc/poollimits/SLCMTTxTimeoutHome">
    <enterpriseBean xmi:type="ejb:Session" href="META-INF/ejb-jar.xml#SLCMTTxTimeout"/>
</ejbBindings>
```
For a bean with both a remote and local home, the above will provide the following custom bindings:
    `Remote Home : suite/r6x/base/misc/poollimits/SLCMTTxTimeoutHome`
    `Local Home  : local:ejb/suite/r6x/base/misc/poollimits/SLCMTTxTimeoutHome`

This issue is for local

**Comment by olendvcook** [comment]
Note: When looking at our old tests and how they actually did the lookup they seem to always do `local:ejb/suite/r6x/base/misc/poollimits/SLCMTTxTimeoutHome`

and looking at TWAS when we created the context `local:` we always created the subcontext `ejb/` and passed that. For Open-Liberty it seems like our namespace should be `local:ejb/`

**Comment by olendvcook** [comment]
delivered
