### ISSUE TITLE
RM: Consider defaulting key and value serializer and deserializer

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/open-liberty#8799]
These currently need to be defined on every channel with config like this:

```
mp.messaging.incoming.foo.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.foo.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
```

These long keys and values are a pain to enter manually. We should consider defaulting them to the `String` serializer and deserializer as we think that's a common use case.

**Comment by tevans78** [comment]
Remove the need for the key serializer and deserializer

**Comment by Emily-Jiang** [comment]
SmallRye does not pass this property on, hence the removal.
