### ISSUE TITLE
MP metrics 2.0 doesn't include fault tolerance metrics

### ISSUE THREAD

**Issue by sdaschner** [OpenLiberty/open-liberty#8806]
When switching the feature from `mpMetrics-1.1` to version `2.0` in an application that uses MicroProfile Fault Tolerance (`mpFaultTolerance-2.0`), the metrics under `/metrics` don't include the metrics for the fault tolerance features such as circuit breakers anymore.

**Reproducer:**

https://github.com/sdaschner/liberty-dev-experience/tree/mp-ft-metrics-test

The `server.xml` file includes `mpMetrics-2.0` which does not cause metrics such as `application:ft_com_sebastian_daschner_openliberty_hello_hi_circuitbreaker_calls_failed_total` to be included anymore.
Changing back to Metrics 1.1 resolves this issue.

I expected a metric similar to `application_ft_com_sebastian_daschner_openliberty_hello_hi_circuitbreaker_calls_failed_total` to be emitted.

Tested with `Open Liberty 19.0.0.8/wlp-1.0.31.cl190820190813-1136`.

**Comment by Azquelt** [comment]
Hi, I have an issue on my backlog to do this: #7594. I hope to get to it early next week.

**Comment by Azquelt** [comment]
This should now be fixed in nightlies and will be included in the next release.
