### ISSUE TITLE
Update messages related to logging JSON field mapping

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#8814]
fix descriptions in LoggingMessages.nlsprops (eventType -> source, liberty_... -> ...)

**Comment by fmhwong** [comment]
9.0.0.10 translation deadline: 9/13/2019
After the files are merged to integration, send an email to:  Philip Nickoll/UK/IBM, Christopher Potter/Poughkeepsie/IBM, Marika Joannidis/Toronto/IBM.
In the email include: the names and paths of the English files that require translation along with their PR numbers.
