### ISSUE TITLE
Liberty error handling creates defaultServer as side-effect

### ISSUE THREAD

**Issue by gjdeval** [OpenLiberty/open-liberty#8824]
An error in a bit of bash scripting just exposed an odd behavior, which seems like a bug ...
If I try to start a Liberty server, and the server name starts with '-' Liberty replies with an error message, which is probably fine ... however, as a side-effect, a defaultServer instance is created.

``` # ls usr/
 # ./bin/server start -cpus-4-runs-25-try-1

CWWKE0013E: Unknown option: -cpus-4-runs-25-try-1

 # ls usr/
servers
 # ls usr/servers/
defaultServer
 #

**Comment by jhanders34** [comment]
Do note this in the help text:
```    serverName
	A locally unique name for the server; the name can be constructed    
	using Unicode alphanumeric characters (for example, A-Za-z0-9), the  
	underscore (_), dash (-), plus (+) and period (.). A server name     
	cannot begin with a dash (-) or period (.).
```
I have also noticed just doing ./bin/server start defaultServer will create a defaultServer directory under usr/servers even though it doesn't exist yet.  I thought that a server would only be started if the server name is already defined in the usr/servers.

**Comment by hlhoots** [comment]
@jhanders34 Not sure on the history of that 'function' you describe above with defaultServer being created on start if it doesnt exist, but a test case was explicitly added for that scenario in April of 2015 in StartCommandTest.java.  Thus I think that logic is working as designed.
