### ISSUE TITLE
bundle resolution problem with spnego-1.0 feature

### ISSUE THREAD

**Issue by brutif** [OpenLiberty/open-liberty#8831]
Creating a server with spnego-1.0 feature causes feature to not work, a bundle resolution error is logged 

[ERROR   ] CWWKE0702E: Could not resolve module: com.ibm.ws.security.spnego [95]
  Unresolved requirement: Import-Package: com.ibm.ws.security.s4u2proxy; version="[1.0.0,2.0.0)"

**Comment by utle** [comment]
Fixed in this PR # https://github.com/OpenLiberty/open-liberty/pull/8870
