### ISSUE TITLE
Bval20: Upgrade the bval 2.0 bucket to verify bval 1.1 behaviour.

### ISSUE THREAD

**Issue by nmittles** [OpenLiberty/open-liberty#892]
"As a Liberty Bval 2.0 Developer I want to to ensure that I do not regress the function/behaviour we currently have for Bval 1.1."

Port the existing bval11 FAT tests into a bval20 FAT bucket to prevent loss of function.
Upgrade all features in server.xml to Java EE levels.
Convert all the validation.xml files to no longer rely on org.apache.bval packages.
Check all test source files for org.apache.bval references, as either class references or string literals.
Port the tWAS multiple validation.xml test case.

**Comment by awisniew90** [comment]
FAT test updates are complete
