### ISSUE TITLE
BETA BLOG 191100 jaeger-1.0

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#8955]
**See the latest in https://github.com/openliberty/open-liberty/issues/8955#issuecomment-541179887**

- Development progress update

  - a. Which Liberty feature does it relate to?
    - i. Human-readable name (eg WebSockets feature)
      - Jaeger for MicroProfile OpenTracing
    - ii. Feature name (eg websockets-1.0)
      - `jaeger-1.0`
    - iii. Is this a new feature or is it an update to an existing feature for this release?
      - New feature
    - iv. Provide the fully qualified name of all public features ( as '*.esa' filenames) that are delivered as part of this work
      - `com.ibm.websphere.appserver.jaeger-1.0`
       (eg: com.ibm.websphere.appserver.transportSecurity-1.0.esa)

       For example new or changed .esa files for public features in dev/com.ibm.websphere.appserver.features/build/libs/repo/

  - b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc
    - application developers. devops
  - c. Write a sentence or two that introduces it to someone new to the general technology/concept.
     - OpenLiberty can use Jaeger as a tracing backend for MicroProfile OpenTracing.
  - d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)
     - OpenLiberty has the support of MicroProfile OpenTracing.  A sample tracer was provided at https://github.com/WASdev/sample.opentracing.zipkintracer for using Zipkin as a tracing backend.  With the introduction of `jaeger-1.0`, developers can also use Jaeger as a tracing backend. 
  - e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.

    - You will need to download the Jaeger client version 0.34.0 library and its dependencies from [Maven repository](https://mvnrepository.com/artifact/io.jaegertracing/jaeger-client/0.34.0). 

    - In the server.xml, 
      - add `<feature>jaeger-1.0</feature>` under `<featureManager> section.`
      - add the following snippet 
```
    <library id="jaegerLib" apiTypeVisibility="api,ibm-api,spec,stable,third-party" >
        <file name="<path>/jaegerLib_0.34/gson-2.8.2.jar" />
        <file name="<path>/jaegerLib_0.34/jaeger-client-0.34.0.jar" />
        <file name="<path>/jaegerLib_0.34/jaeger-core-0.34.0.jar" />
        <file name="<path>/jaegerLib_0.34/jaeger-thrift-0.34.0.jar" />
        <file name="<path>/jaegerLib_0.34/jaeger-tracerresolver-0.34.0.jar" />
        <file name="<path>/jaegerLib_0.34/libthrift-0.12.0.jar" />
        <file name="<path>/jaegerLib_0.34/slf4j-api-1.7.25.jar" />
        <file name="<path>/jaegerLib_0.34/slf4j-jdk14-1.7.25.jar" />
        <file name="<path>/jaegerLib_0.34/opentracing-util-0.31.0.jar" />
        <file name="<path>/jaegerLib_0.34/opentracing-noop-0.31.0.jar" />
    </library>
```

    - define your appplication:

```
    <webApplication location="yourapp.war" contextRoot="/yourapp">
        <!-- enable visibility to third party apis -->
        <classloader commonLibraryRef="jaegerLib"
            apiTypeVisibility="api,ibm-api,spec,stable,third-party" />
    </webApplication>
```

  - f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.
    - Jaeger settings can be set using environment variables.  See https://github.com/jaegertracing/jaeger-client-java/blob/10c641f8df6316f1eac4d5b1715513275bcd724e/jaeger-core/README.md
    - For the `JAEGER_PASSWORD`, the password can be encoded using the `securityUtility` command
    - Depending on Jaeger's sampling settings `JAEGER_SAMPLER_TYPE` and `JAEGER_SAMPLER_PARAM`, Jaeger may not report every spans created by the applications.
  - g. Attach any images to this work item as .png files.

**Comment by fmhwong** [comment]
@jennifer-c Please review

**Comment by jennifer-c** [comment]
Looks good.

**Comment by lauracowen** [comment]
Great, thanks

**Comment by jwalcorn** [comment]
as I recall from the WAD review, we discussed adding a directive to the Dockerfile (something like `ARG jaeger=true` or whatever), that would cause `configure.sh` to download the needed jars from Maven Central or wherever (like it does for Hazelcast).

Also, I vaguely recall discussion of something more clever than the developer having to explicitly list each of those downloaded versioned jars in a `library` stanza - though I forget the details.  Anything like this, that improves the usability for producing a Liberty docker image usage this, would be awesome.

Might perhaps also want to deliver an Appsody stack with this already done.

Anyway, @NottyCode or @arthurdm might remember the specifics....

**Comment by jwalcorn** [comment]
fwiw, I just saw a generator produce this today, still highlighting the old unsupported, as-is user feature for Zipkin.  at least it's using the new MicroProfile 3.0 (which gives you the mpOpenTracing feature).

```
<?xml version="1.0" encoding="UTF-8"?>
<server description="testpo1">

	<featureManager>
		<feature>microProfile-3.0</feature>
		<feature>usr:opentracingZipkin-0.31</feature>
	</featureManager>
	<variable name="defaultHostName" value="0.0.0.0" />
	<quickStartSecurity userName="admin"
		userPassword="adminpwd" />
	<keyStore id="defaultKeyStore" password="mpKeystore" />
	<httpEndpoint id="defaultHttpEndpoint"
		httpPort="${httpPort}" httpsPort="${httpsPort}">
	</httpEndpoint>

	<application location="./testpo1.war" />

	<opentracingZipkin host="${env.ZIPKIN_HOST}" port="${env.ZIPKIN_PORT}" />
</server>
```

**Comment by lauracowen** [comment]
@jwalcorn Can you confirm the exact changes that would be needed to be made to Felix's text for the release blog post, pls?

**Comment by fmhwong** [comment]
## Revised for 19.0.0.11 beta

- Development progress update

  - a. Which Liberty feature does it relate to?
    - i. Human-readable name (eg WebSockets feature)
      - Jaeger for MicroProfile OpenTracing
    - ii. Feature name (eg websockets-1.0)
      - `mpOpenTracing-1.3`
    - iii. Is this a new feature or is it an update to an existing feature for this release?
      - Update
    - iv. Provide the fully qualified name of all public features ( as '*.esa' filenames) that are delivered as part of this work
      - `com.ibm.websphere.appserver.mpOpenTracing-1.3`
       (eg: com.ibm.websphere.appserver.transportSecurity-1.0.esa)

       For example new or changed .esa files for public features in dev/com.ibm.websphere.appserver.features/build/libs/repo/

  - b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc
    - application developers. devops
  - c. Write a sentence or two that introduces it to someone new to the general technology/concept.
     - OpenLiberty can use Jaeger as a tracing backend for MicroProfile OpenTracing.
  - d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)
     - OpenLiberty has the support of MicroProfile OpenTracing.  A sample tracer was provided at https://github.com/WASdev/sample.opentracing.zipkintracer for using Zipkin as a tracing backend.  With the addition of Jaeger support, developers can also use Jaeger as a tracing backend. 
  - e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.

    - You will need to download the Jaeger client version 0.34.0 library and its dependencies from [Maven repository](https://mvnrepository.com/artifact/io.jaegertracing/jaeger-client/0.34.0). 

    - In the server.xml, 
      - add `<feature>mpOpenTracing-1.3</feature>` under `<featureManager>` section.
      - add the following snippet 
```
    <library id="jaegerLib" apiTypeVisibility="+third-party" >
        <file name="<path>/jaegerLib_0.34/gson-2.8.2.jar" />
        <file name="<path>/jaegerLib_0.34/jaeger-client-0.34.0.jar" />
        <file name="<path>/jaegerLib_0.34/jaeger-core-0.34.0.jar" />
        <file name="<path>/jaegerLib_0.34/jaeger-thrift-0.34.0.jar" />
        <file name="<path>/jaegerLib_0.34/jaeger-tracerresolver-0.34.0.jar" />
        <file name="<path>/jaegerLib_0.34/libthrift-0.12.0.jar" />
        <file name="<path>/jaegerLib_0.34/slf4j-api-1.7.25.jar" />
        <file name="<path>/jaegerLib_0.34/slf4j-jdk14-1.7.25.jar" />
        <file name="<path>/jaegerLib_0.34/opentracing-util-0.31.0.jar" />
        <file name="<path>/jaegerLib_0.34/opentracing-noop-0.31.0.jar" />
    </library>
```

    - define your appplication:

```
    <webApplication location="yourapp.war" contextRoot="/yourapp">
        <!-- enable visibility to third party apis -->
        <classloader commonLibraryRef="jaegerLib"
            apiTypeVisibility="+third-party" />
    </webApplication>
```

  - f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.
    - Jaeger settings can be set using environment variables.  See https://github.com/jaegertracing/jaeger-client-java/blob/10c641f8df6316f1eac4d5b1715513275bcd724e/jaeger-core/README.md
    - When specifying `JAEGER_PASSWORD` environment variable, the password can be encoded using the `securityUtility` command
    - Depending on Jaeger's sampling settings `JAEGER_SAMPLER_TYPE` and `JAEGER_SAMPLER_PARAM`, Jaeger may not report every spans created by the applications.
  - g. Attach any images to this work item as .png files.

**Comment by seabaylea** [comment]
Is there a sample app anywhere that can be used to show this working?

**Comment by fmhwong** [comment]
> Is there a sample app anywhere that can be used to show this working?

Any JAX-RS app should do.  Or you can re-use the apps from https://github.com/OpenLiberty/guide-microprofile-opentracing

**Comment by seabaylea** [comment]
In order to use OpenTracing with Zipkin, I need to do the following:

**pom.xml:**
1. Add dependency for mpOpenTracing:
```
        <dependency>
            <groupId>io.openliberty.features</groupId>
            <artifactId>mpOpenTracing-1.3</artifactId>
            <type>esa</type>
        </dependency>
```
2. App property for Zipkin library user feature:
```
    <properties>
        <zipkin.usr.feature>https://github.com/WASdev/sample.opentracing.zipkintracer/releases/download/1.3/liberty-opentracing-zipkintracer-1.3-sample.zip</zipkin.usr.feature>
    </properties>
```
3. Load Zipkin library:
```
            <plugin>
                <groupId>com.googlecode.maven-download-plugin</groupId>
                <artifactId>download-maven-plugin</artifactId>
                <version>${version.download-maven-plugin}</version>
                <executions>
                    <execution>
                        <id>install-tracer</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>wget</goal>
                        </goals>
                        <configuration>
                            <url>${zipkin.usr.feature}</url>
                            <unpack>true</unpack>
                            <outputDirectory>${project.build.directory}/liberty/wlp/usr</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**server.xml**:

1. Add features:
```
    <feature>mpOpenTracing-1.3</feature>
    <feature>usr:opentracingZipkin-0.31</feature>
```
2. Add apiVisibility:
```
    <classloader apiTypeVisibility="api,ibm-api,spec,stable,third-party"/>
```

What are the equivalent steps for Jaeger support?

**Comment by lauracowen** [comment]
@fmhwong I think all this info went into the 'preview' ('beta') section of the 190011 release blog post. Are we fine to just move the same info to the GA part of the 190012 release blog post?
/cc @yasmin-aumeeruddy

**Comment by fmhwong** [comment]
@lauracowen Yes, please use the Oct 11 version https://github.com/openliberty/open-liberty/issues/8955#issuecomment-541179887

**Comment by fmhwong** [comment]
@seabaylea 

You can just include the Jaeger client jars into the WAR by adding the following dependencies.

```
        <!-- https://mvnrepository.com/artifact/io.jaegertracing/jaeger-client -->
        <dependency>
            <groupId>io.jaegertracing</groupId>
            <artifactId>jaeger-client</artifactId>
            <version>0.34.0</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-jdk14 -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-jdk14</artifactId>
            <version>1.7.25</version>
        </dependency>
```

server.xml
```
<server description="Sample Liberty server">

  <featureManager>
    <feature>mpOpenTracing-1.3</feature>
  </featureManager>

  <httpEndpoint id="defaultHttpEndpoint" 
                httpPort="9080" 
                httpsPort="9443"
                host="*" />
      
  <webApplication name="inventory-service" location="inventory-service-1.0-SNAPSHOT.war" contextRoot="/">
    <classloader apiTypeVisibility="+third-party"/>
  </webApplication>

  <applicationManager autoExpand="true"/>
    
</server>
```
