### ISSUE TITLE
Multiple instances of custom ConfigSource from MicroProfile Config 1.3 feature on WLP 19.0.0.8

### ISSUE THREAD

**Issue by 2ppisaHcl** [OpenLiberty/open-liberty#8958]
The custom configSource implemented registered in _org.eclipse.microprofile.config.spi.ConfigSource_ file (using spi lifecycle) results in multiple instance if the application is hot redeployed.
The effect of the described issue is that the code below print the new objectId and the older objectid (not destroyed) after each app hot deploy.

`

    public class CustomConfigSource implements ConfigSource {

    Map<String, String> map = new HashMap<>();

    @Override
    public int getOrdinal() {
        return 400;
    }

    @Override
    public String getValue(String key) {
        return map.get(key);
    }

    @Override
    public String getName() {
        return "Custom Config Source";
    }

    @Override
    public Map<String, String> getProperties() {

        map.put("config_one", "config_one_val:" + new Date());
        System.out.println(">>>>> " + map.get("config_one") + this); // this is still alive after app redeploy
        return map;

    }
    }
`

**Comment by Emily-Jiang** [comment]
@tevans78 can you take a look, please?

**Comment by tevans78** [comment]
@2ppisaHcl a couple of questions...
1) I assume that you are using the dropins folder to do the hot-redeploy?
2) How are you confirming that the old CustomConfigSource instances are never destroyed? They should be garbage collected at some point but it might not be instant.

**Comment by 2ppisaHcl** [comment]
Hi,

@tevans78  thanks for you reply.
The scenario is development test with maven. With the following maven plugin configured  as (application deployed as loose application, so we have the xml file referecing the workspace's artifact in liberty apps dir):

          <plugin>
                <groupId>net.wasdev.wlp.maven.plugins</groupId>
                <artifactId>liberty-maven-plugin</artifactId>
                <version>2.5</version>
                <configuration>
                    <assemblyArtifact>
                        <groupId>io.openliberty</groupId>
                        <artifactId>openliberty-runtime</artifactId>
                        <version>19.0.0.9</version>
                        <type>zip</type>
                    </assemblyArtifact>
                    <serverName>${liberty.server.name}</serverName>
                    <stripVersion>true</stripVersion>
                    <configFile>src/main/liberty/config/server.xml</configFile>
                    <configDirectory>src/main/liberty/config</configDirectory>
                    **<looseApplication>true</looseApplication>**
                    <bootstrapProperties>
                        <default.http.port>${http.port}</default.http.port>
                        <default.https.port>${https.port}</default.https.port>
                    </bootstrapProperties>
                    **<installAppPackages>project</installAppPackages>**
                </configuration>
                <executions>
                    <execution>
                        <id>start-liberty</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>test-start-server</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>stop-liberty</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>test-stop-server</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

After started the server as **mvn package liberty:run** at each code build and application redepoy we can see the older instances. The logging code frangment is:

    


     public Map<String, String> getProperties() {
        Map<String, String> map = new HashMap<>();

        map.put("config_one", "config_one_val:" + new Date());
        System.out.println(">>>>> CHECK CONFIG v3: " + map.get("config_one") + this);
        return map;

      }


The log below gives evidence of not garbage collected ConfigSource instances ending up with ever increasing instance versions. 

[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:27:19 CEST 2019 com.test.service.config.CustomConfigSource@4077e789
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:27:24 CEST 2019 com.test.service.config.CustomConfigSource@4077e789
[INFO] >>>>> **CHECK CONFIG v1**: config_one_val:Tue Sep 24 10:27:29 CEST 2019 **com.test.service.config.CustomConfigSource@4077e789**
[INFO] [AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9088/test
[INFO] [AUDIT   ] CWWKZ0009I: The application test-service has stopped successfully.
[INFO] [INFO    ] CWWKZ0018I: Starting application test-service .
[INFO] [INFO    ] CWWKZ0134I: The test-service  application is using the loose application definition at the <my_path>\target\liberty\wlp\usr\servers\<my_server>\apps\test-service.war.xml location.
[INFO] [INFO    ] SRVE9103I: A configuration file for a web server plugin was automatically generated for this server at <my_path>\target\liberty\wlp\usr\servers\<my_server>\logs\state\plugin-cfg.xml.
[INFO] >>>>> START CONFIG
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:27:33 CEST 2019 com.test.service.config.CustomConfigSource@85120979
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:27:33 CEST 2019 com.test.service.config.CustomConfigSource@85120979
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:27:33 CEST 2019 com.test.service.config.CustomConfigSource@85120979
[INFO] [INFO    ] SRVE0169I: Loading Web Module: Test Microservice.
[INFO] [INFO    ] SRVE0250I: Web Module Test Microservice has been bound to default_host.
[INFO] [AUDIT   ] CWWKT0016I: Web application available (default_host): http://test-service:9088/test/
[INFO] [AUDIT   ] CWWKZ0003I: The application test-service updated in 2.240 seconds.
[INFO] [INFO    ] SESN0176I: A new session context will be created for application key default_host/test
[INFO] [INFO    ] SESN0172I: The session manager is using the Java default SecureRandom implementation for session ID generation.
[INFO] [AUDIT   ] CWWKT0017I: Web application removed (default_host): http://test-service:9088/test/
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:27:38 CEST 2019 com.test.service.config.CustomConfigSource@85120979
[INFO] [INFO    ] SRVE9103I: A configuration file for a web server plugin was automatically generated for this server at <my_path>\target\liberty\wlp\usr\servers\<my_server>\logs\state\plugin-cfg.xml.
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:27:39 CEST 2019 com.test.service.config.CustomConfigSource@4077e789
[INFO] [INFO    ] CWWKZ0018I: Starting application test-service.
[INFO] [INFO    ] CWWKZ0134I: The test-service application is using the loose application definition at the <my_path>\target\liberty\wlp\usr\servers\<my_server>\apps\test-service.war.xml location.
[INFO] [INFO    ] SRVE9103I: A configuration file for a web server plugin was automatically generated for this server at <my_path>\target\liberty\wlp\usr\servers\<my_server>\logs\state\plugin-cfg.xml.
[INFO] >>>>> START CONFIG
[INFO] >>>>> CHECK CONFIG v2: config_one_val:Tue Sep 24 10:28:04 CEST 2019 com.test.service.config.CustomConfigSource@7909716a
[INFO] >>>>> CHECK CONFIG v2: config_one_val:Tue Sep 24 10:28:04 CEST 2019 com.test.service.config.CustomConfigSource@7909716a
[INFO] >>>>> CHECK CONFIG v2: config_one_val:Tue Sep 24 10:28:04 CEST 2019 com.test.service.config.CustomConfigSource@7909716a
[INFO] >>>>> CHECK CONFIG v2: config_one_val:Tue Sep 24 10:28:04 CEST 2019 com.test.service.config.CustomConfigSource@7909716a
[INFO] >>>>> CHECK CONFIG v2: config_one_val:Tue Sep 24 10:28:04 CEST 2019 com.test.service.config.CustomConfigSource@7909716a
[INFO] >>>>> CHECK CONFIG v2: config_one_val:Tue Sep 24 10:28:04 CEST 2019 com.test.service.config.CustomConfigSource@7909716a
[INFO] >>>>> CHECK CONFIG v2: config_one_val:Tue Sep 24 10:28:04 CEST 2019 com.test.service.config.CustomConfigSource@7909716a
[INFO] >>>>> CHECK CONFIG v2: config_one_val:Tue Sep 24 10:28:04 CEST 2019 com.test.service.config.CustomConfigSource@7909716a
[INFO] >>>>> CHECK CONFIG v2: config_one_val:Tue Sep 24 10:28:04 CEST 2019 com.test.service.config.CustomConfigSource@7909716a
[INFO] >>>>> CHECK CONFIG v2: config_one_val:Tue Sep 24 10:28:04 CEST 2019 com.test.service.config.CustomConfigSource@7909716a
[INFO] >>>>> CHECK CONFIG v2: config_one_val:Tue Sep 24 10:28:04 CEST 2019 com.test.service.config.CustomConfigSource@7909716a
[INFO] [INFO    ] CWWKO1660I: The application test-service was processed and an OpenAPI document was produced.
[INFO] [INFO    ] SRVE0169I: Loading Web Module: Test Microservice.
[INFO] [INFO    ] SRVE0250I: Web Module Test Microservice has been bound to default_host.
[INFO] [AUDIT   ] CWWKT0016I: Web application available (default_host): http://test-service:9088/test/
[INFO] [AUDIT   ] CWWKZ0003I: The application test-service updated in 2.825 seconds.
[INFO] [INFO    ] SESN0176I: A new session context will be created for application key default_host/test
[INFO] [INFO    ] SESN0172I: The session manager is using the Java default SecureRandom implementation for session ID generation.
[INFO] [INFO    ] SRVE9103I: A configuration file for a web server plugin was automatically generated for this server at <my_path>\target\liberty\wlp\usr\servers\<my_server>\logs\state\plugin-cfg.xml.
**[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:28:08 CEST 2019 com.test.service.config.CustomConfigSource@85120979
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:28:08 CEST 2019 com.test.service.config.CustomConfigSource@4077e789
[INFO] >>>>> CHECK CONFIG v2: config_one_val:Tue Sep 24 10:28:09 CEST 2019 com.test.service.config.CustomConfigSource@7909716a**
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:28:13 CEST 2019 com.test.service.config.CustomConfigSource@4077e789
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:28:13 CEST 2019 com.test.service.config.CustomConfigSource@85120979
[INFO] >>>>> CHECK CONFIG v2: config_one_val:Tue Sep 24 10:28:14 CEST 2019 com.test.service.config.CustomConfigSource@7909716a
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:28:18 CEST 2019 com.test.service.config.CustomConfigSource@85120979
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:28:18 CEST 2019 com.test.service.config.CustomConfigSource@4077e789
[INFO] >>>>> CHECK CONFIG v2: config_one_val:Tue Sep 24 10:28:19 CEST 2019 com.test.service.config.CustomConfigSource@7909716a
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:28:23 CEST 2019 com.test.service.config.CustomConfigSource@4077e789
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:28:23 CEST 2019 com.test.service.config.CustomConfigSource@85120979
[INFO] >>>>> CHECK CONFIG v2: config_one_val:Tue Sep 24 10:28:24 CEST 2019 com.test.service.config.CustomConfigSource@7909716a
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:28:28 CEST 2019 com.test.service.config.CustomConfigSource@4077e789
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:28:28 CEST 2019 com.test.service.config.CustomConfigSource@85120979
[INFO] >>>>> CHECK CONFIG v2: config_one_val:Tue Sep 24 10:28:29 CEST 2019 com.test.service.config.CustomConfigSource@7909716a
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:28:33 CEST 2019 com.test.service.config.CustomConfigSource@85120979
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:28:33 CEST 2019 com.test.service.config.CustomConfigSource@4077e789
[INFO] >>>>> CHECK CONFIG v2: config_one_val:Tue Sep 24 10:28:34 CEST 2019 com.test.service.config.CustomConfigSource@7909716a
[INFO] [AUDIT   ] CWWKT0017I: Web application removed (default_host): http://test-service:9088/test/
[INFO] [AUDIT   ] CWWKZ0009I: The application test-service has stopped successfully.
[INFO] [INFO    ] CWWKZ0018I: Starting application test-service.
[INFO] [INFO    ] CWWKZ0134I: The test-service application is using the loose application definition at the <my_path>\target\liberty\wlp\usr\servers\<my_server>\apps\test-service.war.xml location.
[INFO] [INFO    ] SRVE9103I: A configuration file for a web server plugin was automatically generated for this server at <my_path>\target\liberty\wlp\usr\servers\<my_server>\logs\state\plugin-cfg.xml.
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:28:38 CEST 2019 com.test.service.config.CustomConfigSource@4077e789
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:28:38 CEST 2019 com.test.service.config.CustomConfigSource@85120979
[INFO] [INFO    ] FFDC1015I: An FFDC Incident has been created: "java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigSource: Provider com.test.service.config.CustomConfigSource not found com.ibm.ws.microprofile.config.sources.DefaultSources 95" at ffdc_19.09.24_10.28.38.0.log
[INFO] [INFO    ] FFDC1015I: An FFDC Incident has been created: "com.ibm.ws.microprofile.config.interfaces.ConfigException: CWMCG0010E: Unable to discover ConfigSources. The exception is: java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigSource: Provider com.test.service.config.CustomConfigSource not found. com.ibm.ws.microprofile.openapi.ApplicationListener 45" at ffdc_19.09.24_10.28.38.1.log
[INFO] [INFO    ] SRVE0169I: Loading Web Module: Test Microservice.
[INFO] [INFO    ] SRVE0250I: Web Module Test Microservice has been bound to default_host.
[INFO] [AUDIT   ] CWWKT0016I: Web application available (default_host): http://test-service:9088/test/
[INFO] [AUDIT   ] CWWKZ0003I: The application test-service updated in 2.574 seconds.
[INFO] [INFO    ] SESN0176I: A new session context will be created for application key default_host/test
[INFO] [INFO    ] SESN0172I: The session manager is using the Java default SecureRandom implementation for session ID generation.
[INFO] [AUDIT   ] CWWKT0017I: Web application removed (default_host): http://test-service:9088/test/
[INFO] [AUDIT   ] CWWKZ0009I: The application test-service has stopped successfully.
[INFO] [INFO    ] CWWKZ0018I: Starting application test-service.
[INFO] [INFO    ] CWWKZ0134I: The test-service application is using the loose application definition at the <my_path>\target\liberty\wlp\usr\servers\<my_server>\apps\test-service.war.xml location.
[INFO] >>>>> CHECK CONFIG v2: config_one_val:Tue Sep 24 10:28:39 CEST 2019 com.test.service.config.CustomConfigSource@7909716a
[INFO] >>>>> START CONFIG
[INFO] >>>>> CHECK CONFIG v3: config_one_val:Tue Sep 24 10:28:39 CEST 2019 com.test.service.config.CustomConfigSource@f9b495cb
[INFO] >>>>> CHECK CONFIG v3: config_one_val:Tue Sep 24 10:28:39 CEST 2019 com.test.service.config.CustomConfigSource@f9b495cb
[INFO] >>>>> CHECK CONFIG v3: config_one_val:Tue Sep 24 10:28:39 CEST 2019 com.test.service.config.CustomConfigSource@f9b495cb
[INFO] >>>>> CHECK CONFIG v3: config_one_val:Tue Sep 24 10:28:39 CEST 2019 com.test.service.config.CustomConfigSource@f9b495cb
[INFO] >>>>> CHECK CONFIG v3: config_one_val:Tue Sep 24 10:28:39 CEST 2019 com.test.service.config.CustomConfigSource@f9b495cb
[INFO] >>>>> CHECK CONFIG v3: config_one_val:Tue Sep 24 10:28:39 CEST 2019 com.test.service.config.CustomConfigSource@f9b495cb
[INFO] >>>>> CHECK CONFIG v3: config_one_val:Tue Sep 24 10:28:39 CEST 2019 com.test.service.config.CustomConfigSource@f9b495cb
[INFO] >>>>> CHECK CONFIG v3: config_one_val:Tue Sep 24 10:28:39 CEST 2019 com.test.service.config.CustomConfigSource@f9b495cb
[INFO] >>>>> CHECK CONFIG v3: config_one_val:Tue Sep 24 10:28:39 CEST 2019 com.test.service.config.CustomConfigSource@f9b495cb
[INFO] >>>>> CHECK CONFIG v3: config_one_val:Tue Sep 24 10:28:39 CEST 2019 com.test.service.config.CustomConfigSource@f9b495cb
[INFO] >>>>> CHECK CONFIG v3: config_one_val:Tue Sep 24 10:28:39 CEST 2019 com.test.service.config.CustomConfigSource@f9b495cb
[INFO] [INFO    ] CWWKO1660I: The application test-service was processed and an OpenAPI document was produced.
[INFO] [INFO    ] SRVE0169I: Loading Web Module: Test Microservice.
[INFO] [INFO    ] SRVE0250I: Web Module Test Microservice has been bound to default_host.
[INFO] [AUDIT   ] CWWKT0016I: Web application available (default_host): http://test-service:9088/test/
[INFO] [AUDIT   ] CWWKZ0003I: The application test-service updated in 1.825 seconds.
[INFO] [INFO    ] SESN0176I: A new session context will be created for application key default_host/test
[INFO] [INFO    ] SESN0172I: The session manager is using the Java default SecureRandom implementation for session ID generation.
[INFO] [INFO    ] SRVE9103I: A configuration file for a web server plugin was automatically generated for this server at <my_path>\target\liberty\wlp\usr\servers\<my_server>\logs\state\plugin-cfg.xml.
**[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:28:43 CEST 2019 com.test.service.config.CustomConfigSource@85120979
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:28:43 CEST 2019 com.test.service.config.CustomConfigSource@4077e789
[INFO] >>>>> CHECK CONFIG v2: config_one_val:Tue Sep 24 10:28:44 CEST 2019 com.test.service.config.CustomConfigSource@7909716a
[INFO] >>>>> CHECK CONFIG v3: config_one_val:Tue Sep 24 10:28:44 CEST 2019 com.test.service.config.CustomConfigSource@f9b495cb**
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:28:48 CEST 2019 com.test.service.config.CustomConfigSource@85120979
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:28:48 CEST 2019 com.test.service.config.CustomConfigSource@4077e789
[INFO] >>>>> CHECK CONFIG v2: config_one_val:Tue Sep 24 10:28:49 CEST 2019 com.test.service.config.CustomConfigSource@7909716a
[INFO] >>>>> CHECK CONFIG v3: config_one_val:Tue Sep 24 10:28:49 CEST 2019 com.test.service.config.CustomConfigSource@f9b495cb
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:28:53 CEST 2019 com.test.service.config.CustomConfigSource@4077e789
[INFO] >>>>> CHECK CONFIG v1: config_one_val:Tue Sep 24 10:28:53 CEST 2019 com.test.service.config.CustomConfigSource@85120979
[INFO] >>>>> CHECK CONFIG v2: config_one_val:Tue Sep 24 10:28:54 CEST 2019 com.test.service.config.CustomConfigSource@7909716a
[INFO] >>>>> CHECK CONFIG v3: config_one_val:Tue Sep 24 10:28:54 CEST 2019 com.test.service.config.CustomConfigSource@f9b495cb

**Comment by tevans78** [comment]
- You mentioned that you were using the spi lifecycle to add in the custom source. Did you mean the service loader mechanism?
- Are you using CDI to inject the Config instance? Or using the Java API to get a Config instance directly from the provider?
- Just FYI, as an experiment, I took the example guide code from https://github.com/openliberty/guide-microprofile-config.git and made a similar hot updates. That worked correctly and only ever showed one instance of the CustomConfigSource at one time.

**Comment by 2ppisaHcl** [comment]
I have followed exacly the same configuration's step and among other things we have enabled also 
**mpOpenAPI-1.1** and other feature set 
After some test I come up with  reproduce the issue also in your sample code
enabling the feature **mpOpenAPI-1.1**.
So enabling this feature you will be able to observe the side effect descibed previously.

**Comment by tevans78** [comment]
Thank you, I have now reproduced the problem which should make it much it easier to resolve. As you said, just introducing mpOpenAPI-1.1 caused the change in behaviour.

**Comment by tevans78** [comment]
Looking at the OpenAPI code, I think that it creates one Config instance for the whole server. That Config instance picks up custom user ConfigSource classes but is not re-instantiated if those classes change through a hot-swap update.
https://github.com/OpenLiberty/open-liberty/blob/c9f30ad73ffccb225fccbe5019aa56d8d55278ee/dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/ConfigProcessor.java#L61

**Comment by tevans78** [comment]
@leochr @arturdzm please could one of you take a look at this?

**Comment by tevans78** [comment]
@2ppisaHcl I don't know if this helps at all but I am fairly sure that your application code will always be seeing the correct CustomConfigSource. I think it is only the internal OpenAPI sub-system that is holding on to the wrong one and from your application's point of view that doesn't matter.

Of course we will also continue working on a fix for the OpenAPI code.
