### ISSUE TITLE
Linux Redhat 7 systemd boot-scripts for WebSphere Application Server (Feature)

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#8966]
The wasservices.sh script is creating system V init boot scripts.
However this type of boot scripts are deprecated according to RedHat Support.
Is it possible to change the wasservices.sh script to generate systemd type boot scripts

https://access.redhat.com/articles/754933
(EC: this topic is long, but does not contain the word deprecated)

EC:
Some sub-requirements from PMR discussions:
- systemd may want to know the state of servers started by a node agent
- systemd scripts should (optionally?) restart crashed jvms.

**Comment by atosak** [comment]
Blog post abut this issue: https://www.bea-services.com/blog/websphere-systemd-start-stop-scripts

**Comment by atosak** [comment]
Resolves [RFE 186781](https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/External%20Request%20For%20Enhancements#action=com.ibm.team.workitem.viewWorkItem&id=186781)

**Comment by NottyCode** [comment]
Since Open Liberty doesn't have a wasservice.sh file this is obviously here in error so closing.
