### ISSUE TITLE
BETA BLOG 191000 mpHealth-2.1

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/open-liberty#8974]
- Development progress update

  - a. Which Liberty feature does it relate to?
    - i. Human-readable name (eg WebSockets feature)
      - `MicroProfile Health Check 2.1`
    - ii. Feature name (eg websockets-1.0)
      - `mpHealth-2.1`
    - iii. Is this a new feature or is it an update to an existing feature for this release?
      - `This is a new feature to support MicroProfile Health Check 2.1 specification.`
    - iv. Provide the fully qualified name of all public features ( as '*.esa' filenames) that are delivered as part of this work
       (eg: com.ibm.websphere.appserver.transportSecurity-1.0.esa)
      - `com.ibm.websphere.appserver.mpHealth-2.1.esa`

       For example new or changed .esa files for public features in dev/com.ibm.websphere.appserver.features/build/libs/repo/

  - b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc
    - `Application developers and administrators`
  - c. Write a sentence or two that introduces it to someone new to the general technology/concept.
     - `MicroProfile Health Check 2.1 enables you to provide your own health check procedures to be invoked by Liberty, to verify the health of your microservice.`
  - d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)
In mpHealth-2.1 feature for OpenLiberty, you can now use convenient and simpler methods from standard Java APIs, to construct UP/DOWN named health check responses, in your applications, such as;

     `HealthCheckResponse.up("myCheck");`

     In previous versions, to define a simple successful/failed named health check response, the application level code is always expected to use several static methods together from the HealthCheckResponse API, to retrieve a HealthCheckResponseBuilder used to construct a HealthCheck response.

     `HealthCheckResponse.named(“myCheck”).up().build();`

  - e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.

    - Include the following in the server.xml:
`<feature>mpHealth-2.1</feature>`

---
Applications are expected to provide health check procedures, by implementing the HealthCheck interface with the @Liveness or @Readiness annotations, which will be used by Liberty to verify the Liveness or Readiness of the application, respectively. Add the logic of your health check in the call() method, and return the HealthCheckResponse object, by constructing using the simple up()/down() methods from the API. To view the status of each health check, access the either the `http://<hostname>:<port>/health/live` or `http://<hostname>:<port>/health/ready` endpoints.

```
**Liveness Check**
@Liveness
@ApplicationScoped
public class AppLiveCheck implements HealthCheck {
...
    @Override
     public HealthCheckResponse call() {
       ...
       HealthCheckResponse.up("myCheck");
       ...
     }
}
```
---

  - f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.
* [MicroProfile Health Check 2.1 Release Page](https://github.com/eclipse/microprofile-health/releases/tag/2.1)
* [Javadocs](
http://download.eclipse.org/microprofile/microprofile-health-2.1/apidocs/)
* [Specification document](
http://download.eclipse.org/microprofile/microprofile-health-2.1/microprofile-health-spec.html)
  - g. Attach any images to this work item as .png files.

**Comment by lauracowen** [comment]
thanks
