### ISSUE TITLE
Language Server for Eclipse MicroProfile

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#8975]
We should have a LSP implementation for MicroProfile to enable our developers and make it easier for folks to build cloud-native applications with MP/Java EE.

This will allow us to close gaps with Spring -- Spring has LSPs that we expect can be easily integrated with Microclimate while there is none for Eclipse MicroProfile and Java/Jakarta EE.

This involves at least the below in the beginning:
- Work out what should be done
- Prototype for a LSP implementation (in the open)
- Partner with the community (RedHat/Tomitribe/Payara) to build it out

We will partner with the Dev Ex tribe within IBM to move this forward.

More on the latest that Spring has here: https://spring.io/blog/2018/09/25/spring-tools-4-ga-released

**Comment by angelozerr** [comment]
@atosak jus for your information, we have implemented a MicroProfile LS for Quarkus in https://github.com/redhat-developer/quarkus-ls/ and consumes it in https://github.com/redhat-developer/vscode-quarkus

I'm working on MicroProfile Fault Tolerance in https://github.com/redhat-developer/vscode-quarkus/issues/174, here the current status:

![MPFTDemo](https://user-images.githubusercontent.com/1932211/73949161-5139fc80-48fa-11ea-9e95-3e47a59a0cd6.gif)

**Comment by yeekangc** [comment]
Good to see you here, @angelozerr.  =)  Yes, we are aware of what you and the Quarkus team are building.

As you know, what we have thus far is at https://github.com/MicroShed/microprofile-language-server.  As we discussed, we are looking forward to collaborate with the Quakus team to make this a common MP Language Server and hopefully as a common project under Eclipse Foundation too.

**Comment by rzgry** [comment]
Eclipse project proposal: https://projects.eclipse.org/proposals/eclipse-lsp4mp-language-server-eclipse-microprofile-0

**Comment by rzgry** [comment]
UFO -  https://ibm.box.com/s/9wd513bblx6uof2xgnug6vk2ozgvim2y

**Comment by frowe** [comment]
UFO review moderator notes:
No actions noted.
Question about support for translation into other languages.
Question about support for eclipse client.  Answer is no and would have to investigate to see what would be required to support it.

**Comment by yeekangc** [comment]
+1 to elaborate on client support on what and how though implementation should/will be in separate items.

**Comment by frowe** [comment]
UFO review recording at https://ibm.ent.box.com/file/681008647692

**Comment by angelozerr** [comment]
> Question about support for eclipse client. Answer is no and would have to investigate to see what would be required to support it.

I'm sorry I don't understand why you say `Answer is no`? The MicroProfile language server can be consumed on Eclipse IDE by with LSP4E. https://github.com/jbosstools/jbosstools-quarkus is a sample

**Comment by yeekangc** [comment]
You are right, @angelozerr.  The comment captured was more on whether Eclipse support is part of the scope of this issue here.

Yes, we should able to enable it for Eclipse and the intention is to do that as you know.  Not as part of the server implementation itself but there should be a client for Eclipse.  That's what that needs to be clarified.

**Comment by angelozerr** [comment]
> Yes, we should able to enable it for Eclipse and the intention is to do that as you know. Not as part of the server implementation itself but there should be a client for Eclipse. That's what that needs to be clarified.

IMHO I think we should follow the same idea than we would like to have for vscode:

 * a vscode-microprofile extension which starts the MicroProfile LS and communicate with MicroProfile JDT LS.
 * a vscode-quarkus extension which extends the vscode-microprofile to add Quarkus stuff (when MicroProfile LS is started the extension will add in the classpath the proper Quarkus LS JAR, and on JDT LS side, it register Quarkus JDT LS).

For Eclipse IDE, I think we should have a LSP4E client which is extensible (to add Quarkus LS in the classpath). Perhaps it could be a good idea to have this Eclipse IDE LSP client (based on LSP4E) in the LSP4MP project?

@fbricon, @jeffmaury are the best people to discuss about that.

**Comment by rzgry** [comment]
Closing this issue as we have delivered the first release of lsp4mp.

Language Server repo: https://github.com/eclipse/lsp4mp
VSCode Client repo: https://github.com/redhat-developer/vscode-microprofile
Eclipse Project: https://projects.eclipse.org/projects/technology.lsp4mp
