### ISSUE TITLE
Improve integration wtih IntelliJ IDEA

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#8977]
Improve the integration between Liberty & tWAS with IntelliJ IDEA

Note: the IDEA terminology is different to Eclipse - use this 'IDEA for Eclipse users page' https://www.jetbrains.com/idea/help/eclipse.html

Some scenarios you can achieve in Eclipse, which you can't (or you can with difficulty) from IntelliJ:
1. I want to easily get from empty project to project that's ready to run Liberty.
1a. Install Liberty from within IDEA - either from Liberty repository, LARS, or local archive (high)
1b. Install features from the Liberty repository intothe Liberty runtime.
1c. Install a beta runtime
1d. Use multiple servers in the same install (low)

2. I want to easily author a server.xml
2a. design editor for server.xml to assist with adding elements
2b. adding a feature to a server.xml - if it's not installed, offer to install it from the liberty repository

3. I want to create the same kind of modules as I can projects in Eclipse that run on Liberty
3a. EAR / WAR / EJB (probably just a test effort)
3b. user feature
3c. OSGi - EBA / WAB / others like persistence bundle

4. I want to use WebSphere provided api's in my application (spec/ibm/third-party)
5. I want to use WebSphere provided spi's in my feature

**Comment by yeekangc** [comment]
Superseded by #10352.  Closing as duplicate.
