### ISSUE TITLE
LocalConnectorActivator depends on 2 renamed/internalized JDK APIs

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#8981]
The Liberty class com.ibm.ws.jmx.connector.local.LocalConnectorActivator depends on 2 JDK APIs which are being renamed and internalized in Java 9:
- sun.misc.VMSupport -> jdk.internal.vm.VMSupport
- sun.management.Agent -> jdk.internal.agent.Agent

We should change the LocalConenctorActivator code to accomplish the same thing using proper JDK APIs. Failing to do so would leave us vulnerable to these APIs being removed without warning in a future java release.

Update (2017-11-03):
As of Oracle JDK 9.0.1 the Agent class has been removed entirely, so it's not possible to use localconnector-1.0 with the latest Java 9 anymore.

**Comment by atosak** [comment]
1. Erik Hochstedt

Seems to be more in the JMX side.​
2.Arthur De Magalhaes
Michael - can you please take a look?​

3.Michael Glavassevich
There is no Java SE API for starting/accessing the JMX agent, otherwise we would have used it. Is this actually broken in Java 9 or are we just worried that it might break?​

4.ANDREW GUIBERT
I wasn't able to find any alternate API either (I checked before I opened this defect). 
It isn't completely broken in Java 9, but the classes are being moved to internal packages, which are subject to change/removal:
 jdk.internal.agent.Agent
 jdk.internal.vm.VMSupport
To continue to depend on these APIs in java9 would require a permanent workaround/hack of adding JVM command line options every time a Liberty server is started, but even then we are still vulnerable to the APIs changing or being removed in the future.

So far we have not needed to depend on any JDK internal APIs for Java 9 support (we are about 75% done). If we do determine that there really is no alternative API, we ought to take this to a design issue meeting and possibly push on the Java 9 community to get a proper replacement API.

​5.Michael Glavassevich
Some background of how this feature ended up in Liberty to begin with. The WDT tools required a way to connect to Liberty's JMX server. They tried to use the Java Attach API (not part of the Java SE spec) [1] but had problems with it hanging. It's also vendor dependent (differences in the package names between IBM and Oracle) and is unable to connect to JVMs from another vendor, meaning if the tools are running on an IBM JVM and Liberty is running on an Oracle JVM it won't work. As a last resort we ended up creating a feature (localConnector-1.0) which accomplishes what a client would do with the Java Attach API and that unfortunately required digging into the internals of the JMX agent. Would be happy to convert that into proper API calls if Oracle provided such an API.

[1] https://docs.oracle.com/javase/8/docs/technotes/guides/attach/index.html

​6.ANDREW GUIBERT 
I did experiment with the attach API for a few hours and wasn't able to get it to work. Here is my understanding of the need for these APIs:

Agent: invoke "agentmain" to start the JMX agent for the server. Normally this is done by an external process, but for Liberty we are starting our own JMX agent
VMSupport: to read the local connector address that can be used to connect to the JMX agent we started with Agent.agentmain().

It sounds like the Attach API should be a suitable replacement, but you say that "we had problems with it hanging". Could you provide more detail on these issues? Once I understand the usage and why the Attach API is insufficient, I can go to the Java 9 mailing list and try to argue to keep these APIs around, but I'll need some reasoning behind not being able to use the Attach API.​7 

Michael Glavassevich
In the com.ibm.ws.jmx_fat project there is a test method (JMXTest.testMBeanAttachAPI()) that was disabled due to the problems we were having with using the Attach API. You'll see multiple references to BVT failures in the RTC history. That was over 5 years ago and probably with Java 6. Connecting to an IBM JVM from an Oracle JVM (and vice versa) was also an issue at the time. The Attach API couldn't find the process IDs of JVM's from other vendors.

The API being available in com.ibm.tools.attach.* on IBM JVMs vs. com.sun.tools.attach.* on Oracle JVMs, and having to load up tools.jar (which may not exist in all JREs) made it complicated to use. See com.ibm.ws.jmx.fat.attach.VirtualMachineProxyHelper. This class was written to hide that complexity but not sure it works in every environment (e.g. no tools.jar, non-IBM/non-Oracle JVM) 
.​8.ANDREW GUIBERT
Converting this to a feature per discussion with Kevin Sutter.​

9.Michael Glavassevich 

FYI, I unassigned this from myself. App platform folks need to prioritize. May just want to limit the scope of localConnector-1.0 to Java 8 and earlier.

**Comment by frowe** [comment]
FIXED BY: https://github.com/OpenLiberty/open-liberty/issues/6989

**Comment by hmozaffari** [comment]
I'm facing it in OpenLiberty 21.0.0.10 and Eclipse OpenJ9 11.0.9+11 since jdk.attach module is not available in JRE. May I ask if this issue is resolved or still in OpenLiberty roadmap? 

I realized in OpenLiberty 21.0.0.10 and in java9.options file jdk.attach has been exported:
https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.kernel.boot/publish/platform/java/java9.options#L15

So no matter if we use LocalConnector or not we get the following warning:

`WARNING: Unknown module: jdk.attach specified to --add-exports`

Is there a way to override java9.options the same way we override jvm.options to customize it for JRE 11?
