### ISSUE TITLE
Update Open Liberty landing page to match website redesign

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#8982]
The design team are redesigning the OpenLiberty website so it will look very different. We should update the product landing page to have a similar design aesthetic. 

Also add translation and make sure the page passes accessibility.

What commercial Liberty edition does this feature belong in (pick one)?

       Open Liberty

​

Should this feature be included in the Bluemix buildpack?

 N/A

What SalesForce Skill/Mission Team and legacy RETAIN queue will be responsible for supporting this feature?

N/A

**Comment by mbroz2** [comment]
Regarding FAT Approval, the splash page does not have tests.

Regarding Globalization Approval, the splash page was not previously translated.  As part of this epic, translation support was added.

Regarding Demo Approval, the new splash page was demoed on the 12/17 EOI meeting.

**Comment by mhldr** [comment]
Changes were made here https://github.ibm.com/was-liberty/WS-CD-Open/issues/16331
Feature Test Summary is here https://github.com/openliberty/open-liberty/issues/10294
