### ISSUE TITLE
Standalone config editor

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#8987]
We have an eclipse based config editor, and a web based config editor, but nothing standalone. Suggest we take the admin center editor, package it as an electron app and make it available via openliberty.io. We should consider hosting the server.xml schema online so when we do new releases we don't have to publish a new version of the app.

**Comment by atosak** [comment]
Prototype is done. Delivery is depandant on the scope which is currently not well defined.

**Comment by malincoln** [comment]
Alasdair and Graham reviewed today and determined not likely to complete this feature.  Agreed to close.
