### ISSUE TITLE
Common app and server lifecycle

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#8988]
With a single application per server (likely to be common in a microservices architecture) it makes sense that the server and application have a common lifecycle. In particular, if the application fails to start, the server should exit. This is important in a Docker scenario where the exit of the application will also cause the container to exit signaling the failure to the Docker engine.

**Comment by malincoln** [comment]
Alasdair and Graham reviewed today and determined not likely to complete this feature.  Agreed to close.
