### ISSUE TITLE
APSFOUND-24- Allow properties objects to be configured in server.xml

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#8992]
Resolves [Aha Idea](https://cloud-platform.ideas.ibm.com/ideas/TWAS-I-39)

 

Glassfish provides a way to bind a properties object into JNDI. Customer requests for this in Liberty:

<custom-resource res-type="java.util.Properties" jndi-name="config"
factory-class="org.glassfish.resources.custom.factory.PropertiesFactory">
 <property name="property" value="value"></property>
</custom-resource>

they suggested using an ObjectFactory approach, but if we do something in Liberty something more integrated would be better.

**Comment by samwatibm** [comment]
RFE moved to https://cloud-platform.ideas.aha.io/ideas/TWAS-I-39

**Comment by malincoln** [comment]
Agreed to close.
