### ISSUE TITLE
APSFound 15 - Recovery Log Serviceability Improvements

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#8993]
resolves RFE[ 209851​](https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/External%20Request%20For%20Enhancements#action=com.ibm.team.workitem.viewWorkItem&id=209851)

Applies to Liberty and tWAS.

**Comment by malincoln** [comment]
Discussed with Alasdair and he agreed this should be closed given the RFE has been rejected and per the description it should never have been created.
