### ISSUE TITLE
Optimize Configuring Infinispan for Session Caching

### ISSUE THREAD

**Issue by nmittles** [OpenLiberty/open-liberty#9028]
User story:
"As a user of Liberty, I want to use Infinispan as my JCache provider to back my HTTP sessions with as minimal xml configuration as possible."

Currently our investigation of Infinispan has resulted in the following infinispan.xml:
```
<infinispan>
  <jgroups>
     <stack-file name="jgroups-tcp" path="/default-configs/default-jgroups-tcp.xml"/>
  </jgroups>
  <cache-container>
    <transport stack="jgroups-tcp" />
    <replicated-cache-configuration name="com.ibm.ws.session.*"/>
  </cache-container>
</infinispan>
```

We would like to reduce the amount of configuration needed by the user as much as possible.  Especially for Liberty specific items such as `name="com.ibm.ws.session.*"`.  According to the documentation, everything that can be configured via XML can be configured programmatically.  Therefore, we should be able to detect the presence of Infinispan libraries and use its APIs to configure items such as the replicated-cache-configuration's name. However, further investigation is required to determine if a replicated cache should always be used for HTTP session caching, or whether invalidation cache (what is this?) or distributed caches are appropriate in certain scenarios.

Finally, we should investigate whether configuring the jgroup settings to use `default-jgroups-tcp.xml` is a appropriate in all scenarios or one of the other default jgroups should be used in certain situations: `default-jgroups-udp.xml`, `default-jgroups-ec2.xml`, and `default-jgroups-kubernetes.xml `. Once we know more about the various jgroups, we'll need to decide if creating Liberty config for jgroups makes sense, if we'll automatically detect the environment (ie kubernetes) to programmatically set the jgroup, or if we'll leave it to the user to configure.

Current plan (all of this is conditional on having Infinispan provider):
0. Need to decide which type to default to (replicated-cache vs others). [different story?]
1. If no URI is supplied, then create our own Infinispan xml to prevent the use of isolated caches.  In this case, we will need to choose some jgroups settings as a default.  If the customer doesn't like it, they can supply their own URI to Infinispan config.
2. If URI is supplied and doesn't contain jgroups, add settings per 1 above.
3. If URI is supplied and contains jgroups, check it for com.ibm.ws.session in replication/other setting.  If there, do nothing more.  If absent, then add it, either by programmatic config, or by writing a new config file.

Alternative to 2&3: raise a useful error message instructing customer what to add.

There will be no layer in between such as new httpSessionCache attributes to specify between cache types. The proper way for the user to do this is via URI - already configurable.

**Comment by njr-11** [comment]
The implemented solution involves supplying an infinispan.xml in the absence of any.
Otherwise, it checks all *-cache and *-cache-configuration elements for a cache name pattern matching the cache name prefix for HTTP session persistence.  If not found, then it adds a replicated-cache-configuration for the HTTP session persistence caches.
