### ISSUE TITLE
Provide mechanism to disable 1PC optimization

### ISSUE THREAD

**Issue by jonhawkes** [OpenLiberty/open-liberty#9031]
Add a boolean transaction service configuration attribute "1PCOptimization".

**Comment by djmatthews** [comment]
A new Transaction Manager service configuration property has been provided to allow the one-phase optimization to be disabled.  The name of the property is OnePCOptimization and the value is a boolean indicating whether the optimization is enabled.  By default the value is true, maintaining the existing behaviour and indicating that the optimization is enabled.  The optimization can be disabled by setting the property to a value of false.
