### ISSUE TITLE
GA Blog Post for LG-60 #6079:  Make Liberty JSON log field names be configurable

### ISSUE THREAD

**Issue by Yushan-Lin** [OpenLiberty/open-liberty#9087]
**a) Which Liberty feature does it relate to?**
**i) Human-readable name**
JSON Logging
**ii) Feature name**
logging
**iii)Is this a new feature or is it an update to an existing feature for this release?**
This is an update to the existing logging configuration
**iv) Provide the qualified name of all changed feature deliveries to this release?**
N/A

**b) Who is the target audience?**
Any developers, administrators and liberty users using logging in JSON format.

**c) What does this feature provide in general? Write a sentence or two that introduces it to someone new to the concept.**
In Liberty, users have the option to format their server logs in `basic` or `JSON` format. When logs are in JSON format, users have to specify the sources (message, trace, accessLog, ffdc, audit) they want to send to messages.log or console.log/standard-out.

**d) What is new/changed in this release?**
This feature adds an option for users to replace default JSON field names with any new field names in the JSON logging process. Previously, all JSON field names only have the default Liberty provided field names. Users can now modify the JSON field names directly.

**g) Why should they get excited about this new thing (2-3 sentences)? Explain how this new feature literally makes their life easier? Why should they care? What was the problem before and how does this solve it for them?**
The option to configure JSON field names in Liberty is extremely useful, since Liberty field names may differ from other container field names. For example, a Liberty message end up in a field called "message", while other containers message end up in a field called "log". When users want to visualize their logs on a dashboard, they will see two different visualizations of the messages instead of one. Now, users can modify the Liberty output field names that best matches with other data and view them all in the same visualization.

**f. Explain how to make it work.**
When logs are in JSON format, you can use the` jsonFieldMappings` attribute to replace default field names with new field names. To configure the new field name for all sources, use the following format: `defaultFieldName:newFieldName`. To configure the new field name for a specific source, use the following format:` source:defaultFieldName:newFieldName` where `source` is the source you want to specify (such as message, trace, accessLog, ffdc, audit).
An example of configuring JSON field name by adding the following to bootstrap.properties:
    `com.ibm.ws.logging.json.field.mappings=trace:message:log,ibm_datetime:datetime`
**g) Provide links to any docs in the externally available Knowledge Center. If you don't know the URL, ask your ID person to predict it.**
https://openliberty.io/docs/ref/config/#logging.html
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_logging.html

**h) If relevant, provide links to external articles etc about this technology.**
N/A
**i) Is this feature part of Open Liberty or is it WebSphere Liberty-only?**
This feature is part of Open Liberty.

**j) Attach any images to this work item as .png files.**
N/A

**Comment by Yushan-Lin** [comment]
#6079

**Comment by donbourne** [comment]
@Yushan-Lin we should use an example that shows how to configure this through bootstrap.properties rather than server.xml since server.xml gets read after we may have already output some json-formatted messages.
