### ISSUE TITLE
Liberty splash page redesign

### ISSUE THREAD

**Issue by k8vance88** [OpenLiberty/open-liberty#9114]
Make the following updates & changes:

- [x] General styling to match ol.io home page (no animations).
- [x] Change the main logo (curently png) to the SVG from the ol.io home page for better scaling.
- [x] Add tagline under logo (similar to ol.io homepage) with the following "A lightweight open framework for building and running fast, efficient cloud-native Java microservices." (placeholder for now)
- [x] Add the "Open Liberty integrates with the Open Source community" with the Jakarta and MP logos
- [x] Add link to open-liberty github repo (https://github.com/OpenLiberty/open-liberty)
- [x] Add support link to ol.io (https://openliberty.io/support/)
- [x] Add link to stackoverflow (https://stackoverflow.com/questions/tagged/open-liberty) 

The welcome page is in the open-liberty\dev\com.ibm.ws.transport.http project. With the majority of the pages content in open-liberty\dev\com.ibm.ws.transport.http\resources.

**Comment by mbroz2** [comment]
The following redesign was implemented and delivered:
![image](https://user-images.githubusercontent.com/3076261/70476704-e48eb700-1a9c-11ea-91a4-6ead13a4f537.png)
