### ISSUE TITLE
BETA BLOG 191000 mpMetrics-2.2

### ISSUE THREAD

**Issue by Yushan-Lin** [OpenLiberty/open-liberty#9133]
**a) Which Liberty feature does it relate to?**
**i) Human-readable name**
`MicroProfile Metrics 2.1`
**ii) Feature name**
`mpMetrics-2.1`
**iii)Is this a new feature or is it an update to an existing feature for this release?**
`This is a new feature to support MicroProfile Metrics 2.1 specification.`
** iv) Provide the fully qualified name of all public features ( as '*.esa' filenames) that are delivered as part of this work **
`com.ibm.websphere.appserver.mpMetrics-2.1.esa`

**b) Who is the target audience?**
Application developers and administrators.

**c) What does this feature provide in general? Write a sentence or two that introduces it to someone new to the concept.**
MicroProfile Metrics 2.1 enables developers to instrument metrics in their (microservice) applications for easy monitoring by their operations team.

**d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)**

Previously, the Gauge metric was intended to sample numerical values only, but users could sample non-numeric values (such as String). MicroProfile Metrics 2.1 restricts the scope such that Gauge can only sample numbers now.

Previously, the MetadataBuilder API had reusable() and notReusable() method to set the reusable field to true or false. The MetadataBuilder API has been changed to include a new setter method for the reusable attribute. This change is implemented so the MetadataBuilder API follows the builder pattern.

**e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.**
Include the following in the server.xml:
`<feature>mpMetrics-2.1</feature>`

The following is an example of how to set the reusable field with the MetadataBuilder API:
```
MetadataBuilder mdb = Metadata.builder();

mdb = mdb.withName("metricName").withType(MetricType.COUNTER)
  .reusable(resolveIsReusable());
```
f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

The Changes section under:
https://github.com/eclipse/microprofile-metrics/releases/tag/2.1.0

g. Attach any images to this work item as .png files
N/A

**Comment by donbourne** [comment]
Need to make sure this is all updated to mpMetrics-2.2

**Comment by lauracowen** [comment]
@tomjenningss ^^^ Can you make sure the release blog posts has the right version numbers?
