### ISSUE TITLE
remove logstashCollector-1.1 (but keep logstashCollector-1.0)

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#9162]
Originally logstashCollector-1.1 was created to redo the field names we used in elasticsearch to match the names in bluemixLogCollector-1.0.  Since bluemixLogCollector feature was un-beta'd we need to also remove the logstashCollector-1.1 beta feature.

Note that the logstashCollector-1.0 feature will be unaffected by this change.

- remove topic from beta documentation at https://www.ibm.com/support/knowledgecenter/en/was_beta_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_analytics_logstashv1_1.html
- remove references to logstashCollector-1.1 from https://www.ibm.com/support/knowledgecenter/en/was_beta_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/cwlp_analytics_collectors.html
- remove logstashCollector-1.1 feature and configuration from beta features list and server.xml sample
- remove logstashCollector-1.1 from our code

**Comment by pgunapal** [comment]
Code base is in WebSphere Liberty, closing Issue and re-opening it WS-CD.
