### ISSUE TITLE
API-15-Liberty Batch:  Configure an execution id for batch jobs (vs submitter id)

### ISSUE THREAD

**Issue by atosak** [OpenLiberty/open-liberty#9181]
This feature is for RFE 97707.
The point is that the submitter doesn't have all the necessary access to run the job. The submitter is just some automation thing. They want to define a userid in the batchJmsExecutor element that will be used to run any jobs selected by the message selector. Essentially, a job for this application runs under this ID. Think of it is as a 'runAs' for a batch job.

**Comment by samwatibm** [comment]
RFE's have moved: https://cloud-platform.ideas.aha.io/ideas/TWAS-I-241

**Comment by gcharters** [comment]
Closing as the RFE is no longer under consideration for implementation.

**Comment by malincoln** [comment]
@gcharters I see you closed this one so I'm removing it from the roadmap board.
