### ISSUE TITLE
FAT Approval Test Summary - APSFOUND-1 Liberty Annotation Caching

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#9187]
FAT Approval Test Summary for "APSFOUND-1 Liberty Annotation Caching" https://github.com/OpenLiberty/open-liberty/issues/6329

**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature.

If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by tbitonti** [comment]
FAT Updates:

FAT updates were made to the existing FAT test component "open-liberty/dev/com.ibm.ws.anno_fat"

FAT tests are through FAT Suite "open-liberty/dev/com.ibm.ws.anno_fat/fat/src/com/ibm/ws/tests/anno/FATSuite.java"

FAT suite tests:

These test classes existed previously and are unchanged:

    com.ibm.ws.tests.anno.jandex.JandexAppDefaultAppMgrDefaultTest
    com.ibm.ws.tests.anno.jandex.JandexAppDefaultAppMgrTrueTest
    com.ibm.ws.tests.anno.jandex.JandexAppFalseAppMgrFalseTest
    com.ibm.ws.tests.anno.jandex.JandexAppFalseAppMgrTrueTest
    com.ibm.ws.tests.anno.jandex.JandexAppTrueAppMgrFalseTest
    com.ibm.ws.tests.anno.jandex.JandexAppTrueAppMgrTrueTest

These test classes were added for annotation caching:

    com.ibm.ws.tests.anno.caching.CacheEnablementTest
    com.ibm.ws.tests.anno.caching.MetadataCompleteTest
    com.ibm.ws.tests.anno.caching.MetadataIncompleteTest
    com.ibm.ws.tests.anno.caching.FragmentOrderTest
    com.ibm.ws.tests.anno.caching.LooseConfigTest

An additional test class was provided to gather performance data, but is currently disabled:

    com.ibm.ws.tests.anno.caching.unused.BigAppTest

The new test classes implement the following tests:

    com.ibm.ws.tests.anno.caching.CacheEnablementTest
      cacheEnablement_testDisabledCache()
        Verify that cache function may be disabled by a JVM option
      cacheEnablement_testEnabledCache()
        Verify that cache function is enabled
      cacheEnablement_testReadOnlyCache()
        Verify that cache function will use existing data but will not write new data when the cache is set to read-only mode

    com.ibm.ws.tests.anno.caching.MetadataCompleteTest
      metadataComplete_testUpdate()
        Verify that the cache properly handles data from metadata-complete regions of applications

    com.ibm.ws.tests.anno.caching.MetadataIncompleteTest
      Verify that the cache properly handles data from metadata-complete regions of applications.
      metadataIncomplete_testMyServlet()
        "MyServlet" is stored in WEB-INF/classes
      metadataIncomplete_testSimpleServlet()
        "SimpleTestServlet" stored in WEB-INF/lib/
      metadataIncomplete_testServletA()
        "ServletA" is stored in WEB-INF/lib/testservleta.jar
      metadataIncomplete_testServletB()
        "ServletB" is stored in WEB-INF/lib/testservletb.jar
      metadataIncomplete_testServletC()
        "ServletC" is stored in WEB-INF/lib/testservletc.jar
      metadataIncomplete_testServletD()
        "ServletD" is stored in WEB-INF/lib/testservletd.jar

    com.ibm.ws.tests.anno.caching.FragmentOrderTest
      Verify that cache data is correct for a web application which relies on fragment ordering.
      fragmentOrder_testAbsoluteOrdering()
        Verify that absolute-ordering is handled by the cache.
      fragmentOrder_testAbsoluteOrderingNoRestart()
        Verify several ordering cases.  Verify cache invalidation caused by fragment order changes.

    com.ibm.ws.tests.anno.caching.LooseConfigTest
      Verify that cache function correctly handles loosely configured application data.
      looseConfig_testLooseAppUpdates()
        Verify that loose application data is handled.
        Verify cache invalidation due to changes to application data.
        Verify cache invalidation dur to changes to data at loosely mapped locations.

**Comment by sabolo** [comment]
I have updated this with the FAT approval template.  I see there are comments on the actual testing but question 2 of the template has not been answered.  Please can you update this issue to provide the required details.  Many thanks

**Comment by tbitonti** [comment]
For question (2), the testing level is "4".
