### ISSUE TITLE
Bundling latest swagger UI version

### ISSUE THREAD

**Issue by igbluz** [OpenLiberty/open-liberty#9203]
Is it possible to bundle the latest swagger UI version (3.18.x) with OpenLiberty? There is support for Multipart media type, so one can use the upload feature on the UI when an openapi.yaml is correct defined. This gives a better developer experience.

**Comment by arturdzm** [comment]
Hello, yes we are planning to upgrade to latest version of Swagger UI

**Comment by Eng-Fouad** [comment]
Latest version of Swagger UI fixes #6637 as well.

**Comment by arturdzm** [comment]
The UI was updated in this PR https://github.com/OpenLiberty/open-liberty/pull/9880 to 3.24.1
