### ISSUE TITLE
microprofile-config.properties is added to config sources too late

### ISSUE THREAD

**Issue by srnjak** [OpenLiberty/open-liberty#9204]
I did implementation of `OASFilter`, where I wanted to read config value, which is stored inside `microprofile-config.properties` file. The value hasn't been found.

Code I tried:
```
Config config = ConfigProvider.getConfig();
config.getValue("my.var", String.class)
```

After some investigation, I found out, that config file hadn't been added to config sources yet and `OASFilter` method is being executed.

I printed out all config sources:

> Server XML Application Properties Config Source(600)
Server XML Variables Config Source(500)
System Properties Config Source(400)
Environment Variables Config 1.3 Source
server.xml.variable.config.source(1)

When I tried to run the same code later over REST endpoint, everything worked as expected.

> Server XML Application Properties Config Source(600)
Server XML Variables Config Source(500)
System Properties Config Source(400)
Environment Variables Config 1.3 Source
Properties File Config Source: file:/opt/ol/wlp/usr/servers/defaultServer/apps/expanded/my.project.war/WEB-INF/classes/META-INF/microprofile-config.properties(100)
server.xml.variable.config.source(1)

It seems that `microprofile-config.properties` file is added too late to config sources.

**Comment by tevans78** [comment]
I don’t think this is a question of “too late”. I think it is more likely that the correct thread context class loader is not available when the  filter code is being invoked. Will investigate to confirm that hypothesis.
