### ISSUE TITLE
Not able to execute Stored procedures with using Eclipse Link and buildpack 19.0.0.8

### ISSUE THREAD

**Issue by nandikolla** [OpenLiberty/open-liberty#9266]
Recently we made upgrade from build pack 19.0.0.4 to 19.0.0.8, since then we are not able to execute Oracle Stored procedures using Eclipse Link. 

we are getting below exception 

Error Code: 6550
Internal Exception: java.sql.SQLException: ORA-06550: line 1, column 54:
Caused by: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.8.WAS-v20190716-31d7cf7): org.eclipse.persistence.exceptions.DatabaseException
 ... 95 more

**Comment by dazey3** [comment]
I am working on pulling in the fix for this with #8820

**Comment by nandikolla** [comment]
I am able to run oracle stored procedure after updating  JPA version from 2.1 to 2.2.
Updated server.xml 
<featureManager>
	     <feature>javaee-8.0</feature>
             <feature>localConnector-1.0</feature>
    </featureManager>

**Comment by dazey3** [comment]
@nandikolla #8820 was merged into master and also included in fixpack 19.0.0.11. Can you verify if the issue you were encountering has been resolved in the latest release/master? Thanks!

**Comment by dazey3** [comment]
@nandikolla Please let me know if this issue is still occurring on the latest OpenLiberty fixpack. Otherwise, I will close out this issue soon. Thanks!

**Comment by dazey3** [comment]
Please reopen this issue if it can be reproduced.
