### ISSUE TITLE
implement a Message specific for Kafka connection

### ISSUE THREAD

**Issue by pivicini** [OpenLiberty/open-liberty#9276]
MicroProfile Reactive Messaging is messaging broker agnostic, but it would be very usefull to have a Message extension specific for Kafka so that it would be possible for a producer to specify the key, a partition to write to and headers.
For example under SmallRye Reactive Messaging there is a KafkaMessage that is specific for these kind of tasks.
Generally speaking it would be usefull to have the ability to specify the parameters that a kafka client ProducerRecord accepts.
thank you
Pier

**Comment by Emily-Jiang** [comment]
Thank you @pivicini for opening this issue! 
We are investigating how best to proceed: 
-  Expose this SmallRye API 
- Create an API to fulfill the requirement.

**Comment by tevans78** [comment]
@pivicini In Open Liberty 20.0.0.3 we made it possible to get and set properties directly on Producer and ConsumerRecords. I think that resolves this issue. Thank you for raising it.
https://openliberty.io/blog/2020/03/13/access-specific-kafka-properties-samesite-20003.html#kafka

**Comment by pivicini** [comment]
Thank you for this usefull feature.

Il Mer 18 Mar 2020, 16:56 Tom Evans <notifications@github.com> ha scritto:
