### ISSUE TITLE
Use internal Maven central mirror in TCK FATs for automated builds

### ISSUE THREAD

**Issue by lamkavan** [OpenLiberty/open-liberty#9279]
This is an extension to https://github.com/OpenLiberty/open-liberty/issues/9098 which does not cover TCK FATs. Gathering dependencies from an internal maven central mirror will in theory reduce the chances of a failure. Using an internal mirror will result in less overloading of Maven Central and allow for greater control in retrieving dependencies.

**Comment by jennifer-c** [comment]
Related to issue #9014, as the test failures are due to issues transferring artifacts from Maven.

**Comment by lamkavan** [comment]
A PR has been made and merged. This issue will close once the changes reach the master branch without issues.
