### ISSUE TITLE
Investigate vertx interprocess backpressure

### ISSUE THREAD

**Issue by hughesj** [OpenLiberty/open-liberty#9308]
Understand the capabilities of vertx, backpressure and the event bus to help design #8962 (backpressure across OpenLiberty and vertx processes).

**Comment by hutchig** [comment]
Topics that need to be researched for WAD:

# Use Case
# Testing
# Developer Experience
# Communications
# Cross Server Clustering/Point-to-Point
## Network Security
# Threads
# Lifecycle
## Grace Shutdown on inbound and outbound work
## Port Opening on Channel Config Discovery
# Comms Stack
## Ports
## User Experience of Comms Config
# Metrics
# Health
# CDI
## Injection Into 
## 'Request' Scope or Custom Scope
# API
# Transitive Back-Pressure
# Transitive 'Ack' 
# User Debug
# RAAS
## FFDC
## Tracing
 

# (Open)Tracing
# Security
## Authentication
### Groups
### Authorisation
## Certificates
### Remote
### Local/Client
