### ISSUE TITLE
We need to update he wording of message CWWKS5523E or create a new message

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#9309]
If the public key specified with the mp.jwt.verify.publickey property in the microprofile-config.properties file is "bad" (or in this specific case, missing the "-----BEGIN PUBLIC KEY-----" and "-----END PUBLIC KEY-----"), we get the following failure message.
CWWKS5523E: The MicroProfile JWT feature cannot authenticate the request because a valid JWT cannot be created from the token included in the request. CWWKS6029E: The JSON Web Token (JWT) cannot be validated because a signing key cannot be found. The configured signature algorithm [RS256] requires a key to validate the token. 
The message is misleading as we're not trying to "create" a JWT.  We're trying to validate the JWT.  If we're using this same message to create a JWT (in the OP), we'll need to create a second message for use when validating JWT's.  If we don't use this message during creation, we can just clarify this message.

**Comment by brutif** [comment]
The message is in MicroProfileJwtMessages.nlsprops, so it's not used by any OP, it can just be edited.
