### ISSUE TITLE
Refactor OpenTracing features to use common module

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#9316]
There are code duplication in `mpOpenTracing-1.0`, `mpOpenTracing-1.1`, `mpOpenTracing-1.2` and `mpOpenTracing-1.3`.  Refactor them to use a share code base.

**Comment by fmhwong** [comment]
@tevans78 We probably will one more OpenTracing release in 4Q2019 or 1Q2020 and OpenTracing project will be deprecated in 2Q2020.  It will be superseded by OpenTelemetry.  Does it still worth the effort to consolidate them into common code?

cc @donbourne

**Comment by tevans78** [comment]
What do you mean by deprecated? Those features will still be in service. If someone finds a bug in one which is common to all, it is better not to have to fix it four times.

**Comment by fmhwong** [comment]
Not planning to do this for now.
