### ISSUE TITLE
API-31: FAT Approval Test Summary for MP GraphQL 1.0

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/open-liberty#9319]
**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature.

If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

**The MP GraphQL 1.0 TCK is executed under _com.ibm.ws.microprofile.graphql_fat_tck_ - this already includes a fairly exhaustive test suite that covers compatibility with the specification.  It covers normal function tests, validation, exception handling, etc.**

**The _com.ibm.ws.microprofile.graphql.1.0_fat_ project contains additional tests - some of which overlap TCK tests but in slightly different variations.  It also covers edge cases not currently tested in the TCK as well as OpenLiberty-specific behavior including diagnostic-gathering, per-request logging, some security, etc.**

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths.  There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here.  Error/outlying scenarios are not really covered.  There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios.  There is a risk when the feature is used outside the golden paths however we are confident on the golden path.  Note:  This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature.  The testing covers all golden path cases as well as all the error/outlying scenarios that make sense.  We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

**4**

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer.  Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above.  We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5.  We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc.  Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**N/A**

**Comment by andymc12** [comment]
This FAT Approval Test Summary is for Epic Issue #7956 - MP GraphQL 1.0.

**Comment by dave-waddling** [comment]
Hi @andymc12,

Thanks for completing the Feature Test Summary. Having reviewed all is looking good and the testing passed cleanly in the latest SOE. I'll add the FAT Focal Approval to the feature Epic now.

**Comment by dave-waddling** [comment]
Re-opening as I noticed there was a new functional delivery recently merged when I added the FAT Focal Approval. I'd like that change to make it through an SOE before approving.

**Comment by dave-waddling** [comment]
Hi @andymc12,

I've just checked the latest SOE and all of the testing is passing perfectly. I'll add the FAT Focal Approval to the parent epic now.
