### ISSUE TITLE
FAT Approval Test Summary for LG-234: MicroProfile Metrics 2.2

### ISSUE THREAD

**Issue by Yushan-Lin** [OpenLiberty/open-liberty#9323]
**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

The TCK (FAT) is the comprehensive test coverage for this feature. This was developed in tandem with the Red Hat team to cover the extent of the changes to MicroProfile Metrics from 2.0 to 2.2. It should be noted that the TCK extends on top of the MicroProfile Metrics 2.0 TCK. It provides a thorough coverage of the use case of the MicroProfile Metrics API usage (Java API + annotation usage).

Throughout development there were manual execution of the TCK (i.e as RC releases were made for 2.2)

Regarding FAT test coverage, the FAT project introduced is the   `com.ibm.ws.microprofile.metrics.2.2_fat_tck` which encompasses the MicroProfile Metrics 2.2 TCK.
See the MicroProfile Metrics 2.2 release : https://github.com/eclipse/microprofile-metrics/releases/tag/2.2

Note: As the MicroProfile Metrics 2.1 specification is effectively _skipped_. the TCK for MicroProfile Metrics 2.2 is similar to the MicroProfile Metrics 2.0 TCK. There have been improvements (i.e refactor/tweaks + minor additions ore removals) but overall coverage is the same as there have been **no** additional functionality introduced in the `2.2` specification in relation to the `2.0` specification.

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below. This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths. There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here. Error/outlying scenarios are not really covered. There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios. There is a risk when the feature is used outside the golden paths however we are confident on the golden path. Note: This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios. While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature. The testing covers all golden path cases as well as all the error/outlying scenarios that make sense. We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

4

**Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer. Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above. We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5. We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc. Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)**

N/A

**Comment by Channyboy** [comment]
@sabolo 
Hi Kevin. May you please review.

In #8653 you mentioned the mpConfig issue RTC268458 would be a blocker.
RTC268458  seems to be closed now.

**Comment by Channyboy** [comment]
accidentally hit close

**Comment by Channyboy** [comment]
To expand:
The TCK of MicroProfile Metrics 2.1 was expanded on top of the TCK of MicroProfile Metrics 2.0.
There was one change that affected the code to be changed in an implementation of MicroProfile Metrics 2.1.
Similarily, the metrics community modified the TCK to test for this change.

It was decided that this change in `2.1` was a breaking change and that a `2.2` release  was needed to revert the change into `2.1`.
In effect the code for `2.2` is the same as `2.0`. The TCK had to be reverted too and similarily the TCK for `2.2` tests the same coverage as `2.0`.
