### ISSUE TITLE
RP is incorrectly determining token type

### ISSUE THREAD

**Issue by c00crane** [OpenLiberty/open-liberty#9332]
TS002862627 
We have an OP that is issuing an opaque token.  The token contains a "." and our RP is finding that "." and determining that the token is a JWT.  It tries but fails to parse that "JWT" token.
The token in question is:  00D4P0000010NAb!ARoAQEDiHHa8rCOzYb4doaCL8HGvQRtP0SRQ9hw3hcB1ajOaIhArhPM4aNMfkLe9RX3kJAr7cO6OzFsYBoyjIlESaf.532sR

We need to determine the token type with different logic.

**Comment by ayoho** [comment]
@chunlongliang-ibm

**Comment by ayoho** [comment]
We're assuming this has been fixed since Barb hasn't heard back from the customer, and there were a couple of fixes delivered (we believe) that made it into the 20.0.0.2 release (possibly earlier).
