### ISSUE TITLE
FAT Approval Test Summary for SEC-381

### ISSUE THREAD

**Issue by ayoho** [OpenLiberty/open-liberty#9335]
**1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.**

**2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below. This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered

1 - We have minimal automated coverage of the feature including golden paths. There is a relatively high risk that defects or issues could be found in this feature.

2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here. Error/outlying scenarios are not really covered. There are likely risks that issues may exist in the golden paths

3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios. There is a risk when the feature is used outside the golden paths however we are confident on the golden path. Note: This may still be a valid end state for a feature... things like Beta features may well suffice at this level.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios. While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.

5 - We have delivered all automated testing we believe is needed for this feature. The testing covers all golden path cases as well as all the error/outlying scenarios that make sense. We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer. Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above. We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5. We need your honest assessment as a team and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc. Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by acdemyers** [comment]
There are 2 parts to this enhancement to trusted in SSL connections:
1.  Adding a certificate from an environment variable to a keystore.  The environment variable value can either be the certificate or a file path to a certificate.   I'll refer to this a the **env-certs** feature when talking about tests.

2.  Using the JDK default truststore for trust in addition to the configured truststore on when enabled.   I'll refer to this as the **default-certs** feature.

**Comment by acdemyers** [comment]
1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule.

For **env-certs**

The tests are added to com.ibm.ws.ssl_fat project in the WS-CL-Open.    Include in the TrustCertScenarioTest.java.  Test cover:

Test to make sure an ssl connection can get trust from a certificate from the environment variable.  First the tests makes an ssl connection that fails with a cert path error then set the keystore environment variable to include the trusted certificate needed and the ssl connection is successful.

Test to make sure a ssl connection can get trust from a cert file the keystore environment variable points to.  The test first makes a ssl connection that fails with a cert path error then set the keystore environment to point to a file that include the trusted certificate needed and the ssl connection is successful.

Test to make sure SSL client cert authentication can get trust from a certificate stored in an keystore environment variable.   First run ssl connection with client authentication enabled and make sure the server side of the communication get the trust failure.  Add the certificate needed for trust to the keystore environment variable and the ssl connection succeeds.

Test to make sure SSL client cert authentication can get trust from a certificate stored in file referenced by the keystore environment variable.   First run ssl connection with client authentication enabled and make sure the server side of the communication get the trust failure.  Add the path to a certificate file to the keystore environment variable and the ssl connection succeeds.

Test to make sure a warning is logged when a corrupt certificate is set on a keystore environment variable.   Put a corrupt cert in the keystore environment variable start the server and make sure a warning is put in the logs saying the there was a problem reading the certificate.   But it does not stop a SSLContext from getting created.

Test to make sure a warning is logged when a bad file location is set on a keystore environment variable.   Put a corrupt file path in the keystore environment variable start the server and make sure a warning is put in the logs saying the there was a problem reading the certificate.   But it does not stop a SSLContext from getting created.

**Comment by acdemyers** [comment]
1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature. The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). Automated testing is expected for all features with manual testing considered an exception to the rule..

For default-certs

The tests are added to com.ibm.ws.ssl_fat project in the WS-CL-Open. Include in the TrustCertScenarioTest.java. Test cover:

Test to make sure a SSL configuration with trustDefaultCerts enabled can access a server containing a certificate contained in the JDK's default trust store cacerts.   First access the server with trustDefaultCerts disabled make sure the is a cert path error.  Dynamically enable trustDefaultCerts, then access the server again successfully.

Test to make sure errors CWPKI0823E and CWPKI0828E are written to the logs if the trustDefaultCerts attribute is enabled and both the configured truststore and the JDK default do not have trust.
  
Test to make sure a SSL configuration with trustDefaultCerts enabled and the JDK configured to use an alternate default using the javax.net.ssl.* properties that access a server from trust for alternate default truststore.   Start the server with javax.net.ssl.* properties set and trustDefaultCerts disabled then access a server and get a cert path error.   Enable trustDefaultCerts and successfully access the server.

Test to make sure the warning CWPKI0825W is written to the logs if the server try to access the JDK default truststore and the JDK cannot load the default truststore.  Done with the javax.net.ssl.* properties.
 
Test to make sure when trustDefaultCerts is enabled and the server has client authentication enabled that the server trust on the client comes form the JDK default.   Enable a server with client authentication and make sure the server gets a cert path error when the server is access.   Enable trustDefaultCerts have the client access the server again and access succeeds.

**Comment by acdemyers** [comment]
2) Collectively as a team you need to assess your confidence in the testing delivered based on the values below. This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.

4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios. While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.


What was tested is listed above.
