### ISSUE TITLE
Add new metric representing Process CPU Time to mpMetrics-2.2

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#9383]
new Gauge metric called Process CPU Time, which is getProcessCpuTime from the OSMXBean https://docs.oracle.com/javase/7/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html
description is “Returns the CPU time used by the process on which the Java virtual machine is running in nanoseconds.”

need to take care as this is implemented differently on different JVMs

**Comment by jennifer-c** [comment]
Since the implementation of mpMetrics-2.0 and 2.2 are pretty much the same, PR #9945 has covered 2.2 as well.
