### ISSUE TITLE
LG-248: Add new metric representing Process CPU Time to mpMetrics-2.0

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#9384]
new Gauge metric called Process CPU Time, which is getProcessCpuTime from the OSMXBean https://docs.oracle.com/javase/7/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html
description is “Returns the CPU time used by the process on which the Java virtual machine is running in nanoseconds.”

need to take care as this is implemented differently on different JVMs

**Comment by donbourne** [comment]
Sorry, took short cut on this thinking it was one line change that didn't warrant a lot of process.  Would like to request demo / FAT / globalization approvals to close this properly.

This issue adds a single new metric to our set of base metrics for mpMetrics, the value of which it gets from the OS MXBean.  We have 3 other values that we currently pull from the same MXBean, so the pattern for doing that is well understood.  We also have code that handles the JMX -> mpMetrics bridging, so this was just a one line code addition copied from the other 3.  (see code in #9945)

The metric is part of the MP Metrics spec.  It's an optional metric.

@tevans78 , we demo'd this new metric to the SVT team, showing them the new metric and how it appears in grafana dashboards.

@sabolo , as you can see from #9945, this PR includes one more value from the OS MXBean (we already pull 3 metrics from the OS MXBean) into the MetricsRegistry for mpMetrics.  No additional tests were needed since the bridging of metrics from JMX is already well tested through the MP Metrics TCK.

@marikaj123 , translations have been checked in as expected for this (for the description of the metric).  I've confirmed that the new description appears in the translation files.

**Comment by tevans78** [comment]
@donbourne please demo this at an EOI. I can give you the approval once the demo has been added to an upcoming EOI agenda.

**Comment by sabolo** [comment]
Hi...  This has just come on our radar.  Can you please complete the feature test summary so we can work through the review.  Thanks

**Comment by sabolo** [comment]
I have created the feature test summary issue for you and put it under this Epic.  Please complete and advise when ready.  Thanks

**Comment by jennifer-c** [comment]
@sabolo I've filled out the feature test summary.

**Comment by jennifer-c** [comment]
@tevans78 I've added myself to the agenda for the next EOI call.
