### ISSUE TITLE
Guide: Create OpenTracing guide for Jaeger 

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/open-liberty#9417]
LG-37: Jaeger support in MicroProfile Open Tracing https://github.com/OpenLiberty/open-liberty/issues/6906

Please create a new OpenTracing guide and use Jaeger as the tracing backend.

**Comment by gkwan-ibm** [comment]
Issue moved to [OpenLiberty/guides-common #360](https://github.com/OpenLiberty/guides-common/issues/360) via [**ZenHub**](https://www.zenhub.com/)
