### ISSUE TITLE
With 19.0.0.10 we are unable to create/start liberty as windows service

### ISSUE THREAD

**Issue by c-koell** [OpenLiberty/open-liberty#9440]
After upgrading to 19.0.0.10 we have problems starting Liberty as windows service.

The service is created normally but if we try to start the service we see ..
```
sc start TestServer
SERVICE_NAME: TestServer
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 2  START_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x7d0
        PID                : 5960
        FLAGS              :
```
The Service immediately stops afterwards.
After downgrading to 19.0.0.9 and installing as Windows Service it starts normal.

Maybe a problem from https://github.com/OpenLiberty/open-liberty/issues/8842

I have tried it on Windows Server 2019 and Windows Server 2016. On both the same problem.

**Comment by billw1024** [comment]
does starting the server this way allow it to work:
server startWinService serverName [options]

as per this documentation:
https://www.ibm.com/support/knowledgecenter/en/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_setup_new_server_winserv.html

**Comment by c-koell** [comment]
Yes i have tried it as described but it doesn't start ...

**Comment by hlhoots** [comment]
when you start the server with 'server startWinService <servername>' it should create a commons-daemon.<date>.log file.  what are the contents of that file when you encounter the server not physically starting up ?

**Comment by c-koell** [comment]
Hi. It seems it was my mistake ... sorry for the noise ...
