### ISSUE TITLE
Add JSON Web Encryption (JWE) support (jwtBuilder and jwtConsumer)

### ISSUE THREAD

**Issue by jtmulvey** [OpenLiberty/open-liberty#9444]
Today we support JWS (JSON Web Signature) JWTs https://datatracker.ietf.org/doc/rfc7515/. This feature would add support in Open Liberty for JWEs (JSON Web Encyption) tokens https://datatracker.ietf.org/doc/rfc7516/.

**Comment by teddyjtorres** [comment]
MP JWT 1.2 epic #11022 will add support to accept encrypted claims and nested tokens using JWE. This Epic will then focus on the generation side or it may be determined if it should be part of the MP JWT 1.2 work in #11022.
