### ISSUE TITLE
Offline validation of User Token and Service Token  

### ISSUE THREAD

**Issue by celek** [OpenLiberty/open-liberty#9450]
How to validate a User Token and Service Token offline ? Can they behave more like a JWT token  (meaning the base64 decode will list the expiry time) and the client can calculate if the bearer has been tempered with ?

**Comment by brutif** [comment]
This might help - Liberty's jwt-1.0 feature includes api's for building and consuming (validating) JWT's independent of any kind of user authentication.  There are also open source libraries that can do this. 

The Liberty docs are here https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_sec_consume_jwt.html

Unfortunately they don't have a good end-to-end consumer example. 

That bluemix URL is a "JWK" (Json Web Keys) URL that hold the keys to decode the jwt.  A jwt-1.0 consumer can be configured to read it to decode jwt's by adding it as "jwkEndpointUrl" in server.xml as described here: 
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.liberty.autogen.base.doc/ae/rwlp_config_jwtConsumer.html

Once that's done, you'd new up a JwtConsumer(config_id_in_server.xml) and pass it the encoded jwt to get back a "JwtToken" object,  that object has methods on it to extract the contents of the jwt, and will throw an exception if the jwt's not valid. 

https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.jwt_1.1-javadoc/com/ibm/websphere/security/jwt/JwtConsumer.html#%3Cinit%3E(java.lang.String)

**Comment by celek** [comment]
@brutif thanks - is there a key/signature I can use to validate the JWT has not been tempered ?  Check http://jwt.io - they seem to imply we need a secret to validate the signature
Nothing about validating the user Session offline ?

**Comment by brutif** [comment]
@celek one of the keys in https://iam.ng.bluemix.net/oidc/keys is the one you need.  Within the jwt, there should be a "kid" claim, that describes which key to use.  I've never tried pasting one of those into jwt.io to see if it works or not.

**Comment by celek** [comment]
Got it @brutif  - that's the issue though, the token I got  from oc sa get-token has not kid - this means I can't validate it - you agree ?  I tried with all signature and they all failed. Usually (unless I misunderstood) the oidc publishes the keys for its own ouath - I would be surprised if bluemix public certificate would actually match my own openshift cluster - otherwise it means I could pretend to be bluemix public right ? 

{
  "alg": "RS256",
  "kid": ""
}

**Comment by brutif** [comment]
Right, if you got a token from openshift, I think you would need to validate it against your openshift cluster's "TokenReview" endpoint.  https://docs.openshift.com/container-platform/3.7/rest_api/apis-authentication.k8s.io/v1.TokenReview.html

Bluemix and Openshift probably aren't that tightly integrated (yet).

**Comment by celek** [comment]
Good start, seems to be perfect for JWT Service Token, but not User Token,,,,

**Comment by celek** [comment]
seems to be what I need - thanks - doing more tests....

**Comment by brutif** [comment]
@celek I'm going to close this as it's been inactive for a long time,  if that's not the right thing please let me know.
