### ISSUE TITLE
NullPointerExceptions in com.ibm.ws.security.wim.registry.util.*Bridge classes

### ISSUE THREAD

**Issue by jvanhill** [OpenLiberty/open-liberty#9473]
The bridge classes for WIMUserRegistry are doing get(...) calls on multi-valued WIM properties (Lists) for the output properties returned in the Entity without checking whether they are null and this is leading to NPEs. The classes need to be inspected and return String.valueOf(null) in the same way that a single valued property would be returned if it were null.

An example stack trace from 18004 is below.

```
java.lang.NullPointerException
	at com.ibm.ws.security.wim.registry.util.DisplayNameBridge.getGroupDisplayName(DisplayNameBridge.java:361)
	at com.ibm.ws.security.wim.registry.WIMUserRegistry.getGroupDisplayName(WIMUserRegistry.java:373)
       ...
```

**Comment by ryanesch** [comment]
This looks to be fixed by https://github.com/OpenLiberty/open-liberty/issues/7539 in https://github.com/OpenLiberty/open-liberty/pull/7916
