### ISSUE TITLE
AnnotationScanner from openApi ignores  mp.openapi.scan.exclude property

### ISSUE THREAD

**Issue by anton-balaniuc** [OpenLiberty/open-liberty#9483]
According to microprofile [documentation](https://download.eclipse.org/microprofile/microprofile-open-api-1.0/microprofile-openapi-spec.html#_core_configurations) it is possible to exclude certain packages and classes from OpenAPI scanning 
`mp.openapi.scan.exclude.packages` and `mp.openapi.scan.exclude.classes`.  This is working fine until there are classes which extend `javax.ws.rs.core.Application`. In this case `com.ibm.ws.microprofile.openapi.AnnotationScanner` ignores those properties and actually reads the class. 

For example: 
 microprofile-config.properties :
```
mp.openapi.scan.exclude.packages=com.example.excluded 
```
com.example.excluded.DemoRestApplication 
```
package com.example.excluded;

import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

@ApplicationPath("/data1")
public class DemoRestApplication extends Application {
}
```
trace of com.ibm.ws.microprofile.openapi.*
```
com.ibm.ws.microprofile.openapi.ApplicationProcessor         1 Retrieved configuration values : ConfigProcessor : {
mp.openapi.model.reader=null
mp.openapi.filter=null
mp.openapi.scan.disable=false
mp.openapi.extensions.liberty.validation=true
mp.openapi.extensions.liberty.file.polling.interval=2
mp.openapi.scan.classes=null
mp.openapi.scan.packages=null
mp.openapi.scan.exclude.classes=null
mp.openapi.scan.exclude.packages=[com.example.excluded]
mp.openapi.servers=null
mp.openapi.servers.path.=null
mp.openapi.servers.operation.=null
}
com.ibm.ws.microprofile.openapi.AnnotationScanner            1 Found application classes:  
                                                                                                               [com.example.demo.DemoRestApplication, com.example.excluded.DemoRestApplication]
```
`com.example.excluded.DemoRestApplication` hasn't been excluded.

**Comment by anton-balaniuc** [comment]
@leochr, thanks a lot for your replay, I have actually created a PR for solving this issue https://github.com/OpenLiberty/open-liberty/pull/9486, but I am not quite sure if this is the right approach. Can you please have a look when you have a chance? 

Best Regards, 
Anton Balaniuc

**Comment by leochr** [comment]
@anton-balaniuc Thanks for the PR! Please see my comment when you get a chance: https://github.com/OpenLiberty/open-liberty/pull/9486#pullrequestreview-307258024

**Comment by leochr** [comment]
The PR is being reviewed and hopefully be merged soon

**Comment by leochr** [comment]
PR #9486 is now merged. Closing. Thanks for the fix @anton-balaniuc!
