### ISSUE TITLE
OIDC RP does not reject requests that match more than one filter

### ISSUE THREAD

**Issue by barbj** [OpenLiberty/open-liberty#9512]
TS002875940
With OIDC, if there is a filter match for more than one OP, the request will be rejected.  With RPs, this is not happening.  OIDC should be rejecting the request if it matches the filter for more than one RP.  

This issue is easily reproduced by using the same authfilter reference for two RPs.

**Comment by brutif** [comment]
Recreated.  I think we should issue a warning when the config is processed if >1 RP config is using the same authFilter.  That's more efficient than scanning all RP's on every inbound request.

**Comment by barbj** [comment]
@brutif 
Using the exact same authfilter is only one case where this could happen.  For instance, lets take the examples in the KC:

<authFilter id="myAuthFilter1">
         <requestUrl id="myRequestUrl" urlPattern="/SimpleServlet" matchType="contains"/>
</authFilter>


<authFilter id="myAuthFilter2">
         <remoteAddress id="myRemoteAddress" ip="127.0.0.*" matchType="equals"/>
</authFilter>

Those don't appear to be the same filter at all.

Now say you get a request to https://host:port/contextroot/**SimpleServlet** .  That matches **myAuthFilter1**.  But the request comes from **127.9.3.124**.  That matches **myAuthFilter2**.  In this case, we should throw an exception.

**Comment by brutif** [comment]
I'm confused, I thought we were trying to detect when >1 RP references the same auth filter.  We probably need to walk through this scenario

**Comment by brutif** [comment]
@barbj reviewing with @chunlongliang-ibm we're not going to change default behavior for this but we will log a warning if >1 matching filter is found.

**Comment by brutif** [comment]
We'll warn on 2 cases, 1) >1 client refers to same authfilter, and 2) request matches more than one auth filter.

**Comment by jmgomez77** [comment]
Kindly suggest you to document how to configure 2 filters with different criteria for 1 oidc client, e.g. in the example above, what if we need to associate one openid client to both myAuthFilter1 and myAuthFilter2? Thanks!
