### ISSUE TITLE
Unfriendly user error message displayed and user is blocked from signing in to their application when their liberty session expires

### ISSUE THREAD

**Issue by barbj** [OpenLiberty/open-liberty#9516]
TS002922020
The Liberty OIDC client is configured to consume App ID as the OIDC provider. 
An app uses App ID to authenticate its users. Whenever a user visits the app, they're redirected to App ID, as expected. However, if a user does not complete authentication in time, and the session that was established with Liberty expires, when used does complete authentication, they're redirected back to Liberty and receive the following error message:

**CWOAU0073E: An error was encountered while authenticating a user.  Please try authenticating again, or contact the site administrator if the problem persists.**

The liberty **authenticationTimeLimit** property is set to 12 hours for the app. This means that if the app user signs out the app at the end of a business day but does not close their browser, and then returns the next day to sign in again, they can't because they do not have a valid liberty cookie and will receive the CWOAU0073E error.

**Desired Solution**
Two possible options:

1. Update the existing error message to provide more meaningful information to the user (i.e. tell the user that their session has expired and to sign back in they need to return to the application URL to start over.)
2. Update the existing error message as described in (1) and provide the option for the user to return to the sign in page and enable them to sign in again.

**Comment by fodonne** [comment]
@barbj I've been informed by our Watson Care Manager (WCM) customer support team that one of  our customers, Washoe, encountered the above error. Their users (attorneys) were attempting to access WCM while in court and were unable to do so due to the error. This led to unacceptable delays. As a result of this, can we escalate a fix for this issue as soon as possible please?

**Comment by brutif** [comment]
requesting logs and trace.

**Comment by brutif** [comment]
We've updated the message to the user can take the correct action when this happens.  Since we couldn't get trace we can't take further action.  Closing, please reopen if more is needed.

**Comment by fodonne** [comment]
Hi @brutif 
Ok, that's fine. Can you share with me the wording of the message that you intend to surface?  This wording will need to conform to IBM writing guidelines. Thanks, Fionnuala

**Comment by brutif** [comment]
Hi @fodonne, #9832 changes the message from:

CWOAU0073E: An error was encountered while authenticating a user. Please try authenticating again, or contact the site administrator if the problem persists.

to:

CWOAU0073E: An error was encountered while authenticating a user. Please try closing the web browser and authenticating again, or contact the site administrator if the problem persists.

(closing the browser should clear up any mangled state cookies).

**Comment by fodonne** [comment]
Hi @brutif 
I asked ID (information design) to review the new message and to confirm if it complied with IBM writing guidelines. They recommended that the message be changed to this in order to comply - 

_CWOAU0073E: An authentication error occurred. Try closing the web browser and authenticating again, or contact the site administrator if the problem persists._

Thanks, Fionnuala

**Comment by brutif** [comment]
@fodonne, thanks, an updated message has already been delivered on #9832

**Comment by fodonne** [comment]
@brutif So is it the case that the suggested rewrite hasn't been taken onboard? That update, #9832 went through 15 days ago... The message should conform to IBM writing guidelines.

**Comment by brutif** [comment]
right, ID did not comment on the original change, so it went through as is

**Comment by fodonne** [comment]
@brutif Is there scope to get it updated? Our application should adhere to IBM writing guidelines...

**Comment by brutif** [comment]
@fodonne the change is very minor, but I will bring in the updated wording on my next set of changes, and put a remark here when that happens.

**Comment by brutif** [comment]
updated wording will go in on #10045

**Comment by fodonne** [comment]
@brutif Thank you very much! 👍

**Comment by fodonne** [comment]
@brutif Can you confirm when 10045 is to be released? Is it the end of this month (i.e. January 2020)? Our WCM QA team are reporting still seeing the old wording after leaving themselves logged in to WCM over the weekend  - "CWOAU0073E: An error was encountered while authenticating a user. Please try authenticating again, or contact the site administrator if the problem persists."

**Comment by brutif** [comment]
@fodonne the english version was merged into the product on 12/10 and is included in 20.001 but it looks like the translated versions have not come back yet @pnickoll , I guess the translations for open-liberty/dev/com.ibm.ws.security.oauth/resources/com/ibm/ws/security/oauth20/resources/ProviderMsgs.nlsprops will make 20.002?

**Comment by fodonne** [comment]
Thanks @brutif. It's the english version that we should be seeing. Is it the case that we won't see this until the other translated versions are merged. If @pnickoll could confirm release date for these translation that would be some appreciated. Just need to set expectations on my end. Thanks.

**Comment by brutif** [comment]
@fodonne the message comes from the provider side, so it won't change until the provider (not the client) is updated to 20001.

**Comment by fodonne** [comment]
Ok, thanks @brutif. WCM releases on a monthly basis so can i safely assume that this won't be available in jan 2020 but will be available in Feb 2020?

**Comment by brutif** [comment]
@fodonne it's hard to say for sure how WCM ticks but that seems like a reasonable assumption.  A look in messages.log of the provider and client sides at startup should show the liberty versions in use.

**Comment by fodonne** [comment]
Ok, thanks @brutif
