### ISSUE TITLE
Allow Kafka-specific parameters to be directly used in a MP Reactive Messaging application

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#9570]

**Comment by tevans78** [comment]
The actual requirement described in #9276 is to allow Kafka specific parameters to be set, to make it `possible for a producer to specify the key, a partition to write to and headers`. It goes on to say `it would be usefull to have the ability to specify the parameters that a kafka client ProducerRecord accepts`.

Having done some investigation, it is far easier to allow ProducerRecord parameters to be set directly than it is to expose them through the SmallRye KafkaMessage API.

**Comment by tevans78** [comment]
Since the ProducerRecord and ConsumerRecord interfaces are part of the Kafka client API that the application provides, this solution will require minimal internal code changes and almost no changes to externals. At most we may have to document some special configuration properties (set via MP Config).

**Comment by Azquelt** [comment]
## Design suggestion

### Producer

 - user can return a `ProducerRecord` as a message payload
 - if topic explicitly defined in config, it overrides the ProducerRecord

#### Example 1
```java
@Outgoing("food")
public Message<ProducerRecord> publish() {
   ProducerRecord pr = new ProducerRecord("myTopic", "myValue");
   return Message.of(pr);
}
```
```properties
mp.reactive.messaging.food.connector=liberty-kafka
mp.reactive.messaging.food.topic=myOtherTopic #Overrides value in code
```

#### Example 2
```java
@Outgoing("food")
public Message<ProducerRecord<K, V>> publish() {
   ProducerRecord pr = new ProducerRecord("myTopic", "myValue");
   return Message.of(pr);
}
```
```properties
mp.reactive.messaging.food.connector=liberty-kafka
# No topic defined, message goes to "myTopic" as set in users ProducerRecord
```

#### Example 3 (maintaining existing behaviour)
```java
@Outgoing("food")
public Message<String> publish() {
   return Message.of("myValue");
}
```
```properties
mp.reactive.messaging.food.connector=liberty-kafka
# No topic defined, message goes to "food" as set in @Outgoing annotation
```

### Consumer

No configuration, user can call `Message.unwrap()` to retrieve the `ConsumerRecord` associated with the message.

```java
@Incoming("food")
public CompletionStage<Void> consume(Message<String> message) {
    ConsumerRecord<String, String> cr = (ConsumerRecord<String, String>) message.unwrap(ConsumerRecord.class);
    cr.key();
    cr.headers();
    // whatever
}
```

**Comment by NottyCode** [comment]
@tevans78 reading this over it seems you need documentation. In addition you say the design doesn't change externals, but based on the examples I assume that `ProducerRecord` and `ConsumerRecord` are kafka APIs which are not currently a product external.

**Comment by tevans78** [comment]
@Emily-Jiang What kind of documentation do you think this needs?
@NottyCode Liberty is not exposing a new API here. The Kafka Client API is included in the user's appication. We are simply allowing the user to use that API in their MP Reactive Messaging code.

**Comment by Emily-Jiang** [comment]
@tevans78 The documentation will be a blog on open liberty to show and tell how to set or retrieve Kafka headers. The doc will be focusing on `how` aspect in end user's code, nothing about the Liberty internal.

**Comment by atosak** [comment]
Can this be closed?

**Comment by tevans78** [comment]
Yes, the code is GA and the blog post is done.
