### ISSUE TITLE
Springboot fatjar occasionally fails to start

### ISSUE THREAD

**Issue by gjdeval** [OpenLiberty/open-liberty#9575]
About 1 time out of 25-50 Liberty startups, the springboot fatjar app fails to start. I've captured logs for a couple of these failures, and they show
```
[ERROR   ] CWWKE0701E: FrameworkEvent ERROR java.lang.IllegalStateException: Configuration pid com.ibm.ws.app.manager_0 was deleted.
	at com.ibm.ws.config.admin.internal.ExtendedConfigurationImpl.exceptionIfDeleted(ExtendedConfigurationImpl.java:666)
	at [internal classes]
```
Here are logs from a couple of the failure cases.
[springboot-startup-fail-logs (1).zip](https://github.com/OpenLiberty/open-liberty/files/3790970/springboot-startup-fail-logs.1.zip)
The app is placed in <install>/wlp/server/<server-name>/dropins/spring  directory

Here is the server.xml (renamed as .txt for upload)
[server.txt](https://github.com/OpenLiberty/open-liberty/files/3790999/server.txt)

Here is the fatjar (renamed as .zip for upload).
[authservice-springboot-2.1.1-SNAPSHOT.zip](https://github.com/OpenLiberty/open-liberty/files/3790991/authservice-springboot-2.1.1-SNAPSHOT.zip)

**Comment by tjwatson** [comment]
Marking closed.  This was fixed back in 20004 release.
