### ISSUE TITLE
The "OPTIONS" method under jax-rs returns too many types of methods per endpoint as allowed.

### ISSUE THREAD

**Issue by srnjak** [OpenLiberty/open-liberty#9579]
I created a resource class with GET and PUT implementations for the same path (let's say `/my/resources/{id}`). I created another method in the same class, but path higher (`/my/resources`), which was annotated with the POST.

After sending a request using OPTIONS method on url `/my/resources/{id}`, I received this response:

```
curl -v -X OPTIONS "http://myhost/my/resources/15"

> OPTIONS /my/resources/15 HTTP/1.1
> Host: myhost
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< X-Powered-By: Servlet/4.0
< Allow: POST,GET,PUT,OPTIONS,HEAD
< Date: Thu, 31 Oct 2019 14:17:01 GMT
< Content-Length: 0
< Content-Language: en-US
<
```
Response said, that allowed method is POST as well, which I believe shouldn't be on the list.

(I used OpenLiberty 19.0.0.10)

**Comment by andymc12** [comment]
Hi @srnjak , thanks for reporting this issue.  Can you post your resource class(es) (with source) so that we could reproduce the behavior?

**Comment by srnjak** [comment]
Here is my code:
```
import javax.ws.rs.*;
import javax.ws.rs.core.Response;

@Path("/my/resources")
public class MyResource {

    @POST
    public Response create() {
        return Response.ok().build();
    }

    @GET
    @Path("/{id}")
    public Response get(
            @PathParam("id") String id) {

        return Response.ok(id).build();
    }

    @PUT
    @Path("/{sourceId}")
    public Response update(
            @PathParam("sourceId") String id) {

        return Response.ok().build();
    }
}
```

I created yet another resource class, and put `DELETE` method in it. Now I get listed even this one in response.  Even if that one was in totally different path.
Here is the example:

```
import javax.ws.rs.*;
import javax.ws.rs.core.Response;

@Path("/another/resources")
public class AnotherResource {

    @DELETE
    @Path("/{sourceId}")
    public Response update(
            @PathParam("sourceId") String id) {

        return Response.ok().build();
    }
}
```

**Comment by andymc12** [comment]
Thanks for the sample - I've created a test case based on your changes that reproduce the problem.  I'll look into what is going wrong tomorrow.

**Comment by jkoehler22** [comment]
PR https://github.com/OpenLiberty/open-liberty/pull/12104

**Comment by WhiteCat22** [comment]
PR went into 20.0.0.8
