### ISSUE TITLE
Fix JWKS behavior that returns cached JWK despite the JWK not having right KID

### ISSUE THREAD

**Issue by ayoho** [OpenLiberty/open-liberty#9588]
The `JWKSet.getJWKByKidInCollection()` method has a behavior that's probably not what we want. Taking a look [here](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JWKSet.java#L92), you'll see the method is implemented to:
1. Return the only cached JWK entry if a `kid` wasn't provided and there's only one JWK in the cache
1. Return the JWK in the cache whose `kid` matches the `kid` provided to the method
1. If the above don't apply, return the only cached JWK entry if there's only one JWK in the cache

That last point - returning the only cached JWK even if the `kid` doesn't match - probably isn't the implementation we want. The method should probably be changed to return `null` in this case, where a `kid` is provided to the method but there are no JWKs in the cache with a matching `kid`. That should be done even if there's only one JWK that's cached. That will force the runtime to do a remote call to attempt to fetch the correct JWK.

**Comment by chunlongliang-ibm** [comment]
If the incoming JWT uses the kid header field and there is a key in the supplied JWK set with the same kid, only that key is considered for verification of the JWT’s digital signature.

Other key reference or identifier (e.g., x5t) works the same way.

If no key identifier in JWT, and JWK only contains one key, the key will be used for signature validation

**Comment by ayoho** [comment]
My straightforward fix that I had attempted actually ended up breaking a number of tests associated with the MP-JWT feature, including several in the TCK bucket. I investigated one of those failures and found that there are nuances that need to worked out with JWKs in PEM format.

The TCK tests use a file-based PEM key as their JWK source. At runtime, Liberty reads the file, parses the PEM key, and caches it. The problem is that the PEM file is a raw key and doesn't have any kind of KID associated with it. That results in the key being parsed and cached as a JWK correctly, but without the JWK being given a KID. Thus, when the runtime receives an inbound JWT that includes a `"kid"` in the header, we can't find the corresponding key because there is no JWK in the cache that has a matching KID.

**Comment by pellmont** [comment]
the problem still persists in openliberty 20.0.0.6.

here
https://github.com/OpenLiberty/open-liberty/blob/78e3f3d968519291976f944c07fb017a43ea1d15/dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JwKRetriever.java#L188 

probably null should be returned

**Comment by pellmont** [comment]
could you please re-open this issue?

**Comment by teddyjtorres** [comment]
Hi @pellmont. The issue https://github.com/OpenLiberty/open-liberty/issues/12778 will be used to address the problem.
Thank you for bringing this issue up!
