### ISSUE TITLE
Feature Test Summary for 4Q MP-JWT updates

### ISSUE THREAD

**Issue by arunavemulapalli** [OpenLiberty/open-liberty#960]
# 1) Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.

The description should include the positive and negative testing done, whether all testing is automated, what manual tests exist (if any) and where the tests are stored (source control). If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Squad)?

All the testing is automated and include both positive and negative tests.
### /com.ibm.ws.security.jwt_fat.mpjwt/fat/src/com/ibm/ws/security/jwt/fat/mpjwt/CommonTests/MPJwtPropagationTests.java

Testing is done using multiple servers - mp-jwt builder, jax-rs client server and the jax-rs service server to make sure that the token is propagated to the target service.

The typical test scenario :
The test case first invokes jwt builder apis (or reach OP endpoint) to access mp-jwt token. The request with token is sent to the jax-rs client application (which is protected by mp-jwt feature). Jax-rs client application will add the mp-jwt token to the request header, so it can 
be propagated to the target jax-rs service.

The token propagation happens,
 if the jax-rs client configuration property com.ibm.ws.jaxrs.client.mpjwt.sendToken is true
or
 if the server has WebTarget configuration and authnToken attribute is set to "mpjwt"

Multiple tests are added to run webTarget configuration attribute "authnToken" set to "mpjwt", or not set at all and client config
com.ibm.ws.jaxrs.client.mpjwt.sendToken is not set, or set to true, false, "true" or "false"

### com.ibm.ws.security.jwt_fat.mpjwt/fat/src/com/ibm/ws/security/jwt/fat/mpjwt/CommonTests/MPJwtLoginConfig_VariationTests.java

The test scenario :

Set "ignoreApplicationAuthMethod" to "false". Specify login-config (set to MP-JWT) in either web.xml or in the application itself to make sure that mp-jwt TAI intercepts the request and handles the authentication.

Multiple tests are added to specify (or not specify) login-config with various values (including MP-JWT) either in the web.xml or in the application itself. The extending test classes will either have no mpJwt config, or have an mpJwt config with "ignoreApplicationAuthMethod" set to either true or false. These tests will ensure that we get the proper behavior based on the config and the login-config setting.

### /com.ibm.ws.security.jwt_fat.mpjwt/fat/src/com/ibm/ws/security/jwt/fat/mpjwt/CommonTests/MPJwtConfigTests.java

The new tests cover the scenarios where mapToUserRegistry attribute is true and 
1. The principal user exists in the registry
2. user does not exist in the registry
Another test is added to test the "mapToUserRegistry" is false and to make sure that the user mapping is not done in this case.

# 2) Collectively as a squad you need to assess your confidence in the testing delivered based on the values below.

This should be done as a squad and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the squad as a whole.

Please indicate your confidence in the testing (up to and including FAT) delivered with this feature by selecting one of these values:

0 - No automated testing delivered
1 - We have minimal automated coverage of the feature including golden paths. There is a relatively high risk that defects or issues could be found in this feature.
2 - We have delivered a reasonable automated coverage of the golden paths of this feature but are aware of gaps and extra testing that could be done here. Error/outlying scenarios are not really covered. There are likely risks that issues may exist in the golden paths
3 - We have delivered all automated testing we believe is needed for the golden paths of this feature and minimal coverage of the error/outlying scenarios. There is a risk when the feature is used outside the golden paths however we are confident on the golden path. Note: This may still be a valid end state for a feature... things like Beta features may well suffice at this level.
4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios. While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.
5 - We have delivered all automated testing we believe is needed for this feature. The testing covers all golden path cases as well as all the error/outlying scenarios that make sense. We are not aware of any gaps in the testing at this time. No manual testing is required to verify this feature.

Based on your answer above, for any answer other than a 4 or 5 please provide details of what drove your answer. Please be aware, it may be perfectly reasonable in some scenarios to deliver with any value above. We may accept no automated testing is needed for some features, we may be happy with low levels of testing on samples for instance so please don't feel the need to drive to a 5. We need your honest assessment as a squad and the reasoning for why you believe shipping at that level is valid. What are the gaps, what is the risk etc. Please also provide links to the follow on work that is needed to close the gaps (should you deem it needed)

**Comment by sabolo** [comment]
I have reviewed this and the content above is good.  I cannot yet close this out as there are multiple failures of the tests occurring in the cross platform testing.  Please refer to the feature for links to these cross platform defects.

**Comment by sabolo** [comment]
Defects are now resolved so approving this feature.
