### ISSUE TITLE
Disable SSL certificate creation 

### ISSUE THREAD

**Issue by cblomart** [OpenLiberty/open-liberty#9618]
Hello,

Is there a way to prevent default SSL Certificate creation? (takes some seconds more to boot with docker and is not used by devs)

Cédric

**Comment by acdemyers** [comment]
The default keystore/certificate gets created because there is a password generated during the server create and added to the server.env file.    If the "--no-password" flag is added on the server create then the default keystore and certificate will not be created.

**Comment by acdemyers** [comment]
To prevent a password from being added to the server.env file the server must be created with the "--no-password" flag, eg.  server create testServer --no-password
