### ISSUE TITLE
BETA BLOG 191100 : APSFOUND-1 Liberty Annotation Caching

### ISSUE THREAD

**Issue by tbitonti** [OpenLiberty/open-liberty#9647]
Parent:
APSFOUND-1 Liberty Annotation Caching
https://github.com/OpenLiberty/open-liberty/issues/6329

a. Which Liberty feature does it relate to?

   i. Human-readable name: Annotation Caching (APSFOUND-1 Liberty Annotation Caching)
   ii. Feature name: com.ibm.ws.anno
   iii. New feature or update: Update
   iv. Public features delivered:
       com.ibm.websphere.appserver.anno-1.0.esa
       com.ibm.websphere.appserver.containerServices-1.0.esa

b. Who is the target audience?
       Application Developers
       AppServer Administrators
       Pipeline Developers

c. Write a sentence or two that introduces it to someone new to the general technology/concept.

       During application startup, application classes are scanned for class signature information and for annotations.
       Typically, all application classes are scanned, which is time consuming.

d. What has been updated?  What is exciting about the updates?

       This update adds caching function to application class scanning.  A first start of an application must still
       perform a scan.  Second and subsequent starts read data from an on-disk cache, bypassing the scan step,
       making application startups faster.  (See the attached table for performance results.)

e. Explain how to make it work.

       The following enablement and java custom properties are for only the BETA edition of the caching function.
       When available as GA function, the caching function will default to be enabled.

       As BETA function: Annotation caching is enabled when the product edition is "EARLY_ACCESS".

       As BETA function: For other product editions, annotation caching is disabled, but may be forced on by setting
       java custom property "anno.beta" to "true".

       As BETA function: When the product edition is "EARLY_ACCESS", the caching function may be forced off by setting
       java custom property "anno.beta" to "false".

       As BETA function: The new scan engine may be enabled with cache function turned off by setting java custom
       property "anno.cache.disabled" to "true".

       As BETA function: The new scan engine may be prevented from writing new data by setting java custom property
       "anno.cache.readOnly" to "true".  Already generated cache data will still be read.  This may be necessary in
       certain deployment pipelines.

       When enabled, application class scan steps automatically write (cache) scan data, and automatically read cached
       scan data.  Cache data is automatically regenerated when changes are detected in application classes.  No
       additional settings are necessary to use the new function.  (Pipeline developers, however, see "Important Note",
       below.)

       Cache data is visible as a new, nested directory of server workarea named "anno".  (Cache data uses a binary
       format and is not human readable.)  Cache data is relocatable: Movement of a server image to a new location
       does not require that the application class scan cache data be regenerated.

       The cache of application class data is cleared when performing a clean server start (starting the server with
       the "--clean" option).  In normal operations, the clearing of cache data is not necessary, since the cache 
       automatically detects class changes and regenerates invalid cache data.  However, the cache function has no
       way to tell when cache data is obsolete.  If the same server is used with many different applications, a clean
       start should be performed occasionally to remove stale cache data.

       Important Note: In a pipeline deployment environment, for example, Docker, for caching to be effective, the server image must be
       "warmed" before packaging the deployment image, and application class cache data must be included in the
       deployment image.  "Warming" the server means performing a single start of the server.  This will cause
       cache data to be generated and available when packaging the server image.  A failure to generate the cache
       data or to include the cache data in the deployment image will result in longer startup times, since a typical startup
      uses a fresh copy of the deployment image, which will not have any cached data.

f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

       N/A

g. Attach any images to this work item as .png files.

      This chart shows server startup times with annotation caching enabled, relative to server startup times for the
      same application and with annotation caching disabled.  Startup times with annotation caching enabled
      have cache data already generated.

      Generally, performance improvements are larger for larger applications, and for applications which use CDI or
      WebService functionality.

      "BetaResults-06-Nov-2019.png"

**Comment by tbitonti** [comment]
![BetaResults-05-Nov-2019](https://user-images.githubusercontent.com/31104478/68228726-f2e04380-ffc3-11e9-801e-c42b28890e28.png)

**Comment by tbitonti** [comment]
![BetaResults-06-Nov-2019](https://user-images.githubusercontent.com/31104478/68343228-49c84480-00ba-11ea-9847-6ecffeaa1bc5.png)

**Comment by jakub-pomykala** [comment]
Closing. Issue live [here](https://openliberty.io/blog/2019/11/08/diagnose-slow-requests-easily-190011.html)
