### ISSUE TITLE
properties map will lose values when there is invalid value specified in server.xml

### ISSUE THREAD

**Issue by zhenzhenclaire** [OpenLiberty/open-liberty#9658]
**Describe the bug**
Hi there, I'm working for IBM z/OS Connect Team. We found that when we specify an invalid value to elements in server.xml, the generated properties map will lose all configured parameters(key and value) in server.xml. Thus, code cannot parse this map.

**Steps to Reproduce**
1) Specify an invalid value in element in server.xml, like this:
<zosconnect_apiRequesters updateTrigger="polled" requireAuth="**invalidvalue**">
2) Start Liberty server. During the activate method to parse the property map, it will issue NPE.
The activate method has thrown an exception java.lang.NullPointerException
3) When you print the map content, you will see there is no "updateTrigger" or "requireAuth" in the map.

**Expected behavior**
When invalid value is specified, only the parameter contains invalid value should be ignored, just like not specified. The other ones should be put into the map.

**Diagnostic information:**
 - OpenLiberty Version: WAS FOR Z/OS 19.0.0.9, z/OS Connect 03.00.26 (wlp-1.0.32.cl190920190905-0148)
 - java.version = 1.8.0_221
 - server.xml configuration (WITHOUT sensitive information like passwords)

	
<zosconnect_apiRequesters updateTrigger="polled" pollingRate="1245" requireAuth="**invalidvalue**">
        <apiRequester name="Language-Translator_2.0.0" connectionRef="conn"/>
        <apiRequester name="Book-Inventory-API_1.0.0" connectionRef="conn"/>
</zosconnect_apiRequesters>

**Comment by brenthdaniel** [comment]
The properties map is always a reflection of what is configuration admin. Can you provide the metatype definition for zosconnect_apiRequesters and the component definition that uses the configuration? 

My guess would be that you have defined the component with configurationPolicy OPTIONAL. I would also guess that the requiredAuth attribute is defined as required, so that the configuration is not created when it is invalid. So, when the component activates there is no corresponding configuration and your component code is assuming that there is.

**Comment by zhenzhenclaire** [comment]
Hi brenthdaniel, thanks for your reply.

Here is the metatype definition of zosconnect_apiRequesters, this attribute is defined as optional.
```
 <OCD id="com.ibm.zosconnect.apirequesters.metatype" ibm:alias="apiRequesters" name="%apiRequesters.name" description="%apiRequesters.desc">
        <AD id="requireAuth" required="false" type="Boolean" name="%requireAuth.apirs.name" description="%requireAuth.apirs.desc"/>
  </OCD>
```
And here is the component definition, is there any place to define configurationPolicy as OPTIONAL?
```
@Component(configurationPid = "com.ibm.zosconnect.apirequesters", immediate = true,
                service = { ApiRequesterManager.class }, property = { "service.provider = IBM" })
public class ApiRequesterManagerImpl implements ApiRequesterManager, ArchiveManagerListener {...}
```

**Comment by brenthdaniel** [comment]
Hi, 
OPTIONAL is the default, but in this case you want REQUIRED so that your component does not activate with an empty map of properties. Adding `configurationPolicy = ConfigurationPolicy.REQUIRE` to the component definition should resolve your problem.

**Comment by SueBayliss** [comment]
@brenthdaniel Hi Brent,
I have picked up this issue from zhenzhenclaire who raised it (but has left our team).
In our case we need to use `configurationPolicy = ConfigurationPolicy.OPTIONAL` and `immediate = true` to allow the component to be satisfied even if the corresponding Configuration object is not present.

Is there anything we can rely on in the properties map (e.g. service.pid ) to distinguish between:

- the **requireAuth attribute not having been configured** (it is missing from properties map, but other attributes, service.provider, component.name, component.id service.pid are present)

- and **requireAuth attribute having been configured with an invalid value** (it is missing from properties map, and the only properties seem to be service.provider, component.name and component.id}

**Comment by brenthdaniel** [comment]
Hi, 

In general we strongly recommend against using ConfigurationPolicy.OPTIONAL, especially for components with a factory PID. If the component needs to activate without configuration, the best option would be to use ConfigurationPolicy.REQUIRE and use a default instance of the configuration. 

There isn't a way to distinguish between the two scenarios you mention. I'm assuming `requireAuth` is a boolean, so you wouldn't be able to do something like using a known default value that would alert your component that nothing was configured.

**Comment by SueBayliss** [comment]
@brenthdaniel Hi Brent,
Thanks for the information, 
i.e. that to achieve this, `configurationPolicy = ConfigurationPolicy.REQUIRED` should be specified.
We're happy to close this issue, can you do that for us please.
