### ISSUE TITLE
Non english characters in logoutRedirectUrl of oauthProvider results in incorrect redirection

### ISSUE THREAD

**Issue by ugatkal** [OpenLiberty/open-liberty#9692]
I am using
Product name: WebSphere Application Server
Product version: 19.0.0.9
Product edition: BASE

My application and OpenId Provider both uses above liberty but are on different servers.

I want OpenIdProvider to redirect to certain url on application logout hence I am using following configuration
oauthProvider id="OauthSample" jwtAccessToken="true" httpsRequired="false" allowPublicClients="true" customLoginURL="/login" logoutRedirectURL="https:www.google.com"

The above settings works fine as longs as redirection url has English characters only

If the logout url contains non english characters then redirection does not occur correctly. For example, if I set following line in OpenIdProvider's server.xml
oauthProvider id="OauthSample" jwtAccessToken="true" httpsRequired="false" allowPublicClients="true" customLoginURL="/login" logoutRedirectURL="https://shopee.tw/search?keyword=asus巧克力鍵盤"
then I am redirected to
https://shopee.tw/search?keyword=asus%E7K%9Bu%E4
which is incorrect url and page doesn't get displayed.

I even tried with encoded url, in this case things get worst
oauthProvider id="OauthSample" jwtAccessToken="true" httpsRequired="false" allowPublicClients="true" customLoginURL="/login" logoutRedirectURL="https%3A%2F%2Fshopee.tw%2Fsearch%3Fkeyword%3Dasus%E5%B7%A7%E5%85%8B%E5%8A%9B%E9%8D%B5%E7%9B%A4"
in this case I am redirected to
https://va8227.in.ibm.com:11443/oidc/endpoint/openidProviderSC/https%3A%2F%2Fshopee.tw%2Fsearch%3Fkeyword%3Dasus%E5%B7%A7%E5%85%8B%E5%8A%9B%E9%8D%B5%E7%9B%A4
which is completely wrong

**Comment by ugatkal** [comment]
What is the ETA to fix this issue?
Is there any workaround available?

**Comment by brutif** [comment]
Fix has been submitted on #9706, should be in the nightly builds in a day or few.

**Comment by brutif** [comment]
To work around, I think you can url encode the query params, for example 
logoutRedirectURL="https://www.google.com?item=%E5%B7%A7 
renders in browser as  
![screenshot 55](https://user-images.githubusercontent.com/26486297/68484461-eb5aad80-0202-11ea-83c4-bde2cc1f34b3.png)

**Comment by brutif** [comment]
#9706 has merged, so closing this issue.
