### ISSUE TITLE
Discuss how to expose a new API to closely work with Kafka

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#9737]
In order to support #9276, Open Liberty needs to expose an API like [KafkaMessage](https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/KafkaMessage.java) 
There are two options:

Option 1: Consume smallrye-kafka completely
We can expose the APIs under smallRye instead of duplicating the APIs in Open Liberty. However, the smallrye-kafka connector uses Vert.x. 
+ use the common codebase with smallRye
-  The quick investigation on Vert.x shows that putting Vert.x in OL is not trivial and it will take some time.

Option 2: Consume smallRye-kafka connector APIs not implementation
- use slightly different implementation
+ The API implementation is simple and can be done without the need of Vert.x. Hope to contribute back to smallRye-kafka if the implementation is much improved.

Option 3: Create a new API similar to SmallRye's KafkaMessage
- different codebase 
- The API is different and very likely drift away from SmallRye's KafkaMessage

**Comment by tevans78** [comment]
@Emily-Jiang I don't think this design issue is relevant any more since we made Producer and ConsumerRecord useable?

**Comment by tevans78** [comment]
Resolved by https://github.com/OpenLiberty/open-liberty/issues/9570
Closing.
