### ISSUE TITLE
Best practices on testing microservices - unit and integration

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#9753]
Testing microservices sometimes can be challenging. I was asked multiple times on how best unit test and integrate testing microservices. I think with this lab, we can demonstrate test containers and some well-known test technologies such as acquillian and mock framework.

**Comment by yeekangc** [comment]
Issue moved to [OpenLiberty/guides-common #371](https://github.com/OpenLiberty/guides-common/issues/371) via [**ZenHub**](https://www.zenhub.com/)
