### ISSUE TITLE
Best Practices on creating docker images for Open Liberty

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/open-liberty#9754]
We need a guide to demonstrate how to create a small docker image and demonstrate the best practices mentioned by Arthur and Leo such as:
1. layers
2. Users and Labels
3. Container immutability
4. Multi-stage
5. Start from the kernel image and run config.sh, etc.

**Comment by yeekangc** [comment]
Issue moved to [OpenLiberty/guides-common #370](https://github.com/OpenLiberty/guides-common/issues/370) via [**ZenHub**](https://www.zenhub.com/)
