### ISSUE TITLE
Configuring Open Liberty using YAML

### ISSUE THREAD

**Issue by jamiecoleman92** [OpenLiberty/open-liberty#9839]
**Is your feature request related to a problem? Please describe.**
I have been running workshops all over Europe this year and one very common piece of feedback I receive is that the younger developers really do not like configuring things in xml format. I have been asked the same question repeatedly which is “why do you not use yaml format to configure your server?”. It is not like developers actually like using yaml but it is something they all know very well with the rise of Kubernetes etc.

**Describe the solution you'd like**
What I am proposing is that we continue to use the xml format but also have the option to use yaml to be able to configure Open Liberty. From what I have been told yaml should be able to do everything xml does regarding configuration. I do not know how difficult this would be to implement but it would make developers much happier about using and configuring our server from what I have experienced from attending all these conferences.

**Describe alternatives you've considered**
I have been doing some research into other xml type config we could use as an alternative and it looks like yaml is here to stay. There was a number of other projects started a few years back such as TOML but most of these have had very little adoption and with Kubernetes backing yaml I think we will not have to worry about it being replaced any time soon.

**Additional context**
Need to consider the effect on other tools like schemagen

**Comment by hlhoots** [comment]
UFO link: https://ibm.box.com/s/bpedn7p6wh6x4ublkbpii5dpdvyr4ida

**Comment by yeekangc** [comment]
A few quick thoughts:

- Don't think we will need a guide for this.  We can mention YAML config as an option in existing guide(s) for getting started with Liberty.

- We will need to discuss and work through Developer Experience impact from the build plugins to tooling.  e.g. Language server for Liberty server config will need to be able to handle YAML as an alternate format.

@cherylking @ericglau @gkwan-ibm @rzgry @kathrynkodama

**Comment by frowe** [comment]
A couple of questions I'd like to see answered in the UFO.
1) How do we leverage all the functionality of the existing metatype system for things like required attributes, choices, ibm:*, etc?  Would we parse the yaml into xml and feed it into the existing config system, avoiding having to duplicate all the error checking and detection?
2) It seems that there could be startup time impact depending on how we decide to do this, how do we address that?

**Comment by malincoln** [comment]
Alasdair and Graham reviewed today and determined not likely to complete this feature.  Agreed to close.
