### ISSUE TITLE
acmeCA-2.0: Feature Test Summary

### ISSUE THREAD

**Issue by kristip17** [OpenLiberty/open-liberty#9850]
This is the Feature Test Summary for #9017 

### Test strategy and approach
This is a new feature and required new unit and FAT tests, as well as new FAT infrastructure to test. In addition to the unit/FAT tests, we developed a test certificate authority (CA) that runs as a docker test container (can run on local or remote docker). We used `Pebble` (https://github.com/letsencrypt/pebble) and `Boulder` (https://github.com/letsencrypt/boulder) for our test certificate authority. 

**Unit tests:**
`com.ibm.ws.security.acme.internal.AcmeClientTest` (unit test)
- Empty or null URI

`com.ibm.ws.security.acme.internal.AcmeConfigTest` (unit test)
- Empty or null domain key file, account key file
- Unreadable or unwriteable domain or account key file
- Missing domain or directory URI
- General invalid values for config
- Variations on `refreshBeforeExpiration` config
- Variations on certificate checker configuration

**New automated test project:** `com.ibm.ws.security.acme_fat`

`com.ibm.ws.security.acme.fat.AcmeSimpleTest` and `com.ibm.ws.security.acme.fat.AcmeURISimpleTest`
- Successfully connect to test CA (Pebble), retrieve certificate.
- Restart with existing, valid certification
- Fetch new certificate on config updates
- Empty keystore
- Correct a bad config, fetch certificate
- Enable/disable/enable the acmeCA feature (verify background scheduler starts/stops)
- Change domains

`com.ibm.ws.security.acme.fat.AcmeDisableTriggerSimpleTest` -- subset of AcmeSimple test with the keystore file trigger disabled
- Successfully connect to test CA (Pebble), retrieve certificate.
- Correct a bad config, fetch certificate
- Enable/disable/enable the acmeCA feature (verify background scheduler starts/stops)
- Change domains

`com.ibm.ws.security.acme.fat.AcmeClientTest`
- Single domain cert
- Multi domain cert
- Revoke certificate

`com.ibm.ws.security.acme.fat.AcmeCaRestHandlerTest`
- Exercise ACME REST API to renew certificate
- REST API requested by user with incorrect roles (reader vs admin)
- Check that rapid requests are correctly blocked (Rate limit exceeded)

`com.ibm.ws.security.acme.fat.AcmeValidityAndRenewTest`
- Certificate hits expires refresh time on restart
- Correct and adjust timing settings for renewBeforeExpiration property
- Certificate is automatically renewed from the cert checker task
- Certificate is not automatically renewed if the cert checker is disabled
- Cert checker does not renew a certificate that is still valid (task runs, no renew)
- Cert checker hits an error, recovers, renews a certificate as expected
- Enable and disable cert checker with different configuration options and check that it runs/doesn't run as appropriate.

`com.ibm.ws.security.acme.fat.AcmeRevocationTest`
- Exercise ACME REST API to revoke certificate, using valid, default and invalid revoke reasons
- Revoked certificate is renewed on server start
- Cert checker renews a revoked certificate automatically
- If revocation is disabled, we do not renew the certificate

`com.ibm.ws.security.acme.fat.AcmeSwapDirectoriesTest`
- ACME historical file is created upon server start
- Detect dynamic directory URI change and renew the certificate
- If the ACME directory is not readable or writable, renew the certificate
- Enforce maximum file size and ensure the oldest entry is replaced when rolling over

**Additional manual testing:**
The only way to test against a "real" (public/external) CA is to do manual testing. We created cloud accounts with a public domain in order to run against the Lets Encrypt staging and production server.
Date of last manual testing: 6/11/20
Manual tests done: 
- Ran with the production Lets Encrypt server and the staging (test) Let's Encypt server.
- Did renews, revokes with the staging server.
- Swapped back and forth between the production and staging server.

Team test confidence statement: We created several golden path and error scenario tests. We wrote tests to enable and disable the feature as well as options on the feature to ensure the correct behaviors take place. We adjusted timing attributes to run within a fat test so they can be exercised (for example, renew a certificate on startup or during automatic checks). We built up our test buckets over the last several weeks and resolved build break issues to stabilize our new tests.

Team Test Confidence Level :  4

**Comment by ayoho** [comment]
Coverage looks good to me. Remainder of the test issues seem to be infrastructure, so I'm approving this.
