### ISSUE TITLE
Enforce access_token processing priority in social login

### ISSUE THREAD

**Issue by chunlongliang-ibm** [OpenLiberty/open-liberty#9851]
In sociallogin-1.0 feature, if server is configured with accessTokenRequired or accessTokenSupported, and if request contains LTPA token, server must not process LTPA token first. To honor this processing order, we need restructure socialLogin TAI to be invoked to process access_token before LTPA, and also to be able to start social login if necessary after LTPA. The order of TAI is controlled by annotation of  "invokeAfterSSO".

**Comment by brutif** [comment]
@arunavemulapalli  can this be closed?  I think you reworked the tai for this.
