### ISSUE TITLE
acmeCA-2.0: Add configuration options for acmeCA feature

### ISSUE THREAD

**Issue by kristip17** [OpenLiberty/open-liberty#9855]
Add configuration options for the acmeCA feature per plans from the design review (see slide 19 of the design review).

Proposed  feature configuration (defaults –no config required-singleton on the server):
```
<acmeCA
host=“letsencrypt.org”
port=“443”
challengeType=”HTTP-01”  << maybe this does not exist till TLS-ALPN-01?
alsoRevoke=“false” />
```
Currently, we just have some dummy config parameters that can be removed:

```
public static final String PARM1 = "configParm1";
public static final String PARM2 = "configParm2";
```
For #9017

**Comment by kristip17** [comment]
We can probably pull #9865 into this one -- right now we are thinking that we'll have a config option that the user has to set to accept terms of service.

**Comment by jvanhill** [comment]
This work was completed incrementally under other issues. Closing.
