### ISSUE TITLE
acmeCA-2.0: Remove acceptTermsOfService  from the metatype

### ISSUE THREAD

**Issue by kristip17** [OpenLiberty/open-liberty#9865]
This was a discussion point brought up while reviewing the sample -- If the CA provider asks to accept terms of service, how do we do this programmatically as well as logistically on behalf of the user. We may need to add an option in the metatype that the user has to set to true/agree.

We can also check if anyone else has already dealt with a similar problem.

Depends on #10799

For #9017

**Comment by kristip17** [comment]
Hammered this out through legal. We can remove `acceptTermsOfService` from the metatype.xml.

**Comment by kristip17** [comment]
Changed this to a removal task -- after #11008  merges, we can remove the acceptTermsOfService  support.

**Comment by ryanesch** [comment]
PR #11291

**Comment by jvanhill** [comment]
This was completed under issue #11619
