### ISSUE TITLE
SVC: Can the message hint about "access_id" usage when user registry is not configured for security role mapping?

### ISSUE THREAD

**Issue by meiaus** [OpenLiberty/open-liberty#9883]
Problem scenario:
When the server.xml is not configured with user registration information for security role mapping or 'access_id', attempting to access the application for social login feature with Oauth in Open Shift, the following error appeared in messages.log.

```
11/15/19, 22:54:12:666 GMT] 0000005d .ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl A CWWKS9104A: Authorization failed for user acme-user1 while invoking AcmeSAMLWebEar on /. The user is not granted access to any of the required roles: [admins, users].

```
and browser:

![image](https://user-images.githubusercontent.com/27024803/69259381-c7dd1e80-0b83-11ea-85e5-3dd3fcd69035.png)

server.xml:
```
<security-role id="admins" name="admins">
              <user name="acme-user1" />
              <user name="acme-user2" />
              <user name="acme-user3" />
              <group name="acme-group" />
         </security-role>
         <security-role name="users">
              <user name="acme-user1" />
              <user name="acme-user2" />
              <user name="acme-user3" />
              <group name="acme-group" />
 </security-role>

```

Question/Consideration:
The error is common when user and group mapping information is not found from a user registry.  But since this scenario involves with containerized application deployed in Open Shift where pre-configured user registry may not be quickly managed, will there be possibility to provide a hint in the message for using 'access_id' in the form of URL with realm/user or realm/group as follows.

Or, this can only be handled through the documentation?

```
<security-role id="admins" name="admins">
              <user name="acme-user1" access-id="user:https://kubernetes.default.svc/acme-user1"/>
              <user name="acme-user2" access-id="user:https://kubernetes.default.svc/acme-user2"/>
              <user name="acme-user3" access-id="user:https://kubernetes.default.svc/acme-user3"/>
              <group name="acme-group" access-id="group:https://kubernetes.default.svc/acme-group"/>
         </security-role>
         <security-role name="users">
              <user name="acme-user1" access-id="user:https://kubernetes.default.svc/acme-user1"/>
              <user name="acme-user2" access-id="user:https://kubernetes.default.svc/acme-user2"/>
              <user name="acme-user3" access-id="user:https://kubernetes.default.svc/acme-user3"/>
              <group name="acme-group" access-id="group:https://kubernetes.default.svc/acme-group"/>
      </security-role>

```

**Comment by meiaus** [comment]
Side question:
When leaving the `realmName` attribute in the server.xml as follows, even though the security role binding information has correct `access_id` configuration, the same authorization error appeared.
We know the `realmName` attribute is not required for OAuth Proxy scenario, but wondering if the error is expected here? will there be a different message instead to helpful pinpoint the misuse of `realmName`?

```
<oauth2Login
realmName="https://oauth-openshift.apps.kneeing.os.fyre.ibm.com"
...
</oauth2Login>

. . .
 <application-bnd>
         <security-role id="admins" name="admins">
              <user name="acme-user1" access-id="user:https://kubernetes.default.svc/acme-user1"/>
              <user name="acme-user2" access-id="user:https://kubernetes.default.svc/acme-user2"/>
              <user name="acme-user3" access-id="user:https://kubernetes.default.svc/acme-user3"/>
              <group name="acme-group" access-id="group:https://kubernetes.default.svc/acme-group"/>
         </security-role>
         <security-role name="users">
              <user name="acme-user1" access-id="user:https://kubernetes.default.svc/acme-user1"/>
              <user name="acme-user2" access-id="user:https://kubernetes.default.svc/acme-user2"/>
              <user name="acme-user3" access-id="user:https://kubernetes.default.svc/acme-user3"/>
              <group name="acme-group" access-id="group:https://kubernetes.default.svc/acme-group"/>
      </security-role>
      </application-bnd>

```

**Comment by meiaus** [comment]
@brutif as discussed in the scrum, assign to you

**Comment by brutif** [comment]
As the user-to-role mapping stuff is base security code and not part of social login, there's not much we can do in the scope of this feature to make it more usable. Bruce is going to make sure the release blog contains well-commented example server.xml's for both the proxy and sidecar flows.

**Comment by meiaus** [comment]
thanks @brutif 

Closing and will check the blog when it's ready.
