### ISSUE TITLE
Open Liberty beta design questions

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/open-liberty#9892]
This will feed into feature #9888 

We should make Open Liberty beta content available and easily consumable on the same 4-weekly schedule as our regular GA releases. It would be based off the same build.

There are three ways in which someone might wish to obtain an Open Liberty beta and/or Open Liberty beta features;
 
1) A simple zip download via https://openliberty.io/downloads/. This image could be either
     - OL beta runtime + beta features
     - OL beta runtime + GA features + beta features
 
2) Maven or Gradle dependency, downloaded from Maven Central
2a) A standard runtime dependency, an image just like the download in 1)

The current maven plugin is configured like this; 
```
<assemblyArtifact>
  <groupId>io.openliberty</groupId>
  <artifactId>openliberty-kernel</artifactId>
  <version>[19.0.0.9,)</version>
  <type>zip</type>
</assemblyArtifact>
``` 

This could be changed to pull in a beta instead; 
```
<assemblyArtifact>
  <groupId>io.openliberty</groupId>
  <artifactId>openliberty-beta</artifactId>
  <version>2020.1.0.0</version>
  <type>zip</type>
</assemblyArtifact>
``` 
Notice that we shouldn't use "RELEASE" (or other keyword version) to get the latest beta version. You have to very intentionally change the artifactId and specify the exact beta version you want.
 
2b) Dependency on individual features. The beta dependencies in maven might look like this;
```
    <dependencyManagement>
       <dependencies>
           <dependency>
               <groupId>io.openliberty.beta-features</groupId>
               <artifactId>beta-features-bom</artifactId>
               <version>2020.1.0.0</version>
               <type>pom</type>
               <scope>import</scope>
           </dependency>
       </dependencies>
   </dependencyManagement>

   <dependencies>
       <dependency>
           <groupId>io.openliberty.beta-features</groupId>
           <artifactId>microProfile-4.0</artifactId>
           <type>esa</type>
           <scope>provided</scope>
       </dependency>
   </dependencies>
```
I think it is important to use a groupId here which is clearly beta. If the groupId were to remain the same as for our GA features then they would get mixed together in maven central: https://repo1.maven.org/maven2/io/openliberty/features/

3) A Docker image on Docker Hub
   - Based on the same images from 1, named something like `openliberty/beta` ... but I don't know exactly which images/tags (java versions etc)
   - We would also keep the existing `openliberty/daily` images as well as they include ALL features (currently there are 6 different tags for this - https://hub.docker.com/r/openliberty/daily/tags)

**Comment by yeekangc** [comment]
Is the idea that the "OL beta runtime + beta features" package will only have features that are marked beta only?  Will developers need more than the beta features to effectively try out the beta features?  If so, "OL beta runtime + GA features + beta features" seems like the option to go?

**Comment by gcharters** [comment]
I think "OL beta runtime + GA features + Beta features" is good.  We could subset the GA features to cover MicroProfile & Web Profile and any other features required to support the Beta features.

I'd prefer approaches 2 & 3 (in that order) initially as these the most common way to get hold of Liberty.

I like the idea of separating the maven coordinates for the features using the groupId.  I think just relying on the version will lead to confusion as people may not appreciate the subtlety of the different versioning schemes.
