### ISSUE TITLE
embedded liberty server can be started using java 7

### ISSUE THREAD

**Issue by garypicher** [OpenLiberty/open-liberty#9903]
This check is now present:

```
echo %JAVA_HOME%
c:\dev\java7\sdk

productInfo version
Product name: Open Liberty
Product version: 22.0.0.4
Product edition: Open

server start test
CWWKE0042E: The correct Java version is not running. The runtime environment requires Java 8 or higher.
```

**Describe the bug**
When starting an Open Liberty server inside an existing Java 7 JVM using the embedder SPI, the server will successfully start.  Our intention for 19.0.0.9 (now moved to 20.0.0.1) is that starting a server using Java 7 should result in a hard failure with a clear message, and we did add code to that effect, however that code only seems to work when starting a standalone server with the "server" script.

**Steps to Reproduce**

- Create a new standalone Java class that imports and uses open-liberty/dev/com.ibm.ws.kernel.boot.core/src/com/ibm/wsspi/kernel/embeddable/ServerBuilder to start a Liberty server inside an existing JVM.
- Run this class in a Java 7 JVM.
- The server will start without an error, leaving it vulnerable to odd failures if a code path that is incompatible with Java 7 is ever executed.

**Expected behavior**
The server should fail to start with a clear error that Java 7 is no longer supported.

**Diagnostic information:**
 - OpenLiberty Version: 19.0.0.9 and later
 - Java Version: Any Java 7 VM.
 - server.xml configuration (WITHOUT sensitive information like passwords): Any server.xml configuration.
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Comment by tbitonti** [comment]
Cancelling.  The check was added some time ago.
