### ISSUE TITLE
doc update for LG-255: Provide ability to omit specified fields from JSON logging output

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/open-liberty#9948]

**Comment by Yushan-Lin** [comment]
https://www.openliberty.io/docs/ref/general/#logging.html:
Change description of jsonFieldMappings to:
When logs are in JSON format, use this attribute to replace default field names with new field names. Use this attribute to omit fields as well. Configure the new field name by using the following format: `defaultFieldName:newFieldName?`. For field names that are associated with logs of a specified source, use the following format: `[source:]?defaultFieldName:newFieldName?`, where `[source]` is the source you want to specify (such as message, trace, or accessLog). Leave newFieldName blank if you want to omit the defaultFieldName. To rename/omit multiple fields, specify a comma-separated list of field name mappings.

**Comment by donbourne** [comment]
@Yushan-Lin , I don't think that was the latest version... should be...

When logs are in JSON format, use this attribute to replace default field names with new field names. Use this attribute to omit fields as well. Configure the new field name by using the following format: defaultFieldName:newFieldName?. For field names that are associated with logs of a specified source, use the following format: [source:]?defaultFieldName:newFieldName?, where [source] is the source you want to specify (such as message, trace, or accessLog). Leave newFieldNameblank if you want to omit the field. To rename/omit multiple fields, specify a comma-separated list of field name mappings.

**Comment by ellen-lau** [comment]
From conversation with @dmuelle, the suggested ID edit:

When logs are in JSON format, use this attribute to replace default field names with new field names or to omit fields from the logs. To replace a field name, configure the new field name by using the following format: defaultFieldName:newFieldName?. For field names that are associated with logs of a specified source, use the following format: [source:]?defaultFieldName:newFieldName?, where [source] is the source you want to specify, such as message, trace, or accessLog. To omit a field from the logs, specify the field name without a replacement, as shown in the following example: defaultFieldName:. To rename or omit multiple fields, specify a comma-separated list of field name mappings.

**Comment by Yushan-Lin** [comment]
ID done: https://github.ibm.com/was-liberty/liberty-docs/issues/1883
