### ISSUE TITLE
CORS config "maxAge" sends wrong response header

### ISSUE THREAD

**Issue by pugmas** [OpenLiberty/open-liberty#9951]
**Having the following cors config in server.xml**

` 
<cors domain="/" 
          allowedOrigins="*"
          allowedMethods="GET,DELETE,POST,PUT,OPTIONS"
          allowedHeaders="origin,accept,content-type,authorization,if-match"
          exposeHeaders="etag"
          allowCredentials="true"
          maxAge="600" />
`

**Liberty sends the following response headers:**

`
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://localhost:3000
Access-Control-Allow-Max-Age: 600
Access-Control-Allow-Methods: GET, DELETE, POST, PUT, OPTIONS
Access-Control-Allow-Headers: origin, accept, content-type, authorization, if-match, accept-language`

**The browser does not cache the response, because**

`Access-Control-Allow-Max-Age: 600 `

**should be** 

`Access-Control-Max-Age: 600`

([https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age))

OpenLiberty Version: (Open Liberty 19.0.0.11/wlp-1.0.34.cl191120191031-0300) on Eclipse OpenJ9 VM, version 11.0.2+9

**Comment by navidsh** [comment]
Good catch @pugmas! Thanks
