### ISSUE TITLE
configured features microProfile-3.0 and usr:opent racinqZipkin-0.31 include one or more features that cause the conflict

### ISSUE THREAD

**Issue by thomassuedbroecker** [OpenLiberty/open-liberty#9954]
**1. Describe the bug**

This Bug is related to the update from MicroProfile 2.1 to MicroProfile 3 with OpenLiberty 19.0.0.9 and OpenTracing 1.3.

First I got following message.

**MicroProfile 3** and **usr:opentracinqZipkin-0.31**  features can't be loaded at the same time. 

Console output:

```
.. loaded at the same time. The configured features microProfile-3.0 and usr:opent
racinqZipkin-0.31 include one or more features that cause the conflict,
```
when  **usr:opentracinqZipkin-0.31** feature is removed the following Error message appears:

```
ERROR ] CWMOT0008E: OpenTracing cannot track JAX-RS requests because an Opentracing
TracerFactory class was not provided.
```
Here is an image with screen shots:

![2019-11-26_13-39-52](https://user-images.githubusercontent.com/12815392/69643905-37f81280-1064-11ea-800a-0ee95f90901f.png)

**2. Steps to Reproduce**

Update a  Microservice from MicroProfile 2.1 to MicroProfile 3-0.

a) Changing the container images from 
_open-liberty:microProfile2-java11_ to _open-liberty:19.0.0.9-kernel-java11_.

b) Changes in the server.xml:

-  From **microProfile-2.1** and **opentracingZipkin-0.31**  in the server.xml

```
<featureManager>
        <feature>webProfile-8.0</feature>
        <feature>microProfile-2.1</feature>
        <feature>usr:opentracingZipkin-0.31</feature>     
    </featureManager>
```

- To  **microProfile-3.0** and **opentracingZipkin-0.31**  in the server.xml
    
```
<featureManager>
        <feature>microProfile-3.0</feature>
        <feature>webProfile-8.0</feature>
        <!-- <feature>usr:opentracingZipkin-0.31</feature> -->
</featureManager>
```

**3. Expected behavior**

The Microservice should work as before.

**4. Diagnostic information:**
 - OpenLiberty Version: open-liberty:19.0.0.9-kernel-java11
 - server.xml configuration (WITHOUT sensitive information like passwords)
```
<?xml version="1.0" encoding="UTF-8"?>
<server description="OpenLiberty Server">
	
    <featureManager>
        <feature>microProfile-3.0</feature>
        <feature>webProfile-8.0</feature>
        <!-- <feature>usr:opentracingZipkin-0.31</feature> -->
    </featureManager>

    <httpEndpoint id="defaultHttpEndpoint" host="*" httpPort="8080" httpsPort="9443"/>
    
    <!--
    <logging traceSpecification="*=info:JCDI=all:com.ibm.ws.webbeans*=all:org.jboss.weld*=all:com.ibm.ws.cdi*=all:com.ibm.ws.microrprofile.config*=all"
        traceFileName="trace.log"
        traceFormat="BASIC" /> -->
    
    <logging traceSpecification="com.ibm.ws.opentracing.*=all:com.ibm.ws.microprofile.opentracing.*=all"/>

    <!-- the following configuration is only needed if the persistence datastore db2 is used -->
    <library id="DB2JCCLib">
        <fileset dir="${shared.resource.dir}" includes="jcc*.jar"/>
    </library>

    <dataSource id="articlejpadatasource"
              jndiName="jdbc/articlejpadatasource">
        <jdbcDriver libraryRef="DB2JCCLib" />
        <properties.db2.jcc databaseName="BLUDB"
            portNumber="50000"
            serverName="DB2-SERVER"         
            user="DB2-USER" 
            password="DB2-PASSWORD" />
  </dataSource>
</server>
```
- Server image from Dockerhub
_open-liberty:19.0.0.9-kernel-java11_

**5. Additional context**

Maybe this problem is related to the issue #8037.

**Comment by fmhwong** [comment]
MicroProfile 2.1 includes `mpOpenTracing-1.2`.  MicroProfile 3.0 includes `mpOpenTracing-1.3`.  Please make sure you are using the Zipkin sample built for `mpOpenTracing-1.3`.  It can be downloaded at https://github.com/WASdev/sample.opentracing.zipkintracer/releases/tag/1.3

**Comment by thomassuedbroecker** [comment]
@fmhwong Thanks now it works with "old" configuration in the server.xml.

Very important link in that case: https://github.com/WASdev/sample.opentracing.zipkintracer/tags
