### ISSUE TITLE
GA BLOG: Reader Role

### ISSUE THREAD

**Issue by jvanhill** [OpenLiberty/open-liberty#9987]
a. Which Liberty feature does it relate to?

   i. Human-readable name (eg WebSockets feature)

```
Application Security 2.0
Application Security 3.0
```

   ii. Feature name (eg websockets-1.0)

```
appSecurity-2.0
appSecurity-3.0
```

   iii. Is this a new feature or is it an update to an existing feature for this release?

```
Pre-existing features, new configuration element (reader-role).
```

b. Who is the target audience? eg application developers, devops pipeline devs, appserver administrators, etc

```
appserver administrators
```

c. Write a sentence or two that introduces it to someone new to the general technology/concept.

``` 
The reader-role is a management role that allows read-only access to select 
administrative REST APIs as well as the Admin Center UI (feature: adminCenter-1.0).
```

d. What is new/changed in this release and why should they get excited about this new thing (2-3 sentences)? What was the problem before and how this new feature make their life easier? (Why should they care?)

```
Prior to this release, the Administrator management role was the only management
role within Liberty and it provided read and write access. The new Reader management
role provides the ability to assign a read-only role to users and groups that will 
allow those users and groups to monitor the server without granting those users the
ability to modify the server in anyway.
```

e. Explain how to make it work. Include screenshots and/or code snippets to illustrate how to use it, if relevant. Provide server.xml snippet for how to enable the feature.

```
Using the new Reader management role is nearly identical to using the Administrator
management role. In the server.xml include the *appSecurity-2.0* or *appSecurity-3.0*
feature and also add the new *reader-role* configuration element, that specifies the
group(s), user(s), and / or the access ID of the group(s) or user(s) that should be 
granted the Reader management role.

<server>
    <featureManager>
        <feature>appSecurity-3.0</feature>
    </featureManager>

    <reader-role>
        <group>group</group>
        <group-access-id>group:realmName/groupUniqueId</group-access-id>
        <user>user</user>
        <user-access-id>user:realmName/userUniqueId</user-access-id>
    </reader-role>
</server>
```

f. Provide any public URLs where the reader can find out more about this specific update and/or about the wider technology.

```
NONE
```

g. Attach any images to this work item as .png files.

```
NONE
```

**Comment by jvanhill** [comment]
@lauracowen - I assume this can be closed?

https://openliberty.io/blog/2019/12/06/microprofile-32-health-metrics-190012.html#rrs

**Comment by lauracowen** [comment]
Aye. Sorry. Will do
